### ISSUE TITLE
xonsh 0.3.0 takes significantly longer to load

### ISSUE THREAD

**Issue by Cheaterman** [xonsh/xonsh#1023]
Hello,

xonsh 0.3.0 seems to load significantly slower on my system, up to about 2.3s from 0.2.7's initial 0.9s approximatively.

My CPU (in case it matters):
model name	: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz

Thanks in advance for investigating!

**Comment by adqm** [comment]
Yes, same here.  It seems to be #900 that was the culprit.  In addition, `prompt_toolkit` is no longer being lazily loaded (rather, it is being loaded on every startup, regardless of whether it is used or not).  I have fixes in mind for both of these, and I'll try to get them in as soon as possible (the slow startup is annoying to me, as well!).

**Comment by Cheaterman** [comment]
I don't use prompt_toolkit here though, it causes other issues (the colors become way off), so that's probably not the reason, I'd rather lean towards that autocompletion loading indeed (I remember it used to increase bash load time a lot back in the days).

**Comment by scopatz** [comment]
Yeah, lots of us have been bothered by this - so I imagine that it will get fixed soon enough :).  Also, note that ptk had some slowdowns on startup recently, but we have been working through those at jonathanslenders/python-prompt-toolkit#298.

**Comment by scopatz** [comment]
Thanks for reporting @Cheaterman, and I 100% agree with @adqm here.

**Comment by laerus** [comment]
i believe this has been fixed aswell in the latest master!
