### ISSUE TITLE
Warn about suspended and background jobs before exit

### ISSUE THREAD

**Issue by willsALMANJ** [xonsh/xonsh#1028]
Now that #867 and #962 have made job control work, I noticed that xonsh exits immediately when given the `exit` command. Other shells like bash and zsh will print a message about suspended or running jobs and refuse to exit in this case. I think this would be a nice feature to have in xonsh as well.

**Comment by scopatz** [comment]
Thanks for letting us know!  This likely wouldn't be too hard to implement. Happy to point people in the right direction here.

**Comment by scopatz** [comment]
I believe that only this function would need to change: https://github.com/scopatz/xonsh/blob/master/xonsh/jobs.py#L202
