### ISSUE TITLE
Add API for custom key bindings for prompt toolkit

### ISSUE THREAD

**Issue by willsALMANJ** [xonsh/xonsh#1036]
There is some context for this request in the mailing list here: https://groups.google.com/forum/#!topic/xonsh/RWyvShZNibg

Right now, custom bindings require working through the prompt toolkit API via `__xonsh_shell__.shell`.

**Comment by adqm** [comment]
I think the general solution here involves re-thinking the way things are loaded at the start of xonsh.

For example, we could introduce function "hooks" at several points in the load process (or maybe just one, after everything is loaded).  Such a function (one that is run after the shell is loaded) could be a reasonable place to manipulate key bindings...

**Comment by willsALMANJ** [comment]
It would be nice if `.xonshrc` was sourced after the shell was fully instantiated so that one could do this using the prompt toolkit API (before a xonsh API is created). I guess the reason this isn't what is done right now is that some of the environment variables one might want to set in `.xonshrc` are only referenced while the shell is being set up?

**Comment by scopatz** [comment]
Right, the way it is done now allow the user to set their shell backend selection in the rc file.  It would be annoying to have to set this on the command line or in the config file all the time.

**Comment by willsALMANJ** [comment]
I'm not sure how you were thinking the hooks would work, but having something like `wait_for_shell` that you could put in `.xonshrc` and have xonsh split the rc file at that point and execute everything before that the way it does now and everything after that once the shell was fully loaded would work for me.

**Comment by gforsyth** [comment]
There is now documentation (http://xon.sh/tutorial_ptk.html) on how to customize keybindings for PTK which makes use of the events system.
