### ISSUE TITLE
Matplotlib interactive mode freezes the figures

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1043]
I have tried to use matplotlib from xonsh. As far as creating the figure it works fine. 

```
snail@sea ~ $ from matplotlib import pyplot as plt                                    
snail@sea ~ $ plt.plot([1,3])                                                         
[<matplotlib.lines.Line2D at 0x15eeb318dd8>]
snail@sea ~ $ plt.show()                                                              
```

This blocks xonsh similar to what it does in python, and the figure is shown. It also behaves nicely if I close the figure. But xonsh crashes if I instead try to close the figure by pressing ctrl-c in xonsh.

```
snail@sea ~ $ plt.show()                                                              
<ctrl-c>
QObject::killTimers: timers cannot be stopped from another thread
```

If I try to use interactive mode: 

```
snail@sea ~ $ plt.ion()                                                            
snail@sea ~ $ plt.plot([1,2])                                                        
[<matplotlib.lines.Line2D at 0x1df8de65ac8>]
snail@sea ~ $
```

Then xonsh does not block, but the figure opens  in a non-responsive state:

![image](https://cloud.githubusercontent.com/assets/1038978/15650464/0c681d28-2679-11e6-86be-9664de0fef41.png)

if I try to close the figure (clicking x on the windows) I get a Python crashed dialog: 
![image](https://cloud.githubusercontent.com/assets/1038978/15650481/2a98da12-2679-11e6-9369-3450edec3e65.png)

The figure window stays in an unresponsive state. If I then try to run `plt.close()` from xonsh then the figure windows closes down nicely.

**Comment by JohnLunzer** [comment]
I did some research into getting pyqtgraph to run interactively in xonsh as well. I was drawn to [how this is achieved in IPython](http://ipython.readthedocs.io/en/stable/config/eventloops.html) ,  which has what looks to be an extensive system for integrating GUI event loop hooks.

It seems like it would be no small feat to integrate this type of system in Xonsh. I think it would make sense to pull in IPython's system if this effort were to be undertaken.

**Comment by scopatz** [comment]
Hmm strange, if I run `ion()` I don't see any of the figures after this, even if I run `show()`.

**Comment by scopatz** [comment]
Potential fix in #2225

**Comment by melund** [comment]
#2225 fixes part of the problem on Windows. Will close this one and open a new issue.

**Comment by scopatz** [comment]
Thanks @melund!
