### ISSUE TITLE
\n at start of $PROMPT is ignored with ptk

### ISSUE THREAD

**Issue by tgoodlet** [xonsh/xonsh#1052]
I want to have a blank line between shell inputs (I find it more readable).
Seems like I can only get this behavior if I put 2 `\n`s like so:
`$PROMPT = '\n\n xonsh {GREEN}>>>{NO_COLOR} ' `

If I put only one newline it seems to be ignored.
The problem is definitely in ptk since if I use 
`$SHELL_TYPE = 'readline'` everything works as expected.

**Comment by adqm** [comment]
Weird!  Thanks for reporting.

I don't personally use the ptk shell, but maybe @scopatz or @jonathanslenders can help out here.

**Comment by adqm** [comment]
Extra interesting since, at least for me, having `\n\n` at the start actually makes _two_ newlines show up, but the single `\n` at the start doesn't cause a newline at all.

**Comment by gforsyth** [comment]
Even weirder:
```console
$PROMPT='\n>>>'
```
and there's no newline in front, but 
```console
$PROMPT=\n>>>\n
```
and there's both a leading and trailing newline.  That is super weird.

**Comment by scopatz** [comment]
I think that this has gotta be a ptk issue and we should report it there. I can't find anything in xonsh that would produce this behavior.

**Comment by gforsyth** [comment]
Hey @tooglet -- I think I figured this one out, it has to do with the way PTK handles token splitting on multiline prompts.  For now, an easy workaround is just to put a space before the `\n` and it will work as you expect, so
```console
$PROMPT = ' \n xonsh {GREEN}>>>{NO_COLOR} '
```

**Comment by scopatz** [comment]
New issue opened at jonathanslenders/python-prompt-toolkit#310

**Comment by gforsyth** [comment]
This has been resolved.  Please reopen if any issue persists.  Thanks!
