### ISSUE TITLE
%CD% is not known in xonsh

### ISSUE THREAD

**Issue by jankatins** [xonsh/xonsh#1058]
on a normal shell, %CD% points to the current directory (using cmder):

``` bat
C:\data\downloads\libpng\win-64-libpng-1.6.17-vc14_1\Library\lib
λ echo %CD%
C:\data\downloads\libpng\win-64-libpng-1.6.17-vc14_1\Library\lib
```

In xonsh, `echo %CD%` prints `%CD%` :-(

**Comment by gforsyth** [comment]
Hey @janschulz -- does `pwd` work?

**Comment by janschulz** [comment]
Yes, a bit strange:

xonsh: 
```
`-> % pwd
/c/data/downloads/libpng/matplotlib-1.5.0+2326.gf349629-np18py27_0.tar/matplotlib-1.5.0+2326.gf349629-np18py27_0/Lib/site-packages/matplotlib
```

cmd (cmder, including git utils in PATH):
```
C:\data\downloads\libpng\win-64-libpng-1.6.17-vc14_1\Library\lib
λ pwd
C:\data\downloads\libpng\win-64-libpng-1.6.17-vc14_1\Library\lib
```

**Comment by melund** [comment]
I think @gforsyth meant the `$PWD` environment variable in xonsh. It does the same as `%CD%` in cmd.exe. 

When just call `pwd` you get the `pwd.exe` which is the pwd unix tool included in the git for windows installation.

**Comment by janschulz** [comment]
```
`-> % $PWD
'C:\\data\\downloads\\libpng\\matplotlib-1.5.0+2326.gf349629-np18py27_0.tar\\matplotlib-1.5.0+2326.gf349629-np18py27_0\\Lib\\site-packages\\matplotlib'
```

> When just call pwd you get the pwd.exe which is the pwd unix tool included in the git for windows installation.

but why the path mangling which does not happen in cmd?

**Comment by melund** [comment]
Sorry. Not sure what you are getting at?

**Comment by adqm** [comment]
If you're referring to the backslashes, that is because `$PWD` is a Python string, and that is how Python displays literal backslashes (with the extra backslash to escape them).

Running `print($PWD)` should yield a "prettier" result, I think.

**Comment by janschulz** [comment]
re mangling: 
```
pwd
/c/data/downloads/libpng/matplotlib-1.5.0+2326.gf349629-np18py27_0.tar/...
```

-> Its the cygwin version of the path, not the windows style: `/` instead of `\` (or `\\` if it is a python string) and it starts with a slash (`/c/`) instead of the windows style drive letter `c:\`.

**Comment by melund** [comment]
Ahh . Now I get it. That is just how the MSYS 'linux' system represents paths on windows. Cygwin does the same. The reason you don't see it in Cmder is that it overwrites the `pwd` command to give you windows style paths. Try running it in cmd.exe, or do the following in cmder: 

```
C:\Users\mel
λ pwd
C:\Users\mel

C:\Users\mel
λ pwd.exe
/c/Users/mel
```

You can make a similar alias in xonsh to mimic what you see in cmder. Run this, or put it in your `.xonshrc` file.
```
aliases['pwd'] = lambda args, stdin: print($(pwd.exe).lstrip('/').replace('/','\\').replace('\\',':\\',1))
```

**Comment by melund** [comment]
Ok. A faster and better alias to do the same would be: 
```aliases['pwd'] = lambda args, stdin=None: print(os.getcwd())```

**Comment by janschulz** [comment]
@melund Wow, didn't realize that cmder overwrites that. Thanks for the find!

I think the only "problem" here is that `%CD%` seems to be not defined in the subprocess shell as it seems to be some magic stuff:

```
C:\Users\jschulz
λ set | grep CD

C:\Users\jschulz
λ xonsh
jschulz@littlebottom ~ $ echo %CD%
%CD%
jschulz@littlebottom ~ $ echo %R_USER%
C:\portabel\R
``` 

-> Only variables which are visible in `set` are replaced

BTW: are the cmd internal commands not available?
```
jschulz@littlebottom ~ $ set
set
jschulz@littlebottom ~ $ $[set]
xonsh: subprocess mode: command not found: set
Did you mean one of the following?
    del:  Alias
    ren:  Alias
jschulz@littlebottom ~ $ where echo
C:\Program Files\Git\usr\bin\echo.exe
jschulz@littlebottom ~ $ echo.
xonsh: subprocess mode: command not found: echo.
jschulz@littlebottom ~ $ echo

jschulz@littlebottom ~ $
```

vs on cmd:
```
C:\Users\jschulz
λ echo
ECHO ist eingeschaltet (ON).
```

[`echo.` is the windows version of echoing a empty line...]

**Comment by melund** [comment]
You are right. I think `%CD%` is builtin of `cmd.exe`. You can't use things that are specific to cmd.exe when you are in subprocess mode. This is because subprocesses are just launched directly in windows, and they don't invoke cmd.exe first.  Xonsh is its own shell, not just something that runs on top of cmd.exe. 

You could of course just call cmd.exe directly 
```
$ $(cmd /C set)
b'CLICOLOR=1\r\nGIT_PAGER=cat\r\nPAGER=cat\r\nPROMPT=$P$G\r\nSYSTEMROOT=C:\\Windows\r\nCOMMONPRO.......'
```

But it isn't really that useful since any changes to the environment would not be reflected back into  xonsh. But there is probably a solution for that. Something that along the way we source bat files. 

There is a discussion about something similar for bash here: 
https://github.com/scopatz/xonsh/issues/1056

**Comment by janschulz** [comment]
[sorry, put that first into the wrong issue]

A lot of these internal commands are already aliased: https://github.com/scopatz/xonsh/blob/master/xonsh/aliases.py#L518 

But all these commands do not affect the environment like set would do :-( So set probably needs a special function which would do that instead of calling `cmd /c set x=y`. echo could probably justed added as an alias: 

```
C:\Users\jschulz
λ xonsh
jschulz@littlebottom ~ $ cmd /c echo %CD%
C:\Users\jschulz
jschulz@littlebottom ~ $
```

**Comment by melund** [comment]
I think it is OK with the cmd aliases to commands that don't clash with other names. I am not sure I would want cmd's 'echo' in the default aliases. We are in the process of implementing many of the core utilities in pure python https://github.com/scopatz/xonsh/pull/742. They will be much faster as there is a big overhead in calling a subprocess for every command. 

Also, I am not sure we need to implement something for `cmd /c set x=y` as you can always use `$x=y in xonsh. If you really wanted you could implement your own alias in python that imitates the set behaviour. Something along these lines.

```
def _set(args, stdin=None):
    if len(args) == 0:
        #no input just print the env
        for k,v in ${}.detyped():
            print(k+'='+v)
            return
    var ,*value= "".join(args).split('=')
    if len(value)==0:
        for k,v in ${...}.detyped():
             if k.startswith(var):
                 print(k+'='+v})
    else:
        ${var}=value
aliases['set'] = _set
del _set
```

**Comment by janschulz** [comment]
> I am not sure I would want cmd's 'echo' in the default aliases

That I have a echo.exe is is an artifact of using cmder, which makes the git commands available in the path, but a plain cmd has no echo.exe in path.

Re set: 

> The language is a superset of Python 3.4+ with additional shell primitives that you are used to from Bash and IPython.

Reading that, my expectations were that I can more or less use all the commands I know from bash (or better cmd), but get all the niceties from python (aka nicer string handling if I want it -> my expectations were a bit naive :-)). I usually don't realize that set is different than cp, so it's a bit strange that cp (and copy, which is internal under cmd) work, but set not...

**Comment by melund** [comment]
> That I have a echo.exe is is an artifact of using cmder, which makes the git commands available in the path, but a plain cmd has no echo.exe in path.

I guess you are right. It it probably missing. But now that we are implementing most core-utilities in Python I don't think we will need it to be. 

With regard to `set` we could implement a Python version that was only included on Windows. And added benefit could that it would work with the xonsh system where anything can really go into the environment.

**Comment by melund** [comment]
The coreutils are now a contrib in xonsh. Adding some of the windows tools should be easy. I am changing this to a feature request.

**Comment by astronouth7303** [comment]
@melund what's the feature request?

**Comment by melund** [comment]
Sorry for not being clear. I think the feature request is having some of the cmd built-ins available in xonsh. Should be Windows only. Could also be a wincoreutils xontrib.

**Comment by astronouth7303** [comment]
+1 for putting this in `xontrib-cmdisms`

**Comment by anki-code** [comment]
Closed because too old issue without any new thoughts. For anyone who interesting in this the new xontrib is welcome. We have [cookiecutter template](https://github.com/xonsh/xontrib-cookiecutter) to creating xontribs in 10 minutes.
