### ISSUE TITLE
Support for sql queries.

### ISSUE THREAD

**Issue by aisipos** [xonsh/xonsh#1066]
There is an excellent IPython magic for this:
https://github.com/catherinedevlin/ipython-sql

It even has an option to turn the result automatically into a Pandas dataframe.

It would be quite useful to have something like this in xonsh

**Comment by scopatz** [comment]
HI @aisipos, thanks for opening this issue!  I think that this would make a great xontrib, either distributed with xonsh itself or perhaps even coming bundled with ipython-sql.  @catherinedevlin, maybe this is something  would be interested in adding? I am happy to help!

**Comment by laerus** [comment]
This can also use the new macro feature, just a reference for anyone willing to tackle this.

**Comment by scopatz** [comment]
Yep this is definitely a macro use case that should be in a xontrib.
