### ISSUE TITLE
AttributeError: 'PromptToolkitShell' object has no attribute 'completer'

### ISSUE THREAD

**Issue by cryzed** [xonsh/xonsh#1070]
When attempting to execute the following xonsh script:
```
cryzed@arch ~ $ cat update-aur-gits.xsh 
#!/usr/bin/env xonsh


def main():
    packages = []
    for line in $(pacaur -Qsq git).splitlines():
        if not line.endswith('-git'):
            continue

        packages.append(line)

    ![pacaur -S @(' '.join(packages)) --noconfirm --noedit]



if __name__ == '__main__':
    main()
```

This happens:

```
cryzed@arch ~ $ xonsh update-aur-gits.xsh 
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 228, in main
    args = premain(argv)
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 215, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/lib/python3.5/site-packages/xonsh/shell.py", line 72, in __init__
    ctx=self.ctx, **kwargs)
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 33, in __init__
    self.pt_completer = PromptToolkitCompleter(self.completer, self.ctx)
AttributeError: 'PromptToolkitShell' object has no attribute 'completer'
```

When changing `$SHELL_TYPE` to `readline` the scripts runs as expected.

```
cryzed@arch ~ $ pacman -Qi xonsh-git python-prompt_toolkit cryzed-python-pygments-hg | grep Version -B 1
Name            : xonsh-git
Version         : 0.3.2.r27.g5bb8c56-1
--
Name            : python-prompt_toolkit
Version         : 1.0.0-1
--
Name            : cryzed-python-pygments-hg
Version         : r4465.4459f971dd43-1
```

**Comment by gforsyth** [comment]
Hey @cryzed, thanks for reporting!
I can't reproduce this on Arch.  Can you post the output of `xonfig`?

**Comment by cryzed** [comment]
Of course!
```
cryzed@arch ~ $ xonfig
+------------------+-------+
| xonsh            | 0.3.2 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 1.0.0 |
| pygments         | 2.2a0 |
| on posix         | True  |
| on linux         | True  |
| distro           | arch  |
| on darwin        | False |
| on windows       | False |
| is superuser     | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by adqm** [comment]
As one might expect from the error message, it looks like the `PromptToolkitShell` only gets a `completer` attribute in certain situations.

The readline shell doesn't rely on `self.completer` being around in the same way that the prompt toolkit shell does.

So I think I know how to fix.  I'll try to get a PR in tonight.

Sorry for the delay, @cryzed!

**Comment by cryzed** [comment]
I don't mind the delay at all! Thanks for taking a look at it!

**Comment by adqm** [comment]
But, now that I think about it a little bit, the _really_ weird thing here is that it is trying to use the prompt_toolkit shell at all!  xonsh should run in a "headless" shell when executing a script.  I can't reproduce either.

Not to say we shouldn't fix the fact that the ptk shell relies on completer being defined, but this is bizarre.

Do you have anything in your xonsh JSON config?  Or only in .xonshrc?  Trying to reproduce this now...

**Comment by cryzed** [comment]
```
cryzed@arch ~ $ cat .xonshrc
import os

HOME = os.path.expanduser('~')


$PATH.append(os.path.join(HOME, '.bin'))
$EDITOR = 'subl3 --wait'
$MAKEFLAGS='-j' + $(nproc)

$XONSH_COLOR_STYLE = 'rrt'
$XONSH_SHOW_TRACEBACK = True


source-bash @(os.path.join(HOME, '.xonshrc-bash'))
screenfetch | lolcat
print()
```

Yes, `screenfetch | lolcat` is of critical importance.

```
cryzed@arch ~ $ cat .xonshrc-bash
pacman-explicitly-installed() {
    comm -23 <(pacman -Qeq | sort) <(pacman -Qgq base base-devel "$@" | sort)
}
```

My `~/.config/xonsh/config.json` only contains `{}`.

**Comment by adqm** [comment]
Hmmm.  I'm sorry; I still can't reproduce this.  Maybe I'll spin up an Arch VM tomorrow.  How did you install xonsh?

In the meantime, can you try wiping everything and doing a fresh install from [the `nocompinscrpt` branch of `https://github.com/adqm/xonsh`](https://github.com/adqm/xonsh/tree/nocompinscrpt)?

Sorry for all the trouble.

**Comment by cryzed** [comment]
I installed [xonsh-git](https://aur.archlinux.org/packages/xonsh-git/) and [python-prompt_toolkit](https://aur.archlinux.org/packages/python-prompt_toolkit/) from the AUR.

> In the meantime, can you try wiping everything and doing a fresh install from the nocompinscrpt branch of https://github.com/adqm/xonsh?

I'll let you know when I've done that.

**Comment by adqm** [comment]
Thanks!  I'm going to have to call it a night, but I will revisit tomorrow.  If that patch works, we can merge it in to master.  And either way, I'll spin up an Arch VM to see if I can replicate this and figure out if there isn't some deeper issue.  Thanks for your help with tracking this down!

**Comment by cryzed** [comment]
Of course, thanks for developing xonsh!

**Comment by cryzed** [comment]
Just commenting to notify you of the edit to my previous comment!

**Comment by adqm** [comment]
Okay, well at least we have treated the symptom!  You're right that we still have to figure out why it is loading prompt toolkit shell instead of the headless shell...

**Comment by cryzed** [comment]
Sorry for replying so late; thank you for adding a workaround so quickly.

**Comment by adqm** [comment]
> thank you for adding a workaround so quickly.

No worries; glad we got it working!  We want to get things running smoothly for as many as possible as soon as possible.  Still need to track down the real issue (as of now, it's still a mystery).

**Comment by laerus** [comment]
hey @cryzed is this still an issue?

**Comment by cryzed** [comment]
Hey @laerus no, @adqm's `nocompinscrpt` branch had fixed it successfully and has since been merged. Sorry for not closing the issue!
