### ISSUE TITLE
xonsh --hep doesn't error

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1073]
`xonsh --hep` doesn't error. I expected it to error and show the command help. 

Possibly related to https://github.com/scopatz/xonsh/issues/1072?

**Comment by scopatz** [comment]
Thanks for reporting, @asmeurer.  Why would you expect it to error?  And how?  This is what I see currently:

```console
scopatz@artemis ~/xonsh master $ xonsh --help
usage: xonsh [-h] [-V] [-c COMMAND] [-i] [-l] [--config-path CONFIG_PATH]
             [--no-rc] [--no-script-cache] [--cache-everything]
             [-D [ITEM [ITEM ...]]]
             [--shell-type {readline,prompt_toolkit,best,random}]
             [script-file] [args [args ...]]

xonsh

positional arguments:
  script-file           If present, execute the script in script-file and exit
  args                  Additional arguments to the script specified by
                        script-file

optional arguments:
  -h, --help            show help and exit
  -V, --version         show version information and exit
  -c COMMAND            Run a single command and exit
  -i, --interactive     force running in interactive mode
  -l, --login           run as a login shell
  --config-path CONFIG_PATH
                        specify a custom static configuration file
  --no-rc               Do not load the .xonshrc files
  --no-script-cache     Do not cache scripts as they are run
  --cache-everything    Use a cache, even for interactive commands
  -D [ITEM [ITEM ...]]  define an environment variable, in the form of
                        -DNAME=VAL. May be used many times.
  --shell-type {readline,prompt_toolkit,best,random}
                        What kind of shell should be used. Possible options:
                        readline, prompt_toolkit, random. Warning! If set this
                        overrides $SHELL_TYPE variable.
scopatz@artemis ~/xonsh master $ __xonsh_history__.rtns[-1]
0
```

**Comment by asmeurer** [comment]
That's because you spelled `help` correctly.

**Comment by scopatz** [comment]
hah! Touche. This is because we only parse known args before deciding whether or not we are running a script that has its own arguments, ie `xonsh file.xsh --hep` could be legitimate.  But you are right, in other cases this should throw an error.

**Comment by asmeurer** [comment]
Yeah, the standard way to handle this is to assume that `--` arguments are keyword arguments (even if they don't exist), and require a bare `--`, like `xonsh -- --hep` to handle the case where a file is literally called `--hep`. 

Does xonsh use argparse? I would have thought it handles all of this automatically.

**Comment by scopatz** [comment]
There are a lot of problems with just assuming that you can use `--`, though.  This mostly is a problem with the shebang lines in xonsh scripts, for example, if you want to do:

```python
#!/usr/bin/env xonsh
```

you can't use 

```python
#!/usr/bin/env xonsh --
```

because many systems limit shebang lines to two tokens for security reasons.

**Comment by scopatz** [comment]
And yeah, we do use argparse but it doesn't have an API for handling this stuff automatically.

**Comment by asmeurer** [comment]
I didn't know that about shebang lines. What systems limit shebang line tokens? 

This seems like a usability tradeoff. A better way to handle it in my opinion would be to have a separate `xonsh-script` executable that always assumes the argument is a script for shebang lines.

**Comment by scopatz** [comment]
> What systems limit shebang line tokens?

Linux, and presumably most other posix environments

1. https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability
2. http://mail-index.netbsd.org/netbsd-users/2008/11/09/msg002388.html

> This seems like a usability tradeoff. A better way to handle it in my opinion would be to have a separate xonsh-script executable that always assumes the argument is a script for shebang lines.

That is not a bad idea, though it is non-standard.  Python, bash, etc and basically everything else have some way of passing all arguments to a script, so it must be avoidable.  That is you don't use a different bash or python commend in a shebang line.  It is a single interface.

**Comment by asmeurer** [comment]
I just checked and on OS X at least `python --hep` and `bash --hep` error and show the usage as I would expect.

**Comment by scopatz** [comment]
Obviously, I was just saying that there isn't a python-script that you use in scripts.

**Comment by laerus** [comment]
this extends to:
`xonsh ------`
`xonsh -asdf`
even
`xonsh -[[`

**Comment by scopatz** [comment]
Yeah, I think that this effects everything that is invalid.
