### ISSUE TITLE
Github banner disappears on click (from xon.sh)

### ISSUE THREAD

**Issue by camdroid** [xonsh/xonsh#1079]
On [xon.sh](xon.sh), the Github banner disappears after clicking on it (without linking the user to Github).

Mac OS X 10.11.5
Chrome 51.0.2704.63

<img width="754" alt="screen shot 2016-06-03 at 10 29 38 am" src="https://cloud.githubusercontent.com/assets/189652/15787297/6143d6a2-2976-11e6-80cc-c77660131d35.png">
<img width="765" alt="screen shot 2016-06-03 at 10 29 46 am" src="https://cloud.githubusercontent.com/assets/189652/15787298/6147f2be-2976-11e6-92d4-6c9657cc2276.png">

**Comment by scopatz** [comment]
Thanks for reporting @camdroid

**Comment by adqm** [comment]
I could replace this at the time it was first mentioned, but I can't now.  Is this still an issue for you, @camdroid?

**Comment by camdroid** [comment]
It's still happening for me. It seems like sometimes I have to click on it twice, but either way, it disappears and doesn't take me to the github repo.

**Comment by adqm** [comment]
Hmm.  I wonder if it's a Chrome issue?  Works fine for me in IceCat (Firefox-based)...

Ah, but it fails in qutebrowser (Qt-based).  And just tried on Chrome.  Fails there, too.

**Comment by scopatz** [comment]
For what it is worth, I have noticed that this fails on chrome for me too.

**Comment by melund** [comment]
It happens for me as well. Chrome

**Comment by pgoelz** [comment]
I have a similar problem on safari. Both with and without JS.
The only difference is that the banner is white on click, but comes back afterwards without the link having an effect.

Through some testing, I have found out that the white color comes from the whole `<div class="body" role="main">` appearing in front of the banner.
I might have something to do with the `<h1>`'s hover effect. The element overlaps the image.

**Comment by scopatz** [comment]
This was fixed at some point. Maybe by @Carreau?
