### ISSUE TITLE
Aliases run my bash configuration

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1085]
I've probably reported this before, but it's worth reporting again, because this is a total showstopper for me. Function aliases, like [this one](https://github.com/asmeurer/dotfiles/blob/9f6629343651e38d0d535636c0c702c60c573cd1/.xonshrc#L203) run my entire .profile every time they are run. This is a huge issue because my bash configuration does stuff every time it is run. I thought maybe adding `@foreground` as suggested in the [docs](http://xon.sh/tutorial.html#aliases) would make a difference, but it doesn't. Neither does running xonsh with `-l` or without `-l` (which is interesting, because my bash configuration is only run in login mode).

**Comment by asmeurer** [comment]
Actually, another issue in my list might be the real cause here, which is that the aliases that I have defined in my .xonshrc aren't the actual aliases that are run! Rather, my bash aliases (of the same name) are run instead.

**Comment by scopatz** [comment]
OK, so any `"extra_args"` you provide to a foreign shell (or that you read on init) are now stored automatically on any aliases that are created. `ForiegnShellFunctionAliases` also has an `extra_args` that you can set.  This allows you to a provide a `--norc` or `--noprofile` that can be passed down to bash when the alias is called.

However, at this point I'd recommend that you probably remove pulling from the bash configuration at start up, unless you really need it for some reason. Typically it just slows xonsh down at this point.

**Comment by scopatz** [comment]
I think this is no longer true.
