### ISSUE TITLE
Job control documentation

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1086]
It would be nice to have some documentation on how exactly xonsh handles job control. In particular, how does one split a command into separate jobs, or combine them into a single job. For instance, in bash, commands separated by `;` are separate jobs, unless combined with parentheses (see https://stackoverflow.com/questions/13600319/bash-run-one-command-after-another-even-if-i-suspend-the-first-one-ctrl-z).

**Comment by scopatz** [comment]
Yup, this is needed.

**Comment by gforsyth** [comment]
Tracking in #2315
