### ISSUE TITLE
Cheat sheet

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1087]
It would be nice to have a cheat sheet, particularly for the extra syntax. I always forget what `$`, `!`, `@`, and so on do.

**Comment by adqm** [comment]
Agreed; I think that would be nice.  A good place to start might be building on [the Bash-to-xonsh page of the web site](http://xon.sh/bash_to_xsh.html).

PRs welcome.

**Comment by asmeurer** [comment]
Actually I personally want something that's more Python-to-xonsh.

**Comment by scopatz** [comment]
For what it is worth, I imagined many language-to-xonsh guides. py-to-xonsh, seems like a good idea.

**Comment by astronouth7303** [comment]
Made an initial stab at a general-purpose daily reference cheat sheet [on the wiki](https://github.com/xonsh/xonsh/wiki/Cheatsheet).

I may do a formatted version after the basic form's been refined some.

**Comment by scopatz** [comment]
Thanks a billion @astronouth7303!

**Comment by JackofSpades707** [comment]
@asmeurer 
There's a program that aims to be exactly this for a plethora of various tools/programs

Although, when launching said program from within an xonsh shell, neovim glitches, you can read my bug report here: #2987

P.S. the program is called cheat, you can find it here: 
https://github.com/chrisallenlane/cheat

**Comment by gforsyth** [comment]
This is present on the website here: https://xon.sh/bash_to_xsh.html

Also linking to #3225 for tracking for website redesign/improvements

**Comment by anki-code** [comment]
I created cheat sheet as the distinct repo - https://github.com/anki-code/xonsh-cheatsheet
