### ISSUE TITLE
tab-complete only listing directories

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1094]
I just installed xonsh on Fedora 23. Looking great so far!

One issue I ran into is filename auto completion.
E.g. typing
  
  cat [tab]

only lists local directories, but no files. Is there a flag to make tab completion bash compatible?

**Comment by scopatz** [comment]
Hi @mburo!  Thanks for reporting this.

I just tried this on my computer, and `cat <TAB>` does produce a list of files, following the Bash completion conventions.  I am not sure what is going on here, other than perhaps your Bash completions are not being loaded correctly.

Can you verify that the files listed in `$BASH_COMPLETIONS` actually exist?

**Comment by mburo** [comment]
These files exist. I did some more testing:

cd /usr/include
cat [tab][tab]        only shows directories (need 2 tabs)
                            bash after 2 tabs says "Display all 743 
                            possibilities?" which include all files and directories
 
mkdir test ; cd test ; touch xxx ; mkdir yyy
cat [tab]    only lists yyy/
                bash shows xxx yyy/ after 2 tabs
cat x[tab]  shows xxx

**Comment by scopatz** [comment]
Hi @mburo - we just merged in a refactored completion tools. Would you mind grabbing master and trying it out now, please?

**Comment by mburo** [comment]
Anthony Scopatz writes:

 > Hi @mburo - we just merged in a refactored completion tools. Would
 > you mind grabbing master and trying it out now, please?

I did git pull --rebase, followed by python3.4 setup.py install

$ env | grep -i xonsh
XONSH_VERSION=0.3.2
XONSH_LOGIN=1
XONSH_INTERACTIVE=True

Still 0.3.2, so I am not sure if something actually changed.

My cat [tab] test in a directory containing xxx yyy/ still
only shows yyy/

/Michael

**Comment by scopatz** [comment]
Hmm odd.  What do the following two lines report:

```console
scopatz@artemis ~ $ from xonsh.completers import bash as xcb
scopatz@artemis ~ $ xcb.BASH_COMPLETE_FUNCS['cat']
'_longopt'
```

Also, for reporting system specs, note that you can use the `xonfig` command.

**Comment by mburo** [comment]
Anthony Scopatz writes:

> Hmm odd.  What do the following two lines report:
 > 
 > ```console
 > scopatz@artemis ~ $ from xonsh.completers import bash as xcb
 > scopatz@artemis ~ $ xcb.BASH_COMPLETE_FUNCS['cat']
 > '_longopt'
 > ```
                           output
                           
cat:   _longopt            yyy                      [1 tab]

emacs: _filedir_xspec      ../   ./    xxx   yyy/   [2 tabs required]

/bin/emacs:  KeyError: '/bin/emacs' Display all 262 possibilities ... starting with !( != ... dict dir .. |= ~
  which looks odd - for unknown commands I would expect a regular file/dir listing.

bash shows:  xxx yyy/ after 2 tabs for all commands I tried: cat, ls, vi, emacs, /bin/emacs, ...

 > Also, for reporting system specs, note that you can use the `xonfig` command.

+------------------+----------+
| xonsh            | 0.3.2    |
| Python           | 3.4.3    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | True     |
| distro           | Fedora   |
| on darwin        | False    |
| on windows       | False    |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+

If you see other outputs on your system, it may have to do with my
bashrc imports. I am not sure how to switch importing off, but that
would be the way to go to indentify the cause. Also, instead of you
remotely diagnosing the problem I could try to debug this issue
myself. What is the output you expect for cat [1-tab] and cat [2-tabs]
and where would you place diagnostic outputs?

/Michael

**Comment by lmacken** [comment]
I was hitting this issue as well, and in the process of testing the latest version with docker, I noticed that hitting <tab> alone on an empty line triggers this:

```python
Traceback (most recent call last):                                                                      
  File "/usr/local/lib/python3.4/threading.py", line 911, in _bootstrap_inner                           
    self.run()                                                                                          
  File "/usr/local/lib/python3.4/threading.py", line 859, in run                                        
    self._target(*self._args, **self._kwargs)                                                           
  File "/usr/local/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 759, in run           
    completions = list(buffer.completer.get_completions(document, complete_event))                      
  File "/usr/local/lib/python3.4/site-packages/xonsh/ptk/completer.py", line 36, in get_completions     
    self.ctx)                                                                                           
  File "/usr/local/lib/python3.4/site-packages/xonsh/completer.py", line 41, in complete                
    out = func(prefix, line, begidx, endidx, ctx)                                                       
  File "/usr/local/lib/python3.4/site-packages/xonsh/completers/base.py", line 15, in complete_base     
    out = (complete_python(prefix, line, start, end, ctx) |                                             
  File "/usr/local/lib/python3.4/site-packages/xonsh/completers/python.py", line 32, in complete_python 
    first = line.split()[0]                                                                             
IndexError: list index out of range                                                                     
```

**Comment by adqm** [comment]
Thanks for reporting, @lmacken!  I just pushed a hotfix that I think should fix that issue.

**Comment by lmacken** [comment]
Thanks @adqm, that did the trick for me.

**Comment by adqm** [comment]
@lmacken, great!  Are you still having the issue with only directories showing up in the possible completions for `cat`, or does that seem to be resolved?

**Comment by mburo** [comment]
The issue hasn't been resolved on my end:

cat + 2 tabs in a directory that only contains file xxx :
    ../ ./ xxx            

cat + 1 tab in a directory containing xxx and yyy/ :
     yyy

**Comment by adqm** [comment]
@mburo, can you try installing from adqm/xonsh@4ee4d31eefdc8f8dc7dc6f51c0a8051cb0ce5059 and let me know what the output is?  For me, I get the following when running from the xonsh directory:
```
hartz@virtual1 ~/xonsh $ cat using result from completer: 'bash'
using result from completer: 'bash'

.appveyor.yml           .gitignore              CHANGELOG.rst~          appveyor.yml            license                 requirements-docs.txt   tests                   xonsh.egg-info
.binstar.yml            .landscape.yaml         CONTRIBUTING            binstar.yml             logo.txt                requirements-tests.txt  travis.yml              xontrib
.git                    .travis.yml             MANIFEST.in             build                   recipe                  scripts                 xonsh                   xontribs.json
.gitattributes          CHANGELOG.rst           README.rst              docs                    release.xsh             setup.py                xonsh-in-docker.py      

```

**Comment by mburo** [comment]
foo6[~/git-repos/external/xonsh]:cat using result from completer: 'bash'
using result from completer: 'bash'

.git            docs            scripts         xonsh           xontrib         
build           recipe          tests           xonsh.egg-info

**Comment by mburo** [comment]
How to prevent xonsh from importing any bash material on startup ?

**Comment by adqm** [comment]
I don't think it's possible as of right now to avoid loading things from bash on startup (though that is something we intend for the future).  To avoid using the completer, you should be able to use the following (which you should also be able to add to your `.xonshrc`):

`completer remove bash`

**Comment by scopatz** [comment]
To avoid loading Bash on startup, in addition to the command that @adqm mentioned, you can also set your config file to:

```json
{"foreign_shells": []}
```

This is described and demoed in http://xon.sh/xonshconfig.html  We'll get to removing Bash-by-deafult soon.  This was a crutch we have mostly healed from at this point.

**Comment by gforsyth** [comment]
I think all the inherent issues in here have been resolved, so I'm closing this.  Please ping/reopen if the issue persists!
