### ISSUE TITLE
zsh does offer syntax highlighting (as a third party plugin), and IPython will do so in 5.0 (currently beta)

### ISSUE THREAD

**Issue by anntzer** [xonsh/xonsh#1096]
For the comparison table http://xon.sh/#comparison:
zsh: https://github.com/zsh-users/zsh-syntax-highlighting
IPython 5.0 beta release: https://mail.scipy.org/pipermail/ipython-dev/2016-June/017112.html

**Comment by scopatz** [comment]
Thanks for bringing this up @anntzer! We'd be happy to update the table after these features make it into a released version of the respective packages.

**Comment by scopatz** [comment]
Also, we could probably draw a distinction between highlighting the input and the output. I think only xonsh highlights the output, though IPython could optionally do so too.

**Comment by gforsyth** [comment]
Closing here and tracking on website meta-issue #3225
