### ISSUE TITLE
Bash's ![prefix]

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1104]
Can we have bash's ![prefix] to rerun recent commands?
I guess it's easy to create our own "! [prefix]" alias but the
additional space clashes with muscle memory.

```
xonfig
+------------------+----------+
| xonsh | 0.3.2 |
| Python | 3.4.3 |
| PLY | 3.7 |
| have readline | True |
| prompt toolkit | None |
| shell type | readline |
| pygments | None |
| on posix | True |
| on linux | True |
| distro | Fedora |
| on darwin | False |
| on windows | False |
| is superuser | False |
| default encoding | utf-8 |
+------------------+----------+
```

**Comment by gforsyth** [comment]
Hey @mburo -- you can do `!!` to rerun the previous command and `!n 3` (for example) to rerun the third most recent command.

**Comment by mburo** [comment]
Indeed, but I (and probably others, too) find ![prefix] handy.

!![ret] can be accomplished by [up][ret]  (twice as fast :-) ) and !n requires knowing the actual history sequence.

**Comment by gforsyth** [comment]
Ahh, I misunderstood.  You probably don't want to use square brackets in the explanation since we'll (or at least I will) interpret that as an uncaptured subprocess.  

I don't *think* that will clash with anything already in the parser, although I will defer to @scopatz or @adqm on that.

**Comment by adqm** [comment]
I don't think that would collide with anything.

We already have a token `DOLLAR_NAME` for environment variables.  This would involve making a new token `BANG_NAME` or similar, and making the parser generate an AST to call an appropriate function (looking through the history and re-running an appropriate command).

**Comment by mburo** [comment]
I can see this creating confusion. E.g. what to make of input !n ? It could match ![[string]]  looking to replay a command starting with n or command !n itself. So, it might be best to keep things as they are right now: allow any aliases starting with ! and requiring at least one space for separating parameters.

I added a replay_match alias (!) to my ~/.xoshrc file to mimic Bash's
behavior (up to the extra space after !):

```
def replay_match(args, stdin=None):

  if len(args) <= 0 or len(args[0]) <= 0:
    return (None, 'empty prefix\n', 1)

  exp = '^ ' + args[0]
  cmd = $(history | tail -n 10 | cut -f 3- -d ' ' | grep @(exp) | tail -n 1)
  cmd = cmd.strip();

  if cmd != '':
    print('replay:', cmd)
    # ^fixme: how to make this only appear in TTY not stdout/stderr (like in bash)?                       
    if (cmd.startswith('rm')):
      return (None, "sorry Dave, I won't replay rm commands\n", 2)
    return $[@([i.strip() for i in cmd.split()])]
    # ^checkme: are cmd's stdout, stderr, return code handled correctly here?                             

  else:
    return (None, 'no recent command matches\n', 3)

...
aliases['!'] = replay_match

```

**Comment by scopatz** [comment]
Thanks for bringing this up @mburo! I am not sure that this feature really needs or deserves extra syntax, especially syntax that could be confused with other syntax.

That said, I think that both `!replay` and `!n` could be satisfied if we allowed keys in the aliases/commands to be regular expressions.  This would allow a certain alias/command to be used for a whole class of command names.  A pull request with this would be most welcome :).

**Comment by scopatz** [comment]
Happy to give hints if needed.

**Comment by gforsyth** [comment]
Changes of this sort can be PR'd into the `bashisms` xontrib but we won't implement it in core
