### ISSUE TITLE
empty commands 100% CPU ?

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1105]
Just hitting [ret] repeatedly in the terminal shows that something
is consuming lots of CPU cycles (top shows 100% CPU) when
executing empty commands. It looks like at ~6 commands can
be executed each second. Scrolling may take some cycles, but I
doubt that many.

xonfig
+------------------+----------+
| xonsh | 0.3.2 |
| Python | 3.4.3 |
| PLY | 3.7 |
| have readline | True |
| prompt toolkit | None |
| shell type | readline |
| pygments | None |
| on posix | True |
| on linux | True |
| distro | Fedora |
| on darwin | False |
| on windows | False |
| is superuser | False |
| default encoding | utf-8 |
+------------------+----------+

**Comment by adqm** [comment]
>  It looks like at ~6 commands can be executed each second.

Are you saying that when you hit return, it takes ~1/6 seconds for the prompt to come back?  If so, I think that is unusual.  What is the value of your `$PROMPT` environment variable?  In theory, depending on what values are there, it could be computing something heavy each time...

Also, are you operating inside a Git or Mercurial repo?

**Comment by mburo** [comment]
echo $PROMPT
{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR}

I am using git cloned xonsh and cd'ed to ~
It looks as if there is a delay after each comman is executed.
I just tried ls: printing is instant, but then there is a noticeable delay
right after before the next prompt is printed.

**Comment by adqm** [comment]
Can you try, just as a test, setting `$PROMPT = "> "` and seeing whether that makes a difference?

(you may first want to store the original prompt somewhere so you can easily set it back)

**Comment by mburo** [comment]
That did it. 4% CPU.

**Comment by adqm** [comment]
I do know that the computation of `branch_color` and `curr_branch` can take a while, depending on your setup.  I typically remove that bit from my prompt.  I use:

`$PROMPT = '{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {short_cwd} {BOLD_BLUE}{prompt_end}{NO_COLOR} '`

Can you try that and see how that one performs?

**Comment by scopatz** [comment]
yeah, we really need to set timeout on those.

**Comment by mburo** [comment]
OK, that seems to be the culprit. I used the default $PROMPT, so perhaps it should be changed to the simpler form. Thanks!

**Comment by adqm** [comment]
@scopatz, or maybe the right thing is to remove them from the default prompt.  That would get my vote.

**Comment by mitnk** [comment]
+1 for @mburo 

The first thing I using xonsh (or other shells), I'd remove everything related of git from `$PROMPT`. It's too slow, and I alway check git status myself if I need it.

**Comment by adqm** [comment]
@mburo, @mitnk: I feel like this has been addressed (at least in part) by #1166, and there are workarounds, so I am going to close this issue for now.  Please feel free to reopen if necessary.

**Comment by mitnk** [comment]
cool for me!

**Comment by useredsa** [comment]
Hello, I'm facing the same issue on an (almost clear) installation of xonsh. This is my `.xonshrc` file

```
# XONSH WEBCONFIG START
$PROMPT = '{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR} '
# XONSH WEBCONFIG END


# broot (https://github.com/Canop/broot) br function
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
def _br(args):
    $f = $(mktemp).strip()
    broot --outcmd "$f" @(args)
    if not $(cat "$f"):
        rm -f "$f"
        return -1
    @$(cat "$f")
    rm -f "$f"

def _nn(args):
    # Block nesting of nnn in subshells
    if 'NNNLVL' in ${...} and !(test $NNNLVL -ge 1):
        echo "nnn is already running"
        return

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    $NNN_TMPFILE = $XDG_CONFIG_HOME + '/nnn/.lastd'
    $NNN_COLORS  = '1234'
    $NNN_TRASH   = '1'

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn @(args)

    if !(test -f $NNN_TMPFILE):
        cat $NNN_TMPFILE
        comm = $(cat $NNN_TMPFILE).split()
        cd @(comm[1][1:-1])
        rm -f $NNN_TMPFILE > /dev/null

aliases['br'] = _br
aliases['nn'] = _nn
aliases['o'] = 'xdg-open'
aliases['myg++'] = 'g++ -O2 -Wall -std=c++14'
aliases['mylatex'] = 'pdflatex -halt-on-error -output-directory out'
aliases['quietlatex'] = 'texfot pdflatex -halt-on-error -output-directory out'

$EDITOR = 'kak-connect'


from prompt_toolkit.keys import Keys
@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.add

    @handler('c-f')
    def resume_process(event):
        fg

```

When I enter an empty line the prompt takes noticeable time to render (ms, but still I notice it's slower than bash). And as pointed out here, if I open `top` and maintain enter pressed it consumes 100% of my cpu and xonsh can handle all of the empty lines, so it starts to miss some prompts. If I press it long enough (5 seconds?), I can make it show this message;

```
Unhandled exception in event loop:

Exception None

Press ENTER to continue...
```

It's not a problem with `$PROMPT` content, because changing it to `$ ` or `> ` didn't help.

xonfig:
```
+------------------+----------------------+
| xonsh            | 0.9.14               |
| Git SHA          | 777bdc73             |
| Commit Date      | Feb 23 13:28:31 2020 |
| Python           | 3.6.8                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by useredsa** [comment]
@adqm Please consider reopening the issue

**Comment by scopatz** [comment]
This issue is from almost 4 years ago. Can you please open a new one?
