### ISSUE TITLE
launching ssh via functions freezes xonsh

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1112]
Consider

```
def hal_fun(args, stdin=None):
   return $(ssh mic@192.168.1.1)

aliases['hal']      = hal_fun
aliases['hal2']     = ['ssh', 'mic@192.168.1.1']
```

calling hal2 works like expected, but hal freezes xonsh

This is probably expected because the current function
interface doesn't allow proper handling of stdin/stdout streams.

Is this something we can expect to be addressed in future releases?

The string based approach also causes problems when message timing matters. For instance:

```
# send some commands and wait for xine to finish, then stop the loop
(
counter=0
while [  $counter -lt $zoom ]; do
    echo "zoomin";
    let counter=counter+1 
done
while [ -f $f ]; do sleep 1; done;
echo "quit"
) | (xine -D --auto-play=q -f --stdctl "$play"; rm -rf $f; echo done);
```

I wonder how something like this could be implemented in xonsh. Command grouping (...) seems to be missing, plus stdout messages are collected and only sent when the producing process is done... (as I understand it)

**Comment by adqm** [comment]
Thanks for bringing this up, @mburo.  The issue with SSH is happening because you are using _captured_ subprocess mode by using `$()`, which tries to capture stdout as a string, rather than just showing it to you.

If you use `$[]` instead, it should work.  Or, better yet, it isn't even needed!  Something like the following should work:
```
def test(args, stdin=None):
     ssh myhost.com
aliases['hello'] = test
```

**Comment by adqm** [comment]
> This is probably expected because the current function interface doesn't allow proper handling of stdin/stdout streams.

We do have this.  If you make your alias function take `(args, stdin, stdout, stderr)` instead of `(args, stdin=None)`, then `stdin`, `stdout`, and `stderr` should be file-like objects that you can interact with.

**Comment by mburo** [comment]
Ah, that's convenient and worth mentioning in the tutorial.

So, how would one go about sending the stdout output of say

`  (echo abc; sleep 5; echo def)`

to the stderr stream that was passed on as a parameter?

**Comment by adqm** [comment]
> So, how would one go about sending the stdout output of say...

Unfortunately, we don't support the "subshell" idea yet, and so it is hard to group those commands together.  It is also not yet possible to use IO redirection to one of those Python objects (only to files).  But something along these lines would be really nice in the future.  We can think on this for a bit; there has to be a nice way.

For that specific example, it is possible to rewrite it in a "Pythonic" way:

```
def thing(args, stdin, stdout, stderr):
    print('abc', file=stderr)
    sleep 5
    print('def', file=stderr)
```

but I imagine you are wanting to do something more complicated than that.

I'll think about this.  I think at the very least we should have all subprocess commands inside the alias run in an environment where they use the stdin, stdout, stderr that are passed in to the function...

**Comment by mburo** [comment]
Thanks. I tried
```
def xxx(args='', stdin, stdout, stderr):
  print('abc', file=stdout, flush=True)
  sleep 1
  print('def', file=stdout, flush=True)
  sleep 1
  print('ghi', file=stdout, flush=True)
```
but

`xxx | grep abc`

just hangs and

`xxx > aaa`

works. 

However, with
```
def xxx(args='', stdin, stdout, stderr):
  print('abc', file=stdout, flush=True)
  time.sleep(1)
  print('def', file=stdout, flush=True)
  time.sleep(1)
  print('ghi', file=stdout, flush=True)
```
`xxx | grep abc` works. So sprinkling in shell commands interferes,
which perhaps is to be expected, unless we somehow inform them about context stdin,stdout,stderr

**Comment by scopatz** [comment]
Hi @mburo both versions of this function seem to work for me now. Please feel free to reopen if needed!
