### ISSUE TITLE
pip install, don't setup

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1126]
As per the discussions in #1060 and #1111, we must destroy the evil that is setup.py in favor of pip.  However, `pip install .` seems to fail at implicit namespace packages.

**Comment by aterrel** [comment]
taking @twobraids to heart, perhaps we need a little evil, you know to up the fractal dimension. A worthy cause.

For those not at PyCon see: https://www.youtube.com/watch?v=bSfe5M_zG2s

**Comment by Siecje** [comment]
So the reason to use ```pip``` is that

1. pip guarantees that ```setuptools``` will be there

So you can later do ```pip uninstall```.

Is that it?

Right now there is special handling in setup.py if ```setuptools``` is not present. So should ```setuptools``` be required?

Seems strange that ```pip install .``` breaks ```xontribs``` but installing from Pypi works. Is this a pip bug? Is there an open issue?

**Comment by scopatz** [comment]
> taking @twobraids to heart, perhaps we need a little evil, you know to up the fractal dimension. A worthy cause.

This is definitely my favorite sentence of the day. 

> So should setuptools be required?

Setuptools should not be required because this would break the "only have the Python standard library as hard requirements" idea.  If setuptools is around, we are happy to use it, but forcing it should be considered a bug.

> Is this a pip bug? Is there an open issue?

This seems to be a pip bug.  I believe that this is the relevant issue pypa/pip#3160. I'll cross reference this issue there, but maybe more of us should let them know, since it has been open for 8 months.

**Comment by scopatz** [comment]
Note that there might be a workaround in https://github.com/pypa/pip/issues/3 if anyone wants to platy around with this.

**Comment by astronouth7303** [comment]
`ensurepip` has been bundled with Python since 3.4. While this isn't quite the same as pip (and setuptools) being bundled with Python, is it close enough?

**Comment by gforsyth** [comment]
@astronouth7303 -- it might be, but there's a further problem there in that Continuum's Python builds _don't_ bundle `ensurepip`

**Comment by astronouth7303** [comment]
This is why we can't have nice things.

**Comment by gforsyth** [comment]
I've just tested this out in a fresh environment and using `pip install .` worked fine and I was able to install `xontribs` and use them, so I think we may finally be able to put this one behind us.

**Comment by scopatz** [comment]
Odd, the latest comment on the relevant pip issue (https://github.com/pypa/pip/issues/3160#issuecomment-377927760) indicates that it is indeed fixed on pip-master.  What version of pip were you on @gforsyth ?

**Comment by gforsyth** [comment]
Hmm, in that env it wasn't even the latest release.  Worked for me on `9.0.1`

**Comment by scopatz** [comment]
cool

**Comment by scopatz** [comment]
pip now handles implicit namespace packages.  But there are still concerns that it won't regenerate the parser table for development. This requires more investigation

**Comment by jaraco** [comment]
`setup.py install` is discouraged if not deprecated (both for Setuptools and distutils). The Python Packaging Authority is very much invested in supporting configurable installers based on standards (PEP 517/518). If `pip install` doesn't satisfy xonsh's use-case, I'd be very interested in knowing why and capturing that as an issue at pypa/packaging-issues. When you have time to investigate, please help distilling the undesirable behavior w.r.t regenerating the parser table. Thanks.

**Comment by scopatz** [comment]
@jaraco - There were also issues back in the day where using pip would generate entry points that could take minutes longer for xonsh to start up because it would insert pkg_resources imports.  Has that gone away / is that avoidable yet?

**Comment by daniel-shimon** [comment]
As per #4355 `pip install` always runs amalgamate.py and AFAIK has works flawlessly
