### ISSUE TITLE
problems sourcing zsh functions

### ISSUE THREAD

**Issue by aliceriot** [xonsh/xonsh#1134]
I have a number of functions written for `zsh` that I'd like to avoid reimplementing when switching to xonsh. When I try to use the `source-zsh` function to import a file that includes all of these functions I get this error:

![xonsh-error](https://cloud.githubusercontent.com/assets/6207644/15825915/9083e5f6-2bd3-11e6-8f8b-1b912b5d38c9.png)

(only the first line shown here is relevant).

Am I missing something? There's not much in the docs about `zsh` interop. The file I'm trying to source is here: https://github.com/aliceriot/dotfiles/blob/master/zsh/functions/functions.zsh

**Comment by gforsyth** [comment]
Hey @aliceriot -- thanks for reporting!  Could you post the output of `xonfig` and also try running the `source-zsh` command after setting `$XONSH_SHOW_TRACEBACK=True` and paste the full traceback from the error?  Thanks!

**Comment by gforsyth** [comment]
Mmm, also -- does it work if you comment out all of the `source ...zsh` lines at the beginning?  I wonder if that's tripping it up.

**Comment by aliceriot** [comment]
I get the same error if I `source-zsh` on a file that just defines functions, and doesn't have any `import` statements, e.g: https://github.com/aliceriot/dotfiles/blob/master/zsh/functions/git.zsh

When I try to run `xonfig` I get this:

![xonfig-error](https://cloud.githubusercontent.com/assets/6207644/15826142/61d21fd8-2bd4-11e6-9ac4-628e02ff10f5.png)

setting `$XONSH_SHOW_TRACEBACK` doesn't seem to have any effect, sourcing a `.zsh` file still gives the same error.

Other details: I'm running `xonsh` from `zsh`, which is still set as my login shell (not being able to import existing setup is holding me back b/c I use these functions all day when working). My system is Arch Linux, terminal is xfce4-terminal.

**Comment by aliceriot** [comment]
reinstalled `ply`, now `xonfig` gives me:

```
+------------------+----------------+
| xonsh            | 0.3.2          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| pygments         | 2.1.3          |
| on posix         | True           |
| on linux         | True           |
| distro           | Antergos Linux |
| on darwin        | False          |
| on windows       | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
```

**Comment by gforsyth** [comment]
I'm not sure what's up here, @aliceriot , beyond the obvious fact that `source_foreign` is falling down somewhere.  I'll try to play around with your .zsh files later tonight and see if I can narrow down what the failure point(s) are.

**Comment by aliceriot** [comment]
Update: I'm now getting the following error:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/base_shell.py", line 165, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 63, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'source' is not defined
```

when I try to `source-zsh` this file: https://github.com/aliceriot/dotfiles/blob/master/zsh/functions/github.zsh

output of `xonfig`:

```
+------------------+---------------------------------------------------+
| xonsh            | 0.4.4                                             |
| Git SHA          | None                                              |
| Python           | 3.5.2                                             |
| PLY              | 3.7                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.3                                             |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.1.3                                             |
| on posix         | <xonsh.lazyasd.LazyBool object at 0x7fe7a7a89f28> |
| on linux         | True                                              |
| distro           | Antergos Linux                                    |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
+------------------+---------------------------------------------------+
```

so something is different! Still not working though.

**Comment by scopatz** [comment]
@aliceriot thanks for the update.  Are you source-zsh-ing from your xonshrc or from the command line?

**Comment by aliceriot** [comment]
from the command line.

**Comment by scopatz** [comment]
hmm that is very strange....

**Comment by aliceriot** [comment]
If I add the same command to `.xonshrc` I get a similar error.

my `~/.xonshrc`:

```
from datetime import datetime

$VI_MODE = True

# setting the prompt
$FORMATTER_DICT['curr_time'] = lambda: datetime.strftime(datetime.now(), '%H:%M')
$PROMPT = ' {BLUE}{user} {RED}<3 {BLUE}{short_cwd} '
$RIGHT_PROMPT = '{branch_color}{curr_branch} {BLUE}{curr_time} '

source-zsh("~/dotfiles/zsh/functions/github.zsh")
```

the error:

```
/usr/lib/python3.5/site-packages/xonsh/environ.py:1435: RuntimeWarning: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/environ.py", line 1423, in xonshrc_context
    run_script_with_cache(rcfile, execer, env)
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 143, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 63, in run_compiled_code
    func(code, glb, loc)
  File "/home/alice/.xonshrc", line 13, in <module>
    source-zsh("~/dotfiles/zsh/functions/github.zsh")
NameError: name 'source' is not defined

error running xonsh run control file '/home/alice/.xonshrc': name 'source' is not defined
  warnings.warn(msg.format(exc, rcfile, err), RuntimeWarning)
```

**Comment by scopatz** [comment]
What happens if you try running the following instead:

```
source-zsh ~/dotfiles/zsh/functions/github.zsh
```

**Comment by aliceriot** [comment]
I get this error, a bit less info:

```
xonsh: error: Source failed: source "/home/alice/dotfiles/zsh/functions/github.zsh"
```

**Comment by scopatz** [comment]
And as an experiment, what about

```
source-foreign zsh ~/dotfiles/zsh/functions/github.zsh
```

 or

```
![source-foreign zsh ~/dotfiles/zsh/functions/github.zsh]
```

**Comment by aliceriot** [comment]
sure! experiments are fun!

they both give:

```
xonsh: error: Source failed: None "/home/alice/dotfiles/zsh/functions/github.zsh"
```

**Comment by scopatz** [comment]
Doubly strange, I can `source-zsh ~/github.zsh` just fine on my machine when I download that file to my home dir... I'll keep looking...

**Comment by aliceriot** [comment]
whaaa

that is really strange. could it be something to do with how `xonsh` is installed? I installed it globally using the python3 pip (`pip3`) supplied by the Arch linux repos.

**Comment by scopatz** [comment]
OK, I think I see at least two errors related to this. But can you also try the following lines and report back:

```
from xonsh.foreign_shells import foreign_shell_data
e, a = foriegn_shell_data(shell='zsh', sourcer='source', prevcmd='source "/home/alice/dotfiles/zsh/functions/github.zsh"')
print(e)
print(a)
```

From the command line might be best

**Comment by aliceriot** [comment]
`e` and `a` are both `None` when I try that, from the cli.

**Comment by gforsyth** [comment]
hmm, so I just installed xonsh using arch's `pip3` and it errored out doing a `source-zsh` but worked using `source-bash`.  Does that work on your end @aliceriot ?

**Comment by aliceriot** [comment]
aha it does!

**Comment by aliceriot** [comment]
brilliant!

**Comment by gforsyth** [comment]
although weird... but glad it works!

**Comment by aliceriot** [comment]
huh so still not totally working, some of my `.zsh` files still give the error:

https://github.com/aliceriot/dotfiles/blob/master/zsh/functions/git.zsh
https://github.com/aliceriot/dotfiles/blob/master/zsh/functions/misc_dev_related.zsh
https://github.com/aliceriot/dotfiles/blob/master/zsh/functions/fzf.zsh

**Comment by scopatz** [comment]
OK so now what happens if you run

```
foriegn_shell_data(safe=False, shell='zsh', sourcer='source', prevcmd='source "/home/alice/dotfiles/zsh/functions/github.zsh"')
```

**Comment by aliceriot** [comment]
a bit more info from that one!

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/base_shell.py", line 165, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 63, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 251, in foreign_shell_data
    universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zsh', '-i', '-c', 'set -e\nsource "/home/alice/dotfiles/zsh/functions/github.zsh"\necho __XONSH_ENV_BEG__\nenv\necho __XONSH_ENV_END__\necho __XONSH_ALIAS_BEG__\nalias -L\necho __XONSH_ALIAS_END__\necho __XONSH_FUNCS_BEG__\n# get function names\nnamefile="{"\nfor name in ${(ok)functions}; do\n  loc=$(whence -v $name)\n  loc=${(z)loc}\n  file=${loc[7,-1]}\n  namefile="${namefile}\\"${name}\\":\\"${(Q)file:A}\\","\ndone\nif [[ "{" == "${namefile}" ]]; then\n  namefile="${namefile}}"\nelse\n  namefile="${namefile%?}}"\nfi\necho ${namefile}\necho __XONSH_FUNCS_END__']' returned non-zero exit status 1
```

**Comment by scopatz** [comment]
OK, great, and now please try:

```
foriegn_shell_data(safe=False, use_tmpfile=True, shell='zsh', sourcer='source', prevcmd='source "/home/alice/dotfiles/zsh/functions/github.zsh"')
```

And what version of zsh are you using?

**Comment by aliceriot** [comment]
Sure!

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/base_shell.py", line 165, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 63, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 251, in foreign_shell_data
    universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zsh', '-i', '-c', 'set -e\nsource "/home/alice/dotfiles/zsh/functions/github.zsh"\necho __XONSH_ENV_BEG__\nenv\necho __XONSH_ENV_END__\necho __XONSH_ALIAS_BEG__\nalias -L\necho __XONSH_ALIAS_END__\necho __XONSH_FUNCS_BEG__\n# get function names\nnamefile="{"\nfor name in ${(ok)functions}; do\n  loc=$(whence -v $name)\n  loc=${(z)loc}\n  file=${loc[7,-1]}\n  namefile="${namefile}\\"${name}\\":\\"${(Q)file:A}\\","\ndone\nif [[ "{" == "${namefile}" ]]; then\n  namefile="${namefile}}"\nelse\n  namefile="${namefile%?}}"\nfi\necho ${namefile}\necho __XONSH_FUNCS_END__']' returned non-zero exit status 1
```

`zsh --version` reports its version as 5.2.

**Comment by scopatz** [comment]
Ok, can you write the following to a file (test.zsh) and report what the `zsh -i test.zsh` gives?

**test.zsh**
```
set -e
source "/home/alice/dotfiles/zsh/functions/github.zsh"
echo __XONSH_ENV_BEG__
env
echo __XONSH_ENV_END__
echo __XONSH_ALIAS_BEG__
alias -L
echo __XONSH_ALIAS_END__
echo __XONSH_FUNCS_BEG__
# get function names
namefile="{"
for name in ${(ok)functions}; do
  loc=$(whence -v $name)
  loc=${(z)loc}
  file=${loc[7,-1]}
  namefile="${namefile}\"${name}\":\"${(Q)file:A}\","
done
if [[ "{" == "${namefile}" ]]; then
  namefile="${namefile}}"
else
  namefile="${namefile%?}}"
fi
echo ${namefile}
echo __XONSH_FUNCS_END__
```

Also, for what it is worth:

```
$ zsh --version
zsh 5.0.2 (x86_64-pc-linux-gnu)
```

**Comment by aliceriot** [comment]
It's a bit long so here's a gist: https://gist.github.com/aliceriot/886179904b2a4b1369b78e54ebe4faf9

**Comment by scopatz** [comment]
OK,  can you please add a line at the top of `test.zsh` that reads `set -x`?  I think this is because there is something the function finding code that either doesn't work on your system, isn't robust enough, or is new between zsh 5.0.2 and 5.2

**Comment by scopatz** [comment]
They probably changed it to a non-zero return code by v5.2

**Comment by aliceriot** [comment]
this is the output I get when I add `set -x` to the top of the file: https://gist.github.com/aliceriot/9f940ba270d0d8539ed358729793a85e

sorry my zsh config is kind of a mess, I've just been adding stuff to it without any real discipline, so that might be contributing to this issue.

**Comment by scopatz** [comment]
Hi @aliceriot - I haven't forgotten about this!  Sorry about the delay in responding (summer travel).  So I think that the bad news is that there is no consistent way to find filename information anymore.  I have posted [a question to SO](http://stackoverflow.com/q/39069075/2312428) in the hope that someone know how to do this and it is simply my ignorance.

The good news is that your last gist showed that (for whatever reason) this doesn't affect *all* zsh functions, only most of them.  I have opened #1605, which skips invalid filenames.  This probably should have happened anyway. Hopefully this helps, in part.

**Comment by aliceriot** [comment]
No worries, I'm using zsh on the day-to-day for now, which is quite sufficient :)

I'll give things a try again later today, thanks for putting time into this!

**Comment by scopatz** [comment]
Late but worth the wait, hopefully. A potential fix is available in #2241.

**Comment by scopatz** [comment]
Closing this because #2241 has been merged. Please feel free to reopen if needed.

**Comment by aliceriot** [comment]
Awesome! Looking forward to trying it out 😁
