### ISSUE TITLE
Zsh aliases and function not importing from oh-my-zshell settings

### ISSUE THREAD

**Issue by Xorso** [xonsh/xonsh#1136]
Config:
```
cat ~/.config/xonsh/config.json
{
 "foreign_shells": [
  {
   "login": true,
   "shell": "/bin/zsh"
  }
 ],
 "xontribs": [
  "prompt_ret_code"
 ]
}
```
There are no custom aliases discovered.

If I use the source-zsh command I get:
```
$ source-zsh ~/.zshrc
KeyError: 'Unknown environment variable: $PWD'
{env_name}{user}@{hostname} {cwd}{branch_color}{curr_branch} {prompt_end}
```

**Comment by scopatz** [comment]
Thanks for reporting, @Xorso, and sorry about the delay. Could you please set `$XONSH_SHOW_TRACEBACK=True` and report the full traceback?

**Comment by Xorso** [comment]
I have it set to True, but there is still no output.

```

**Comment by scopatz** [comment]
Well this second time you sourced the KeyError didn't show up.  Is there anyway you can get the KeyError and the full traceback, please?

**Comment by Xorso** [comment]
I upgraded to 0.4.0 and can't get the key error again. I still have the prompt that turns weird but no keyerror. We can close this since the error is no longer visible.
