### ISSUE TITLE
Malformed $PROMPT crashes xonsh

### ISSUE THREAD

**Issue by adqm** [xonsh/xonsh#1137]
From [this comment in the recent Reddit thread](https://www.reddit.com/r/Python/comments/4mng7l/xonsh_using_python_as_your_shell/d3xsxs7).

`$PROMPT` variables with one too many open squigglies break xonsh completely.  I tested a few things, and it doesn't look like there is an easy way to escape the squigglies to prevent this.  Example:

```
hartz@tabby-3 ~ $ $PROMPT = "{{hello"
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 260, in main
    shell.cmdloop()
  File "/usr/local/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 116, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/local/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 63, in singleline
    prompt_tokens = self.prompt_tokens(None)
  File "/usr/local/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 137, in prompt_tokens
    toks = partial_color_tokenize(p)
  File "/usr/local/lib/python3.5/site-packages/xonsh/pyghooks.py", line 206, in partial_color_tokenize
    for literal, field, spec, conv in formatter.parse(template):
ValueError: expected '}' before end of string
```

xonsh then quits.

**Comment by adqm** [comment]
Worse, from the conversation on Reddit, it seems like this is happening to some users _before_ having set anything.  I wonder if this isn't related to the `$PROMPT` issue we had on Windows (#1080).

**Comment by nicolasavru** [comment]
I hit a similar issue when trying to start xonsh for the first time from zsh. I had $PROMPT set to ```[%{\x1b[0;35m%}%*%{\x1b[39;49;m%}][%(!.%{\x1b[91m%}%n%{\x1b[39;49;m%}.%{\x1b[0;36m%}%n%{\x1b[39;49;m%})@%{\x1b[0;37m%}%m%{\x1b[39;49;m%}:%{\x1b[0;33m%}%~%{\x1b[39;49;m%}]%(!.#.$) ```,  (sadness like that is one of the reasons I tried xonsh) which threw this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 134, in prompt_tokens
    p = partial_format_prompt(p)
  File "/usr/lib/python3.5/site-packages/xonsh/environ.py", line 1147, in partial_format_prompt
    for literal, field, spec, conv in _FORMATTER.parse(template):
ValueError: expected ':' after conversion specifier
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 256, in main
    shell.cmdloop()
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 116, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 63, in singleline
    prompt_tokens = self.prompt_tokens(None)
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 137, in prompt_tokens
    toks = partial_color_tokenize(p)
  File "/usr/lib/python3.5/site-packages/xonsh/pyghooks.py", line 206, in partial_color_tokenize
    for literal, field, spec, conv in formatter.parse(template):
ValueError: expected ':' after conversion specifier
```

If a xonsh config file doesn't exist, it may be worth unsetting $PROMPT (perhaps only if parsing it raises an exception).

**Comment by adqm** [comment]
> [%{\x1b[0;35m%}%*%{\x1b[39;49;m%}][%(!.%{\x1b[91m%}%n%{\x1b[39;49;m%}.%{\x1b[0;36m%}%n%{\x1b[39;49;m%})@%{\x1b[0;37m%}%m%{\x1b[39;49;m%}:%{\x1b[0;33m%}%~%{\x1b[39;49;m%}]%(!.#.$)

:scream: 

>  it may be worth unsetting $PROMPT

@nicolasavru, I wasn't aware that zsh used `$PROMPT` as well.  We should certainly unset that if it comes from a foreign shell.  We already do something like this for some environment variables on Windows.  Should be a pretty quick fix, I think, to do it for other OS's as well.

@melund, you were right, of course!  We should be ignore `$PROMPT` from foreign shells, regardless of OS.

**Comment by adqm** [comment]
@nicolasavru, I just put in #1150, which I believe should fix this.  Would you mind giving that a shot, and letting us know whether it fixes this issue for you?

**Comment by nicolasavru** [comment]
The patch does what you intended; xonsh doesn't crash now, though I almost wish it did:
```
xonsh
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 134, in prompt_tokens
    p = partial_format_prompt(p)
  File "/usr/lib/python3.5/site-packages/xonsh/environ.py", line 1153, in partial_format_prompt
    for literal, field, spec, conv in _FORMATTER.parse(template):
ValueError: expected ':' after conversion specifier
[%{^[[0;35m%}%*%{^[[39;49;m%}][%(!.%{^[[91m%}%n%{^[[39;49;m%}.%{^[[0;36m%}%n%{^[[39;49;m%})@%{^[[0;37m%}%m%{^[[39;49;m%}:%{^[[0;33m%}%~%{^[
```

**Comment by adqm** [comment]
Oh my goodness.

That wasn't what I was expecting at all...but we're on the right track, I think.  Some more work.  Thanks for the help!

Out of curiosity, if I wanted to try to reproduce this myself...you have zsh as your default shell, and are running xonsh on top of it?

**Comment by nicolasavru** [comment]
> Out of curiosity, if I wanted to try to reproduce this myself...you have zsh as your default shell, and are running xonsh on top of it?

Correct

**Comment by adqm** [comment]
Okay, I just pushed again to #1150 with something that (I think) fixes this issue.  I was misunderstanding exactly where the `PROMPT` from zsh was working its way in there.  Would you mind giving it another look?  If all goes well, it should ignore your `PROMPT` from zsh completely.

**Comment by nicolasavru** [comment]
Success!
```
$ xonsh
avru@gateway ~ $ 
```

**Comment by adqm** [comment]
Hooray!  Hopefully we'll get this merged into master soon.  This has apparently been a long-standing issue.  Thanks for your help with debugging!

**Comment by adqm** [comment]
Should be fixed, via #1150!  Hopefully we'll get a release out in the next day so it's easy for others to pull this in.

**Comment by scopatz** [comment]
Yup!  I am working on getting the VC speed ups in too, so hopefully that can go in as well

**Comment by adqm** [comment]
Great!  With these two things and the Windows fixes, this is good progress for a day :)
