### ISSUE TITLE
Crash when run from gdb

### ISSUE THREAD

**Issue by kirbyfan64** [xonsh/xonsh#1143]
```
ryan@DevPC-LX ~/fy $ gdb build/fy
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/fy...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/ryan/fy/build/fy 
Traceback (most recent call last):
  File "/media/ryan/stuff/anaconda/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.0', 'console_scripts', 'xonsh')()
  File "/home/ryan/stuff/anaconda/lib/python3.4/site-packages/xonsh/main.py", line 233, in main
    run_code_with_cache(args.command, shell.execer, mode='single')
  File "/home/ryan/stuff/anaconda/lib/python3.4/site-packages/xonsh/codecache.py", line 182, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/ryan/stuff/anaconda/lib/python3.4/site-packages/xonsh/codecache.py", line 57, in run_compiled_code
    func(code, glb, loc)
  File "6c307e9a77dbb5d35a4aae7de5d259a4", line 1, in <module>
NameError: name 'home' is not defined
During startup program exited with code 1.
(gdb) 
```

gdb seems to always use the login shell, which is in my case Xonsh. Evidently, Xonsh doesn't seem to like that too much...

**Comment by scopatz** [comment]
Thanks a million for reporting this @kirbyfan64, and sorry for the slow response.  

What happens if you run it in one of the following ways?

```console
$ sh -c gdb ...
$ env SHELL=sh gdb ...
$ env SHELL=/bin/sh gdb ...
```

Do any of these work?  We can easily provide an alias if one does.

**Comment by kirbyfan64** [comment]
@scopatz The latter two commands work.

**Comment by scopatz** [comment]
Ok great!  I think the second one should be an alias then.  Would you mind submitting a PR with this please?

**Comment by kirbyfan64** [comment]
@scopatz Isn't there more of a bug here? I mean, an alias still wouldn't work if one has another name for gdb (e.g. `gdb-x.x` or something).

This seems to be because, in Xonsh, `exec` refers to the builtin function, while gdb expects it to be like most shells.

So it runs `xonsh -c exec /home/ryan/...`, which Xonsh interprets as dividing `exec` by the variable `home`. And, since `home` is undefined, it then gives an error.

This is kind of related to the minor annoyance that `bin/xyz` fails because `bin` is a Python builtin.

**Comment by scopatz** [comment]
Hi @kirbyfan64 - I think you are right that gdb expects $SHELL to be an sh-based language, which xonsh is not. I would argue that it would be hard or impossible for xonsh to be fully sh-compliant if we want to remain fully Python compliant.  

So if anything, this is a deficiency in gdb in not being able to use non-sh languages.  Now maybe that is outside of their design spec....

That all being said, I have two thoughts here:

1. the `gdb` alias, even if it didn't work for `gdb-x.x` would still give people a way to find out how to set their own aliases to work.
2. I think allowing regexes as aliases keys would be a good idea eventually. 
3. We could try to have a gdb/sh compatibility layer that would be explicitly turned on in these cases.  Most of the overlap in names doesn't cross the subproc mode / pymode split.  For example, it is `exec args` in subproc mode and `exec(args)` in python mode. It could be possible to provide enough function aliases to fake sh compatibility when needed. I think this would be confusing for regular usage, but potentially helpful here.

**Comment by kirbyfan64** [comment]
@scopatz What if Xonsh had two different command-line parameters:

- `-c` would always run in subprocess mode. `exec` would do what sh exec does.
- `-e` (like Perl) would actually run Xonsh code.

It would be a breaking change, but I think it'd be beneficial in the long run.

**Comment by scopatz** [comment]
I don't think it is a wise idea to have multiple or optional language features.  We'd have to make the compatibility layer work with the language, not against it.  Luckily, I think that most subproc funcs that *have* to be named things like exec and eval are unambiguously subprocesses not. The fact that Python always wins shouldn't get in their way.

**Comment by scopatz** [comment]
We could certianly have a command line option that would load the comparability layer, though.

**Comment by kirbyfan64** [comment]
@scopatz I think you misunderstood me a bit! I'm proposing the following things:

1. Change `-c` to `-e`.
2. Add a *different* `-c`, which always, unconditionally uses subprocess mode, not Python mode.
3. Add an `exec` builtin to subprocess mode.

This should also allow compatibility with other debuggers and tools that expect `-c "exec ..."` to work.

**Comment by scopatz** [comment]
Hi @kirbyfan64 - thanks for the suggestions, I'll go through them one by one:

> 1. Change -c to -e.

I think that this would be inconsistent with how Python and Bash treat the `-c` options, which means to compile and execute in the language itself.  So `xonsh -c` should compile xonsh code.

> 2. Add a different -c, which always, unconditionally uses subprocess mode, not Python mode.

It is not entirely clear what is proposed here.  As you know, xonsh allows users nest python and subprocess modes through the various operators `$(), @(), ![]` etc.  So does unconditionally using subprocess mode mean to not allow this nesting at all? I think that would be very difficult to implement to implement with what we have now, and perhaps not that useful, because users wouldn't be able to programtically construct subproc args in Python with `@()` and they would not be able to and/or subprocs together (which happens in Python mode).

Alternatively, you could just mean that the top-level nesting starts in subproc mode rather than Python mode.  Again I think that this would be difficult to implement given  the current structure and would end up being a different language.  This is because in the current xonsh, all subproc modes are Python expressions. There is no notion of a suite of subproc suite or block.  So, currently, starting in subproc mode would limit the user to a single expression. This doesn't seem super useful. And changing this would likely result in a whole new parser.

I am happy to entertain any option, as long as it is consistent with the one language, one parser criterion.   

> 1. Add an exec builtin to subprocess mode.

I am actually in favor this as an alias function.  Perhaps as a stock xontrib so it can be optionally loaded.

I hope this helps clarify my thinking on this!

**Comment by kirbyfan64** [comment]
> I think that this would be inconsistent with how Python and Bash treat the `-c` options, which means to compile and execute in the language itself. So `xonsh -c` should compile xonsh code.

Perl uses `-e`, as does Ruby and most languages other than Python and POSIX shells.

> It is not entirely clear what is proposed here. As you know, xonsh allows users nest python and subprocess modes through the various operators `$(), @(), ![]` etc. So does unconditionally using subprocess mode mean to not allow this nesting at all? I think that would be very difficult to implement to implement with what we have now, and perhaps not that useful, because users wouldn't be able to programtically construct subproc args in Python with `@()` and they would not be able to and/or subprocs together (which happens in Python mode).

Sorry; I'm not very good at trying to get across ideas...

Basically, you know how Xonsh determines whether or not the current line is a subprocess based on whether or not the first word is defined in the current scope? `-c` could just *unconditionally* run it as if the first word were NOT defined in the current scope.

But, based on what you said afterwards, this may not even be necessary:

> I am actually in favor this as an alias function. Perhaps as a stock xontrib so it can be optionally loaded.

So this would cause `exec` to always mean what it means in Posix shells? Well, that would be much simpler and basically mean that gdb works, so I'm all for it. :)

Out of curiosity, how would it work, since `exec` is defined in Python?

**Comment by sirex** [comment]
Same here:

```
$ gdb python
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...Reading symbols from /usr/lib/debug//usr/bin/python2.7...done.
done.
(gdb) run
Starting program: /usr/bin/python 
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 233, in main
    run_code_with_cache(args.command, shell.execer, mode='single')
  File "/usr/local/lib/python3.4/dist-packages/xonsh/codecache.py", line 182, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/codecache.py", line 57, in run_compiled_code
    func(code, glb, loc)
  File "2b8f8a2e97cfbfb65c538e2341008ffa", line 1, in <module>
NameError: name 'usr' is not defined
During startup program exited with code 1.
(gdb) 
```

Not sure how to fix that, but I expect `gdb` to work out of the box, other way, I consider this is a xonsh bug.

**Comment by sirex** [comment]
I think, that `xonsh` as a shell command should behave in the same way as any shell does, because with `xonsh` command we are interacting with the outside world and outside world always expect than a `$SHELL` should behave in a very similar way like `sh` or `bash`.

So `xonsh -c` should do exactly same thing as `sh -c`.

**Comment by scopatz** [comment]
@sirex - the fix is to run `env SHELL=sh gdb` or make an alias:

```python
aliases['gdb'] = ['env', 'SHELL=sh', 'gdb']
```

If someone wants to PR this in that would be very helpful!

**Comment by kirbyfan64** [comment]
Just to bump this a little: what happened to just adding `exec`? The alias works in theory, but it would be one of those really weird "gotchas", where people are trying to figure out why the hell `gdb x` works but `./gdb x` or `gdb-7.x` doesn't.

Though this doesn't really affect me too much anymore; I switched to [LLDB](http://lldb.llvm.org/index.html). :D

**Comment by scopatz** [comment]
My current thinking is that exec can be added as a xontrib.

**Comment by scopatz** [comment]
Given #1560, could you check if this works on master / v0.4.5 please @kirbyfan64 and @sirex ?

**Comment by scopatz** [comment]
Hi @kirbyfan64 - I have tested this out myself and gdb now seems to work with xonsh as the login shell. Please feel free to close!
