### ISSUE TITLE
How to check exit code of previous command?

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1146]
```
$ ls file-does-not-exist
ls: file-does-not-exist: No such file or directory
$ echo $?
$?
```

Is this what we still need to add or there is a new way to do it in xonsh?

**Comment by adqm** [comment]
If you have _just_ run the previous command, you should be able to access the associated  `CompletedCommand` object via `_`.

So you can get the return code with `_.rtn`:
```
hartz@virtual1 ~/xonsh $ ls nonexistent
/bin/ls: cannot access nonexistent: No such file or directory
hartz@virtual1 ~/xonsh $ _.rtn
2
```

Downside is that this won't work in a script.

**Comment by scopatz** [comment]
You can use `__xonsh_history__.rtns[-1]`, see the history tutorial for more details http://xon.sh/tutorial_hist.html

**Comment by mitnk** [comment]
Thanks! Will consume more docs :)

**Comment by Carreau** [comment]
> Thanks! Will consume more docs :)

Or write more, if it's not in there  !

**Comment by jaraco** [comment]
> You can use `__xonsh_history__.rtns[-1]`, see the history tutorial for more details http://xon.sh/tutorial_hist.html

Looks like today it's `__xonsh__.history.rtns[-1]`.

**Comment by jaraco** [comment]
After a bit more investigation, I stumbled on `__xonsh__.last.rtn`, which is cleaner and works in scripts irrespective of behavior.
