### ISSUE TITLE
sudo password timeout doesn't work

### ISSUE THREAD

**Issue by nicolasavru** [xonsh/xonsh#1151]
In xonsh, sudo asks for the password every time:

```
[0:33:23][avru@gateway:~]$ sudo whoami
[sudo] password for avru: 
root
[0:33:27][avru@gateway:~]$ sudo whoami
root
[0:33:28][avru@gateway:~]$ xonsh
[00:33:36][avru@gateway:~]$ sudo whoami
[sudo] password for avru: 
root
[00:33:40][avru@gateway:~]$ sudo whoami
[sudo] password for avru: 
root
[00:33:44][avru@gateway:~]$ 
```

The first two sudos are in zsh, the second two in xonsh. Note the timestamps.

**Comment by adqm** [comment]
Thanks for reporting, @nicolasavru!  This one I can't reproduce (the password timeout seems to be working on my machine).  Can you include here the results of running the `xonfig` command?

**Comment by Carreau** [comment]
Keep in mind that the time are the time when the previous command vas executed (IIUC), unless ptk redraw the prompt ?

**Comment by nicolasavru** [comment]
xonfig output:
```
+------------------+----------------+
| xonsh            | 0.3.3          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | True           |
| on linux         | True           |
| distro           | arch           |
| on darwin        | False          |
| on windows       | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
```

@Carreau: the timestamp should be from when the prompt is drawn. It is configured like this:
```
import datetime
def timestamp():
    now = datetime.datetime.now()
    return '{:02d}:{:02d}:{:02d}'.format(now.hour, now.minute, now.second)

$FORMATTER_DICT['timestamp'] = timestamp
    
$PROMPT = ('[{PURPLE}{timestamp}{NO_COLOR}]'
           '[{CYAN}{user}{NO_COLOR}@{WHITE}{hostname}{NO_COLOR}:'
           '{YELLOW}{cwd}{NO_COLOR}]{prompt_end} ')

```

**Comment by scopatz** [comment]
This actually happens to me all the time, but I have never looked into it. Thanks for reporting @nicolasavru. I wasn't aware it actually worked anywhere.

**Comment by nicolasavru** [comment]
I think I found the problem. One of the attributes that sudo uses to identify a particular terminal is the shell's session id. In bash/zsh, the session id of all subprocesses is the same as that of the shell:
```
[0:56:50][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))'
6927
[0:56:53][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))'
6927
[0:56:53][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))'
6927
```
However, in xonsh, the session id is different for each command and doesn't match the xonsh's session id:
```
[01:13:42][avru@gateway:~]$ os.getsid(0)
6927
[01:14:36][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))'
20310
[01:14:41][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))'
20312
[01:14:42][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))'
20314
```
The session id of xonsh matches that of zsh because I launched xonsh from that zsh process.

Child processes normally inherit the parent's sid, unless setsid() is called. Python's pty.fork() (https://github.com/python-git/python/blob/master/Lib/pty.py#L90) calls os.setsid() and explicitly states in the docstring (but not the docs) that it makes the child a session leader. xonsh calls pty.fork() from https://github.com/xonsh/xonsh/blob/master/xonsh/teepty.py#L132.

The correction behavior is for each shell to be a session leader and for each process launched from the shell to share the shell's session id. So pty.fork() (if it is used at all) should be used to spawn new shells, not subprocesses from a shell.

I don't yet know exactly what the correction implementation would be. Also, I don't yet know what the correct session id behaviour for non-interactive shells is.

Additional tidbits:
1. A (IMO undesirable) workaround for this is bug is disabling the tty_tickets options in sudoers by adding this line to /etc/sudoers: ```Defaults !tty_tickets```
2. Lots of reading sudo source, hexdumping, and stracing was involved in debugging this issue.
3. fish had a similar bug (https://github.com/fish-shell/fish-shell/issues/122), though for a different reason. They were changing the controller tty's (/dev/pts/*) ctime, which is one of the other attributes sudo uses to identify shells.

**Comment by scopatz** [comment]
Wow, @nicolasavru! Thanks for the footwork tracking this issue down.  After some testing I believe that this is caused by `$XONSH_STORE_STDOUT`.  Normal Python subprocess.Popen() does not use pseudo terminal (pty) and does not call os.setsid(), [see the source](https://github.com/python-git/python/blob/master/Lib/subprocess.py).  However, we do use ptys to tee I/O so that we can store stdout.

To show this, consider the following on my machine:

```console
# Not storing  stdout
scopatz@artemis ~ $ $XONSH_STORE_STDOUT
False

# Note the python subproc has all the same SIDs
scopatz@artemis ~ $ python -c 'import os; print(os.getsid(0))'
3809
scopatz@artemis ~ $ python -c 'import os; print(os.getsid(0))'
3809
scopatz@artemis ~ $ python -c 'import os; print(os.getsid(0))'
3809

# And thus I am only asked for my sudo password on the first time.
scopatz@artemis ~ $ sudo echo wow mom
[sudo] password for scopatz: 
wow mom
scopatz@artemis ~ $ sudo echo wow mom
wow mom
scopatz@artemis ~ $ sudo echo wow mom
wow mom

# now set storing stdout to true
scopatz@artemis ~ $ $XONSH_STORE_STDOUT = True

# then note that the SIDs are all different
scopatz@artemis ~ $ python -c 'import os; print(os.getsid(0))'
3945
scopatz@artemis ~ $ python -c 'import os; print(os.getsid(0))'
3951
scopatz@artemis ~ $ python -c 'import os; print(os.getsid(0))'
3957

# now note that I am asked for my sudo password each time
scopatz@artemis ~ $ sudo echo wow mom
[sudo] password for scopatz: 
wow mom
scopatz@artemis ~ $ sudo echo wow mom
[sudo] password for scopatz: 
wow mom
```

If you can confirm this, we can talk about mitigation strategies. The easy one would be to have a way for aliases or commands either declare that they can't run in stored mode, or a way for them to declare the proc class (Popen, ProcProxy, TeeProcProxy, etc) that they wish to be run with.

**Comment by scopatz** [comment]
As a work around, I think you can so something like the following for the moment:

```python
with ${...}.swap(XONSH_STORE_STDOUT=False):
    sudo cmd args
```

**Comment by nicolasavru** [comment]
Confirming that sudo works when $XONSH_STORE_STDOUT is False.

I'm not very comfortable with the easy way that you suggest as I don't know what various programs use the session id for. I think we should implement it the right way for all proc classes, even if we need to stop using pty.fork().

https://github.com/xonsh/xonsh/issues/519 may be related, session id does have some job control implications: https://www.gnu.org/software/libc/manual/html_node/Concepts-of-Job-Control.html

**Comment by nicolasavru** [comment]
This also leads to some other unfortunate consequences:
```
[13:36:12][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))'
8787
[13:36:18][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))' | less
# prints "6004" in less
[13:36:33][avru@gateway:~]$ python -c 'import os; print(os.getsid(0))' | tee /tmp/sid_out




^C[13:37:23][avru@gateway:~]$ 
# the blank lines are me hitting enter a few times
[13:37:47][avru@gateway:~]$ cat /tmp/sid_out 


[13:37:49][avru@gateway:~]$ 
```
And a non-contrived examples:
```
[13:45:52][avru@gateway:~]$ $XONSH_STORE_STDOUT=True
[13:47:56][avru@gateway:~]$ pacman -Ss archlinux-keyring
core/archlinux-keyring 20160402-1 [installed]
    Arch Linux PGP keyring
[13:48:03][avru@gateway:~]$ yaourt -Ss archlinux-keyring
core/archlinux-keyring 20160402-1 [installed]
    Arch Linux PGP keyring
[13:48:08][avru@gateway:~]$ pacman -Ss archlinux-keyring | less
# empty output in less
[13:48:36][avru@gateway:~]$ yaourt -Ss archlinux-keyring | less
# empty output in less
[13:49:09][avru@gateway:~]$ pacman -Ql archlinux-keyring
archlinux-keyring /usr/
archlinux-keyring /usr/share/
archlinux-keyring /usr/share/pacman/
archlinux-keyring /usr/share/pacman/keyrings/
archlinux-keyring /usr/share/pacman/keyrings/archlinux-revoked
archlinux-keyring /usr/share/pacman/keyrings/archlinux-trusted
archlinux-keyring /usr/share/pacman/keyrings/archlinux.gpg
[13:49:33][avru@gateway:~]$ yaourt -Ql archlinux-keyring
archlinux-keyring /usr/
archlinux-keyring /usr/share/
archlinux-keyring /usr/share/pacman/
archlinux-keyring /usr/share/pacman/keyrings/
archlinux-keyring /usr/share/pacman/keyrings/archlinux-revoked
archlinux-keyring /usr/share/pacman/keyrings/archlinux-trusted
archlinux-keyring /usr/share/pacman/keyrings/archlinux.gpg
[13:49:35][avru@gateway:~]$ pacman -Ql archlinux-keyring | less
# less output:
#archlinux-keyring /usr/
#archlinux-keyring /usr/share/
#archlinux-keyring /usr/share/pacman/
#archlinux-keyring /usr/share/pacman/keyrings/
#archlinux-keyring /usr/share/pacman/keyrings/archlinux-revoked
#archlinux-keyring /usr/share/pacman/keyrings/archlinux-trusted
#archlinux-keyring /usr/share/pacman/keyrings/archlinux.gpg
#/tmp/tmp133j2prs (END)
[13:49:52][avru@gateway:~]$ yaourt -Ql archlinux-keyring | less
# empty output in less
[13:50:20][avru@gateway:~]$ pacman -Ql archlinux-keyring | tee /tmp/pacman_out
^C[13:51:01][avru@gateway:~]$ yaourt -Ql archlinux-keyring | tee /tmp/yaourt_out
^C[13:51:10][avru@gateway:~]$ 
# tee is broken for both
```
I don't know what yaourt is doing that causes it to break more than pacman, but both have problems.

All of this works as expected with $XONSH_STORE_STDOUT=False. Until this is fixed (if you think it will take a lot of work), I think this could definitely use some big warnings in the docs and the sample xonshrc snippet (http://xon.sh/xonshrc.html#snippets-for-xonshrc) should not set $XONSH_STORE_STDOUT = True.

**Comment by jeremydonahue** [comment]
This is an interesting one. It looks like `os.forkpty()` calls `setid()` even though the documentation doesn't explicitly state that. This can be observed with `strace` if you monkeypatch `pty.fork()`, commenting or removing the call to `setsid()` on [line 101](https://github.com/python-git/python/blob/master/Lib/pty.py#L101):

```
    try:
        pid, fd = os.forkpty()
    except (AttributeError, OSError):
        pass
    else:
        if pid == CHILD:
            try:
                #os.setsid()  # <<<--------  LINE 101
                pass
            except OSError:
                # os.forkpty() already set us session leader
                pass
        return pid, fd
```
You can see that `setsid() is still being called:
```
$ sudo strace -p4325 -f -e trace=setsid
...
Process 4442 attached
[pid  4442] setsid()                    = 4442
---
```

If you change `pty.fork()` with a version that doesn't try calling `os.forkpty()` at all (commenting [lines 94-105](https://github.com/python-git/python/blob/master/Lib/pty.py#L94-L105)), and doesn't call `setsid()` on [line 111](https://github.com/python-git/python/blob/master/Lib/pty.py#L111), it runs the same steps the documentation outlines [here](http://linux.die.net/man/3/forkpty), but doesn't change session id for the child process and things like `sudo` behave correctly. The changes in question result in `pty.fork()` looking like this:

```
def fork():
    master_fd, slave_fd = openpty()
    pid = os.fork()
    if pid == CHILD:
        os.close(master_fd)

        # Slave becomes stdin/stdout/stderr of child.
        os.dup2(slave_fd, STDIN_FILENO)
        os.dup2(slave_fd, STDOUT_FILENO)
        os.dup2(slave_fd, STDERR_FILENO)
        if (slave_fd > STDERR_FILENO):
            os.close (slave_fd)

        # Explicitly open the tty to make it become a controlling tty.
        tmp_fd = os.open(os.ttyname(STDOUT_FILENO), os.O_RDWR)
        os.close(tmp_fd)
    else:
        os.close(slave_fd)

    # Parent and child process.
    return pid, master_fd
```
This _does_ change the behavior of the job control problem outlined in #519. With the above changes I'm able to background a job with `$XONSH_STORE_STDOUT = True`. _However_, Xonsh never returns after the job is stopped, which I think stems from the parent process (xonsh) blocking while attempting to read from the child process's stdout. I don't know enough about the way Xonsh is passing signals around, but I think if the `read` is non-blocking and can be interrupted when Ctrl+Z is detected it should work as expected. Or maybe the output should be captured in another thread? Just thinking out loud here.

**Comment by scopatz** [comment]
I am all for updates to documentation :).  Another idea is to use the `tee` command directly on supported platforms.  @adqm had an implementation of this at one point but I think there were other issues.  I am not sure if tee also calls setsid(), though, too.  I would imagine there is a reasonable likelihood that it does though.  

We could also try to make things work with @jeremydonahue's version of fork () :)

**Comment by adqm** [comment]
> @adqm had an implementation of this at one point but I think there were other issues.

Thanks for bringing up these painful memories...it was _so close_to working.  #563.  But you're right; I had problems with `mutt` and `vim` in particular, who expected to be outputting to a pty instead of to a pipe (as with tee).  So then I tried explicitly opening a new pty and it was a reasonable workaround, except that the way some programs interacted with that were different than others (and I didn't see any way to detect the difference).

That said, maybe I should give this another shot.  Again, it was quite close to working before, and maybe it's closer to what we want in the end.

> I am not sure if tee also calls setsid(), though, too. I would imagine there is a reasonable likelihood that it does though.

I can't see that happening, actually.  The `tee` process would be totally separate from the actual process we care about and so would be unaffected.

**Comment by scopatz** [comment]
> Thanks for bringing up these painful memories...it was _so close_to working

:'( So very close....

> The tee process would be totally separate from the actual process we care about and so would be unaffected.

Maybe I am confusing `script` and `tee`. I am 80% sure that `script` considers itself another shell and calls setsid().

**Comment by scopatz** [comment]
This has been fixed at least since the subprocess refactor last year, please feel free to reopen if it remains an issue.
