### ISSUE TITLE
Command cannot use multiple lines values

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1152]
```
$ git commit -am 'Fixed issue xxx - <hit RETURN key>
fatal: Paths with -a does not make sense.
$
```

When writing git commit message, we sometime need to type into multiple messages for good. But this is break in xonsh when hit Enter.

**Comment by mitnk** [comment]
We could use `git commit <hit ENTER>` for workaround though.

**Comment by mitnk** [comment]
closing this one, since this seems duplicated with #806

**Comment by adqm** [comment]
Interesting.  It makes sense that this won't work as written (single-quoted strings can't span multiple lines); I would have thought this would work with Python's multiline strings (with triple-quotes), but that also seems not to work.  I think there is indeed a bug here.

I get really bizarre output for the following:
```
hartz@virtual1 ~/cat-soop default $ echo """hello
```

```
"""hello]
![echo """hello
```

**Comment by scopatz** [comment]
I agree that the multiline strings should probably work in subproc mode

**Comment by scopatz** [comment]
See #2246 for a potential fix

**Comment by scopatz** [comment]
I am reopening this issue for signle quotes but changing the bug label to a feature one until we decide what to do.

**Comment by mitnk** [comment]
Quoting from [here](https://github.com/xonsh/xonsh/pull/2246#issuecomment-282498503):

> I think we could move #1152 to a feature request. Personally, I am not interested in 
> implementing it. Also, as discussed above, I think there are good reasons for
> marking it as WONTFIX since Python strings and subproc strings would diverge.
> I think we'd need a broader conversation about it.

This makes sense to me. Thanks!

**Comment by gforsyth** [comment]
This has been implemented.
