### ISSUE TITLE
protect users from paste jacking

### ISSUE THREAD

**Issue by rahiel** [xonsh/xonsh#1154]
Xonsh together with prompt-toolkit is safe from pastejacking: pasting the malicious but harmless looking command [here](https://thejh.net/misc/website-terminal-copy-paste) in Bash will auto-execute, but on xonsh (w/ prompt-toolkit) I get to see the whole code and have to press Enter explicitly. Xonsh with readline is not protected from this.

I think it's worth mentioning Xonsh protects users against pastejacking, even if this feature was not on purpose.

References:  
- https://github.com/dxa4481/Pastejacking.
- https://github.com/Aaronmsv/PastejackingProtection

Edit: this does not apply to all xonsh users, changed to a feature request.

**Comment by melund** [comment]
It is not safe when doing it on windows (cmd.exe running xonsh with prompt_toolkit).

**Comment by adqm** [comment]
@rahiel, I'm not sure this is true generally speaking.  If I copy something that contains the newline at the end, it is still be run automatically.

**Comment by rahiel** [comment]
Sorry guys, I assumed the behaviour would be the same for everyone. I run xonsh \w prompt-toolkit on Linux (Ubuntu), in a xfce4-terminal. @adqm what is your setup? 

I've changed the issue to be more of a feature request.

**Comment by gforsyth** [comment]
@adqm usually runs with the readline shell, so that could be one difference.  
I'm on Arch using PTK and I do have the pastejacking protection you noticed

**Comment by scopatz** [comment]
Hi @rahiel - yeah, on ubuntu with ptk it does not execute automatically, but with readline it does. I think this would be a nice thing to have but hard to implement on readline, since by its very nature reads in lines :).  Pull requests welcome for sure.

**Comment by rahiel** [comment]
> Hi @rahiel - yeah, on ubuntu with ptk it does not execute automatically, but with readline it does. I think this would be a nice thing to have but hard to implement on readline, since by its very nature reads in lines :). Pull requests welcome for sure.

Starting from readline 7 it also has paste jacking protection, but it's off by default. Bash users can add `set enable-bracketed-paste on` to their `~/.inputrc` to enable it. Maybe xonsh can also enable it when it is in readline mode?

**Comment by scopatz** [comment]
Ahh OK, This should like a good idea.  Would you be willing to put in a PR to this effect?  You'll want to modify the "setup_readline()" function, somewhere around https://github.com/xonsh/xonsh/blob/master/xonsh/readline_shell.py#L91

IIRC the parse and bind function lets you set config option programatically.

**Comment by gforsyth** [comment]
This should still be implemented for the readline backend and should definitely be documented, on the website (#3225) and/or the manual(#2315)
