### ISSUE TITLE
Foreground commands get interrupted when resizing window

### ISSUE THREAD

**Issue by TurboTurtle** [xonsh/xonsh#1161]
This is a bit of an odd one, but I encountered this while test-driving xonsh.

I have multiple terminals open in a terminator window. My resize hotkey is Alt+$arrow to resize the active window in the left/right/up/down direction. If I am running, for example, a tar extraction and resize the window - the command terminates with the following:

> 
> File "/usr/lib/python3.4/site-packages/xonsh/base_shell.py", line 154, in default
>     run_compiled_code(code, self.ctx, None, 'single')
>   File "/usr/lib/python3.4/site-packages/xonsh/codecache.py", line 57, in run_compiled_code
>     func(code, glb, loc)
>   File "<xonsh-code>", line 1, in <module>
>   File "/usr/lib/python3.4/site-packages/xonsh/built_ins.py", line 607, in subproc_captured_hiddenobject
>     return run_subproc(cmds, captured='hiddenobject')
>   File "/usr/lib/python3.4/site-packages/xonsh/built_ins.py", line 472, in run_subproc
>     **subproc_kwargs)
>   File "/usr/lib/python3.4/site-packages/xonsh/proc.py", line 468, in __init__
>     tpty.spawn(args, env=env, stdin=stdin, delay=delay)
>   File "/usr/lib/python3.4/site-packages/xonsh/teepty.py", line 166, in spawn
>     _, self.wcode = os.waitpid(pid, 0)
> InterruptedError: [Errno 4] Interrupted system call

This only happens when I *hold* Alt+$arrow to continuously resize. If I hit the key combination once, even if repeatedly several times, the above does not happen. 

I don't see anything in the docs about hotkeys or anything being bound to an alt keystroke by default, so I'm at a bit of a loss as to what's going on here. I'm not able to reproduce this in any other terminal emulator, but neither have I been able to reproduce this with any other shell in terminator, so not entirely sure if this is isolated to an issue with xonsh that only manifests in terminator, or if it's specifically xonsh-in-terminator, but I can reproduce it 100% with xonsh-in-terminator. 

If I am manually resizing the window with a click-and-drag, this does not happen.

This is on Fedora 22, xonsh-0.3.3 and terminator-0.98-1.fc22.noarch.

**Comment by scopatz** [comment]
Hi @TurboTurtle, thanks for reporting!  This is a weird one. I use xonsh in terminator (on ubuntu) and I have never seen this happen (but I don't resize that oftern).  When you resize a window a SIGWINCH signal is sent.  My guess is that you are issuing these window change signals so fast that they are interrupting each other.  Which shell type are you using?  Can you report the output of the `xonfig` command, please?

**Comment by TurboTurtle** [comment]
> $ xonfig 
> +------------------+----------+
> | xonsh            | 0.3.3    |
> | Python           | 3.4.2    |
> | PLY              | 3.7      |
> | have readline    | True     |
> | prompt toolkit   | None     |
> | shell type       | readline |
> | pygments         | None     |
> | on posix         | True     |
> | on linux         | True     |
> | distro           | Fedora   |
> | on darwin        | False    |
> | on windows       | False    |
> | is superuser     | False    |
> | default encoding | utf-8    |
> +------------------+----------+
>

**Comment by laerus** [comment]
i'm actually using terminator in the same way since i've started using xonsh and never encountered this problem, and i'm using exactly the same shortcut `ALT + arrow`, i will close this issue but feel free to reopen if the problem persists on the latest xonsh version.
