### ISSUE TITLE
ZSH-like Suffix Aliases

### ISSUE THREAD

**Issue by nvalis** [xonsh/xonsh#1162]
In ZSH it is possible to set [suffix aliases](http://zshwiki.org/home/examples/aliassuffix). These define a function to call with the file as its argument if the suffix matches the aliased one. For example:

```
$ echo "test" > foo.bar
$ alias -s bar='cat'
$ foo.bar
test
$ ./foo.bar
test
$ /abs/path/to/file/foo.bar
test
```

It is a nice feature if you are working on the shell and often open pdf documents or images etc.

Some more useful examples:

```
$ alias -s pdf=evince
$ alias -s {jpg,png,tif}=feh
$ alias -s {mp3,flac}=vlc
```

I guess it first checks whether the file is executable or not, if yes the "execution mode" wins. If not then it checks whether there is an alias for the suffix. If yes execute alias and if not error.

<hr>

Edit: Actually I just tested it and the execution mode seems to loose. So even if executable the suffix mode will be used if there is a valid suffix alias. I think it would be more useful as described above.

**Comment by scopatz** [comment]
Thanks for suggesting this @nvalis! I this could be made to be supported via allowing alias keys to be regexs.

**Comment by gforsyth** [comment]
This can be implemented as a `xontrib` using `events.on_precommand`
