### ISSUE TITLE
Provide file location as a variable when sourcing a file

### ISSUE THREAD

**Issue by willsALMANJ** [xonsh/xonsh#1169]
As far as I can tell, there is no way for a `.xsh` file to tell where it is located (did I miss something?). It would be nice to have the equivalent of `$BASH_SOURCE` in bash or `__file__` in Python. This is useful if you want to store data in other files in the same directory as the `.xsh` file to be sourced without having to hard code all the paths inside the `.xsh` file.

**Comment by adqm** [comment]
Yes, this is a really good idea.

This might be a good first/early patch for someone.  In `xonsh.main.main`, there is a mode `XonshMode.script_from_file`.  When we're running in that mode, we should be able to grab the filename from the arguments that were passed in and store it in `$XONSH_SOURCE` (maybe after calling `os.path.normpath` and/or `os.path.expanduser` to normalize in some way).

**Comment by adqm** [comment]
This has been implemented in #1179, so I'm going to close this issue.  If you notice any other related issues, please feel free to re-open.

**Comment by willsALMANJ** [comment]
#1179 is great, but it is only half of what I wanted. It defines `$XONSH_SOURCE` within a script when you do `xonsh script.xsh`. I also wanted `$XONSH_SOURCE` to defined when one does `source script.xsh` inside of `xonsh` (`$BASH_SOURCE` behaves this way).

For context, the specific reason I want this is for this autojump script I made for `xonsh`: https://github.com/willsALMANJ/autojump-xonsh.  Right now, you need to add

```
import os
$AUTOJUMP_DIR = os.path.join($HOME, '.config/autojump')
source @(os.path.join($AUTOJUMP_DIR, 'autojump.xsh'))
```

to `.xonshrc` for it to work. `$AUTOJUMP_DIR` is needed right now so that `autojump.xsh` knows where to find `autojump-completion.bash`, so it can add it to `$BASH_COMPLETIONS`. If `autojump.xsh` could determine its own location and assume `autojump-completion.bash` was in the same directory, this could be simplified to just

```
source ~/.config/autojump/autojump.xsh
```

**Comment by scopatz** [comment]
@willsALMANJ - I believe that if you import an xsh file as a module, it will have a `__file__` global on it, just like any other python module you import. If it doesn't this is a bug and should be fixed.

**Comment by scopatz** [comment]
Adding `$XONSH_SOURCE` to the source alias is also not hard. I am reopening this for now.

**Comment by adqm** [comment]
Agreed.  But to anyone tackling this, if I'm not mistaken, we'll want to add `$XONSH_SOURCE` at the start, and then take it away at the end.  It might be tricky to make this work reliably with nested `source` calls (I'm not sure what, e.g., Bash does in that case).

**Comment by scopatz** [comment]
We'd probably just need some global list / stack that we append to at the start of a source call and pop off of at the end, right?  Maybe this could be another function or two so that it could also be used from main?

**Comment by adqm** [comment]
Sounds right to me.

**Comment by scopatz** [comment]
This has been implemented
