### ISSUE TITLE
UnboundLocalError: local variable 'readline' referenced before assignment

### ISSUE THREAD

**Issue by jhdulaney** [xonsh/xonsh#1170]
Hello!

When running in an environment with a local install of python 3 and no readline, I get:

No readline implementation available.  Skipping setup.
Could not find xonsh configuration or run control files.
UnboundLocalError: local variable 'readline' referenced before assignment

While the first two are logical and follow not having readline, the third seems to be an error.  I have not yet managed to track down the reference in question.

**Comment by adqm** [comment]
Thanks for reporting @jhdulaney!  One way to get a better traceback might be to create a `~/.xonshrc` file, and put inside of it:
`$XONSH_SHOW_TRACEBACK = True`

This should cause xonsh to show you a more complete traceback when it hits that error.  Can you give that a shot and let us know what you find?

**Comment by jhdulaney** [comment]
I've got an idea as to what it is; it detects that readline is not present, but then, in xonsh/shell.py that is basically ignored (in the __init__ of class Shell)  The question then becomes what to do about it?

**Comment by adqm** [comment]
In some sense, if the user doesn't have readline installed and they are trying to use the readline shell, it might make sense just to exit before trying to build the shell (I'm not sure exactly what else would be appropriate in that case...).

**Comment by jhdulaney** [comment]
The issue is that xonsh defaults to the readline shell, even if readline is not installed

**Comment by adqm** [comment]
Right.  But xonsh won't run without readline (unless PTK is installed), so it's not clear to me that there's anything we can do in that case.

I guess in theory we could add a third shell type that uses `input` or something like that, so that we don't have to kick users out and they can still access some of the goodness, and just warn them that the experience is super suboptimal without readline or PTK installed...

**Comment by scopatz** [comment]
Except that input() uses readline :).  The [Cmd class](https://docs.python.org/3/library/cmd.html) (which we subclass) should fall back to using stdin, stderr and stdout file handles directly. We might not be using this is the safest way, then.  This is probably a legitimate bug where we aren't checking is full readline is available.

**Comment by adqm** [comment]
Ah, okay.  I wasn't aware that `Cmd` would function without readline.  In that case, this should be a simple check and a warning that readline isn't installed, right?

**Comment by jhdulaney** [comment]
Well, it already checks and warns that readline is not available, and then tries to use it anyway.  On top of that, it actually appears to work without it, as it throws the exception but doesn't halt.

**Comment by a-da** [comment]
can we change instead of ?

    No readline implementation available.  Skipping setup.

to
   
    No readline implementation available.  Skipping setup. See https://github.com/xonsh/xonsh/issues/1170

And here in comments user will find solution like:

    apt-get install libncurses5-dev
    pip install readline

**Comment by scopatz** [comment]
I would also add a sentence that says "please install a backend (readline, prompt-toolkit, etc) to use xonsh interactively."

Also anyone please feel free to put in a PR for this!

**Comment by scopatz** [comment]
#1170 has been merged. Please feel free to reopen if needed.
