### ISSUE TITLE
space before curr_branch on PROMPT

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1171]
is there a reason why the `current_branch` function in environ.py, that is the value for the prompt-variable `curr_branch` in FORMATTER_DICT, has a `pad` argument that is by default True?

wouldn't be easy to just include the space in the PROMPT itself?

**Comment by melund** [comment]
Then there would be an extra (redundant) space in the PROMPT when you are not in a repository. Try to experiment a little. If you come up with a better solution a PR would be very welcome.

**Comment by scopatz** [comment]
That said, we do need a better way to handle padding iff the return value longer than 0.
