### ISSUE TITLE
Atom can't figure out environment variables when launched by lunchctl

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1172]
When not using a terminal to open atom it doesn't figure out environment variables. Inside atom compare the differences in "process.env" in the console (opt+cmd+i to open). Looking at the documentation of the old environment package https://atom.io/packages/environment it should be opening a xonsh instance and then importing everything that env outputs. I don't know what exactly is braking or how to see any error messages on atom.

**Comment by scopatz** [comment]
Hi @santagada - Thanks for reporting this. As someone who is not an atom user, and not knowing the error message, I am not entirely sure what we can do about this at the moment.  If you can figure out a way to get the error message, that would be super helpful.

**Comment by santagada** [comment]
I think I'm seeing the same problem with pycharm which also uses some work around launchctl crazyness.

**Comment by santagada** [comment]
sent a pull request for atom https://github.com/atom/atom/pull/12535 I think this can be closed when the PR is merged/released

**Comment by scopatz** [comment]
Is this ready to close now, @santagada, since the atom issue has been merged and released?

**Comment by santagada** [comment]
totally.
