### ISSUE TITLE
!(command) could be usefully iterable

### ISSUE THREAD

**Issue by eode** [xonsh/xonsh#1175]
So, this is nicely doable with regular file objects:

```python
for line in open('somefile.txt'):
    # do something with each line
```

..this is *very* succinct when dealing with something you only care about the textual output of, as is the case with a lot of system calls.

It might be nice to do something like this:

```python
for line in !(somecommand):
    # do something with each line of stdout
```

..and even more awesome (IMO) if one could do something like this:

```python
try:
    for line in !(somecommand):
        # do something with each line of stdout
except SomeException as error:
        # If the return value is nonzero, and after iterating through all lines of stdout,
        # the iterator raises an appropriate exception instead of StopIteration.
        # Error probably contains the object returned by !(somecommand)
```

..just a thought.. :-)

**Comment by adqm** [comment]
I agree that this would be a cool feature; thanks @eode!  I've marked this with the `newcomer` tag because I think it might be a nice place for someone to jump into the code.

The `!()` operator creates an instance of `xonsh.proc.CompletedCommand`, which contains (among other things) the string representing the process's standard output.  I think an initial solution would just involve adding an `__iter__` method to that class, which loops over the lines in the string representing `stdout`.

**Comment by eode** [comment]
Yep, makes sense to me.  I'll dig in with a fork.

**Comment by eode** [comment]
As to the error situation -- what error would be appropriate?

**Comment by eode** [comment]
I considered creating a subclass of CompletedCommand that's also an exception, but I dunno if that's a good idea.

**Comment by adqm** [comment]
I think `subprocess.CalledProcessError` is a reasonable candidate, since that is what is normally used to indicate those kinds of errors.  

I wonder if that exception should only be raised if [`$RAISE_SUBPROC_ERROR`](http://xon.sh/envvars.html#raise-subproc-error) is `True`.  Though then again, if we have that, calling the subprocess would already have raised an error.  Are you talking about raising that exception specifically within `__iter__`?  What do you think the benefit of that would be, beyond what `$RAISE_SUBPROC_ERROR` does?

**Comment by eode** [comment]
Well, the idea was mainly that you'd be able to process all of the input, regardless of whether or not the process returned an error -- so, for example, if you had something that returned *some* valid input that you *do* want, but borked on an error, this would allow you to process both appropriately.

**Comment by adqm** [comment]
Oh, I see; raising the exception _after_ the last line of stdout.  Gotcha; that's a great idea.  Sorry I misread!

**Comment by eode** [comment]
Hehe.  ..was in the process of defining that more clearly, but you got it.

**Comment by eode** [comment]
Is the fact that _CCTuple is a namedtuple going to introduce any complication?  ..that is, is there a place to your knowledge where you already rely on iteration of the tuple?

**Comment by adqm** [comment]
I don't think so, no.  And I can't imagine any reasonable use of `_CCTuple`'s iterator (since that iterator would be kind of nonsensical).  I just used namedtuple there to avoid having to write everything out.

```
xonsh $ for i in !(ls):
.......     print(type(i))
.......
.......
<class 'NoneType'>
<class 'str'>
<class 'str'>
<class 'int'>
<class 'int'>
<class 'list'>
<class 'list'>
<class 'NoneType'>
<class 'NoneType'>
<class 'NoneType'>
<class 'tuple'>
xonsh $ #why did i do that loop???
```

**Comment by eode** [comment]
Sounds good.  Last question, I think:  Include line endings, or no?

**Comment by adqm** [comment]
My vote would be to get rid of the line endings.  I imagine that most people wouldn't want them.

**Comment by eode** [comment]
Sounds good.  Is it a problem if it's more than one commit, or should I rework that somehow to be cleaner?  ..people can be understandably picky about git history.

**Comment by adqm** [comment]
We're not too picky.  In fact, I (and, I think, @scopatz) prefer to see the whole history of commits when looking at the log, so as to keep logical changes separate (rather than having everything in one big diff).  Thanks again for working on this!

**Comment by scopatz** [comment]
+1 to what @adqm said.  If I am picky at all it is when people destroy history (squash etc.)  But if you are just on your own branch it is your sand box :)

**Comment by scopatz** [comment]
Also +1 to getting rid of line endings.  I think that this is how it works when you iterate through a file.  Also, also this is a super neat idea!

**Comment by eode** [comment]
Hrm, so, a little bit of a complication.

In theory, when there's an error, the executed command should be present to inspect -- however, that's handled in builtins.py, and it doesn't return the executed command on success.

Should we create a new field in _CCTuple called e.g. "executed_cmd", that has the command that was actually executed?

**Comment by adqm** [comment]
It's _kind of_ there, in the `args` and `alias` field, but I agree completely that it should be there in a more accessible form.  I think `"executed_cmd"` sounds good!

**Comment by eode** [comment]
K, will do.

**Comment by eode** [comment]
Pull Request:  #1183
