### ISSUE TITLE
~ should be interpreted inside env variables

### ISSUE THREAD

**Issue by Cheaterman** [xonsh/xonsh#1176]
Hello,

Today I tried $PATH.insert(0, '~/somedir') - it fails for reasons that are now obvious, but scopatz said the following on IRC:

`<scopatz> Cheaterman: Well the PATH should just be a dumb list of strings.  However, things that use $PATH should do user and envvar expansion when they use them.  It looks like this is not happening.`

So I suppose this should be considered a bug - xonsh will be even more comfy this way too ^__^

Thanks in advance!

**Comment by scopatz** [comment]
Thanks for reporting this @Cheaterman

**Comment by laerus** [comment]
this issue is fixed!
