### ISSUE TITLE
xonsh installation fails on python 3.2 on ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by zaxebo1** [xonsh/xonsh#118]
when on ubuntu 12.04 LTS , using python 3.2 i tried to install xonsh with the command
  sudo  pip3 install xonsh
then installation FAILED with "following" log in $HOME/.pip/pip.log
------------------------------------------------------------
------------------------------------------------------------
Downloading/unpacking xonsh
  Getting page https://pypi.python.org/simple/xonsh/
  URLs to search for versions for xonsh:
  * https://pypi.python.org/simple/xonsh/
  Analyzing links from page https://pypi.python.org/simple/xonsh/
    Found link https://pypi.python.org/packages/source/x/xonsh/xonsh-0.1.0.tar.gz#md5=f1ed00e0d48042ba930aa120ec26dd18 (from https://pypi.python.org/simple/xonsh/), version: 0.1.0
    Found link https://pypi.python.org/packages/source/x/xonsh/xonsh-0.1.1.tar.gz#md5=7e61c7a4d0e2a80917c659cd6ae2a4df (from https://pypi.python.org/simple/xonsh/), version: 0.1.1
    Found link https://pypi.python.org/packages/source/x/xonsh/xonsh-0.1.2.tar.gz#md5=11458e7c3788a4bbc41d5eec600fa02b (from https://pypi.python.org/simple/xonsh/), version: 0.1.2
  Using version 0.1.2 (newest of versions: 0.1.2, 0.1.1, 0.1.0)
  Downloading from URL https://pypi.python.org/packages/source/x/xonsh/xonsh-0.1.2.tar.gz#md5=11458e7c3788a4bbc41d5eec600fa02b (from https://pypi.python.org/simple/xonsh/)
  Running setup.py (path:/tmp/pip_build_root/xonsh/setup.py) egg_info for package xonsh
    zip_safe flag not set; analyzing archive contents...
    
                               ╓██▄
                              ╙██▀██╕
                             ▐██4Φ█▀█▌
                           ²██▄███▀██^██
                         -███╩▀ " ╒▄█████▀█
                          ║██▀▀W╤▄▀ ▐║█╘ ╝█
                     ▄m▀%Φ▀▀  ╝*"    ,α█████▓▄,▄▀Γ"▀╕
                     "▀██¼"     ▄═╦█╟║█▀ ╓ `^`   ,▄ ╢╕
                      ,▀╫M█▐j╓╟▀ ╔▓▄█▀  '║ ╔    ╣║▌  ▀▄
                   ▄m▀▀███╬█╝▀  █▀^      "ÜM  j▐╟╫╨▒   ╙▀≡═╤═m▀╗
                   █æsæ╓  ╕, ,▄Ä   ▐'╕H   LU  ║║╠╫Å^2=⌐         █
                ▄æ%Å███╠█ª╙▄█▀      $1╙       ║║╟╫╩*T▄           ▌
               ╙╗%▄,╦██▌█▌█╢M         ╕      M║║║║█═⌐ⁿ"^         ╫
                 ╙╣▀████@█░█    ▌╕╕   `      ▌║▐▐║█D═≈⌐¬ⁿ      s ║⌐
                   ╙╬███▓║█`     ▌╚     ╕   ╕▌║▐▐╣▌⌐*▒▒Dù`       ▐▌
                    ╙╬██╨U█      ╟      $ ▌ ▌▌▐▐▐M█▄═≤⌐%       ╓⌐ ▌
                     ║║█▄▌║             ╟ ▌ ▌M▐▐▐M█▀▒▒▒22,       ▐▌
                      ███╙^▌            ║ ▌ ⌐M▐▐▐M█≤⌐⌐¬──        ▐M
                      ║██ ▌╙   ╓       H║ ▌╒ M║▐▐M█"^^^^^"ⁿ      ║
                       ██╕╙@▓   ╕      ▌║ H'  ║▐▐▐█══=.,,,       █
                       ╙█▓╔╚╚█     ╠   ▌└╒ ▌▐ ╚║║║▀****ⁿ -      ╓▌
                        ╙█▌¼V╚▌   ▌  ╕ ▌ ║╒ ║ ▌▒╠█▀≤≤≤≤≤⌐       █
                         ╙█▌╔█╚▌     ┘ M ▌║ ╫ UUM██J^^"        ▐▌
                          ╙██╙█╙▌  ╕$j  ▐⌐▌ ▌║╝╟█Å%%%≈═        █
                           ╙╣█╣█^▌ ╠║▐  ║ ▌▐.DU██^[""ⁿ       -╒▌
                             ▀█▄█`▌ ░M▀ ▌▐ Å£╝╝█╜%≈═╓""w   ⁿ⌐ █
                              `▀▄▀`▌ ▌█▐⌐║▐UW╖██%≤═░*─    =z ▄Γ
                                ╙██╙▄▌█  ▌Å╛╣██╨%╤ƒⁿ=    -` ▄┘
                                  █▌╢▓▌▌ W £6█╤,"ⁿ `   ▄≡▀▀▀
                                   █"█▌▌╟Å╓█╓█▀%`    ▄▀
                                   ╙▌██`▒U▓U█%╗*     █
                                    ▌╫║ ▌ÅÅ║▀╛¬`      `"█
                                    ▌╫  ╫╟ █▄     ~╦%▒╥4^
                                    ▌▌  "M█ `▀╕ X╕"╗▄▀^
                                    █▌   ╓M   ╙▀e▀▀^
                                    ╙██▄▄▀
                                      ^^
    
    
    Installed /tmp/pip_build_root/xonsh/ply-3.4-py3.2.egg
    running egg_info
    creating pip-egg-info/xonsh.egg-info
    writing requirements to pip-egg-info/xonsh.egg-info/requires.txt
    writing pip-egg-info/xonsh.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/xonsh.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/xonsh.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/xonsh.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/xonsh.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/xonsh.egg-info/SOURCES.txt'
  Source in /tmp/pip_build_root/xonsh has version 0.1.2, which satisfies requirement xonsh
Downloading/unpacking ply (from xonsh)
  Getting page https://pypi.python.org/simple/ply/
  URLs to search for versions for ply (from xonsh):
  * https://pypi.python.org/simple/ply/
  Analyzing links from page https://pypi.python.org/simple/ply/
    Found link https://pypi.python.org/packages/source/p/ply/ply-3.4.tar.gz#md5=ffdc95858819347bf92d7c2acc074894 (from https://pypi.python.org/simple/ply/), version: 3.4
    Skipping link http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/); not a file
    Skipping http://www.dabeaz.com/ply/ply-2.0.tar.gz (from https://pypi.python.org/simple/ply/) because it is externally hosted.
    Skipping http://www.dabeaz.com/ply/ply-2.1.tar.gz (from https://pypi.python.org/simple/ply/) because it is externally hosted.
    Skipping http://www.dabeaz.com/ply/ply-2.2.tar.gz (from https://pypi.python.org/simple/ply/) because it is externally hosted.
    Skipping http://www.dabeaz.com/ply/ply-2.4.tar.gz (from https://pypi.python.org/simple/ply/) because it is externally hosted.
    Skipping http://www.dabeaz.com/ply/ply-2.5.tar.gz (from https://pypi.python.org/simple/ply/) because it is externally hosted.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ply-2.0.tar.gz (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ply-2.1.tar.gz (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ply-2.2.tar.gz (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ply-2.4.tar.gz (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Not searching http://www.dabeaz.com/ply/ply-2.5.tar.gz (from https://pypi.python.org/simple/ply/) for files because external urls are disallowed.
  Downloading from URL https://pypi.python.org/packages/source/p/ply/ply-3.4.tar.gz#md5=ffdc95858819347bf92d7c2acc074894 (from https://pypi.python.org/simple/ply/)
  Running setup.py (path:/tmp/pip_build_root/ply/setup.py) egg_info for package ply
    running egg_info
    creating pip-egg-info/ply.egg-info
    writing pip-egg-info/ply.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/ply.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/ply.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/ply.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/ply.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/ply.egg-info/SOURCES.txt'
  Source in /tmp/pip_build_root/ply has version 3.4, which satisfies requirement ply (from xonsh)
Installing collected packages: xonsh, ply
  Running setup.py install for xonsh
    Running command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/xonsh/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2gp4cw-record/install-record.txt --single-version-externally-managed --compile
    
                               ╓██▄
                              ╙██▀██╕
                             ▐██4Φ█▀█▌
                           ²██▄███▀██^██
                         -███╩▀ " ╒▄█████▀█
                          ║██▀▀W╤▄▀ ▐║█╘ ╝█
                     ▄m▀%Φ▀▀  ╝*"    ,α█████▓▄,▄▀Γ"▀╕
                     "▀██¼"     ▄═╦█╟║█▀ ╓ `^`   ,▄ ╢╕
                      ,▀╫M█▐j╓╟▀ ╔▓▄█▀  '║ ╔    ╣║▌  ▀▄
                   ▄m▀▀███╬█╝▀  █▀^      "ÜM  j▐╟╫╨▒   ╙▀≡═╤═m▀╗
                   █æsæ╓  ╕, ,▄Ä   ▐'╕H   LU  ║║╠╫Å^2=⌐         █
                ▄æ%Å███╠█ª╙▄█▀      $1╙       ║║╟╫╩*T▄           ▌
               ╙╗%▄,╦██▌█▌█╢M         ╕      M║║║║█═⌐ⁿ"^         ╫
                 ╙╣▀████@█░█    ▌╕╕   `      ▌║▐▐║█D═≈⌐¬ⁿ      s ║⌐
                   ╙╬███▓║█`     ▌╚     ╕   ╕▌║▐▐╣▌⌐*▒▒Dù`       ▐▌
                    ╙╬██╨U█      ╟      $ ▌ ▌▌▐▐▐M█▄═≤⌐%       ╓⌐ ▌
                     ║║█▄▌║             ╟ ▌ ▌M▐▐▐M█▀▒▒▒22,       ▐▌
                      ███╙^▌            ║ ▌ ⌐M▐▐▐M█≤⌐⌐¬──        ▐M
                      ║██ ▌╙   ╓       H║ ▌╒ M║▐▐M█"^^^^^"ⁿ      ║
                       ██╕╙@▓   ╕      ▌║ H'  ║▐▐▐█══=.,,,       █
                       ╙█▓╔╚╚█     ╠   ▌└╒ ▌▐ ╚║║║▀****ⁿ -      ╓▌
                        ╙█▌¼V╚▌   ▌  ╕ ▌ ║╒ ║ ▌▒╠█▀≤≤≤≤≤⌐       █
                         ╙█▌╔█╚▌     ┘ M ▌║ ╫ UUM██J^^"        ▐▌
                          ╙██╙█╙▌  ╕$j  ▐⌐▌ ▌║╝╟█Å%%%≈═        █
                           ╙╣█╣█^▌ ╠║▐  ║ ▌▐.DU██^[""ⁿ       -╒▌
                             ▀█▄█`▌ ░M▀ ▌▐ Å£╝╝█╜%≈═╓""w   ⁿ⌐ █
                              `▀▄▀`▌ ▌█▐⌐║▐UW╖██%≤═░*─    =z ▄Γ
                                ╙██╙▄▌█  ▌Å╛╣██╨%╤ƒⁿ=    -` ▄┘
                                  █▌╢▓▌▌ W £6█╤,"ⁿ `   ▄≡▀▀▀
                                   █"█▌▌╟Å╓█╓█▀%`    ▄▀
                                   ╙▌██`▒U▓U█%╗*     █
                                    ▌╫║ ▌ÅÅ║▀╛¬`      `"█
                                    ▌╫  ╫╟ █▄     ~╦%▒╥4^
                                    ▌▌  "M█ `▀╕ X╕"╗▄▀^
                                    █▌   ╓M   ╙▀e▀▀^
                                    ╙██▄▄▀
                                      ^^
    
    running install
    Remove xonsh/lexer_table.py
    Remove xonsh/parser_table.py
    Building lexer and parser tables.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_root/xonsh/setup.py", line 114, in <module>
        main()
      File "/tmp/pip_build_root/xonsh/setup.py", line 71, in main
        setup(**skw)
      File "/usr/lib/python3.2/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command
        cmd_obj.run()
      File "/tmp/pip_build_root/xonsh/setup.py", line 37, in run
        build_tables()
      File "/tmp/pip_build_root/xonsh/setup.py", line 29, in build_tables
        from xonsh.parser import Parser
      File "/tmp/pip_build_root/xonsh/xonsh/parser.py", line 9, in <module>
        from xonsh import ast
      File "/tmp/pip_build_root/xonsh/xonsh/ast.py", line 3, in <module>
        from ast import Module, Num, Expr, Str, Bytes, UnaryOp, UAdd, USub, Invert, \
    ImportError: cannot import name NameConstant
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/xonsh/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2gp4cw-record/install-record.txt --single-version-externally-managed --compile:
    

                           ╓██▄

                          ╙██▀██╕

                         ▐██4Φ█▀█▌

                       ²██▄███▀██^██

                     -███╩▀ " ╒▄█████▀█

                      ║██▀▀W╤▄▀ ▐║█╘ ╝█

                 ▄m▀%Φ▀▀  ╝*"    ,α█████▓▄,▄▀Γ"▀╕

                 "▀██¼"     ▄═╦█╟║█▀ ╓ `^`   ,▄ ╢╕

                  ,▀╫M█▐j╓╟▀ ╔▓▄█▀  '║ ╔    ╣║▌  ▀▄

               ▄m▀▀███╬█╝▀  █▀^      "ÜM  j▐╟╫╨▒   ╙▀≡═╤═m▀╗

               █æsæ╓  ╕, ,▄Ä   ▐'╕H   LU  ║║╠╫Å^2=⌐         █

            ▄æ%Å███╠█ª╙▄█▀      $1╙       ║║╟╫╩*T▄           ▌

           ╙╗%▄,╦██▌█▌█╢M         ╕      M║║║║█═⌐ⁿ"^         ╫

             ╙╣▀████@█░█    ▌╕╕   `      ▌║▐▐║█D═≈⌐¬ⁿ      s ║⌐

               ╙╬███▓║█`     ▌╚     ╕   ╕▌║▐▐╣▌⌐*▒▒Dù`       ▐▌

                ╙╬██╨U█      ╟      $ ▌ ▌▌▐▐▐M█▄═≤⌐%       ╓⌐ ▌

                 ║║█▄▌║             ╟ ▌ ▌M▐▐▐M█▀▒▒▒22,       ▐▌

                  ███╙^▌            ║ ▌ ⌐M▐▐▐M█≤⌐⌐¬──        ▐M

                  ║██ ▌╙   ╓       H║ ▌╒ M║▐▐M█"^^^^^"ⁿ      ║

                   ██╕╙@▓   ╕      ▌║ H'  ║▐▐▐█══=.,,,       █

                   ╙█▓╔╚╚█     ╠   ▌└╒ ▌▐ ╚║║║▀****ⁿ -      ╓▌

                    ╙█▌¼V╚▌   ▌  ╕ ▌ ║╒ ║ ▌▒╠█▀≤≤≤≤≤⌐       █

                     ╙█▌╔█╚▌     ┘ M ▌║ ╫ UUM██J^^"        ▐▌

                      ╙██╙█╙▌  ╕$j  ▐⌐▌ ▌║╝╟█Å%%%≈═        █

                       ╙╣█╣█^▌ ╠║▐  ║ ▌▐.DU██^[""ⁿ       -╒▌

                         ▀█▄█`▌ ░M▀ ▌▐ Å£╝╝█╜%≈═╓""w   ⁿ⌐ █

                          `▀▄▀`▌ ▌█▐⌐║▐UW╖██%≤═░*─    =z ▄Γ

                            ╙██╙▄▌█  ▌Å╛╣██╨%╤ƒⁿ=    -` ▄┘

                              █▌╢▓▌▌ W £6█╤,"ⁿ `   ▄≡▀▀▀

                               █"█▌▌╟Å╓█╓█▀%`    ▄▀

                               ╙▌██`▒U▓U█%╗*     █

                                ▌╫║ ▌ÅÅ║▀╛¬`      `"█

                                ▌╫  ╫╟ █▄     ~╦%▒╥4^

                                ▌▌  "M█ `▀╕ X╕"╗▄▀^

                                █▌   ╓M   ╙▀e▀▀^

                                ╙██▄▄▀

                                  ^^

running install

Remove xonsh/lexer_table.py

Remove xonsh/parser_table.py

Building lexer and parser tables.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/xonsh/setup.py", line 114, in <module>

    main()

  File "/tmp/pip_build_root/xonsh/setup.py", line 71, in main

    setup(**skw)

  File "/usr/lib/python3.2/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command

    cmd_obj.run()

  File "/tmp/pip_build_root/xonsh/setup.py", line 37, in run

    build_tables()

  File "/tmp/pip_build_root/xonsh/setup.py", line 29, in build_tables

    from xonsh.parser import Parser

  File "/tmp/pip_build_root/xonsh/xonsh/parser.py", line 9, in <module>

    from xonsh import ast

  File "/tmp/pip_build_root/xonsh/xonsh/ast.py", line 3, in <module>

    from ast import Module, Num, Expr, Str, Bytes, UnaryOp, UAdd, USub, Invert, \

ImportError: cannot import name NameConstant

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/xonsh/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2gp4cw-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/xonsh
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.2/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/local/lib/python3.2/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/local/lib/python3.2/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/xonsh/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2gp4cw-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/xonsh

**Comment by scopatz** [comment]
Yup - this is known.  Currently xonsh only targets the Python v3.4 AST.  I would very readily support any PR that modified xonsh to work on other versions of Python.

**Comment by gforsyth** [comment]
I'm closing this.  Anyone who wants to modify the parser to support Python 3.2 is still welcome to do so.
