### ISSUE TITLE
.xonsh_history file config choice

### ISSUE THREAD

**Issue by paul-hammant** [xonsh/xonsh#1189]
If the user desires, Xonsh could build history in the **current directory** - in a .xonsh_history file. If you're reverse searching through history it would check that file and .xonsh_history files in parent directories only.

Rationale?  Oh, because the world is a messy, asynchronous place.

**Comment by scopatz** [comment]
@paul-hammant You are suggesting this in addition to the current history mechanisms, right? I am not sure this is really consistent with the XDG open desktop standard, but the important feature here is to have PWD-dependent history.  I think this could be done simply by having a file or files in the XONSH_DATA_DIRS that stores history by PWD.  

This would be kind of annoying to implement given the way the ptk and readline history work, but I would be in favor of having this. 

I am happy to walk anyone who wants to implement it through what I would think needs to happen.

**Comment by paul-hammant** [comment]
I'd prefer it per actual directory rather than the XONSH_DATA_DIRS way. I mean if I `cp -R foo foo2` I get all the history too, and all the commands that were relative within the history for that would work fine, if replayed.

**Comment by scopatz** [comment]
I'd be fine if the per-directory stuff was added as an option.  However, I think that the default should be the single file in `XONSH_DATA_DIRS` method for both performance and standards reasons.  Users could set an envvar that controls this if they wanted the alternate behavior.

**Comment by gforsyth** [comment]
Closing this out due to age.  Ping if you're interested in taking it on.
