### ISSUE TITLE
Python libraries conflict with sub process namespaces

### ISSUE THREAD

**Issue by ns-phennessy** [xonsh/xonsh#1190]
This could be a potential problem to be aware of: 

    $ time date
    Thu Jun  9 12:34:39 CDT 2016
    0.00user 0.00system 0:00.00elapsed ?%CPU (0avgtext+0avgdata 1972maxresident)k
    0inputs+0outputs (0major+79minor)pagefaults 0swaps```

    $ import time
    $ time
    <module 'time' (built-in)>
    $ time.time()
    1465493831.8466434

    $ time date
    Thu Jun  9 12:37:20 CDT 2016
    0.00user 0.00system 0:00.00elapsed ?%CPU (0avgtext+0avgdata 1956maxresident)k
    0inputs+0outputs (0major+78minor)pagefaults 0swaps

If we have a binary with the same name as something that exists in Python; how does Xonsh decide which is which?

**Comment by melund** [comment]
Yes. That can easily happen. On Windows for example `dir` command clashes with Python's built-in of the same name. In those cases Python wins. Nothing weird about that. 


In some cases you could delete the built-in commands but that could have some bad consequences.

**Comment by melund** [comment]
So with the windows example: if you type `dir .` instead xonsh will see that it not a valid Python command and fall back to subproc mode.

**Comment by ns-phennessy** [comment]
This could also cause a problem:

    $ import time
    $ aliases['time'] = 'echo foo'
    $ time
    <module 'time' (built-in)>

So along with what you said it favors Python above any 'shell-y' items?

**Comment by laerus** [comment]
from xon.sh Tutorial:
> For any given line if the left-most name cannot be found as a current variable name xonsh will try to parse the line as a subprocess command instead, then subprocess mode will be attempted. If parsing in subprocess mode fails, then the line is left in Python-mode.

i guess aliases come last in the hierarchy

**Comment by ns-phennessy** [comment]
Would there be a way to tell Xonsh to explicitly execute in subprocess or python mode? It would solve this problem so you could happily use either if you bump into this.

**Comment by laerus** [comment]
yes with $() and @() you can explicitly choose an execution mode
its all there in the docs, and many more cool stuff!

[http://xon.sh/tutorial.html](xonsh)

**Comment by ns-phennessy** [comment]
Awesome! Thanks @laerus
