### ISSUE TITLE
`__file__` not defined when importing a `.xsh` file

### ISSUE THREAD

**Issue by willsALMANJ** [xonsh/xonsh#1194]
Creating a file `test.xsh` with content

```
print(__file__)
```

and then importing it with `import test` gives me `NameError: name '__file__' is not defined` whereas as mentioned in #1169 `__file__` should be set to the path to `test.xsh`.

**Comment by scopatz** [comment]
Thanks for reporting @willsALMANJ! Looks like there is more work to do on the import hooks.

**Comment by laerus** [comment]
its seem that `get_filename()` method in `XonshImportHook` isn't being called when importing a .xsh script.
