### ISSUE TITLE
Pure-ANSI PTK Theme?

### ISSUE THREAD

**Issue by adqm** [xonsh/xonsh#1195]
This is mostly for @Carreau's eyes, since I think he is the most likely to know, but others are welcome to chime in.

Is it possible to make a theme for PTK that just uses only 16-color ANSI escape sequences, and no custom hex colors?  If possible, it seems like this would be a nice default theme for PTK.

It looks like there is some code in pyghooks that attempts to do this, but I have been unable to get it to work, and I have been unable to reconcile the code there with [the one mention I found of ANSI colors in PTK](https://github.com/jonathanslenders/python-prompt-toolkit/pull/240) (hey look it's @Carreau!).

**Comment by Carreau** [comment]
> Is it possible to make a theme for PTK that just uses only 16-color ANSI escape sequences, and no custom hex colors? If possible, it seems like this would be a nice default theme for PTK.

Yes likely, that one of the things I want to do with IPython as well, we have to figure out all the used  token and build a theme from that. haven't tried though, and don't know how it behave with bold, as bold is a weird thing in ansi.

**Comment by Carreau** [comment]
Oh, and I'm not even sure if the `#ansicodes` are working for background.

**Comment by Carreau** [comment]
So in pyghook, you already have the following:

```
if hasattr(pygments.style, 'ansicolors'):
    DEFAULT_STYLE = {
        Color.BLACK: '#ansidarkgray',
        Color.BLUE: '#ansiblue',
        Color.CYAN: '#ansiturquoise',
        Color.GREEN: '#ansigreen',
        Color.INTENSE_BLACK: '#ansiblack',
        Color.INTENSE_BLUE: '#ansidarkblue',
        Color.INTENSE_CYAN: '#ansiteal',
        Color.INTENSE_GREEN: '#ansidarkgreen',
        Color.INTENSE_PURPLE: '#ansipurple',
        Color.INTENSE_RED: '#ansidarkred',
        Color.INTENSE_WHITE: '#ansilightgray',
        Color.INTENSE_YELLOW: '#ansibrown',
        Color.NO_COLOR: 'noinherit',
        Color.PURPLE: '#ansifuchsia',
        Color.RED: '#ansired',
        Color.WHITE: '#ansiwhite',
        Color.YELLOW: '#ansiyellow',
    }
```

it's missing the BOLD, UNDERLINE, BACKGROUND versions. We could likely do that with a default dict implementation (to simplify) but it needs pygment master.

**Comment by adqm** [comment]
Oh I see.  I am on the most recent release of pygments (but not master), so that might explain why this wasn't working for me.

**Comment by Carreau** [comment]
> Oh I see. I am on the most recent release of pygments (but not master), so that might explain why this wasn't working for me.

Maybe it does now that PTK handle it, we should try. Though the completions does not seem to use that so the theme might need to be improved.

**Comment by adqm** [comment]
Nice!  Updating to pygments master makes the prompt use the ANSI colors!  But you're right that the completer doesn't use them yet.  So I agree there are some improvements to be made to the theme, potentially.  Thanks!

**Comment by Carreau** [comment]
I believe `CompoundColorMap` have PTK_STYLE too early in pyghook. thus the default style take precedence.

changin setup.py with:

```
    if HAVE_SETUPTOOLS:
        skw['entry_points'] = {
            'pygments.lexers': ['xonsh = xonsh.pyghooks:XonshLexer',
                                'xonshcon = xonsh.pyghooks:XonshConsoleLexer'],
+           'pygments.styles': ['xonshean = xonsh.theme:CrustaceanlyYours'],
            'console_scripts': ['xonsh = xonsh.main:main'],
            }
        skw['cmdclass']['develop'] = xdevelop
```

And adding the right file after that, seem work for me with proposed fixes.

**Comment by gforsyth** [comment]
I believe this is available as the `default` theme when using the PTK shell
