### ISSUE TITLE
Wrong path completions when filenames have spaces

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1201]
I have a problem with path completion when folders have spaces. 

If I have the following folders: 
'Program Files (x86)'
'Program Files'
ProgramData

if I type: 
```
snail@sea C:\ $ cd Prog<Tab>
``` 
It only gives me `ProgramData`

If I instead start with a quote. It gives me all completions.
```
snail@sea C:\ $ cd "Prog<Tab>
```

**Comment by laerus** [comment]
can you please add the output of `xonfig` ?

**Comment by melund** [comment]
Sorry about that. I am the current master. 

```
+------------------+----------------+
| xonsh            | 0.3.4          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | False          |
| on linux         | False          |
| on darwin        | False          |
| on windows       | True           |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+

$ completer list
Registered Completer Functions:
python_mode : Python-mode completions for @( and ${
       base : If the line is empty, complete based on valid commands, python names, and paths.
              If we are completing the first argument, complete based on valid
              commands and python names.
       skip : Skip over several tokens (e.g., sudo) and complete based on the rest of the
              line.
         cd : Completion for "cd", includes only valid directory names.
      rmdir : Completion for "rmdir", includes only valid directory names.
       bash : Completes based on results from BASH completion.
        man : Completes an option name, based on the contents of the associated man page.
     import : Completes module names and contents for "import ..." and "from ... import ..."
     python : Completes based on the contents of the current Python environment, the Python
              built-ins, and xonsh operators.
       path : Completes based on a path name.
```

**Comment by melund** [comment]
@laerus : Were you not able to reproduce?

**Comment by laerus** [comment]
yes, i can confirm this.

**Comment by adqm** [comment]
Yeah, I wonder if this is a result of #1167.  I didn't implement the quoting of paths there.  If you turn off `$SUBSEQUENCE_PATH_COMPLETION` and `$FUZZY_PATH_COMPLETION`, do you still see this problem?

**Comment by laerus** [comment]
yes it still needs the quote in order to complete pathnames containing space

**Comment by adqm** [comment]
okay, i will try to take a look later today

**Comment by adqm** [comment]
Looking into this, it  seems to me like this might be a prompt_toolkit issue.  It really looks to me like we are sending the right completions to PTK in the case you mentioned, but only the one without spaces is being shown in the result (perhaps because they don't have the same prefix?).

Maybe ptk updated their completer recently?  It sure seems like this used to work...

**Comment by melund** [comment]
@adqm. You are right. I also remember that this used to work.

I just added a print statement to test this. And the path completer do return all the right entries. 

![image](https://cloud.githubusercontent.com/assets/1038978/15999204/3d2a2a70-3144-11e6-9fd9-6b0139049db5.png)

I will open a bug report on PromptToolkit tonight if no-one beats me to it.

**Comment by gforsyth** [comment]
This is fixed for me on prompt_toolkit master -- can anyone else confirm?

**Comment by melund** [comment]
I don't seem to be fixed for me. Maybe my setup is screwed up.

**Comment by gforsyth** [comment]
Hey @melund -- sorry, I completely misunderstood before.  
On prompt_toolkit 1.0.0 it would complete paths with spaces but wouldn't quote them, making them unusable.  That's no longer the case, but I also don't see paths with spaces in the list of autocompletion results.

**Comment by melund** [comment]
This has been fixed
