### ISSUE TITLE
Branch labels disappear after some time

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1203]
The new timeout for the branch labels (https://github.com/xonsh/xonsh/pull/1166) seems to have a bug in my system. 

Sometimes the label completely disappears. Do anyone else experience this weird bug?

It doesn't happen if I set `$VC_BRANCH_TIMEOUT` to a high value from the beginning of a session. 

But if I don't and the branch label disappear, there is no way to make it start working again. Even setting `$VC_BRANCH_TIMEOUT = 100` has no effect. 

I am on master: 
```
$ xonfig
+------------------+----------------+
| xonsh            | 0.3.4          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | False          |
| on linux         | False          |
| on darwin        | False          |
| on windows       | True           |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
```

**Comment by melund** [comment]
We really ought to have a logging system in place :) I will add something temporary to see if I can figure out what is going on here

**Comment by melund** [comment]
@scopatz  It is `cmds.lazyin('git') or cmds.lazylen() == 0` which evaluates False when the branch labels disappear:  https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py#L927

In my case the `cmds.lazylen()` is 1184 and `cmds.lazyin('git')` is False. 

Does it give you any clues?

**Comment by scopatz** [comment]
Ahh, yes.  Why is `cmds.lazyin('git')` False? Do you not have git in your PATH?

**Comment by adqm** [comment]
but it must be hitting true some other times, else @melund wouldn't _ever_ see the branch name, right?

@melund, does it come and go?  and does the result of `cmds.lazyin('git')` change values?

**Comment by scopatz** [comment]
Well, no, if cmds.lazylen() is zero, then it just goes ahead and tries it, because it doesn't want to wait for command names to be loaded.  Command names are then loaded whenever someone calls the completer for the first time, at which point the length is no longer zero.

What is weird is that *it works* even though git isn't on the PATH.

**Comment by melund** [comment]
Ohh..No git not on my PATH. GitForWindows doesn't add itself to the path by default  And I have been trying to use default as much as possible lately. 

The reason the completer works is here: 
https://github.com/xonsh/xonsh/blob/master/xonsh/platform.py#L191
We find the GItForWindows install in the Registry, and then use full path directly in the bash completer. 

I don't know if this explains it. It usually works for a while before it suddenly stops. I don't know what is causing it. I thought it was a time-out. Because if I set the time-out to a high value at the beginning of a session I can't seem to trigger the error.

**Comment by melund** [comment]
Oh. Wait. Git is on my path. it was bash bineary I meant.

**Comment by melund** [comment]
Can a timeout cause the executable to be removed from the cashe?

**Comment by scopatz** [comment]
I don't think so, unless you happen to modify the PATH in some way.  Sometimes a timeout can leave a dangling git lock file, but that only exists in the `.git` directory, which is presumably not on your PATH.

**Comment by melund** [comment]
I haven't seen this for some time, and since the command cache has canged a lot: I am just going to close it.

**Comment by scopatz** [comment]
I think we bumped the timeout to make it so that this doesn't happen except very rarely.
