### ISSUE TITLE
try/except around `source` call seems not to work

### ISSUE THREAD

**Issue by adqm** [xonsh/xonsh#1206]
I noticed this when working on the updates to the xonsh bot:
```
hartz@debian ~ $ try:
................     source nonexistent
................ except:
................     pass
................
TypeError: invalid file: None
```

That exception seems not to be caught by the `try`/`except`.  Maybe this is true of aliases in general?

**Comment by scopatz** [comment]
In a script (or on the command line) I think that the right way to handle this is to set `$RAISE_SUBPROC_ERROR` http://xon.sh/envvars.html#raise-subproc-error

**Comment by adqm** [comment]
Ah, right!  Duh!
