### ISSUE TITLE
Make history expansion happen earlier

### ISSUE THREAD

**Issue by matletix** [xonsh/xonsh#1221]
Xonsh introduces the `!n` and `!!` aliases to execute previous commands.
In bash, those history expansions are among the first to execute making it possible to use them inside of expressions.
Here is an example of command that execute the previous command with elevated privilege in bash and that fail in xonsh : `sudo !!`

It would be nice to make history expansion happen early in xonsh too.

**Comment by scopatz** [comment]
Thanks for reporting @matletix!

**Comment by gforsyth** [comment]
`sudo !!` is now available using the `bashisms` xontrib.  Just put `xontrib load bashisms` in your `xonshrc` and you should be good to go.
