### ISSUE TITLE
Fish like colorful text

### ISSUE THREAD

**Issue by minecraft2048** [xonsh/xonsh#1225]
I think it will be very nice if xonsh supports this kind of colorful text in command like in fish:
![one three terminal to rule them all - fish -home-feanor_006](https://cloud.githubusercontent.com/assets/2445636/16030393/b9bff908-321a-11e6-8b60-d63994364445.png)
unlike current white only text in xonsh:
![one three terminal to rule them all - feanor silmaril xonsh_007](https://cloud.githubusercontent.com/assets/2445636/16030408/d4fe332e-321a-11e6-9cba-95c4d0a32523.png)

**Comment by scopatz** [comment]
Hi @minecraft2048 - we do support this, but you need to use the promtp-toolkit, rather than  the readline, backend.

**Comment by minecraft2048** [comment]
How do I use that prompt-toolkit instead of readline?

**Comment by scopatz** [comment]
Prompt-toolkit should be used automatically, if you have it installed.  You can check by running the `xonfig` command.

**Comment by scopatz** [comment]
We should have better docs on this.... Sorry!

**Comment by minecraft2048** [comment]
Crash warning: Apparently xonsh with prompt-toolkit requires pygments as dependency, but `pip3 install prompt-toolkit` doesn't install pygments, so xonsh crashes with this:

```
feanor@silmaril ~> xonsh
/usr/local/lib/python3.5/dist-packages/xonsh/xontribs.py:32: ImportWarning: could not find xontrib module 'prompt_ret_code'
  warn('could not find xontrib module {0!r}'.format(name), ImportWarning)
/usr/local/lib/python3.5/dist-packages/xonsh/xontribs.py:32: ImportWarning: could not find xontrib module 'xo'
  warn('could not find xontrib module {0!r}'.format(name), ImportWarning)
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.4', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 236, in main
    args = premain(argv)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 223, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/shell.py", line 67, in __init__
    from xonsh.ptk.shell import PromptToolkitShell as shell_class
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ptk/shell.py", line 11, in <module>
    from pygments.styles import get_all_styles
ImportError: No module named 'pygments'
```
Now how do I customize the text colors so it looks like fish?

**Comment by santagada** [comment]
you can look at the current colors with:
`xonfig colors`
and see the style options with:
`xonfig styles`
and setting a style with:
`$XONSH_COLOR_STYLE = 'native'`

**Comment by Siecje** [comment]
@minecraft2048 You also have to install ```pygments```. ```pip install pygments```

**Comment by adqm** [comment]
> I think I remember having that in xonsh but I can't seem to get it.

I don't think we ever had that in xonsh.  I do think it would be nice, but it would require some tricky work in the pygments parser to get this kind of syntax highlighting while still retaining the nice syntax highlighting it has for Python...

**Comment by matheus2740** [comment]
> I think I remember having that in xonsh but I can't seem to get it.
+1 to that. Currently the only feature preventing me from switching completely to xonsh (yes, fish spoiled me hard).

**Comment by matheus2740** [comment]
> Hi @minecraft2048 - we do support this, but you need to use the promtp-toolkit, rather than the readline, backend.

@scopatz , I think what OP meant was coloring available commands blue and 'wrong' commands red

**Comment by scopatz** [comment]
Oh, I see.  Well PRs welcome.  I don't think it would b e too hard to look up the first token in the commands cache if it exists...

**Comment by santagada** [comment]
I found documentation on the CommandsCache but couldn't figure out how to change xonsh lexer to implement this, because its not only first command, its everywhere a command can be eg(in fish):
echo (ls)

both get red/blue as you type. But even for starters I couldn't figure out how to run a function during lexing.

**Comment by gforsyth** [comment]
I'm going to go ahead and close this.  We have syntax highlighting and also recently added in support for valid command syntax highlighting.  The pygments installation issue is duplicated in several other places.

**Comment by Surferlul** [comment]
Maybe this is useful for someone: I had everything installed, but it didn't work until I updated my packages
