### ISSUE TITLE
Can't get base16-shell working

### ISSUE THREAD

**Issue by eliangcs** [xonsh/xonsh#1228]
xonsh is awesome, but there's one thing keeping me from actually switching to it from zsh -- I can't get my color settings working properly. I use base16 color scheme with iTerm2 on Mac. Please refer to:
- https://github.com/chriskempson/base16
- https://github.com/chriskempson/base16-shell
- https://github.com/chriskempson/base16-iterm2

This is my ~/.xonshrc:

```
import os

# Base16 Shell
$BASE16_SHELL = os.path.join($HOME, ".config/base16-shell/base16-tomorrow.dark.sh")
source-bash $BASE16_SHELL
```

On my iTerm2, the following color preset is imported:

https://github.com/chriskempson/base16-iterm2/blob/master/base16-tomorrow.dark.256.itermcolors

When I run `colortest` script of base16-shell in xonsh, I got the following. The blue colors suggest base16-shell is not working.

<img width="566" alt="screen shot 2016-06-14 at 4 11 00 pm" src="https://cloud.githubusercontent.com/assets/740461/16035621/a295ae00-324a-11e6-8649-cfd38cf415dd.png">

Running it in zsh using the same setup gives me the correct result:

<img width="565" alt="screen shot 2016-06-14 at 4 12 15 pm" src="https://cloud.githubusercontent.com/assets/740461/16035664/e4293cba-324a-11e6-9aac-eeba053aed3a.png">

I'm not sure if it's issue of xonsh or base16-shell. Any hints are appreciated.

**Comment by laerus** [comment]
can you try `xonfig colors` and see if you get the colors right from sourcing the base-16 script?

**Comment by eliangcs** [comment]
@laerus `xonfig colors` looks right:

<img width="712" alt="screen shot 2016-06-14 at 6 20 00 pm" src="https://cloud.githubusercontent.com/assets/740461/16039477/a8e61d46-325c-11e6-9d06-32906685e68a.png">

**Comment by laerus** [comment]
actually sourcing the base16 script doesn't change colors for me

**Comment by laerus** [comment]
a temporary workaround adding in .xonshrc `$[bash -c  'source base16-tomorrow.dark.sh']`

**Comment by eliangcs** [comment]
The workaround works. Thanks!

**Comment by scopatz** [comment]
Can you instead run `source-bash base16-tomorrow.dark.sh` in your xonshrc?

**Comment by scopatz** [comment]
Also, please add a note about this to the Mac OSX docs!  That way we can point people to it in the future.

**Comment by eliangcs** [comment]
`source-bash base16-tomorrow.dark.sh` doesn't work for me, but `$[bash -c 'source base16-tomorrow.dark.sh']` does.

**Comment by laerus** [comment]
these base-16 scripts use escape codes and printf to change the colors which is kinda dirty and not always working, if i switch focus from my terminal, colors get reset, buts thats prolly a terminator thingy.

**Comment by scopatz** [comment]
@eliangcs what is the error message that  you see with source-bash?

**Comment by laerus** [comment]
iirc there is no error message, colours just don't change

**Comment by scopatz** [comment]
Ahh strange.

**Comment by eliangcs** [comment]
Yeah, no error message with source-bash.

**Comment by scopatz** [comment]
Well I think some documentation on this in the OSX guide, http://xon.sh/osx.html, would still be very helpful if one of you would be interested and willing!

**Comment by ErickTucto** [comment]
Hello, You can use this alias
```python
def base16(arg):
    # Helpers
    def s(cmd):
        return cmd.strip('\n') if type(cmd) is str else cmd

    def l(cmd):
        return cmd.split("\n")[:-1] if type(cmd) is str else cmd

    def all_themes():
        for theme in l(s($(ls -1 $BASE16_SHELL/scripts))):
            yield theme[7:-3]

    # Declaration of variables
    if not arg:
        return 'Dont select theme. Write \033[0;32mlist\033[0;0m to list the themes.'
    theme = arg[0]
    if (theme == 'list'):
        themes = [theme for theme in all_themes()]
        return '\n'.join(themes)
    script = $BASE16_SHELL + "scripts/base16-" + theme + ".sh"

    # Checking if exist theme
    if (isfile(script)):
        bash @(script)
        ln -fs @(script) ~/.base16_theme
        $BASE16_THEME = theme
        template = f"if !exists('g:colors_name') || g:colors_name != 'base16-{theme}'\n  colorscheme base16-{theme}\nendif"
        echo -e @(template) > ~/.vimrc_background
        return True
    else:
        print("Not exists theme.")
        return False
    # TODO: Terminate Hooks
    # code ...


aliases['base16'] = base16
```
link to [gist](https://gist.github.com/ErickTucto/0bac5d7ac5ed4b677e471ac6a1358bb0/c8d9e336e580473e157724c7111dc6c04f943f6c)

**Comment by scopatz** [comment]
Amazing @ErickTucto! Is this something that should be in xonsh by default or as a xontrib? Happy to have a PR for this!

**Comment by ErickTucto** [comment]
@scopatz this code must be on `~/.xonshrc` or install my extension *xontrib-base16-shell*, [click here](https://github.com/ErickTucto/xontrib-base16-shell)

**Comment by gforsyth** [comment]
Closing this out -- thanks so much for wrapping this up in a xontrib, @ErickTucto !
