### ISSUE TITLE
Implement VIRTUAL_ENV_DISABLE_PROMPT or something covering the same use case(s)

### ISSUE THREAD

**Issue by Russell-Jones** [xonsh/xonsh#1229]
See https://virtualenv.pypa.io/en/stable/reference/#configuration

Handy if, e.g. installing and running xonsh in a VE using --system-site-packages. The prompt is displayed by xonsh, so I guess it'd need to be set in environ.py, but I'm not sure whether it would be best as a change to env_name() or to the prompt templates when env['VIRTUAL_ENV_DISABLE_PROMPT'] is set to anything but ''. The original reportedly prevents activate from modifying the shell prompt, but I can't see a direct equivalent to that (xonsh can't parse or do clever sub-shell things with bash/zsh/*sh prompt strings can it?).

**Comment by melund** [comment]
The function that sets the environment part of the prompt is here: 
https://github.com/xonsh/xonsh/blob/3d9e844f55390b1a3cf3898dc47c1d139b4b6ab8/xonsh/environ.py#L1120

I guess it could just check that environement variable exist:
`if builtins.__xonsh_env__.get('VIRTUAL_ENV_DISABLE_PROMPT','') != '':` and then not set the environment prompt.

**Comment by Russell-Jones** [comment]
Yes, but should it do it in the prompt template(s) or in env_name()? Is the output of env_name() exposed anywhere? Perhaps the difference in semantics is sufficient that there should be an xonsh specific env var with the closest functionality available.

**Comment by melund** [comment]
`env_name()` is the functions that provide the environment name that is inserted into the `PROMPT` template. I am not familiar with who Virtualenv works but think this should be enough.

**Comment by gforsyth** [comment]
Question: it seems like `VIRTUAL_ENV_DISABLE_PROMPT` comes into play at the time of env creation, is this the behavior we want to enable?  Or do we want a general blanket "if this env var is set, don't change the prompt"?

**Comment by Russell-Jones** [comment]
@gforsyth It's not at env creation, but at env activation.

**Comment by gforsyth** [comment]
I don't use virtualenv and can't test this right now, but the documentation you linked to in the initial post indicates otherwise: 

>VIRTUAL_ENV_DISABLE_PROMPT
>
 >   Any virtualenv created when this is set to a non-empty value will not have it’s activate script modify the shell prompt.

But I would not be surprised if the docs were out-of-date / incomplete / wrong.

**Comment by Russell-Jones** [comment]
I managed to get the effect I wanted with
```
import os
$FORMATTER_DICT['env_name']=lambda: '' if os.path.basename($VIRTUAL_ENV) == 'myve' else '('+os.path.basename($VIRTUAL_ENV)+')'
```
Though I could have used the even more succinct `$FORMATTER_DICT['env_name']=''`
I've put this in ~/.xonshrc and it works fine AFAIAC (I might add sys and a few others there too), so closing.
