### ISSUE TITLE
crashing xonsh with argparse

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1235]
```
import argparse
import sys
p = argparse.ArgumentParser()
p.parse_args(sys.argv) # argv instead of argv[1:]
```

the default Python REPL crashes too but IPython gets away with this
i think ArgumentParser throws a SystemExit (arggggh!)

**Comment by santagada** [comment]
```
~ $ import argparse
... import sys
... p = argparse.ArgumentParser()
... try:
...   p.parse_args(sys.argv) # argv instead of argv[1:]
... except:
...   import traceback
...   traceback.print_exc()
...
...
usage: xonsh [-h]
xonsh: error: unrecognized arguments: /usr/local/bin/xonsh
Traceback (most recent call last):
  File "<xonsh-code>", line 5, in <module>
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1729, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 2385, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 2372, in exit
    _sys.exit(status)
SystemExit: 2
```

so apparently it does raise a SystemExit. I would look at what ipython does in this case but maybe exiting is not so bad. if I type exit in a shell it will terminate.

**Comment by adqm** [comment]
We ignore `KeyboardInterrupt` in the shell, so maybe we could just ignore `SystemExit` as well?  Not sure right away what unintended side effects that might have...

**Comment by scopatz** [comment]
I would say that this is known annoyance.  It should probably be fixed so that running scripts from xonsh can just use sys.argv, rather than sys.argv[1:]  Though it should be noted that you can use the $ARGS and $ARG1, $ARG2, ... variables http://xon.sh/tutorial.html#executing-commands-and-scripts.

Happy to have a PR that fixes it, since I haven't gotten to it in a year :)

**Comment by scopatz** [comment]
Please see #2249 for a potential fix. I'll also note that we already catch SystemExit for callable aliases for exactly the argparse reason. I don't think the unintended consequences are bad, even if they exist.

**Comment by melund** [comment]
#2249 seems to work for me. So I will close this. Feel free to open if there are other issues.
