### ISSUE TITLE
the line wrapps at 80 chars in mintty

### ISSUE THREAD

**Issue by vmiheer** [xonsh/xonsh#1236]
for long commands the line is wrapped this happens in mintty cygwin.
![1](https://cloud.githubusercontent.com/assets/535650/16072422/6c64a4a8-32fe-11e6-82e4-6721e1888b8f.png)
![2](https://cloud.githubusercontent.com/assets/535650/16072428/72861fd8-32fe-11e6-84b6-82a8d8db10d0.png)
![3](https://cloud.githubusercontent.com/assets/535650/16072434/76ddd396-32fe-11e6-8bc8-7b5db06d59d8.PNG)

**Comment by vmiheer** [comment]
This doesn't happens in zsh in same terminal
![4](https://cloud.githubusercontent.com/assets/535650/16072476/b53c59be-32fe-11e6-8bfe-e7ec2a17f76d.PNG)

**Comment by melund** [comment]
Doesn't happen in the default windows terminal either.

What is the output of:
```
snail@sea ~ $ import shutil
snail@sea ~ $ shutil.get_terminal_size()
os.terminal_size(columns=153, lines=12)
```

**Comment by melund** [comment]
Just tried with `mintty` that comes with GitForWindows. 

`start C:\Program Files\Git\usr\bin\mintty.exe C:\Users\user\Anaconda3\Scripts\xonsh.exe`

Here I don't see the problem.

**Comment by vmiheer** [comment]
mvaidya@MVAIDYA-LT ~ $ shutil.get_terminal_size()
os.terminal_size(columns=189, lines=56)

Here is my mintty version:
mintty 2.3.7 (x86_64-pc-cygwin)
(C) 2013/2016 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.

**Comment by scopatz** [comment]
@vmiheer - what is the output of your `xonfig` command?

**Comment by vmiheer** [comment]
```
mvaidya@MVAIDYA-LT ~ $ xonfig
+------------------+----------+
| xonsh            | 0.3.4    |
| Python           | 3.4.3    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | False    |
| on darwin        | False    |
| on windows       | False    |
| on cygwin        | True     |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+
```

**Comment by scopatz** [comment]
This is probably because you are using readline and you are on windows.  Could you please install prompt-toolkit and see if this issue remains? http://xon.sh/windows.html#installation

**Comment by vmiheer** [comment]
That works, thank you so much. closing.
