### ISSUE TITLE
Pressing v in vi-mode opens nano text editor

### ISSUE THREAD

**Issue by Melonel** [xonsh/xonsh#1237]
Hello,

There's an issue that's been bugging me and I have not been able to figure out where it comes from.

While using the vi-mode with the prompt toolkit, pressing the key v (in the normal mode) launches the nano text editor with the current input, instead of starting the visual selection as expected. 

Pressing V visually selects the whole line as expected and pressing ctrl-v selects a visual block. 

Thanks for the help.

**Comment by laerus** [comment]
this ptk setting comes from xonsh/ptk/shell.py its called `enable_open_in_editor` to the ptk KeyBindingManager, and its hardcoded to True.

**Comment by Melonel** [comment]
Does it also exist in the emacs mode? I don't understand the point in vi-mode, and why the key v is chosen.

**Comment by Melonel** [comment]
Ok, it is a choice done in prompt toolkit. Is there a way to disable this option manually? I find this option very unintuitive for vi-mode users.

**Comment by laerus** [comment]
no sure about emacs, the 'v' binding is what the old readline lib uses for opening the editor, also note that readline doesn't have visual mode.

atm i don't see any way to disable this option rather than changing the source

**Comment by Melonel** [comment]
Ok, thanks. It was not the behavior I was used to in the command-line prompts I have used.

**Comment by laerus** [comment]
what other prompt tools have you used? prompt_toolkit is optional for xonsh and maybe support for other readline-like tools will be added.

**Comment by Melonel** [comment]
I was using vi-mode on zsh for a long time. It does not have this open-editor option by default.

**Comment by laerus** [comment]
apparently zsh doesn't use readline (like bash, bleh), it uses its own zle which has visual mode (very cool)
xonsh can add support for zle at some point

**Comment by gforsyth** [comment]
Thanks for reporting @Melonel -- in emacs mode (where this is obviously more useful), it's `Ctrl-X Ctrl-E` to open up the editor.  I wasn't aware that it also bound `v` in vi-mode which does seem a little weird.

**Comment by gforsyth** [comment]
Ok -- I think that it's fine to preserve expected vim-like behavior here even with `open-in-editor` enabled.  The emacs binding still works in vi-mode, so I'll change the `v` key to enter character selection mode instead of opening the editor.

**Comment by gforsyth** [comment]
Hi @Melonel -- I just put in #1239 with `v` enabling character selection if you want to give it a whirl.  You can still open in an external editor using the emacs binding `Ctrl-X Ctrl-E`

**Comment by Melonel** [comment]
Ok, my bad. It's `Ctrl-X` then `Ctrl-E`, not one or the other.

**Comment by scopatz** [comment]
Also, I would imagine that you can select which editor is launched via `$EDITOR = '/my/editor'`

**Comment by aashiksamuel** [comment]
Change the environment variable $VISUAL to vi and put this in your .bashrc or zshrc
@scopatz You are right , I faced the similar problem and I had vi in $EDITOR but editing $VISUAL fixed it. I guess $EDITOR corresponds to gui editor and for CLI $VISUAL is used. 


`export VISUAL=vim`

**Comment by ianchanning** [comment]
I believe this is relevant too - it happens in normal bash https://stackoverflow.com/questions/16995399/opening-editor-while-the-edit-mode-is-vi-in-readline
