### ISSUE TITLE
AttributeError: 'Env' object has no attribute 'docs'

### ISSUE THREAD

**Issue by sheridp** [xonsh/xonsh#1241]
When starting xonsh, I get the following:

No readline implementation available.  Skipping setup.
Could not find xonsh configuration or run control files.
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.4', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 240, in main
    xonfig.main(['wizard', '--confirm'])
  File "/usr/local/lib/python3.5/site-packages/xonsh/xonfig.py", line 468, in main
    return _MAIN_ACTIONS[ns.action](ns)
  File "/usr/local/lib/python3.5/site-packages/xonsh/xonfig.py", line 294, in _wizard
    wiz = make_wizard(default_file=fname, confirm=ns.confirm)
  File "/usr/local/lib/python3.5/site-packages/xonsh/xonfig.py", line 272, in make_wizard
    YesNo(question=WIZARD_ENV_QUESTION, yes=make_env(), no=Pass()),
  File "/usr/local/lib/python3.5/site-packages/xonsh/xonfig.py", line 209, in make_env
    w = _make_flat_wiz(make_envvar, sorted(builtins.__xonsh_env__.docs.keys()))
AttributeError: 'Env' object has no attribute 'docs'

CentOS Linux release 7.2.1511 (Core)
Kernel 3.10.0-327.el7.x86_64
Python 3.5.1

Not sure if important, but my /usr/bin/python points to python2, and I have created a symlink /usr/bin/python3 ->  /usr/local/bin/python3.5.   Xonsh was installed with python3 setup.py install.

**Comment by gforsyth** [comment]
Hey @sheridp -- thanks for reporting!  You are on latest master, yes?  I'm pretty sure that this is due to #1231 which I merged in yesterday (mea culpa). 

If you are on master, reverting to 0.3.4 should solve this.  In any case, could you post the output of `xonfig`?

**Comment by gforsyth** [comment]
FIx incoming

**Comment by gforsyth** [comment]
Hey @sheridp , would you mind trying out #1242 and seeing if it solves your problem?  Thanks!

**Comment by sheridp** [comment]
Sure. I am on the latest master:  916dc2a6d474dd2b0c4bb11303e1639132e0a4a3.  I'll try 1242 now.

Not sure how to run xonfig.  I see that it's a .py in the build directory, but running gives:

python3 xonfig.py

Traceback (most recent call last):
  File "xonfig.py", line 2, in <module>
    import ast
  File "/root/xonsh/xonsh/ast.py", line 5, in <module>
    from ast import Module, Num, Expr, Str, Bytes, UnaryOp, UAdd, USub, Invert, \

**Comment by gforsyth** [comment]
Once xonsh starts up you can just run `xonfig` at the command line

**Comment by sheridp** [comment]
Just did a git pull to c0d489013aa88109265f240a36e153818b3a21ac, and it seems to have resolved this issue.  I am still getting the following error:

No readline implementation available.  Skipping setup.
Could not find xonsh configuration or run control files.
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
UnboundLocalError: local variable 'readline' referenced before assignment

**Comment by gforsyth** [comment]
Are you on OSX?

**Comment by sheridp** [comment]
Centos 7.2

**Comment by gforsyth** [comment]
Well, there goes that theory...

That's strange, I'm not sure why you don't have readline available, but if you want to get up and running, you can install `prompt_toolkit` using `pip install prompt_toolkit` (although make sure you use the version of `pip` that corresponds to your python3.5 install

**Comment by gforsyth** [comment]
If you want to get readline mode working correctly, you can start by running the python interpreter and trying an `import readline` and reporting back whatever error it throws

**Comment by sheridp** [comment]
Installed prompt_toolkit (and pygments) and it now seems to be working.

**Comment by gforsyth** [comment]
Great!  Feel free to close this, or we can try to sort out readline.
