### ISSUE TITLE
single dot in cli throwing wrong error

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1243]
when typing just a single dot '.' with `$AUTO_CD = False` i get
`xonsh: subprocess mode: permission denied: .`

```
$ which .
. not in $PATH or xonsh.builtins.aliases
```

**Comment by gforsyth** [comment]
Thanks for reporting, @laerus !

**Comment by adqm** [comment]
Hi @laerus,  Just out of curiosity: what kind of error message would you expect here?

In fact, what we are seeing here is the error I would expect (since this will try to execute the current directory `.` and not be able to).

One way to get around this would be to implement a `.` builtin (similar to what bash has) so that `.` is actually a valid command.

**Comment by santagada** [comment]
are you saying you want . to be aliased to source like in bash and zsh? I think that is a terrible feature, but we could do like fish and print "source: '.' command is deprecated, and doesn't work with STDIN anymore. Did you mean 'source' or './'?"

**Comment by adqm** [comment]
I'm not trying to say anything about what I want, but rather just trying to figure out what a better message would be (if there is one) and how we could make that happen.

**Comment by laerus** [comment]
What does it actually mean to execute a directory? (i think this is very obscure in python please help out!)

searching through cpython to find out why `subprocess.call(['.'])` raises a `PermissionError: [Errno 13] Permission denied` the only thing i could find is that `execve` raises  the EACCES  error that could mean one of (from execve man page):


> EACCES    Search permission is denied on a component of the path prefix of
>                   filename or  the  name  of  a  script  interpreter.
> 
> EACCES    The file or a script interpreter is not a regular file.
> 
> EACCES    Execute  permission  is  denied  for the file or a script or ELF
>                   interpreter.
> 
> EACCES    The filesystem is mounted noexec.

at this point i'm really confused cause 3 out of 4 cases have to do with permissions and one with the type of the file, if _i couldn't refuse the temptation_ i would guess that the second one is our case (?)


bash throws a rather more explicit error

```
> exec .
bash: exec: .: cannot execute: Is a directory
```

```
> ./
bash: ./: Is a directory
```

in xonsh if $AUTO_CD is True then you kinda actually 'execute' the directory as in get the contents etc. (kudos btw for the AUTO_CD concept, very cool)

if $AUTO_CD is False then maybe a command not found would be more appropriate or an error that points that 'you can't execute a directory you may like turning $AUTO_CD on' or something

**Comment by PaulReiber** [comment]
Happy to share an idea I implemented in tcsh some years back.

Sure, (as implemented w/ $AUTO_CD) if the end user types in a directory
name, one good option is to "cd" there.  Another option is to have a
dictionary of (directory, commands) - the directory is the key, the
commands to run are the value.

What I build using tcsh scripting combined these ideas - the shell would
auto-cd to the directory, then run whatever commands it found in that
associative array right away for me.

Examples (somewhat contrived) of directory->command mappings:

/home/paul => ls -lart
/home => who
/ => uptime
/proc => pstree -paul
/var/www => service apache status


So... answering "What does it actually mean to execute a directory?" - it
can mean whatever the shell makes it mean.

Possibly xonsh could provide a means of running either a snippet of python
code, or a subprocess pipeline (or both?) in this case.

My implementation in tcsh would chdir to the directory first, then run the
commands, then provide an interactive prompt.  I haven't given too much
thought to the pros and cons of having AUTO_CD and AUTO_COMMANDS (just made
that name up) be independent of each other.

While I think it'd be kind of intuitive/expected that the commands would
run with a CWD of the named directory, possibly there's value in having
them run in ~ if AUTO_CD is false.

Final note - what I implemented resolved relative paths first.  By that I
mean, the dictionary keys were fully qualified directory names, starting
with a /   When the user typed in "."  or ".." or "../whatever" (or "~")
 the first step was to get the full pathname for the directory, and then
that full pathname was what was used as the key into the dictionary, not
the shorthand which had been typed at the commandline.

Hope this makes sense, and hope it gets some gears turning regarding how
xonsh might respond when asked to execute directories.


Kind regards,
-Paul Reiber
Phone: (650)430-7926
Email: paul@reiber.org
Web: http://bit.ly/reiber

**Comment by scopatz** [comment]
I would definitely be in favor of something along the lines of 'permission denied: is a directory'. If someone could put in a PR with this fix that would be amazing!

**Comment by scopatz** [comment]
@PaulReiber - I believe that xonsh can already perform the basics of what you are asking for. If you use a directory name as an alias, you are then able to 'execute' that directory.  For example, 

```console
scopatz@artemis ~ $ aliases['/home'] = 'echo sham wow'
scopatz@artemis ~ $ /home
sham wow
```

Perhaps there was something more to your suggestion? I believe this is basically the same idea though.

**Comment by PaulReiber** [comment]
Hi Anthony,

It's somewhat different than just an array of aliases.

if you were in /home/anthony and you did a "cd .." ...would your aliases
mechanism end up echoing "sham wow" even though the /home command was never
run?  My solution handled that - if/when your shell entered a directory
where there commands to do, it did them.
If I was in /home/paul and I did "cd ../.." it ran whatever commands were
appropriate to run for "/".

Question... if instead of "sham wow" what occurs if/when you echo `pwd` or
$CWD or better still, the output of "readink -f ." ?

Really happy to see xonsh coming together into an interesting tool! Thanks
for all your hard work!

Kind regards,
-Paul Reiber
Phone: (650)430-7926
Email: paul@reiber.org
Web: http://bit.ly/reiber

**Comment by scopatz** [comment]
Ahh I see, we don't really have a post-cd mechanism.  Though this wouldn't be hard to build.  One would simply have to 

```python
from xonsh.dirstack import cd

def post_cd(args, stdin=None):
    rtn = cd(args, stdin=stdin)
    # run post hook
    return rtn

aliases['cd'] = post_cd
```

I'd be interested in having official support for something like this is if someone wanted to put in a PR :)

**Comment by PaulReiber** [comment]
Hi Anthony,

I'm almost certain the below won't work exactly as coded, but I'm
hopeful as pseudocode it might be a sufficient spec to work from.

from xonsh.dirstack import cd

def post_cd(args, stdin=None):
    rtn = cd(args, stdin=stdin)       if rtn && post_cd_hooks[$CWD]
eval post_cd_hooks[$CWD]       return rtn

aliases['cd'] = post_cd

...that's more or less what was at the heart of what I'd built using
tcsh's capabilities.
-Paul

**Comment by scopatz** [comment]
Sure thing @PaulReiber. If someone wants to add something like this, I think we'd be happy to have it.

**Comment by PaulReiber** [comment]
I've been looking into what changes would be needed to implement a post-cd-commands mechanism in xonsh.

I like the idea of having a dictionary with a fully qualified directory as the key, and activities to do in that directory as the value. 

From what I've determined something could quite handily be added in dirstack.py at the end of  _change_working_directory() that would action whatever post-cd commands are in that dictionary for the particular current-working-directory.

I'm still pondering how best to give the end user access to the dictionary - input's welcome.

**Comment by PaulReiber** [comment]
One thought....  let's say the new post-cd activity stuff is toggled via AUTO_ACT.
If AUTO_CD's off, and AUTO_ACT is on, possibly naming the directory at the commandline would initiate an interaction with the user:

xonsh-prompt>   /etc
What would you like to automatically run when you cd to /etc?
(user types in:  "pstree -paul")
Post-CD activity for /etc/ set to:  pstree -paul
xonsh-prompt>

**Comment by scopatz** [comment]
Hi @PaulReiber, thanks for tackling this!

> I like the idea of having a dictionary with a fully qualified directory as the key, and activities to do in that directory as the value.

I think this is the right model.

> let's say the new post-cd activity stuff is toggled via AUTO_AC

I think this would be best as a builtin (like aliases or history) rather than an envvar.  I don't think this is the sort of thing that would ever get transferred down to a subshell.  

I would be tempted to call this `__xonsh_cd_actions__`. It wouldn't even necessarily exist unless someone wanted this feature.

**Comment by PaulReiber** [comment]
Anthony,

> I think this is the right model.
Awesome! I'm glad I'm on the right track.

> I think this would be best as a builtin (like aliases or history) rather
than an envvar
> I would be tempted to call this __xonsh_cd_actions__. It wouldn't even
necessarily exist unless someone wanted this feature.

That sounds right to me, interface-wise. I'll take a look at what it'll
take to do that way.

In the interim, Anthony (and generally, to the list) if there's any
additional advice/approach you'd like to provide, I'm all ears.

Thanks!

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
I am going to close this issue since it is not clear what is left to be done here. Please feel free to reopen if needed. In this particular case, I'd recommend a new, more targeted issue though. Thanks!
