### ISSUE TITLE
bleeding edge version needs dirty version number

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#1248]
To avoid confusion, the version of  `xonsh` offered at the conda channel
```bash
xonsh/channel/dev
```
should get a dirty version number, maybe adding simply `dev`[counter] or something like that.
Currently, it says 0.3.4 while @scopatz has confirmed that that is not correct and that that package actually is newer (I guess GH master?).
Maybe setuptools_scm or similar stuff could be used to create a dirty version tag?

**Comment by melund** [comment]
For the conda packages the build number indicates the number of commits since the last release. I agree we need this in the xonsh as well. I would be nice to see something like that when running `xonfig`.

**Comment by scopatz** [comment]
+1 to these!

**Comment by gforsyth** [comment]
This now works for people installing via `setup.py` or `pip`.  `conda` will require a separate solution (I think)

**Comment by gforsyth** [comment]
wait, nevermind!  I think it just works, since `conda build` runs `setup.py`.  I just compiled a conda package locally, installed it into a clean environment and I have a git sha and dev version number in my `xonfig`.  

@melund -- is there anything extra that needs to happen to make this work with the dev channel?

**Comment by gforsyth** [comment]
ok, confirmed -- it's already working!

**Comment by scopatz** [comment]
@gforsyth - yeah, this will totally work if you conda build locally.  The problem is building on conda-forge (and maybe the dev channel).  conda-forge specifically does not have access to the repo.

**Comment by gforsyth** [comment]
I just installed from the dev channel and it's already showing me a SHA and a devN suffix on the version.  So whatever @melund set up just ran with it.  conda-forge won't work, agreed, but that shouldn't be a problem really, right?  Given that it's just serving up "full" releases?

**Comment by scopatz** [comment]
Ahh great news about the dev channel! And yeah, that is right about conda-forge that it isn't a big problem
