### ISSUE TITLE
Getting return code from last run command

### ISSUE THREAD

**Issue by ns-phennessy** [xonsh/xonsh#1251]
i understand that doing something like `!(ls foo).returncode` will give me the return code i'm interested in.

Bash offers the `$?` variable to get return code of the last run command; do we have an equivalent of this in xonsh?

**Comment by gforsyth** [comment]
Hey @ns-phennessy -- it's not quite as concise, but `__xonsh_history__.rtns[-1]` will show the return code of the most recent command.

**Comment by gforsyth** [comment]
And you could alias that to something shorter, certainly, like 

```console
aliases['lrtn'] = lambda args, stdin=None: '{}\n'.format(__xonsh_history__.rtns[-1])
```

although the alias probably shouldn't contain `$`...

**Comment by melund** [comment]
The shortest version is `_.rtn`

**Comment by gforsyth** [comment]
man, i keep forgetting about that.  thanks, @melund!

**Comment by melund** [comment]
He he. No problem ;)

**Comment by ns-phennessy** [comment]
Perhaps this could be mentioned in the docs?

**Comment by gforsyth** [comment]
Definitely!  It would be right at home in the bash to xonsh translation guide.
http://xon.sh/bash_to_xsh.html

**Comment by scopatz** [comment]
Pull requests always welcome!

**Comment by gforsyth** [comment]
@laerus added this in in #1254 -- closing now (it will show up on the docs page after the next release, which is soon!)
