### ISSUE TITLE
Improvement on handling bash functions

### ISSUE THREAD

**Issue by Cheaterman** [xonsh/xonsh#1263]
Hello buddies, I hope you're all doing good ^__^

I have this snippet on top of my .bashrc (likely many people do):

```
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi
```

But I have functions defined inside of my bashrc below that. When I try to call these functions, xonsh fails with:
`subprocess.CalledProcessError: Command '['bash', '-c', 'source "/home/cheaterman/.bashrc"\ntitle owiii\n']' returned non-zero exit status 127`
Buddy BlaXpirit on IRC helped me pinpoint it to the non-interactive exclusion above, and raised the following question:
`16:52:56 < BlaXpirit> it's strange.  why doesn't xonsh run   `bash -ic 'myfunction'`  instead of  `bash -c 'source ~/.bashrc; myfunction'`?`
In the meantime he fixed my issue by adding && -z $XONSH_INTERACTIVE in the condition above, but maybe it would be nice if xonsh didn't require this?

Thanks in advance for answering this question ^__^ have a good one!

**Comment by scopatz** [comment]
Hi @Cheaterman - thanks for reporting!  Note that this is effectively the same issue as http://xon.sh/linux.html#default-ubuntu-bashrc-breaks-foreign-shell-functions We might want to add some generic text

**Comment by scopatz** [comment]
That being said, if you want to make your bashrc ro zshrc that is sourced at startup run in interactive mode, in the config.json file you simply have to add the `"interactive": true" key to that foreign shell: http://xon.sh/xonshconfig.html#foreign-shells

Alternatively, if you are running from the command line, you just need to add `-i true` to your command, so something like `source-bash -i true file` should work instead.

**Comment by Cheaterman** [comment]
Hi @scopatz and thanks for answering! It might be a good idea to make the default in xonfig wizard have interactive=True so that fewer people stumble upon this issue? It might be worth mentioning this fix in the documentation page that you linked :-) thanks in advance!

**Comment by Cheaterman** [comment]
@scopatz also interactive seems to default to true, and this only applies to initial sourcing, but I'm speaking about using a function defined in bash at runtime after initial sourcing, and the
``` subprocess.CalledProcessError: Command '['bash', '-c', 'source "/home/cheaterman/.bashrc"\ntitle owiii\n']' returned non-zero exit status 127```
is the actual command that xonsh tries to run (title being my function and owiii an example argument)
