### ISSUE TITLE
Document sequence attributes of the history object

### ISSUE THREAD

**Issue by BlaXpirit** [xonsh/xonsh#1275]
```python
self.tss = CommandField('ts', self)
self.inps = CommandField('inp', self)
self.outs = CommandField('out', self)
self.rtns = CommandField('rtn', self)
```

It turns out these are supposed to be the public interface to the history object but they scared me away because they're missing in [the documentation](http://xon.sh/api/history.html#xonsh.history.History)

**Comment by scopatz** [comment]
Thanks for opening this @BlaXpirit!
