### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1287]
I just installed Fedora 24 (Beta) and pulled the latest xonsh changes.
Typing xonsh results in no output for 7 seconds followed by this error message:

foo6[~]:xonsh
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16271, in main
    args = premain(argv)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16258, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16003, in __init__
    kwargs.get('cacheall', False))
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16052, in _init_environ
    xontribs.update_context(name, ctx=self.ctx)
NameError: name 'xontribs' is not defined

I am using Python 3.5.1 compiled with GCC 6.1.1-2

**Comment by melund** [comment]
Hi @mburo . I am not familiar with the your linux install. You could try to nuke your build directory and remove all `__pycache__` files and any old startup scripts. A lot has happend with xonsh lately

**Comment by mburo** [comment]
I cloned xonsh into a fresh directory and installed it again. Same error message.

**Comment by laerus** [comment]
i can confirm in debian-testing too, from current master

**Comment by gforsyth** [comment]
@mburo and @laerus -- can you both please post the contents of `xonfig` and also try running `xonsh` with the `--no-rc` flag?  And @laerus, can you confirm that the traceback also points to the file `amalgam.py`?  
That is a little strange to me, as it is `__amalgam__.py` on my machine, but that may be distro specific.

**Comment by scopatz** [comment]
I have a potential fix for this in #1289, if you'd like to test it out.

**Comment by scopatz** [comment]
Again, mea culpa.  I knew the transition to the amalgamation would be annoying, but I am sorry that there have been so many lingering issues.

**Comment by scopatz** [comment]
Thanks for bearing with us!

**Comment by laerus** [comment]
@gforsyth i was getting the same error but from `__amalgam__.py`

**Comment by mburo** [comment]
fix #1289 seems to work. BTW, the startup time is still a bit long - around 0.6 seconds on my system.

**Comment by scopatz** [comment]
@mburo - what does your xonfig say?  If you are using prompt-toolkit I am not sure how much we can do other than to make ptk itself load faster

**Comment by mburo** [comment]
+------------------+----------------+
| xonsh            | 0.3.4          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | True           |
| on linux         | True           |
| distro           | Fedora         |
| on darwin        | False          |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+

Is there a way to disable prompt_toolkit ? Removing that package and reinstalling xonsh produces an error message:

    return tuple(int(x) for x in ptk_version().strip('<>+-=.').split('.'))
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 3171, in ptk_version
    import prompt_toolkit
ImportError: No module named 'prompt_toolkit'

Also, I recall ca. 2 weeks ago when first running xonsh I didn't have prompt_toolkit installed and starting xonsh tool ~0.6 secs (reported elsewhere).

**Comment by laerus** [comment]
@mburo try setting `$SHELL_TYPE ='readline'` in .xonshrc

**Comment by laerus** [comment]
also maybe you.ll have to reinstall xonsh

**Comment by scopatz** [comment]
Yep, @laerus is correct. See also, http://xon.sh/envvars.html#shell-type

> Also, I recall ca. 2 weeks ago when first running xonsh I didn't have prompt_toolkit installed and starting xonsh tool ~0.6 secs

2 weeks was a very long time ago :)

**Comment by mburo** [comment]
For ~/.xonshrc = 
```
$SHELL_TYPE ='readline'
$PROMPT="> "
```
using the lastest xonsh version I get

foo6[~]:time xonsh -c exit

real    0m0.589s
user    0m0.546s
sys     0m0.095s

No difference when using $SHELL_TYPE ='prompt_toolkit'. I guess by the time ~/.xonshrc is read, the time consuming code has already been executed. I find 0.6 seconds excessive. I also removed ~/.bashrc thinking the time is spent parsing it. It isn't. What else can take one billion instructions? Perhaps the results can be cached.

**Comment by laerus** [comment]
you can try removing git-branch prompt or changing `$VC_BRANCH_TIMEOUT` to a lower value

**Comment by mburo** [comment]
Shown above, I already use a minimal prompt. Setting $VC_BRANCH_TIMEOUT = '0' doesn't change the startup time. As I mentioned before, the 0.6 second delay probably happens before ~/.xonshrc is read.

**Comment by laerus** [comment]
solved!
