### ISSUE TITLE
Commands not working "xonsh: subprocess mode: command not found:"

### ISSUE THREAD

**Issue by vjohansen** [xonsh/xonsh#1294]
I just installed xonsh and basic commands are not working

   ... ~ # ls
   xonsh: subprocess mode: command not found: ls

   ... ~ # echo "sdf"
   xonsh: subprocess mode: command not found: echo

pip  list |findstr xons
←[33mYou are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.←[0m
xonsh (0.3.4)

**Comment by vjohansen** [comment]
C:\Users\vj>python --version
  Python 3.4.4 :: Anaconda 4.0.0 (32-bit)

**Comment by melund** [comment]
On windows the linux commands will not work unless you have GitForWindows installed and added to the path. That will change in the next version where it will find the linux tools even if it isn't on path. 

`echo` is also on windows, so it is a bug that it doesn't work. You can add with an alias
`aliases['echo'] = ['cmd.exe', '/C', 'ehco']`

If you are using Anaconda, then it is best to install xonsh with conda:  `conda install -c conda-forge xonsh`

**Comment by jsarver** [comment]
Is this bug with the echo command fixed in a future release of xonsh?

**Comment by melund** [comment]
No. It hasn't been fixed. It needs to go into this list. https://github.com/xonsh/xonsh/blob/master/xonsh/aliases.py#L528

But maybe with a check that users don't have the MSys echo.exe from GitForWindows already on their PATH. 

A PR is very welcome

**Comment by jsarver** [comment]
Sorry did not mean to delete my previous comment.  I've been looking for a way to contribute so will take a stab at this.  Would it make sense to add all the internal commands to that list for completeness or is there a reason why some of them were excluded? 

Here is a list of all internal windows cmds for reference.  

http://ss64.com/nt/syntax-internal.html

**Comment by melund** [comment]
I don't think much thought has been given to what is in the list. Some of the command alter the environment in some way which previously could not be feed back into xonsh environment. 

That is possible now with the source foreign functionality (`source_cmd()`)

**Comment by jsarver** [comment]
@melund do you have suggestions on how I would validate if echo exists for gitforwindows? I found the git_for_windows_path() function to get the path for get and I was going to just do an os.path check to see if echo is in the bin directory  but I noticed in some git installs the echo command is in /usr/bin vs just bin.

Should I just check both of those paths and use whichever is found and if not, defer to the windows echo.exe?

**Comment by melund** [comment]
Good. Question. We could just look if it is available on the PATH. ´locate_binary()` can do that for us. But we don't really want to search the whole path for binaries on startup. 

Aliases always take precedence, and we don't have a way to specify they should be secondary to binaries. We have a similar issue with `sudo` windows stuff in the `aliases.py`. It also looks adds itself only if a ´sudo.exe` is not available on PATH: Not the best thing if we want to reduce startup time. 

Maybe we could make aliases which would unregister them self if the binary is on the PATH the first time they run

**Comment by jsarver** [comment]
So I am probably missing the drawback but is it really necessary to use the git version of echo over the MS verison? If we just add the default alias of cmd /c echo, it's going to resolve to the git version (if present) and if not then it should resolve to the built in version right?

**Comment by scopatz** [comment]
Well, there probably should be a xoreutils version of echo, but no one has implemented it yet.

**Comment by paulschmeida** [comment]
I just tried to `ls` on Windows and it's not working 5 years later. Seriously, I can `ls` in powershell but not in xonsh? This project is effectively dead...

**Comment by jnoortheen** [comment]
you can install [cmdix](https://github.com/jaraco/cmdix) or [coreutils](http://gnuwin32.sourceforge.net/packages/coreutils.htm)

the community is also welcome to any contributions to its own xoreutils xontrib
