### ISSUE TITLE
error 'loader for xonsh.__amalgam__ cannot handle xonsh.main' on Windows startup

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#1295]
Brand new pull from master, install on Windows (10), running Python 3.5.2 rc1.  Shell start at `xonsh.main` fails with error as above, but will start (and apparently run OK ) at `xonsh`

Same config runs OK if I revert to 0.3.4.

Git LOG, Build/install log, and nose tests attached.

[xonsh1.txt](https://github.com/xonsh/xonsh/files/323955/xonsh1.txt)

```
======== NCSD10227 ==== A:\src\mgmt\tools\xonsh
+> xonsh
C:\Program Files\Python35\python.exe: loader for xonsh.__amalgam__ cannot handle xonsh.main

======== NCSD10227 ==== A:\src\mgmt\tools\xonsh
+> python -m xonsh.main
C:\Program Files\Python35\python.exe: loader for xonsh.__amalgam__ cannot handle xonsh.main

======== NCSD10227 ==== A:\src\mgmt\tools\xonsh
+> python -m xonsh
C:\Program Files\Python35\lib\site-packages\pygments\plugin.py:39: UserWarning: Module xontrib was already imported from None, but a:\src\mgmt\tools\xonsh is being added to sys.path
  import pkg_resources
-------------------------- bob@NCSD10227 A:/src/mgmt/tools/xonsh master
$

```

**Comment by melund** [comment]
You probably have some old left over xonsh startup scripts in your Python distribution. 

A lot have happened to xonsh the last few weeks and there are a lot of bugs in the current master. So you may want to use the release version. But of course any help bug hunting is also appreciated.

**Comment by bobhy** [comment]
I was pretty sure I had cleaned up before running the above procedure the first time, but I double checked that path was cleansed of cruft (captured in log) and tried again.  Same failure 
[xonsh2.txt](https://github.com/xonsh/xonsh/files/324019/xonsh2.txt)

I've flipped back to 0.3.4 for today, will roll forward again tomorrow if there's news (or a suggestion on more focused data collection to do.  I have never seen this "can't handle" error from Python before, don't really know what would be helpful).

**Comment by scopatz** [comment]
Hi @bobhy - thanks for reporting!  I agree with @melund that this looks like an install issue.  When you say that you cleaned it up, did you remove the install the target location (ie in site-packages/xonsh) or just the build dir in the source directory/repo?  Some of the more recent changes may require a deep wipe.

**Comment by bobhy** [comment]
I did delete subtree from site-libraries/xonsh (2nd log has transcript), but now that I think about it, I did not do setup.py clean between versions, just ```install```.  I'll try again tomorrow AM.

**Comment by scopatz** [comment]
Sounds good!

**Comment by bobhy** [comment]
Resolved!  I reverted to Python 3.5.1 (from 3.5.2rc1), and now it works.

Before that, I tried installing Python 3.5.2rc1 in a Windows folder that did not contain space (i.e c:\Python35 rather than the default c:\Program Files\Python35), and observed that the error still happened, but one of the failing nose tests started working, FWIW.

I also tried updating my GIT tools (from 2.7.0.windows.1 to 2.9.0.windows.1), but that made no difference to the error.

So I'll stick with this interpreter and master branch of the shell and help keep on pushing the envelope.

**Comment by scopatz** [comment]
Glad to hear that this is resolved!

**Comment by bj0** [comment]
I am getting this on a fresh install of miniconda3 (python 3.5.2) followed by a pip install xonsh.

**Comment by scopatz** [comment]
@bj0 can you post the output of `xonfig`  and the full traceback please? Thanks!

**Comment by bj0** [comment]
there is no traceback, only:
```
python -m xonsh.main
C:\Miniconda3\python.exe: loader for xonsh.__amalgam__ cannot handle xonsh.main
```

And xonfig isn't on the path.

**Comment by scopatz** [comment]
Can you try setting the environment variable XONSH_DEBUG=1 *before* trying to start xonsh.  (Sorry I don't know how to do this from cmd.exe, which I am guessing you are using.)  See also http://xon.sh/envvars.html#xonsh-debug

**Comment by melund** [comment]
On windows it is: 
`set XONSH_DEBUG=1`

**Comment by melund** [comment]
@bj0 If you are on mini-conda, then just use the conda packages: 

First, add the conda-forge channel:
```
conda config --add channels conda-forge
``` 
then install xonsh with conda:
```
conda install xonsh
```

**Comment by melund** [comment]
I can reproduce this in a py3.5 conda environment, installing from pip
```
(t3) C:\Users\mel>xonsh
C:\Users\mel\Anaconda3\envs\t3\python.exe: loader for xonsh.__amalgam__ cannot handle xonsh.main
```
With `XONSH_DEBUG=1` it starts 
```
(t3) C:\Users\mel>SET XONSH_DEBUG=1

(t3) C:\Users\mel>xonsh
C:\Users\mel\Anaconda3\envs\t3\lib\site-packages\xonsh\shell.py:57: UserWarning: prompt_toolkit is not available, using readline instead.
  warnings.warn('prompt_toolkit is not available, using '
No readline implementation available.  Skipping setup.
(t3) snail@sea ~ $
```
Installing pyreadline fixes the last warning, but it doesn't fix the initial problem "`loader for xonsh.__amalgam__ cannot handle xons... `"

Installing the conda pacakge is probably the easiest workaround for @bj0

**Comment by scopatz** [comment]
Maybe we should make prompt-toolkit a pip dependency on windows.

**Comment by scopatz** [comment]
Or maybe we should just change the warning message to tell people that their Python does not contain readline and so they should install prompt-toolkit or pyreadline. 

Also it is strange that @bj0 did not see the full warning message...

**Comment by melund** [comment]
I didn't see it either when running amalgamated

**Comment by scopatz** [comment]
Yeah... that is bad :(

**Comment by bj0** [comment]
I had already installed prompt-toolkit.  Turning on the debug flag showed that I was missing pygments.  ```pip install pygments``` fixed it.

**Comment by scopatz** [comment]
Ahh, shoot this pygments issue again.

**Comment by bj0** [comment]
I may have spoke too soon.  Now it seems to only be working with the XONSH_DEBUG flag actually set...
```
set XONSH_DEBUG=

xonsh
C:\Miniconda3\python.exe: loader for xonsh.__amalgam__ cannot handle xonsh.main

set XONSH_DEBUG=0
xonsh  # works
```

**Comment by scopatz** [comment]
Is this still an issue?

**Comment by bj0** [comment]
I am not seeing it with the latest version.

**Comment by scopatz** [comment]
Great! Thanks!
