### ISSUE TITLE
Certain aliases show no output until the whole underlying command completes

### ISSUE THREAD

**Issue by wreed4** [xonsh/xonsh#1306]
I have noticed that certain aliases copied from my .bashrc seem to run in the background and show no output until they complete.  They are not function aliases.  Specifically this is an alias to a proprietary make-like script, but let's call it `my_make`.  So if I just type `my_make`, then I get no output and then suddenly all the output all at once.  But if I type `bash -l -c "my_make"` (this is the same alias in my bashrc, which is sourced by the `-l` flag), I get output line by line like I'd expect.  Is there a way to avoid this?

**Comment by laerus** [comment]
Hello @wreed4 and thanks for reporting! Can you try creating an alias in xonsh that runs `my_make` directly and see if it works?

**Comment by scopatz** [comment]
@wreed4 - this doesn't seem correct.  What does your `xonfig` say?  Can you come up with an example that reproduces this in a way that is shareable?

**Comment by gforsyth** [comment]
@wreed4 -- does this behavior still occur on either 0.4.7 or current master?

**Comment by scopatz** [comment]
I hope not, since one of the points of the run subproc refactor was to fix these kinds of issues :)

**Comment by wreed4** [comment]
@gforsyth Yes, I can confirm this still happens on 0.4.7

I'm not entirely sure how to replicate it, but I have determined that it doesn't have to do with the alias.  Here is the situation the best I can describe it:

The alias is something like:`aliases['mk'] = 'proprietary_make build'`
`proprietary_make` is a `rake`-like tool that my company owns and has written.  It is basically a perl script. It also executes things via ssh.  Anything more than that I probably can't divulge.  

So now, when I type `mk` or `proprietary_make build` on the command line, I get no output until the end where it all prints at once.  However in bash, I get each line as it comes.  I can turn ssh off and it doesn't seem to change anything.

**Comment by gforsyth** [comment]
Hi @wreed4 -- noted.  How about on current master?

**Comment by wreed4** [comment]
Yes, I can confirm this still happens on current master.

**Comment by gforsyth** [comment]
Ok @wreed4 -- it's going to be hard to debug this any further since we don't really know what's going on in that script (and, of course, understand that you can't tell us).  
If output isn't streaming, then it's probably because something that shouldn't be threaded is being threaded.  
I would try the following:
First, add the `proprietary_make` script to the `threadable_predictors` dictionary with a value of `predict_false`

```console
from xonsh.proc import predict_false
__xonsh_commands_cache__.threadable_predictors['proprietary_make'] = predict_false
```
and try that out (you can stick these in your `xonshrc`)
If you still have trouble, then try adding in the various programs that get called by the script one by one.  If there's anything that is curses based, we know already that those cause trouble, so I would start there.  

Let us know if that helps at all.  If it does and the programs you've added aren't proprietary, you can open a PR to add them to `xonsh/command_cache.py`

**Comment by wreed4** [comment]
I figured it out I think.  Turns out that if I hit `CTRL-C` while proprietary_make` is running, I get an error that includes this line: 
```
subprocess.CalledProcessError: Command '['bash', '-c', 'source "/home/user/scripts/proprietary_setup.sh"\nproprietary_make\n']' returned non-zero exit status 255
```
  This led me to check `aliases['proprietary_make']` which turned out to be `<xonsh.foreign_shells.ForeignShellFunctionAlias at 0x.........>`.  This is odd because `which proprietary_make` gives simply `/home/bin/proprietary_make`.  This is what I checked before.  Usually, when you do `which` on an alias, it mentions that it's an alias.  Or just returns the same name.  By doing `del aliases['proprietary_make']`, everything appears to be running in the foreground now.  

So I guess I'd have a couple of comments on this. First, `xonsh.foreign_shells.ForeignShellFunctionAlias` should probably have a better `__str__` (in my opinion).  Second, `which` should probably return the command that's actually being run (the `bash -c` command, or the alias).  And thirdly, I'm still not sure why the original command was being backgrounded.  

Also, @gforsyth, it seems like `predict_false` can't be imported from `xonsh.proc` for some reason.  It wouldn't let me.

**Comment by gforsyth** [comment]
Hey @wreed4 -- `predict_false` will only be available on master.  

Not sure what's up with `which` acting that way.  It returns the command being run on my machine. You can pass it the `-v` flag for more information, or the `-a` flag to look at all possible returns.  But generally, the behavior is to show the expanded command (or in the case of a function alias, to show the name of the function it's aliased to).  

```
gil@bad_cat ~ 🐚  which ls
ls --color=auto -v
gil@bad_cat ~ 🐚  which -v ls
aliases['ls'] = ['ls', '--color=auto', '-v']
gil@bad_cat ~ 🐚  which -a ls
aliases['ls'] = ['ls', '--color=auto', '-v']
/usr/bin/ls (from PATH element 1)
```

If it's running as a foreign shell, it sounds like there may be something set up in your `config.json` that's screwing with everything else.  You could try removing that file to see if it changes behavior.

**Comment by wreed4** [comment]
@gforsyth Yes, in all other cases, I've seen `which` perform correctly as well.  I didn't know about `-v` and `-a` though.  I'll have to look at what those return.

**Comment by scopatz** [comment]
I think this has been taken care of with many of the recent changes. However, if there is a reproducible way to show that this is still occuring, please feel free to reopen!
