### ISSUE TITLE
Xonsh wildcards should sort lexicographically

### ISSUE THREAD

**Issue by eode** [xonsh/xonsh#1314]
Bash uses lexicographical sort when a list is created via a wildcard.   We should, too.

This is useful because:
* it is a bashwards-facing feature
* it is useful 
* its drawback is minor (sort time)
* the alternative (current state) is disorder, where typically order is desired
* ordering by name is a very reasonable default
* it is a de-facto standard of shell behaviour

usage example:
``` cat *.sql | mysql -u foo -p -- somedb ```

..where the '*.sql' files are prefixed by a numeric token, such as `001_cows.sql, 002_add_cow_stomachs.sql, 003_cow_currently_masticating_colum.sql`, or are prefixed by a datestring, such as `20120105_monthly_update.sql, 20120201_monthly_update.sql, [...]`

..this is particularly significant in cases where people have already structured their filenames for use in scripting, as the scripting in Xonsh would add a needless step.   Granted, this can be done in python anyways, but the simplest syntax is to implicitly sort on wildcards:
```python
cat *.sql | mysql -u foo -p -- somedb
//or
cat @(' '.join(sorted(f for f in $(ls -1 *.sql).split('\n')))) | mysql -u foo -p -- somedb
// or 
from glob import glob
cat sorted(glob('*.sql')) | mysql -u foo -p -- somedb
```

**Comment by pgoelz** [comment]
It seems to work automatically for me (v0.3.4, OSX).

I'll attach the testing code I've used in case someone wants to quickly test it on their system:

    from tempfile import TemporaryDirectory
    from random import randrange
    
    oldpath = $(pwd).strip('\n')
    directory = TemporaryDirectory()
    
    cd @(directory.name)
    for _ in range(200):
        num = randrange(10000, 99999)
        with open(str(num), "w") as file:
            file.write(str(num) + "\n")
    
    output = list(map(int, $(cat *).strip('\n').split('\n')))
    
    if output == sorted(output):
        print("Wildcard seems to sort.")
    else:
        print("Wildcard did not sort: ")
        print(str(output))
    
    cd @(oldpath)
    directory.cleanup()

**Comment by scopatz** [comment]
This behaviour might be platform dependent because the behaviour of glob might be platform dependent.  It would be nice to have a PR for this.  Additionally it might be nice to have an envvar that controlled whether the sort happened or not. I can a imagine a few situations were it doesn't matter or you would want it turned off.

**Comment by pgoelz** [comment]
Okay, I can reproduce the bug on current master, arch linux.

Can you try whether this works: bfbc8968a8fbfaac788a08c3f017d17756470eff ?

**Comment by pgoelz** [comment]
@scopatz I'll try to add this and make a pull request.

**Comment by scopatz** [comment]
@pgoelz awesome, thanks!
