### ISSUE TITLE
Homebrew bleeding edge install too please

### ISSUE THREAD

**Issue by ph-hs** [xonsh/xonsh#1324]
I encountered https://github.com/xonsh/xonsh/issues/1198. Seems to have been fixed in master. Thought I'd uninstall the brew installed xonsh, and go for the conda one. Conda is an incomplete mess on the Mac, I find. "brew install Caskroom/cask/miniconda" doesn't put anything in the path. Similarly "~/miniconda3/bin/conda install -c xonsh/channel/dev xonsh" doesn't put anything in the path. 

I'd be nice to do "brew install Caskroom/cask/xonsh-dev" for a smooth experience.

**Comment by gforsyth** [comment]
Hi @ph-hs -- thanks for reporting.  We can try to work on a brew install, although that's outside of my personal experience.  

`conda`, if you aren't using environments, installs things into the `bin` folder within it, so if you add `~/miniconda3/bin` to your path that should give you access to master until we have homebrew up and running

**Comment by scopatz** [comment]
Hi @ph-hs - Also note that the current brew install was not written and is not supported by any of the core xonsh devs.  But thanks for bringing this up and hopefully someone will implement it. We'd be happy to help support this effort if the implementer has specific needs that aren't currently covered.

It might be faster to bring this up with the brew recipe authors :)

**Comment by gforsyth** [comment]
I'm going to close this as we don't handle the brew recipe
