### ISSUE TITLE
pytest seems to randomly timeout on travis 

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1335]
Not sure what is causing this.  Maybe we should remove the quiet flag?

**Comment by scopatz** [comment]
Or maybe it is coverage that is failing.

**Comment by laerus** [comment]
running tests locally through bash on python3.4:

```
$ python3 -m coverage run --source xonsh -m py.test -q

Exception ignored in: <bound method Execer.__del__ of <xonsh.__amalgam__.Execer object at 0xb57b58ec>>
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/__amalgam__.py", line 16144, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <generator object get_tokens at 0xb37832ac>
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/__amalgam__.py", line 9970, in get_tokens
TypeError: catching classes that do not inherit from BaseException is not allowed


$ XONSH_DEBUG=1 python3 -m coverage run --source xonsh -m py.test -q

Exception ignored in: <bound method Execer.__del__ of <xonsh.execer.Execer object at 0xb568918c>>
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/execer.py", line 47, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by laerus** [comment]
@scopatz master build failing cause of py3.4 stalled tests, it seems that i cannot restart them. also any idea on wthat that crazy `TypeError: catching classes that do not inherit from BaseException is not allowed` in `get_tokens` is about?

**Comment by scopatz** [comment]
I don't really know why the test is stalled. The error we should be able to track down though...

**Comment by stockninja** [comment]
I installed the pytest-timeout pip package, and ran tests with --timeout=10 flag to try and get a stacktrace -> https://gist.github.com/stockninja/849134871d2e118055ff9feb2046b7f7

test_ast.test_multilline_num and test_tools.test_partial_string both appear to have time.sleep problems. I don't understand what's going on nearly well enough to solve, but this should help others solve the problem ...

**Comment by melund** [comment]
`test_tools.test_partial_string` used to run a lot of test assertions. Like many thousands. I don't know if @laerus solved this when moving to pytest. Maybe this is causing problems with xonsh history?

**Comment by laerus** [comment]
right! i remember `test_partial_string` needing a refactor but i didnt touch it in the migration. I will try and mess with it today. Many tests still need refactoring, we could rly use a speed up in CI.

**Comment by laerus** [comment]
`test_partial_string` atm runs ~1020 tests, i think we can cut down a lot, i will try and parametrize it.

**Comment by laerus** [comment]
this was probably an indentation gone back on the migration, my fault.. i'm refactoring this anyway, PR incoming.

**Comment by santagada** [comment]
https://travis-ci.org/xonsh/xonsh/jobs/146857204 see this failing job on timeout. It seems to be related to sleeping wainting for a parser.

**Comment by scopatz** [comment]
I wonder if it is failing because so many test threads are launched....  We should add a way to circumvent loading on another thread, maybe using XONSH_DEBUG?

**Comment by laerus** [comment]
i don't think this is still an issue, closing for now.
