### ISSUE TITLE
Support coconut

### ISSUE THREAD

**Issue by bj0** [xonsh/xonsh#1336]
This is just a feature request, but it would be really cool if xonsh could optionally support coconut syntax in the shell (it's a superset of python).  Not sure if it would be possible to do as an Xontrib or would have to be built in.

edit: link: http://coconut-lang.org/

**Comment by scopatz** [comment]
Hi @bj0, thanks for opening this issue! I am not sure what you mean by support, exactly.

I am pretty sure that you can import coconut in a xonsh session and then start execing it, though I have tried this. there could probably pretty easily be a xontrib that get you most of the way.

As far as the syntax goes, looking at coconut, the grammars seem incompatible without going into a special coconut mode. If there is specific syntax that you are interested in, please feel free to propose that.

**Comment by bj0** [comment]
Indeed I was thinking about a "coconut mode" where you can just type valid coconut syntax into the shell (like you can currently type valid python into the shell).  I don't know exactly how xonsh handles syntax parsing so I understand this might be difficult.  I just wanted to throw out the idea as a possible future enhancement which would be a pretty cool feature (coconut is still pretty new but has some very nice functional syntax).

**Comment by scopatz** [comment]
For what it is worth, I have been thinking a lot about how to implement this.

**Comment by mhsekhavat** [comment]
Hi guys,
I am not so familiar with xonsh internals. Do you think it is possible that we integrate https://github.com/sspipe/sspipe with xonsh so that we can use it's `__or__` operator overloading for forwarding stdout of a process to the next?

**Comment by scopatz** [comment]
It seems like sspipe should just work with xonsh out-of-the-box.  Are you seeing an issue with it?

**Comment by mhsekhavat** [comment]
Aha, yes I was missing the `$()` construct:

```python
>>> ls | p(len)
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NameError: name 'ls' is not defined

>>> $(ls) | p(len)
103
```

**Comment by scopatz** [comment]
Awesome!

**Comment by dotsdl** [comment]
This is best addressed with a xontrib. Closing!

**Comment by WillForan** [comment]
coconut provides a xcontrib!
https://coconut.readthedocs.io/en/latest/DOCS.html#xonsh-support
