### ISSUE TITLE
completion fails

### ISSUE THREAD

**Issue by konsilanto** [xonsh/xonsh#1338]
Using the latest version (0.4.1) completion does not work al all (at least for me):

- If CDPATH is set with `[".", "/home/foo/workspace"]` and the HOME-directory as well as the directory  "~/workspace" contain a directory "bin", then performing the following command (from the HOME  directory) `cd work<TAB><TAB>` completes to `cd bin/`. Therefore, it can't be used.

- Removing CDPATH (`del $CDPATH`) the false completion does not occur but
  `cd work<TAB><TAB>` activates the first entry in the popup and therefore I am not 
  able to choose one of the subdirectories based on the starting letter.  Typing `cd workspace/<TAB>` does not activate the the first entry and I am able to choose one of the subdirectories by specifying one or several starting letters.

  Typing `cd workspace//<TAB>` popups the list of directories and does not activate the first
  entry but it is at least cumbersome.

**Comment by scopatz** [comment]
Thanks for reporting @konsilanto! Can you please post the output of the `xonfig` command?

**Comment by gforsyth** [comment]
Hey @konsilanto -- this won't help the `CDPATH` issue but if you want to check out #1340 I changed the completer behavior to display completions but not autoselect the first option

**Comment by konsilanto** [comment]
Here the output of `xonfig`:
    +------------------+----------------+
     | xonsh             | 0.4.1           |
     | Python           | 3.5.1          |
     | PLY              | 3.7            |
     | have readline    | True           |
     | prompt toolkit   | 1.0.3          |
     | shell type       | prompt_toolkit |
     | pygments         | 2.1.3          |
     | on posix         | True           |
     | on linux         | True           |
     | distro           | unknown        |
     | on darwin        | False          |
     | on windows       | False          |
     | on cygwin        | False          |
     | is superuser     | False          |
     | default encoding | utf-8          |
     +------------------+----------------+

**Comment by konsilanto** [comment]
@gforsyth -- `dont_select_first` works like a charm. thanks

**Comment by scopatz** [comment]
Great!  Feel free to close this issue, then @konsilanto!

**Comment by konsilanto** [comment]
I am sorry but it was a simple misunterstanding... the one particular problem (concerning selecting the first entry of the popup) is solved however the other just remains unresolved (CDPATH related)

**Comment by adqm** [comment]
Sorry for the confusion, @konsilanto.  Yes, it does look like the completer isn't properly handling `$CDPATH`.

I'll take this one, unless someone else wants to jump in and beat me to it.

**Comment by gforsyth** [comment]
@konsilanto -- I believe `CDPATH` completion works now, would you mind giving it another shot and reporting back?  Thanks!

**Comment by konsilanto** [comment]
@gforsyth -- yes, `CDPATH` completion works now... thanks!!!
