### ISSUE TITLE
setup.py install fails if git is not installed

### ISSUE THREAD

**Issue by chronitis** [xonsh/xonsh#1350]
The `dirty_version()` function which tries to check if a random git revision is being built fails if `git` isn't in `$PATH`.

At `setup.py:112` (in v0.4.2) it checks for `CalledProcessError`, but git being unavailable instead throws (uncaught) `FileNotFoundError`.

**Comment by melund** [comment]
Thanks for reporting this @chronitis. I have pushed a fix for it.
