### ISSUE TITLE
aliases do not play well with functools partial

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#1363]
The code in question is here, https://github.com/xonsh/xonsh/blob/master/xonsh/built_ins.py#L466-L472 :

``` python
            numargs = len(inspect.signature(aliased_cmd).parameters)
            if numargs == 2:
                cls = SimpleProcProxy if bgable else SimpleForegroundProcProxy
            elif numargs == 4:
                cls = ProcProxy if bgable else ForegroundProcProxy
            else:
                e = 'Expected callable with 2 or 4 arguments, not {}'
                raise XonshError(e.format(numargs))
```

Specifically using `inspect.signature` will give the total number of arguments including those frozen with  partial. This is a problem because if I have a more abstract alias command as such: 

``` python
from functools import partial
def rename_term(args, stdin=None, cmd=None, name=None)
rename_htop = partial(rename_term, cmd = 'htop', name='htop')
aliases['top'] = rename_htop
```

then my new `top` alias will fail because the number of arguments is seen to be `6` after stdout and stderr get added to the parameter list.

The truth is this is not a bug per say but more a limitation of `functools.partial`. However, I find a lot of value in using partial functions as aliases (which I was able to get around by using the `partial` implementation in the Python documentation). 

I think `xonsh` can be more flexible here to accommodate the standard library. Perhaps instead of checking if there are 2 or 4 arguments we could instead check to make sure that `['args', 'stdin']` or `['args', 'stdin', 'stout', 'sterr']` are the first parameters in `signature(aliased_cmd).parameters.keys()`?

**Comment by scopatz** [comment]
Thanks for bringing this up @JohnLunzer! I am not sure what the correct path is.  I don't think that we should force people to have certain argument names, though.  I am also surprised that partial works this way though. It seems like the right workaround for now is to wrap the original function in a lambda with the right signature.

**Comment by laerus** [comment]
this `run_subproc` is a pain in the eyes :(

**Comment by scopatz** [comment]
@laerus I agree `run_subporc()` needs to be split up.  However, this issue about the ProcProxy classes.

**Comment by scopatz** [comment]
See #2256 for a potential fix.

**Comment by melund** [comment]
#2256 has been merged. @JohnLunzer Let us know if this doesn't fix it.

**Comment by JohnLunzer** [comment]
Just got a chance to try this out and the fix works flawlessly. Great work. Thanks for the attention!
