### ISSUE TITLE
the xonsh commandline

### ISSUE THREAD

**Issue by PaulReiber** [xonsh/xonsh#1365]
On a thread about introducing hooks into xonsh for customization (great idea, by the way!) I wrote an aside:

> On the other hand, part of me thinks commandlines are "pipelines" by default, and almost never intentionally "or cases" typed in manually.  By extension the first | on a commandline would need to be examined to see if what's after, to EOL, is valid in subprocess mode, and if so, auto-wrap the left-hand-side python code in @() so that pipe isn't accidentally interpreted as an "or".  Because, who actually intentionally uses "or" on a commandline, vs. wanting to pipe the output.  So, for that case, I think BASH-ishness would be a better default.  Maybe a setting "OR_MEANS_PIPE" to let the end-user decide?

While my "solution" of auto-wrapping the left-hand-side doesn't seem to actually work in testing, the idea was to get the output from the python expression and pipe it forward.

Anthony recommended:

> @PaulReiber - That seems like it is a separate topic, if you'd like to open one up. Also it seems like this is similar in idea to what plumbum does. And autoplumber is an interesting concept. Maybe that could be a xontrib or if we could figure out a way to automatically insert names into the context based on the current **xonsh_commands_cache** keys... I am not sure this is 100% safe all of the time (would have to see an implementation) but I think it is certainly worth a discussion in another thread.

Indeed- my note was an aside on another thread.  Anthony had asked for clarification, here's what I wrote, re-expressing the thought.

> I don't understand this @PaulReiber. Can you explain it again, please?

I'll try, sure.   What's it mean to be "at the command line?"  Here's my proposal, regarding xonsh in interactive mode.

I guess it's all a matter of perspective - when you're typing at the command line, what are you trying to do? From sh, csh, tcsh, zsh, bash, korn shell onward the command line has been a means to let one build useful pipelines on the fly.  Processing cascades - outputs of one process being sent to the next, then the next, then the next, as needed.

wikimedia 's explanation of tee is a pretty good visual of a simple pipeline:
![pipeline](https://cloud.githubusercontent.com/assets/58688/16902979/4760389e-4c25-11e6-8123-d5acb3b7d516.png)

Martin Kleppmann has a great visual for what I'm headed at:
![pipes](https://cloud.githubusercontent.com/assets/58688/16903196/1b82bdd0-4c2c-11e6-9859-59357c1da428.png)

So, for xonsh, sure, Python's primary, but when in interactive mode,  when encountering a | what does that mean?

I use interactive shells to construct pipelines, not or-cascades.  I love the idea of piping the output of a bunch of relevant python code to some subprocesses by simply "piping it":

```
$ 4 + 4 | cat
8
$ 
```

It's the one place where I think being non-pythonic might make some sense. And, as I said, it could be left to the end-user to decide.

-=-

Possibly I'm doing things a harder way than needed.  Consider:

```
$ $(echo @(4 + 4) | sed 's/8/awesome/')
'awesome\n'
$
```

The above's good but not great - it's somewhat complicated to build the pipeline.

My proposal here is to put some thought into commandline parsing, to see if we couldn't come up with simpler/easier ways of blending python mode and subprocess mode via pipeline notations similar to BASH:

```
$ 4 + 4 | sed 's/8/awesome/'
awesome
$ 

```

Here's the core thing to ponder:  How many times, at the xonsh commandline, do you really need python's OR, vs needing to express a pipeline.

Thanks Anthony and the rest of the xonsh core team, for all your hard work on all of these various issues.  Great work - I see one awesome shell starting to emerge.

**Comment by scopatz** [comment]
Thanks for opening this issue @PaulReiber

**Comment by pgoelz** [comment]
You could also use anonymous aliases as follow:

    @(lambda a, i: 4 + 4) | cat

**Comment by bobhy** [comment]
I'll offer another scenario and a possible solution.
I would like this to work:

`> ls -l <magicPipe> for line in string:
    <Do something in Python with line of ls output>`

For <magicPipe> I propose `.|`.

And it could work the other way, too.  

<Python expression> <magicPipe> <shell commands> 

Could pipe result of expression to shell command.

Means introducing another Xonsh-specific operator, but maybe worth it?

**Comment by scopatz** [comment]
@bobhy, you can already do this with `!(...)`,

```python
for line in !(ls -l):
    pass
```

**Comment by bobhy** [comment]
I did not know that till this very day.

OK, that's clean enough for me.

Coming back to @PaulReiber 's scenario, would this work?

```
cat @(4+4) | sed /8/awesome/
```

Better than a lambda, but still not as clean as desired.  Maybe there is room in Xonsh for a custom operator after all.

**Comment by scopatz** [comment]
It would actually be `$ echo @(4+4) | sed -e s/8/awesome/`, but yeah.  Happy to hear suggestions for alternative syntax!

**Comment by laerus** [comment]
maybe we can always treat `|` as a pipe in xonsh when not in interactive mode, so other programs that invoke xonsh won't complain.

**Comment by scopatz** [comment]
I am pretty wary of any modal syntax that changes base on settings in the env or how xonsh is called etc.

**Comment by scopatz** [comment]
Closing due to age, I think most of the issues have been addressed / acknowledged
