### ISSUE TITLE
Filename Tab Completion Twice

### ISSUE THREAD

**Issue by jwhite007** [xonsh/xonsh#1380]
xonsh v0.4.3
iterm2 v2.1.4
OS X v10.11.5

I would first like to say that xonsh is damn cool.

I'm not sure if this is really an issue, or if it was an intended design feature. I often rename files to a variant of the original name. It's very easy to 'mv "first part of filename' + tab 'first part of filename' + tab", and then to change the second filename entry. This works in xonsh if filenames have no spaces; however, if the filename has spaces, I only get the first tab completion. In bash this is not the case.

Thanks for your hard work on xonsh.

Cheers,
James T. White

**Comment by scopatz** [comment]
Hi @jwhite007! Thanks for using xonsh and asking this question!  

When you get tab complete files with spaces in the name, you should get a quote at the start of the file name.  Or if you added a space, you should start the file name with an initial quote to complete the rest. Hopefully this makes sense.

**Comment by scopatz** [comment]
If this doesn't work for some reason, @adqm may know more.

**Comment by jwhite007** [comment]
@scopatz 
Anthony,

This does not appear to be an issue with the latest xonsh (0.4.7)

xonsh r0x!!

Cheers,
James

**Comment by scopatz** [comment]
Awesome!

**Comment by scopatz** [comment]
I love when things aren't an issue ;)
