### ISSUE TITLE
Typo in lazyasd?

### ISSUE THREAD

**Issue by janschulz** [xonsh/xonsh#1382]
I just stole the file for a different project and found that my IDE flagged this:

https://github.com/xonsh/xonsh/blob/master/xonsh/lazyasd.py#L131

```py
    def __delitem__(self, key):
        if key in self._d:
            del self._d[lkey] # <- lkey instead of key?
        else:
            del self._loaders[key]
            self._destruct()
```

IMO that's a typo?

**Comment by scopatz** [comment]
@janschulz that is definitely a typo! Thanks for reporting. Would you mind putting in a PR for this?

**Comment by janschulz** [comment]
See https://github.com/xonsh/xonsh/pull/1383
