### ISSUE TITLE
Can't put a backslash before double quotes in subshell mode if they contain an inline python mode section

### ISSUE THREAD

**Issue by Russell-Jones-OxPhys** [xonsh/xonsh#1388]
(I'm not sure how to escape quotes in subshell mode, either, other than inline python-mode escaping)
This applies to at least the backslash, but not all characters.

```
$ echo \" @(1+2) \"
......................... 
\" 3 \"
$ echo \" @("hi") \"
......................... 
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: \
echo \" @("hi") \"
$ echo  @("hi") 
hi
$ echo \" @('hi') \"
\" hi \"
$ echo " @("hi") "
......................... 
" @("hi") "
$ echo a" @("hi") "
......................... 
a" @("hi") "
$echo a" @("hi") a"
a" @("hi") a"
$echo \" " \"
\" " \"
```

**Comment by scopatz** [comment]
Hi! Thanks for bringing this up, I think that but you can just quote the quotes,

```
$ echo '"' @(3+2) '"'
```

**Comment by Russell-Jones** [comment]
Is \" an escaped quote or a slash and a quote to pass to the sub-shell? If the latter, the equivalent using single quoting would be `'\\"'` (or visa-versa "\\'") which does work as expected, but is annoying to type. The problem only shows up when double quotes (or single quotes: `test \' @('hi') \` gives the same error and stack trace) are used in the `@()` section.

```
$ def __test(args, stdin=None):
     print(repr(' '.join(args)))
$ aliases['test']=__test

$ test \" @("hi") \"
......................................... 
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 154, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 307, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 2334, in p_error
    self.xonsh_code)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 408, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:17: Unmatched ")" at line 1, column 17
![test \" @("hi"]) \"
                 ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../python/35ve/src/xonsh/xonsh/ptk/shell.py", line 100, in push
    locs=None)
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 101, in compile
    tree = self.parse(input, ctx, mode=mode, transform=transform)
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 72, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 212, in _parse_ctx_free
    raise original_error
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 154, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 307, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 2334, in p_error
    self.xonsh_code)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 408, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: \
test \" @("hi") \"

$ test '\\"' @("hi") '\\"'
'\\" hi \\"'
```

**Comment by scopatz** [comment]
> Is \" an escaped quote or a slash and a quote to pass to the sub-shell?

Nope, xonsh has no escape characters outside of strings.  Inside of strings it is the normal, Python string escapes.

This issue is a balancing act.  Having raw backslash escapes is a huge pain on Windows, where backslashes are used everywhere. Also, we'd have to support strings anyway, and so we have to-date decided to keep the model simpler. Some cases such as this one are a little more annoying, but this comes with the benefit of fully avoiding some truly terrible cases.

**Comment by Russell-Jones** [comment]
OK, that makes sense. But it doesn't explain the interaction between `\"` and `@(... " ...)` in sub-shell mode (and the same for single quotes, e.g. `echo \' \@("'")`)

**Comment by scopatz** [comment]
Hi @Russell-Jones-OxPhys - I am not sure I understand your example.  What are you trying to print?  I am not seeing why there is a backslash before the @

**Comment by Russell-Jones** [comment]
@scopatz I guess what I'm asking is why \ has any effect on subsequent use of the character it comes before. I might e.g. want to pass \' as a parameter to a command. Shouldn't xonsh either treat it as an escaped ' or leave it alone? 
I'm not sure why I put \ before @, it may have been so the command would be executed. It doesn't anymore. `echo \' @("\'")` does, and doesn't give an error (outputs `\' '`), but still doesn't quite make sense to me given `echo @("'")` works (outputs `'`), yet `echo \' @("'")` doesn't (SyntaxError).

**Comment by scopatz** [comment]
Yeah, it seems like `echo \' @("'")` should work.  I think this is a bug.

**Comment by scopatz** [comment]
https://github.com/xonsh/xonsh/issues/1390#issuecomment-282507465, I think this can be closed since you should escape quotes with quotes, not with backslashes.

**Comment by scopatz** [comment]
Please feel free to reopen if needed!

**Comment by Russell-Jones-OxPhys** [comment]
Why is it necessary to escape backslashes if they're not used for escaping? Example: 
echo "\\" -> \
echo \ -> .. (incomplete expression)

**Comment by gforsyth** [comment]
Hi @Russell-Jones-OxPhys -- your example is one that is ambiguous between subproc and python commands -- you could be trying to echo a `\` (which you are), but you could also have a variable named `echo` and you are asking Python for a line continuation with a `\`.  
In these situations, `xonsh` follows the general rule that Python always wins, so you need to quote escape the `\` so you don't trigger line continuation. 

Hope that helps, and feel free to close this out yourself if you feel the issue has been addressed.  Thanks!
