### ISSUE TITLE
Mercurial branch is always yellow.

### ISSUE THREAD

**Issue by moigagoo** [xonsh/xonsh#1389]
No matter if the repo is dirty or not, the branch color is always yellow. Confirmed on both release and devel versions.

This should be trivial to fix. I'm posting it so it's not lost.

**Comment by melund** [comment]
This is intended behavior, although we should maybe add a warning the first time it happens. 

Yellow indicate that the branch function stuff has timed out. It was added to ensure that large git or mercurial repos do not slow the prompt. 

You can increase the timeout by changing `$VC_BRANCH_TIMEOUT`

**Comment by melund** [comment]
See: https://github.com/xonsh/xonsh/pull/1166

**Comment by melund** [comment]
On windows `$VC_BRANCH_TIMEOUT` is 0.2 and 0.1 otherwise. Maybe there is a other reason why you suddenly start to see this.

**Comment by moigagoo** [comment]
Thanks for the clarification!

The repo is tiny; it's weird that 0.1 is not enough for the branch function to complete.

Anyway, setting $VC_BRANCH_TIMEOUT to 0.2 did the trick for me, so I'm closing the issue.

Thanks again!
