### ISSUE TITLE
handle multiple python versions on windows

### ISSUE THREAD

**Issue by bj0** [xonsh/xonsh#1395]
I have python2.7 (installed first, in c:\python27) and python3.5 (installed second, in c:\users\...).  Both are in the path, but python2.7 is first.  The following installs xonsh fine:

    pip3 install xonsh

but when trying to run it, you get the error `No module named xonsh`.  It seems it finds the `xonsh.bat` file in the python3 scripts directory, but the script executes the first python.exe found on the path (the 2.7 version).

As a workaround I modified xonsh.bat to:

    @echo off py -3 -m xonsh.main %*

so that it would use pylauncher ([pep397](https://www.python.org/dev/peps/pep-0397/)).  There may be a better way to do this, but using pylauncher in some way might be a good idea because it's included with python starting with 3.3.

**Comment by gforsyth** [comment]
Hey @bj0 -- thanks for reporting this and sorry for the delay in getting back to you!  Your solution seems like a good one to me, but I don't use windows.  Maybe @melund or @BYK can comment on if this is robust?

**Comment by scopatz** [comment]
Also, please feel free to put in a pull request with the proposed change!

**Comment by BYK** [comment]
@scopatz aren't we Python 3.4+ anyways? I think we can rely on pylauncher to exist. I can also probably add some trickery to detect it and fallback to `python` if it doesn't exist. What do you think?
