### ISSUE TITLE
Escape sequences don't work on $PROMPT variable (using prompt-toolkit)

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1403]
if I use echo to print a escape sequence that changes term title:

``` bash
$ echo '\033]0;sadf@saf: asdf\007'

```

it works as expected, changes the term title and doesn't print anything on the screen. On the other hand if I do that on the $PROMPT variable:

``` bash
$ $PROMPT = '\033]0;sadf@saf: asdf\007'
^[]0;sadf@saf: as
```

My prompt becomes corrupted and the title doesn't change. It really looks like \033 is being converted to the ^[ set of chars and not being passed as is to the terminal... but it can be something else

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for bringing this up, @santagada. what is the output of xonfig? Importantly, are you using readline or prompt toolkit?

**Comment by santagada** [comment]
```
$  xonfig
+------------------+----------------+
| xonsh            | 0.4.3          |
| Python           | 3.5.2          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.3          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | True           |
| on linux         | False          |
| on darwin        | True           |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
| git SHA          | None           |
+------------------+----------------+
```

and I'm using prompt-toolkit

**Comment by santagada** [comment]
using readline works... and colors even look better

**Comment by scopatz** [comment]
Ahh yeah, @santagada. The ANSI escape sequences will currently only work with readline.  However, I guess it wouldn't be too hard to add support for ANSI colors to prompt-toolkit either. If anyone is interested, the relevant change would need to happen in `xonsh.pyghooks.partial_color_tokenize()` https://github.com/xonsh/xonsh/blob/master/xonsh/pyghooks.py#L197

I'd be happy to help guide someone through this if they are interested.  I think that most of the tools are there or could be built relatively easily for the common cases.

**Comment by melund** [comment]
So this would also be useful for windows, when the next release comes out. 
I finally got my computer upgraded to windows 10 insider preview. And lo and behold;  ConHost (the windows console) has added support for ANSI escape sequences \o/ 

So now I can run the readline shell on windows with colors. 

![image](https://cloud.githubusercontent.com/assets/1038978/16758046/b5cb9d38-480f-11e6-9ea1-c47995f13a00.png)

It still only supports 16 colors but 256 colors are coming. I am excited to see how @jonathanslenders will support this in prompt_toolkit. I think I will create an issue for it.

**Comment by scopatz** [comment]
Sweet, so I think this is simply missing an implementation ;)

**Comment by anki-code** [comment]
@dyuri does #3690 should close this issue?

I can run starship as $PROMPT but the issue from the first message of this thread is still actual:

![Screenshot_20200919_164953](https://user-images.githubusercontent.com/1708680/93668859-27ec6c00-fa98-11ea-9411-7c2b909e6020.png)

**Comment by dyuri** [comment]
Escape sequences starting with "ESC ]" are not handled by my PR, only those with "ESC [". Supporting them in `tokenize_ansi` should be pretty straightforward, but aren't these replaced/overridden by $TITLE?

**Comment by anki-code** [comment]
@dyuri thank you for the fast response!

In the starship repo there are PR https://github.com/starship/starship/pull/1265 and issue https://github.com/starship/starship/issues/272  about xonsh support where @vladimyr [refer this issue as a blocker](https://github.com/starship/starship/pull/1265#issuecomment-635692495). I think it will be great to add xonsh support to starship and I'm trying to understand does your PR solve the problem.

If the the problem doesn't solved by PR but adding "Esc ]" is "pretty straightforward" it will be great if you do this!

**Comment by dyuri** [comment]
Ok, I'll take a look.

**Comment by dyuri** [comment]
Required a different approach, but now those terminal title setter escape sequences work for me.

**Comment by anki-code** [comment]
@dyuri Wow! You rock! It works for me:
![Screenshot_20200919_220057](https://user-images.githubusercontent.com/1708680/93687081-9a267600-fac3-11ea-9aa2-16dfedad8f3f.png)

**Comment by shadowrylander** [comment]
@anki-code How did you manage to get the prompt properly formatted? I'm stuck like this (`xonfig` in the screenshot):
![2020-10-04-021120_1366x768_scrot](https://user-images.githubusercontent.com/12785394/95008337-08505a00-05e7-11eb-8ccd-e77553abb5db.png)

**Comment by dyuri** [comment]
@shadowrylander what's the value of your evaluated prompt? (`$PROMPT()`)

![image](https://user-images.githubusercontent.com/126637/95009005-c6430a80-061e-11eb-8a2a-3db08e7f54d4.png)

And does it work, if you set something directly, like `$PROMPT="\033[31mthis should be red > "` ?

**Comment by anki-code** [comment]
@shadowrylander first of all install xonsh from master because it's not released yet:
```
pip install -U git+https://github.com/xonsh/xonsh/
```

**Comment by shadowrylander** [comment]
@dyuri Same value as yours, and while the prompt you provided is not red, it does in fact work.

@anki-code Installed the (currently) latest commit `580b675f1a146e7f029eee1b0c1ccc1d770566ab`, but it's still not working for me.

**Comment by dyuri** [comment]
What terminal emulator are you using? It definitely seems to support some kind of formatting.
What if you simply print any string with ANSI color codes? Something like:
![image](https://user-images.githubusercontent.com/126637/95023743-ff12cc00-067e-11eb-91c9-deff40425887.png)

**Comment by shadowrylander** [comment]
Kitty, the GUI accelerated terminal; while the code prints RED, it does not so in, well, red. I'll try with some other terminals!

**Comment by shadowrylander** [comment]
Doesn't work with Alacritty; also, when starting up, xonsh prints `NO_COLOR is deprecated and should be replaced with RESET`. Is this related?

**Comment by shadowrylander** [comment]
Actually, is there a way to check exactly which commit I'm on directly from xonsh, to make sure?

**Comment by shadowrylander** [comment]
Ah; turns out the red color wasn't printing due to my terminal theme; it works fine on Alacritty. But the prompt itself is still not working properly, though.

**Comment by dyuri** [comment]
I'm using `kitty` too, it should support ANSI color codes, so it's strange.
The deprecation warning is in current `master` (might be fixed for the release), it's not related and that version should be fine.

Does executing the command `starship prompt` (w/o setting it as prompt) displays the colored prompt?

**Comment by shadowrylander** [comment]
Exactly as improperly formatted as the xonsh prompt. It seems to work fine with other shells, though, so it doesn't seem to be a problem with starship itself.

**Comment by jonathanslenders** [comment]
FYI: I did not read through the whole conversation, but this could be useful. If you're using the prompt_toolkit ``ANSI`` object, it supports any zero-width escape sequence, if it's wrapped between ``\001`` and ``\002``.
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/formatted_text/ansi.py#L14

**Comment by shadowrylander** [comment]
Unfortunately, I have no idea how to use that here! 😅

**Comment by dyuri** [comment]
That's really strange, if printing the ANSI colored string doesn't work, that's unrelated to the PROMPT issue.
Can you try to display it using `echo` like, and with for example disabling subprocess threading:
```
> echo "\033[31mRED"
RED
> $THREAD_SUBPROCS=False
> echo "\033[31mRED"
RED
```
(For me both prints red "RED".)

**Comment by shadowrylander** [comment]
Quick note: I quickly mentioned before that the red RED not appearing was due to my color scheme in Kitty; Alacritty works fine. However, the prompt itself still messes up, with percentage signs and curly braces all around the prompt.

**Comment by dyuri** [comment]
"Exactly as improperly formatted as the xonsh prompt." < That's why I assumed formatting did not work. Then please try the output of `starship prompt` with subprocess threading disabled. But I don't really have much more ideas.

**Comment by shadowrylander** [comment]
Found the problem; it seems to be somewhat incompatible with the `source-zsh` command? I'm sourcing the `fasd` init script.
