### ISSUE TITLE
feature request: more history control

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1411]
edit: After #1585 The feature request is about changing the `__xonsh_history__` object API to resemble the functionality presented below and __not__ about __adding new syntax__ to xonsh.

bash history expansion has *event designators* which can be specified almost anywhere in the command line and they are references to a cmd entry in the history list i.e:

```
!n     Refer to command line n.

!string
              Refer  to the most recent command preceding the current position
              in the history list starting with string.
!?string
              Refer to the most recent command preceding the current  position
              in  the  history  list containing string.

^string1^string2^
    Quick substitution.   Repeat  the  previous  command,  replacing string1  with  string2.
```

after these event designators you can specify *word designators. which are used to select desired words from the event.  A : separates  the event specification from the word designator.* i.e:

```
!:n            the nth word
!:$            the last word
!:x-y         a range of words
```

any ideas on how can we go about implementing these for xonsh?

**Comment by laerus** [comment]
related to #1221

**Comment by scopatz** [comment]
Thanks for bringing this up, @laerus!  I am not sure that having a special syntax for these things is needed, since each of these cases seems to be do-able at worst by dropping into Python mode with `@()`.  Maybe we need better examples in the translation guide?

**Comment by dylanmc** [comment]
I've got !$ and !* hard-wired into my bash-fingers, so having these work in xonsh would be great. Also :p at the end of a history-modifier prints that item, and adds it to your history, but doesn't execute it - also really useful.

**Comment by scopatz** [comment]
Perhaps we could / should add common Bash idioms like this as a xontrib.

**Comment by laerus** [comment]
my main concern is how we can implement this in a way that it requires a short syntax.

++ for a xontrib that adds common bash idioms like this.

**Comment by laerus** [comment]
@scopatz do you think it would be proper to implement these in the `_` underscore ie:
`_[-1]` is the last command and `_[-1][-1]` is the last argument of the last command etc so we can do something like:
```
$ mkdir /home/laerus/xonsh/test/some_long_dir_name
$ cd @(_[-1][-1])
```

another way would be to change the the `!n` to return the nth command inp without executing.

atm i like the idea of overloading `_` cause i don't think is being used a lot for just accessing the last command which would just change to `_[-1].rtn`

**Comment by scopatz** [comment]
I don't think it is safe to use `_` for this everywhere.  The fact is that `_` already has semantic (if not syntactic) meaning elsewhere in Python.  

`__xonsh_history__` provides an interface for performing all of these actions. However, this is a direct interface to the model. It seems like what people want is a syntax for referring to historical objects, in the same way that `${...}` refers to `__xonsh_env__`.  I think something like this would be good to have...

... However, my personal objection to most of the proposals that I have seen so far either

1. try to replace Python syntax (like here) and Python always wins, or
2. try to emulate Bash's syntax, which I have anecdotally found to be confusing and hard to teach.

So while, I am in favor of an optional Bash-like interface through a xontrib, I think that if xonsh is going to have a history syntax, it needs to be new, clean, and intuitive. Happy to have suggestions.

**Comment by scopatz** [comment]
Until then, people can just use the `__xonsh_history__` API.

**Comment by laerus** [comment]
you're totally right, atm i'm playing around with the `__xonsh_history__` interface trying to implement features like this.

**Comment by laerus** [comment]
the only other syntax i could think of atm is to overload `${}` to handle other builtins like history, or even make it possible to customize it to w/e.

**Comment by scopatz** [comment]
Well, to me, I see `$` as representing the environment, `!` representing subproc mode, `@` as representing python mode.  I think we need another symbol for representing history

**Comment by laerus** [comment]
isnt $( subproc mode too?

can a xontrib introduce new syntax ? i think i'm missing something.

**Comment by scopatz** [comment]
`$(...)` is for subprocesses too, but that was one of the first operators implemented. Also, at least in the core, it has been replaced with `!(...)`

**Comment by laerus** [comment]
i feel like introducing new syntax just for history would be an overkill, same feelings for `${...}` , its very usefull but its not so widely used. A first thought is to make it so `${}` can take flags or something so you can reference builtins in general and not just the envvar table. thoughts on something like this?

**Comment by scopatz** [comment]
> i feel like introducing new syntax just for history would be an overkill

I agree.  But for whatever reason people don't seem to want to use `__xonsh_history__`.  Maybe it isn't well documented enough?  Maybe the Bash compatibility xontrib would go a long way towards helping with this.

> ${...} , its very usefull but its not so widely used. A first thought is to make it so ${} can take flags or something so you can reference builtins in general and not just the envvar table. thoughts on something like this?

Well, `${}` is supossed to be the environment lookup operator from a Python expresssion.  The `...` syntax comes for free because of Python's ellipsis. It is just these two lines: https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py#L781 I don't think it is a good idea to change this operator to do non-env stuff.

**Comment by laerus** [comment]
doing things with `__xonsh_history__` is a little more verbose than what the special bash syntax offers, and there is also the muscle memory of ppl that come from bash.

i feel like the same rules apply to `__xonsh_env__` though, you can do everything without the special `${}` syntax.

**Comment by gforsyth** [comment]
> there is also the muscle memory of ppl that come from bash.

While it's worth considering, I don't think our first (or second, or third) concern should be people's muscle memory.  They can, after all, always stick with bash.  As for grabbing the last argument to the previous command, one possibility is

```console
_.inp.split()[-1]
```

**Comment by laerus** [comment]
you're right @gforsyth, i'm just saying why ppl look for a shorter bashlike syntax. my only concern is that we have special syntax for the environment when we already have the $ and __xonsh_env__ , 3 ways for something that isnt even so widely used, someone can argue that they use history more than ennvars on a daily basis so why not have special syntax for that. And sooner or later someone will want new syntax for something else. so maybe we want to think about having an operator than can be customized or that is more flexible.

**Comment by gforsyth** [comment]
It's a good point, @laerus -- although we are running out of operators...

**Comment by scopatz** [comment]
I am definitely interested in hearing proposals.  Maybe `!{...}` could refer to history?
