### ISSUE TITLE
AttributeError: 'BaseShell' object has no attribute 'cmdloop'

### ISSUE THREAD

**Issue by Kilte** [xonsh/xonsh#1419]
Steps to reproduce: launch Thunar and choose "Open Terminal Here" in context menu.

![Imgur](http://i.imgur.com/uSL8OEg.png)

 xonfig:

```
+------------------+----------+
| xonsh            | 0.4.3    |
| Python           | 3.4.2    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | 2.0.2    |
| on posix         | True     |
| on linux         | True     |
| distro           | debian   |
| on darwin        | False    |
| on windows       | False    |
| on cygwin        | False    |
| is superuser     | False    |
| default encoding | utf-8    |
| git SHA          | g139cb5b |
+------------------+----------+
```

Thunar version: 1.6.3.

"Open Terminal Here" is a predefined [custom action](http://docs.xfce.org/xfce/thunar/custom-actions): `exo-open --working-directory %f --launch TerminalEmulator`

**Comment by scopatz** [comment]
Thanks for reporting @Kilte.  What command is your terminal emulator setup to run?

**Comment by scopatz** [comment]
This doesn't look like it should be possible unless you are setting the shell type to none explicitly somewhere.

**Comment by Kilte** [comment]
> What command is your terminal emulator setup to run?

I've already said, if I unterstood you correctly:

`exo-open --working-directory %f --launch TerminalEmulator`

**Comment by Kilte** [comment]
If I run `exo-open --working-directory /home --launch TerminalEmulator` manually, it works as expected.

**Comment by scopatz** [comment]
Nope, that is what Thunar uses to launch the terminal emulator.  What does the terminal emulator use to launch xonsh?

**Comment by Kilte** [comment]
Gnome Terminal

**Comment by scopatz** [comment]
But how does Gnome terminal launch xonsh, or do you have xonsh as your login terminal?  Also, don't you need to do `=%d` instead of `%f`?

**Comment by Kilte** [comment]
Oh, sorry. Xonsh is my login shell.

>  Also, don't you need to do =%d instead of %f

Doesn't work.

**Comment by scopatz** [comment]
ok, I am going to need more information to help debug this, because this error doesn't make sense to me.  Would you mind please modifying you  xonsh to print out the command line arguments it sees?

**Comment by Kilte** [comment]
I've added the following lines to `/usr/local/lib/python3.4/dist-packages/xonsh/__init__.py `:

```python
import sys

with open('/home/kilte/x', 'w') as __w:
    __w.write(str(sys.argv))

```

And the output is: `['/usr/local/bin/xonsh']`

I'm not sure that it can help, maybe I can try something else?

**Comment by scopatz** [comment]
Can you add the following lines to the `__init__.py` now and report the result:

```python
import xonsh.main
with open('/home/kilte/x', 'w') as __w:
    __w.write(str(xonsh.main.premain()))
```

**Comment by Kilte** [comment]
`Namespace(args=[], cacheall=False, command=None, config_path=None, defines=None, file=None, force_interactive=False, help=False, login=False, mode=<XonshMode.interactive: 3>, norc=False, scriptcache=True, shell_type=None, version=False)`

**Comment by scopatz** [comment]
Ok, can you now try the following, please?

```python
import builtins
import xonsh.main
import xonsh.platform
ns = xonsh.main.premain()
msg = 'best: ' + xonsh.platform.best_shell_type() + '\n'
msg += 'env: ' + str(builtins.__xonsh_env__['SHELL_TYPE']) + '\n'
msg += 'shell: ' + str(builtins.__xonsh_shell__.shell.stype) + '\n'
msg += 'ns: ' + str(ns) + '\n'
with open('/home/kilte/x', 'w') as __w:
    __w.write(msg)
```

**Comment by Kilte** [comment]
`ns = xonsh.main.premain()` throws:
```
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 16630, in main
    args = premain(argv)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 16616, in premain
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 12410, in run
    env = builtins.__xonsh_env__  # pylint: disable=no-member
AttributeError: 'module' object has no attribute '__xonsh_env__'

    env = builtins.__xonsh_env__
AttributeError: 'module' object has no attribute '__xonsh_env__'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 15202, in run
    files = hist.gc.files()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 12435, in files
    xdd = builtins.__xonsh_env__.get('XONSH_DATA_DIR')
AttributeError: 'module' object has no attribute '__xonsh_env__'
```
And `builtins.__xonsh_env__`  also doesn't work.

`xonsh.platform.best_shell_type()` returns `readline`.

**Comment by scopatz** [comment]
@Kilte - where did you add that code?

**Comment by Kilte** [comment]
Same place: [`/usr/local/lib/python3.4/dist-packages/xonsh/__init__.py`](http://pastebin.com/r54PVMiu) at the bottom of the file. Also I've changed `xonsh.main` and `xonsh.platform` to `sys.modules['xonsh.main']` and `sys.modules['xonsh.platform']`, because it doesn't work otherwise.

**Comment by scopatz** [comment]
Oh OK, can you try it, but by putting it before all of the amalgamation stuff, right after the version number please?

**Comment by Kilte** [comment]
Sorry for delay. It doesn't work because `xonsh.main` requires `xonsh.__version__` and (IMHO) it causes something like a deadlock while importing.

I've added the following code to `/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py`:
```
def main(argv=None):
    """Main entry point for xonsh cli."""
    if argv is None:
        argv = sys.argv[1:]
    args = premain(argv)

    # Here:
    print('ns: ' + str(args))
    print('best: ' + best_shell_type())
    print('env: ' + builtins.__xonsh_env__['SHELL_TYPE'])
    print('shell: ' + str(builtins.__xonsh_shell__.shell) + ' ' + str(dir(builtins.__xonsh_shell__.shell)))
    from time import sleep
    sleep(10)

    # ...
```
Result:
```
ns: Namespace(args=[], cacheall=False, command=None, config_path=None, defines=None, file=None, force_interactive=False, help=False, login=False, mode=<XonshMode.interactive: 3>, norc=False, scriptcache=True, shell_type=None, version=False)
best: readline
env: none
shell: <xonsh.__amalgam__.BaseShell object at 0x7fd5105fcbe0> ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_append_history', '_styler', 'buffer', 'color_style', 'color_style_names', 'completer', 'ctx', 'default', 'emptyline', 'execer', 'format_color', 'mlprompt', 'need_more_lines', 'precmd', 'print_color', 'prompt', 'push', 'reset_buffer', 'settitle', 'singleline', 'styler']
```

As you can see `builtins.__xonsh_shell__.shell` has no attribute `stype`, so I decided to show a list of attributes.

**Comment by scopatz** [comment]
OK I think the issue is that something in Thunar is setting the environment variable `SHELL_TYPE` to `none`, which xonsh happens to use.  Can you try using the following in Thunar to launch xonsh:

```
exo-open --working-directory %f --launch TerminalEmulator xonsh --shell-type=best
```

**Comment by Kilte** [comment]
It works! Thank you.

**Comment by scopatz** [comment]
Great! Would you mind adding an entry about thos to our Linux documentation page?

**Comment by Kilte** [comment]
@scopatz, do you mean this [page](https://github.com/xonsh/xonsh/blob/master/docs/linux.rst)? Anyway I can try to do it later.

**Comment by Kilte** [comment]
@scopatz done in #1450

**Comment by scopatz** [comment]
thanks @kilte! glad we could figure this out
