### ISSUE TITLE
rm -i does not prompt

### ISSUE THREAD

**Issue by prabhuramachandran** [xonsh/xonsh#1425]
xonsh is awesome but I am running into a painful annoyance.  I am using xonsh version 0.4.3 on OS X (10.11.5), Python version 3.4.3 via brew and pip installed xonsh.  Here is the issue:

```
$ touch junk.txt
$ rm -iv junk.txt
remove junk.txt? $
```

It does not prompt, this happens with `mv` or `cp` as well. 

Thanks!

**Comment by gforsyth** [comment]
Hey @prabhuramachandran , thanks for reporting this!  This is related to both #741 and #727.  And it is annoying.  Could you also post the output of `xonfig`, please?  This issue seems to affect a strange subset of OS versions.  (Arch and now, apparently, OSX among them)

**Comment by gforsyth** [comment]
@prabhuramachandran -- one more question when you have a moment.  If you set `$XONSH_STORE_STDOUT=True` does the prompt appear?  Thanks!

**Comment by prabhuramachandran** [comment]
Here you go:
```
$ xonfig
+------------------+----------------+
| xonsh            | 0.4.3          |
| Python           | 3.4.3          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.0.2          |
| on posix         | True           |
| on linux         | False          |
| on darwin        | True           |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
| git SHA          | None           |
+------------------+----------------+
```
Aha, yes if i do set `$XONSH_STORE_STDOUT=True` the prompt works!  Thank you!

**Comment by gforsyth** [comment]
Closed via #1436 -- @prabhuramachandran , please reopen if this rears its head again!

**Comment by prabhuramachandran** [comment]
Yes, I can confirm that this works for me, thanks!

**Comment by proboscis** [comment]
The same thing seems to be happening to me on my mac with this xonfig setting.
```
 $ xonfig
+------------------+-----------------+
| xonsh            | 0.4.6           |
| Git SHA          | None            |
| Python           | 3.4.3           |
| PLY              | 3.7             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
 $ $XONSH_STORE_STDOUT
True
```
What seems to be the problem?
