### ISSUE TITLE
Problems with docker bash completion

### ISSUE THREAD

**Issue by xsteadfastx** [xonsh/xonsh#1429]
I have some problems with the docker bash completion. I use [this](https://github.com/docker/docker/blob/master/contrib/completion/bash/docker) file. It works perfectly under bash and zsh. It looks like it does the completion to a stage where it tries to enter the api (thats my guess). It completes for certain options for example:

```
--help
--tls
-D
...
```
But it doesnt if it tries to get the names of the available docker images. Maybe someone has an idea. What i tried so far:

- deleted `~/.local/share/xonsh/bash_completion_cache`
- tried to set `foreign_shell`... im a xonsh beginner and thought it could have something to do with it :-)
- moved the docker bash completion file around to different locations. this didnt helped but that was before i found out that some completions for docker worked.

right now i set up xonsh for all boxes and servers im in control on... im a fan :)

```
+------------------+----------------+
| xonsh            | 0.4.3          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.3          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | True           |
| on linux         | True           |
| distro           | Ubuntu         |
| on darwin        | False          |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
| git SHA          | None           |
+------------------+----------------+
```

**Comment by scopatz** [comment]
Thanks a ton for reporting this @xsteadfastx!

One idea that came up in conversation with @gforsyth yesterday is that maybe we could just have a python completer for docker. That would solve your problem but not whatever the broader underlying problem is.

**Comment by xsteadfastx** [comment]
Oh I would love to try to code that. As a first step into xonsh. :) 

Am 14. Juli 2016 16:52:03 MESZ, schrieb Anthony Scopatz <notifications@github.com>:

**Comment by scopatz** [comment]
@xsteadfastx - great!  

Also, I bet that this is because the completion sets some global state the doesn't transfer from one completion to another.  This seems like it is a bug with that completer and you should raise it there.  I say this because the basic interface works, but you are only having an issue getting the image names.

Also, what happens if you set `$DOCKER_COMPLETION_SHOW_IMAGE_IDS = "all"` before you try to run the completions.

**Comment by xsteadfastx** [comment]
The `$DOCKER_COMPLETION_SHOW_IMAGE_IDS = "all"` has no effect for me. i read now through the code of other xonsh completers and think i can do this. We will see :)

**Comment by xsteadfastx** [comment]
[Here](https://github.com/xsteadfastx/xonsh-docker-tabcomplete) is my work in progress on a xonsh docker plugin. Far from done and im not on my computer this weekend. but next week i will try to get it done.

**Comment by scopatz** [comment]
Sweet thanks! Please open a Pull Request whenever you fell ready

**Comment by scopatz** [comment]
*feel

**Comment by xsteadfastx** [comment]
i uploaded the first alpha 0.1 version:
https://pypi.python.org/pypi/xonsh-docker-autocomplete/0.1

**Comment by laerus** [comment]
cool @xsteadfastx tyvm for this! will try it later today, nom nom

**Comment by scopatz** [comment]
great! please register it! http://xon.sh/tutorial_xontrib.html#tell-us-about-your-xontrib

**Comment by xsteadfastx** [comment]
done :)

**Comment by gforsyth** [comment]
hey @xsteadfastx, can this be closed now?

**Comment by xsteadfastx** [comment]
On Thu, 21. Jul 08:10, Gil Forsyth wrote:
> hey @xsteadfastx, can this be closed now?

i dont know. because the main "problem" is still there. i just try to
work around it with my xontrib completer. i think its a decission for
the maintainers :)

**Comment by gforsyth** [comment]
Ok, well, that's me!  I think @scopatz is right that this is upstream, so I'm going to label this `wontfix` and close it out since we have a functional workaround now.
