### ISSUE TITLE
How do I overwrite an alias with default args

### ISSUE THREAD

**Issue by wreed4** [xonsh/xonsh#1452]
So that's a bad title, but basically, I often have aliases that just supply default arguments to commands.  `ls = ls --color` for example or the like.  The one I'm specifically interested in doing here is `dirs = dirs -v`.  But i'm not sure how to write this.. If I just do it `aliases['dirs'] = "dirs -v"` it breaks saying it can't find the `dirs` command.  

I then tried importing the default dirs alias as `_dirs` and tried a host of things like:
`aliases['dirs'] = "@(_dirs) -v"`, `aliases['dirs'] = "_dirs(['-v'])"` and several others.  I'm sure I'm missing something obvious, but I can't seem to get this to work.  Any thoughts?

**Comment by scopatz** [comment]
Hi @wreed4, you should be able to do something like the following:

```python
from xonsh.dirstack import dirs

def verbose_dirs(args, stdin=None):
    return dirs(['-v'] + args, stdin=stdin)

aliases['dirs'] = verbose_dirs
```

**Comment by wreed4** [comment]
@scopatz Thanks for the quick reply.  A few questions.  First, is there no way to make this on one line? I just like to keep my alias definitions as compact as possible.  I suppose, making this a lambda would work right? so...
```python
from xonsh.dirstack import dirs as d

aliases['dirs'] = lambda a, s=None: d(['-v'] + a, s)
```
I needed to add the "as d" part so the import didn't clobber the alias I was creating.  Also, could I then `del d` for purposes of keeping as clean a namespace as possible? It seems like that doesn't work.  I could keep it out of the global namespace with a function like you did above, but is there a way to do it on one line? 

Lastly, what is the difference between importing `dirs` from `xonsh.dirstack` and importing it from `xonsh.aliases`?

**Comment by scopatz** [comment]
> Also, could I then del d for purposes of keeping as clean a namespace as possible?

No, because Python scoping doesn't work that way.

> It seems like that doesn't work. I could keep it out of the global namespace with a function like you did above, but is there a way to do it on one line?  

With some crazy importlib hacks, yes. But I would recommend against this.

> Lastly, what is the difference between importing dirs from xonsh.dirstack and importing it from xonsh.aliases?

dirstack is where the function is defined.  aliases also imports from dirstack, so importing from aliases is another layer of indirection.
