### ISSUE TITLE
[bug] Error parsing rvm-restart in aliases.py

### ISSUE THREAD

**Issue by neoecos** [xonsh/xonsh#146]
Hi, i think there's a bug, i have rvm installed (rvm.io)

/usr/local/lib/python3.4/dist-packages/xonsh/aliases.py:89: RuntimeWarning: could not parse Bash alias "rvm-restart": ValueError('No escaped character',)
  RuntimeWarning)

**Comment by scopatz** [comment]
Hi @neoecos, what is the alias that you are using?  Also are you on the master HEAD or v0.1.3?  There is a bug related to this (possibly) that we have fixed in master.

**Comment by neoecos** [comment]
Hi, i don't know the alias. I assume is one created by rvm. I'm usiing 0.13 in 0.12 there were no log about this problem.

**Comment by scopatz** [comment]
In bash, what do you get when you type the following:

```bash
$ alias rvm-restart
```

**Comment by neoecos** [comment]
sortiz@mtardis:~$  alias rvm-restart
alias rvm-restart='rvm_reload_flag=1 source
'\''/home/sortiz/.rvm/scripts/rvm'\'''


On Wed, Mar 25, 2015 at 3:44 PM, Anthony Scopatz <notifications@github.com>
wrote:

> In bash, what do you get when you type the following:
>
> $ alias rvm-restart
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scopatz/xonsh/issues/146#issuecomment-86209189>.
>



-- 
Sebastián Ortiz Vásquez.
2015

**Comment by neoecos** [comment]
I also checked running it, and it does !
```
sortiz@mtardis:~$ rvm-restart
RVM reloaded!
```

**Comment by scopatz** [comment]
Ahh yeah, So this bash alias isn't importable into xonsh for a couple of reasons.  (1) it uses source and (2) the quotes are messed up for xonsh syntax.  The warning that you are seeing is xonsh just skipping this alias.  We are working on a mechanism to turn off bash-alias importing, but it is not done yet.  This really does not effect much if you don't use the alias.

**Comment by scopatz** [comment]
Closing due to age. Please let us know if you still are running into this issue.
