### ISSUE TITLE
Customize prompt-toolkit in .xonshrc

### ISSUE THREAD

**Issue by mrapogee** [xonsh/xonsh#1463]
I'd like to bind `jk` to enter normal mode in prompt_toolkit with `$VI_MODE = True`

Is it possible to customize prompt-toolkit right now? I can't find it in the docs.

**Comment by gforsyth** [comment]
Hey @mrapogee -- sorry, no can do at the moment, but it's in the works!

**Comment by scopatz** [comment]
Given the new docs and events, I think this is now available, correct?

**Comment by astronouth7303** [comment]
Given #2193, I think this is closable.

**Comment by scopatz** [comment]
Please feel free to reopen if needed.
