### ISSUE TITLE
Tab not interpreted properly while starting

### ISSUE THREAD

**Issue by urbaniak** [xonsh/xonsh#1469]
I'm not sure it's issue in xonsh or prompt toolkit.

When starting new shell and typing cd /us<tab>loc before it fully loads I'm getting cd /usloc instead of the completed cd /usr/loc.

Other shells like zsh are handling the <tab> character properly while starting.

When xonsh is fully loaded it's working properly.

**Comment by scopatz** [comment]
Thanks for reporting @urbaniak!  I see two options for fixing this:

1. buffer stdin somehow prior to the shell loading.
2. decrease startup times.  I am a little supprised that you are even able to type that much before the shell starts.

What are you startup times like on average?  What is the output of the `xonfig` command for you?

**Comment by scopatz** [comment]
I believe that this has been fixed by #2214. Please feel free to reopen.
