### ISSUE TITLE
Unicode in $TITLE on non-unicode terminals prevents commands from executing

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1471]
If you have Unicode in your prompt (eg 🐚 in your `prompt_end`), and then log in to a non-Unicode terminal (eg, the VT when xonsh is set as your login shell), you're left unable to execute commands.

Specifically, executing `ls` got me this traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13086, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1937, in run_compiled_code
    func(code, glb, loc)
  File "/home/astronouth7303/.local/lib/python3.5/site-packages/xontrib/vox_tabcomplete.xsh", line 1, in <module>
    import os
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15737, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15600, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1471, in _execute_child
    for k, v in env.items()]
  File "/usr/lib/python3.5/subprocess.py", line 1471, in <listcomp>
    for k, v in env.items()]
  File "/usr/lib/python3.5/os.py", line 860, in fsencode
    return filename.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f41a' in position 0: ordinal not in range(128)
```

(This doesn't appear to be the case if you log in with zsh and then execute xonsh. Instead, you just get a box on the prompt.)

**Comment by scopatz** [comment]
What happens if you try something simple, like running `1+1` instead of running a command?

**Comment by astronouth7303** [comment]
Python commands work just fine. No, changing the environment variables doesn't appear to fix this.

**Comment by scopatz** [comment]
Which envvars?  Have you tried changing `$XONSH_ENCODING` and `$XONSH_ENCODING_ERRORS`? http://xon.sh/envvars.html#xonsh-encoding 

Also, could you try starting xonsh with `env $XONSH_DEBUG=1 xonsh` so that we can see where the error is coming from?

**Comment by astronouth7303** [comment]
Have my [`.xonshrc`](https://gist.github.com/astronouth7303/33d5e61cdb1db435526b01ad140f14fb). No, I haven't messed with encoding.

I'll try, but I'm also fighting bugs where i3 won't load if xonsh is my shell (might be the same bug), and chrome locks up if I've ever switched to a vt.

**Comment by scopatz** [comment]
Yeah, luckily this seems like it is pretty self contained bug and does not affect prompt rendering itself.

**Comment by astronouth7303** [comment]
Oh, it totally breaks prompt substitution.

**Comment by astronouth7303** [comment]
Running xonsh from a login zsh prevents this issue (SPIRAL SHELL renders as a lower-half box). Same if I'm using `env` to start xonsh from zsh.

Setting `$XONSH_DEBUG` from the prompt appears to have no effect.

**Comment by scopatz** [comment]
Yeah, you can't set XONSH_DEBUG from the prompt in this case. You have to set it prior to xonsh being started.

**Comment by scopatz** [comment]
...when disabling amalgamation.

**Comment by scopatz** [comment]
Also what are the values of those encoding envvars?

**Comment by astronouth7303** [comment]
Ok, here's the closest thing I can get to the environment as passed by `login`:

```
XDG_VTNR=1
XDG_SESSION_ID=c7
TERM=linux
SHELL=/tmp/env
USER=astronouth7303
MAIL=/var/spool/mail/astronouth7303
PATH=/usr/bin
PWD=/home/astronouth7303
SHLVL=1
XDG_SEAT=seat0
HOME=/home/astronouth7303
LOGNAME=astronouth7303
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
_=/usr/bin/env
```

**Comment by astronouth7303** [comment]
Setting `XONSH_DEBUG` in `/etc/environment` was the best way to do it.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/base_shell.py", line 165, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 63, in run_compiled_code
    func(code, glb, loc)
  File "/home/astronouth7303/.local/lib/python3.5/site-packages/xontrib/vox_tabcomplete.xsh", line 1, in <module>
    import os
  File "/usr/lib/python3.5/site-packages/xonsh/built_ins.py", line 647, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.5/site-packages/xonsh/built_ins.py", line 510, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1471, in _execute_child
    for k, v in env.items()]
  File "/usr/lib/python3.5/subprocess.py", line 1471, in <listcomp>
    for k, v in env.items()]
  File "/usr/lib/python3.5/os.py", line 860, in fsencode
    return filename.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f41a' in position 0: ordinal not in range(128)
```

**Comment by astronouth7303** [comment]
(I've got v0.4.4 released installed. I don't use `HEAD` as my installed shell.)

**Comment by astronouth7303** [comment]
![img_20160722_170516](https://cloud.githubusercontent.com/assets/401438/17071306/b424f8ea-502e-11e6-98b2-55bc5a51be5f.jpg)

(Sometimes, you need to screencap with a camera.)

**Comment by astronouth7303** [comment]
`$XONSH_ENCODING` is reported as `'utf-8'`. `$XONSH_ENCODING_ERRORS` is `'surrogateescape'`.

**Comment by scopatz** [comment]
And what is the output of `xonfig`?

**Comment by astronouth7303** [comment]
(Oh, look, I just triggered a very similar bug with ssh.)

```
+------------------+---------------------------------------------------+
| xonsh            | 0.4.4                                             |
| Git SHA          | None                                              |
| Python           | 3.5.2                                             |
| PLY              | 3.7                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.3                                             |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.1.3                                             |
| on posix         | <xonsh.lazyasd.LazyBool object at 0x7f5ffeb549e8> |
| on linux         | True                                              |
| distro           | arch                                              |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
+------------------+---------------------------------------------------+
```

(Should be default)

**Comment by astronouth7303** [comment]
I'm also able to induce this bug with `ssh localhost` when my login shell is xonsh. No, `ssh localhost xonsh` won't do it.

**Comment by astronouth7303** [comment]
I wrote a script that seems to induce the bug, at least on my machine.

```python
#!/usr/bin/python3
import os
import subprocess

env = {
    'XONSH_DEBUG': '1',
    'XONSH_TRACEBACK_LOGFILE': '/tmp/xonsh-traceback',
    'PATH': '/usr/bin',  # '/usr/bin:/bin:/usr/sbin:/sbin' may also be acceptable
    'SHELL': '/usr/bin/xonsh',
}

envpassthru = {
    'DBUS_SESSION_BUS_ADDRESS',
    'HOME',
    'LOGNAME',
    'MAIL',
    'TERM',
    'USER',
    'XDG_RUNTIME_DIR',
    'XDG_SESSION_ID',
}

for e in envpassthru:
    if e in os.environ:
        env[e] = os.environ[e]

subprocess.call(['xonsh'], env=env)
```

**Comment by astronouth7303** [comment]
So i'm trying to expand that script to including writing a dummy xonshrc so there's less variables. Oddly, this so far is making it behave better.

**Comment by astronouth7303** [comment]
So after experimenting with different features from my xonshrc, I discovered this has to do with the `$TITLE`, not the `$PROMPT`, and I believe the script above will now induce the bug on any system.

**Comment by scopatz** [comment]
It probably has to do with the locale not being set correctly and is not related to the title or the prompt, which I believe are symptomatic.

**Comment by astronouth7303** [comment]
Just setting the `$PROMPT` doesn't cause a problem, though. Setting the `$TITLE` does, regardless of the `$PROMPT`.

The environment that script emulates is based on the ones from `login` (VT) and `ssh`. (I set `env` as my shell and logged in.)

**Comment by astronouth7303** [comment]
Yeah, you're probably right about the misconfigured locale. My investigations lead me to believe that this happens when `sys.getfilesystemencoding()` returns an encoding that doesn't support the full Unicode gamut.

I would assert, though, that this shouldn't leave xonsh in an unusable state. Looking kinda funky? Sure.

**Comment by scopatz** [comment]
Frankly, I just think it is wrong to remove to remove all of `LC_ALL`, `LC_CTYPE`, `LANG`, and `LANGUAGE` from the calling environment: https://docs.python.org/3.5/library/locale.html#locale.getdefaultlocale

Once Python starts up it is impossible to recover from since they purposefully removed the ability to change the default encoding: http://stackoverflow.com/a/17628350/2312428

Thus the calling environment should have at least one of these variables. You can either startup xonsh with something like `env LC_ALL=C.UTF-8 xonsh`, or we can modify `xon.sh` to do this.

**Comment by astronouth7303** [comment]
Wrong or not, that's what I recorded for the calling environment. That's outside of xonsh. Maybe non-Arch systems do set locale in these situations, though.

Maybe the solution is to "fix" the locale in certain circumstances by setting the appropriate environment variables and calling `os.exec*()` to force Python to use them? It sounds hackish, but I'd rather have a hack that lets it be usable than be pure and unusable.

At the very least, it should be documented somewhere that unicode in the title requires the locale to be set.

BTW, the work-around I'm now using is:

```
if sys.getfilesystemencoding() == 'utf-8':
    $TITLE = '\N{SPIRAL SHELL} {current_job:{}:}{cwd}'
```

**Comment by scopatz** [comment]
Potential fix is now available in #1472.  With this you should be able to run xon.sh instead of xonsh and have everything work.  Feel free to open a PR with an os.exec*() solution that is more pure.

**Comment by astronouth7303** [comment]
Yes, #1472 does fix this if `xon.sh` is set as your shell (not currently the recommended method).

Minor comment: Shouldn't `xon.sh` use `exec`?

**Comment by scopatz** [comment]
> Yes, #1472 does fix this if xon.sh is set as your shell (not currently the recommended method).

great! and I don't see why you shouldn't use it if it fixes the problem, at least temporarily,.

> Minor comment: Shouldn't xon.sh use exec?

Probably. Please feel free to put in a PR to that effect!

**Comment by scopatz** [comment]
Also @astronouth7303, feel free to close this issue if you feel it has been resolved on master,
