### ISSUE TITLE
Weird problem using tmux+xonsh+vim

### ISSUE THREAD

**Issue by fisadev** [xonsh/xonsh#1483]
Using tmux with xonsh as the default shell, some vim plugins (so far: syntastic and vim-airline) break with strange error messages. Those plugins work perfectly when other shells (tried fish, zsh, bash) are the default shells on tmux. And they also work perfectly when I manually launch a xonsh shell from inside a different shell (example: fish as default, then run the xonsh command inside fish, then vim inside xonsh). They fail only if I start tmux having xonsh as the default shell in it.

To reproduce the error, you can create a `.tmux.conf` file with this:

```
set-option -g default-shell "/usr/local/bin/xonsh"
```

And use this vim config (it will install the plugins automatically): http://fisadev.github.io/fisa-vim-config

Once you have tmux with its config, and vim with the plugins working, close any tmux sessions, start tmux again, and open vim. You will see this error from syntastic first:

```
syntastic: error: your shell /usr/local/bin/xonsh can't handle traditional UNIX syntax for redirections
```

And an error similar to this from airline:

```
Error detected while processing function airline#extensions#tagbar#currenttag[3]..tagbar#currenttag[16]..<SNR>118_Init[4]..<SNR>118_CheckForExCtags[54]..<SNR>118_ExecuteCtags:
line   26:
E484: Can't open file /tmp/vbAhLLA/1
```

My `.xonshrc` only has aliases and a custom prompt. And I have the following xontribs enabled: mpl, vox, prompt_ret_code, apt_tabcomplete, docker_tabcomplete, vox_tabcomplete, autoxsh.

The versions I'm using:
- Ubuntu 16.04
- Vim 7.4, from the `vim-nox` package (which provides a vim compiled with python 3 support).
- tmux 2.1
- xonsh 0.4.4
- Airline and syntastic plugins latest versions, downloaded automatically by the mentioned vim config (latest version too)

**Comment by PaulReiber** [comment]
Similar problem was reported for fish.

The simple work-around appears to be to tell Vim specifically to use bash:
https://github.com/amix/vimrc/issues/132

...but that really doesn't address the issue, does it?
>xonsh can't handle traditional UNIX syntax for redirections

Indeed - when a xonsh commandline encounters | it doesn't do a pipe - it
does a python OR.

Possibly this is another manifestation of the same problem already
identified here:
https://github.com/xonsh/xonsh/issues/1365


Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
Yeah I am pretty sure this is related to all those issues.

**Comment by fisadev** [comment]
Thanks for the work-around, it appears to solve the problem :)
Regarding fish, at the moment with my setup it's working fine. Probably they fixed/changed something.

**Comment by scopatz** [comment]
Please feel free to reopen if this is still occurring!
