### ISSUE TITLE
Aliased commands don't have autocompletion

### ISSUE THREAD

**Issue by fisadev** [xonsh/xonsh#1490]
This is a feature request, inspired on zsh and fish, which already do this.

If I create this alias:

    aliases['g'] = "git"

I would like to have the proper git autocompletion for the new "g" command. 
Currently if I do:

    git br<TAB>

It correctly completes with "branch". But if I do:

    g br<TAB>

It does nothing.

**Comment by scopatz** [comment]
thanks for reporting! I thought that this used to work, but it might have been lost in the transition to the new completer system.

**Comment by gforsyth** [comment]
this definitely used to work.  The original issue was #391 and it was implemented in #526.  The new completer system seems to have undone some of that.

**Comment by gforsyth** [comment]
Fixed in #1495.  Please reopen if the issue persists.  Thanks!
