### ISSUE TITLE
Possible race conditions on tests

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1494]
I see this three exceptions intermittently when running Xonsh tests:

```
Exception ignored in: <bound method Execer.__del__ of <xonsh.execer.Execer object at 0x110b23208>>
Traceback (most recent call last):
  File "/Users/santagada/devel/xonsh/xonsh/execer.py", line 46, in __del__
  File "/Users/santagada/devel/xonsh/xonsh/built_ins.py", line 751, in unload_builtins
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/abc.py", line 187, in __instancecheck__
AttributeError: 'NoneType' object has no attribute '_abc_invalidation_counter'

```

and:

```
Exception ignored in: <bound method Execer.__del__ of <xonsh.execer.Execer object at 0x7f4e0dd1e908>>
Traceback (most recent call last):
  File "/home/travis/build/santagada/xonsh/xonsh/execer.py", line 46, in __del__
  File "/home/travis/build/santagada/xonsh/xonsh/built_ins.py", line 751, in unload_builtins
TypeError: isinstance() arg 2 must be a type or tuple of types

```

and

```

Exception ignored in: <bound method Execer.__del__ of <xonsh.__amalgam__.Execer object at 0x7f6adbb43128>>
Traceback (most recent call last):
  File "/home/travis/build/santagada/xonsh/xonsh/__amalgam__.py", line 15993, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <generator object get_tokens at 0x7f6ad3559af0>
Traceback (most recent call last):
  File "/home/travis/build/santagada/xonsh/xonsh/__amalgam__.py", line 8852, in get_tokens
TypeError: catching classes that do not inherit from BaseException is not allowed
```

I think the three exceptions look like race conditions on some uninitialised globals. I was thinking of putting None checks in them but a more robust solution seems better.

**Comment by scopatz** [comment]
Thanks for filing an issue @santagada! I think that there is certainly something odd happening in the teardown of the tests.  Also, it is worth noting that these are new with `py.test`, since this stuff didn't seem to happen with nose, or nose was better at hiding it.

**Comment by laerus** [comment]
these are so annoying, i'm returning later today, will try and investigate more. i think we can narrow down the tests that cause these.

**Comment by santagada** [comment]
__del__ can be called later by the gc so this can prove to be hard to find.

I don't think its pytest holding on to some objects... but it can be related to assertion rewrite, let me see if I can test this

**Comment by santagada** [comment]
py.test --assert=plain doesn't change the errors

`py.test tests/test_tools.py` already gives one error in a generator.

digging deeper I got the very strange feeling that inside a `__del__` you can only be sure that your object still exists, everything else might already be deallocated, thats why all the nones. Do we need the `__del__` in most places? I saw a bunch that were related to being deallocated without calling .close() on them.

Seems we have two options, either inside a `__del__` we don't mess with other structures / we check they are not none (and if it calls other code we need to do that inside them as well) or we drop most `__del__` methods and call .close() or other manual methods on those objects.

**Comment by scopatz** [comment]
I think this issue is out of date.
