### ISSUE TITLE
xon.sh command doesn't work on OS X with homebrew

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1502]
my #! line on the xonsh command is correctly set to: #!/usr/local/bin/python3 -u

but for xon.sh it is: /usr/bin/env PYTHONUNBUFFERED=1 python3 -u -m xonsh $@

/usr/local/bin is not on the default $PATH of the system so xon.sh fails. Somehow getting the same value that distutils get for the xonsh script is what we should be using on xon.sh as well.

**Comment by laerus** [comment]
thanks for reporting! a PR for this would be very welcome!

**Comment by santagada** [comment]
anyone with an idea on how does the xonsh binary gets its hashbang? I can definitely work a PR and maybe even with tests 👍

**Comment by scopatz** [comment]
This the fault of distutils / setuptools. Here are some potential fixes: http://stackoverflow.com/questions/1530702/dont-touch-my-shebang

**Comment by scopatz** [comment]
This answer is probably the best: http://stackoverflow.com/a/33345596/2312428

**Comment by santagada** [comment]
@scopatz What I need is to do the inverse right? To actually get the modified shebang line and/or find the full path to the python binary running the install.

**Comment by scopatz** [comment]
Oh yeah, that is right.  `sys.executable` gives the full path to the Python executable you are running with, if you need it.  We should probably have something similar for xonsh...

**Comment by santagada** [comment]
closed with the merge of #1510
