### ISSUE TITLE
sys.stdin tab completes to sys.stdin[

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1508]
`sys.stdin` tab completes to `sys.stdin[`. I don't see why you would ever want to automatically complete a square bracket, but for sys.stdin it especially doesn't make sense, since it isn't indexable.

**Comment by gforsyth** [comment]
Thanks for reporting, @asmeurer -- I think there's a bigger question here, too, of whether python-mode completions should extend to the opening container character, be it a `[` or a `(`.  

But yeah, I think square brackets shouldn't be part of the completion

**Comment by asmeurer** [comment]
I don't like that but maybe other people do.

**Comment by laerus** [comment]
+1 for changing this

**Comment by scopatz** [comment]
Pull requests welcome!
