### ISSUE TITLE
xonsh does not restore terminal settings correctly on exit

### ISSUE THREAD

**Issue by PaulReiber** [xonsh/xonsh#1509]
I've determined what's at the heart of some odd recent xonsh-related behavior.

> $ /bin/cat
> this works correctly
> this works correctly
> $xonsh
> ...{xonsh prompt}... $ exit
> $ /bin/cat
> tthhiiss  ddooeess  nnoott wwoorrkk ccoorrrreeccttllyy
> 

When it exited, xonsh left my terminal in a different mode than it was initially - and that mode's pretty broken.  To save you some time cross-comparing... the particular settings of concern are on the final line, beginning w/ isig.

> pbr@mongo:~$ stty -a
> speed 38400 baud; rows 38; columns 138; line = 0;
> intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
> rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
> -parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
> -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon ixoff -iuclc -ixany -imaxbel -iutf8
> opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
> isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
> pbr@mongo:~$ xonsh
> pbr@mongo ~ $ exit
> 
> pbr@mongo:~$ stty -a
> speed 38400 baud; rows 38; columns 138; line = 0;
> intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
> rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
> -parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
> -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon ixoff -iuclc -ixany -imaxbel -iutf8
> opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
> -isig -icanon -iexten echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt -echoctl -echoke
> pbr@mongo:~$ 

...Maybe related to how xonsh is using readline?  Let me know if you'd like further testing done.

**Comment by PaulReiber** [comment]
when cat is doubling up the characters  it's also ignoring control-D and control-\ and control-C 

Related to not getting the terminal settings right at exit - it doesn't seem to have them right for regular processes getting run and using stdin either.

I.e. this is why the following hangs until I re-establish an ssh connection:

> pbr@mongo:~$ xonsh
> pbr@mongo ~ $ x=$(cat)
> this is a test
> ...nothing except ~. works here... not control-C, not control-\, not control-D... nothing....
>

**Comment by PaulReiber** [comment]
pbr@mongo:~$ diff stty.sane stty.post_xonsh 
9,10c9,10
< isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
< echoctl echoke
---
> -isig -icanon -iexten echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt
> -echoctl -echoke

Settings which are left in a state different from the recommended "sane" are:
isig icanon iexten echoe echok echoctl and echoke

**Comment by scopatz** [comment]
Thanks for reporting @PaulReiber Do you have any idea of what is causing this?  If it is readline, does this not occur under prompt-toolkit, for instance?

**Comment by PaulReiber** [comment]
Having just upgraded the universe, and recompiled xonsh, I'm no longer seeing the problem.

I'm chalking this up to a bad local build environment. Closing.  Sorry 'bout that.

**Comment by scopatz** [comment]
No worries! It is certainly possible it was a bug that was accidentally fixed :)
