### ISSUE TITLE
vox deactivate no longer resets my path

### ISSUE THREAD

**Issue by wreed4** [xonsh/xonsh#1513]
`which python3` returns the same thing before and after `vox deactivate` now.  `vox activate` correctly changes it, but `vox deactivate` no longer puts it back.  I am on the newest label of xonsh.

**Comment by scopatz** [comment]
Thanks for reporting @wreed4!  Pull requests most welcome for this for any vox users out there...

**Comment by astronouth7303** [comment]
I can confirm. I guess I broke something in that rewrite...

**Comment by wreed4** [comment]
I also have reason to believe it's not correctly setting the import path.  When I launch bash and source the activate script in my virtualenv myself, I can import a specific module.  But when running `vox activate` from xonsh, I cannot import this module.  In both cases, i'm trying to import from within the `python3` shell (which is the correct virtualenv path in both cases).

**Comment by wreed4** [comment]
I take it back.  This seems to have been a symptom of my company's environment.  They break our path periodically in tmux sessions. So I just had to restart my tmux server.  very annoying, but not Xonsh's fault.

**Comment by scopatz** [comment]
glad it was figured out
