### ISSUE TITLE
Invalid sys.argv when running a xonsh script

### ISSUE THREAD

**Issue by SirNickolas** [xonsh/xonsh#1515]
```sh
$ cat test.py
#!/usr/bin/env python3
import sys
print(sys.argv)
$ ./test.py --hello world
['./test.py', '--hello', 'world']
$ python3 test.py --hello world
['test.py', '--hello', 'world']
$ sed -i s/python3/xonsh/ test.py
$ ./test.py --hello world
['--hello', 'world']
$ xonsh test.py --hello world
['--hello', 'world']
$ execx($(cat test.py))
['/usr/local/bin/xonsh']
$
```

As you can see, program name is not passed into `argv[0]`. This behaviour differs from *every other* existing programming language, including Python. Thus, none of the option parsing libraries work with default settings, since they try to use `sys.argv[1:]`.
Hoping this is a bug that's going to be fixed, I'm using the following workaround for now:

```py
if semver.match(re.search(r"([\w.-]+)\W*$", $(xonsh --version)).group(1), "<=0.4.4"):
    args = sys.argv
else:
    args = sys.argv[1:]
```

By the way, why does `xonsh --version` print a `repr` of a tuple?

**Comment by laerus** [comment]
Hey @SirNickolas thanks for reporting! This is an issue that was bugging me for some time, you can expect a fix soon or even try for a PR.
