### ISSUE TITLE
Remove Anaconda Build

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1522]
Since it is going to be removed https://www.continuum.io/blog/developer-blog/powering-down-the-anaconda-build-ci-system

**Comment by melund** [comment]
Ah. I thought it was coming. Conda-forge rules... I will take a look at removing it.

**Comment by scopatz** [comment]
Much agreed.  It would be nice if we could figure out better integration with conda-forge to build dev packages (and also release packages ~_~).  For now though, a simple removal is probably enough...  Thanks @melund!

**Comment by melund** [comment]
Yes. We could maybe get something similar with Travis/CircleCI/AppVeyor. Anyway, the dev builds wasn't used by many. So I think we can safely remove them.
