### ISSUE TITLE
Suggestion: Add fallback shell

### ISSUE THREAD

**Issue by derphilipp** [xonsh/xonsh#1525]
As xonsh fails if a configuration error exists, it would be nice to define a fallback shell that would be used if xonsh crashes / can not start.

This could lead to more adopters being able to set xonsh as their default shell.

**Comment by xsteadfastx** [comment]
Thats a good idea. I had the problem when my filesystem got remounted read-only and it couldnt write the history file no more. no chance to login. happily i had a ssh server open and could `ssh foo@bar /bin/sh` into it.

**Comment by scopatz** [comment]
I am definitely in favor of this idea. It just needs an implementation.  PRs welcome!

**Comment by PaulReiber** [comment]
Logistically, one can't guarantee a fallback would even work - the fallback
shell could easily be affected by the same problem Xonsh faced.

Scope/responsibility wise, the OS defines the users shell - it's there, not
within Xonsh, that one might introduce a fallback feature/capability.
Interesting idea, but it'd be down to init/login/getty to do the right
things when a user shell gets hung - not the user shell itself.

It's easy enough to ensure a user can login via another shell.

A Xonsh user can have multiple entries in /etc/passwd to ensure they can
always login with another shell:

pbr:x:1000:1000:Reiber Labs,,,:/home/pbr:/usr/local/bin/xonsh
pbrbash:x:1000:1000:Reiber Labs,,,:/home/pbr:/bin/bash

Note the UID and home directory are the same - these are effectively the
same user, just logging in using different shells.

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
> Logistically, one can't guarantee a fallback would even work - the fallback
shell could easily be affected by the same problem Xonsh faced.

I agree that this isn't about gaurantees.  Rather it is about "Oh no!" moments and debugging.  If dropping into a backup shell works, great! If not, then things were broken already.  The backup shell would still be run from within the xonsh process, so I don't see this as stepping on the toes of the OS.

**Comment by asmeurer** [comment]
Most terminal emulators let you define different profiles that start different shells. Maybe this is useful for ssh, though?

**Comment by asmeurer** [comment]
Also, I'd argue that xonsh already does have a backup shell, namely, itself. If .xonshrc can't be loaded, it falls back to xonsh with no configuration.

**Comment by scopatz** [comment]
@asmeurer Yes, I agree that should be the correct behaviour for configuration for configuration failures.  But what about if there is a bug in xonsh itself that is triggered by something else on the system.  A fallback shell could still be useful so that one could fix the system.

**Comment by xsteadfastx** [comment]
On Wed, 03. Aug 10:39, Paul Reiber wrote:

> A Xonsh user can have multiple entries in /etc/passwd to ensure they can
> always login with another shell:
>
> pbr:x:1000:1000:Reiber Labs,,,:/home/pbr:/usr/local/bin/xonsh
> pbrbash:x:1000:1000:Reiber Labs,,,:/home/pbr:/bin/bash

This blew my mind. Never thought about this. I will try this today.
Maybe thats a good way to work around some ansible exec problems. Yeah!

**Comment by mitnk** [comment]
@PaulReiber @xsteadfastx Wow! this tip works great! Thanks!

Steps for who want try this out - manually update file `/etc/passwd` add a aliased user with a different shell. Then do a `sudo passwd <user-aliased>` to make aliased user to be login-able. (At least I have to do a `passwd` to make it work).

**Comment by mitnk** [comment]
This issue should have been addressed by #2020, closing now. Feel free to reopen. Thanks @derphilipp
