### ISSUE TITLE
Piping does not work as expected

### ISSUE THREAD

**Issue by Droggelbecher** [xonsh/xonsh#1526]
```
$ echo Hello | less
```

Expected: The well-known pager "less" runs, displaying "Hello".
What does happen: Nothing except for a short screen flicker.

Xonsh version: 0.4.4 on Ubuntu.

If there is a good reason why this behavior is like this (and you guys think it should stay that way), I would expect some remarks about that in the documentation, e.g. in the tutorial section that suggests that pipes work like in bash as long as you are in subprocess-mode.

PS: Despite little issues like these I still love this shell, please keep up the good work <3

**Comment by Droggelbecher** [comment]
Sorry for the wrong report, seems to work fine with latest git master, nvm!

**Comment by scopatz** [comment]
Thanks for reporting anyway @Droggelbecher!
