### ISSUE TITLE
Add Appveyor to PRs?

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1528]
Could you add AppVeyor to the pull request test suite per http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests#comment_33212404 ?

This way, contributors get a more pro-active notification if tests break.

**Comment by melund** [comment]
I thought it was already configured like that, but apparently, it was only for the old inactive appveyor account. I think it should be good now.
