### ISSUE TITLE
Functional testing for Xonsh

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1531]
This is more of a feature request, have functional tests using pexpect or similar to start xonsh to see if it is running fine and not emitting errors when starting or executing a set of actions (eg xonsh -c 'ls -l' or xonsh -c '$VAR="hi"; echo $VAR'

**Comment by laerus** [comment]
I think we can test these cases without pexpect. The hard part would be to test xonsh without the `-c` a.k.a we need tests for the Shell.

**Comment by astronouth7303** [comment]
You should be able to test commands with something like:

```python
def test_ls(xonsh_execer):
    result = xonsh_execer.eval("ls -l")
    assert result
```

I think `result` will always be a [`CompletedCommand`](http://xon.sh/api/proc.html#xonsh.proc.CompletedCommand).

**Comment by scopatz** [comment]
We now how tests in this vein in the `test_ingrations.py` file. Please feel free to reopen if this is not sufficient for some reason.
