### ISSUE TITLE
imphooks not automatically loaded

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1535]
Xonsh does not currently load the `.xsh` import machinery (`xonsh.imphooks`) automatically. This causes xontribs authored in xsh to not be found or loadable by `xontrib`.

I [made a test](https://github.com/xonsh/xonsh/compare/master...astronouth7303:test-xsh-xontrib) for the xontrib problem.

This is affecting @Siecje contributing the prompt-ret-code xontrib.

**Comment by astronouth7303** [comment]
I'm sure there just needs to be a `import xonsh.imphooks` in `__init__.py`, but i'm not sure how to properly flag it for flake8 and amalgamate.

**Comment by Carreau** [comment]
And that was removed in #1446 ... I'll send a fix.

**Comment by astronouth7303** [comment]
Thanks, @Carreau! Please kindly include the test?

**Comment by Carreau** [comment]
> Thanks, @Carreau! Please kindly include the test?

Yes, of course. Done.

**Comment by Carreau** [comment]
> Thanks, @Carreau! Please kindly include the test?

And thanks a lot for writing them !
