### ISSUE TITLE
iTerm2 Unicode 9.0 support

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1539]
Since the latest wcwidth supports Unicode 9.0 (which makes emoji double-width), you can pass a special escape sequence to iTerm2 to tell it that Unicode 9.0 is supported. See https://gitlab.com/gnachman/iterm2/wikis/unicodeversionswitching. It's only supported in the nightly builds thus far.

**Comment by astronouth7303** [comment]
Hmmm... General question for core devs.

Should terminal-specific features be in xontribs or core? Like, the current directory stuff (OSC 7) is core because many many terminals support it.

**Comment by scopatz** [comment]
@astronouth7303 I think it really depends on how common the feature is.  For things like iTerm2 support, I think this should be a xontrib. For things like colors, which are pretty much in all modern terminals, that should come stock.

**Comment by santagada** [comment]
and as there is no obvious improvement to jump to unicode 9 right now, we should just document how to pin wcwidth to an older release.

**Comment by scopatz** [comment]
@santagada I agree documentation to this effect seems like the right way to go for the moment.

**Comment by asmeurer** [comment]
Unicode 9 support is preferred if possible. The emoji characters are double width, meaning they render properly in the terminal (they don't overlap each other).

**Comment by astronouth7303** [comment]
@asmeurer which terminal? Most terminals do _not_ handle emoji correctly.

**Comment by asmeurer** [comment]
Right now, only the nightly version of iTerm2 (although I believe a release is coming soon). But as I noted in the OP, there is a special escape sequence you can send to make it only work in compatible versions (there's also some escape sequence you can send to check if you are in iTerm2 and what version, but I don't remember what they are). 

Only since Unicode 9.0, which was just released earlier this year, have emoji even been set by the standard as double width. So it will take while for terminals to keep up.

**Comment by santagada** [comment]
There is no way to choose unicode <9 on newer versions of wcwidth, so using this will change our support from all terminals to only working correctly on iterm2. Right now there is workaround for using emojis on all terminals that support them (using a space or nonbsp). 

If someone contributes a way to choose unicode version on wcwidth and a way to detect/whitelist terminals that support unicode 9, it would make sense to add this, until then unicode < 9 and wcwidth < 0.1.7 is the solution we can use.

**Comment by santagada** [comment]
Sorry, I might have raised the bar too high for no good reason. My last considerations are for what I think is necessary for something to be in core xonsh (but I'm no judge of that).

When we document this as installing prompt-toolkit right now defaults to wcwidth that uses unicode 9 and breaks in most terminals we can certanly document it as such:

Install prompt-toolkit and wcwidth 0.1.6 or if your terminal supports unicode 9 add this line to your .xonshrc:
echo <unicode escape>9

or something like it, then people that wants to use unicode 9 can.

**Comment by scopatz** [comment]
I think this is more or less an upstream and xontrib issue
