### ISSUE TITLE
Pretty print alias

### ISSUE THREAD

**Issue by wreed4** [xonsh/xonsh#1540]
I really like the way that when you just type a variable name on the command line, the output is colorized nicely.  But, I noticed that the command line calls `repr()` instead of `str()`.  This makes perfect sense and seems like a sound design decision.  However, in the case where my object that i'm working with has a simple, unambiguous `__repr__` like `"Object(15, 32)"` and a more verbose `__str__` like `"val1: 15\nval2:32"`, I would like to be able to get the same nice coloration for `str(obj)` that I do with just `obj`.  

I'm at somewhat of a loss as to how to implement this alias (it could be a function I suppose or whatever, and alias just makes more sense to me for command line use).  It should take a command (python or system, though python is more important... actually maybe it only makes sense for python???) and print out the colorized output.  This is what I have so far..

``` python
from xonsh.tools import print_color
from xonsh.lazyimps import pygments, pyghooks

def _pp(args, stdin=None):
    pval = pretty(eval(" ".join(args)))
    tokens = list(pygments.lex(pval, lexer=pyghooks.XonshLexer()))
    print_color(tokens)
```

This throws a `SyntaxError` when doing something like `pp str(obj)`.  The syntax error is in prompt_ret_code, so I can try removing that xontrib to see what the real problem is.  

I'm not married to this implementation or anything about it really.  I just want a way to get nice colorized output for `__str__()` as well as `__repr__()` in a non-verbose way.  Any thoughts?

**Comment by astronouth7303** [comment]
`pp str(obj)` mixes Python and subcommand mode; it'll never work.

In fact, an aliases are always handed strings, never objects. You just want a normal Python function, so `pp = pprint` in your `.xonshrc` is the best you got.

There is an argument to be made for the ability for xontribs to modify/replace the formatter. (No, I don't think this should be an event.)

**Comment by wreed4** [comment]
> `pp str(obj)` mixes Python and subcommand mode; it'll never work.

I can accept this, but it's a little odd to me as the alias calls a python method, so I don't really see why it wouldn't just be the same as calling a python method.  But I can accept this is not the case. I'm fine with making it a function.  
> `pp = pprint`

Where are you getting `pprint` from here though? That's my question.  What function or series of functions would I have to call to get a string to print the way `__repr__` does automatically?

**Comment by astronouth7303** [comment]
It's an example. Python includes a `pprint` module, although I don't think it has colorization options.

**Comment by wreed4** [comment]
I was specifically wondering how to get the colorization that xonsh uses.

**Comment by astronouth7303** [comment]
https://github.com/xonsh/xonsh/blob/master/xonsh/pretty.py

**Comment by wreed4** [comment]
Thanks for the link.  That seems to suggest that my current implementation would work however. And it doesn't.  I've changed my implementation slightly from above in response to your comment about aliases being impossible here. 

```python
def pp(s):
    pval = pretty(s)
    tokens = list(pygments.lex(pval, lexer=pyghooks.XonshLexer()))
    print_color(tokens)
```

Is there anything you see that I'm doing wrong? When I do `pp(str(a))`, I just get a string.  when I do `pp(a)`, I do get colored output, but for the `__repr__` function.  I'd like to pass `pp` a string, if possible.

**Comment by melund** [comment]
@wreed4 You are almost there. 

@astronouth7303 is not quite right when he says you can't mix python and subproc mode. It is correct that subproc mode can only pass string arguments, but you can use those arguments to look up the variable in the xonsh context dictionary. 

Here is a simple example that does what you want. Color `str()` representations of objects. 

 ```
from xonsh.tools import print_color
from xonsh.lazyimps import pygments, pyghooks

def _pp(args, stdin=None):
    val = str(__xonsh_shell__.shell.ctx[args[0]])
    tokens = list(pygments.lex(val, lexer=pyghooks.XonshLexer()))
    print_color(tokens)

aliases['pp'] = _pp
del _pp
```

**Comment by wreed4** [comment]
It works!! Thanks! 

So the main difference is you're not calling `pretty` on it? I would have thought that was an important part. But I suppose that calls `__repr__` which is why I was getting a colored string and not the output I wanted.

**Comment by melund** [comment]
Yes. pretty does not use the `__str__` method. The difference is also that I lookup the variable in `__xonsh_shell__.shell.ctx`

**Comment by scopatz** [comment]
Also, I believe that `__xonsh_shell__.shell.ctx is __xonsh_ctx__`, if you wanted something shorter
