### ISSUE TITLE
"bin/some_binary" parsing

### ISSUE THREAD

**Issue by Droggelbecher** [xonsh/xonsh#1541]
I have several scripts under ~/bin, I have the habit of calling them from my home directory like this:

```
bin/some_script
```
This gets parsed as python (as 'bin' exists and is the function that gives you a binary representation of an int).
I don't know the exact rules by which this is decided but it seems that xonsh cares whether the first subexpression ("bin") is in the python namespace, but does not care for the rest ("some_script"), which seems odd. Is there a specific reason for this?

Now I know there's several ways to avoid the issue such as
```
./bin/some_script
~/bin/some_script
![bin/some_script]
...
```

I guess my questions on this are however:

1. Is there any hope the xonsh parser will be smart enough to figure out that although "bin/some_script" is syntactically correct python it will not work and should be tried rather as a subprocess?
2. Why is it that only the first subexpression is tested? Eg. "foo/bar" seems to be considered python iff "foo" is in the python namespace and doesn't care at all about "bar". Whats the rationale behind this?
3. Would it be wise to do something like "del bin" in xonshrc?
4. If I did that, how could I make bin still be available in (explicit) python mode? Preferrably without renaming it in order to not break scripts/code snippets/etc...

**Comment by gforsyth** [comment]
Hi @Droggelbecher!  Sorry for the delay in getting to this.  

> Is there any hope the xonsh parser will be smart enough to figure out that although "bin/some_script" is syntactically correct python it will not work and should be tried rather as a subprocess?

Mmm, probably not?  We have a strict "Python always wins" policy when it comes to python/subprocess mode conflicts and `bin` is valid Python, so it's always going to try to parse it as such.  

> Why is it that only the first subexpression is tested? Eg. "foo/bar" seems to be considered python iff "foo" is in the python namespace and doesn't care at all about "bar". Whats the rationale behind this?

As per http://xon.sh/faq.html:
```
While the grammar of the xonsh language is context-free, it was convenient to write the executer in a way that is slightly context sensitive. This is because certain expressions are ambiguous as to whether they belong to Python-mode or subprocess-mode. For example, most people will look at ls -l and see a listing command. However, if ls and l were Python variables, this could be transformed to the equivalent (Python) expressions ls - l or ls-l. Neither of which are valid listing commands.

What xonsh does to overcome such ambiguity is to check if the left-most name (ls above) is in the present Python context. If it is, then it takes the line to be valid xonsh as written. If the left-most name cannot be found, then xonsh assumes that the left-most name is an external command. It thus attempts to parse the line after wrapping it in an uncaptured subprocess call ![]. If wrapped version successfully parses, the ![] version stays. Otherwise, the original line is retained
```

I think the short answer is: the more context-sensitive parsing we do, the harder and slower everything gets.

> Would it be wise to do something like "del bin" in xonshrc?

I don't think it would be disastrous.

> If I did that, how could I make bin still be available in (explicit) python mode? Preferrably without renaming it in order to not break scripts/code snippets/etc...

Mm, yeah, that's tricky.  I don't know how you can have commands mean different things in different contexts.  That's sort of the thing we're trying to stop with xonsh.  

Muscle memory is a force to be reckoned with, but I think the simplest solution to your problem is just to add `~/bin` to your `$PATH`.

**Comment by scopatz** [comment]
Thanks for the great response @gforsyth! And again, sorry for the delay @Droggelbecher.  I'll be a little more hopeful.

I *think* it could be possible to loosen the leftmost name restriction to instead check that all names in a Python expression are in scope. Arguably, the expression would be fail if they weren't all in scope.  In the case where not all names are available, then we can proceed as now by trying to wrap in a subprocess. 

Of course, this wouldn't help at all for totally degenerate cases such as `bin/dir`, but it should expand the number of cases that are covered 'correctly'.

**Comment by scopatz** [comment]
An implementation is now available in #1604

**Comment by scopatz** [comment]
@Droggelbecher Master should now support the majority of your use cases. Please feel free to try it out and/or close this issue

**Comment by laerus** [comment]
this is fixed for me on latest master,
```
>>> pwd
/home/laerus/lab
>>> ls -d bin
bin
>>> bin/skata
>>> pwd
/home/laerus/lab/bin/skata
```
closing this feel free to reopen though.

**Comment by Droggelbecher** [comment]
Fixes for me as well, thanks!
