### ISSUE TITLE
Could not create '.git/index.lock': File exists.

### ISSUE THREAD

**Issue by Droggelbecher** [xonsh/xonsh#1542]
The above error message happens to me a lot when running git commands since using xonsh. Apart from the xonsh prompt I there is no other process meddling with my repo that could be responsible for it.

Although frequent enough to be remarkable, it does not seem to occur deterministically, but has a random component (maybe a timing/parallelization issue?).

**Comment by laerus** [comment]
I get that too from time to time, never thought it is cause of xonsh. You can try using `fuser` or `lsof` on the file when it happens to see what os holding it. maybe this happens cause of the branch prompt mechanism allthough this is just a guess.

**Comment by astronouth7303** [comment]
I also get this intermittently. I'm using this work-around:

```python
def _gitfix(a, s=None):
    if !(pidof git):
        return "", "Git is currently running; cowardly refusing\n", 1
    elif not os.path.exists('.git/index.lock'):
        return "", "No fixing required\n"
    else:
        ![rm .git/index.lock]
aliases['fixgit'] = _gitfix
```

So far, it hasn't cowardly refused.

**Comment by mitnk** [comment]
Remove git related info from your xonsh prompt :)

**Comment by astronouth7303** [comment]
Does `xonsh.environ.current_branch()` kill the process if it times out?

**Comment by laerus** [comment]
Doesn't seem so. `get_git_branch` uses `subprocess.check_output` and even though python docs explicitly say that `subprocess.run` kills the child proc on timeout, it doesn't say anything about `checkout_output` except that the signature is the same. The `timeout` parameter is passed on  `Popen.communicate` that explicitly states 

> If the process does not terminate after timeout seconds, a TimeoutExpired exception will be raised. Catching this exception and retrying communication will not lose any output.
> 
> The child process is not killed if the timeout expires, so in order to cleanup properly a well-behaved application should kill the child process and finish communication

so we may have to look a little deeper in the CPython source except if someone knows what's going on.

**Comment by astronouth7303** [comment]
I'm pretty sure killing `git` would cause this problem.

**Comment by scopatz** [comment]
I believe that this is because of the timeout.  You can fix this either by removing the version control stuff from the $PROMPT or by bumping the timeout length with `$VC_BRANCH_TIMEOUT` http://xon.sh/envvars.html#vc-branch-timeout 

A fix that cleans up the lock file in the event of a time out (if it exists) would be most welcome!

**Comment by astronouth7303** [comment]
So I went investigating how exactly git computes the git directory (potentially non-trivial with multiple workspaces), and I came upon the [lockfile API](https://github.com/git/git/blob/c2c5f6b1e479f2c38e0e01345350620944e3527f/lockfile.h).

If I'm reading this right, read-only operations shouldn't be locking anything, and `index.lock` should only be set by commands such as `git add` that modify the index (where changes are staged before commit).

**Comment by scopatz** [comment]
Well, the lockfile might be created if your CWD is dirty or something.

**Comment by gforsyth** [comment]
Hi @Droggelbecher -- are you still seeing this behavior semi-regularly?

**Comment by rnovacek** [comment]
I still do see this issue quite often (like once a day) with xonsh==0.4.5 from PyPI.

**Comment by laerus** [comment]
i think we should deprecate/remove `get_git_branch` in `xonsh.prompt.vc_branch` in favor of `gitstatus` of `xonsh.prompt.gitstatus` which seems more robust and see if this fixes this.

**Comment by gforsyth** [comment]
that sounds good to me

**Comment by Droggelbecher** [comment]
Sorry for the late reply, just updated xonsh to latest git master, let me know if I should try anything or you need more info

**Comment by ns-phennessy** [comment]
is this issue considered fixed? 

i'm running `xonsh/0.4.6`

**Comment by scopatz** [comment]
I believe that this was fixed, if not in v0.4.7, then on master

**Comment by brianmay** [comment]
I am seeing this behaviour in 0.5.9 on OSX. Only happens if ``{gitstatus}`` is in the prompt.

**Comment by arkhan** [comment]
i have this problem in the last xonsh release

**Comment by laerus** [comment]
hey @arkhan  are you using `gitstatus` aswell?

**Comment by brianmay** [comment]
I personally solved it by modifying my ``config.json`` as follows:

```
{
    "env": {
        ...
        "VC_BRANCH_TIMEOUT": 0.5
    },
    ...
}
```

**Comment by arkhan** [comment]
@laerus, yes
