### ISSUE TITLE
Xonsh editable install does not load importhooks

### ISSUE THREAD

**Issue by Carreau** [xonsh/xonsh#1543]
In particular, as the dev install does not use amalgamate, the `sys.modules` ends up missing the following imports:

```
['xonsh.contexts',
 'xonsh.imphooks',
 'xonsh.completers.__amalgam__',
 'xonsh.tracer',
 'xonsh.__amalgam__',
 'xonsh.readline_shell',
 'xontrib.prompt_ret_code',
 'xonsh.ansi_colors',
 'xontrib.xonda'] 
```

and in particulat  `xonsh.imphooks` [which](https://lh3.googleusercontent.com/-5GTvwtJHZdU/TXmQM8FCatI/AAAAAAAAKko/hpQvPGuyz0k/I+Am+Not+A+Witch+-+Monty+Python+and+the+Holy+Grail.jpg) makes `xontrib/*.xsh` to  not be able to be imported. 

Not sure if it's an https://github.com/xonsh/amalgamate bug as well, as it shoudl not have found imphooks as it's imported nowhere else...

**Comment by laerus** [comment]
i'm running develop mode and i can still load xontribs.

**Comment by Carreau** [comment]
> i'm running develop mode and i can still load xontribs.

Can you see where `xonsh.imphooks` is loaded from, so that I can diagnose why my system does not import it?

I don't find any place where these are loaded from:

```
$ grep -r imphook **.py
tests/test_imphooks.py:from xonsh import imphooks  # noqa
xonsh/__init__.py:        imphooks = __amalgam__
xonsh/__init__.py:        _sys.modules['xonsh.imphooks'] = __amalgam__
```


And this after nuking all my xonsh/xontrib a few time and restarting from scratch.
Could it be a setuptools version (25.1.6) ? Or the fact that I'm on OS X / Conda ?

**Comment by melund** [comment]
It used to be in premain() in main.py ... Seems like it has disappeared. I will try Git bisect later if no one beats me to it...

**Comment by astronouth7303** [comment]
This looks like a duplicate of #1535

**Comment by Carreau** [comment]
Ah ! Thanks @astronouth7303 it is indeed a duplicate though the information that it affect only editable install is missing in this one !
