### ISSUE TITLE
[Question] history and readline

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1547]
Sometimes I run a cmd say: `ls abc`; then I typed `<UP>` (or `Ctrl-P`) key, another command (than `ls abc`) was showed up. What could be the reason?

Another question: when a hit `<UP>` key, is this event handled by xonsh or readline, can I possible change the behaviour how it shows history items?

Thanks in advance!

**Comment by scopatz** [comment]
Thanks for asking @mitnk!

> Sometimes I run a cmd say: ls abc; then I typed <UP> (or Ctrl-P) key, another command (than ls abc) was showed up. What could be the reason?

This is because we have set the up key to perform a reverse search in history.

> Another question: when a hit <UP> key, is this event handled by xonsh or readline, 

by readline

> can I possible change the behaviour how it shows history items?

Yes, you can through the normal readline mechanism.  Mainly you can provide a ~/.inputrc file to change readline's behaviour. See https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html#Readline-Init-File-Syntax

**Comment by mitnk** [comment]
Thanks @scopatz for detailed answers!

> > Sometimes I run a cmd say: ls abc; then I typed (or Ctrl-P) key, another command (than ls abc) was showed up. What could be the reason?

> This is because we have set the up key to perform a reverse search in history.

For this first question, It seems not that simple. When that happen, `ls abc` is not in the output items of `history`.

**Comment by scopatz** [comment]
> For this first question, It seems not that simple. When that happen, ls abc is not in the output items of history.

That is probably a bug that I have noticed sometimes.

**Comment by scopatz** [comment]
And it depends which history sub-command you mean...

**Comment by mitnk** [comment]
the bare `history` cmd :)

**Comment by scopatz** [comment]
Ahh, yeah, up should scroll through all xonsh session history, not just the current session.
