### ISSUE TITLE
`xonsh.completers.pip` explodes if `pip` is not on PATH

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1548]
On my Windows installation, Python is not on PATH (because multiple Python madness), and therefore neither is pip. However, the pip completer [expects pip to be on the path](https://github.com/xonsh/xonsh/blob/master/xonsh/completers/pip.py#L14).

This causes the completer to blow up with a `FileNotFoundError` when it tries to complete.

**Comment by scopatz** [comment]
Potential fix in #1551
