### ISSUE TITLE
Can't run this command `git stash apply stash@{3}`

### ISSUE THREAD

**Issue by Udayan12167** [xonsh/xonsh#1549]
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: /usr/local/lib/python3.5/site-packages/xontrib/prompt_ret_code.xsh:1:4: ('code: stash',)
git stash apply stash@{3}
```

**Comment by melund** [comment]
This example clashes a bit with xonsh syntax. But if you wrap the offending argument in quotes then it should work. 

```
git stash apply "stash@{3}"
```

**Comment by scopatz** [comment]
Maybe a note on this should be put in the docs somewhere?  Closing, but please feel free to reopen.

**Comment by laerus** [comment]
with #1432 and all, i would like to add this to the docs so we can close a bunch of issues, but i have no idea where/how.

**Comment by scopatz** [comment]
Well, I think it might deserve its own tutorial page, so `docs/tutorial_quotes.rst`?
