### ISSUE TITLE
TAB in $INDENT

### ISSUE THREAD

**Issue by whoizit** [xonsh/xonsh#1553]
How can I use TAB in $INDENT. I try `\t`, `\\t` `ctrl+vTAB` ? Not works for me. `Shift+TAB` not helps to me.

**Comment by gforsyth** [comment]
Hey @atommixz -- sorry for the delay in responding.  
I'm not sure that we support using tabs right now (as the indent character).  Could you post the output of `xonfig` please?

**Comment by atommixz** [comment]
```
$ xonfig                                                                                               15:02 16-08-16
+------------------+----------------+
| xonsh            | 0.4.4          |
| Git SHA          | None           |
| Python           | 3.5.2          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.3          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | True           |
| on linux         | True           |
| distro           | arch           |
| on darwin        | False          |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+

```

**Comment by scopatz** [comment]
On both the readline shell and prompt-toolkit shell, Shift+Tab will insert value of the $INDENT envvar (http://xon.sh/envvars.html#indent).  This is 4 spaces by default.  

Playing around with it, if you change $INDENT to a literal tab character ('\t') it seems like prompt-toolkit will instead insert an '^I'.  This is probably a bug in prompt-toolkit that should be reported to them. In the readline shell, this just triggers tab completion.

Hopefully 4 spaces is enough for you though @atommixz for the moment!  We'd welcome any fixes in this regard.

**Comment by atommixz** [comment]
I prefer TAB with 4 space size

**Comment by scopatz** [comment]
Please then open an issue on prompt-toolkit.  I am not sure if this can be fixed with readline.

**Comment by scopatz** [comment]
The `$INDENT="\t"` is still an upstream issue in PTK v2
