### ISSUE TITLE
System and user xonshrc files not loaded

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1559]
I'm probably going to be made to feel pretty silly, but at present I'm unable to do anything to get either my system or user xonshrc to work.
(I'm a new user - it hasn't stopped working, I've never had it working.)

```sh
~ $ cat "$XDG_CONFIG_HOME/xonsh/config.json"
{
 "env": {
  "IGNOREEOF": true,
  "INDENT": "    ",
  "MULTILINE_PROMPT": "",
  "PROMPT": "{env_name:{} }{cwd}{curr_branch: ({branch_color}{}{NO_COLOR})} {prompt_end} ",
  "SHELL_TYPE": "prompt_toolkit",
  "VI_MODE": true,
  "XONSHRC": "('/etc/xonshrc', '/home/ojf/dotfiles/xonsh/.xonshrc')"
 }
}
~ $ cat "/etc/xonshrc"
aliases['foo'] = 'ls'
~ $ foo
xonsh: subprocess mode: command not found: foo
Did you mean one of the following?
    EOF:  Alias
    od:   Command (/usr/bin/od)
    fg:   Alias
    col:  Command (/usr/bin/col)
    toe:  Command (/usr/bin/toe)
~ $ uname -r
4.7.0-1-ARCH
~ $ xonsh --version
('xonsh/0.4.4',)
~ $ 
```

**Comment by laerus** [comment]
"There are no silly questions". I am pretty sure the problem here is that `XONSHRC` is a string rather than a tuple of strings. We prolly should rly strip envvars off quotes in general.

**Comment by scopatz** [comment]
Yeah, this doesn't seem like correct JSON.

```diff
- "XONSHRC": "('/etc/xonshrc', '/home/ojf/dotfiles/xonsh/.xonshrc')"
+ "XONSHRC": ["/etc/xonshrc", "/home/ojf/dotfiles/xonsh/.xonshrc"]
```

**Comment by scopatz** [comment]
Also thanks a million for reporting @OJFord!

**Comment by OJFord** [comment]
> I am pretty sure the problem here is that XONSHRC is a string rather than a tuple of strings.

Right, I had to change it to be double-quoted because otherwise xonsh complained (correctly) that it wasn't valid JSON on startup.

> Yeah, this doesn't seem like correct JSON.

It is, it's just a string. Albeit one that happens to contain a Python-parseable tuple.

> ```
> - "XONSHRC": "('/etc/xonshrc', '/home/ojf/dotfiles/xonsh/.xonshrc')"
> + "XONSHRC": ["/etc/xonshrc", "/home/ojf/dotfiles/xonsh/.xonshrc"]
> ```

It dose work with this change though, thanks!

This is a definite [docs](http://xon.sh/envvars.html#xonshrc) bug though:

> A tuple of the locations of run control files, if they exist. User defined run control file will supersede values set in system-wide control file if there is a naming collision.
>
> configurable: True
>
> default: On Linux & Mac OSX: (‘/etc/xonshrc’, ‘~/.xonshrc’) On Windows: (‘%ALLUSERSPROFILE%xonshxonshrc’, ‘~/.xonshrc’)
>
> store_as_str: False

I'd suggest changing 'tuple' for 'list', and the examples should also be JSON lists - i.e. square brackets and double quotes.

This is related to #1555 - the first-run wizard gives the same examples - but it's even worse there, it's literally telling you that it is "currently" this tuple with single quotes.

**Comment by laerus** [comment]
hey @OJFord! single and double quotes are the same for python and xonsh in general, so are list and tuple for this specific example (*duck typing*), doesn't rly matter as long as it's a sequence of strings. On the other hand a tuple/list and a string that looks like a tuple/list are very different indeed. I think the best we can do is just `.strip` quotes around envvars but this may make things more loose and users will never actually pass the right object for each envvar.

**Comment by PaulReiber** [comment]
From http://xon.sh/tutorial.html :* xonsh will automatically convert back
and forth to untyped (string-only) representations of the environment as
needed (mostly by subprocess commands). When in xonsh, you’ll always have
the typed version.*

End-users need to be especially aware of whether environment access is
happening 'in subprocess mode' vs regular python.  That could trip people
up, and this could as well:






*Sometimes this type is imposed based on the variable name. The current
rules are pretty simple:\w*PATH: any variable whose name ends in PATH is a
list of strings.\w*DIRS: any variable whose name ends in DIRS is a list of
strings.XONSH_HISTORY_SIZE: this variable is an
int.CASE_SENSITIVE_COMPLETIONS: this variable is a boolean.*

Most shells differentiate between "shell variables" and "environment
variables", with environment variables following  more rules and having a
bit less flexibility.   Most shells consider the environment to be a list
of key,value pairs where both the key and the value are strings.  I think,
in subprocess mode in xonsh, that's the case, but havent tested it or tried
to break it.  But, in xonsh mode, it's definitely NOT the case - the
environment's quite a different thing than one might expect.

I think possibly some better documentation about it would help.

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by OJFord** [comment]
Woah, sorry for the delay, but I'm even more confused now:

>  single and double quotes are the same for python and xonsh in general, so are list and tuple for this specific example (duck typing), doesn't rly matter as long as it's a sequence of strings.

I'm familiar with Python's handling of this; it's the `.json` extension which made me assume this file had to be valid JSON... which single quotes are not, neither are tuples (i.e parentheses).

**Comment by scopatz** [comment]
Yes, the JSON file has to be valid JSON.  The only evaluation that we do is `json.loads()`

**Comment by OJFord** [comment]
> Yes, the JSON file has to be valid JSON. The only evaluation that we do is json.loads()

Thanks for the clarification @scopatz.

This means though that:
> single and double quotes are the same for python and xonsh in general, so are list and tuple
can't be true @laerus? Double quotes and lists are required.

**Comment by laerus** [comment]
what i meant was that the json module handles these cases:
```
$ json.dumps({'tt':(1,2,3)})
'{"tt": [1, 2, 3]}'
$ json.dumps({"tt":[1,2,3]}) == json.dumps({'tt':(1,2,3)})
True
```

**Comment by OJFord** [comment]
Oh right, okay. But `loads` doesn't, since it's _not_ valid JSON; so it cannot be used in the config file, as discussed.

As such, the docs should not say "A tuple of the locations" et al. or give examples of tuples with single-quoted values.

The examples should be valid if copy-pasted. Presently, they're worse than useless - they're totally misleading.

**Comment by scopatz** [comment]
Well, I don't think that they are *that* bad.  They are simply aimed at a different target.  The current documentation is aimed at using environment variables from within xonsh or Python.  This doesn't precisely meet the direct needs of JSON config.  Currently the user has to know how to translation from JSON to Python and which data structures are valid.  

Admittedly, this may be a non-ideal user interaction, and the wizard needs more streamlining overall.  As with everything though, pull requests here are very welcome!  I am happy to give pointers on where to get started and potential restructuring of the docs.

**Comment by gforsyth** [comment]
Both release and dev docs have been updated to address the inconsistency.  Please reopen or file a separate issue if there's still an issue.  Thanks!
