### ISSUE TITLE
"history" broken 

### ISSUE THREAD

**Issue by mandarvaze** [xonsh/xonsh#1568]
``history`` command doesn't seem to work for me. There is no error, but there is no output either

    mandar@MacBook-Pro /tmp $ history
    mandar@MacBook-Pro /tmp $ history zsh  
    mandar@MacBook-Pro /tmp $ history info
    mandar@MacBook-Pro /tmp $ history show

Then I thought, ``history`` is just an alias. So let me try ``__xonsh_history__`` instead.
That gave even bigger error : 

    mandar@MacBook-Pro /tmp $ __xonsh_history__.show('zsh')
    xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
    NameError: name 'bultins' is not defined

OK, so lets get the traceback

	mandar@MacBook-Pro /tmp [1]$ $XONSH_SHOW_TRACEBACK = True; __xonsh_history__.show('zsh')
	xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13086, in default
	    run_compiled_code(code, self.ctx, None, 'single')
	  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1937, in run_compiled_code
	    func(code, glb, loc)
	  File "/usr/local/lib/python3.5/site-packages/xontrib/autoxsh.xsh", line 1, in <module>
	    #!/usr/bin/env xonsh
	  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12068, in show
	    return _hist_show(*args, **kwargs)
	  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 11876, in _hist_show
	    hist = bultins.__xonsh_history__
	NameError: name 'bultins' is not defined

I think ``builtins`` is misspelled as ``bultins`` (or may be not, I couldn't find the file ``__amalgam__.py`` is git repo)

Now the entire ``xonsh`` seems to be broken, simple change directory (``cd``) doesn't work

	mandar@MacBook-Pro /tmp [1]$ $XONSH_SHOW_TRACEBACK = True; cd /tmp
	xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13086, in default
	    run_compiled_code(code, self.ctx, None, 'single')
	  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1937, in run_compiled_code
	    func(code, glb, loc)
	  File "/usr/local/lib/python3.5/site-packages/xontrib/autoxsh.xsh", line 1, in <module>
	    #!/usr/bin/env xonsh
	NameError: name 'tmp' is not defined

FWIW, I'm using version 0.4.4 via ``pip3 install``

    mandar@MacBook-Pro /tmp [1]$ xonsh --version
    ('xonsh/0.4.4',)

**Comment by laerus** [comment]
hey @mandarvaze thanks for reporting! History has gone under some serious refactoring lately and some bugs got into release 0.4.4, i'm pretty sure these are all fixed in latest master, you can try out latest master or wait for the pending 0.4.5 release that fixes tones of bugs including history.

**Comment by mandarvaze** [comment]
@laerus Roughly when can we expect 0.4.5 release ?
Also, https://github.com/xonsh/xonsh/releases shows only till 0.4.0 , but PyPi obviously has lot more :)

**Comment by laerus** [comment]
I would say probably this week, we should update releases info aswell, thanks for pointing this out!

**Comment by laerus** [comment]
@mandarvaze release 0.4.5 is now live on PyPI! i'm closing this, feel free to reopen if any issues still exist.

**Comment by mandarvaze** [comment]
Upgraded to 0.4.5 successfully.
``__xonsh_history__.show()`` command now works.
``history`` command still provides no output, but I think mainly because the alias is broken in **my setup**
I'll open a separate issue for this.
