### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by a-da** [xonsh/xonsh#1573]
In case we use virtualenv we get this exception

    $ . /opt/chpok/bubuieci/bin/activate
    $ python
    Python 3.5.2
    $ xonsh 
    bash: /opt/chpok/bubuieci/bin/xonsh: /usr/local/bin/python3.5: bad interpreter: No such file or directory

to reproduce bug

    $ docker run --name xonsh_issue2 ubuntu:14.04 bash -c '
	    apt-get update
	    cd /opt
	    wget --version || apt-get install -y wget # install wget in case is not present
	    wget -c https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz

	    xz --version || apt-get install -y xz-utils  # install xz in case is not present
	    tar xf Python-3.5.2.tar.xz
	    cd Python-3.5.2/
	    gcc --version || apt-get install -y build-essential  # install xz in case is not present
	    apt-get install -y libssl-dev # ssl is required by PIP module
	    ./configure
	    make
	    ./python --version # should show Python 3.5.2
	    /opt/Python-3.5.2/python -m venv /opt/chpok/bubuieci
	    /opt/chpok/bubuieci/bin/pip install --upgrade pip
	    /opt/chpok/bubuieci/bin/pip install xonsh
           
            . /opt/chpok/bubuieci/bin/activate
	    xonsh
	'
    ...
    Successfully installed xonsh-0.4.5
    bash: /opt/chpok/bubuieci/bin/xonsh: /usr/local/bin/python3.5: bad interpreter: No such file or directory

Is this a bug or a feature ?

**Comment by gforsyth** [comment]
Hi @a-da , thanks for reporting!  Yes, this looks like a bug to me.  I have a docker container running with the commands you specified above and I can see that `/opt/chpok/bubuieci/bin/xonsh` starts with a shebang as

`#!/usr/local/bin/python3.5 -u`

which is clearly incorrect.

**Comment by a-da** [comment]
@gforsyth, can I give a try to fix it or it is something very simple and you will fix by self ?

**Comment by gforsyth** [comment]
Hey @a-da -- definitely give it a shot! 

I've confirmed that if I install system Python (3.4) within the container, I can install xonsh within a virtualenv and it works fine, so it's something to do with the downloaded+compiled version.

**Comment by a-da** [comment]
This is `distutils` issue. 

from /opt/Python-3.5.2/Lib/distutils/command/build_scripts.py

                        executable = os.path.join(
                            sysconfig.get_config_var("BINDIR"),
                           "python%s%s" % (sysconfig.get_config_var("VERSION"),
                                           sysconfig.get_config_var("EXE")))
which return 

    '/usr/local/bin/python3.5'

And I think it will never be fixed but as workaround for this issue we can use:
   1. Edit manualy from "#!/usr/local/bin/python3.5" into "#!/python/from/venv"
   2. Run with /python/from/venv xonsh

**Comment by gforsyth** [comment]
Ahh good old python packaging...  Nice detective work @a-da !
