### ISSUE TITLE
"history" alias broken with foreign shell zsh

### ISSUE THREAD

**Issue by mandarvaze** [xonsh/xonsh#1577]
`zsh` has an alias as :

    $ alias history
    history='fc -l 1'

it works in ``zsh`` because it is a [builtin command](https://www-s.acm.illinois.edu/workshops/zsh/history/fc.html) in ``zsh``
I also happen to have ``fc`` binary in my setup (I think is "font cache" but I am not sure what it is) So when builtin zsh command is not available, the alias refers to ``fc`` binary, which causes even more confusion. Otherwise, I would have received an errors like 

    xonsh: subprocess mode: command not found: fc

When I enabled foreign shelll ``zsh`` via ``xonfig wizard``, all the ``zsh`` aliases are "imported", overwriting the builtin alias for ``history``

out-of-the-box, ``history`` alias is defined in ``xonsh`` as :
 ``<function xonsh.__amalgam__.history_main>``

So I tried to define the alias as follows, but didn't work

    $aliases['history']=xonsh.__amalgam__.history_main
    xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
    NameError: name 'xonsh' is not defined

Queries: 

1. How to define ``history`` alias to match the out of the box definition ?
2. Once I set it in my **current** session, how do I persist it i.e. where are ``aliases`` definitions saved ?

**Comment by laerus** [comment]
hey @mandarvaze! `~/.xonshrc` is the file you're looking for, checkout http://xon.sh/xonshrc.html, there you can add this snippet so `history` will be the xonsh alias and not the zsh:
```
from xonsh.aliases import history_main
aliases['history'] = history_main
```
or maybe you can prevent zsh from aliasing history but i have no clue on how to do that.

also keep in mind that `history` is actually `history show session` which shows history only for the current xonsh session you're in, if you want to get all history from all xonsh sessions you can use `history show all`, `history show --help` may clear some things out.

hope this helps!

**Comment by mandarvaze** [comment]
@laerus Your trick worked !!! It answered both my questions, and now I have working ``history`` command.
I'm closing this one, since #1155 is reopened.
