### ISSUE TITLE
Commented command in addditional setup

### ISSUE THREAD

**Issue by SanketDG** [xonsh/xonsh#1580]
http://xon.sh/add_to_shell.html#additional-setup

the part to add it to the shells is commented out

Is it intended?

**Comment by gforsyth** [comment]
Hey @SanketDG -- thanks for reporting!  

This is a little annoying.  It's supposed to be a `#` sign to signify that the command should be run as root, but ideally it wouldn't also use the commented text style on that line.  I'm not super familiar with sphinx, but maybe there's a better way to manage this.

**Comment by SanketDG** [comment]
This has nothing to do with sphinx.

```
Then, as root, add xonsh to the shell list

.. code-block:: bash

   # which xonsh >> /etc/shells
```

Bash comments start with #, so I guess that's why its commented out.

**Comment by gforsyth** [comment]
changing the code-block style from bash -> console seems to have sorted it
