### ISSUE TITLE
Add other interpreters to vox

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1588]
Currently, Vox can only create venvs of the current interpreter, ie the one running xonsh. Add support for other interpreters, by version and path.

Bonus: Can we support Py2 in this? There's no standard venv module for Py2, and pyvenv (the official one) was never backported.

**Comment by astronouth7303** [comment]
However, venv is a single-file module, so back-porting it might not be hard. If I get clever, I might even be able to bundle it into xonsh such that nothing has to be installed.

**Comment by scopatz** [comment]
+1 for this feature!

**Comment by astronouth7303** [comment]
Hard use case: AWS Lambda still requires Py2. So I need a Py2 venv to do any serious lambda work.

**Comment by astronouth7303** [comment]
Closing in favor of #692.
