### ISSUE TITLE
`[], []` is parsed to `[[]]`

### ISSUE THREAD

**Issue by blahgeek** [xonsh/xonsh#1593]
```
$ [], []
[[]]
```

**Comment by laerus** [comment]
Hey @blahgeek, thanks for reporting! This seems like a legitimate bug, it should rerurn a tuple with two empty lists. Are you on the 0.4.5 version of PyPI?

**Comment by blahgeek** [comment]
Yes, `xonsh --version` prints `xonsh/0.4.5`. My python version is 3.5.2

**Comment by scopatz** [comment]
Also note these cases:

```
scopatz@artemis ~ $ [], [],
[[]]
scopatz@artemis ~ $ [1], []
[1, []]
scopatz@artemis ~ $ [1], [1]
[1, [1]]
scopatz@artemis ~ $ ([1], [1])
([1], [1])
```

**Comment by scopatz** [comment]
Oof thanks for finding thsi @blahgeek!
