### ISSUE TITLE
ls(1) alias broken on NetBSD

### ISSUE THREAD

**Issue by krytarowski** [xonsh/xonsh#1596]
```
kamil@chieftec ~ $ uname -rms
NetBSD 7.99.35 amd64
```

```
kamil@chieftec ~ $ ls
ls: unknown option -- -
usage: ls [-1AaBbCcdFfghikLlMmnOoPpqRrSsTtuWwXx] [file ...]
```

```
kamil@chieftec ~ $ xonsh --version
('xonsh/0.4.0',)
```

**Comment by laerus** [comment]
Hey @krytarowski, thanks for reporting! Can you try `which -v ls`  and show the output? also there is a new 0.4.5 version with a lot of bug fixes, you can try updating and see if the problem persists.

**Comment by krytarowski** [comment]
```
$ which -v ls                              
which: unknown option -- v
Usage: which [-ap] program [...]
```

```
$ which  ls   
/bin/ls
```

The same issue with `ls`(1) and xonsh 4.5.

**Comment by krytarowski** [comment]
And this is from inside of the xonsh shell:

```
$ which -v ls
aliases['ls'] = ['ls', '--color=auto', '-v']
```

**Comment by krytarowski** [comment]
Both, `-v` and `--color=auto` are GNUisms.

**Comment by scopatz** [comment]
HI @krytarowski - thanks for reporting.  My guess is that the same fixes that we use for FreeBSD will also work for you.  To implement them, what is the value of your `sys.platform`?

**Comment by krytarowski** [comment]
```
$ python2.7                                                                                                                                                                          
Python 2.7.12 (default, Aug 20 2016, 11:13:11) 
[GCC 5.4.0] on netbsd7
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.platform
netbsd7
```

In general I propose to check for `startswith("netbsd")`

**Comment by scopatz** [comment]
Thanks,, could you check on Python 3, too, please just to be sure?

**Comment by krytarowski** [comment]
Python 3.5 gives the same result.

**Comment by scopatz** [comment]
OK great!

**Comment by scopatz** [comment]
Please see #1601

**Comment by krytarowski** [comment]
Fixed by @scopatz Thanks!
