### ISSUE TITLE
Windows-specific problems

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#1600]
Pity the poor Windows user...
I'd like to use Xonsh as the vehicle to finally escape the clutches of CMD.EXE: the backslashes, the funky string escaping conventions, but I keep tripping over the simple things.  I fixed PUSHD for UNC paths for myself.  I don't want to reopen old conversations about alternative command line styles, my goal is to use more Xonsh and less CMD.EXE dialect, but these classes of problem just keep tripping me up.

### Forward slashes in internal subprocess CMD.EXE

I have to be constantly mindful of the few but frequent cases that I cannot use forward slashes in file paths; they work in python lines and subprocess mode for *external* commands, but not *internal* commands lines for CMD.EXE.  E.g 

```cmd
$ notepad ./logo.txt
```
works, but 

```cmd
$ dir ./logo.txt
Parameter format not correct - "logo.txt".
``` 

Where is the code that's fixing up the path being fed to Notepad above?  It doesn't seem to happen in Xonsh, is it somewhere in `os`?  

### Globbing
Likewise, globbing requires too much thought on Windows.  Again, mostly a problem with *internal* commands in subprocess mode:

```cmd
$ d *.txt
 Volume in drive N is BobHyNetDisk
 Volume Serial Number is CC25-0181

 Directory of n:\devwork\work\xonsh

01-Jul-16  05:02 PM             3,164 bug.os.chdir.txt

 Directory of n:\devwork\work\xonsh

06-Jun-16  07:53 PM             3,151 logo.txt

 Directory of n:\devwork\work\xonsh

06-Jun-16  07:53 PM                38 requirements-docs.txt

 Directory of n:\devwork\work\xonsh

29-Jul-16  11:34 AM               202 requirements-tests.txt
               4 File(s)          6,555 bytes
               0 Dir(s)  413,687,772,160 bytes free
```
vs the less obvious:

```cmd
$ d '*.txt'
 Volume in drive N is BobHyNetDisk
 Volume Serial Number is CC25-0181

 Directory of n:\devwork\work\xonsh

01-Jul-16  05:02 PM             3,164 bug.os.chdir.txt
06-Jun-16  07:53 PM             3,151 logo.txt
06-Jun-16  07:53 PM                38 requirements-docs.txt
29-Jul-16  11:34 AM               202 requirements-tests.txt
               4 File(s)          6,555 bytes
               0 Dir(s)  413,687,772,160 bytes free
```

I could just use unix ports of `cp`, `ls`, `rm` like a sane person, but maybe there's a place in Xonsh parsing that could special case CMD.EXE internal commands and suppress the glob for them?  Where would be a good place to start?

### Extra Python continuation prompt
Consider this trifecta:

```cmd
$ d n:
. <extra CR>
-------------------------- bobhy@BobHy-PC n:/devwork/work/xonsh winuncpushd
$ d n:/
Invalid switch - "".
-------------------------- bobhy@BobHy-PC n:/devwork/work/xonsh winuncpushd
$ d n:\
. <extra CR>
 Volume in drive N is BobHyNetDisk
 Volume Serial Number is CC25-0181

 Directory of n:\
14-Jul-15  08:31 PM    <DIR>          39f143f1c75290cddbc9
                         . . . snip . . .
31-Jan-15  06:23 PM    <DIR>          websites
               4 File(s)          5,446 bytes
              20 Dir(s)  413,687,772,160 bytes free
```

The second example is just a backslash botch, covered elsewhere.  But I don't understand what's causing the extra continuation in the other 2 cases.

**Comment by gforsyth** [comment]
> But I don't understand what's causing the extra continuation in the other 2 cases.

You're using the `prompt_toolkit` shell, I imagine?  We have some logic for when `Enter` means 'submit and execute' and when it means 'add new line'.  One of the triggers for add new line is the previous line ending in a colon, one of the others is lines ending in a backslash.

**Comment by bobhy** [comment]
I am indeed using ``prompt_toolkit``, and that does explain the 2 cases.  

So a lot of my issues boil down to Windows path syntax vs unix.   I'll add one more example where using tab completion is bootless if I'm invoking a CMD internal command or most Windows native command line tools in subproc mode:

```cmd
$ dir tes<TAB>ts/hist<TAB>ories/
Invalid switch - "histories".
```

Tab completion adds the forward slash to directory names automagically, but it's wrong for most of the lines I type (and I do use tab completion a lot). 

I am struggling here to come up with a concise problem statement.  The user experience though, is that Xonsh is hard to use on Windows because it forces me to think modally ("If the line I'm about to type is a subprocess command, I'd better remember to use backslashes, and to escape them properly at the end of lines, and also to escape the file globbing wildcards.  But if it's python, or invoking a unix utility, I must use forward slashes and can let globbing happen."  Put that way, it sure sounds like a lot to keep straight.

But to ask the question is to answer it.  Maybe completers for Windows commands could handle escaping the globbing, and, now that I think of it, maybe could handle the file path transforms too.  Let me take a look at that api...

**Comment by astronouth7303** [comment]
That's odd. On my windows machine, filename tab completion substitutes backslashes.

**Comment by scopatz** [comment]
I bet this is related somehow +/- cygwin http://xon.sh/envvars.html#force-posix-paths

**Comment by astronouth7303** [comment]
Possibly. I'm using native Python, although I do have some msys/mingw utilities installed because of git-for-windows.

**Comment by bobhy** [comment]
@scopatz is right! I had ``$FORCE_POSIX_PATHS`` enabled in ``config.json`` for some reason.
Turning it off more or less resolves my issues with the slashes.
The globbing behavior remains, but it's clear what's going on.

**Comment by bobhy** [comment]
Closing this thread, I've got a workable answer.
