### ISSUE TITLE
Cannot install/use conda related functionality when you enter xonsh when already inside conda env

### ISSUE THREAD

**Issue by michaelpacer** [xonsh/xonsh#1613]
So there are a couple of different pieces to this. The first is getting xonda/conda set up so that you can use `conda activate env1` from inside a `xonsh` instance. Several odd errors popped up including stating that it couldn't find `conda`, and then when trying to `pip install conda` it fails because it (reasonably) doesn't want install conda while inside a conda env. 

Popping out and installing from the root env, opening xonsh, pip installing xonda, running xontrib load xonda then allows you to have access to the appropriate `conda activate env1` command.  But only from the root directory. If you then go into another directory, it may not have a functioning version of xonda, even if it has a functioning version of xonsh. 

So one solution is to always initialise xonsh from the root env, and then enter envs only afterwards. If you set that up only partially correctly it can lock you out of your envs.

Update: 

With help from @carreau I got this working. What needed to happen was to set up xontribs to load xonda as part of my config from the root directory and then to make sure that no other versions of xonsh were shadowing that root version with the appropriate config and access to the proper version of conda. Then for all of my environments, I needed to remove xonsh(pip uninstall xonsh), delete `~/anaconda3/envs/dev/bin/xonsh`, rehash (`hash -r`) and then it would load properly from the root xonsh that had been set up properly. This then allowed shifting into xonsh while already inside the conda environment.

**Comment by gforsyth** [comment]
Hey @michaelpacer , thanks for reporting!  And sorry for the headache!  

I'll have to think about this -- I think I understand a few of the root issues -- I have `xonsh` set up as my default shell so many of these problems I haven't run across.  This may actually just be an issue with the way I have `xonda` set up -- I'm not sure.  I'll try to dig in soonish and see if I can sort this out.  But in any case, glad it's working for the moment!

**Comment by gforsyth** [comment]
Feel free to reopen this on https://github.com/gforsyth/xonda but I'm closing here as it's not a xonsh issue.
