### ISSUE TITLE
Import other shell history

### ISSUE THREAD

**Issue by seanfarley** [xonsh/xonsh#1614]
It seems to be a bit of a downer that bash / zsh / whatever history isn't imported upon first use. Or am I missing something?

## Comments in this thread
* [The common way to load history from the foreign shell. Example for bash. ](https://github.com/xonsh/xonsh/issues/1614#issuecomment-748372973)
* [Load zsh history](https://github.com/xonsh/xonsh/issues/1614#issuecomment-483386184)
* Load fish history: [1](https://github.com/xonsh/xonsh/issues/1614#issuecomment-608379813), [2](https://github.com/xonsh/xonsh/issues/1614#issuecomment-764797612)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laerus** [comment]
hey @seanfarley! can you try `history show bash` or `history show zsh` and see if this works out?

**Comment by seanfarley** [comment]
Yep, sorry to mention that: `history show bash` works but isn't included when pressing `ctrl+r`.

**Comment by laerus** [comment]
oh right, this would be a cool feature! thanks for opening this, PRs are always welcomed!

**Comment by GMLudo** [comment]
Hi,

I'm also interested in by this feature. Is it enough to generate the *.json file ?
A long time ago, you had a .xonsh_history file. Is somebody has made a convertor for the new format ?

Have a nice week.

**Comment by scopatz** [comment]
Hi @GMLudo Sorry for the delay, but yes, it would be enough to create a JSON file of teh correct form.  But since we now have multiple history backend support, it might be a better idea to have readers for the history files of different shells and then write them out to via a History class.

**Comment by astronouth7303** [comment]
I feel like I should point out that since xonsh is only trivially compatible with the bourne-family shells, any command of complexity imported from bash history will fail.

**Comment by scopatz** [comment]
Good point @astronouth7303! But if we wanted to be clever we'd build a sh-parser and translator to xonsh... Not now, of course, there are still too many open issues :)

**Comment by GMLudo** [comment]
:-( I've a lot of interesting commands in my bash history, but I understand it's a lot of work.

Have a nice week.

**Comment by scopatz** [comment]
Well, I think having something like this would still be valuable, even if it wasn't a fully featured translator. If anyone wants to work on it, I would be most grateful!

**Comment by timokau** [comment]
I wrote a little script to import my zsh history:

```python
import re
from xonsh.history.main import construct_history

# <command-number> <unix epoch> <command>
history_line_pat = re.compile(r'^\s*\d+  (?P<timestamp>\d{10})  (?P<command>.*)$')

# Query zsh's builtin `fc` (don't use zsh_history directly since it
# mangles unicode). To do that, we have to first force it to read the
# history (which it normally doesn't do with -c) and also force it to
# act in interactive mode (-i).
history_lines = $(zsh -i -c 'fc -R ~/.zsh_history; fc -l -t "%s" 0').splitlines()

hist = construct_history(
	gc=False,
	# exlictily set buffersize to prevent slowing down to a crawl because of excessive flushing
	buffersize=len(history_lines)
)

for line in history_lines:
    match = history_line_pat.match(line)
    command = match.group('command')
    timestamp = match.group('timestamp')
    command = command.replace(r'\\n', '\n')
    hist.append({'inp': command, 'rtn': 0, 'ts': (timestamp, timestamp)})
hist.flush()
print(hist.info().filename)
```

**Comment by scopatz** [comment]
That's awesome @timokau! Any interest in adding this to xonsh proper?

**Comment by timokau** [comment]
I'm not entirely sure if its polished enough for that and wouldn't know where to put it, but feel fee to do so :)

Take this as the "Do whatever you want" license, no attribution or anything necessary.

**Comment by jnoortheen** [comment]
This is the script I used to import fish-history
```py
import os
import sqlite3
import time
import uuid

FISH_HIST = "~/.local/share/fish/fish_history"
XONSH_HIST = "~/.local/share/xonsh/xonsh-history.sqlite"
SQL = f"""
INSERT INTO xonsh_history (inp, rtn, tsb, tse, sessionid, out, info)
VALUES (?, ?, ?, ?, ?, ?, ?);
"""

sess_id = uuid.uuid4()


def import_fish_history():
    fish_history = os.path.expanduser(FISH_HIST)
    from collections import OrderedDict
    cmds = OrderedDict()
    with open(fish_history) as fr:
        for line in fr.read().splitlines():
            if line.startswith("-"):
                _, cmd = line.split("cmd:")
                cmds[cmd.strip()] = None

    conn = sqlite3.connect(os.path.expanduser(XONSH_HIST))
    curr = conn.cursor()
    for cmd in cmds:
        curr.execute(SQL, (
            cmd, 0, time.time(), time.time() + 1, str(uuid), None, None
        ))
    conn.commit()
    conn.close()
```

perhaps, adding an API to add commands to `xonsh` history will make this process more easier.

**Comment by scopatz** [comment]
Yep that would be awesome! PRs very welcome here

**Comment by rsalmei** [comment]
I've just used @timokau 's trick posted [here](https://github.com/xonsh/xonsh/issues/1614#issuecomment-483386184) with success in my tool, to import the non-utf8 zsh history to fish! Thank you!
[zsh-history-to-fish](https://github.com/rsalmei/zsh-history-to-fish)

**Comment by anki-code** [comment]
> since xonsh is only trivially compatible with the bourne-family shells, any command of complexity imported from bash history will fail.

There is simple workaround for this -- loading sh-shells commands from history with [subprocess macro](https://xon.sh/tutorial_macros.html#subprocess-macros) prefix:
```python
bash -c ! <command from ~/.bash_history>
zsh -c ! <command from ~/.zsh_history>
fish -c ! <command from ~/.local/share/fish/fish_history>
```
And search with `Ctrl+R` will work. 

Yeah, this is not 100% solution but I think it will cover most cases. If anyone want to implement this I suggest to add environment variable for switching this functionality on or off (off by default).

**Comment by aneeshdurg** [comment]
Here's a variation on @timokau 's history importer for importing fish history:
```python
import re
from xonsh.history.main import construct_history

with open(".local/share/fish/fish_history") as history_file:
    history_lines = history_file.readlines()

hist = construct_history(
	gc=False,
	# exlictily set buffersize to prevent slowing down to a crawl because of excessive flushing
	buffersize=len(history_lines)
)

for i in range(len(history_lines)):
    line = history_lines[i];
    if not line.startswith("-"):
        continue

    cmd = line.split("cmd:")[1].strip()
    timestamp = int(history_lines[i + 1].split(":")[1].strip())
    print(cmd, timestamp)
    hist.append({
        'inp': cmd,
        'rtn': 0,
        'ts': (timestamp, timestamp)
    })
hist.flush()
```

This isn't great because it'll do weird things if your command has a ':' in it, but it was sufficient for my use case. Using regex is probably a better approach if you want 100% correctness.

**Comment by gforsyth** [comment]
Thanks for adding to the collection @aneeshdurg !

**Comment by seelaman** [comment]
> > any command of complexity imported from bash history will fail.
> 
> There is simple workaround for this -- loading sh-shells commands from history with [subprocess macro](https://xon.sh/tutorial_macros.html#subprocess-macros) prefix:
> 
> ```python
> bash -c ! <command from ~/.bash_history>
> zsh -c ! <command from ~/.zsh_history>
> fish -c ! <command from ~/.local/share/fish/fish_history>
> ```
> 
> Example:
> 
> ```python
> with open(p'~/.bash_history') as bash_history:
>     for cmd in bash_history:
>         if not cmd.startswith('#'):
>             cmd = cmd.rstrip()
>             __xonsh__.shell.shell.prompter.history.append_string(f'bash -c ! {cmd}')
> ```
> 
> And search with `Ctrl+R` will work.
> 
> Yeah, this is not 100% solution but I think it will cover most cases. If anyone want to implement this I suggest to add environment variable for switching this functionality on or off (off by default). Or may be the best way is to have this as a xontribs i.e. three xontribs `xontrib-history-bash/zsh/fish` to allow bash/zsh/fish users work on enrichment distinctly.
> 
> I'm using this kind of approach in [xontrib-sh](https://github.com/anki-code/xontrib-sh) very long time and it works perfect for me.

Thanks that worked beautifully.

**Comment by seelaman** [comment]
This worked for me on importing .bash_history

```
from xonsh.history.main import construct_history
hist = construct_history(gc=False)
with open('./.bash_history') as f:
    for line in f:
        hist.append({'inp': line.strip(), "out": "", "ts": (0.0, 0.0), 'rtn': 0})
```

**Comment by anki-code** [comment]
I'm going to close this issue because this could be solved by creating the xontribs for any shell you want to load.

But feel free to post here your snippets of code. Someone will create a xontrib from them.

**Comment by azertyfun** [comment]
I've made the following snippet to import bash history, but adapted from the fish import scripts to use sqlite directly (I've accumulated some 170k lines over the years and the `xonsh.history` facilities are just too slow to be useful here):

```python
import sqlite3
import uuid
import time

uuid = str(uuid.uuid4())
db = sqlite3.connect($HOME + '/.local/share/xonsh/xonsh-history.sqlite')
cur = db.cursor()

with open($HOME + '/.bash_history', 'rb') as fp:
    lines = []
    for line in fp.readlines():
        try:
            lines.append(line.decode('utf-8'))
        except UnicodeDecodeError:
            pass # guess who had some invalid characters pasted in there sometime over the years? let's just sneakily ignore those...

    cur.executemany('INSERT INTO xonsh_history(inp, rtn, tsb, tse, sessionid, out, info) VALUES (?, ?, ?, ?, ?, ?, ?)', [(line, 0, time.time(), time.time() + 1, uuid, None, None) for line in lines])

db.commit()
db.close()
```
