### ISSUE TITLE
Wrong detection mode with environment variables

### ISSUE THREAD

**Issue by rbignon** [xonsh/xonsh#1627]
<pre>
rom1@calepin ~ $ echo $PWD
/home/rom1
rom1@calepin ~ $ echo $PWD/blah
................ 
rom1@calepin ~ $ echo '$PWD/blah'
/home/rom1/blah
</pre>

It may works with the second case.

**Comment by laerus** [comment]
this was solved in #1623 on the latest master.

**Comment by scopatz** [comment]
@rbignon - can you please confirm and/or close? Thanks a million for reporting!

**Comment by rbignon** [comment]
I've updated xonsh and it's fixed. Thank you and sorry for the duplicate!
