### ISSUE TITLE
Problems with redirections

### ISSUE THREAD

**Issue by rbignon** [xonsh/xonsh#1628]
Here are some issues with redirections:

<pre>
$ ls > /dev/null
$ ls >/dev/null
................................. 
</pre>

It may not be needed to have a space between the '>' and the file path.

Also, redirection from stderr to stdout works:

<pre>
$ ls uie > /dev/null
/bin/ls: cannot access 'uie': No such file or directory
$ ls uie 2>&1 > /dev/null
$
</pre>

But not from stdout to stderr:

<pre>
 $ ls uie 1>&2 > /dev/null
................................. 
</pre>

I think this is related to #1536, and the problem with vim's syntastic plugin which tells at startup:

<pre>
syntastic: error: your shell /usr/local/bin/xonsh doesn't use traditional UNIX syntax for redirections
</pre>

**Comment by scopatz** [comment]
Thanks for reporting.  Yes, not all redirections have been implemented yet.

**Comment by scopatz** [comment]
Potential fix for the remaining issue in #2261

**Comment by melund** [comment]
@rbignon This is implemented on master now. Reopen if you think something is missing.
