### ISSUE TITLE
conda env create succeeds to install the env, but requires exiting xonsh to activate

### ISSUE THREAD

**Issue by michaelpacer** [xonsh/xonsh#1631]
Here's a series of commands that should reproduce the error if you have a working xonda extension.

It presumes you have a directory below your home directory called `Jupyter` but that is an unnecessary detail…replace as you need. I think it may be important that xonsh was started in a different place from where the environment was created. It assumes you have a `*nix` box.

```
cd ~
xonsh 
conda create -n documenter python=3
cd Jupyter 
git clone https://github.com/jupyter/notebook
cd notebook
pip install -e .
conda env create -f docs/environment.yml
conda activate notebook_docs 
```
which errs with: `No environment 'notebook_docs' found`.
But if you 

```
exit 
xonsh
conda activate notebook_docs
```

It succeeds without issue.

**Comment by scopatz** [comment]
Thanks for reporting @michaelpacer.  I think you may need to use xonda http://xon.sh/xontribs.html#xonda https://github.com/gforsyth/xonda

**Comment by michaelpacer** [comment]
Actually `xonda` *doesn't* work at all. @Carreau can vouch for that… we were both confused. But `conda` seemed to work just fine in all other ways. 

Note: `conda activate` isn't a standard `conda` command that would work in `bash`.

**Comment by scopatz** [comment]
Hmm, where are you even getting the conda-activate command from?

**Comment by michaelpacer** [comment]
It's a command from `xonda`. I'm having difficulty finding where I added it to the default load (apparently it wasn't in my `.xonshrc`? That's why it was super weird, probably should have posted a bug, but right now `conda` works as an alias to `xonda` but `xonda` doesn't:

```
xonda activate documenter
xonsh: subprocess mode: command not found: xonda
Did you mean one of the following?
    conda:  Alias
    xindy:  Command (/Library/TeX/texbin/xindy)
    xonsh:  Command (/usr/local/bin/xonsh)
```

**Comment by gforsyth** [comment]
This is purely a `xonda` bug, I think.

**Comment by gforsyth** [comment]
Ok, this was due to an incredibly poor placement of an `lru_cache`.  Fixed in https://github.com/gforsyth/xonda/commit/9a7f247faae0aaa9aba9302cb81a9754313addd2 and available as version 0.1.5 on pypi

if you don't have `xontrib load xonda` in your `.xonshrc` and it is still loading, check your `config.json` in `~/.config/xonsh` -- depending on whether you completed the xonsh wizard there may be an entry there to autoload it.

**Comment by michaelpacer** [comment]
Is that for the `xonda` command being lost in favour of the `conda` alias or for the inability to create an env inside of an env and then to activate the new env? 

Based on the caching comment I'm guessing it's the latter (what this issue is actually about), but when I look at the linked commit it's just a version number change so I couldn't figure it out from my phone.

**Comment by gforsyth** [comment]
The latter.  The `xonda` command was eliminated a while ago when I realized I could just wrap all of conda's functionality and provide two extra commands for env activate/deactivation

**Comment by gforsyth** [comment]
Ok, closing this as I believe it's been resolved, but please reopen if there's still an issue.
