### ISSUE TITLE
Improve BASHward compatibility : history interaction

### ISSUE THREAD

**Issue by mandarvaze** [xonsh/xonsh#1632]
This was discussed over twitter with @scopatz [here](https://twitter.com/mandarvaze/status/764887040785735680) where he suggested a separate "bashism" xontrib to handle these

It seems this was discussed on the [google group](https://groups.google.com/d/msg/xonsh/wEs0zI2dHm8/gAS9DuQGBQAJ) and IRC as well (link not available)

Complete details of BASH history interaction feature listed [here](https://www.gnu.org/software/bash/manual/bashref.html#History-Interaction)  - as a reference.

My preference would be to support `!$` first,  since `!!` (to recall last command) already works.

**Comment by laerus** [comment]
Hey! see also #1411

**Comment by mandarvaze** [comment]
@laerus #1411 seems to have a lot more discussion/details
Feel free to close this as duplicate.

**Comment by laerus** [comment]
We haven't discussed about how a xontrib will provide this functionality. Maybe a pre-parsing of some short. #1411 is about the History API now, which may help in the implementation a bashwards xontrib.

**Comment by scopatz** [comment]
I don't think any preparsing is needed:

```console
scopatz@artemis ~/xonsh master $ aliases['!$'] = lambda a, s: 'banana\n'
scopatz@artemis ~/xonsh master $ !$
banana
```

**Comment by laerus** [comment]
will this work like so: `echo !$` ?

**Comment by scopatz** [comment]
Oh, no.  That won't work.  You'd have to do something like `echo @(__xonsh_history__.inps[-1])` right now

**Comment by scopatz** [comment]
Maybe such a preprocessor would be a a good precmd handler (in a xontrib) once we get the event system.  It seems like this kind of expansion would only be useful in the shell, and not in scripts or modules so much anyway.

**Comment by astronouth7303** [comment]
Maybe subprocess-mode macros would help?

**Comment by scopatz** [comment]
Subprocess macros probably mess some of this up.  I think that this is really more a precmd  preprocessor kind of thing.

**Comment by PaulReiber** [comment]
What would be initial goals for recognizers for history preprocessing?
Just !$ or other history subs as well? For example:

$ cd /ect/
cd: /ect/: No such file or directory
$ ^ct^tc

cd /etc

$ pwd
/etc


The above shows a common use case we could call "^wrong^right"
I guess the question is... are we aiming for full BASH level history
substitution?

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
`!!` will also need to be implemented this way.  I would like to drop it from the core.

**Comment by mandarvaze** [comment]
[Documentation](http://xon.sh/xontribs.html?highlight=bashism#bashisms) references bashism xontrib

Does that mean time to close this issue ?

I was able to "load" it, but got an an error something like "enabled but not installed, please use pip install"

The above link says ``pip installl xonsh`` for this xontrib. Is this doc error ? Or does it indicate that the xontrib is installed "by default" with xonsh
If later, I already updated to xonsh 0.5.0 but bashism does not work for me (I think. How to confirm ? I get no error on ``!!`` but nothing happens either)

**Comment by astronouth7303** [comment]
It's `bashisms` plural.

**Comment by scopatz** [comment]
Hi @mandarvaze - we can close this if we want now.  Future issues and PRs should cover expanding bashisms to be more broadly useful.

**Comment by mandarvaze** [comment]
@astronouth7303 Neither ``pip install bashisms`` nor ``pip install xontrib-bashisms`` worked.
Both return the error : ``No matching distribution found `` error.

**Comment by astronouth7303** [comment]
`bashisms` is a bundled xontrib first released with v0.5.0.

**Comment by scopatz** [comment]
Yeah, since it comes with xonsh you don't need to install it. The docs show install instructions: http://xon.sh/xontribs.html#bashisms

**Comment by melund** [comment]
Isn't the issue that:

> I was able to "load" it, but got an an error something like "enabled but not installed, please use pip install"

I haven't tried my self. But I guess you should not get that error for bundled xontribs.

**Comment by scopatz** [comment]
I thought that was when the spelling was `bashism` (incorrect) not `bashisms`(correct). That error message should be better.

**Comment by melund** [comment]
Ahh. Sorry. Missed that :)

**Comment by scopatz** [comment]
@mandarvaze did you ever get this working?

**Comment by mandarvaze** [comment]
OK, when I typed ``xontrib load bashisms`` there were no errors.
it kinda worked, but I'm not sure what all is supposed to work
e.g. ``!!`` works. but ``!$`` doesn't (Is is expected to ?)

**Comment by laerus** [comment]
`!$` is not implemented yet.

**Comment by scopatz** [comment]
Yes, please feel free to open issues or pull requests for each feature desired. Right now, only `!!` is implemented, because that it all that was implemented before.

**Comment by mandarvaze** [comment]
I'm OK to close this one.
I've created new issue #2041 for ``!$`` and substitutions

**Comment by scopatz** [comment]
Sounds great! Let's continue the discussion there.
