### ISSUE TITLE
Invalidate Code Caches on Install

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1649]
I feel like the code cace should be invalidated whenever `__init__.py` or similar is changed.  This could prevent some non-obvious issues.

**Comment by laerus** [comment]
totally agree, i has some issues before that were solved by removing the caches.

**Comment by laerus** [comment]
i'm also having a hard time in develop mode when making changes to the parser, restarting isn't enough, i need to delete `parser_tables.py` to make it work. Should i open a new issue about this?

**Comment by astronouth7303** [comment]
Does `parser_tables.py` need to be written? Or just a `.pyc` cache?

**Comment by laerus** [comment]
should we just remove `xonsh_code_cache` and `parser_tables.py` on each install?

**Comment by gforsyth** [comment]
I think that's a reasonable and simple solution.

**Comment by laerus** [comment]
so `parser_tables.py` is already getting removed in `setup.py` my bad,
the hard part would be to find out if and where $XONSH_DATA_DIR is in `setup.py`

**Comment by scopatz** [comment]
Yeah, I am not sure that we should remove the code cache when we install, because we can't be sure which one the user will use at run time.  This is probably going to have to be a run time check.  You can imagine different xonsh version installs which point to different caches, potentially.

**Comment by scopatz** [comment]
Potential fix for this in #2262
