### ISSUE TITLE
here documents in subprocess

### ISSUE THREAD

**Issue by geraldh** [xonsh/xonsh#1652]
Hello,
are [here documents](http://tldp.org/LDP/abs/html/here-docs.html) supported in subprocess mode ?
I would like to parse the output of:

```
sqlplus / as sysdba <<__DOWN__
shutdown immediate ;
exit;
__DOWN__
```

but if I enter:

```
cmd = !(sqlplus / as sysdba <<__DOWN__
shutdown immediate ;
exit;
__DOWN__)
```

I get:

```
SyntaxError: <xonsh-code>... ('code: <<',)
```

It seems parsing here documents is not implemented yet. Is an implementation of redirecting stdin from here docs planned ?

**Comment by geraldh** [comment]
a workaround would be:
```
cmd = !(echo """shutdown immediate ;
exit;
""" | sqlplus / as sysdba)
```

But still - the here doc syntax is nicer.

**Comment by scopatz** [comment]
Hi @geraldh, we are adding subprocess macros in #1644 that should help with this.

**Comment by scopatz** [comment]
This is supported by subprocess macros and context macros

**Comment by sirex** [comment]
I could not find any example how heredoc syntax would look like in xonsh. So it would be nice if someone knowing it would give an example?

**Comment by anki-code** [comment]
@sirex may [the xonsh cheatsheet will help](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md#create-file-with-content-from-command-line).

**Comment by mattmc3** [comment]
Not sure if this is the preferred way to do heredocs in Xonsh or if there's something better, but since it's all Python this seems to make the most sense to me (and the cheatsheet doesn't seem to cover this adequately):

```python
$ # make a regular Python multiline string with triple quotes
$ script = '''shutdown immediate ;
exit;'''
$ # run the command
$ echo @(script) | sqlplus / as sysdba
$ # or do it as a subprocess
$ cmd = !(echo @(script) | sqlplus / as sysdba)
$ cmd
```

I do this with Xonsh versions of my MacOS utilities that I miss from OMZ/Prezto, for example:

```python
def _pfd(args):
    """Show the current directory in Finder.app"""
    script = '''tell application "Finder"
                    return POSIX path of (target of first window as text)
                end tell'''
    echo @(script) | osascript err>/dev/null
aliases['pfd']=_pfd
```
