### ISSUE TITLE
Nested parentheses highlight incorrectly (innermost-opening and outermost-closing)

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1663]
The highlighting of parentheses is badly matched in a command of the form:
```
execx($(foobar))
```
in which the `$(` and final - not the penultimate - `)` are highlighted green.

**Comment by laerus** [comment]
hey @OJFord thanks for reporting. This happens with any parens:

![xonsh-color-paren-bug](https://cloud.githubusercontent.com/assets/6930157/18201646/114114b8-7114-11e6-8b74-1c2fd416c6bb.png)

**Comment by OJFord** [comment]
No problem, so it does - I just happened to notice it with exec :)

Changed title to reflect.

**Comment by gforsyth** [comment]
This is fixed on master thanks to @blahgeek's great work in #1711
