### ISSUE TITLE
`os.chdir()` detection should fire `on_chdir`

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1666]
The [$PWD fix](https://github.com/xonsh/xonsh/blob/e671c72f1f367c85b0495656bb7d0e5a90e71850/xonsh/base_shell.py#L183) doesn't currently fire `on_chdir`, even though it could change the current working directory.

`on_chdir` should only be fired if the directory actually changes.

(Really, I'll probably do this tonight, but I wanted to leave this here in case I forgot.)

**Comment by bobhy** [comment]
The fix itself does not change current working directory, it just makes $PWD match.  Should we fire an event here? My sense of events is they fire when ```xonsh``` or a script does something.  It's probably a bug to call ```os.chdir``` rather than ```dirstack.cd()``` in an extension or a function and the latter already fires the event.

**Comment by astronouth7303** [comment]
Well, the point of the detection is that the cwd changed without the rest of xonsh noticing, so we have to play 'catch-up' with the `cd` processes, which include:

1. Update `$PWD`
2. Fire `on_chdir` (new)

If you do 1 without 2, xonsh itself might be updated but not any xontribs. (Similar to what happens currently if you load `autoxsh`, `avox`, or `z` and then use `pushd`.)

**Comment by bobhy** [comment]
You're right.  Xonsh should either do both of these or neither. See PR #1684. (need to update $OLDPWD, too, to mimic ```dirstack.cd()``` behavior.
