### ISSUE TITLE
Implement found/not found command in xonsh (a la fish shell)

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1679]
Fish shell does colouring of found/not found commands/alias while you type, it seems a nice feature to have and apparently would be easy to implement as described in #1225

some docs:
how to do a callback: http://pygments.org/docs/lexerdevelopment/#callbacks
documentation on the commandscache: http://xon.sh/api/commands_cache.html (probably lazy_in is what you should use)

I still don't know how to trigger a callback on first token if on process mode/root

**Comment by scopatz** [comment]
Yup, `lazy_in()` would be the right thing to use.

**Comment by gforsyth** [comment]
Implemented in #1688 !
