### ISSUE TITLE
[docs] Core xontribs need full documentation

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1685]
The core xontribs (distributed, mpl, vox) need real documentation on the website. Currently, they get a few sentences on the xontribs page.

**Comment by scopatz** [comment]
mpl and vox both have API pages:

* http://xon.sh/api/mplhooks.html
* http://xon.sh/api/vox.html

**Comment by scopatz** [comment]
Thanks for pointing this out though, @astronouth7303! The docs could be improved for these for sure.

**Comment by astronouth7303** [comment]
Yeah, they have API pages, but they don't have end-user command pages.

And I'm pretty sure the voxapi pages won't make sense unless you know how Vox works.

**Comment by gforsyth** [comment]
I'm going to close this in favor of the manual meta-issue where we are tracking all of these items.

#2315
