### ISSUE TITLE
[suggestion] STDIN should be streamed to functions when using pipes, not single strings

### ISSUE THREAD

**Issue by Dawil** [xonsh/xonsh#1686]
Thanks for the work on xonsh, it's a much needed advancement in shells.

I can use pipes to stream to a xonsh/python function:

```
$ echo foo | @(lambda args, stdin=None: print(stdin))
foo
```

the nice thing about this is I can interface with unix programs the way they expect, but do it with a one off python function instead of some convoluted bash. The problem is that stdin is a string. If I were to pipe a large amount of text into a xonsh function it would have to load it all at once before I can begin processing it. This goes against one of the principles of unix pipes, which is that they only process as needed.

My suggestion is that stdin ought to be an iterable:

```
$ def bar(args, stdin=[]):
..    for line in stdin:
..        print(len(line))
$ cat <<HERE | @(bar)
.. hello
.. world
.. HERE
5
5
```

NB: heredocs don't seem to work, but for the purposes of this example let's pretend they do.

Continuing in this line of reasoning, I think it would be natural if functions could yield their results:

```
$ def baz(args, stdin=[]):
..    yield 'hello'
..    yield 'world'
$ @(baz) | wc -l
2
```

 Lastly it would be great if pipes allowed the passing of python objects, instead of plain strings, in the cases where both sides of the pipe are python functions:

```
$ def qux(args, stdin=[]):
..    yield 1
..    yield [1,2]
$ @(qux) | @(lambda args, stdin=[]: [ print(type(line)) for line in stdin ])
<type 'int'>
<type 'list'>
```

I appreciate these changes may not be simple or fitting with your vision for the project.

**Comment by scopatz** [comment]
Hi @Dawil, Thank for reporting!  I am working on a refactor right now (`rs` branch) that should enable the kinds of redirections that you brought up.

**Comment by Dawil** [comment]
That's lucky timing on my part, then!

I had a quick glance at the commits but for someone unfamiliar with the codebase it makes about as much sense as you'd expect.

Is there a PR I can subscribe to so I can try the changes out once they're finished?

**Comment by scopatz** [comment]
There is no PR yet, @Dawil, because it is still in development.  Hopefully soon though.  I'll make a not on the issue once there is.

**Comment by scopatz** [comment]
I believe that this has been addressed in that PR. The 0.5.x series should have this. I am closing this but please feel free to reopen if it remains an issue.

**Comment by astronouth7303** [comment]
For the record, there's several signatures callable aliases can have, and some of them take streams instead. http://xon.sh/tutorial.html#callable-aliases
