### ISSUE TITLE
Problem with non-callables passed to evalx

### ISSUE THREAD

**Issue by meatballs** [xonsh/xonsh#1687]
When writing my new xontrib, I needed to extract the last command used from history and pass it into evalx.

I found that if I simply used `__xonsh_history__[-1]` it was passed as a string without first being evaluated.

Once I replaced it with the callable `__xonsh_history__.__getitem__(-1)` then it was evaluated first and the result passed to evalx.

Full details are available at https://github.com/meatballs/xontrib-thefuck/commit/8a929963884888270a5774afa8b1e1060a20d50e

**Comment by scopatz** [comment]
It is odd that you are using getitem in the first place?  What are you looking for exactly?  Is it the input?  If so you might try `__xonsh_history__.inps[-1]`

**Comment by scopatz** [comment]
Also, I would always expect the input to be returned as a string...  Thanks for reporting @meatballs

**Comment by meatballs** [comment]
The problem was that the string being passed was ```__xonsh_history__[-1]``` - it wasn't being evaluated at all.

**Comment by scopatz** [comment]
The flow control is still not clear to me, right now, but addmittedly, I  haven't tried it out.  @laerus has done the most work in history recently, so maybe he has a better sense of things :)

**Comment by meatballs** [comment]
if the last command in the history was 'puthon'
```
def _new_command(args, stdin=None):
      last_command = __xonsh_history__[-1]
      evalx('thefuck {}'.format(last_command))
```

results in 
```
thefuck __xonsh_history__[-1]
```
which fails.

Using a callable instead:
```
def _new_command(args, stdin=None):
     last_command = __xonsh_history__.__getitem__(-1)
      evalx('thefuck {}'.format(last_command))
```
results in
```
thefuck puthon
```
and is then corrected to 'python'

**Comment by laerus** [comment]
this is somewhat confusing. `__xonsh_history__[-1]` is turned into `__xonsh_history__.__getitem__(-1)` by python and doesn't do any evaluation, its just returns a string.

```
>>> __xonsh_history__.__getitem__(-1) == __xonsh_history__[-1] == __xonsh_history__.inps[-1].strip()
True
>>> print('ok')
ok
>>> evalx(__xonsh_history__[-1])
ok
>>> print('ok')
ok
>>> evalx(__xonsh_history__.__getitem__(-1))
ok

```

**Comment by laerus** [comment]
Hey @meatballs! have you managed to get this to work or have any more info on what's the actual issue?

**Comment by scopatz** [comment]
Closing due to age.  Please reopen if it persistes
