### ISSUE TITLE
Vox lists organization directories

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1689]
When using organized venvs (that is, venv names with slashes in them), `vox list` will show the organizational directory as a venv.

(Also, it doesn't show envrionments under it.)

```
$ vox create spam/eggs
$ vox list
spam
```

**Comment by laerus** [comment]
Should we even allow names like these?

**Comment by astronouth7303** [comment]
I would say yes, so that big, complex, multi-part projects can map relatively cleanly to vox venvs.

**Comment by gforsyth** [comment]
conda and vox don't get along, so I can't test this -- is there any difference if you first create `spam` and then `spam/test`?  
And what is the desired behavior of the venv name with a slash?  It should create a directory or no?

**Comment by astronouth7303** [comment]
I don't think there is, but it's a case to be careful of. Doesn't help that different platforms use different content names. I feel like this should be discouraged, but it's not technically disallowed.

It does create a directory. `spam/eggs` will create the directories `~/.virtualenvs/spam`, `~/.virtualenvs/spam/eggs`, `~/.virtualenvs/spam/{bin,lib}`, etc.
