### ISSUE TITLE
just rebuilt, tested - xonsh wins!

### ISSUE THREAD

**Issue by PaulReiber** [xonsh/xonsh#1698]
Greetings,

Happy to share what I'm seeing w/ latest build.  
```
pbr@mongo:~$ xonsh
aliases: alias 'fgrep' of shell 'bash' tries to override xonsh alias, xonsh wins!
aliases: alias 'grep' of shell 'bash' tries to override xonsh alias, xonsh wins!
aliases: alias 'egrep' of shell 'bash' tries to override xonsh alias, xonsh wins!
aliases: alias 'ls' of shell 'bash' tries to override xonsh alias, xonsh wins!
pbr@mongo ~ $ 

```
...wondering why xonsh has to win here.

**Comment by gforsyth** [comment]
Hey @PaulReiber, I know one specific problem we were trying to avoid with this (there are probably others).  `zsh` has a `history` alias that itself aliases a `zsh` command `fc` which `xonsh` doesn't have, so the alias just breaks and gives a message about `fc` not installed.  If there are conflicts with builtin `xonsh` aliases, we override to avoid these sorts of problems.  

You can definitely re-override them by setting them in your `xonshrc`.

**Comment by scopatz** [comment]
Thanks for reporting @PaulReiber. In addition to what @gforsyth said, I think that we can change the text of "xonsh wins!" to be more clear that xonsh is ignoring that alias and using the existing xonsh one.

**Comment by laerus** [comment]
i did that 'xonsh wins' cause everything else was too long, what exactly do you want to message to say @scopatz ?

**Comment by PaulReiber** [comment]
Can we look at this from, say, 50 feet up instead of so close?
My concern's not with the message - it's with what's going on.

This is the xonsh shell, not zsh, not bash, not csh, not tcsh, not dash.

My first thought when I learned that xonsh was reading my .bashrc was:
 WHY?!?!?  (yes, the thought in my head had the exclamation marks and
question marks along with it)

Why's it reading in startup files designed to be used by OTHER shells as it
starts up?  I'm looking at this and pondering:

What are the responsibilities of a shell?

Is xonsh (a) missing anything it should be doing or (b) doing anything it
shouldn't be doing?

Is xonsh maintaining a proper separation of concerns?

Traditionally the environment's the only thing a parent shares with the
child process, data-sharing wise.  There's nothing in Linux that says child
processes which happen to be shells should process the config files of
$SHELL as well.

Maybe I'm missing something?

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by laerus** [comment]
Do you mean that xonsh should not load aliases and such from other shells?
It would be cumbersome to rewrite all aliases one might have from bash/zsh in .xonshrc,
this is done mostly for old users that have big rc files and/or 
maybe they want to use both bash and xonsh with the same aliases. 
For a new user this doesn't make much of a difference, 
they will never add a foreign shell and all is good.

**Comment by PaulReiber** [comment]
> Do you mean that xonsh should not load aliases and such from other shells?

Well, maybe not by default?  We might have it be an available xonsh startup
feature but only if the end-user specifies they want that?

> It would be cumbersome to rewrite all aliases one might have from
bash/zsh in .xonshrc,
> this is done mostly for old users that have big rc files

I'm not against the feature - only surprised that it happened by default.

My bash aliases are whatever my system defaulted to giving me.  That's just
about how it'll be for new users too.

> maybe they want to use both bash and xonsh with the same aliases.

Well, yes - and this is what I thought I was getting from xonsh - in that,
whenever within xonsh I'm in "subprocess mode" I would get the same
behaviour I get from $SHELL. If it's a bash alias, it'd be there.

I'm realizing as I write this that I had made a somewhat large assumption
there. However, if that assumption doesn't hold, I think it may confuse a
lot of people.

> For a new user this doesn't make much of a difference,

As I mentioned above I don't heavily customize so my UX is usually pretty
close to what 'a new user' will see.  In this case - they'll see these odd
messages about aliases they didn't even know they had now getting
overridden by xonsh aliases of the same name.  If they're new enough new
user they won't even know what an alias is.  If they're like me, they may
not have even realized there were a few simple aliases that my system's
bash config had thrown in 'for good measure'.

> they will never add a foreign shell and all is good.

I didn't 'add a foreign shell' either (at least, I don't think I did)

I pulled down the latest master from github and built and installed,
replacing the previously installed xonsh on my system.   I enjoyed that
wonderful apprehensive moment I always feel when I first run something that
just finished compiling.  Then I saw these odd messages I'd never seen with
my earlier testing, and I decided to share them.

Finally... I'm still wondering about the basic question, "why?"

Most systems process their startup files in a specific order.  Settings
done by files earlier in the list-of-files are sometimes intentionally
overridden with new values in other config files loaded later.

This seems to be saying "earlier guy wins" which doesn't sound right to me.

Happy to share, hope it's helpful.  If you have further questions, just ask.

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
> Well, maybe not by default?  We might have it be an available xonsh startup
feature but only if the end-user specifies they want that?

Xonsh no longer loads any foreign shells by default.  There must be something in your configuration that is doing this.

**Comment by PaulReiber** [comment]
Thanks, Anthony,

Happy to check and confirm.  Where's that probably going to be hiding?


Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
In your config.json

**Comment by PaulReiber** [comment]
Found it:

pbr@mongo:~/xonsh$ cat /home/pbr/.config/xonsh/config.json
{
 "foreign_shells": [
  {
   "login": true,
   "shell": "bash"
  }
 ],
 "xontribs": [
  "mpl"
 ]
}

...That must have been put there by the xonfig wizard some time ago.

I didn't quite grok that xonsh was using ~/.config/xonsh directory.

 Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by laerus** [comment]
we can always just ignore the aliases silently (maybe if `XONSH_DEBUG=0`) and talk about it in the docs.

**Comment by scopatz** [comment]
Yeah, maybe that is the right thing to do.

**Comment by laerus** [comment]
closing since #1712 has been merged, feel free to reopen!
