### ISSUE TITLE
Auto build docs meta issue.

### ISSUE THREAD

**Issue by Carreau** [xonsh/xonsh#1699]
I'm opening a meta issue about auto-doc building to track the things I want to tackle before having a fully-auto deploy especially if we want to keep docs for multiple version of Xonsh. Mostly inspired by issue we struggled with in IPython. 
## build docs in a `Y.x` subfolder.

Potentially `x` being a literal `x`, and figure out how to expose a javascript version switcher (à la read the docs), which reads the available urls dynamically from a json file (?) thus allowing old docs build to include a switcher to newer versions.
## Rel-canonical.

We failed to include a way to set `<link rel='canonical'>` for IPython docs. Thus Google have overly indexed old version of the docs with IPython version number in url, and it's extremely painful to have these de-index and/or to figure out how to rebuild them. 

Proposal, have all xonsh-documentation page have a rel-canonical that point to an url containing `stable` in place of the version number, even if this imply have 2 copies of the docs. With `stable` always being the latest release which is potentially a duplicate of a `X.y` version.

A way to modify this rel-canonical globally without rebuilding the old docs (if we want to move the docs one day), would be useful as well.
## get a /stable/ and /latest/ url

Potentially with a "no-index" "no-follow" on "/latest/"

Note that despite /stable/ being technically a duplicate of a "X.y" url, it is useful to have both at the same time, especially when referencing things. 
## figure out "no-index" "no-follow" on old-docs

If would be nice to have a quick way to no-index old doc build without rebuilding (which is a pain). 
Maybe an HTML comment than can be easily parsed and removed ?

**Comment by gforsyth** [comment]
We don't have the javascript switcher, but we are using `doctr` to maintain separate "stable" and "dev" docs.
