### ISSUE TITLE
py.test does not load xonsh plugin.

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1700]
I don't really have any idea how to get this working so any pointers would be nice :)

**Comment by laerus** [comment]
btw i think they deprecated `py.test` in favor of `pytest`

**Comment by scopatz** [comment]
No dice on the `pytest` trial.  It still does does not run the test*.xsh files

**Comment by melund** [comment]
I will try to look into it. Did it happen when we upgraded to pytest 3? Also if setuptools is not available on install I think the plugin will not will not register. There may be some workarounds for that.

**Comment by melund** [comment]
I don't see the problem locally. I think it is because setup_tools is missing when running tests. Should we add setup_tools to the tests requirements or shall I look at workaround that doesn't involve setup_tools in tests.

**Comment by scopatz** [comment]
This happens on both pytest 2 and pytest 3. Also I tired some of the workarounds and that doesn't seem to affect it.  When I ask pytest to show the list of registered plugins, it is in there.

**Comment by melund** [comment]
Seems that circle does run the xsh tests, but AppVeyor does not.

```
case $CIRCLE_NODE_INDEX in 0) py.test --timeout=10 ;; 1) py.test --timeout=10 ;; esac
============================= test session starts ==============================
platform linux -- Python 3.4.5, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/ubuntu/xonsh, inifile: setup.cfg
plugins: timeout-1.0.0, xonsh-0.4.6
collected 2716 items 

tests/test_xonsh.xsh ...
tests/test_aliases.py .........
...
```

```
C:\Python35\Scripts\py.test
============================= test session starts =============================
platform win32 -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: C:\projects\xonsh, inifile: setup.cfg
plugins: cov-2.3.0, flake8-0.5, timeout-1.0.0
collected 2715 items
tests\test_aliases.py ....s......
tests\test_ast.py ...............
...
```

@scopatz Is it locally you have the problem?

**Comment by melund** [comment]
The problem with AppVeyor is because setuptools is not installed. I think we can make a workaround for that, by registering the plugin manually in the top-level conftest file if setuptools is not available.

**Comment by scopatz** [comment]
Yeah, it is locally that I had the problem, I do have setuptools, and I tried the conftest fix but it dind't work.

**Comment by melund** [comment]
The files have to start with `test_`  and end with `.xsh`. Can you try adding a `import pdb;pdb.set_trace()` to https://github.com/xonsh/xonsh/blob/master/xonsh/pytest_plugin.py#L33

Just to see if the ever looks for files.

**Comment by scopatz** [comment]
Hi @melund - yeah.  I never seems to call that function at all.  Weird.

**Comment by scopatz** [comment]
This seems to be fixed for me now. No clue what changed, but I'll accept it.
