### ISSUE TITLE
Cmd highlighting and completer uses upper case commands on Windows

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1702]
On Windows the keys of the `command_cache` are all stored in upper case. This is a bit of problem since we are starting to use the keys of the `command_cache` for all kinds of things. 

This has the effect that it doesn't highlight commands unless they match the uppercase key in the command_cache. Here is an example with `git` which only highlight if we specify `GIT.EXE`

![image](https://cloud.githubusercontent.com/assets/1038978/18379185/5b562e82-7671-11e6-891f-05e0fe9c49d6.png)![image](https://cloud.githubusercontent.com/assets/1038978/18379198/74992eb2-7671-11e6-8ed4-84e96f9e5c8a.png)

Another problem is the command completer which shows the commands in upper case: 

![image](https://cloud.githubusercontent.com/assets/1038978/18379229/a3dda3b0-7671-11e6-80e8-0e725b782e4d.png)

**Comment by gforsyth** [comment]
Hey @melund -- do you remember why we're storing the commands in uppercase on Windows?  Is there a potential simple fix to be had here by preserving case?

**Comment by melund** [comment]
Because @scopatz thought it was a good idea :) The keys have to be unique, so to handle case-insensitivity all command keys are changed to upper-case. I don't think he expected the keys to really be used for other stuff than looking up the path of the command. 

I guess we could change it to use the orginal case for keys but keep the property that 'git/Git/GIT.EXE' all still look up the same command.

**Comment by scopatz** [comment]
Yeah, the PATHEXT stuff really threw me off originally :).

**Comment by gforsyth** [comment]
> Because @scopatz thought it was a good idea :)

That's a reasonably good excuse.

> I guess we could change #1703 to use the orginal case for keys but keep the property that 'git/Git/GIT.EXE' all still look up the same command.

That seems like a good idea to me

**Comment by gforsyth** [comment]
Closed via #1703
