### ISSUE TITLE
Xonsh doesn't invoke data file that is associated with a command

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#1714]
"Invoking" a data file for which the shell has an executable file type extension registered is a pure Windows-ism, but it is handy.  

``` cmd
$ d *.htm
 Volume in drive C has no label.
 Volume Serial Number is D4E1-33F8

 Directory of C:\Users\bobhy\Documents\My Web Sites\WebSite1

17-Apr-15  12:41 PM               691 iisstart.htm
               1 File(s)            691 bytes
               0 Dir(s)  146,260,512,768 bytes free

$ which -v git.exe
C:\Program Files\Git\cmd\git.exe (from PATH element 11)
$ which -v iisstart.htm
iisstart.htm not in $PATH or xonsh.builtins.aliases
$ cmd /c 'assoc .htm'
.htm=htmlfile
$ cmd /c 'ftype htmlfile'
htmlfile="C:\Program Files\Internet Explorer\IEXPLORE.EXE" %1

$ iisstart.htm                      # short pause, then nothing happens
$ cmd /c 'iisstart.htm'        # opens iisstart.htm in browser, as expected
```

I'll take a crack at fixing this if someone will provide a pointer where to start.  I don't think it's the parser, I compared the debug output for `iisstart.htm' with`git.exe` and saw the same sequence of states (whew).

**Comment by gforsyth** [comment]
Hi @bobhy -- sorry for the delay in responding!  I would normally suggest that something this OS-specific belongs in a xontrib (and it very well may) but I think it requires some fiddling with `run_subproc` which is... well, a bit of a monster.

**Comment by scopatz** [comment]
This should be easier to approach with #1758, since it is effectively the same logic as `$AUTO_CD`.  We could consioder doing something similar using open/xdg-open for Mac and Linux.  Maybe an `$AUTO_OPEN` envvar could turn this on and off?  I would be in favor of this :)

**Comment by scopatz** [comment]
Probably best in a xontrib
