### ISSUE TITLE
Auto quote file names with and/or

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#1721]
We already do this for names with spaces. If a filename has the word `and` in it then the resulting command is almost certainly not what the user expects. Instead, the name should be wrapped in quotes automatically.

**Comment by laerus** [comment]
with #1432 and all maybe we should generalize this a little more and quote more args in subproc mode?

**Comment by gforsyth** [comment]
That's a good conversation to have.  i should clarify that I mean this specifically in completion results

**Comment by scopatz** [comment]
I am pro this!

**Comment by gforsyth** [comment]
Closed via #1748
