### ISSUE TITLE
tab completion after tab completion

### ISSUE THREAD

**Issue by nhumrich** [xonsh/xonsh#1725]
Sometime when I do things, I use tab-completion chained together. 
For example I might type `~/co` and hit tab with multiple options, and the one I want it `code`, then I want to select that option and keep hitting tab. 

Is this supported? I cant figure out how to select an option and make the tab selection menu go away without me typing anything. 
I am used to fish, and when you hit enter, it selects the completion. In xonsh, if I hit enter, it executes the command immediately and I cant keep completing.

**Comment by gforsyth** [comment]
Hey @nhumrich, thanks for the question!

You can set `$COMPLETIONS_CONFIRM=True` in your `.xonshrc` and then you can hit Enter to accept a completion without executing the current line

**Comment by nhumrich** [comment]
Thats awesome. Thanks.
Just curious, is there a reason this isnt the default behaviour? Is there a case where the opposite would be expected of new users? If so, is hitting enter really all that bad for new users? Maybe true should be the deafult and people can override it by setting to False?

**Comment by gforsyth** [comment]
It's a new-ish addition, but yeah, I would be fine with having it set as default True.  If there's a consensus among the other @xonsh/core-developers then we can switch it over.

**Comment by Carreau** [comment]
The "Enter Execute" is an "issue" only on simple line, as it often will not execute on multi line statements.
People did complain a lot on the IPython side every time we touch the completion a bit, though the current state is Enter to pick up completion, and we did not had too many long-term complain, so I'm or switching default.

**Comment by melund** [comment]
Having the same default behavior as IPython is a good idea. I think I am for it as well although I better try it :)

**Comment by scopatz** [comment]
I am -1 on switching the default, as I think that case-in-point people who want it will go looking for it.  As always though, feel free to outvote me - especially for consistency reasons :).

**Comment by nhumrich** [comment]
@scopatz you could argue those who dont want it will go looking for it as well. Hitting enter twice isnt bad, but hitting enter and having it execute before you wanted to could cause issues

imagine: `git push -f mas[tab][enter] when you really wanted `git push -f master:some_other`

**Comment by scopatz** [comment]
Again, feel free to out vote me :).  I think an implementation would go a long way here.

**Comment by gforsyth** [comment]
I'm going to close this out.  Ping if you have strong feelings about changing defaults and want to champion that issue.
