### ISSUE TITLE
More robust prompt formatter

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1731]
As is it now if there is a bug on any of the functions that return a value for the formatter dict the whole prompt turns ugly. Maybe we want a more robust way to handle the formatting and explicitly show an error about the specific value and not turn the prompt useless without any warnings.

**Comment by scopatz** [comment]
Yup, I would definitely be in favor of this. I think it is probably just a small modification to the except block in the formatter func.

**Comment by laerus** [comment]
also all the prompt formatting stuff should be moved to the `xonsh.prompt` package.
