### ISSUE TITLE
ImportError importing anything

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1733]
Without modifying `sys.path`, I get an `ImportError` when I try to `import` anything at all (that is already `pip` installed).

It is fixed in my `.xonshrc` by:
```python
import sys                                                                                                                  
sys.path.extend([                                                                                                           
    p for p in eval($(python3 -c 'import sys; print(sys.path)'))                                                            
    if p not in sys.path                                                                                                    
])
```
which works, but feels _so_ wrong.

Any idea what the real problem is, or a better solution?

**Comment by laerus** [comment]
hey @OJFord, thanks for reporting! Can you please show the value of `$PATH` ?

**Comment by OJFord** [comment]
```sh
$ $PATH
['/usr/local/bin', '/usr/local/opt/coreutils/libexec/gnubin', '/usr/bin', '/usr/sbin', '/bin']
```

What'd I miss? 😫 🔫

**Comment by laerus** [comment]
`$PATH` seems okay, can you also please show the output of `xonfig` and `sys.path` before modifying it?

**Comment by OJFord** [comment]
```sh
$  xonfig
+------------------+-----------------+
| xonsh            | 0.4.6           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.7             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
$ import sys; sys.path
['/usr/local/Cellar/xonsh/0.4.6/libexec/bin',
 '/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python35.zip',
 '/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5',
 '/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/plat-darwin',
 '/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/lib-dynload',
 '/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5',
 '/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin',
 '/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages']
```

I think the key one missing that is in Python's `sys.path` is `/usr/local/lib/python3.5/site-packages`? I just added all missing (4, including the empty-string `cwd` as discussed in #1563) to be sure.

**Comment by laerus** [comment]
Yeah something is missing for sure, maybe this is a bug in our part, this needs more investigation.

**Comment by gforsyth** [comment]
I think this may be an issue with the `brew` recipe

**Comment by OJFord** [comment]
@gforsyth It seems to install it into a virtualenv, that's surely not right?

My `.xonshrc` fix for it effectively makes non-venv packages available too.

**Comment by gforsyth** [comment]
Yeah, I think that's right and then it symlinks a bunch of stuff.  Xonsh will use the `sys.path` associated with the python env it was installed to, which may be why you able to import without the path hack.  

A few things to try out for more info:

1. Without your `sys.path` hack, can you import standard library modules?  does `import os` work? (I imagine yes, since `import sys` seems to work fine...)
2. Within xonsh, if you `pip install` something, then restart xonsh, can you import that module?  
3. What does `which pip` and/or `which pip3` say?

**Comment by OJFord** [comment]
@gforsyth Thanks for your reply; sorry for the delay, was on a different machine earlier.

1. Yes, I can `import os; import sys` et al
2. No, restarting has no affect
3. `pip` is an alias of my defining to `pip3`; `which` is `brew install`ed to `/usr/local/bin/pip3`

**Comment by gforsyth** [comment]
Thanks @OJFord !

is there a `pip` installed in `/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/` anywhere?  (not in that exact directory, but in a `bin/` directory somewhere within that tree)

**Comment by gforsyth** [comment]
Hey @OJFord -- so without using brew (or having a mac) I can't confirm this, but my suspicion is that brew installs xonsh into its own virtualenv, as you mentioned above.  Then it symlinks it into `/usr/local/bin` or whatever the brew equivalent is.  `sys.path` in xonsh will only have entries for the corresponding python install (unless, as you have done, you edit it).  

So this is more of a brew issue than anything else (if I'm right).  Workarounds would include installing xonsh with `pip`, which would install it where you have the rest of your python libraries installed, or, conversely, using the `pip` that's included in the `xonsh` python installation (this seems messier).  

In terms of fixing the brew recipe, I think you could symlink the `site-packages` directory corresponding to brew `pip` into the `xonsh` install and it _should_ make all your pip-installed packages available.  No promises there, though...

**Comment by OJFord** [comment]
Thanks @gforsyth - I'll have a play with the brew formula later.

It will be complicated by the fact that a brew user may still be using system pip, but should be surmountable.

**Comment by gforsyth** [comment]
Hey @OJFord -- closing this out as it appears to be a brew issue, but please reopen if issues persist after any brew fixes are applied.  Thanks!
