### ISSUE TITLE
XSH Import uses console encoding

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1737]
I would think that when importing xsh files, the same encoding rules as importing Python should apply. That is:
- If an encoding header is found, use that
- Default to UTF-8

(I discovered this when loading `xontrib-powerline` on Windows.)

**Comment by scopatz** [comment]
Hi @astronouth7303, thanks for pointing this out.  I think this runs into locale issues too.  I really have no idea what the story on windows is like.

**Comment by astronouth7303** [comment]
Well, "console encoding" is the current locale on linux.

Currently, windows is ASCII. I think that's slated to change in 3.6 when they add a wrapper around the console-specific functions.

**Comment by scopatz** [comment]
Potential fix in #2263

**Comment by scopatz** [comment]
Closing because #2263 has been merged, please reopen if needed.
