### ISSUE TITLE
Multi-command aliases

### ISSUE THREAD

**Issue by sopoforic** [xonsh/xonsh#1739]
Making an alias perform multiple commands is troublesome. Right now, as far as I can tell, the only choice is to write a function and point the alias at it. Trying to write the alias naively gives confusing and unexpected results, if you don't know how aliases are parsed:

```
$ echo "foo" and echo "bar"
foo
bar

$ aliases['foo'] = 'echo "foo" and echo "bar"'
$ foo
foo and echo bar
```

Whereas in bash I can:

```
$ echo "foo" && echo "bar"
foo
bar

$ alias foo='echo "foo" && echo "bar"'
$ foo
foo
bar
```

**Comment by laerus** [comment]
Hey @sopoforic thanks for reporting! We don't support this yet, a workaround is to make the alias a function like so 
`aliases['foo'] = lambda *args, stdin=None: echo foo and echo bar`

**Comment by laerus** [comment]
Hey @sopoforic thanks for reporting! We currently don't support this, a workaround would be to define a function for the alias:
```
def _foo(*args, stdin=None):
    echo foo and echo bar

aliases['foo'] = _foo
```

**Comment by sopoforic** [comment]
Yes, that's what I'm doing now. It'd be nice for this to be supported in a simpler way, but I think the bigger problem is that it breaks expectations--you'd expect `aliases['foo'] = 'bar'` to result in `foo` and `bar` being equivalent commands, but that's not the case.

**Comment by PaulReiber** [comment]
In bash and some other shells as well, running an alias 'a' from the
commandline result in a whole new commandline generated by 'a' getting
parsed end-to-end, from ^ to $ and run as a separate entity.  ...and,
arguments to the alias provided by the end user when it's run can be passed
into the resulting string anywhere.  By that I mean that 'a p1 p2 p3' can
result in this, in bash:  'cmdA p1 | cmdB p2 | cmdC p3' for example.

Wouldn't it be pretty straightforward to do the same in Xonsh? I would
think the results of an alias expansion would be the entire commandline,
which then has to be re-evaluated to figure out what parts of it are
python, vs. bash, i.e. starting over on it.

Hope that helps,

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
This *might* be easier to address in a future version of run subproc.  Right now it is kind of a pain.

**Comment by scopatz** [comment]
The base issue is solved with `ExecAlias`. However this isn't triggered on `&&` or `and`, etc. So we probably need to update this to be fixed.  Right now you can do this with a semicolon:

```bash
scopatz@artemis ~ $ aliases['foo'] = 'echo "foo"; echo "bar"'
scopatz@artemis ~ $ foo
foo
bar
scopatz@artemis ~ $ aliases['foo']
ExecAlias('echo "foo"; echo "bar"\n', filename='<exec-alias:foo>')
```

**Comment by gforsyth** [comment]
I don't know _when_ we fixed this, but we did.

```
(base)   ~ 🐚  aliases["mytest"] = "echo foo && echo bar"
(base)   ~ 🐚  mytest
foo
bar
(base)   ~ 🐚  aliases["mytest"] = "echo foo and echo bar"
(base)   ~ 🐚  mytest
foo
bar
(base)   ~ 🐚  aliases["mytest"] = "echo 'foo' and echo 'bar'"
(base)   ~ 🐚  mytest
foo
bar
```
