### ISSUE TITLE
Logical operators wrongly detected in subprocess mode

### ISSUE THREAD

**Issue by chronitis** [xonsh/xonsh#1742]
This is a fairly minor case, (and can easily be handled by quoting), but this didn't behave how I expected:

    $ mkdir a_and_b
    # works as expected
    $ mkdir a.and.b
    xonsh: subprocess mode: command not found: .b

I would expect the operator not to be seen here, since `a.and.b` is a single word by normal shell rules. This is presumably the result of splitting on `!\w`, but I couldn't work out exactly where in the parser it happens.

**Comment by laerus** [comment]
Hey @chronitis thanks for reporting! this has been addressed at #1721

**Comment by chronitis** [comment]
Ah, sorry. Should have spotted that.

**Comment by laerus** [comment]
Well actually my bad, #1721 is about completion. This falls into the list of issues in #1432,  i will include this there, reopening for now.
