### ISSUE TITLE
Highlighting breaks on --long-options

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1750]
When passing a long-name flag with two or more words, the highlighting is broken.

For example:
```sh
$ pre-commit run --all-files
```
highlights "--all-".

I believe the intention is to only highlight the hyphens? In this case however I'd suggest only the leading "--" should be highlighted.

**Comment by gforsyth** [comment]
Thanks for reporting @OJFord .  This sounds like an issue with the pygments lexer.

**Comment by blahgeek** [comment]
Hi @OJFord  is "pre-commit" a valid command? If it's not, then this line would be highlighted in python mode, in which "all" is a python keyword and "-" is a python operator, and so should be highlighted.

**Comment by OJFord** [comment]
@blahgeek Yes, but it was just an example - I see this behaviour with any command.

**Comment by blahgeek** [comment]
Could you please run `xonfig` and post the results here? I'm on current master version of xonsh and I can't seem to reproduce this issue.

**Comment by OJFord** [comment]
@blahgeek Sorry for the slow response, `xonfig`:
```
+------------------+-----------------+
| xonsh            | 0.4.6           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.7             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

I think I have a better clue though:
  - `ls --human-readable` highlights correctly (the three dashes);
  - `pre-commit run --all-files` still does not

Presumably the 'double-barrelled' command is throwing it off some how?

**Comment by blahgeek** [comment]
Thanks for your reply! Would you mind trying current master version of xonsh? This issue should already have been fixed by a new implementation of XonshLexer in #1711

**Comment by OJFord** [comment]
I'm sorry for the delay again - Github's auto-disappearing notifications make it easy to lose track if not actioned immediately on reading.

I'm not entirely sure what the desired highlighting looks like, but it no longer "looks broken" - on master the "pre-commit" is highlighted green, and "run --all-files" is not.

**Comment by gforsyth** [comment]
Ok, great!  I'll close this, then, but please reopen if there are any remaining highlighting issues.
