### ISSUE TITLE
Make gitstatus prompt customizable like the main prompt

### ISSUE THREAD

**Issue by t184256** [xonsh/xonsh#1756]
@blahgeek, I appreciate your `gitstatus` module and it's pretty nice.
The only thing it lacks now is proper prompt customizability.
I've tried to enhance it a little bit, so some parts of the whole 'numbers' part could be optional (see github.com/t184256/xonsh/gitstatus-flexible-join), but a better idea struck me while I was doing this.

`gitstatus` prompt should be customizable in the spirit of the main prompt. Something like that:
`'{branch_name}{operations:| {}}{dirty:|}{staged: {RED}●{}{NO_COLOR}}`...

`xonsh` customizers are supposed to already know this syntax from the tutorial, so that should lower the entry barrier and allow more flexible tricks at the same time.

As I understand, the code to handle such formatting is already in `xonsh`: [xonsh/prompt/base.py](xonsh/prompt/base.py), but judging by the leading underscores, it's private to that module and is subject to change. I'm new to `xonsh` (I learned about its existence less than 24 hours ago), so I'm currently not comfortable with reusing that code in `gitstatus` all by myself. At least not until I learn what is that strange `xonsh.lazyasd` and why is it there all over the code.

Regarding backwards compatibility with current `$XONSH_GITSTATUS_STAGED` and friends... I can only assume that if that lands before the next release, there will be no compatibility issues to worry about.

What do you think about this? Is the idea OK? Could you do that or hint me how to do that?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laerus** [comment]
Hey @t184256 thanks for bringing this up and for using xonsh! You can learn all about `lazyasd` in the [lazyasd repo](https://github.com/xonsh/lazyasd) but basically it's just a way to delay construction of global objects until we actually need to use them. You can also look at the implementation of the `lazyasd.LazyObject` which is very straightforward. I think that giving the user more freedom to customize their prompt is something we should have so +1 for that!

**Comment by laerus** [comment]
@blahgeek xonsh and gitstatus would benefit a lot if we split the code for gitstatus into a xontrib, care to maintain it?

**Comment by sbliven** [comment]
I expected gitstatus colors to be customizable through `$PROMPT_FIELD_COLORS` like other fields. I was disappointed to see that colors are hard-coded, with RESET inserted regularly so that background colors from surrounding prompt sections break (e.g. powerline3 sets a dark background, which gets reset jaringly by the clean symbol).
