### ISSUE TITLE
xonsh on login not having all commands available in emacs subshell

### ISSUE THREAD

**Issue by kootenpv** [xonsh/xonsh#1769]
I have setup xonsh to be my login shell. I have some command 'grip' that's available by default immediately in iTerm2. The problem is that somehow in Emacs whenever it executes in a subprocess, I assume my bashrc/bash_profile are ignored?

Does anyone have an idea what I should change?

**Comment by gforsyth** [comment]
Hi @kootenpv -- thanks for reporting!  
Just to clarify: You open `xonsh` in iTerm2 and you have the `grip` command available, but when you run `term` in emacs it isn't?  

Did you add `bash` as a foreign shell in your setup?

**Comment by kootenpv** [comment]
@gforsyth And thanks for answering on such short notice!

Yep. Steps:

1. xonsh then xonfig wizard
2. Resulting in the file `/Users/me/.config/xonsh/config.json`

```
{
 "foreign_shells": [
  {
   "login": true,
   "shell": "bash"
  }
 ]
}

```
3.  Ran `chsh -s /Library/Frameworks/Python.framework/Versions/3.5/bin/xonsh` to make xonsh my default shell
4. Logout, come back and notice that xonsh is working in iTerm2. grip works.
5. Open Emacs.app and executing any kind of "custom" commands do not work. `ag` doesn't work, `grip` doesn't work.

Any more information needed?

**Comment by gforsyth** [comment]
Are `ag` and `grip` both python scripts?

**Comment by kootenpv** [comment]
@gforsyth `grip` *is* a python script, `ag` isn't (C).

**Comment by gforsyth** [comment]
Ok.  So you are doing `M-x shell`, yes?  Then `xonsh` opens in the subshell but you can't use `ag` or `grip`.  What is the value of `$PATH` in the subshell?  If it's incorrect, you should be able to update it in your `xonshrc` and it will be loaded in the subshell.

**Comment by mandarvaze** [comment]
I have similar problem, that is NOT related to emacs. But it is related to $PATH

My default shell is ``zsh`` - In iTerm2, if I enter ``xonsh`` from within ``zsh``, all paths are set correct. 

I have NOT set xonsh as my default shell, but I have setup xonsh as a login shell for Hyper.app (Terminal Emulator built using Electron)

So when ever I open a new tab in Hyper - I directly enter into the xonsh shell
But the ``$PATH`` is incorrect - Value is set to :

    ['/usr/bin', '/bin', '/usr/sbin', '/sbin']

This itself seems wrong, because as per the [documentation](http://xon.sh/envvars.html#path) default value should contain ``/usr/local/bin`` where ``ag`` resides.

I think my ``.zshrc`` is still executed when in Hyper, because some other variables which are set only in ``.zshrc`` are visible (e.g. ``$ANDROID_HOME``, ``$GOPATH``)


    $ cat /Users/mandar/.config/xonsh/config.json
    {
     "env": {
      "SHELL_TYPE": "best",
      "XONSH_COLOR_STYLE": "native"
     },
     "foreign_shells": [
      {
       "shell": "zsh"
      },
      {
       "shell": "bash"
      }
     ],
     "xontribs": [
      "vox",
      "prompt_ret_code",
      "vox_tabcomplete",
      "z"
     ]
    }

I just upgraded to 0.5.0 (was on 0.4.6 for a long time) but that has not changed the behaviour.

**Comment by mandarvaze** [comment]
@gforsyth Do I need to explicitly set the $PATH in ``.xonshrc`` - if xonsh is (like) default shell ? (See above, why xonsh is not *exactly* default shell for me - but *like* a default)

**Comment by gforsyth** [comment]
Hi @mandarvaze -- that's weird. On OSX `/usr/local/bin` should be in default `$PATH`.  I'm not sure how Hyper sets things up in this instance, which may be contributing to the strangeness.  

You can explicitly _add_ to the `$PATH` in your `.xonshrc` to workaround the issue.  
Something like

```console
if '/usr/local/bin' not in $PATH:
    $PATH.insert(0, '/usr/local/bin')
```

**Comment by scopatz** [comment]
Hi @mandarvaze, are you starting Hyper through zsh or via the launcher?

**Comment by mandarvaze** [comment]
@scopatz via Launcher

@gforsyth -  Do you think this is because I **upgraded** from previous version ?

**Comment by gforsyth** [comment]
@mandarvaze - I don't think so, it shouldn't have made a difference.

**Comment by scopatz** [comment]
I suspect the $PATH is being set by the OS or the launcher.  I couldn't find anything in hyper that sets the $PATH. As @gforsyth says, you can either add the dir back to the PATH in your xonshrc file, or you can `del $PATH` in your xonshrc to have it fall back to the xonsh default.

Also, how do you like hyper? I have been thinking about moving to it.

**Comment by mandarvaze** [comment]
@scopatz For now, I've worked around the problem by explicitly adding ``/usr/local/bin`` to ``$PATH``.

> Also, how do you like hyper? I have been thinking about moving to it.

Not enough to switch away from iTerm2 on OSX. (due to the ``$PATH`` issue, I didn't use it for a while. May be I'll try to use it exclusively for some time, now that ``$PATH`` issue is resolved)

**Comment by scopatz** [comment]
Is this still occurring on master?

**Comment by gforsyth** [comment]
I'm going to close this out as "answered" but feel free to ping with additional questions / concerns

**Comment by SolidHal** [comment]
After switching my login shell to `xonsh`, I found emacs (spacemacs) would never start with the correct path, leading to tramp not finding the ssh command. 

My workaround for this was to add 
```
  (setenv "PATH"
          (concat
           "/usr/local/sbin" ":"
           "/usr/local/bin" ":"
           "/usr/sbin" ":"
           "/usr/bin" ":"
           "/sbin" ":"
           "/bin" ":"
           (getenv "PATH")
           )
          )
  (setq-default shell-file-name "/bin/bash")
```
to my emacs config which just brute forces the correct PATH and changes the default shell to bash. 

When I startup my emacs without this, it sees `$PATH` and `$SHELL` as:
```
~ $ (getenv "PATH")
${PATH-e7baaa3eabed3a41afd77b0e01a096a6}
~ $ (getenv "SHELL")
/usr/local/bin/xonsh
```

and when I startup my emacs with this, it sees them as:
```
~ $ (getenv "PATH")
/home/solidhal/android/bin:/home/solidhal/.local/bin:/home/solidhal/bin:/home/solidhal/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/solidhal/android/bin:/home/solidhal/.local/bin:/home/solidhal/bin:/home/solidhal/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/solidhal/android/sdk/platform-tools:/home/solidhal/android/android-studio/bin
~ $ (getenv "SHELL")
/bin/bash
```

to me, it looks like the way emacs and xonsh communicate about the $PATH variable is broken, `${PATH-e7baaa3eabed3a41afd77b0e01a096a6}` seems like a python pointer? 

Sorry for reviving this old thread, I can open a new issue if folks would prefer.
