### ISSUE TITLE
most commands don't work

### ISSUE THREAD

**Issue by komuW** [xonsh/xonsh#1773]
I've installed xonsh on OSX using brew, 
However most commands especially of python packages do not work(unix commands though do work)

 ~ $ xonsh
xonsh: subprocess mode: command not found: xonsh

~ $  pip
xonsh: subprocess mode: command not found: pip
Did you mean one of the following?
    pp:   Command (/usr/bin/pp)
    lp:   Command (/usr/bin/lp)

~ $ youtube-dl
xonsh: subprocess mode: command not found: youtube-dl

 ~ $ ls
Applications    Downloads       Music           VirtualBox VMs 
Desktop         Library         Pictures        bin  Documents       Movies          Public 

cat ~/.config/xonsh/config.json
{
 "env": {
  "AUTO_CD": true,
  "AUTO_SUGGEST": true,
  "COMPLETIONS_CONFIRM": true,
  "INDENT": "\"\"\"    \"\"\"",
  "MULTILINE_PROMPT": "\"\"\".\"\"\"",
  "SHELL_TYPE": "prompt_toolkit",
  "XONSH_CACHE_EVERYTHING": true,
  "XONSH_SHOW_TRACEBACK": true
 },
 "foreign_shells": [
  {
   "shell": "bash"
  }
 ]
}

**Comment by gforsyth** [comment]
hi @komuW -- thanks for opening the issue!

This sounds like a problem with your `$PATH`.  If you do a `which pip` and/or a `which xonsh` in Bash, do the directories containing those show up in `$PATH` in xonsh?

**Comment by komuW** [comment]
@gforsyth thanks for a prompt reply!

~ $ which xonsh
xonsh not in $PATH or xonsh.builtins.aliases

~ $ which pip
pip not in $PATH or xonsh.builtins.aliases

~ $ $PATH
['/usr/bin', '/bin', '/usr/sbin', '/sbin']

**Comment by gforsyth** [comment]
Hey @komuW -- ok, cool.  So it looks like your `$PATH` is just the default one that xonsh ships with.  However, if you use `brew` and whatnot, it symlinks a bunch of binaries to places like `/usr/local/bin` (I think... not a mac person).  So you want to find out where `pip` and `xonsh` live and then add those locations to `$PATH` in your `xonshrc` file so that they persist between sessions.

**Comment by komuW** [comment]
@gforsyth thanks! 
seems like brew didn't symlink `/usr/local/bin`. 
I just added that and now it works like a charm.

**Comment by gforsyth** [comment]
Woohoo!  Awesome.
