### ISSUE TITLE
git_dirty_working_directory always returns True if git not in english

### ISSUE THREAD

**Issue by xsteadfastx** [xonsh/xonsh#1776]
im using the latest version from master (commit 1c96dc4ab23ad67). i found out about the changes for `git_dirty_working_directory`. it checks for a dirty git directory in a different way. the old way was with `git status --porcelain` (https://github.com/xonsh/xonsh/blob/e10c38deccf94189012cca9864cac2bff77dd984/xonsh/environ.py#L1036) and right now it checks for the bytestring `nothing to commit` (https://github.com/xonsh/xonsh/blob/master/xonsh/prompt/vc_branch.py#L139). my git is in german so it always returns True. has it a deeper reason that it uses a new way of finding out about a dirty git directory? i thought i ask first before i send a pull request for using the old way again.

**Comment by laerus** [comment]
Sorry for this @xsteadfastx, this change was part of a fix on the `vc_branch.py`, i should have kept the function in it's older version.
