### ISSUE TITLE
Slicing the last result of a piped expression.

### ISSUE THREAD

**Issue by dam5h** [xonsh/xonsh#1784]
I needed to search via regex my zsh history so I tried the following in an effort to just retrieve the last line that is returned to stdout when I run the command.

`history show zsh | ack 'invoke\ make_' -1`

I get the following output:
```bash
invoke make_datapkg guids.out test_pkg
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
BrokenPipeError: [Errno 32] Broken pipe
```

That first line that you are seeing is the first line of the output, in total there are about 25 lines and I only want the most recent so that I can execute it.

Thanks for xonsh, I'm looking forward to taking it for a spin.

**Comment by gforsyth** [comment]
hey @dam5h -- that sort of slicing operation isn't supported since the output from the `ack` isn't going to be a python list (unless you make it one).  

So you could do:

`$(history show zsh | ack 'invoke\ make_').split('\n')[-1]`

but it's probably cleaner to just use `tail`, a la

`history show zsh | ack 'invoke\ make_' | tail -n 1`

**Comment by dam5h** [comment]
Great, that makes total sense to use tail in this case since I just want the last item.  While I have your attention whats the easiest way to then get that output to execute from the command line.  Is there a xonsh alias for the most recent output?  Thank you!

**Comment by laerus** [comment]
i think you can also do `@$(history show zsh | ack 'invoke\ make_' -1)`

**Comment by laerus** [comment]
you can access the last output with the underscore  `_` for example:
```
$ $(history show zsh | ack 'ls' -1)
'ls -l\n'
$ _
'ls -'\n'
$ @(_.rstrip())  <---execute
```

**Comment by dam5h** [comment]
This `_` approach only works for python results correct?  In subprocess mode I don't get anything from the `_` underscore character.
```bash
 ~/Code
$ ls -l | tail -1
drwxr-xr-x  5 dave users     4096 Jul 15  2014 zh_api
 ~/Code
$ _
 ~/Code
$ 
```

Thanks again!

**Comment by scopatz** [comment]
`_` is set to a special hidden object, which, like None, does not get printed in the display hooks.  However, you can still access its attribute to get info about the last command if you would like to.

**Comment by dam5h** [comment]
Very cool, I'll look in the source for more details.  Thanks.

**Comment by astronouth7303** [comment]
It's a [`HiddenCompletedCommand`](http://xon.sh/api/proc.html?highlight=hiddencompletedcommand#xonsh.proc.HiddenCompletedCommand). Of course, the documentation on that and `CompletedCommand` are pretty horrific.

**Comment by scopatz** [comment]
And those are going away in the subproc refactor...
