### ISSUE TITLE
Vi-mode `cw` inconsistent with actual vi

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1785]
In Vi,

> "cw" and "cW" are treated like "ce" and "cE" if the cursor is on a non-blank.  This is because "cw" is interpreted as change-word, and a word does not include the following white space.
-- http://vimdoc.sourceforge.net/htmldoc/motion.html#word-motions

This means that, if I type `brew search xonsh` in Vi(m), with my cursor placed at the beginning of 'search'; `cw` will allow me to type `install<esc>` to change the sentence to `brew install xonsh`.

In xonsh with `$VI_MODE == 1`, however, the same process would result in `brew installxonsh`.

It may sound trivial, but vim-users will spend more time using vim commands in vim than on the CLI, so it's hard to remember and if forgotten results in an un-executable command.

I've had a brief look at the source - it seems like these bindings might be outsourced to `prompt_toolkit`?

**Comment by gforsyth** [comment]
Hi @OJFord -- the entirety of `VI_MODE` is handled by prompt_toolkit, so you should raise this issue there.

**Comment by OJFord** [comment]
Thanks @gforsyth - I've opened jonathanslenders/python-prompt-toolkit#394.
