### ISSUE TITLE
release.xsh should submit a release to github

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1793]
I think the automated release script should also submit the changelog fragment to github as a [release](https://github.com/xonsh/xonsh/releases).

This process should be:
1. Read the merged news for that release
2. Run through pandoc (or similar) to convert the rst to markdown
3. Submit the converted news to [github as a release](https://developer.github.com/v3/repos/releases/)

**Comment by scopatz** [comment]
I totally agree with the automating of this.  I think (2) might not be strictly necessary, and I have used rst in that field before.

**Comment by astronouth7303** [comment]
That would explain some of the formatting behavior I saw doing some of the recent releases manually.

I wish there was an option to abbreviate the body on the index page.

**Comment by scopatz** [comment]
Yeah, me too

**Comment by gforsyth** [comment]
Closing via #2390
