### ISSUE TITLE
~ expands even if there is no user for it

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1794]
There are commands that expect a leading `~`, such as `git reset --hard "~HEAD"`. I don't think there's a way to escape this properly.

**Comment by gforsyth** [comment]
I think `HEAD` only takes trailing `~`s or `^`s for relative checkouts -- are there other commands that expect the leading `~`?

**Comment by adqm** [comment]
I am not able to reproduce this.  Running `git reset --hard "~HEAD"` (with or without escaping with quotes) works fine for me (git receives `~HEAD`), and tab completion of `git reset --hard ~HEA<tab>` does not seem to try to expand to `/home/HEAD`.  Is there something I am missing?

**Comment by astronouth7303** [comment]
@gforsyth Oops! You're right. I just ended up using the hash.

@adqm _That's_ odd. I'm currently on my Windows work box, and even with v0.4.7 it still happens.

**Comment by astronouth7303** [comment]
`echo ~HEAD` also works just fine.

**Comment by adqm** [comment]
Extra interesting!  Maybe something Windows-specific?  I'll be around a Windows machine this evening, and I can try to test there.

**Comment by astronouth7303** [comment]
Yes, it is. `ntpath.expanduser()` never actually checks the existence of anything, just looks up some environment settings and does some string manipulation. (`posixpath` actually calls out to the password database, where the home directory is stored.)

**Comment by scopatz** [comment]
Potential fix in #2268

**Comment by scopatz** [comment]
Please feel free to reopen if #2268 was not sufficient!
