### ISSUE TITLE
pdb console input not showing on screen when using xonsh

### ISSUE THREAD

**Issue by dam5h** [xonsh/xonsh#1797]
This is a bit odd but I am doing some debugging on an application and have entered `ipdb`.  For some reason when I launch the application from a xonsh shell I cannot see the letters that I type in the `ipdb` console.  Specifically I am working on a desaktop UI so I am using `pdb4qt`.

I tried a simple test outside of PyQt as well and had the same issue with regular `pdb`.

Anyone have any ideas?

**Comment by gforsyth** [comment]
Hey @dam5h -- this is a problem with stdin redirection.  For what it's worth, this is not an issue with the pending (and nearly merged) refactor that @scopatz is working on, so it should be resolved shortly.

**Comment by dam5h** [comment]
Great, good to hear.  Thanks for the rapid response!

**Comment by gforsyth** [comment]
Fixed in #1758
