### ISSUE TITLE
xexec crashes xonsh

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1807]
`xexec echo tt`
`xexec ls`

anyone can reproduce?

**Comment by laerus** [comment]
oh well xexec replaces current xonsh instance so i guess this is not a bug.

**Comment by astronouth7303** [comment]
Is that the shortest lived bug we've ever had?

**Comment by laerus** [comment]
:laughing: maybe, i may have opened a shorter living bug in the past.
