### ISSUE TITLE
Nested lookup in $PROMPT

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1809]
As described in #1660 (pinging @scopatz, who there suggested opening a separate issue) it would be nice to 'nest' lookup properties like `curr_branch` in config.json values.

For example, my prompt is currently:

```
"{env_name:{} }{cwd}{curr_branch: (}{branch_color}{curr_branch:{}}{NO_COLOR}{curr_branch:)}{prompt_end}"
```

which routinely times out when opening a new tab, and could anyway be much simplified to:

```
"{env_name:{} }{cwd}{curr_branch: ({branch_color}{}{NO_COLOR})}{prompt_end}"
```

if such nested lookup were supported.

The cleanest way to implement this currently is a `lambda`, but it seems unfortunate to move it out of the config.json when it is in fact a static configuration.

**Comment by astronouth7303** [comment]
`config.json` just sets `$PROMPT`. This has to deal with how `$PROMPT` (and `$TITLE`, etc) are formatted.

**Comment by OJFord** [comment]
Yes, sorry, I wasn't sure if other keys in `config.json` took the same or similar formatting tags and would similarly benefit.

**Comment by astronouth7303** [comment]
I do wonder, though: What's the upper limit on complexity for the `$PROMPT` template language? Do we allow full django/jinja-like templating?

Maybe instead we could have the ability to embed python expressions like

```
"{env_name:{} }{cwd}{? ' (' + branch_color + curr_branch + NO_COLOR if curr_branch else '' ?}{prompt_end}"
```

**Comment by OJFord** [comment]
Personally, my preferred solution would be ditching `config.json` entirely, and embedding Python expressions natively via a lambda if not a truly static string. But my preference carries no weight :)

If you were to go that way, I think it could be better accomplished with Python 3.6 'literal string interpolation' [PEP 498](https://www.python.org/dev/peps/pep-0498/) than re-implementing it with a new DSL. I suppose that doesn't work if 2.7 support is a long-term goal though.

**Comment by astronouth7303** [comment]
>  I suppose that doesn't work if 2.7 support is a long-term goal though.

It's not.

**Comment by astronouth7303** [comment]
BTW, `.xonshrc` is a thing. I, myself, don't use `config.json` and do it all by hand in `.xonshrc`.

**Comment by OJFord** [comment]
Yep, but my `config.json` sets the `.xonshrc` location, so it made sense to me to do as much else there as possible. Though now that I say that, obviously it is picked up okay itself, so perhaps I need to revisit the way it's configured...

**Comment by OJFord** [comment]
Actually @astronouth7303, I just realised that in this case moving it to `.xonshrc` has no benefit, since unless I'm mistaken the `lambda` for `$PROMPT` would be given no arguments; so it doesn't know whether it's in a git repo any more than the string in `config.json` does?

Goal is to do `{curr_branch: (}{branch_color}{curr_branch:{}}{NO_COLOR}{curr_branch:)}` for `(branch_name)` where parentheses are not coloured without 3 calls to `get_git_branch`.

**Comment by astronouth7303** [comment]
@OJFord They could always ask `os.getcwd()` or `$FORMATTER_DICT['curr_branch']`.

**Comment by OJFord** [comment]
Oh, thanks, I didn't know about that. I'm now doing:
```python
def branch_prompt():
    branch = $FORMATTER_DICT['curr_branch']()
    if branch is None:
        return ''
    else:
        return '({{branch_color}}{}{{NO_COLOR}})'.format(branch)
$PROMPT = lambda: '{venv}{cwd}{branch}{{prompt_end}}'.format(
    venv='{env_name:{} }',
    cwd='{cwd}',
    branch=branch_prompt()
)
```

which is a little messy, but at least it only makes one subprocess call to determine the branch.

**Comment by astronouth7303** [comment]
You can assign `branch_prompt` directly to `$FORMATTER_DICT` and use it that way. The way you have it, it won't automatically update each prompt. (You'd have to manually recompute `$PROMPT` yourself each postcommand.)

**Comment by OJFord** [comment]
Ah, yes. So now it looks like:
```python
def branch_prompt():
    branch = $FORMATTER_DICT['curr_branch']()
    if branch is None:
        return ''
    else:
        return '({branch_color}{branch_name}{{NO_COLOR}})'.format(
            branch_color=$FORMATTER_DICT['branch_color'](),
            branch_name=branch
        )
$FORMATTER_DICT['branch_prompt'] = branch_prompt
$PROMPT = '{env_name:{} }{cwd}{branch_prompt}{prompt_end}'
```

which seems to be okay.

I still think nested lookup would be good though - `$PROMPT = "{env_name:{} }{cwd}{curr_branch: ({branch_color}{}{NO_COLOR})}{prompt_end}"` would be much neater!

**Comment by scopatz** [comment]
I think this is basically implemented
