### ISSUE TITLE
Add env variable for whether quotes should be added to tab-completions of files with spaces inthe name

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#181]
See #68

**Comment by wrywerytwreywery** [comment]
I am not sure how I feel about this.  Not adding quotes means that tab completion (as currently implemented) would lead to completions that aren't valid.  To me, it seems like if you want to turn off quotes, the only other valid option is not to offer completions for names with spaces in them.  Alternatively, we could allow escaping spaces with `\`, but that feels weird (to me, the "right" way in xonsh is to use Python strings for this, though I could understand that that might be a turn-off for some).

**Comment by scopatz** [comment]
I am not a huge fan of this either, which is why I won't implement it personally :).  Though I do empathize with people who want tools to work for them.  So if someone plopped down a PR that implemented this, I'd be all for including it.  I think the current behaviour should remain as the default, though.

**Comment by mfeif** [comment]
Hi there. You say that you want current behaviour to remain the default;

I'm having a weird thing wherein the "current behavior" is different on my Mac laptop vs my Ubuntu server. On Ubuntu:

```
touch "my file.txt"
ls my<TAB>
(leads to...)
ls my file.txt
```

On OSX:
```
touch "my file.txt"
ls my<TAB>
(leads to...)
ls 'my file.txt'
```

Interestingly, on Ubuntu, if I preface the `m` with a `"` then xonsh changes it into:
`ls 'my file.txt'`

I just installed xonsh today, after hearing you on the podcast, so the environments should be "pretty" clean. I didn't have any weirdo stuff going on (though trying to set the PROMPT ala the tutorial doesn't work on OSX).

My thought is that "correct" is to make valid commands/filenames, etc. And to conform to how bash/etc work(ed). I like the way it's working on OSX Any idea why these two platforms are different, and how I might be able to address it?

Both shells are being launched directly when logging in (not from an existing bash/sh/tsh/whatever).

**Comment by gforsyth** [comment]
Hey @mfeif -- what are the contents of `$BASH_COMPLETIONS` on your Ubuntu box?  

And how did you install xonsh?

**Comment by mfeif** [comment]
In both cases, I installed via pip from a zip file pulled from a github tag (xonsh-0.2.3.zip). In the case of the server, I installed with sudo.

`$BASH_COMPLETIONS` are: ['/etc/bash_completion', '/usr/share/bash-completion/completions/git']

**Comment by gforsyth** [comment]
Ok -- I think I fixed the missing quotes issue in #561 -- would you mind installing from the current xonsh master and seeing if that resolves your issue? 

I think with pip you can just

```
pip install git+git://github.com/scopatz/xonsh.git
```

**Comment by adqm** [comment]
fwiw, I'm also working on something that will make completion of names with spaces a bit more robust (as it is written now, even with your fix, it's a bit on the flaky side)

:)

**Comment by gforsyth** [comment]
Hey @scopatz -- no rush on this, but do you want to keep this feature request open?  I think with quoted paths working cross-platform that we're probably ok not offering to turn them off.  What say ye?

**Comment by scopatz** [comment]
Yeah, I am happy to close this since our quote and tab completion handling has vastly improved over tge past year thanks to @adqm!
