### ISSUE TITLE
stdin hides parts of stdout stream

### ISSUE THREAD

**Issue by cryzed** [xonsh/xonsh#1814]
Something about the stdin/stdout handling must have been changed recently. When I run my package manager on my system now (pacaur, Arch Linux), I almost reliably run into [display issues](http://i.imgur.com/FcEemDk.png). The update prompt isn't displaying in this instance -- however when I enter `Y` and press enter the process continues (however the update prompt itself is never displayed).

Sometimes when I check for updates and many lines are printed at a rapid pace followed by an expected stdin input, huge chunks of the stdout output directly before it seem to be missing. This is hard to debug or provide more information on because it doesn't actually raise any kind of exception or error. My xonsh version is `xonsh/0.4.7.dev175`.

EDIT: Ah yes, this stops happening completely when I start a bash-shell from xonsh and do it there instead.

**Comment by laerus** [comment]
Hey @cryzed! If you are on current master there was a major refactor on how the subprocesses are being run in xonsh and it's still a little unstable, you may want to bump `$XONSH_PROC_FREQUENCY` to something like `2e-4` or `5e-4` and see if that helps. We are actively working on this and any feedback is appreciated. Note that you can always roll back to version 0.4.7 before the refactor.

**Comment by cryzed** [comment]
Hey @laerus thanks for the quick reply, that explains it! Setting these and restarting xonsh doesn't seem to have any positive effect on the issue, I'll downgrade to the official 0.4.7 version for now. If you need me to test any branches or commits related to this issue, let me know and I'll try to do so ASAP and comment back here.

**Comment by astronouth7303** [comment]
This sounds a lot like the issues we were having with the refactor, but in the middle of the process.

The standard test I was using was:

```python
errors = 0
for i in range(10000):
    if len(''.join(!(echo @("*"*500)))) != 501: 
        errors += 1
        print(errors)
```

If that produces any output on `master`, you need to adjust your settings as @laerus said above.

Otherwise, I think we might need to dig into this more and see if we get a minimum failing case.

**Comment by cryzed** [comment]
That doesn't produce any output, however the issue isn't fixed either by setting it:

```shell
cryzed@arch ~ $ $XONSH_PROC_FREQUENCY
0.0002
cryzed@arch ~ $ errors = 0
............... for i in range(10000):
...............     if len(''.join(!(echo @("*"*500)))) != 501: 
...............         errors += 1
...............         print(errors)
...............         
cryzed@arch ~ $
```

Running `pacaur/pacman -Syu` breaks it very often when it uses the animated progressbars for example.

**Comment by astronouth7303** [comment]
Ok, so this is a different issue than what we were seeing before.

**Comment by gforsyth** [comment]
Hey @cryzed -- would you mind trying out the `pacman_cache` branch and see if fixes the pacman/pacaur streaming issue?  Thanks!

**Comment by cryzed** [comment]
At first glance it seems to fix the issue I had! Sometimes the console output still seems a bit wonky though, for example when aborting a process using Ctrl+C my cursor suddenly ends up somewhere in the line above etc. I'll keep an eye on it and see if I can come up with a more accurate description.

**Comment by cryzed** [comment]
Something that still breaks completely (stdout output and crashing) is running `nethogs`. After starting it many of the elements aren't displayed correctly and rapidly resizing it leads to crashes. This is the best traceback I could recover from the crash:

```
Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>                 
Traceback (most recent call last):                                                                                           
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown                                                            
    t.join()                                                                                                                 
  File "/usr/lib/python3.5/threading.py", line 1054, in join                                                                 
    self._wait_for_tstate_lock()                                                                                             
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock                                                
    elif lock.acquire(block, timeout):                                                                                       
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9596, in _signal_int                                    
    self.send_signal(signum)                                                                                                 
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9721, in send_signal
    rtn = self.proc.send_signal(signal)
  File "/usr/lib/python3.5/subprocess.py", line 1777, in send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted

Warning: Program '/usr/bin/xonsh' crashed.
```

**Comment by gforsyth** [comment]
Ok.  `nethogs` is also a curses-based interface, so it should get an entry in `xonsh/command_cache.py`

**Comment by cryzed** [comment]
I'm not sure what this module is used for, but it almost sounds like a whitelist for programs to make them work properly?

**Comment by scopatz** [comment]
That is effectively what it is for the time being from a users perspective. Really what it does it declares that a subproc (under certain argument conditions) does or does not produce capturable ouput.  For most alternate mode programs, it just gives a performance benefit. For certain programs that don't go into alternate mode but are interactive, like shells, it is more necessary to get things to work.

We are still working on a way to generalize this.

**Comment by anki-code** [comment]
Hi @cryzed! Does this still actual?

**Comment by cryzed** [comment]
No seems fine now, I'll close this -- thanks for the heads-up.
