### ISSUE TITLE
Add type

### ISSUE THREAD

**Issue by Siecje** [xonsh/xonsh#1817]
As of version `0.4.7` there is no `type`.

``` shell
$ type echo
echo is a shell builtin
```

**Comment by astronouth7303** [comment]
Use `which`.

In general, we never claim to be bash-compatible or posix-compatible. And because `type` is a pretty major thing in Python, in general we don't like to overload it as an alias.

(`exec` is an exception because of the shear amount of expectation about its existence.)

**Comment by melund** [comment]
Yes. And `exec` is only overloaded in subproc mode not in Python mode

**Comment by scopatz** [comment]
Also, I personally find the semantics of type in sh-lang rather confusing.

**Comment by Siecje** [comment]
```which``` doesn't tell you if it is a builtin or a function.

**Comment by gforsyth** [comment]
You can use the `-v, --verbose` flags to show that info.  The `-a` flag will also show give additional info about all matches in PATH

**Comment by Siecje** [comment]
Both ```-v``` and ```-a``` just seem to show the path location.

```shell
~ $ which echo --verbose
/bin/echo (from PATH element 8)
~ $ which echo -a
/bin/echo (from PATH element 8)
```

**Comment by astronouth7303** [comment]
Try it on an alias, or something that appears on the path more than once.

**Comment by gforsyth** [comment]
```console
gil@theo ~ 🐚  which -v which
Type:         function
String form:  <function which_main at 0x7f989b38df28>
File:         /home/gil/anaconda/lib/python3.5/site-packages/xonsh/xoreutils/which.py
Definition:   (args=None, stdin=None)
Source:
def which_main(args=None, stdin=None):
    """This is the which command entry point."""
    which(args, stdin=stdin)


aliases['which'] = <function which_main at 0x7f989b38df28>
gil@theo ~ 🐚  which -a ls
aliases['ls'] = ['ls', '--color=auto', '-v']
/usr/bin/ls (from PATH element 1)
```

**Comment by gforsyth** [comment]
Although it's true that we don't pass through information like `echo` being a shell builtin

**Comment by gforsyth** [comment]
Closing this out as answered.
