### ISSUE TITLE
xonsh hangs when I write "aaaaaaaaaa ." and then press the Up arrow

### ISSUE THREAD

**Issue by daym** [xonsh/xonsh#1818]
Hi,

xonsh 0.4.6 (also xonsh from git from a few minutes ago) hangs when I write "aaaaaaaaaa ." (without the quotes) and then press the Up arrow (on the interactive shell). Right before that the screen flashes.

First I thought it was a problem with the terminal emulator but it also happens on the Linux console. It's always 100% reproducible.

My .config/xonsh/config.json is:

``` python
{
 "env": {
  "AUTO_PUSHD": true,
  "CASE_SENSITIVE_COMPLETIONS": false,
  "COMPLETIONS_DISPLAY": "single",
  "DIRSTACK_SIZE": 50,
  "DYNAMIC_CWD_WIDTH": [
   40.0,
   "%"
  ],
  "HISTCONTROL": "ignoredups,ignoreerr",
  "MOUSE_SUPPORT": true,
  "PUSHD_SILENT": "True",
  "SHELL_TYPE": "readline",
  "UPDATE_OS_ENVIRON": true,
  "XONSH_HISTORY_SIZE": [
   15778800.0,   "s"
  ],
  "XONSH_STORE_STDIN": true,
  "XONSH_TRACEBACK_LOGFILE": "/home/dannym/backup/xonsh.traceback"
 },
 "xontribs": [
 ]
}
```

How can I debug this further?

I think it's a problem with readline.

**Comment by melund** [comment]
Thanks for reporting. First check if it also happens on 0.4.7 or on master. It could be fixed and then you don't need to waste time debugging.

**Comment by daym** [comment]
I also tested it on xonsh from git master from a few minutes ago and it does the same. (Note: I didn't install the git master version, I just did `from xonsh.main import main ; main()` in there)

**Comment by laerus** [comment]
i cannot reproduce this in v0.4.7. Can you try with prompt_toolkit and see if this happens? Also you can try setting `$XONSH_DEBUG=1` and `$XONSH_SHOW_TRACEBACK=True` and then Ctrl-C when xonsh hangs and see if this produces more info.

**Comment by daym** [comment]
I tried that now; Ctrl-C does nothing.

Sometimes (very rarely) it flashes the screen and then a new prompt appears and then it hangs - hang, however, it always does.

**Comment by gforsyth** [comment]
Hi @daym -- 4 seconds is too long for startup, agreed.  Could you try renaming your `config.json` to something else and then starting xonsh without it?  It would be good to know if any of the options you have set there have any impact on startup times.  

Also, could you please post the output of `xonfig`?

And a final request -- since `sys.path` is sometimes a little wonky, could you try

```console
from xonsh import main
print(main.__file__)
```

in the git repo and ensure that it's actually pointing to the git master and not the installed version?

**Comment by daym** [comment]
`shell
dannym@dayas /x/home/danny/src/xonsh/xonsh master $ python3
Python 3.4.3 (default, Jan  1 1970, 00:00:01) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xonsh import main
print(>>> print(main.__file__)
/x/home/dannym/src/xonsh/xonsh/xonsh/main.py
`

**Comment by gforsyth** [comment]
Hi @daym -- sorry for losing this thread.  
Thanks for posting that output.  
I'm glad to hear that the prompt_toolkit backend works, at least.  

Could you try this please?

1. Open xonsh
2. set `$XONSH_DEBUG=1` and `$XONSH_SHOW_TRACEBACK=True`
3. run `xonsh` from within the current `xonsh` window
4. Try your breaking example
5. Ctrl-C if needed and see if there's any traceback printed to the parent `xonsh` process.

**Comment by gforsyth** [comment]
I can't reproduce this issue.  If this is still a problem please ping.
