### ISSUE TITLE
Pygments highlighting doesn't use terminal colour scheme

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1821]
What's the correct way to change syntax highlighting colour scheme?

![term colours](https://cloud.githubusercontent.com/assets/3946014/19222818/fc7e868e-8e58-11e6-9f76-5e35eec02aa3.png)

Ignoring that some of my colours are broken in the screenshot above, it's clear that the environment variable is a completely different colour to any of them, and barely legible (this is after I changed my background colour specifically so that I could read it at all).

IMO it would be best if pygments was set to use the terminal emulator's scheme by xonsh, at least as a default.

**Comment by laerus** [comment]
You can change the colors in general by setting `$XONSH_COLOR_STYLE`, you can see the available styles by running `xonfig styles`. Atm i don't think you can change only the highlighting colors.

**Comment by OJFord** [comment]
@laerus So it can only be changed among presets? And none of those presets is "use the terminal emulator's settings"?

I find it odd that anyone would want xonsh to be outputting a different colour scheme to that of any tool like `ls`, for example.

Even if you don't agree this should be the default, is there at least a way I can _manually_ set them to be the same as everything else (i.e. add a new entry to that list)?

**Comment by melund** [comment]
@OJFord I think this will work once pygments 2.2 is released. 

Can you try to run with pygments master?

You can see that it should use the ansicolors (terminal colors) but only if it detects that pygments support it. 
https://github.com/xonsh/xonsh/blob/master/xonsh/pyghooks.py#L646

**Comment by OJFord** [comment]
@melund With pygments 2.2.dev20161011, it's fixed in the prompt (presumably anything using the `{COLOR}` formatters), but not the syntax highlighting:

![screen shot 2016-10-11 at 03 29 44](https://cloud.githubusercontent.com/assets/3946014/19256911/27ab5cc8-8f63-11e6-86f1-30bf1e46bfb0.png)
notice that `$FOO` is the same colour as it and the prompt were before starting a new `xonsh`.

**Comment by scopatz** [comment]
Also note that that you have to use the "default" style to get the terminal colors.  

I agree that the color selection and customization interface could benefit from user-facing improvements. Pull requests very welcome!

**Comment by OJFord** [comment]
This is with default set @scopatz:
![screen shot 2016-10-11 at 05 07 10](https://cloud.githubusercontent.com/assets/3946014/19258564/9ccf6816-8f70-11e6-8f42-eaf4ea205f08.png)

**Comment by scopatz** [comment]
@melund, could this be because of the windows color intensifying?  @OJFord, could you try changing the value of [`$INTENSIFY_COLORS_ON_WIN`](http://xon.sh/envvars.html#intensify-colors-on-win) to see if this affects things?

**Comment by melund** [comment]
Well. That could swap some colors around. But is this windows?

**Comment by OJFord** [comment]
Thanks for the reply both, but no, this is on Mac.

**Comment by melund** [comment]
I think the styles for syntax highlighting comes from pygments and they are not implemented with the ANSI color keywords https://bitbucket.org/birkenfeld/pygments-main/src/a042025b350cd9c9461f7385d9ba0f13cdb01bb9/pygments/styles/default.py?at=default&fileviewer=file-view-default

We could implement our own default style that use ANSI color names. Just like we fall back to XONSH _BASE_STYLE if pygments is not available. Then only use pygments styles if the user selects something other than default. The logic goes here:

https://github.com/xonsh/xonsh/blob/master/xonsh/pyghooks.py#L429

A PR is very welcome

**Comment by OJFord** [comment]
Thanks @melund, I'll have a go at it over the weekend.

**Comment by melund** [comment]
@OJFord ... I took at stab at it. It seems that PTK has some issues with the ansicolor names on windows. So we may need to wait until that is fixed.

**Comment by OJFord** [comment]
> some issues with the ansicolor names on windows. So we may need to wait

Any chance non-Windows folks could benefit in the mean time?

Or are you saying it would actually be worse on Windows with this change but without PTK being fixed?

**Comment by melund** [comment]
No worries. Happens to me all the time. 

I am not saying we have to wait until the next PTK release. This only has effects if people have pygments master anyway.

 But I would like to see the effect on the fix to PTK before merging it in xonsh. I don't think it will be long @jonathanslanders is usual quite fast.

**Comment by OJFord** [comment]
Thanks for working on this @melund - looking great with #1894 now!

![screen shot 2016-11-01 at 16 17 00](https://cloud.githubusercontent.com/assets/3946014/19897111/ba8b507e-a04e-11e6-80a3-022b96e2259f.png)


Will the next release bump the pygments dependency as required?

**Comment by gforsyth** [comment]
Hey @OJFord -- we can't bump the dependency until pygments actually does a release.  We can certainly add instructions to the customization FAQ in the docs related to this

**Comment by OJFord** [comment]
> we can't bump the dependency until pygments actually does a release

Ah, gotcha. Sorry I wasn't sure if I actually needed master or if it was just the easiest way of getting at whatever unknown later version was required.

That's a shame, but presumably I can just `pip install` it as I did in the Docker container without unwanted effects?

**Comment by gforsyth** [comment]
yep, kind of a pain

**Comment by OJFord** [comment]
Actually, I still can't get this right.

![screen shot 2016-11-01 at 16 45 55](https://cloud.githubusercontent.com/assets/3946014/19898131/b32482c0-a052-11e6-87e5-066010a92b8c.png)

Is there something more I need to do to get it to use the ANSI colours I have set?

**Comment by melund** [comment]
Good question. Are there other places where we get styles from. I will have look tomorrow.

**Comment by melund** [comment]
@OJFord. Can you try to run the following and check that all the styles use `#ansi` color names: 

``` python
snail@sea ~\Documents\xonsh master $ dict(__xonsh_shell__.shell.styler.styles)
{Token: '',
 Token.Aborted: '#ansilightgray',
 Token.AutoSuggestion: '#ansidarkgray',
 Token.Color.BACKGROUND_BLACK: 'bg:#ansiblack',
 Token.Color.BACKGROUND_BLUE: 'bg:#ansidarkblue',
 Token.Color.BACKGROUND_CYAN: 'bg:#ansiteal',
 Token.Color.BACKGROUND_GREEN: 'bg:#ansidarkgreen',
 Token.Color.BACKGROUND_INTENSE_BLACK: 'bg:#ansidarkgray',
 Token.Color.BACKGROUND_INTENSE_BLUE: 'bg:#ansiblue',
 Token.Color.BACKGROUND_INTENSE_CYAN: 'bg:#ansiturquoise',
 Token.Color.BACKGROUND_INTENSE_GREEN: 'bg:#ansigreen',
 Token.Color.BACKGROUND_INTENSE_PURPLE: 'bg:#ansifuchsia',
 Token.Color.BACKGROUND_INTENSE_RED: 'bg:#ansired',
 Token.Color.BACKGROUND_INTENSE_WHITE: 'bg:#ansilightgray',
 Token.Color.BACKGROUND_INTENSE_YELLOW: 'bg:#ansiyellow',
 Token.Color.BACKGROUND_PURPLE: 'bg:#ansipurple',
 Token.Color.BACKGROUND_RED: 'bg:#ansidarkred',
 Token.Color.BACKGROUND_WHITE: 'bg:#ansiwhite',
 Token.Color.BACKGROUND_YELLOW: 'bg:#ansibrown',
 Token.Color.BLACK: '#ansiblack',
 Token.Color.BLUE: '#ansidarkblue',
 Token.Color.BOLD_BLACK: 'bold #ansiblack',
 Token.Color.BOLD_BLUE: 'bold #ansidarkblue',
 Token.Color.BOLD_CYAN: 'bold #ansiteal',
 Token.Color.BOLD_GREEN: 'bold #ansidarkgreen',
 Token.Color.BOLD_INTENSE_BLACK: 'bold #ansidarkgray',
 Token.Color.BOLD_INTENSE_BLUE: 'bold #ansiblue',
 Token.Color.BOLD_INTENSE_CYAN: 'bold #ansiturquoise',
 Token.Color.BOLD_INTENSE_GREEN: 'bold #ansigreen',
 Token.Color.BOLD_INTENSE_PURPLE: 'bold #ansifuchsia',
 Token.Color.BOLD_INTENSE_RED: 'bold #ansired',
 Token.Color.BOLD_INTENSE_WHITE: 'bold #ansilightgray',
 Token.Color.BOLD_INTENSE_YELLOW: 'bold #ansiyellow',
 Token.Color.BOLD_PURPLE: 'bold #ansipurple',
 Token.Color.BOLD_RED: 'bold #ansidarkred',
 Token.Color.BOLD_UNDERLINE_BLACK: 'bold underline #ansiblack',
 Token.Color.BOLD_UNDERLINE_BLUE: 'bold underline #ansidarkblue',
 Token.Color.BOLD_UNDERLINE_CYAN: 'bold underline #ansiteal',
 Token.Color.BOLD_UNDERLINE_GREEN: 'bold underline #ansidarkgreen',
 Token.Color.BOLD_UNDERLINE_INTENSE_BLACK: 'bold underline #ansidarkgray',
 Token.Color.BOLD_UNDERLINE_INTENSE_BLUE: 'bold underline #ansiblue',
 Token.Color.BOLD_UNDERLINE_INTENSE_CYAN: 'bold underline #ansiturquoise',
 Token.Color.BOLD_UNDERLINE_INTENSE_GREEN: 'bold underline #ansigreen',
 Token.Color.BOLD_UNDERLINE_INTENSE_PURPLE: 'bold underline #ansifuchsia',
 Token.Color.BOLD_UNDERLINE_INTENSE_RED: 'bold underline #ansired',
 Token.Color.BOLD_UNDERLINE_INTENSE_WHITE: 'bold underline #ansilightgray',
 Token.Color.BOLD_UNDERLINE_INTENSE_YELLOW: 'bold underline #ansiyellow',
 Token.Color.BOLD_UNDERLINE_PURPLE: 'bold underline #ansipurple',
 Token.Color.BOLD_UNDERLINE_RED: 'bold underline #ansidarkred',
 Token.Color.BOLD_UNDERLINE_WHITE: 'bold underline #ansiwhite',
 Token.Color.BOLD_UNDERLINE_YELLOW: 'bold underline #ansibrown',
 Token.Color.BOLD_WHITE: 'bold #ansiwhite',
 Token.Color.BOLD_YELLOW: 'bold #ansibrown',
 Token.Color.CYAN: '#ansiteal',
 Token.Color.GREEN: '#ansidarkgreen',
 Token.Color.INTENSE_BLACK: '#ansidarkgray',
 Token.Color.INTENSE_BLUE: '#ansiblue',
 Token.Color.INTENSE_CYAN: '#ansiturquoise',
 Token.Color.INTENSE_GREEN: '#ansigreen',
 Token.Color.INTENSE_PURPLE: '#ansifuchsia',
 Token.Color.INTENSE_RED: '#ansired',
 Token.Color.INTENSE_WHITE: '#ansilightgray',
 Token.Color.INTENSE_YELLOW: '#ansiyellow',
 Token.Color.NO_COLOR: 'noinherit',
 Token.Color.PURPLE: '#ansipurple',
 Token.Color.RED: '#ansidarkred',
 Token.Color.UNDERLINE_BLACK: 'underline #ansiblack',
 Token.Color.UNDERLINE_BLUE: 'underline #ansidarkblue',
 Token.Color.UNDERLINE_CYAN: 'underline #ansiteal',
 Token.Color.UNDERLINE_GREEN: 'underline #ansidarkgreen',
 Token.Color.UNDERLINE_INTENSE_BLACK: 'underline #ansidarkgray',
 Token.Color.UNDERLINE_INTENSE_BLUE: 'underline #ansiblue',
 Token.Color.UNDERLINE_INTENSE_CYAN: 'underline #ansiturquoise',
 Token.Color.UNDERLINE_INTENSE_GREEN: 'underline #ansigreen',
 Token.Color.UNDERLINE_INTENSE_PURPLE: 'underline #ansifuchsia',
 Token.Color.UNDERLINE_INTENSE_RED: 'underline #ansired',
 Token.Color.UNDERLINE_INTENSE_WHITE: 'underline #ansilightgray',
 Token.Color.UNDERLINE_INTENSE_YELLOW: 'underline #ansiyellow',
 Token.Color.UNDERLINE_PURPLE: 'underline #ansipurple',
 Token.Color.UNDERLINE_RED: 'underline #ansidarkred',
 Token.Color.UNDERLINE_WHITE: 'underline #ansiwhite',
 Token.Color.UNDERLINE_YELLOW: 'underline #ansibrown',
 Token.Color.WHITE: '#ansiwhite',
 Token.Color.YELLOW: '#ansibrown',
 Token.Comment: 'underline #ansiteal',
 Token.Comment.Hashbang: '',
 Token.Comment.Multiline: '',
 Token.Comment.Preproc: 'underline #ansibrown',
 Token.Comment.PreprocFile: '',
 Token.Comment.Single: '',
 Token.Comment.Special: '',
 Token.Error: '#ansired',
 Token.Escape: '',
 Token.Generic: '',
 Token.Generic.Deleted: '#ansidarkred',
 Token.Generic.Emph: 'underline',
 Token.Generic.Error: 'bold #ansired',
 Token.Generic.Heading: 'bold #ansidarkblue',
 Token.Generic.Inserted: '#ansigreen',
 Token.Generic.Output: '#ansidarkblue',
 Token.Generic.Prompt: 'bold #ansidarkblue',
 Token.Generic.Strong: '',
 Token.Generic.Subheading: 'bold #ansipurple',
 Token.Generic.Traceback: '#ansidarkblue',
 Token.Keyword: 'bold #ansidarkgreen',
 Token.Keyword.Constant: '',
 Token.Keyword.Declaration: '',
 Token.Keyword.Namespace: '',
 Token.Keyword.Pseudo: 'nobold',
 Token.Keyword.Reserved: '',
 Token.Keyword.Type: 'nobold #ansidarkred',
 Token.Literal: '',
 Token.Literal.Date: '',
 Token.Literal.Number: '#ansidarkgray',
 Token.Literal.Number.Bin: '',
 Token.Literal.Number.Float: '',
 Token.Literal.Number.Hex: '',
 Token.Literal.Number.Integer: '',
 Token.Literal.Number.Integer.Long: '',
 Token.Literal.Number.Oct: '',
 Token.Literal.String: '#ansired',
 Token.Literal.String.Affix: '',
 Token.Literal.String.Backtick: '',
 Token.Literal.String.Char: '',
 Token.Literal.String.Delimiter: '',
 Token.Literal.String.Doc: 'underline',
 Token.Literal.String.Double: '',
 Token.Literal.String.Escape: 'bold #ansibrown',
 Token.Literal.String.Heredoc: '',
 Token.Literal.String.Interpol: 'bold #ansipurple',
 Token.Literal.String.Other: '#ansidarkgreen',
 Token.Literal.String.Regex: '#ansipurple',
 Token.Literal.String.Single: '',
 Token.Literal.String.Symbol: '#ansibrown',
 Token.Menu.Completions.Completion: 'bg:#ansiteal #ansiwhite',
 Token.Menu.Completions.Completion.Current: 'bg:#ansiturquoise  #ansiblack',
 Token.Menu.Completions.ProgressBar: 'bg:#ansiturquoise',
 Token.Menu.Completions.ProgressButton: 'bg:#ansidarkgray',
 Token.Name: '',
 Token.Name.Attribute: '#ansiyellow',
 Token.Name.Builtin: '#ansidarkgreen',
 Token.Name.Builtin.Pseudo: '',
 Token.Name.Class: 'bold #ansiblue',
 Token.Name.Constant: '#ansidarkred',
 Token.Name.Decorator: '#ansifuchsia',
 Token.Name.Entity: 'bold #ansilightgray',
 Token.Name.Exception: 'bold #ansired',
 Token.Name.Function: '#ansiblue',
 Token.Name.Function.Magic: '',
 Token.Name.Label: '#ansiyellow',
 Token.Name.Namespace: 'bold #ansiblue',
 Token.Name.Other: '',
 Token.Name.Property: '',
 Token.Name.Tag: 'bold #ansidarkgreen',
 Token.Name.Variable: '#ansidarkblue',
 Token.Name.Variable.Class: '',
 Token.Name.Variable.Global: '',
 Token.Name.Variable.Instance: '',
 Token.Name.Variable.Magic: '',
 Token.Operator: '#ansidarkgray',
 Token.Operator.Word: 'bold #ansipurple',
 Token.Other: '',
 Token.Punctuation: '',
 Token.Text: '',
 Token.Text.Whitespace: '#ansilightgray'}
```

**Comment by OJFord** [comment]
At first it wasn't, but I just tried from 'scratch', and it's working great. Not sure exactly what the issue is but I'm sure it'll be smooth once all relevant packages have new versions :)

Thanks again for the fix!

![screen shot 2016-11-02 at 00 51 02](https://cloud.githubusercontent.com/assets/3946014/19912988/791a253c-a096-11e6-94df-499618d2fb6a.png)

**Comment by OJFord** [comment]
Damn, I reinstalled xonsh (I was initially after `brew install --HEAD`, but it didn't work easily so I gave up on it, but only after removing my old version) and lost this fix.

I'm not going to fiddle about with it again now to fix just for myself, but I think it makes sense to reopen this as a reminder that it doesn't work out-of the box yet.

To recap, we're expecting it to work when:

- [x] jonathanslenders/python-prompt-toolkit#408 merged
- [ ] pygments 2.2 released
- [ ] xonsh version released with pygments >=2.2.0

**Comment by scopatz** [comment]
Yeah, I really wish that they would release another version of pygments.

**Comment by scopatz** [comment]
Alright, I think that this is finally closable.
