### ISSUE TITLE
Delay when autocompleting file/directory

### ISSUE THREAD

**Issue by rnovacek** [xonsh/xonsh#1824]
When I'm using autocompletion for files and directories, there is a delay between pressing the <TAB> button and the completion appearing. The delay is ~1 second. 

Example:
$ touch somefile
$ ls somefil<TAB>
Nothing happens for like one second, then completion appears. I would prefer the completion to appear immediately. Other completions (command name, environment variable) appear immediately when I press the <TAB> button.

Any ideas how to debug the delay?

xonfig:
```
+------------------+-----------------+
| xonsh            | 0.4.7           |
| Git SHA          | None            |
| Python           | 3.5.1           |
| PLY              | 3.7             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | fedora          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by rnovacek** [comment]
I just found out that it only affects some commands:

```
$ mkdir somedir; touch somefile
$ ls somefi<TAB>  # delay appears, completion appears after ~1s
$ cd som<TAB>  # competion to 'somedir/' appears immediately
```

**Comment by gforsyth** [comment]
Hi @rnovacek , thanks for reporting!  
We definitely don't want a 1 second delay for anything, really.  
Are there a *lot* of files in the directory where you see the delay?  What happens if you try `ls somefi<TAB>` in directory that only has one or two folders/files?

**Comment by gforsyth** [comment]
Sorry, my brain is fried -- I see that that's what you did and there is a delay.  Ok, I'll try to dig around and see if I can see what's up.

**Comment by scopatz** [comment]
My guess is that this delay is coming from Bash completions being slow for some reason.  Do you happen to know if you are using V1 or V2 Bash completions?  Also, can you try turning off Bash completions entirely and see if that improves performance.  See http://xon.sh/tutorial_completers.html#removing-a-completer

**Comment by rnovacek** [comment]
Thanks for the tip. Disabling bash completion with `completer remove bash` helps. Now there is no delay when I press the TAB button.

I don't know what version of bash completions do I use, but the package version suggests that it might be version 2: bash-completion-2.4-1.fc24.noarch (Fedora 24).

**Comment by scopatz** [comment]
Ok, well, at least we have identified the problem.  This is usually super fast for most people.  Maybe your bash has a large set of things it does on startup for some reason (in the profile)? What are your normal bash startup times like?

**Comment by rnovacek** [comment]
Seems pretty quick:

```
$ timeit bash -c true
100 loops, best of 3: 3.54 ms per loop
```

Actually, it's something between xonsh 0.4.5 and 0.4.6. It was working fast in 0.4.5, but in both 0.4.6 and 0.4.7 it much slower.

**Comment by melund** [comment]
You could maybe try Git bisect and pin point which PR caused the change.

**Comment by rnovacek** [comment]
@melund good idea.

git bisect says that after this commit, the delays start to appear: f344231e21934530f056c3629af815727efe4fd7

**Comment by rnovacek** [comment]
This pull request: #1602

**Comment by melund** [comment]
Interesting. I recall people generally experienced that the PR made everything go faster. Maybe @blahgeek has some ideas.

**Comment by blahgeek** [comment]
hi @rnovacek sorry for the issue! 

May I have a look at the bash completion script you are currenly using? (Check $BASH_COMPLTIONS variable to find the file, and maybe post it in gist) Thanks!

**Comment by rnovacek** [comment]
My $BASH_COMPLETIONS contains this: `/etc/bash_completion.d:/usr/share/bash-completion:/usr/share/bash-completion/completions`.

This is the `/usr/share/bash-completion/bash_completion` file: https://paste.fedoraproject.org/453339/47665095/

I also printed the executed script in the bash competer (by writing the `script` content to file at https://github.com/xonsh/xonsh/blob/0.4.7/xonsh/completers/bash.py#L73), it has this content https://paste.fedoraproject.org/453321/50612147/ and takes around 0.75 second to execute by bash.

**Comment by blahgeek** [comment]
Thanks!

Please try setting $BASH_COMPLETIONS to `(/usr/share/bash-completion/bash_completion, )` and see if there's any improvement. All the completion files should be lazy-loaded.

I think there's a bug while setting $BASH_COMPLETIONS 's default value, I would take a look at that later. But this temporary fix should work for you now.

**Comment by rnovacek** [comment]
@blahgeek Thank you very much, setting `$BASH_COMPLETIONS = '/usr/share/bash-completion/bash_completion'` fixes the issue for me.

**Comment by gforsyth** [comment]
Closing via doc updates and better defaults in #1888

**Comment by rnovacek** [comment]
I can confirm that there is no delay in tab completion when using current master.

Thank you very much for fixing this bug so quickly!

**Comment by gforsyth** [comment]
Thanks for reporting @rnovacek -- and thanks a ton @blahgeek for handling the fix!
