### ISSUE TITLE
Pretty printouts of history

### ISSUE THREAD

**Issue by CJ-Wright** [xonsh/xonsh#1825]
Would it be possible to print out histories in a pretty way, including inputs and any outputs (potentially to a PDF)? I am asking so I can use this to write examples/problem sets to be handed out.

**Comment by astronouth7303** [comment]
Perfectly possible--see [`xonsh.history.History`](http://xon.sh/api/history.html#xonsh.history.History). I don't think anyone has, though.

**Comment by mitnk** [comment]
To a PDF or HTML? no ... sounds like a `won't fix/do` (out of xonsh scope) to me :) sorry.

**Comment by scopatz** [comment]
Well, there is no reason this couldn't be optional / in a xontrib.

**Comment by mitnk** [comment]
I forgot the existing of xontrib ...

**Comment by gforsyth** [comment]
Hey @CJ-Wright, I needed (wanted?) something like this for an easier time writing tutorials -- it's early days (you know, like the last hour or so), but you can take a look at https://github.com/gforsyth/history_xonverter

Just a simple script that you hand a xonsh history file to and it outputs a markdown file with the input and outputs broken out.  You could pretty easily convert the md file to pdf or whatever else.

**Comment by CJ-Wright** [comment]
@gforsyth Awesome thank you! I'll try to test this out soon.

**Comment by scopatz** [comment]
Ok, just thought of something I really want: the ability to publish a session to a gist et al. That would be unimaginably useful.

**Comment by anki-code** [comment]
My small xontrib around this topic: [xontrib-hist-format](https://github.com/anki-code/xontrib-hist-format)

I'm going to close this issue it can be solved by creating xontribs.
