### ISSUE TITLE
`which` return code is always 0

### ISSUE THREAD

**Issue by derekbrokeit** [xonsh/xonsh#1826]
In xonsh, I am currently receiving `0` return code even when the command cannot be found. This makes it impossible to use !(which program-that-doesnt-exist) as a boolean or other similar effects. Ideally, `which` should exit with status `1` when no item is found.

Example use case
```
$PAGER = "vimpager" if !(which vimpager) else "less"
```

**Comment by melund** [comment]
This used to work. Probably broke in one of the refactors. I will try to take a look. @derekbrokeit  Thanks for spotting it.

**Comment by melund** [comment]
There seems to be a bug with the return values of callable aliases. The which function does return non-zero if it doesn't find anything. But xonsh seems to ignore this. 

I checked, and this was also a problem before the recent refracture of the subproc system. But after the refracture I can't enter pdb breakpoints in the code. So it is a little difficult to quickly debug. @scopatz How do you get `pdb` working?

**Comment by melund** [comment]
Ahh. A bug was introduced in the 'which' refactor 14 days ago. I fix is incoming

**Comment by melund** [comment]
Still no idea why I can't enter the `pdb` break point on master. Anyone.?

**Comment by melund** [comment]
@derekbrokeit  So there is a fix here #1829. But it probably won't help you much as `!(which)` fails due to some other bug with streaming aliases #1828 . Probably needs to be fixed first.

**Comment by melund** [comment]
So. This problem was also fixed in #1803 which I just merged. But the problem with `!(fun_alias)` #1828 is still there...

**Comment by scopatz** [comment]
> So it is a little difficult to quickly debug. @scopatz How do you get pdb working?

Sorry @melund! I was out for the holiday!  I am back now.  I am not sure why pdb isn't working... That is concerning.  I'll take a look at this and the other problems in their own issues, which seems to have been opened up/
