### ISSUE TITLE
Clearscreen (cls and clear) broken on master (windows)

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1830]
Clear screen `cls` or `clear` (from MSYS) are both broken on master. I believe it comes after the sub-proc refactor. 

![image](https://cloud.githubusercontent.com/assets/1038978/19263848/a646b5e2-8f9e-11e6-914a-fa398c5e9c8a.png)

Instead of clearing the screen it just prints an unrecognizable character.

**Comment by laerus** [comment]
i cannot reproduce this in linux, probably some windows specific code is causing this?

**Comment by gforsyth** [comment]
Hey @melund, is there any difference if you try a different terminal emulator?

**Comment by astronouth7303** [comment]
Is this even something xonsh can control?

**Comment by melund** [comment]
Apparently, since it works on 0.4.7. I have to read up on how `cls` works for Windows conhost.

**Comment by melund** [comment]
I am thinking that maybe subprocess are executed in their own process so that the does affect state of xonsh. Maybe that is also why I can't add pdb brakepoints in callable aliases. @scopatz could that be the reason for what I observe with the `cls` alias not working.

**Comment by scopatz** [comment]
Potential fix in #1845

**Comment by melund** [comment]
Fixed in master
