### ISSUE TITLE
Interested in refactoring $PROMPT format to work like a formatted string

### ISSUE THREAD

**Issue by derekbrokeit** [xonsh/xonsh#1831]
I am interested in working on  a refactor of how the prompt string is generated, but I wanted to ask if it was of interest or not before beginning to work on it.

In particular, I feel like most users of xonsh will be familiar with typical string `format` functionality, but that is not how the `$PROMPT` is actually generated. It appears to be pieced together in stages and therefore it is difficult to grasp at first how the `$FORMATTER_DICT` will actually behave until after playing with it for awhile. Instead, I propose that the `$FORMATTER_DICT` be renamed to renamed to `$PROMPT_FORMATTER` and be used to generate a dictionary that is passed to `$PROMPT.format(**generated_kwargs)` to make it as transparent as possible. 

An example of how I see the `$PROMPT` variable changing:

```
# current default
$PROMPT = '{env_name:{} }{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR}

# proposed change
$PROMPT = '{env_name:{{%e}} }{color:bold_green}{user}@{hostname}{color:bold_blue} {cwd}{branch_color}{curr_branch:{{%b}}}{color:no_color} {color:bold_blue}{prompt_end}{color:no_color}
```

The proposed items in `$PROMPT_FORMATTER` will include both callables and objects that implement the `__format__` method to produce customizable output. A prime example use case would be a color object that produces the appropriate color escape sequence when passed the color string to `__format__`. This would also give us the ability to highly customize the way that `$PROMPT_FORMATTER['gitstatus']` looks. If a callable fails or throws an exception, we could replace it with a `PromptError` object that simply prints that the exception occurred.

I wanted to propose this and see if there is interest before going to far. Also, are there ways to set `pdb` traces inside xonsh running framework. I was unable to get the trace to fire in my initial testing.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by astronouth7303** [comment]
[PEP 3101](https://www.python.org/dev/peps/pep-3101/) doesn't define any format specifiers for strings. Care to elaborate on what you hand in mind?

In addition, `{env_name:{{%e}} }` won't work the way you expect (brace doubling only escapes outside of fields).

I would like to suggest that because of the importance of color in the prompt (and for the sake of brevity), they should be promoted back to fields, not a special formatter.

**Comment by derekbrokeit** [comment]
As an example, the idea I had in mind for `env_name` is as such:

```
# in the event of a current environment named 'test'
>>> '{env_name:{{%e}} }'.format(**kwargs)
'{test} '

# in the event of no current environment
>>> '{env_name:{{%e}} }'.format(**kwargs)
' '
```

Promoting colors to fields would break python format syntax in the event of a hex color code `#000`, but it could be reduced for brevity to something like `{c:#000}` with a more verbose `{color:#000}` that references the same object.

**Comment by derekbrokeit** [comment]
Similarly you could do this:
```python
# in the event of a current environment named 'test'
>>> '{env_name:(%e) }'.format(**kwargs)
'(test) '

# in the event of no current environment
>>> '{env_name:{{%e}} }'.format(**kwargs)
' '
```

**Comment by derekbrokeit** [comment]
Silly me, I forgot the dictionary parentheses 😜 

```python
# in the event of a current environment named 'test'
>>> '{env_name:(%(e)) }'.format(**kwargs)
'(test) '

# in the event of no current environment
>>> '{env_name:{{%(e)}} }'.format(**kwargs)
' '  # empty string

**Comment by scopatz** [comment]
Hi @derekbrokeit! Happy to have you (or anyone) take a stab at refactoring this stuff.  It would be great to have more eyes and ideas on this.  

I do agree with @astronouth7303 that colors (and most things) should be first class.   Also, one of my personal guiding principles for xonsh is that it should be easy to learn, easy to teach, and easy to use.  Some of your examples seem a bit syntax heavy with respect to the state of affairs right now. It seems like it would be easy to mess up the nesting, especially for newcomers.  If you can simplify this down while retaining the desired functionality, that would be great!

**Comment by derekbrokeit** [comment]
I actually totally agree with you. One thing that I thought about but totally failed to mention is that most of these can also have a default string format that requires no special formatting. By that I mean that `{env_name}` could produce the most common or expected use case that works for most users. Then, we can have documentation that talks about **advanced prompt formatting**. 

I also thought about it a bit and we could build in a special case where hex colors do not need a keyword reference:

```python
# we could just build in an initial string replacement to fix that special formatting case
# so that it hides it from users and makes $PROMPT less verbose
'{#FFF}'.replace('{#', '{c:#'))
```

Here's a working example of how an `EnvName` object could be used in my hypothetical refactoring:

```python
>>> class EnvName:
...     environment = 'test'
...     
...     def __format__(self, format_spec):
...         if not format_spec:
...             return '({}) '.format(self.environment)
...         return format_spec.replace('%e', self.environment)
... 
>>> e = EnvName()
>>> '{env_name}'.format(env_name=e)
'(test) '
>>> '{env_name:[%e] }'.format(env_name=e)
'[test] '
```

In principle, there may be several existing xonsh variables in memory that could be perfect candidates for adding a `___format___` method to and not require significant additional memory usage.

**Comment by astronouth7303** [comment]
Do we support hex colors now? Is that a feature we want?

Also, the formatter will happily take `#000` as an identifier are attribute. ie, "{#000}" and "{spam.#000}" are both valid format strings (if the appropriate data is passed in).

**Comment by derekbrokeit** [comment]
Yes, hex colors are supported already. 

I guess I got ahead of myself. The main reason I would perform this correction and use a special object is that without a single color object, we would then need to format using a dictionary that has all possible iterations of colors. That would be very inefficient.

**Comment by astronouth7303** [comment]
Or a dynamic mapping. Or a custom formatter with a custom `get_value()`.

**Comment by laerus** [comment]
caching of values and updating only when needed would be nice too, there was a small discussion here #1564

**Comment by melund** [comment]
I am all for this as well. As long as simplicity is a guiding principle. 

Btw. I can't get pdb brake point working at the moment either. Is this something others are experiencing?

**Comment by astronouth7303** [comment]
I don't think the prompt formatter itself can do caching because it has no idea when to invalidate the cache. That is: It's pretty easy for a xontrib to compute a value on event and store it in either a module value or in `$FORMATTER_DICT`, or do lazy evaluation with a cache-clearing event.

But having the formatter control caching would complicate the formatter interface without significant net decrease in complexity (since each field would still need to control its cache invalidation and computation).

#1564 should be trivial with a custom `get_value()`.
