### ISSUE TITLE
doubled commas in tab-completed aliases

### ISSUE THREAD

**Issue by sejktmcsdlmfhsc** [xonsh/xonsh#1833]
As posted on xonsh gitter channel Oct 10 20:25:
After update from 0.4.6 to 0.4.7 tab completion of custom aliases with leading comma (did work nicely in 0.4.6) from .xonshrc result in doubled commas: 
```python
aliases[',xsconf'] = 'vim /dt/.xonshrc'
```
after typing ", x s tab" turns into ",,xsconf" instead of ",xsconf".

Thank you!
Best, Sej

xonsh 0.4.7 on debian, python 3.4.2, prompt_toolkit 1.07, PLY 3.8, pygments 2.1.3, encoding utf-8

**Comment by gforsyth** [comment]
Hey @sejktmcsdlmfhsc, thanks for reporting! 
Could you check out #1834 and see if that fixes the problem for you?  

Also when you want to report system info you can use `xonfig` to print out a nice configuration summary.

**Comment by sejktmcsdlmfhsc** [comment]
hej @gforsyth , thank you so much for the quick response!
I added your lines from #1834 to xonsh/completers/python.py and restarted terminals, then even machine. 
But unfortunately the doubled comma is still popping up when tabbing..
I have the module installed to my user - not sure if that matters?
~/.local/lib/python3.4/site-packages/xonsh

sys info: yes, thanks - I actually took it from xonfig - 
but just now figured the appropriate git mark down:
```python
+------------------+-----------------+
| xonsh            | 0.4.7           |
| Git SHA          | None            |
| Python           | 3.4.2           |
| PLY              | 3.8             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | debian          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by gforsyth** [comment]
Hi @sejktmcsdlmfhsc -- we have a couple of somewhat confusing things happening behind the scenes in `xonsh` to help startup times and I think those are preventing you from seeing the changes.  

If you have changed the appropriate lines in `xonsh/completers/python.py` within the `site-packages/xonsh` directory, then could you please set `$XONSH_DEBUG=1` within a xonsh session, then type `xonsh` to start a new session within the existing one and see if the doubled comma still persists?  

Thanks!  And let me know if you have any questions.

**Comment by sejktmcsdlmfhsc** [comment]
Nice - in the doubled xonsh it works like a charm! 
Would I need to put $XONSH_DEBUG=1 into my .xonshrc to make it persistent?

**Comment by sejktmcsdlmfhsc** [comment]
Hm putting it into .xonshrc did not help - it only seems to work for the second/inner xonsh..

**Comment by gforsyth** [comment]
Hey @sejktmcsdlmfhsc -- great!  

One of the ways that xonsh improves performance is by amalgamating all of its parts into one file so we avoid duplicate imports and a bunch of other stuff.  So the file that `xonsh` is running from (when it _isn't_ in debug mode) is actually `__amalgam__.py`.  That's why you didn't see the changes the first time.  

From here, you have three options:
1. Clone the repository and install from source after the pull request with the fixes is merged in.
2. Edit `__amalgam__.py` with my changes as you did in `xonsh/completers/python.py` (just search for the appropriate text)
3. Wait for the next release

**Comment by sejktmcsdlmfhsc** [comment]
I see. Thanks a lot for explanation and solutions!! 
I will try option 2 and if I fail on that, option 3..
