### ISSUE TITLE
Colored output broken (Windows10/readline)

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1842]
The new windows 10 conhost can interpret ansicolor codes. Nice when using the fast readline shell. 

The prompt coloring is still working on master, but the coloring the output seems to have been broken after the subproc refactor. Now it prints the ansi codes. 

This is how it looks on 0.4.7:
----
![image](https://cloud.githubusercontent.com/assets/1038978/19341824/69476f64-912f-11e6-9c7f-c944cf8bd36a.png)

And on master:
-----
![image](https://cloud.githubusercontent.com/assets/1038978/19341875/b88cc8c6-912f-11e6-8517-046f794e8ef8.png)

**Comment by melund** [comment]
I think this is related to #1830 somehow. I didn't think ConHost on windows relied on escape characters, but it seems the ANSI escape sequences are messed up in the output. Could `cls` and `clear` work in the same way? 

That would explain why the `cls` command also produce a weird character similar to the above. 
![image](https://cloud.githubusercontent.com/assets/1038978/19360490/227d0b84-917f-11e6-8a9a-10d7d660191d.png)

**Comment by scopatz** [comment]
Hi @melund, out of curiosity, what is the actual byte that you see for cls?

**Comment by scopatz** [comment]
Also, are you in `win_unicode_console` when using this?

**Comment by melund** [comment]
I only recently reinstalled it to test. The example above is without `win_unicode_console` installed.

**Comment by melund** [comment]
> @melund, out of curiosity, what is the actual byte that you see for cls?

I tried to dig into that. And it is 0x0C which is actually just the linefeed character. It also goes away with the fixes in #1845 

´Clear.exe´ from the msys unix tool gives me some odd more characters. 
1b 5b 48 1b 5b 4a  

But those are also not visible when the program is not backgrounded.

**Comment by scopatz** [comment]
As long as #1845 and #1851 fixed the clear issue, that is good.  I doubt we'd be able to redirect just a single LF anyway. I am still concerned about the colored output being broken here, though...

**Comment by melund** [comment]
I am going to close this in favor #1851.
