### ISSUE TITLE
Add `xontrib install`

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#1849]
Certain flavors of install (eg brew) keep xonsh in its own isolated venv. While this is probably a good thing, it makes installing xontribs difficult.

A `xontrib install` command should be added that will inspect `xontribs.json` for a xontrib of the given name and call `pip.main()` (NOT the `pip` command on the `$PATH`), or possibly the conda equivelent?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
> or possibly the conda equivelent?

`conda` won't work for this, it doesn't talk to PyPI, it should be `pip` for all xontribs unless we start creating conda-forge packages for them (which is massive overkill)

**Comment by gforsyth** [comment]
And I'm not sure if having `xonsh` in an isolated venv is a good thing (although that's not strictly speaking up to us).  We have a number of issues with users trying to use python packages they've installed and having errors.

**Comment by astronouth7303** [comment]
#2110 proposes a more generic solution to this problem.

**Comment by scopatz** [comment]
Should we close this in favor of #2110?

**Comment by astronouth7303** [comment]
Eh, also having `xontrib install` that looks at `xontribs.json` is a nice UX polish. Plus, it contributes to the goal of xonfig wizard automatically installing selected xontribs.

**Comment by gforsyth** [comment]
I didn't realize but `pip` has a `target` flag `-t`, so we can figure out where `xonsh` is installed and then have `pip` install the xontribs into the correct directory, even if we're sandboxed by brew, etc

**Comment by astronouth7303** [comment]
Assuming that there isn't a version incompatibility between the environments.

**Comment by gforsyth** [comment]
ugh, gross

**Comment by gforsyth** [comment]
if there is a version mismatch, then the env should have `pip` installed, right? So maybe we can search for the correct `pip` based on `xonsh`'s install location

**Comment by astronouth7303** [comment]
Right. Hence the outlined alias in #2110. Technically, you _can_ make a venv without pip, but that's also pretty easy to work around (`python -m ensurepip`).

**Comment by gforsyth** [comment]
Just a note on that: for reasons unknown, the default environment in an anaconda/miniconda install does not have `ensurepip`, however it is installed in any created environments

**Comment by astronouth7303** [comment]
But *conda does install pip, so not a problem.

**Comment by gforsyth** [comment]
I just mean that if you have xonsh installed in conda root and it runs `ensurepip` it will error out, so we should be ready to catch that exception
