### ISSUE TITLE
'r' as first letter in directory name is escaped when using $PWD on windows

### ISSUE THREAD

**Issue by derekbrokeit** [xonsh/xonsh#1850]
The following will fail:

``` shell
mkdir repo
cd repo
git clone https://github.com/xonsh/xonsh.git
cd xonsh
pip install $PWD
```

`$PWD` as a string is `'C:\\other\\dir\\repo'`, so I would have expected the `\\` to have been escaped rather than the `\r`. The problem is that the `$PWD` gets escaped (possibly twice) and the `\r` becomes a carriage return. The temporary fix is below:

``` shell
pip install @($PWD)
```

**Comment by astronouth7303** [comment]
Can confirm. The last backslash is getting double-interpolated sometimes.

For me, these paths are dropped:

* `C:\Users\James\code\aca-dev`
* `C:\Users\James\AppData\Local\Temp\repo`

These are not:
* `C:\Users\James\AppData\Local\Temp`
* `C:\Users\James\AppData\Local`
* `C:\Users\James`
* `C:\Users\James\code`

I tested this with `echo $PWD`, and comparing to just `$PWD`.

**Comment by astronouth7303** [comment]
Some stranger mis-transformations:

* `C:\Users\James\code\aca-dev\billing` -> `C:\Users\James\codeca-deilling`
* `C:\Users\James\code\aca-dev\users` -> `C:\Users\James\codeca-dev\users`

**Comment by scopatz** [comment]
Oof, thanks for reporting @derekbrokeit... This is on PTK?

**Comment by astronouth7303** [comment]
For me, yes.

**Comment by bobhy** [comment]
Garbling due to string escape processing '\a' --> BEL, etc. Only some subdirs start with a magic character.

```cmd
$ $PWD
'n:\\Users\\James\\code\\aca-dev\\billing'
-------------------------- bobhy@BobHy-PC n:\Users\James\code\aca-dev\billing
$ echo $PWD
n:\Users\James\codeca-deilling
-------------------------- bobhy@BobHy-PC n:\Users\James\code\aca-dev\billing
$ t = $(echo $PWD)
-------------------------- bobhy@BobHy-PC n:\Users\James\code\aca-dev\billing
$ t
'n:\\Users\\James\\code\x07ca-dev\x08illing\n'
-------------------------- bobhy@BobHy-PC n:\Users\James\code\aca-dev\billing
$ mkdir foo
-------------------------- bobhy@BobHy-PC n:\Users\James\code\aca-dev
$ cd foo
-------------------------- bobhy@BobHy-PC n:\Users\James\code\aca-dev\foo
$ t1 = $(echo $PWD)
-------------------------- bobhy@BobHy-PC n:\Users\James\code\aca-dev\foo
$ t1
'n:\\Users\\James\\code\x07ca-dev\x0coo\n'
```

**Comment by scopatz** [comment]
I believe that this is fixed now and has been for a little while. Please feel free to reopen if this issue continues to crop up.
