### ISSUE TITLE
DOC: knight vs snail broken

### ISSUE THREAD

**Issue by CJ-Wright** [xonsh/xonsh#1853]
It seems this [link](https://github.com/xonsh/xonsh/blob/master/_static/knight-vs-snail.jpg) is broken in the guidelines.

**Comment by scopatz** [comment]
I believe that this works in the rendered docs http://xon.sh/devguide.html  It might be too much to expect that the doc source will render correctly on github statically :) Thanks for reporting!

**Comment by OJFord** [comment]
I think it's because `docs/devguide.rst` is a symlink for `CONTRIBUTING.rst` - and the image URI is relative to the former.

This works on xon.sh, but not when Github renders it (because quite correctly, it doesn't find a `_static` dir in the repo root).

Without changing the symlink setup, the only solution is probably to make it an absolute link to one of:
- https://github.com/xonsh/xonsh/raw/master/docs/_static/knight-vs-snail.jpg
- https://raw.githubusercontent.com/xonsh/xonsh/master/docs/_static/knight-vs-snail.jpg

**Comment by scopatz** [comment]
Right, but absolute links would break locally hosted docs.

**Comment by OJFord** [comment]
> absolute links would break locally hosted docs.

I don't follow, is there offline access to docs (without having cloned the repo)?

Trying to find such a thing made me think - could be neat to have xonsh override Python's `help()` to add xonsh-stuff; fallback on Python help when passed a Python object.

**Comment by laerus** [comment]
`which -a` pretty much searches for everything, better not mess with the builtin `help`
but it would be nice to have a general help-like command, a xontrib on this matter would be great.

note: you can also use `${...}.help(ENVVAR)` to get formatted info from the VarDocs.

**Comment by astronouth7303** [comment]
Would a `help!` be ok? Then you could say `help! $XONSHRC`.

**Comment by melund** [comment]
What about ? and ??:  Could they be made to work on environment variables. `$XONS_SHOW_TRACEBACK??`

**Comment by scopatz** [comment]
> I don't follow, is there offline access to docs (without having cloned the repo)?

Not really without the repo or tarball.  But being able to `cd docs and make html` is pretty important to ensuring the docs are correct.

> What about ? and ??: Could they be made to work on environment variables. $XONS_SHOWH_TRACEBACK??

Yes, it would take a small amount of mucking around in the parser, but could be done.

**Comment by scopatz** [comment]
I like `$VAR?` more than `help!` personally.  The other option, of course, is the make the Env class have keys that are special strings whose `__help__()` or `__doc__` is overwritten.  Then no changes to the parser would need to be made.

**Comment by laerus** [comment]
EnvVar object..  I've added Env.help but now i see there is no use for it in xonsh scripts, +1 for dropping it for the `?` syntax.

**Comment by gforsyth** [comment]
Closing this
