### ISSUE TITLE
echo foo >bar doesn't work

### ISSUE THREAD

**Issue by daym** [xonsh/xonsh#1863]
Maybe it's different in xonsh than in bash but I type that very frequently and I get:

``` shell
echo foo >bar
............................................. 
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: foo',)
echo foo >bar
     ^
```

**Comment by astronouth7303** [comment]
Nope, that is [valid xonsh syntax](http://xon.sh/tutorial.html#input-output-redirection). Although in general, it's safer to assume xonsh does things different than bash.

**Comment by daym** [comment]
Hmm, what's doing on with it, then?

**Comment by laerus** [comment]
yes this is a place where xonsh separates from bash,
xosh can redirect the streams with words too, for example:
`echo foo err>out > file` will redirect both stdout and stderr in 'file'.
but if you wanted to redirect to a file named 'out' then it would be very ambiguous

Redirections are arguments that may take filename arguments,
and like every argument in subprocess mode, it's separated at whitespace.

we must add this as a warning or a note in that tutorial section @astronouth7303 linked.
