### ISSUE TITLE
Parentheses after shell commands when using sympy

### ISSUE THREAD

**Issue by pgoelz** [xonsh/xonsh#1868]
A friend just reported this to me and I could confirm it:
As soon as I enable unicode printing in sympy, there is an additional "()" after every shell command. Other commands are not effected.

```
$ from sympy import init_printing
$ init_printing(use_unicode=True)
$ echo "hello"
hello
()
```

I am working on xonsh 0.4.7 and sympy 1.0.

**Comment by scopatz** [comment]
Thanks for reporting @pgoelz! For what it is worth, this doesn't seem to happen on master for me.

**Comment by scopatz** [comment]
Though, it does start adding newlines to all output, oddly.  Does sympy patch the display hook?

**Comment by koehlma** [comment]
Yes it does patch the display hook in `sympy.interactive.printing._init_python_printing`. Should this be fixed in Sympy? Storing the old display hook and calling it if the object is not a Sympy object does fix it.

**Comment by scopatz** [comment]
Yes, this should probably be fixed in SymPy. There isn't much we can do from xonsh, I don't think

**Comment by gforsyth** [comment]
I'm going to close this out since it's a SymPy issue.  Please reopen if there's something needed on our end.  Thanks!
