### ISSUE TITLE
less doens't work on Windows

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1874]
The `less` command (from the GitForWindows Unix tools) is broken on Windows. It just quits and prints all output. 

This affects commands like `git log` which uses `less` to show large output. Running `git log` in xonsh repo outputs a _lot_ of lines :)

@BYK has also confirmed this issue.

**Comment by laerus** [comment]
for me on this slow machine this pretty much affects every command with huge output

**Comment by scopatz** [comment]
Thanks for reporting @melund The only thing we should be doing different from 0.4.7 for less is that we os.pipe() stdout, where maybe we shouldn't.

@laerus are there specific commands that fail? Namely the ones that go into alternate mode?

**Comment by laerus** [comment]
using `ls` in big directories, or greping huge output like `apt list`.

**Comment by scopatz** [comment]
`apt list` seems to work for me.  What happens exactly?

**Comment by laerus** [comment]
On the slow netbook the output gets cut off on commands with huge output, even with low proc frequency. (through piping or not)

**Comment by gforsyth** [comment]
Hey @laerus -- if you add `apt` as a `predict_help_ver` in `xonsh/command_cache.py` do you still have issues with output being cut off?

**Comment by melund** [comment]
This is fixed in master now.
