### ISSUE TITLE
Some aliases stopped working after commit 7be2813

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#1879]
I have an alias for `ranger` which is not too complicated. It does two things, it renames my tmux window and it also changes to the last navigated directory upon exiting ranger.

This alias has worked for me for a long time. After checking out commit c262e0358f053ad374e256efcd31007141eb1c7e executing `ranger` at shell was working but with the next commit, 7be281375ae74995a7878cad20f387bb1e341353, executing `ranger` hangs. If I press `Ctrl+C` I can get back to the prompt.

I would be grateful if somebody could help me identify if I'm doing something wrong or if there is a bug.

``` python
def rename_term(args, stdin=None, tcmd=None, tname=None):                                                                             
    win_info = $(tmux display-message -p) 
    if win_info:                                                                                                                      
        win_info = win_info.split()[1].rstrip(',').split(':')                                                                         
    if win_info and len(win_info) == 2:                                                                                               
        $(tmux rename-window -t @(win_info[0]) @(tname)) 
    evalx(" ".join([tcmd]+args))  #Command is actually run here
    if win_info and len(win_info) == 2:                                                                                               
        sleep 0.25                                                                                                                    
        $(tmux rename-window -t @(win_info[0]) @(win_info[1])) 

@foreground                                                                                                                           
def execRanger(args, stdin=None):                                                                                                     
    rename_term(args=args,                                                                                                            
                tcmd=$(which -s ranger).strip(),   
                tname='ranger')                                                                                                       
    with open(join(expanduser('~'), ".config/ranger/bookmarks"), 'r') as book: 
        bookmarks = book.readlines()                                                                                                  
    currDir = [line for line in bookmarks if line.startswith("'")]                                                                    
    if currDir and currDir[0]:                                                                                                        
        currDir = currDir[0][2:].replace('\n', '')                                                                                    
        cd @(currDir)                                                                                                                 

aliases['ranger'] = execRanger
```

**Comment by scopatz** [comment]
Hi @JohnLunzer, I'll take a look at these this weekend (assuming my university duties don't take over my life.)

**Comment by JohnLunzer** [comment]
Thanks for trying to find some time.

**Comment by gforsyth** [comment]
@JohnLunzer -- what happens if you remove the `@foreground` decorator?

**Comment by JohnLunzer** [comment]
If I remove `@foreground` then `ranger` loads but contains graphical errors, is sluggish, and upon exiting crashes `xonsh`. I wrote these aliases a long time ago, but that's probably why I added it in the first place.

Here is the traceback:

```python
Traceback (most recent call last):
  File "/home/usr/xonsh/xonsh/ptk/shortcuts.py", line 108, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 380, in feed
    self._input_parser.send(c)
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 299, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 332, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 1007, in feed_key
    cli.input_processor.process_keys()
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 209, in process_keys
    cli.invalidate()
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 333, in invalidate
    self.eventloop.call_from_executor(redraw, _max_postpone_until=_max_postpone_until)
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 237, in call_from_executor
    os.write(self._schedule_pipe[1], b'x')
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/usr/xonsh/xonsh/main.py", line 221, in main
    shell.shell.cmdloop()
  File "/home/usr/xonsh/xonsh/ptk/shell.py", line 123, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/usr/xonsh/xonsh/ptk/shell.py", line 92, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/usr/xonsh/xonsh/ptk/shortcuts.py", line 113, in prompt
    eventloop.close()
  File "/jlunz/anaconda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 254, in close
    os.close(schedule_pipe[1])
OSError: [Errno 9] Bad file descriptor

```

**Comment by gforsyth** [comment]
Can you post the output of `xonfig`?

**Comment by JohnLunzer** [comment]
Using the most recent upstream master
```
+------------------+---------------------------------------------------+
| xonsh            | 0.4.7                                             |
| Git SHA          | 00ef1c4                                           |
| Python           | 3.5.1                                             |
| PLY              | 3.7                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.3                                             |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.0.2                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7fd10914bba8> |
| distro           | CentOS                                            |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+
```

**Comment by JohnLunzer** [comment]
For good measure I updated prompt-toolkit to 1.0.8 with no change in behavior.

**Comment by gforsyth** [comment]
I thought that might help with the graphical irregularities in ranger but it didn't work on my end.  

The only place we use the `@foreground` decorator in xonsh core is in `trace` which also appears to hang now, so I'm thinking that's the likely culprit.

**Comment by scopatz** [comment]
Thanks for hunting down the foreground issue. (And sorry I didn't get a chance to look at this over the weekend.) Looking at this now

**Comment by scopatz** [comment]
I think that this is partially, though not wholly related to #1870.

**Comment by gforsyth** [comment]
Adding `ranger` with a `predict_false` to the command cache does eliminate the graphical weirdness

**Comment by scopatz** [comment]
what is ranger?

**Comment by gforsyth** [comment]
@scopatz: It's a curses backed file manager written in Python

@JohnLunzer: Can you try out your alias now after removing the `@foreground` decorator?  And do you have any other alias failures on current master?

**Comment by scopatz** [comment]
Ahh ok, basically everything that is curses based should go into the predict-false category

**Comment by JohnLunzer** [comment]
@gforsyth , sorry I'm a little confused. I updated to the current master and removed the `@foreground` decorator and received the same graphical issues when running `ranger` in `tmux` and crashing when running `ranger` in the straight xonsh shell. 

I added `'ranger': predict_false` to `command_cache.py` and I'm getting the same behavior as if the `@foreground` decorator were there, ie. `ranger` doesn't start.

Additionally, if I exit the hung `ranger` with `ctrl+c` and then try to exit `xonsh` I get a message that says that jobs are still running.

**Comment by gforsyth** [comment]
Whoops!  Sorry, I thought I had added `ranger` to the threadable predictors dict.  
There may be other parts of your alias causing trouble -- can you confirm whether or not ranger works as expected if you just run it as is, without the alias (but with the entry in `commands_cache.py`)?

**Comment by JohnLunzer** [comment]
with `'ranger': predict_false` on the current master an unaliased `ranger` runs fine (no crashing or graphical errors ) inside and outside of `tmux`. I must be doing something funny in my alias...

**Comment by JohnLunzer** [comment]
Let me simplify the error case here, this alias:
```python
rcmd = $(which -s ranger).strip()

def execRanger(args, stdin=None):
     evalx(rcmd)

aliases['ranger'] = execRanger
```
Hangs with `'ranger': predict_false` and graphical errors without. Am I misusing `evalx`? I also tried with `$(@(rcmd))` and the same behavior. 

If I just type `evalx(rcmd)` at the command line with `'ranger': predict_false` it runs without issue.

**Comment by JohnLunzer** [comment]
And just for comparison, this last example works with and without the `@foreground` decorator in commit https://github.com/xonsh/xonsh/commit/c262e0358f053ad374e256efcd31007141eb1c7e.

**Comment by gforsyth** [comment]
Ahhh... ok, this is interesting.  No, you are not misuing `evalx`.  I can reproduce this with any program that we've set as not threadable being used inside an alias.  

```console
def _vim(args, stdin=None):
    vim
aliases['myvim'] = _vim
vim
```
will hang, as will (mutatis mutandis) `htop`, `top`, `ranger`, etc...
but

```console
def _python(args, stdin=None):
    ipython
aliases['ipy'] = _python
ipy
```
works fine.

I think we're getting caught up in `_update_last_spec` in `xonsh.built_ins` -- we don't do the threadability check if something is a callable alias.  Probably need to rework some of the logic there... I'll play with it for a bit, but this may require @scopatz's tender ministrations.

**Comment by scopatz** [comment]
A glimmer of hope: $[myvim] seems to work for me.  Gonna figure out how to formalize this.

**Comment by scopatz** [comment]
Hi @JohnLunzer, would you mind trying #1912?

**Comment by scopatz** [comment]
And also @gforsyth :)

And by trying, I mean decorate your aliases with both unthreadable and uncapturable:

```python
from xonsh.proc import uncapturable, unthreadable

@uncapturable
@unthreadable
def _vim(args, stdin=None):
    vim

aliases['myvim'] = _vim
myvim
```

**Comment by gforsyth** [comment]
Hey @JohnLunzer -- sorry about the autoclose.  Could you confirm that the following works for you on current master?

```
from xonsh.proc import unthreadable, uncapturable

@uncapturable
@unthreadable
def _ranger(args, stdin=None):
    ![$(which -s ranger)]

aliases['ranger'] = _ranger
```

**Comment by JohnLunzer** [comment]
@scopatz, your provided ```myvim``` alias does not hang. If I remove the decorators it does hang. Interestingly if I create two aliases, one with the decorators and one without the decorators but otherwise identical, ```myvimold```, and I run ```myvimold``` first and it hangs and I ```Ctrl+c``` out then ```myvim``` will also hang when I try to run it.

@gforsyth, your provided ```ranger``` alias does not hang, but I am still having graphical abnormalities both inside and outside of Tmux. You have to move through the directory tree a bit for the abnormalities to show up.

My current xonfig:
```
+------------------+---------------------------------------------------+
| xonsh            | 0.4.7                                             |
| Git SHA          | c82848e                                           |
| Python           | 3.5.1                                             |
| PLY              | 3.7                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.8                                             |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.0.2                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7fbdac18ea58> |
| distro           | CentOS                                            |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+
```

**Comment by gforsyth** [comment]
Hey @JohnLunzer -- can you try out #1919 and see if that fixes the ranger issues?  Thanks.

**Comment by gforsyth** [comment]
We're open to any suggestions for how to manage that list heuristically...

Sigh.  I think all of these issues have been resolved -- please close if this is good to go!  Thanks!
