### ISSUE TITLE
No output from scp command

### ISSUE THREAD

**Issue by blahgeek** [xonsh/xonsh#1880]
While running scp in xonsh, the progress does not showed up:

https://asciinema.org/a/322p80uvb0pjyaic2e51iqmhq

I'm using version 3f45378

**Comment by gforsyth** [comment]
Hi @blahgeek -- could you try out the fix in #1890 and see if that resolves your issue?

**Comment by gforsyth** [comment]
Also, sorry for not responding before thsi!

**Comment by blahgeek** [comment]
Works for me, thanks a million!
