### ISSUE TITLE
Pipes hang on windows.

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1885]
I get a hanging process if I pipe stuff on windows. Here are two examples:

``` bash
snail@sea ~\Documents\xonsh master $ echo @('hello') | clip
       [hangs here... Presssing ctrl-c gives this]
ValueError: Unsupported signal: 2
snail@sea ~\Documents\xonsh master $ cat CHANGELOG.rst | grep regression
       [hangs here... Pressing ctrl-c gives this]
ValueError: Unsupported signal: 2
snail@sea ~\Documents\xonsh master $ jobs
[1]+ running: cat CHANGELOG.rst | grep regression (19004)
```

**Comment by scopatz** [comment]
Hi @melund, thanks for reporting. I won't be at my windows box until after work, but did #1870 help at all?  I fixed a couple on piping issues on windows that I noticed there.

**Comment by melund** [comment]
I hoped it would as well, but sadly no.  #1870 didn't change anything for this issue.

**Comment by scopatz** [comment]
OK, I will take a look tonight.

**Comment by gforsyth** [comment]
I'm seeing this, too, actually, but without any error messages.

```console
cat junkfile | wc -l
```
just hangs and Ctrl-C returns to prompt without output.

**Comment by scopatz** [comment]
Oh yeah, weird.  Great though.  That means I can debug at least part of this on Linux :)

**Comment by scopatz** [comment]
At least the case @gforsyth brought up is a bug I introduced fixing the `parallel` command

**Comment by mitnk** [comment]
mac has the same issue. the latest of #1893 not fixing it on mac.

**Comment by scopatz** [comment]
@mintk can you give some specific examples, one of the test cases was fixed on mac, and there are probably many simultaneous issues.

**Comment by mitnk** [comment]
As I mentioned in #1801, seems piped jobs has issue in general. cases are:

```
$ ps ax | wc -l
$ cat /etc/hosts | wc -l
$ cat /etc/hosts | sort
```

Basically, the new version (0.4.7) broken on Mac OS X. Currently I'm using bash :(

**Comment by melund** [comment]
Well. It fixes the pipe issue I was having on windows.

**Comment by mitnk** [comment]
Ah, #1893 fixed my issue on my Mac home, but not the one at work, weird.
