### ISSUE TITLE
echo and cp crash on os x

### ISSUE THREAD

**Issue by vancesteven** [xonsh/xonsh#1892]
('xonsh/0.3.2',)
'3.5.1 |Anaconda custom (x86_64)| (default, Dec  7 2015, 11:24:55) \n[GCC 4.2.1 (Apple Inc. build 5577)]'

https://gist.github.com/vancesteven/67737927c7f3d5a5c8b570247c78c1c1

**Comment by scopatz** [comment]
Thanks for reporting @vancesteven.  Can you run the `xonfig` command to give us more information?  Also v0.3.2 is pretty far out of date at this point.  Any way that you could upgrade?  Also note that the error is actually coming from prompt-toolkit, which I am also guessing is far out of date....

**Comment by scopatz** [comment]
Also also, we now use the conda-forge channel, instead of the xonsh channel for conda packages. You'll probably want to switch...

**Comment by scopatz** [comment]
And sorry, didn't mean to close.

**Comment by vancesteven** [comment]
Hi @scopatz, here's the xonfig:
+------------------+-------+
| xonsh            | 0.3.2 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 1.0.3 |
| pygments         | 2.1.1 |
| on posix         | True  |
| on linux         | False |
| on darwin        | True  |
| on windows       | False |
| is superuser     | False |
| default encoding | utf-8 |
+------------------+-------+

That's helpful, as I was concerned xonsh wasn't seeing readline.  I'll see about upgrading outside of conda.

**Comment by vancesteven** [comment]
@scopatz okay, conda-forge install renders the echo error irreproducible. Thanks!

**Comment by scopatz** [comment]
Excellent.  Please feel free to close this then!
