### ISSUE TITLE
Mutt Line Wrapping Broken In Recent xonsh?

### ISSUE THREAD

**Issue by adqm** [xonsh/xonsh#1901]
In recent xonsh, mutt is not wrapping lines as it should (in particular, with the mutt sidebar enabled).  Rather than wrapping around inside the area where I can usually read the message, they are wrapping to cover up the sidebar, and not being properly cleared when I switch between messages.  I would guess this means that certain escapes aren't being handled properly?

**Comment by scopatz** [comment]
Mutt is curses based, right?

**Comment by scopatz** [comment]
@adqm, thanks for mentioning this.  Can you please try #1902?

**Comment by gforsyth** [comment]
Hey @adqm -- is this still an issue on master or did the unthreadable fix handle it?

**Comment by adqm** [comment]
Yes, seems to be fixed.  Closing.
