### ISSUE TITLE
mvim issue - exec breaks on Mac?

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1904]
On Mac, when I start a MacVim from xonsh with `mvim`:

$ mvim foo.txt

It opens up a MacVim GUI window and,

in previous version of xonsh or bash:

the process of `mvim` exits and xonsh session can be typed with new commands.

**But in current xonsh**,

the xonsh session hangs up until I exit the MacVim Application process.

The code of `mvim` [is here](https://github.com/macvim-dev/macvim/blob/master/src/MacVim/mvim).

**Comment by mitnk** [comment]
It hangs on the `self._safe_close(s.captured_stdout)` line of `xonsh.proc.CommandPipeline`.

**Comment by gforsyth** [comment]
Hi @mitnk -- thanks for reporting!  Could you try out the branch `mvim_cache` and let me know if that resolves your issue?  Thanks!

**Comment by mitnk** [comment]
Yes, it works. (I think I had tried the same way, like `mutt`, but did work that time. weird). Anyway thanks a lot!

I'm a little concerned the way it being fixed. The list would get longer and longer. And ever we add an ability to extend the list via xonshrc (can we now?), this is a new rule of xonsh for users to aware.

**Comment by scopatz** [comment]
> I'm a little concerned the way it being fixed. The list would get longer and longer. 

Yes, we need a generic way of predicting threadability. I am open to suggestions!

> And ever we add an ability to extend the list via xonshrc (can we now?), this is a new rule of xonsh for users to aware.

You can already do this at any time in xonsh (including the rc) with by adding an entry to the `__xonsh_commands_cache__.threadable_predictors`  dict.

**Comment by gforsyth** [comment]
Closed via  	1b85482
