### ISSUE TITLE
Piping to `less` not working on Windows.

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1905]
So `less` is working again, and pipes also seem to work in general. 

But piping to ´less´ doesn't work. It just prints all the output and exists less. I think @scopatz  is aware of that. 

```
$ cat CHANGELOG.rst | less
```

Maybe it is the same issue we see with `git log`. Behaviour seems very similar.

**Comment by scopatz** [comment]
As an update, I think I have a generic fix for windows in the works that manages to retain normal streaming behaviour while also capturing output.  I think I have the hard pieces figured out, but haven't integrated it with the proc architecture yet.

**Comment by scopatz** [comment]
At least that specific example is fixed for me on #1911
