### ISSUE TITLE
xonsh consumes too much CPU

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1913]
I found on Mac, running server like applications, like `python3 -m http.server` will make xonsh consuming about 15% CPU. It seems xonsh loops hard for checking something?

**Comment by scopatz** [comment]
Hi @mitnk - thanks for reporting.  @laerus has mentioned this happens, particularly on slower and older machines.  We are trying to figure out how to address this.  What are the specs for your system?

**Comment by mitnk** [comment]
MBPr 2015, 2.2G i7, 16G Ram. And another older Mac has the same issue - both at 15% CPU (on one core).

**Comment by laerus** [comment]
hey @mitnk this got a lot better for me after the latest changes @scopatz introduced, can you check if the cpu usage is the same on latest master?

**Comment by mitnk** [comment]
`python3 -m http.server` still consume ~20% CPU.

```
+------------------+---------------------+
| xonsh            | 0.4.7.dev1495       |
| Git SHA          | a797a9d             |
| Commit Date      | Nov 8 23:24:25 2016 |
| Python           | 3.5.2               |
| PLY              | 3.7                 |
| have readline    | True                |
| prompt toolkit   | 1.0.4               |
| shell type       | readline            |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by scopatz** [comment]
I am seeing this myself.

**Comment by JohnLunzer** [comment]
I believe I am seeing something similar using `gevent.wsgi.WSGIServer()` but I can't say for sure. 

I just noticed that xonsh is running about 30% on one of my machines and 45% on my other (both linux, rhel and centos) when I run one of my applications which uses this. This didn't used to be the case.

**Comment by scopatz** [comment]
Yup, this is a serious issue. Now that I am done addressing some performance issues elsewhere, I'll take a look at this one.

**Comment by scopatz** [comment]
Ok, woud you all mind trying out #1950.  This seems to do the trick for me.

**Comment by gforsyth** [comment]
Closing this -- if anyone still has spikes in CPU usage let us know and we can revisit this.
