### ISSUE TITLE
Background jobs are broken

### ISSUE THREAD

**Issue by SirNickolas** [xonsh/xonsh#1928]
In the subprocess mode, the trailing ampersand is not recognized as a background job indicator, and instead passed directly to argv:

```sh
>>> # Xonsh 0.4.6:
>>> sleep 3 &
[1]+ running: sleep 3 & (28043)

>>> # Xonsh 0.4.7:
>>> sleep 3 &
/bin/sleep: invalid time interval '&'
Try '/bin/sleep --help' for more information.
```

**Comment by Siecje** [comment]
This is fixed in ```master```

**Comment by SirNickolas** [comment]
My fault. Should test that before filing an issue.

**Comment by Siecje** [comment]
I did just check ```master```. But the only reason I know is because I did the same thing https://github.com/xonsh/xonsh/issues/1804
