### ISSUE TITLE
MOUSE_SUPPORT=True prevents scrolling, selection macOS

### ISSUE THREAD

**Issue by mangecoeur** [xonsh/xonsh#1930]
Setting $MOUSE_SUPPORT=True on macOS appears to break touch (two finger) and scrollwheel scrolling in macOS Terminal, as well as text selection and copy/paste. All of these actions simply stop working (no error messages). Somewhat ironically, mouse input is better supported with mouse_support=False :/

**Comment by scopatz** [comment]
Hello @mangecoeur, I am assuming that you are using the PTK shell.  We simply call out to their mouse handling.  I recommend that you report this to https://github.com/jonathanslenders/python-prompt-toolkit  If there is anything that we can do or should do in xonsh, please let us know!

**Comment by mangecoeur** [comment]
@scopatz yes I am using PTK shell, will report accordingly

**Comment by gforsyth** [comment]
Closing this since it's a PTK issue.

**Comment by sbliven** [comment]
As reported in the prompt-toolkit thread, the work-around in iTerm2 is to disable 'Report mouse wheel events' in Preferences > Profiles > Terminal.
