### ISSUE TITLE
Incorrect piping results when a job is "long"

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#1931]
TLDR: piping a long file through sort and writing it out to a file gives inconsistent/wrong results

I was putting together a tutorial using some uber pickup data and ran into this.  
I have a csv file that's 14 million+ lines long

```console
gil@theo ~/ube/uber-trip-data master 🐚  wc -l uber-raw-data-janjune-15.csv
14270480 uber-raw-data-janjune-15.csv
```

It's not sorted by date, so I do

```console
gil@theo ~/ube/uber-trip-data master 🐚   cat uber-raw-data-janjune-15.csv | sort -t "," -k2 > janjune-15-sorted.csv
```

but then I get

```console
gil@theo ~/ube/uber-trip-data master 🐚  wc -l janjune-15-sorted.csv
0 janjune-15-sorted.csv
```

```
gil@theo ~/ube/uber-trip-data master 🐚  for i in range(10000, 130000, 10000):
........................................     head -n @(i) uber-raw-data-janjune-15.csv | sort -t "," -k2
........................................  > xonsh_sort.csv
........................................     wc -l xonsh_sort.csv
........................................      
10000 xonsh_sort.csv
20000 xonsh_sort.csv
30000 xonsh_sort.csv
30856 xonsh_sort.csv
0 xonsh_sort.csv
0 xonsh_sort.csv
0 xonsh_sort.csv
0 xonsh_sort.csv
0 xonsh_sort.csv
0 xonsh_sort.csv
110000 xonsh_sort.csv
120000 xonsh_sort.csv
```

So is this overflowing an `os.pipe` somewhere or something?

**Comment by gforsyth** [comment]
If it's strictly a streaming affair, there are no issues:

```console
gil@theo ~/ube/uber-trip-data master 🐚  for i in range(1000000, 15000000, 1000000):
........................................     head -n @(i) uber-raw-data-janjune-15.csv | sed 's/B/ /' > 
........................................ xonsh_sed.csv
........................................     wc -l xonsh_sed.csv
........................................     
1000000 xonsh_sed.csv
2000000 xonsh_sed.csv
3000000 xonsh_sed.csv
4000000 xonsh_sed.csv
5000000 xonsh_sed.csv
6000000 xonsh_sed.csv
7000000 xonsh_sed.csv
8000000 xonsh_sed.csv
9000000 xonsh_sed.csv
10000000 xonsh_sed.csv
11000000 xonsh_sed.csv
12000000 xonsh_sed.csv
13000000 xonsh_sed.csv
14000000 xonsh_sed.csv
```

**Comment by scopatz** [comment]
Hey gil I know this is a dumb question but could you verify that this actually works in bash please? My concern is that this might actually be a problem with sort

**Comment by gforsyth** [comment]
Hey @scopatz -- it does work in bash.  I checked to make sure I wasn't going crazy.

**Comment by scopatz** [comment]
Okay great. is there a place that you can point me to so I can get the data set and play around with it as well? Thanks!

**Comment by gforsyth** [comment]
Sure thing!
https://github.com/fivethirtyeight/uber-tlc-foil-response/blob/master/uber-trip-data/uber-raw-data-janjune-15.csv.zip?raw=true

**Comment by gforsyth** [comment]
And the `--parallel` flag in `sort` is your friend

**Comment by scopatz** [comment]
It is good to have friends ;) I might not get to this until tomorrow, if that is ok?

**Comment by gforsyth** [comment]
No worries at all.  Not a huge rush on this, just a strange thing I stumbled on

**Comment by scopatz** [comment]
OK Cool.  I am actually looking forward to debugging this one :)

**Comment by scopatz** [comment]
Sorry for the delay @gforsyth! It seems like some of the performace fixes (and namely the blocking addition to the end of PopenThread.run()) may have fixed this.  The above two examples work locally for me at least:

```
scopatz@artemis ~/temp $ xonsh large.xsh 
14270480 uber-raw-data-janjune-15.csv
14270480 janjune-15-sorted.csv
scopatz@artemis ~/temp $ xo large-chunk.xsh
scopatz@artemis ~/temp $ xonsh large-chunk.xsh 
10000 xonsh_sort.csv
20000 xonsh_sort.csv
30000 xonsh_sort.csv
40000 xonsh_sort.csv
50000 xonsh_sort.csv
60000 xonsh_sort.csv
70000 xonsh_sort.csv
80000 xonsh_sort.csv
90000 xonsh_sort.csv
100000 xonsh_sort.csv
110000 xonsh_sort.csv
120000 xonsh_sort.csv
```

I can send the scripts too, but they are copied directly from what you posted.

**Comment by gforsyth** [comment]
Woohoo!  Works here, too!
