### ISSUE TITLE
HISTCONTROL ignoreerr - Better would be commenterr

### ISSUE THREAD

**Issue by daym** [xonsh/xonsh#1935]
Hi,

I've tried using ignoreerr for some weeks and it's just too jarring if the entry is missing from the interactive history (file history not so much).

I think much better would be something that, on error, added the offending line with a comment character "#" in front.

Let's say 

```shelll$
garble
```

failed, then it would add

`#garble` 

to the history.

What do you think?

**Comment by scopatz** [comment]
Hi @daym, Thanks for bringing this up.  I am generally not a fan of rewriting history, and the behaviour that you want seems to be different than a simple ignore. 

I would suggest that maybe we could have an additional flag for HISTCONTROL, maybe named `commenterr` that has the behaviour you suggest.  Does this sound reasonable? Pull requests very welcome!  I can point people to the relevant part of the code if needed.

**Comment by scopatz** [comment]
I think this has been implemented
