### ISSUE TITLE
Ctrl-w and alt-backspace do the same thing and are less powerful than in bash

### ISSUE THREAD

**Issue by jonjitsu** [xonsh/xonsh#1937]
In bash the behavior is different and more useful.

Ctrl-w: delete chars backwards up to first whitespace char (non-inclusive) and put in "clipboard"
alt-backspace: delete chars backwards up to first non-alphanumeric (non-inclusive) and put in "clipboard"

I'm unsure of the exact behavior of these two commands in bash but they're more useful than the equivalents in xonsh. Perhaps being able to set the desired behavior in xonshrc could be a possibility.

**Comment by laerus** [comment]
hey @jonjitsu thanks for reporting! can you please post the output of `xonfig`?

**Comment by scopatz** [comment]
Thanks @jonjitsu, and yes, the `xonfig` command would help us determine if this is a readline or prompt-toolkit issue.

**Comment by santagada** [comment]
for me with prompt-toolkit ctrl+w works better than zsh (libedit/readline) examples:
"vim /" becomes "vim " in xonsh (prompt_toolkit) and "" in zsh.
"vim something" becomes "vim " in both.

alt+backspace doesn't do anything in either.

**Comment by mitnk** [comment]
@jonjitsu [python-prompt-toolkit has updated ctrl-w](https://github.com/jonathanslenders/python-prompt-toolkit/issues/426) on master to the way what you wanted, but not release yet.

**Comment by scopatz** [comment]
That is awesome! Looking forward to the release then!

**Comment by mitnk** [comment]
Hi @jonjitsu, so with new version of `python-prompt-toolket` (version 1.0.13) you will get `echo ` with `echo hello-world<Ctrl+W>` (It was `echo hello-` before with version 1.0.8).

And as @santagada mentioned, `Alt-backspace` doesn't do anything in my side both in bash and xonsh.

So I'm closing this issue, feel free to reopen if you think xonsh should do some extra things here. Thanks!

**Comment by GuillaumeLeclerc** [comment]
It seems still to be a problem in the current version of `xonsh`. How can one configure <Ctrl+w> to behave normally ? It's really annoying to not be able to just delete a single part of a path.

**Comment by GuillaumeLeclerc** [comment]
In the meantime I ended up doing this in case anyone needed it. Hopefully it doesn't have too many edge cases:

.xonshrc
```python

@events.on_ptk_create
def custom_keybindings(bindings, **kw):

    @bindings.add(Keys.ControlW)
    def delete_to_last_path_separator(event):
        line = event.current_buffer.text
        pos = event.current_buffer.cursor_position
        rp = pos
        seps = ['/', ' ']
        add = 0
        cc = line[pos - 1]
        if line[pos - 1] in seps:
            pos -= 1
            add = 1
            seps = [line[pos - 1]]
        for path_sep in ['/', ' ']:
            if path_sep in line[:pos]:
                last_sep_pos = line[:pos].rindex(path_sep)
                coord = pos - last_sep_pos + add
                event.current_buffer.delete_before_cursor(coord)
                if add == 1:
                    event.current_buffer.insert_text(path_sep)
                break
        else:
            event.current_buffer.delete_before_cursor(rp)
```
