### ISSUE TITLE
emacsclient -t

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#1944]
I use the emacs daemon via the `emacsclient -t` command to run emacs in my console. I create an alias for that which I shorted to `em`.

Unfortunately I'm getting some odd behavior as an alias. Without `emacsclient` added to `commands_cache.py` the editor never opens, just hangs the shell. If I add `'emacsclient': predict_help_ver` to `commands_cache.py` then the editor will open and run correcty but upon exiting will hang the console. I did not add any decorators to the alias.

I'm not sure what is the way forward to get this to execute and exit normally.

**Comment by laerus** [comment]
Hey @JohnLunzer ty for reporting! Does Ctrl-C in either case of a hang up produce any traceback? this might need `$XONSH_SHOW_TRACEBACK=True`

**Comment by JohnLunzer** [comment]
I have `$XONSH_SHOW_TRACEBACK=True` and Ctrl-C in either case does not produce a traceback, but it does unhang the console.

**Comment by scopatz** [comment]
Hi @JohnLunzer, can you post the alias please? Thanks for reporting

**Comment by JohnLunzer** [comment]
I'll post it as soon as I get back to my desktop.

**Comment by JohnLunzer** [comment]
```python
def testEmacsClient(args, stdin=None):                                                                                                
    evalx(" ".join(["emacsclient -t"]+args))
aliases['em'] = testEmacsClient
```
The hanging behavior is not entirely consistent. If I run this a couple times and it hangs upon exit and I `ctrl+c` out it then sometimes it will not hang upon exiting emacs. Additionally, everytime I `ctrl+c` out it turns the process into a background process (which is the same behavior I've seen when I was having issues with other aliases of full screen console applications).

**Comment by scopatz** [comment]
I think the evalx is the blocking piece. What happens if you use:

```python
def testEmacsClient(args, stdin=None):                                                                                                
    emacsclient -t @(args)
```

instead?

**Comment by JohnLunzer** [comment]
Your version works without . If possible can you explain why the one works and the other doesn't? Sometimes I find it more clear to use `evalx` (though in this case yours is far more elegant) so it would be nice to try to understand this a little bit.

As a reminder, the alias you provided only works if I add `'emacsclient': predict_help_ver` to `commands_cache.py`. This addition does not appear to interfere with GUI version.

For the future... would it be possible to create a decorator with an argument to take a string for the different predict options which would do the same thing as editing `commands_cache.py`? This is not a long term solution but will allow a simple way to get certain aliases working for testing purposes.

**Comment by scopatz** [comment]
> If possible can you explain why the one works and the other doesn't? 

Basically, I think that you end up in a race condition where it is not clear whether evalx or the subproc or the alias should end first.  And for whatever reason, when the subproc ends, it is not propagating up.

> Sometimes I find it more clear to use evalx (though in this case yours is far more elegant) so it would be nice to try to understand this a little bit.

That is interesting to note.  I rarely use evalx myself, and it might implement the blocking semantics.

> For the future... would it be possible to create a decorator with an argument to take a string for the different predict options which would do the same thing as editing commands_cache.py? This is not a long term solution but will allow a simple way to get certain aliases working for testing purposes.

Yeah, that could definitely happen.  Anyone should please feel free to put in a PR.  I think it would only be a couple of lines.

**Comment by laerus** [comment]
I got my hands on windows10 machine, using PowerShell installed latest master
long story sort:
```
$ execx("def tt(): print('ok')")
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: None: no further code
$ execx("def tt(): print('ok')\n")
$ tt()
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NameError: name 'tt' is not defined
$ execx("def tt(): print('ok')\n", glbs=__xonsh_ctx__, locs=__xonsh_ctx__)
$ tt()
ok
```

@JohnLunzer any chance the alias works by adding `__xonsh_ctx__` 
on the `glbs` and `locs`  keywords of `evalx` ?

**Comment by JohnLunzer** [comment]
I should be clear, I'm not receiving any exceptions. I was interested in why my `evalx` syntax was hanging on exit of `emacsclient` but the syntax @scopatz provided does not hang on exit.

**Comment by JohnLunzer** [comment]
I'm going to close this as a resolution was found. Because I do not understand the mechanics well enough I'm not willing to say that the hanging behavior seen when using `evalx` is an issue. That said, there should probably be a disclaimer in the docs with regards to using `evalx` in aliases.

**Comment by laerus** [comment]
+1 for a working `evalx` in aliases.

**Comment by scopatz** [comment]
@JohnLunzer did you try using the unthreadable decorator on the alias?
