### ISSUE TITLE
Subprocess output is not captured using $(...) for some commands

### ISSUE THREAD

**Issue by cryzed** [xonsh/xonsh#1947]
```
cryzed@arch ~ $ xonsh --version
xonsh/0.4.7.dev538
cryzed@arch ~ $ a = $(echo "Hello")
cryzed@arch ~ $ a
'Hello\n'
cryzed@arch ~ $ b = $(pacman -Qmq)
anything-sync-daemon
arc-dark-suite-git
arc-suite-git
[...]
cryzed@arch ~ $ b
''
cryzed@arch ~ $ !(pacman -Qmq)
anything-sync-daemon
arc-dark-suite-git
arc-suite-git
[...]
CommandPipeline(stdin=None, stdout=None, stderr=None, pid=30659, returncode=0, args=['pacman', '-Qmq'], alias=None, stdin_redirect=['<stdin>', 'r'], stdout_redirect=['<stdout>', 'a'], stderr_redirect=['<stderr>', 'r'], timestamps=[1478876453.635026, 1478876453.9975464], executed_cmd=['/usr/bin/pacman', '-Qmq'], input=, output=, errors=None)
```

So the stdout/stderr output of the pacman command seems to be entirely uncaptured. This has definitely worked in previous versions.

**Comment by scopatz** [comment]
Thanks for reporting, @cryzed. Are you on master? What is the output of the xonfig command?

**Comment by cryzed** [comment]
Yes, I am, check the first few lines of the output I posted. [This](https://github.com/xonsh/xonsh/commit/28359582f3b71f3ef6cce4a592ab3d71f4e9ec60) commit to be specific.

```
cryzed@arch /mnt/sdb1/makepkg $ xonfig
+------------------+----------------------+
| xonsh            | 0.4.7.dev538         |
| Git SHA          | 2835958              |
| Commit Date      | Nov 11 13:46:35 2016 |
| Python           | 3.5.2                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.8                |
| shell type       | prompt_toolkit       |
| pygments         | 2.1.3                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by scopatz** [comment]
I think that this is because pacman was added to the `threadable_predictors` as false in most cases: https://github.com/xonsh/xonsh/blob/master/xonsh/commands_cache.py#L268

This seems weird to me and maybe it should be removed.  @gforsyth might know or remember more.

**Comment by gforsyth** [comment]
Yeah, I did that because pacman output was being printed in the wrong order in some cases.  It may be that that problem has been resolved elsewhere and we can remove it from `threadable_predictors`.  That said, I tried that this morning and I still can't capture the output of `pacman`

**Comment by scopatz** [comment]
Does pacman print to stderr? That would explain this behaviour.

**Comment by cryzed** [comment]
Nope:

```
cryzed@arch ~ $ from subprocess import Popen, PIPE
cryzed@arch ~ $ process = Popen(('pacman', '-Qmq'), stdout=PIPE, stderr=PIPE)
cryzed@arch ~ $ len(process.stdout.read()), len(process.stderr.read())
(1082, 0)
```

**Comment by cryzed** [comment]
I really have to say, the 0.4.7 release works much better than the current master. Of course that is to be expected from a stable release, but I feel that the recent changes to the stream-handling have introduced quite a few number of bugs. Could someone explain why these changes were necessary in the first place?

**Comment by gforsyth** [comment]
Hey @cryzed -- there were a large number of open issues that we wanted to address that required a refactor of `run_subproc`; that function was 300+ lines and very hard to touch (as evidenced by the ongoing issues in trying to get everything working again).  One of the main goals was to enable storing stdout in history files which caused a lot of problems in 0.4.7 and earlier.

**Comment by gforsyth** [comment]
Sorry -- I must've missed something the first time.  After much digging, it looks like `pacman` was still in the `threadable_predictors` dict and so was being run as a "regular" subprocess.  Fix incoming.

**Comment by scopatz** [comment]
To echo @gforsyth, once all of the kinks are worked out, I believe that the new model will be much better than the old one.  I apologize for any temporary instabilities on master, but we are trying to keep them at a minimum.

**Comment by cryzed** [comment]
Thanks for explaining, it really was more curiosity than actual critique! Of course I'm aware that expecting the development branch to be as stable as an actual release is unreasonable.

**Comment by gforsyth** [comment]
Ok, I think this is sorted. Thanks for reporting!

**Comment by con-f-use** [comment]
It's not sorted out:
```
┌─06-14:28 [confus@jcgbx ~]                                                  😱  😱
└$ cd $(mktemp -d)                                                              
cd: no such file or directory: /tmp/tmp.GETaBFFj2G
                                 
┌─06-14:28 [confus@jcgbx ~] [1]                                              😱  😱
└$ ll /tmp | grep tmp.GETaBFFj2G                                                
drwx------  2 confus  confus  4,0K Aug  6 14:28 tmp.GETaBFFj2G

┌─06-14:32 [confus@jcgbx ~]                                                  😱  😱
└$ xonfig                                                                       
+------------------+----------------------+
| xonsh            | 0.9.9                |
| Git SHA          | 550d70d2             |
| Commit Date      | May 22 01:42:07 2019 |
| Python           | 3.6.8                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by laloch** [comment]
@con-f-use, it's because there's a trailing newline at the end of the value returned from `$()` operator.
Try `cd @($(mktemp -d).rstrip())`.

**Comment by con-f-use** [comment]
A sorry, deleted my comment, because something was in fact captured, so thought a separate issue might be appropriate.
