### ISSUE TITLE
History Load at Launch Time Seems Slow

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1958]
When open a new xonsh session, for the first few seconds, when I input some prefix (say `ssh `) and hit `<UP>` key. Xonsh doesn't complete it the the commands already in history. I have to wait some seconds and hit `Ctrl+C`, input `ssh <UP>` again, then the xonsh completion begins to work. Is this the same case at your side too? I'm using readline shell at a Mac.

And an idea to this is a proposal - we can implement a simpler version of history (compare to the existing rich one), the ones don't need rich version can set to use simple version in RC and make history loading a bit lighter. Does this make sense?

**Comment by scopatz** [comment]
History is loaded asyncronously.  I doesn't really wait for many seconds for me.  1 sec tops.  How much history are you storing?

**Comment by scopatz** [comment]
We can definitely try to figure out a way to make this faster by caching closed histories or something.

**Comment by mitnk** [comment]
kept everything
```
$ ls xonsh-*.json | wc -l
    2351  ## of history files
$ history show all | wc -l
    5071
```

**Comment by mitnk** [comment]
did some `gc`(to 2002 / 1043, numbers as above), load speed did get faster..
