### ISSUE TITLE
Running loops in the background

### ISSUE THREAD

**Issue by kahrkunne** [xonsh/xonsh#1959]
Does xonsh have a way to run loops in the background, as in roughly the equivalent of the following bash code:
```bash
while true ; do 
    echo "text"
    sleep 1
done &
```

I'm new to xonsh, so I decided to learn to use it by rewriting some of my old bash scripts in it, but I can't figure out a way to do this.
If xonsh doesn't have such a feature, can we get it?

**Comment by astronouth7303** [comment]
Currently, you have to do it with Python's [`threading`](https://docs.python.org/3/library/threading.html). 

You can't currently background an alias. (_Might_ be fixed in master.)

xonsh is not bash. It's more like Python with some shell-friendly extras.

**Comment by kahrkunne** [comment]
I see. That's how I fixed it myself too, by using threading.
Personally I would prefer if xonsh had a way to do this though, because it's such a common operation (and doing it with threading is a bunch of ugly boilerplate code)

**Comment by astronouth7303** [comment]
If you can think of a good, pythonic way of doing it, feel free to discuss it. Find us on [gitter](https://gitter.im/xonsh/xonsh).

**Comment by adqm** [comment]
> You can't currently background an alias

Is that true?

In the old days, you used to be able to do that (wrap the loop in an alias, call it backgrounded).  Proc Proxies have never been job controllable, but they used to be backgroundable.  Does the following not work?

```
$ import time
$ def _dummy(a, s=None):
.     time.sleep(2)
.     print('hey')
.     
. 
$ @(_dummy) &
$ # typing something
$ 
$ hey
```

**Comment by kahrkunne** [comment]
@adqm 

That does not work, sadly. (In fact, it was one of the first things I tried )

**Comment by adqm** [comment]
:(

Okay, must have been one of the things that got lost in the recent refactor.

**Comment by astronouth7303** [comment]
@adqm I tried on 0.4.7.

**Comment by laerus** [comment]
jobs and backgrounding does seems to work in general. why did we close this issue?

**Comment by scopatz** [comment]
Hello all, aliases are threadable / backgroundable by default.  The alias has to be explicitly marked as unthreadable in order to be run on the calling thread. This is separate from backgrounding and job control, which there have been some reports of not working.

**Comment by scopatz** [comment]
And I recall backgrounding being broken before the refactor. The refactor was suppossed to make it easier to reason about why these things were broken, because it was too coupled before.

**Comment by scopatz** [comment]
This works in modern versions
