### ISSUE TITLE
vox creates bin/python that can't see dyn lib; via Homebrew on macOS

### ISSUE THREAD

**Issue by dansanderson** [xonsh/xonsh#1962]
I installed xonsh on a new Mac (macOS 10.12.1 Sierra) via Homebrew. This puts xonsh's python binary (`sys.executable`) at `/usr/local/Cellar/xonsh/0.4.7_1/libexec/bin/python3.5`. This binary relies on dynamically loading a library stored at a path relative to the executable: `../.Python`, which in turn is a symlink to `/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/Python`, which Homebrew installed as a dependency of xonsh.

When I create a new virtual environment using vox, it appears to copy the 12,988 byte binary to `~/.virtualenvs/myenv/bin/python3`. However, this breaks the relative reference to `.Python`, and using the virtual environment results in this error:

```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/dan/.virtualenvs/myenv/bin/python3
  Reason: image not found
```

Homebrew installed Python 3.5 as a dependency of xonsh, and it put a 13,620 byte binary at this path (symlinked by a couple of steps to `/usr/local/bin/python3`): `/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/bin/python3` In xonsh, sys.executable is xonsh's own libexec version. I don't know the relationship between these small binaries so I don't know what ought to be happening here, but I thought I'd mention it.

It's possible I had an installation issue specific to my machine. I originally had Python 3.5 installed by the official CPython installer. `brew doctor` advised me against this and I uninstalled it without incident. `/usr/local/bin/python3` points to the Homebrew version. As far as I can tell this is not related to the issue.

**Comment by dansanderson** [comment]
A workaround is to symlink .Python into the virtual env's root directory:

```
ln -s /usr/local/Cellar/xonsh/0.4.7_1/libexec/.Python ~/.virtualenv/myenv/.Python
```

This has to be done for each virtual env.

**Comment by santagada** [comment]
so I have brew installed python and pip installed xonsh and it works perfectly with vox. I think the problem is probably the homebrew package for xonsh. Can you try removing it and installing xonsh with pip3? if that works fine with vox then this ticket should be filled on the homebrew formula.

**Comment by astronouth7303** [comment]
vox leaves the hardwork of actually creating the virtual environment to the [`venv`](https://docs.python.org/3/library/venv.html) module. This is either a bug in Python or a bug in homebrew.

**Comment by scopatz** [comment]
Thanks for reporting @dansanderson

**Comment by dansanderson** [comment]
I can confirm that this is specific to the Homebrew installation, though I don't know where the fix belongs. I'll resolve this for now. Thanks!

**Comment by scopatz** [comment]
If there is a fix or workaround that we can implement, please let us know. Happy to accept a PR for this.
