### ISSUE TITLE
CPU usage when idle if using bottom toolbar

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1963]
I noticed that when using bottom toolbar even when idle I see a 10% processor usage from xonsh. It might be a but with prompt_toolkit or with our implementation of bottom toolbar.

**Comment by mitnk** [comment]
version 0.4.7 did introduced some CPU usage issue, which have been fixed in latest master. If you are not using master, you can try it out to see if it fixes your issue.

**Comment by santagada** [comment]
I was on master and still saw it, but just updated and I don't see it anymore, thanks!
