### ISSUE TITLE
directory completion wrong when completing on user home abbreviation (~) eg: ~/.xonshrc

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1964]
when completing: "vim ~/.xon" on any directory and press tab I get:
"vim ~/.xon/Users/santagada/.xonsh"
which is obviously wrong. If there anything else to help debug this I would.

**Comment by mitnk** [comment]
Which version of xonsh are you using?
I tried master for both readline & PTK, both have no issue to complete `vim ~/.xon`

**Comment by santagada** [comment]
master, ptk.

**Comment by santagada** [comment]
```
xonfig
+------------------+----------------------+
| xonsh            | 0.4.7.dev559         |
| Git SHA          | 02e1938              |
| Commit Date      | Nov 18 21:44:46 2016 |
| Python           | 3.5.2                |
| PLY              | 3.7                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.9                |
| shell type       | prompt_toolkit       |
| pygments         | 2.1.3                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by mitnk** [comment]
Weird, I cannot reproduce your case. Completion works for both Mac and Linux.

**Comment by santagada** [comment]
Nailed it to $BASH_COMPLETIONS, if I set it to $BASH_COMPLETIONS = [] then it appears to work.

**Comment by santagada** [comment]
I need bash_completions for the git branch completion which is pretty nice, but that's the only one I care about.

**Comment by mitnk** [comment]
> I set it to $BASH_COMPLETIONS = [] then it appears to work
Nice that you found where this issue from. (Though I still cannot reproduce it with default `$BASH_COMPLETIONS`, it's `['/usr/local/share/bash-completion/bash_completion', '/usr/local/etc/bash_completion']` on my side).

For git completion you can hack it easily, (that's why we use xonsh, right?), see [my version here](https://github.com/mitnk/dotfiles/blob/master/xonsh/xonshrc#L83) :)

**Comment by santagada** [comment]
@mitnk can you submit those for inclusion in xonsh? or at least create a xontrib for them? I would use them now.

**Comment by scopatz** [comment]
Maybe we need to do a user/path expansion before calling bash completions....

**Comment by santagada** [comment]
@scopatz I think we need to compress it back when we get the response, because I think the /Users/santagada is somehow not matching with the ˜/ dir.

But more importantly than that, can I give a much lower priority to bash completions? I really don't need directory completion from bash as the one from xonsh is supposed to be better.

**Comment by scopatz** [comment]
> But more importantly than that, can I give a much lower priority to bash completions?

I think so, if you go through the completions API. http://xon.sh/tutorial_completers.html#registering-a-completer

**Comment by mitnk** [comment]
@santagada I could, I will clean it up and put it as a xontrib :)

**Comment by santagada** [comment]
Unfortunately if I move bash to last then it never triggers because the path completion triggers before it. for now what I did was this workaround:
$BASH_COMPLETIONS = ['/usr/local/etc/bash_completion.d/git-completion.bash']

I think the proper fix would be a way to block path completions for bash, as we supposedly have a better system for it. Another possible fix is correctly interpreting ~

**Comment by scopatz** [comment]
I am all for correctly interpreting `~`.  It seems like your work around turns off all completions expect git.

**Comment by moigagoo** [comment]
I've applied @santagada 's workaround for now since git completions is what I really care about. Does the trick for now.

However, is there a way to enable all bash completions *except* for path completions? That would be perfect, since I'm very much happy with xonsh's path completions/

**Comment by scopatz** [comment]
@moigagoo That is an interesting idea. I am not sure that you can since the bash completions themselves specify the path expansions.  Though looking at it, direxpand might do part of what you want: https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html

We could certainly make these kind of thing optional behaviour as determined by an envvar.  A PR would be most welcome!

**Comment by melund** [comment]
I don't see this behaviour anymore. @santagada Is this also solved for you on master?

**Comment by santagada** [comment]
not anymore.
