### ISSUE TITLE
Stability - psql session freeze 

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1974]
I seemed encountered psql session got freeze after opening psql for some time. Encounter twice. Should be easy to reproduce. Will test more.

**Comment by santagada** [comment]
Let's find and fix it, but just so you know there is pgcli which is a prompt-toolkit version of psql which I found to be awesome (been using it with redshift not pg but should work with both).

**Comment by scopatz** [comment]
@mitnk maybe this needs to be added to unthreadable list...

**Comment by scopatz** [comment]
See #1985

**Comment by mitnk** [comment]
Thanks!!

@santagada pgcli seems great! will try it out!
