### ISSUE TITLE
"native" $XONSH_COLOR_STYLE broken in urxvt

### ISSUE THREAD

**Issue by kahrkunne** [xonsh/xonsh#1976]
Best explained in an image:
http://imgur.com/8uy1sM5

Top is a urxvt instance ($TERM is rxvt-unicode) running xonsh, showing that my $XONSH_COLOR_STYLE is 'native'. Bottom is another instance of urxvt running htop (only top is shown) to illustrate what my color scheme is supposed to look like (it's composed of all kinds of different blue hues, there is no red in it).

Issue exists on urxvt, but not on xterm or st.

Output of xonfig:

```
+------------------+----------------------+
| xonsh            | 0.4.7.dev607         |
| Git SHA          | de9e168              |
| Commit Date      | Nov 24 23:46:44 2016 |
| Python           | 3.5.1                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.9                |
| shell type       | prompt_toolkit       |
| pygments         | 2.1.3                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Gentoo Base System   |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```

**Comment by santagada** [comment]
2 things:
1) you can drag+drop images here them they are visible inline (and no need for imgur)
2) can you run xonfig colors and paste a screenshot here?

**Comment by scopatz** [comment]
@kahrkunne, thanks for reporting. My first hunch is to blame this on pygments not having a release for a very long time.  Does changing $TERM to `xterm-color` fix it?

**Comment by scopatz** [comment]
Or `xterm-256color`?

**Comment by scopatz** [comment]
A new version of pygments has been released.  Please feel free to reopen if you continue to experience this issue.
