### ISSUE TITLE
Add styling info to documentation

### ISSUE THREAD

**Issue by anddam** [xonsh/xonsh#1981]
I was looking info about how to change the color theme in xonsh.
Searching for "style" in 0.4.7 documentation on website yields only "Developer's Guide" with coding style info and "Windows Guide" that has windows specific color style enhancement, other than API references.
The only info about how to change styling I found is in [this Gil Forsyth's message](https://groups.google.com/d/msg/xonsh/X1ews8K01ZU/1D1f75zJAgAJ) on the group.

Please add a "Styling" section to "Configuration & Setup" in docs.

**Comment by anddam** [comment]
It's (shortly) described here, I still suggest to highlight styling info more.

**Comment by laerus** [comment]
More docs are always nice, a PR on this would be awesome!

**Comment by scopatz** [comment]
More docs are always welcome!

**Comment by astronouth7303** [comment]
Sounds like we need a tutorial specifically on customizing xonsh? Probably including color samples.

**Comment by scopatz** [comment]
Almost certainly.

**Comment by scopatz** [comment]
closing for #2315
