### ISSUE TITLE
Stuck terminal in master

### ISSUE THREAD

**Issue by anddam** [xonsh/xonsh#1982]
Latest master, I specifically tried de9e1686353ec1d7a76e76e2c43185406de88e73, introduced some quirks with terminal so that child processes seems to not be able to take control under certain conditions.

In shell I use to have shorthands functions to quickly jump into remote hosts, attaching to remote sessions when no arguments are provided.
In xonsh this translated in having structures like the following one into .xonshrc:

```python
def _myhost(args, stdin=None):

    if args:
        ![ssh myhost @(args)]
    else:
        ![ssh myhost -t 'tmux attach']


aliases['myhost'] = _myhost
```

This works as expected in 0.4.7 but on master this results in:

```
me@host ~ $ myhost

me@host ~ [None]$
xonsh: there is an unfinished job
-----
[1]+ stopped: ssh myhost -t tmux attach (72991)
-----
Type "exit" or press "ctrl-d" again to force quit.
```

where at line 2 of output the terminal was stuck with no output, I hit ctrl-C to kill the current process, then ctrl-D to exit the shell and then the process that was meant to be killed is a stopped job instead.

Starting any other process at this point results in another stuck process.
For example running 'vim foo' blocks the process early, before the vim's swap file is created. Again hitting ctrl-C results in this vim process being stopped.

On a fresh new shell instance vim works as expected and even a direct "ssh myhost -t 'tmux attach'" will, that is running the command directly rather than going through a callable alias that uses uncaptured subprocess ![] .

Can anyone reproduce the behavior?
What additional information can I provide in order to track this down?

**Comment by scopatz** [comment]
Can you try decorating with `@unthreadable` or `@unbackgroundable`? See https://github.com/xonsh/xonsh/blob/master/docs/tutorial.rst#unthreadable-aliases These aliases might need these decorators to conform to the new execution model.

**Comment by anddam** [comment]
Confirmed that uncapturable decorator did the trick.

**Comment by anddam** [comment]
Just as a note using only unthreadable decorator will correctly display the ssh session but leave a stray process when the calling terminal is closed. With both decorators the behavior is the expected one, on closing of the calling terminal the remote session is detached and local ssh process dies.

**Comment by scopatz** [comment]
Thanks @anddam, I think the docs that I linked above try to lead folks in that direction.  If you think it could be more clear or needs a note or something, please feel free to open a PR. My original docs weren't clear enough it seems :)
