### ISSUE TITLE
Provide a demo with dply to test xonsh without installing it on your own machine

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1984]
https://dply.co/ provides free 2 hour servers that can be initalised with a script: https://dply.co/help/cloud-init

I created one and the demo button is:
html:
`<a href="https://dply.co/b/UVPpAJqc"><img src="https://dply.co/b.svg"/></a>`
markdown:
`[][![Dply](https://dply.co/b.svg)](https://dply.co/b/UVPpAJqc)`
direct link:
https://dply.co/b/UVPpAJqc

it uses ubuntu 16.04 with this script:

```
#!/bin/sh
export DEBIAN_FRONTEND=noninteractive;
apt-get update;
apt-get -y upgrade;
apt-get -y install python3-pip;
pip3 install xonsh[ptk,linux];
usermod -s $(which xonsh) root;
```

**Comment by scopatz** [comment]
Thanks @santagada! Is there a way that you would like this integrated or put into the docs? PRs welcome!

**Comment by scopatz** [comment]
This website seems to no longer be in existence,
