### ISSUE TITLE
PTK Completion Issue

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1994]
```
$ mkdir foo
$ touch foo/main.rs
```

Completion issue
```
$ ls f<TAB>  # Will be 'ls foo/'
$ ls foo/<TAB>  # let hit <TAB> again
```
then we expected it to be `ls foo/main.rs`, but it is `ls foo/` with a popup menu showing `rs`.

You can replace `foo/main.rs` with `foo/bar/`, completion would be `foo/` with a popup with an empty thing shows instead of `foo/bar/`

**Comment by gforsyth** [comment]
Hey @mitnk -- thanks for reporting!  
I can confirm this, but note that the _completion_ is still correct (if you select the `rs` option it fills in `main.rs`) but the display is incorrect.  

I thought we had all of these issues fixed, but obviously not.

**Comment by laerus** [comment]
do we have any tests for completions? i can't find any.

**Comment by mitnk** [comment]
If there is only one item in completion, popup should not show up, should extend path directly ;)

**Comment by mitnk** [comment]
@gforsyth we fixed all known issues for readline completion. nowadays I'm trying out PTK ...

The PTK completion works file for `ls foo/<TAB>`, but not for `ls f<TAB><TAB>`. The later will show a popup, which should not.

@jonathanslenders could you help here to see if this is prompt-toolkit issue itself, or a issue of using it? Thanks :)

**Comment by scopatz** [comment]
Potential fix in #2275

**Comment by melund** [comment]
Fixes it for me. Awesome.

**Comment by mitnk** [comment]
Thanks @scopatz @melund
