### ISSUE TITLE
Wrong events tutorial link

### ISSUE THREAD

**Issue by tgoodlet** [xonsh/xonsh#1996]
The advanced events page (http://xon.sh/advanced_events.html) links to http://xon.sh/tutorial_events.rst when I'm pretty sure it should link to http://xon.sh/tutorial_events.html.

**Comment by astronouth7303** [comment]
Sloppy of me.

@scopatz Do we want to expedite this to the live site?

**Comment by scopatz** [comment]
I think it can wait until we get the release out. Can you put in a PR, please?

**Comment by astronouth7303** [comment]
Oh, I just fixed it directly, since it was a 4-character change. Was that not the right thing?

**Comment by scopatz** [comment]
That is totally fine! I'd rather nothing got in the way of documentation ;)

**Comment by tgoodlet** [comment]
Looks good :)
