### ISSUE TITLE
exit status color

### ISSUE THREAD

**Issue by hayd** [xonsh/xonsh#1997]
I like to have the following setup:

![screen shot 2016-12-06 at 1 15 55 am](https://cloud.githubusercontent.com/assets/1931852/20919665/d664fdd6-bb51-11e6-896a-cabd2053db5b.png)

It would be neat to expose a {status_color} similar to {branch_color} to allow this setup.

**Comment by melund** [comment]
Hi @hayd 

You can easily create something like this yourself: 

![image](https://cloud.githubusercontent.com/assets/1038978/20922705/58556cd4-bba9-11e6-95a8-29e6f9aac0c9.png)

Just add those lines to your xonsh run-control file in your home directory (`.xonshrc`)

**Comment by melund** [comment]
maybe also append a line to remove reference to `_status_color` so it doesn't pollute your namespace,
`del _status_color`

**Comment by melund** [comment]
Ok. I realize that this can be done even simpler. So here is a one-liner that does the same: 
```
$PROMPT_FIELDS['prompt_end'] = lambda : '{RED}$' if __xonsh_history__.rtns[-1] else '{GREEN}$'
```

**Comment by astronouth7303** [comment]
xontrib `prompt_ret_code` adds a `{ret_code_color}` formatting field (as well as `{ret_code}`).

**Comment by gforsyth** [comment]
This seems sorted, yeah?  I'm going to close this out, but reopen if you feel something hasn't been addressed.  Thanks!
