### ISSUE TITLE
Support PEP 519

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2001]
[PEP 519](https://www.python.org/dev/peps/pep-0519/) adds the `__fspath__()` special method (with the accompanying `PathLike` ABC and some utility functions) and will be available with 3.6 (now rc).

The following areas should be adjusted to accept `PathLike` objects:

* [x] `@()` substitution
* [x] Env vars that take paths
* [x] Vox

(Feel free to add to this list if I've forgotten something.)

**Comment by astronouth7303** [comment]
My personal rationale: Using `pathlib` in my own Python work, I've found it much, _much_ more concise than `os.path` and generally easier to read and use.

In general, enabling xonsh to support them through out (eg #1862) will be useful. `Path` objects have really fantastic utility methods and bring together a lot of code from other places in the standard library: `.match()`, `.glob()`, `.read_{bytes,text}()`, and others. 

Given that a large chunk of a shell's job is working with files and file names, anything we can do to make this easier for users will be helpful.

**Comment by laerus** [comment]
+1

**Comment by scopatz** [comment]
I am for any changes folks want to make in this direction.

**Comment by melund** [comment]
So am I. I haven't used the Path objects yet, but I will certainly try.

**Comment by scopatz** [comment]
These have been implemeted!
