### ISSUE TITLE
Locale issue with vox

### ISSUE THREAD

**Issue by anddam** [xonsh/xonsh#2007]
On Macos 10.12 (Sierra) with xonsh 0.4.7 from Macports trying to create a new environment yields

    subprocess.CalledProcessError: Command '['/Users/anddam/.virtualenvs/test/bin/python3.5', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1 

My LANG env variable is untouched by my xonsh config file, 'locale' command prints it as empty but echoing or evaluating it in xonsh returns 'C.UTF-8' that is valid on Macos but not widely recognized by programs.

    $ locale
    LANG=
    LC_COLLATE="C"
    LC_CTYPE="C"
    LC_MESSAGES="C"
    LC_MONETARY="C"
    LC_NUMERIC="C"
    LC_TIME="C"
    LC_ALL=
    $ echo $LANG
    C.UTF-8
    $ $LANG
    'C.UTF-8'

Manually setting LANG variable to 'C', a sane default value, allows me to manually run the failing subprocess command, that is

    /Users/anddam/.virtualenvs/test/bin/python3.5 -Im ensurepip --upgrade --default-pip

but vox alias still fails with the aforementioned subprocess.CalledProcessError exception.

I tried to print out os.environ at different levels of the traceback stack and found that very early, at the alias decorator in xonsh/__amalgam__.py,  the subprocess call loses the calling shell environment, I'm not sure if this is intentional or not.

I couldn't see any of my configured shell environment variables, not even PWD, using:

    --- __amalgam__.py.orig	2016-12-11 10:22:19.000000000 +0100
    +++ __amalgam__.py	2016-12-11 10:21:47.000000000 +0100
    @@ -9601,6 +9601,9 @@
         @functools.wraps(f)
         def wrapped_simple_command(args, stdin, stdout, stderr):
             try:
    +            print("OS.ENVIRON")
    +            for key, value in os.environ.items():
    +                print("  %r: %r" % (key, value))
                 i = stdin.read()
                 if bgable:
                     with redirect_stdout(stdout), redirect_stderr(stderr):

and then creating a test environment with:

    vox new test

So in my case while I can set LANG in my xonsh runcontrol file to a proper value like 'C' or 'en_GB.UTF-8', this setting doesn't reach the vox alias and the setup of the venv fails.

A manually spawned subprocess, e.g. calling a new xonsh process, correctly inherits all the environment.

    $ echo $FOO
    $FOO
    $ $FOO = 'bar'
    $ echo $FOO
    bar
    $ xonsh
    $ echo $FOO
    bar
    $

Should this be worked internally to xonsh by making the environment propagate, or on the user config side?

**Comment by gforsyth** [comment]
Hi @anddam -- thanks for reporting!  I expect that this issue will persist, but could you confirm the same behavior on master?  We've made some sweeping changes since 0.4.7.

**Comment by anddam** [comment]
Nevermind, it was my $VI_MODE set True. I'm sorry for the noise.

**Comment by gforsyth** [comment]
Hi @anddam -- I think this is more of an issue with how OSX handles (or fails to handle) locale stuff. 

Could you try adding these lines to a `~/.profile` file and then start a new session and see if the error persists?

```console
export LC_ALL=en_GB.UTF-8  
export LANG=en_GB.UTF-8
```
and obviously change those values as you see fit.

**Comment by anddam** [comment]
Using setting env variables in ~/.profile and starting a new session doesn't change the behavior.

**Comment by astronouth7303** [comment]
Note that `vox` hands off to the standard `venv` module to do the hard work of creating the virtual environment.

`os.environ` may or may not contain the "environment" variables. See [`$UPDATE_OS_ENVIRON`](http://xon.sh/envvars.html#update-os-environ). (Defaults to false.)

**Comment by astronouth7303** [comment]
Hm. It should.

I see the bug now: because `venv` is doing its own thing outside of the xonsh execution flow, it's not picking up on the xonsh environment.

Normally, this is not a problem because the most essential things are set externally to xonsh. But if they're set in eg `.xonshrc`, then they won't get passed on by `venv`. The `venv` API doesn't give us a way to pass this in, so properly fixing it is non-trivial.

**Comment by melund** [comment]
> The venv API doesn't give us a way to pass this in, so properly fixing it is non-trivial.

Well. That is what UPDATE_OS_ENVIRON is for. Maybe you can enable it temporarily while launching venv

**Comment by astronouth7303** [comment]
@melund `$UPDATE_OS_ENVIRON` doesn't currently work that way, and I'm assuming we have it default to False for a reason.

**Comment by oca159** [comment]
any updates about this issue? i am still seeing the subprocess.CalledProcessError exception

**Comment by scopatz** [comment]
@oca159 - I don't think that there have been any updates, but we are happy to take any PRs to fix it!

**Comment by anki-code** [comment]
Hi @anddam @oca159! Could you please give a repeatable example to reproduce this issue?

**Comment by anddam** [comment]
> Hi @anddam @oca159! Could you please give a repeatable example to reproduce this issue?

I honestly cannot, sorry. I changed shell, OS and locale since 2016.
