### ISSUE TITLE
random various piping issues

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2009]
these pipelines have some unexpected behaviors,
for example Ctrl-C doesn't work:

```
$ ls -l /usr/bin | grep 'sh' | less
$ ls -l /usr/bin | sort | more

```

(more info incoming)

**Comment by gforsyth** [comment]
I can confirm that `more` has issues on my machine with this example -- keypresses don't seem to get through.  I don't have any issues with `less`, however...

**Comment by gforsyth** [comment]
Ok, I can also confirm `less` issues.

```console
$ ls -l /usr/bin | sort | less
```

gives a blank window, `Ctrl-C` just prints `:skipping...:`

**Comment by adqm** [comment]
FWIW, I think `more` has always been an issue, but the `less` one is probably a result of the more recent changes.  I'm running a modified 0.3.4 that has the `more` issue, but not the `less` one.

**Comment by scopatz** [comment]
#2017 seems to fix these bugs for me now.
