### ISSUE TITLE
Infinite Syntax Error loop

### ISSUE THREAD

**Issue by rtpg** [xonsh/xonsh#2010]
Got a weird `Syntax Errror` loop going on when trying to do some import timing research.

At first I thought this was a weird `__future__` bug but it happens with other libs too
```
>>> def time_import(pkg):
...     return $(timeit python -c "import '@(pkg)'")
...

>>> time_import('__future__')
  File "<string>", line 1
    import
         ^
SyntaxError: invalid syntax
  File "<string>", line 1
    import
SyntaxError: invalid syntax
  File "<string>", line 1
    import
SyntaxError: invalid syntax
  File "<string>", line 1
    import
SyntaxError: invalid syntax
  File "<string>", line 1
    import
SyntaxError: invalid syntax
  File "<string>", line 1
    import
[ repeated]
```

**Comment by rtpg** [comment]
I just noticed in a related test that this is using a `xonsh-timeit` builtin, so the issue might be from there

```
>>> timeit python -c "print('Yo')"
[snip]
SyntaxError: <xonsh-timeit>:6:18: ('code: print',)
        python -c print('Yo')
```

**Comment by gforsyth** [comment]
Thanks for raising this @rtpg.  
`timeit` operates the same way (more or less) as the `%timeit` magic in IPython, but it is xonsh-compatible, however, you need to operate in Python mode.

```console
$ timeit "print('yo')"
[snip]
10000 loops, best of 3: 11.7 µs per loop
```

It _sort of_ works for import timings, but not really

```console
$ timeit "import numpy"
The slowest run took 281554.64 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 343 ns per loop
```
That 343 ns result is bogus -- `timeit` works in its own namespace and so after it's imported `numpy` once, it's just the overhead to check the import. That slowest run is the more accurate measure:

```console
$ 281554.64*343*10**-9
0.09657324152000002
```

so about 10 ms, give or take.  

You can instead use `time` and do this:

```console
$ def time_import(pkg):
..     time python -c @("import {}".format(pkg))
..
```  
```console
$  time_import('numpy')
0.16user 0.00system 0:00.17elapsed 98%CPU (0avgtext+0avgdata 29844maxresident)k
0inputs+0outputs (0major+4444minor)pagefaults 0swaps
$  time_import('__future__')
0.05user 0.00system 0:00.05elapsed 98%CPU (0avgtext+0avgdata 8636maxresident)k
0inputs+0outputs (0major+1156minor)pagefaults 0swaps
```

**Comment by rtpg** [comment]
Ah I see, thanks for the explanation. I totally mixed up `time` and `timeit`. I ended up writing a variant of what you set up to get some times that were more or less accurate for my use case.

**Comment by scopatz** [comment]
Also note that if you don't want to quote things, you can also use subprocess macros, 

```console
$ timeit! import numpy
```

Read more here: http://xon.sh/tutorial_macros.html#subprocess-macros

**Comment by gforsyth** [comment]
I'm closing this.  Please reopen if you have further concerns.  Thanks!
