### ISSUE TITLE
Multi-line history handling?

### ISSUE THREAD

**Issue by wrouesnel** [xonsh/xonsh#2011]
Is there a way to get a block of inline Python from the history, rather then each line separately?

i.e. in iPython-qt pressing the up key scrolls back through logical multi-line blocks, whereas this is not the case in xonsh. This is something of a major time-killer, since a mistyped block means a lot of retyping.

**Comment by gforsyth** [comment]
Hey @wrouesnel -- this is the default behavior if you are using the `prompt_toolkit` backend.  If you install `prompt_toolkit` using `conda` or `pip`, then `xonsh` should use that automatically.

**Comment by wrouesnel** [comment]
Works perfectly, though I don't recall seeing it on the setup page (it's a pretty important feature if you're being python-ish).

**Comment by gforsyth** [comment]
It's listed on the various install pages but we could make the feature distinction a little more visible.  Feel free to put in a PR for the doc update!

**Comment by scopatz** [comment]
Also, feel free to close this issue!
