### ISSUE TITLE
Tilde expands inside quotes

### ISSUE THREAD

**Issue by dsnellgrove** [xonsh/xonsh#2013]
What I expected:
```
$ ls '~'
ls: ~: No such file or directory
```

What actually happens:
```
$ ls '~'
contents of home are listed
```

This breaks various commands when trying to pass a tilde to them as part of a quoted parameter, for example when running `$ vagrant ssh -c '~/thing'` tilde is replaced with the host user's home directory (an invalid path in the guest VM) instead of being passed to the guest for interpretation.

**Comment by astronouth7303** [comment]
Try

```
$ ls `~`
```

For more info, see http://xon.sh/tutorial.html#advanced-path-search-with-backticks

**Comment by melund** [comment]
I am not sure that was the question. The point is when xonsh does ~ substitution. You can't disable substitution with quotes. In xonsh you can always quote stuff. That is the xonsh equivalent to escaping stuff in bash.

 Let's say you wanted to list the content of `~/my folder with spaces` that is possible in xonsh using quotes 

`ls '~/my folder with spaces'`

@scopatz or @gforsyth may remember the rules for substitution. I haven't thought about the issue with SSH commands but I think it has been discussed before.

**Comment by gforsyth** [comment]
There's probably a simple-ish fix for this, but it's evading me at the moment.  

We do call [`expand_path`](https://github.com/xonsh/xonsh/blob/master/xonsh/built_ins.py#L85) on just about everything.  That's actually run inside the parser whenever it encounters a string literal. 

`expand_path` itself calls `os.path.expanduser` and that ignores tildes that follow `=` or `:` but the vagrant syntax isn't covered by that.

**Comment by scopatz** [comment]
Hi All, I think the right thing to do for literal strings is either to use a subprocess macro or to wrap a python-mode string.

```console
scopatz@andromache ~ $ echo "~"
/home/scopatz
scopatz@andromache ~ $ echo! ~
~
scopatz@andromache ~ $ echo @("~")
~
```

So here we would use, ` vagrant ssh -c ! ~/thing` or ` vagrant ssh -c @('~/thing')`.  

Also note that we do have a flag for turning on/off env vars in string literals, with `$EXPAND_ENV_VARS` See [here](http://xon.sh/envvars.html#expand-env-vars).  Maybe we should have something similar for path expansion.  Even still, I think the explicit raw strings would be easier in this case.

**Comment by laerus** [comment]
#1432 
This needs some documenting in tutorial on the [quoting](https://github.com/xonsh/xonsh/blob/master/docs/tutorial.rst#quoting) section.

**Comment by scopatz** [comment]
Much agreed!

**Comment by dsnellgrove** [comment]
When the documentation stated "Single or double quotes can be used to remove the special meaning of certain characters or words to xonsh" it surprised me to find that tildes fall on the "stays special" side of the fence, whereas in bash quotes remove their special meaning.

**Comment by laerus** [comment]
The documentation about quoting/escaping in xonsh is a work in progress as we figure things out. Xonsh is not bash and will deviate in many things. The rules of quoting in bash are a little too special to easily remember, for example double quotes don't escape the same characters as single quotes. 

(maybe we can make use of python raw strings for preventing all expansions)

**Comment by mitnk** [comment]
> Xonsh is not bash and will deviate in many things.
When we say `Xonsh is a BASHwards-looking shell`, how much it is like bash, or how much it's not? If the quote rules are different, then I'd say it is different in a significant way.

Back to the `'~'` thing, I found `~` will not expending when there is any char before it, like `echo ' ~'`, or `ssh host 'ls ~'`.

**Comment by gforsyth** [comment]
Proposal: `xonsh` is no longer "BASHwards looking".

"Python-powered, cross-platform, UNIX-gazing shell"?

**Comment by scopatz** [comment]
> (maybe we can make use of python raw strings for preventing all expansions)

@laerus this is a good idea, but we should probably have a different character other than `r` to denote this. We shouldn't have the same prefix mean different things in different contexts.  PRs definitely welcome :)

**Comment by scopatz** [comment]
will be covered in #2315
