### ISSUE TITLE
Docker `rmi` fails when images listed by subprocess

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#2021]
In bash, `docker rmi $(docker images -q)` successfully enumerates image hashes, and removes them.

In xonsh, the same apparently valid command returns:
> Error response from daemon: 404 page not found

However, running `docker images -q` and then manually `docker rmi abc def ...` works as expected, and also confirms that the former is a `\n` separated list as expected.

**Comment by hugo-aa** [comment]
In xonsh, the counterpart is `docker rmi @$(docker images -q)`

**Comment by hugo-aa** [comment]
And maybe xonsh could do some optimization here so that `docker rmi $(docker images -q)` could do the same thing.

**Comment by OJFord** [comment]
@hugo-aa Huh, thanks, haven't come across that one. 

What's the `@` changing? When I just echoed `$()` it seemed good to go.

**Comment by melund** [comment]
Look at the following and you may see the problem: 

```
snail@sea ~ $ img = $(docker images -q)
snail@sea ~ $ img
'8b7112257895\n9e4f13a0901e\ne647c90a4beb\n00ba08a766d3\n'
```
I don't think docker accepts that kind of input. What you need to do is split the input on new-lines. You need to be in pyhton mode to do that, so the actual command would look like this: 

```
snail@sea ~ $ docker rmi @([i.strip() for i in $(docker images -q).split()])
```

It is pretty annoying to write that for such a common use-case, hence, the `@$()` shorthand.  See here: http://xon.sh/tutorial.html#command-substitution-with

**Comment by OJFord** [comment]
I think I see, thank you @melund. Slightly unfortunate, but it sounds like `@$` is always right for this then (docker is the only place plain `$` has gone wrong) so I'll just get used to it. 

So would `img = $(printf @$(docker images -q))` reveal that the `@$` construct has removed the trailing newline?

**Comment by gforsyth** [comment]
> And maybe xonsh could do some optimization here so that docker rmi $(docker images -q) could do the same thing.

I think this might be a bit _too_ context aware regarding parsing. If we start special casing individual programs in the parser I think it will quickly get completely out of control.

**Comment by OJFord** [comment]
@gforsyth It's the trailing newline that's the problem, right?

How about a rule that just rewrites `{shell cmd} $({shell cmd})` -> `{shell cmd @$({shell cmd})` - isn't it always desired?

**Comment by astronouth7303** [comment]
Except for when you add flags afterwards and are surprised when it stops working.

**Comment by gforsyth** [comment]
I suspect there will be a huge number of edge cases where that assumption doesn't hold.

**Comment by OJFord** [comment]
There's also a (presumably related) problem running `docker rm @$(docker ps -q)`. It reveals a docker daemon error, despite it working fine for:
```xonsh
for id in @$(docker ps -q).splitlines():
    docker rm @(id)
```

I don't expect this is cleanly fixable in xonsh - it must be some quirk of the change of environment and what docker expects - but I thought it would be at least worth documenting in this issue as another docker problem and how to avoid it.

I'll close this issue now, since xonsh is behaving as intended.

**Comment by OJFord** [comment]
Actually there's definitely a more general issue - or something I don't understand - here.

Doesn't work:
```xonsh
pacaur -Rns @$(pacaur -Qqtd)
```

Works:
```xonsh
for pkg in $(pacaur -Qqtd).splitlines():
    pacaur -Rns @(pkg)
```

**Comment by astronouth7303** [comment]
```
🐚 python -c "import sys; print(sys.argv)"                                                                                                                     ['-c']
🐚 python -c "import sys; print(sys.argv)" @$(echo spam eggs foo bar)                                                                                          ['-c', 'spam', 'eggs', 'foo', 'bar']
🐚 python -c "import sys; print(sys.argv)" $(echo spam eggs foo bar)                                                                                                         ['-c', 'spam eggs foo bar\n']
```

That looks like expected behavior?
