### ISSUE TITLE
On Windows, some environment variable names change case

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#2024]
I use xonsh on Windows (0.4.7)

Specifically, I open a command prompt, and then run xonsh explicitly under it.

I noticed some (but not all) environment variables that existed in mixed case show up as upper case once in Xonsh.

As an example,

in Windows prompt:

FrameworkDIR64 

Once in Xonsh, this becomes

FRAMEWORKDIR64

This is causing a few things to break on our side.

Not sure why this happens. Can I control this? Also not sure why it doesn't happen on all variables.

Thanks.

**Comment by scopatz** [comment]
Thanks for reporting @beetleb. I am not a Windows person, but this sounds like a windows environment thing.  Does the same thing happy in Python, when you look at the environment there? Maybe @melund @BYK or @astronouth7303 have more experience in this area?

**Comment by astronouth7303** [comment]
CPython does this to `os.environ`. For xonsh to circumvent this would be.... troublesome.

**Comment by beetleb** [comment]
Hmm... Looking around more, I find this:

http://stackoverflow.com/questions/7797269/python-environment-case-senstivity-os-environ

And a ticket in Python for it:

https://bugs.python.org/issue28824

According to the first link: On Windows, although the OS preserves the case, apparently it is case insensitive. So I can create an environment variable called "abc", but if I set ABC, it will update the one in "abc".

So Windows environments should not have more the same environment variable in multiple cases.

However, Xonsh does allow this. If I go into xonsh, abc becomes ABC due to os.environ. But then I can create a new environment variable called "abc" and I'll have both.

For my needs, this duplicate is the issue (the case probably doesn't matter). Here are the steps:

1. Xonsh inherits an environment variable (let's call it abc), and converts to upper case ($ABC). 

2. Then as part of some build script we have (probably a batch file somewhere), it tries to update abc. 

3. Since in Xonsh, $abc does not exist, instead of updating $ABC, it creates a new environment variable called $abc. 

4. Later on in the build script, some tool is storing all the environment variables, and apparently quits if it finds duplicate environment variables. I really don't know the internals of that tool, but the error message from that tool complains about the key already existing, and points to that environment variable.

Do you see the problem?

The "proper" solution is not obvious, but I can sympathize with the comments to the question on the StackOverflow page. Somehow Xonsh should not allow the same environment variable to show up more than once in multiple cases in Windows, as it can easily break things in Windows. I do not know if Xonsh has any "say" when a .bat file is called, though.

Ideas?

Thanks.

**Comment by astronouth7303** [comment]
Hm. I suspect this has extra-interesting ramifications if `$UPDATE_OS_ENVIRON` is set.

@scopatz As I see it, there's a few solutions to this:

1. Case-fold all `$` var names to uppercase unconditionally
2. Do what the underlying platform does

I think 1 makes for a more consistent (and therefore better) language, but on Unix could prevent some variables from being accessible. (In practice, I don't think I've ever seen a lower-case environment variable.)

**Comment by beetleb** [comment]
I'm not sure I fully understand the proposals, but my 2 cents:

1. We should not prevent case sensitive variables on Linux.

2. On Windows only, is there a way to intercept attempts to set an environment variable (be it through a .bat file or the command line), and just "reroute" it to the existing environment variable?

I think the solution has to be a Windows-only solution, and not impact Linux - just as Python itself has separate behavior on Windows and Linux regarding environment variables. This will make xonsh not be "truly" cross platform. However, as one commenter mentioned (I believe on the SO page): Trying to be cross platform in everything means creating a system that has the worst of all worlds. Had Python itself tried to be truly cross platform on this issue, it would mean less capability on Linux.

If we go with option 2, I guarantee eventually someone will open a ticket complaining how something on Linux is broken because some system relied on having case sensitive environment variables.

**Comment by scopatz** [comment]
Hello All, if you look at the Python issue that @beetleb linked, there are two things I found interesting.

1. This will be fixed in Python 3.6 or 3.7 
2. `nt.environ` actually has the correct casing.

So I think the solution is to have an alias in xonsh.platform that dispatches either to os.environ or nt.environ.  We'd then need to change all of the os.environ references everywhere to use our alias.

If anyone, especially a windows dev, would be willing to put in a PR to this effect, that would be great!

**Comment by scopatz** [comment]
Potential fix in #2276

**Comment by melund** [comment]
Merged #2276
