### ISSUE TITLE
$BASH_COMPLETIONS Does not Support directories 

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2030]
In #1888 @blahgeek fixed a delay issue in #1824, and made $BASH_COMPLETIONS do not support dirs anymore.

The original idea of $BASH_COMPLETIONS I think is that if I have this:
```
$ ls /usr/local/etc/bash_completion.d
aria2c                     cargo                      tmux
brew                       task.sh                    youtube-dl.bash-completion
```
And I set `$BASH_COMPLETIONS = ['/usr/local/etc/bash_completion.d']`, then I'll get all apps (brew, aria2c, etc) completion work.

Now I have to put all full paths of these scripts.

If we do want to make them to be files for speed (like #1824 mentioned), we may need to update the docstring of `$BASH_COMPLETIONS` to make it clear.

Any thoughts here?

**Comment by scopatz** [comment]
Yeah, I am not entirely sure about the logic of quitting after the first successful completer is found. Maybe @blahgeek @melund or @astronouth7303 remember.

**Comment by astronouth7303** [comment]
I never messed with completions, sorry.

**Comment by scopatz** [comment]
Sorry about the noise @astronouth7303. 

@mitnk I think what the code it doing now is wrong but I am still not sure what it was fixed like that. I probably need to reread it all.

I think there are two issues here: 1) We should probably at least try to load all of the completions files listed in BASH_COMPLETIONS, and 2) We should decide if we should load directories.

**Comment by blahgeek** [comment]
Hi @scopatz @mitnk Sorry for the delay, I've been busy at work for quite some time and missed all these notifications... Let me explain.

So the basic idea of the new bash completion is to take advantage of bash-completion's lazy loading to improve performance, which is available from bash-completion 2.x.

The single `bash_completion` script would (lazy) load all the completion files for you (in /etc/bash_completion.d and some other dirs). In that case, xonsh should not load all those scripts, just that single script is enough.

The document of BASH_COMPLETIONS also explains this (https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py#L363)

But if this is not working for you, I would recommend:

- check BASH_COMPLETIONS variable, set to the path of `bash_completion` script, for me it's `/usr/share/bash-completion/bash_completion`
- try it in bash: check the completion after `source /usr/share/bash-completion/bash_completion`

**Comment by mitnk** [comment]
> The single bash_completion script would (lazy) load all the completion files 
> for you (in /etc/bash_completion.d and some other dirs). In that case, 
> xonsh should not load all those scripts, just that single script is enough.

Ah, now I understand that PR :) and that make sense. Thanks.

But 1) how does this single script (bash-completion/bash_completion) determine which dirs to scan and load? Any URL refer to its usage / functionality?   2) on Mac there isn't such a single bash_completion file. Then the original dirs-scan-implementation make a lot of sense for the situation I describe in the first thread of this issue.

PS. Info checked on my Mac:

```
$ sudo find /etc -name '*bash*completion*'
$ # no results

$ sudo find /usr -type d -name '*bash*completion*'
# all dirs
/usr/local/Cellar/aria2/1.25.0/etc/bash_completion.d
/usr/local/Cellar/aria2/1.25.0/share/doc/aria2/bash_completion
/usr/local/Cellar/glib/2.48.1/share/bash-completion
/usr/local/Cellar/task/2.5.1/etc/bash_completion.d
/usr/local/Cellar/tmux/2.3_1/etc/bash_completion.d
/usr/local/Cellar/youtube-dl/2016.07.09.2/etc/bash_completion.d
/usr/local/etc/bash_completion.d

$ sudo find /usr -type f -name '*bash*completion*'
# files
/usr/local/Cellar/youtube-dl/2016.07.09.2/etc/bash_completion.d/youtube-dl.bash-completion
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bash-completion.rb
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions/bash-completion2.rb
/usr/share/zsh/5.0.8/functions/_bash_completions
```

**Comment by blahgeek** [comment]
Try installing bash-completion2 from homebrew?

Explain:

There's two kinds of bash completion scripts actually: 1. Those come with their own package, like aria2, they are stored in /etc/bash_completion.d, and 2. Those come with bash-completion2 package, stored in /usr/share/bash_completion2/..., which are for some general purpose completions like ls, rm, etc. 

bash-completion2 package also comes with a "main entry" script called bash_completion to load all these scripts, including those in /etc/bash_completion.d. 

So in order to use bash completion, installing bash-completion2 is a must.

**Comment by scopatz** [comment]
should we change the default value on Mac then to accommodate this?

**Comment by scopatz** [comment]
@blahgeek maybe we should update the docs, which state that v2 is only recommended?  Or maybe we can detect this somehow and issue a warning?

**Comment by bestlem** [comment]
And how do you do this without homebrew? and with odd files not in the same directory as bash_completion 
The docs  and actual code only list directories which are not on standard OSX ['/usr/local/share/bash-completion/bash_completion',
 '/usr/local/etc/bash_completion']

Also not macOS bash is only 3.2 which if bash_completion  comes from here https://github.com/scop/bash-completion is a problem. The actual bash_completion.sh via macports that gives that address does nothing for bash < 4.1 and for > 4.1 it sources every file in the directory

**Comment by scopatz** [comment]
Hi @bestlem - I think you can manually install bash completions too, depending on your platform.

**Comment by bestlem** [comment]
Ok got it partially working. I use macports. They supply a bash_completions.sh that sources bash_completions from two directories - this does not seem to work

However if I put one of these bash_completions at the front of $BASH_COMPLETIONS it works.

**Comment by scopatz** [comment]
Interesting. Would you mind writing up something for our Mac OSX guide? http://xon.sh/osx.html#extras-for-osx 

That would be awesome!

**Comment by scopatz** [comment]
This was completed
