### ISSUE TITLE
pty-related issues in a chroot

### ISSUE THREAD

**Issue by chronitis** [xonsh/xonsh#2031]
While trying to update the packaging for xonsh 0.4.7 -> 0.5.0, I encountered an apparent regression in the test suite; a number of tests which previously passed now fail with `OSError('out of pty devices')`. These tests pass when run in a normal terminal but fail when run in a build chroot (debian sbuild).

This does not appear to be due to a change in the toolchain; I can still rebuild the 0.4.7 package without any test errors.

This causes errors in `test_xonsh.xsh` (only `test_xonsh_party`) and `test_integrations.py`:

 * `test_script case7` ("test piping 'real' command")
 * `test_script case8` ("test double piping 'real' command")
 * `test_single_command` (all)
 * `test_redirect_out_to_file` (all)

It would appear this occurs wherever a capturing subprocess is used.

I assume this derives somehow from the changes in `xonsh/built_ins.py:_update_last_spec`, but I haven't worked out exactly what.

```
_________________________ xonsh test: test_xonsh_party _________________________
xonsh execution failed
  File "/tmp/autopkgtest.s042CA/autopkgtest_tmp/tests/test_xonsh.xsh", line 15, in test_xonsh_party
    out = $(echo @(x + '-' + y)).strip()
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 16114, in subproc_captured_stdout
    return run_subproc(cmds, captured='stdout')
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 16066, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 16041, in cmds_to_specs
    _update_last_spec(specs[-1])
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 16007, in _update_last_spec
    r, w = pty.openpty() if use_tty else os.pipe()
  File "/usr/lib/python3.5/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.5/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
```

```
______________________________ test_script[case7] ______________________________

case = ('\nwith open(\'tttt\', \'w\') as fp:\n    fp.write("Wow mom!\\n")\n\n![cat tttt | wc]\n', ' 1  2 9 <stdin>\n', 0)

    @pytest.mark.parametrize('case', ALL_PLATFORMS)
    def test_script(case):
        script, exp_out, exp_rtn = case
        out, err, rtn = run_xonsh(script)
>       assert exp_out == out
E       assert ' 1  2 9 <stdin>\n' == 'Traceback (most re...ut of pty devices\n'
E         -  1  2 9 <stdin>
E         + Traceback (most recent call last):
E         +   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
E         +     "__main__", mod_spec)
E         +   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
E         +     exec(code, run_globals)
E         +   File "/usr/lib/python3/dist-packages/xonsh/__main__.py", line 2, in <module>
E         +     main()
E         +   File "/usr/lib/python3/dist-packages/xonsh/main.py", line 300, in main
E         Detailed information truncated (25 more lines), use "-vv" to show

tests/test_integrations.py:156: AssertionError
```

**Comment by chronitis** [comment]
I think this is probably due to incorrect permissions on the pty device in the chroot, since the tests succeed when run as root.

I don't know whether nonetheless it is worth looking into whether there is a way to gracefully degrade in the circumstances that `openpty()` will fail or this should just be considered an unsupported configuration - I'm afraid I'm at the edge of my knowledge of unix plumbing for whether this is something likely to be encountered in practice.

**Comment by scopatz** [comment]
Thanks so much for reporting @chronitis! I think it is extremely unlikely that this will arrive in a real-world circumstance.  I think that this is a by-product of the limited execution environment of the package tester.  

We will happily skip these tests. Is there any way (environment variable, etc) that we can tell we are in a debian sbuild environment?  Sorry, that is reaching the ends of my knowledge :)

**Comment by chronitis** [comment]
This appears to be a bug with the test environment rather than xonsh (debian #817236), so I don't think any workarounds are needed. I'll add a temporary workaround on my end until it is dealt with.

**Comment by scopatz** [comment]
Ahh Ok excellent. Well, let us know if you need anything else.
