### ISSUE TITLE
Enhancements to bashims

### ISSUE THREAD

**Issue by mandarvaze** [xonsh/xonsh#2041]
Refer to [this comment](https://github.com/xonsh/xonsh/issues/1632#issuecomment-243276638)

I also thing that ``!$`` and substitutions like the following should be available

    $ cd /tpm
    cd: no such file or directory: /tpm
    $ ^tpm^tmp^

I would vote for ``!$`` as first priority and substitutions as second priority.

**Comment by scopatz** [comment]
Thanks for opening this @mandarvaze! Pull requests for these are most welcome!
