### ISSUE TITLE
tty attrs change when executing a command which catch the tty and the prediction fails

### ISSUE THREAD

**Issue by jb-leger** [xonsh/xonsh#2049]
Hi everybody,

I have a bug which blocks my usage, when I use a program which use the tty directly, _e.g._ `git commit -p` which call `vim` at the end. For the first commit it's works fine, for the second, when I need to enter something I have troubles.

```
jben@germinale ~/falsegit master $ git commit -p
[...git stuff with vim...]
jben@germinale ~/falsegit master $ git commit -p
diff --git a/truc b/truc
[...a diff...]
Stage this hunk [y,n,q,a,d,/,e,?]? y^M^M^M^M^M^M^M^M^M
```

In fact, when I look the source code, some command are handled differently, in `xonsh/built-ins.py`:
```python
def _update_last_spec(last):
[...]
    if callable_alias:
        pass
    else:
        thable = builtins.__xonsh_commands_cache__.predict_threadable(last.args)
        if captured and thable:
            last.cls = PopenThread
        elif not thable:
            # foreground processes should use Popen and not pipe stdout, stderr
            last.threadable = False
            return
    [...]
```

We see that we try to predict if a command is threadable, this is done in `xonsh/commands_cache.py` with predictor, from a default value:

```python
def default_threadable_predictors():
    """Generates a new defaultdict for known threadable predictors.
    The default is to predict true.
    """
    # alphabetical, for what it is worth.
    predictors = {
        'bash': predict_shell,
        'csh': predict_shell,
        'clear': predict_false,
         [...]
```

This explain that we do not have this behavior with some commands, but with other.

But, I do _not_ think adding `git` here is a good idea, and I have a lot of home made script which call vim or which use directly the tty, so I investigate to found what's happening.

As far as I understand, when the prediction is incorrect, and a catching tty program is launch when `xonsh` did not predict that, the program change directly the attributes of the tty, as you can see:

```
jben@germinale ~/falsegit master $ import sys,termios
jben@germinale ~/falsegit master $ termios.tcgetattr(sys.stdin.fileno())[0:-1]
[17664, 5, 191, 35387, 15, 15]
jben@germinale ~/falsegit master $ git commit -p
[...git stuff with vim...]
jben@germinale ~/falsegit master $ termios.tcgetattr(sys.stdin.fileno())[0:-1]
[17408, 1, 191, 2602, 15, 15]
```

So I think, to cover the case of incorrect predictions, each time a command is finished, `xonsh` should be check the pty attributes have not changed, and in this case set it again to the right value.

If I do so, it works well.

```
jben@germinale ~/falsegit master $ import sys,termios
jben@germinale ~/falsegit master $ attrs = termios.tcgetattr(sys.stdin.fileno())
jben@germinale ~/falsegit master $ git commit -p
[...git stuff with vim...]
jben@germinale ~/falsegit master $ termios.tcsetattr(sys.stdin.fileno(),termios.TCSADRAIN,attrs)
jben@germinale ~/falsegit master $ git commit -p
[...it works well now...]
```

I do not know where to do that stuff nicely in the architecture of `xonsh`. For me I use only a dirty quick fix with notification in my prompt, in my `.xonshrc` I added:

```python
$STDIN_ATTRS = termios.tcgetattr(sys.stdin.fileno())
def dirty_quick_fix():
    new_attrs = termios.tcgetattr(sys.stdin.fileno())
    if new_attrs[0:-1] == $STDIN_ATTRS[0:-1]:
        return None
    termios.tcsetattr(sys.stdin.fileno(),termios.TCSADRAIN,$STDIN_ATTRS)
    return "[dirty quick fix applied]"
$PROMPT_FIELDS['dirty_quick_fix'] = dirty_quick_fix
$PROMPT = $PROMPT.replace('{prompt_end}','{BOLD_RED}{dirty_quick_fix:{} }{prompt_end}')
```

And now, I can use my `xonsh` without this bug:
```
jben@germinale ~/falsegit master $ grep bonjour /tmp/truc #command which do not catch tty
jben@germinale ~/falsegit master $ #ok all is good, nothing done
jben@germinale ~/falsegit master $ git commit -p
[...git stuff with vim...]
jben@germinale ~/falsegit master [dirty quick fix applied] $ #tty attrs were restored
```

I hope this stuff helps you to fix this bug.

**Comment by scopatz** [comment]
Thanks for all of the sleuthing here @jb-leger. I think that the places in the code, architecture wise, to look at implementing this are in:

* SubprocSpec in `xonsh.built_ins`
* The PopenThread, ProcProxy, and ProcProxyThread classes in `xonsh.proc`
* CommandPipeline in `xonsh.proc`

Basically, the SubprocSpec class uniquely determines how a suprocess should be run.  You'll probably only be concerned with modifying the last spec in a pipeline, which has some special semantics. The actually, running of a command is done by the Popen and ProcProxy (for function aliases) classes. PopenThread is probably the trouble maker here and where I would start.  The CommandPipeline is then responsible for tying together many commands into a pipeline. If you need to execute code after a pipeline has finished, this would be the place to do it.

**Comment by scopatz** [comment]
@jb-leger, can we close this out given your recent addition?

**Comment by jb-leger** [comment]
The issue is still present when the predictor fails. But now, most of the time, the predictor do the job. I am preparing a PR for this case, we do not need to keep this issue open, we will continue the discussion in the PR.

**Comment by melund** [comment]
Cool. Closing then...
