### ISSUE TITLE
CompletedCommand class still mentioned in tutorial despite having been replaced

### ISSUE THREAD

**Issue by das-g** [xonsh/xonsh#2052]
`CompletedCommand` [has been removed in Xonsh 0.5.0](http://xon.sh/previous/changelog.html#v0-5-0) but is [still being mentioned in the tutorial](https://github.com/xonsh/xonsh/blob/0.5.0/docs/tutorial.rst#captured-subprocess-with--and-).

**Comment by gforsyth** [comment]
Thanks for reporting @das-g.  PRs fixing this are welcome!
