### ISSUE TITLE
Colored man pages?

### ISSUE THREAD

**Issue by tgoodlet** [xonsh/xonsh#2055]
I tried a few different things at this point but can't seem to get colored man pages working as described [here](https://wiki.archlinux.org/index.php/Color_output_in_console#man) using ANSI escape codes.

I've of course tried stripping out the preceding `$` but still no luck...
What's the special sauce I need to cook with up with xonsh?

**Comment by astronouth7303** [comment]
What code are you using?

**Comment by tgoodlet** [comment]
@astronouth7303 This is what I got but no idea if it's what you'd expect:

```xonsh
# Coloured man page support                                                
# using 'less' env vars (format is '\E[<brightness>;<colour>m')            
$LESS_TERMCAP_mb = "\e[01;31m"     # begin blinking                        
$LESS_TERMCAP_md = "\e[01;31m"     # begin bold                            
$LESS_TERMCAP_me = "\e[0m"         # end mode                              
$LESS_TERMCAP_so = "\e[01;44;36m"  # begin standout-mode (bottom of screen)
$LESS_TERMCAP_se = "\e[0m"         # end standout-mode                     
$LESS_TERMCAP_us = "\e[00;36m"     # begin underline                       
$LESS_TERMCAP_ue = "\e[0m"         # end underline                         
```

**Comment by astronouth7303** [comment]
`\e` isn't a Python string escape character. You want `\033` or `\x1b`.

**Comment by scopatz** [comment]
Or you might be able to use `\\e`

**Comment by tgoodlet** [comment]
@astronouth7303 thanks this worked!

```sh
# Coloured man page support                                                  
# using 'less' env vars (format is '\E[<brightness>;<colour>m')              
$LESS_TERMCAP_mb = "\033[01;31m"     # begin blinking                        
$LESS_TERMCAP_md = "\033[01;31m"     # begin bold                            
$LESS_TERMCAP_me = "\033[0m"         # end mode                              
$LESS_TERMCAP_so = "\033[01;44;36m"  # begin standout-mode (bottom of screen)
$LESS_TERMCAP_se = "\033[0m"         # end standout-mode                     
$LESS_TERMCAP_us = "\033[00;36m"     # begin underline                       
$LESS_TERMCAP_ue = "\033[0m"         # end underline                         

```

How do you guys feel about me PR-ing this into the docs?

**Comment by scopatz** [comment]
I am always +1 on more docs :)

**Comment by astronouth7303** [comment]
I had a suspicion, and just opened up xonsh and typed `"\e"` and got `"\\e"` back. Look up what bash thinks `\e` should be.

**Comment by tgoodlet** [comment]
@scopatz where do you suggest sticking it?
[envvars](http://xon.sh/envvars.html)? 
[customization](http://xon.sh/customization.html)?

**Comment by scopatz** [comment]
Yeah maybe customization. It isn't an envvar that we manage in any way, so I don't think that is the right place for it.
