### ISSUE TITLE
Artefacts in ncurses applications

### ISSUE THREAD

**Issue by xsteadfastx** [xonsh/xonsh#2056]
i just came back from the holidays and updated some tools i use in a daily bases. for example my beloved xonsh. i started weechat and it throws so many artefacts that its not usable. they come up everytime i move from channel to channel.  i made a screenshot. 

![xonshartefact](https://cloud.githubusercontent.com/assets/168397/21640870/5cc947c8-d278-11e6-9658-269cc5e0fc90.png)

i tried it with bash and dash and weechat runs just fine. any ideas?

**Comment by gforsyth** [comment]
hey @xsteadfastx -- sorry about that! fix incoming.

**Comment by gforsyth** [comment]
see #2057

**Comment by scopatz** [comment]
Also @jb-leger may have a general fix for this class of problems in #2061. I am hopeful!

**Comment by xsteadfastx** [comment]
this sounds good. i hope it gets merged soon.

**Comment by scopatz** [comment]
@xsteadfastx @gforsyth's fix should now be in 0.5.2 for you

**Comment by xsteadfastx** [comment]
@scopatz this looks great. no artefacts right now <3

**Comment by scopatz** [comment]
Awesome!
