### ISSUE TITLE
tqdm-based CLI completely breaks

### ISSUE THREAD

**Issue by cryzed** [xonsh/xonsh#2058]
```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.5.1.dev35         |
| Git SHA          | 8f3c8b0d            |
| Commit Date      | Jan 3 19:57:11 2017 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.9               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | True                |
| distro           | arch                |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

Even with an adjusted `$XONSH_PROC_FREQUENCY` of 5e-4 or lower, subsequent alternating writes to stdout and stderr break proper formatting (using `tqdm.write`). Starting the same application in bash works. Also the console size doesn't seem to be recognized properly by tqdm, causing the animated progressbar to either disappear entirely or be way too small.

A small example script:
```python
import time
from tqdm import tqdm


def main():
    with tqdm(list(range(100)), 'Processing...') as progress:
        for step in progress:
            time.sleep(0.1)
            if progress.n % 10 == 0:
                tqdm.write('I did something!')


if __name__ == '__main__':
    main()
```

Looks like [this](http://i.imgur.com/Q2VjO20.png) for me, while it should actually look like [this](http://i.imgur.com/WaRSg1g.png) (executed using bash, the progressbar has the correct width, is even adjustable by resizing the terminal's width when using `ncols=True` in tqdm, and things written to stdout using `tqdm.write` appear "above" without breaking the layout).

I suspect it's again a problem with the features that allows saving the stdout output of ran commands; while that sounds neat it unfortunately seems to create more problems than it solves. The same issues exist in the release version; is there a way to maybe disable this feature and restore the old behavior?

**Comment by scopatz** [comment]
That is tqdm should really set `file=None` and then only grab sys.stderr as needed. It should mimic the behaviour of `print(s, file=None)`

**Comment by scopatz** [comment]
In fact, there is already an open issue for this at tqdm/tqdm#275. Maybe we could get by with a monkey patch for the time being?

**Comment by cryzed** [comment]
That was quick, thank you. I was about to open a bug report when I saw your first post. Thanks for taking care of it. Should this stay open until it is fixed in tqdm?

**Comment by scopatz** [comment]
Yeah, I think this should stay open until tqdm is fixed or we have a fix.  The monkey patch would be super simple since all it would do is replace the keyword arg. But, in essence, I agree that an upstream fix would be much better.

**Comment by cryzed** [comment]
Then by all means, a monkey patch would be great -- although I must admit that I am confused as to where it would actually take place for it to work in every scenario.

**Comment by scopatz** [comment]
Well, we'd probably make a new xontrib that import tqdm and then modifies the main class. If this happens on xonsh load, then it would affect all future imports. Not sure if it would work if you were using tqdm in a scrip though.

**Comment by lrq3000** [comment]
Hey there, I'm one of tqdm's devs, thanks for reporting the issue.

Indeed, tqdm requires `\r` to work for base functionalities, but for `tqdm.write()` you also need support for moving the character up: `\x1b[A`, so you might want to check this is also supported by xonsh.

However yes for redirection, the PR https://github.com/tqdm/tqdm/pull/293 should fix some issues, but also https://github.com/tqdm/tqdm/pull/331 to automatically do `flush()` as required. These two PRs should be merged in soon (in the next few weeks).

**Comment by scopatz** [comment]
Thanks for letting us know, @lrq3000! By the way, xonsh effectively just implements a tee. So we do write back out to `sys.__stderr__`. So it *should* just work once your fixes are in.

**Comment by casperdcl** [comment]
well that was a fun way to see how many people are using `pyup-bot` and `tqdm`... Hopefully our latest fixes help!

**Comment by scopatz** [comment]
Thanks @casperdcl, I think this is good to close now. Feel free to reopen if the issue persists!

**Comment by DBerke** [comment]
```
+------------------+-----------------+
| xonsh            | 0.9.13          |
| Python           | 3.7.3           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
~ $ conda list | grep tqdm   
tqdm                       4.32.1
```
I'm seeing this issue so thought I'd report it, but given that I also have an unresolved case of `xonsh` not picking up my git-completer scripts on the same laptop I'm now leaning toward this particular Mac just being hopelessly messed up somehow.

**Comment by DBerke** [comment]
So, completely by accident I discovered a solution to this issue which I'll share for anyone encountering it: wrapping a script call (which otherwise has issues with `tqdm` breaking visually) in `$[...]` causes `tqdm` to work perfectly.
