### ISSUE TITLE
Autodetect ncurse and program which use directly tty

### ISSUE THREAD

**Issue by jb-leger** [xonsh/xonsh#2061]
Hi,

There is a predictor dict used to predict if a command will be runnable in background (i.e. do not use the tty), by manually adding commands. Command have to be manually added as view in #2056, with associated PR #2057.

I had some problems with other commands which use tty, and I wonder why we do not try to detect ncurses / tty usage automatically?

I wrote that, in https://github.com/jb-leger/xonsh/tree/background_preditor_from_bin, it seems to work fine on POSIX systems.

Is it useful?

**Comment by scopatz** [comment]
Hi @jb-leger - that would be extraordinarily useful! Could you put in a PR so that we can talk about it there, please? Thanks so much!

**Comment by jb-leger** [comment]
Associated PR merged. I close this issue.
