### ISSUE TITLE
ls | more does not work on mac

### ISSUE THREAD

**Issue by afetek** [xonsh/xonsh#2064]
xonsh version: 0.5.2
python version 3.6.0

*****************************************************************************************************************************
```
>>> ls | more
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 17380, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 1964, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16159, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16127, in run_subproc
    command.end()
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 11116, in end
    for _ in self.tee_stdout():
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 11041, in tee_stdout
    for line in self.iterraw():
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10940, in iterraw
    wait_for_active_job()
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 3694, in wait_for_active_job
    _continue(active_task)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 3607, in _continue
    _send_signal(job, signal.SIGCONT)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 3542, in _send_signal
    os.kill(pid, signal)
ProcessLookupError: [Errno 3] No such process
```
*****************************************************************************************************************************

Also, I created a alias function ls-more on python version 3.5... now that does not work either.

def _lsmore(args, stdin):                                                                                                           
    ls -lt @(args) >> .ls_more                                                                                                      
    more .ls_more                                                                                                                   
    rm .ls_more   

aliases['ls-more'] = _lsmore

**Comment by scopatz** [comment]
Thanks for reporting @afetek.  Would you be willing to try out #2065 to see if that fixes your problem.

**Comment by afetek** [comment]
Yes I can try it. Should I just pull the code?

**Comment by afetek** [comment]
cloned the repo and checkout sigmac branch and ran 
python3 setup.py install
Seemed to install correctly in site-packages.
So the "ls | more" does not error out any more but hangs and the job does not cleanup after
I CONTOL-C

[origin/sigmac][Jan 05, 2017 19:18:44]~/p/xonsh
 >>> ls | more
CHANGELOG.rst
CONTRIBUTING.rst
MANIFEST.in
Makefile
README.rst
__pycache__
amalgamate.py
appveyor.yml
build
circle.yml
codecov.yml
conftest.py
docs
empty
github_deploy_key.enc
license
logo.txt
news
release.xsh
requirements-docs.txt
requirements-tests.txt
scripts
setup.cfg
setup.py
tests
travis.yml
xonsh
xonsh-in-docker.py
xonsh.egg-info
xontrib
xontribs.json

[origin/sigmac][Jan 05, 2017 19:19:48]~/p/xonsh
 >>> jobs
[1]+ stopped: ls | more (68170)
[origin/sigmac][Jan 05, 2017 19:19:55]~/p/xonsh
 >>>

**Comment by mitnk** [comment]
I can confirm with @afetek on this issue, and also `ls | more` with stuck with #2065 fixes.

**Comment by mitnk** [comment]
On master `ls | more`, `ls | less`, `ls | view -` have issues. Replace `ls` with `ps ax` works ok.
```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.5.2.dev3044       |
| Git SHA          | 9949e2c             |
| Commit Date      | Jan 6 08:16:26 2017 |
| Python           | 3.6.0               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.9               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by scopatz** [comment]
Ok now that is really weird.  From xonsh's point of view, ls and ps should be the same. Do you have any aliases for either of these?  I think there is a default alias for ls which enables color. If you run ls directly without this option does it still hang when piped through less?

**Comment by mitnk** [comment]
removed the ls alias, still raises exception.
```
$ which ls
/bin/ls
$ which ps
/bin/ps
```
Will check into it later on.

**Comment by afetek** [comment]
I have had this problem for a while, a work around before python 3.6 was creating the following alias functions in .xonsrc

```
def _lsmore(args, stdin):
    ls -lt @(args) >> .ls_more
    more .ls_more
    rm .ls_more
def _lsless(args, stdin):                                                                                                           
    ls -lt @(args) >> .ls-less                                                                                                      
    less .ls-less                                                                                                                   
    rm .ls-less                                                                                                                     

aliases['ls-more'] = _lsmore
aliases['ls-less'] = _lsless
```

Withe the patch you gave me handling, this now works better again with python 3.6

**Comment by scopatz** [comment]
Hmm this is not good. You should definitely be able pipe to less without filesystem redirects. I don't have access to a mac to test/develop this though. Hopefully @mitnk or other mac devs can take a look soon. Happy to help however I can

**Comment by scopatz** [comment]
Now that #2177 has been merged, is this closable?

**Comment by scopatz** [comment]
Please feel free to reopen if needed.
