### ISSUE TITLE
Inconsistencies in subprocess operators

### ISSUE THREAD

**Issue by chronitis** [xonsh/xonsh#2075]
These are probably related to #2044 (the point at which streams are closed). The result of a `!()` call appears to be a non-finalised object, the semantics of which change if I subsequently call `end()` (or access a property which implicitly does so). This distinction doesn't appear in the docs, and I'm assuming is not intended.

Output is empty by default, and the process reports as incomplete, and has no end timestamp (but we do have a returncode):
```
>>> x = !(echo hello)
>>> x.output
''
>>> x.returncode
0
>>> x.ended
False
>>> x.timestamps
[1234, None]
```

But populated after `end()` is called (or by access a property which calls end)
```
>>> x = !(echo hello)
>>> x.end()
>>> x.output
'hello\n'
```

But not if we access `output` first (since the first access sets `self._output`)
```
>>> x = !(echo hello)
>>> x.output
''
>>> x.end()
>>> x.output
''
```

Before `end()` is called we can access the stdout buffer, but not afterwards
```
>>> x = !(echo hello)
>>> x.stdout
<_io.BytesIO at 0xdeadbeef>
>>> x.stdout.getvalue()
b'hello\n'
>>> x.out  #calls end()
'hello\n'
>>> x.stdout.getvalue()
ValueError: I/O operation on closed file
```

The results of `![]` are also different, meaning I can't trivially interchange them in scripts:
```
>>> y = ![echo hello]
>>> y.ended
True
>>> y.output
'hello\n'
>>> y.timestamps
[1234, 1235]
>>> y.stdout
<_io.TextIOWrapper encoding='utf-8'>
>>> y.stdout.getvalue()
AttributeError
>>> y.stdout.read()
ValueError: I/O operation on closed file
```

`xonsh = 0.5.2, python = 3.5.2`

**Comment by chronitis** [comment]
Unless I call `end()` on the result of `!()`, piped commands are not terminated:

```
>>> z = !(echo hello | cat)
>>> z.ended
False
>>> ^d
xonsh: there is an unfinished job
-----
[1]+ running: echo hello | cat (1234)
-----
Type "exit" or press "ctrl-d" again to force quit.
```

Getting the repr of the object is enough to implicitly call `end()`:
```
>>> z = !(echo hello | cat)
>>> z.ended
False
>>> z
CommandPipeline(args=['cat'], ...)
>>> z.ended
True
```

(but this is not true of a single command)
```
>>> x = !(echo hello)
>>> x.ended
False
>>> x
CommandPipeline(args=['echo', 'hello'], ...)
>>> x.ended
False
```

**Comment by scopatz** [comment]
Thanks for bringing this up @chronitis. I think this is an error in the docs, actually, as the behaviour is intended.  `!(cmd)` is meant a non-blocking, iterable.  It is fundamentally different from both `![cmd]` and `$(cmd)`.  `!(cmd)` is meant to do things like, 

```python
for line in !(cmd):
    print(line.upper())
``` 

While you can iterate over lines of `![cmd]`, it will wait until the command is complete to yield the first line. Additionally, the lines will be streamed to stdout/stderr, rather than being buffered.

`$(cmd)` returns a str of the entire output.

We probably need a summary table for all of these in the docs too.

**Comment by chronitis** [comment]
Fair enough. As well as the intended use of the different subprocess operators, it would be useful to clarify which properties of `CommandPipeline` are meant as public API for use by scripts; the existence of both `out` and `output` with different semantics is confusing, and it is not clear that some properties like `returncode` cause the pipeline to be finalised while others do not.

**Comment by laerus** [comment]
Hey @chronitis! The subprocess mechanism has gone under a big refactor and we still figure things out as we go, any ideas on the matter are appreciated. 

#2052

**Comment by scopatz** [comment]
Closing to be included in manual
