### ISSUE TITLE
readline shell crash with Python 3.6 on Mac

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2078]
It seems gnureadline lib doesn't work well with Python 3.6.0, it crash the the whole python process before Python can handle exceptions.

PTK works fine with Python 3.6.0 on mac.

**Comment by scopatz** [comment]
Thanks for reporting @mitnk. Readline has some known issues on mac (where they use libedit instead). Do you have gnureadline installed?

**Comment by mitnk** [comment]
Yes installed. Xonsh do not crash with only libedit.

**Comment by mitnk** [comment]
When I first notice this issue, there wasn't any results of googling "gnurealine python3.6". Now there is one related result: [https://trac.macports.org/ticket/53176](https://trac.macports.org/ticket/53176).

It's not an issue for IPython (which mentioned in this thread), I think, is because IPython now forced required PTK and do not use readline anymore.

**Comment by scopatz** [comment]
Oh weird.  I would actually expect that gnureadline would be more stable than libedit.  Oh Well.

**Comment by mitnk** [comment]
It was, until it start crash with Python 3.6, not sure a issue of this lib itself or a integration issue.

**Comment by mitnk** [comment]
An issue has be created in upstream: https://github.com/ludwigschwardt/python-gnureadline/issues/50

**Comment by scopatz** [comment]
Great!

**Comment by harukaeru** [comment]
I encounter the same trouble in Python3.6 and Mac OS X 10.11.2.

![screenshot 2017-02-26 15 01 32](https://cloud.githubusercontent.com/assets/5797788/23337528/89f5e1e4-fc34-11e6-80ac-3e6042534c1b.png)
```C
Python(8671,0x7fff77d85000) malloc: *** error for object 0x1065d6770: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    8671 abort      xonsh
```
↑ Here is for googlability to resolve this problem someones encounter the same trouble in future.

**Comment by scopatz** [comment]
Hi @harukaeru, maybe you can ping the gnureadline issue above? More people saying that it doesn't work helps.

**Comment by ludwigschwardt** [comment]
I think this issue is fixed in the master branch of [python-gnureadline](https://github.com/ludwigschwardt/python-gnureadline). Could you confirm before I make a new release?

**Comment by mitnk** [comment]
Hi @ludwigschwardt Indeed! Installing it from master works well with Python 3.6! Thanks a lot for this!

I'll keep this issue open for a moment before `gnureadline` releasing a new version.

**Comment by ludwigschwardt** [comment]
gnureadline 6.3.8 is finally out there!

**Comment by scopatz** [comment]
Have you verified that this fixes the problem on mac @ludwigschwardt? if so, we can go ahead and close this :)

**Comment by ludwigschwardt** [comment]
I've verified it, yes, go ahead!
