### ISSUE TITLE
Running out of ptys on macOS (Python 3.6, xonsh 0.5.2)

### ISSUE THREAD

**Issue by jonathanhogg** [xonsh/xonsh#2082]
I just had all of my open `xonsh`s fail with an error about running out of ptys – attempting to execute any command in one of them would give the same error. Unfortunately, I didn't grab a traceback from any – sorry! 😳

My Mac is showing as having been up for 23 days, I generally open/close terminal windows/tabs on a regular basis.

I managed to kill all `xonsh` processes from an emergency bash shell and everything seems to be back to normal now.

Leaking ptys in the new sub-process code?

**Comment by scopatz** [comment]
Thanks for reporting @jonathanhogg. This is a fun one! It might just be that the number of ptys is really low by default on macs.  The default seems like it might be 127 on mac, whereas on linux it is 4096/

What does `sysctl -a | grep kern.tty.ptmx_max` say?  Also there are instructions for how to change it here: https://codybonney.com/increase-the-max-number-of-ptys-on-os-x-10-8-3/

**Comment by jonathanhogg** [comment]
Yeah, I'm at the default:

```shell
resistance$ sysctl -a | grep kern.tty.ptmx_max
kern.tty.ptmx_max: 127
resistance$ uname -a
Darwin resistance.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

but I've never seen this before and I've been using `xonsh` in pretty much the same way for a long time now. I'm going to keep an eye out for it happening again and try to get some more info next time.

**Comment by scopatz** [comment]
Yeah, if you could get an error message that would be great :).  I don't *think* we are leaking ptys because the code basically tries to double close all handles and we only use ptys on the last command in a pipeline.  So I guess you could hit this if you had 127 processes simultaneously running commands. It seems like we'd only leak ptys if we also leaked processes... which we shouldn't be and are much more obvious.

**Comment by jonathanhogg** [comment]
Ah. Interesting. Taking a closer look, it appears that I *am* seeing processes leaking. Every time I close a terminal window without exiting the shell first, I see that the underlying `xonsh` process is still running. They die on a `HUP` signal or if I issue a ctrl-D in the window (which then closes), but not on closing the window with the prompt active. I'm not sure what the macOS **Terminal.app** does when a window is closed.

**Comment by jonathanhogg** [comment]
Hmmm… shell dies cleanly if a sub-command is running (either a shell-mode command or some long-running Python), but fails to if at the prompt. Very curious.

**Comment by jonathanhogg** [comment]
Aha! OK, I have it: I have a callable alias defined in my `.xonshrc` that I immediately call after definition. If I remove this, then everything is fine (found by bisecting the file).

I just tried adding the `@uncapturable` modifier on the alias and that makes the problem go away.

Of course, I can't be certain that this is what led to the pty exhaustion, but it seems a strong contender.

**Comment by astronouth7303** [comment]
@jonathanhogg What was the alias, out of curiosity?

**Comment by jonathanhogg** [comment]
@astronouth7303, sure, alias is this:

```python
if os.path.exists('/usr/local/bin/usepackage'):
    @xonsh.proc.uncapturable
    def _use(args, stdin=None):
        for line in !(/usr/local/bin/usepackage -c @(args)):
            cmd, name, value = line.rstrip('\n;').split(' ', 2)
            if value.startswith('"') or value.startswith("'"):
                value = value[1:-1].replace('\\'+value[0], value[0])
            if cmd == 'setenv':
                if name.endswith('PATH'):
                    ${name} = value.split(':')
                else:
                    ${name} = value
            elif cmd == 'alias':
                aliases[name] = value
    aliases['use'] = _use
    del _use

    use normal

else:
    $PATH.extend(['/usr/local/sbin', '/usr/sbin', '/sbin'])
```

`usepackage` is a for managing environment variables that I have been using for a very long time and am still nostalgically attached to (I wrote it). This alias was a hack to make it work with `xonsh` – it normally outputs commands for bsh- or csh-like shells that one can source back into the environment, this alias just interprets the csh-like output.

**Comment by scopatz** [comment]
@jonathanhogg were the PTYs leaking if the `use` alias failed?

**Comment by jonathanhogg** [comment]
@scopatz what do you mean by "failed"? Do you mean an exception in this function or a non-zero return from one of the sub-processes it executes? I'm not sure I've seen it fail as such.

**Comment by scopatz** [comment]
Yeah that is what I meant.  OK. Good to know.

**Comment by scopatz** [comment]
Since uncapturable seems to fix this, and we can't automatically increase the pty count as it required root privileges, I am closing this. Feel free to reopen if needed or open a new issues if similar problems arise!
