### ISSUE TITLE
Install cannot find pip or apt Xonsh packages 

### ISSUE THREAD

**Issue by ns-phennessy** [xonsh/xonsh#2084]
Greetings!

I'm on a fresh crisp Ubuntu 16.04.1 LTS machine. Running a `pip search xonsh` or `apt search xonsh` returns nothing. Is there a repo I need to add to find it?

**Comment by gforsyth** [comment]
Hey @ns-phennessy -- not sure if `xonsh` will show up in `apt` or not, but it's definitely on PyPI. You should be able to just `pip install xonsh` (and also `pip install pygments prompt_toolkit` if you want the prompt_toolkit backend).

**Comment by scopatz** [comment]
Also, note that xonsh didn't hit Ubuntu until 16.10: http://packages.ubuntu.com/search?keywords=xonsh

**Comment by ns-phennessy** [comment]
Gotcha; maybe we should update the install docs with that information? 

Also sry; i misread the output from pip; it is indeed there

**Comment by scopatz** [comment]
@ns-phennessy which piece of information? Please feel free to open a PR, too!

**Comment by ns-phennessy** [comment]
Xonsh apt package being 16.10+. I think a lot of users will be on 16.04 since it's the LTS

**Comment by scopatz** [comment]
Ah yeah. A PR would be most welcome.
