### ISSUE TITLE
bpython integration.

### ISSUE THREAD

**Issue by AkhterAli** [xonsh/xonsh#2089]
Could there be a bpython like text prediction on xonsh?  This would be awesome, annoying too at times if not imported properly, but that would make the use case of xonsh much more desirable.

**Comment by astronouth7303** [comment]
Could you clarify?

**Comment by AkhterAli** [comment]
<img width="2550" alt="screen shot 2017-01-13 at 10 48 55 pm" src="https://cloud.githubusercontent.com/assets/7011993/21952137/8cf7b828-d9e2-11e6-947d-3ca8b3daf7a5.png">

I've taken a picture of it as it's not easy to explain.  If you see my cursor, I've only typed a portion of my client variable creation, which calls a method on boto3.  As I type the class, I get all of the available methods that can be used with this class and tab through them to select what I want.

I was wondering if such a feature could be possible on xonsh.

**Comment by astronouth7303** [comment]
Ah, python-mode completions.

**Comment by scopatz** [comment]
I am all for this feature! We may have another issue related to this, namely #344.  Pull requests most welcome!

**Comment by scopatz** [comment]
Please see #2175 for an implementation of this feature. Note that it is restricted to the prompt-tollkit shell for now. If someone wants to implement this in readline they are more than welcome to :)
