### ISSUE TITLE
Vox prompt variable

### ISSUE THREAD

**Issue by tgoodlet** [xonsh/xonsh#2090]
`vox` is cool and it's handy to be able to show the current venv name in the prompt like `virualenv` does.

So far I'm using this in my `$PROMPT` function:
```python
venv = __xonsh_env__.get('VIRTUAL_ENV')                                                     
venvname = '({})'.format(os.path.basename(venv)) if venv else '' 
```

Do you guys think this is worth turning into a prompt variable?

**Comment by astronouth7303** [comment]
it's `{env_name}` already, part of core.

**Comment by melund** [comment]
He he. Was just about to write the same. It is enabled in the default prompt. Btw. it also works with conda environments.

**Comment by tgoodlet** [comment]
Jeeze not sure how I missed that...
@astronouth7303 @melund maybe it's worth mentioning it on the [vox page](http://xon.sh/python_virtual_environments.html)?

**Comment by astronouth7303** [comment]
It's part of the default prompt, too.

**Comment by tgoodlet** [comment]
@astronouth7303 yeah I see that now hehe.

So what if I stick a little section in the vox page on how to make your prompt behave as it does with `virtualenv`? I figured it's useful to anyone looking especially when they've already customized their prompt (as was my case).

**Comment by astronouth7303** [comment]
Yeah, that would be cool.
