### ISSUE TITLE
Sed capture groups cannot be referenced

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#2097]
I've no idea what's actually causing this - feel free to change (or suggest if not able) the title if you have a better idea of the root cause.

If I run:
```sh
>echo 'testing' | sed -E 's/(testing)/\1/g'
```
I would expect:
```sh
testing
```
but instead I get:
```

```

Yep, nothing.
```sh
> echo 'testing' | sed -E 's/(test)ing/\1/g'
ing
```

If I drop into `bash` it works as expected.

I assume `xonsh` is consuming the `\1` and not replacing it with anything, so `sed` *actually* sees `'s/(testing)//g'` and then the behaviour is as we expect for that?

**Comment by adqm** [comment]
You're right that xonsh (Python?) is eating that `\1`.  But xonsh (like Python) has raw strings, which should be able to make sure that the `\1` actually still gets to sed:
```
$ echo 'testing' | sed -E r's/(testing)/\1/g'
```

**Comment by OJFord** [comment]
@adqm Ahah! Thank you - that beats the super-unportable `\\1` I was thinking of using. (Which would work for xonsh, but print a literal `\1` in other shells 😖 ).

**Comment by OJFord** [comment]
I suppose if it's Python doing the eating, this is unfixable?

**Comment by adqm** [comment]
> I suppose if it's Python doing the eating, this is unfixable?

I think that depends on what you mean.  The version with double quotes and double-backslash seems to work both in xonsh and in Bash (since in Bash double-quoted strings handle the backslash escape).  It's a little ugly, but it would mean that you could use the same command both in Bash and in xonsh, if that's your desired end result:

```
$ echo 'testing' | sed -E "s/(testing)/\\1/g"
```
