### ISSUE TITLE
xonsh breaks git for me (protocol error)

### ISSUE THREAD

**Issue by Droggelbecher** [xonsh/xonsh#2098]
**Environment**

The "Server" machine is a Ubuntu 14.04 (however with various packages from other releases/ppa's),
with xonsh from git like this (ill explain in a bit what server/client means here):
```
$ git log -n 1
commit 6eeac872724e2353ddeb84b5f6ffeed7c68d2996
Author: Jamie Bliss <astronouth7303@gmail.com>
Date:   Sat Jan 14 18:22:15 2017 -0500

    Re-establish `on_precommand`. (Thought I fixed this in the PR?)
$ xonsh --version
xonsh/0.5.2.dev61
```

Xonsh is set as the default shell (/usr/bin/local/xonsh set using chsh).

A recent git is installed:
```
$ git --version
git version 2.11.0
```

The following issue was observed with 2 different "client" machines, one isa macbook (git 2.11.0), the other an archlinux system (also a recent git, iirc also 2.11.x). Both observe the same issue

**The issue**

When using a "git pull" or "git push" command from one of the client machines, targeting the server machine, this error is observed:
```
Fatal: protocol error: bad line length character: 
003
fatal: The remote end hung up unexpectedly                        
```
The problem does **not** occur when I set bash as the default shell on the server machine.
Some googling turned out that something seems to meddle with the 4th byte that git transmits.
Eg. https://www.spinics.net/lists/git/msg133582.html says there is 0x01-byte expected that might be mangled somehow?

I ensured that I don't have any extra output generated that could be the cause (eg. ssh me@server echo x, just echos "x" and nothing else).

Does anyone have a clue what might be happening here?

EDIT: Formatting

**Comment by mitnk** [comment]
I can reproduce this issue, but no ideas what's the reason :)

**Comment by Droggelbecher** [comment]
Well thats already a relief, I was worried I might have something weird going on in my specific environment.

Is there (as a workaround) a way to tell git to use a different shell on the remote end when pushing/pulling so I don't have to login and change my default shell before every pull/push?

**Comment by mitnk** [comment]
I think we need to find out the reason why xonsh caused this.

But for now, here is a workaround - (creating an aliased user which use bash as the login shell on your server](https://github.com/xonsh/xonsh/issues/1525#issuecomment-237478842). And then use `user-aliased@host` as your git remote. (If you count this as a workaround :-)

**Comment by Droggelbecher** [comment]
Possibly related (can't test here right now): http://tiebing.blogspot.de/2014/06/git-windows-push-hang-100.html

**Comment by scopatz** [comment]
Hi @Droggelbecher @mitnk, this is disconcerting. I can't seem to reproduce this myself. Is there a docker container or some instructions that you can provide that might help reproduce this?

**Comment by mitnk** [comment]
@scopatz Did you host a git repo on a Linux host via a user and with xonsh set as the default shell for this user?

**Comment by scopatz** [comment]
Well, I think I did. I init'd a bare repo in my userspace (which has xonsh as the $SHELL) and then cloned that. Pushing and pulling from that seemed to work fine.

**Comment by astronouth7303** [comment]
Double check with xonsh as the login shell and git over ssh.

**Comment by scopatz** [comment]
OK, I think I understand the failure mode.  It should be reading `003f` from `git-upload-pack`. However it is instead reading `\n003`. There is an off-by-one bye error somewhere. Maybe newlines are being transmitted as `\r\n` accidentally?

**Comment by scopatz** [comment]
Actually, it seems to be a NULL byte that is being lost in transmission.

**Comment by scopatz** [comment]
Scratch that this is a newline issue. It seems that pty.openpty() is replacing `\n` with `\r\n` in the buffer. os.pipe() seems to behave correctly. Investigating why this is the case.

**Comment by scopatz** [comment]
It looks like this is a long standing issue in Python: https://mail.python.org/pipermail/python-list/2013-June/650460.html

**Comment by scopatz** [comment]
Ok, I have a potential fix in #2137.

**Comment by mitnk** [comment]
I have confirmed that that PR fixed this issue. Great job! @scopatz

**Comment by Droggelbecher** [comment]
Thanks a lot :-)

**Comment by scopatz** [comment]
Thanks!
