### ISSUE TITLE
Integrate python syntax sugar

### ISSUE THREAD

**Issue by TheJJ** [xonsh/xonsh#2105]
https://github.com/czheo/syntax_sugar_python

Might be a valuable addition to the xonsh.

**Comment by laerus** [comment]
looks a lot like http://coconut-lang.org/

**Comment by scopatz** [comment]
@TheJJ, this seems like it is just a library that works with normal Python. You should be able to just uses it in xonsh.  Have you experienced any problems with it?

@laerus I think we could integrate coconut pretty easily with context manger macros / blocks pretty easily at this point.

**Comment by moigagoo** [comment]
@scopatz 

> I think we could integrate coconut pretty easily with context manger macros / blocks pretty easily at this point.

Could you please elaborate a bit on this? How would one add coconut syntax to xonsh?

**Comment by astronouth7303** [comment]
@TheJJ Run this:

```
$ xip install syntax_sugar
```

Add this to your `~/.xonshrc`:

```python
from syntax_sugar import *
```

You can use all of it on your prompt.

**Comment by astronouth7303** [comment]
@moigagoo:

```
with! coconut():
    "hello, world!" |> print
```

**Comment by moigagoo** [comment]
@astronouth7303 `NameError: name 'coconut' is not defined`. Coconut is installed and in PATH.

**Comment by astronouth7303** [comment]
@moigagoo It's hypothetical. Nobody's done it yet. But it's very doable with [context manager macros](http://xon.sh/tutorial_macros.html#context-manager-macros).

**Comment by moigagoo** [comment]
@astronouth7303 Thanks for the link and sorry for the misunderstanding.
