### ISSUE TITLE
Move bash completion to separate repo

### ISSUE THREAD

**Issue by imomaliev** [xonsh/xonsh#2108]
I needed python interface for bash completion for my project(https://github.com/imomaliev/ptrepl), and ended up copying https://github.com/xonsh/xonsh/blob/master/xonsh/completers/bash.py to separte repo(https://github.com/imomaliev/bash-completion-python) and making it work without xonsh's environment 

I suggest to actually move this whole feature to separate repo, so other developers could use it. Or is too hardwired to existing xonsh environment to do that?

**Comment by gforsyth** [comment]
Hi @imomaliev -- it's an interesting question. It might be possible to decouple, although we do tie in to a couple of xonsh internals to make sure things work in a cross-platform way. 

Implementing something like this would help your case a lot, but if anyone can separate it cleanly, I don't think there would be a problem in hosting it in a separate repo.

**Comment by scopatz** [comment]
Hi @imomaliev - we would be in favor of carving this out.  We have done something similar with amalgamate and lazyasd.  If you are interested in working with us on this, we can make a separate repo in the xonsh org to get things started. I think that there might be another issue open that suggests the same thing and I know that other people are interested.

Help here would be most appreciated!

**Comment by gforsyth** [comment]
`xonsh/bash-xompletion`?

**Comment by scopatz** [comment]
Hahah, well, it would a generic Python bash completer interface. It might make sense to just call it `(py-?bash-completions`.  Also as a point of clarification, I think other folks were asking for the foreign shell interface to be broken out, not completions.

**Comment by gforsyth** [comment]
I think `py-bash-completions` sounds good

**Comment by imomaliev** [comment]
@scopatz 
> If you are interested in working with us on this, we can make a separate repo in the xonsh org to get things started. I think that there might be another issue open that suggests the same thing and I know that other people are interested.

Help here would be most appreciated!

I can start decoupling `bash-completion` from `xonsh` with usage of my already existing project(https://github.com/imomaliev/bash-completion-python) and when I'm done and we are satisfied with result, this project could be moved to xonsh org.

@gforsyth 
`py-bash-completions` sounds good to me too

**Comment by scopatz** [comment]
Sounds like a plan to me @imomaliev! I think we are happy to move things over sooner too, if that is preferable. Otherwise, whenever you feel it is ready.

**Comment by gforsyth** [comment]
@imomaliev 
Sounds good! See [xonsh/py-bash-completion](https://github.com/xonsh/py-bash-completion)

**Comment by scopatz** [comment]
I believe that this is closable, please feel free to reopen if needed.
