### ISSUE TITLE
Add `xip`

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2110]
Add a core alias `xip` ("kip") that will always run pip in xonsh's python environment (as opposed to the system, the current venv, or any other).

The interface is exactly the same as `pip`.

This is a problem because some tools (eg, homebrew) will install xonsh in an isolated environment, which makes installing xontribs or shell-accessible modules challenging.

The goal is to make it so that eg `xip install requests` will make the `requests` module usable from the shell context.

As a bonus: This should also try to detect if a `sudo` is necessary and automatically use it.

The alias is approximately `@(sys.executable) -m pip @(argv)`.

**Comment by astronouth7303** [comment]
(I'm really filing this so that I don't forget it. Although if someone else wants to take it, feel free.)

**Comment by scopatz** [comment]
+1 to this!
