### ISSUE TITLE
[RFC] Type Annotating Xonsh code

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2124]
(before little Xonsh turns into Cthulhu)

feelings?

**Comment by scopatz** [comment]
I am +0 on this. I don't mind having them but I do wonder what the benefit would be? Would we run tests against them? Or would we use them to provide expansions?

**Comment by astronouth7303** [comment]
Anything we can do to help automated testing. IIRC, what held it back previously was 3.4 support. Until we officially drop 3.4, we don't have `typing`.

Of course, the final 3.4 release may have come out? I always loose the link where PSF says the actual 3.4 cut-off date.

**Comment by laerus** [comment]
we can always pip-install `typing` under py3.4. I think that xonsh would benefit a lot from mypy in counterbalancing the lack of tests and overall the code quality. Seeing the amusing bugs bash used to have in the last 20 years makes me think about the future of xonsh, anything that can make my shell more robust i'll take it.

not sure what you mean about providing expansion @scopatz

I am all for dropping 3.4 support, is there any other distro apart from debian-stable that's still 3.4 ? maybe we can mark a release as last py3.4 compat and point ppl to install this.

**Comment by astronouth7303** [comment]
There's the standing policy of 0 required dependencies, though.

**Comment by scopatz** [comment]
> not sure what you mean about providing expansion @scopatz

I meant completions, sorry.

> I am all for dropping 3.4 support, is there any other distro apart from debian-stable that's still 3.4 

Yeah, I think this is the main reason we haven't dropped v3.4 yet.

**Comment by TeamSpen210** [comment]
You could also use stub files, and not include them in the source files. Then no runtime requirements are needed at all, since it's not run as code.

**Comment by laerus** [comment]
sadly stub files only work for imports not the actual files you run mypy on.

**Comment by Russell-Jones-OxPhys** [comment]
14.04LTS has 3.4, and will be around until 2019. Personally I'd like 3.4 to be supported for another six months ot so :) As there's reportedly a back-ported "typing" module, I guess this isn't enough to drop 3.4 by itself?

**Comment by scopatz** [comment]
Hopefully, to assuage you, I don't think that there are no current concrete plans to drop Python v3.4. If the distros update and/or we get to Python v3.7, it will probably be time though :)

**Comment by santagada** [comment]
about running tests, running mypy on CI is enough to guarantee that no one is breaking typing. I'm +1 as it does help with IDEs and are some form of documentation.

**Comment by laerus** [comment]
> 2017-06-17: Release of Debian 9/Stretch ! 
with py3.5
