### ISSUE TITLE
Branch not shown if 'git' is aliased to 'hub'

### ISSUE THREAD

**Issue by moigagoo** [xonsh/xonsh#2135]
I you do `brew install hub` and add `aliases['git'] = ['hub']` to ~/.xonshrc, git branches will no longer be shown in directories.

This is very strange since Hub is just a wrapper around git, and `hub branch` yields exactly the same output as `git branch`. In fact the former just invokes the latter.

**Comment by gforsyth** [comment]
Hey @moigagoo -- thanks for reporting. 

Quick question: does the same behavior occur if you set `aliases['git'] = 'hub'`?

**Comment by gforsyth** [comment]
hmmm, interesting. I can duplicate this by setting `aliases['git'] = 'git'`

**Comment by moigagoo** [comment]
Yes, the same behavior occurs with `aliases['git'] = 'hub'`.

**Comment by laerus** [comment]
the `curr_branch` function in `$PROMPT_FIELDS` that fetches the branch for the current git repo calls the git binary through python's subprocess module, same for the `gistatus` prompt field.

**Comment by moigagoo** [comment]
@laerus invoking `hub branch` with subprocess works just fine:

```python
>>> subprocess.run("git branch", shell=True)
* develop
  master
CompletedProcess(args='git branch', returncode=0)
>>> subprocess.run("hub branch", shell=True)
* develop
  master
CompletedProcess(args='hub branch', returncode=0)
```

**Comment by gforsyth** [comment]
Ok, I think I have an idea about what's going on.
Aliasing `git` to something, even itself, is throwing off something in `locate_binary`. It's not finding a binary for `git` since it's an alias and then the branch info isn't returned.

**Comment by gforsyth** [comment]
yeah, ok, in `commands_cache.py` line 165

`return path if not is_alias else None`

similar issue if you try, for instance, to do a `locate_binary('ls')`

**Comment by moigagoo** [comment]
Hello again!

It seems like the issue is back in another form. The branch is shown, but it's yellow no matter the repo state.

The problem is the same: if the `hub` alias is set, `xonsh.prompt.vc.dirty_working_directory()` returns `None`. It doesn't matter if the alias is set in .xonshrc, .zshrc, or ad-hoc with `aliases['git'] = 'hub'`.

The problem can be tracked to `__xonsh_commands_cache__.lazy_locate_binary('git')`, which returns `None` if the alias is set.

Should I reopen this issue or report a new one?

**Comment by moigagoo** [comment]
This PR should fix that https://github.com/xonsh/xonsh/pull/2424
