### ISSUE TITLE
Using xo xontrib freezes everything

### ISSUE THREAD

**Issue by airdrik** [xonsh/xonsh#2139]
Recently when I've tried using the xo xontrib from xonsh, it has started just freezing - it doesn't load anything, it just sits there on the line after the command to run xo until I hit ctrl+c to try and close out and try again/something else.  Event then hitting ctrl+c doesn't always exit the call to xo and I have to restart xonsh.

I'm not entirely sure what may have caused this, though I suspect it may be something related to upgrading xo from 0.1.11 to 0.1.13

Tested using xonsh 5.2 and 5.3, Ubuntu 14.04, python 3.4, xonsh and xo/exofrills installed using pip (for python 3.4).

I also tried unloading the xo xontrib and running the separate xo command and that works just fine.
Only other xontrib loaded is apt_tabcomplete which seems to work just fine.

**Comment by scopatz** [comment]
Thanks for reporting this @airdrik. Would you please also report it over on xo? Thanks!

**Comment by airdrik** [comment]
Done: https://github.com/scopatz/xo/issues/17
