### ISSUE TITLE
git completion on windows broken

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2140]
Git completions on windows has stopped working:
```
snail@sea ~\Documents\xonsh master $ $BASH_COMPLETIONS
['C:\\Program Files\\Git\\usr\\share\\bash-completion\\bash_completion', 
'C:\\Program Files\\Git\\mingw64\\share\\git\\completion\\git-completion.bash']
```

I guess it could be some of the recent fixes to bash completion scripts. Do we require bash completion 2.0? 

On windows we use the git bash completions that come bundled with 'Git for Windows'. I don't think that 2.0

**Comment by scopatz** [comment]
How are you getting the completions on windows? I am on conda's git and it doesn't seem to come with the completions

**Comment by scopatz** [comment]
Also! Thanks for reporting!

**Comment by melund** [comment]
'git for Windows' comes with MSys which has bash completion. Mostly for the Git bash shell, but xonsh is configured to detect if it is installed and then use it git complete script. Although now it seems to not work anymore. 

Unless anyone has some quick insights, then I will dig into this. That was one of my favorite features

**Comment by scopatz** [comment]
I think v1 is supported still, as per http://xon.sh/envvars.html#bash-completions.  This is definitely something we shouldn't leave broken.

**Comment by astronouth7303** [comment]
There was a bug report about bash completions recently and some discussion about v1 vs v2 support.

**Comment by melund** [comment]
This is a mixture of several bugs, and me having the 'Windows Subsystem for Linux (WSL)' installed. WSL bash can't be used for anything in this regard.

Bash from WSL is in `C:\Windows\system32\bash.exe` and is always picked by the subprocess even though I have the 'Git for Windows' bash first on my xonsh path. It seems like subprocess doesn't respect the environment that is passed in here: (https://github.com/xonsh/xonsh/blob/master/xonsh/completers/bash.py#L92). 

I found this (https://bugs.python.org/issue15451) that states that subprocess doesn't use the passed in `env` when searching the for the executable on Windows. It seems to do that on Linux. That was surprising to me. 

This means that we should use the `locate_binary` instead in `xonsh.platform.bash_command()` when determining if bash is on the path: https://github.com/xonsh/xonsh/blob/master/xonsh/platform.py#L289

And maybe some code to prevent us from picking up the WSL bash.exe if it is installed. 

I have a PR incoming.

**Comment by scopatz** [comment]
I feel like we have encountered this before. Thanks for finding it and putting in the PR!
