### ISSUE TITLE
xonsh fails to recognize '!' regex option for 'find' command

### ISSUE THREAD

**Issue by ferkulatius** [xonsh/xonsh#2156]
When using the `-not` option in `find`'s regex, things work as expected.
Using the alternative **`!`**, xonsh coughs up:

`$ find -type f -regextype posix-extended -not -regex '.*\.(md|txt)$' | wc -l`
vs:
`$ find -type f -regextype posix-extended ! -regex '.*\.(md|txt)$' | wc -l`

Output in xonsh 0.5.2:
![xonsh-0-5-2-bug-find-unknown-option-part-1](https://cloud.githubusercontent.com/assets/6187502/22625133/26342186-eb8e-11e6-9a4e-a17517bb4d93.png)

Output in GNU bash, Version 4.4.11(1)-release:
![xonsh-0-5-2-bug-find-unknown-option-part-2](https://cloud.githubusercontent.com/assets/6187502/22625135/2c365a90-eb8e-11e6-9690-aa9fab0231bc.png)

My xonfig:
<pre>
+------------------+-----------------+
| xonsh            | 0.5.2           |
| Python           | 3.6.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.9           |
| shell type       | prompt_toolkit  |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         | (Manjaro XFCE x86_64)
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
</pre>

**Comment by mitnk** [comment]
Hi @ferkulatius, thanks for reporting.
The reason is `not` is parsed as a Python/xonsh keyword. This is a known issue, same as #1921.

**Comment by mitnk** [comment]
Ah sorry, it is `!` not working here, so ignore my last comment :)

**Comment by scopatz** [comment]
Hi @ferkulatius, try putting the exclamation point in quotes `"!"`. The `!` is a special character for subprocess macros: http://xon.sh/tutorial_macros.html#subprocess-macros

**Comment by ferkulatius** [comment]
Thanks @scopatz, I learned something new today!
`$ find -type f -regextype posix-extended '!' -regex '.*\.(md|txt)$' | wc -l` works as intended.
