### ISSUE TITLE
Interrupted system call in clients

### ISSUE THREAD

**Issue by daym** [xonsh/xonsh#2160]
When I use xonsh 0.5.3 I get interrupted system call really really often.

To reproduce, run xterm -e xonsh, then maximize the xterm window (that's important) and then run top.

top will fail (!).

top: failed tty set: Interrupted system call

I've also had similar problems with guix environment, ssh sessions etcetc. But the above is an easy way to reproduce the problem.

**Comment by scopatz** [comment]
Hii @daym, thanks for reporting. It seems like this is a duplicate of an issue that was fixed in #2158. Would you mind trying out current master and seeing if that works for you? Also, could you please post the output of the `xonfig` command and the contents of your xonshrc.

**Comment by daym** [comment]
Yeah, seems to work now.

**Comment by scopatz** [comment]
OK great! Feel free to close this then.

**Comment by daym** [comment]
But doesn't work with 0.5.5.

**Comment by gforsyth** [comment]
Hi @daym -- can you try upgrading to 0.5.7 and see if the issue persists there?  Thanks!

**Comment by daym** [comment]
Yes, I tried it now. Doesn't work (same as before).

**Comment by scopatz** [comment]
What you mean by "top fails" @daym? Can you provide a traceback or an asciinema or a video?

**Comment by daym** [comment]
I mean top just says "Interrupted system call" and then dies. 

I'll check how to provide asciinema or a video.

**Comment by scopatz** [comment]
Thanks! I really appreciate it!

**Comment by gforsyth** [comment]
I believe this has been fixed.
