### ISSUE TITLE
time.clock() is deprecated

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#2163]
Should remove and replace in timings module.

**Comment by StreakyCobra** [comment]
> Deprecated since version 3.3: The behaviour of this function depends on the
  platform: use perf_counter() or process_time() instead, depending on your
  requirements, to have a well defined behaviour.

So, should it be `perf_counter()`, or `process_time()`?

- `perf_counter()`:

      Return the value (in fractional seconds) of a performance counter, i.e. a
      clock with the highest available resolution to measure a short duration.
      It does include time elapsed during sleep and is system-wide. The
      reference point of the returned value is undefined, so that only the
      difference between the results of consecutive calls is valid.

- `process_time()`:

      Return the value (in fractional seconds) of the sum of the system and user
      CPU time of the current process. It does not include time elapsed during
      sleep. It is process-wide by definition. The reference point of the
      returned value is undefined, so that only the difference between the
      results of consecutive calls is valid.

Also --- if I understood correctly --- the calls to `time.clock()` are only used on windows:

        # There is no distinction of user/system time under windows, so we
        # just use time.clock() for everything...

So, is it just a matter of replacing `time.clock()` calls by one of the above, or should it be a more deep refactoring of `timing.py` in regard to these functions?

**Comment by scopatz** [comment]
> So, is it just a matter of replacing time.clock() calls by one of the above

This one, and probably with `perf_counter()`
