### ISSUE TITLE
Timing missed a lot of import time on Windows.

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2168]
@scopatz 

I do see why you made the last change to the timing branch before merging. It is nicer code in general:
https://github.com/xonsh/xonsh/pull/2162/commits/53d65334ca386740a586288b6a94246e9644265a

On posix it has no effect on the timings since `clock()` measures time since the process started. But on Windows we want to call `clock()` as early as possible. Here `clock()` measures time since the first call to the function. That is why I had the code in the module scope, and why I had the timing module import before other xonsh imports in main.py. 

Right now, we miss around 200 ms on Windows because of this.

Here is the timing with `clock()` in `setup_timings()` (your change on master):
```
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.004   |   0.004   |
|post_execer_init  |   0.152   |   0.148   |
```` 

And here is the timing with `clock()` as early as possible.
```
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.248   |   0.248   |
|post_execer_init  |   0.379   |   0.131   |
```

**Comment by melund** [comment]
So I put in a PR for another small blunder in the timing code. 

If you have any good ideas for where to place a call to `clock()` on Windows let me know, or feel free to update the PR directly

**Comment by scopatz** [comment]
Whoops, sorry about that @melund. I have put in a fix on a2eed1f (on master). My real issue with what you had written before was the `if "--timings" in sys.argv`, since checking if a str is in a list of str can be relatively expensive, and we should try to do as little work as possible at global state.  Hopefully this get this right balance. If not please let me know!

**Comment by astronouth7303** [comment]
How expensive is `clock()`? Could we just call it in `pre_main` or whatever? It just has to be called as early as possible, right?

**Comment by melund** [comment]
My original `if` was to prevent this but I hadn't considered that string competitions are relatively heavy in Python. I don't think `clock()` is expensive but I will check later. Any way it is only called on Windows.

However, it must be called here. Otherwise we can't measure the time it takes to make all the xonsh imports. We could maybe just have an `if` to check the length of `argv`. If it is length 1 we can assume no argument and skip it.

**Comment by astronouth7303** [comment]
I'm pretty sure that string comparisons are just fine, given that it's all in memory and we're probably dealing with less than 100 characters altogether.

**Comment by melund** [comment]
@scopatz is right. It seems faster to just skip `if '--timings' in argv` and just call `clcok()`
```
snail@sea ~\Documents $ from time import clock
snail@sea ~\Documents $ timeit !clock()
10000000 loops, best of 3: 58.3 ns per loop
snail@sea ~\Documents $ argv = ['xonsh']
snail@sea ~\Documents $ timeit ! '--timings' in argv
10000000 loops, best of 3: 64.4 ns per loop
```

**Comment by melund** [comment]
I think we can close this now..

**Comment by scopatz** [comment]
`clock()` and friends are meant to be very cheap.  And my concern really is in implicit loop that `in` coupled to str comparisons. In any event, I am glad this is good enough.
