### ISSUE TITLE
script that calls ssh gets interrupted

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2170]
```
laerus@xonsh$ cat autossh 
ssh laerus@192.168.1.10
laerus@xonsh$ ./autossh 
^Z <--- didn't press anything here, this comes from xonsh or ssh
```

tried again with a non-lan remote
```
laerus@xonsh$ ./autossh
^Z
tcsetattr: Interrupted system call
```

**Comment by mitnk** [comment]
@laerus good catch! I added a PR for this issue #2172, could you check it whether fixes this issue.

**Comment by scopatz** [comment]
@laerus - let us know if this was actually fixed or if it should be reopened.

**Comment by laerus** [comment]
fixed, thanks @mitnk !
