### ISSUE TITLE
Startup 200 ms slower on py36

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2183]
I am seeing slightly longer startup times on python3.6 compared to 3.5. 

The difference is the time it takes from `on_pre_cmdloop` to `on_pre_prompt`

Py3.5:  ~400ms
Py3.6: ~630 ms

I will try to dig a little to figure out where it comes from. But let me know if you have any ideas. 

## Python 3.6

| Event name       | Time (s)  | Delta (s)  |
| ---------------- | --------- | --------- |
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.058   |   0.058   |
|post_execer_init  |   0.201   |   0.144   |
|on_pre_rc         |   0.202   |   0.000   |
|on_post_rc        |   0.293   |   0.092   |
|on_ptk_create     |   0.449   |   0.155   |
|on_post_init      |   0.449   |   0.000   |
|on_pre_cmdloop    |   0.450   |   0.001   |
|on_pre_prompt     |   1.083   |   0.633   |

```
+------------------+----------------------+
| xonsh            | 0.5.4                |
| Git SHA          | 72a4cef9             |
| Commit Date      | Feb 12 02:57:00 2017 |
| Python           | 3.6.0                |
| PLY              | 3.9                  |
| have readline    | False                |
| prompt toolkit   | 1.0.13               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

## Python 3.5

| Event name       | Time (s)  |  Delta (s)  |
| ----------------- | ---------- | ---------- |
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.060   |   0.060   |
|post_execer_init  |   0.205   |   0.145   |
|on_pre_rc         |   0.206   |   0.000   |
|on_post_rc        |   0.257   |   0.051   |
|on_ptk_create     |   0.454   |   0.197   |
|on_post_init      |   0.456   |   0.002   |
|on_pre_cmdloop    |   0.457   |   0.001   |
|on_pre_prompt     |   0.860   |   0.403   |
 

```
+------------------+----------------------+
| xonsh            | 0.5.4                |
| Git SHA          | 72a4cef9             |
| Commit Date      | Feb 12 02:57:00 2017 |
| Python           | 3.5.3                |
| PLY              | 3.9                  |
| have readline    | False                |
| prompt toolkit   | 1.0.13               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by melund** [comment]
I found the line that causes this by setting up timing events around it: 
```
prompt_args['lexer'] = PygmentsLexer(pyghooks.XonshLexer)
```
https://github.com/xonsh/xonsh/blob/time_lexer/xonsh/ptk/shell.py#L112


It takes 95 ms on Py35 and 281 ms on Py36

Python 3.6
```
|Before PygmentsLexer  |   0.674   |   0.220   |
|After PygmentsLexer   |   0.956   |   0.281   |
```

Python 3.5
```
|Before PygmentsLexer  |   0.639   |   0.222   |
|After PygmentsLexer   |   0.734   |   0.095   |
```

Do any of you see this on Linux...

**Comment by scopatz** [comment]
Thanks for pointing this out, @melund! I am not on Python 3.6 (yet) but that seems like it is from Pygments import. This probably means that whatever we are doing in lazyasd to import pygments on another thread is no longer working on Python v3.6

**Comment by gforsyth** [comment]
since `prompt_toolkit` supports everything we use pygments for, we might want to consider just removing pygments entirely?  It would require writing or forking a Python lexer for syntax highlighting but not much else?

**Comment by scopatz** [comment]
I think we use pygments to syntax highlight output independent of ptk.

**Comment by scopatz** [comment]
Though it is a noble thought to consider dropping pygments, maybe you are right that there is a way to do this @gforsyth :)

**Comment by scopatz** [comment]
Also, we'd still want to keep our pygments lexer around so our docs would be highlighted. But at runtime there is probably no need for it.

**Comment by melund** [comment]
I don't have an overview of what it will take to remove pygments. 

But, I think @scopatz is right. We would still want to keep pygments around. I find it nice to be able to open syntax highlighted `.xsh` files in for example spyder. Our pygments plugin takes care of that.

**Comment by gforsyth** [comment]
> But, I think @scopatz is right. We would still want to keep pygments around. I find it nice to be able to open syntax highlighted .xsh files in for example spyder. Our pygments plugin takes care of that.

Agreed -- but I think we can probably remove it from runtime and use PTK to provide most of the features that we use but keep a pygments plugin for `xsh` files and whatnot.

**Comment by scopatz** [comment]
Maybe this is because the trick to monkey patch `pkg_resources` doesn't work in v3.6

**Comment by melund** [comment]
This seemed to be solved now on master. Maybe @gforsyth effort to eliminate the run-time pygments dependencies. 

|Event name            | Time (s)  | Delta (s) |
|----------------------|-----------|-----------|
|Before PygmentsLexer  |   0.692   |   0.249   |
|After PygmentsLexer   |   0.780   |   **0.089**   |
