### ISSUE TITLE
`on_ptk_create` doesn't appear in documentation

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2189]
[The events references](http://xon.sh/events.html) doesn't list `on_ptk_create`.

**Comment by scopatz** [comment]
This is probably because ptk isn't imported when  docs are created.

**Comment by gforsyth** [comment]
So just adding a ptk import to `conf.py` doesn't do the trick.  I can get the `on_ptk_create` event to show up if I add the following:

```
from xonsh.environ import Env
builtins.__xonsh_env__ = Env()  # required or next line barfs
from xonsh.ptk.shell import events
```

question: is this too horrible to add in?

**Comment by astronouth7303** [comment]
Will build machines always have PTK installed?

**Comment by gforsyth** [comment]
Have to add it to `docs-requirements.txt`

**Comment by astronouth7303** [comment]
Will it cause other problems with the these machines moving from readline to ptk?

**Comment by gforsyth** [comment]
i don't think so -- it's just a travis linux image and the docs dont' really run xonsh at all

**Comment by gforsyth** [comment]
See #2281

**Comment by scopatz** [comment]
Should be fixed now. Please reopen if it persists.
