### ISSUE TITLE
Feature Request - Use underscore to store unstored call results (like in REPL)

### ISSUE THREAD

**Issue by ttufts** [xonsh/xonsh#2190]
Not sure if this has been suggested/knocked down before, I did a quick search of past issues and didn't see it. 

It would be awesome if the _ in xonsh could work like the _ in REPL. For instance, if I run a command and don't think to store it's output, always dump it into _ for later retrieval. I love this about _ in REPL because I very often run a command and completely forget to store it in a named variable. _ is my savior.

**Comment by scopatz** [comment]
thanks for opening! I am 99% sure this already exists. is there a specific case that is failing?

**Comment by ttufts** [comment]
Ooh; I see. It works for any python, and any $() wrapped commands, I had
only checked it on 'ls' without wrapping it.

I apologize for not investigating further before I put in the issue.

**Comment by scopatz** [comment]
I think it also works for unwrapped subprocess commands. They are just wrapped as HiddenCommandPipelines, which like None, don't print anything out at the REPL.

**Comment by ttufts** [comment]
Is there a way to get the output of them then?

**Comment by laerus** [comment]
Hey @ttufts have you tried `_.out` ? `_` in this case is the HiddenCommandPipeline and `out` the attribute that holds the output

**Comment by scopatz** [comment]
yeah, look at their attributes

**Comment by ttufts** [comment]
very nice! That does it!

**Comment by ttufts** [comment]
I was just trying that when Konstantinos chimed in. Trouble with trying to
look at the attributes of _ is that it gets overwritten with every command.
I'd just copied the value into another variable for some deeper digging
when he gave me the answer.

Thanks all!

**Comment by laerus** [comment]
xonsh can be overwhelming at first @ttufts :)
if you see anything missing from the docs
you're more than welcomed to open a PR!
