### ISSUE TITLE
Implement ergonomica like autocomplete

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#2192]
I saw today ergonomica another cool python shell, one of the nicest things in the intro video was that they always show autocomplete boxes, without needing the first tab like all other shells (including xonsh for now). Can we have a switch to add it, and  possibly in the future have it always on by default?

https://github.com/ergonomica/ergonomica

**Comment by gforsyth** [comment]
Hey @santagada -- you can set `$UPDATE_COMPLETIONS_ON_KEYPRESS=True` on current master and it should do what you want.

In re: having it on by default, I'm personally not a fan of that since I find it distracting.

**Comment by scopatz** [comment]
I believe that this sort of feature has been implemented on master: https://github.com/xonsh/xonsh/blob/master/news/compup.rst

Let us know if this isn't what you are looking for.

**Comment by santagada** [comment]
It probably is, I can reopen if its not. Thanks everyone!

**Comment by ahundt** [comment]
it seems that rst file is gone, how do you enable this?

**Comment by melund** [comment]
Those news files gets collected for every release and added to the release notes. You can find the release notes here. 
https://github.com/xonsh/xonsh/blob/master/CHANGELOG.rst

Search for `UPDATE_COMPLETIONS_ON_KEYPRESS` to find the relevant line. 

You can enable by typing:
```
$UPDATE_COMPLETIONS_ON_KEYPRESS=True
```

in a running session, or add the line to a `~/.xonshrc` file, so it is always enabled.
