### ISSUE TITLE
Getting last item out of history

### ISSUE THREAD

**Issue by ns-phennessy** [xonsh/xonsh#2199]
A useful plugin for Zshell was that if a command took a certain amount of time to run, at the very end, it would print out a timer showing how long it took. 

With xonsh's rich history, I think this is totally possible. I however cannot figure out how to easily get the last run command metadata. Is there an easy way to do this?

**Comment by gforsyth** [comment]
hey @ns-phennessy -- `_` will point to the last command run. If you want the execution time you could do `_.end_time - _.start_time`

**Comment by ns-phennessy** [comment]
@gforsyth genius!

**Comment by astronouth7303** [comment]
[prompt_ret_code](https://github.com/xonsh/xonsh/blob/master/xontrib/prompt_ret_code.xsh) might be helpful.

Or if you prefer the indexed API, I think `__xonsh_history__[-1]` will also work.

**Comment by StreakyCobra** [comment]
For a ZSH's like behavior:

```python
@events.on_postcommand
def _print_elapsed_time(**kwarsg):
    time = _.endtime - _.starttime
    if time > 5:
        print('Total time: {:.2f} sec.'.format(time))
```

Prints the total time after a command if it spent more than 5 seconds.

**Comment by ns-phennessy** [comment]
@StreakyCobra 
getting errors with that one
```xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 7981, in fire
    rv = handler(*pargs, **kwargs)
TypeError: _print_elapsed_time() takes 0 positional arguments but 4 were given
Exception raised in event handler; ignored.
```

are there docs on the event hook things? thats super useful

**Comment by gforsyth** [comment]
they'll be available soon at: https://xonsh.github.io/xonsh-docs/events.html

error looks like you're missing the `ts, **kwargs` arguments in your function definition?

**Comment by ns-phennessy** [comment]
```@events.on_postcommand
def _print_elapsed_time(ts, **kwargs):
```

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 7981, in fire
    rv = handler(*pargs, **kwargs)
TypeError: _print_elapsed_time() takes 1 positional argument but 4 were given
Exception raised in event handler; ignored.
```

i copied an pasted the wrong stack trace

**Comment by astronouth7303** [comment]
The biggest problem is that you're running an older version of xonsh. The event system was changed in v0.5.3.

**Comment by xyb** [comment]
> For a ZSH's like behavior:
> ... 
> 
> Prints the total time after a command if it spent more than 5 seconds.

Thanks @StreakyCobra, but the [on-postcommand](https://xon.sh/events.html#on-postcommand)'s arguments changed, my new working copy is:

```python
@events.on_postcommand
def _print_elapsed_time(cmd, rtn, out, ts):
    time = ts[1] - ts[0]
    if time > 5:
        print('Total time: {:.2f} sec.'.format(time))
```
