### ISSUE TITLE
Xonsh clears screen after open/close text editor

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#2202]
Whereas the previous commands and output should still be visible.  @mitnk any ideas? Or have you noticed this?

**Comment by mitnk** [comment]
cannot reproduce this. any details?

**Comment by scopatz** [comment]
Sorry Yeah, I was using `xo`

**Comment by mitnk** [comment]
Checked with xo, and reproduced the issue. The solution is to revert #2191 - it will fix 1) this issue 2) #2198. And the revert won't break #2186, which #2191 was trying to fix (at least not an issue from my testing). I've added some context tof the reason to revert it [here](https://github.com/xonsh/xonsh/issues/2198#issuecomment-280087026). Thoughts @scopatz ?

**Comment by scopatz** [comment]
Potential fixes in #2206 and #2211
