### ISSUE TITLE
Add generators to @(...) evaluation 

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#2209]
See https://github.com/xonsh/xonsh/issues/1217#issuecomment-228021152

**Comment by t184256** [comment]
While you are pondering at what can go inside `@(...)`, please consider making `echo @('a', 'b')` work.

**Comment by scopatz** [comment]
@t184256 please feel free to open another issue for that!

**Comment by t184256** [comment]
OK, requested in #2253.

**Comment by scopatz** [comment]
This should now be available on master.  Please feel free to reopen if needed, and thank @adqm :)
