### ISSUE TITLE
Tab completion swallowing the start of paths.

### ISSUE THREAD

**Issue by tinloaf** [xonsh/xonsh#2231]
Hi. I'm on 0.5.2.dev69 (more-or-less current master), not using PTK. I experience strange tab-completion problems when I do this:

1. Hit \<Up\> to bring up a command from history
2. Partially edit a filename in this command
3. Hit \<Tab\> to complete the edited filename

What happens is that the filename is actually correctly completed, but the beginning of the path is swallowed. This seems to only happen when the edited filename is *not* the last argument.

Here is an example:
```
lukas@i11pcbarth ~/tmp/tabproblem $ ls -R
.:
bar  foo

./bar:

./foo:
file.txt
lukas@i11pcbarth ~/tmp/tabproblem $ cd bar/
lukas@i11pcbarth ~/tmp/tabproblem/bar $ cat ../foo/file.txt ../foo/file.txt 

[The file is empty, no output, everything OK up to here]
[Press <Up>]
lukas@i11pcbarth ~/tmp/tabproblem/bar $ cat ../foo/file.txt ../foo/file.txt 
[Edit the first filename]
lukas@i11pcbarth ~/tmp/tabproblem/bar $ cat foo/file[Cursor here]  ../foo/file.txt 
[Press <Tab>]
lukas@i11pcbarth ~/tmp/tabproblem/bar $ cat o/file.txt [Cursor here] ../foo/file.txt 
```

It looks like autocompletion inserts five characters (".txt" plus a space) and these five characters are removed from the begin of the argument.

Please let me know if you need any additional debugging information. Here's a 'xonfig' for starters:

```
+------------------+----------------------+
| xonsh            | 0.5.2.dev69          |
| Git SHA          | d1b371c              |
| Commit Date      | Feb 20 08:51:19 2017 |
| Python           | 3.5.2                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

Regards,

Lukas

**Comment by adqm** [comment]
This is definitely a bug, and one that I have noticed as well; thanks for reporting.  I think the current completer assumes that your cursor is on the last character of the line, which can cause bizarre behavior when using tab completion on something in the middle of a line.

**Comment by scopatz** [comment]
Hi @tinloaf and @adqm, thanks for reporting. I believe that this was fixed in v0.5.4 (though it was only reported for readline).  Would you please try it out on the current version (v0.5.5) or on the current master.  There has been a lot of clean up in the past couple of weeks.

**Comment by scopatz** [comment]
See the changelog here: http://xon.sh/previous/changelog.html#id1

**Comment by tinloaf** [comment]
Indeed, it works! Thanks a lot. I thought I was using current master, but the more you know…
