### ISSUE TITLE
Subprocess-mode line continuations eat spaces in scripts

### ISSUE THREAD

**Issue by t184256** [xonsh/xonsh#2254]
I thought it should be somewhere in the tutorial or bash translation guide, but I can't find it there. Let's suppose I wanna convert this piece of a script to xonsh:
```
echo --option1 value1 \
    --option2 value2 \
...
    --optionZ valueZ
```

Currently this eats spaces: `--option1 value1--option2 value2...`. The tutorial kinda warns about that, so cool, everybody needs something to eat.

I can use trailing spaces and `$[` to overcome this:
```
$[
echo --option1 value1 
    --option2 value2 
...
    --optionZ valueZ
]
```
But you know, _trailing spaces_.

I can also get creative and build it like that:
```
$[
echo @((
    '--option1', 'value1',
    '--option2', 'value2',
...
    '--optionZ', 'valueZ'
))
]
```
That's cool and flexible, but overly bracely and magical.

Let's suppose I don't need that flexibility and I just want to write an extremely long command in a script without trailing spaces or three layers of braces. What's the best practice for running long shell commands in a script?

**Comment by scopatz** [comment]
Hi @t184256, it seems like 

```
echo --option1 value1 \
    --option2 value2 \
```

should work.  There have been a couple of fixes to this part of the code but apparently there is more work to do.

Personally, I don't have a problem with the trailing spaces. It is a fairly Pythonic idiom.

**Comment by t184256** [comment]
So the first one is the preferred way, but it's not working at the time? Ugh, I fail to name issues all the time. Not even close!
```
$ echo -n 'echo --option1 value1 \\\n--option2 value2' > ml.xsh
$ xonsh ml.xsh
--option1 value1 --option2 value2
```

> Personally, I don't have a problem with the trailing spaces. It is a fairly Pythonic idiom.

Whoa. With all respect, this particular opinion doesn't seen Pythonic at all to me. The first strong opinion that springs to mind is, um, PEP 8:

> Avoid trailing whitespace anywhere. Because it's usually invisible, it can be confusing: e.g. a backslash followed by a space and a newline does not count as a line continuation marker. Some editors don't preserve it and many projects (like CPython itself) have pre-commit hooks that reject it.

**Comment by scopatz** [comment]
> Whoa. With all respect, this particular opinion doesn't seen Pythonic at all to me. The first strong opinion that springs to mind is, um, PEP 8:

Right, you shouldn't have trailing whitespace. But the explicit subproc bracketing with `$[]`, `$()` , `![]`, `!()` allows you to have multiline input within a single expression. That is what seems Pythonic to me.

**Comment by t184256** [comment]
Oh, I see. Yes, implicit line joining inside braces definitely is Pythonic, to the point I intuitively used it for this purpose.

**Comment by scopatz** [comment]
Potential fix in #2287

**Comment by gforsyth** [comment]
Hey @t184256 -- the fix has been merged to master -- could you try it out and see if it solves your issue and then close this out?  Thanks!

**Comment by t184256** [comment]
Looks like it does. Thanks a lot!
