### ISSUE TITLE
Working directory is locked (Windows)

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2269]
Python somehow locks the current working directory on Windows. 
```
snail@sea ~\Documents\xonsh delcwd
$ rm -rf ~/x; mkdir ~/x; cd ~/x; rm -r ~/x
rm: remove directory 'C:\Users\mel/x'? y
rm: cannot remove 'C:\Users\mel/x': Device or resource busy
```

Or if I try from the GUI:

![image](https://cloud.githubusercontent.com/assets/1038978/23343355/7a81b202-fc6a-11e6-9170-83b9f8b87315.png)

Does anyone know a way to prevent this? I have search but haven't come up with anything.

**Comment by astronouth7303** [comment]
Windows is pretty big on file locks (same thing happens with executing programs). I have a strong suspicion that Windows does this automatically for all current directories of any program.
