### ISSUE TITLE
Show welcome message instead of Wizard for new users

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2271]
I would suggest that we don't throw new users into the Wizard, but instead show a welcome screen:

I think we may have discussed it before a long time ago. I base it on the reaction I have seen when introducing xonsh to new users. Most people find the xonsh exiting when I tell about it, and they want to try it fast. Then when it is finally installed the wizard becomes a 'turn-off' when all they want is try it out fast.

So what about a welcome screen instead when no rc files are present. 

```
             Welcome to the xonsh shell (v0.57)

   ~ Python-powered, cross-platform, Unix-gazing shell ~    

xonfig tutorial -> Launch a tutorial in browser http://xon.sh/tutorial.html
xonfig wizard   -> Configure the shell and dispell this welcome message
                   (or create ./xonshrc file)
user@home ~/ $ 
```

We should of course have most of the tag-lines in the welcome message as well.

**Comment by scopatz** [comment]
+1 I think that this is a great idea!

**Comment by melund** [comment]
Any pointer on how to use the wizard system to create the message: I guess that would be the easiest way to get it colored and add different tag lines.

**Comment by scopatz** [comment]
I don't think you need to use the wizard. You can just use `print_color()` and then random.choose() for the  tagline.
