### ISSUE TITLE
Error importing certain aliases from zsh

### ISSUE THREAD

**Issue by angiest** [xonsh/xonsh#2291]
I just installed xonsh from the AUR.  I was having issues and eventually found #2241 so I moved to xonsh-git, which seems to have improved things.  However, I am still having some problems.  I am using an unmodified grml config file from the extra repository.  Two aliases won't import.  I can certainly comment those out as I never use them, but I think it is something worth looking at anyway.  This is what I am getting:

>jefosburgh@jef-nt ~ $ source-zsh  /etc/zsh/zshrc
Skipping application of 'egrep' alias from 'zsh' since it shares a name with an existing xonsh alias. Use "--overwrite-alias" option to apply it anyway.
Skipping application of 'grep' alias from 'zsh' since it shares a name with an existing xonsh alias. Use "--overwrite-alias" option to apply it anyway.
Skipping application of 'l' alias from 'zsh' since it shares a name with an existing xonsh alias. Use "--overwrite-alias" option to apply it anyway.

_snip more of the same_
>/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py:8936: RuntimeWarning: could not parse alias "term2iso": ValueError('No escaped character',)
  RuntimeWarning)
/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py:8936: RuntimeWarning: could not parse alias "term2utf": ValueError('No escaped character',)
  RuntimeWarning)

Here's those two aliases from the config file:

>alias term2iso="echo 'Setting terminal to iso mode' ; print -n '\e%@'"
alias term2utf="echo 'Setting terminal to utf-8 mode'; print -n '\e%G'"

zsh version is 5.2.1-1.
grml config version is 0.13.2-1.

**Comment by gforsyth** [comment]
Thanks for reporting, @angiest!
Could you post the output of `xonfig` please?

And I'll note that the dev cycle of xonsh is sufficiently fast that the `xonsh-git` AUR package frequently lags the master branch by a fair bit -- you might try cloning and installing from master to see if your issue is still present.

Thanks!

**Comment by angiest** [comment]
>jefosburgh@jef-nt ~ $ xonfig 
+------------------+---------------------+
| xonsh            | 0.5.7.dev20         |
| Git SHA          | c9f1ea7a            |
| Commit Date      | Mar 3 06:19:48 2017 |
| Python           | 3.6.0               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.13              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | arch                |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+

**Comment by gforsyth** [comment]
Thanks @angiest and sorry for the delay.  So there are a few things going on here. 

The first set of messages you are getting are expected -- if you source any kind of foreign shell config file and it tries to overwrite an existing `xonsh` alias, we require you to use that `--overwrite-alias` flag.  This is to avoid conlicts between multiple config files. 

The second issue is related to a separate issue we have, I have to dig up the issue number. `zsh` is relying on a builtin it has called `print` which is causing issues when we parse it. 

We might have to start exclusing `zsh` aliases that rely on these builtins, too, to stop these errors

**Comment by angiest** [comment]
I figured the first part was expected behavior.  Thanks for looking into the rest.

**Comment by zommerfelds** [comment]
I have another alias that loads fine under `zsh` but not with `xonzsh`:
`alias nocolor="perl -pe 's/\e\[?.*?[\@-~]//g'"`

**Comment by scopatz** [comment]
I think that the original issue here was closed in a recent release with the additional of exec aliases. 

> alias nocolor="perl -pe 's/\e\[?.*?[\@-~]//g'"

@zommerfelds - If I do `aliases["nocolor"] = "perl -pe 's/\e\[?.*?[\@-~]//g'"`, it seems to load fine.

**Comment by khughitt** [comment]
Encountered a similar `RunTimeWarning` issue with xonsh 0.8.12 when attempting to parse aliases defined in the oh-my-zsh [git plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh):

```sh
/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py:10049: RuntimeWarning: could not parse alias "glod": ValueError('No escaped character')
  'could not parse alias "{0}": {1!r}'.format(key, exc), RuntimeWarning
/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py:10049: RuntimeWarning: could not parse alias "glol": ValueError('No escaped character')
  'could not parse alias "{0}": {1!r}'.format(key, exc), RuntimeWarning
```

The problematic aliases are:

```sh
glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'
glod='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'
```

**Comment by scopatz** [comment]
These can be written as follows:

```
 aliases['glog'] = "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'"
```

I think this is a non-issue for xonsh
