### ISSUE TITLE
Python 3.4 no longer supported?

### ISSUE THREAD

**Issue by duerrp** [xonsh/xonsh#2294]
Hi all,

First of all, thank you all for your great work. 

I have noticed that the version bump to 0.5.7 introduced a call to `os.scandir` which is not supported by Python <3.5 afaik. As I am still using Ubuntu 14.04 with Python 3.4 on a few machines, this is a little bit of a headache... I don't know the codebase, but it looks like `xonsh.platform.scandir` could be used instead?

**Comment by melund** [comment]
@duerrp . Thanks a lot for spotting this. You are absolutely right. We should use the internal version instead. 

I have put in a PR to fix it #2295.

**Comment by duerrp** [comment]
Great work! Thank you very much.
