### ISSUE TITLE
which broken on Windows

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2297]
`which` seem to be broken on windows.
```
snail@sea ~\Documents\xonsh master
$ which man
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 13009, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\xoreutils\which.py", line 127, in which
    original_os_path = xp.os_environ['PATH']
KeyError: 'PATH'
```

**Comment by astronouth7303** [comment]
That's.... odd. I thought Windows had a PATH.

**Comment by melund** [comment]
I think this is related to the #2276 

Now access to the `os_environ` has to use the correct case, even though it environment variables are case-insensitive on Windows. I think we need to something similar to how we handle the `__command_cache__`...

**Comment by melund** [comment]
So on my machine the path variable is now called `Path`

**Comment by melund** [comment]
I think I have a solution to this...

**Comment by melund** [comment]
That is what I am doing :)

**Comment by melund** [comment]
It seems like `nt.environ` is read only, thus I can't find the documentation on it. I think it can only be used to get the correct cased names on initialization. Changing the values in `nt.environ` doesn't seem to have any effect on os.environ mapping.
