### ISSUE TITLE
Regression on Windows from 0.5.6 to 0.5.7

### ISSUE THREAD

**Issue by ofek** [xonsh/xonsh#2299]
Inside https://github.com/ofek/bit/tree/master/docs running command `make clean && make html` fails on 0.5.7:

```
The 'sphinx-build' command was not found. Make sure you have Sphinx
installed, then set the SPHINXBUILD environment variable to point
to the full path of the 'sphinx-build' executable. Alternatively you
may add the Sphinx directory to PATH.

If you don't have Sphinx installed, grab it from
http://sphinx-doc.org/
```

**Comment by mitnk** [comment]
I guess `make html` was working because it's running in your Python 2 environments? and now you are invoking sphinx in Python 3 (where xonsh exists). If so, you could install `sphinx` under python, like using `pip3`.

**Comment by ofek** [comment]
@mitnk I'm only using Python 3.

**Comment by mitnk** [comment]
Ah, sorry :) Or the PATH doesn't include the directory where `sphinx` located?

**Comment by ofek** [comment]
@mitnk The point is if I `pip install xonsh==0.5.6` it works again :) There was a regression.

**Comment by mitnk** [comment]
Okay, then it should be a bug..

**Comment by mitnk** [comment]
No issue here on Mac. Maybe it is something to do with #2297

**Comment by mitnk** [comment]
@ofek Could you try latest master to see if this issue get fixed?

**Comment by ofek** [comment]
@mitnk Fixed on master it seems.

**Comment by mitnk** [comment]
Nice! Thank you for reporting.
