### ISSUE TITLE
Retry last command with !!

### ISSUE THREAD

**Issue by AgilDat** [xonsh/xonsh#2301]
In others shells you can use !! to refer last command.

In bash is executed when you typed it. In zsh you need to press enter twice to execute it. In xonsh isn't recognized.

**Comment by melund** [comment]
There is xontrib to support more bash like features. Like this one.  It is called `bashisms`

See:
http://xon.sh/xontribs.html#bashisms

**Comment by pando85** [comment]
How could I enable this? I have already installed xonsh with pip (`pip install xonsh`).
Thanks.

**Comment by gforsyth** [comment]
you can run `xontrib load bashisms` and the command will be available. You can stick that command in your `xonshrc` if you want it to be loaded at runtime

**Comment by pando85** [comment]
A ok thanks, you can close this issue!!

**Comment by gforsyth** [comment]
Thanks!

**Comment by melund** [comment]
I think our documentation on how to enable xontribs are lacking. Several people have asked the same question. The docs show how they should be installed but now how to enable them.

**Comment by gforsyth** [comment]
Agreed. It is Docathon week -- maybe I can get to this tomorrow
