### ISSUE TITLE
xonsh doesn't reset title when command exits

### ISSUE THREAD

**Issue by adqm** [xonsh/xonsh#2306]
On current master, running `echo "hi"` seems to leave the terminal title set with `echo` prepended even after the `echo` command exits, rather than resetting it to the normal value.

This happens for certain commands (`echo`, `ls`, `cat`, `hg`, ...) but not for others (`git`, for example).  Maybe `git` is doing something to the terminal title itself?

**Comment by gforsyth** [comment]
Thanks for reporting, @adqm! 
I can't reproduce this, only because I don't have titlebars in my window manager...

**Comment by santagada** [comment]
for me most commands stay there, I could only get git to not stay there. I wish xonsh would do that with all apps.

@gforsyth you can set your bottom toolbar to it for testing: `$BOTTOM_TOOLBAR ='<{current_job}>'`

**Comment by adqm** [comment]
@santagada it used to work that way, so yes, definitely a regression.  not sure when this started happening.

**Comment by santagada** [comment]
it might help that I'm not running master, I'm on: 25c105c8f206c43ea5bfa03e55b636411f8bf17f which is from 2017-02-19

**Comment by astronouth7303** [comment]
This has been consistent for me for a while. I just didn't care enough to file a bug.

**Comment by laerus** [comment]
cannot reproduce on current master

**Comment by santagada** [comment]
@laerus are you on what system? I can reproduce on current master on osx 10.12.

Now I see something strange, xonfig says my xonsh is from feb 19:
+------------------+----------------------+
| xonsh            | 0.5.8                |
| Git SHA          | 25c105c8             |
| Commit Date      | Feb 19 07:49:27 2017 |
| Python           | 3.6.0                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.13               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

strange but apparently I did remove xonsh and installed it from master

**Comment by laerus** [comment]
debian-testing.

@santagada have you ever installed xonsh in develop mode? that seems to leave some traces behind.

**Comment by t184256** [comment]
Also affected, also too lazy to report.
Debian stretch, never installed xonsh in dev mode, reproducible even in a clean docker container:
```
$ docker run -it --net=host debian:stretch /bin/bash
# apt install python3-pip git
...
# pip3 install -U git+https://github.com/xonsh/xonsh.git
# xonsh
<user>@cola / # echo a
```

the title becomes `echo | user@cola: / | xonsh` and doesn't unstick until the next command.

**Comment by Jitsusama** [comment]
FYI; I have the same problem. I'm running xonsh from `cmd.exe` via ConEmu on Windows 7. I did figure out a workaround with my `.xonshrc` file though:

```python
def my_prompt_title():
    from xonsh.jobs import get_next_task
    from xonsh.proc import PopenThread

    job = get_next_task()

    if job is not None:
        is_alive = True
        if isinstance(job['obj'], PopenThread):
            is_alive = job['obj'].isAlive()

        if not job['bg'] and is_alive:
            return ' '.join(job['cmds'][0])

    return $PROMPT_FIELDS['cwd']()

$PROMPT_FIELDS['my_prompt_title'] = my_prompt_title
$TITLE = '{my_prompt_title: {}}'
```

The issue seems specific on the type of command in use. I had to combine using some logic from `xonsh.prompt.job`'s `_current_job()` function (defined as `$PROMPT_FIELDS['current_job']`) and a bit of my own trial and error trickery to get this resolved on my system. The upside is my `$TITLE` seems to be 100% now.

**Comment by Jitsusama** [comment]
I'm trying to remember everything I figured out, but I believe the issue seemed to be with PopenThreads not getting garbage collected after being finished. I started digging through code, but it got convuluted, and it was a long day, so I just hacked my way out of it 😄

**Comment by laerus** [comment]
afaik [slug](https://github.com/xonsh/slug) will remove `PopenThread`, imho we should focus there.

**Comment by anki-code** [comment]
I can't repeat this in Konsole with xonsh 0.9.27.
