### ISSUE TITLE
Bug i guess

### ISSUE THREAD

**Issue by SolarAquarion** [xonsh/xonsh#2311]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/proc.py", line 1349, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/lib/python3.6/site-packages/xonsh/proc.py", line 1171, in proxy_two
    return f(args, stdin)
  File "/usr/lib/python3.6/site-packages/xonsh/dirstack.py", line 234, in cd
    pushd(['-n', '-q', cwd])
  File "/usr/lib/python3.6/site-packages/xonsh/dirstack.py", line 331, in pushd
    if len(DIRSTACK) > maxsize:
TypeError: '>' not supported between instances of 'int' and 'str'

**Comment by gforsyth** [comment]
Thanks for reporting, @SolarAquarion! Can you please post the output of `xonfig` and also the commands or situation in which this traceback is triggered?  Thanks!

**Comment by SolarAquarion** [comment]
cd $folder

**Comment by SolarAquarion** [comment]
xonsh            | 0.5.8                                             |
| Python           | 3.6.0                                             |
| PLY              | 3.9                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.13                                            |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.2.0                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7efdcf195860> |
| distro           | arch                                              |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+

**Comment by gforsyth** [comment]
Thanks! And what was the value of `$folder`?

**Comment by SolarAquarion** [comment]
solaraquarion@apollo ~/.cache/pacaur/xonsh master $ cd
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/proc.py", line 1349, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/lib/python3.6/site-packages/xonsh/proc.py", line 1171, in proxy_two
    return f(args, stdin)
  File "/usr/lib/python3.6/site-packages/xonsh/dirstack.py", line 234, in cd
    pushd(['-n', '-q', cwd])
  File "/usr/lib/python3.6/site-packages/xonsh/dirstack.py", line 331, in pushd
    if len(DIRSTACK) > maxsize:
TypeError: '>' not supported between instances of 'int' and 'str'

**Comment by SolarAquarion** [comment]
dirstack_ensurer fixes it thans

**Comment by melund** [comment]
Awesome. #2312 has been merged into master
