### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#2315]
Currently, everything just gets dumped into the tutorial.

We should break this up into an extensive manual/reference and a getting started tutorial.

**Comment by gforsyth** [comment]
+1 on this. Also I think that we should make it available as a man page on *nix

**Comment by astronouth7303** [comment]
If we're able to fit the entirety of the manual into a single man page, it is nowhere near complete.

However, we should have a man page and it should include at least a summary syntax.

**Comment by dotsdl** [comment]
This is now a meta-issue / epic for this effort. We will list all issues subsumed by this effort in the list below:

1. #834 
2.

**Comment by anki-code** [comment]
I'm going to close this because most of issues that were mentioned are closed.
