### ISSUE TITLE
Partial lines are not displayed

### ISSUE THREAD

**Issue by paulkernfeld** [xonsh/xonsh#2316]
Can I provide any additional information on this?

```
paul ~/projects/iron  $ echo hi
hi
paul ~/projects/iron  $ echo -n hi
paul ~/projects/iron  $ xonsh --version
xonsh/0.5.8
```

**Comment by gforsyth** [comment]
Hey @paulkernfeld -- thanks for reporting! Could you post the output of `xonfig` please?

And a question: is the `echo`ed 'hi' showing up to the left of the prompt initially and then disappearing when you run the next command?

**Comment by paulkernfeld** [comment]
I actually just noticed that the output flashes up for an instant where it's supposed to go, but then it is almost immediately replaced by the command prompt.

Here's the output of `xonfig`.

```
+------------------+---------------------+
| xonsh            | 0.5.8               |
| Git SHA          | e7a9bcf             |
| Commit Date      | Mar 6 23:45:51 2017 |
| Python           | 3.6.0               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | None                |
| shell type       | readline            |
| pygments         | None                |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by anki-code** [comment]
Hello! I can't repeat this behavior and never seen it on xonsh >= 0.9.12.

This issue looks not actual and should be closed.

**Comment by paulkernfeld** [comment]
I no longer use xonsh (😭) so I don't mind if you want to close the issue. 👍

**Comment by anki-code** [comment]
@paulkernfeld thank you for the response! I have no access for this. Please just click close.

**Comment by paulkernfeld** [comment]
After using xonsh for a year or two, I migrated back to zsh. I think that xonsh didn't feel as snappy and that I sometimes needed to modify shell scripts before using them in xonsh. I ended up not using the Python scripting functionality enough to make xonsh the right choice for my workflow.

**Comment by anki-code** [comment]
Thanks! JFI I'm using [xontrib-sh](github.com/anki-code/xontrib-sh) to run the scripts from sh-shells. Also I'm using [xontrib-ergopack](https://github.com/anki-code/xontrib-ergopack) that improves my experience with the shell and I don't want to use zsh or fish for this. Finally I'm using [xxh](https://github.com/xxh/xxh) with xonsh that completely change the mindset of using SSH seesions to remote hosts.
