### ISSUE TITLE
Syntax for *just* stripping last newline

### ISSUE THREAD

**Issue by refi64** [xonsh/xonsh#2328]
`@$` is nice, but, oftentimes, you need everything to stay together as *one* argument, in which case the only way to do it is `@($(mycommand).rstrip('\n'))`. (Or at least for me, I often want it that way!) It'd be nice if there were a syntax akin to `@$` that just strips the ending newline, something that would be like bash's `$(my-command)` syntax.

**Comment by laerus** [comment]
maybe we should strip last new line by default.

**Comment by astronouth7303** [comment]
You do sometimes pipe binary data. (eg, imagemagick) However, I think it's unlikely that this will be by argument. (Especially since I think you can't pass nulls in an argument on POSIX.)

**Comment by ErickTucto** [comment]
#### funcion delete \n

```python
def e(cmd):
  return cmd.strip('\n') if type(cmd) is str else cmd
```
![2018_06_22_002](https://user-images.githubusercontent.com/22831024/41805624-b91f95d6-7673-11e8-8fc5-e7f026e03e65.png)

**Comment by laloch** [comment]
What about introducing yet another "stripping" captured subprocess operator, e.g. `$$(cmd)`, which would basically do `$(cmd)[:-len(os.linesep)]`?

**Comment by ErickTucto** [comment]
`$$(cmd)` is short version... my function `e` is long... Is the version available `$$(cmd)`? I have xonsh/0.9.4 and xonsh is throwing an error (** SyntaxError **) @laloch

**Comment by laloch** [comment]
There's no such operator. It was just a question for eventual further discussion. It may easily turn out to be a bad idea for some reason.

**Comment by laloch** [comment]
@xonsh/xore, what do you think? Could/should we add another pair of subprocess operators delivering their output with the trailing newlines stripped?

**Comment by scopatz** [comment]
We have the [`@$(cmd)` operator](https://xon.sh/bash_to_xsh.html) which does this right now.

Unfortunately, I don't think this has made it into the tutorial docs (oh no!)  and I am not sure where else this is documented.

The idea with this operator was that you could insert function names into the `@func$(cmd)` or `@func1@func2$(cmd)` and the functions could transform the output as needed.  I don't think that ever was fully implemented.

**Comment by scopatz** [comment]
`@$(cmd)` is just the default which happens to only strip the trailing newline

**Comment by laloch** [comment]
OK, I see. The `@$(cmd)` is in fact documented in [the tutorial](https://xon.sh/tutorial.html#command-substitution-with).
Behavior of `$ $(pidof systemd)` and `$ @$(pidof systemd)` is, however not quite the same.

**Comment by laloch** [comment]
> `@$(cmd)` is just the default which happens to only strip the trailing newline

Nope, it calls `.strip()` on the output, which is not quite right here. It should do `run_subproc(cmds, captured="stdout")[:-len(os.linesep)]` to strip just the trailing newline.

**Comment by scopatz** [comment]
Ahh yeah, that should probably be changed

**Comment by scopatz** [comment]
Changed from strip to `[:-len(os.linesep)]`, that is

**Comment by laloch** [comment]
It still does not solve the issue. Try
```
$ cat @([i[:-len(os.linesep)] for i in !(ls -1)])
```
vs.
```
$ cat @$(ls -1)
```

**Comment by scopatz** [comment]
`@$(cmd)` is equivalent to `@($(cmd).strip())`, whereas we might want it to be `@($(cmd)[:-len(os.linesep)])`

**Comment by laloch** [comment]
Nope, according to the tutorial, `@$(cmd)` should be equivalent to `@([i.strip() for i in $(cmd).split()])`, which it is currently not.
To be correct, it should be equivalent to `@([i[:-len(os.linesep)] for i in $(cmd).split()])`.

**Comment by laloch** [comment]
> To be correct, it should be equivalent to `@([i[:-len(os.linesep)] for i in $(cmd).split()])`.

Wrong! `@([i.strip() for i in $(cmd).split()])` is right in this case.

**Comment by laloch** [comment]
Thinking of the actual implementation now, it seems to be quite right to me. Only that `__xonsh__.execer.parser.lexer.split()` now interprets the newline characters, which it probably didn't at some point in time.

**Comment by laloch** [comment]
I'm now testing [this](https://gist.github.com/laloch/1a4ae80c7f10f7c2a8f446f5ccc9211a) modification. It works a bit better - I can now do for instance `cat @$(ls -1)`. I still can't, however, do something as simple as `ls /lib/modules/@$(uname -r)/kernel`.
