### ISSUE TITLE
adding $HOME on windows

### ISSUE THREAD

**Issue by sejktmcsdlmfhsc** [xonsh/xonsh#2334]
On windows $HOME seems to be missing. 
At least on the machine I have a work, 
when trying to get xontrib powerline to work. 
https://github.com/santagada/xontrib-powerline/issues/9
The following lines in my .xonshrc fixed it:
```python
import os
$HOME=os.path.expanduser("~")
```
Maybe it could be added? (not sure where)
Best, sej

**Comment by laerus** [comment]
hey thanks for reporting! can you post the output of `xonfig` please? 
maybe related to #2320

**Comment by melund** [comment]
I don't think it is related. There is no $HOME environment variable on Windows. It is called $HOMEPATH instead. This is an issue with the powerline xontrib. The should use an other method of getting the user's home drive. Python has some options ...

**Comment by melund** [comment]
@sejktmcsdlmfhsc You should maybe post the issue here:
https://github.com/santagada/xontrib-powerline/

**Comment by melund** [comment]
Thanks a lot for spotting this ...

**Comment by santagada** [comment]
Its kind of bizarre we have all to create code to support windows instead of centralizing it in one place. Anyway, I will use the onwindows check and add support for it there, thanks.

**Comment by sejktmcsdlmfhsc** [comment]
@laerus @melund sure, you're welcome. 
Since it is weekend I am currently away from my work machine.
But the xonfig would show: 
xonsh 0.5.8 
python 3.6
on windows 
not on cygwin
prompt_toolkit 1.0.20 
PLY 3.9 
pygments 2.2.0
thanks @melund I was not aware of $HOMEPATH . I actually posted it first on xontrib-powerline: santagada/xontrib-powerline#9
But to be honest I would agree with @santagada and assume something like a central 
onwindows $HOME=$HOMEPATH might help other situations/xontribs as well?

**Comment by melund** [comment]
I don't think xontribs needs to support all platforms. It is up to the maintainer. 

Also we do have `xonsh.platform` as a central place for code that does this kind of abstractions. 

In this case doing: $HOME=$HOMEPATH is the wrong solution. Python has `os.expanduser('~')`

**Comment by santagada** [comment]
Released a new version of xontrib-powerline that uses path.expanduser.

**Comment by melund** [comment]
Awesome. Thanks a lot for that @santagada. @sejktmcsdlmfhsc feel free to close this issue.

**Comment by sejktmcsdlmfhsc** [comment]
thank you!
