### ISSUE TITLE
Prompt Update Call

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#2338]
Add an API call for xontribs to force the prompt to update.

Use case: xontrib that automatically does things in the background on file change and updates the prompt with the results.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Related to #3640

**Comment by jnoortheen** [comment]
This is already possible as mentioned here https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1286#issuecomment-733822749 ,
The same is used by async-prompt option . The upstream project can make this more explicit though.

**Comment by anki-code** [comment]
@jnoortheen may be you can provide the simple example for the xonsh shell? For example the prompt with the time where second will be automatically updated.

**Comment by jnoortheen** [comment]
Here is a sample script

```py
import datetime
import time

from prompt_toolkit import PromptSession
import threading
import funcy


# @funcy.print_calls
def get_prompt():
    " Tokens to be shown before the prompt. "
    now = datetime.datetime.now()
    return [
        ("bg:#008800 #ffffff", "%s:%s:%s" % (now.hour, now.minute, now.second)),
        ("bg:cornsilk fg:maroon", " Enter something: "),
    ]

def update_in_bg(session: PromptSession):
    time.sleep(3)
    session.message = get_prompt()
    session.app.invalidate()


def main():
    session = PromptSession()
    t = threading.Thread(target=update_in_bg, args=(session, ))
    t.start()
    result = session.prompt(get_prompt(), refresh_interval=None)

    print("You said: %s" % result)



if __name__ == "__main__":
    main()
```
