### ISSUE TITLE
@$ result is not satisfying

### ISSUE THREAD

**Issue by shipup** [xonsh/xonsh#2340]
When I run `@$(which ls)` I expect to see this result:
`some_file  some_other_file`

But I see this:
`ls: invalid option -- '
'
Try 'ls --help' for more information.
`

xonsh version: 0.5.9
os : linux (Ubuntu 16.04.2)

**Comment by laerus** [comment]
thx for reporting @shipup !  this is defo a bug and maybe related to #2326

**Comment by melund** [comment]
@laerus Are you sure you mean #2329 ?

**Comment by gforsyth** [comment]
I think this may be separate from #2329 and more a function of using `@$` with aliased commands?

`@$(which ls)` works as expected for me if I first do a `aliases.pop('ls')`
