### ISSUE TITLE
OSX Python 3.6 memory error

### ISSUE THREAD

**Issue by brianmay** [xonsh/xonsh#2342]
All I did was push enter once, after starting xonsh:

```
$ xonsh
Warning: Unconfigured $PROJECT_DIRS. Using ~/code
<cwd> $ 
python3.6(74187,0x7fffccbb73c0) malloc: *** error for object 0x10f470da0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
zsh: abort      xonsh
```

**Comment by astronouth7303** [comment]
Note: the warning is from avox. Shouldn't be a problem.

Of course, this is such a low-level error I'm not even sure where to begin.

**Comment by brianmay** [comment]
I forgot to mention, I installed xonsh using brew. As per the instructions: ``http://xon.sh/osx.html``.

I suspect this comes supplied with its on version of python (instead of using the python that comes with brew???) that is broken.

**Comment by brianmay** [comment]
I also installed xonsh with pip, so it uses the brew version of Python 3.6, and get the same error.

**Comment by laerus** [comment]
hey @brianmay are you using readline or prompt_toolkit? if you're on readline can you try installing prompt_toolkit and see if this is still happening?

**Comment by mitnk** [comment]
May be related with #2078

**Comment by brianmay** [comment]
Yes, does look identical to #2708. I installed prompt_toolkit and now it looks good.

**Comment by gforsyth** [comment]
I'm going to close this out, since it's a duplicate and #2078 is just waiting on a new release of gnureadline anyway
