### ISSUE TITLE
how to remove new line dots?

### ISSUE THREAD

**Issue by tkossak** [xonsh/xonsh#2343]
When i enter long command that goes into new line, xonsh draws that many dots (in this new line) as my prompt length. It's very annoying if my prompt is long (because I am in some deep folder structure). How do I turn it off?

**Comment by laerus** [comment]
hey @tkossak i think you're looking for the `$MULTILINE_PROMPT` envvar.

**Comment by tkossak** [comment]
I set it to "" (empty string) and new line is still filled, only with spaces this time instead of dots. What values should i set `$MULTILINE_PROMPT' to, to disable this multiline completely?

**Comment by laerus** [comment]
do you want to not wrap the line at all or just start at the first column of the next line when its wrapped?

**Comment by tkossak** [comment]
I'd like it to start at first column of the next line when it is wrapped.

**Comment by laerus** [comment]
yup i don't think this is possible atm, this would be a nice feature though! you're using prompt_toolkit right?

**Comment by laerus** [comment]
[this](https://github.com/xonsh/xonsh/blob/master/xonsh/ptk/shell.py#L215) method needs a little tweaking for anyone willing to tackle this!

**Comment by tkossak** [comment]
Yes, i use prompt_toolkit. Thank you for this awesome shell.

**Comment by gforsyth** [comment]
I'm not sure this is going to be easy to do -- the first column of the next line is part of the same multiline buffer and if we arbitrarily insert dots into it they're going to be parsed as part of the command...

**Comment by gforsyth** [comment]
IPython does something similar to us for the same reason:
```python
In [2]: for i in range(5):
   ...:     print(i)
   ...:
```

**Comment by melund** [comment]
What about always starting at the first column. Just append a newline to the prompt. I know it wasn't what you asked for.

Of course we could maybe change the prompt to include the newline whenever we switch to multiline mode and then ask prompt_toolkit to redraw somehow.

**Comment by gforsyth** [comment]
@tkossak you can also set `$DYNAMIC_CWD_WIDTH='20%'` (or choose some percentage you like) and `xonsh` will creatively truncate the file-path in the prompt so it never exceeds 20% (or whatever) of the total terminal width.

**Comment by tkossak** [comment]
> I'm not sure this is going to be easy to do -- the first column of the next line is part of the same multiline buffer and if we arbitrarily insert dots into it they're going to be parsed as part of the command...

but that's what i want - to be no chars there (no arbitrary dots, nor anything except the command itself) in my buffer! :)

ok, if it's too difficult i see that the workaround would be shortening the default prompt (with `$DYNAMIC_CWD_WIDTH` or using `cwd_base` instead of `cwd` in the `$PROMPT`) or adding new line character at the end.

Maybe i just use `cwd_base` in my prompt, so the dots won't disturb too much.

**Comment by gforsyth** [comment]
Or add a `\n` to the end of your `$PROMPT` and there won't be any dots at all.

**Comment by haqishen** [comment]
ipython's `...` won't be selected when I want to copy paste multiple lines, while xonsh's `...............` will.
that's the difference I think.

**Comment by jaraco** [comment]
I'm having a related issue. I often wish to copy/paste a previous command, but if that command is indented (and those indents are detected as characters to be copied), it corrupts the syntax. Consider this session:

```
cherrypy master $ echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a
                  liqua."                                                                                                                    
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
cherrypy master $ echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a
                   
.................                   liqua."  
.................                                                                                                                            
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: "
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a
     ^
```

I'd like to disable the indentation of wrapped lines so that a command is true to its input and avoid issues like these.

Of course, in the example above, I could have used command history to retrieve that command, but there are other cases where that's not possible (different shells, cancelled commands, etc).

**Comment by jaraco** [comment]
I seem to recall that with older versions of prompt toolkit, this behavior wasn't present, so this wasn't an issue.

**Comment by scopatz** [comment]
This might be an issue we need to report upstream to PTK.

**Comment by anki-code** [comment]
I'm going to close this with reference to upstream [prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit).

Personally I'm using this in my `~/.xonshrc`:
```python
$MULTILINE_PROMPT=' '
```
