### ISSUE TITLE
xonsh builtin - nohup & disown

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2346]
Currently, when I want to run something in background with `nohup` like:
```
$ nohup py myserver.py -p 8080 &
```
After this, the server should still be running after `exit`. But we have:
```
$ exit
xonsh: there is an unfinished job
-----
[1]+ running: nohup py myserver.py .... (35438)
-----
Type "exit" or press "ctrl-d" again to force quit.
```

A "force quit" would kill the `myserver` process.

The server stay normal if I forcely close the terminal Tab, but it will be great if xonsh recognizes `nohup` "natively".

**Comment by astronouth7303** [comment]
What we really need is a disown.

**Comment by mitnk** [comment]
I never use disown. Seems similar things: http://unix.stackexchange.com/questions/3886/difference-between-nohup-disown-and

**Comment by astronouth7303** [comment]
`nohup` does a bunch of piping/signal stuff and is more about POSIX. `disown` does job control stuff and is more about the shell. Together (`nohup mybackground thing & disown`), they allow you to spin off processes.

**Comment by mitnk** [comment]
When using `nohup something &`, an extra `disown` would not be needed I guess.

**Comment by astronouth7303** [comment]
Strictly it would, since `nohup something` would still be a job.

**Comment by mitnk** [comment]
Practically, it's not :) At least for bash, nohup made the process (or process group) detached from the controlling terminal, and though it remains in jobs, there's not effects from the shell's exit, since SIGHUP is suppressed by nohup. The link I put above explains all of these details.

**Comment by astronouth7303** [comment]
Oh, bash no longer blocks exit when there's uncompleted jobs. It used to.

zsh does warn but exits anyway.

Both of them list `nohup` processes as jobs.

**Comment by anddam** [comment]
Worth mentioning #1246, I guess.

**Comment by adqm** [comment]
I don't know anything about xonsh after the big subprocess rewrite.  In older versions, this was pretty close to trivial (see [this patch](https://notabug.org/adqm/tako/commit/31fd57b331cd228c5949a7731ee66e363bbcf2ed)), so maybe there is a similarly simple patch here (though I tried just using that patch, and it failed because of weird Thread-handling thing).

**Comment by ion201** [comment]
Old thread, but I just came across xonsh and missed "disown" quite a bit. I have a basic working implementation for this feature which will just require some cleanup and more thorough testing before I submit a PR: https://github.com/ion201/xonsh/commit/d0262cc0189c6215fd1357f76a114eb36d316d91

**Comment by ion201** [comment]
PR #4090 is only for disown.

For nohup compatibility, it might be as simple as changing this function to send SIGHUP instead of SIGKILL though I don't usually use nohup so have not put much thought into it: https://github.com/xonsh/xonsh/blob/7fe7242/xonsh/jobs.py#L361-L367
