### ISSUE TITLE
vox image not found on OSX

### ISSUE THREAD

**Issue by brianmay** [xonsh/xonsh#2347]
```
$ vox new abc
Creating environment...
subprocess.CalledProcessError: Command '['/Users/brianmay/.virtualenvs/abc/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

Running this copy of python3.6 manually I get:

```
$ /Users/brianmay/.virtualenvs/abc/bin/python3.6
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/brianmay/.virtualenvs/abc/bin/python3.6
  Reason: image not found
Aborted (core dumped)
```

I believe this should work...

**Comment by mitnk** [comment]
Does venv work with bash?

**Comment by mitnk** [comment]
Could you try following command in bash to see if it works:
```
bash $ python3.6 -m venv foo
bash $ source foo/bin/activate
```
I think it may not related xonsh.

**Comment by brianmay** [comment]
The above lines work perfectly. I tried both with both versions of Python3.6 (I have no idea why the brew xonsh package for OSX installs its own version of xonsh - might be better to use the pip package). Odd, I wasn't expecting that...

I note that the python3.6 binary inside the chroot is normally a symlink:

```
$ /usr/local/Cellar/xonsh/0.5.9/libexec/bin/python3.6 -m venv foo                     
$ source foo/bin/activate
$ ls -l foo/bin 
total 48
-rw-------  1 brianmay  staff  2147 29 Mar 09:21 activate
-rw-------  1 brianmay  staff  1263 29 Mar 09:21 activate.csh
-rw-------  1 brianmay  staff  2427 29 Mar 09:21 activate.fish
lrwx------  1 brianmay  staff     9 29 Mar 09:21 python -> python3.6
lrwx------  1 brianmay  staff     9 29 Mar 09:21 python3 -> python3.6
lrwx------  1 brianmay  staff    51 29 Mar 09:21 python3.6 -> /usr/local/Cellar/xonsh/0.5.9/libexec/bin/python3.6
```

However via vox I don't get a symlink:

```
$ vox new abc
Creating environment...
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
subprocess.CalledProcessError: Command '['/Users/brianmay/.virtualenvs/abc/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
$ ls -l ~/.virtualenvs/abc/bin/
total 96
-rwxr-xr-x  1 brianmay  staff  13068 29 Mar 09:25 python
-rwxr-xr-x  1 brianmay  staff  13068 29 Mar 09:25 python3
-rwxr-xr-x  1 brianmay  staff  13068 29 Mar 09:25 python3.6
```

According to diff, this ``python3.6`` binary is identical to ``/usr/local/Cellar/xonsh/0.5.9/libexec/bin/python3.6``.  Ok, I wasn't expecting that.

So maybe it is an issue that python3.6 doesn't like being copied like this.

I am now going to delete the brew package, and install from pip - so I will use the brew version of Python3.6 - and report what happens.

**Comment by brianmay** [comment]
Ok, if I do that, it works. The file is still copied - not symlinked - which is odd. However it works. So I suspect the bundled version of python that comes with the brew package for xonsh is broken. Far easier just to use the pip package (and make sure you install stuff for Python 3.6 - so use ``pip3.6`` not ``pip`` as per instructions that sometimes appear).

**Comment by mitnk** [comment]
Yeah, when a lot of python (or pip) exist on system, weird thing would happen. I think `vox` of xonsh would use the python which launched xonsh for creating the virtualenv.

I use home brew, but never use it to install python - python is too complex a thing for me to use brew to handle. I always install Python via the pkg installer of python.org

**Comment by astronouth7303** [comment]
Vox does use the xonsh python to build venvs with. (It actually calls the `venv` module API, not spinning new processes.) Homebrew does do some kind of bundling (which nicely avoids the Python version of DLL hell, but is fairly unusual).

I should note #1588, which is about using other Pythons for the basis of the venvs.

What confuses me is why `venv` calls the wrong program, or why the program is broken. This might be a bug in homebrew or python.

**Comment by anki-code** [comment]
I can't repeat this on Linux and on MacOS:
```
xonsh --no-rc 
xontrib load vox
vox new qqq
ls -la ~/.virtualenvs/qqq/bin/
# python -> /Users/pc/miniconda3/bin/python
~/.virtualenvs/qqq/bin/python
# Python 3.8.3
# >>>
```
