### ISSUE TITLE
$COLOR_OUTPUT environment variable ignored?

### ISSUE THREAD

**Issue by adqm** [xonsh/xonsh#2351]
It seems that the `$COLOR_OUTPUT` environment variable is currently being ignored (see the conversation near https://gitter.im/xonsh/xonsh?at=58e2e760408f90be668640a7, confirmed on my own machine)

**Comment by adqm** [comment]
Indeed, the string `COLOR_OUTPUT` doesn't even show up in the codebase anymore (maybe got lost as part of the big subproc update?)

**Comment by astronouth7303** [comment]
It's not mentioned in [Environment Variables](http://xon.sh/envvars.html). What was it supposed to do?

**Comment by adqm** [comment]
Ah, sorry; I misread something.  The appropriate variable is called `$COLOR_RESULTS`, and it works just fine.
