### ISSUE TITLE
Operators not rendering

### ISSUE THREAD

**Issue by josh-janrain** [xonsh/xonsh#2354]
Taking xonsh for a test drive I'm unable to get operators to render:
![xonsh_no_operators](https://cloud.githubusercontent.com/assets/6332503/24914929/99a5d446-1e8a-11e7-8073-009f6eacf813.png)
Guessing this is just a config issue on my end but haven't been able to find anything in the docs, using prompt_toolkit.

**Comment by astronouth7303** [comment]
What's the output of `xontrib`? Did you choose a theme?

**Comment by josh-janrain** [comment]
@astronouth7303  thank you very much for pointing me in the right direction:
![xonsh_rocks](https://cloud.githubusercontent.com/assets/6332503/24925611/a8450dc8-1ead-11e7-9d70-b86b9ad64a22.png)
I'm extremely excited about xonsh :)
