### ISSUE TITLE
xonsh --rc <rcfile> doesn't load properly

### ISSUE THREAD

**Issue by chiahaoliu** [xonsh/xonsh#2356]
Hi,

I was trying to run desired control file with ``--rc`` option. I created the ``xonshrc`` and the ``xonshrc.xsh`` files, both with a simple ``print('hi')``, and place them after ``--rc`` and tried to run both of them.

``xonsh`` can be launched without error but the ``xonshrc`` file wasn't loaded.

I also confirmed if I move the ``xonshrc`` file into ``home`` then the print statement can be run successfully.  

att: @CJ-Wright

**Comment by laerus** [comment]
hey @chiahaoliu thanks for the report!

can confirm that `--rc` doesn't work
cannot confirm the second part that moving xonshrc to home folder solves this.

**Comment by gforsyth** [comment]
Hi @chiahaoliu -- I've got a fix for this in #2359 if you'd like to try that out.

**Comment by gforsyth** [comment]
#2359 was merged into master -- please ping this issue if it's still a problem.  And thanks for reporting!
