### ISSUE TITLE
Proposal - Set Unthread-able as Default When Calling Programs

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2361]
Hi all,

As you may notice, several issues recently are related with run program in thread [1]. Besides the WIP slug, I'm thinking what we can do for now.

I've tried changing default from threadable to unthreadable. This way, we could fix all these issues, without having to update predictors-threadable-dict every time we found one more unthreadable program. I've manually tested this change with varies cases, and haven't found any breaking effects.

So ideas on this proposal? Or @scopatz did I missed something here?

[1] using the same list of @adqm pointed out in email: #2353 #2348 #2358 #2355

**Comment by laerus** [comment]
+1

**Comment by melund** [comment]
Wouldn't this mean capturing stdout would be off by default?

**Comment by mitnk** [comment]
@melund this may what I missed. Could you put more details about it here? Is the "stdout capturing" something related history? or something like `foo = $(ls -l | wc -l)`?

**Comment by astronouth7303** [comment]
I believe under the current implementation, threading is required for piping, capturing stdout, running multiple aliases in the same job, and generally other things shells are expected to do.

**Comment by laerus** [comment]
xonsh captures everything by default, something bash (and others?) don't do but we like it, you must be able to opt-out though. 

Non-blocking looping over `!()` (`iterrraw`) is based on threads too, a killer feature imo and one that probably noone uses (has some issues still).

**Comment by laerus** [comment]
@mitnk no this is not related to history at first. `HiddenCommandPipeline` and `CommandPipeline` capture stdout.

**Comment by mitnk** [comment]
Thanks for comments guys.

@laerus yes, `!()` seems break when set unthreadable as default. i.e. the behavior of the following changed:
```
for x in !(ls -lh):
    print('=={}=='.format(x))
```
And this is only case broken by this change. (`$()`, `@$()` are not affected).

@astronouth7303 piping like `ls`, `ls | wc | cat | wc` would work as before. multiple aliases in same job also works:
```
$ ls | cat | mycat | cat | mycat | wc | mycat
86      87     926
$ tail .xonshrc
def _cat(args, stdin=None):
    for line in stdin:
        print(line.strip())
aliases['mycat'] = _cat
```

@gforsyth So do you mean `!()` by saying "It would break several existing bits of functionality", I haven't found any other breaking cases.

I'm now not going to push the PR to merge, but collect the background info for it. If you know any cases break by changing unthreadable as default, you could let me know.

**Comment by mitnk** [comment]
if `$()` is the only breaking case, maybe we could make these case as threadable (though I'm not sure how hard/easy that would be) while keeping unthreadable as default. This may work?

**Comment by laerus** [comment]
i think our best chance is `slug`. Its still pretty small so its clean and readable, any coredev who can help @astronouth7303 would also benefit from knowing how this works so more people can contribute after slug gets merged.

**Comment by gforsyth** [comment]
Hey @mitnk -- I thought, as @astronouth7303 did, that there would be some extra issues with piping and aliases.  As it stands, it looks like the two breakages are `!()` and also storing stdout

**Comment by mitnk** [comment]
yeah, storing stdout to history is a breakage too. things are more complex than I thought.

**Comment by gforsyth** [comment]
> things are more complex than I thought.

New xonsh t-shirt slogan
