### ISSUE TITLE
gitstatus error on tty

### ISSUE THREAD

**Issue by arkhan** [xonsh/xonsh#2363]
hello i have this error on tty
![photo_2017-04-26_20-11-13](https://cloud.githubusercontent.com/assets/3141865/25463474/2ad98308-2abc-11e7-952a-debf28a047e4.jpg)

Thanks

**Comment by gforsyth** [comment]
Hey @arkhan -- thanks for reporting!  This looks like a problem with your encoding.  What's the value of `locale`?

**Comment by arkhan** [comment]
I have this
![selected_window_20170427095724](https://cloud.githubusercontent.com/assets/3141865/25489543/bc6d36a2-2b2f-11e7-8895-e74ee48ea418.png)

**Comment by gforsyth** [comment]
Hmm... well, that seems correct. I wonder why it's complaining about `ascii` then...

Can you also post the output of `xonfig` please?

**Comment by arkhan** [comment]
sure 
![selected_window_20170428090901](https://cloud.githubusercontent.com/assets/3141865/25532256/6312fa7e-2bf2-11e7-97d9-20034f2ba40b.png)

**Comment by arkhan** [comment]
What about this..?

**Comment by laerus** [comment]
Do you get this with other cases as well or only `gitstatus`?

**Comment by arkhan** [comment]
@laerus yes only with gitstatus

**Comment by laerus** [comment]
i think gitstatus uses some emojis and the decoding used here is 'ascii' as it seems from the Exception, not sure why yet.. will try to dig more.

**Comment by astronouth7303** [comment]
Linux VT comes up as ASCII. This is the same error as if you try to put SPIRAL SHELL in your prompt and then use xonsh from the VT.

Known issue, don't know if we have a solution at this time.

**Comment by laerus** [comment]
Maybe we can handle the error a little better and not crash the shell from non-core parts like gitstatus.

**Comment by arkhan** [comment]
Before I had an error it seems to report in #676

**Comment by laerus** [comment]
what if you set `$XONSH_ENCODING_ERRORS='ignore'` in your `~/.config/xonsh/config.json` or `.xonshrc` @arkhan ?

**Comment by arkhan** [comment]
@laerus work's but don load my conf, have this

![photo_2017-05-04_15-11-00](https://cloud.githubusercontent.com/assets/3141865/25723042/16ef0d7e-30dc-11e7-9df9-599bf6fa46dc.jpg)

**Comment by anki-code** [comment]
Hey @arkhan could you please test the latest version from master:
```
pip install -U git+https://github.com/xonsh/xonsh
```
Does this issue still actual?

**Comment by arkhan** [comment]
@anki-code not already solved

Thanks
