### ISSUE TITLE
tab completion with arrow selection like zsh

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2364]
Is there a way in xsh to enable tab completion like the following where it lets me select from the list with the arrow key buttons? (up and down works too if there are many items)

Here is a video of what I mean:

[![zsh tab completion](https://cloud.githubusercontent.com/assets/55744/25497561/06bfe6aa-2b53-11e7-831f-233ef80623a9.png)](https://youtu.be/ew51b7n7QOQ)

Also perhaps there is a color scheme like the one in the video?

**Comment by astronouth7303** [comment]
Completing file names should be default. There's a variety of color schemes available.

**Comment by ahundt** [comment]
The names appear but the arrow doesn't work by default, sorry if that wasn't clear.

**Comment by gforsyth** [comment]
Hi @ahundt -- up and down arrow keys should work with prompt_toolkit, but they don't support left-right as of yet.  See #917

**Comment by ahundt** [comment]
Thanks for the link, am I correct that the issue is closed but the functionality doesn't yet exist?

**Comment by gforsyth** [comment]
@ahundt, I closed the previous issue since it's an upstream thing. But yeah, no right-left arrows yet.

**Comment by ahundt** [comment]
Oh I see that functionality is part of python-prompt-toolkit rather than xonsh 
https://github.com/jonathanslenders/python-prompt-toolkit/issues/147

ok fair enough, thanks!

**Comment by ahundt** [comment]
Ah, these already exist:
```
$XONSH_HISTORY_MATCH_ANYWHERE = True
$COMPLETIONS_CONFIRM = True
```
https://xon.sh/envvars.html#completions-confirm

Any chance these or some even better set of automation options could be enabled by default? :-)

**Comment by gforsyth** [comment]
Hey @ahundt -- I'm definitely game for setting `$COMPLETIONS_CONFIRM=True` as the default -- if we get a quorum of @xonsh/xore to agree to that we can change the default.

I'm a little more wary of the match anywhere, only because it's more computationally intensive, but I'm open to being convinced if you want to run some profiling on search timings with long histories!

**Comment by scopatz** [comment]
I am in favor of `$COMEPLETIONS_CONFIRM = True` if someone wants to put in a PR

**Comment by anki-code** [comment]
I also use True value and PR is here.
