### ISSUE TITLE
coreutils cat broken

### ISSUE THREAD

**Issue by brianmay** [xonsh/xonsh#2365]
```
$cat
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13061, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12896, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xoreutils/cat.py", line 58, in cat
    o = _cat_single_file(opts, i, stdin, stdout, stderr, line_count)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xoreutils/cat.py", line 21, in _cat_single_file
    _r = r = f.readline()
AttributeError: 'NoneType' object has no attribute 'readline'
```

Lets try:

```
$cat -
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13061, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12896, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xoreutils/cat.py", line 58, in cat
    o = _cat_single_file(opts, i, stdin, stdout, stderr, line_count)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xoreutils/cat.py", line 21, in _cat_single_file
    _r = r = f.readline()
AttributeError: 'NoneType' object has no attribute 'readline'
```

**Comment by laerus** [comment]
I feel like we should remove xoreutils from core xonsh, they are poorly tested and a small burden for maintaining xonsh, they fit better in a xontrib anyway. i don't think others shells provide such builtins (`pwd` being an exception). @xonsh/core-developers feelings?

**Comment by gforsyth** [comment]
Aren't they already a xontrib?  Or do you mean that they should live in a separate repo?

**Comment by laerus** [comment]
yeah, a separate repo would be a good idea.

**Comment by adqm** [comment]
I don't quite remember how they actually got put in.  When I left off, they were still marked as WIP and had some real deficiencies.  Maybe @scopatz worked on them after that?  Totally in favor of getting rid of them.

**Comment by melund** [comment]
Coreutils has its value especially on windows where launching subprocesses are extremely heavy and where many of the standard core utilities are either missing or have very limited functionality. Having coreutils means that xonsh scripts will be a bit more cross-platform. I think this was also some of the reason @adqm started the work. 

If some of the coreutils are not working yet, I think we can just disable them until we can find an implementation that works. Otherwise, just disable the coretuilts xontrib by default. I am not in favor of moving it out of the repo.

**Comment by astronouth7303** [comment]
It's currently a bundled xontrib--Managed as a xontrib, but shipped with xonsh. I think that's the perfect place for it. This is important enough that I think it should be bundled, but it shouldn't be core.

I would only want to move it out if someone wanted to champion it, and make a really strong, on-going effort to maintain and improve it.

**Comment by laerus** [comment]
my main concern is that they 0% tested, (except from `which`)
each of the scripts are <50 loc, it would be easy for someone to re-implement 
some parts specific for what they want. basic `cat` functionality is like 2loc right?

is any core-dev using them?
