### ISSUE TITLE
source python venv error

### ISSUE THREAD

**Issue by jkw** [xonsh/xonsh#2367]
Can't activate virtual environment:
`
jkw@zepto ~/repos/madmin $ source py361/bin/activate
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: py361/bin/activate:4:14: ('code: {',)
deactivate () {
              ^
`

**Comment by gforsyth** [comment]
Hey @jkw -- thanks for reporting!  So there are a few things going on here.  

First, `source` in `xonsh` is for `xsh` or `py` files and `activate` isn't written in `xsh`. You instead probably want to use `source-bash`.  

That said, there's also built-in venv management via [Vox](http://xon.sh/python_virtual_environments.html)

**Comment by jkw** [comment]
Oh, my bad. Just found xonsh yesterday, and as a Python enthusiast I thought I'd give it a fair try. Been using zsh and oh-my-zsh for a long time. :) I'll try the vox thing out, thanks for the tip. You can close the issue if you want.

**Comment by gforsyth** [comment]
No worries! Let us know if you have any other questions. You can post here, SO or find us on gitter
