### ISSUE TITLE
xonsh is slow after startup (some delay in input after starting)

### ISSUE THREAD

**Issue by lazmol** [xonsh/xonsh#2369]
Hello,
xonsh starts quite fast but then it is busy for seconds and it is quite annoying. So what happens is that I start up a terminal, xonsh start quickly and I can type for a second or so but then the input lags for a couple seconds, only then I can continue typing.
What I checked so far is:
-prompt_toolkit is installed (that is my SHELL_TYPE)
-in another thread there was something like parser_table.py was missing, I checked that and I have it.
-I source my old bashrc with the config.json (I disabled the foreign shell) but the delay in input still persists
So could you give me a hint what to check? Or what could be the reason for the laggy input after startup? I am not sure it is because of xonsh either (but there is some chance as bash works fine)...still some help would be appreciated.
I am using xonsh 0.5.9 on arch linux setup from pip:
`$ xonsh -V
xonsh/0.5.9
$ which xonsh
/home/laco/anaconda3/bin/xonsh
`
Thanks,
Lazlo

**Comment by laerus** [comment]
Hey @lazmol thanks for messing with this! 

There is a helpful cli argument to xonsh that shows various timings
you can run it with ``xonsh --timings``.

I remember there was an error with the `parser_table.py` on arch not getting picked up.

We use threads to load the yacc parser,
[this](https://github.com/xonsh/xonsh/blob/master/xonsh/parsers/base.py#L347) may also be part of the lag.

btw when in xonsh you can run `xonfig` to get platform/build related info!

**Comment by melund** [comment]
I don't think `xonsh -timings` will help you much. It just gives some insight to what happens until the prompt is shown. I recall that there are a few libraries which are loaded on separate threads, to prevent them from slowing down xonsh startup. 

`pkg_resources` from setuptools is, if I recall correctly, one of them. Maybe that package is taking extra long time on your machine preventing prompt_toolkit from accepting input. That is just a guess. I really think @scopatz is the right person to ask here.

**Comment by lazmol** [comment]
Thanks @laerus and @melund for the hints.
1. Output of xonfig:
```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.5.9                |
| Git SHA          | 2ae5218              |
| Commit Date      | Mar 15 12:06:26 2017 |
| Python           | 3.6.1                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.14               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```
2. timings with prompt_toolkit
```
$ xonsh --timings
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.027   |   0.027   |
|post_execer_init  |   0.073   |   0.047   |
|on_pre_rc         |   0.073   |   0.000   |
|on_post_rc        |   0.073   |   0.000   |
|on_ptk_create     |   0.140   |   0.067   |
|on_post_init      |   0.140   |   0.000   |
|on_pre_cmdloop    |   0.140   |   0.000   |
|on_pre_prompt     |   1.617   |   1.477   |
|------------------|-----------|-----------|

```
3. timings with prompt_toolkit
```
$ xonsh --timings
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.027   |   0.027   |
|post_execer_init  |   0.073   |   0.047   |
|on_pre_rc         |   0.073   |   0.000   |
|on_post_rc        |   0.077   |   0.003   |
|on_post_init      |   0.090   |   0.013   |
|on_pre_cmdloop    |   0.090   |   0.000   |
|on_pre_prompt     |   0.090   |   0.000   |
|------------------|-----------|-----------|
```
With prompt_toolkit on_pre_prompt takes much longer 1.6s than with readline but I still get some delay with readline type too. The only difference is that the delay is not in the input but in the output, e.g. i type ll+enter then it still takes what I type but it takes the shell some seconds to return me the output from ls -l. So the problem is still there even with readline.

4. How can I check the delay with yacc parser? Shall I measure the time it spends in that while loop by modifying the python file?

5. Which libraries are loaded on separate threads?

**Comment by lazmol** [comment]
I found the issue.
I don't think I am too much of a terminal user, but I noticed I had 565 xonsh-<sessionid>.json files in my  $XONSH_DATA_DIR. Removed them and viola, xonsh has no delay anymore!
Related to history, how can I see all my history from previous terminal sessions? The history command just shows the history of my current session, which is not so useful I think, as I'd like history to store what I did a week ago in whatever session and be able to grep for it. Could you help/fix these issues?
Cheers

**Comment by laerus** [comment]
you can view all history with `history show all`. `history show --help` may clear some things out

**Comment by lazmol** [comment]
Ah thanks, and I am sorry I missed the all option, even though it is in the[ tutorial here too: ](http://xon.sh/tutorial_hist.html). But how can I create an alias for this: history | grep -i ?
Then, only the original issue remains, do you see slowish/delays in xonsh startup as well, when there are lots of history json files in the $XONSH_DATA_DIR?

**Comment by gforsyth** [comment]
Hi @lazmol -- yes, I do notice a delay in startup time when there are a bunch of `.json` files in history. 

Going to have to investigate this, since the history files are loaded on a separate thread, so it's strange that they would impact prompt start time. Something may be blocking that we don't expect to block.

**Comment by anki-code** [comment]
Hi @lazmol !
Could you please install xonsh from master and try again? Install:
```bash
pip install -U git+https://github.com/xonsh/xonsh
```
If you still see the lags please run:
```bash
# bash
COMMANDS_CACHE_SIZE_WARNING=1 xonsh --timings
```
and post here the output please. If no please close the issue.

**Comment by lazmol** [comment]
Hi @anki-code,

thanks, got much faster compared to 2,5 years ago. The timings say 0.5s startup compared to 1.6s before.

**Comment by VicPetrov** [comment]
IF you're having this on WSL2 Launching xonsh with elevated priviledges helps.
