### ISSUE TITLE
xonsh not working on cygwin

### ISSUE THREAD

**Issue by fmv1992** [xonsh/xonsh#2370]
xonsh is not working on cygwin:

```
data_utilities/tests [develop●] » echo $XONSH_SHOW_TRACEBACK
True
data_utilities/tests [develop●] » xonsh --version
xonsh/0.5.1
data_utilities/tests [develop●] » xonsh
user@computer ~/path $ ls
                               [...] hangs [...]
```

some normal commands like ls, l, rm, etc remain in a irresponsive state. Ctrl + c does not work.

Python commands are working though:

```
/tmp » xonsh
user@computer /tmp $ print('hey')
hey
user@computer /tmp $
```

Finally commands can be taken out of the hanging state by using Ctrl + Z.

When quitting one of those sessions full of hangs I got:

```
xonsh: there are unfinished jobs
-----
[7]+ stopped: ls -a (10448)
[6]- stopped: rm ./bool_0.png (11000)
[5]  stopped: ls (10352)
[4]  stopped: ls (9600)
[3]  stopped: ls (10984)
[2]  stopped: ls (10080)
[1]  stopped: ls (9536)
```
(I have the same problem with the newest version and versions 0.4.x)
Please let me know how can I be of more help.

I can't wait to have it working on my computer : )

Best,

Felipe.

**Comment by laerus** [comment]
hey @fmv1992 thanks for opening this!

i think Cygwin was always one of xonsh's weak spots.
We've gone back and forth about how we manage subprocesses trying to be
cross-platform and all and the main lesson was:
> Things are more complicated that we expected.

(it's going to be on the xonsh t-shirt too)

Jokes aside there is a major effort going on to fix this.
The best i can give you right now is to roll back to a xonsh version <=0.4.7
and see if this works out.

**Comment by astronouth7303** [comment]
Unfortunately, xonsh/slug#5

**Comment by fmv1992** [comment]
Can you outline as to what the problem is?

I'm willing to contribute even though I have no experience with designing a shell program.

**Comment by anki-code** [comment]
I'm going to close this because we have many changes since 2017. Please open the separate issues with repeatable examples.
