### ISSUE TITLE
Alias commands always run in subprocess mode

### ISSUE THREAD

**Issue by Danmou** [xonsh/xonsh#2373]
If I define an alias running som python code as so:
    `aliases['pl'] = 'from pylab import *'`
running the alias results in xonsh trying to execute a command called `from` with arguments `pylab import *`.
Even if the alias is defined as:
    `aliases['pl'] = '@(from pylab import *)'`
xonsh will try to execute a command called `@(from`.

**Comment by laerus** [comment]
hey @Danmou, yeah string aliases currently run only in subproc mode,
but you can have an alias that is a python function and do pretty much w/e you want,
for example `aliases['hello'] = lambda args, stdin=None: print('Hello Xonsh')`

**Comment by Danmou** [comment]
Ok, yes I am aware that python functions can be used as aliases but in this case I would like to import a library as in my example, which I can't do from a function. Any idea for how to achieve this?

**Comment by adqm** [comment]
I don't know of any way that isn't a hack, but something like the following can work:

```
hartz@desk ~ $ def _foo(a, s=None):
..............     exec('from math import *', __xonsh_ctx__)
..............     
..............     
..............     
hartz@desk ~ $ aliases['foo'] = _foo
```

**Comment by astronouth7303** [comment]
... you can totally have imports inside functions. If you can't, that's a bug.

**Comment by adqm** [comment]
You can have imports inside of functions, but you have to work around the fact that those imports are locally scoped (I don't know a way to make them global without resorting to something like the above, or maybe there's a way by invoking something from `importlib`).

**Comment by Danmou** [comment]
@adqm thanks that works perfectly :+1:

Regarding the original issue, that string aliases always run in subprocess mode, is this a bug? I would expect an alias to work like any string I enter in the xonsh prompt.

**Comment by astronouth7303** [comment]
@Danmou I think that's by design, since the arguments get appended.

@adqm You can do it with introspection, too. The exact logic depends on what you know and what you're expecting.

**Comment by laerus** [comment]
even with importlib you would have to do something like:
 `globals()['module'] = importlib.import_module('module')` 
inside the alias function.

Is there any reason we don't pass string aliases through the xonsh execer?

**Comment by astronouth7303** [comment]
@laerus I assume it's the args thing.

If the alias `spam` expands to `foo bar`, then `$ spam foobar` becomes `foo bar eggs`. If your alias involves Python code, this will just fall apart.

I think we should make the syntax to define aliases less clunky.

**Comment by anki-code** [comment]
Functions widely used as aliases. This issue looks solved and should be closed.
