### ISSUE TITLE
Password manager support

### ISSUE THREAD

**Issue by arkhan** [xonsh/xonsh#2374]
hello,
It's possible to add support for pass:

https://www.passwordstore.org/

Thanks

**Comment by adqm** [comment]
This seems related to the `xclip` problem that was posted earlier (`pass` works without the `-c` flag, which pipes its output to `xclip`).

**Comment by astronouth7303** [comment]
We won't have specific hooks for `pass` in core; that belongs in a xontrib.

Is there a problem with using `pass`?

**Comment by arkhan** [comment]
add auto-completion for pass

**Comment by astronouth7303** [comment]
We support using bash completions. I agree, a xonsh-native completion would be nice.

**Comment by anki-code** [comment]
Hello! 
This functionality looks very welcome in xontrib. The best way to create xontrib is [to use cookiecutter template](https://github.com/xonsh/xontrib-cookiecutter).

This issue looks not related to core xonsh functionality. Please close this issue.
