### ISSUE TITLE
command line can't recognize .com executables under windows

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#2375]
I think .com extension does not work as intended. This requires to call command with extension:
```
$ chcp 65001
xonsh: subprocess mode: command not found: chcp
$ chcp.com 65001
Active code page: 65001
$ $PATHEXT
['.COM',
 '.EXE',
 '.BAT',
 '.CMD',
 '.VBS',
 '.VBE',
 '.JS',
 '.JSE',
 '.WSF',
 '.WSH',
 '.MSC']
```

When cmd.exe can:
```
$ cmd /c chcp
Active code page: 65001
```

**Comment by gforsyth** [comment]
Hey @andry81 -- thanks for reporting this and sorry for the delay in responding! 

I'm a bit lost when comes to the windows stuff, but hopefully one of the more windows-savvy devs can chime in here.

**Comment by astronouth7303** [comment]
That's.... not right. I thought xonsh deferred this to the OS, but I would have to look at the program resolution code to understand it.

**Comment by gforsyth** [comment]
@andry81 -- do any of the other path extensions in `PATHEXT` work or not work? Is it just `com` that's causing trouble?

**Comment by andry81** [comment]
xonsh must read this variable as cmd.ex does:
http://environmentvariables.org/PathExt

**Comment by melund** [comment]
I can't reproduce this problem. @andry81 Do you mind trying this out on the master branch?

**Comment by andry81** [comment]
in 0.5.10.dev1 it works now
