### ISSUE TITLE
"dir *" hangs in windows

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#2376]
For example, `echo *` works as intended.

**Comment by gforsyth** [comment]
Hey @andry81 -- thanks for reporting! I think this is because `dir` conflicts with the python builtin and we always defer to Python in these ambiguous cases. It shouldn't hang, though.

Does `dir .*` work?

**Comment by andry81** [comment]
I tried to select `dir .*` output, but got hit another bug with console windows redraw glitch.
Is that command intended to print not empty directory list of files? If so, then no it does not work. Prints empty list.

**Comment by andry81** [comment]
Seems the version `0.9.6` in `python 3.7.3 x86/x64` does work now.
