### ISSUE TITLE
[RFC] Add proper logging

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2377]
Currently the logging that is produced from xonsh is either
python exceptions, ply logging, a few `print` to stderr functions.

When trying to hunt down a bug using `print` is a pain
cause of the interactive nature of xonsh. I usually
add some logging logic with debug level messages
but then i remove them if there is a PR.

i am not so familiar with logging best practices,
anyone has any comments on how to structure logging in xonsh?

**Comment by astronouth7303** [comment]
For in-dev debugging, you may find [q](https://pypi.python.org/pypi/q) to be helpful.

For more in-depth logging, most projects do use the `logging` standard module, despite how un-Pythonic and complex it is. I suspect we want to test for what kind of overhead it has (even in a noop configuration) before we use it wide-spread, though.
