### ISSUE TITLE
Resize in mc (ncurses?) not working

### ISSUE THREAD

**Issue by ulno** [xonsh/xonsh#2383]
```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.5.9           |
| Python           | 3.5.3           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.9           |
| shell type       | prompt_toolkit  |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | Ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```
I am trying to use mc (Midnight Commander, https://midnight-commander.org/) and its editor mcedit in xonsh. It works in general, but resizes of the terminal window (xfce4-terminal) after starting mc or mcedit are not reflected. The size stays the same. When executing bash from xonsh and then mc, the resize works instantaneously.

Some ncurses updates getting lost here?

Example of not/wrongly resized window:
![image](https://cloud.githubusercontent.com/assets/72434/26106451/f1264fd0-3a13-11e7-9a31-48d00a6465ea.png)

**Comment by DanielFGray** [comment]
I too experience this, seems like xonsh eats SIGWINCH without passing it to child processes

**Comment by laerus** [comment]
Hey guys thanks for the feedback! Can you try to reproduce with readline?

**Comment by ulno** [comment]
Same issues when running xonsh --shell-type readline

Both methods (readline and prompt_toolkit + start of an ncurses application) destroy mouse selection in the terminal where it was executed - even when leaving xonsh.

**Comment by ulno** [comment]
Interesting observation.
byobo (based on tmux) resize seems to run correctly in xonsh.
If I start byobo in xonsh and mx in byobu (which opens bash), mc resizing works correctly.
Starting byobo, and then xonsh in it and then mc shows same issues as before.

**Comment by ulno** [comment]
Ranger (consoel based file manager) actually works too.

I wonder, if ncurses works but slang based programs don't.

**Comment by ulno** [comment]
neovim does also not work and eats most of special keys and mouse events (just showing messed up characters) - similar to #2461

**Comment by gforsyth** [comment]
Hi @ulno -- thanks for reporting these.  Ncurses and slang tend to mess things up for us. 

Two things: 
1. could you upgrade xonsh to the latest released version?
2. can you add the following to `xonshrc` and see if the issues persist?

```
from xonsh.commands_cache import predict_false
__xonsh_commands_cache__.threadable_predictors['neovim'] = predict_false
__xonsh_commands_cache__.threadable_predictors['mc'] = predict_false
```

**Comment by ulno** [comment]
Just pip installed xonsh 0.5.12 into my virtual environment added suggested lines (and one for nvim and edit - I have my own edit wrapper - too to ~/.xonshrc) and hooray, yes, I can confirm that this solves all issues for mc and nvim - resize, mouse, and keys. I assume it solves the issues from the other thread, too.

So, how to go from here? Just a nice documentation somewhere: if you want to use slang or ncurses apps in xonsh: add these lines to ~/.xonshrc
Or, can we do something more sophisticated and intuitive for other users (autodetection, preload library for slang and curses which sets this if used)?

**Comment by scopatz** [comment]
Hi All, We probably should add these to the default list of known exceptions.

**Comment by ulno** [comment]
it would still not work for something like my edit script - but maybe as temporary workaround. You probably need to add it for nvim, vim, emacs, and mc
I can confirm it works for fzf and ranger without modification.
Not sure what other ncurses/slang command line programs need to be detected.
The edit script could be also covered by documentation. Maybe there should be a template xonsh script for starting a shell program with predict_false. Maybe even some kind of prefix-wrapper, so you could just try out if indexing helps:
```
# run command with predict_false
cursed_fix mc
```

**Comment by ulno** [comment]
need to add nano to the list
