### ISSUE TITLE
Autocomplete problem

### ISSUE THREAD

**Issue by riwogo** [xonsh/xonsh#2386]
Hi please watch the gif (I hit tab in each step for autocomplete or suggestions after I write `rm -r` and I don't write even a letter of file names): [Gif](http://m.UploadEdit.com/ba3s/1495530471169.gif)

**Comment by gforsyth** [comment]
Thanks for reporting @riwogo !

**Comment by adqm** [comment]
Hi @riwogo, can you include the output of `xonfig` here?

I'm interested to know whether this is an issue with the prompt-toolkit shell, with the readline shell, or with both.  Does this behavior occur with both `xonsh --shell-type prompt_toolkit` and `xonsh --shell-type readline`?

**Comment by riwogo** [comment]
Here's my xonfig:

+------------------+----------------------+
| xonsh            | 0.5.9                |
| Git SHA          | 2ae5218              |
| Commit Date      | Mar 15 12:06:26 2017 |
| Python           | 3.5.2                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

**Comment by rossnomann** [comment]
@riwogo image is no longer available.

**Comment by riwogo** [comment]
@rossnomann here's the image: [https://ibb.co/khjwFF](url)

**Comment by scopatz** [comment]
I can no longer reproduce this issue on xonsh 0.7.3 with the readline shell. Is anyone else still seeing it?

**Comment by scopatz** [comment]
Also, I noticed @riwogo was using v0.5.9, and I know we have had bug fixes for this since then.

**Comment by gforsyth** [comment]
I'm closing this out.  If the issue arises, please open a new issue.  Thanks!
