### ISSUE TITLE
How to deactivate virtualenv

### ISSUE THREAD

**Issue by diazgilberto** [xonsh/xonsh#2388]
I'm able to activate with `source-bash dj-1-9-tutorial/bin/activate` but how to deactivate. The `deactivate` command doesn't work.

- OS X El Capitan 10.11.1
- Xonsh xonsh/0.5.9

**Comment by astronouth7303** [comment]
Use [Vox](http://xon.sh/python_virtual_environments.html).

**Comment by diazgilberto** [comment]
Interesting!!!
Going ahead to learn this stuff. Thank you, @astronouth7303.

**Comment by diazgilberto** [comment]
How do you link a project to a virtualenv. Or you just cd to the root of the project, `vox workon <venv_name>` and that directory become linked to that virtualenv?

**Comment by astronouth7303** [comment]
Vox applies no policies or opinions with regards to how directories are "linked" to virtualenvs. You have to manually activate and deactivate them every time.

There are [3rd party xontribs](http://xon.sh/xontribs.html) that _do_ apply such policies, but they are not supported by those developers, not the xonsh team.

**Comment by diazgilberto** [comment]
I need help. I just `pip uninstall xonsh` to try something, and now my terminal doesn't open with zsh wither bash. Where I can manually modify the `chsh`.

**Comment by astronouth7303** [comment]
`/etc/passwd` is where it's kept.

**Comment by PaulReiber** [comment]
Gilbert you're going to need to repair this by logging in as some other
user, escalating to root, and then using chsh to change the shell of your
regular user.


Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by diazgilberto** [comment]
I ended up formatting the laptop and installing Sierra.
