### ISSUE TITLE
Current release 0.5.9 or 0.5.10?

### ISSUE THREAD

**Issue by ilovezfs** [xonsh/xonsh#2389]
On PyPI the latest version is 0.5.10 but on GitHub the latest release is marked as 0.5.9. Which is actually the current stable version?

**Comment by laerus** [comment]
Fixed, i don't think our `release.xsh` performs a github release.

**Comment by ilovezfs** [comment]
@laerus thanks! It would be great if it did. There is an API for doing that, FWIW.

**Comment by astronouth7303** [comment]
Yeah, it's on the todo list (#1793).

**Comment by ilovezfs** [comment]
@astronouth7303 :cool:
