### ISSUE TITLE
xonsh without colorized prompt

### ISSUE THREAD

**Issue by mitzkia** [xonsh/xonsh#2393]
Hi,

Maybe it is a duplicate, but I did not found similar issue. 

I have installed a fresh xonsh with pip, and also some other relevant packages
```
sudo pip3 install -U xonsh
```
After that I walked through the xonfig wizard. Then I am exiting from xonsh and entering it again and got the following prompt. 

I am missing the colors of the prompt. I have got only such code:
```
{BACKGROUND_#333}{WHITE} ~ {NO_COLOR}{#333}{NO_COLOR}
```
![2017-05-30-181853_3840x2141_scrot](https://cloud.githubusercontent.com/assets/2952076/26593479/7ac5d0e8-4564-11e7-9bfe-d3b84a9dfe67.png)

Maybe I am missconfigured something?
Terminal emulator is: tilix
original shell: bash

Thanks

**Comment by gforsyth** [comment]
Hi @mitzkia -- thanks for reporting! I wonder if one of the `xontribs` you are using is responsible for this. Could you try to selectively disable them and see if the prompt is fixed? 

You can also try to install `pygments` and see if that fixes the issue.

**Comment by gforsyth** [comment]
And I would start by disabling the `powerline` xontrib, as I think that's the most likely culprit

**Comment by mitzkia** [comment]
Hi @gforsyth, after installing the pygments package it started working. 
Now I have colorized prompt again :). 
I think the issue can be close. Should I close it?

**Comment by gforsyth** [comment]
Go for it!
