### ISSUE TITLE
0.5.10 release has dev1 suffix

### ISSUE THREAD

**Issue by jhdulaney** [xonsh/xonsh#2400]
Hey, y'all, the 0.5.10 release is suffixing dev1, which is throwing off my rpm build for Fedora.  You also can get it when doing a pip install.

**Comment by astronouth7303** [comment]
@laerus You packaged this release. I remember discussing it briefly, but not coming to any conclusions.

Is this a bug on how this specific version was packaged, or setup.py generally?

**Comment by laerus** [comment]
i think the problem was the sphinx crashing and creating a dirty git repo, then our setup.py messes with the version specified on `__init__.py` suffixing it with dev if the repo is dirty.

i think we should do a 0.5.11 release?

**Comment by astronouth7303** [comment]
It's been about a week.

**Comment by jhdulaney** [comment]
I'm +1 on a .11 release because that would be less effort than modifying my rpm spec file twice.

**Comment by gforsyth** [comment]
There's a 0.5.12 release out now, sans suffix.  Sorry for the trouble!

**Comment by jhdulaney** [comment]
Thanks!
