### ISSUE TITLE
Poor choice of text colors on welcome screen

### ISSUE THREAD

**Issue by njsmith** [xonsh/xonsh#2401]
I just tried starting up xonsh on a whim, and got this:

![foo](https://user-images.githubusercontent.com/609896/27001031-d7939176-4d74-11e7-866e-d671282d1e4d.png)

I think there might be some text there? That I might want to read? It's hard to say. I'm guessing the vibe you were going for was like... "welcoming"? but it landed on "eyestrain".

(Possibly this is my fault for using an almost-but-not-quite-white background for my terminal.)

**Comment by gforsyth** [comment]
Hey @njsmith -- thanks for reporting! And sorry about the eyestrain. 

Yeah, there's definitely text there, and it's definitely white. We should change that.

**Comment by gforsyth** [comment]
Ooooh, there might be a few issues here, actually. Do you have either/both of `prompt_toolkit` and `pygments` installed in your virtualenv? If you do, xonsh will use your terminal colors which should hopefully avoid the problem above.  

But we should fix the defaults in any case to be kinder to a range of terminal background colors.

**Comment by njsmith** [comment]
I do have both pygments and prompt_toolkit installed in that same
virtualenv, yeah. Are you saying that should have prevented the problem? Or
that it's their defaults that are (de)faulty?

**Comment by gforsyth** [comment]
I thought that would've prevented the problem. With pygments >= 2.2.0 xonsh should use ansicolors and grab the scheme that your terminal is using, so it's strange that it would print out white on slightly-off-white

**Comment by njsmith** [comment]
Not sure what "scheme" means here; IIRC basically a stock gnome terminal where I went to the config panel and customized the background color. Is there an assumption that all the basic ANSI colors should have good contrast with the background? Are light colored terminal configurations supposed to make the "white" color be, like, black or something?

I won't be shocked if it turns out there's some piece of code that avoids using a foreground color that exactly matches the background, and I broke it by being lazy (?) and not making ANSI white = my slightly off white. But if that's what's happening then I still vote that the check be updated to check for similarity rather than exact equality :-)

**Comment by gforsyth** [comment]
I was sloppy with language there (and I don't like when I do that). I did mean that with pygments and prompt_toolkit, xonsh defaults to using the colors set by the terminal emulator. 

A quick perusal of some of the color styles available in xonsh leads me to believe that in the light-colored terminal configs that "white" does become... not white... which is weird. 

And I don't think that we have code to check even exact matches of foreground and background colors, much less a fuzzy match to avoid the problem you ran in to. We should definitely handle this better.

**Comment by njsmith** [comment]
Yeah, from a quick look at the built-in schemes in gnome-terminal, it looks like many of them make "white" be something that's not quite white. But... I flipped through a bunch of the built-in styles that have light-colored-background and different ansi-color-palettes, and the xonsh welcome screen was still pretty much unreadable in all of them.

**Comment by anki-code** [comment]
The place of the code to fix this:

https://github.com/xonsh/xonsh/blob/c4e7843598201236307352b1db77e53c14ae9ade/xonsh/xonfig.py#L856-L876

PR is welcome!
