### ISSUE TITLE
How to jump across words with Ctrl+Left/Right

### ISSUE THREAD

**Issue by nh2** [xonsh/xonsh#2403]
In bash, zsh and fish I can use Ctrl+Left or Ctrl+Right to jump across whole words, and Alt+Left or Alt-Right to jump around inside words.

For example, for the contents of the prompt `hello you-person` with the caret at the end, Ctrl+Left would jump across `you-person` and Alt-Left would jump across `person`.

How to achieve the same in xonsh?

I imagine this needs some `prompt_toolkit` configuration but I can't quite figure out what I have to do.

**Comment by nh2** [comment]
OK, I figured it out:

The `find_start_of_previous_word()` function in `python-prompt-toolkit` has an argument `WORD=False` that if set to `True` jumps over whole words, like I want it. See its [code here](https://github.com/jonathanslenders/python-prompt-toolkit/blob/46d07b00530e76eee8126d38ecb3f9c043bf2eae/prompt_toolkit/document.py#L421).

The code for [`forward-word`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/46d07b00530e76eee8126d38ecb3f9c043bf2eae/prompt_toolkit/key_binding/bindings/named_commands.py#L84) doesn't use that.

I could add this feature to xonsh by putting into `.xonshrc`:

```python
# Key bindings for jumping over whole words (everything that's not
# white space) using Ctrl+Left and Ctrl+Right;
# Alt+Left and Alt+Right still jump over smaller word segmetns.
# See https://github.com/xonsh/xonsh/issues/2403

@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.registry.add_binding

    @handler(Keys.ControlLeft)
    def ctrl_left(event):
        buff = event.current_buffer
        pos = buff.document.find_previous_word_beginning(count=event.arg, WORD=True)
        if pos:
            buff.cursor_position += pos

    @handler(Keys.ControlRight)
    def ctrl_right(event):
        buff = event.current_buffer
        pos = buff.document.find_next_word_ending(count=event.arg, WORD=True)
        if pos:
            buff.cursor_position += pos
```

Could we add this as some easy-to-use setting to xonsh somehow?

E.g. as some recipe in the documentation, or should it be a setting or a `xontrib`?

**Comment by gforsyth** [comment]
Hey @nh2 -- nice! Yeah, so this seems like the way to go if you want to use the Ctrl keys to this.  You can alternatively set `$VI_MODE=True` and then move by word with `w` and `b` if that's to your liking. 

In terms of incorporating your solution into xonsh, i think this would be a great `xontrib`.  We are trying not to add in too many default keybindings since there are a LOT of different opinions on which keys should do what.

**Comment by nh2** [comment]
> In terms of incorporating your solution into xonsh, i think this would be a great xontrib.

OK, made a PR at #2407

**Comment by rossnomann** [comment]
#2407 merged. So I guess this issue can be closed.

**Comment by nh2** [comment]
Yep.
