### ISSUE TITLE
__builtins__ type mismatch

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2422]
I'm not sure how much parity we want to keep with the Python REPL, but:

```
🐚 type(__builtins__)
dict
🐚 python
>>> type(__builtins__)
<class 'module'>
```

This means that `__builtins__.print` (for example) will work under Python, but not under xonsh.

(Yes, I'm aware that `__builtins__` is considered an implementation detail.)

**Comment by laerus** [comment]
this is part of the way we store xonsh's global singletons right?

**Comment by astronouth7303** [comment]
Sort of.

```
>>> import builtins
>>> __builtins__ is builtins
True
```

xonsh doesn't refer to `__builtins__` anywhere in the source (that github identifies).

**Comment by astronouth7303** [comment]
Oh! CPython makes this discrepency:

https://docs.python.org/3/library/builtins.html#module-builtins Notes that `__builtins__ is an implementation detail, and states that it may be the module or a dict. Specifically, [`exec()`](https://docs.python.org/3/library/functions.html#exec) has this exact behavior.

I actually wonder if we want to use this to our advantage to further minimize the effect of xonsh on the core interpreter? Registering so much stuff on `builtins` always bothered me, and this way we can define the primitives needed by compiled xonsh code without needing to mung a core module.

**Comment by laerus** [comment]
wanna to close this in favor of  #2385 and move the discussion there?

**Comment by astronouth7303** [comment]
I'm closing this as not a bug (acceptable discrepancy).

I'll make note of the `__builtins__` behavior in #2385.
