### ISSUE TITLE
Changelog broken on website

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2423]
http://xon.sh/changelog.html seems pretty broken.

@gforsyth would this be you?

**Comment by gforsyth** [comment]
Ugh, probably my fault. I'll try to fix this next week some time.

**Comment by gforsyth** [comment]
Ok, fixed this. I actually thought we were publishing our release docs with doctr now, but it's just the dev stuff.  So http://xon.sh is now up-to-date and also has a non-borked changelog.
