### ISSUE TITLE
Add special method for printing to the prompt

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2428]
I feel like maybe we should have a pretty repr method?

This is kinda strenuous, but it would be nice if types could have a verbose "on the prompt" format. I would like this to be distinct from `.__repr__()` because these verbose formats would be really annoying if you're debugging or embedding it in something else.

**Comment by scopatz** [comment]
This is a good idea; thanks for bringing it up @astronouth7303!  Jupyter has a `display()` method, I believe, for displaying things in the notebook.  We could build out a similar hook.

**Comment by AaronV77** [comment]
@astronouth7303 and @scopatz I added a hook for printing special methods to the prompt. The name of the hook is xonsh_display. Thanks.

**Comment by scopatz** [comment]
Thanks @AaronV77!
