### ISSUE TITLE
cannot install xontribs 

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#2431]
After I change the config.json with xonfig wizard, restart the xonsh  always say error: 
```
The following xontribs are enabled but not installed:
    z powerline fzf-widgets
To install them run
    pip install xontrib-z xontrib-powerline xontrib-fzf-widgets
```

even i run the second command and installed all the xontribs

**Comment by astronouth7303** [comment]
Installed with homebrew or conda?

Use `xip` instead of `pip`. It's a xonsh-specific alias for pip inside of xonsh's environment.

**Comment by eggcaker** [comment]
cool! it's works now, good to know

**Comment by ahundt** [comment]
@astronouth7303 what about installing one that's not on pip?

I tried `xip install mypackage --no-index --find-links file:///srv/pkg/mypackage`

but I get:

```
$ import sacredx
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
ModuleNotFoundError: No module named 'sacredx'
$  import sacredx
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
ModuleNotFoundError: No module named 'sacredx'
$  import xontrib-sacredx
```

this is for the new xontrib I've started writing https://github.com/ahundt/sacredx

**Comment by astronouth7303** [comment]
I suggest using PIP's local file features.

```
$ xip install ~/path/to/sacredx
```
