### ISSUE TITLE
cannot redefine the $XONSHCONFIG? 

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#2432]
I defined the $XONSHCONFIG  to another directory (~/.xonsh.d/cofig.json) instead default (.config/xonsh/config.json), seems all my zsh alias lost. 

- .xonshrc file 
```
...
$XONSH_HISTORY_BACKEND = 'sqlite'
$XONSH_HISTORY_SQLITE_FILE = "~/.xonsh.d/xonsh_history.sqlite"
$XONSHCONFIG = "~/.xonsh.d/config.json"
...
```

- config.json
```
{
 "foreign_shells": [
  {
   "shell": "zsh"
  }
 ],
 "xontribs": [
  "distributed",
  "coreutils",
  "vox",
  "z",
  "fzf-widgets"
 ]
}

```

if i move the config.json to .config/xonsh/config.json, all aliases works. did I missing some configuration?

**Comment by astronouth7303** [comment]
You can't set your `config.json` from `.xonshrc`. The JSON file is loaded before `.xonshrc` and won't be re-read.
