### ISSUE TITLE
How to use fzf with readline mode

### ISSUE THREAD

**Issue by nh2** [xonsh/xonsh#2442]
Hi, maybe this is obvious but I can't figure it out:

How to make keybindings (for fzf or in general) in readline mode?

xonsh's fzf-widgets uses `@events.on_ptk_create` so that won't do it.

**Comment by scopatz** [comment]
Hi @nh2, thanks for reporting! Generally speaking, to modify readline, you can edit your `~/.inpurc` file to create keybinding behaviour you want.  Xonsh respects this file.  Here are the instructions available: https://cnswww.cns.cwru.edu/php/chet/readline/readline.html

Additionally, in Python you can also use the `readline.parse_and_bind()` function to configure the current readline instance https://docs.python.org/3/library/readline.html#readline.parse_and_bind  You may use these functions from the xonshrc file.

**Comment by nh2** [comment]
OK, thanks for the info!
