### ISSUE TITLE
How to apply directory tab complete with prompt_toolkit?

### ISSUE THREAD

**Issue by nh2** [xonsh/xonsh#2443]
Assume I have `mkdir -p dira/file1 dirb/file2`.

When I do `ls <TAB>`, the prompt_toolkit menu pops up. I press TAB until the dir I want is selected (e.g. `dira`). Then the xonsh shell contains `ls dira/`.

But the menu is still open. How can I close the menu so that I can tab-complete again, so that it completes me to `ls dira/file1`?

Thanks!

**Comment by gforsyth** [comment]
Hey @nh2 -- you can set `$COMPLETIONS_CONFIRM=True` in your `xonshrc` or similar and then you can press `Enter` to close out the completions menu without executing the current line -- then if you hit TAB again, it will bring up the next completion menu.

**Comment by nh2** [comment]
Thanks, that's perfect @gforsyth.

Now that I know it, I could easily find it documented here:

http://xon.sh/customization.html#select-a-tab-completion-result-without-executing-the-current-line
