### ISSUE TITLE
xonsh autocomplete suggests files that don't exists

### ISSUE THREAD

**Issue by nh2** [xonsh/xonsh#2445]
```
touch a
ls a
rm a
```

After that, xonsh (with prompt_toolkit backend) will suggest a completion that doesn't make sense:

If I press `ls <TAB>`, it will suggest `a` in the completion menu even though that file doesn't exist.

Why is that, and how can I turn it off?

Thanks!

**Comment by gforsyth** [comment]
This is because the 'autocomplete' entries (that you would normally complete by hitting right-arrow or Ctrl-e are also included as the first item in the completions menu. 

I would be in favor of having this behavior be optional, since it routinely confuses me.

**Comment by scopatz** [comment]
Thanks for reporting @nh2! I could have sworn this was optional, but I can't find an envvar for it @gforsyth!

**Comment by scopatz** [comment]
Potential fix in #2452

**Comment by melund** [comment]
@nh2 This was fixed by @scopatz in #2452. Feel free to reopen if there is something you were missing.

**Comment by nh2** [comment]
Thanks all, I'm using the new `$AUTO_SUGGEST_IN_COMPLETIONS = False` now in my `.xonshrc` and it works well.
