### ISSUE TITLE
can't activate conda environment  [Ubuntu 16]

### ISSUE THREAD

**Issue by pyeguy** [xonsh/xonsh#2447]
hi all trying to activate a conda env in the normal `source activate <envname>` is giving me the following error in ubuntu server 16.04

``` python

xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13063, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12885, in proxy_two
    return f(args, stdin)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 18107, in source_alias
    builtins.execx(src, 'exec', ctx, filename=fpath)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19748, in exec
    transform=transform)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19709, in compile
    transform=transform)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19678, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19778, in _parse_ctx_free
    raise original_error from None
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19765, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 348, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2726, in p_error
    column=p.lexpos))
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 479, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: /home/cpye/anaconda3/bin/activate:4:9: ('code: $BASH_VERSION',)
if [[ -n $BASH_VERSION ]]; then
```
xonfig:
```
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.9               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by scopatz** [comment]
Please see the `xonda` project for the moment. https://github.com/gforsyth/xonda  Conda activate in most versions of conda requires the shell to remain in the same session.  conda v3.4 includes some overhauls that make `conda activate` more accessible.  Note that this replaces conda's old `source activate`

**Comment by scopatz** [comment]
Please feel free to close if you feel that this has been addressed! Thanks for reporting!

**Comment by pyeguy** [comment]
ah that does indeed work, it seems like that might be good to include standard in xonsh as opposed to a xontrib. similar to how activate/deactivate get aliased on windows? just my 2¢ . love xonsh and want to see it as a seemless bash/powershell replacement!

**Comment by astronouth7303** [comment]
Conda management isn't a core feature for a shell. Virtual Environment, rvm, pyenv, etc management isn't core either.

What we can do is improve the process of installing and activating xontribs, and make them more visible to new users.

**Comment by melund** [comment]
@pyeguy I agree with @astronouth7303 on this. The reason we have the alias on Windows, is that xonsh didn't always have xontribs. Also, Windows users are usually less tech savvy and often doesn't get the concept of source'ing a script.

**Comment by pyeguy** [comment]
@melund  alright alright, everybody likes to hate on the windows users out there... but i see where you and @astronouth7303  are coming from. Particularly highlighting xontribs and streamlining their installation-->activation would be great. If anyone has ideas on how to do it i'd like to contribute. 

closing.

**Comment by astronouth7303** [comment]
#1849 starts this. The next step would be to have the xonfig wizard automatically install selected xontribs.

After that, if we add fields to `xontribs.json` describing what aliases/globals a xontrib adds, we can have a missing command handler that looks this up and suggests xontribs.

**Comment by melund** [comment]
> @melund alright alright, everybody likes to hate on the windows users out there.

@pyeguy Don't get me wrong. I am using Windows exclusively myself. It is just observations from introducing  xonsh to friends and colleagues. The `activate` alias and the 'cmd.exe' foreign shell stuff was one of things I contributed to xonsh.

**Comment by scopatz** [comment]
Yeah, @pyeguy we do try to support windows as a first class platform, in the same way that CPython does. Please keep letting us know if there are explicit pain points!

**Comment by pyeguy** [comment]
@melund no offense taken, i know the type. @scopatz  i'll keep raising issues when i run into them in my windows world.

This isn't really appropriate for this thread but one minor annoyance I have with the windows shell experience is how the windows path's get formatted on tab completion. ie with quotes and escaped backslashes. I know xonsh is a superset of python so this how the path string is interpreted but it would be nice if there was a prettier intermediate representation particularly during tab completions...

**Comment by scopatz** [comment]
@pyeguy We are open to suggestions :) So what do you mean by prettier?  What would it look like in your ideal world?
