### ISSUE TITLE
Add a missing command event

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#2455]
Add an event that fires when a command is not found:

```
on_command_not_found(name: str) -> None
```

In addition to factoring out the default handler (spelling-based) into a xoretrib, xontribs can be written to handle things like checking the package manager.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laerus** [comment]
+1

**Comment by scopatz** [comment]
Great idea!
