### ISSUE TITLE
[RFC] Move to zipapp distribution

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#2459]
* Python (since 2.6) supports running a zip-formatted file directly if it contains `__main__.py` in the root (formalized and improved in [PEP441](https://www.python.org/dev/peps/pep-0441/))
* You can make these files executable by prepending a shebang line and setting the execute permission
* You can strongly isolate a script from the system environment by using the `-I` and `-S` interpreter options

This would also have a performance impact, because all of xonsh and dependencies can be loaded into memory with a single, bulk read. (Although I don't know what CPython actually does.) Initial 5mins of testing show a 20%~40% improvement in load times. (More details below.)

I think this is worth pursuing because we can abolish amalgamation and vendoring, and the issues and weirdnesses those cause, while actually improving performance. We can also get some secondary benefits (such as nearly single-file distribution).

The downside is that there is very little tooling around this. Distributing by PyPI would need to be examined. I have no idea if the `.pyz` system discussed in PEP441 is an actual thing. Careful choice of shebangs is necessary (to avoid interference from active virtual environments or other weirdnesses) and possibly distro-specific. We would have to explicitly handle the xonsh installation environment (ie, what `xpip` installs into).

### Testing Methodology

EDIT: All of this testing is invalid because pex self-extracts instead of running directly from zip.

EDIT 2: This testing isn't completely invalid because while yes pex self-extracts, this only appears to be used for the benefit of `__file__` (and therefore data files), and what is on `sys.path` is still the zip file. But this still needs to be rerun with a non-pex zipapp because this is too complex to reason about.

I conducted extremely basic tests using [pex](https://github.com/pantsbuild/pex) to create the zipapp version of xonsh. This was built using the command `pex "xonsh[ptk,pygments,linux,proctitle]" -m xonsh -o /tmp/xonsh.pex` (creating a feature-rich version of xonsh). This pex file came in at 2.3MB as well as:

* Contained overhead added by pex
* Contained egg-info, RST files, and other files of little-to-no use
* Only the previously-mentioned pex overhead was bytecompiled. All other files (including xonsh and dependencies) did not have cached bytecode in the zipapp. (I'm fairly certain this means that all files were recompiled every time the zipapp was run, but the bytecode caching mechanisms were not consulted or invoked.)
* Had the shebang line of `#!/usr/bin/env python3.5` (although this can be adjusted this with an option to `pex`)

This was compared to the system xonsh I use daily on the system I conducted this testing on. This is a standard conda install of xonsh from conda-forge, and included most of the same extras (`distro` from the `linux` extra was not installed, but most importantly, Prompt Toolkit and Pygments were installed).

Amalgamation was active in both.

The commands I used to conduct these tests were `/tmp/xonsh.pex --timings --no-rc` and `xonsh --timings --no-rc`. I ran each of these several times to get some idea of spread, although not enough to be statistically significant. (Also, I barely passed statistics. :stuck_out_tongue:)

The zipapp version showed a time to prompt in the range of 0.22~0.24.

The conda version showed a time to prompt of 0.29~0.52 (upper 0.3's most common).

I think these results are extremely significant and call into question some of our assumptions about the performance of initialization, in particular about the expense of producing bytecode vs caching bytecode.

Further testing involving the removal of pex overhead, the removal of amalgamation, and the addition of cached bytecode is necessary. In particular, I would like to make sure tests are conducted on both a spinning metal disk and an SSD, so that the cost of IO vs CPU is examined. (I personally suspect that IO plays a huge role, but we should examine this empirically.)

### Further Questions

In order to turn this into actual software development, many questions need to be examined.

* Can virtual environments interfere with the xonsh zipapp? Even if `-IS` is set?
* What shebangs are necessary on what systems? How do we handle extremely custom configurations?
* How does `pip` decide where to install packages? Can we just add (for example) `~/.xonsh/lib` to `sys.path` and `pip` will just work?
* How do we distribute xonsh moving forward? Are PyPI and Conda packages still viable and/or useful?
* What extras do we include with xonsh? Do we produce multiple builds for multiple combinations?
* What will the user-managed environment (`xpip`) look like?
* Build tools? Is setuptools still viable? Should we move away from `setup.py` being the developer's primary entry point for managing packaging? (Note that this is distinct from using `setup.py` as the installation entry point for any sdist packages, seeing as we could generate one as part of the build process.)
* CI builds? Do we want to move to a model where we produce a build, test a build, and promote a build?
* How are data files handled? (eg, `xontribs.json`)

**Comment by astronouth7303** [comment]
Actually, some testing with `$XONSH_DEBUG` shows very little difference in startup performance between having it and not (and therefore amalgamated and not).

**Comment by astronouth7303** [comment]
[xonsh-0.5.12.zip](https://github.com/xonsh/xonsh/files/1181594/xonsh-0.5.12.zip)

This is the zipapp with 3.6 bytecode, without pex. At home, it's loading slower than pip xonsh.  (2.17~2.54 vs 1.61~2.07)

And `$XONSH_DEBUG` is loading faster than regular with pip xonsh (1.36~1.38) and about the same with zipapp (2.44~2.55).

If other people could run similar tests and report their results, that would be great. The flip in results is confusing me.

**Comment by anki-code** [comment]
I'm going to close this because:
* Zipapp still have no support and building system that allows to put it to release assets.
* We have pretty stable and documented well AppImage that has automatical building that putting it to the release assets.

If anybody wants to make zippapp great again feel free to reopen this issue and remember about automatisation of the building and enrich xonsh release assets and docs.
