### ISSUE TITLE
Better error message for print statement

### ISSUE THREAD

**Issue by ngoldbaum** [xonsh/xonsh#246]
I'm not 100% converted to python3 yet and especially in an interactive prompt, I still get bitten by muscle memory that print is a statement.

Right now, we get this not so helpful error message:

```
goldbaum@eudora /zang/goldbaum/feedback_comparison $ print file
xonsh: subprocess mode: command not found: print
Did you mean one of the following?
    grin:    Command (/home/goldbaum/miniconda/bin/grin)
    ping:    Command (/bin/ping)
    printf:  Command (/usr/bin/printf)
    pylint:  Command (/home/goldbaum/miniconda/bin/pylint)
    grind:   Command (/home/goldbaum/miniconda/bin/grind)
```

when instead I would expect an error message about print not being a statement.

**Comment by rbrewer123** [comment]
On my ubuntu system it seems there is a program named 'print', so others may want that program usable by default.  A quick workaround would be to add something like this to your .xonshrc:

'''
aliases['print'] = ['echo', 'please try print()']
'''

**Comment by rbrewer123** [comment]
(Only without the triple quotes)

**Comment by scopatz** [comment]
I also have print on my system, though I agree that it might be nice to an error message.  Another option is to perhaps alias print as a print function. Something like:

```python
aliases['print'] = lambda args, stdin=None: print(*args)
```

**Comment by laerus** [comment]
i'm closing this since i don't think it's worth changing the default behavior for just print and you can get around this with an alias, also if you install `mime-support` package on debian the `print` is actually a command, feel free to reopen though.
