### ISSUE TITLE
Xonsh and Midnight Commander

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#2461]
Several issues:

1. midnight commander takes a lot longer to load.

2. You should be able to click the column headings to sort. This works sometimes, and not others.

3. Highlighting text (shift Click) works randomly.

4. I cannot press ^O to see the shell (very limiting!)

Regardless of terminal software I use.

Using xonsh 0.5.9

Other issues:

Typing crontab -e loads up my crontab in nano. But keybindings like ^X to quit don't work immediately. Instead, it displays ^X on the screen.

Stuff like this happens with other programs too (don't remember the examples, though).

This is frustrating. I use mc a lot. It shouldn't take this long to load! And I need access to the shell.

**Comment by ulno** [comment]
I am pretty sure, this is the same issue as this: #2383

**Comment by scopatz** [comment]
Did the fix in #2383 work here?

**Comment by ulno** [comment]
works for me, can't speak for @beetleb

**Comment by beetleb** [comment]
I tried adding those lines to my .xonshrc.

1 and 4 are still problems. I cannot immediately verify the other 2 as those were random. Will run for several days to see if this has solved it.

**Comment by beetleb** [comment]
Edit: Problem 4 seems to be solved! Needed to add a line for crontab (separate from nano).

Would still love to know why loading midnight commander takes so long! 

Also, added another mc related issue (which is still an issue):

5. In midnight commander, pressing ^O should take me to the command prompt. It does not, though. It hides the panels, but as soon as I type, it brings them back.

**Comment by ulno** [comment]
I have none of the above stated problems after the fix.

Let's compare:

- I am running xonsh 0.5.12 in a virtual python3 environment
- in an xfce4-terminal
- TERM is set to xterm-256color
- mc is version 4.8.19 compiled with slang - not ncurses
- I run void linux with xfce4

Let's see what's different. Anything else what I should check?

**Comment by beetleb** [comment]
I suspect my mc is built with slang (the "slang" USE flag is set in GENTOO for mc).

Running 4.8.18 - I doubt that should make a big difference.

My TERM is set to the same as yours. 

What is the value of your $SHELL?

If it's relevant, my base shell is zsh. My .zshrc will launch xonsh at the very end. I kind of needed this as xonsh was/is not that stable. 

To give you an idea, loading mc from xonsh takes about 11 seconds. In zsh, it's under 1 second.

Never mind - I just figured it out. For the curious:

1. My .zshrc launches xonsh
2. mc would not show the prompt. So I changed my $SHELL to zsh
3. Whenever I'd launch mc, it would launch zsh behind the scenes - which then would launch xonsh

3 was causing the slowdown. If I comment out the xonsh line from my .zshrc, then mc is fast.

 So my last problem kind of remains: Why cannot I use ^O in mc if my $SHELL is set to xonsh? I can hack around it by setting $SHELL to zsh. Then I can load mc from xonsh, but use the zsh command prompt under mc. It's workable, but not ideal.

(At this point I suppose we should wonder if I should open a separate ticket for this and close this?)

**Comment by ulno** [comment]
Sorry, I was on the road - my default shell is bash.
For testing I installed zsh, opened a terminal, (starting bash), starting zsh, starting xonsh, starting mc. ctrl-o (and resize and mouse) still works for me. Maybe because mc is still runnning bash as shell?

**Comment by beetleb** [comment]
I forgot about all this. The problem is solved. I honestly don't remember what I did to solve the ^O problem. Checking right now, when I do ^O, it puts me in zsh. I guess I can live with that.
