### ISSUE TITLE
Investigate using watchdog for filesystem changes

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#2462]
I saw that every time xonsh is autocompleting commands it does multiple stats on folders in your path, maybe it can be much easier/faster to use https://pypi.python.org/pypi/watchdog for this kind of things.

Another option is to do like zsh and ask people to refresh their binaries.

**Comment by astronouth7303** [comment]
hmmm... we'd have to do this as an internal service (similar to events).

I believe there's also some issues with programs hitting inotify limits really quickly, especially if you're trying to watch something recursively.

There's also some of this that would be difficult to avoid. For example, anything using git is going to call out to the binary, and Python-based git handling can be a bit of a mess.

**Comment by anki-code** [comment]
I'm going to close this because autocompleting in xonsh is completely customisable and the approaches around it could be realised as a xontrib (xonsh extension). If it shows the big benefit it could be moved in the core.
