### ISSUE TITLE
xonsh website improvement

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2477]
I think there might be a couple of small changes that can make the [xon.sh](http://xon.sh) homepage and docs much easier to browse. Unfortunately, I kept getting lost and could not find my way back to pages I saw before. What do you think of the following?

1. `Contents` section on the homepage be added as a page next to index at the top right, or on the left under the xonsh icon
2. Update `Contents` section to show three levels instead of just two
   - Installation
        - ...
   - Guides
      - [Tutorial](http://xon.sh/tutorial.html)
        - [Customizing the prompt](http://xon.sh/tutorial.html#customizing-the-prompt)
        - ...
      - ...
    - ...
3. "Index" link be renamed "API Index"

**Comment by gforsyth** [comment]
Hi @ahundt -- any improvements to the website are always welcome! If you're familiar with sphinx we'd love to have any help you can offer.

**Comment by ahundt** [comment]
I tried dropping in a theme I happen to have on hand but I'm getting errors I don't know how to resolve:

```
writing output... [  0%] advanced_events
Recursion error:
maximum recursion depth exceeded in comparison

This can happen with very large or deeply nested source files.  You can carefully increase the default Python recursion limit of 1000 in conf.py with e.g.:
    import sys; sys.setrecursionlimit(1500)
make: *** [html] Error 1

```

I tried setting the recursion limit to 10000 to no effect...

**Comment by ahundt** [comment]
@gforsyth done! see #2480

**Comment by gforsyth** [comment]
Hey @ahundt, if you think your changes in #2480 meet the points raised feel free to close this out.  Thansk again!

**Comment by ahundt** [comment]
Yep essentials are there, thanks. :-)
