### ISSUE TITLE
try it out button on xon.sh home page doesn't work

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2484]
I've never actually been able to type anything on the try it out field of xon.sh. Is it broken? I'm on google chrome.

**Comment by gforsyth** [comment]
Hey @ahundt -- we had to disable it almost immediately after we added it. In it's current (previous?) state, everyone who tried it was in a shared environment and it took all of 5 minutes for the less savory elements of the internet to decide to rename a bunch of things. 

Hopefully we can re-enable it at some point and spin up and destroy containers per-user

**Comment by astronouth7303** [comment]
The project is [xonsh/inabox](https://github.com/xonsh/inabox).

**Comment by ahundt** [comment]
Perhaps it would be best to replace it with a demo gif for now? If its too much effort to come up with something new it could probably be cut from the presentation of @scopatz pretty easily, or perhaps he has the replay script still to record a fresh run?

**Comment by ahundt** [comment]
How about something like this?
![xonsh giv](https://j.gifs.com/1j5XkV.gif)

**Comment by melund** [comment]
I should probably be made with asciinema, to get good colors and quality.  Before the 'Try it now' box we had this: 

https://asciinema.org/a/9kp21a67ahhng25wtzoep3pyx/embed?size=medium&speed=2

It was pretty good, but it is outdated now with all the new features and syntax. It takes forever to record (just ask @scopatz), unless you can use some sort of autotyping.

**Comment by laerus** [comment]
i remember @carreau having a cool presentation, but it was more of a long tutorial, any chance we can have parts for this?

**Comment by ahundt** [comment]
@melund oh yes I remember seeing that long ago, well that's certainly an improvement! Could it be put back since try it now is disabled?

**Comment by gforsyth** [comment]
Closing this as the "try it out" has been removed until we figure something out
