### ISSUE TITLE
zsh config messing with xonsh configuration?

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2486]
My default shell is zsh with [zprezto](https://github.com/sorin-ionescu/prezto) and from there I run xonsh. However either this, or the loading of zsh config scripts at xonsh startup might have an effect where xonsh is trying to disable autocorrect for certain commands which is available on zsh but not xonsh.

```
$ rm -rf robotiq_85_gripper/
xonsh: subprocess mode: command not found: nocorrect
nocorrect: command not found
```

This means the file also wasn't deleted! This is mildly amusing for now, but I've got to figure something out. :-)

It might be these [aliases in init.zsh](https://github.com/sorin-ionescu/prezto/blob/a60fe47359fdef9cbf4798690e66efe973aab363/modules/utility/init.zsh#L21):

```
# Disable correction.
alias ack='nocorrect ack'
alias cd='nocorrect cd'
alias cp='nocorrect cp'
alias ebuild='nocorrect ebuild'
alias gcc='nocorrect gcc'
alias gist='nocorrect gist'
alias grep='nocorrect grep'
alias heroku='nocorrect heroku'
alias ln='nocorrect ln'
alias man='nocorrect man'
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv'
alias mysql='nocorrect mysql'
alias rm='nocorrect rm'
```

https://github.com/xonsh/xonsh/pull/665 might also be relevant. In particular, I'd prefer xonsh to use its internal implementations since it appears to be trying to run the subprocesses right now.

Do you have any suggestions on how both xonsh and zsh can be made happy?

**Comment by ahundt** [comment]
I think deleting all the aliases with the might work, but is there a way to delete an alias right now?

I can't find anything obvious in the relevant commits that might do that.
https://github.com/xonsh/xonsh/commit/cee3a7165073f38eb433154c4d09d01cd5cba108

**Comment by gforsyth** [comment]
`aliases` is a dictionary -- if you want to remove one, you can `pop` it, so `aliases.pop('rm')` should do the trick.

**Comment by gforsyth** [comment]
Also, `xonsh` isn't disabling anything but it is inheriting aliases from `zsh` and many of those rely on `zsh` builtins, like `nocorrect` which are not valid commands outside of `zsh`

**Comment by ahundt** [comment]
Here is the workaround to add to your `.xonshrc` in case anyone comes across this in the future:

```
aliases.pop('ack', None)
aliases.pop('cd', None)
aliases.pop('cp', None)
aliases.pop('ebuild', None)
aliases.pop('gcc', None)
aliases.pop('gist', None)
aliases.pop('grep', None)
aliases.pop('heroku', None)
aliases.pop('ln', None)
aliases.pop('man', None)
aliases.pop('mkdir', None)
aliases.pop('mv', None)
aliases.pop('mysql', None)
aliases.pop('rm', None)
```

**Comment by ahundt** [comment]
Actually with the above none of the commands work. This seems relevant: https://github.com/xonsh/xonsh/issues/102

**Comment by ahundt** [comment]
I still haven't figured this one out, my workaround was to modify my zshrc to detect if it is in zsh vs xonsh and only load the aliases in zsh.

**Comment by gforsyth** [comment]
@ahundt -- do you have `zsh` set up as a foreign shell in `.config/xonsh/config.json`?

**Comment by ahundt** [comment]
This is what's in there, hmm a bit redundant but probably should still have been doing the right thing:
```
 "foreign_shells": [
  {
   "shell": "zsh"
  },
  {
   "shell": "zsh"
  }
 ]
```

**Comment by gforsyth** [comment]
@ahundt -- if you have time, can you see if this is still an issue with the current xonsh?  We have eliminated the static configuration file, so you should put a `source-zsh .zshrc` or similar in your `xonshrc` to load in your zsh config.  Curious if the issue with the builtins is still a problem.

**Comment by anki-code** [comment]
Hi @ahundt! Have you a chance to check the Gil`s proposal?
