### ISSUE TITLE
autocorrect feature request

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2487]
Autocorrect would be very nice to have. :-)

The zsh version has proven very useful for me over time. Not enough free cycles to contribute this one myself but would anyone else find it useful?

**Comment by gforsyth** [comment]
Note that there is already `$FUZZY_PATH_COMPLETION` available -- this could be expanded to cover more cases.  What did you have in mind?

**Comment by ahundt** [comment]
Here is an example:

```
$ ptyhon
Did you mean the following?
    python:  Command (/usr/bin/python)

```

**Comment by anki-code** [comment]
hi! Command correction is an additional function (plugin). As I see you use zsh with OMZ or something like this. For xonsh you also can find the plugins - [xontrib-thefuck](https://github.com/meatballs/xontrib-thefuck) for example.

This issue could be closed I suppose.
