### ISSUE TITLE
Wrong NotADirectoryError for function _yield_accessible_unix_file_names in cygwin

### ISSUE THREAD

**Issue by fmv1992** [xonsh/xonsh#2489]
As the title suggests I'm getting:

`NotADirectoryError: [Errno 20] Not a directory: '/cygdrive/c/WINDOWS/system32'`

which is wrong.

The following corrects the issue:
```
def _yield_accessible_unix_file_names(path):
    """yield file names of executable files in path."""
    if not os.path.exists(path):
        return
    try:
        for file_ in scandir(path):
            try:
                if file_.is_file() and os.access(file_.path, os.X_OK):
                    yield file_.name
            except (FileNotFoundError, NotADirectoryError):
                # broken Symlink are neither dir not files
                pass
    except NotADirectoryError:
        return
```

It is not within the scope of this specific error but I'm using a hack to operate xonsh in cygwin. I'm using one version for interactive sessions (my own mod of 0.4.3; the latest that supported cygwin) and the newest 0.5.10 to run my scripts.
This latter version does not work for interactive sessions.

**Comment by anki-code** [comment]
Hello @fmv1992! We merged a PR about cygwin support recently. Could you please test it again with xonsh 0.9.23? Or if you haven't time for this just close this issue because it looks outdated.
