### ISSUE TITLE
Decent editor for *.xsh scripts

### ISSUE THREAD

**Issue by a-da** [xonsh/xonsh#2490]
Is there any decent IDE (at least vim plugin) approved by XONSH team ?

I have a few scripts in xonsh.
Usually I use pycharm for bash and python.
It is highlighting and provide autocompletion.

In case of xonsh it will not work. 
If I use bash plugin it will complain on python.
If I use python plugin it will complain on bash.
So I will have something like ![selection_059](https://user-images.githubusercontent.com/17334646/29709833-32e40a38-898e-11e7-863a-494ecc8ea7bf.png)

I think also XONSH editor shoduld be mention in documentation also, because 90% of frustration comes from it.

**Comment by melund** [comment]
Well. We have a pygments plugin to highlight Xonsh code. That means that all editors that support pygments should hightlight xonsh code correctly.  I only know of the Spyder IDE that uses pygments. 

What we really need is a TextMate language grammar file to highlight xonsh code. If we had such a thing it would be easy to create extensions to most modern text editors. Both TextMate, Sublime, Atom, VS-Code and probably more support `tm_language` files for highlighting.

**Comment by astronouth7303** [comment]
I generally use Python mode in sublime. It works well enough.

**Comment by gerardlouw** [comment]
It looks like this is being worked on for VSCode: https://github.com/Microsoft/vscode-python/issues/3487.

**Comment by scopatz** [comment]
Yeah someone should pick that back up!

**Comment by LoveIsGrief** [comment]
As one would expect, there's a syntax file for vim https://github.com/linkinpark342/xonsh-vim (installation help https://vimawesome.com/plugin/xonsh-vim).

**Comment by anki-code** [comment]
@meatballs @scopatz Why there is no answer here https://github.com/microsoft/vscode-python/pull/3488#pullrequestreview-187209841 ?

**Comment by scopatz** [comment]
Not sure.  I think @meatballs didn't want to work on that PR anymore... but someone should!

**Comment by anki-code** [comment]
I asked JetBrains (PyCharm) about the best way to add syntax highlighting for xonsh scripts. The answer was:

> You can add custom syntax highlighting by importing the corresponding TextMate bundle: https://blog.jetbrains.com/pycharm/2013/06/textmate-bundles-in-pycharm/

**Comment by anki-code** [comment]
_Originally posted by @laloch in https://github.com/xonsh/xonsh/issues/2837#issuecomment-424344692_
>In vscode you can change the language by "Change Language Mode" command (Ctrl+K, M) 
> or you can add the following to your settings.
```
    "files.associations": {
        ".xonshrc": "python",
        "*.xsh": "python",      
    }
```

**Comment by jnoortheen** [comment]
I have created an extension

https://marketplace.visualstudio.com/items?itemName=jnoortheen.xonsh
https://github.com/jnoortheen/xonsh-vscode-ext

it has syntax support. It is just a start. Since we separate the file associations, we can have Python extension's formatting withing the same workspace. Contributions are welcome . Please check this awesome [tutorial](https://code.visualstudio.com/api/language-extensions/overview) if you wish to contribute

**Comment by anki-code** [comment]
I'm going to close this issue with many thanks to all who push the xonsh support into the editors and especially to jnoortheen for the most useful one. Feel free to post here news and new editors.

Also I want to remember about:
* we have a [discussion board](https://github.com/xonsh/xonsh/discussions) now
* we have [a page in the docs](https://xon.sh/editors.html)

**Comment by eugenesvk** [comment]
FYI there is a `xonsh` package for **Sublime Text 4** now https://github.com/eugenesvk/sublime-xonsh or https://packagecontrol.io/packages/xonsh that can deal with xonsh's extra syntax while preserving everything from Python (using Sublime's native Python package):
![img](https://user-images.githubusercontent.com/12956286/135798050-039e21a2-bd67-4397-8047-00306b4d0477.png)
