### ISSUE TITLE
Hatch now supports Xonsh

### ISSUE THREAD

**Issue by ofek** [xonsh/xonsh#2495]
@scopatz @gforsyth @astronouth7303 @laerus @Granitosaurus @melund 

I just wanted to inform you that as of 0.10.0, Hatch fully supports Xonsh on all platforms and even if pyenv is in use https://github.com/ofek/hatch#0100

Perhaps this could be added to the virtual environment docs?

Here's an example on Windows:

![xt](https://user-images.githubusercontent.com/9677399/30351773-06a1c8be-97eb-11e7-8e78-fe95f0c231d6.PNG)

**Comment by scopatz** [comment]
Thanks for bringing this to our attention! Please feel free to put in an a PR with additional docs! Thanks!

**Comment by anki-code** [comment]
This issue looks not refer to xonsh core functionality and should be close.

PR with info about hatch in the docs still welcome.
