### ISSUE TITLE
xontrib for windows to linux translator

### ISSUE THREAD

**Issue by CJ-Wright** [xonsh/xonsh#2498]
Is there (should there be?) a xontrib for linux users working on windows xonsh terminals? It could alias common linux commands such that they work as expected on windows (eg. `pwd`).

**Comment by astronouth7303** [comment]
I thought we had a coreutils xontrib at one point, but it's not necessarily a bad idea in general.

**Comment by melund** [comment]
@CJ-Wright I like the idea too. But you can get most the things for free by installing "Git for Windows". Just select the option to add the MSys tools to the path when installing. This will give you all the Linux tools right at your disposal.

**Comment by anki-code** [comment]
I can add for this issue that you can use WSL/WSL2 with full linux support on Windows 10.
This issue looks not actual and should be closed.
