### ISSUE TITLE
How do I add jdk in $PATH (java 1.8.0) ???

### ISSUE THREAD

**Issue by ErickTucto** [xonsh/xonsh#2501]
I use `append()` method, but I can't use `java -version` command

Pls See Capture

![xonsh_java](https://user-images.githubusercontent.com/22831024/31023924-020c5ca4-a503-11e7-8e6a-11e1a6f3eaeb.png)

**Comment by gforsyth** [comment]
Hi @ErickTucto -- are you sure there's a `java` binary in one of those `PATH` locations?

**Comment by ErickTucto** [comment]
I go to the JDK folder and use the java -version command but it outputs the same error

![imagen](https://user-images.githubusercontent.com/22831024/31025033-a10c563a-a506-11e7-8075-e0d7870ffeaf.png)

**Comment by astronouth7303** [comment]
Does `/home/erick/jdk1.8.0_141/java` exist, is a file, and is executable?

**Comment by ErickTucto** [comment]
el ejecutable de java estaba dentro de /home/erick/jdk1.8.0_141/bin

![imagen](https://user-images.githubusercontent.com/22831024/31025440-4a43e8c0-a508-11e7-9f32-7da76c1c4aca.png)

**Comment by ErickTucto** [comment]
the `java` executable was inside `/home/erick/jdk1.8.0_141/bin`

![imagen](https://user-images.githubusercontent.com/22831024/31025500-79681e32-a508-11e7-99ed-ee0e4d184efe.png)
