### ISSUE TITLE
Command line parameters in xsh file?

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2505]
Is there an xsh script equivalent to `$0`, `$1` etc from bash? I searched the tutorials and cheat sheet page and didn't see it, so sorry if I missed it in the docs.

**Comment by gforsyth** [comment]
Hey @ahundt, this is one of these places where we just defer to python, so you can use `sys.argv` to grab parameters.

**Comment by ahundt** [comment]
ok that works, thanks!

**Comment by adqm** [comment]
Actually, there is a way from xonsh directly.  There was some arguing about the syntax at the time, but the thing that won was `$ARG<n>` (e.g., `$ARG1` is the equivalent of `$1`).

These are also available as a list called `$ARGS` in Python mode.

See <http://xon.sh/tutorial.html#executing-commands-and-scripts>

**Comment by ahundt** [comment]
Reopening because it seems `$ARG<n>` and `$ARGS` don't end up in http://xon.sh/envvars.html, maybe they don't end up in the generator code? https://github.com/xonsh/xonsh/blob/master/docs/conf.py#L265

Not sure how that works, could they be added to the env list manually (or automatically?).

**Comment by anki-code** [comment]
I think this issue should be closed.
