### ISSUE TITLE
slow startup after update

### ISSUE THREAD

**Issue by ykonoclast** [xonsh/xonsh#2509]
I had been using Xonsh for 6 months on Fedora25 without any problem (and frankly loving it) and I just upgraded to Fedora26 this morning. Now getting to the prompt takes longer than before (about 5 seconds). 
After trying `xonsh --timings` this is what I get :
 ```
Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.048   |   0.048   |
|post_execer_init  |   0.134   |   0.086   |
|on_pre_rc         |   0.134   |   0.000   |
|on_post_rc        |   4.608   |   4.474   |
|on_ptk_create     |   4.717   |   0.109   |
|on_post_init      |   4.717   |   0.000   |
|on_pre_cmdloop    |   4.717   |   0.000   |
|on_pre_prompt     |   5.490   |   0.773   |
|------------------|-----------|-----------|
```

it seemed to be taking some time to read xonshrc, so I tried deleting it. The startup time did not change : and I have no general xonshrc in /etc so it doesn't seem to be linked to rc files.

Here is my `xonfig` :

```
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.6.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.14              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | fedora              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

Trying --no-rc gives the same time, with different partition :

```
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.047   |   0.047   |
|post_execer_init  |   0.135   |   0.089   |
|on_pre_rc         |   0.135   |   0.000   |
|on_post_rc        |   0.136   |   0.000   |
|on_ptk_create     |   2.887   |   2.752   |
|on_post_init      |   2.887   |   0.000   |
|on_pre_cmdloop    |   2.888   |   0.000   |
|on_pre_prompt     |   4.904   |   2.016   |
|------------------|-----------|-----------|
```

Also, simply closing a terminal gives a "misbehavior" alert in Gnome, whatever that might mean

**Comment by gforsyth** [comment]
Thanks for reporting @ykonoclast! And thanks for the kind words -- hopefully we can get you back up to a reasonable start time.
What was the rough startup time before?  Is this an increase of multiple seconds (i'm guessing yes)?

At first blush, this looks like the cached parser table isn't installed or is otherwise having trouble.  That would lead to having to regenerate it at each startup, which adds around 2 seconds to startup time.

Could you try reinstalling xonsh? And if that doesn't change things, could you try installing it into a separate Python env and seeing if times improve there?  

Thanks!

**Comment by ykonoclast** [comment]
Yes the increase is in the order of multiple seconds as I never noticed any delay upon opening a terminal and now, while not insufferable, the delay is a nuisance.

After reinstalling, the problem is actually worse : the return code part of my prompt is not functional anymore, it has been replaced by the litteral `{ret_code_color}{ret_code}`

The Fedora upgrade process might be the culprit here, maybe things are a little more bumpy than with a clean install.

**Comment by ykonoclast** [comment]
Problem stayed mysterious, I finally just did a clean install and now startup takes the same time as before.

**Comment by scopatz** [comment]
Weird.... I am glad this cleared up though!
