### ISSUE TITLE
Alternative and customizable semantics for @() and @$()

### ISSUE THREAD

**Issue by nilehmann** [xonsh/xonsh#2512]
The first time I tried to use `@$()` I was surprised that the following didn't work:
```
pacman -R @$(pacman -Qdtq)
```
I don't know if this is a bug, but at least  the documentation says that `@$(cmd)` is equivalent to `@(i.strip() for i in $(cmd).split())`. This kept me thinking and I like to to share my ideas around this.

The main purpose of `@()` is to get from python objects into subprocess mode. Thus, `@()` is just a function that takes a python object and produces a list of strings (and perhaps a callable in the first position). A common use for `@()` is to receive a string. I believe the natural way to process a string is by splitting it in a meaningful way to produce a list of strings relevant for subprocess mode. I argue that the most useful way is to split it by newlines.

With this definition of `@()` we could simplify the meaning of `@$()` and define it just as `@($())`. All the heavy lifting is done by `@()`.

Now, as important as it is to get the correct default meaning for `@()`, maybe some users want to split their strings in a different way or they have an example where it makes sense to produce meaningful lists from other python objects. so why not let users customize the meaning of `@()`? The user just need to define a function producing list of strings (or callables) from any python object. Note that this also makes sense if the default meaning of `@$()` doesn't depend on `@()` as the user could provide a different function for each.

And just one last crazy idea. The function defining `@()` could also receive the current AST node (or a simplification of it) for crazy levels of context dependent customizations. 

If you think any of this makes sense I would love to implement any of it :)

**Comment by astronouth7303** [comment]
Nope. If the string is, say, a filename with spaces, you'll end up in "surprise split" land.

`@($())` is semantically equivalent to `@("spam & eggs")`. This is _why_ we have `@$()`, appropriately splitting command output is Surprisingly Tricky.

In additional, globally customizing core syntax is a Bad Idea, especially in such a highly pluggable shell. While this opens the door for interesting customization for the user, it destabilizes the base on which xontribs can depend on to work everywhere. This does not encourage a thriving ecosystem of interesting and powerful shell-integrated apps.

**Comment by nilehmann** [comment]
Sorry to bring this back up, but at least something must change in the documentation because `@$(cmd)` is not equivalent to `@(i.strip() for i in $(cmd).split())`.

**Comment by astronouth7303** [comment]
No, but it's mostly right. I think it's more of a xonshy split, but the idea is right.

**Comment by nilehmann** [comment]
Then maybe something is wrong because both behave extremely different for newlines.

In master:
```
>>> __xonsh_execer__.parser.lexer.split('a\nb')
['a\nb']
>>> [i.strip() for i in 'a\nb'.split()]
['a', 'b']
```
I think it got lost in all the noise about the customizable `@$()`, but this was my actual concern. I'll be more than happy if `@$(cmd)` behaves (almost) as  `@(i.strip() for i in $(cmd).split())`

**Comment by astronouth7303** [comment]
The actual implementation is [`subproc_captured_inject()`](https://github.com/xonsh/xonsh/blob/master/xonsh/built_ins.py#L854), and it's covered by testing, so I assume that it's behaving as expected.

But I didn't design the splitting rules. Looking at the blame, @adqm, @scopatz, or @gforsyth would be better to people to ask.

**Comment by adqm** [comment]
When I first added `@$(...)`, it did exactly what it says in the docs (which is consistent with Bash).  There was late discussion that caused the split to be "smarter" (to take quoting into account, mostly).  Not sure when that got changed or who made the change.

The idea of user-definable `@$(...)` behavior was actually floated a long time ago when `@$(...)` came into existence (see #926 and [this earlier e-mail thread](https://groups.google.com/forum/#!topic/xonsh/fRoEQR0QGeA/discussion)).  I think we decided against it then, and I think I agree that user-definable default behavior is scary.  But the notion of being able to apply a general filter is interesting; in the PR I linked, @scopatz floated the `@f@g$(...)` syntax for applying functions `g` and `f` to the result, and in the e-mail thread, he floated a different syntax.  Neither ever caught on, but maybe something similar is worth thinking about.

**Comment by adqm** [comment]
From the example above, I would guess that `__xonsh_execer__.parser.lexer.split` only splits on spaces specifically, rather than on spaces or newlines.  Not sure if that's the only issue, but if that is it, then I would imagine it's not too big of a change.  A quick glance at [the relevant function](https://github.com/xonsh/xonsh/blob/master/xonsh/lexer.py#L381-L406) makes it look like it's _trying_ to take newlines into account.  But it seems like there should be an easier way to do what it's trying to do anyway (perhaps relying on [the tokenizer](https://github.com/xonsh/xonsh/blob/master/xonsh/tokenize.py) or [this regex](https://github.com/xonsh/xonsh/blob/master/xonsh/tools.py#L1667-L1670) to separate out strings?).
