### ISSUE TITLE
PROMPT is over when I use command `cat`

### ISSUE THREAD

**Issue by ErickTucto** [xonsh/xonsh#2513]
In image, you see gnome-terminal and [hyper](https://hyper.is/).
In line 8 my **.xonsh** file dont show on terminal when I executed the command `cat .xonshrc`

![capture_2017_10_18_12 34 59](https://user-images.githubusercontent.com/22831024/31733652-ec78bae6-b401-11e7-8e25-96bf80e36725.png)

**Comment by Siecje** [comment]
If you add a new line at the end of your `.xonshrc` file you will see it.

It is being output but then the prompt starts at the start of the line and overwrites it.

https://github.com/xonsh/xonsh/issues/2093

**Comment by gforsyth** [comment]
Note that this is an upstream issue with `prompt_toolkit`.
Closing this out here.
You can workaround the problem by setting `XONSH_APPEND_NEWLINE=True` in your `xonshrc`

**Comment by ErickTucto** [comment]
Thank :+1:

**Comment by scopatz** [comment]
I was also seeing the issue in readline too for some reason.  A more permenant fix is available in #2605
