### ISSUE TITLE
Ncurses based python app does not run correctly on Xonsh, runs fine on Bash

### ISSUE THREAD

**Issue by amitkot** [xonsh/xonsh#2517]
```
pip install cryptop

...

$ cryptop
```
The app's UI is shown, but pressing any key (A to add a coin or Q to quit) does not work, instead the letter is written to the screen.

Runs fine from Bash.

**Comment by gforsyth** [comment]
Hi @amitkot -- thanks for reporting.  We can't always detect ncurses based applications automatically. 

Can you try adding the following to your `xonshrc` and see if the issue persists?  Thanks!

```
__xonsh_commands_cache__.threadable_predictors['cryptop'] = lambda args: False
```

**Comment by gforsyth** [comment]
The easier and less-general fix here is to add `cryptop` to the threadable predictor list [here](https://github.com/xonsh/xonsh/blob/master/xonsh/commands_cache.py#L388-L437) with a `predict_false`.

Better would be to figure out a general way to detect if an application is using `ncurses` and set them as non-threadable.
