### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by Danmou** [xonsh/xonsh#2519]
Currently, whenever a Python error occurs in the xonsh backend (such as in #2515 and #2518), the traceback is just printed to the console. Of course, ideally this kind of error should not occur, but since it does occasionally I think it would be worth it to make them a little less annoying.

As a minimum, the prompt and typed text should be reprinted after the traceback, because currently the behavior is quite weird if the error happens while typing an input. An option to put the tracebacks in a log file instead of printing them could also be useful

**Comment by scopatz** [comment]
Hi @Danmou - I believe that many of the features you are referring to are already implemented.  Checkout 

* `$XONSH_SHOW_TRACEBACK` http://xon.sh/envvars.html#xonsh-show-traceback
* `$XONSH_TRACEBACK_LOGFILE` http://xon.sh/envvars.html#xonsh-traceback-logfile

**Comment by Danmou** [comment]
Thanks @scopatz, I had apparently enabled `$XONSH_SHOW_TRACEBACK` in my `.xonsrc` and forgotten all about it. The only suggestion that remains is reprinting the prompt after showing the traceback, if `$XONSH_SHOW_TRACEBACK` is enabled. However, for my purposes pushing the tracebacks to a log file is good enough, so I can't say if it's worth implementing.

**Comment by scopatz** [comment]
> The only suggestion that remains is reprinting the prompt after showing the traceback,

I'd happily review a PR to that effect :)

**Comment by Danmou** [comment]
After further testing, it appears not all exceptions are stopped by setting `$XONSH_SHOW_TRACEBACK = False`. For example, if I revert the fix you made in #2528 and type `(`, I  will get the traceback regardless of the setting.
Looking at the code, it seems like wrapping `xonsh.ptk.completer.get_completions` in a `try/except` and calling `xonsh.tools.print_exception` on exceptions should fix this specific issue, but shouldn't there rather be some fallback that will catch all exceptions and run them through `print_exception`?

**Comment by scopatz** [comment]
That is a good point @Danmou.  We do have a `print_exception()` that encapsulates the whole main function, so there must be some other except block somewhere that is eating this... It is worth looking into.

**Comment by anki-code** [comment]
Closed because this question is too old and many work around exceptions was done.
