### ISSUE TITLE
Improvements to 'autopair' behavior

### ISSUE THREAD

**Issue by Danmou** [xonsh/xonsh#2520]
Currently, if the `XONSH_AUTOPAIR` setting is enabled, entering any of the characters `' " ( [` will also insert its matching counterpart to the right of the cursor. This behavior is often more annoying than useful, for example when you are trying to wrap some text in quotes after writing it. To make it more useful, and in line with the behavior in popular editors like Sublime Text, I would suggest the following changes:

* For quotes `'` and `"`, the matching quote should only be inserted if there is whitespace (or BOL/EOL) on both sides of the cursor.
* For brackets `(`, `[` and `{` (note that `{` is not currently included in the autopair behavior), the matching bracket should only be inserted if there is whitespace (or EOL) to the right of the cursor.
* Pressing backspace when the cursor is between a matching pair, e.g. `'|'` or `(|)` should delete both characters.

Examples (where `|` represents the cursor):

`echo |some text {that needs to be put in quotes}` -> press `'`
* Current behavior: `echo '|'some text {that needs to be put in quotes}`
* Desired behavior: `echo '|some text {that needs to be put in quotes}`

`echo 'some text {that needs to be put in quotes}|` -> press `'`
* Current behavior: `echo 'some text {that needs to be put in quotes}'|'`
* Desired behavior: `echo 'some text {that needs to be put in quotes}'|`

`|2 + 2) / 5` -> press `(`
* Current behavior: `(|)2 + 2) / 5`
* Desired behavior: `(|2 + 2) / 5`

`function(|)` -> press backspace
* Current behavior: `function|)`
* Desired behavior: `function|`

### Edit:
To make autopair work properly inside nested brackets, we have to allow a closing bracket instead of whitespace on the right side of the cursor, and an opening bracket on the left side of the cursor. For example:

`function(|)` -> press `'`
* `function('|')`

`function()|` -> press `[`
* `function()[|]`

**Comment by Danmou** [comment]
I've submitted a PR that implements this.

**Comment by scopatz** [comment]
Thanks for this @Danmou!
