### ISSUE TITLE
point release?

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2523]
since the repository seems to have been stable for a few weeks, could a point release be created which might also get the reorganized docs published on the website?

**Comment by gforsyth** [comment]
Yes, we're well overdue.  I'll try to put out a point release later this week.

**Comment by ahundt** [comment]
Thanks!

**Comment by scopatz** [comment]
Yes, we are way overdue :)

**Comment by scopatz** [comment]
We could probably even go for a v0.6.0 at this point
