### ISSUE TITLE
Add pf-strings

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2524]
Add support for pf-strings. That is, an f-string that is cast to a `Path`.

**Comment by t184256** [comment]
Could you post a link to a description of those 'pf-strings'?

**Comment by gforsyth** [comment]
Hey @t184256 -- they don't really exist.  We have p-strings in xonsh, that work like:

```
 ~ 🐚  p'/home/gil/xonsh'
PosixPath('/home/gil/xonsh')
```

So a pf-string might be something like
```
 ~ 🐚  pf'{HOME}/xonsh'
PosixPath('/home/gil/xonsh')
```

**Comment by MrQubo** [comment]
I want to mention that the evaluation of env variables inside of p-strings is already supported.
```
$ p'$HOME'
PosixPath('/home/arch')
```

**Comment by MrQubo** [comment]
Seems like this need some additions [here](https://github.com/xonsh/xonsh/blob/fd448e515a36cf23a4f03f4e6b16c9dd227196b7/xonsh/parsers/base.py#L2322-L2335).
