### ISSUE TITLE
Unknown Terminal type using conda env (Windows 10 --> WSL)

### ISSUE THREAD

**Issue by pyeguy** [xonsh/xonsh#2525]
Getting some weird behavior using a conda environment in windows subsystem for linux. 
If I enter the env (USING XONDA) and try to `clear` the screen i get an `unknown terminal type` error

```
cpye@DESKTOP-0IGRTG4                                                                                            [~/pydev]
$ $TERM
'xterm-256color'
cpye@DESKTOP-0IGRTG4                                                                                           [~/pydev]
$ conda activate macrolib
(macrolib) cpye@DESKTOP-0IGRTG4                                                                          [~/pydev]
$ clear
'xterm-256color': unknown terminal type.
```

but when i deactivate the env it works fine...

xonfig:
```
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.6.3               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.15              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by gforsyth** [comment]
Hey @pyeguy -- thanks for reporting.  

Is there a difference in the output of `which clear` when the environment is activated or not?

**Comment by pyeguy** [comment]
@gforsyth 

yes there is:
no env:
```
$ which clear
/home/cpye/miniconda3/bin/clear
```
in env:
```
(macrolib) cpye@DESKTOP-0IGRTG4                                                            
$ which clear
/home/cpye/miniconda3/envs/macrolib/bin/clear
```

**Comment by pyeguy** [comment]
also if i use `/home/cpye/miniconda3/bin/clear` while in the env it works and i get no error...

**Comment by gforsyth** [comment]
Can you try a `which -a clear` (without the env activated) and see if there's a WSL "native" version of `clear` built in?  And if there is, can you try running that both in and out of the env?

**Comment by gforsyth** [comment]
Oh yeah, and what happens if you run `/home/cpye/miniconda3/envs/macrolib/bin/clear` when _not_ in the environment?

**Comment by pyeguy** [comment]
all good diagnostics!

`which -a clear` output **inside** env:
```
/home/cpye/miniconda3/envs/macrolib/bin/clear (from PATH element 0)
/home/cpye/miniconda3/bin/clear (from PATH element 3)
/usr/bin/clear (from PATH element 7)
```

`which -a clear` output **outside** env:
```
/home/cpye/miniconda3/bin/clear (from PATH element 2)
/usr/bin/clear (from PATH element 6)
```
`/usr/bin/clear ` **works** inside  _**and**_ outside the env

`/home/cpye/miniconda3/envs/macrolib/bin/clear`  **fails** inside _**and**_  outside the env

**Comment by gforsyth** [comment]
Ok, I think this is a problem with anaconda? 
Can you see if there is a terminfo file for `xterm-256color` in `/home/cpye/miniconda3/envs/macrolib/share/terminfo/x/`?
And if not, symlinking the one that I'm pretty sure exists in `/home/cpye/miniconda3/share/terminfo/x/` to that location should fix this.  
Not sure why the terminfos aren't making it through when you create a new environment...

**Comment by pyeguy** [comment]
sorry for the delayed response, and sorry to dash your hypothesis, there is a `xterm-256color` in the `/home/cpye/miniconda3/envs/macrolib/share/terminfo/x/` directory...

**Comment by gforsyth** [comment]
Ok, thanks @pyeguy.  Can you try creating a new environment and confirming that `clear` malfunctions there, as well?  I may be missing some setting in the activate function in `xonda`

**Comment by anki-code** [comment]
hi @pyeguy! Does this still actual?
