### ISSUE TITLE
Support add operation between EnvPath and list

### ISSUE THREAD

**Issue by rnarkk** [xonsh/xonsh#2533]
It's comfortable if you can write $PATH like:
```
$PATH = ['/usr/local/bin'] + $PATH
```
maybe in `~/.xonshrc` file.

It can be implemented by `__add__` special method as you know.

Why don't we support that?

**Comment by scopatz** [comment]
Thanks for reporting @rnarkk.  Actually, isn't that an radd? I believe that we do support add.  PRs most welcome!

**Comment by rnarkk** [comment]
Thank you @scopatz . Maybe both `__add__` and `__radd__` are to be implemented. I'll try it.

**Comment by astronouth7303** [comment]
#2446

**Comment by rnarkk** [comment]
Thanks @astronouth7303.

I confirmed the latest version that can be installed via pip (v0.5.12) was not supported add operation, but it's already implemented in master branch.

Then I will wait for the new version to be released. thank you all!
