### ISSUE TITLE
Xonsh crashes hard on files named `~`

### ISSUE THREAD

**Issue by traverseda** [xonsh/xonsh#2540]
Let's not get into why I have a file named `~`.

xonsh/0.6.0 running under pypy.

```
traverseda@demesne ~ $ ls \~
ls: cannot access '\~': No such file or directory
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 14820, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2322, in run_compiled_code
    func(code, glb, loc)
  File "/opt/pypy3/site-packages/xontrib/vox_tabcomplete.xsh", line 1, in <module>
    def _vox_completer(prefix, line, begidx, endidx, ctx):
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19376, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19339, in run_subproc
    command.end()
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12645, in end
    self._end(tee_output=tee_output)
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12664, in _end
    self._raise_subproc_error()
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12774, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['ls', '--color=auto', '-v', '\\~']' returned non-zero exit status 2
```

And then it enters into an infinite loop.

**Comment by scopatz** [comment]
Oof thanks for reporting!

**Comment by traverseda** [comment]
I think the infinite error loop is #2366 related.

**Comment by scopatz** [comment]
I am having trouble replicating this.  First because I think that `~` is not escaped by `\~`.  I think in this case you might need to use the absolute path.

**Comment by scopatz** [comment]
I don't see an exception or error either though...

**Comment by traverseda** [comment]
> think that ~ is not escaped by \~.

Is is on bash, is escaping supposed to work differently on xonsh?

I suspect the exception on-error is actually #2366 related. I can replicate it pretty consistently. But it looks for all the world like some syscalls are just failing.

Might by pypy-related? When I get a few minutes I'll try it under CPython3.

```
Python 3.5.3 (d72f9800a42b46a8056951b1da2426d2c2d8d502, Oct 05 2017, 15:57:05)
[PyPy 5.9.0-beta0 with GCC 7.2.0]
```

**Comment by scopatz** [comment]
> is escaping supposed to work differently on xonsh

Yeah, xonsh uses Python's escaping rules, not bash's. 

>  But it looks for all the world like some syscalls are just failing.

That would be really bad! Maybe it is some PyPy thing we can identify or work around...

**Comment by traverseda** [comment]
Doesn't look pypy related, I'm seeing the same behavior under CPython `Python 3.6.3`.

The pypy virtualEnv was fresh. I've got to get some breakfast, and I'm not really sure where to start with tracking this problem down.

```
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/home/alex/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():
  File "/home/alex/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 470, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (4, 'Interrupted system call', None, None, None)
```

Which isn't anything new. I can very reliably reproduce it though.

**Comment by traverseda** [comment]
```
cffi (1.11.1)
greenlet (0.4.12)
pip (9.0.1)
prompt-toolkit (1.0.15)
readline (6.2.4.1)
setuptools (28.8.0)
six (1.11.0)
wcwidth (0.1.7)
xonsh (0.6.0)
```
Things that did not work

 * Installing and running via cpython
 * Reinstalling all dependencies 
 * Running in a chroot
 * removing my bashrc
 * **Setting the shell_type to readline**

That did differentiate the errors in CPython/pypy though. https://pastebin.com/m8Wp5Jbt

**Comment by traverseda** [comment]
What did work, deleting my `.config/xonsh/config.json`. I would recommend including a xonsh version in that file.

**Comment by gforsyth** [comment]
Well, let's call that another vote for getting rid of static config files

**Comment by traverseda** [comment]
Yeah, I never really saw a use for it, but it seemed like "best practice" so I gave it a shot, and mostly forgot it existed.

I am still confused that `ls \~" didn't work, and I'm not sure how one would format that command. Let alone the dreaded `rm \~ -r`. But that's not really important. Closing this now.

**Comment by scopatz** [comment]
> I am still confused that ls \~" didn't work, and I'm not sure how one would format that command

So tilde expansion only happens when the tilde is the beginning of a token (like in Bash), so if you had a file locally that has a tilde, you could do either of the following:

```
$ ls ./~
$ ls /path/to/~
```
