### ISSUE TITLE
calling `help(which tty)` when using coreutils xontrib causes xonsh to xrash

### ISSUE THREAD

**Issue by traverseda** [xonsh/xonsh#2541]
Crashes to shell. I would expect output similar to `which -a tty`.

**Comment by traverseda** [comment]
Huh, I am not currently getting a crash, just a traceback. Which is perfectly a perfectly reasonable way to handle that. Not sure what's up with that, but it's not really an issue.

**Comment by scopatz** [comment]
Glad that this resolved itself!
