### ISSUE TITLE
Get rid of static config files

### ISSUE THREAD

**Issue by traverseda** [xonsh/xonsh#2542]
I didn't want to close #2540 until there was a ticket open. So here it is.  #2510 also references this.

Good idea, bad idea? Well at least we've got a ticket to collect that information in.

**Comment by scopatz** [comment]
I think the consensus is that it is a good idea. The only tricky part is how we adjust the wizard to account for this.

**Comment by scopatz** [comment]
(Un)implemented in #2567

**Comment by astronouth7303** [comment]
Is the expectation that the wizard will be able to modify arbitrary `.xonshrc` files? Will it be able to modify existing ones at all?

**Comment by scopatz** [comment]
> Is the expectation that the wizard will be able to modify arbitrary .xonshrc files?

Yes

> Will it be able to modify existing ones at all?

Yes, it can.  The code that the wizard produces is commented blocked by:

```python
# XONSH WIZARD START
AUTO_SUGGEST_IN_COMPLETIONS = ''
$COMPLETIONS_DISPLAY = 'single'
$COMPLETION_QUERY_LIMIT = '10'
...
# XONSH WIZARD END
```

If a user reruns the wizard, this block is replaced.  Right now it defaults to writing to `~/.xonshrc`, but we could change the default to something like `~/.local/config/xonsh/xonshrc` and adding that path to the default $XONSHRC list. However, at the end of the day we still need to write something to userspace for this to work.

**Comment by Daniel-at-github** [comment]
Maybe importing a wizard generated specific file could make the trick.

Example:

`~/.xonshrc`
~~~ py
import os.path
if os.path.isfile(os.path.expanduser('~/.local/config/xonsh/xonshrc_wizard')):
    source '~/.local/config/xonsh/xonshrc_wizard'
~~~

`~/.local/config/xonsh/xonshrc_wizard`
~~~ py
# XONSH WIZARD FILE
# Do not edit!!. It will be overwritten by xonfig.
...
~~~
