### ISSUE TITLE
Weird Drawing of nano

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2543]
`nano` draws... weirdly under xonsh 0.6.0, but fine under bash.

**Comment by scopatz** [comment]
Thanks for reporting @astronouth7303! It draws fine for me, but it does seem to eat control sequences for me sometimes like ^X

**Comment by astronouth7303** [comment]
![screenshot from 2017-11-28 16-21-13](https://user-images.githubusercontent.com/401438/33348327-050130ca-d464-11e7-991d-2462df830468.png)

The header isn't drawn, the footer is drawn badly, and the cursor is in the wrong place.

**Comment by scopatz** [comment]
hmm it is like it is getting the wrong terminal size.  Have you tried it in other terminal emulators?

**Comment by astronouth7303** [comment]
On further testing, xonsh on bash on QTerminal works fine. xonsh on LilyTerm (VTE) doesn't work. Bash on LilyTerm works. xonsh on LilyTerm fails.

**Comment by scopatz** [comment]
Good to know! Probably an issue somewhere with termios...

**Comment by astronouth7303** [comment]
This might be sizing issues. `man` isn't formatting right, either.

**Comment by scopatz** [comment]
Also, which shell are you using? Readline or PTK?

**Comment by astronouth7303** [comment]
PTK.

**Comment by astronouth7303** [comment]
And `stty size` appears to be reporting the correct value....

**Comment by astronouth7303** [comment]
Sorted it. `$COLUMNS` and `$LINES` were set incorrectly. Deleting them fixed it.

Should we do anything about them in xonsh? The default would be to set a xontrib to do it, but I don't like having default xonsh being potentially broken.

**Comment by scopatz** [comment]
Weird, yeah, default xonsh should not be broken and I think this should be a fix in xonsh itself.  On my machine COLUMNS and LINES aren't set at all...  Also Bash is doing something weird where these aren't real variables (if you look at the output of `env`) but then if you do `echo $LINES` it will give the right value.

Maybe we should be popping these variables out of the environment when we run a subprocess?  Or putting them in at the proper value?

**Comment by astronouth7303** [comment]
My initial thought was to remove them from the environment on initialization.

Maybe with a bundled xontrib that will add them to the environment and update them when the terminal changes? (Which implies an event that fires when the terminal changes size.)

**Comment by scopatz** [comment]
I am all for that, but it seems like it shouldn't even be a bundled xontrib, but just part of xonsh. Though I wouldn't say no to a bundled xontrib :)

**Comment by astronouth7303** [comment]
I'd want to do more research on the role of `$LINES` & `$COLUMNS` and how applications use them before including them in the default environment, especially since this is in opposition to other shells.

**Comment by scopatz** [comment]
Turns out Bash considers COLUMNS and LINES local variables, and so they are not exported: http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_02.html

**Comment by astronouth7303** [comment]
So, unset them during environment initialization?
