### ISSUE TITLE
Question: How to set env for subprocess?

### ISSUE THREAD

**Issue by roxma** [xonsh/xonsh#2553]
Hi, thanks for this amazing project,

I've been searcing around the documentation, but I can't find an equivalence command for 
`HTTP_PROXY=myproxy curl www.google.com`

With bash, I have an `alias proxy="http_proxy=myproxy https_proxy=myproxy "`, so that I can use proxy when I need to, e.g. `proxy curl www.google.com`.  Is it possible with xonsh?

**Comment by roxma** [comment]
Current working attempt

```
def proxy(args):
    def impl():
        $http_proxy='....' 
        $https_proxy=''....' 
        return args
    $[@(impl())]

aliases['proxy'] = proxy
```

**Comment by gforsyth** [comment]
Hey @roxma -- you can take a look here for how to use the `swap` method on the env: http://xon.sh/bash_to_xsh.html?highlight=swap

You can also use the `env` command, 
```
env HTTP_PROXY='....' mycommand
```

**Comment by roxma** [comment]
Thanks

**Comment by scopatz** [comment]
Also, I'd happily welcome any PRs that add support for this, though I think we'd probably want the syntax `$HTTP_PROXY='....' mycommand`

**Comment by astronouth7303** [comment]
I'd be happy with PRs to that effect with considerable test coverage.
