### ISSUE TITLE
Wildcards in quotes not working

### ISSUE THREAD

**Issue by AlecRosenbaum** [xonsh/xonsh#2563]
Wildcards in quotes don't seem to be working. For example:

```
 $ ls *
'asdf asdf.txt'   asdf_asdf.txt
 $ ls '*'
ls: cannot access '*': No such file or directory
```

This is only really a problem in cases where you want to wildcard names that have spaces in it. For example:

`cp '~/test directory/test*' ` or `ls '~/test/test *'`

**Comment by astronouth7303** [comment]
I believe this is by design.

You can also use explicit [backtick globs](http://xon.sh/tutorial.html#advanced-path-search-with-backticks).

**Comment by AlecRosenbaum** [comment]
Oh cool! I didn't realize that was a feature. Thanks!

**Comment by jaraco** [comment]
I have this issue also.

```
~ $ ls '/Volumes/Documents/Kubernetes Keys'
kubernetes-admin.key     kubernetes-admin-other.key
~ $ cp '/Volumes/Documents/Kubernetes Keys/*' ~/yg/devops/kubernetes/client
cp: /Volumes/Documents/Kubernetes Keys/*: No such file or directory
```

I was able to use the backtick globs to workaround the issue:

```
~ $ cp `/Volumes/Documents/Kubernetes Keys/.*` ~/yg/devops/kubernetes/client
```

It does seem to me a little awkward that regular globbing can't work inside quotes, but not entirely surprising, especially if `'*'` is meant to represent the literal `*`.
