### ISSUE TITLE
Port to PTK 2.0!

### ISSUE THREAD

**Issue by tgoodlet** [xonsh/xonsh#2564]
I've been trying to hack a bit on `xonsh` and found I need to add some stuff to `python-prompt-toolkit` to get the new features I want in but it seems `xonsh` has in no way been ported to the [ptk 2.0 branch](https://github.com/jonathanslenders/python-prompt-toolkit).

I would prefer to get the new features working on the latest code bases and am willing to start that effort on a branch as long as we can come to a xonshensus that it's a good idea.

Let me know what the sentiment is :)

**Comment by scopatz** [comment]
Yes please! We'd love to have ptk 2.0 support!

**Comment by melund** [comment]
That sounds awesome. I believe @jonathanslenders [once promised us a merge request when PTK 2.0 was released](https://github.com/xonsh/xonsh/pull/2125#issuecomment-276023785) so he would probably be more than happy if someone else started the task.

**Comment by jonathanslenders** [comment]
Hi all, yes, I'm more than happy that you start working on this. Right now prompt_toolkit 2.0 is becoming stable. I don't see any changes to the architecture coming, and right now, I'm basically fixing bugs (when reported) and writing documentation. Feel free to ping me if you have questions, or if you need some help.

**Comment by Achimh3011** [comment]
Hi, looks like this issue can be closed after PTK2.0 support was already added. 
Or am I missing something here?

**Comment by melund** [comment]
Thanks @Achimh3011
