### ISSUE TITLE
source updates __name__

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#2572]
When `source` is used, the global context's `__name__` is updated from `"__main__"` to the filename that was sourced.

**Comment by scopatz** [comment]
Ahh that should be fixed.  It is a matter of swapping the name back the "__main__" after the source if complete.

**Comment by scopatz** [comment]
Hmmm, it should already be doing this... Can you please provide a more complete example? Thanks!

**Comment by scopatz** [comment]
Specifically, this line: https://github.com/xonsh/xonsh/blob/master/xonsh/aliases.py#L300

**Comment by astronouth7303** [comment]
Sorry, I don't have the computer I observed this on anymore. I was just sourcing a script that collected a bunch of metrics, so I could manipulate them in a xonsh environment.

**Comment by anki-code** [comment]
```python
echo 'print(__name__)' > 1.xsh
xonsh 1.xsh
# __main__
```

This issue looks not actual and should be closed.

**Comment by anki-code** [comment]
Oh, my bad, I can repeat:
```python 
# xonsh 0.9.24
cd /tmp
echo 'print(__name__)' > 1.xsh
source 1.xsh 
/tmp/1.xsh
```

**Comment by scopatz** [comment]
I think it should return `__main__` or the filename.

**Comment by anki-code** [comment]
So it works as expected:
```python
cd /tmp
echo 'print(__name__)' > 1.xsh
source 1.xsh 
# /tmp/1.xsh

echo @(__name__)
# __main__


# Prepared by xontrib-hist-format
```
