### ISSUE TITLE
'cat large_binary_file' followed by ^C followed by any command fails with endless stream of 'Interrupted system call' errors

### ISSUE THREAD

**Issue by j-c-w** [xonsh/xonsh#2581]
Hi,

I have a core dump in my home directory.  Running:

 `    cat core`

Pressing ^C is a little bit unresponsive, but does kill the process (not directly the issue*). Subsequently running 'ls' results in an infinite stream of:

```
jackson@jackson-laptop ~ $
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
terminos.error: (4, 'Interrupted system call')
```

Setting show traceback before doing this results in an infinite stream of:

```
jackson@jackson-laptop ~ $

xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():
  File "/usr/lib/python3/dist-packages/prompt_toolkit/terminal/vt100_input.py", line 470, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (4, 'Interrupted system call')
```

xonsh --version yields

`xonsh/0.5.12
`
*I say this because from a user perspective it seems as though there might be a bunch of stuff from the file getting dumped into the standard input.  If this is the case, it is just very very long.

Hitting ^C a few times before typing a new command prvents this infinite stream from occurring.

Jackson

**Comment by gforsyth** [comment]
Hey @j-c-w -- thanks for reporting!
I don't imagine it will make a difference, but can you try to upgrade to `0.6.0` and see if the issue persists?  Thanks!

**Comment by anki-code** [comment]
Hi @j-c-w! Could you try to update xonsh and repeat the test?
