### ISSUE TITLE
rustc 100% cpu after tab completion

### ISSUE THREAD

**Issue by offero** [xonsh/xonsh#2582]
rustc 100% cpu after tab completion.

> vim ~/\<tab\>

I'm not sure if this is due to xonsh or something else, but I can't tab complete anything.

Mac OSX 10.13.2
iTerm2 3.1.5

**Comment by astronouth7303** [comment]
What's your `xonfig` output? I'm not sure what `rustc` has to do with completions...

**Comment by anki-code** [comment]
I can't reproduce this. Looks not actual and should be closed.
