### ISSUE TITLE
Programmatic Auto-Suggestions 

### ISSUE THREAD

**Issue by enricozb** [xonsh/xonsh#2586]
I know that we can programmatically modify the behavior of tab-completion by changing entries in `__xonsh_completers__`, but I'm curious if there is any way to also modify the auto-suggestions? The main reason that I want to do this is that auto-suggestions does not take into account if the files in the command line arguments exist, it primarily (if not only) relies on the history.  For example,

```
$ ls dir1
    file1.txt
$ ls dir2
    file2.txt
$ cd dir1
$ vim dir1
$ cd ../dir2
$ vim |
```
If `|` is the current cursor position, `vim file1.txt` will be the autosuggestion, even though `file2.txt` is what should be suggested, assuming it is in the history. I know that this is difficult to get right in general but I think I can modify it to suit my needs. 

The way I plan to do this is check that, before a command is run, it checks which command-line arguments match to files, and it wont suggest that instance of that command again unless all of the arguments that matched files previously match files again.

 How would I go about this?

**Comment by gforsyth** [comment]
Hi @enricozb -- 

It's going to be a little involved. We use the default `prompt_toolkit` setting which makes use of the `prompt_toolkit` function `AutoSuggestFromHistory`

The line in question is here: https://github.com/xonsh/xonsh/blob/master/xonsh/ptk/shell.py#L149

You might want to take a look at https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/prompt_toolkit/auto_suggest.py, specifically the `ConditionalAutoSuggest` which may help you accomplish what you're after.  

Then the default filter could be `None` or just a filter that does a complete passthrough by default and then you could edit it accordingly.

**Comment by enricozb** [comment]
This put me on the right track. I was hoping to not have to modify the source, and instead only modify my `~/.xonshrc` and maybe monkey patch `AutoSuggestFromHistory`, but that was too convoluted.

Now, only commands that are likely to run, based on the presence of the command line arguments as files, will be suggested. I also have command line arguments auto-suggest to a file in the current directory.

I think xonsh's default auto-suggest still has some improving to do. Fish's auto-complete as it stands is much more natural than xonsh's

Thanks for your help!

**Comment by scopatz** [comment]
@enricozb pull requests welcome for any improvements!  We'd be happy to have them. Feel free to reopen if needed.
