### ISSUE TITLE
Feature request: @$(...)

### ISSUE THREAD

**Issue by ndemou** [xonsh/xonsh#2587]
Sometimes I need to compose a complex bash command using python and capture its output in order to again process it with python. So I'm writing code like this:
```
cmd = ... # python code to compose a somewhat complex bash command
ret = $(bash -c @(cmd)) # run cmd and capture the output
... # python code to process the output
```
So IMHO it would be nice to add an operator like `$@(...)` that would do the same thing as `$(bash -c @(cmd))`. By the way it would also be ... pretty (in some geeky sense of prettiness) if both @$ and $@ do something :-).

**Comment by gforsyth** [comment]
Hey @ndemou, 
I can definitely understand the allure of streamlining oft-used commands.  
I would gently push back against adding an operator to do this, as it's specific to bash and I'm also a little bit concerned that it's too easy to mix up with `@$`. 
One thing that immediately came to mind is to set up an alias for this, something like:

```console
def evalbash(args):
    return $(bash -c @(args))

aliases['evalbash'] = evalbash
```

**Comment by ndemou** [comment]
Yes I can understand your feelings. Thanks for the tip. Oh! and thanks for xonsh -- I love it! Especially now that I also discovered the fantastic pyfunctional library. xonsh + pyfunction made it a joy to do complex processing of text files in way that is often better and more powerful than using long bash lines which compine grep,sed,cut,sort and uniq with pipes. Here's a snippet from my xonsh history:

```
from pyfunctional import seq
( seq.open('/tmp/foo').  
filter(lambda x: 'grep grep' not in x).
map(lambda x: [len(x.split('|')), x.split('|')]).
filter(lambda x: x[0]>6).
map(lambda x: x[1]).
map(lambda x: seq(x).
map(lambda x: x.partition(' ')[0]) ).
flatten().sorted().distinct()
)
```
