### ISSUE TITLE
Conditionally add Commands to History

### ISSUE THREAD

**Issue by enricozb** [xonsh/xonsh#2588]
I only want the history to contain commands that ran with non-zero error code. I want slightly more control than this though, as I only want this to apply for certain commands. `cd`, `apt`, and some others.

How would I go about this?

**Comment by gforsyth** [comment]
Hi @enricozb -- sorry for the delay in responding to this.  

To do this you will have to write a custom history backend.  There is a tutorial here on how to do this: http://xon.sh/tutorial_history_backend.html

In short, customize the `append` method with some conditionals to apply your requirements for what gets saved.

**Comment by gforsyth** [comment]
I'm going to close this issue, but please feel free to post any followup questions here.
