### ISSUE TITLE
"Command not found" when using ![] operator with backslashes (Windows)

### ISSUE THREAD

**Issue by igortg** [xonsh/xonsh#2590]
Running commands with `![]` operator throws "command not found" when using backslashes:
```
$py_cmd = 'C:\\work\\envs\\flask-rest-orm\\python'
![$py_cmd]
>> xonsh: subprocess mode: command not found: C:\work\envs♀lask-rest-orm\python

subprocess.call($py_cmd)
>> OK
```

Seems that `![]` is not using the raw string.

**Comment by gforsyth** [comment]
Thanks for reporting @igortg -- yeah, we should probably be using raw strings.  

For now as a temporary workaround you can set `$py_cmd = r'C:\\work\\envs\\flask-rest-orm\\python'` and it should work

**Comment by scopatz** [comment]
Hmm why did this shift from the C drive to the W drive?

**Comment by igortg** [comment]
I edited the output before posting to avoid confusion, but seems that I just made it worth ;) 

fixed

**Comment by scopatz** [comment]
hahah OK. Well, please feel free to reopen if needed
