### ISSUE TITLE
Autocomplete doesn't understand multi-space in name of a file

### ISSUE THREAD

**Issue by riwogo** [xonsh/xonsh#2596]
xonsh autocomplete can't understand multi-space (more than one space) in name of a file and consider it as one space the following gif will show it: [bug gif](https://ibb.co/eVno7x)

**Comment by gforsyth** [comment]
Hi @riwogo -- thanks for reporting!  Yep, that's definitely a bug.

**Comment by scopatz** [comment]
I think this may technically be a bug in https://github.com/xonsh/py-bash-completion

**Comment by scopatz** [comment]
Potential fix is in https://github.com/xonsh/py-bash-completion/pull/4

**Comment by scopatz** [comment]
Fix available in #2604
