### ISSUE TITLE
Escaping #

### ISSUE THREAD

**Issue by worldmind** [xonsh/xonsh#2602]
I try to remove emacs backup file - it name start from # 
```
rm #file.bak#
/bin/rm: missing operand
```
looks like xonsh think that it is comment
bash autoescape # symbol
`rm \#file.bak#`

How escape it in xonsh?

**Comment by gforsyth** [comment]
Hi @worldmind -- `xonsh` uses quotes to escape, so you can `rm '#file.bak#'`

**Comment by worldmind** [comment]
@gforsyth many thanks, maybe I miss it in docs

**Comment by worldmind** [comment]
Some difference with bash - bash escape special characters in file names automatically after TAB completion, maybe xonsh must do it like bash?

**Comment by gforsyth** [comment]
Hey @worldmind -- fix in #2612
