### ISSUE TITLE
XDG Directory Specification

### ISSUE THREAD

**Issue by dosimple** [xonsh/xonsh#2609]
Xonsh already supports XDG Directory Specification. So why doesn't xonsh implement it also for per-user run control file `(~/.xonshrc)`?

**Comment by scopatz** [comment]
Hi @dosimple, I am a little confused. We do support a `~/.xonshrc` file, see http://xon.sh/xonshrc.html. Or are you suggesting that we support something in the `$XDG_CONFIG_HOME` dir, like `~/.config/xonsh/rc.xsh`?

**Comment by dosimple** [comment]
Hi @scopatz, I meant the second one, like `~/.config/xonsh/rc.xsh`.

**Comment by scopatz** [comment]
This is something that would be relatively easy to add, I think.

**Comment by gforsyth** [comment]
Not a blocker necessarily, but we should think about what happens if you set your `$XDG_DATA_HOME` in your `xonshrc`

**Comment by scopatz** [comment]
Yeah, good point @gforsyth - I am not sure that is a valid action according to the spec (but would have to double check).  It might be interesting to have interactive-read-only  environment variables...

**Comment by scopatz** [comment]
Added this in #2611
