### ISSUE TITLE
When quitting midnight commander, navigate to the directory last visited

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#2617]
Many of us use midnight commander. One desired feature is that when you exit midnight commander, you usually want the shell to be in the directory last visited in mc. Most distributions will have wrapper scripts for mc in each shell (bash, zsh, etc) to allow you to do that. I decided to tackle this for xonsh. 

My solution (placed in .xonshrc):

    MC_TMP_DIR = '/tmp/mcdir'
    def _mc(args):
        if not os.path.exists(MC_TMP_DIR):
            os.mkdir(MC_TMP_DIR)
        if not os.path.isdir(MC_TMP_DIR):
            print("Sorry, I cannot create the temporary directory %s" % MC_TMP_DIR)
        pid = os.getpid()
        mc_filename = os.path.join(MC_TMP_DIR, "%d" % pid)
        $[/usr/bin/mc -P @(mc_filename) @(args)]
        directory = $(cat @(mc_filename)).strip()
        $[cd @(directory)]
        $[rm @(mc_filename)]

    aliases["mc"] = _mc

Thought I'd post here in case someone else wants to do the same.

**Comment by melund** [comment]
Thanks, @beetleb. I think this really deserves to be a [xontrib](http://xon.sh/tutorial_xontrib.html#tutorial-extensions-xontribs). So if you (or anyone else) will do this, that would be awesome.
