### ISSUE TITLE
Question: how make sudo expand aliases?

### ISSUE THREAD

**Issue by t184256** [xonsh/xonsh#2618]
What is the official way to make sudo expand aliases, like `alias sudo='sudo '` on bash?

This is what I tried:
```xsh
$ACTUAL_SUDO = $(which sudo)
def sudo_expanding_aliases(args):
    $ACTUAL_SUDO @(aliases.eval_alias(args))
aliases['sudo'] = sudo_expanding_aliases
del sudo_expanding_aliases
```

This works, but it's kinda verbose and pollutes the environment.

```xsh
def sudo_expanding_aliases_clojure():
    actual_sudo = $(which sudo)
    def sudo_expanding_aliases(args):
        @(actual_sudo) @(aliases.eval_alias(args))
    return sudo_expanding_aliases
aliases['sudo'] = sudo_expanding_aliases_clojure()
del sudo_expanding_aliases
```

That one is a syntax error around the `return sudo_expanding_aliases` and I have no idea why. It's also even more verbose and ugly.

Am I thinking in the correct direction? Is it a good idea in general? Am I doing the expansion right? How can I reduce environmental pollution?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hi @t184256 - thanks for bringing this up!  I think this might be an oversight more that a question.  Your workaround certainly is effective.  

For Tab completion, the code to expand the aliases is at https://github.com/xonsh/xonsh/blob/5a2c077ec1c2b9b6ed0a119cb9c69a713881fb38/xonsh/completers/commands.py#L32  Any PRs or help would be most welcome!

In terms of expanding the command and running it, I think you are doing it correctly. Something like this should probably just be part of xonsh itself.  If you felt like putting in a PR to modify [aliases.py](https://github.com/xonsh/xonsh/blob/5a2c077ec1c2b9b6ed0a119cb9c69a713881fb38/xonsh/aliases.py) that would be awesome!

**Comment by anki-code** [comment]
Just want to leave this the short version:

```python
aliases['sudo'] = lambda args: $[@($(which -s sudo)) @(aliases.eval_alias(args))]
```

Sad but the case with `sudo ls | less` still not working in xonsh 0.9.27.

**Comment by anki-code** [comment]
I've taken a short look into this. 

1. At this time the alias resolving is working only for the first argument. And `bash ls` (where `ls` is alias `ls --color`) is working like in bash (without resolving).

2. I've also tried ExecAlias to solve this but without success (with #4201):

```python
aliases['sudo'] = '/usr/bin/env sudo @(aliases.eval_alias($ALIAS_ARGS))'
sudo ls | less
# no response
```

3. The start point to research is here:

https://github.com/xonsh/xonsh/blob/7168b262ae35d0ee97a7c2970742d73f494e61c4/xonsh/procs/specs.py#L589-L596

It looks like we should have a feature to resolve the second argument in certain commands like `sudo`.
