### ISSUE TITLE
Update Docs to say which versions of ubuntu xonsh is available for

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#2621]
As in title. Maybe @CJ-Wright wants to take a stab at this one? :)

**Comment by CJ-Wright** [comment]
I guess the docs building code can inspect the ubuntu website?

**Comment by scopatz** [comment]
No no, I would just go for somethign simple like looking it up and putting the version X.Y+

**Comment by scopatz** [comment]
There is no point automating something that only needs to be done once :wink:

**Comment by CJ-Wright** [comment]
Ah ok can you assign this to me?

**Comment by CJ-Wright** [comment]
bionic: 0.6.0+dfsg-1
artful: 0.5.12+dfsg-1

**Comment by scopatz** [comment]
Oddly no.  It doesn't let me assign it to you

**Comment by CJ-Wright** [comment]
Huh, maybe I'm not a member of the org?

**Comment by scopatz** [comment]
Yeah I don't think you are

**Comment by CJ-Wright** [comment]
Well let me put in this PR and then I'll be a contributor I think.
