### ISSUE TITLE
stdout/stderr out of order when using rwt or Powershell under xonsh

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#2632]
I'm using a pre-release of xonsh on macOS 10.13.

I originally discovered this issue with [rwt](https://pypi.org/project/rwt), a project I maintain (and use regularly) that installs to a temporary location Python dependencies and then launches a Python instance with those dependencies available. When invoked without any parameters, it runs in a degenerate mode, not installing any dependencies but only launching the Python interpreter.

When running under zsh, the python interpreter that's launched runs as expected with stdout and stderr emitted at the expected times.

```
~ $ zsh
$ rwt
Python 3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 08:11:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined
>>>
```

And when running without rwt, the expected order is observed.

```
~ $ python
Python 3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 08:11:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined
>>> ^D
```

But when running under rwt, the io streams are out of order.

```
~ $ rwt
Python 3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 08:11:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetimeTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined

>>>
^D
```

What I'm observing there is the carriage return on stdin is echoed after the stderr is emitted and even after the new prompt appears on stdout.

The same issue occurs when launching rwt with runpy.

```
~ $ python -m rwt
Python 3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 08:11:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetime
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined
^D
```

So it may be the case that `rwt` is in fact implicated here and that `rwt` should be doing something differently, though as you can see in [the code](https://github.com/jaraco/rwt/blob/ea79922119de579b3767de221770f0bbc1c355f0/rwt/launch.py#L83), the Python process is launched with little customization, and since it works under bash/zsh/powershell, I'm suspicious there's something about xonsh that's violating an expectation.

Interestingly, Powershell seems to have the same issue (when running under xonsh):

```
~ $ pwsh
PowerShell v6.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /Users/jaraco> python
Python 2.7.14 (default, Mar 15 2018, 09:26:06)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetime
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined
```

So the issue isn't specific to Python or rwt. Is there something I should be doing differently to launch these processes?

**Comment by jaraco** [comment]
This is related, maybe even a dupe, with #2561.

**Comment by jaraco** [comment]
Also #2502.

**Comment by jaraco** [comment]
Also #2129.

**Comment by scopatz** [comment]
If @melund's advice works, we should add these to the defaults.

**Comment by jaraco** [comment]
So yes, configuring the threadable_predictors for `rwt` and `pwsh` does address the issue described above, except for the case where `rwt` is launched with `runpy`:

```
~ $ python -m rwt
Python 3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 08:11:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetimeTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined

>>>
```

What's strange - what I don't fully understand yet - is why doesn't the presence of `python` and/or `python3` in the `__xonsh_commands_cache__` not affect that invocation?

It seems the presence of parameters on the command affects the threading treatment.

```
~ $ __xonsh_commands_cache__.threadable_predictors['rwt']
<function xonsh.commands_cache.predict_shell>
~ $ rwt requests
Python 3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 08:11:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetimeTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined
```

But not always :/

```
~ $ python -s
Python 3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 08:11:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> datetime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined
```

In that case, the presence of parameters to python didn't break the commands-cache.

**Comment by ErickTucto** [comment]
Thanks, this issue occurs with GHCI (Haskell)
![ghci-haskell](https://user-images.githubusercontent.com/22831024/63046202-9293a700-be97-11e9-9baa-94e3b7428342.png)


I use on `~/.xonshrc` [(comment of @melund )](https://github.com/xonsh/xonsh/issues/2632#issuecomment-385179771)
```python
from xonsh.commands_cache import predict_shell
__xonsh__.commands_cache.threadable_predictors['ghci'] = predict_shell
```
### Xonfig
![xonfig](https://user-images.githubusercontent.com/22831024/63046196-8f98b680-be97-11e9-8b3b-2038fc64a677.png)
