### ISSUE TITLE
UserWarning: Module xontrib was already imported 

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2633]
I have started to get this warning at startup on the master branch when adding `xontrib load <name>` to my `.xonshrc`. Has anyone else seen this? 

```
snail@sea ~\Documents\xonsh pefnf
$ C:\Users\mel\anaconda3\lib\importlib\__init__.py:126: UserWarning: Module xontrib was already imported from None, but c:\users\mel\documents\xonsh is being added to sys.path
```

**Comment by scopatz** [comment]
hmm i have not seen that. That is weird.  What xontribs do you use and do any of them have an `xontrib\__init__.py` file?

**Comment by scopatz** [comment]
hmmm that is pretty weird.  I wonder what is going on.  I guess we can close this for now then.
