### ISSUE TITLE
xonsh uses pip internal API ... and it's gone now

### ISSUE THREAD

**Issue by Achimh3011** [xonsh/xonsh#2637]
Hi,
with Version 10 pip has removed internal APIs from export (as [previously announced](https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html)).

Starting `xonsh` with a current `pip` (≥10.0) now yields

    pip removed `get_installed_distributions`

Workaround is downgrade to 9.0.3:

    xpip install pip==9.0.3

(but it comes back after each upgrade of course...)

Happens to other packages as well: 
* https://github.com/Miserlou/Zappa/issues/1471 
* https://github.com/pypa/pip/issues/5154

**Comment by Achimh3011** [comment]
Just found out culprit is [xonsh-click-tabcomplete](https://github.com/Granitosaurus/xonsh-click-tabcomplete/blob/master/xontrib/click_tabcomplete.xsh#L2), so closing it here.

**Comment by scopatz** [comment]
Thanks for letting us know @Achimh3011!
