### ISSUE TITLE
is possible to bindkey to jk to exit vi mode ?

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#2645]
I enabled the vi mode with $VI_MODE = True, I want to bind a short key `fd` or `jk` to exit vi insert mode back to normal mode like in zsh 
```
bindkey fd vi-cmd-mode
```

how can do this in xonsh ?

**Comment by gforsyth** [comment]
Hey @eggcaker -- so this is a little bit involved, but if you put this snippet in your `xonshrc` file it will bind `jk` to go to navigation mode when you are in insert mode.  
There's some explanation of how to do this sort of thing in the docs here:
http://xon.sh/tutorial_ptk.html

```
from prompt_toolkit.filters import ViInsertMode
from prompt_toolkit.key_binding.vi_state import InputMode

@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.registry.add_binding

    @handler('j', 'k')
    def exit_insert_mode(event, filter=ViInsertMode):
        vi_state = event.cli.vi_state
        vi_state.reset(InputMode.NAVIGATION)
```

**Comment by gforsyth** [comment]
And if you want to bind to `fd` instead, you can change those keys in the `@handler` line

**Comment by eggcaker** [comment]
@gforsyth thanks, it's works!

**Comment by dysfungi** [comment]
> Hey [@eggcaker](https://github.com/eggcaker) -- so this is a little bit involved, but if you put this snippet in your `xonshrc` file it will bind `jk` to go to navigation mode when you are in insert mode. There's some explanation of how to do this sort of thing in the docs here: http://xon.sh/tutorial_ptk.html
> 
> ```
> from prompt_toolkit.filters import ViInsertMode
> from prompt_toolkit.key_binding.vi_state import InputMode
> 
> @events.on_ptk_create
> def custom_keybindings(bindings, **kw):
>     handler = bindings.registry.add_binding
> 
>     @handler('j', 'k')
>     def exit_insert_mode(event, filter=ViInsertMode):
>         vi_state = event.cli.vi_state
>         vi_state.reset(InputMode.NAVIGATION)
> ```

Had to change this a bit to get working for me:

```python
from prompt_toolkit.filters import vi_insert_mode
from prompt_toolkit.key_binding.vi_state import InputMode

@events.on_ptk_create
def custom_keybindings(bindings, **kwargs):

    @bindings.add("j", "k", filter=vi_insert_mode)
    def exit_insert_mode(event):
        event.cli.vi_state.input_mode = InputMode.NAVIGATION
```
