### ISSUE TITLE
xonsh wizard writes .xonshrc causing error: "xonsh: subprocess mode: command not found: $"

### ISSUE THREAD

**Issue by rhencke** [xonsh/xonsh#2648]
When configuring xonsh's history retention through the Xonsh wizard, if the value `1 GB` is specified, an invalid `.xonshrc` configuration file is written.

Environment:

* xonsh/0.6.4
* macOS 10.13.4 (17E199)
* Python 3.6.5

Steps to reproduce:

1) From a clean environment (no `.xonshrc`, etc), run `xonsh`
2) Run `xonfig wizard`.
3) When prompted: `Would you like to set env vars now, yes or no [default: no]?`, answer `yes`.
4) Accept all defaults, up to, but not including, that for `$XONSH_HISTORY_SIZE`.
5) When prompted for a value for `$XONSH_HISTORY_SIZE`, answer `1 GB`.
A message is printed: `Converted input '1 GB' to (1073741824, 'b').`
6) Accept all remaining defaults.
7) When prompted: `Would you like to write out the current state, yes or no [default: no]?`, answer `yes`.
8) Accept the default location for `.xonshrc`
The following is then written to `.xonshrc`:
```
# XONSH WIZARD START
$ = "(1073741824, 'b')"
$0 = '1073741824'
$1 = 'b'
# XONSH WIZARD END
```
9) Type `exit`.
10) Run `xonsh`.

Expected result:
The xonsh shell starts without error.

Actual result:
The xonsh shell starts, showing the following error:
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: $
Did you mean one of the following?
    w:   Command (/usr/bin/w)
    [:   Command (/bin/[)
    X:   Command (/opt/X11/bin/X)
    cd:  Alias
    fg:  Alias
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: Unexpected token: TokenInfo(type=53 (OP), string='$0', start=(3, 2), end=(3, 4), line="![$0 = '1073741824']\n")
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: Unexpected token: TokenInfo(type=53 (OP), string='$1', start=(4, 2), end=(4, 4), line="![$1 = 'b']\n")
```

**Comment by scopatz** [comment]
Thanks for reporting @rhencke!

**Comment by scopatz** [comment]
Potential fix is available in #2651

**Comment by melund** [comment]
@rhencke The fix is in master now. Please open a new bug report if you find more issues.

**Comment by rhencke** [comment]
@melund Will do - thanks very much for the fix!
