### ISSUE TITLE
Process stops accepting input after resuming from suspend

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#2650]
As reported in #616, I see a similar but also subtly different failure.

On macOS High Sierra with xonsh 0.6.3 (or thereabouts; installed from master a few weeks ago), I seem to be experiencing something similar to #616. Using `git mergetool`, it was prompting to delete a file. I suspended the process with `^Z`, then resumed with `fg`. Afterword, the process was no longer accepting input.

```
rst.linker master $ git mergetool
Merging:
.travis.yml
README.rst
docs/conf.py
tests/requirements.txt

Normal merge conflict for '.travis.yml':
  {local}: modified file
  {remote}: modified file

Normal merge conflict for 'README.rst':
  {local}: modified file
  {remote}: modified file

Normal merge conflict for 'docs/conf.py':
  {local}: modified file
  {remote}: modified file

Deleted merge conflict for 'tests/requirements.txt':
  {local}: modified file
  {remote}: deleted
Use (m)odified or (d)eleted file, or (a)bort? ^Z^Z
rst.linker master $ edit .
rst.linker master $ fg
[1]+ running: git mergetool (94608)
d

d
d
```

Using Ctrl+C, the process terminated and I was able to restart it.

**Comment by scopatz** [comment]
Thanks for opening a new issue, @jaraco!

**Comment by jaraco** [comment]
I don’t, but I’ll see if I can make one.

**Comment by scopatz** [comment]
Thanks at ton! I'd really appreciate.  Otherwise, I'll be on the look out for this happening myself.

**Comment by scopatz** [comment]
Also, I just tried this with `less` and it accepted input when I cam back.  But maybe this is an issue with threadable predictors.  On the command line or in your `~/.xonshrc`, can you try:

```python
__xonsh_commands_cache__.threadable_predictors['git'] = lambda args: args[0] != 'mergetool'
```

And then try using `git mergetool`?

**Comment by jaraco** [comment]
I'm finding that the issue seems to be that the suspend/resume is not just preventing input, but is preventing the command from proceeding after the command's subprocess exits, with or without the threadable_predictors override. Consider:

```
path.py master $ __xonsh_commands_cache__.threadable_predictors['git'] = lambda args: args[0] != 'mergetool'
path.py master $ git pull gh://jaraco/skeleton
From https://github.com/jaraco/skeleton
 * branch            HEAD       -> FETCH_HEAD
Auto-merging setup.py
CONFLICT (content): Merge conflict in setup.py
Auto-merging docs/conf.py
CONFLICT (content): Merge conflict in docs/conf.py
Auto-merging .travis.yml
Automatic merge failed; fix conflicts and then commit the result.
path.py master $ git mergetool
Merging:
docs/conf.py
setup.py

Normal merge conflict for 'docs/conf.py':
  {local}: modified file
  {remote}: modified file
^Z^Z
path.py master $ fg
[1]+ running: git mergetool (45046)
```

At the point where that command terminates, there's a cursor, but the command doesn't respond to Ctrl+C nor to a sigterm from another session, even though the merge tool has exited. The suspend and resume were both enacted while the merge tool was active (prior to exiting the merge tool cleanly). I've found only a SIGKILL on the process will allow it to exit.
