### ISSUE TITLE
http://xonsh.org/tutorial.html displays an empty page

### ISSUE THREAD

**Issue by JulesGM** [xonsh/xonsh#2652]
I'm getting an empty page from http://xonsh.org/tutorial.html . I'm not sure if here is the appropriate place to submit this. I'm on the latest version of Macos, tried with both Safari and Firefox.

**Comment by JulesGM** [comment]
OK the issue appears to be that http://xonsh.org/ is the site of an older version of xonsh. That site should probably be taken down to not confuse people

**Comment by gforsyth** [comment]
Thanks for reporting, @JulesGM and sorry for the confusion.  See #1077 for the long, sad and ongoing story/nightmare of xonsh.org
