### ISSUE TITLE
Something is screwing with `sed` capture groups

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#2653]
I'll try to dig in to the actual cause of this later, but dropping it here as a reminder.

on `xonsh`

```console
 ~ 🐚  echo "1234.567.89" | gsed -r 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1, \2, \3/'
, ,
```

on `bash`

```console
> echo "1234.567.89" | gsed -r 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1, \2, \3/'
1234, 567, 89
```

note that `gsed` is just `gnused` prefixed with a `g` to not collide with stupid osx `sed`

**Comment by scopatz** [comment]
Hi @gforsyth - I think this is an issue with escaping `\1, \2,` etc.  Using a raw string seems to fix it for me:

```console
scopatz@artemis ~ $ echo "1234.567.89" | sed -r 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1, \2, \3/'
, , 
scopatz@artemis ~ $ echo "1234.567.89" | sed -r r's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1, \2, \3/'
1234, 567, 89
```

Though probably using double backslashes will work too:

```console
scopatz@artemis ~ $ echo "1234.567.89" | sed -r 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\\1, \\2, \\3/'
1234, 567, 89
```

**Comment by gforsyth** [comment]
That did the trick.  Thanks @scopatz and @melund!
