### ISSUE TITLE
Save history when the shell is exiting abnormally

### ISSUE THREAD

**Issue by dratini0** [xonsh/xonsh#2657]
When using the JSON backend, the history is not saved unless the shell is exited properly (for example, by ^D). When the `exec` alias is used, or a crash is induced (by for example adding invalid colors into `$BOTTOM_TOOLBAR`), the history file is not saved, and is left locked without commands being written into it.

My suspicion is that this is due to the fact that exit  handlers are not ran when exec is used. This doesn't happen with SQLite for obvious reasons.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @dratini0!  I can confirm this behavior.

**Comment by scopatz** [comment]
> My suspicion is that this is due to the fact that exit handlers are not ran when exec is used.

Really? I thought that atexit was always run...

**Comment by ofek** [comment]
This still is bugged fyi

**Comment by ofek** [comment]
For others wishing to move to SQLite, use this once:

```python
from xonsh.history.json import JsonHistory
from xonsh.history.sqlite import SqliteHistory

class History(SqliteHistory):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.clear()

        jh = JsonHistory(**kwargs)
        for item in jh.all_items():
            self.append(item)
```
