### ISSUE TITLE
>> can't append to new file on Windows

### ISSUE THREAD

**Issue by jeremy886** [xonsh/xonsh#2658]
This is a standard behaviour but it doesn't work for xonsh on Windows:

>> not working if the file is new (not existing)
> working

```
$ pip freeze >> requirements.txt
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
OSError: [WinError 6] The handle is invalid

$ pip freeze > requirements.txt
```

However, when I tried cmd.exe, it worked as expected.

So maybe we can treat it as a bug?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by melund** [comment]
I thinks this is a known bug. Try to see if you can find it by searching the issues and then link to it from here. 

We haven't been able to find the reason for this. But  on my computer I only get the error the first time. Afterwards redirection works as expected. Do you see the same?

**Comment by anki-code** [comment]
Closed because no new info.
