### ISSUE TITLE
hg commit -i fails

### ISSUE THREAD

**Issue by Siecje** [xonsh/xonsh#2659]
`hg commit -i` opens a curses interface and it allows you to select sections of code to include in the commit.

When I run this from `xonsh` and press `f` which is supposed expand a file (it is a tree view), instead an `f` character is displayed on top of the interface.

**Comment by scopatz** [comment]
Thanks for reporting @Siecje! I think I know the fix.

**Comment by Siecje** [comment]
Awesome!

So you are able to reproduce it?

I was going to look into it, so the issue is not very detailed. One thing to mention is that I have set Mercurial to use the curses interface[0].

0: https://bitbucket.org/Siecje/hg_setup/src/fa26c13ca84b1b1e9661f4bcb160f822156c7b35/.hgrc#lines-5

**Comment by scopatz** [comment]
I didn't try to reproduce it :)  But there is a potential fix in #2670 if you want to try it out, that'd be great! It probably always makes sense to turn off threadability when interactive, so I don't think curses is solely at fault here.

**Comment by Siecje** [comment]
That PR fixes the issue! Thanks for your quick response!
