### ISSUE TITLE
Setting up XONSH_DEBUG when it's used as a login shell

### ISSUE THREAD

**Issue by ghost** [xonsh/xonsh#2661]
I use `xonsh` as a login shell. Where do I have to set the `XONSH_DEBUG` environment variable? It isn't obvious since xonsh doesn't have multiple startup files.

One option might be to set it in `.xonshrc`, since it will be sourced for login shells and all other programs will inherit from it. But I find myself having to use bare tty's from time to time, when X server breaks.

**Comment by scopatz** [comment]
Yeah, this is a great question @gsaga. Normally, what I do in this situation is to change whatever is launching xonsh to use `env XONSH_DEBUG=1 xonsh` instead of just `xonsh`

**Comment by anki-code** [comment]
This works for me:
```python
vim $(which xonsh)
```
Add before any other imports:
```python
import os
os.environ['XONSH_DEBUG'] = '1'
os.environ['XONSH_SHOW_TRACEBACK'] = '1'
```
