### ISSUE TITLE
Activating envs through virtualenv and pipenv

### ISSUE THREAD

**Issue by deeuu** [xonsh/xonsh#2663]
Hey,

Firstly, thanks for this awesome shell!

Over time there have been a number of issues raised, e.g. #16, #108, #379, #498, and #2397, about [virtualenv](https://github.com/pypa/virtualenv) and [pipenv](https://github.com/pypa/pipenv) support, resulting in a number of `xonsh`-side hacks, such as to use `source-bash` or write wrappers around `vox activate`.

As I understand it, the main issue is activating environments created by `virtualenv` because [there is no `activate` script for xonsh](https://github.com/pypa/virtualenv/tree/master/virtualenv_embedded). So would it make sense for me to attempt a `xonsh` script (that makes use of `vox`) and file a pull-request to [virtualenv](https://github.com/pypa/virtualenv)?

Then again, I don't fully grasp [this reply](https://github.com/pypa/pipenv/issues/498) from @astronouth7303 , which suggests this is more involved

> From a loose scan of the features and such, it looks like the only problem is pipenv shell, because xonsh is also python, so trying to call xonsh with a venv set is potentially problematic and unfortunately would need to be fixed on our end by redoing how we're packaged and called. (Potentially related to xonsh/xonsh#1861?) Otherwise, because there's no shell sourcing and nothing that needs to be added to rc files, I'm guessing pipenv doesn't do emit any bourne, and otherwise should work fine.

but I guess my typical use case is to call `virtualenv` and `pipenv` from within `xonsh`.

Any thoughts on this?

Thanks again.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by rca** [comment]
I ran into this myself just yesterday, and it would be great to be able to use plain vanilla `pipenv shell`.  To get up and running, as you suggested, I resorted to making my own `pipenv-shell` alias around vox.  So far, so good, but it's not ideal.  In case anyone's interested, Yet Another Pipenv Hack:

```
def _pipenv_shell():
    venv_path = $(pipenv --venv).strip()
    venv_root, venv_name = os.path.split(venv_path)

    with ${...}.swap(VIRTUALENV_HOME=venv_root):
        vox activate @(venv_name)

aliases['pipenv-exit'] = 'vox deactivate'
aliases['pipenv-shell'] = _pipenv_shell
```

**Comment by scopatz** [comment]
Thank for reporting @deeuu and commenting @rca!  We'd be happy to take and review any PRs on this that improve vox, including adding these aliases or more.  I personally don't use vitrualenvs, but I would like it if xonsh could support you as much as possible.

If you have any questions about how to open or write a PR, please let me know. We also have a developer's guide here: http://xon.sh/devguide.html

**Comment by deeuu** [comment]
@scopatz Thanks for getting back.

I'm thinking that this shouldn't be a `xonsh` or `vox` fix, but rather that `virtualenv` should support `xonsh` by means of an activation script (if that's all that is required). 

I know I could be asking over there, but I'd like input from you guys!

The alternative, as you suggest, is to just provide `virtualenv` and `pipenv` wrappers as part of `vox`, but seems like more maintenance?

Thoughts?

**Comment by scopatz** [comment]
> virtualenv should support xonsh by means of an activation script

Yes, they should and that is the proper fix. Unfortunately, the way they wrote their Bash activation script, it only works in the same Bash session.  So in xonsh, `source-bash activate` doesn't even work.

> The alternative, as you suggest, is to just provide virtualenv and pipenv wrappers as part of vox, but seems like more maintenance?

Exactly! This has seemed to be the easier path for us so far, but I would love it if users and devs could rally to get better virtualenv support.  On a related note, we need to do the same thing for conda too.

**Comment by rca** [comment]
Don't use virtualenvs?  They'll change your life!  ;)  Seriously, though, if you juggle multiple projects with differing dependencies on a single machine, it makes a world of difference.

I _think_ this issue is a non-issue.  I perused and found [an issue](https://github.com/fish-shell/fish-shell/issues/989) and [some `--fancy` docs](https://docs.pipenv.org/#cmdoption-pipenv-shell-fancy) describing how fancy shells (here's looking at you, xonsh 🥇) work.  The rundown is below:

# Setup xonsh as a system shell

First, your system has to officially accept xonsh as a system shell.  This means adding its path to `/etc/shells` (I'm intentionally disarming the sudo call for copy/pasters):

```
echo "$(which xonsh)" #| sudo tee -a /etc/shells
```

# Change your default shell:

Next, make your account's default shell `xonsh`:

```
chsh -s $(which xonsh) $USER
```

# Finally, be `--fancy`

By default Pipenv will use `activate`.  When `--fancy` is used it does more proper modern shell stuff.

```
pipenv shell --fancy
```

Works! 🍾

**Comment by deeuu** [comment]
Well I missed that one!

A few things, however:

(a) `pipenv shell --fancy` from inside xonsh (yes my default shell, of course ;-), yields
```
ERROR: The virtualenv hasn't been activated correctly.
Either the env is corrupted (try running `pew restore env`),
Or an upgrade of your Python version broke your env,
Or check the contents of your $PATH. You might be adding new directories to it
from inside your shell's configuration file.
In this case, for further details please see: https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
```
(this comes from [pew](https://github.com/berdario/pew), which `pipenv` uses for the fancy shell).

which I believe is due to `$PATH` being set in my `.xonshrc`, [e.g.](https://github.com/pypa/pipenv/blob/ea13302671fa82ceebbdb2486293da14ec03b17c/docs/basics.rst#-about-shell-configuration):

> A proper shell configuration only sets environment variables like PATH during a login session, not during every subshell spawn (as they are typically configured to do)

@scopatz `xonsh` doesn't have a `.bash_profile` equivalent does it? Or a `status --is-login` as in `fish`?

Otherwise I'll have to play with the ordering of my `$PATH`.

(b) @scopatz yeah I was using the `xonda` xontrib. In terms of next moves, if I got a `xonsh` activation script working for `virtualenv` would there be any use for `vox`? Trying to understand if there was a good reason for not doing this prior to development of `vox`.

**Comment by rca** [comment]
Running `${...}` I found `$XONSH_LOGIN` and `$XONSH_INTERACTIVE`, which might be what you're looking for.

As for the pew error, I wouldn't know how to begin diagnosing aside from trying with an empty `~/.xonshrc` and slowly add things back in until it breaks.  Your comment about `$PATH` being set in your rc file made me check mine and, indeed, it needed a little tweaking.  I was double-prepending some paths when dropping into the Pipenv shell.  I ended up updating my $PATH setting to look something like this:

```
```

**Comment by deeuu** [comment]
Okay the problem was that I had xonsh installed as a pyenv shim, so I believe that pyenv was updating `$PATH` post pew activation (so inserting on top of the path to the venv). I've now installed xonsh inside an isolated environment and it works!

So, in short:

1. [pew](https://github.com/berdario/pew) works with xonsh.
2. [pyenv](https://github.com/pyenv/pyenv) can be used for installing different versions of Python, which can then be passed to penv, e.g. `penv new my_env_name --python /path/to/python/version`. Or one can use [pythonz](https://github.com/saghul/pythonz) on unix, which integrates with pew.
3. Add `$PIPENV_SHELL_FANCY=1` to your `.xonshrc` and `pipenv shell` works gracefully with `xonsh`.

@scopatz Perhaps a small setup kind could be added to [the documentation](http://xon.sh/python_virtual_environments.html), which currently states that pew does not play well with xonsh (unless I'm missing something)?

**Comment by scopatz** [comment]
> @scopatz xonsh doesn't have a .bash_profile equivalent does it? Or a status --is-login as in fish?

We have a slightly simpler (and thus better :man_shrugging:) model. [`$XONSHRC`](http://xon.sh/envvars.html#xonshrc) and the `--rc` command line option are lists of run control files. Something like `.bash_profile` could be replicated with this. Alternatively, you could use [`$XONSH_INTERACTIVE`](http://xon.sh/envvars.html#xonsh-interactive) to switch between behavior in a default xonshrc file, as @rca pointed out :)

> (b) @scopatz yeah I was using the xonda xontrib. In terms of next moves, if I got a xonsh activation script working for virtualenv would there be any use for vox? Trying to understand if there was a good reason for not doing this prior to development of vox.

No necissarily. Maybe there is some tab completion stuff in there? But that could also be in the activate script.

> @scopatz Perhaps a small setup kind could be added to the documentation, which currently states that pew does not play well with xonsh (unless I'm missing something)?

That would be great!  Pull requests very welcome on this front! It would also be great if there was a pew xontrib or similar that would add this support automatically

**Comment by rca** [comment]
Until recently, xonsh + pipenv have been working wonderfully by either running `pipenv shell --fancy` or setting `$PIPENV_SHELL_FANCY = '1'` in the environment and simply running `pipenv shell`.

After setting up a new machine [I ran into issues](https://github.com/pypa/pipenv/issues/498#issuecomment-417326930), which turn out being due to the latest pipenv release.  Using `pipenv==2018.6.25` solves the problem.

**Comment by deeuu** [comment]
@rca Did you track down the cause of these issues? I am also having issues with interactive programs inside the venv spawned by `pipenv shell --fancy`.

**Comment by rca** [comment]
Unfortunately, no. Went back to my trusty ‘ol bash.

**Comment by deeuu** [comment]
@scopatz @rca I've put together a [`xontrib`](https://github.com/deeuu/xonsh-pipenv) for auto activating a `pipenv` virtual environment on `cd`.

Try it out!

**Comment by astronouth7303** [comment]
@deeuu I would encourage you to look at `voxapi` and use that for the actual activate/deactivate mechanics. (You're not doing the full process.)

You may want to look at my [avox xontrib](https://github.com/astronouth7303/xontrib-avox) for some prior art. (I notice you don't handle automatic deactivation when you cd out of a project, and I think it'll also fail if you cd past a `Pipfile`.)

**Comment by astronouth7303** [comment]
Oh, and sorry for the late reply. The tl;dr on my comment in the pipenv repo is that afaik, xonsh doesn't like to be started with a venv already activated. This is not an unfixable problem, but it does require some changes with how xonsh is packaged and distributed.

**Comment by deeuu** [comment]
@astronouth7303 Thanks for the feedback

> You're not doing the full process.

Can you expand on this?

> I notice you don't handle automatic deactivation when you cd out of a project

This should be easy enough to incorporate, cheers!

>  I think it'll also fail if you cd past a `Pipfile`

True: it will won't activate. The activiation is based on the presence of the `Pipfile` in the working directory. I'd rather not have to search for the `Pipfile`, or introduce some new workflow in order to handle the name of the venv assigned by `pipenv` (which involves a hash of the `Pipfile`'s location). Did you have something else in mind?

Thanks

**Comment by astronouth7303** [comment]
The full activation is https://github.com/xonsh/xonsh/blob/5d87fc76eff525a91b8994b1c7439f4ab60bc22c/xontrib/voxapi.py#L339-L350

The way avox handles it is that it resolves both the old and new directory into their matching venvs (or None), and if the old and new don't match, it performs actions. The resolution process involves starting at the cwd and climbing up.

**Comment by deeuu** [comment]
I've got the activation working from a sub-dir of a `pipenv` project, as well as auto-deactivation when leaving one.

Still not using the `voxapi` but feel free to raise an issue (or let me know here) if you think I'm missing something.

**Comment by scopatz** [comment]
Note that the next version of virtualenv will include xonsh support!

**Comment by deeuu** [comment]
Exciting!

**Comment by ubrg** [comment]
Hi,

Firstly, thanks for that very useful tool !
I discovered it a few days ago and I cannot stop using it anymore :)

I found that issue looking for a way to fix some errors with `virtualenv`. 
As @scopatz noticed, the `virtualenv` last version (16.6.0) includes xonsh support by providing `activate.xsh` file which can be run using `source activate.xsh`.

I didn't noticed any error to create, activate or deactivate a virtual environnement with that new version (whereas I got some errors using a previous version of `virtualenv` and running `source-bash activate`).

I don't know exactly what `pipenv`is about but it looks like a kind of wrapper around `pip` and `virtualenv`. A xonsh support from `virtualenv` probably means a future xonsh support from `pipenv` (if it is not already supported).

**Comment by scopatz** [comment]
That's awesome! I hadn't realized they had done a release with support yet!  If someone can verify that pipenv works, we can close this issue!

**Comment by jnoortheen** [comment]
They have removed the active.xsh due to some maintenance issue. I think it is fair to use xontribs to activate virtualenvs like I 've done [here for poetry](https://github.com/jnoortheen/xontrib-avox-poetry) . Also there is a PR in work here for virtualenv plugin support - https://github.com/xonsh/xonsh/pull/4466

**Comment by gforsyth** [comment]
I'm going to close this out since `virtualenv` removed their activator.  Our solution is to use `xontribs` to handle this.
