### ISSUE TITLE
A bug in test/test_news.py

### ISSUE THREAD

**Issue by gsaga** [xonsh/xonsh#2667]
The `test_news.py` script fails with an `index out of bounds error` for this job:
https://travis-ci.org/xonsh/xonsh/jobs/388607928

That's likely a bug in the test script. A file parsing script shouldn't fail with this error. This is the rst file for which it failed:

    **Fixed:**
    
    * issue 2313
    
    **Changed:**
    
    * built_ins.py, corrected a typo. 
    
    **Added:** None
    
    **Deprecated:** None
    
    **Removed:** None
    
    **Security:** None
    

It failed on the second last line. There should be a check before line 40 in `test_news.py` to check if the current entry is the last entry.

One way I could think of is to convert the file to a string based on the number of stars with which it's lines start, so the above file will become "2010201020202020", and then do a regex search on this string.

**Comment by scopatz** [comment]
Thanks for reporting!
