### ISSUE TITLE
weird failure?

### ISSUE THREAD

**Issue by SolarAquarion** [xonsh/xonsh#2672]
```
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/completer.py", line 82, in get_completions
    yield Completion(comp, -l, display=disp)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/completion.py", line 40, in __init__
    assert self.start_position <= 0
AssertionError
```

**Comment by gforsyth** [comment]
Thanks for reporting @SolarAquarion!  It looks like this might have come up when you tried to tab-complete something?  Do you have any more context for the error?  And can you post the output of `xonfig`, please?  Thanks!

**Comment by SolarAquarion** [comment]
yes, it was when i tried to do ya

**Comment by scopatz** [comment]
Hi @SolarAquarion - where does the yay command come from?

**Comment by SolarAquarion** [comment]
Zsh and bash, but it happens in more commands then that

**Comment by scopatz** [comment]
Sorry, I meant what package is it from?

**Comment by gsaga** [comment]
@scopatz It's an AUR package:
https://aur.archlinux.org/packages/yay/

**Comment by scopatz** [comment]
Hmm are there any other commands that this is failing for?

**Comment by SolarAquarion** [comment]
Plenty, it appears randomly

**Comment by scopatz** [comment]
Hmm Can you please post the next example that comes up? Preferably something that is not arch-specific :wink: Thanks!

**Comment by SolarAquarion** [comment]
This time it failed on "cp"

**Comment by scopatz** [comment]
Can you post the traceback too, please?

**Comment by scopatz** [comment]
And what is the output of the `xonfig` command?

**Comment by SolarAquarion** [comment]
Traceback (most recent call last):                                                                                                  
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                    
    self.run()                                                                                                             
  File "/usr/lib/python3.6/threading.py", line 864, in run                                                                 
    self._target(*self._args, **self._kwargs)                                                                              
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run                                             
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/completer.py", line 82, in get_completions
    yield Completion(comp, -l, display=disp)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/completion.py", line 40, in __init__
    assert self.start_position <= 0
AssertionError

+------------------+---------------------+
| xonsh            | 0.6.5.dev25         |
| Git SHA          | 18477ce9            |
| Commit Date      | Jun 6 11:39:54 2018 |
| Python           | 3.6.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 1.0.15              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | arch                |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+

**Comment by SolarAquarion** [comment]
Nope

**Comment by SolarAquarion** [comment]
it does not happen

**Comment by gforsyth** [comment]
I can replicate this failure using `cat` if there are any files or folders with spaces in their names.
I thought it was another `path` completer issue but it looks like it's actually the `complete_from_bash` function returning an invalid value for `lprefix`:
```
gil@bad_cat ~/tmp/foo 🐚  ls
 afile  'a file with spaces
```

```
gil@bad_cat ~/tmp/foo 🐚  for func in __xonsh_completers__.values():
.........................     print(func.__name__)
.........................     func('', 'cat ', 3, 3, None)
.........................     
_xonda_completer
complete_python_mode
set()
complete_base
set()
complete_completer
complete_skipper
set()
complete_pip
complete_pip
complete_cd
set()
complete_rmdir
set()
complete_xonfig
complete_xontrib
complete_from_bash
({"'a file with spaces'", "'afile'"}, -1)
```

that `-1` as the length of the `prefix` is hitting the assertion check in `prompt_toolkit`

**Comment by gforsyth** [comment]
Hey @SolarAquarion -- this has been fixed on master.  Please re-open if the issue persists for you.  Thanks!
