### ISSUE TITLE
Sandbox execution

### ISSUE THREAD

**Issue by CJ-Wright** [xonsh/xonsh#2674]
It would be nice if we could sandbox the environment for execution.

My main motivation for this is allowing the sourcing of xonsh files and have that source only last for a little while.

**Comment by scopatz** [comment]
Thanks for requesting the feature @CJ-Wright! Pull requests welcome

**Comment by anki-code** [comment]
I'm going to close this because the best environment to test scripts is [docker](https://www.docker.com/). Just put your code into xonsh docker image and run tests in isolated environment:
```python
docker run -it --rm xonsh/xonsh:slim xonsh -c @("""
  pip install -U -q pip lolcat
  echo "We are in docker container now!" | lolcat
  """)
```

Or use any python image:
```python
docker run --rm -it python:3.9-slim /bin/bash -c @("""
  pip install 'xonsh[full]'
  pip list
  xonsh
  """)

```
