### ISSUE TITLE
Paths relative to `CDPATH` are completed even for commands that aren't `cd`, and are buggy

### ISSUE THREAD

**Issue by dratini0** [xonsh/xonsh#2677]
Steps to reproduce:
1. Navigate to an empty directory
2. Set your `CDPATH` to include your home directory
3. Type `cat `
4. Start typing the name of some directory in your home, then press  tab
5. It will be completed, and a space will be inserted after instead of the usual slash
6. Delete the space, add a slash and start typing the name of a file or a directory in said directory, then press tab again
7. The whole thing will be replaced with the name of the file/subdirectory, once again, with a space after.

This is probably two bugs, but I can't reproduce one without the other.

Xonfig:
```
+------------------+---------------------+
| xonsh            | 0.6.6.dev1          |
| Git SHA          | 4c78866e            |
| Commit Date      | Jun 6 18:21:58 2018 |
| Python           | 3.6.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 1.0.15              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by scopatz** [comment]
Hi @dratini0 - thanks for reporting! This is really weird.  I have basically the exact same xonfig as you do and I cannot reproduce this at all.  Cat does not fill in anything when I hit tab.  What does the `xontrib list` command return?

**Comment by scopatz** [comment]
Also, what is in your xonshrc?
