### ISSUE TITLE
How to use any version of python with vox?

### ISSUE THREAD

**Issue by worldmind** [xonsh/xonsh#2684]
Hello, I start to use vox and have question - how to use a any version of python in vox env? For example from [pyenv](https://github.com/pyenv/pyenv).
In my opinion it must looks like:
`vox new 3.6.5 myenv`
like [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) do it.
What the best and simple way make this?

**Comment by scopatz** [comment]
Hi @worldmind - are you running into problems with this? Can you post the error if you are? Thanks!

**Comment by astronouth7303** [comment]
#692

**Comment by worldmind** [comment]
ok, close as duplicate
