### ISSUE TITLE
Autocomplete suggestion seems to be on even if set to off

### ISSUE THREAD

**Issue by battaglia01** [xonsh/xonsh#2708]
I've set `$AUTO_SUGGEST_IN_COMPLETIONS=False`, but it still seems to be auto suggesting previous stuff I've entered. I have the path completer ahead of the bash completer. How does this work?

**Comment by gforsyth** [comment]
Hey @battaglia01 -- there are two separate completion features.  One is the tab completion list that pops up when you hit tab.  The other is auto suggest, which shows ghosted text that matches previous commands.  Tab completion is reasonably "smart" about what it shows you, while the auto suggest doesn't pay attention to context, it just shows things that match your history.

`$AUTO_SUGGEST_IN_COMPLETIONS`, if `True`, adds that greyed out text to the tab completion list.  If you want to disable the greyed out text entirely, then set `$AUTO_SUGGEST=False`

**Comment by battaglia01** [comment]
Oh, thank you! Had the wrong setting then.

**Comment by gforsyth** [comment]
Happy to help!  Please re-open if you have any more issues around auto suggest!
