### ISSUE TITLE
Unable to create alias for interactive command with subprocesses

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#2710]
In [this conversation](https://gitter.im/xonsh/xonsh?at=5b0c20cc3759c406277a1e2d), I describe a command for which I'd like to create an alias, but because the command is itself an interactive process, the recommended technique for creating the alias causes the subprocess to block until the process exits, so interactivity is not possible.

Consider this simple alias:

```
~ $ def mongo2():
...     return $(mongo)
...
~ $ aliases['mongo2'] = mongo2
~ $ del mongo2
```

Invoking `mongo2` causes the output to be blocked until the process completes, although it is possible to send stdin to the process.

```
~ $ mongo2
MongoDB shell version v4.0.0
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 4.0.0
Server has startup warnings:
...
> show dbs
admin                 0.000GB
...
test                  0.000GB
> ^C
bye
```

It seems that either the alias machinery or the `$()` machinery is requiring the full output of the process before any is rendered.

**Comment by jaraco** [comment]
I noticed [the docs on uncapturable](http://xon.sh/tutorial.html#uncapturable-aliases), but that didn't seem to help:

```
~ $ from xonsh.tools import unthreadable, uncapturable
~ $ aliases['mongo2'] = unthreadable(uncapturable(aliases['mongo2']))
```

(mongo2 still buffers all output)

**Comment by anki-code** [comment]
I think this is the misunderstanding from the Gitter chat. The original question of this issue from Gitter was:

> Is it possible to turn this command into an alias? mongo mongodb.jaraco.com/admin -u jaraco -p @($(keyring get mongodb.jaraco.com/admin jaraco).strip())

And the answer is yes but you shouldn't pass the command to the captured ouput `$()`. Just run the command uncaptured:

Example for mc:
```python
def _mc():
    mc
    
aliases['mc2'] = _mc
mc2
# normal running the mc
```
or use [ExecAlias](https://xon.sh/tutorial.html#aliases):
```python
aliases['mc2'] = "mc @('/tmp')"
```

Example for the simple interactive app:
```python
echo @("""
while 1:
     try:
         text = input('> ')
     except:
         exit()
     print(text)
""") > /tmp/inter

def _inter():
    xonsh /tmp/inter
    
aliases['inter'] = _inter
inter
# > 123
# 123
```

**Comment by jaraco** [comment]
Thanks for the tip. Yes, I think you're right. I don't know what made me think I needed to capture the output.
