### ISSUE TITLE
Issues with the Jupyter kernel

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#2712]
The Jupyter kernel seems nice, but it doesn't seem to work too well in a notebook:

- Output isn't printed until the command exits
- Commands like a git clone that clear the line aren't cleared (compare this to the standard IPython `!git clone`)
- It doesn't know that the output isn't a tty. So something like `git log` will not work, and it messes up the terminal that the notebook is running from

**Comment by scopatz** [comment]
Ok, so I think the issue might be that we are subclassing from `ipykernel`, which is leading to all sorts of wrong assumptions about the code being valid Python. We probably shouldn't be doing that anymore, but maybe @Carreau can weight in with his thoughts

**Comment by scopatz** [comment]
> It doesn't know that the output isn't a tty. So something like git log will not work, and it messes up the terminal that the notebook is running from

This actually isn't possible, given my reading of [the docs](http://jupyter-client.readthedocs.io/en/stable/messaging.html#messages-on-the-stdin-router-dealer-channel). Even the Bash kernel messes up in such cases. CC @takluyver

**Comment by Carreau** [comment]
Yep that seem right, we'll need the kernel nanny stuff to be able to correctly handle this kind of stuff. 
I'm guessing that might be also a challenge for @SylvainCorlay to start xonsh from the Python C Api using Xeus ?

**Comment by asmeurer** [comment]
If you run `!git log` in the regular Python kernel it does the right thing (also don't run that from a large git repo or will do bad things to your browser).

**Comment by SylvainCorlay** [comment]
> Yep that seem right, we'll need the kernel nanny stuff to be able to correctly handle this kind of stuff.
I'm guessing that might be also a challenge for @SylvainCorlay to start xonsh from the Python C Api using Xeus ?

Just from the name of the project Xonsh seems like a really good fit for Xeus :)

**Comment by scopatz** [comment]
@Carreau - yeah, a kernel nanny or some lower level systems programming that allows us to redirect pipes would be great for this purpose.

@asmeurer - yes, things like `!git log` seem to work (though I am not sure how).  While in the normal Python kernel, things like `!less file` still break in weird ways because stdin isn't available.

@SylvainCorlay - haha yeah! Excellent fit indeed ;)

**Comment by scopatz** [comment]
Also, note that the Bash kernel fails to display `less file` in a totally different way than the xonsh or Python kernels. So there are at least three failure modes for the same behavior :sweat_smile:

**Comment by asmeurer** [comment]
I think IPython must be faking a tty (using pexpect?). When I run `!tty` it gives me a tty number that is different from the terminal that the kernel is run in.

**Comment by takluyver** [comment]
I think we set `PAGER=cat` in some places - that will make things like `git log` and `man` do the right thing (for a given value of 'right' - as @asmeurer noticed, `git log` in a big repo will give you problems). Of course explicitly invoking `less` still tries to page. You could try making less an alias which just passes data through,  but it's probably more trouble than it's worth.

> I think IPython must be faking a tty (using pexpect?). When I run !tty it gives me a tty number that is different from the terminal that the kernel is run in.

Yes, `!` commands in the kernel are run through pexpect. Terminal IPython doesn't do that, however.

**Comment by scopatz** [comment]
I have fixed the PAGER issues, such as with `git log` and `less`, in #2761
