### ISSUE TITLE
xonsh cannot running on python 3.7

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#2717]
after I upgraded all xonsh and python  to latest version with brew, when i running `xonsh --version` i got error : 
```
om xonsh.main import main
  File "/usr/local/lib/python3.6/site-packages/xonsh/__init__.py", line 12, in <module>
    from xonsh import __amalgam__
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2628, in <module>
    ASYNC = token.ASYNC
AttributeError: module 'token' has no attribute 'ASYNC'
```

I thinks this bug should fixed in this release with 4e212cab78084acac9e78f20f61864802e86efe2

**Comment by scopatz** [comment]
Thanks for reporting! Can you please post the output of the xonfig command?

**Comment by scopatz** [comment]
Actually, I think this has been fixed in 0.7.0

**Comment by scopatz** [comment]
Please let us know one way or the other

**Comment by eggcaker** [comment]
~ $ xonfig
+------------------+-----------------+
| xonsh            | 0.6.10          |
| Python           | 3.7.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit  |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

**Comment by eggcaker** [comment]
after installed the 0.7.0  with pip3  and modified the xonsh first line from 
```
#!/usr/local/opt/python/bin/python3.6
```
to 
```
#!/usr/local/opt/python/bin/python3.6
```

it's working now any way,  not sure it's some thing wrong on my side.   Thanks.
Still need doing some module  migration from 3.6 to 3.7

**Comment by scopatz** [comment]
Thanks for testing it out @eggcaker! Let us know if there is anything else.
