### ISSUE TITLE
xonsh version 0.7.0 does not start with prompt_toolkit >= 2.0 when no pygments is installed

### ISSUE THREAD

**Issue by Achimh3011** [xonsh/xonsh#2734]
xonsh 0.7.0 was installed though `brew upgrade`. Release notes for 0.7.0 state that prompt_toolkit>=2.0 is supported.  However, xonsh does not start with `prompt_toolkit==2.0.3` (falling back to bash).  With `prompt_toolkit==1.0.15` xonsh starts , but also shows an error message (due to API changes).

## xonfig
$ xonfig

_As xonsh doesn't start with prompt_toolkit installed, this xonfig output was generated without it. xonsh complains about prompt_toolkit missing, but at least it starts._

````
+------------------+-----------------+
| xonsh            | 0.7.0           |
| Python           | 3.7.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
````

## Expected Behavior
xonsh should start up (and work) without error message.

## Current Behavior

`$` means running xonsh, `>` means bash prompt.

From a xonsh installation w/o prompt_toolkit:

````
$ xpip install 'prompt_toolkit==2.0.3'
Collecting prompt_toolkit==2.0.3
  Using cached https://files.pythonhosted.org/packages/bb/c5/e5c7098fa2441d669bba512c4b7a6291333db4af218e4365e73b7919c9ee/prompt_toolkit-2.0.3-py3-none-any.whl
Requirement already satisfied: wcwidth in /usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages (from prompt_toolkit==2.0.3) (0.1.7)
Requirement already satisfied: six>=1.9.0 in /usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages (from prompt_toolkit==2.0.3) (1.11.0)
Installing collected packages: prompt-toolkit
Successfully installed prompt-toolkit-2.0.3
$ ^D
> env XONSH_DEBUG=1 xonsh
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages/xonsh/main.py", line 342, in main
    return main_xonsh(args)
  File "/usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages/xonsh/main.py", line 368, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 160, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 120, in singleline
    for key, value in DEFAULT_STYLE_DICT
  File "/usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 120, in <dictcomp>
    for key, value in DEFAULT_STYLE_DICT
ValueError: not enough values to unpack (expected 2, got 0)
Xonsh encountered an issue during launch
Failback to /bin/bash
>
````

With `prompt_toolkit==1.0.15` xonsh starts with errors, but at least does not fall back to bash.

````
$ xpip install 'prompt_toolkit==1.0.15'
Collecting prompt_toolkit==1.0.15
  Using cached https://files.pythonhosted.org/packages/04/d1/c6616dd03701e7e2073f06d5c3b41b012256e42b72561f16a7bd86dd7b43/prompt_toolkit-1.0.15-py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages (from prompt_toolkit==1.0.15) (1.11.0)
Requirement already satisfied: wcwidth in /usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages (from prompt_toolkit==1.0.15) (0.1.7)
Installing collected packages: prompt-toolkit
Successfully installed prompt-toolkit-1.0.15
$ ^D
> env XONSH_DEBUG=1 xonsh
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages/xonsh/events.py", line 217, in _call
    handler(**self._kwargs)
  File "/usr/local/Cellar/xonsh/0.7.0/libexec/lib/python3.7/site-packages/xontrib/whole_word_jumping.py", line 18, in custom_keybindings
    handler = bindings.add
AttributeError: 'KeyBindingManager' object has no attribute 'add'
Exception raised in event handler; ignored.
$
````

## Steps to Reproduce

2.0.3:

    > brew install xonsh
    > xonsh
    > xpip install prompt_toolkit
    > exit
    > xonsh

1.0.15:

    > brew install xonsh
    > xonsh
    > xpip install 'prompt_toolkit<2'
    > exit
    > xonsh

**Comment by melund** [comment]
Can you try to install pygments as well. It should work without now but there may be a bug ...

**Comment by Achimh3011** [comment]
Cheers!  That solved the issue:

````
> /usr/local/Cellar/xonsh/0.7.0/libexec/bin/pip3 install pygments
Collecting pygments
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Installing collected packages: pygments
Successfully installed pygments-2.2.0
> env XONSH_DEBUG=1 xonsh
$
````

I'd still consider it a bug that you need to apply these non-obvious steps, though.

**Comment by melund** [comment]
Thanks for  checking.  Both the ability  to run without  pygment and support  for ptk2 are new features. There seem to be a bug between the two.

**Comment by melund** [comment]
Could you change  the title of the issue so it summarizes what the problem is?

**Comment by Achimh3011** [comment]
Title ok?

**Comment by gforsyth** [comment]
Looks good, @Achimh3011, thanks!

**Comment by scopatz** [comment]
Should the brew package depend on pygments?  It would also be nice to fully separate pygments from ptk2, but I am not sure what we loose in that process.

**Comment by scopatz** [comment]
This seems to be the brew recipe: https://github.com/Homebrew/homebrew-core/blob/master/Formula/xonsh.rb

**Comment by gforsyth** [comment]
We lose syntax highlighting, for sure.  This error, though, looks like an oversight by me because this https://github.com/xonsh/xonsh/blob/master/xonsh/ptk2/shell.py#L113-L122 is a little silly.

**Comment by gforsyth** [comment]
Ahh, figured it out.  Fix incoming.  It was a silly thing.

**Comment by gforsyth** [comment]
Also, the `whole_word_jumping` xontrib error is a separate thing that I can address in a different PR

**Comment by melund** [comment]
This should hopefully fix issues @Achimh3011. But the homebrew recipe probably  should be changed so users get the full experience. I guess none of the core contributors are mac users. So is that something  you could assist  with @Achimh3011 ?

**Comment by Achimh3011** [comment]
Yes, I can give you feedback.

**Comment by Achimh3011** [comment]
Installation with `brew install --HEAD xonsh` (and subsequent `xpip install prompt_toolkit` from within xonsh) works fine. I think, the bug can be closed.

Thanks a lot for your fast reaction and remedy!

I'll look into adding prompt_toolkit as a dependency in homebrew.

**Comment by melund** [comment]
Thanks @Achimh3011. A new release will probably come within a few days.  

I don't know how the brew files work but don't think 'six' is a direct dependency  of xonsh.

Here is a list of dependencies which gives the best user experience:

    - ply
    - prompt_toolkit
    - pygments
    - setproctitle

If you would be willing to add a PR  to the homebrew-core when a new release comes out that would be awesome.

**Comment by scopatz** [comment]
Thanks @Achimh3011!

**Comment by Achimh3011** [comment]
_sorry to still post to this offically dead thread (point me to a better place if you like...)_

FB for the PR was that this list of recommended packages to install should be documented somewhere in xonsh documentation. I think that is fair to ask for. What would be a good place? Is somewhere near https://github.com/xonsh/xonsh/blame/master/docs/osx.rst#L46 appropriate?
