### ISSUE TITLE
Create PPA for Xonsh/Add to Apt

### ISSUE THREAD

**Issue by hjc1710** [xonsh/xonsh#274]
It would be really great if I could install `xonsh` through apt. If I have to add a PPA, that's totally fine. If it just appears in Debian testing, that's even better :smile:.

Right now, looks like `xonsh` is only available in these package managers:

1. pip
2. conda
3. homebrew
4. pacman

Source for the above: https://twitter.com/scopatz/status/613383868851183616

**Comment by scopatz** [comment]
Thanks for opening this @hjc1710

**Comment by adqm** [comment]
I am happy to take this one unless someone else has a burning desire.  I've been meaning to learn about Debian packaging for a while, and this might be a good chance.

**Comment by scopatz** [comment]
Knock yourself out :) It would be most appreciated!

**Comment by hjc1710** [comment]
Yea, I've also been meaning to learn about Debian packaging for a while, but god knows when I'll get a chance to actually **do it**, so taking this would be awesome!

**Comment by adqm** [comment]
I know this was a long time ago, but I think it's actually in the process of happening now on Debian (see [this thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825112)), no thanks to me :)
