### ISSUE TITLE
history replay not working? 

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#2744]
What I want to do is to load bunch of  commands to build a working envirement ex: requre joson lib, load json data parse sub data set.

I try  the replay command but when run 
```
history replay -o ~/new.json ~/.local/share/xonsh-history.sqlite 
``` 
show error : 
```
history: error: cannot convert 'replay' to slice
```

two questions: 
1. did I use the replay command correct ? 
2. is the replay best way to me 

## xonfig
```
+------------------+----------------------+
| xonsh            | 0.7.1                |
| Git SHA          | dd42b8e1             |
| Commit Date      | Jul 22 13:58:31 2018 |
| Python           | 3.7.0                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | prompt_toolkit1      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```

**Comment by scopatz** [comment]
Hi @eggcaker - thanks for bringing this up!  I think the issue is that the replay functionality has not been updated to work with the SQLite backend.  The database that xonsh uses contains the history of many sessions and `history replay` has no way of specifiy which session to replay. A pull request to fix this would be most welcome!

**Comment by anki-code** [comment]
`history replay` was removed in v0.9.19
