### ISSUE TITLE
Add option for history builtin to output null-delimited results

### ISSUE THREAD

**Issue by laloch** [xonsh/xonsh#2746]
As of now the `history show` builtin can only print EOL-delimited list of commands. This makes it very hard for external filters to properly handle multi-line commands. For instance this example from the Bash to Xonsh Translation Guide:
```
with ${...}.swap(N=V):
    command
```
if used like `history show | fzf` will inevitably end up in fzf like
```
>'with ${...}.swap(N=V):'
>'    command'
```
Please consider adding an optional parameter to switch the output to null-delimited format.

**Comment by scopatz** [comment]
This has been implemented in #2747
