### ISSUE TITLE
How does changing $LS_COLORS work?

### ISSUE THREAD

**Issue by battaglia01** [xonsh/xonsh#2767]
I wanted to change the way that directory colors look on my system when typing `ls`. A manual to do so using the `$LS_COLORS` environment variable is here:

http://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors

I notice that in bash, `$LS_COLORS` is set somewhere by default. xonsh also seems to use these colors, however in xonsh, `$LS_COLORS` is not set at all.

If I set $LS_COLORS, for instance by using `$LS_COLORS="ow=01;33"` to just change other-writable directories, xonsh seems to use this while also using the rest of the default `$LS_COLORS` for everything else.

Is this behavior documented somewhere? How do people recommend that I change $LS_COLORS?

My xonfig

```
+------------------+---------------------+
| xonsh            | 0.7.3               |
| Git SHA          | 9bbbf07b            |
| Commit Date      | Aug 2 18:08:44 2018 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 2.0.4               |
| shell type       | prompt_toolkit2     |
| pygments         | None                |
| on posix         | True                |
| on linux         | True                |
| distro           | neon                |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by melund** [comment]
You are right. Xonsh doesn't do anything to set the `$LS_COLORS` variable. I don't know how `ls` behaves when the variable is not set. It is not something that is defined in xonsh. 

I have added a`$LS_COLORS` definition I found online to my`.xonshrc` file. 

```
$LS_COLORS='rs=0:di=01;36:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:'
```
I agree that maybe we should do like bash and set a default variable if the user doesn't define one. A nice color for `ls` is a big part of the user experience, and not everyone will dig into adding their own defition. 

I think a PR is welcome here. Look at how other environment variables are defined in: 
https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py

**Comment by laloch** [comment]
@melund: I do agree that ls colors are nice to have, but I don't think that bash does anything to set them up. Maybe a better way would be to add an option into the xonfig wizard. Just my two cents...

**Comment by scopatz** [comment]
I agree, it would ne nice for xonsh to do a couple of things with `$LS_COLORS`, I just never have gotten arround to it.  

First, it would be great if `$LS_COLORS` were a dictionary.  Second, it would be great if it would accept and translate xonsh color values down to their ANSI color. Third it would be doubly great if this could be made to respect the xonsh color style.

You can use the command `dircolors` so get the default / current value of `$LS_COLORS`.  

I have never gotten around to this, but it would be awesome if someone did even part of this! PRs welcome.  Happy to walk people through how to do this!

**Comment by melund** [comment]
@scopatz That is a great idea. If anyone is interested then a good place to start is to look at how the `PATHEXT` variable is implemented:
https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py#L156-L157

It abstracts a semicolon separated string to a python list. 
This would basically be the same just for a dictionary. 

> Third it would be doubly great if this could be made to respect the xonsh color style.

Not sure if that is possible or necessary. All we specify for `$LS_COLORS` are the ansi-color codes, then `ls` handles which ansi-escapes are generated.

**Comment by scopatz** [comment]
> Not sure if that is possible or necessary. All we specify for $LS_COLORS are the ansi-color codes, then ls handles which ansi-escapes are generated.

I think it could work if the ANSI colors were first translated into xonsh colors. I think this would be a nice accessablity feature, because otherwise coming up with your own LS_COLORS can be very annoying.

**Comment by comfortablynick** [comment]
I may take a stab at this. How does xonsh use the colors now? Does it implement its own `ls` command and drop in the ANSI escape sequences from `dircolors`? I've been looking through the code but so far haven't found how a command like `ls --color=auto` is handled.

**Comment by scopatz** [comment]
That would be great @comfortablynick! 

So xonsh has an [`ansi_colors`](https://github.com/xonsh/xonsh/blob/master/xonsh/ansi_colors.py) module for converting between the various supported color styles and ANSI escape sequences.  You could combine this with the environment variable to/from converters ([registered here](https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py#L168), and many defined in [tools](https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py#L156-L157`)) 

So in xonsh, we'd like to see `$LS_COLORS` as a dict, for example:

```console
$LS_COLORS = {
    'rs': 'RED',
    'di': 'BLUE',
    ...
}
```

And this would need to be converted back and forth to the srting `'rs=0:di=01;36:...` etc.  I think most of the tools for this exist already, but someone needs to tie them together.

**Comment by scopatz** [comment]
Let me know if you have any questions!

**Comment by uclatommy** [comment]
In case anyone found this while trying to set LS_COLORS for the OSX Terminal, use:
```
$LSCOLORS = "exfxcxdxbxegedabagacad"
```
in your `.xonshrc` file.

More details on how this works [here](http://hints.macworld.com/article.php?story=20031025162727485).

**Comment by scopatz** [comment]
Interesting! PS to support `$LSCOLORS` would be very welcome too!
