### ISSUE TITLE
different cursor shape for insert mode

### ISSUE THREAD

**Issue by t184256** [xonsh/xonsh#2777]
Just a low-importance feature request.

I like how vim changes the cursor shape to indicate whether I am in insert mode or normal mode. This could be useful for users of `$VI_MODE` as an intuitive and familiar reminder of which mode they are currently in.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for the suggestion @t184256! Pull requests certainly welcome here :)
