### ISSUE TITLE
Can not add completion function

### ISSUE THREAD

**Issue by gsaga** [xonsh/xonsh#2779]
I'm having trouble registering completion function for an alias. Here's a minimal example:

    def _f():
        def j():
            pass
    
        global aliases
        aliases['j'] = j
    
        def completions(pref, *args):
            return set(['hello', 'world'])
    
        completer add j completions "start"
    
    _f()
    del _f
    

## xonfig
+------------------+----------------------+
| xonsh            | 0.7.5.dev3           |
| Git SHA          | 8faf3a4c             |
| Commit Date      | Aug 18 22:45:11 2018 |
| Python           | 3.7.0                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | prompt_toolkit1      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

## Expected Behavior
The function `completions` should be added as the completion function for command `j`

## Current Behavior
sourcing the above code emits the following error:

[FrameInfo(frame=<frame at 0x7fda763c0be8, file '/home/saga/.local/lib/python3.7/site-packages/xonsh/completers/_aliases.py', line 89, code _register_completer>, filename='/home/saga/.local/lib/python3.7/site-packages/xonsh/completers/_aliases.py', lineno=89, function='_register_completer', code_context=None, index=None), FrameInfo(frame=<frame at 0x7fda76334b88, file '/home/saga/.local/lib/python3.7/site-packages/xonsh/completers/_aliases.py', line 132, code completer_alias>, filename='/home/saga/.local/lib/python3.7/site-packages/xonsh/completers/_aliases.py', lineno=132, function='completer_alias', code_context=None, index=None), FrameInfo(frame=<frame at 0x7fda763efbb8, file '/home/saga/.local/lib/python3.7/site-packages/xonsh/proc.py', line 1172, code proxy_two>, filename='/home/saga/.local/lib/python3.7/site-packages/xonsh/proc.py', lineno=1172, function='proxy_two', code_context=None, index=None), FrameInfo(frame=<frame at 0x55ece10312d8, file '/home/saga/.local/lib/python3.7/site-packages/xonsh/proc.py', line 1351, code run>, filename='/home/saga/.local/lib/python3.7/site-packages/xonsh/proc.py', lineno=1351, function='run', code_context=None, index=None), FrameInfo(frame=<frame at 0x7fda7001a5d8, file '/usr/lib/python3.7/threading.py', line 917, code _bootstrap_inner>, filename='/usr/lib/python3.7/threading.py', lineno=917, function='_bootstrap_inner', code_context=None, index=None), FrameInfo(frame=<frame at 0x7fda76330980, file '/usr/lib/python3.7/threading.py', line 885, code _bootstrap>, filename='/usr/lib/python3.7/threading.py', lineno=885, function='_bootstrap', code_context=None, index=None)]
No such function: completions

## Steps to Reproduce
Execute the above mentioned snippet.

**Comment by gforsyth** [comment]
Hey @gsaga -- thanks for reporting!

A couple of things to note here --
First, if you move the definition of the `completions` function outside of your `_f` block you will be able to register it using the `completer add j completions "start"` command. 
I'm not sure why it's throwing an error in the way you've set it up, but that's a workaround for now.

Second, the name of the completer is just a name and it won't be default be associated with your alias `j`.  In fact, since you are adding it to the start of the completer list, you will get `("Hello", "World")` back as the completion results for nearly any command that you run.

If you want a completion to only fire for a certain command, you can add in some logic to check which function is being executed and if it isn't the command you want, then you can just return an empty set and the completers will continue firing in order. You can see an example of how that's done in the [`xompletions`](https://github.com/xonsh/xonsh/blob/master/xonsh/completers/xompletions.py#L7-L19) completer, where we only fire if the command is `xonfig` and have further checks for the secondary arguments.

**Comment by gsaga** [comment]
>If you want a completion to only fire for a certain command, you can add in some logic to check which function is being executed and if it isn't the command you want, then you can just return an empty set and the completers will continue firing in order.

Shouldn't that logic be a part of the xonsh shell. It's different from any other shell I've used. What is the reason behind xonsh completion system being the way it is? It looks computationally expensive as well. If I have 1000 completion functions registered, the shell might possibly have to call all 1000 of them.

**Comment by gforsyth** [comment]
Hey @gsaga -- it could be made part of the xonsh shell but would require some rethinking of the completion framework.  It can be computationally expensive, although we take advantage of bash completions where available and that has removed the need for a lot of built-in completions.  I believe, too, that the prompt_toolkit version handles the completion calls in a non-blocking fashion so it shouldn't slow down user experience in a noticeable way.  

One of the hurdles to clear if we do something more akin to dynamic dispatch for completions is that the mixed context nature of xonsh can make it unclear which completion functions should be run in which situations.

 We're certainly open to a discussion of other options and any contributions that people want to make towards improving things!
