### ISSUE TITLE
[DISCUSSION]: Is PTK1 deprecated?

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#2786]
@laloch raised a point in #2762 that I think we should discuss / come to a consensus on.

We have some feature splits between prompt_toolkit and readline, because readline can't support all of things that prompt_toolkit does.  But we generally try to keep feature parity between the two backends when possible.

We are still supporting PTK1 right now so we don't just break for people on upgrade.  That said, I would propose that new features only be implemented in PTK2 (and in readline where possible/applicable).

Thoughts?

**Comment by melund** [comment]
I agree with @gforsyth, and I think we could even drop support for PTK1 once IPython makes the switch to PTK2 in the upcoming version. But until then I agree that we can limit new features to PTK2

**Comment by scopatz** [comment]
Yes I agree!

**Comment by laloch** [comment]
Regarding the idea of dropping PTK1 support altogether: There's an issue with out-of-tree (or 3rd party) xontribs. I do myself use [powerline](https://github.com/santagada/xontrib-powerline) and [fzf-widgets](https://github.com/shahinism/xontrib-fzf-widgets). Both of them seem to be unmaintained and none of them work well with PTK2. To be absolutely correct fzf-widgets xontrib is already horribly broken in several other ways, but one of them is, that it can't handle PTK2 key bindings.

**Comment by gforsyth** [comment]
Blarg.  That's another good point @laloch.  We've had a discussion in the past (I think on here?  But maybe on gitter?) about how and when we would remove extensions from our extension directory.
We can certainly open PRs to fix them and if they get merged, so much the better.  If not, then we need to figure a timeline for removing those extensions from the list.

**Comment by anki-code** [comment]
We have ptk3 now and this thread looks not actual.
