### ISSUE TITLE
Configure xonsh to directly complete instead of displaying a menu if there's a single completion entry.

### ISSUE THREAD

**Issue by gsaga** [xonsh/xonsh#2791]
Is there a way to configure xonsh so that it directly completes the word instead of displaying a menu if there's a single completion entry? It's very difficult to browse directory tree without it.

## xonfig

    +------------------+----------------------+
    | xonsh            | 0.7.6.dev5           |
    | Git SHA          | 837c714a             |
    | Commit Date      | Aug 25 18:35:16 2018 |
    | Python           | 3.7.0                |
    | PLY              | 3.9                  |
    | have readline    | True                 |
    | prompt toolkit   | 1.0.15               |
    | shell type       | prompt_toolkit1      |
    | pygments         | 2.2.0                |
    | on posix         | True                 |
    | on linux         | True                 |
    | distro           | arch                 |
    | on darwin        | False                |
    | on windows       | False                |
    | on cygwin        | False                |
    | on msys2         | False                |
    | is superuser     | False                |
    | default encoding | utf-8                |
    | xonsh encoding   | utf-8                |
    | encoding errors  | surrogateescape      |
    +------------------+----------------------+

**Comment by gforsyth** [comment]
Hey @gsaga -- that should be the default behavior in that situation (and is the way it works on my machine).  Do you have any non-default options related to completions set in your `xonshrc`?

**Comment by gsaga** [comment]
Try these command:
 
    mkdir /tmp/a/b/c/d/e
    cd /tmp/a

and then type `cd b` and press `tab` repeatedly. I would expect the shell to complete all the paths until e, the way it does in `zsh`, but instead it gets stuck on `c`.

**Comment by laloch** [comment]
I can confirm that. You can set `$COMPLETIONS_CONFIRM = '1'` as a workaround if you don't mind pressing `return` key to confirm the completion.

**Comment by scopatz** [comment]
@gsaga - that sounds like a great feature! Would love to see the `cd` completer updated to allow this

**Comment by gsaga** [comment]
@scopatz I've checked the `complete_path` function in `xonsh/completers/path.py` and looks like it just returns a set of completions, and it works correctly(returns a set of one entry if there's just one completion).

Implementing this feature might require modifying the tab completion mechanism (which calls various completer functions) so that it directly inserts the entry if there's only one.

The readline shell performs the completion as expected. Maybe some switch to prompt_toolkit needs to be tweaked.

**Comment by scopatz** [comment]
Hmm interesting yeah, perhaps it does!

**Comment by gforsyth** [comment]
This is a weird one -- because it should allow the paths to continue to complete but @gsaga is correct that it starts offering the dropdown a couple folders deep, but there aren't any other valid completions at that point.

**Comment by gforsyth** [comment]
Ha, figured this one out, PR incoming

**Comment by gforsyth** [comment]
Forgot to push it up yesterday, but there's a fix in #2800 for ptk2
