### ISSUE TITLE
Xonsh should display a menu instead of listing possible commands when an invalid command is run.

### ISSUE THREAD

**Issue by ghost** [xonsh/xonsh#2807]
When an invalid command is executed, the shell displays a list of matching command names. It would be better if the shell would display a chooser menu when a wrong command is entered.

The menu could have commands sorted by type, with 'tab' switching between them.  

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by battaglia01** [comment]
If this is added, I'd personally prefer if one could also leave this behavior out via xonfig setting.

**Comment by scopatz** [comment]
Thanks for the suggestion @gsaga! I think this would be a nice feature to have (probably PTK v2 only, though).  And yes, the default would probably be off for this.  Pull requests welcome!

**Comment by anki-code** [comment]
I'm going to close this because it could be implemented as a xontrib.
Example: https://github.com/meatballs/xontrib-thefuck
