### ISSUE TITLE
Xonsh wizard crashed

### ISSUE THREAD

**Issue by mikehearn** [xonsh/xonsh#2823]
I installed xonsh onto macos using homebrew, started it, and ran the wizard. I told it I wanted to import fish as a foreign shell and accepted all the defaults for every other question.

My wizard experience ended like this:

```
Would you like to enable xontribs now, yes or no [default: no]?

'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'


xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by scopatz** [comment]
Thanks for reporting @mikehearn!

I think that this is because we don't yet support fish as a foreign shell (see #485).  Still it shouldn't crash.

**Comment by scopatz** [comment]
Potential fix is in #2831

**Comment by gforsyth** [comment]
Hey @mikehearn -- this autoclosed when I merged in the fix but let us know if the issue persists and we can reopen.  Thanks again for reporting!

**Comment by mikehearn** [comment]
Thanks - in that case the bug would have been both not checking user input and the wizard having misleading text in it. `xonfig wizard` explicitly says:

> The xonsh shell has the ability to interface with foreign shells such as Bash, zsh, or fish.

So I assumed it'd work. Glad to see that you've extended support though - xonsh is great!

**Comment by scopatz** [comment]
@mikehearn - yeah, fish is a little tricky to implement explicit support for, so no one has gotten around to it yet.  PRs very welcome though!

**Comment by michaelaye** [comment]
I'm confused, the wizard clearly offers fish? So, is it supported or not?

**Comment by mikehearn** [comment]
The wizard looks like it offers fish, but actually doesn't. I agree this is confusing.

**Comment by gforsyth** [comment]
A PR removing the option from the wizard would be very welcome! (Or adding fish support, although that's a bigger lift)
