### ISSUE TITLE
[feature] Boolean flags behavior

### ISSUE THREAD

**Issue by MrQubo** [xonsh/xonsh#2826]
Currently, boolean flags (e.g. `source-foreign`'s `--safe`) accepts an argument. Those arguments are parsed [here](https://github.com/xonsh/xonsh/blob/e83ab51164d54e42796f45021a2ea3e546dd1fb8/xonsh/tools.py#L1192-L1199).
I'm not sure how `argparse` works but I think that the argument passed to this function will always be a string. So, basically it works that way, that if an argument is in the list of falsy values it is converted to `False`, every other string is converted to `True`.

The help outputs of commands (e.g. `source-foreign --help`) don't say which arguments are parsed as `False` and which are parsed as `True`. I tried with 'off' (see #2825) and it was converted to `True`!

I think we should hold both the list of falsy and truthy values and fail if an argument cannot be found in any of them. In my opinion, the current behavior is really user unfriendly.

The alternative would be to convert all those boolean flags to not accept argument but have a `--no-` counterpart. (e.g. `--safe` and `--no-safe`).
This solution would be even better, I think it's more common to handle boolean flags that way. I find it more natural to write `source-foreign --safe FILE` than `source-foreign --safe=true FILE`. Currently the former will cause the `FILE` to be parsed as an argument to `--safe` and just silently be converted to `True`.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by MrQubo** [comment]
I can implement this but it needs discussion.

**Comment by scopatz** [comment]
Hi @MrQubo, thanks for opening this! Would you consider this taken care of now that `off` can be used?  Also, I am in favor of adding additional options to the CLI, but wouldn't really want to remove them (since I am not sure a deprecation cycle is worth it in this case.)

**Comment by MrQubo** [comment]
I think that `--show=yes`, `--show=no` syntax can be left as it is. But `--show  yes` and `--show  no` is unintuitive and should be removed or deprecated.
Removing the second syntax would allow us to introduce `--show` and `--no-show` syntax and still left `--show=yes` and `--show=no` for backward compatibility.

**Comment by scopatz** [comment]
With argparse, `--show=yes` and `--show yes` are equivalent

**Comment by MrQubo** [comment]
Actually, I made a mistake in my example, the `--show` flag isn't a boolean flag but `store_true`. So it's a flag without any arguments.
I had `--safe` flag in my mind.
I've updated the main comment.

**Comment by MrQubo** [comment]
@scopatz We could add `--safe=yes`, `--safe=t`, etc. as flags without arguments. Like this:
```py
parser = __import__('argparse').ArgumentParser()
parser.add_argument(
    '--test',
    '--test=yes',
    '--test=t',
    '--test=y',
    '--test=on',
    action='store_true',
    default=False,
    dest='test',
)
parser.add_argument(
    '--no-test',
    '--test=no',
    '--test=f',
    '--test=n',
    '--test=off',
    action='store_false',
    default=False,
    dest='test',
)
__import__('pprint').pprint(parser.parse_args())
```
Works quite well and the help lists all allowed falsy and truthy flags.

**Comment by anki-code** [comment]
Hi @jnoortheen! You made a big effort around improving the arguments parsing during past months. Could you please review this issue.

**Comment by jnoortheen** [comment]
The said foreign functions now have removed that confusing options and now use `--unsafe` flag to specify the False value to `safe` argument. Most of the alias-function parsers now have it this way. If there is any other options that is supposed to accept boolean values, we can create equivalent flags and remove custom parsing of input values. I am closing this, this is no longer the case with source-foreign commands.

@anki-code Thanks for bringing it up.
