### ISSUE TITLE
No prompt after `sudo`

### ISSUE THREAD

**Issue by CGenie** [xonsh/xonsh#2833]
## xonfig
```
+------------------+-----------------+
| xonsh            | 0.7.8           |
| Python           | 3.7.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------
```

## Expected Behavior
I use ArchLinux with the `aurman` package manager. When I want to install some package, `aurman` prompts for the `sudo` password, and later displays another prompt whether I want to install a package.

## Current Behavior
Currently `xonsh` doesn't display the second prompt, the screen just freezes until I kill the process with `Ctrl-C`. `sudo` remembers the password for a while so when I rerun the `aurman` command, I get a normal prompt about package installation from `aurman` (since it doesn't ask for `sudo` password for a while).

## Steps to Reproduce
Described above basically. I don't know how to reproduce that with some other command. I tried with `ssh` where I have to enter the password, however it does work with `sudo` in `xonsh`. I guess there's something with `aurman` here that makes it different.
However I never got such behavior in other shells be it Bash or Zsh.

**Comment by laloch** [comment]
I'm also an Arch Linux user and I also use aurman. The catch with xonsh (it's a known issue) is that there's a kind of race between the standard output and standard error output. If you look closely at the terminal, you'll find out that the screen is not really frozen. It waits for your input. The prompt just got mixed with the rest of the aurman's output. You'll get used to it :wink:

**Comment by CGenie** [comment]
OK but it doesn't print out the prompt and when it comes to install packages on the system, I don't want to blindly make inputs :)

**Comment by laloch** [comment]
Are you sure it doesn't print the prompt? For me it usually looks like this:
```
aurman -Syu                                                                                                             0  18:46 
:: Synchronizing package databases...
 core is up to date
 extra                                                  1635.9 KiB  11.2M/s 00:00 [###############################################] 100%
 community                                                 4.6 MiB  11.1M/s 00:00 [###############################################] 100%
 multilib is up to date
 archlinuxfr is up to date
:: Starting full system upgrade...
warning: sdcc: local (3.7.0_rc1-4) is newer than community (3.7.0-5)
resolving dependencies...
looking for conflicting packages...
:: Proceed with installation? [Y/n] 
Packages (3) linux-4.18.9.arch1-1  linux-headers-4.18.9.arch1-1  xterm-336-1

Total Download Size:    82.93 MiB
Total Installed Size:  165.68 MiB
Net Upgrade Size:        4.67 MiB
```
The `Proceed with installation? [Y/n]` prompt is supposed to be at the bottom of course. It's obviously not at the bottom, but it's still there.

**Comment by laloch** [comment]
@CGenie you might want to try out this patch: https://gist.github.com/laloch/e72ab1952ed14f4e7f7df2cb4e189d7f#file-xonsh-aurman-cache-patch

**Comment by gforsyth** [comment]
Hey @CGenie , so @laloch has the correct workaround, which is to set `aurman` as a `predict_false`.

If you'd like a quick one-liner to test with, you can run this line in the xonsh session, or add it to your `xonshrc`

```
 __xonsh_commands_cache__.threadable_predictors['aurman'] = lambda args: False
```

**Comment by laloch** [comment]
@gforsyth that's just wow! I was about to suggest something along the the lines of
```
def customize_predictors():
    import xonsh
    __xonsh_commands_cache__.threadable_predictors['aurman'] = xonsh.commands_cache.predict_false

customize_predictors()
```
but I'm a C programmer :(

**Comment by CGenie** [comment]
@gforsyth Indeed that fixes the problem, thanks a lot!

**Comment by scopatz** [comment]
Should `aurman` go into a default permanent false threadable predictors?
