### ISSUE TITLE
hg split keys not being propogated

### ISSUE THREAD

**Issue by joetoth** [xonsh/xonsh#2834]
`hg split` from Mercurial brings up a curses based ui. When I type j/k up/down it just prints the code characters. *If I type j and then hit Enter, it will propagate the keypress.*

Mercurial is written in python, if that makes any difference
https://www.mercurial-scm.org/repo/hg/file/tip/mercurial/ui.py

## xonfig
+------------------+----------------------+
| xonsh            | 0.7.9.dev6.dev6      |
| Git SHA          | ad06426e             |
| Commit Date      | Sep 21 11:55:18 2018 |
| Python           | 3.5.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Debian               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

## Expected Behavior
Should be able to use arrow keys to move up and down.

## Current Behavior
Just prints characters to the screen ^[OB^[OA

## Steps to Reproduce
If you have mercurial installed, try using hg split

Let me know if you need any more info.

Thanks!

**Comment by scopatz** [comment]
Thanks for opening this issue @joetoth! A potential fix is available at #2836

**Comment by joetoth** [comment]
Awesome, thanks!
Checked it out and it works. Though there are a bunch of other commands that need to be whitelisted.
I didn't mention initially because I thought, if one was fixed, they all would be. Sorry about that.

There are other commands, extensions and user defined aliases that can be interactive. So I'm not sure appending to a whitelist is the most effect way going forward.

I haven't taken a look at the code yet, but if you can describe the problem and why the whitelist approach is needed I can take a look and see what I can do.

Thanks!

**Comment by scopatz** [comment]
Awesome! Yeah, if there are other commands, feel free to either let me know, or just put them into a PR.  This PR should tell you exactly what you'd need to change :wink:
