### ISSUE TITLE
Overriding Prompt Toolkit style 

### ISSUE THREAD

**Issue by laloch** [xonsh/xonsh#2838]
PTK2 defaults to reverse the colors of the bottom toolbar, which visually breaks the Powerline extension:
![screenshot_20180923_120221](https://user-images.githubusercontent.com/1336917/45926805-a3a69300-bf28-11e8-8f93-b8696e5d6b84.png)
In order to get rid of that annoyance, one needs to set `'bottom-toolbar': 'noreverse'` PTK style. My question is: What's the correct way to do it in xonsh? I got lost in the many style translation layers and the best I could come with is the below which does the trick, but is obviously wrong.
```
index 4a55664c..144d6f1b 100644
--- a/xonsh/ptk2/shell.py
+++ b/xonsh/ptk2/shell.py
@@ -144,6 +144,7 @@ class PromptToolkit2Shell(BaseShell):
             else:
                 style = style_from_pygments_dict(DEFAULT_STYLE_DICT)
 
+            style.style_rules.append(('bottom-toolbar', 'noreverse'))
             prompt_args["style"] = style
 
         line = self.prompter.prompt(**prompt_args)
```
![screenshot_20180923_121133](https://user-images.githubusercontent.com/1336917/45926876-df8e2800-bf29-11e8-973b-2a32f88ff972.png)

**Comment by laloch** [comment]
@bestlem I know about your fork ... and I don't like your solution :stuck_out_tongue_winking_eye:

**Comment by scopatz** [comment]
PRs welcome!
