### ISSUE TITLE
Pin version of `black` used in CircleCI checks

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#2846]
In #2845 the `black` formatting check failed because of an update made to `black` that handles formatting [numeric literals](https://github.com/ambv/black#numeric-literals).  Since the change was made after we used `black` to set the baseline for the entire code-base, it failed when the PR in question was opened, since there was a new version of `black` installed by CI.

So, we should pin the version of `black` that we install on Circle and deliberately update it when needed so we don't have random `black` fixes scattered among otherwise unrelated PRs.

**Comment by scopatz** [comment]
Thanks for pointing this out @gforsyth!

**Comment by dbarbuzzi** [comment]
I’d like to grab this since it appears open. Since the process is already just pulling the current `black` release, are there any objects to pinning the current release?

**Comment by gforsyth** [comment]
Hey @dbarbuzzi, that sounds good to me! Thanks!
