### ISSUE TITLE
Add to "projects that use Xonsh" in README and docs

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#2849]
All we have listed right now is `gitsome` but there's also 
* rever: https://regro.github.io/rever-docs/
* the regro autotick bot: https://github.com/regro/cf-scripts

and maybe more?  who knows?

**Comment by scopatz** [comment]
Much agreed!

**Comment by gforsyth** [comment]
Closed via #2850 but if there are more, please add them!
