### ISSUE TITLE
ZSH like MC light tab completion/file browser

### ISSUE THREAD

**Issue by nootropics** [xonsh/xonsh#285]
I love zsh and the only reason I haven't switched to xonsh is because I couldn't live without the file "browser" style tab completion, is this possible?

**Comment by scopatz** [comment]
Hi @nootropics - I am not sure what you mean exactly (though I have a guess).  Can you send a screen shot, please?

**Comment by nootropics** [comment]
![Of course I can!](http://i.stack.imgur.com/GvC4A.png)

Where you can press the arrow keys and move about folders like a limited mc install, it's an awesome feature

**Comment by scopatz** [comment]
Looks great :) Pull requests definitely welcome.

**Comment by nootropics** [comment]
I wish I was intelligent enough to help :(

**Comment by scopatz** [comment]
I believe that our prompt-toolkit shell satisfies this feature (and has for a while). If you'd like a more specific feature or improvement, please feel free to open a new issue.
