### ISSUE TITLE
[idea] Reimplement  parser as a fork of python implementation

### ISSUE THREAD

**Issue by MrQubo** [xonsh/xonsh#2871]
I was thinking of an idea to implement xonsh parser by forking some existing python implementation like [cpython](https://github.com/python/cpython). Currently, we're parsing the python code ourselves [here](https://github.com/xonsh/xonsh/tree/master/xonsh/parsers) and building the AST tree from it.

- With the current solution, we need to update the parser in case of some new python syntax. With a fork, we would have to just merge the implementation from the upstream when it will be available.

- Some bugs in xonsh are related to the parser, e.g. see #2870, #2721 and #2688. By using much more tested, existing implementation we would have much less of those.

- Writing portion of the xonsh source code in a low-level language like C would make it faster than the equivalent code in python. Direct access to the python's source code might also open the possibility for more optimizations.

- Currently, users can use xonsh with different python versions. Shipping xonsh with its own python fork will have a positive impact on stability. For example, some bugs might be present only on a specific python version.

As for drawbacks:

- The overall size of xonsh will increase because python would stop being a dependency and be included instead.

- It will be quite a lot of work to do and it will be harder for newcomers to write PRs.

- It will _massively_ increase the built times.

To demonstrate, I've forked [cpython](https://github.com/python/cpython) and implemented the env variables including the syntax with braces. It's the [xonsh](https://github.com/MrQubo/cpython/tree/xonsh) branch on this [repository](https://github.com/MrQubo/cpython/tree/xonsh).

**Comment by scopatz** [comment]
Hi @MrQubo - Thanks for opening this.  the tl;dr version is that anyone who wants to help take on parser issue is welcome to! We could certainly use the help.  

The big advantages I see here is that it could,

1. dramatically speed up parse time (which isn't really a big issue)
2. dramatically speed up load time (which is a huge problem for us)

The main disadvantages I see are, 

1. As you note the build time is much longer
2. We might not have access to some of less used platforms, right now we run on anything that Python supports and if we were to require a C-extension as a required component, we'd only easily have access to build on Window, Mac, Linux.
3. I don't think we want xonsh to contain a Python interpreter.  I think we'd want to rip out just the parsing part of CPython.
4. This could make it harder for xonsh to be run on alternative Python interpreters, such as PyPy and Jython.

I think we'd therefore want any C-based speedups to be optional, not required. This adds additional complexity to the build and development, but I feel is worth it overall
