### ISSUE TITLE
xonsh doesn't find non-standard-libs anymore

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#2885]
## xonfig

```bash
(py36) klay6683@macd2860 ~ $ xonfig
+------------------+-----------------+
| xonsh            | 0.8.0           |
| Python           | 3.6.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.6           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```
## Expected Behavior

I had this working before, at least on a different machine, so I don't know what's missing.
I am running xonsh inside conda envs, and have astropy installed, and before I could simply do:

```python
from astropy import units as u
```
and use the units system inside my shell, which is genius! ;)

## Current Behavior

(py36) klay6683@macd2860 ~ $ from astropy import units as u
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16330, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/Users/klay6683/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2453, in run_compiled_code
    func(code, glb, loc)
  File "/Users/klay6683/miniconda3/lib/python3.6/site-packages/xontrib/xonda.xsh", line 1, in <module>
    import os
ModuleNotFoundError: No module named 'astropy'

## Steps to Reproduce

I really don't know, that's the current state I'm in, and even removing the `.xonshrc` file doesn't solve this. Where should I look?

System: macOS 10.13.6

**Comment by michaelaye** [comment]
ah, this is related to the fact that I had to put the xonsh instance into the `base` env to make `xonda` work, but I don't have my software installed in `base`. :( Guess I can't have both `xonsh` and `conda`. Pity. Well, see you in another year then.

**Comment by scopatz** [comment]
Hey @michaelaye - I'd really like to help you resolve the issues you are seeing.  I use xonsh + conda all the time.  Are you going to be at PyData NYC by chance?

**Comment by michaelaye** [comment]
thanks for your effort, unfortunately not. Maybe you could write a blog post with your detailed setup somewhere?

**Comment by scopatz** [comment]
Well, I usually use the base env, which I think is the problem here.  Maybe we could set up a time for a video call and you could show me what is going wrong?

**Comment by michaelaye** [comment]
Very simple, if I xonsh and xonda only installed in the base env, when I activate other envs, I can't import from astropy or other 3rd party packages, b/c I keep the base env clean for only conda related stuff, no other installs. My work happens in several environments. But I don't like to keep xonsh, xonda and all other installs up to date in all my other envs, so there needs to be a way xonsh can look up the current paths and not where it's installed to find python packages to import. Otherwise it's too much maintenance overload.
