### ISSUE TITLE
in-place expansion of aliases

### ISSUE THREAD

**Issue by aramiscd** [xonsh/xonsh#2889]
Fish shell expands aliases in-place.

![](http://hashstore.aramis.auriga.uberspace.de/9f38ec63c7c9820d718fd80e3bb0a1cd.gif)

It is triggered by `<enter>` and `<space>` (at least).

I prefer that behaviour because it lets me see (and modify if necessary) what is actually going on, instead of hiding it behind the alias.  I'm opening this issue to document my interest in that feature for xonsh.  Unfortunately I can't contribute a PR for it myself.  At least not right now.

**Comment by scopatz** [comment]
Hi @qqhann - you should look at https://github.com/xonsh/xonsh/blob/master/xonsh/ptk2/key_bindings.py This is where all of the key bindings for PTK live.  Any help here is very welcome!

**Comment by jnoortheen** [comment]
this is recently added to the master as a xontrib `abbrevs` - https://github.com/xonsh/xonsh/pull/3484
