### ISSUE TITLE
Slowish startup (via bash's completion system)

### ISSUE THREAD

**Issue by blueyed** [xonsh/xonsh#289]
I am trying out xonsh, and noticed that it's rather slow to start up, which is significant for me, because I tend to use many shells / terminal windows:

    % time xonsh -c exit
    xonsh -c exit  1,37s user 0,17s system 96% cpu 1,602 total

Profiling it shows this:

    % python -m cProfile -s cumtime =xonsh -c exit | head -n 25
    
             203330 function calls (199603 primitive calls) in 1.551 seconds
    
       Ordered by: cumulative time
    
       ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        124/1    0.023    0.000    1.552    1.552 {built-in method exec}
            1    0.000    0.000    1.552    1.552 xonsh:3(<module>)
            1    0.000    0.000    1.308    1.308 xonsh:2(<module>)
            1    0.000    0.000    1.223    1.223 main.py:52(main)
            1    0.000    0.000    1.126    1.126 shell.py:25(__init__)
            4    0.000    0.000    1.039    0.260 subprocess.py:565(check_output)
            4    0.000    0.000    1.027    0.257 subprocess.py:919(communicate)
            4    0.016    0.004    1.027    0.257 subprocess.py:1575(_communicate)
          955    0.011    0.000    0.998    0.001 selectors.py:356(select)
          955    0.984    0.001    0.984    0.001 {method 'poll' of 'select.poll' objects}
            1    0.000    0.000    0.565    0.565 shell.py:53(_init_environ)
            1    0.000    0.000    0.564    0.564 execer.py:19(__init__)
            1    0.000    0.000    0.542    0.542 readline_shell.py:87(__init__)
            1    0.000    0.000    0.535    0.535 built_ins.py:564(load_builtins)
            1    0.000    0.000    0.530    0.530 base_shell.py:17(__init__)
            1    0.000    0.000    0.530    0.530 completer.py:41(__init__)
        126/9    0.002    0.000    0.375    0.042 <frozen importlib._bootstrap>:2234(_find_and_load)
        126/9    0.002    0.000    0.375    0.042 <frozen importlib._bootstrap>:2207(_find_and_load_unlocked)
       123/10    0.002    0.000    0.368    0.037 <frozen importlib._bootstrap>:1186(_load_unlocked)

Before this, I had looked at `strace -f …` and noticed a bunch of bash_completion related files.

The callers of `subprocess.check_output`:

    O% callers check_output
       Random listing order was used
       List reduced from 1388 to 1 due to restriction <'check_output'>

    Function                           was called by...
                                           ncalls  tottime  cumtime
    …/subprocess.py:565(check_output)  <-       1    0.000    0.261  …/xonsh/aliases.py:72(bash_aliases)
                                                1    0.000    0.228  …/xonsh/completer.py:217(_load_bash_complete_funcs)
                                                1    0.000    0.235  …/xonsh/completer.py:234(_load_bash_complete_files)
                                                1    0.000    0.262  …/xonsh/environ.py:470(bash_env)

I am using Zsh as my shell, and `bash` is not slow to start up:

    % time bash -c exit
    bash -c exit  0,00s user 0,00s system 77% cpu 0,005 total

But `bash -i` more so:

    % time bash -i -c exit
    exit
    bash -i -c exit  0,20s user 0,02s system 84% cpu 0,265 total

I think this could be optimized by a) avoiding `bash -i` if possible and b) only call it once and then do all required querying there in one go.

Python 3.4.3.

**Comment by blueyed** [comment]
It turns out that the slow part is `source /etc/bash_completion`, which is used
with `bash -i` and the setup of xonsh's completion system.

I have the following installed in /etc/bash_completion.d:

    ag                     gdbus            parecord
    alltray                gem1.8           pasuspender
    apport_completion      gem1.9.1         pbuilder
    apt-file               git-prompt       pbuilder-dist
    axi-cache              gresource        phoronix-test-suite
    boinc                  grub             pon
    bzr                    gsettings        pulseaudio
    cmake                  initramfs-tools  pulseaudio-bash-completion.sh
    cpack                  insserv          pycompletion.sh
    cryptdisks             libreoffice.sh   pygmentize
    ctest                  lxc              quilt
    debconf                lxc.sh           rake
    deborphan              mercurial        rdiff-backup
    desktop-file-validate  mosh             redis-cli
    devscripts.chdist      npm              subversion
    devscripts.pkgnames    openvpn          tig
    dkms                   pacat            torsocks
    docker                 pacmd            ufw
    dput                   pactl            upstart
    etckeeper              padsp            youtube-dl.bash-completion
    fastboot               paplay
    gammu                  parec

When removing them, bash is faster to startup:

    bash -i -c exit  0,06s user 0,01s system 64% cpu 0,111 total

For reference, I've tried to find a possible culprit using this (Zsh syntax), but they are all equally slow and it just adds up:

   % cd /etc/bash_completion
   % sudo mkdir out
   % sudo mv * out
   % (TIMEFMT='%*E'; for i in /etc/bash_completion.d/out/*; do echo -n "== ${i:t}: "; sudo mv $i ${i:h}/..; time (echo 'source /etc/bash_completion' | bash); sudo mv ${i:h}/../${i:t} ${i:h}; done)

**Comment by blueyed** [comment]
I've just noticed that this is heavily related to my notebook being on AC vs. battery.  On the former, it's not so slow anymore:

    xonsh -c exit  0,63s user 0,05s system 91% cpu 0,747 total

But there's still room for improvement nonetheless.

**Comment by scopatz** [comment]
Hi @blueyed! Thanks for these timings.  They are super helpful.  Just as a point of reference, my timings are (on a battery):

```console
$ time xonsh -c exit
real 0.34
user 0.28
sys 0.02
```

I think that you are right that a lot of the slow down comes from these multiple bash instances that we start up and the flags that we pass to them.  Unfortunately, in some cases `-i` flag needs to be there to capture the needed environment data.  

It is good to know that bash completions are the culprit.  We don't have non-interactive xonsh instances implemented yet. If we did, then we could turn off a lot of stuff at startup as needed.  Pull requests welcome :)

I think that if you set the `$BASH_COMPLETIONS 	= []` environment variable to an empty list, then there will be nothing to source and we can safely turn off completions.  Perhaps `None` should also be valid here.

**Comment by blueyed** [comment]
There's a TODO about using threads and/or doing it lazily in https://github.com/scopatz/xonsh/blob/c5ab05409dd5fe60e89a2f189815f58ae3ebc370/xonsh/completer.py#L49-L52 for `Completer.__init__` already.

Another idea that came to my mind would be to use a pickled cache for this (and potentially other things).  It could use the timestamps for the bash completion input files / mtime of the involved dirs and use its cache when it has not changed.

Also `_load_bash_complete_funcs` and `_load_bash_complete_funcs` could be combined into a single call to bash, using Bash's scripting to build/parse the lists.

**Comment by scopatz** [comment]
Do you mean `_load_bash_aliases()`?

**Comment by asmeurer** [comment]
How many times does xonsh run bash -i when starting up? Even a reasonably fast bash startup can be compounded. I know ideally one would move all configuration to .xonshrc, but for now I want to keep both xonsh and bash usable. There's got to be a better way.

**Comment by scopatz** [comment]
I think that bash -i is currently only run twice.  I don't see us totally removing bash compatibility for a long time, but maybe we should have a way to turn it off optionally.

**Comment by asmeurer** [comment]
I'm all for bash compatibility, but can't you organize things so that you run bash -i exactly once?

**Comment by scopatz** [comment]
Yes, and this is what I wanted to do originally, but didn't want to fight with the implementer too much. Now that we know it is definitely causing problems we can go ahead and fix it.

**Comment by gforsyth** [comment]
Closing this.  All the completion stuff is lazily loaded now and amalgamate should give a 10+x speedup. Please reopen if any issues persist.  Thanks!
