### ISSUE TITLE
xonsh on a dumb terminal (because it runs in an Emacs comint buffer)

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#2891]
I run `xonsh`  from a `bash` inside an Emacs `comint` buffer. 

## xonfig

```

+------------------+-----------------+
| xonsh            | 0.7.9           |
| Python           | 3.7.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 2.0.4           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

When starting `xonsh` from the `bash` shell the environment variable `TERM` is set to `dumb`, so I would hope `xonsh` doesn't use any coloring or other escape sequences.  Or if that's not possible I would like to know how I can manually switch off the use of all escape sequences, say, via the `.xonshrc` file.

## Current Behavior

`xonsh` seems to emit escape sequences despite a dumb terminal. (The prompt seems to be written in invisible colors). Also I get the following message:

    WARNING: your terminal doesn't support cursor position requests (CPR).

## Steps to Reproduce

In a graphical GNU Emacs 26.1 on macOS start a shell comint buffer, then run `xonsh`.

**Comment by scopatz** [comment]
Thanks for reporting @halloleo! This would be a great feature to have.  Xonsh has a model that uses multiple shell types, i.e. backends providers.  You can [read about them here](https://xon.sh/envvars.html#shell-type). 

For prompt-toolkit, [there is a long-standing open issue about this](https://github.com/jonathanslenders/python-prompt-toolkit/issues/390). You may want to revive that conversation.

For readline, it isn't clear to me that setting `$TERM='dumb'` does anything.  

We could certainly implement another shell type that implements a dumb terminal. (PRs welcome!) However, it isn't clear to me what the dumb terminal actually allows. [This seems to indicate](http://invisible-island.net/ncurses/terminfo.src.html) that it basically has bel, cr, nl, etc. and nothing else

**Comment by halloleo** [comment]
Thanks for the pointers, @scopatz.  I switched to the readline shell type and it seem to work with that.

**Comment by scopatz** [comment]
Ahh excellent!  Adding this to the docs would be great!

**Comment by halloleo** [comment]
Will do so after cloning the repo.

**Comment by halloleo** [comment]
If I want to document that `xonsh` + `readline` work reasonably in a Emacs `shell-mode` buffer, I guess the `xonsh-docs` repo is the repo to write a pull request for, correct?

**Comment by melund** [comment]
>I guess the xonsh-docs repo is the repo to write a pull request for, correct? 

No. That repo is used to host the compiled documentation. The source documentation lives in 
https://github.com/xonsh/xonsh/tree/master/docs

**Comment by halloleo** [comment]
Thanks @melund. Will look for a good place in the sources to add this.

**Comment by halloleo** [comment]
At the moment I set in the `$SHELL_TYPE` by hand to `'readline'`  my .xonrc file if $TERM == 'dump'. - Would it make sense to build this into the built-in startup of xonsh when the `$SHELL_TYPE` default `'best'` is used?

**Comment by scopatz** [comment]
I am not an emacs user, so how would I set up emacs to use xonsh so that I could test a dumb terminal?

**Comment by scopatz** [comment]
potential fix in #2959

**Comment by halloleo** [comment]
@scopatz One way to test this is to open on macOS or Linux a bash shell (via `M-x shell`) and then start a xonsh in there and see whether the shell navigation works properly. If you don't want to go via bash set the Emacs variable `explicit-shell-file-name` to your xonsh executable.

**Comment by halloleo** [comment]
BTW, I have checked the new build 0.8.5 against this issue and it works now without setting $SHELL_TYPE manually in my xonsh file. :-)

**Comment by scopatz** [comment]
Excellent!
