### ISSUE TITLE
My alias-expanding sudo hangs with 0.8.1

### ISSUE THREAD

**Issue by t184256** [xonsh/xonsh#2893]
In xonsh 0.8.1 with `--no-rc` I can do `sudo ls | less` and it works fine.

With a .xonshrc consisting of the following lines only:
```
# make sudo expand aliases
def sudo_expanding_aliases(args, stdin=None):
    /usr/bin/env sudo @(aliases.eval_alias(args))
aliases['sudo'] = sudo_expanding_aliases
del sudo_expanding_aliases
```

`/usr/bin/env sudo ls | less` works as expected, while `sudo ls | less` hangs hard since 0.8.1, `C-C` or `C-\` do not help.

Couldn't find any relevant recent changes at the first glance, were there any?

**Comment by scopatz** [comment]
Thanks for reporting @t184256! Actually, on 0.8.0, I am getting `sudo ls | less` hanging with that alias, so I don't think that 0.8.1 broke it in any real way. 

I think that the main issue here is that stdout in the alias isn't be redirected correctly.

**Comment by scopatz** [comment]
I think this is the right way to write such an alias:

```python
def sudo_expanding_aliases(args, stdin=None, stdout=None): 
    p = !(/usr/bin/env sudo @(aliases.eval_alias(args))) 
    for line in p: 
         stdout.write(line) 
    return p.returncode

aliases['sudo'] = sudo_expanding_aliases 
del sudo_expanding_aliases 
```

**Comment by scopatz** [comment]
We should probably have sudo, env and a few others always expand aliases too, though.

**Comment by t184256** [comment]
I've tried your suggestion way and it doesn't play nice with interactive commands like vi. Went back to https://github.com/xonsh/xonsh/issues/2618#issue-316610134

**Comment by scopatz** [comment]
Let us know if there is anything specific we can do

**Comment by t184256** [comment]
I am very sorry, I don't know how to put it into a specific request. Honestly, I want `sudo` to expand aliases in a way that "Just Works" (tm).

Currently my version hangs hard on my example, while your version hangs on any interactive command, alias or not, displaying a lone `^Z`.

Is anything I can do to provide more info on this? Could you fix my version? What do others use?

**Comment by scopatz** [comment]
Yeah, I am honstely pretty confused about what is going on here

**Comment by t184256** [comment]
Does 0.8.10 alias work bring anything new to the table?

**Comment by scopatz** [comment]
It probably does, but I haven't had a chance to look at this issue specifically.

**Comment by anki-code** [comment]
I've added feature label because I think the expanding aliases for sudo is a good feature. For example it allows to reduce these lines in xpip implementation that require special logic [in case with AppImage](https://github.com/xonsh/xonsh/issues/4069):

https://github.com/xonsh/xonsh/blob/8ad8b043e8f7c55634dcfcf5ff1bace2f8d872eb/xonsh/aliases.py#L771-L772

**Comment by anki-code** [comment]
I've taken a short look into this. 

1. At this time the alias resolving is working only for the first argument. And in xonsh the command `bash ls` (where `ls` is alias `ls --color`) is working like in bash (without resolving) i.e `bash ls` is `bash ls` instead of `bash ls --color`.

2. I've also tried ExecAlias to solve this but without success (with #4201):

```python
aliases['sudo'] = '/usr/bin/env sudo @(aliases.eval_alias($ALIAS_ARGS))'    # ExecAlias
sudo ls | less
# no response
```

3. The start point to research is here:

https://github.com/xonsh/xonsh/blob/7168b262ae35d0ee97a7c2970742d73f494e61c4/xonsh/procs/specs.py#L589-L596

It looks like we should have a feature to resolve the second argument in certain commands like `sudo`. OR the best way is [to working on threading and piping](https://github.com/xonsh/xonsh/issues/2159).

**Comment by anki-code** [comment]
I tried to solve this issue by manipulating with predictors.

This alias is working with piping into capturable tools like `grep`:
```python
from xonsh.commands_cache import predict_false, predict_true

def sudo_expanding_aliases(cmd, stdin=None, stdout=None, stderr=None):
    curr_sudo_predictor = __xonsh__.commands_cache.threadable_predictors['sudo']
    try:
        __xonsh__.commands_cache.threadable_predictors['sudo'] = predict_true
        if r := ![sudo echo -n]:  # to get password prompt in uncapturable mode
            if __xonsh__.commands_cache.predict_threadable(cmd):
                __xonsh__.commands_cache.threadable_predictors['sudo'] = predict_true
                p = !(sudo @(aliases.eval_alias(cmd)))
                p.end()
                for line in p:
                    stdout.write(line)
                if p.errors:
                    for line in p.errors.splitlines():
                        stderr.write(line + '\n')
                __xonsh__.commands_cache.threadable_predictors['sudo'] = curr_sudo_predictor
                return p.returncode
            else:
                __xonsh__.commands_cache.threadable_predictors['sudo'] = predict_false
                r = ![sudo @(aliases.eval_alias(cmd))]
                __xonsh__.commands_cache.threadable_predictors['sudo'] = curr_sudo_predictor
                return r.rtn
    finally:
        __xonsh__.commands_cache.threadable_predictors['sudo'] = curr_sudo_predictor

aliases['sudo'] = sudo_expanding_aliases
del sudo_expanding_aliases

sudo ls / | grep bin
```
But this alias is not working with uncapturable tools like `less`. This is the common alias issue described in #4277.
