### ISSUE TITLE
__amalgam__.py deprecation warnings with shell commands

### ISSUE THREAD

**Issue by dotsdl** [xonsh/xonsh#2894]
Running a shell command, such as `clear`, yields:

    /usr/lib/python3.7/site-packages/xonsh/__amalgam__.py:21828: DeprecationWarning: __xonsh_env__ has been deprecated, please use __xonsh__.env instead.
  DeprecationWarning,

## xonfig

```
+------------------+-----------------+
| xonsh            | 0.8.1           |
| Python           | 3.7.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.4           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | antergos        |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

I don't expect to see warnings like this, but I'm not knowledgeable on how `__amalgam__.py` is constructed.

**Comment by laloch** [comment]
It's most probably unrelated to [amalgamate](https://github.com/xonsh/amalgamate) or xonsh by itself. I would rather say that the deprecated `__xonsh_env__` is used by some of the external extensions (xontribs) you use. You may easily confirm my assumption by commenting out `xontrib load` line in your `~/.xonshrc` file.

**Comment by flaper87** [comment]
Try updating `xontrib-z` to 0.4, that fixed it for me

**Comment by dotsdl** [comment]
Closing, as I found the culprit to be `vox_tabcomplete`. Thanks all!
