### ISSUE TITLE
Website tutorial.html is blank

### ISSUE THREAD

**Issue by alekratz** [xonsh/xonsh#2896]
## Expected Behavior
Tutorial page appears.

## Current Behavior
Empty page appears.

## Steps to Reproduce
1. Go to http://xonsh.org/tutorial.html in browser
2. :cry:

**Comment by gforsyth** [comment]
Hey @alekratz, sorry about that. We don't control xonsh.org and can't seem to get it taken down.

You can find the tutorial page here: https://xon.sh/tutorial.html

**Comment by alekratz** [comment]
Huh, well there you go. Thanks for quick update.
