### ISSUE TITLE
no attribute 'settitle' error when using xonsh inside a vim terminal

### ISSUE THREAD

**Issue by joetoth** [xonsh/xonsh#2899]
Recently been trying out the vim terminal instead of tmux for managing multiple terminals. Works great, though there seems to be an issue with Xonsh.

It seems like when I have the following in my .xonshrc I get the following error.

if os.path.isfile($WORK_XSH):
  source $WORK_XSH
$(/usr/games/fortune)

xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
AttributeError: 'NoneType' object has no attribute 'shell'
error running xonsh run control file /home/joetoth/.xonshrc': 'NoneType' object has no attribute 'shell'

xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 17806, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 2548, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 2453, in run_compiled_code
    func(code, glb, loc)
  File "/home/joetoth/.xonshrc", line 123, in <module>
    $(/usr/games/fortune)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 21287, in subproc_captured_stdout
    return run_subproc(cmds, captured="stdout")
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 21271, in run_subproc
    command.end()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 13879, in end
    self._return_terminal()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 13912, in _return_terminal
    builtins.__xonsh__.shell.shell.restore_tty_sanity()
AttributeError: 'NoneType' object has no attribute 'shell'
error running xonsh run control file '/home/joetoth/.xonshrc': 'NoneType' object has no attribute 'shell'

## xonfig
+------------------+----------------------+
| xonsh            | 0.8.1                |
| Git SHA          | fe2a1c32             |
| Commit Date      | Sep 23 10:10:21 2018 |
| Python           | 3.5.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.6                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Debian               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

## Steps to Reproduce
I think if you add an executable or source another file from your .xonshrc then open up vim and create a :term you should get the error.

Let me know if there is anything else I can do.

Thanks!

**Comment by laloch** [comment]
The same happens in screen and tmux.
