### ISSUE TITLE
Where to load xontribs and the rc/profile files

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#2901]
I want to load the vox xontrib by default. What is the best place to do so? The `.xonshrc` file?

Speaking of the `.xonshrc` file: Is there a `.xonsh_profile` file as well?

**Comment by gforsyth** [comment]
Hey @halloleo -- great questions!

You should do the `xontrib load vox` in your `xonshrc` file if you want it to autoload.  There is not a `.xonsh_profile` file -- for non-interactive shells there is currently no configuration file (although you can force interactive mode with the `-i` flag)

**Comment by halloleo** [comment]
Thanks for the info. Makes sense.
