### ISSUE TITLE
boto3 is unable to find the relevant AWS_* variables

### ISSUE THREAD

**Issue by BrianGallew** [xonsh/xonsh#2903]
## xonfig
+------------------+----------------------+
| xonsh            | 0.7.8                |
| Git SHA          | ecca7a7c             |
| Commit Date      | Sep 11 13:48:32 2018 |
| Python           | 3.6.5                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.13               |
| shell type       | prompt_toolkit1      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

## Expected Behavior
boto3.client('ec2') in an internally created function (i.e. something in my .xonshrc) should be able to find its credentials.

## Current Behavior
When using a function (see below) inside xonsh that uses boto3 to work with AWS, it doesn't see the relevant environment variables (e.g. AWS_PROFILE or AWS_SESSION_TOKEN).

If I put the boto3 code into a separate python program and run it, it find the credentials just fine.  It feels like a caching issue, but I'm not sure.

## Steps to Reproduce
have a functional [dev] section in your ~/.aws/credentials
source example.xsh (see below)

```
import boto3
import os
from importlib import reload
from pprint import pprint

$XONSH_SHOW_TRACEBACK = False
$UPDATE_OS_ENVIRON = True


class DegradationTester:
    aws_groupings = {
        'dev': ['us-east-1', 'us-east-2', 'us-west-1', 'us-west-2'],
        'prod': ['us-west-1', 'us-west-2', 'us-east-1'],
        'owl': ['us-west-1', 'us-west-2', 'us-east-1'],
        'govcloud': ['us-gov-west-1'],
    }

    def __init__(self, debug=False):
        self.client = None
        self.debug = debug

    def log(self, msg):
        if self.debug:
            print(msg)

    def display_some_responses(self, results):
        for result in results:
            instance = None
            for event in [x for x in result['Events'] if 'Completed' not in x['Description']]:
                if instance is None:
                    instance_thing = self.client.describe_instances(InstanceIds=[result["InstanceId"]])
                    instance = instance_thing['Reservations'][0]['Instances'][0]
                    try:
                        instance_name = [x['Value'] for x in instance['Tags'] if x['Key'] == 'Name'][0]
                    except:
                        instance_name = '(no name tag)'
                print(f'{result["AvailabilityZone"]} {instance_name} {result["InstanceId"]} {event["NotBefore"]} {event["Description"]}')

    def find_degraded(self):

        for region in self.aws_groupings[os.environ['AWS_PROFILE']]:
            self.log(f"Working on {os.environ['AWS_PROFILE']} in {region}")
            boto3 = reload(boto3)
            self.client = boto3.client('ec2', region_name=region)
            page_token = ''
            while True:
                response = self.client.describe_instance_status(
                    Filters=[{'Name': 'event.code',
                              'Values': [
                                  'instance-reboot', 'system-reboot', 'system-maintenance',
                                  'instance-retirement', 'instance-stop',
                              ]
                              }],
                    NextToken=page_token)
                self.display_some_responses(response['InstanceStatuses'], client)
                page_token = response['NextToken'] if 'NextToken' in response else ''
                if not page_token:
                    break


$AWS_PROFILE='dev'
a = DegradationTester(True)
a.find_degraded()
```

**Comment by gforsyth** [comment]
Thanks for reporting @BrianGallew!  I suspect that this is a caching issue as you pointed out. 
`boto3` looks for credentials related environment variables at import time and creates a "default session" that everything runs in unless otherwise specified.  You are setting those credentials in the same Python/xonsh session after `boto3` is imported and so the session doesn't include them (I think).

I'm not sure if there's a way to make it behave the way you want with a straight `client` call, however, if you instead pass the profile to a `Session` call that should work.  

So you could change

```python
self.client = boto3.client('ec2', region_name=region)
```

to

```python
self.client = boto3.Session(profile_name='dev').client('ec2', region_name=region)
```

and that should work.

**Comment by melund** [comment]
Hi @BrianGallew

You could also try to set  `$update-os-environ=True` and see if that helps 

https://xon.sh/envvars.html#update-os-environ

**Comment by BrianGallew** [comment]
`$UPDATE_OS_ENVIRON = True` is set in the example script, and doesn't help.  However, a gforsyth pointed out, using boto3.Session works around the problem beautifully.  Thanks!
