### ISSUE TITLE
How to file glob in Python mode

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#2906]
I try to translate the following bash line to xonsh:

    for f in *.jpg: do echo "images file" $f; done

Is there a way to file-glob in Python mode?

**Comment by Ohjeah** [comment]
```python
for file in g`*.jpg`:
    print(f"images file {file}")
```

See also the [wiki](https://github.com/xonsh/xonsh/wiki/Cheatsheet#globbing)

**Comment by melund** [comment]
And if you want the `echo` command as well: 
```py
for f in g`*.jpg`:
    echo "images file" @(f)
```

**Comment by halloleo** [comment]
Cool! I didn't know about the `g` modifier. Thanks a lot!
