### ISSUE TITLE
Have shell that uses pyreadline backend.

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#291]
This could be a nice alternative to readline in the standard library, but probably worse than prompt-toolkit :)

https://github.com/pyreadline/pyreadline

**Comment by rbrewer123** [comment]
We're currently using pyreadline by default on Windows and it works well.  So I would imagine it will be straightforward to use it by default on other platforms too.

**Comment by scopatz** [comment]
Cool :) Good to know.

**Comment by scopatz** [comment]
pyreadline is no longer actively developed and most of the need here has been supplanted by prompt-toolkit.  I think we'd still be interested in a backend, if it came along. However, I will close this for the time being.

**Comment by laerus** [comment]
maybe we should at some point write our own
