### ISSUE TITLE
Alias for cat in xonsh

### ISSUE THREAD

**Issue by meatballs** [xonsh/xonsh#2913]
I've switched to using https://github.com/sharkdp/bat as a replacement for `cat`

However, when I try to create an alias, it doesn't have any effect. I'm guessing this is something to do with the fact that `cat` is a xonsh specific version.

Is there any way I can get around this?

**Comment by meatballs** [comment]
oh good grief. I just had a stupid typo in there that I couldn't see. I shall go and beat myself around the head with a blunt instrument.

**Comment by gforsyth** [comment]
No worries! And thanks for the pointer to `bat`!
