### ISSUE TITLE
How to use module environment management with xonsh?

### ISSUE THREAD

**Issue by szsdk** [xonsh/xonsh#2926]
## xonfig
```
| xonsh            | 0.8.2           |
| Python           | 3.7.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.4           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
```

## Current Behavior
I am tring to use xonsh with module environment management which is the default tool to set up the environment in our clusters. I come up a rc file to add the module command
```
$MODULEPATH.append("~/Modules")
def _module(args, stdin=None):
    modulecmd @('zsh') @(' '.join(args))
aliases['module'] = _module
module load anaconda3
```
However, it does not work. I get a bunch of information when I start the xonsh.
```
_LMFILES__modshare=/home/sz/Modules/anaconda3:1; export _LMFILES__modshare;
LOADEDMODULES_modshare=anaconda3:1; export LOADEDMODULES_modshare;
PYTHONPATH_modshare=/home/sz/miniconda3/lib/python3.7/site-packages:1; export PYTHONPATH_modshare;
PATH=/home/sz/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/opt/mpich/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl; export PATH;
_LMFILES_=/home/sz/Modules/anaconda3; export _LMFILES_;
LOADEDMODULES=anaconda3; export LOADEDMODULES;
PYTHONPATH=/home/sz/miniconda3/lib/python3.7/site-packages; export PYTHONPATH;
PATH_modshare=/home/sz/miniconda3/bin:1:/usr/bin/vendor_perl:1:/usr/bin:1:/usr/local/sbin:1:/opt/cuda/bin:1:/opt/mpich/bin:1:/usr/local/bin:1:/usr/lib/jvm/default/bin:1:/usr/bin/site_perl:1:/usr/bin/core_perl:1; export PATH_modshare;
test 0;
```

Is this because of that xonsh and bash mange environment in a different way? Or I did not do it correctly.

**Comment by halloleo** [comment]
Not sure if I understand your code correctly, but `modulecmd ` seems to be a Python package, object or function. 

To call it use the Python syntax. Like if it is a function `modulecmd (arguments...)`. In your code `modulecmd` is parsed in [subprocess mode](https://xon.sh/tutorial.html#python-mode-vs-subprocess-mode). 

HTH...

**Comment by melund** [comment]
@szsdk I don't know what `modulecmd` is. But if it is a command, then the line: `modulecmd @('zsh') @(' '.join(args))` seems incorrect. It would basically parse the the arguments as a single argument. Something like `modulecmd zsh "load anaconda"`

It should probably just look like this: `modulecmd zsh @(args)`

**Comment by szsdk** [comment]
@halloleo  @melund  The `modulecmd` comes from http://modules.sourceforge.net/index.html which is a very useful tool.

**Comment by gforsyth** [comment]
It looks like the tool does various `$PATH` hacking based on the contents of various `module` files. 
My guess is that someone will have to write a xonsh layer for this and submit it upstream to really get it working. (Or we can reimplement the meat of it as a xontrib). Might also be worth running the command via `source-bash` and seeing if that works.

Also dropping a link here pointing to their python shim (for reference) https://github.com/cea-hpc/modules/blob/master/init/python.py.in

**Comment by scopatz** [comment]
I agree with @melund that it looks like it should be `modulecmd zsh @(args)`

**Comment by anki-code** [comment]
Looks as solved or not actual question and should be closed.
