### ISSUE TITLE
Executing xonsh in xonsh results in AttributeError

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#2928]
When I'm executing `xonsh` in a running xonsh shell and I load the `vox` xontrib in the `.xonshrc` I get a strange error:

    xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
    Traceback (most recent call last):
      File "/working/software/venv/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 1300, in xonsh_script_run_control
        run_script_with_cache(filename, execer, ctx)
      File "/working/software/venv/xonsh/lib/python3.6/site-packages/xonsh/codecache.py", line 162, in run_script_with_cache
        run_compiled_code(ccode, glb, loc, mode)
      File "/working/software/venv/xonsh/lib/python3.6/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
        func(code, glb, loc)
      File "/home/halloleo/.xonshrc", line 3, in <module>
        xontrib load vox 
      File "/working/software/venv/xonsh/lib/python3.6/site-packages/xonsh/built_ins.py", line 952, in subproc_captured_hiddenobject
        return run_subproc(cmds, captured="hiddenobject")
      File "/working/software/venv/xonsh/lib/python3.6/site-packages/xonsh/built_ins.py", line 904, in run_subproc
        pause_call_resume(proc, builtins.__xonsh__.shell.settitle)
    AttributeError: 'NoneType' object has no attribute 'settitle'
    error running xonsh run control file '/home/halloleo/.xonshrc': 'NoneType' object has no attribute 'settitle'

The `.xonshrc` file to make this bug happen is:

    $XONSH_SHOW_TRACEBACK = True
    $SHELL_TYPE='readline'
    xontrib load vox 

My `xonfig` output is:

    +------------------+---------------------------------+
    | xonsh            | 0.8.1                           |
    | Git SHA          | 23246604                        |
    | Commit Date      | Oct 18 09:55:19 2018            |
    | Python           | 3.6.4                           |
    | PLY              | 3.9                             |
    | have readline    | True                            |
    | prompt toolkit   | 2.0.7                           |
    | shell type       | readline                        |
    | pygments         | None                            |
    | on posix         | True                            |
    | on linux         | True                            |
    | distro           | Red Hat Enterprise Linux Server |
    | on darwin        | False                           |
    | on windows       | False                           |
    | on cygwin        | False                           |
    | on msys2         | False                           |
    | is superuser     | False                           |
    | default encoding | utf-8                           |
    | xonsh encoding   | utf-8                           |
    | encoding errors  | surrogateescape                 |
    +------------------+---------------------------------+

Also, how can I better debug an error like this? `$XONSH_DEBUG=3` doesn't seem to give more details about the exception (but rather about the parsing of the input line).

**Comment by melund** [comment]
Thanks for reporting  @halloleo. I think this may have been fixed in 0.8.2 by this PR #2886. Do you mind updating a check if it is still a problem?

**Comment by halloleo** [comment]
That's it. Updating to 0.8.2 overcomes the problem!

Speaking of updating. I did so **in** xonsh by issuing: 

    python -m pip install -U xonsh

(This should work at least if xonsh is installed in its own virtual environment.)

Is it worth to put the update process somewhere in the documentation?

**Comment by gforsyth** [comment]
Hey @halloleo -- glad the issue is resolved!  And documentation improvements are always welcome!

One tweak I would suggest -- we create an `xpip` alias that always points to the version of `pip` corresponding to the python installation where `xonsh` is installed, so it would be better to point people in that direction, so something like

```
xpip install -U xonsh
```

**Comment by scopatz** [comment]
Also! Good news everyone: https://github.com/pypa/virtualenv/pull/1206

**Comment by halloleo** [comment]
@gforsyth `xpip` is cool! Will put this in the doco.
