### ISSUE TITLE
TypeError when piping into lambda function 

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#2933]
Create a text file `file.txt` with at least two lines. 

Then define a callable:

    fx = lambda args, stdin: [ $[echo @(l.strip())] for l in stdin ]

Finally issue the pipe:

    cat file.txt | @(fx)

## Current Behavior

The output contains only the first line, then it stops with the error "TypeError: an integer is required (got type NoneType)".

## Expected Behavior

I expected both lines from the input file be printed.

## Note

This issue comes from the StackOverflow question [In xonsh how can I receive from a pipe to a python expression?](https://stackoverflow.com/questions/53119083/in-xonsh-how-can-i-receive-from-a-pipe-to-a-python-expression/53141977?noredirect=1#comment93320525_53141977)
    
## xonfig

    +------------------+---------------------------------+
    | xonsh            | 0.8.3                           |
    | Git SHA          | 07eb341c                        |
    | Commit Date      | Nov 6 07:39:16 2018             |
    | Python           | 3.6.4                           |
    | PLY              | 3.11                            |
    | have readline    | True                            |
    | prompt toolkit   | 2.0.7                           |
    | shell type       | readline                        |
    | pygments         | None                            |
    | on posix         | True                            |
    | on linux         | True                            |
    | distro           | Red Hat Enterprise Linux Server |
    | on darwin        | False                           |
    | on windows       | False                           |
    | on cygwin        | False                           |
    | on msys2         | False                           |
    | is superuser     | False                           |
    | default encoding | utf-8                           |
    | xonsh encoding   | utf-8                           |
    | encoding errors  | surrogateescape                 |
    +------------------+---------------------------------+

**Comment by scopatz** [comment]
Something like 

```python
fx = lambda args, stdin: max([![echo @(l.strip())].returncode for l in stdin ])
```

is a better example, because the lambda adheres to the specification for callable aliases: https://xon.sh/tutorial.html#callable-aliases

**Comment by scopatz** [comment]
Thanks for bringing this up @halloleo  and let us know if you have any questions!

**Comment by anki-code** [comment]
This works for me:
```python
echo -e "1\n2\n3" > file.txt
fx = lambda args, stdin: max([![echo @(l.strip())].returncode for l in stdin ])
cat file.txt | @(fx)
# 1
# 2
# 3
```

**Comment by halloleo** [comment]
@anki-code Thanks for looking at this.

Your example is not like mine though. I tyeped `$[]` and when using that I get even in recent versions of xonsh "_TypeError: an integer is required (got type NoneType)_". Looks neither right nor understandable to me.

`$[]`  is a normal xonsh construct. I reckon this issue should stay open.

**Comment by anki-code** [comment]
This example was written by scopatz above and you can use it as workaround.

Also I've created #4281 with the minimal example to repeat the error.

**Comment by halloleo** [comment]
Yep, #4281 is the same issue. Thanks.
