### ISSUE TITLE
Feature Request: control $COLOR_RESULTS from pretty()

### ISSUE THREAD

**Issue by philopon** [xonsh/xonsh#2939]
Xonsh calls `_repr_pretty_` or `xonsh_display` when output.
I want to display inline image on iterm2 by using `_repr_pretty_`. However, outputs of _repr_pretty_ are always pygmentized when `$COLOR_RESULTS == True`. Thus, inline image cannot display when `$COLOR_RESULTS == True`.

I want the API to disable $COLOR_RESULTS in `_repr_pretty_` (or other API).

### pseudo API

```.py
class Obj:
    def _repr_pretty_(self, p, cycle):
        p.color_results = False  # disable $COLOR_RESULTS in this output
        p.text(self_to_image_bytes(self))
```

## xonfig

```
+------------------+-----------------+
| xonsh            | 0.8.3           |
| Python           | 3.7.1           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.7           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

```.py
class Obj:
    def _repr_pretty_(self, p, cycle):
        p.text(self_to_image_bytes(self))
```

```
$ $COLOR_RESULTS
False
$ Obj()
# display image

$ $COLOR_RESULTS = True
$ Obj()
# display image
````

## Current Behavior

```
$ $COLOR_RESULTS
False
$ Obj()
# display image

$ $COLOR_RESULTS = True
$ Obj()
?]1337;File=name=VW5uYW1lZ……
````

**Comment by scopatz** [comment]
Hi @philopon - thanks for bringing this up! (And sorry for the slow response.)  This would be a great feature to have! In particular it would be great to have iterm2 support more broadly even, although something like this would be great too.

Pull requests very welcome here.

**Comment by anki-code** [comment]
I'm going to close this issue because of time, no new requests or thumbs ups and lack of full repeatable examples (i.e. the code for display the image).

Meanwhile the start point could be here:

https://github.com/xonsh/xonsh/blob/27db574d99ab1be1d0435ca9e298830c0f2aba66/xonsh/main.py#L261-L266
