### ISSUE TITLE
conda shows too many significant figures when downloading packages

### ISSUE THREAD

**Issue by hmaarrfk** [xonsh/xonsh#2941]
## xonfig
```bash
$ xonfig                                                                        
+------------------+-----------------+
| xonsh            | 0.8.3           |
| Python           | 3.7.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.7           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior
Did anybody notice that there are too many digits being displayed when conda is downloading packages?

Seems like something that didn't used to happen when I was using bash. It makes it really difficult to use even modest sized terminal windows.

My internet is slow, but it does the hashtag/pound sign progress bar on bash`#########123456789`
with bash
![image](https://user-images.githubusercontent.com/90008/48557589-84c1ed00-e92a-11e8-9ac1-f7470ea1b49c.png)

## Current Behavior

With xonda + xonsh

![image](https://user-images.githubusercontent.com/90008/48557396-f9e0f280-e929-11e8-87bb-9d0965165916.png)

## Steps to Reproduce
download something with conda.

xref: https://github.com/gforsyth/xonda/issues/42
cc: @gforsyth

**Comment by scopatz** [comment]
I see this behavior too.  This makes me think it is a tqdm or conda problem, where they do something different if they don't detect Bash.

**Comment by hmaarrfk** [comment]
It could be that they have an older vendored version of tqdm.

```
        if json:
            pass
        elif enabled:
            bar_format = "{desc}{bar} | {percentage:3.0f}% "
            try:
                self.pbar = tqdm(desc=description, bar_format=bar_format, ascii=True, total=1)
            except EnvironmentError as e:
                if e.errno in (EPIPE, ESHUTDOWN):
                    self.enabled = False
                else:
                    raise
```
this is their code, pretty straightforward. No special bash detection.

**Comment by scopatz** [comment]
They do: https://github.com/conda/conda/tree/master/conda/_vendor/tqdm

**Comment by anki-code** [comment]
Looks not actual and should be closed.
