### ISSUE TITLE
`xonsh.__env__` and `env` subproc command precedence issue

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#2943]
If you use `env` to set a temporary env var for a one-line command, that works as expected
```
 ~ 🐚  env BAI="HAI" bash -c "echo $BAI"
"HAI"
```
and `$BAI` isn't available in the current session after the command completes
```
 ~ 🐚  $BAI
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'Unknown environment variable: $BAI'
```

But if `$BAI` is set already and then `env` is used, the value in `__xonsh__.env` overrides the temporary value:
```
 ~ 🐚  $BAI="BYE"
 ~ 🐚  env BAI="HAI" bash -c "echo $BAI"
BYE
```

## xonfig

```
+------------------+---------------------+
| xonsh            | 0.8.3               |
| Git SHA          | 07eb341c            |
| Commit Date      | Nov 6 07:39:16 2018 |
| Python           | 3.6.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.6               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```
## Expected Behavior

```
 ~ 🐚  $BAI="BYE"
 ~ 🐚  env BAI="HAI" bash -c "echo $BAI"
HAI
```

**Comment by laloch** [comment]
Have you found where the expansion takes place? I already wanted to change the behavior once to not expand the `DOLLARNAME` token within `r""` raw strings. Funnily enough, I wasn't even able to find out where exactly the `DOLLARNAME` is being expanded in this particular case.

**Comment by gforsyth** [comment]
Hey @laloch -- which expansion are you referring to?

**Comment by laloch** [comment]
Well, usual environment variable ID references (aka dollar names) get lexed [here](https://github.com/xonsh/xonsh/blob/e9866478b4a306dab78dce84fbe075186cef13c0/xonsh/tokenize.py#L1013-L1014) into the `DOLLARNAME` token which is later parsed [here](https://github.com/xonsh/xonsh/blob/e9866478b4a306dab78dce84fbe075186cef13c0/xonsh/parsers/base.py#L2358-L2360). That does not, however, apply to "DOLLARNAMEs" embedded in single/double/triple quoted strings. IIRC I looked also at several other places within the parser where some kind of environment substitution takes place, but I just could not find the place where quoted environment variable IDs get expanded.

**Comment by scopatz** [comment]
Thanks for opening this @gforsyth! @laloch is right that the env var expansion happens in/by xonsh **before** running the subprocess. Since the subprocess here is `env`, which is an alias and could do literally anything (or nothing), xonsh has no way (currently) of predicting what the intended value for the env var is.  Note that bash has this problem too:

```bash
scopatz@artemis:~$ env BAI="HAI" bash -c "echo $BAI"

scopatz@artemis:~$ export BAI="BYE"
scopatz@artemis:~$ env BAI="HAI" bash -c "echo $BAI"
BYE
```

This is actually a perfect illustration of the use case where `env VAR=VALUE cmd` does not necessarily equal the results of `VAR=VALUE cmd`.  Bash still fails in this case, but we could parse out the env vars and then expand them in the context of just the command.  It is probably time to implement this long-awaited feature :)

**Comment by scopatz** [comment]
Quoted values IIRC are expanded by calls to `__xonsh__.expand_path()`

**Comment by laloch** [comment]
@scopatz : You're not right about the issue to be present in bash - in bash you can use single quotes to prevent the expansion:
```
$ export BAI="BYE"
$ env BAI="HAI" bash -c 'echo $BAI'
HAI
```
