### ISSUE TITLE
Exception on startup (pygments_cache)

### ISSUE THREAD

**Issue by dugres** [xonsh/xonsh#2944]

**Comment by dugres** [comment]
I ran into the issue #2692 (which has been closed) on Fedora 29 with Xonsh 0.8.3
I don't have the problem on Manjaro nor on Ubuntu.

**Comment by matheus2740** [comment]
@dugres 

There was a reversion.
Manually opening "PATH/TO/PYTHON/site-packages/xonsh/ptk2/__init__.py"
and commenting averything in the file fixed it for me. (I basically read what was in the PR that solved the issue previously and looked at what was done).

**Comment by dugres** [comment]
@matheus2740 

That worked for me too. Thanks

That brings up 2 questions though:
 - Why #2692 hasn't been merged ?
 - Why the issue only appears on Fedora ?
