### ISSUE TITLE
Why do cat FILE and ls DIR behave differently in !(...)?

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#2946]
Why do `cat FILE` and `ls DIR` behave differently in `!(...)`?

## Expected Behavior
`!(cat FILE-LISTING_OF_DIR)` and `!(ls -1 DIR)` behave the same in Python mode giving a list of file names to iterate over.

## Current Behavior

`!(cat FILE-LISTING_OF_DIR)` works, `!(ls -1 DIR)` doesn't. Details in the next section:

## Steps to Reproduce

If I do 

    $ ls -1 $VIRTUALENV_HOME > ~/tmp/venvs.txt
    $ venvs = [ d for d in map(str.strip, !(cat ~/tmp/venvs.txt)) if Path(d).is_dir ]

I get - as expected - in `venvs` a Python list of all VENV directories

However, if I issue in one go

    $ venvs = [ d for d in map(str.strip, !(ls -1 $VIRTUALENV_HOME)) if Path(d).is_dir ]

I get the venvs listed on stdout and the variable `venvs` is empty.

Why on earth does this happen? And can that be right?

## xonfig

    +------------------+---------------------+
    | xonsh            | 0.8.3               |
    | Git SHA          | 07eb341c            |
    | Commit Date      | Nov 6 07:39:16 2018 |
    | Python           | 3.7.0               |
    | PLY              | 3.11                |
    | have readline    | True                |
    | prompt toolkit   | 2.0.4               |
    | shell type       | readline            |
    | pygments         | 2.2.0               |
    | on posix         | True                |
    | on linux         | False               |
    | on darwin        | True                |
    | on windows       | False               |
    | on cygwin        | False               |
    | on msys2         | False               |
    | is superuser     | False               |
    | default encoding | utf-8               |
    | xonsh encoding   | utf-8               |
    | encoding errors  | surrogateescape     |
    +------------------+---------------------+

**Comment by gforsyth** [comment]
Ok, so I'm also on OSX and in trying to figure this one out, discovered that `ls` on OSX relies on `ncurses` for no reason that I'm aware of.  But that's what is causing it to be flagged as unthreadable because usually `ncurses` based applications are interactive and don't play nice with output capture.

So, two options:
1. My quick fix above
2. install the `coreutils` package using `brew` and then alias `gls` for `ls`

**Comment by halloleo** [comment]
Super thanks for the details. I guess I should dive a bit more in the internals of xonsh. :-)

I will check on Centos/RHEL as well what `ls` is doing and report back here.

**Comment by halloleo** [comment]
I can confirm: On Centos/RHEL 6 it works in both cases. (Centos has `ls` from the `coreutils` installed.) So the fix is only needed on macOS

**Comment by gforsyth** [comment]
Great.  Thanks for following up @halloleo!  so the fix is to add `ls` as a `predict_true` in the default threadable predictors list in `command_cache.py`

**Comment by scopatz** [comment]
@halloleo @gforsyth - any chance we can get a PR for this? Thanks!

**Comment by halloleo** [comment]
So does this mean that with the new build  we don't need on macOS `__xonsh__.commands_cache.threadable_predictors['ls'] = predict_true` in our .xonshrc anymore?

**Comment by gforsyth** [comment]
Hey @halloleo, yes, that's right.
