### ISSUE TITLE
xonsh tutorial doesnt load as linked from landing page

### ISSUE THREAD

**Issue by paulkarayan** [xonsh/xonsh#2953]
i'm using chrome - latest version.

![image](https://user-images.githubusercontent.com/1227327/49533210-48234a80-f873-11e8-8451-020f4bb2e8e0.png)

will send screen cap if desired.

**Comment by gforsyth** [comment]
xonsh.org was taken over by an unknown third party a few years ago -- you can find up-to-date docs on https://xon.sh

**Comment by scopatz** [comment]
@laloch - how do we take it back over once that date arrives?

**Comment by anki-code** [comment]
Not actual now. Should be closed.
