### ISSUE TITLE
No exception raised when using cd to change dir to a non existent directory 

### ISSUE THREAD

**Issue by dwjbosman** [xonsh/xonsh#2962]
I have this xonsh script:

```
$RAISE_SUBPROC_ERROR = True

try:
    cd blaat

    r = !(cd blaat)
    print(r.returncode)

    r = !(cd /home)
    print(r.returncode)


except:
    print("cd failed")

```

The folder 'blaat' does not exist so it should print "cd failed". However the output is:

> cd: no such file or directory: blaat
> cd: no such file or directory: blaat
> 1
> 0

## xonfig
+------------------+---------------------+
| xonsh            | 0.8.4               |
| Git SHA          | 8405b8dd            |
| Commit Date      | Dec 7 10:39:36 2018 |
| Python           | 3.6.2               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 1.0.15              |
| shell type       | prompt_toolkit1     |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+

**Comment by scopatz** [comment]
Thanks for reporting! This should be an easy fix!
