### ISSUE TITLE
history show freezes

### ISSUE THREAD

**Issue by ndemou** [xonsh/xonsh#2965]
After upgrading to 0.8.4 the command `history show all|grep foo` became unresponsive. Ctrl-C had no effect. This happened twice in two days.

`strace`ing the unresponsive xonsh process showed this `futex(0x7f0a9c000c10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff`

**Comment by scopatz** [comment]
Thanks for reporting @ndemou! Does this happen all the time? Or just sometimes?  Also, can you please post the results of `xonfig`? Thanks!

**Comment by ndemou** [comment]
No it's that ugly kind of bug that appear apparently randomly. I had more problems with 0.8.4 (reported elsewere) and I'm back to 0.8.2 for now
```
+------------------+----------------------+
| xonsh            | 0.8.2                |
| Git SHA          | 78b13924             |
| Commit Date      | Oct 29 14:16:50 2018 |
| Python           | 3.5.2                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | prompt_toolkit1      |
| pygments         | 2.3.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by scopatz** [comment]
Hmm Ok.  I noticed that you are on prompt-toolkit v1.  Any way I can convince you to upgrade to prompt-toolkit v2?

**Comment by sagartewari01** [comment]
@ndemou Can you try out #3000 and see if it fixes the issue you're facing?

**Comment by ndemou** [comment]
I noticed that scopatz was strongly in favor of switching to prompt-toolkit v2. Do you know how to accomplish it*? 

----
*: pip install -U ptk is not doing it and the [official documentation](https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading.html) has nothing useful (_"More guidelines on how to upgrade will follow"_)

**Comment by gforsyth** [comment]
Should just be a `pip install -U prompt_toolkit` to get the latest version

**Comment by ndemou** [comment]
Thanks gforsyth, unfortunately it conflicts with some part of jupyter so I'm staying at ptk v1 for the moment. 
The day that I'll have to spend some time to figure out virtual environments is getting closer.

**Comment by scopatz** [comment]
@ndemou - the part of Jupyter it conflicted with IIRC is IPython, but that conflict has been removed because IPython also upgraded to PTK2.  Maybe try upgrading IPython first, then xonsh.

**Comment by scopatz** [comment]
Or rather, then PTK

**Comment by scopatz** [comment]
Also, 

> 0.8.2 because 0.8.4 is painfully slow

Would it be possible for you to do a `git bisect` between these two and figure out the commit where it becomes painfully slow? That would help us a lot!

**Comment by ndemou** [comment]
Thanks scopatz! I'm on prompt_toolkit v2 now. 
It's worth noting that after a few hours with patch #3000 and ptk v1 I had not experienced the history freeze. Continuing with ptk v2.

**Comment by scopatz** [comment]
Awesome! It is OK to close this then?

**Comment by ndemou** [comment]
It's been 2 days without an issue :-)

**Comment by scopatz** [comment]
Excellent!

**Comment by ndemou** [comment]
:-) Just a quick note to let you know that everything is still OK after so many days

**Comment by scopatz** [comment]
Great!
