### ISSUE TITLE
vox creates venv without pip

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#2974]
## Summary

vox creates venvs without `pip` executable, even if *not* asked for this via command line option.

## xonfig

```
+------------------+----------------------+
| xonsh            | 0.8.5                |
| Git SHA          | c075bb51             |
| Commit Date      | Dec 18 18:24:43 2018 |
| Python           | 3.7.0                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.7                |
| shell type       | dumb                 |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

## Expected Behavior
When issuing

    vox create myvenv

I expected a venv with a `pip` executable in `myvenv/bin/pip`.

## Current Behavior
When issuing

    vox create myvenv

the new venv does not contain `pip`.

**Comment by scopatz** [comment]
Thanks for reporting @halloleo! PRs welcome!

**Comment by halloleo** [comment]
Will try to look into this soon.

**Comment by halloleo** [comment]
As it turns out the problem is related to the way xonsh is instantiated when xonsh is installed into a virtual environment itself.

If I start xonsh just with this minimal script (called from a bash prompt):

```
#!/Users/halloleo/venv/xonsh/bin/python
from xonsh.main import main
main()
```

then `vox create new_venv` craetes a vebnv *without* pip, but if I start xonsh with proper venv activation via something like

```
#!/usr/bin/env python3
import sys
import os
from pathlib import Path

activate_file = '/Users/halloleo/venv/xonsh/bin/activate_this.py'
with open(activate_file) as f:
    exec(f.read(), dict(__file__=activate_file))

from xonsh.main import main
main()
```

then it works correctly and pip is installed. 

So I don't think it is a bug in xonsh, but rather a reminder that **it is important to start a 'venved' xonsh via a proper venv activation script.**

**Comment by knowsuchagency** [comment]
This should actually be solved with the current master version of xonsh on master, `0.8.8`

**Comment by halloleo** [comment]
Thanks for chiming in, @knowsuchagency . Does this mean I can start xonsh from the Python exe of its venv *without* all the path munging `activate_this.py` does?

More generally asked: **What's the best way to start a xonsh in its own venv?** I have noticed `xpip` does funny things when used in a venv, while `pip` acts on the  namespace of venv's Python and not on the system python.

This is all not a problem, just a bit confusing...

**Comment by knowsuchagency** [comment]
I think the best way to do what you want is to use [`pipx`](https://github.com/cs01/pipx) to install xonsh

**Comment by halloleo** [comment]
Thanks  for the advice, @knowsuchagency .

I've tested installation via `pipx` - and it is **by far the superior method of installing xonsh if you want to install it into its own virtual environment!** Here the good things you get from it inside the xonsh repl:

* `python`, `python3` and `pip` reference the system executables. :-)
* xpip references the pip in xonsh' venv. :-)

Plus:

* When you create a venv via `vox` it now contains a pip.

I think it's all good now.
