### ISSUE TITLE
Color does not work in Windows

### ISSUE THREAD

**Issue by NeverMine17** [xonsh/xonsh#2977]
There is no color in cmd. I have tried reinstalling xonsh and prompt-toolkit, but no luck.

## xonfig
```
+------------------+-----------------------------------------------+
| xonsh            | 0.8.7                                         |
| Git SHA          | f6a5ac5b                                      |
| Commit Date      | Dec 27 10:47:21 2018                          |
| Python           | 3.7.2                                         |
| PLY              | 3.11                                          |
| have readline    | False                                         |
| prompt toolkit   | 2.0.7                                         |
| shell type       | prompt_toolkit2                               |
| pygments         | None                                          |
| on posix         | False                                         |
| on linux         | False                                         |
| on darwin        | False                                         |
| on windows       | True                                          |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x03BA7E90> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x03BA7ED0> |
| is superuser     | False                                         |
| default encoding | utf-8                                         |
| xonsh encoding   | utf-8                                         |
| encoding errors  | surrogateescape                               |
+------------------+-----------------------------------------------+
```

## Expected Behavior
There should be color in cmd, such as in this screenshot: https://xon.sh/docs-ahundt-sphinx-readable-theme-pypi/_images/better_colors_windows.png

## Current Behavior
There is no color in cmd:
![2019-01-01 14_34_27-window](https://user-images.githubusercontent.com/23419131/50572476-9c6a0d80-0dd2-11e9-91af-b2ba83dc0559.png)

## Steps to Reproduce
  1. Install python 3.7.2 through https://python.org
  2. Install xonsh and prompt-toolkit using pip
  3. Open cmd and run xonsh

**Comment by NeverMine17** [comment]
### `pip freeze`:
```
prompt-toolkit==2.0.7
ptk==1.3.5
Pygments==2.3.1
six==1.12.0
wcwidth==0.1.7
win-unicode-console==0.5
xonsh==0.8.7
```

**Comment by melund** [comment]
I don't have this issue, with the default released version on "conda": 

![image](https://user-images.githubusercontent.com/1038978/50584300-ffa97d80-0e6e-11e9-85c7-f284dacd7012.png)

What version of Windows do you use?

**Comment by melund** [comment]
I also tried to installing directly from master. Colors still work. @NeverMine17  do you have any clue to what could be special in your setup?

![image](https://user-images.githubusercontent.com/1038978/50584390-95dda380-0e6f-11e9-9c0c-ae92947afdd9.png)

**Comment by NeverMine17** [comment]
Installing from conda does not solve it either:
![image](https://user-images.githubusercontent.com/23419131/50603053-978c8300-0ed2-11e9-9e86-bdcf6a811e7a.png)
My exact Windows 10 version is 10.0.18305.1003

**Comment by melund** [comment]
> My exact Windows 10 version is 10.0.18305.1003

Ok... I don't know how to interpret that. Mine is called: 

| Windows 10:  Version 1809 (OS Build 17763.195)

Do other programs generate color in your terminal? 

There are basically two ways to get colors on windows. Using the old Win32 api in the console or with ANSI100 sequences. The first is  used on older versions of windows 10 and when using prompt_toolkit 1 (PTK1). With PTK2 and on recent versions of Windows 10 we use the ANSI100 escape escape sequences. Similar to how colors are generated on Linux. We use some functions from PTK2 to detect if Windows supports ansi colors. 

Can you try to run the following (in python or xonsh).

```py
>>> from prompt_toolkit.utils import is_windows_vt100_supported, is_conemu_ansi
>>> is_windows_vt100_supported()
>>>is_conemu_ansi()
```
Then report what the functions return?

**Comment by melund** [comment]
@NeverMine17 Are you using the pre-release of Windows for the April update? I would say that constitutes something "special in your setup" :-/ Are you on the "Windows Insiders" fast channel, or did you install manually?

Console colours have been broken before in the pre-releases. But if you can find the cause that would be great.

**Comment by NeverMine17** [comment]
Oops, just found out that pre-release version of Windows 10 disabled all colored text in new version of cmd. Solution to this is  https://github.com/composer/composer/issues/5323#issuecomment-220871883. Fixed that for me.

**Comment by melund** [comment]
Great that you solved it :)

**Comment by scopatz** [comment]
Is there anything we need to do on our front
