### ISSUE TITLE
source-bash: How do I provide arguments to the bash script?

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#2978]
I have a Bash script I need to source. It takes in arguments - but I can't figure out how to get source-bash to take in those arguments. 

Consider a script that (in Bash) would be run as:

`source script.sh -a arg -b 3`

Doing 

`source-bash script.sh -a arg -b 3` does not work. 

xonfig output:

```
+------------------+----------------------+
| xonsh            | 0.8.1                |
| Git SHA          | 23246604             |
| Commit Date      | Oct 18 09:55:19 2018 |
| Python           | 3.6.3                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 2.0.7                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | rhel                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by scopatz** [comment]
Hi @beetleb - if you put the script and all args in quotes, it should work.  That is, 

```
$ source-bash "script.sh -a arg -b 3"
```

This treats `"script.sh -a arg -b 3"` as the single argument to source.  Note that you can always inspect what `source-bash` will run with by adding the `--dry-run --show` options.

**Comment by beetleb** [comment]
Hmm... Now I get `xonsh: error: Possible reasons: File not found or syntax error`.

But a simple Bash script works. 

I think I need to dig deeper. Probably should close this ticket for now.

**Comment by scopatz** [comment]
Ahh Ok! If you can share the Bash script, we might be able to help!

**Comment by ckline-tryptic** [comment]
### **Given** a bash script `test.sh`:
```bash
#!/bin/bash
MY_VARIABLE="$1"
export MY_VARIABLE
```

### **When** your try to `source-bash` the script with an argument:
```bash
source-bash ./test.sh foo
```

current output
`xonsh: error: Source failed: 'source .test.sh\nsource`
`xonsh: error: Possible reasons: File not found or syntax error`

```bash
source-bash "./test.sh foo"
```

### **Then** exported variable `$MY_VARIABLE` should exist:
```bash
echo $MY_VARIABLE
```

current output
`$MY_VARIABLE`

expected output
`foo`
