### ISSUE TITLE
homebrew version out-of-date

### ISSUE THREAD

**Issue by knowsuchagency** [xonsh/xonsh#2985]
The [current formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/xonsh.rb) is one patch version out-of-date. 0.8.7 vs 0.8.8

Would someone be able to update it or provide a guide so as to do so?

**Comment by scopatz** [comment]
That would be great.  I am not sure who maintains the homebrew code.  You might just want to put in a PR to that repo

**Comment by scopatz** [comment]
Closing this.  But feel free to repoen if needed.
