### ISSUE TITLE
cheat

### ISSUE THREAD

**Issue by JackofSpades707** [xonsh/xonsh#2987]
neovim not keyboard input properly (under certain conditions)

## xonfig
```
+------------------+-----------------+
| xonsh            | 0.8.8           |
| Python           | 3.7.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.7           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior
I can type within nvim even when cheat calls nvim

## Current Behavior
The modes on neovim should change in accordance to which key I hit. Instead it sends the ascii characters in a way that appears to be writing over the buffer, and not in the buffer.
Ctrl+C / Kill $pid are the only ways out of neovim
I've yet to test this with the other versions of vim

## Steps to Reproduce
$ xonsh
$ cheat -e xonsh
# Try typing/doing things

**Comment by JackofSpades707** [comment]
P.S.
Cheat is written in python, here's the traceback when you Ctrl+C out of neovim (This only happens when cheat launches neovim within the xonsh terminal)

'''
File "/bin/cheat", line 57, in <module>                                         
    sheet.create_or_edit(options['<cheatsheet>'])                                 
  File "/usr/lib/python3.7/site-packages/cheat/sheet.py", line 35, in create_or_edit4     ${'SP'+'AM'}: Get the env var from an expression (eg, SPAM)               
    edit(sheet)$ARG1, ... $ARG9: Script command line argument at index n, ex: run   File "/usr/lib/python3.7/site-packages/cheat/sheet.py", line 46, in edit        
    open_with_editor(path(sheet))d line parameter arguments, ex: create myscript.x  File "/usr/lib/python3.7/site-packages/cheat/utils.py", line 64, in open_with_editoret ['myscript.xsh', 'hello', 'world'] as output.                              
    subprocess.call(editor_cmd + [filepath])                                      
  File "/usr/lib/python3.7/subprocess.py", line 325, in call                      
    return p.wait(timeout=timeout)                                                
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait                      
    return self._wait(timeout=timeout)                                            
  File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait                    
    (pid, sts) = self._try_wait(0)                                                
  File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait                
    (pid, sts) = os.waitpid(self.pid, wait_flags)                                 
KeyboardInterruptures output, returns stdout 
'''

(Yes that's the exact output the user sees)

**Comment by t184256** [comment]
Does `__xonsh__.commands_cache.threadable_predictors['cheat'] = lambda _: False` fix that?

**Comment by scopatz** [comment]
@JackofSpades707 - thanks for reporting!  I can't reproduce the issue you are seeing.  But it might be because I have a different editor set.  What is the value of $EDITOR that you see?

**Comment by scopatz** [comment]
Any updates on this?

**Comment by eppeters** [comment]
I am able to reproduce this issue with another command - I haven't tried `cheat`, but more importantly, @t184256's suggested workaround fixes the issue for me _inside the xonsh Docker container_.

I have been having this issue when any `xonsh` subprocess opens an instance of `nvim`, but I don't have the same problem with `vim`. So, I used `git` to reproduce this instead of `cheat`, but I believe the problems are from the same issue. I can try `cheat` later, but I wanted to chime in on this because this bug has been bothering me for a while.

I believe that #3311 also stems from the same issue, so if I'm right, we could fix two issues at once by fixing this bug.

That said, I'm not up on what threadable predictability is, but I'm happy to help fix this if anyone wants to point me in the right direction. For the moment I'm going to dig up any docs I can and start reading the `xonsh` code I can grep about threadable prediction.

**Comment by eppeters** [comment]
Apologies - after filing that comment I searched for "threadable" in the issues and found #3285, which deals specifically with `git`. I hadn't realized that specific commands can be/are marked threadable or unthreadable in `xonsh` - just thought there was some generic bug afoot here. So, I see this is a separate issue from the `git` and `emacs` ones (#3285 and 3311).

**Comment by anki-code** [comment]
@eppeters does this still actual? If yes please add the detailed description to the title.
