### ISSUE TITLE
Starting xonsh from an activated virtualenv results in a partially-loaded venv in xonsh

### ISSUE THREAD

**Issue by bskinn** [xonsh/xonsh#2997]
## xonfig
```
 $ xonfig
+------------------+---------------------+
| xonsh            | 0.8.8               |
| Git SHA          | b64a2126            |
| Commit Date      | Jan 2 19:02:13 2019 |
| Python           | 3.6.6               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | None                |
| shell type       | readline            |
| pygments         | None                |
| on posix         | True                |
| on linux         | True                |
| distro           | unknown             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

## Expected Behavior
When starting xonsh from within an active virtualenv, either
1) xonsh should ignore the active venv and start venv-free, or
2) xonsh should be fully ready to operate in the active venv

## Current Behavior
When xonsh loads, portions of the virtualenv are loaded correctly (e.g., `which python` gives a sane result), but in particular the `deactivate` command is not correctly configured.

## Steps to Reproduce
Starting from bash:
```
bash$ source env/bin/activate
(env) bash$ xonsh
[[ welcome screen ]]
(env) xonsh$ which python
.../env/bin/python
(env) xonsh$ which pip
.../env/bin/pip
(env) xonsh$ deactivate
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: deactivate
(env) xonsh$ source env/bin/activate.xsh
(env) xonsh$ deactivate
xonsh$
```

Similar behavior occurs on Windows, except instead of an error the `deactivate` just ends up being a no-op.

It *looks* like the `deactivate` alias/script for the virtualenv isn't being created when xonsh loads.

A fix might be to check `if ...env.get('$VIRTUAL_ENV', '')` as xonsh loads, and if it's truthy to go ahead and try re-activating the active environment before dropping to xonsh prompt (equivalent of `source $VIRTUAL_ENV/bin/activate.xsh`)?

**Comment by scopatz** [comment]
Thanks for reporting @bskinn! This seem more like a bug in the virtual-env implementation of activation than in xonsh itself.  Should we open this issue there?

**Comment by bskinn** [comment]
I just tested csh, fish, and bash itself -- the same sort of problem happens with all of them... a portion of the surrounding virtualenv gets imported into the new shell, but not all of it, and I'd be leery of trusting the behavior.

So, now that I look at it again, this actually seems like it might be a broader problem with launching a new shell of *any* kind from within a virtualenv.

As such, rather than attempting some sort of fix, that might end up running aground of all sorts of treacherous corner cases, it might be better just to admonish users that this is a Thing Not To Do™.

**Comment by scopatz** [comment]
Yeah, I'm am not super suprised, frankly.
