### ISSUE TITLE
No installation guide on homepage or in README

### ISSUE THREAD

**Issue by ntdef** [xonsh/xonsh#3012]
Hi! 👋 

I'm eager to try out `xonsh`! While reading through the docs, it wasn't quite clear what I should do to actually install `xonsh`. From the looks of it, I'm guessing I should `pip install xonsh`, however, that's very much implicit rather than explicit in the docs. Moreover, it's not clear if there's a corresponding `brew` package, and no instructions on how to make `xonsh` my preferrer shell in, say, iTerm. 

I don't need help here in particular (ie. I know how to setup iTerm). I think newer python users would benefit from the increased clarity. 

Thanks for building this! I'm excited to try it out. 😄

**Comment by gforsyth** [comment]
Hey @ntdef -- there are some instructions here for different OS.  Let us know if there's any more information you'd like to see on here!

https://xon.sh/#installation

**Comment by ntdef** [comment]
Oh I see. I definitely missed this. I think I was just thrown off on the TOC here. 

Regards,
Troy de Freitas

**Comment by ntdef** [comment]
I think it’s the fact that 
Dependencies
Development Dependencies
Are listed below in the same doc but the installation instructions aren’t. It’s a little bit confusing. 

Regards,
Troy de Freitas

**Comment by scopatz** [comment]
Awesome! Thanks! We really appreciate it!

**Comment by ntdef** [comment]
Just made a pr.
