### ISSUE TITLE
command takes 30 seconds to start, how to profile?

### ISSUE THREAD

**Issue by mogenson** [xonsh/xonsh#3022]
## xonfig

<details>

```

xontrib load coreutils z

# set hostname environmental variable so that {vte_new_tab_cwd} works
$HOSTNAME = $(hostname).strip()
$CASE_SENSITIVE_COMPLETIONS = False
$EDITOR = 'kak'
$VI_MODE = True
$XONSH_AUTOPAIR = True

# set prompt with {vte_new_tab_cwd}
$PROMPT = '{vte_new_tab_cwd}{GREEN}{short_cwd}{NO_COLOR} {gitstatus:[{}] }{GREEN}{prompt_end}{NO_COLOR} '

# aliases
aliases['diff'] = 'icdiff --line-numbers'
aliases['rm'] = 'rm -I'

```

</details>

# Issue

The text editor [Kakoune](http://kakoune.org/) takes up to 30 seconds to start when launched from xonsh. I initially thought this was an issue with kak, but it launches in under 1 second from bash, even from a bash shell started from xonsh.

I used the `time` utility to measure the time to start `kak`. The process is: start `kak` and immediatly send it the 'quit' command. Save the stderr output from `time` to kak-from-bash.log.

### From bash

```
/usr/bin/time -p kak -e quit 2> kak-from-bash.log
cat kak-from-bash.log
real 0.36
user 0.24
sys 0.17
```

### From xonsh

```
env XONSH_DEBUG=1 xonsh --no-rc
/usr/bin/time -p kak -e quit err> kak-from-xonsh.log
cat kak-from-xonsh.log
real 27.49
user 0.47
sys 0.30
```

How would I go about profiling the startup of this command to see what is taking so long? I know the `kak` executable sources a number of configuration files and evaluates their contents with `/bin/sh`. Is there a reason that python/xonsh would be very slow at spawning a number of `/bin/sh` processes?

**Comment by andrewchambers** [comment]
You could use strace to write a log of all syscalls and timing information to get some hints.

**Comment by mogenson** [comment]
Couldn't figure out what was causing the delay. I ended up writing a shell wrapper script:

```
#!/bin/sh
kak "$@"
```
