### ISSUE TITLE
If you type it immediately after executing the command, it will not accept the input

### ISSUE THREAD

**Issue by kontikusho** [xonsh/xonsh#3023]
## xonfig

<details>

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.8.10              |
| Git SHA          | 2cb42bdb            |
| Commit Date      | Feb 6 16:49:16 2019 |
| Python           | 3.7.2               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | None                |
| shell type       | readline            |
| pygments         | None                |
| on posix         | True                |
| on linux         | True                |
| distro           | unknown             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```
</details>

## Current Behavior

[![asciicast](https://asciinema.org/a/s13lMz7sLzeNJ512frqQ7b6Jx.svg)](https://asciinema.org/a/s13lMz7sLzeNJ512frqQ7b6Jx)

|OS|SSH Server|SSH Client|SSH Client Shell|
|:---|:---|:---|:---|
|Windows 10 Home|WSL WLinux|mintty+msys2|tmux+bash|

### Traceback (if applicable)

<details>

```
traceback
```
</details>

## Steps to Reproduce

1. exec command
2. quick input
3. hang up

Sorry. A bug occurred in this procedure, but I am not sure.

**Comment by scopatz** [comment]
Thanks for reporting @kontikusho! If anyone with WSL could take a look at this, that would be great!

**Comment by melund** [comment]
@kontikusho I can't reproduce this. I can write in the readline buffer just after submitting a command, but it never hangs and ctrl-c can always get the prompt back. 

Can you try to install prompt_toolkit 2 and see if that solves the problem for you? It also nicer than readline in general.

**Comment by kontikusho** [comment]
@melund I installed prompt_toolkit, but it hangs up.
[![asciicast](https://asciinema.org/a/MoKkdiNUJA2zFaOrCFEqgPHWN.svg)](https://asciinema.org/a/MoKkdiNUJA2zFaOrCFEqgPHWN)

|OS|Distribution|Shell|
|:---|:---|:--|
|Windows 10 Home|WSL WLinux|Bash|

It became difficult to reproduce with the clear command. (Reproduced with the ls command this time)

**Comment by kontikusho** [comment]
I solved the problem with the upgrade.
Thank you very much.

Xonfig:
```
+------------------+----------------------+
| xonsh            | 0.9.9                |
| Git SHA          | 5aac8711             |
| Commit Date      | Jul 19 17:43:33 2019 |
| Python           | 3.7.4                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```
