### ISSUE TITLE
Default prompt doesn't have any color on Windows 10

### ISSUE THREAD

**Issue by LexSong** [xonsh/xonsh#3027]
## xonfig

    +------------------+-----------------+
    | xonsh            | 0.8.10          |
    | Python           | 3.7.2           |
    | PLY              | 3.11            |
    | have readline    | True            |
    | prompt toolkit   | 2.0.8           |
    | shell type       | prompt_toolkit2 |
    | pygments         | 2.3.1           |
    | on posix         | False           |
    | on linux         | False           |
    | on darwin        | False           |
    | on windows       | True            |
    | on cygwin        | False           |
    | on msys2         | False           |
    | is superuser     | False           |
    | default encoding | utf-8           |
    | xonsh encoding   | utf-8           |
    | encoding errors  | surrogateescape |
    +------------------+-----------------+    

## Expected Behavior
correct colored prompt

## Current Behavior and Steps to Reproduce
![screenshot](https://user-images.githubusercontent.com/35987111/52937687-d00cf100-339a-11e9-974f-30035b2f4c27.png)
On Windows 10, the default prompt is using {BOLD_COLOR}, but somehow it doesn't work.
If I change `$PROMPT` to use {COLOR}, it works as expected.

**Comment by melund** [comment]
This is not a xonsh issue. Conhost on windows doesn't support bold colors. I believe this is similar to some old terminals on Linux. Setting text as bold will just upgrade colour to a more intense version. 

This is something that Microsoft will address eventually. See this issue: https://github.com/Microsoft/console/issues/109#issuecomment-375827482

**Comment by LexSong** [comment]
Yes, but currently the `default_prompt()` in `xonsh/xonsh/prompt/base.py` just uses a bad default. 
It used to show color correctly in previous version of prompt toolkit.

Besides, the prompt toolkit should just ignore bold style and print color correctly, and it's not the behavior here.

**Comment by melund** [comment]
You are right. I was a little too hasty here. It shouldn't just remove the colors...

But it is not a problem I see on my end: 
![image](https://user-images.githubusercontent.com/1038978/52939692-1e070200-3365-11e9-82bf-545d76cc9130.png)

**Comment by melund** [comment]
Which version of Windows 10 are you using? There have been some beta "insider" versions in the "fast ring" which broke stuff before.

**Comment by LexSong** [comment]
The Windows 10 version is 17134.590. I supposed that I'm not using an insider build.

**Comment by LexSong** [comment]
If I rolled back the prompt-toolkit to version 1.0.15 it works as expected. It doesn't work on ptk 2.0.2.

**Comment by melund** [comment]
Can you try 2.0.7 or higher:
```
snail@sea ~
$ xonfig
+------------------+-------------------------------------------------------+
| xonsh            | 0.8.10.dev28                                          |
| Git SHA          | 43d05276                                              |
| Commit Date      | Feb 14 16:00:20 2019                                  |
| Python           | 3.7.1                                                 |
| PLY              | 3.11                                                  |
| have readline    | True                                                  |
| prompt toolkit   | 2.0.7                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | 2.3.1                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
```

**Comment by LexSong** [comment]
Nope, 2.0.7 and 2.0.8 both doesn't work.

**Comment by melund** [comment]
With

**Comment by melund** [comment]
With prompt toolkit 2 can you try the following:

```
from prompt_toolkit.output.windows10 import is_win_vt100_enabled
is_win_vt100_enabled()
```

and report the result?

**Comment by LexSong** [comment]
`is_win_vt100_enabled()` returns `True`

**Comment by melund** [comment]
Ok. I found a PC with the same Windows version as yours. Will try to see if happens there...

**Comment by LexSong** [comment]
Maybe I found the possible issue..

If I removed `pygments` I can get the color output, but looks like PTK just fall back to default behavior.

**Comment by melund** [comment]
Well. I can see the same behaviour on Windows 10 version 1803 (17134.590), but not on 1809. 

The version 1809 was the October update, so it should be rolling out to most people now.

A pull request is welcome if you can check the Windows version from Python and update the default $PROMPT  accordingly. Otherwise, this seems to resolve itself once everyone gets the October 2018 update.

**Comment by LexSong** [comment]
Thanks for your help! I may just change the prompt in xonshrc and wait for the update.
