### ISSUE TITLE
Thank you contributors!

### ISSUE THREAD

**Issue by swayson** [xonsh/xonsh#3030]
I just wanted to say thanks to all the contributors for this wonderful tool. I discovered it recently, and as somebody who needs to work in a Windows environment in many cases, this tool has truly been a fantastic.

Thank you for this and sharing it with the world!

Perhaps at some stage this year I can also contribute.

**Comment by scopatz** [comment]
Thanks so much @swayson! Really looking forward to your contributions! Anything helps!
