### ISSUE TITLE
Hyperlink of Xontribs - autojump is 404

### ISSUE THREAD

**Issue by tamuhey** [xonsh/xonsh#3036]
The hyperlink pasted in [this xontirbs page](https://xon.sh/xontribs.html#autojump) is incorrect.

The link -> 
https://github.com/gsaga/autojump-xonsh

**Comment by tamuhey** [comment]
I found an excellent tool that is alternative for the autojump-xonsh:

https://github.com/willsALMANJ/autojump-xonsh

**Comment by scopatz** [comment]
Thanks! PRs welcome to fix up the docs here!

**Comment by astronouth7303** [comment]
The [PyPI page](https://pypi.org/project/xontrib-autojump/) points to https://github.com/sagartewari01/autojump-xonsh
