### ISSUE TITLE
Prompt background color is not reflected for ubuntu

### ISSUE THREAD

**Issue by re3turn** [xonsh/xonsh#3038]
# issue
Set the background color `BACKGROUND_` and text color at the same time at ubuntu prompt, colors will not be reflected.
But in macOS it is reflected even if background color and character color are set at the same time.
Why is it different?

# Set prompt

```:xonsh
$PROMPT='{BACKGROUND_GREEN}{BLACK}AAA{NO_COLOR}@{WHITE}{BACKGROUND_RED}BBB{NO_COLOR}@{BACKGROUND_BLUE}CCC{NO_COLOR}@{BLUE}DDD{NO_COLOR}$ '
```

# ubuntu 18.10

![ubuntu](https://user-images.githubusercontent.com/8900042/53821417-1a07f080-3fb1-11e9-87a5-0cfe6a3d7556.png)

# macOS(Mojave)
![macos](https://user-images.githubusercontent.com/8900042/53821433-22f8c200-3fb1-11e9-9a14-a0d72dc67b52.png)

**Comment by virusbb001** [comment]
I guess this difference is caused by different shell-type or using pygments.
I confirmed to not be reflected when shell type is prompt-toolkit and not using pygments in Arch Linux (on VirtualBox).
I confirmed to be reflected when shell type is readline, or shell type is prompt-toolkit and using pygments 2.3.1.

Checked xonfig (ptk2, pygments)
```
+------------------+----------------------+
| xonsh            | 0.8.12               |
| Git SHA          | 986bf28d             |
| Commit Date      | Mar 11 14:37:52 2019 |
| Python           | 3.7.2                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```
Result of my inspection about ptk2 is [here(asciinema)](https://asciinema.org/a/NKLHMjTnab9bjpLUdjyT8NtPD).

**Comment by re3turn** [comment]
That’s it.
Background color reflected when installing pygments.
Thanks!
