### ISSUE TITLE
python 3 not found

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [xonsh/xonsh#3040]
how to configure the python path? i have py3 installed

**Comment by swayson** [comment]
Hi there,

This could prove insightful.

https://stackoverflow.com/questions/19917492/how-to-use-pythonpath

**Comment by Abdur-rahmaanJ** [comment]
@swayson i mean xonsh seeks py by path. that is bad, any way to configure it internally without changing system settings?

**Comment by swayson** [comment]
pipenv or conda perhaps?

**Comment by Abdur-rahmaanJ** [comment]
ok thank you, requesting a feature
