### ISSUE TITLE
[feature] configure python exec in xonsh instead of python path

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [xonsh/xonsh#3042]
include a way to include which version of python we want xonsh to run with instead of pulling settings from  python path

**Comment by gforsyth** [comment]
Hi! I'm not sure I understand the request here. 
 xonsh will use whichever python you've installed it with. 
You can sandbox it, if you'd like, by creating a python environment, installing xonsh in it and then you can symlink the xonsh entry point into wherever on your system path you'd like.

**Comment by Abdur-rahmaanJ** [comment]
ah that's clever !

that clears away everything!

issue can be closed!

>

**Comment by gforsyth** [comment]
Great! Let us know if you have any other questions / feature requests!
