### ISSUE TITLE
[headache] installed with python 3.4 but used python 2.7

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [xonsh/xonsh#3043]
installed with py 3.4 showed
when typing xonsh on the cli
```
Python 3 not found!
Installed Pythons found by py Launcher for Windows
 -2.7-32 *

Requested Python version (3) not installed, use -0 for available pythons
```
tried with 3.7 showed

```
Python 3 not found!
Installed Pythons found by py Launcher for Windows
 -2.7-32 *

Requested Python version (3) not installed, use -0 for available pythons
```

**Comment by Abdur-rahmaanJ** [comment]
edit: worked with anaconda but not normal python

**Comment by virusbb001** [comment]
I guess you are using Windows so I will talk on this premise.

```
Python 3 not found!
Installed Pythons found by py Launcher for Windows
 -2.7-32 *

Requested Python version (3) not installed, use -0 for available pythons
```

This messages doesn't mean "I'm using python2.7", but means "I found python 2.7 but python 3.x was not found"
It seems something wrong happens in installing python 3.(Such like it failed to write registry)

Could you try to reinstall python 3 and run `py -0` to check that normal python 3 has been succesfully installed. `py -0` shows you installed version.

If `py -0` doesn't show you 3.x version, please tell how did you install python3 to make it easy to reproduce your problem.
