### ISSUE TITLE
less is immediately backgrounded

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#305]
```
dotfilesmaster*%=🐚 less .profile

*[1] stopped: less .profile & (313)
```

If I type `fg` it displays, although it seems to be a broken `less` that doesn't support the alternate screen mode (i.e., it's line-based). If I do that and then run `less .profile` again, it works as expected and all future `less` commands do as well.

**Comment by scopatz** [comment]
Hmm this is weird.  I am not able to reproduce this on my machine.  less works just fine. Were you in iterm2?

**Comment by scopatz** [comment]
Also were you running xonsh from within bash?

**Comment by asmeurer** [comment]
Yes and yes.

**Comment by LuckyHyena** [comment]
I'm getting this issue running within bash in xfce4-terminal 0.6.3 on Xubuntu 14.04. It's inconsistent: if I run the same less command over and over again it will work fine most times but will eventually be backgrounded

**Comment by scopatz** [comment]
@LuckyHyena weird.

**Comment by scopatz** [comment]
I have no idea what this issue is about. I can't reproduce it.

**Comment by davidbrochart** [comment]
I have the same problem here. The job is stopped and if I try to kill it with "kill %1" I get the following error:
kill: failed to parse argument: '%1'

**Comment by scopatz** [comment]
What if you try to kill it with just `kill 1`

**Comment by davidbrochart** [comment]
No error, but it didn't kill it.

**Comment by scopatz** [comment]
Hmm @davidbrochart can you give me more information about what you are doing exactly? A history file would be nice too... Thanks!

**Comment by davidbrochart** [comment]
```
david@david-OptiPlex-745:~$ xonsh
david@david-OptiPlex-745 ~ $ more toto
tata
david@david-OptiPlex-745 ~ $ more toto

*[1] stopped: more toto & (5443)
david@david-OptiPlex-745 ~ $ jobs
*[1] stopped: more toto & (5443)
david@david-OptiPlex-745 ~ $ kill %1
kill: failed to parse argument: '%1'
david@david-OptiPlex-745 ~ $
```

**Comment by scopatz** [comment]
What is the value of `$XONSH_STORE_STDOUT`and what version of xonsh are you on? (As a side note, Also I don't believe that `%1` is valid xonsh subproc syntax.)

**Comment by davidbrochart** [comment]
`$XONSH_STORE_STDOUT` is set to `False` and I run `xonsh/0.2.0`.

**Comment by davidbrochart** [comment]
Isnt' it that the `more` or `less` commands try to take control of the command line? For example, even in the Python interpreter, trying to do `more` on a file which is bigger than your screen and requires a user input to display the rest doesn't play well with subprocess:
```python
import subprocess
>>> import subprocess
>>> subprocess.Popen(['more', 'toto'])
```

**Comment by scopatz** [comment]
Are you on a Mac @davidbrochart?

**Comment by scopatz** [comment]
I can't seem to reproduce this on my Linux setup.

**Comment by davidbrochart** [comment]
No it's Ubuntu 14.04, but an old machine. On a newer one I don't have the problem.

**Comment by scopatz** [comment]
does this happen with prompt-toolkit too, or just readline?

**Comment by davidbrochart** [comment]
With prompt-toolkit also, but less frequently.

**Comment by scopatz** [comment]
Hmmm I wonder if it is an old libreadline issue that was fixed, then.  If you discover what the root cause is, or see the issue crop up on a contemporary version of Ubuntu, please let us know. More information would be really helpful.

**Comment by gforsyth** [comment]
@asmeurer -- is this still an issue on master?

**Comment by asmeurer** [comment]
I haven't seen it in a while, but I also don't use xonsh regularly.

**Comment by adqm** [comment]
Okay.  I'm going to close for now, then.  If we see this come up again, we can reopen (or discuss in a new issue).
