### ISSUE TITLE
IPython mode with explicit exec by !

### ISSUE THREAD

**Issue by techtonik** [xonsh/xonsh#3051]
In https://xon.sh/tutorial.html#python-mode-vs-subprocess-mode subprocess mode is context dependent, which is tricky to debug. Is it possible to add explicit mode where are subprocess commands need to be prefixed with `!` as it is done in IPython?

**Comment by scopatz** [comment]
Yep! We actually have 4 different subprocess operators.  See https://xon.sh/tutorial.html#captured-subprocess-with-and and https://xon.sh/tutorial.html#uncaptured-subprocess-with-and 

Also, out of curiosity, what wasn't working for you?

**Comment by techtonik** [comment]
`xonsh` tried to use my variable name as a shell command, and I want it to treat everything that is not explicitly prefixed as Python.

**Comment by scopatz** [comment]
That shouldn't happen unless the variable name doesn't exist.

**Comment by scopatz** [comment]
Do you have some example code?

**Comment by techtonik** [comment]
> That shouldn't happen unless the variable name doesn't exist.

I don't like this implicit rule. If variable doesn't exist, I expect it to stop with an error.

**Comment by anki-code** [comment]
This should work:

```python
$[@(var) 123]
# NameError: name 'var' is not defined

var = 'echo'
$[@(var) 123]
123
# Prepared by xontrib-hist-format
```
