### ISSUE TITLE
$PWD is incorrect when accessed via python-mode.

### ISSUE THREAD

**Issue by kalekundert** [xonsh/xonsh#3054]
I've found that the value of the `$PWD` environment variable (which should contain the path to the current working directory, taking into account whatever symlinks the user may have used to get there) is incorrect when accessed via python-mode, but correct when accessed via subprocess-mode.

Below are two minimal examples that highlight the problem:

```sh
$ mkdir foo
$ cd foo
$ echo $PWD
/home/kale/foo
$ import os; os.getenv('PWD')
/home/kale
```

In this example, I'd expect `os.getenv('PWD')` to return `/home/kale/foo` like `$PWD`.

```sh
$ echo "import os; print(os.getenv('PWD'))" > pwd.py
$ python pwd.py
/home/kale/foo
$ import subprocess; subprocess.run(['python', 'pwd.py'])
/home/kale
CompletedProcess(args=['python', 'pwd.py'], returncode=0)
```

This example is a little more complicated, but it shows that even scripts are affected.  In this case, the output of the script depends on whether it was launched from subprocess-mode or python-mode (and only subprocess-mode produces the correct result).

Here's the output from `xonfig`:
```sh
$ xonfig
+------------------+----------------------+
| xonsh            | 0.8.12               |
| Git SHA          | 986bf28d             |
| Commit Date      | Mar 11 14:37:52 2019 |
| Python           | 3.7.0                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | readline             |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by kalekundert** [comment]
In fact, looking at this a little closer, this behavior occurs for any environment variable, not just `$PWD`:

```sh
$ $FOO='foo'
$ echo $FOO
foo
$ import os; os.getenv('FOO')  # no output
```

**Comment by scopatz** [comment]
Does setting `$UPDATE_OS_ENVIRON = True`  fix this for you? Docs at https://xon.sh/envvars.html#update-os-environ

**Comment by laloch** [comment]
You might want to check `$UPDATE_OS_ENVIRON` variable.

**Comment by kalekundert** [comment]
Yes, that definitely fixes this for me.  Thanks for the fast response!

**Comment by scopatz** [comment]
awesome!
