### ISSUE TITLE
ls not working

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [xonsh/xonsh#3057]
```ls``` does not  work on win

```
xonsh: subprocess mode: command not found: ls
Did you mean one of the following?
    cls:  Alias
    cd:   Alias
    fg:   Alias
    bg:   Alias
    rd:   Alias
```

**Comment by gforsyth** [comment]
Hi @Abdur-rahmaanJ 

`ls` is not a shell built-in, it needs to be available from the underlying OS.  
There is some info here on how to avoid a namespace collision with `dir`: https://xon.sh/windows.html#name-space-conflicts

**Comment by melund** [comment]
Hi @Abdur-rahmaanJ. If you install 'Git for Windows' and select to add the Unix tools to path during installation, then you get all nice commands in xonsh on Windows as well

**Comment by jaraco** [comment]
Or if you like your commands implemented in Python, consider [cmdix](https://pypi.org/project/cmdix), a pure-python implementation of the gnu coreutils.

**Comment by scopatz** [comment]
Ahh neat! cmdix would be awesome to vend as part of xonsh.  This was the idea behind the `xoreutils` subpackage

**Comment by gforsyth** [comment]
Closing this, as the original issue/question has been answered, will open a new feature issue for dropping in `cmdix` in place of `xoreutils`
