### ISSUE TITLE
type builtin, or some equivalent

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#306]
In bash, you can use the `type` builtin to see if a command is a file, alias, or shell function. It would be useful to have this in xonsh, especially to tell if a command is coming from xonsh or from subprocess mode. Right now, type calls `/usr/bin/type` (not sure what that is all about). This would also be useful if xonsh ever implements PATH hashing. 

Note that `type` is also a command on Windows which means something else entirely. Bash also has `command -V` which is the same as `type`.

**Comment by scopatz** [comment]
Weird, I don't have `/usr/bin/type`. I agree though.  There needs to be some utility to determine what a command is.

**Comment by scopatz** [comment]
Thanks for pointing out the oversight.

**Comment by funkyfuture** [comment]
what about `whatis` as command name?

**Comment by astronouth7303** [comment]
Is there a preferred name to call this builtin?

A quick look around the source code didn't uncover a straight-forward way to use the existing machinery to do this. Is there something I missed?

**Comment by gforsyth** [comment]
Hey @astronouth7303 -- it might not cover everything, but `xoreutils.which` is pretty good at this.  Especially with the `-v` flag.  

```
gil@bad_cat ~ $ which -v conda
aliases['conda'] = <function _xonda at 0x7f5f34244e18>
gil@bad_cat ~ $ which -v python
/home/gil/miniconda3/bin/python (from PATH element 0)
```

**Comment by asmeurer** [comment]
`which` is a logical place to put this functionality. One suggestion for improvement: `type` in bash gives the full source for built in functions:

```
$type sizeup
sizeup is a function
sizeup ()
{
    if [[ -z "$1" ]]; then
        DIR=.;
    else
        DIR="$1";
    fi;
    du -a -h -x "$DIR" | gsort -h
}
```

**Comment by gforsyth** [comment]
That shouldn't be too difficult.  We could add a flag to `which` to have it call `xonsh_superhelp`.  Or we could just have the `verbose` flag do that by default?

**Comment by astronouth7303** [comment]
Hm. zsh just defines `type` as `which -v`.

**Comment by scopatz** [comment]
Note that you should be able to get this by passing the function through `xonsh.built_ins.superhelp()`

**Comment by gforsyth** [comment]
@asmeurer, #1500 has been merged into master and I believe addresses this issue.
