### ISSUE TITLE
Xonsh is over 14x slower than Bash on a simple script (156x slower with "trace on")

### ISSUE THREAD

**Issue by certik** [xonsh/xonsh#3064]
Compare these two scripts in Bash:
```bash
#!/usr/bin/env bash

#set -x

ls
echo "OK"
x
ls
```
and Xonsh:
```
#!/usr/bin/env xonsh

#trace on

ls
echo "OK"
x
ls
```
Then time them using Bash and Xonsh:
```
$ time xonsh test.xsh 
adapters  ast     codegen  prompt.py  test.sh   tests
asr       cli.py  parser   semantic   test.xsh  __init__.py
OK
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: x
Did you mean one of the following?
    X:   Command (/usr/bin/X)
    xz:  Command (/home/certik/ext/miniconda3/envs/xonsh/bin/xz)
    [:   Command (/usr/bin/[)
    ex:  Command (/usr/bin/ex)
    w:   Command (/usr/bin/w)

x: command not found
adapters  ast     codegen  prompt.py  test.sh   tests
asr       cli.py  parser   semantic   test.xsh  __init__.py

real	0m0.556s
user	0m0.445s
sys	0m0.120s
$ time bash test.sh 
adapters  ast	  codegen      parser	  semantic  test.sh
asr	  cli.py  __init__.py  prompt.py  tests     test.xsh
OK
test.sh: line 7: x: command not found
adapters  ast	  codegen      parser	  semantic  test.sh
asr	  cli.py  __init__.py  prompt.py  tests     test.xsh

real	0m0.036s
user	0m0.022s
sys	0m0.015s
```

And if you enable `trace on` and `set -x`, then Bash timing does not change, but Xonsh timing gets 12x slower due to #3063, so overall with `trace on`/`set -x`, which is my default setting in Bash scripts, Xonsh is ~150 slower than Bash on a four line script.

Python loops are in general ~200 slower than, say, C, so for code that has loops perhaps a 200x slowdown is warranted. But I don't have any loops here, so this should execute fast.

**Comment by gforsyth** [comment]
Hey @certik -- thanks for reporting.

I believe that most of the timing difference there (ignoring the `trace` issue for the moment) is due to xonsh's startup time vs. bash.

We've made strides in reducing it, but it won't approach bash's startup time.

**Comment by certik** [comment]
It's not the start time. 

Compare this:
```
$ cat test.sh 
#!/usr/bin/env bash

for i in {1..50}
do
    echo "i = " $i
done
```
with:
```
$ cat test.xsh 
#!/usr/bin/env xonsh

for i in range(1, 51):
    echo "i =" @(i)
```
and
```
$ cat test2.xsh 
#!/usr/bin/env xonsh

bash test.sh
```
Timings:
```
$ time xonsh test.xsh 
i = 1
i = 2
i = 3
...
i = 50

real	0m0.588s
user	0m0.446s
sys	0m0.182s
```
and:
```
$ time bash test.sh 
i =  1
i =  2
i =  3
...
i =  50

real	0m0.032s
user	0m0.025s
sys	0m0.008s
```
and
```
$ time xonsh test2.xsh 
i =  1
i =  2
i =  3
...
i =  50

real	0m0.276s
user	0m0.249s
sys	0m0.038s
```

And you can then subtract the start up time and you can see that Xonsh **without* startup time is over 10x slower than Bash:
```python
>>> xonsh = 0.588
>>> bash = 0.032
>>> xonsh_bash = 0.276
>>> startup_time = xonsh_bash - bash
>>> xonsh_nostartup = xonsh - startup_time
>>> startup_time
0.24400000000000002
>>> xonsh_nostartup
0.344
>>> xonsh_nostartup / bash
10.749999999999998
```

**Comment by scopatz** [comment]
This is really interesting @certik! I think that some of this is because xonsh puts in a lot of slow-downs when calling subprocesses to ensure that the subprocess and file handles are all correctly set-up and redirected.  So when you call a lot of subprocesses (such as `echo @(i)`) you are hitting all of those sleeps() many times.  These are all below human notice (ie `<< 0.1 s` ).  

The reason for this is that until recently we had to support Python v3.4 which meant that our entire subprocess execution had to be run with Popen in threads. Now that we have dropped v3.4, we can move to async.  I am pretty sure that this situation will improve when we can await processes to be ready rather than having to sleep for them.  The code here makes for a great test case for that.

**Comment by certik** [comment]
@scopatz this reminds me a lot about Git vs Mercurial. Mercurial, being in Python, had (I don't know if it still has) this sluggishness, which is really annoying, but perhaps you can learn to live with it. Then you try Git, and every command like `git diff` is immediate. After you taste that, you can't go back to sluggishness again.

Coming from Bash, which is immediate, to Xonsh, which is sluggish, was not a good experience for me due to this.

Unfortunately I don't know how to fix this in Python. From experience, lots of this default sluggishness (such as startup time!) goes away when switching to compiled languages such as C++.

**Comment by scopatz** [comment]
I 100% agree.  We don't want to be slow.  We'd love help improving runtimes as much as possible!

I don't think rewriting xonsh in C++ is the answer (at least not for me personally). I have had a couple of attempts trying to Cythonize ths code base or use nuitka but they genereally don't work.  

Have you tried using xonsh on pypy?  I wonder if that is much faster than using CPython.

I'd also like to point out that xonsh does way more than stock Bash. So, for the moment, it is a matter of tradeoffs.  In this way it is different than git vs hg (which did effectively the same thing). The comparison is whether you want a modern language with a rich process object and all of the batteries included OR do you want something that exists basically everywhere and is fast? Everyone has their own answer to that question :wink:

**Comment by certik** [comment]
I went through a similar route with SymPy, I tried everything, from Cython, C, PyPy, and in the end just ended up using C++ for SymEngine, and I was able to deliver. All the other approaches fail in various ways.

I like that you just extend Python to be usable as a shell. I think it's the right idea. But if I am forced to choose between speed and Python, I personally choose speed and thus Bash.

I still like Python, and I feel one large problem with it is the slow startup time if you have to import packages (it scans the filesystem a lot and then parses reads tons of files, which is slow). If Python could be (optionally) compiled to static binaries, that would help a lot (also with distribution!). I started [experimenting](https://gitlab.com/certik/python_link) with that idea. It's surprisingly not easy, and I don't even know if that would eventually fix all the issues.

**Comment by scopatz** [comment]
> If Python could be (optionally) compiled to static binaries

That is basically what [nuitka](https://github.com/Nuitka/Nuitka) does, as far as I understand it.

> I like that you just extend Python to be usable as a shell. I think it's the right idea. 

I agree :wink: 

> But if I am forced to choose between speed and Python, I personally choose speed and thus Bash.

I think it is also important to point out that xonsh, while slower than Bash, is still leagues faster than other popular shells.  zsh with oh-my-zsh is painfully slow to startup (multiple seconds).  

So since this is a tradeoff, what factor of speed hit would you be willing to accept?  I am curious.

As always, I would love funding, time, etc. to make xonsh faster.  I think this is definitely a solvable problem.

**Comment by certik** [comment]
You might be right, I need to investigate nuitka, that would be awesome if it worked.

Regarding performance: I would like things to feel "immediate". I think startup might be ok if it is a bit slower (if there is no way to fix it), but the actual usage must be "immediate". If it's so slow that I notice, then that's not good.

I don't have an exact timing that is tolerable per command, but essentially there must not be any human noticeable slow down or glitch. This is not a new problem, see for example: https://stackoverflow.com/questions/6880856/whats-the-minimum-lag-detectable-by-a-human, where there seems to be a consensus that over 100ms is too long for sure, and if this is something that is continuously moving, then the upper limit is something like 10-15ms.

**Comment by scopatz** [comment]
Got it, we can defintiely work to acheive that.

**Comment by useredsa** [comment]
> I 100% agree. We don't want to be slow. We'd love help improving runtimes as much as possible!
> 
> I don't think rewriting xonsh in C++ is the answer (at least not for me personally). I have had a couple of attempts trying to Cythonize ths code base or use nuitka but they genereally don't work.
> 
> Have you tried using xonsh on pypy? I wonder if that is much faster than using CPython.
> 
> I'd also like to point out that xonsh does way more than stock Bash. So, for the moment, it is a matter of tradeoffs. In this way it is different than git vs hg (which did effectively the same thing). The comparison is whether you want a modern language with a rich process object and all of the batteries included OR do you want something that exists basically everywhere and is fast? Everyone has their own answer to that question wink

This is just a stupid question, but how difficult could it be to port it to C++? And more importantly, what are the downsides? I suppose the main benefit would be speed.

**Comment by certik** [comment]
@useredsa we started the effort here: https://github.com/xonsh/minixonsh. I got busy the last few months, but I would like to get to it again eventually.

**Comment by mimi89999** [comment]
The issue seems to be related to how `xonsh` is running commands.
```
+------------------+-----------------+
| xonsh            | 0.9.15          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | debian          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

Please see the attached video:
https://lebihan.pl/files/Peek%2015-04-2020%2019-43.webm
At the end in the second terminal tab running `xonsh` i started hitting enter.

**Comment by scopatz** [comment]
I have an idea about how to make tracing a lot faster, by basically inserting print calls into the AST itself.  It might involve making `trace` a keyword, though.  How do folks feel about this?

**Comment by mimi89999** [comment]
I think that xonsh is unbearably slow even without `trace` and it's noticeably slower even when used as a shell. Is there anything that can be done to make that work faster?

**Comment by scopatz** [comment]
Running xonsh in pypy increases the startup time slightly, but does make it a lot more snappy

**Comment by duncreg** [comment]
Just in the interest of completeness, xonsh feels immediate to me and I was shocked that anyone felt it was slow. The benchmarks quoted above have differences of one half and one quarter of a second! That's getting close to an interval a human can't even perceive the difference of. 

Of course, as with Python, there's the issue of human time vs. computer time. Per @certik 's examples, I'd find myself taking a lot more of my time if I had to work in bash and C++ rather than xonsh and SymPy. 

Finally, for what it's worth, given the mention about @() slowing things down, I rewrote the second benchmark to:

for i in range(1, 51):
    print("i =", i)

and it finished over 3X faster, suggesting the problem is writing xonsh scripts like bash scripts rather than closer to Python. :-)

**Comment by anki-code** [comment]
I'm going to close this issue because comparing xonsh with bash a bit inconsistent. Yes, we want to make xonsh faster but for this we need more solid issues that have ideas for potential PRs.

**Comment by anki-code** [comment]
Just want to leave here the update:
1. We learned to compile xonsh with Nuitka:
    * https://github.com/xonsh/xonsh/issues/2895
    * [xonsh-binary](https://github.com/anki-code/xonsh-binary)
2. We learned to run xonsh with Rust Python: 
    * https://github.com/xonsh/xonsh/issues/5082.
3. Before any talks about speed we need to disable rich prompt and colors with commands_cache because they have costs:
    * [pure xonsh engine](https://github.com/anki-code/xonsh-cheatsheet?tab=readme-ov-file#run-pure-xonsh-engine)
