### ISSUE TITLE
xsh script performance comparing with Python code

### ISSUE THREAD

**Issue by certik** [xonsh/xonsh#3065]
Here is a simple Python code:
```
$ cat test.xsh 
#!/usr/bin/env xonsh

for i in range(1, 51):
    print("i = ", i)
```
So that we can compare how fast Xonsh *could* be running, since Python can run this also:
```
$ time python test.xsh
...
real	0m0.023s
user	0m0.016s
sys	0m0.007s
```
vs
```
$ time xonsh test.xsh
...
real	0m0.199s
user	0m0.163s
sys	0m0.040s
```
As you can see, Xonsh is almost an order of magnitude slower to execute it.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by certik** [comment]
I believe this issue is mostly caused by the startup time.

**Comment by scopatz** [comment]
Thanks for opening this @certik - I wonder where the difference in startup time is coming from here.

**Comment by certik** [comment]
Based on the discussion here:

https://github.com/xonsh/xonsh/issues/3064#issuecomment-499275183

I would clarify that the startup time is not the highest priority in terms of being a dealbreaker for me: startup time only happens every time you open a new terminal (assuming Xonsh is the default shell), but it doesn't happen in the actual usage of Xonsh.

**Comment by con-f-use** [comment]
Just because I don't know where else to post:

I'm having an issue on one of my systems with xonsh startup. Is there a way to profile?

What happens is: 

1. I start xonsh
2. the prompt comes up (pretty fast)
3. I type maybe two letters, then the prompt freezes up for 5-10 seconds.
4. The freeze ends and everything responds normal for there

**Comment by filips123** [comment]
Based on some discussion, I see that Xonsh can be slow becasue of Python. So, I wonder, might it be possible to write and run Xonsh in Cython instead? Would this work faster?

**Comment by certik** [comment]
@filips123 We think even better is to just do it in C++, and we started working on that here: https://github.com/xonsh/minixonsh. If you want to help out, we would appreciate any help.

**Comment by filips123** [comment]
Won't Cython be easier to do as it is similar to Python and some parts can be same?

**Comment by BYK** [comment]
Has anyone checked https://github.com/indygreg/PyOxidizer out? Maybe that'd help?

**Comment by anki-code** [comment]
@certik, the #3459 could be interesting to you for xonsh/minixonsh project.

**Comment by certik** [comment]
@anki-code yes, I've been in touch with the author of the Oil shell. We collaborated on brainstorming how to handle AST for LFortran, and that could also be useful for minixonsh, I was going to reuse the same technology.

**Comment by scopatz** [comment]
I am open to any and all options here!

**Comment by certik** [comment]
@anki-code, thanks for the comment. It seems the general startup slowness is a fundamental issue with using Python and it is indeed not easy to fix. One solution is to compile it, as you also suggested. For compile time utilities, using [LPython](https://lpython.org/) might be a great fit.

**Comment by bestlem** [comment]
re 

> Xonsh startup has additional rich features like loading syntax highlighting, loading xontribs, etc. All of this take time and some things are just not optimal. If you want to have pure bash/zsh experience here just disable all of this. See also xonsh-cheatsheet i.e.

> xonsh --no-rc --no-env -DCOLOR_INPUT=0 -DCOLOR_RESULTS=0 -DPROMPT='@ ' \
      -DXONSH_HISTORY_BACKEND=dummy -DXONTRIBS_AUTOLOAD_DISABLED=1 -st rl

Some of this should not be necessary e.g. COLOR_INPUT PROMPT XONSH_HISTORY_BACKEND=dummy
These all should only be run if $XONSH_INTERACTIVE = True - and that command line should be leaving  XONSH_INTERACTIVE as false. If xonsh is not doing that then that is a bug.
Similarly for that command syntax highlighting (and completion) should not be done again unless interactive 

That is the necessary command for fast loading should only need.
```
xonsh --no-rc --no-env -DCOLOR_RESULTS=0 -DXONTRIBS_AUTOLOAD_DISABLED=1 -st rl
```

**Comment by anki-code** [comment]
Just want to leave here the update:
1. We learned to compile xonsh with Nuitka:
    * https://github.com/xonsh/xonsh/issues/2895
    * [xonsh-binary](https://github.com/anki-code/xonsh-binary)
2. We learned to run xonsh with Rust Python: 
    * https://github.com/xonsh/xonsh/issues/5082.
3. Before any talks about speed we need to disable rich prompt and colors with commands_cache because they have costs:
    * [pure xonsh engine](https://github.com/anki-code/xonsh-cheatsheet?tab=readme-ov-file#run-pure-xonsh-engine)
