### ISSUE TITLE
`conda activate myenv` fails to activate myenv

### ISSUE THREAD

**Issue by pletnes** [xonsh/xonsh#3067]
## xonfig

Manual comments:

- distro is ubuntu 18.04 LTS
- python is from miniconda3
- xonsh is running in a conda environment named `xonsh`.

```
+------------------+-----------------+
| xonsh            | 0.8.12          |
| Python           | 3.7.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

I run `conda activate myenv` and I'd like to see `(myenv)` show up in the prompt, and the `$PATH` updated to push this python environment first.

## Current Behavior

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

But `conda init xonsh` is disappointingly doing nothing:

```
no change     /home/paul/miniconda3/condabin/conda
no change     /home/paul/miniconda3/bin/conda
no change     /home/paul/miniconda3/bin/conda-env
no change     /home/paul/miniconda3/bin/activate
no change     /home/paul/miniconda3/bin/deactivate
no change     /home/paul/miniconda3/etc/profile.d/conda.sh
no change     /home/paul/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/paul/miniconda3/shell/condabin/Conda.psm1
no change     /home/paul/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/paul/miniconda3/lib/python3.7/site-packages/xonsh/conda.xsh
no change     /home/paul/miniconda3/etc/profile.d/conda.csh
No action taken.
```

### Traceback (if applicable)

<details>
```
traceback
```
</details>

## Steps to Reproduce

I've tried two different approaches that both led to the same result. The first was using miniconda3:

0. Install ubuntu 18.04 LTS
1. install miniconda3
2. establish a conda environment called `xonsh` with xonsh installed
3. `conda activate base` then `conda init xonsh`

Base ubuntu python3:

0. Install ubuntu 18.04 LTS
1. `python3 -m pip install xonsh` (winds up in `~/.local/bin/xonsh`; python3 is /usr/bin/python3 from ubuntu)
2. ???
3. `conda activate base` then `conda init xonsh`

**Comment by gforsyth** [comment]
Hey @pletnes -- thanks for reporting.  This is a bug in `conda`, I believe.  In the interim, you can use the `xonda` wrapper xontrib which should work.

**Comment by pletnes** [comment]
Might be, I reported it [here](https://github.com/conda/conda/issues/8274) but no luck in getting any assistance so far. I was worried I reported it in the wrong place.

**Comment by pletnes** [comment]
@gforsyth Ack, xonda looks great on paper, but I'm stuck getting a longish traceback with `No module named 'conda'` tacked on at the end when I do `conda activate myenv`.

```
 ~ λ conda activate jupyter
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
ModuleNotFoundError: No module named 'conda'
```

**Comment by gforsyth** [comment]
Ahh, ok, I just noticed that you're starting `xonsh` from within an environment.  I can try to fix that behavior this week if I find some time.  

The initial bug you posted is definitely a `conda` bug -- I'm planning to try to sort that out at PyCon this year.  

For `xonda`, if you aren't opposed, it will work as expected if you install xonsh into your base environment (where `conda` is also installed).  Alternatively you could try something horrible like pointing your `PYTHONPATH` at the conda folder in your base env `site-packages` but I think that might have unexpected effects...

**Comment by pletnes** [comment]
Amazing, this works great! It would be a nice improvement to put this in the docs though - today, it appears logical to me (from current docs) to put all the `xonsh` stuff in a reproducible environment. Put `environment.yml` in a git repo and you’re good!

I notice `deprecationwarning` from both conda, xonsh and xonda. I think it would be great if these were silenced in «production mode» code.

**Comment by gforsyth** [comment]
Docs PRs are welcome (on the `xonda` side and here) -- I've been a bit swamped and we're also looking to fix the built-in `conda` support so we don't need to maintain additional packages.

You can silence the warnings by adding the following to your `xonshrc` (or by updating the packages that are complaining)
```
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)
```

**Comment by pletnes** [comment]
The warnings trick was sort of obvious in retrospect. Could the `xonfig wizard` suggest it, or could it be put into xonsh? I think it's ugly when you get exceptions/warnings that are very programming-language specific pop up during tab completion... (I'm still a python guy of course).

I'll see what I get around to.

**Comment by scopatz** [comment]
conda v3.7 contains actual first class support for xonsh activation. I am going to close this for now.

**Comment by pyeguy** [comment]
having a related issue to this and a related conda issue: https://github.com/conda/conda/issues/7468 

conda 4.8.3 
xonsh/0.9.18

some environments fail to activate (hangs indefinitely) in xonsh via `conda activate <envname>` but the afflicted env activates fine in bash

also using `xonda` xontrib it will activate properly in xonsh...
