### ISSUE TITLE
test_main fails non-deterministically

### ISSUE THREAD

**Issue by carmenbianca** [xonsh/xonsh#3070]
## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.8.12               |
| Git SHA          | 986bf28d             |
| Commit Date      | Mar 11 14:37:52 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | fedora               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior

The test_main tests run correctly.

## Current Behavior

Some test_main tests fail, sometimes. I run into this while building and testing xonsh for Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1695139

The tests don't always fail, and not always the same tests fail. But when the tests fail, they all have something in common: `AttributeError: module 'builtins' has no attribute '__xonsh__'`

### Traceback (if applicable)

[out.txt](https://github.com/xonsh/xonsh/files/3053525/out.txt)

Spec file added for context:

[xonsh.spec.txt](https://github.com/xonsh/xonsh/files/3053530/xonsh.spec.txt)

## Steps to Reproduce

Run the tests.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Yes, this is defintiely true.  This is likely a bug in pytests and their weird monkey patching.  Additonally since xonsh relies on shoving things into builtints, there is some weird interplay.

**Comment by scopatz** [comment]
Thanks for reporting @carmenbianca

**Comment by jnoortheen** [comment]
I have done some [improvements to the test suit](https://github.com/xonsh/xonsh/pull/4581) . Now the test_main is stable, but the integration tests fail sometimes but have a retry decorator.

**Comment by jnoortheen** [comment]
Feel free to reopen if the issue still appears.
