### ISSUE TITLE
How can I use aliases to change an Environment Variable ?

### ISSUE THREAD

**Issue by Howard-00** [xonsh/xonsh#3071]
If I write 

**aliases ['pon']='$ALL_PROXY = "http://127.0.0.1:1080"'**

in xonshrc, when I run pon it replies

**AttributeError: 'ExecAlias' object has no attribute '__name__'**

And if I write

**aliases ['pon']=['$ALL_PROXY' '=' '"http://127.0.0.1:1080"']**

it replies 

**xonsh: subprocess mode: command not found: $ALL_PROXY="http://127.0.0.1:1080"**

**Comment by gforsyth** [comment]
Hey @Howard-00 -- here's a pattern you can use for this kind of change:

```
 ~ $ $ALL_PROXY
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'Unknown environment variable: $ALL_PROXY'
 ~ $ def _pon():
....     $ALL_PROXY="http://127.0.0.1:8080"
....
 ~ $ aliases['pon'] = _pon
 ~ $ pon
 ~ $ $ALL_PROXY
'http://127.0.0.1:8080'
```

**Comment by laloch** [comment]
It's a bit dirty messing with the `Env` mapping internals, but you can also do
```
aliases['pon']=lambda: ${...}.update({'ALL_PROXY': 'http://127.0.0.1:8080'})
```
