### ISSUE TITLE
Easy way to assign a path with an environment variable to new variable

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3072]
I have a hard time to easily assign a path with an environment variable to new variable:

Say, I have a path in $DOCS (e.g. `/home/data/docs`) and from a bash script I have a construct for a new path like

    MANUAL=$DOCS/rectopa/manual.md

Using the text`$DOCS/rectopa/manual.md` what is an *easy and clean* way to set the new environment variable `MANUAL`? I tried

    MANUAL='$DOCS/rectopa/manual.md'

but it does not expand the `$DOCS` variable. Another idea was

   MANUAL=$DOCS+'/rectopa/manual.md'

It works, but here I have to fiddle with the copied text `$DOCS/rectopa/manual.md`. The best solution I came up with is:

    MANUAL=$(echo -n $DOCS/rectopa/manual.md)

which is neither very short nor clean.

Any other ideas?

**Comment by gforsyth** [comment]
Hey @halloleo, 

I usually assign `pathlib` paths to env-vars for this kind of thing, so you could start with

```
$DOCS = p'/home/data/docs'
```

Then you can do

```
MANUAL = $DOCS / 'rectopa/manual.md'
```

Alternatively, if you have a regular string in `$DOCS` you can add to it

```
> $DOCS='/home/data/docs'
> $DOCS + '/rectopa/manual.md'
'/home/data/docs/rectopa/manual.md'
```

**Comment by gforsyth** [comment]
Also, `p-strings` will expand env-vars, so you can do things like

```
> $DOCS = '/home/data/docs'
> p'$DOCS'
PosixPath('/home/data/docs')
```

**Comment by halloleo** [comment]
Cool, I really like the `p-string` method. I think it is the cleanest solution in this case. 

Anyway, I found another way - using `xonsh.tools`'s function `expand_path`:

    from xonsh.tools import expand_path
    expand_path('$DOCS/rectopa/manual.md')
