### ISSUE TITLE
When using system() in a C++ program to run another program, the keys are terrible.

### ISSUE THREAD

**Issue by Howard-00** [xonsh/xonsh#3074]
I use `system(nvim)` in a C++ program, in bash and zsh, everything is OK. But in xonsh, the keys such as `ESC`  and arrows doesn't work at all. For example, when I click `ESC`, it just shows `^[` but can't be received by nvim. And when I click `i`, it just shows `i`, only after I press `Enter`, nvim turns to `INSERT` mode and adds a newline at the same time.
Is there a way to make it run normally as run directly or in other shells？

**Comment by scopatz** [comment]
Hey @Howard-00 - sorry for taking a while to get back to you on this.  If you add something like the following to your xonshrc or your current session:

```
__xonsh__.commands_cache.threadable_predictors['my-cpp-program'] = lambda *args, **kwargs: False
```

It will disable automatically running the command in a separate thread, and therefore inadvertantly capturing the escape codes.

**Comment by gforsyth** [comment]
Closing this out as answered but please ping with any additional questions, @Howard-00 .
