### ISSUE TITLE
How do I debug a xonsh script?

### ISSUE THREAD

**Issue by ndemou** [xonsh/xonsh#3090]
I'm looking for something like "python -m pdb" or "bash -x" but didn't find it in the docs.

**Comment by laloch** [comment]
You can use the `pdb` module in the same way as you would do in Python REPL:
```
$ import pdb
$ source your_script.xsh
$ pdb.run('your_func("some args")', globals=globals())
```

**Comment by ndemou** [comment]
Thanks laloch! 
Is there a way to use pdb without refactoring small quick'n'dirty scripts to have all the logic inside a function[1]? For the moment I'm adding two lines to misbehaving scripts (`from pdb import set_trace as breakpoint` at the top and a `breakpoint()` before the problematic lines) but I miss the convenience of `python -m pdb script`.

_____________
[1] I'm usually sloppy with small xonsh/bash/python scripts: global vars, no main function -- I just want to try an idea without investing too much time until I'm sure it works and is gonna be needed for more that a few hours/days.

**Comment by ndemou** [comment]
BTW is this (the issue tracker) a good place for questions like this?

**Comment by scopatz** [comment]
@ndemou - yep the issue tracker is a good place for these scripts.  We certainly could do more to make debugging easier.  PRs most welcome

**Comment by anki-code** [comment]
I add that there are `XONSH_DEBUG` and `XONSH_TRACE_SUBPROC` env vars too.

Looks like this issue could be closed.

**Comment by anki-code** [comment]
Profiling with samply - https://github.com/mstange/samply/issues/743
