### ISSUE TITLE
Uncaptured subprocess hangs indefinitely

### ISSUE THREAD

**Issue by haqle314** [xonsh/xonsh#3097]
If I run a plain command like `ls`, it blocks indefinitely (doesn't response to SIGINT). Nothing is outputted regardless of the value of `$XONSH_DEBUG`. On the other hand, something like `$(ls)` works perfectly.
From the `strace` output, it looks like something is failing to write to stdout. `strace` will print this block repeatedly when the process hangs.

    write(1, "\33]0;ls | hle@crimson: ~ | xonsh\7", 32) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
    --- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
    getpid()                                = 9171
    rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)

I'm running `xonsh` inside a `conda` environment

    >>> xonfig
    +------------------+-----------------+
    | xonsh            | 0.8.12          |
    | Python           | 3.6.8           |
    | PLY              | 3.11            |
    | have readline    | False           |
    | prompt toolkit   | 2.0.9           |
    | shell type       | prompt_toolkit2 |
    | pygments         | 2.2.0           |
    | on posix         | True            |
    | on linux         | True            |
    | distro           | unknown         |
    | on darwin        | False           |
    | on windows       | False           |
    | on cygwin        | False           |
    | on msys2         | False           |
    | is superuser     | False           |
    | default encoding | utf-8           |
    | xonsh encoding   | utf-8           |
    | encoding errors  | surrogateescape |
    +------------------+-----------------+

    >>> {tup[0]:tup[1] for tup in ${...}.items() if tup[0].startswith("XONSH")}
    {'XONSHRC': EnvPath(
    ['/etc/xonshrc',
    '/home/hle/.config/xonsh/rc.xsh',
    '/home/hle/.xonshrc']
    ),
    'XONSH_APPEND_NEWLINE': True,
    'XONSH_AUTOPAIR': True,
    'XONSH_CACHE_EVERYTHING': False,
    'XONSH_CACHE_SCRIPTS': True,
    'XONSH_COLOR_STYLE': 'default',
    'XONSH_CONFIG_DIR': '/home/hle/.config/xonsh',
    'XONSH_DATA_DIR': '/home/hle/.local/share/xonsh',
    'XONSH_DATETIME_FORMAT': '%Y-%m-%d %H:%M',
    'XONSH_DEBUG': 0,
    'XONSH_ENCODING': 'utf-8',
    'XONSH_ENCODING_ERRORS': 'surrogateescape',
    'XONSH_HISTORY_BACKEND': 'sqlite',
    'XONSH_HISTORY_FILE': '/home/hle/.xonsh_history.json',
    'XONSH_HISTORY_MATCH_ANYWHERE': False,
    'XONSH_HISTORY_SIZE': (8128, 'commands'),
    'XONSH_INTERACTIVE': True,
    'XONSH_LOGIN': True,
    'XONSH_PROC_FREQUENCY': 0.0001,
    'XONSH_SHOW_TRACEBACK': False,
    'XONSH_STDERR_POSTFIX': '',
    'XONSH_STDERR_PREFIX': '',
    'XONSH_STORE_STDIN': False,
    'XONSH_STORE_STDOUT': False,
    'XONSH_TRACEBACK_LOGFILE': None,
    'XONSH_VERSION': '0.8.12'}

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for reporting @haqle314.  It is a little unclear to me what command exactly you are running.  Can you please clarify exactly what you type in?

**Comment by haqle314** [comment]
Hi, `ls` is the exact input. But that's just an example, any command will do the same thing for me.

**Comment by gforsyth** [comment]
Hey @haqle314 -- which distro are you running?

**Comment by haqle314** [comment]
I'm running Gentoo but I installed `xonsh` through `conda` instead of the system package manager.

**Comment by scopatz** [comment]
from the conda-forge channel?

**Comment by haqle314** [comment]
Yes, that's right.

**Comment by scopatz** [comment]
That is super weird

**Comment by anki-code** [comment]
Hi @haqle314!
Could you please update the xonsh version and try to repeat the error?

**Comment by anki-code** [comment]
Closed until new info.
