### ISSUE TITLE
$COMPLETIONS_MENU_ROWS has no effect in some circumstances

### ISSUE THREAD

**Issue by shadow-light** [xonsh/xonsh#3104]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.8.12               |
| Git SHA          | 986bf28d             |
| Commit Date      | Mar 11 14:37:52 2019 |
| Python           | 3.6.8                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior
Lines are reserved at bottom of terminal for completion options to be displayed.

## Current Behavior
Lines are not reserved when all completion options have a common prefix.

## Steps to Reproduce
 1. Produce any output until prompt is at bottom of window
 2. Try `git sh<tab>`
     * The 'o' is common to all the options and results in no reserved space for display
 3. Try `git sho<tab>`
     * There is no common prefix to all the options and so space is reserved

The offending code is here: https://github.com/xonsh/xonsh/blob/4f48345fa21836364783e0fb11d3a9fbba65c328/xonsh/ptk2/completer.py#L62

It seems it can simply be removed, but I'm assuming someone put it there for a reason. Any idea why? Otherwise please remove that logic.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for reporting this @shadow-light! I am taking a look at this now.

**Comment by scopatz** [comment]
So I am a little confused by this issue exactly.  When you type `git sh<TAB>`, the `o` is added.  There is no need to reserve space because the completer can fill in a value as much as possible

**Comment by gforsyth** [comment]
I think I started to write out a response to this issue a while ago and then forgot to actually comment. I had the same reaction @scopatz. But my second thought which I was just reminded of is that there's an alternate possible behavior, which is to complete the common prefix and then reserve space for showing the remaining options (except in the case where the common prefix exactly matches one of the possible results, in which case a second tab strike would be required). 

I don't think this is what most shell completers do, but it might be nice to have.

**Comment by shadow-light** [comment]
Hmm, so xonsh's current behaviour for me is to display the possibilities after a single tab. So `git sh<TAB>` for me both adds the `o` **and** shows `shortlog/show/show-branch`. Two tabs are not required.

Here's my xonfig:
```
+------------------+----------------------+
| xonsh            | 0.8.12               |
| Git SHA          | 986bf28d             |
| Commit Date      | Mar 11 14:37:52 2019 |
| Python           | 3.6.8                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

I also have `$COMPLETIONS_CONFIRM = 1` set.

**Comment by gforsyth** [comment]
Riiight, ok, I remember this now.  We _do_ complete the common prefix and then show the remaining completions in a dropdown, but in this instance the dropdown isn't displayed because we aren't reserving the space for it.

**Comment by scopatz** [comment]
Oh I see, it could do the fill in and then show the remaining completions.  I think that is more complex than what was proposed for removing the two lines.

**Comment by scopatz** [comment]
but maybe not much more.
