### ISSUE TITLE
Feature request: Add ways to do auto-split on results.

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#311]
The example given in #310 :
```python
for fname in $(ls).split():
   print(fname)
```
requires a `.split()` because xonsh does not split automatically the results on space.
To minimize typing I would welcome a way to add the `.split()` under the hood of xonsh, either with a new operator, maybe `lss` ?

Possibly there are several other standard bash operators that would require this, the question would be, would they all require a sister-operator that includes splitting on space, or would it be helpful (or too costly in performance?) to look up a global variable that stores if the user wants the splitting on space for all results? 
Let me ask the other way around: 

* What could go wrong if results are always split on whitespace? 
* Does this maybe depend on the system call that is being used? 
* Maybe there are bash/system results that include newlines that possibly should always be split on? Then this would be a per-operator decision potentially?

**Comment by scopatz** [comment]
I'll give my two cents here. So I think that this is a place that just reimplementing Bash is wrong.  Bash will always capture and split together, even though these are two operations.  This is because a core concept of Bash is to always split.  However, in Python these are separate ideas. Capturing an then splitting is much more natural from a data flow perspective.  You may, for example, what to capture some process that returns something that isn't whitespace separated, such as CSV or JSON.  In xonsh, you can capture and then parse using another mechanism.  The core concept in xonsh is to treat these as separate operations.

I agree that sometimes, like in the example above, it might be convenient to automatically split. But I think that this should be different syntax. It is not entirely clear what this syntax should be, but I am open to suggestions.  It wouldn't be hard to add.

**Comment by asmeurer** [comment]
I think it would be more useful if `ls` (or some equivalent) returned a list. Maybe it would be better practice to make use of os.path or pathlib.

**Comment by michaelaye** [comment]
If I understand you correctly, you agree to implementing split on whitespace where deemed useful, but not on a general level?

**Comment by scopatz** [comment]
@michaelaye @asmeurer - yes.  I agree that this would be a useful thing to have, but it is not a fundamental abstraction.  We'd need some alternate syntax to represent this.  For examplem `$<ls>` might be ok.

**Comment by michaelaye** [comment]
*blarg* if xonsh starts to look like Perl in terms of extra required characters, it's not for me. Why not this: add an `s` to any command to get it's output split at white-space?

**Comment by scopatz** [comment]
What do you mean?

**Comment by scopatz** [comment]
I don't understand the syntax you are proposing.

**Comment by michaelaye** [comment]
`ls` returns a string, `lss` returns a list.

**Comment by scopatz** [comment]
That poses a lot of problems and ambiguity.  There might be a command on the system that is already called `lss`, or whatever.

**Comment by scopatz** [comment]
This might be a better discussion for the mailing list.

**Comment by ns-phennessy** [comment]
I too would like to see something like this. 

```python
for playbook in $(find . -name playbook.*).split('\n'):                                                                                                                            
    print(playbook)                                                
``` 

I find the above code inconvenient, would rather just be able to take output from a subshell and use it as an iterable. If we capture it into a variable; then it would be up to us to split

Would it be possible to split by new line on the `__iter__` method on strings returned from a subshell?

**Comment by adqm** [comment]
It is possible now (on master) after #1183, with the following syntax:


```
for playbook in !(find . -name playbook.*):
    print(playbook)
```

**Comment by melund** [comment]
My first thought was that we could do it with `@$`:
```
snail@sea ~\Documents $ for x in @$(find scratch -name file*):
.......................     print(x)
```
But that is only enabled for subproc mode. I completely forgot about  `!()`.

**Comment by ns-phennessy** [comment]
@adqm that worked for me but I saw a bunch of extra stuff at the end of the loop:

```
7763
0
['find', '.', '-name', 'playbook.*']
None
None
None
None
(1466018424.19756, 1466018424.2133446)
```

As I understand that `!()` is supposed to give us more verbose output about the command being run; but really this loop is only concerned with the actual stdout of the command

**Comment by melund** [comment]
Yes. I can see that it is a little confusing. `!()` returns a CompletedProcess object. It does have all information of the process. But it also implements the iterator protocol, which only loops over lines in stdout.

**Comment by ns-phennessy** [comment]
I think that iter also grabbed a bunch of meta data about the process too. Should that iter only return stdout?

**Comment by melund** [comment]
Yes. That is how I understood it. I didn't follow that PR very closely.  You can see the docs here: https://github.com/xonsh/xonsh/pull/1183/files#diff-4d9b827ea9acd34bb46c7b7354630920R359

**Comment by adqm** [comment]
@ns-phennessy, are you running from current master (not the most recently released version)?  What you're describing sounds like it would have been what happened in the current 0.3.4 release, but not on master.

**Comment by ns-phennessy** [comment]
@adqm 

```
[phennessy : ~]$ xonfig
+------------------+----------------+
| xonsh            | 0.3.3          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.1            |
| on posix         | True           |
| on linux         | True           |
| distro           | Ubuntu         |
| on darwin        | False          |
| on windows       | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
```

i installed xonsh from master like 2 weeks ago

**Comment by adqm** [comment]
Right. The addition of the nice way to loop over stdout was added since then.  I would recommend updating.

**Comment by ns-phennessy** [comment]
I don't own this ticket but i'd call it resolved :)

**Comment by scopatz** [comment]
Alright, closing :).  Feel free to reopen.
