### ISSUE TITLE
[SOLVED] syntastic: error: exception running system uname under xonsh

### ISSUE THREAD

**Issue by ExileInParadise** [xonsh/xonsh#3111]
With xonsh as my login shell, vim-syntastic throws the following error when starting to vi files:
$ vi def_check_file.py 
syntastic: error: exception running system('uname'): Vim(let):E484: Can't open file /tmp/vqhzk40/0
Error detected while processing function syntastic#util#system:
line   19:
E121: Undefined variable: g:_SYNTASTIC_DEBUG_CHECKERS
E116: Invalid arguments for function syntastic#log#debug
Press ENTER or type command to continue

## xonfig
Not needed - is not xonsh issue directly
<details>
```
$ xonfig
```
</details>

## Expected Behavior

vim-syntastic should open to edit the file without syntastic errors.

## Current Behavior

See error above
 
### Traceback (if applicable)
Not needed here
<details>
```
traceback
```
</details>

## Steps to Reproduce

On Fedora 29
With vim-syntastic installed
In xonsh current
Do vi file

## WORKAROUND/FIX
Add the following line to the top of $HOME/.vimrc
set shell=/bin/bash

SEE ALSO:
The syntastic issue thread that put me onto this workaround/fix:
https://github.com/vim-syntastic/syntastic/issues/2013

Throwing this here in case others run into this issue.
Apparently syntastic excepts specific system() behavior which is supported by bash but not other shells such as fish or xonsh.
Telling syntastic that you're on bash explicitly, when you're not seems to satisfy it and avoid the errors getting thrown.

**Comment by john9631** [comment]
I had a similar issue running the ion shell.   The suggested solution solved the problem.
