### ISSUE TITLE
source-bash  $(/usr/libexec/path_helper -s) does not only  run the path_helper output

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3146]
I try to simplify my path management in different shells, for this I want to make the output of `/usr/libexec/path_helper` available in xonsh.

So I tried following the documentation

    source-bash  $(/usr/libexec/path_helper -s)

and, yes, `$PATH` and `$MANPATH` get updated as I expect but additionally I get the following warning messages:

```
Skipping application of 'dqr' alias from 'bash' since it shares a name with an existing xonsh alias. Use "--overwrite-alias" option to apply it anyway.You may prevent this message with "--suppress-skip-message" or "$FOREIGN_ALIASES_SUPPRESS_SKIP_MESSAGE = True".
Skipping application of 'mdfn' alias from 'bash' since it shares a name with an existing xonsh alias. Use "--overwrite-alias" option to apply it anyway.You may prevent this message with "--suppress-skip-message" or "$FOREIGN_ALIASES_SUPPRESS_SKIP_MESSAGE = True".
```

`dqr` and `mdfn` are aliases I define separately in `.xonshrc` and in `.bashrc`. Obviously these aliases are not in the output of `path_helper`, so I assume `source-bash` starts a bash with the standard dot files, but I want bash to run only the output of `path_helper`. Any way to achieve this?

### xonfig

<details>
```
+------------------+----------------------+
| xonsh            | 0.8.12               |
| Git SHA          | 986bf28d             |
| Commit Date      | Mar 11 14:37:52 2019 |
| Python           | 3.7.1                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | dumb                 |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```
</details>

**Comment by scopatz** [comment]
Thanks for reporting @halloleo 

`source-bash` shouldn't be running with the `.bashrc` (depending on how your system is set up.)  You can see the script that source-bash runs via `source-bash --dry-run --show $(/usr/libexec/path_helper -s)`. Maybe `$(/usr/libexec/path_helper -s)` is sourcing something that is causing this?

However, you should be able to pass arguments down to the bash invocation with `--extra-args`.  So something like `source-bash --extra-args "--norc" $(/usr/libexec/path_helper -s)` might work

**Comment by halloleo** [comment]
Sorry, I'm not on macOS at the moment will look at this on the weekend.

**Comment by eppeters** [comment]
I think what is happening is that your shell run-control (`.bashrc`) file is being sourced by the call to `source-bash`, which is the default.

However, you can pass `--interactive false` to `source-bash` and avoid sourcing this:

```
eddie@eddie-ubuntu ~ $ source-bash --help                                                                                                         
...omitted for brevity...
  -i INTERACTIVE, --interactive INTERACTIVE
                        whether the sourced shell should be interactive
...omitted for brevity...
```

If you want your `source-bash` calls to be non-interactive by default, which it sounds like you do, then you can add the following alias to your `.xonshrc`:

```
aliases['source-bash'] = aliases['source-bash'] + ['--interactive=false']
```

Hope this helps!

**Comment by halloleo** [comment]
Thanks @eppeters!

That's exactly it: `--interactive=false` is clear, clean and does the trick!

**Comment by scopatz** [comment]
Awesome! Thanks @eppeters! @halloleo - is this OK to close now?

**Comment by halloleo** [comment]
Yep, only thing might be to add it to the docs...

**Comment by sbliven** [comment]
In xonsh 0.12 the command is now `source-bash -n file.sh`
