### ISSUE TITLE
How can I replace Bash with Xnosh in Ubuntu?

### ISSUE THREAD

**Issue by blueray453** [xonsh/xonsh#3153]
I am using Linux Mint 19.1 based on Ubuntu 18.04

I want to replace Bash with Xnosh.

How can i do that?

**Comment by scopatz** [comment]
Hi @blueray453 - does this answer your question? https://xon.sh/customization.html#set-xonsh-as-my-default-shell

**Comment by blueray453** [comment]
Thanks. This answers my question.

**Comment by scopatz** [comment]
Awesome!
