### ISSUE TITLE
Moving content of folders with space .

### ISSUE THREAD

**Issue by RomuloPBenedetti** [xonsh/xonsh#3158]
Moving folder's content not working, even with the "in doubt quote it" rule  :smile:  when the folder name contains spaces, tried:

    mv "my folder/*" .
    mv "my folder"/* .

## xonfig

<details>

    +------------------+----------------------+
    | xonsh            | 0.8.12               |
    | Git SHA          | 986bf28d             |
    | Commit Date      | Mar 11 14:37:52 2019 |
    | Python           | 3.7.3                |
    | PLY              | 3.11                 |
    | have readline    | True                 |
    | prompt toolkit   | 2.0.9                |
    | shell type       | prompt_toolkit2      |
    | pygments         | 2.3.1                |
    | on posix         | True                 |
    | on linux         | True                 |
    | distro           | fedora               |
    | on darwin        | False                |
    | on windows       | False                |
    | on cygwin        | False                |
    | on msys2         | False                |
    | is superuser     | False                |
    | default encoding | utf-8                |
    | xonsh encoding   | utf-8                |
    | encoding errors  | surrogateescape      |
    +------------------+----------------------+

</details>

## Expected Behavior

Should move the folder content to parent.
    
## Current Behavior

it fails with:

    /usr/bin/mv: cannot stat 'my folder/*': No such file or directory

**Comment by gforsyth** [comment]
hmm, thanks for reporting @RomuloPBenedetti !  

That `mv "my folder/*"` doesn't work doesn't surprise me, but I thought that `mv "my folder/"*` would.  In the interim, one workaround is to use xonsh glob backticks to handle this.  That way the `*` will be explicitly treated like a glob-expansion.

```
mv g`my folder/*` new_dest
```

**Comment by RomuloPBenedetti** [comment]
Thanks @gforsyth, I used regex in the mean time:

    mv `my folder/.+` .

**Comment by halloleo** [comment]
Yes, this problem has frustrated me too!

There are two separate issues here, I think:

1. **Asterisk inside the quotes** (e.g. `'my folder/*'`)

    In that case you'd hope the string gets as is pass to the command - and the command might be able to deal with the glob pattern.

    An this varies with command and platform: For erxample on Linux `ls` is not able to deal with it, while on Windows `ls` (from the [GOW distribution](https://github.com/bmatzelle/gow)) _is_ able to handle the asterisk.

2. **Asterisk outside the quotes** (e.g. `'my folder/'*`)

    Here xonsh should do globbing - but for me it does do so on any platform. Not sure why...

**Comment by RomuloPBenedetti** [comment]
@halloleo  Hum, I don't understand what you mean ... it works perfectly, it is the expected behavior in bash, single quotes will escape almost everything and commands do no expansion internally.

But xonsh confused me a bit at first as `mv "my folder/"*` was not working so I started trying everything even "my folder/*" :sweat_smile: as I'm still familiarizing with Xonsh syntax.

Apparently Xonsh do some special expansions cases like bash, as `ls "$HOME"` what is fine if consistency is maintained, anyway I believe now I know what to expect:

`$` expansion in `strings ` (" " or ' ')
no expansions on `raw strings` (r" " or r' ')
python regex globbing in `Regular Expression Globbing`  (\` \`)
normal globing in `Normal Globbing` (g\` \`)
and well, normal globing without special syntax in subprocess mode will need to be fixed. :)

**Comment by scopatz** [comment]
We have had a lot of discussion on this topic in the past, which resulted in this part of the tutorial: https://xon.sh/tutorial_subproc_strings.html  I hope this helps clarify things!

**Comment by halloleo** [comment]
I don't understand fully your point, @scopatz. 

If I am not mistaken, this is not so much how strings with spaces are treated, but rather how to tell the xonsh shell what to do with glob strings: Either
* xonsh does the default globbing and passed the candidates to the command (**case 1**)
or
* xonsh passes the string with globbing characters to the command - so the command does the globbing (**case 2**)

I though if the asterisk is _outside_ the quotes xonsh does case 1 and when _inside_ the quotes xonsh does case 2. But what ever seems to be happening **xonsh needs ways to enable both cases.**

**Comment by RomuloPBenedetti** [comment]
The point is documentation or behavior must change as normal globing is not always guaranteed in subprocess mode without any special syntax.

**Comment by scopatz** [comment]
I think the point here is about how & when strings are expanded. We have a couple of general rules, such as "Python always wins", which means we won't be doing funny things with strings that Python itself doesn't allow.

However, @RomuloPBenedetti is right that we do perform string `$` expansion in subprocess mode, which is turned off for raw strings. We probably should extend this to include globbing for consistency and is likely an oversight.  That would mean that, 

* `echo "a space/*"` would expand properly
* `echo "a space/"*` would NOT expand because `"a space/"*` is actually equivalent to `'"a space/"*'` as per the docs
* echo g`a space/*` will always work, because you are expliclty asking for a glob.

**Comment by scopatz** [comment]
I'd happily review / merge a PR that fixes this issue.

**Comment by RomuloPBenedetti** [comment]
> "a space/"* is actually equivalent to '"a space/"*' as per the docs

Ok I missed macros documentation... got it now, Advanced Path Search with Backticks can be confusing without extra context

**Comment by halloleo** [comment]
> ...hat would mean that,
> 
>     * `echo "a space/*"` would expand properly
> 
>     * `echo "a space/"*` would NOT expand because `"a space/"*` is actually equivalent to `'"a space/"*'` as per the docs
> 
>     * echo `` g`a space/*` `` will always work, because you are explicit asking for a glob.

Sounds sensible to me. For consistent I just want to add what you mentioned separately:

* `echo r"a space/*"` does NOT expand.
AddingI'

**Comment by astronouth7303** [comment]
Could we not do this? Like, having an explicit "please glob this" syntax is pretty ok? And plenty of commands accept unprocessed globs and regexes as an argument. (eg, `find -name "*.jpg"`)

**Comment by scopatz** [comment]
Yeah that is a fair point, @astronouth7303.  I am pretty happy with the fact that putting explicit strings ignors most expansions.

I wonder if this should be an env var, like [`$EXPAND_END_VARS`](https://xon.sh/envvars.html#expand-env-vars), whose default is false.

**Comment by astronouth7303** [comment]
I'm a fan of not? Especially as xonsh as an ecosystem grows, language consistency is important?

**Comment by halloleo** [comment]
@scopatz You write:

> I wonder if this should be an env var, like [`$EXPAND_END_VARS`](https://xon.sh/envvars.html#expand-env-vars), whose default is false.

If I see this correctly a switch toggled by an env var is a pretty blunt instrument - I think it should be a *syntax* thing like using normal strings (doing the globbing) and raw strings (not doing the globbing). But maybe I overlook something here.

**Comment by astronouth7303** [comment]
That's pretty much what we're doing now? Backticks are a globbed string, quotes are unglobbed. See https://github.com/xonsh/xonsh/wiki/Cheatsheet#globbing and https://xon.sh/tutorial.html#advanced-path-search-with-backticks

**Comment by halloleo** [comment]
Yes, these options are available. However for path names *without* spaces there is another rather natural option to request shell globbing: Typing the path including the asterisk without quotes, but this is not available for paths with spaces. 

Maybe we just live with the fact that in the case names with spaces only the g`..` style for shell globbing is available...

**Comment by astronouth7303** [comment]
That's how most shells work? Unquoted globs work, but if you need a glob with special characters (spaces or other), you need to quote it.

Xonsh has an added variant where r-strings are untouched, other strings have variable expansions, and backticks have variable and glob expansion.

**Comment by RomuloPBenedetti** [comment]
The current behavior is fine to me, xonsh do not need to pursue aggressively to be like other shells but I believe there should exist a attention mention of  `The Quotes Stay` in `Advanced Path Search with Backticks` for those that pass a quick eye through documentation as I did and are not aware of the existence of the extra outer layer quotation when leading and trailing quotes are not matched.

**Comment by daniel-shimon** [comment]
Closing this since back ticks solve it and are explained in https://xon.sh/tutorial.html#advanced-path-search-with-backticks
