### ISSUE TITLE
Question: Running a command unaliased

### ISSUE THREAD

**Issue by Meptl** [xonsh/xonsh#3164]
Is there a way to perform a command while explicitly ignoring aliases? This would be similar to bash's backslash prefix. In bash `\ls` would run the `ls` command regardless of what aliases are in place.

My use case is for adding personal hooks into existing commands. The issue is that I want my command to keep the name of the original commands, but I can't do so without being able to call the original, unaliased command. For example, trying to always run `echo 3` after `cd`

Initially I tried:
```
def mycd(args, stdin=None):
    x = !(cd @(args))
    if x.returncode == 0:
        echo 3
    return x.returncode

aliases['cd'] = mycd
```
but expectably this ended up causing an infinite loop - the alias was calling the newly aliased version of cd. I was able to solve this particular problem by calling the underlying cd function like so:
```
def cdls(args, stdin=None):
    stdout, stderr, exit_code = __import__('xonsh').dirstack.cd(args, stdin)
    if exit_code == 0:
        echo 3
    return stdout, stderr, exit_code

aliases['cd'] = cdls
```

I'm looking to do this for other commands that don't have the xonsh builtin fallthrough.

**Comment by gforsyth** [comment]
Hey @Meptl -- good question!  You can use `which -s` to return a matching element in `$PATH` ignoring any matches in `aliases` so you can avoid the infinite lookup.  

```
gil@badcatredux ~/tmp $ which ls                                                              
ls --color=auto -v
gil@badcatredux ~/tmp $ $(which -s ls) -F                                                     
'a space'/   nospace/
gil@badcatredux ~/tmp $ _.inp                                                                 
'/usr/bin/ls -F'
```

**Comment by Meptl** [comment]
Doh! Should've thought of that one. Thanks very much! If there's a need to document this, I'm willing.
