### ISSUE TITLE
XSH importer fails with zips

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#3171]
Experimenting with #3170, I found that the xontrib `prompt_ret_code` doesn't load, even if its included in the zipapp.

It also fails to import directly.

`prompt_ret_code` is the only xontrib I'm including that uses a `.xsh` instead of a `.py`.

So I think `xontrib.imphooks` is missing zip support somehow, but I'm not certain what?

**Comment by astronouth7303** [comment]
It's also failing to import xontribs from the filesystem? Some kind of namespace package problem?

**Comment by scopatz** [comment]
Is `prompt_ret_code.xsh`  present in the zip?

**Comment by scopatz** [comment]
And do you mean `xonsh.imphooks`?

**Comment by astronouth7303** [comment]
Yeah, it's getting packaged up. You can grab a copy for yourself from https://gitlab.com/doyouevenclick/xonsh/pipelines .

I mean the thing that allows `.xsh` files to be imported as Python modules, which the xontrib machinery implicitly depends on.

**Comment by astronouth7303** [comment]
`xontrib.lib.{os,subprocess}` won't load either.

**Comment by astronouth7303** [comment]
Found the problem,

https://github.com/xonsh/xonsh/blob/8c173facfaf9afcf44527f57108a1ed4f3e663e9/xonsh/imphooks.py#L119-L120

I feel like the real solution is to use more of `importlib.machinery` instead of reproducing logic, but it's not super clear how zip importing works or what classes should be used?

**Comment by astronouth7303** [comment]
Oh, it's in [`zipimport`](https://docs.python.org/3/library/zipimport.html) which is a native module, which are often terrible to extend/subclass.

**Comment by astronouth7303** [comment]
My work around for this for my zipapp work is to just copy the bundled xsh xontribs to the user's xonsh venv when creating it.

**Comment by scopatz** [comment]
Is there somethign we can do to help here?

**Comment by astronouth7303** [comment]
If anyone remember the mechanics of `importlib` and stuff? Basically, everything in `zipimport` needs to be either wrapped or reimplemented.

There was a python implementation of it floating around, but it was described as bloated.

**Comment by scopatz** [comment]
Yeah, I though there had to be a native implementation in CPython

**Comment by anki-code** [comment]
I'm going to close this with reference to https://github.com/xonsh/xonsh/issues/3205#issuecomment-797330652
