### ISSUE TITLE
I'd like to port zdharma/history-search-multi-word to xsh, where do I start?

### ISSUE THREAD

**Issue by NorthIsUp** [xonsh/xonsh#3177]
https://github.com/zdharma/history-search-multi-word

Zsh has an awesome search/autosuggest plugin that lets you easily scroll through options and also see more than one option at a time.

Where is the best place to start implementing this?

**Comment by astronouth7303** [comment]
Structured as a xontrib, hooking either ptk or the completion framework.

The `jedi` xontrib may give some hints, as well as the various tab completion xontribs.

**Comment by laloch** [comment]
@NorthIsUp, you might want to check fzf-widgets xontrib. It uses http://github.com/junegunn/fzf as a backend with all its whistles and blows. If the "official" version would not work for you (esp. list item selection would not yield any output), you may try [my fork](https://github.com/laloch/xontrib-fzf-widgets) of the xontrib.

**Comment by NorthIsUp** [comment]
awesome, this is most of what I want. I do find it is a bit slow, is that a my setup thing or does history search take a bit of time to load normally?

**Comment by NorthIsUp** [comment]
regarding speed: I was playing around with `fzf` and it seems that `fzy` is much faster (and does less). So I'm playing with making the tool pluggable. Once its working I'll share up.

**Comment by laloch** [comment]
> I do find it is a bit slow, is that a my setup thing or does history search take a bit of time to load normally?

I don't observe any noticeable slowdowns on either of my workstations in `fzf` history serach. There are indeed slowdowns in <kbd>Ctrl</kbd>+<kbd>t</kbd> file name search, but that's due to the `fzf` doing a recursive file system search.

**Comment by NorthIsUp** [comment]
after some searching I'm thinking my performance is not the norm, fzf takes seconds to load

(on macOS 10.14.5)


```
# to make the enter fast I just held down the enter key.
echo "hi\nho" | time fzf
hi
        2.79 real         0.00 user         0.00 sys
```

**Comment by NorthIsUp** [comment]
and what I came up with: https://gist.github.com/NorthIsUp/4564b834147bee4afbaa80435e6b0bd9

it has a class to keep the history warm if you are using the default json history module. and it should be easier to extend.
