### ISSUE TITLE
Is there any simple way to tell xonsh to run a command as shell?

### ISSUE THREAD

**Issue by dclong** [xonsh/xonsh#3186]
I got an error running the following shell command. I think it is because xonsh confused the command as a Python statement. Of course, I can wrap the command into `os.system` to run it as shell. But is there a even simpler way to do this? For example, IPython allows users to prefix a command with `!` to run it as shell command.
```
pip3 install dask[complete]
```

**Comment by gforsyth** [comment]
Hi @dclong -- you can wrap a command in `$[]` to force it to run as a subprocess.  For this particular example, wrapping the final argument in quotes should do the trick, so

```bash
python -m pip install "dask[complete]"
```

**Comment by dclong** [comment]
@gforsyth Thank you for much for the tips!
