### ISSUE TITLE
different output in python evaluation command `@(...)` and python w/o evaluation

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3188]
## config
`windows x64 7`, `Python 3.7.3`, `xonsh/0.9.6`

## details
*With out evaluation*
```
import shutil
shutil.copyfile('c:/aaa', 'c:/bbb')
```
**Output**:
```
'c:/bbb'
```

*With evaluation*:
```
# call from pipe
def pcall(args):
  args.pop(0)(*args)

import shutil
@(pcall, shutil.copyfile, 'd:/aaa', 'd:/bbb')
```
**No output**

In the same time the `print` does work as expected:
```
@(pcall, print, 123)
```
**Output**:
```
123
```

**Updated:**
As stated here: https://xon.sh/tutorial.html#uncapturable-aliases
I have tried to use uncaptured variant:
```
import xonsh

@xonsh.tools.uncapturable
def pcall_nocap(args):
  args.pop(0)(*args)

import shutil
@(pcall_nocap, shutil.copyfile, 'd:/aaa', 'd:/bbb')
```
Bit it didn't work either.

## Expected Behavior
The same output as w/o python evaluation.

## Current Behavior
In case of piped call the output is silenced.

**Comment by laloch** [comment]
Hi @andry81, this is because the `@()` python evaluation operator returns a python object, but does not print anything by itself. The behavior is different at the command line, because the Xonsh/Python REPL prints out the `__repr__()` value of the last expression.

**Comment by andry81** [comment]
All I wanted is to auto log any arbitrary script or a function:
```
def foo(args):
  ...
  # any valid code here
  ...

# call from pipe
def pcall(args):
  args.pop(0)(*args)

@(pcall, foo, 123) | ./wtee.exe .log123
```

It loses the output because of the `@(...)` operator and so draws the piping feature useless for auto log any arbitrary code.

**Comment by scopatz** [comment]
I think what you want is something like:

```
def pcall(args, stdin=None, stdout=None):
    print(args.pop(0)(*args), file=stdout)
```  

You may also be able to get away with the following if you think you'll usually be returning string.

```
def pcall(args):
    return args.pop(0)(*args)
```

Does this work for you @andry81?  Basicually, you have to tie the output to the command that you are running. xonsh shouldn't inspect and rewrite arbitrary Python functions to grab what it thinks their output should be, so the callable aliases need to be explicit in what is printed/returned.

**Comment by andry81** [comment]
My point was that the print w/o `file=stdout` argument should behave like the print with the `file=stdout` argument only when a user tries to redirect the output or output is already redirected, because a user expects that, and because a user can't rewrite the code and replace all the print function calls to the proposed one with the necessary argument.

**Comment by scopatz** [comment]
print does behave that way.  But for function which don't print, you either need to print or return to see anything on stdout

**Comment by andry81** [comment]
But in the first example the `shutil.copyfile` does print.

**Comment by laloch** [comment]
> But in the first example the `shutil.copyfile` does print.

No, that's the mistake I tried to explain in the first reply. `copyfile` does **not** print anything. It's the Python REPL that prints the string representation of the **value returned** by `copyfile`.

Try this:
```
$ import shutil
$ def cf():
    shutil.copyfile('a', 'b')
$ cf()
```
You see? It does not print anything.

**Comment by andry81** [comment]
OK, I see. So, for now the only issue is the print function.

**Comment by dotsdl** [comment]
Does this discussion sufficiently address your original problem @andry81? If so, I'll move to close the issue.

**Comment by andry81** [comment]
It's not just a mine problem. That is problem the whole xonsh as long as people searching for the way to move out the shell to the real program languages. And that problem prevent them to fully move to xonsh.
