### ISSUE TITLE
Windows: module `cmdix`/`yes` can not be interrupted (ctrl+c) from the python evaluation command `@(...)`

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3189]
## config
`windows x64 7`, `Python 3.7.3`, `xonsh/0.9.6`

## details
1. Install `cmdix` module.
2. Run the code:

```
import cmdix
@(cmdix.run, 'yes')
```
**Result:**
Infinite `y` output w/o ability to interrupt by the `ctrl+c` (only `ctrl+break` works which does close the xonsh itself)**

## Expected Behavior
Interrupt as usual.

## Current Behavior
Can not interrupt.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Even `/usr/bin/yes` has problems with job control sometimes (it fills up the buffers too fast and then takes a long time to dump to screen once Ctrl+C has been noticed). Is there another command that you are seeing this behaviour with?  

(And yes, we know there are job control issues.)

**Comment by jaraco** [comment]
I tried replicating the failure. I'm unsure how to do so. I created a virtualenv and installed xonsh and cmdix to it:

```
py -m venv .venv
.venv/Scripts/python -m pip install xonsh[full] cmdix
```

I then ran xonsh and entered the repro commands and got a [deprecation warning](https://github.com/xonsh/xonsh/issues/5530):

```
jaraco@bulletproof ~\draft [2] @# import cmdix
jaraco@bulletproof ~\draft @# @(cmdix.run, 'yes')C:\Users\jaraco\draft\.VENV\Lib\site-packages\xonsh\ast.py:145: DeprecationWarning: Constant.__init__ got an unexpected keyword argument 'is_raw'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  return Constant(value=s, kind="str", **kwargs)
jaraco@bulletproof ~\draft @# @(cmdix.run, 'yes')
Command `XONSH.EXE` not found.
```

Ignoring the deprecation warning, the command `@(cmdix.run, 'yes')` fails because no `XONSH.EXE` is found.

Can you help me understand what it is about `@(cmdix.run, 'yes')` that's expecting a `XONSH.EXE`?

**Comment by jaraco** [comment]
Since I'm unable to reproduce the issue (still) and it's proposed to be fixed, so let's assume that's the case unless we hear otherwise.

**Comment by andry81** [comment]
@jaraco 

I don't have `Windows 7` currently to retest. But can retest in `Windows 8.1`.

>ver

```
Microsoft Windows [Version 6.3.9600]
```

`Python 3.12.2`, `xonsh/0.18.3`, `cmdix 3.1.3`

If run the code from the xonsh command line, then it reports it could not find xonsh command:

> Command `xonsh` not found.

If add `Scripts` directory to the PATH variable, then it does not fix the error.

So I could not reproduce either.
