### ISSUE TITLE
[Feature Request] xonsh.source(var_root + '/blabla.xsh')

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3193]
## config
`Windows x64 7`, `Python 3.7.3`, `xonsh/0.9.6`

## details
Currently this does not work because the `source` is a statement:
```
source SCRIPTS_ROOT + '/blabla.xsh'
```

I use this to import `.xsh` scrtips dynamically:
```
evalx('source "' + SCRIPTS_ROOT + '/blabla.xsh"')
```

But I think it would be much better to use something from the xonsh package itself:
```
import source from xonsh
source(SCRIPTS_ROOT + '/blabla.xsh')
```

Yes, I can do it by myself by add a function, but the first line which import the source with the function still would be through the direct call to the `evalx`. Better to move it to the xonsh module to avoid that inconvenience.

## Expected Behavior
Dynamic `.xsh` scripts import additionally to the `source` statement.

**Comment by laloch** [comment]
Hi @andry81, you can actually call `source` command using `@()` python mode evaluation:
```
$ $SCRIPTS_ROOT = p"~"
$ source @($SCRIPTS_ROOT/"test.xsh")
```
You can also use `import` statement. See https://xon.sh/tutorial.html#importing-xonsh-xsh
