### ISSUE TITLE
[Feature Request] xonsh.ret() to return from a single `.xsh` script instead of exit the xonsh process

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3194]
## config
`Windows x64 7`, `Python 3.7.3`, `xonsh/0.9.6`

## details
Currently this does not work:
**1.xsh**
```
source 2.xsh
print(333)
```
**2.xsh**
```
print(111)
return() # error: can not be out of a function
exit()     # error: no such function, but interrupts the script execution with the `NameError: name 'exit' is not defined` message
exit       # misbehaviour: calls to the xonsh main process exit
print(222)
```
```
source 1.xsh
```

I suggest either add the return as the `xonsh.ret` function because full named `return` already reserved in the python, when the `xonsh.exit` function might be useful for something else, like exit from inner xonsh subprocess.

Or add the return as a statement to the xonsh itself:
```
return
```

## Expected Behavior
Return from the most inner `source` statement execution instead of close the xonsh process or return from a subprocess.

**Comment by laloch** [comment]
The `source` command runs the script passed as an argument in the context of the current shell instance. It is therefore perfectly reasonable to exit the current shell upon execution of `exit` command from within the sourced script. The behavior is also consistent with sh-lang compatible shells (e.g. bash).
You most probably want to run your script as an uncaptured subprocess. See https://xon.sh/tutorial.html#uncaptured-subprocess-with-and for details.

**Comment by andry81** [comment]
> The source command runs the script passed as an argument in the context of the current shell instance. It is therefore perfectly reasonable to exit the current shell upon execution of exit command from within the sourced script.

I don't want exit the shell, I want exit the script. Instead of this:
```
if not __INITED__:
  ...
  long text here
  ...
  __INITED__ = 1
```
I want to write like that:
```
if __INITED__:
  return
```
This is quite a different thing.

> You most probably want to run your script as an uncaptured subprocess. See https://xon.sh/tutorial.html#uncaptured-subprocess-with-and for details.

I don't see how it could help.
