### ISSUE TITLE
Ctrl-z in xonsh prompt itself

### ISSUE THREAD

**Issue by ivanov** [xonsh/xonsh#3216]
This might be related to #1103, #2353, #2847, but here's a separate simple reproducible case:

At the xonsh prompt - press `Ctrl-Z` followed by `Enter`.

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.8.dev9           |
| Git SHA          | 8576e9c2             |
| Commit Date      | Jul 13 15:36:33 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior
`Ctrl-Z` should no-op at the top level xonsh.

## Current Behavior

I typed `Ctrl-Z`, followed by `Enter`, and kept repeating `Enter'. The coloring of the prompt, as well as its content (the 'master' portion) shows up inconsistently.

![image](https://user-images.githubusercontent.com/118211/61176461-d89ed780-a586-11e9-90e6-68335618bc05.png)

## Steps to Reproduce
Type `Ctrl-Z`, followed by `Enter`, and keep pressing `Enter'.

**Comment by ivanov** [comment]
This is better than it was in 0.8.12, where the `^Z` was printed along with this trace
![image](https://user-images.githubusercontent.com/118211/61176517-bf4a5b00-a587-11e9-91b5-8ad039207e09.png)

**Comment by scopatz** [comment]
Thanks for reporting @ivanov! this is definitely part of our larger job control issues

**Comment by anki-code** [comment]
I can't reproduce on xonsh 0.9.26.
