### ISSUE TITLE
Website improvements (towards 1.0)

### ISSUE THREAD

**Issue by dotsdl** [xonsh/xonsh#3225]
This is a meta-issue / epic for the effort for website improvement in anticipation of 1.0. We will list all issues subsumed by this effort in the list below:

1. #969 
2. #1126 (add line in developer docs advising `python setup.py install` for parser table regeneration)
3. #1096 
4. #1087 
5. #1154 
6. #1430

**Comment by anki-code** [comment]
https://github.com/xonsh/xonsh/issues/3706#issuecomment-738913669

**Comment by anki-code** [comment]
Most of mentioned issues are closed or unrelated to website. I'm going to close this.
