### ISSUE TITLE
Octal numbers not highlighted

### ISSUE THREAD

**Issue by friedkeenan** [xonsh/xonsh#3233]
## xonfig

<details>

```
$ xonfig
```

</details>

## Expected Behavior

When you type something like `0o10` it should have the same color as any other int.
## Current Behavior

When typing an octal number, only the starting `0` gets highlighted.

## Steps to Reproduce

Type `0o10`

**Comment by scopatz** [comment]
Thanks! I can confirm that this is true.  This might be a bug in Pygments as well, but is something we could fix in the xonsh pygments highlighter. PRs very welcome!

**Comment by dannysepler** [comment]
just lookin through some older issues, this seems fixed now!

<img width="421" alt="Screen Shot 2020-08-08 at 3 41 01 PM" src="https://user-images.githubusercontent.com/3710083/89718585-a9c38280-d98d-11ea-97c1-e3998b022b86.png">

**Comment by friedkeenan** [comment]
yep, seems it is
