### ISSUE TITLE
Numbers and symbols not displaying

### ISSUE THREAD

**Issue by ncclementi** [xonsh/xonsh#3235]
## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.9           |
| Python           | 3.6.7           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

```
</details>

## Expected Behavior

When typing numbers or math symbols I should see them.

## Current Behavior

When typing numbers or math symbols they don't display. For example, if I type `a=3` I only see `a   `, same if I type  `b = ['a', 'b', 'c']` I see `b   ['a', 'b', 'c']`. If I do `2+3` it will still not display and the output neither. Although I can `print(a)` or `print(2+3)` ( which shows as print(     )) and the output will be visible in this case. 

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

Not sure how to reproduce this behavior, but maybe some useful information:
I'm on Ubuntu 16.04, and not sure if it's useful but the output of `echo $SHELL` is `/usr/bin/zsh`

**Comment by astronouth7303** [comment]
Wait, like, you type it and it just doesn't show on the prompt, the keystrokes don't echo? _That's_ a bug.

**Comment by ncclementi** [comment]
@astronouth7303 Yes, if I type math symbols or numbers, they won't show. It introduces spaces. If I do `a=2+3` (which in the prompt will look like `a    `, it won't show the = sign nor the numbers), and then `print(a)` it will print 5, but if I just do `a` and return, it'll show empty.

**Comment by astronouth7303** [comment]
That's weird, I smell a font/terminal issue?

**Comment by jb-leger** [comment]
More a terminal issue for me. @ncclementi, what is your terminal (if it is the default from you desktop environment, what is your desktop environment)?

And, can you provide us all terminal related variables in your env ?
```
# pythonic method
jben@garance ~ $ {k:v for k,v in __xonsh__.env.items() if 'TERM' in k}                                                                                                                                                             
...
# or classic shell method
jben@garance ~ $ env | grep TERM                                                                                                                                                                                                   
...
```

**Comment by ncclementi** [comment]
@jb-leger My default terminal is `zsh` , 
`zsh --version`   ----> `zsh 5.1.1 (x86_64-ubuntu-linux-gnu)`
and the output of `env | grep TERM` ---->  `TERM=xterm-256color`

**Comment by astronouth7303** [comment]
No, terminal as in terminal emulator, so like gnome-terminal, Konsole, xterm, rxvt, alacritty, etc.

**Comment by ncclementi** [comment]
Oh, I see, it's the gnome-terminal.

**Comment by jb-leger** [comment]
Are you sure you are using `gnome-terminal`, you should have more environment variables for gnome terminal containing `TERM`.

Could you try with xterm?

**Comment by ncclementi** [comment]
Yes I'm pretty sure I'm using `gnome-terminal`, and the only output I get for `env | grep TERM` is just `TERM=xterm-256color` (tried this on a different machine that uses Konsole and output is the same). 

Now if I launch `xterm` the bug seems to go away. (Although, tbh I wouldn't like to use xterm)
What I get for  `env | grep TERM` in `xterm` is

```
TERM=xterm
XTERM_VERSION=XTerm(322)
XTERM_LOCALE=en_US.UTF_8
XTERM_SHELL=/usr/bin/zsh 
```

**Comment by jb-leger** [comment]
Ok, you have the bug with your terminal (probably gnome-terminal) but you do not have it with xterm.

 - Can you check your term is gnome-terminal by exploring the process tree (with `ps axjf | less -S` for example)?
 - Do you have the but with Konsole since you have also Konsole? You said _the same_, but the same as xterm or as your first terminal?

**Comment by ncclementi** [comment]
- I'm sure is `gnome-terminal`, another way of confirming that is 
```
$ ps -p $$ -o args, ppid
COMMAND                      PPID
zsh                         28902
$ ps -p 28902 -o args
/usr/lib/gnome-terminal/gnome-terminal-server
```
Not sure how to find it in the process tree, but I am sure is the `gnome-terminal`. 

Regarding "Do you have the but with Konsole since you have also Konsole? You said the same, but the same as xterm or as your first terminal?"

What I said was that was for the gnome-terminal the "output I get for `env | grep TERM` is just `TERM=xterm-256color` (tried this on a different machine that uses Konsole and output is the same)." When I say "this" I'm referring to the same output of `env | grep TERM` ---> `TERM=xterm-256color` but it's on a different machine.

**Comment by scopatz** [comment]
This is pretty weird.  I used to use gnome-terminal all of the time and it always worked.  I just tried it again now with out any issues.

Can you run `dconf dump /org/gnome/terminal/` to see the settings? Mine is:

```bash
$ dconf dump /org/gnome/terminal/
[legacy]
default-show-menubar=false
schema-version=uint32 3

[legacy/profiles:]
default='74b84327-5298-436a-a30a-0d7e16500133'
list=['b1dcc9dd-5262-4d8d-a863-c897e6d979b9', '74b84327-5298-436a-a30a-0d7e16500133', '462a802d-dab5-444b-a157-41bfb7c74c8f']

[legacy/profiles:/:462a802d-dab5-444b-a157-41bfb7c74c8f]
background-color='rgb(255,255,255)'
foreground-color='rgb(0,0,0)'
use-custom-command=true
scrollback-unlimited=true
custom-command='/home/scopatz/.local/bin/xonsh'
use-theme-colors=false
visible-name='xonsh-light'

[legacy/profiles:/:74b84327-5298-436a-a30a-0d7e16500133]
scrollback-unlimited=true
use-custom-command=true
font='Monospace 22'
custom-command='/home/scopatz/.local/bin/xonsh'
visible-name='xonsh-dark'
use-system-font=false
```

**Comment by ncclementi** [comment]
I'm starting to think the problem might be related to my background color or something like that
Here is what I got from running the command

```
$ dconf dump /org/gnome/terminal/

[legacy]
dark-theme=true
schema-version=uint32 3

[legacy/profiles:]
list=['7c9012ab-b413-45a1-b708-94fd3e3bc07d']
default='7c9012ab-b413-45a1-b708-94fd3e3bc07d'

[legacy/profiles:/:7c9012ab-b413-45a1-b708-94fd3e3bc07d]
foreground-color='rgb(131,148,150)'
visible-name='Agnoster'
palette=['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']
default-size-rows=25
default-size-columns=104
use-system-font=false
use-transparent-background=false
use-theme-colors=false
font='Droid Sans Mono Slashed for Powerline 11'
bold-color-same-as-fg=true
background-color='rgb(0,43,54)'
background-transparency-percent=5
```

**Comment by scopatz** [comment]
hmm do you have xonsh set as your login shell? or does gnome-terminal start in Bash?

**Comment by scopatz** [comment]
This seems like it might be related to #3245

**Comment by jaddison06** [comment]
I had this in Konsole, turned out to just be a colour theme issue. Play around with your terminal theme, look for the text colours that are similar to your background colour and change them, see if it makes a difference.
