### ISSUE TITLE
Module 'pip' has no attribute

### ISSUE THREAD

**Issue by jkw** [xonsh/xonsh#3237]
## xonfig
´´´jkw@dasslock ~ $ cat .xonshrc 
\# XONSH WIZARD START
xontrib load apt_tabcomplete autojump autoxsh avox click_tabcomplete coreutils distributed docker_tabcomplete fzf-widgets histcpy jedi powerline readable-traceback ssh_agent vox vox_tabcomplete xo z
\# XONSH WIZARD END```

## Expected Behavior
Clean startup.

## Current Behavior
`Warning: Unconfigured $PROJECT_DIRS. Using ~/code
<unknown>:1: DeprecationWarning: invalid escape sequence \w
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
AttributeError: module 'pip' has no attribute 'get_installed_distributions'`

### Traceback (if applicable)
None.
</details>

## Steps to Reproduce
Clean install on ArchLinux.

**Comment by astronouth7303** [comment]
`Warning: Unconfigured $PROJECT_DIRS. Using ~/code` comes from the avox xontrib. If that is unclear, please open an issue there.

How did you install xonsh? What is the output of `xpip --version`?

**Comment by gforsyth** [comment]
I'm closing this as it's related to a non-bundled xontrib

**Comment by astronouth7303** [comment]
It might not? The warning is just that, a warning. The real issue I think is 

```
AttributeError: module 'pip' has no attribute 'get_installed_distributions'
```

**Comment by astronouth7303** [comment]
Feel free to totally close it for idleness, though.

**Comment by jkw** [comment]
Thank you @laloch.
