### ISSUE TITLE
Different behaviors between interactive and ssh command

### ISSUE THREAD

**Issue by chengxuncc** [xonsh/xonsh#3239]
## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.9.dev22          |
| Git SHA          | 65fea7dd             |
| Commit Date      | Jul 23 23:44:06 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior

Should shart a new interactive shell session.

## Current Behavior

```
$ ssh cheng@linux "xonsh"
<module 'xonsh' from '/usr/lib/python3.7/site-packages/xonsh/__init__.py'>
Connection to linux closed.

$ ssh -t cheng@linux "xonsh"
<module 'xonsh' from '/usr/lib/python3.7/site-packages/xonsh/__init__.py'>
Connection to linux closed.
```

## Steps to Reproduce

```
$ ssh user@host "xonsh"
```
```
$ man ssh
...
 -t Force pseudo-terminal allocation.  
This can be used to execute arbitrary screen-based programs on a remote machine, 
which can be very useful, e.g. when implementing menu services.  
Multiple -t options force tty allocation, even if ssh has no local tty.
...
```
`-t` is useful to execute some commands before using interactive shell, e.g. `cd` to somewhere.
But `xonsh -i` works fine with ssh command, report this for a bug or something else.

**Comment by jb-leger** [comment]
I assume you use xonsh as you default shell on the distant side. So I do not understand why you want to start xonsh explicitly if it is you default shell.

Anyway, you have a behavior that you didn't expect. It seem you have imported the `xonsh` module somewhere (in your rc-file for example), and once the `xonsh` name is valid in python mode, the subprocess mode is not used. See [this section in tutorial.](https://xon.sh/tutorial.html#python-mode-vs-subprocess-mode)

I hope it answers your problem or I misunderstood the point.

**Comment by chengxuncc** [comment]
I want to execute some commands every time before I using interactive shell, like
```
ssh -t user@host "cd somewhere; xonsh"
```
I understand python mode and subprocess mode, but all I can found it imported `xonsh` package is
```
$ cat /usr/bin/xonsh
#!/usr/bin/python -u

from xonsh.main import main
main()
```
That's the behavior I didn't expect, maybe `/usr/bin/xonsh` is the problem ?

**Comment by jb-leger** [comment]
I mean, on the distant host, is xonsh your login shell?

I think xonsh is your login shell and you have a `import xonsh` in your `~/.xonshrc`.

**Comment by chengxuncc** [comment]
Yes, `xonsh` is my default shell on remote host, and my `~/.xonshrc` is empty, it seems `ssh user@host "xonsh"` is as same as `xonsh -c "xonsh"`.
```
now_is_xonsh $ xonsh -c "bash"
bash: cannot set terminal process group (897): Inappropriate ioctl for device
bash: no job control in this shell
now_is_bash $ bash -c "xonsh"
now_is_xonsh $
```
It seems `xonsh -c` have some probloms.

**Comment by jb-leger** [comment]
It is not the same problem, the problem you point with `bash: cannot set terminal process group (897): Inappropriate ioctl for device`, is the way the command is launched, with `-c` bash is launched as threadable command, it is a bug, but not the same bug as this issue. Please open another issue for this.

For the problem you have in this issue, the name `xonsh` is defined in the python side. If it is not imported in your xonshrc of the remote host (only the xonshrc of the remote host), I do not understand where the name is defined.

To be sure, can you try:

```
ssh -t user@host "cd somewhere; del xonsh; xonsh"
```

**Comment by chengxuncc** [comment]
```
$ xonsh -c "xonsh"
<module 'xonsh' from '/usr/lib/python3.7/site-packages/xonsh/__init__.py'>
$ xonsh -c "del xonsh; xonsh"
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 4, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23994, in main
    _failback_to_other_shells(args, err)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23958, in _failback_to_other_shells
    raise err
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23992, in main
    return main_xonsh(args)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24026, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode="single")
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 3085, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 2943, in run_compiled_code
    func(code, glb, loc)
  File "6eca7d51ff0c65c5050a26223bdfec1f", line 1, in <module>
NameError: name 'xonsh' is not defined
```

**Comment by jb-leger** [comment]
Oh, sorry, the `;` doesn't allow te switch between python mode and shell mode, and I do not know where your NameError is fired. Could you try the following?

```
xonsh -c "del xonsh\nxonsh"
```

**Comment by chengxuncc** [comment]
It's the same.
```
$ xonsh -c "del xonsh\nxonsh"
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 4, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23994, in main
    _failback_to_other_shells(args, err)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23958, in _failback_to_other_shells
    raise err
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23992, in main
    return main_xonsh(args)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24026, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode="single")
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 3085, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 2943, in run_compiled_code
    func(code, glb, loc)
  File "5bf645e44ca12d246324fb43cc1da45b", line 1, in <module>
NameError: name 'xonsh' is not defined
```

**Comment by jb-leger** [comment]
The main problem is I can't reproduce. Maybe somebody can reproduce, it would be helpfull.

**Comment by chengxuncc** [comment]
I mean only use `xonsh` and run command `xonsh -c "xonsh"`, I even can reproduce it on [xon.sh](xon.sh) with `xonsh -c "del xonsh; xonsh"`

**Comment by anki-code** [comment]
Hi! In the [xxh project](https://github.com/xxh/xxh) we run xonsh using `ssh -t` without any issues. You can use [xxh-dev](https://github.com/xxh/xxh-dev) environment as the start point to repeat the issue. But does this issue still actual?
