### ISSUE TITLE
How to exit a script?

### ISSUE THREAD

**Issue by chengxuncc** [xonsh/xonsh#3241]
I don't know how to exit a script, I had searched tutorial and tested this:
```
exit
echo should exit
```
Not working, still echo `should exit`.

**Comment by jb-leger** [comment]
You can use the `exit` from `sys` module.

```
import sys
sys.exit(13)
echo should exit
```

Works as expected with the expected return code status.

**Comment by chengxuncc** [comment]
Thanks, now I get it, `.xsh` script is a superset of python script.

**Comment by anki-code** [comment]
> You can use the exit from sys module.
To avoid importing `sys`/`os` modules you can call `raise SystemExit` ([with or without return code](https://docs.python.org/3/library/exceptions.html#SystemExit)).
