### ISSUE TITLE
pyenv + pyenv-virtualenv

### ISSUE THREAD

**Issue by arkhan** [xonsh/xonsh#3244]
Greetings, a query what is the best way to work with xonsh as shell and pyenv + pyenv-virtualenv

Thank you

**Comment by astronouth7303** [comment]
`vox` supports specific paths and not just names.

I don't believe there's any code to replace the auto activation features yet. I suggest looking at [avox](https://github.com/astronouth7303/xontrib-avox) to see how to implement such a thing.

**Comment by scopatz** [comment]
Xonsh should work with virtualenv now too.

**Comment by arkhan** [comment]
but in the case of wanting to work with several versions of python for development xonsh does not support all the functionalities of pyenv ..?

**Comment by scopatz** [comment]
I have never used pyenv, so I can't say.  If it doesn't, it should!

**Comment by arkhan** [comment]
@scopatz, @astronouth7303 after several tests I work with:
```python
if $(which pyenv):
    $PYENV_ROOT = f'{$HOME}/.pyenv'
    source-zsh --overwrite-alias $(pyenv init -)
    if $(which pyenv-virtualenv):
        source-zsh --overwrite-alias $(pyenv virtualenv-init -)
```

but i have this error

```bash
/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py:10192: RuntimeWarning: could not parse alias "glod": ValueError('No escaped character')
  'could not parse alias "{0}": {1!r}'.format(key, exc), RuntimeWarning
/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py:10192: RuntimeWarning: could not parse alias "glol": ValueError('No escaped character')
  'could not parse alias "{0}": {1!r}'.format(key, exc), RuntimeWarning
/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py:10192: RuntimeWarning: could not parse alias "glod": ValueError('No escaped character')
  'could not parse alias "{0}": {1!r}'.format(key, exc), RuntimeWarning
/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py:10192: RuntimeWarning: could not parse alias "glol": ValueError('No escaped character')
  'could not parse alias "{0}": {1!r}'.format(key, exc), RuntimeWarning
```

Thanks

**Comment by astronouth7303** [comment]
No, there is no code I know of that integrates pyenv's core functionality (juggling Python installations by managing `$PATH`) into xonsh. This is, however, totally in the realm of possibility of a xontrib.

**Comment by deeuu** [comment]
Previous to my `conda` setup, I was able to use the core features of `pyenv` and `pipenv` successfully alongside `xonsh`. I basically installed `pyenv` and then `pip install pipenv` and put `xonsh` inside its own dedicated virtual environment (don't install `xonsh` as a `pyenv` shim). The following `$PATH` configuration seemed to work:

```
$PYENV_ROOT = os.path.join($HOME, ".pyenv")
$PATH.insert(0, os.path.join($HOME, ".pyenv/shims"))
$PATH.insert(0, os.path.join($HOME, ".pyenv/bin"))
```

**Comment by rajaravivarma-r** [comment]
@deeuu Thanks for the hint not to install xonsh as Pyenv shim, it broke a lot of stuff. But may I know why it doesn't work as Pyenv shim while it works when I launch it directly with the path?

**Comment by deeuu** [comment]
@rajaravivarma-r I can't quite remember the issues I encountered, but I think it boiled down to `PATH` manipulation. It's safer to have a dedicated `xonsh` environment.

**Comment by rajaravivarma-r** [comment]
@deeuu Oh alright, that makes sense. Thank you.
