### ISSUE TITLE
Automatic Vox Policies?

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#3246]
One of the re-occuring feature requests for vox is automatic de/activation of venvs, based on various polices (avox is based on a concept of project directory, I think someone did it based on `.venv`, just saw one based on `pyenv-virtualenv` (which is based on the presence of a `.python-version` file).

Wondering if we should refactor `avox` into a generic framework bundled with xonsh, and have these different polices plug in to it.

**Comment by scopatz** [comment]
Yeah, that seems like a nice approach.
