### ISSUE TITLE
Hardcoded path for command-not-found

### ISSUE THREAD

**Issue by vlaci** [xonsh/xonsh#3247]
NixOS has its own `command-not-found` implementation which lives at a different path then on Ubuntu. Unfortunately its path is hardcoded in https://github.com/xonsh/xonsh/blob/975c07ef15991fb29f86a52a0e6577d24a55e24a/xonsh/tools.py#L835

### Suggestions
Either
* Make the path of `command-not-found` configurable in an environment variable.
* Add some heuristics using `xoreutils.which` or something like that to look up the command.

I am happy to open a puil request if we can agree what the solution should be.

**Comment by laloch** [comment]
Hi @vlaci, thanks for reporting.
I would say that we should rather search for the executable on the contents of the `$PATH` environment variable using `shutil.which("command-not-found")`, which returns either the path to the executable or `None` if the executable cannot be found.
A PR would be great!
