### ISSUE TITLE
Autocompletion for man pages

### ISSUE THREAD

**Issue by vlaci** [xonsh/xonsh#3248]
(do not confuse with manpage based parameter autocompletion)

Zsh provides completion for man pages which works like this:
```
$ man read<tab>
completing manual page, section 1 (general commands)
readlink                  realpath                
completing manual page, section 3 (library functions)
readdir      readfile     readproc     readproctab
completing manual page, section 8 (maintenance commands and procedures)
readprofile
```

I find this extremely handy. If you like the idea to have something like this I am willing to implement it.

**Comment by laloch** [comment]
Hi @vlaci, Xonsh can make use of `bash-completion`, so this feature works for me "out-of-the-box".

**Comment by vlaci** [comment]
Thanks. Will look into it more as it indeed works for me in bash too.

**Comment by laloch** [comment]
The above is not correct. Xonsh has its own `man` completer in [https://github.com/xonsh/xonsh/blob/master/xonsh/completers/man.py]()

**Comment by vlaci** [comment]
Doesn't it just used for completing command line arguments for other commands using their man pages?

**Comment by laloch** [comment]
Oops, you're right! Then my man completions come from the bash completer indeed. Sorry for the confusion.
Btw, the paths to the bash completion script(s) are stored in `$BASH_COMPLETIONS` environment variable.

**Comment by vlaci** [comment]
My `BASH_COMPLETIONS` environment variable is set but empty. Completion still works in bash though.

**Comment by laloch** [comment]
It probably means that you `bash_completion` script is installed somewhere Xonsh doesn't look for it.
Check our bash completer to see how the default path is constructed: https://github.com/xonsh/xonsh/blob/adf528f25bbfe224dc9230d6167a0fb31fb6fe08/xonsh/completers/bash_completion.py#L73
You can set the `$BASH_COMPLETIONS` variable manually to make it point to the correct location.

**Comment by vlaci** [comment]
I think this is related to https://github.com/xonsh/xonsh/issues/2814. I'll try to fix the issue from the packaging side in NixOS.

Thanks for the help!
