### ISSUE TITLE
OSX guide to add path_helper clashes with conda!

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#3267]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.9           |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior

Conda envs should be highest in $PATH always, to reach their executables first.

## Current Behavior

After following the OSX guide here: https://xon.sh/osx.html to add the path helper my $PATH had `/usr/local/bin` and other paths much higher in the PATh hierarchy than my conda env, creating much confusion for a while until I realized that.

Here's my `.xonshrc`, as you can see, all I had to do to fix this is to comment out the `source-bash` line for the `path_helper`:

```bash
$ cat ~/.xonshrc

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
import sys as _sys
from types import ModuleType as _ModuleType
_mod = _ModuleType("xontrib.conda",
                   "Autogenerated from $(/Users/klay6683/miniconda3/bin/conda shell.xonsh hook)")
__xonsh__.execer.exec($("/Users/klay6683/miniconda3/bin/conda" "shell.xonsh" "hook"),
                      glbs=_mod.__dict__,
                      filename="$(/Users/klay6683/miniconda3/bin/conda shell.xonsh hook)")
_sys.modules["xontrib.conda"] = _mod
del _sys, _mod, _ModuleType
# <<< conda initialize <<<

# XONSH WIZARD START
$AUTO_CD = '1'
$AUTO_PUSHD = '1'
$AUTO_SUGGEST_IN_COMPLETIONS = '1'
$COMPLETIONS_CONFIRM = '1'
$COMPLETION_IN_THREAD = '1'
$DYNAMIC_CWD_ELISION_CHAR = '...'
xontrib load autojump autoxsh coreutils docker_tabcomplete mpl readable-traceback ssh_agent whole_word_jumping
# XONSH WIZARD END

$PROMPT='{$CONDA_PROMPT_MODIFIER}{YELLOW}{user}{NO_COLOR}@{PURPLE}{hostname}{GREEN} {cwd}{branch_color}{curr_branch: [{}]}{NO_COLOR}\n{prompt_end} '

#source-bash $(/usr/libexec/path_helper -s)

conda activate py37
```

**Comment by bestlem** [comment]
I just had this. 

I think the issue is that a shell gets called to run xonsh and if that shell is zsh, bash or tcsh (and possibly others) then that shell gets initialised and that will include a startup file in /etc. These startup files in macOS include calls to path_helper and to your startup files. If you setup conda in your bash or zsh+ files then that setup is there before xonsh starts.

I 'solved' this by making my .zprofile minimal and not calling conda or really anything else. I now use fish or xonsh for interaction and python for any scripting.



It would be useful if there was documented the exact calls to start xonsh - and whether they get another shell called.

**Comment by anki-code** [comment]
Yes, `source-bash` does many complex things. 
You can look at #3146 and [this chat](https://gitter.im/xonsh/xonsh?at=605dfe6a8478e061b960a9f3).

To simplify the `path_helper` loading this could be added to `~/.xonshrc` instead of using `source-bash`:
```python
$PATH = $(/usr/libexec/path_helper -s).split('"')[1]
```
