### ISSUE TITLE
Add the bash umask command to xonsh

### ISSUE THREAD

**Issue by trollodel** [xonsh/xonsh#3268]
Xonsh don't allow to set the permission mask to the shell (umask), default mask is 0006.
For me this causes issues when I install packages using xpip (or sudo pip) because I can't read the package directory as user, due to missing r permission to others.

## xonfig
On a Ubuntu 18.04 based distro (KDE neon)
```
$ xonfig  --json
```
```json
{
 "Commit_Date": "Jul 19 17:43:33 2019",  
 "Git_SHA": "5aac8711",  
 "PLY": "3.11",  
 "Python": "3.6.8",  
 "default_encoding": "utf-8",  
 "distro": "neon",  
 "encoding_errors": "surrogateescape",  
 "have_readline": true,  
 "is_superuser": false,  
 "on_cygwin": false,  
 "on_darwin": false,  
 "on_linux": true,  
 "on_msys2": false,
 "on_posix": true,
 "on_windows": false,
 "prompt_toolkit": "2.0.9",
 "pygments": "2.4.2",
 "shell_type": "prompt_toolkit2",
 "xonsh": "0.9.9",
 "xonsh_encoding": "utf-8"
}
```

## Expected Behavior
Exists an umask command, an env variable or something else to set the permission mask

## Current Behavior
No way to set the permission mask

**Comment by scopatz** [comment]
Thanks for opening this @trollodel

**Comment by trollodel** [comment]
Any update?

**Comment by adqm** [comment]
I just opened #3403, which is an attempt at a `umask` implementation.  Alternatively, it might work just to `import os` and then invoke `os.umask` directly (which is what the alias from that PR does).

**Comment by scopatz** [comment]
Thanks @adqm!  Closing this as that PR was merged
