### ISSUE TITLE
Is xonsh first-class conda citizen yet?

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#3269]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.9           |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

```

</details>

## Expected Behavior

1. activate scripts should be run
1. `conda --version` should work

## Current Behavior

1. I got these scrips in the `<env>/etc/conda/activate.d` folder:

```bash
(py37) klay6683@macl3886 ~/miniconda3/envs/py37/etc/conda/activate.d
$ ll
total 40
drwxr-xr-x  7 klay6683  2260  224 Aug 10 19:53 .
drwxr-xr-x  4 klay6683  2260  128 Aug 10 19:53 ..
-rw-rw-r--  2 klay6683  2260  973 Jul 22 11:20 gdal-activate.sh
-rw-rw-r--  2 klay6683  2260  555 May 21 10:03 geotiff-activate.sh
-rw-rw-r--  2 klay6683  2260  404 May 23 05:48 proj4-activate.csh
-rw-rw-r--  2 klay6683  2260  280 May 23 05:48 proj4-activate.fish
-rw-rw-r--  2 klay6683  2260  390 May 23 05:48 proj4-activate.sh
```
and when I am activating my conda env via `fish`, the variables inside the proj4-activate.fish scripts are being set:
```bash
$ cat proj4-activate.fish
#!/usr/bin/env fish

if set -q PROJ_LIB
  set -gx _CONDA_SET_PROJ_LIB "$PROJ_LIB"
end

if test -d "$CONDA_PREFIX/share/proj"
  set -gx PROJ_LIB "$CONDA_PREFIX/share/proj"
else if test -d "$CONDA_PREFIX/Library/share/proj"
  set -gx PROJ_LIB "$CONDA_PREFIX/Library/share/proj"
end
```
but nothing is set when activating it while having `xonsh` running.

Will full functionality inside `xonsh` require an additional `.xsh` script here, or will this be parsed from either .csh/.sh/.fish script in the future? If it requires another script here, is this the responsibility of each conda package's author or is this a functionality of `conda` that is missing?

2. error:
```bash
$ conda --version
usage: xonsh command
xonsh: error: the following arguments are required: command
```

**Comment by scopatz** [comment]
Yep there is a bug in with conda activation scripts and conda right now. Basically, it is just that conda needs to run `source-bash` on the activation scripts, and it doesn't. This is a bug in upstream conda that I haven't gotten around to fixing (but will eventually, because it bothers me too). If you want to beat me to it, that'd be great!

**Comment by michaelaye** [comment]
if you can point me to what I need to read to understand `source-bash` well, I might get to it. Can't promise, but I'd like this to be fixed, b/c `conda` is my bread and butter and I need that to work perfectly.

**Comment by scopatz** [comment]
So the command `conda shell.xonsh actiavte` produces something like the following:

```
$ conda shell.xonsh activate <env-name>
$PATH = '/home/scopatz/miniconda/bin:/home/scopatz/miniconda/condabin:/home/scopatz/.local/bin:/home/scopatz/miniconda/bin:/home/scopatz/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
$CONDA_PREFIX = '/home/scopatz/miniconda'
$CONDA_SHLVL = '1'
$CONDA_DEFAULT_ENV = 'base'
$CONDA_PROMPT_MODIFIER = '(base) '
$CONDA_EXE = '/home/scopatz/miniconda/bin/conda'
$_CE_M = ''
$_CE_CONDA = ''
$CONDA_PYTHON_EXE = '/home/scopatz/miniconda/bin/python'
```

Whereas bash's version (for an environment with activation scripts) produces:

```
$ conda shell.bash activate <env-name>
PS1='(nuitka) '
export PATH='/home/scopatz/miniconda/envs/nuitka/bin:/home/scopatz/miniconda/condabin:/home/scopatz/.local/bin:/home/scopatz/miniconda/bin:/home/scopatz/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export CONDA_PREFIX='/home/scopatz/miniconda/envs/nuitka'
export CONDA_SHLVL='1'
export CONDA_DEFAULT_ENV='nuitka'
export CONDA_PROMPT_MODIFIER='(nuitka) '
export CONDA_EXE='/home/scopatz/miniconda/bin/conda'
export _CE_M=''
export _CE_CONDA=''
export CONDA_PYTHON_EXE='/home/scopatz/miniconda/bin/python'
. "/home/scopatz/miniconda/envs/nuitka/etc/conda/activate.d/activate-binutils_linux-64.sh"
. "/home/scopatz/miniconda/envs/nuitka/etc/conda/activate.d/activate-gcc_linux-64.sh"
. "/home/scopatz/miniconda/envs/nuitka/etc/conda/activate.d/activate-gfortran_linux-64.sh"
. "/home/scopatz/miniconda/envs/nuitka/etc/conda/activate.d/activate-gxx_linux-64.sh"
. "/home/scopatz/miniconda/envs/nuitka/etc/conda/activate.d/gdal-activate.sh"
. "/home/scopatz/miniconda/envs/nuitka/etc/conda/activate.d/geotiff-activate.sh"
. "/home/scopatz/miniconda/envs/nuitka/etc/conda/activate.d/proj4-activate.sh"
```

Those `.`s at the end need to be replaced with xonsh's [`source-bash`](https://xon.sh/aliases.html#source-bash)

**Comment by scopatz** [comment]
And note that a lot of this is implemented in: 

* https://github.com/conda/conda/blob/8232664e43c323e8381ced751c4c80411f4ee4ee/conda/activate.py
* https://github.com/conda/conda/blob/master/conda/shell/conda.xsh

**Comment by michaelaye** [comment]
My question is, how does one know that gdal and geotiff etc. have this activation scripts in bash? Who is producing them? The package owner? Or is there some scripts that parses some config file to create these scripts?

**Comment by michaelaye** [comment]
Implementing something that simply checks for what bash does feels suboptimal.

**Comment by scopatz** [comment]
> how does one know that gdal and geotiff etc. have this activation scripts in bash? Who is producing them? The package owner?

Yeah, so the way the conda ecosystem works is that the package authors write activation scripts. And they either write these in bash or windows batch.  Luckily xonsh can source both of these formats.  Otherwise, package authors would need to write xonsh activation scripts (which would be better), but is unlikely to happen in the short term / consistently across the ecosystem

**Comment by michaelaye** [comment]
any clue why `conda --version` doesn't work?

**Comment by scopatz** [comment]
Ahh yeah, that is probably another bug in the conda implementation

**Comment by scopatz** [comment]
I have a PR into conda to fix these issues: https://github.com/conda/conda/pull/9305  It was smaller than I expected!
