### ISSUE TITLE
Autoloaded xontribs

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#3275]
Thinking about other ways/contexts to ship xonsh, and there are cases where you (the packager) want to inject loaded-at-init code into the distribution.

* zipapp: My zipapp distribution has a xontrib to fix `xpip` and to manage the user's site/venv
* CI: CI contexts need additional envvars registered
* GitHub Actions: Additional envvars, such as parsing `$GITHUB_EVENT_PATH` (a path to a JSON) and `$INPUT_*`.

I would argue that xonsh is ripe for automation like above, due to its ability to strongly manipulate both data and the system. Being able to inject autoloaded xontrib-like modules would be immensely helpful.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by astronouth7303** [comment]
This might be related to #2151

**Comment by astronouth7303** [comment]
This is especially true since no rc files are loaded for scripts, so it's not obvious where to stick things like "parse the environment into a more usable form".

**Comment by scopatz** [comment]
Yeah, this would be great! 

If the xontrib exists, we could add a `--xontrib` option to the CLI to load xontribs on the command line.

For conda, we add the following to the `xonshrc` file, 

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
import sys as _sys
from types import ModuleType as _ModuleType
_mod = _ModuleType("xontrib.conda",
                   "Autogenerated from $(/home/scopatz/miniconda/bin/conda shell.xonsh hook)")
__xonsh__.execer.exec($("/home/scopatz/miniconda/bin/conda" "shell.xonsh" "hook"),
                      glbs=_mod.__dict__,
                      filename="$(/home/scopatz/miniconda/bin/conda shell.xonsh hook)")
_sys.modules["xontrib.conda"] = _mod
del _sys, _mod, _ModuleType
# <<< conda initialize <<<
```

This is effectively creating a fake xontrib

**Comment by anki-code** [comment]
It will be cool to have a xontrib installation pattern that excludes the editing of the `.xonshrc` file i.e.:
```python
xpip install xontrib-prompt-bar[autoloaded] xontrib-sh[autoloaded]  # etc
```
