### ISSUE TITLE
Click-like alias definitions

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#3278]
In general, I've been pretty impressed defining CLIs with [click](https://click.palletsprojects.com/).

I've wanted a nicer way to define aliases for a long time. (The current entrypoint->argparse->subcommands just isn't great, and gets worse as commands get more complex.)

I think that bundled with xonsh (or be a separate xonsh-maintained project) should be a framework for defining aliases, and I think that framework should use or be heavily inspired by click.

As an example, here is a [complex click application](https://gitlab.com/spirostack/saltlab/blob/master/saltlab/cli.py) I wrote (which doesn't even use the click context features well!)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by deeuu** [comment]
Interesting. What workfkow/features are you thinking for aliases?

**Comment by AstraLuma** [comment]
Something akin to:

```python
from xonsh import xlick

@xlick.command()
@xlick.option('--count', default=1, help='Number of greetings.')
@xlick.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        xlick.echo('Hello %s!' % name)
```

```
🐚 hello --count=3
Your name: John
Hello John!
Hello John!
Hello John!
```

Automatically registers the command as an alias (using with the function name or a `name` given to `xlick.command()`), sets up all the argument parsing, accepts and configures the stdio streams (so that `xlick.echo()` goes to the right place), etc etc.

In general, the goal is to make a friendlier experience for creating aliases with more declarative and less boilerplate.

**Comment by deeuu** [comment]
@astronouth7303 If you start a new project (at least for now) I'd be up for contributing where possible!

**Comment by scopatz** [comment]
yep this would be great!

**Comment by AstraLuma** [comment]
I think this should probably be a separate but highly encouraged project?

* xonsh core tries very hard to minimize dependencies
* I don't want to fork & maintain click

**Comment by micimize** [comment]
After a bit of messing around:

```python3
import click


def xonshify(command: click.Command, prog_name=None):
    global aliases

    if prog_name is None:
        prog_name = command.name
        
    def aliased(args):
        return command(
            args=args,
            prog_name=prog_name,
            complete_var=complete_var,
            standalone_mode=standalone_mode,
            **extra
        )
    aliased.__name__ = prog_name
    aliases[prog_name] = aliased
    return command


@xonshify
@click.command('foo')
@click.option('--foo-bar')
def cli(foo_bar):
    print(foo_bar)

foo --foo-bar barble
#=> barble
```

**Comment by micimize** [comment]
All we really need is a good decorator project that depends on `click`, right? 
```python3
import click


def xonshify(command: click.Command, prog_name=None):
    global aliases

    if prog_name is None:
        prog_name = command.name
        
    def aliased(args):
        return command( args=args,)
    aliases[prog_name] = aliased
    return command


@xonshify
@click.command('foo')
@click.option('--foo-bar')
def cli(foo_bar):
    print(foo_bar)
```

**Comment by AstraLuma** [comment]
I would prefer to integrate more deeply and eg explicitly pass the stdio streams.

**Comment by astronouth7303** [comment]
Potential alternative base: https://github.com/sdispater/cleo

I haven't used it, I just see it exists.

**Comment by halloleo** [comment]
Deep Click integration would be great indeed. 

For know I try @micimize's approach.  :-)

**Comment by halloleo** [comment]
**Side note:**

@micimize's approach is ok. 

On minor grip is that the command's help shows `xonsh` as command  name, so for the exanmple from above `foo --help` outputs:

```
Usage: xonsh [OPTIONS]

Options:
  --foo-bar TEXT
  --help          Show this message and exit.
```

I tried to fix this by setting `info_name` in `context_settings`, but [it doesn't work](https://stackoverflow.com/questions/60272698/python-click-how-to-change-the-value-of-info-name-for-the-global-context).

Anyway, this is only a minor issue, by and large `@xonshify` does its job.

**Comment by halloleo** [comment]
**2nd side note:**

A fix for the wrong name in the help is actually easy:

```
def xonshify(command: click.Command, prog_name=None):
    global aliases

    if prog_name is None:
        prog_name = command.name
        
    def aliased(args):
        return command(args=args, prog_name=prog_name) # <--- Herr I added prog_name in
    aliases[prog_name] = aliased
    return command
```

(Thanks to [Stephen Rauch's Stackoverflow answer](https://stackoverflow.com/a/60284522/65889).)

**Comment by AstraLuma** [comment]
https://github.com/mahmoud/face exists but has no docs.

**Comment by AstraLuma** [comment]
After using click some, and really going "huh" at the advanced features, I've got some ideas for what I would want out of this.

**Comment by jnoortheen** [comment]
I am seeing this issue only now. 
I also wanted to have a nice wrapper for aliases and was looking for lightweight library. At the last I've created https://github.com/jnoortheen/arger . I think finally now it is ready for general use. We can keep Python functions as well as have CLI for them. Also one can auto generate completions for the aliases.
Can we vendor this to solve the issue ?

**Comment by jnoortheen** [comment]
Xonsh now has https://github.com/xonsh/xonsh/blob/main/xonsh/cli_utils.py module which implements a way to create parsers from functions and dispatch from CLI. Most of the things can be specified explicitly. 

It has auto-completions support + color support. Most of the xonsh's builtin aliases now use that to build parsers.

**Comment by halloleo** [comment]
Thanks for the link to `cli_utils`. Looks very promising!

**Comment by halloleo** [comment]
Additional Note for people who look for  a _**click**_-like CLI: [`cli_utils.py`](https://github.com/xonsh/xonsh/blob/main/xonsh/cli_utils.py) is hands things off to **argparse**, so it does _not_ things the **click** way.

If you want to use [**click**](https://click.palletsprojects.com/) itself with xonsh, IMHO the "[@xonshify](https://github.com/xonsh/xonsh/issues/3278#issuecomment-588045475) " approach is  still the best we have.

But of course a proper **xlick** module/xontrib (as [suggested by @AstraLuma](https://github.com/xonsh/xonsh/issues/3278#issuecomment-523668768)) which translates things to click calls) would be a dream!

**Comment by jnoortheen** [comment]
I find click to be very verbose, [typer](https://typer.tiangolo.com/) is bearable, but doesn't recognize docstrings. The main problem I had with click is that, I couldn't pass [args] to the parser , so I wasn't able to wrap the args from alias-functions and send it to click. As you can see [here](https://click.palletsprojects.com/en/8.0.x/testing/), for testing, one has to create CliRunner, in argparse, we can just pass the args as a list to the main parser. A xontrib for click integration is always welcome, anyways I don't see a need for it in any small to medium sized CLIs 

Here is my own project https://jnoortheen.github.io/arger/, that does the dispatch and some value conversion. Here is how I integrate it with xonsh https://github.com/jnoortheen/xontrib-commands/blob/main/xontrib_commands/dev_cmd.py

**Comment by anki-code** [comment]
@AstraLuma what do you think about this:

Wrapper (xonsh 0.23.0):

<details>

```xsh
def _click_command_alias(name=None):                                                         
    import click                                                                                                                                                            
    def decorator(func):
        if isinstance(func, click.Command):                                         
            cmd = func                                          
            original_name = (cmd.callback.__name__ if cmd.callback else cmd.name)   
        else:                                                   
            original_name = func.__name__
            cmd = click.command()(click.pass_context(func))
                                          
        class XonshContext(click.Context):      
            def __init__(self, *args, xsh=None, **kwargs):                                  
                super().__init__(*args, **kwargs)                                           
                xsh = xsh or {}                                                             
                self.xsh_args = xsh.get("args")                                             
                self.stdin = xsh.get("stdin")                           
                self.stdout = xsh.get("stdout")
                self.stderr = xsh.get("stderr")                                             
                self.spec = xsh.get("spec")     
                self.stack = xsh.get("stack")                                               
                self.alias_name = xsh.get("alias_name")                                     
                self.called_alias_name = xsh.get("called_alias_name")
                self.env = xsh.get("env")                                                   
                                          
                                          
        cmd.context_class = XonshContext    
                                                                                    
        registered_name = name or original_name.lstrip("_").replace("_", "-")       
                                                                                    
        def _wrapper(args, stdin=None, stdout=None, stderr=None,                    
                    spec=None, stack=None, alias_name=None,                        
                    called_alias_name=None, env=None):         
            xsh_data = {                                                            
                "args": args,                                   
                "stdin": stdin,                                                     
                "stdout": stdout,
                "stderr": stderr,                                                   
                "spec": spec,                                   
                "stack": stack,
                "alias_name": alias_name,                                           
                "called_alias_name": called_alias_name,
                "env": env,                                                         
            }                                                   
            try:
                cmd.main(                                                           
                    args=args,
                    prog_name=called_alias_name or registered_name,                 
                    standalone_mode=False,                      
                    xsh=xsh_data,       
                )
            except click.exceptions.ClickException as e:                            
                e.show()
                return e.exit_code                                                  
            except click.exceptions.Abort:                      
                return 1                
            return 0
                                                                                    
        aliases.register(registered_name, dash_case=False)(_wrapper)
        return _wrapper                                                             
    return decorator                                            
                
aliases.click_command = _click_command_alias   
aliases.click = @.imp.click
```

</details>

Example:

```xsh
@aliases.click_command()
@aliases.click.option('--count', default=1, help='Number of greetings.')
@aliases.click.option('--name', help='The person to greet.')
def _hello(ctx, count, name):  # ctx.stdin, ctx.stdout, ctx.stder, etc are available
    """Say my name."""
    for i in range(count):
        print(name)

hello --name snail --count 3
# snail
# snail
# snail
```

Do you want to have this in xonsh core?

**Comment by anki-code** [comment]
* https://github.com/xonsh/xonsh/pull/6265

**Comment by halloleo** [comment]
The Click support via #6265 is wonderful! Thank you.
