### ISSUE TITLE
Good way to search the xonsh history?

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3281]
I often want to look up old commands in my xonsh history across the different terminals I use on a machine. Let's say I want to find my last few uses of `scp`, for this I do:

    hsa | gri scp | tail

with 

    aliases['hsa'] = ['history', 'show', 'all']
    aliases['gri'] = ['grep', '-i']

This is not too bad, but I am hoping that - maybe - a shorter and more native solution for this exists...

**Comment by gforsyth** [comment]
Hey @halloleo,

Does Ctrl-r do the trick? You can advance further back in history by
hitting Ctrl-r again.

**Comment by halloleo** [comment]
Doesn't Ctrl-r only search the current terminal's history?

**Comment by gforsyth** [comment]
It should be searching through the combined terminal history -- it gets
loaded in a background thread after start-up

**Comment by halloleo** [comment]
I just checked, and yes, Ctrl-R does the trick when available. But is there a **command** doing this? (I use xonsh in an Emacs `comint` session and it is not easy to  forward special characters from the Emacs session to the xonsh shell.)

**Comment by scopatz** [comment]
I'd be open to having a `history search` command, if this is of interest.

**Comment by halloleo** [comment]
I think that would be great!

Maybe I could have a stab at it…

**Comment by scopatz** [comment]
That would be amazing!

**Comment by halloleo** [comment]
Hope I can look at it next week. - From my understanding I could model a `history search` command on `history show` which lives in `_xh_show_history()` in `xonsh/history/main.py`.

**Comment by soloturn** [comment]
where could one hook into if all history should be searched like fish shell does it, while typing?

**Comment by halloleo** [comment]
No idea how to search all history *while typing*...

I think the base/default of what xonsh looks through (i.e. the default for the `xonsh show` command) should be configurable, maybe via an environment variable.

This should then apply to the `xonsh search` command as well. :-)

**Comment by scopatz** [comment]
@soloturn - sorry for the slow reply.  The "while-typing" behavior is determined by the shell type, so it is going to be different for different types.  The most fish-like shell type is prompt toolkit (which is used by default if it is installed). This is implemented in `xonsh/ptk2/` (see https://github.com/xonsh/xonsh/tree/master/xonsh/ptk2)

**Comment by laloch** [comment]
Maybe we could spawn a per-session or per-user xonsh history server daemon? Just an idea...

**Comment by scopatz** [comment]
Yeah, @laloch - that has come up before.  It would be great to have!

**Comment by jnoortheen** [comment]
Ctrl+r is available as mentioned earlier.  xontrib-fzf-widgets overrides that with fzf selector.
