### ISSUE TITLE
Pure Python alternative to $()?

### ISSUE THREAD

**Issue by EdwardJB** [xonsh/xonsh#3284]
Hi,

Is there any way I can replace `$()` with pure Python? I've tried this:

`output=aliases['exec']('echo hello'.split())`

But it doesn't seem to output anything. (In fact it seems to crash Xonsh and lands be back in Bash.)

Why am I doing this? I want to write a set of functions to source using a proper IDE without it complaining about Xonsh syntax. So while I still want to use `$()` at the shell, I'd like to keep the stuff I source into the shell in pure Python.

**Comment by EdwardJB** [comment]
Thanks for the reply! I've tried `run` and it almost has the same behaviour. But where `$()` just captures (which is what I want) `run` _echos_ and captures:
```
ed@eb ~ $ output=$(echo hello)
ed@eb ~ $ output
'hello\n'
```

```
ed@eb ~ $ output=run('echo hello'.split()).out
hello
ed@eb ~ $ output
'hello\n'
```

Can I make `run` behave exactly like `$()`?

**Comment by EdwardJB** [comment]
Hmm. `check_output` seems to have the same behaviour as `run`:

```
ed@eb ~ $ output=check_output('echo hello'.split())
hello
ed@eb ~ $ output
'hello\n'
```

**Comment by EdwardJB** [comment]
Thanks,

Additionally I found that variables are expanded with `$()`, but aren't with `check_output`:

```
ed@eb $ echo $USER
ed
```
```
ed@eb $ echo $(echo $USER)
ed
```
```
ed@eb $ check_output('echo $USER'.split())
$USER
b'$USER\n'
```

**Comment by laloch** [comment]
Environment variables within strings are IMO only expanded in subprocess mode. Since `check_output` is called in Python mode, you most probably need to access `$USER` as a Python variable:
```
$  check_output(f'echo {$USER}'.split())
```

**Comment by gforsyth** [comment]
@EdwardJB can this be closed?
