### ISSUE TITLE
xonsh should return a non-zero exit code when a script cannot be found

### ISSUE THREAD

**Issue by certik** [xonsh/xonsh#3292]
Currently xonsh returns a zero exit code when the script cannot be found:
```
$ xonsh xx.xsh && echo "OK"
xonsh: xx.xsh: No such file or directory.
OK
```
That seems like a bug. Compared to bash, which returns a non-zero exit code:
```
$ bash xx.xsh && echo "OK"
bash: xx.xsh: No such file or directory
```

**Comment by gforsyth** [comment]
Hey @certik -- thanks for reporting!  I agree that xonsh in script mode should return a non-zero exit code in this case.

**Comment by certik** [comment]
I got burned by this several times already, when I change the path of the script that Xonsh should execute and the CI "succeeds" and I didn't notice until much later (after the PR that broke it got merged into master).
