### ISSUE TITLE
Support "set -e" and "set -x"

### ISSUE THREAD

**Issue by certik** [xonsh/xonsh#3294]
I use `set -ex` in all my Bash scripts. It's easy to remember and short to type. In Xonsh the equivalent is:
```
$RAISE_SUBPROC_ERROR = True
trace on
```
Which is long and hard to remember for me. I think it would be great if Xonsh could support `set -e` as a shortcut for `$RAISE_SUBPROC_ERROR = True` and `set -x` as a shortcut for `trace on`, and also support combining them as `set -ex`.

**Comment by astronouth7303** [comment]
This sounds like an excellent contribution to the [bashisms](https://github.com/xonsh/xonsh/blob/master/xontrib/bashisms.py) xontrib.

**Comment by scopatz** [comment]
Yeah I agree with @astronouth7303 - that would be a great addition to bashisms.  You'd have to override `set` to have a `__sub__` method that does the above

**Comment by anki-code** [comment]
Huge amount of bash features could be added to bashisms xontrib. PRs is very welcome!
