### ISSUE TITLE
Prompt hangs/becomes nonresponsive on 0.9.10-0.9.11, but not 0.9.9

### ISSUE THREAD

**Issue by markrawls** [xonsh/xonsh#3298]
(I've got my entire [xonsh config in a repo](https://github.com/markrawls/xonsh_config) if it helps debug. I can reproduce it every time on my machine.)

On version 0.9.9 the prompt loads successfully and does not hang, on versions 0.9.10 and up the aliases file in my config causes the prompt to not accept/show input and has to be shutdown with kill -9.

xonsh is set as my default shell on both systems. If it matters, I've tried it through three different terminal emulators: Yakuake, Konsole, and Emac's ansi-term.

## xonfig

On the system running 0.9.9:

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.9           |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

On the system running 0.9.10 (which should be configured near identically):

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.10               |
| Git SHA          | dd16d59d             |
| Commit Date      | Aug 25 13:21:16 2019 |
| Python           | 3.7.4                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

## Expected Behavior
I am able to interact with the shell in any way.

## Current Behavior
Currently, it hangs and accepts no input. It does not respond to regular kill signals, only kill -9. I have to start Emacs' ansi-term and open up a Fish session to get a usable shell.

## Steps to Reproduce
Clone that repository on a fresh (0.9.10 - 0.9.11) xonsh installation, and run the install script. Restart your computer. Load up a new shell.

## Things that make me think it's either a race condition or the whimsy of a cruel god
If I replace my aliases file with the one attached to this, it works flawlessly every time. (The extension has been changed to .txt to make github happy.)

Also, intriguingly, using the `@unthreadable` decoration from `xonsh.tools` causes the shell to crash, saying something to the effect of "invalid file prefix `/usr/bin`, defaulting to `/bin/sh`".

Slightly more frustratingly, about 1/6 of the time this does not happen.

Ideally I'd like to have all of my aliases available on both machines as I use them fairly interchangeably.
[aliases.txt](https://github.com/xonsh/xonsh/files/3563156/aliases.txt)

**Comment by gforsyth** [comment]
Hey @markrawls -- thanks for reporting and for your patience. 
This is a horrible ask, but can you attempt to narrow down the config file that's causing xonsh to hang?

**Comment by markrawls** [comment]
Of course. It looks like my aliases file is what's causing the problem. Specifically, the more callable aliases I have (the Python functions) the more likely it is that it hangs on start-up. Removing those seems to solve the problem.

**Comment by markrawls** [comment]
An update - after removing the existence check for updating `$PATH`, I no longer have the prompt hang on startup. I'm not sure how it's related.

**Comment by anki-code** [comment]
Hi! Does it still actual issue? Current version of xonsh is 0.9.25.
