### ISSUE TITLE
hangs after `source` of a script which has been already sourced

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3299]
## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.11                                                |
| Git SHA          | dd16d59d                                              |
| Commit Date      | Aug 25 13:21:16 2019                                  |
| Python           | 3.7.4                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | None                                                  |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000000002AD8B08> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000000002AD8B48> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Expected Behavior
Include the source script.

## Current Behavior
Hangs.

## Steps to Reproduce
**A.xsh:**
```
import os, sys

print('A.xsh')

def source_module(dir_path, module_name):
  print("source_module:", dir_path, module_name)
  #source dir_path/module_name
  evalx('source r"{0}"'.format(os.path.join(dir_path, module_name).replace('\\', '/')))

source_module('.', 'B1.xsh')
source_module('.', 'B2.xsh')
```
**B1.xsh:**
```
print('B1.xsh')
```
**B2.xsh:**
```
print('B2.xsh')

source_module('.', 'B1.xsh')
```
**Usage**:
```
python -m xonsh ./A.xsh
```
Output:
```
A.xsh
source_module: . B1.xsh
B1.xsh
source_module: . B2.xsh
B2.xsh
source_module: . B1.xsh
B1.xsh
```
... and hangs.

**At second**:
The `source_module` function seems for me as an absolute need in the case of inclusion **any** script at **any** point, otherwise i have to include that function in **all** user scripts. Or may be there is already exist such a function in the `xonsh` module?

**At third**:
What about inclusion guards? Or is there a caching handles it?

**Comment by gforsyth** [comment]
@andry81, regarding your `source_module` function, I'm not sure I understand the need.  Can you not just `source /path/to/file`?  If it's a windows `\\/` issue, you could always use p-strings instead, so `source p'/path/to/file'` should do the right thing

**Comment by andry81** [comment]
> regarding your `source_module` function, I'm not sure I understand the need

The need is to write instead of messy `evalx('source r"{0}"'.format(os.path.join(dir_path, module_name).replace('\\', '/')))` use a convenient way with the `myfoo(mydir, myscript)`.

> If it's a windows \\/ issue, you could always use p-strings instead, so source p'/path/to/file' should do the right thing

I need to use a composite with a variable and a relative path or a module file name (may be in a variable too). The p-string as I understand correctly is just a shortcut to a literal string as typed path.

**Comment by gforsyth** [comment]
There are also `pf` strings that I think will do what you want.  And `p` strings return `pathlib.Path` objects and those definitely support relative paths.

```
(base) gil@badcatredux ~/nottmp $ pwd                                                         
/home/gil/nottmp
(base) gil@badcatredux ~/nottmp $ sourcefile = "test.xsh"                                     
(base) gil@badcatredux ~/nottmp $ cat ../tmp/test.xsh                                         
def foo():
    echo I AM A FOO
(base) gil@badcatredux ~/nottmp $ source pf"../tmp/{sourcefile}"                              
(base) gil@badcatredux ~/nottmp $ foo()                                                       
I AM A FOO
```

**Comment by andry81** [comment]
Ye, this has worked. Is strange, why the `evalx` does not?
