### ISSUE TITLE
[Feature Request] `source_module` function with built-in inclusion guards and predicates to transpose the global variables

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3300]
## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.11                                                |
| Git SHA          | dd16d59d                                              |
| Commit Date      | Aug 25 13:21:16 2019                                  |
| Python           | 3.7.4                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | None                                                  |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000000002AD8B08> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000000002AD8B48> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Some background
All script or compile languages at least once had a problem with the inclusion recursion or it's controllable execution. In the python the recursed import does handled through the cache machanism, but in a scripted language a module file becomes a script which have to be executed again even if it has already been included. This means that the user is responsible to protect a script from double execution in a recursed inclusion sequence.

Basically inclusion guards is a part of a script, but in case of the python it becomes a mess after indent whole file because of an inclusion guard.

The idea is to put the inclusion guard ouside the xonsh script in the function like referenced - `source_module`. But, there is still some problems on the way, one of these is the global variables related particularly to the being sourced script.

Example:
```
import sys, os, inspect

# our global variables, for example, to include other scripts relative to this script
SOURCE_FILE = os.path.abspath(inspect.getsourcefile(lambda:0)).replace('\\','/')
SOURCE_DIR = os.path.dirname(SOURCE_FILE)

# example of implementation with global variables transpose
def source_module(dir_path, module_name):
  # inclusion guards here and return
  # ...

  # save common globals
  src_file = globals()['SOURCE_FILE']
  src_dir = globals()['SOURCE_DIR']
  #source dir_path/module_name
  evalx('source r"{0}"'.format(os.path.join(dir_path, module_name).replace('\\', '/')))
  # restore common globals
  globals()['SOURCE_FILE'] = src_file
  globals()['SOURCE_DIR'] = src_dir
```

(another related issue: https://github.com/xonsh/xonsh/issues/3299)

The declared `SOURCE_FILE` and `SOURCE_DIR` global variables still can be referenced after a `source_module` call and no need to use an inclusion guard in the user script.

**Pros**:

* No need to create an inclusion guard in the user script and so indent the whole file in the `if` block
* The user global variables does not affected by inclusion a script module

**Cons**:

* To source **any** user script from **any** user script the `source_module` must be declared in **all** user scripts before the usage
* Global variables transpose (save/restore) for **any** variables have to be somehow automated

To avoid the `Cons` the function must be implemented in the `xonsh` module. Is there a chance to be so?

**Comment by astronouth7303** [comment]
Why not `from my_thingy import *`?

**Comment by andry81** [comment]
>Also gives the modules control over what is actually added to the shell context (global scope).

I don't quite understand where the user can control it.

**Comment by astronouth7303** [comment]
The user can control what is imported via `from spam import foo, bar, baz`

The module author can control what's imported by default (`from spam import *`) with `__all__ = ('foo', 'bar', 'baz')`

Xonsh is a Python language superset, and all of Python's tools and abilities are available.

**Comment by andry81** [comment]
> The user can control what is imported via `from spam import foo, bar, baz`

This is different how the `source` works. As I understand correctly the `source` always imports and executes the whole file w/o scope and w/o need to create a package to import a single file, so the inclusion guard has more meaning for the `source` as a base inclusion operator in the `xonsh`. When the import can not include a single file by default, at least w/o a user function through the `importlib` or `imp` module.

**Comment by astronouth7303** [comment]
This is true. You have to place the file in your Python path (`sys.path`) somewhere.

**Comment by andry81** [comment]
> This is true. You have to place the file in your Python path (`sys.path`) somewhere.

This is different way of import. I do want to import by the source file path and don't depend on the import order in the `sys.path`.

**Comment by andry81** [comment]
> Why not `from my_thingy import *`?

I have tried to workaround it through the `importlib` or `imp` and gained the same result, it does not see the module extension, so the xonsh expression parser could not execute:

```
def import_module(dir_path, module_name, ref_module_name = None):
  ### CAUTION: direct implementation, can not load modules directly from any arbitrary directory
  ##evalx('import "{0}"'.format(os.path.join(dir_path, module_name).replace('\\', '/')))

  module_file_path = os.path.join(dir_path, module_name).replace('\\', '/')
  if sys.version_info[0] > 3 or sys.version_info[0] == 3 and sys.version_info[1] >= 4:
    import importlib.util, importlib.machinery
    #import_spec = importlib.util.spec_from_file_location(os.path.splitext(module_name)[0] if ref_module_name is None else ref_module_name, module_file_path)
    import_spec = importlib.util.spec_from_loader(os.path.splitext(module_name)[0] if ref_module_name is None else ref_module_name, importlib.machinery.SourceFileLoader(os.path.splitext(module_name)[0] if ref_module_name is None else ref_module_name, module_file_path))
    import_module = importlib.util.module_from_spec(import_spec)
    import_spec.loader.exec_module(import_module)
    #globals()[module_name if ref_module_name is None else ref_module_name] = import_module # still does not accept modules with periods without this
  else:
    # back compatability
    import imp
    #module_file, module_file_name, module_desc = imp.find_module(os.path.splitext(module_name)[0], [os.path.dirname(module_file_path)])
    #globals()[os.path.splitext(module_name)[0] if ref_module_name is None else ref_module_name] = imp.load_module(module_file_path, module_file, module_file_name, module_desc)
    globals()[os.path.splitext(module_name)[0] if ref_module_name is None else ref_module_name] = imp.load_source(os.path.splitext(module_name)[0] if ref_module_name is None else ref_module_name, module_file_path)

def source_module(dir_path, module_name):
  source_module_path = os.path.abspath(os.path.join(dir_path, module_name)).replace('\\', '/')

  #source dir_path/module_name
  echo @('source : ' + source_module_path)
  #evalx('source r"{0}"'.format(source_module_path)) # xonsh import
  import_module(dir_path, module_name) # python import
```

It is complaining about all xonsh expressions and statements like `echo`.
So I don't think it is reachable through the direct python import, at least, it can not be done w/o lose other features like support a period characters in a module file name or import *any* extension module.

**Comment by astronouth7303** [comment]
Xonsh literally has an [xsh importer built in](https://github.com/xonsh/xonsh/blob/master/xonsh/imphooks.py) and ships with [xsh modules](https://github.com/xonsh/xonsh/tree/master/xonsh/lib) and uses it [to load xontribs](https://github.com/xonsh/xonsh/blob/b067b5a7dc1683b688c71ddfec2483b9c90aa576/xonsh/xontribs.py#L23-L34).

So yes, importing xonsh code as a module is very possible. I'm not sure what you're doing.

**Comment by andry81** [comment]
> So yes, importing xonsh code as a module is very possible. I'm not sure what you're doing.

I do not want to import it as a package, I do want to import it as a single file. The `source` operator does not work because of bugs:
https://github.com/xonsh/xonsh/issues/3302
https://github.com/xonsh/xonsh/issues/3301
https://github.com/xonsh/xonsh/issues/3299
So I've tried to import it through the `importlib`, but it does not understand the xonsh expressions.
Can you demonstrate the minimal example to import the `.xsh` file through the `importlib`?

**Comment by astronouth7303** [comment]
Your example doesn't work because `importlib.util.spec_from_file_location()` only invokes the path-based module loading systems, not the full import stack (starting from the metapath). Path-based loading is not extensible to new file types* because of the way it is implemented, and therefore no project that implements new languages (such as xonsh or my own gqlmod) can use that method.

The semantics you describe in your original post still match those of Python modules, and I'm of the opinion that one of two things should be done:
* Make it easier for users to insert files into the module search path. (This is famously error-prone and currently varies wildly based on installation method.)
* Add a function to handle the jiggery-pokery to import a specific file by pathname.

I prefer the first one because it solves greater usability problems than the immediate functional need described above.

In general, when considering the design of the xonsh environment (language, builtins, and tools), I largely consider xonsh to be python with shell extensions--we should be doing things in that follow python idioms and that encourage our users to do the same.

(* It is possible to add new file types to the path-based search system, but I would reject any PR that features the code snippet `sys.path_hooks[-1].__closure__[1].cell_contents += ((XonshFileLoader, ['.xsh']),)` on the basis that it is unmaintainable, hilariously fragile, and reaches too deep into internal machinery.)

**Comment by andry81** [comment]
>I prefer the first one because it solves greater usability problems than the immediate functional need described above.

This is not just "immediate functional need", this is how the unix shell scripts works (see bash `source` command). And this is a convinient way to include another script in a standalone environment independently to some search paths logic. And I don't see how it should solve anything here, except a hindering problem with actually randomly ordered inclusion paths.

**Comment by andry81** [comment]
To whom who maybe interested in a self deploy pathname-based import function (python 3.4.x and higher only), I have made an implementation here:
https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path/57843421#57843421
See the Update section for details.

Just put the implementation to all entry point scripts to self inject the function `import_module` to all children modules in a single call.

**Comment by astronouth7303** [comment]
Xonsh is not a bourne shell or a bourne derivative, and will buck what other shells do in favor of another method if we think it is better UX or aligns better with the Python/shell duality of xonsh.

As I understand it, the real, core problem you're trying to solve is, "It is hard for users to reliably add personal library files to their xonsh environment." Which I will accept as a factually true statement with no qualms or argument.

The proposed addition is one way to solve this, but it creates a new way of running code and a new kind of conceptual import (of which we have, like, 4 already, defined by caching, relationship with the global context, and a few other things).

What I would much rather see is tooling that better leverages and exposes the existing import concepts and mechanisms--maybe commands to tell you were to put files, maybe a consistent directory that gets added to `sys.path`, maybe a sophisticated tool with editor integrations and package management. In other words, instead of inventing a new tool with its own problems, lets fix the problems with the existing tools.

**Comment by andry81** [comment]
> Instead of inventing a new tool with its own problems, lets fix the problems with the existing tools.

It would be good if the xonsh team will fix the hang issues.

**Comment by scopatz** [comment]
I am not able to reproduce the hanging issues :cry:

**Comment by astronouth7303** [comment]
Any hang issues are unrelated and I interpreted it as a troll.

I had half a mind to just delete the comment.
