### ISSUE TITLE
@(...) evaluation problems when the expression evaluates to an empty string (or a blank space)

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#3308]
This is in Linux. 

Assume I have this (e.g. in a xsh script):

```
if condition():
    args = '-x'
else:
    args = ''

cmd @(args) file_name
```

The idea is that based on some condition, I may want to set `-x`. 

This was failing for me because if `args` is empty, it seems to pass an empty string as an argument to the subprocess command. So the command thinks I'm running:

`cmd '' file_name`

What is the solution for this? Right now I'm simply testing for condition and constructing two separate commands. This will become unwieldy if I have multiple such cases.

I'm not sure what the fix would be here. I was tempted to say that if it sees an empty string (or even a whitespace only string), to not pass it on to the command. But I can see that may break some tools. Would a better alternative be to filter for `None`?

## xonfig

```
+------------------+----------------------+
| xonsh            | 0.9.11               |
| Git SHA          | dd16d59d             |
| Commit Date      | Aug 25 13:21:16 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```

**Comment by astronouth7303** [comment]
Make args a list or other sequence.

**Comment by beetleb** [comment]
That did the trick. Is this documented somewhere?

**Comment by astronouth7303** [comment]
https://xon.sh/tutorial.html#python-evaluation-with

https://github.com/xonsh/xonsh/wiki/Cheatsheet

I'm not sure this specific quirk is documented, other than "Strings are unconditionally added to the argument list".

**Comment by beetleb** [comment]
I had read that and yes, it wasn't clear to me. Or rather, that's how I found out my empty string wouldn't work, but not sure what would. Using None didn't work. I would have expected an empty list to either become a null string or None. But apparently an empty list did work.

In any case, I'll close this.
