### ISSUE TITLE
Cannot use emacsclient -t as $EDITOR

### ISSUE THREAD

**Issue by Grannath** [xonsh/xonsh#3311]
I try using `emacsclient -t` as an editor to be called from e.g. git. But this does not work. The screen shows the emacs frame, but key presses just get printed to the screen. Nothing seems to reach the emacsclient. Escapes are also just printed. ^C does exit it, but the shell often becomes unusable afterwards.

## xonfig
```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.10          |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | manjaro         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

emacsclient should receive keystrokes.

## Current Behavior

emacsclient does not receive any keystrokes. Input gets printed directly onto the screen.

I tried mlterm and kitty, both have the issue. I tried it in tmux and without, does not matter. Happens also with readline shell. It does not happen in bash. It is also fine if I call the emacsclient myself, not indirectly via some tool. It used to work with git at least, not with others like yaourt. After the latest system update, git also does not work. I am not sure unfortunately if git and/or xonsh were part of that upgrade.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

At least on my machine, as far as I can tell, this is enough:
```
$ $EDITOR = 'emacsclient -t -a=""'
$ git commit
```

**Comment by Grannath** [comment]
@halloleo Yes, I do, as a daemon (emacs --daemon). If I call it as `emacsclient -t`, it works just fine. That's my workaround for now. But `emacsclient -t` does not work.

I'm here just by exclusion principle. I've tried to exchange every part of my stack. Nothing changed it, except switching from xonsh to bash. But it's possible (or likely) I forgot to try something. So, if I can help somehow, please say so. It's also possible that it happens because of the order in which things were installed or updated, so now some dependencies are messed up.

**Comment by eppeters** [comment]
I have the same issue with `vim` and `ansible-vault edit`, which opens an `EDITOR` instance. I also have this trouble with `git`, as you do.

```
eddie@eddie-ubuntu ~ $ xonfig                                                                                                                     
+------------------+----------------------+
| xonsh            | 0.9.11               |
| Git SHA          | 00dd8374             |
| Commit Date      | Sep 26 08:37:43 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

I am thinking about using `git bisect` to find the commit that introduced the problem.

**Comment by scopatz** [comment]
Thanks for reporting @Grannath! It would be great if an emacs user could verify this.  For what it is worth, I have my `$EDITOR` set to a custom editor in my xonshrc and all third party packages seem to work just fine.

**Comment by Grannath** [comment]
@scopatz I am moderately sure it's not a general issue. I don't really know the stack that is involved in xonsh, and I'm no Python dev. Can you point me to some Python libraries I should try reinstalling/rolling back/whatever to get down on the cause?

**Comment by scopatz** [comment]
Actually an interesting thing I realized here is that all of the `$EDITOR` values listed here that have problems have spaces in them.  Can you all test to see if these issues go away if you provide a full path and/or no spaces?

**Comment by halloleo** [comment]
@scopatz I have replicated the scenario (xonsh in an xTerm, `$EDITOR` set as listed above as `emacsclient -t -a=""'` , Emacs running as daemon only, then issuing `git commit` in xonsh) - and for me Emacs opens the commit buffer in the xterm terminal as you'd expect.

However some weird things are going on, because `git` opens Emacs even when no EDITOR is set! - This might have to with my xdg settings or so... Maybe something like this might come into play for you too,  @Grannath?
