### ISSUE TITLE
import zsh history file to xonsh history file

### ISSUE THREAD

**Issue by FirstLoveLife** [xonsh/xonsh#3312]
Hi, I'm new to xonsh. I was a zsh user and have a large zsh history file. I learned xonsh stored its own history in some json files. Is there any convinent way to import my zsh history into xonsh's json  history files?

**Comment by gforsyth** [comment]
Hey @FirstLoveLife -- there's some conversation about this in #1614.  There are convenience functions to _show_ `zsh` history but nothing built in to import it into xonsh history.  That said, there seems to be a script that will do just that: https://github.com/xonsh/xonsh/issues/1614#issuecomment-483386184

You can give that a shot -- if it works, we'd be happy to have it included in our history utils.

**Comment by FirstLoveLife** [comment]
> Hey @FirstLoveLife -- there's some conversation about this in #1614. There are convenience functions to _show_ `zsh` history but nothing built in to import it into xonsh history. That said, there seems to be a script that will do just that: [#1614 (comment)](https://github.com/xonsh/xonsh/issues/1614#issuecomment-483386184)
> 
> You can give that a shot -- if it works, we'd be happy to have it included in our history utils.

Thanks! But that python script has syntax error: 

```
  File "a.py", line 11
    history_lines = $(zsh -i -c 'fc -R ~/.zsh_history; fc -l -t "%s" 0').splitlines()
                    ^
SyntaxError: invalid syn
```

How to fix it?

**Comment by gforsyth** [comment]
That script is a xonsh script, not a python script. If you run it with xonsh it should work.

**Comment by FirstLoveLife** [comment]
@gforsyth thanks for the tip. there is still error after use xonsh instead of python:

```
chenli% xonsh a.py
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 4, in <module>
    main()
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 24113, in main
    _failback_to_other_shells(args, err)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 24077, in _failback_to_other_shells
    raise err
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 24111, in main
    return main_xonsh(args)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 24155, in main_xonsh
    args.file, shell.execer, glb=shell.ctx, loc=None, mode="exec"
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 3038, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 2943, in run_compiled_code
    func(code, glb, loc)
  File "a.py", line 28, in <module>
    print(hist.info().filename)
AttributeError: 'collections.OrderedDict' object has no attribute 'filename'
```

**Comment by scopatz** [comment]
That seems like a bug in the actual script / API

**Comment by anki-code** [comment]
I think this issue should be closed because we already have 1614.

**Comment by anki-code** [comment]
@gforsyth please close this issue.
