### ISSUE TITLE
xonsh doesn't play well with percol

### ISSUE THREAD

**Issue by FirstLoveLife** [xonsh/xonsh#3316]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.8           |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior

`ps aux | percol` works fine in bash/fish/zsh, but not in xonsh. 
![image](https://user-images.githubusercontent.com/37442588/65205541-2e7c8800-dac0-11e9-91f4-1bdc0de404e6.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/37442588/65205710-553abe80-dac0-11e9-92f3-d75c998b3e4b.png)

## Steps to Reproduce

sudo apt install percol
ps aux | percol

**Comment by gforsyth** [comment]
Thanks for reporting @FirstLoveLife !  For a temporary workaround, you can add the following to your `xonshrc` and things should work as expected:

```
__xonsh__.commands_cache.threadable_predictors['percol'] = lambda x: False
```

Looks like our heuristics for detecting curses-like things aren't catching `percol` for some reason.

**Comment by scopatz** [comment]
Probably because it is written in Python and doesn't have the curses link soon enough.  Let's add this to the stock ones
