### ISSUE TITLE
cannot get path completion for tar

### ISSUE THREAD

**Issue by FirstLoveLife** [xonsh/xonsh#3318]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.8           |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

```

</details>

## Expected Behavior

![image](https://user-images.githubusercontent.com/37442588/65484071-e8189600-ded0-11e9-8832-13c0ca34e09c.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/37442588/65484093-fb2b6600-ded0-11e9-97a0-7cf0970456ae.png)

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

tar /tmp/whatever-you-have-then-tab

**Comment by FirstLoveLife** [comment]
Well, I find tar -xf /tmp/xxx works fine though

**Comment by laloch** [comment]
Hi @FirstLoveLife, the odd completions you see are in fact generated by [bash-completion](http://github.com/scop/bash-completion) completer. Since `tar` requires the first argument to be one of [-]{A|c|d|r|t|u|x}, not a path, the command you are trying to complete is invalid and the completer is getting confused.
You would observe exactly the same behavior in bash.
