### ISSUE TITLE
expression len('{cwd}') in $PROMPT definition is not updated/false?

### ISSUE THREAD

**Issue by v217** [xonsh/xonsh#3322]
Following the docs this should work:

    $PROMPT =lambda: '{cwd}\n' if len('{cwd}') > 10 else '{cwd}'

I am on ubuntu 19.04 - python3.8 and I use the latest xonsh version. It neither works with all xontrib loaded or unloaded.
Thank you for this wonderful project, where in contrast to ipython,  
sh never gets called, so I don't have to read sh/bash documentation never again. Please keep it simple!

**Comment by v217** [comment]
Ok my fault I am just getting started

**Comment by v217** [comment]
I thought I found the issue.

**Comment by melund** [comment]
Thanks for reporting tis @v217. I am not sure this is an error. I think the `{cwd}` parts may only be expanded after the lambda function has been evaluated.

**Comment by v217** [comment]
Would it not be for the docs, I would have written the prompt without the lambda:

    $PROMPT ='{cwd}\n' if len('{cwd}') > 10 else '{cwd}'

But this way I get the same result. I close the issue, so there is one issue less, and I am quite happy with my current configuration.
