### ISSUE TITLE
xonsh.org records

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#3338]
Just noticed that the `xon.sh` and `xonsh.org` DNS records mismatch.

I think `xonsh.org` has an explicit `A` record pointing to the legacy GitHub Pages IP address.

`xon.sh` is using the correct aliasing techniques.

`xonsh.org`'s DNS configuration should be updated.

**Comment by scopatz** [comment]
Yep, I am working on transfering the registration right now.  Will fix once it is done

**Comment by anki-code** [comment]
This issue looks not actual and should be closed.

**Comment by scopatz** [comment]
Finally fixed. Thanks!
