### ISSUE TITLE
Aliases not execute on OpenBox

### ISSUE THREAD

**Issue by ErickTucto** [xonsh/xonsh#3341]
### xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.4                |
| Git SHA          | a258fdbe             |
| Commit Date      | May 22 11:04:33 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```

</details>

## Expected Behavior
Keybinds of Openbox will execute aliases xonsh

## Current Behavior
![settings](https://user-images.githubusercontent.com/22831024/66236580-76063500-e6b8-11e9-993a-ba3fe8102e7c.png)
my `rc.xml` and `.xonshrc`

**Comment by astronouth7303** [comment]
1. Double check how openbox executes configured commands. The results vary by application by application and can be very surprising.
2. That's not the syntax for aliases? Unless I missed something.
3. `.xonshrc` is only loaded in interactive contexts (#3275 is a related feature request)

**Comment by ErickTucto** [comment]
Better leave this as documentation, because this issue is more for OpenBox than Xonsh.

The solution I gave him was to create an `volumen.xsh` script

I attach my rc.xml
![imagen](https://user-images.githubusercontent.com/22831024/69486525-9df15980-0e1a-11ea-8037-f77d5a9ec733.png)

I attach my script volume.xsh (sorry for the spanish)
![imagen](https://user-images.githubusercontent.com/22831024/69486538-cb3e0780-0e1a-11ea-9419-d684a11f4617.png)
