### ISSUE TITLE
Suggestion: Make coreutils default on windows. 

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#3343]
Windows is really missing coreutils, and the default 'echo' from cmd.exe behaves radically different than the posix version. 

How do people feel about making the coreutils xontrib enabled by default on Windows? 

(Do we have a default place to do that?)

**Comment by scopatz** [comment]
I am in favor of this, especially if coreutils are missing otherwise (ie no git-bash installed).  As out main windows dev, @melund, I think this is kind of up to you :wink: 

> Do we have a default place to do that?

Not really, no.  We could add an element to `$XONSHRC` that lives in the xonsh source code directory. On Windows we could then install a file that says "xontrib load coreutils".

**Comment by astronouth7303** [comment]
`$XONSHRC` isn't used in scripts, though, right?

The desired effect is "please autoload this xontrib on Windows", right?

**Comment by scopatz** [comment]
Yeah that is right, it would only affect interactive use.  We could add an envar for autoloaded xontribs...

**Comment by astronouth7303** [comment]
We should discuss that in some of the other issues I've opened.

**Comment by melund** [comment]
@astronouth7303 . Do you mean #3275?

**Comment by astronouth7303** [comment]
There's a nebulous feature with #3275 and #2151, yeah.

The general idea is there's code that's not core to the parsing, REPL, job management, etc, but is:

* Essential to a modern usable shell
* Essential for certain platforms
* Essential for certain distribution methods

Of course, all of that is just the mechanism that should be used to implement this bug. What the question we should ask here is how much the xonsh+windows environment should deviate from other shell environments. (And how much do other shells on windows deviate?) Do we want to posixify windows or allow it to continue to be its own thing?

**Comment by nedsociety** [comment]
> What the question we should ask here is how much the xonsh+windows environment should deviate from other shell environments. (And how much do other shells on windows deviate?) Do we want to posixify windows or allow it to continue to be its own thing?

PowerShell already provides some of "posixification" by aliasing -- hit `ls` in PS and you'll see it's actually `Get-ChildItem`. Same for `tee` (= `Tee-Object`), `cat` (= `Get-Content`), `echo` (= `Write-Output`) and so on. While the actual behavior of those commands is vastly different from POSIX counterparts, it still shows that MS do care about availability of those names in the shell, so in that perspective xonsh would not deviate much by defaulting coreutils.

**Comment by scopatz** [comment]
That's really good to know.  Thanks @nedsociety

**Comment by anki-code** [comment]
I'm going to close this because the details around the initial suggestion were described and we still not use coreutils by default because of it.
