### ISSUE TITLE
Feature to function as a Makefile alaternative

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3353]
To use xonsh for managing redundant tasks in a project, now I have to create functions and run them passing arguments inside a xonsh shell. If it can work as a Makfile alternative and detect tasks and autocomplete arguments in a cli fashion , it will reach to large number of audience. Now there are python libraries like [invoke](http://www.pyinvoke.org/), plumbum etc.,

But their way of writing shell commands doesn't feel natural. 

Is it possible to make xonsh to understand files named tasks.xsh automatically and work from other shells as well?

**Comment by astronouth7303** [comment]
I think this is out of scope for the core xonsh project. However, it would be very easy to write a xonsh-based tool to do this.

xonsh exposes both import and compile/eval functions, so the process is:

1. Do taskfile discovery
2. Load files
3. Examine the resulting namespaces for tasks
4. Parse CLI args and dispatch tasks

This is easily accomplished with the standard python compiling, evaluating, and introspection tools, all of which xonsh supports and integrates with. (Remember, xonsh is a shell-flavored python superset.)

There's also a lot of design decisions to be made about specific features--Do you want just task execution? Do you want make-ish features, such as dependencies? Do you want to support build-like tasks with inputs and outputs?

I encourage you to write this, it would be a great contribution to the xonsh ecosystem! But again, out of scope for the core runtime and shell.

**Comment by astronouth7303** [comment]
Like, the core of it is something like:

```
args = parse_args()
namespace = {}
evalx(p"__tasks__.xsh".read_text(), namespace, filename="__tasks__.xsh")
namespace[args.task_name](args.task_params)
```

**Comment by jnoortheen** [comment]
Thanks for the code. I will create one such library in the line of pyinvoke.
