### ISSUE TITLE
How to change input color?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3356]
Hello @scopatz! Thank you for the great solution!

Could you please help me to implement my theme:

![image](https://user-images.githubusercontent.com/1708680/66709996-34405300-ed78-11e9-9988-3ce9f4ae6af3.png)

1. What is the best way to change the color of input? I need one color with high intensity (lime color).
2. What is the best way to draw background for toolbar along all terminal window like on screenshot?

Thanks!

**Comment by anki-code** [comment]
The start point is here — https://xon.sh/tutorial.html#customizing-the-prompt :)

**Comment by anki-code** [comment]
Theme draft:
```
def bar():
  cols=$(tput cols).strip()
  pwd=$(pwd).strip()
  date=$(date --rfc-3339=sec).strip()
  lp="{pwd}".format(pwd=pwd)
  rp="{date}".format(date=date)
  wlen = int(cols) - len(lp) - len(rp)
  w = ' '*wlen
  bar = '{lp}{w}{rp}'.format(lp=lp, w=w, rp=rp)
  return '{BACKGROUND_#111}{#AAA}%s{NO_COLOR}' % bar 

$PROMPT_FIELDS['bar'] = bar
$PROMPT="\n{bar}\n{WHITE}{prompt_end}{NO_COLOR} "
```

@scopatz I tried to search the solution to disable syntax highlighting and set the lime color for typed command but have no result. Could you please help me?

**Comment by scopatz** [comment]
Hi there @anki-code! What is the output of your `xonfig` command?  With the readline shell something like `$PROMPT = $PROMPT + "{GREEN}"` works for me, though this does not work for prompt-toolkit.

**Comment by anki-code** [comment]
The highlighting still work for me:
![image](https://user-images.githubusercontent.com/1708680/66871148-b49aca00-efab-11e9-9a01-0a917709e3b1.png)

**Comment by scopatz** [comment]
So the prompt-toolkit shell which you are using has syntax highlighting while you type.  I think that we need a way to set the default `NO_COLOR` value to another color in this case.

**Comment by anki-code** [comment]
I have dark colors for syntax highlighting and this a little annoying because I try to use xonsh day by day. For example if you change page zoom to 70% and review the screenshot above you can see that it's not good for eyes. After this try to scroll a bit above and see lime colors in my previous theme it's perfect and very contrast.

I'm very inspired of xonsh and this detail make me sad. I already tried to change `XONSH_COLOR_STYLE` but have no effect. Most of styles looks dark and without bold. Next I've reviewed the code and it looks like no way to extend color style functions list.

If you can help me it would be like water for me.

**Comment by anki-code** [comment]
Update. After a year:
* The bar theme is here - https://github.com/anki-code/xontrib-prompt-bar
* The solution for change input color is in PR #3878
