### ISSUE TITLE
Simple pipelining

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3366]
Hi! Thank you for great project!

🔽 **Start reading the thread from here** — https://github.com/xonsh/xonsh/issues/3366#issuecomment-545561914

🥈 Most closest solution here — https://github.com/xonsh/xonsh/issues/3366#issuecomment-545673034

**Comment by con-f-use** [comment]
You realize, the Python part of your code is faulty to begin with, so it can't work in xonsh, right?

```
┌─22-23:04 [confus@profusion ~] [1]                                                😱  😱
└$ cat /tmp/test.py                                                                                          
#!/usr/bin/python
import sys
for i, s in enumerate(sys.stdin.readlines()): print("%s %s %s" % (len(s),i,s))

┌─22-23:04 [confus@profusion ~]                                                    😱  😱
└$ echo test | /tmp/test.py                                                                                  
5 0 test
```

That being said, as far as I know, xonsh does not currently support piping into python mode. It will have to be a script.

**Comment by laloch** [comment]
> ```
> # directly taken from 
> echo "hello" | @(lambda a, s=None: s.read().strip() + " world\n")
> ```
> 
> But if one runs this in a recent version of xonsh, xonsh seems to wait for input until the cows come home. Even worse, we now have a process that is not stopped by Ctrl+C and idles in one thread at 100% CPU.

@con-f-use: Works for me just fine on current master/HEAD.

<details>
<summary>xonfig</summary>

```
+------------------+----------------------+
| xonsh            | 0.9.13               |
| Git SHA          | 5648b8d5             |
| Commit Date      | Oct 17 19:02:06 2019 |
| Python           | 3.7.4                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

**Comment by con-f-use** [comment]
Not for me, just checked, also with latest master/HEAD on multiple Ubuntu systems.

<details><summary>Shell session</summary>

    ┌─23-13:43 [jan@jcgbx ~]                                                  😱  😱
    └$ xonfig                                                                       
    +------------------+----------------------+
    | xonsh            | 0.9.13               |
    | Git SHA          | 550d70d2             |
    | Commit Date      | May 22 01:42:07 2019 |
    | Python           | 3.6.8                |
    | PLY              | 3.11                 |
    | have readline    | True                 |
    | prompt toolkit   | 2.0.9                |
    | shell type       | prompt_toolkit2      |
    | pygments         | 2.2.0                |
    | on posix         | True                 |
    | on linux         | True                 |
    | distro           | ubuntu               |
    | on darwin        | False                |
    | on windows       | False                |
    | on cygwin        | False                |
    | on msys2         | False                |
    | is superuser     | False                |
    | default encoding | utf-8                |
    | xonsh encoding   | utf-8                |
    | encoding errors  | surrogateescape      |
    +------------------+----------------------+

    ┌─23-13:43 [jan@jcgbx ~]                                                  😱  😱
    └$ echo "hello" | @(lambda a, s=None: s.read().strip() + " world\n")            
    ^C^C^C^C^C^X   # Waiting forever, cannot abort with Ctrl + C

</details>

**Comment by laloch** [comment]
Could you please checkout d78207459445ddb804f04859e62db5733ecfb0db and try again?

**Comment by con-f-use** [comment]
d782074 works as expected. :1st_place_medal: 

<details>

    ┌─23-13:53 [confus@jcgbx ~/devel/unix/xonsh]                        😱  master|✓ 😱
    └$ git co d782074                                                               
    Note: checking out 'd782074'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    HEAD is now at d7820745 add appimage.rst to TOC

    ┌─23-13:54 [confus@jcgbx ~/devel/unix/xonsh]                     😱  :d7820745|✓ 😱
    └$ sudo -H pip3 install -e ./                                                   
    [sudo] password for confus: 
    Looking in indexes: http://10.17.65.203/root/test/+simple/, http://10.17.65.203/root/production/+simple/
    Obtaining file:///home/confus/devel/unix/xonsh
    Installing collected packages: xonsh
      Found existing installation: xonsh 0.9.13
        Can't uninstall 'xonsh'. No files were found to uninstall.
      Running setup.py develop for xonsh
    Successfully installed xonsh
    ┌─23-13:54 [confus@jcgbx ~/devel/unix/xonsh]                     😱  :d7820745|✓ 😱
    └$ xonsh  
                                                                          
    ┌─23-13:54 [confus@jcgbx ~/devel/unix/xonsh]                     😱  :d7820745|✓ 😱
    └$ xonfig                                                                       
    +------------------+----------------------+
    | xonsh            | 0.9.13               |
    | Git SHA          | d7820745             |
    | Commit Date      | Oct 17 18:16:53 2019 |
    | Python           | 3.6.8                |
    | PLY              | 3.11                 |
    | have readline    | True                 |
    | prompt toolkit   | 2.0.9                |
    | shell type       | prompt_toolkit2      |
    | pygments         | 2.2.0                |
    | on posix         | True                 |
    | on linux         | True                 |
    | distro           | ubuntu               |
    | on darwin        | False                |
    | on windows       | False                |
    | on cygwin        | False                |
    | on msys2         | False                |
    | is superuser     | False                |
    | default encoding | utf-8                |
    | xonsh encoding   | utf-8                |
    | encoding errors  | surrogateescape      |
    +------------------+----------------------+

    ┌─23-13:54 [confus@jcgbx ~/devel/unix/xonsh]                     😱  :d7820745|✓ 😱
    └$ echo "hello" | @(lambda a, s=None: s.read().strip() + " world\n")            
    hello world

</details>

**Comment by laloch** [comment]
OK, thanks for testing. Could you please file a bug report against  5648b8d528824aaca3776d33578dc6a802e6d9ae? Thank you!

**Comment by con-f-use** [comment]
How does one file a bug report against a commit? The only thing I could think of is opening an issue mentioning the respective commit and PR (https://github.com/xonsh/xonsh/pull/3342).

**Comment by laloch** [comment]
Yes, exactly. Sorry for the confusion.

**Comment by anki-code** [comment]
@laloch have you any comments about first message of this issue?

**Comment by laloch** [comment]
@anki-code, as already pointed out by @con-f-use, both your shell code and Python are syntactically wrong. I'm afraid that it's not possible to enumerate lines of standard input on a single line and yield a string as an output at the same time. Let's first create simple helper function to enumerate the lines and apply arbitrary modifications on them:
```python
def filter_stdin(stdin, stdout, filter):
    n = 0
    # call `filter` function for each input line and print the result
    for l in stdin.readlines():
        print(filter(l.rstrip(), ++n), file=stdout)
```
Now we can use it in our shell code:
```
$ ls -1 | @(lambda a,i,o: filter_stdin(i, o, lambda l,n: f"{len(l)} {l} {n}")) | sort -rn | head | @(lambda a,i,o: filter_stdin(i, o, lambda l,n: f"Winner {l}")) > result.txt
```

**Comment by anki-code** [comment]
@laloch thank you for example! My question is about how to reduce the overhead (exclude function and "lambda a,i,o" in your example).

Is there a way to create function @@() and write just `ls -1 | @@(for filename in i: print(i+'!!!'))`?

**Comment by con-f-use** [comment]
It's not really another issue, because if piping doesn't work at all, nothing you want can. Also there is no function to delete or hide comments in github.

On the subject, I agree that the `lambda` thing is very clunky and would like to see a better way.

**Comment by laloch** [comment]
@anki-code: if you don't want to fiddle with the parser code, you can achieve similar results using callable alias:
```python
def _stdfilter(args, stdin, stdout):
    command_string = "lambda line,index:"
    for arg in args:
        command_string += arg + " "
    command_string = command_string.strip()
    fn = eval(command_string)
    index = 0
    for line in stdin.readlines():
        index += 1
        res = fn(line.rstrip(), index)
        print(res, file=stdout, flush=True)

aliases['stdfilter'] = _stdfilter
```
```
$ ls -1 | stdfilter "str(len(line))"
$ ls -1 | stdfilter "f'{len(line)} {line} {index}'" | sort -rn | head | stdfilter "f'Winner {line}'" > result.txt
```

**Comment by anki-code** [comment]
@laloch thanks for tasty piece of code! I tried similar solution )

I stopped experiments on trying to this "not working macro concept":
```python
def pp(cmd):
  eval(cmd)

> ls -1 | pp!(for s in stdin: printf(s+'!!!')) | head
```
If we could mix alias and macro and could catch the stdin it probably will be elegant solution.
For concept example:
```python
def pp(cmd, *, args=None, stdin=None, stdout=None, stderr=None):
  eval(cmd)

> ls -1 | pp!(for s in stdin: printf(s+'!!!')) | head
bin!!!
boot!!!
...
```

**Comment by anki-code** [comment]
@laloch many thanks! The more simple version is works for me like a charm:

```python
def _pp(args, stdin, stdout):
    fn = eval('lambda line:'+arg[0])
    for line in stdin.readlines():
        res = fn(line)
        print(res, file=stdout, flush=True)
			
aliases['pp'] = _pp
		
ls -1 | pp "line[:2]+'!!!'" | head
```

**Comment by laloch** [comment]
You are welcome. This is indeed very useful.
Just a side note: The correct way of stripping the line ends would be:
```python
import os
res = fn(line.rstrip(os.linesep))
```

**Comment by anki-code** [comment]
The `pl` alias turned out to be so convenient that I added a separate [xxh-plugin-pipe-liner](https://github.com/xonssh/xxh-plugin-pipe-liner) for [xxh](xxh) and using it day by day. JFYI @scopatz

**Comment by anki-code** [comment]
xontrib-pipeliner is here https://github.com/xonsh/xonsh/pull/3558
