### ISSUE TITLE
Environment changes are not propagated

### ISSUE THREAD

**Issue by con-f-use** [xonsh/xonsh#3371]
**Edit:**

During discussion this issue basically boils down to: Is it intended behavior that 

1.) Individual variables cannot be mareked for export to `os.environ`, it's all-or-nothing with `$UPDATE_OS_ENVIRON`?

2.) xonsh behaves differently than what users of other shells would expect, when xonsh itself runs in a subprocess and an exported variable of the parent process is changed via `$VARNAME=value` in xonsh? 

------

Changing the environment inside xonsh, does not effect subprocesses:

```
bash$ export SENTINEL=WOHOO
bash$ xonsh

xonsh$ echo $SENTINEL                                                               
WOHOO
xonsh$ __xonsh__.env['SENTINEL']='WOOPS'                                                                                                
xonsh$  import subprocess; subprocess.check_output('echo $SENTINEL', shell=True)                        
b'WOHOO\n'     # this is the old value
```

in contrast:

```
bash$ export SENTINEL=WOHOO
bash$ bash

bashbash$ echo $SENTINEL                                                               
WOHOO
bashbash$ SENTINEL='WOOPS'                                                                                                
bashbas$  bash -c 'echo bashbashbash: $SENTINEL'                        
bashbashbash: WOOPS
```

There is also no good way to pass the environment:

```
xonsh$ subprocess.check_output('echo $SENTINEL', shell=True, env=os.environ.copy())                                                            
b'WOHOO\n'   # old value

xonsh$  subprocess.check_output('echo $SENTINEL', shell=True, env=__xonsh__.env)                                                                     
TypeError: expected str, bytes or os.PathLike object, not int
```

**Comment by laloch** [comment]
Hi @con-f-use, I believe that what you need is `$UPDATE_OS_ENVIRON = True`.

**Comment by con-f-use** [comment]
Oh, did know that existed. Thanks a bunch. Do you know, why it isn't the default?

**Comment by laloch** [comment]
> Thanks a bunch. Do you know, why it isn't the default?

You're welcome.
I think that's analogous to the sh-like shell's `export` command - most of the time you do not want to propagate the local environment changes to your child processes. If you do, you must call `export` explicitly. I admit, that the Xonsh's way of exporting variables is neither obvious nor convenient.

**Comment by laloch** [comment]
Just for the sake of completeness, you can always manipulate the OS environment in the usual Pyhonic way:
```
laloch@uriel ~ $ echo $SENTINEL
$SENTINEL
laloch@uriel ~ $ import os, subprocess
laloch@uriel ~ $ os.environ['SENTINEL']='WOOPS'
laloch@uriel ~ $ subprocess.check_output('echo $SENTINEL', shell=True)
b'WOOPS\n'
```

**Comment by con-f-use** [comment]
related https://github.com/xonsh/xonsh/issues/3227

**Comment by con-f-use** [comment]
I still maintain, this is a bug, because in every other shell I know, one a variable is marked for export to subprocesses, changes to it, will be exported as well:

e.g. Bash:
```
bash-prompt$ export SENTINEL=woohoo
bash-prompt$ bash -c 'echo $SENTINEL'
woohoo

bash-prompt$ SENTINEL=WOOPS
bash-prompt$ bash -c 'echo $SENTINEL'
WOOPS

# and even:
bash-prompt$ bash
bash-in-bash$ SENTINEL=shell-in-shell
bash-in-bash$ bash -c 'echo $SENTINEL'
shell-in-shell
```

**Comment by astronouth7303** [comment]
This only occurs if you use `subprocess`. `xonsh.lib.subproces` does not have this problem, and neither do xonsh language primitives.

Otherwise, `subprocess.run(..., env=${...}.detype())` (or the real python alternative, `subprocess.run(..., env=__xonsh__.env.detype())`) should work reliably.

`$UPDATE_OS_ENVIRON` causes updates to `${...}`/`__xonsh__.env` to be propagated to `os.environ`, which isn't used by xonsh's implementations.

**Comment by anki-code** [comment]
> $UPDATE_OS_ENVIRON

It will be great if the [Environment Variables](https://xon.sh/tutorial.html#environment-variables) section in the tutorial will contains a few words about this flag. I've spend time while searching why manipulations with `${...}` have no affection on `os.environ`. By the description in the tutorial they looks like the synonyms.
