### ISSUE TITLE
A way to donate to the xonsh shell

### ISSUE THREAD

**Issue by con-f-use** [xonsh/xonsh#3375]
I have found the xonsh developers, especially Anthony (@scopatz), David (@laloch) and Gil (@gforsyth) very patient, competent, helpful and kind. I'm sure all other developers and helpers are too, it's just that I haven't interacted with you yet. I also find the xonsh-project exceptionally responsive, well run and maintained. 

That's why I would like to have a way to donate to the project (if there is none I overlooked). Thanks for your efforts, people!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by astronouth7303** [comment]
So the primary problem is that there's currently no legal entity to accept the funds and then do things with them. I think Anthony owns and handles a lot of the xonsh stuff (domains, service accounts, etc).

There's probably a few of us setup for funding? (I, personally, have a ko-fi and GitHub Sponsors to support the variety of open source that I do. Not sure who else does.)

**Comment by con-f-use** [comment]
Maybe a list with members and their respective tip-jars, then?

**Comment by astronouth7303** [comment]
Ok, the following xore members have registered with GitHub Sponsors:

* @astronouth7303 
* @Carreau

I was able to discover additional services for these users:

* @astronouth7303: [ko-fi](https://ko-fi.com/astraluma)

(I'm not including direct payment options, like PayPal, Square Cash, Keybase, etc unless well advertised.)

**Comment by gforsyth** [comment]
Hey @con-f-use -- thanks so much!  We're glad that you're enjoying xonsh!  

As @astronouth7303 pointed out, there is a bit of a tricky dimension around group projects and accepting donations -- certainly in the interim the individuals can post up details to accept donations.  

I'd like to work out something eventually where maybe those tips, etc, can be used to pay for stickers and other swag.  

Xonsh Inxorporated?  

But on a serious note, if any other projects have something like this set up it would be good for us to look it over.

Thanks again for the kind words, @con-f-use !

**Comment by con-f-use** [comment]
> I think Anthony owns and handles a lot of the xonsh stuff (domains, service accounts, etc).
so [bus factor = 1](https://en.wikipedia.org/wiki/Bus_factor)? I hope not.

> I'd like to work out something eventually where maybe those tips, etc, can be used to pay for stickers and other swag.
...and maybe the infrastructure and services involved with xonsh.

In some countries it's very easy to found a service club or non-profit, that core developers then join.

**Comment by scopatz** [comment]
Yep we *need* to do this

**Comment by JackofSpades707** [comment]
> Yep we _need_ to do this

Please do. I love the idea of a shell that easily lets you write code in a language with real data types while also supporting bash/zsh for legacy reasons

This is a great step forward in the right direction :)

**Comment by anki-code** [comment]
We added the section about community by #4585 and I'm going to close this issue until news about our organization.
