### ISSUE TITLE
Weird completion issue

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#3379]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.12          |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior

Tab completion behind shell command `vim` should work

## Current Behavior

existing file is not being found by completion (see screenshot).
As you can see in the lower part of the screenshot, the file `pip_packages_to_install.txt` exists in the current folder but isn't found when used behind the shell command `vim` (but does work behind `cat`).
Is this maybe created by interfering completions installed elsewhere? Maybe some vim completions from homebrew?

<img width="822" alt="Screenshot 2019-10-31 14 11 02" src="https://user-images.githubusercontent.com/69774/67982582-99090380-fbe8-11e9-839a-b6fd0536a3ed.png">

**Comment by michaelaye** [comment]
Addition: `code pip_` also does not autocomplete, which is annoying, so both my editors don't auto-complete.

**Comment by michaelaye** [comment]
adding a ./ in front doesn't help either.

**Comment by gforsyth** [comment]
Thanks for reporting @michaelaye !  The completers fire in order and the `pip` completer comes before the `path` completer -- what's happening here is that the `pip` completer is firing (incorrectly).  

This regex needs to be a little less aggressive: https://github.com/xonsh/xonsh/blob/master/xonsh/completers/pip.py#L10-L12

**Comment by michaelaye** [comment]
of course I get a regex-related reply ON HALLOWEEN!! ;) *scares_the_s***_outta_me* ;)
