### ISSUE TITLE
xonsh incorrectly reorders the test for the pytest

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3380]
mixed (`.py`+`.xsh`) pytests runs in unpredictable or chaotical order.

The main issue:
https://github.com/pytest-dev/pytest/issues/6114

The issue which might be connected too:
https://github.com/pytest-dev/pytest/issues/6113

## xonfig

<details>

```
+------------------+-----------------------------------------------+
| xonsh            | 0.9.12                                        |
| Git SHA          | 50155c66                                      |
| Commit Date      | Oct 3 15:53:08 2019                           |
| Python           | 3.7.3                                         |
| PLY              | 3.11                                          |
| have readline    | False                                         |
| prompt toolkit   | 2.0.10                                        |
| shell type       | prompt_toolkit2                               |
| pygments         | None                                          |
| on posix         | False                                         |
| on linux         | False                                         |
| on darwin        | False                                         |
| on windows       | True                                          |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x027659B0> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x02765870> |
| is superuser     | False                                         |
| default encoding | utf-8                                         |
| xonsh encoding   | utf-8                                         |
| encoding errors  | surrogateescape                               |
+------------------+-----------------------------------------------+
```

</details>

## Expected Behavior
correct order independent to the test file extension

## Current Behavior
random tests order

## Steps to Reproduce
see the above link

**Comment by scopatz** [comment]
Is there anything that we should do here?

**Comment by andry81** [comment]
I don't see how the file is related to the issue is changed: https://github.com/pytest-dev/pytest/issues/6114#issuecomment-548786834
Should I retest it while a change is not take a place?

**Comment by scopatz** [comment]
I think that @melund wrote most of https://github.com/xonsh/xonsh/blob/master/xonsh/pytest_plugin.py so maybe he knows

**Comment by melund** [comment]
I can't remember any of it. I will try to one investigate why we choose to do this is the first place. Otherwise, I will definitely remove that code.

**Comment by melund** [comment]
I think the bad attempt at reordering test was done because we had a bug once where certain test could not run after each other. I belive that has since been fixed.

**Comment by andry81** [comment]
I just commented related line of code: https://github.com/xonsh/xonsh/blob/bb201d77bb0ad7e439739ae008a19dae65de6652/xonsh/pytest_plugin.py#L17
and it fixed the reordering (pytests orders by function name instead by a file path/name)
