### ISSUE TITLE
Background color spanning an entire line of prompt

### ISSUE THREAD

**Issue by gotgenes** [xonsh/xonsh#3388]
After seeing #3356, I'm curious, is it possible to have a background color span an entire line of the prompt in xonsh, as shown in this screenshot (specifically, the lines that begin with "`root abc`")?
![prompt with background spanning entire line](https://user-images.githubusercontent.com/1708680/66709996-34405300-ed78-11e9-9988-3ce9f4ae6af3.png)

I believe the screenshot is from a zsh shell session.

I really like the improvement in delineation of each prompt due to the background spanning the whole line. It makes it easy to identify prompts in the history, especially when scrolling back through large outputs.

**Comment by gotgenes** [comment]
Is this a question that needs to be taken to the Prompt Toolkit team?

**Comment by scopatz** [comment]
I don't know who this should go to

**Comment by gforsyth** [comment]
@gotgenes -- I'm not sure if this is supported by prompt toolkit or not, so it's probably worth asking upstream _if_ it's possible and then we can tackle implementing it in `xonsh` if it is.

**Comment by gotgenes** [comment]
Thanks for looking at this @scopatz and @gforsyth. I will take this question upstream to prompt-toolkit's team.

**Comment by gotgenes** [comment]
I have asked this upstream in prompt-toolkit/python-prompt-toolkit#1111.

**Comment by scopatz** [comment]
Thanks @gotgenes!

**Comment by anki-code** [comment]
@gotgenes This is my everyday theme :)
You can get the example from xxh project - https://github.com/xxh/xxh-plugin-xonsh-theme-bar
Put the code from `pluginrc.xsh` to your `.xonshrc`.
