### ISSUE TITLE
Add support for prompt_toolkit 3.0

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#3391]
Shouldn't be as tricky as the 1->2 upgrade, but we'll probably need to change a few things around.

**Comment by laloch** [comment]
As far as I can tell, we do not use any PTK2 features that changed in PTK3. The only function we need to change is https://github.com/xonsh/xonsh/blob/777bdc73095317649a619d7ff2b66eabf4b02c8c/xonsh/platform.py#L200
which does not have any internal users anyway.

**Comment by gforsyth** [comment]
Hey @laloch -- yeah, I thought I'd had issues with ptk3 but I've confirmed that it works without issue now.  At this point I think the work reflected by this issue is just to add the appropriate flags to allow people to explicitly select `ptk3` as their shell choice

**Comment by anki-code** [comment]
This issue looks solved.

**Comment by gforsyth** [comment]
Yep, thanks @anki-code !
