### ISSUE TITLE
rmtree does not work on windows

### ISSUE THREAD

**Issue by SylvainCorlay** [xonsh/xonsh#3392]
This issue is triggered when using conda-press with `--fatten` on windows, which uses `rmtree` to delete temporary wheels. https://github.com/regro/conda-press/issues/57

The culprit is the `rmtree` implementation

```
    try:
        ![rm @(cmd_args) @(dirname)]
    except PermissionError:
        if sys.platform == "win32":
            ![del /F/S/Q @(dirname)]
        else:
            raise
```

It seems to me that we should start with

```
    if sys.platform == "win32":
        ![del /F/S/Q @(dirname)]
```

**Comment by scopatz** [comment]
Yep, that is a much better implementation. PRs welcome!
