### ISSUE TITLE
xonsh and vim read

### ISSUE THREAD

**Issue by con-f-use** [xonsh/xonsh#3396]
In both `vim` and `nvim`, the `:read !ls` command fails when I `:set shell=xonsh`. I have not been able to pin the problem down exactly, but it is an xonsh problem. I suspect it has something to do with the gernal redirection issues, xonsh struggles with at the moment.

```
:r !ls
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jan/devel/unix/xonsh/scripts/xonsh", line 4, in <module>
    main()
  File "/home/jan/devel/unix/xonsh/xonsh/main.py", line 402, in main
    _failback_to_other_shells(args, err)
  File "/home/jan/devel/unix/xonsh/xonsh/main.py", line 366, in _failback_to_other_shells
    raise err
  File "/home/jan/devel/unix/xonsh/xonsh/main.py", line 400, in main
    return main_xonsh(args)
  File "/home/jan/devel/unix/xonsh/xonsh/main.py", line 434, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode="single")
  File "/home/jan/devel/unix/xonsh/xonsh/codecache.py", line 207, in run_code_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/home/jan/devel/unix/xonsh/xonsh/codecache.py", line 119, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 235, in _parse_ctx_free
    raise original_error from None
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/home/jan/devel/unix/xonsh/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/jan/devel/unix/xonsh/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/jan/devel/unix/xonsh/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/jan/devel/unix/xonsh/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/home/jan/devel/unix/xonsh/xonsh/parsers/base.py", line 3399, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/home/jan/devel/unix/xonsh/xonsh/parsers/base.py", line 676, in _parse_error
    raise err
SyntaxError: ca634c3c5553f3487acf383f3f140aee:1:7: ('code: /',)
(ls) > /tmp/nvimSlD9PL/1
       ^
shell returned 1

E485: Can't read file /tmp/nvimSlD9PL/1
```

**Comment by scopatz** [comment]
Any vim experts around?

**Comment by t0fik** [comment]
I'm no expert on Vim, but what I figured out is:
Vim executes shell commands using this syntax:
$SHELL -c '(command) > /tmp/xxxxx/1'
Xonsh does not allow to redirect output from subshell.

**Comment by con-f-use** [comment]
it might be that `xonsh -c '(echo test) > /tmp/xxxxx/1'` is interpreted as python-mode as opposed to `xonsh -c 'echo test > /tmp/xxxxx/1'`.
But yes, you seem to have hit the nail on the head here.

**Comment by t0fik** [comment]
One more thing, if you call built in command like `echo` in parenthesis:
```
(echo foo)
```
It will be executed in shell, but if you call command like `ls`:
```
(ls)
```
Xonsh will start subshell.
For me it seems inconvenient, the POSIX way is to start subshell. It should also resolve problem with redirection to file, correct me if I'm wrong.
As I was able to understand parser code parenthesis are expanded like that:
```
(one-liner) -> xonsh -c 'one-liner'
```
so forcing subshell would produce something simillar to:
```
(one-liner) > /tmp/xxxxx/1 -> xonsh -c 'one-liner' > /tmp/xxxxx/1
```
and that structure work perfectly.

**Comment by bqv** [comment]
Ah, I knew I'd seen this issue somewhere. I'm now hitting this. It is indeed a fix to just `:set shell=bash`, which is sad but also makes some sense

**Comment by anki-code** [comment]
This working for me - https://github.com/anki-code/xonsh-vim-read

**Comment by con-f-use** [comment]
That is not a solution, merely a workarounnd. Please re-open this issue.

**Comment by anki-code** [comment]
1. After diving into this I see how vim works. It calls `$SHELL -c "(command)> /tmp/file"` and put the output to the editor. By default vim expects that the shell is sh compatible shell. The xonsh is not sh compatible shell and this is the cause why the right solution is to have wrapper for calling vim command in xonsh (it's something like `source-bash`).

2. Probably you want to say that xonsh should run command `(ls) > /tmp/file` without error. Maybe it's right. Please create the distinct issue for this syntax proposal. 
But it's wrong to say that this will solve this issue around the vim read function because tomorrow vim can replace `(cmd) > /tmp/file` to another sh compatible crazy syntax command that will fail in xonsh and this is not mean that we should go to xonsh and support this crazy command (see point 1).

**Comment by con-f-use** [comment]
Well, I wouldn't call it "crazy" since it's been this way for a few decades in multiple shells and vim is very unlikely to change it. @scopatz, @gforsyth do round braces have any syntactic meaning in shell-mode in xonsh? Or maybe as a better question, would it break anything if they were used for grouping in shell mode?

**Comment by anki-code** [comment]
I called it crazy to accent the difference. And we facing with the difference again :)
The braces in bash is not just grouping. It's for [call a subshell](https://tldp.org/LDP/abs/html/subshells.html).
So this is the cause we're open to the new issue about braces syntax.

**Comment by con-f-use** [comment]
So round braces are used for grouping in Python mode, right.  We can't have them spawn a subshell as in bash, because that would conflict with python mode and, among other things, make it difficult to distinguish between the two. But if xonsh used it for grouping in shell mode as well, that would give at least a little more compatibility with normal shells in some situations (as evidenced by this vim issue) and make xonsh more consistent between the modes. But I don't have enough background to really oversee all the consequence, hence asking those who have. Grouping is conceptionally similar to subshelling, after all. It just doesn't spawn a new process environment.

**Comment by anki-code** [comment]
> a little more compatibility with normal shells in some situations (as evidenced by this vim issue)

I was thought like you when I did first steps in xonsh world ;) But now I think that this is wrong opinion.
We will kill xonsh if we will do compromise solutions that has no pretty support of sh shells and no pretty good design for Python mindset. The xonsh shell is not posix compatible shell. Let's do the sane language shell.

In this example yes we can support braces and it will work for the single command like `(ls) > file` but vim expects that user can run `ls | grep | head` or `ls | grep && echo 1; echo 2` and this commands will fail in "simple support" in xonsh. In the choise between "simple compromise solution for single command" vs "no support braces" I prefer to choose "no support".

I believe we should building "the sane language shell" instead of "the nice for sh shells with compromise solutions shell".

**Comment by con-f-use** [comment]
I'd say it's a grey area. Only Siths deal in absolutes. Now, again I'm not sure but using round braces for grouping would make xonsh behave more consistent between python mode, where they are for grouping, and shell mode, increase compatibility a little bit and of course `(ls | grep | head) > file` would work.

Also Anki, I love you man, but we started out at around the same time and you do read a little vindictive and condescending here at times. At least to me.

**Comment by anki-code** [comment]
My words could sound strong because I'm not the english speaker :) Sorry for that. When I talk about crazy sh shells syntax I feel more fun feelings than hate feelings :)

I'm completely for improving the behavior around braces.

**Comment by gforsyth** [comment]
> do round braces have any syntactic meaning in shell-mode in xonsh? Or maybe a better question: would it break anything if they were used for grouping in shell mode, so that `xosnh -c '(cmd) > file'` works?

Nothing immediately jumps out at me as a potential problem here.  Possibly the chance for more subproc vs. python-mode collisions but so long as the rest of the tokens aren't defined in python-mode it will be executed as a subproc
