### ISSUE TITLE
Easy way to delete an entry from history?

### ISSUE THREAD

**Issue by Granitosaurus** [xonsh/xonsh#3401]
Is there a way to delete entry from history? History documentation mentions nothing of deletion and whole rich history structure makes it very complicated to do it manually.

**Comment by Granitosaurus** [comment]
I wrote a simple script which while was successfully deleted history the xonsh wasn't smart enough to pick up on that and now all of the history is gone.

https://gist.github.com/Granitosaurus/45d6ab32acfa13ecc793f99275e6be8b

**Comment by scopatz** [comment]
PRs welcome if you want to add that to xonsh itself!

**Comment by Granitosaurus** [comment]
So there's no way to delete history atm? I'd be willing to implement this if that's the case though I'm a bit confused by the absance of this :grimacing:

**Comment by gforsyth** [comment]
> So there's no way to delete history atm?

There's no way built in to xonsh.  If you SIGTERM a shell your history won't be saved unless you've forced the session to cycle already. Otherwise, you can delete individual session files in the history directory.


> I'd be willing to implement this if that's the case

We'd be happy to have this feature available!

**Comment by Granitosaurus** [comment]
@gforsyth 
> If you SIGTERM a shell your history won't be saved unless you've forced the session to cycle already.

That explains why I've been losing history! Is there a way to avoid this? How does one "force the session to cycle already"?

**Comment by gforsyth** [comment]
Hey @Granitosaurus, you can force the history to dump to file by running `__xonsh__.history.flush().join()`

**Comment by anki-code** [comment]
Personally I recommend to use [sqlite history backend](https://xon.sh/tutorial_hist.html#sqlite-history-backend) because it saves commands immediately.

You can remove the command easily:
```python
sqlite3 $XONSH_HISTORY_FILE "SELECT * FROM xonsh_history WHERE inp = 'ls' LIMIT 10;"
# ls|0|1620469031.78598|1620469031.80443|b78b58b8-ab34-4c20-821b-325d345fb72e|||304

sqlite3 $XONSH_HISTORY_FILE "DELETE FROM xonsh_history WHERE inp = 'ls'"

sqlite3 $XONSH_HISTORY_FILE "SELECT * FROM xonsh_history WHERE inp = 'ls' LIMIT 10;"
# empty
```
