### ISSUE TITLE
conda update 3.8 stopped all input into xonsh terminal

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#3404]
don't know how to debug if I can't type anything into the terminal (iterm2 on Mac).

If I didn't know that I can force iterm2 to execute a different shell at startup, I would have no terminal at all, phew.

Don't have time to debug it today as well, but this as a warning to others..

Workaround on Mac: iterm2 settings->Profiles/General->Command->"/bin/bash"

**Comment by michaelaye** [comment]
i know it's caused by:

`conda activate py37`

as the last line of my .xonshrc, because removing that unblocks the terminal.

**Comment by scopatz** [comment]
Is this still happening?

**Comment by michaelaye** [comment]
Don’t know, sorry. Had to stop using xonsh again, too many hiccups.
