### ISSUE TITLE
name '__xonsh_commands_cache__' is not defined

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#3407]
After upgrading from 0.8.12 to the latest, I get this error:

```name '__xonsh_commands_cache__' is not defined```

This comes from this in my rc.xsh:

```
# This will take care of selection and mouse issues in mc
from xonsh.commands_cache import predict_false
__xonsh_commands_cache__.threadable_predictors['mc'] = predict_false
__xonsh_commands_cache__.threadable_predictors['nano'] = predict_false
__xonsh_commands_cache__.threadable_predictors['crontab'] = predict_false
```

And *that* comes from various issues:  #2383 and #2514.

At the moment it seems xonsh has hard coded nano, mc and others, but not crontab. My crontab command launches nano. 

What is the new way to add entries like this in the rc.xsh? 

Thanks.

**Comment by gforsyth** [comment]
Hey @beetleb -- anything that used to being with `__xonsh` is now in a standalone `__xonsh__` namespace object, so you can do `__xonsh__.commands_cache.threadable_predictors["crontab"] = predict_false`

**Comment by beetleb** [comment]
That worked - thanks.
