### ISSUE TITLE
Emacs mode link in docs

### ISSUE THREAD

**Issue by salotz** [xonsh/xonsh#3412]
> This is an emacs feature request. If this exists, we are happy to include links in our docs!

_Originally posted by @scopatz in https://github.com/xonsh/xonsh/issues/1074#issuecomment-511212179_

Now such a thing exists and has a standard installation process via melpa: https://github.com/seanfarley/xonsh-mode

**Comment by scopatz** [comment]
Pull requests welcome!

**Comment by salotz** [comment]
I've made #3469

**Comment by scopatz** [comment]
Merged! Feel free to close this if you think that helps!
