### ISSUE TITLE
xonsh doesn't print result of service with your aliases

### ISSUE THREAD

**Issue by ErickTucto** [xonsh/xonsh#3416]
I create an aliases to use php services and this does not show the status option

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.2                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.5.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior
The `php-dev status` command produces the same output as `service php7.4-fpm status`

## Current Behavior
Print nothing

## Steps to Reproduce
- Create aliases php-dev(see image, red square)
- Execute command on terminal(see image, blue square)

![not-print](https://user-images.githubusercontent.com/22831024/72003536-97c30b00-3217-11ea-8cf8-16f403d7781e.png)

**Comment by laloch** [comment]
Hi @ErickTucto, the `$()` operator you use in your `php(...)` function is a **captured** subprocess operator, which means that it captures the standard output of the enclosed shell command and returns it as a Python string.
What you really mean to do is:
```python
def _php(args):
    sudo service php-7.4-fpm @(args[0])

aliases["php-dev"] = _php
```
Note: I suggest not to use `php()` as the function identificator, because there's most probably a `php` binary already on your system which gets effectively masked by the function defined in your `.xonshrc`.

**Comment by ErickTucto** [comment]
Thank you very much for helping me find my mistake, I will remember your advice the name of the functions and the binaries
