### ISSUE TITLE
Impossible to escape trailing ampersand in subprocess mode

### ISSUE THREAD

**Issue by ju-kreber** [xonsh/xonsh#3417]
## xonfig
```
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.6.10               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.2                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.5.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | linuxmint            |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

## The situation
Assuming I'm in a directory with a file named `&` (this actually happened to me).
I am trying to examine it using `file &` or `file "&"` or `file '&'`

## Expected Behavior
By escaping the `&` through quotes, the single argument `&` should be passed to `file`.
The `bash` shell does it like this and outputs: `&: ASCII text`

## Current Behavior
`file` is started as a job with no argument
`[1]+ running: file & & (8218)`

Note that this is also very inconvenient if you want to `grep -r '&'` or something similar.

## Possible fixes
Although I just installed xonsh and are highly unfamiliar with the code, I took a quick look and came to the conclusion that it may be a bad idea not to treat `&` like `|`.
The command line input `file foo | less` will be represented as command sequence `(['file', 'foo'], '|', ['less'])` while the command line input `file bar '&'` will be represented as `(['file', 'bar', '&'])`, making the ampersand indistinguishable from a regular argument.

**Comment by scopatz** [comment]
Have you tried `@("&")`?

**Comment by ju-kreber** [comment]
Hi, `@("&")` shows the same behavior. I haven't examined it in detail, but it would be very reasonable that it results in the same problematic processing chain I described above.

**Comment by astronouth7303** [comment]
I expect this happens for identical reasons as #2335: It has to do with the shape of the data structures that go from the parser to the execution handler.

**Comment by laloch** [comment]
Yes, this is essentially the same as #2335. It's exceptionally funny (until you happen to run something along the lines of `echo "/dev/sda4" ">" "/dev/sda1"`). The problem is, that the parser yields "<", ">" and "&" as regular (unquoted) subprocess arguments which are indistinguishable from string literals and then, somewhere under `run_subproc`, these are treated specially, depending how many arguments follow or don't.
So, @ju-kreber, in your case the workaround would be `file "&" x` 😉

Jokes aside, this is especially nasty bug, that can eat your hamster.

**Comment by ju-kreber** [comment]
Yeah, I figured it's a parsing problem. However, if I'm right, these problems do not apply to `|`.
For example `file '|'` vs `file |` results exactly in the difference in behavior that I would expect. So shouldn't it be possible to relatively simply change the parser to consider `<`, `>` and  `&` tokens similarly to `|`? Or is there a resulting difficulty that I'm not aware of? :thinking:

**Comment by laloch** [comment]
Not really. The difference is that the pipe operator/token/atom is currently handled by the parser, whereas the redirection and background operators **are not**. The parser does not treat them specially and they are mixed together with the regular subprocess arguments instead.
So no, to fix this is not completely trivial. We most probably need to extend our grammar and wrap the current `subproc` atom into (possibly multiple levels of) input/output redirect atoms and eventually a redirection atom.

**Comment by laloch** [comment]
I forgot to mention that the redirection operators accept arguments by themselves and their syntax is again non-trivial.

**Comment by laloch** [comment]
There's this parser rule, that doesn't seem to get ever triggered :thinking: 
https://github.com/xonsh/xonsh/blob/3d795b85caf6e24ba1877ef213757d3b8bd74da2/xonsh/parsers/base.py#L2994-L2997

**Comment by astronouth7303** [comment]
I wouldn't be surprised if these fail though:
```
🐚 echo "foo" "|" "bar"
🐚 echo "|" | cat
```

**Comment by laloch** [comment]
@astronouth7303, those are ok, because for pipe operator parser sends the following down into the `run_subproc`:
```
$ echo "foo" "|" "bar"
foo | bar
# the commands were (['echo', 'foo', '|', 'bar'],)
$ echo "|" | cat
|
# the commands were (['echo', '|'], '|', ['cat'])
```
