### ISSUE TITLE
any possbility to support operation like "dir(os) | grep sys"

### ISSUE THREAD

**Issue by hick** [xonsh/xonsh#3420]
it's a suggestion,  it's a way of mixing the bash like shell and the python shell, after "import os", try to find something in module os by keyword "sys"

`dir(os) | grep sys`

**Comment by astronouth7303** [comment]
Seems unlikely, the parsing becomes too murky.

For $() and company, the data types become complicated--you'd need to return a complex time with funky state rules. Sounds like something that would lead to weird and flaky bugs.

**Comment by laloch** [comment]
Hi @hick, you can work the issue around by using [callable aliases](https://xon.sh/tutorial.html#callable-aliases):
```python
$ aliases["pydir"] = lambda: [print(l) for l in dir(os)]
$ pydir | grep sys
sys
sysconf
sysconf_names
system
```

**Comment by laloch** [comment]
More generic callable alias for `dir()`:
```python
$ aliases["pydir"] = lambda args: [print(l) for l in dir(globals()[args[0]])]
$ pydir os | grep sys
sys
sysconf
sysconf_names
system
```

**Comment by hick** [comment]
got it,   thx a lot

**Comment by dotsdl** [comment]
For reference, one could also do something like:
```xonsh
$ echo @("\n".join(dir(os))) | grep sys
sys
sysconf
sysconf_names
system
```
