### ISSUE TITLE
input() crashes xonsh

### ISSUE THREAD

**Issue by steveduell** [xonsh/xonsh#3423]
## Expected Behavior
When I use the input() method in xonsh, I expect the program not to crash,

## Current Behavior
This occurs in Windows 10 using conEmu. Whenever I use the input() method, I am prompted for user input, but after I enter that input, I get kicked out of xonsh and back to the terminal.

## Steps to Reproduce
Please note that I get kicked out each time after inputting anything:

```
C:\Users\sduell>xonsh
sduell@DAOWX001 ~ $ testVar = input('Please enter something, anything:')
Please enter something, anything:OK

C:\Users\sduell>xonsh
sduell@DAOWX001 ~ $ input()
Something

C:\Users\sduell>
```

Thanks for any help to get to the bottom of this!

**Comment by carmenbianca** [comment]
Does not occur on Fedora 31. I suspect it's Windows-only.

**Comment by scopatz** [comment]
hmm yeah this doesn't occur for me on Ubuntu.  @melund - can you take a look, please? Thanks!

**Comment by steveduell** [comment]
I updated xonsh and the problem disappeared.  No need to dig any deeper on
my account.  Thanks!

**Comment by scopatz** [comment]
Yay! Thanks!
