### ISSUE TITLE
@$() broken or unintuitive, not sure which.  Maybe both.

### ISSUE THREAD

**Issue by tshead2** [xonsh/xonsh#3425]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.13               |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.4                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.10               |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```

</details>

## Expected Behavior

I want to use the following to edit every Python file in the current tree:

```vi @$(find . -iname "*.py")```

... that is, vi should be run, with the results of the find command tokenized and passed as individual arguments to the vi command.

## Current Behavior

Instead, the above opens vi, ready to edit a single file named (for example) `"./foo.py^@./bar.py^@./baz.py^@"` ... as if the tokenization isn't happening at all.  However, if I run

```@$(find . -iname "*.py")```

I get

```xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: ./foo.py
./bar.py
./baz.py
```

... as if the tokenization *is* happening, and the first token in the list is taken as the command.

Although the latter behavior seems consistent with the documentation, it seems like the former would be much more useful, in a much wider set of circumstances, and would be consistent with the definition of `@()` more generally.

The most compact workaround I've found is to run

```vi @($(find . -iname "*.py").split())```

which seems overly wordy for a common use-case (and I'm living dangerously by leaving-out the `split()`).

### Traceback (if applicable)

<details>

```
traceback
```

</details>

**Comment by astronouth7303** [comment]
Hm, yup, can confirm.

`python -c "print(__import__('sys').argv)" @$(find)` produces a single argument.

`python -c "print(__import__('sys').argv)" @$(echo foo bar)` produces several arguments.

This does feel like a bug.

The work-around would be something like:

```
🐚 vi g`**/*.py`
```

**Comment by tshead2** [comment]
@astronouth7303: thanks for the confirmation and the suggestion, which strikes me as a better, more "Xonshonic" solution for this case.  It'd still be good to have @$() working more intuitively for the times when I want the equivalent of

    vi $(grep -l foo $(find . -iname "*.py"))

which at the moment, and incorporating your suggestion would be:

    vi @($(grep -l copyright g`**/*.py`).split())

Cheers,
Tim

**Comment by astronouth7303** [comment]
```
vi  @(p for p in pg`**/*.py` if b'foo' in p.read_bytes())
```

`pathlib` is quite strong, and p-strings and p-globs are super useful.

**Comment by tshead** [comment]
This is clear, if not concise.  I’ll start retraining my muscle memory.

Cheers,
Tim
