### ISSUE TITLE
xontrib autojump freezes xonsh shell

### ISSUE THREAD

**Issue by MikePanitz-CCC** [xonsh/xonsh#3429]
[xontrib autojump freezes xonsh shell](https://stackoverflow.com/questions/59973732/xontrib-autojump-freezes-xonsh-shell)

I'm using MiniConda with xonsh installed. Running print(sys.version) produces:

3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
I'm not sure which version of xonsh I'm using, but I installed it yesterday (Jan 29, 2020) and it's whatever the conda command got.

When I run xontrib list I get

apt_tabcomplete     not-installed  not-loaded
autojump            installed      not-loaded <======= NOTE!
autovox             installed      not-loaded
autoxsh             not-installed  not-loaded
avox                not-installed  not-loaded
bashisms            installed      not-loaded
base16_shell        not-installed  not-loaded
coreutils           installed      not-loaded
direnv              not-installed  not-loaded
distributed         installed      not-loaded
docker_tabcomplete  not-installed  not-loaded
free_cwd            installed      loaded
The key point being that autojump is installed, but it is not loaded.

When I run xontrib load -v autojump I get a single message, and then the shell freezes up (the cursor is still blinking, but the shell isn't doing anything). The message is:

loading xontrib 'autojump'
I'm taking care to use the Python stuff from the MiniConda install (not my other copies of Python that I've got).

Would anyone have any ideas about how to debug this? I'd love to find a way to get more information about what's going on and why it's freezing.

Thanks!

**Comment by gforsyth** [comment]
Hey @MikePanitz-CCC -- the autojump xontrib is a third-party contribution, I'm not sure what's going on with it.  
I think it will require also installing `autojump` separately -- is that installed?

**Comment by dotsdl** [comment]
@MikePanitz-CCC I believe [xontrib-z](https://xon.sh/xontribs.html#z), which I use now after using autojump for years in bash, is a pretty good replacement. It may be worth giving that a shot as well to see if it suits your needs.

**Comment by astronouth7303** [comment]
"Freezes on load" is potentially a xontrib author problem. But looking through https://github.com/sagartewari01/autojump-xonsh/blob/master/xontrib/autojump.xsh, nothing jumps out as should be blocking.

This is potentially a xonsh bug, if there's a proper triage.

@sagartewari01 do you have any insight?

**Comment by MikePanitz-CCC** [comment]
@gforsyth - I think that's it.  I didn't realize that I needed to install this separately; it's definitely not installed.

@dotsdl - Thanks for the tip!  I tried that and it installed and loads great.  Z is working great so far.

If there's anything I can do to help with this, or to help triage this, just let me know!
