### ISSUE TITLE
What is the preferred way of writing/executing os command with nested os commands?

### ISSUE THREAD

**Issue by htarnacki** [xonsh/xonsh#3433]
I have a question.
Generally i am curious what is the preffered way of writing following bash command in xonsh:

`docker run --rm -v "$(readlink -f "./restore here"):/restore here" db-files:7.5.2.0`

I was able to build only this one working form:
`docker run --rm -v @($(readlink -f "./restore here").strip() + ':/restore here') db-files:7.5.2.0`
but it seems to look worse then bash version

Is there a better way of writing this example?

**Comment by astronouth7303** [comment]
The above is acceptable. The other alternative is to dip into Python APIs.

The Python call is `os.readlink()`, so I could write that segment as:

```python
@(os.readlink("./restore here") + ':/restore here')
```

Or, for extra fun:

```python
@(f"{os.readlink('./restore here')}:/restore here")
```

**Comment by astronouth7303** [comment]
(For the record, the extra levels of indirection above mostly have to do with how xonsh approaches strings, which is a trade-off.)
