### ISSUE TITLE
Python completion using jedi

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#344]
See http://jedi.jedidjah.ch/en/latest/. It shouldn't be hard to get the basic thing working, since it's designed to be used as a library. 

Interestingly, Jedi's parser is designed to support partial parsing for the cases when you are writing code that isn't completely syntactically correct. As a result, it already seems to work on Xonsh code (at least emacs-jedi is giving me completions for my .xonshrc, which has dollar signs all over the place).  It doesn't complete on environment variables, though. I don't know if Jedi can be easily extended with the full xonsh grammar.

**Comment by scopatz** [comment]
Hi @asmeurer - given the failed attempt in #2127 and the merger of a replacement in #2153. I am going to close this. Feel free to reopen if you think it is needed. I think if someone really wanted jedi completions for some reason, the right place would be in a xontrib, perhaps in jedi itself.

**Comment by asmeurer** [comment]
Jedi is way smarter than just command line completion. If you are just using xonsh for shell stuff it probably is more than you need, but if you use it as a Python REPL, it's very nice. Basically, it lets you write any kind of expression, type `.` at the end, and have a decent hope of getting actual completions after the `.` (without literally evaluating the expression first).

**Comment by scopatz** [comment]
Yeah, my claim isn't that jedi isn't valuable and smart with respect to attr access. Rather that it didn't seem valuable enough for the additional completions in provided while at the command line. On my desktop at home it seemed like it was exceeding my personal 0.1 sec limit for completions. And it definitely didn't seem to work with functions defined in the shell session itself (which was one of the main things I was looking for).

I think we still could have jedi completion, if we wanted, but it should probably be in a xontrib. If people want it, they should have to enable it in my opinion, because it comes with a performance penalty. Such a xontrib is basically written in #2127, if anyone wants to take up the banner.

**Comment by asmeurer** [comment]
I just checked and `??` doesn't work on functions defined in the shell either. Assumedly the same sort of fix would be needed to solve either one.

**Comment by scopatz** [comment]
I am not sure that the semantics of `??` make sense in that case, just like they don't for C-extensions. Feel free to open up an issue for that as there is probably some history hack we can get away with there. 

I am not sure how we'd express that to jedi, but maybe there is a way with a custom file-like object that makes history look like a single file.

**Comment by astronouth7303** [comment]
Could we store the source on the function (or code) object and then use that if it's defined? And presumably extend Jedi to do the same.

**Comment by scopatz** [comment]
Wouldn't that involve monkey patching jedi and/or inspect? xonsh could do it for `??` because it has total control, but I am not sure that would work with jedi.

**Comment by scopatz** [comment]
I just reread through the jedi docs and there really doesn't seem like there is anything we could hook into easily. So I still think that jedi probably does't belong in xore, but does belong in a xontrib. Please feel free to reopen if you disagree. I'm happy to keep this conversation going.

**Comment by asmeurer** [comment]
For inspect.getsource you have to do some monkeypatching (there's some builtin support for a simple monkeypatch that the doctest module uses, so it's not bad). For jedi, maybe I'm missing something, but you just pass it the source. So you just prepend the command history as the source, it should work. You actually would want to pass it transpiled source anyway, as it can't recognize xonsh.

**Comment by scopatz** [comment]
Ok, I've put in #2166 - at least 90% because of the title.
