### ISSUE TITLE
How to run command with rc in command line?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3443]
Hi! Thank you for xonsh! Great work!
I'm trying to run command with rc:
```
$ echo "qwe=123" > xonshrc
$ xonsh -i --rc xonshrc -c "print(qwe)"
NameError: name 'qwe' is not defined
```
Why it is not working? I expected `123` as result.

**Comment by astronouth7303** [comment]
This smells like you want #3275?

**Comment by anki-code** [comment]
Hmm... yup! :) And like #3374 too :)
