### ISSUE TITLE
How to backup xonsh command history

### ISSUE THREAD

**Issue by FirstLoveLife** [xonsh/xonsh#3445]
For some reansons, I have to reinstall my manjaro. But I don't want to lose my xonsh command history, How to megerate my history datas?

**Comment by gforsyth** [comment]
Hey @FirstLoveLife -- assuming you are using the default `json` history backend (probably), the history files live in `$XDG_DATA_HOME/xonsh`.  You can grab all of those `json` files and copy them to the same location in your new install and `xonsh` will grab them from there.

**Comment by FirstLoveLife** [comment]
@gforsyth Thanks!
