### ISSUE TITLE
The online xonsh (via repl.it) is broken

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3448]
When I go to [https://xon.sh/](https://xon.sh/) the prompt under **Try it now!** shows me only a plain Python prompt, not a xonsh prompt.

Even `import xonsh` gives a `ModuleNotFoundError`. So it looks like repl.it's Python REPL does not install the packages from the `requirements.txt`.

**Comment by scopatz** [comment]
Yep, I have been working on a replacement for this

**Comment by halloleo** [comment]
Hey, that's cool. - However on the homepage https://xon.sh/ still the old broken repl.it appears.

**Comment by laloch** [comment]
I can run Xonsh just fine manually on the [repl.it](https://repl.it) web site.
