### ISSUE TITLE
Why ssh is not captured?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3455]
Hello! You are great team! Thank you all guys! You rock!

Let's start from `ls`:
```
$ r=!(ls)   # captured, great!
$
$ r=!(ls -9999)   # here is the error with -999 arg and it was captured, great!
$
```
But when I try ssh:
```
$ r=!(ssh host echo 123)   # I want to get 123 only in r.stdout
123
$ # Why I've got 123 above?
```
Finally:
```
$ r=!(ssh -v host echo 123)   # I want to get 123 only in r.stdout and the verbose log in r.stderr (-v arg)
OpenSSH ......................
debug1: .......................
debug1: .......................
debug1: .......................
123
$ r
CommandPipeline(stdin=None, stdout=None, stderr=None, pid=20161, returncode=None, .....
$ r.stdout is None
True
$ r.stderr is None
True
```
Why the ssh is not captured?

Thanks!

**Comment by astronouth7303** [comment]
Because xonsh and foreground and ahhhhhhhhhh.

I wanted to fix this with #2337 but got bogged down and demotivated.

**Comment by laloch** [comment]
Related to #3342.
I feel strongly that we should rewrite the subprocess handling once again going the "Keras" way this time. This is in my eyes No.1 blocker for v1.0 release.

**Comment by scopatz** [comment]
What is the keras way?

**Comment by laloch** [comment]
@scopatz, you were choosing the names :laughing: #3342:
> The Keras strategy attempts to kill the threads prior to suspending. This means turning off the teeing of stdin, stdout, and stderr. In principle, this is a safe operations because we will be stopping the subprocess and returning control back to the terminal, and then rendering a new prompt.

**Comment by scopatz** [comment]
Oh haha sorry, I totally forgot about that! It sucks that I had to take so much time away from xonsh. Glad that I can get back into it now, though!

**Comment by anki-code** [comment]
Closed because of related issues.

**Comment by anki-code** [comment]
Workaround:
```python
import subprocess
r = subprocess.check_output(['ssh', 'host', 'echo', '123'], stderr=subprocess.DEVNULL)
```

**Comment by anki-code** [comment]
Workaround:
```python
r = subprocess.check_output(['ssh', 'host', 'echo', '123'], stderr=subprocess.STDOUT)
# or
r = subprocess.check_output('ssh host echo 123', shell=True)
```

**Comment by anki-code** [comment]
See many workaround in #4214
