### ISSUE TITLE
Unexpected newlines in @$(...) substitution

### ISSUE THREAD

**Issue by KazWolfe** [xonsh/xonsh#3457]
Seems to be related to #2021, at least in part. 

Whenever I run `docker stop @$(docker ps -aq)`, I receive a Docker error (`404 page not found`), which appears to be caused by the fact that Docker is not receiving a valid container image.

Further experimentation shows this happens with basically everything that uses `@$` notation, which [appears to go against documentation](https://xon.sh/tutorial.html#command-substitution-with) as well as what was mentioned in #2021. 

Am I missing something here?

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior

Commands should be split properly and should execute normally, like Bash's own output:

```
$ ls $(ls)
1:

2:

3:

4:

5:
```

## Current Behavior

```
$ ls @$(ls)
ls: 1
2
3
4
5: No such file or directory
$ ls
1 2 3 4 5
```

`argv` view:

```
$ python -c "import sys; print(sys.argv)" @$(ls)
['-c', '1\n2\n3\n4\n5']
$ python -c "import sys; print(sys.argv)" @([i.strip() for i in $(ls).split()])
['-c', '1', '2', '3', '4', '5']
```

## Steps to Reproduce

1. Navigate to test directory - `cd @$(mktemp -d)`
2. Create test folders - `mkdir 1 2 3 4 5`
3. Run `ls @$(ls)`, observe failure

**Comment by KazWolfe** [comment]
The lexer does not appear to be splitting on `/n`:

```
 $ __xonsh__.execer.parser.lexer.split("hello\nworld how are\tyou")
['hello\nworld', 'how', 'are', 'you']
```

**Comment by laloch** [comment]
Hi @KazWolfe, thanks for reporting. I started work on #3156 some time ago. Perhaps I should get back to it...

**Comment by scopatz** [comment]
Oh weird.  I thought `@$(...)` only stripped the last newline.

**Comment by KazWolfe** [comment]
@scopatz Per the docs, it's supposed to be equivalent to `.split()`. As of now, it is only splitting the last newline. I'd think either the docs need to be updated to reflect this behavior _or_ `@$(...)` should be updated to split on all newlines.

If the former is implemented (doc update), I'd think there would still need to be some way of doing `docker stop $(docker ps -aq)` from bash. Perhaps `$$(...)`?

**Comment by scopatz** [comment]
I agree, it is a bug or a docs issue.  If @laloch (or anyone!) is willing to fix this, that'd be awesome!

**Comment by anki-code** [comment]
@laloch this issue was fixed and then reopened from another issue. I think it's misleading reopen. Please check. Should it be closed?

**Comment by laloch** [comment]
I don't understand. This issue is closed since 2020-04-08.
