### ISSUE TITLE
Any thoughts about wrong xontrib load

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3461]
Hello! Xore team is the best! Thank you for xonsh!
Could you please advise!

I'm running xonsh using AppImage something like that ([here is xonshrc.xsh](https://github.com/xonssh/xxh/blob/master/xonssh_xxh/xonshrc.xsh)):
```
./xonsh.AppImage --no-script-cache -i --rc xonshrc.xsh
```
And everything is great and `xpip` is working. But when I try to load xontribs I've faced with strange behavior.

When I try to load xontrib before install **and then** install **and then** load I've got fail:
```
./xonsh.AppImage --no-script-cache -i --rc xonshrc.xsh
$ xontrib load autojump
autojump  not-installed  not-loaded
$ xpip install xontrib-autojump
$ xontrib load autojump
The following xontribs are enabled but not installed ...
$ xontrib list autojump
autojump  not-installed  not-loaded
```

But when I install xontrib **and then** load a xontrib I get success:
```
./xonsh.AppImage --no-script-cache -i --rc xonshrc.xsh
$ xpip install xontrib-autojump
$ xontrib load autojump
$ xontrib list autojump
autojump  installed  loaded
```
I've tried to reload xontrib module before `xontrib load` with `import importlib; importlib.reload(sys.modules['xontrib'])` but no result.

Could you please advise what could be the cause? What should I check?

**Comment by scopatz** [comment]
Thanks for reporting @anki-code - it seems like this might be a bug with when & how we check if xontribs are installed.  It might be the case that xonsh only checks if it is installed the first time and caches the result, rather than dynamically checking each time

**Comment by astronouth7303** [comment]
`xontrib` is just wrappers around the import machinery. These two lines should have roughly the same effect:

```
xontrib load spam
```

```
from xontribs.spam import *
```

If one of these is work and the other one isn't, then we have a bug.

**Comment by anki-code** [comment]
> These two lines should have roughly the same effect
Yes it is.

Moreover if we replace `xontrib load autojump` to `importlib.util.find_spec('xontrib.autojump')` will see that if we call this function before package installation then after install we have None :(

**Comment by anki-code** [comment]
`XonshImportHook` couldn't affect here?

**Comment by astronouth7303** [comment]
OH CRAP THAT.

I forgot about #3171 for a second.

**Comment by astronouth7303** [comment]
The xsh importer only works with actual files on the filesystem, not other sources.

This is because the import machinery conflates "searching paths and other data sources" with "parsing and loading" and there isn't a solution to separate these concerns.

**Comment by anki-code** [comment]
After two liters of coffee and importlib debugging I found a solution that works :)
I always create empty `xontrib` directory in pip packages folder. And the magic here: importlib or xonsh hooks or little green man but xontrib loading works.

**Comment by anki-code** [comment]
As result I've got full xpip support in xonsh.AppImage in xonssh/xxh project.
