### ISSUE TITLE
fish-shell like abbr-expansion support

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3471]
## xonfig
I am currently moving from fish to xonsh as my main linux-shell. I miss the fish's feature of [abbr](https://fishshell.com/docs/current/cmds/abbr.html) command. It will be cool to have this on xonsh. It will be aliases that are more explicit.

**Comment by astronouth7303** [comment]
Think that's what sequence aliases do?

```
🐚 aliases['spam'] = ['echo', 'eggs']                                                                            
🐚 spam foo bar                                                                                                  
eggs foo bar
```

Unless I'm missing something.

**Comment by jnoortheen** [comment]
say I have an abbr for 
abbr spam="echo eggs"

when I type `spam`, in the prompt, it will expand to `echo eggs `. it is triggered with space or enter. Also it will not mess with any other binary names. just kind completion/expansion.

**Comment by astronouth7303** [comment]
ahh, abbreviations are expanded in the prompt, not at execution, ok.

**Comment by scopatz** [comment]
I would love to see a PR for this!

**Comment by laloch** [comment]
This is surprisingly hard to implement.
@jonathanslenders, do you have any idea about where to hook into prompt_toolkit in order to implement a dictionary-based replacement of the previous token in the buffer? Neither Completer nor Processor seems to the perfect fit for the task and I don't like the idea of binding <kbd>Space</kbd> key.

**Comment by scopatz** [comment]
@laloch - I think you have to bind it to something. And if people wanted this behavior, space seems like the right thing, I would think.

**Comment by jnoortheen** [comment]
@laloch - both space and enter(something that accepts) complete the abbreviation in fish. the same could be adopted.

**Comment by laloch** [comment]
Yes, I know how it shoud work from the user perspective. I was talking about implementation details.

**Comment by jonathanslenders** [comment]
In the prompt_toolkit examples directory I've once done this with the space too: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/autocorrection.py

**Comment by laloch** [comment]
@jonathanslenders, thank's for the answer. I have already figured that out. It just doesn't feel right(TM) to me to bind keyboard in order to process the buffer content.
