### ISSUE TITLE
What is the best way to build xonsh from master?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3472]
Hello! You are the best! Thank you!

I'm [trying to create continuous build](https://github.com/xxh/linuxdeploy-plugin-python) of `xonsh.AppImage` for two branches: current master and latest release. For latest release I use `pip install xonsh`. 

For current master I've tried to use `pip install git+https://github.com/xonsh/xonsh.git` but the result was very slow. It's because no amalgamation and something else I think. May be good to run amalgamater while building?

Could you please help me with shortest and easiest way to build and install xonsh from master with all optimizations?

Thanks!

**Comment by anki-code** [comment]
It looks like this works for me:
```
make amalgamate
pip wheel .
ls *.whl
```

**Comment by scopatz** [comment]
I think "python setup.py install" is the normal way we build on master
