### ISSUE TITLE
How to source xsh with arguments?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3475]
Hi! The xonsh is great! Thanks!

I'm working on environment seamless mode for [xxh project](https://github.com/xxh/xxh) and the case is how to source xsh with arguments.

In bash:
```
bash$ cat 1.sh
echo "$@"

bash$ source 1.sh -h -e -l -l -o
-h -e -l -l -o
```
In xonsh:
```
$ cat 2.xsh
import sys
echo @(sys.argv)

$ source 2.xsh -h -e -l -l -o
/home/xxh/miniconda3/bin/xonsh -l
```
Please advise how to solve this?

Xanks!

**Comment by anki-code** [comment]
Oh! I see `$ARGS` variable. Xanks! :)

**Comment by scopatz** [comment]
Glad you found it!
