### ISSUE TITLE
Slow prompt after empty command

### ISSUE THREAD

**Issue by useredsa** [xonsh/xonsh#3487]
Hello, I'm facing the same issue on an (almost clear) installation of xonsh. This is my `.xonshrc` file

```
# XONSH WEBCONFIG START
$PROMPT = '{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR} '
# XONSH WEBCONFIG END


# broot (https://github.com/Canop/broot) br function
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
def _br(args):
    $f = $(mktemp).strip()
    broot --outcmd "$f" @(args)
    if not $(cat "$f"):
        rm -f "$f"
        return -1
    @$(cat "$f")
    rm -f "$f"

def _nn(args):
    # Block nesting of nnn in subshells
    if 'NNNLVL' in ${...} and !(test $NNNLVL -ge 1):
        echo "nnn is already running"
        return

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    $NNN_TMPFILE = $XDG_CONFIG_HOME + '/nnn/.lastd'
    $NNN_COLORS  = '1234'
    $NNN_TRASH   = '1'

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn @(args)

    if !(test -f $NNN_TMPFILE):
        cat $NNN_TMPFILE
        comm = $(cat $NNN_TMPFILE).split()
        cd @(comm[1][1:-1])
        rm -f $NNN_TMPFILE > /dev/null

aliases['br'] = _br
aliases['nn'] = _nn
aliases['o'] = 'xdg-open'
aliases['myg++'] = 'g++ -O2 -Wall -std=c++14'
aliases['mylatex'] = 'pdflatex -halt-on-error -output-directory out'
aliases['quietlatex'] = 'texfot pdflatex -halt-on-error -output-directory out'

$EDITOR = 'kak-connect'


from prompt_toolkit.keys import Keys
@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.add

    @handler('c-f')
    def resume_process(event):
        fg

```

When I enter an empty line the prompt takes noticeable time to render (ms, but still I notice it's slower than bash). And as pointed out here, if I open `top` and maintain enter pressed it consumes 100% of my cpu and xonsh can't handle all of the empty lines, so it starts to miss some prompts. If I press it long enough (5 seconds?), I can make it show this message;

```
Unhandled exception in event loop:

Exception None

Press ENTER to continue...
```

It's not a problem with `$PROMPT` content, because changing it to `$ ` or `> ` didn't help.

xonfig:
```
+------------------+----------------------+
| xonsh            | 0.9.14               |
| Git SHA          | 777bdc73             |
| Commit Date      | Feb 23 13:28:31 2020 |
| Python           | 3.6.8                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

EDIT: Ok, further testing shows that setting `$PROMPT = '> '` made it consume not more than 60% when doing this. However, it still misses some lines, it's noticeable slow and I don't know what can happen if I have 3 more things open.

_Originally posted by @useredsa in https://github.com/xonsh/xonsh/issues/1105#issuecomment-601989480_

**Comment by gforsyth** [comment]
Thanks for reporting @useredsa -- we're going to be slower than bash in redrawing the prompt.  

The event loop exception you are hitting is coming from prompt_toolkit -- some of the delay is definitely from us (especially if you have something like `git_status` in the `$PROMPT` as we have to scrape a bunch of directories to figure out if you are in a repo or not), but I'm curious if you notice a performance difference if you start with `xonsh --shell-type readline`

**Comment by useredsa** [comment]
Hi @gforsyth, thank you too for the fast answer.

I understand that xonsh is going to be slower than bash. But, even if I set my prompt to `> `, I get to a 60% use of CPU (and I can't hit the exception). It's not that I'm going to press `enter` a lot, but it's very noticeable to the eye that the prompt is late to be drawn. In fact, even with this setting, the cursor moves to the beggining of the line before drawing the prompt sometimes, which is unfortunate.

If I use `xonsh --shell-type readline` then I see a different behaviour. It only goes up to a 45% of cpu usage but it misses a lot more prompts. That means, I see things like:
```
useredsa@Device002 ~ $
useredsa@Device002 ~ $

useredsa@Device002 ~ $
useredsa@Device002 ~ $
useredsa@Device002 ~ $

useredsa@Device002 ~ $
useredsa@Device002 ~ $

useredsa@Device002 ~ $
```

In this case, the percentage of cpu use doesn't change if I change the prompt to a simpler one (`> `), but I don't miss lines anymore. Still, I can see the cursor move to the beginning of the line.


May I ask, is this a generalized problem or does it happen only to me?
And may I also suggest something? Perhaps xonsh could store the previous prompt and write it, and only change it if the new value is different. It would take the same computation time but I wouldn't perceive the slowness after each command, just after those that change directory. I think many things could be done by caching results but this one should be particularly easy to implement (I guess?).

**Comment by gforsyth** [comment]
Hey @useredsa -- no, I see some missing lines, too, when I hold down return. 

We're open to improvements to the render time, but they aren't always as simple as they seem. 
We have an event system, so you could re-render the prompt only if the directory has changed (for instance) but this doesn't take in to account if we stay in the same directory but change a tracked file (so we need to update the prompt color, for instance). 

We could separate out the check for "is this a version controlled repo" from "repo state" and apply caching to the first only.

**Comment by useredsa** [comment]
@gforsyth
Can't we just draw the previous prompt and then draw on top if needed?

**Comment by gforsyth** [comment]
I believe most of the delay we currently see would take a similar amount of time as determining what was needed to redraw.  But I'm happy to look at any POCs!

**Comment by anki-code** [comment]
Hi @useredsa!
Could you please install xonsh from master and try again?
```bash
pip install -U git+https://github.com/xonsh/xonsh
```
If you still see the lags please run:
```bash
# bash
COMMANDS_CACHE_SIZE_WARNING=1 xonsh --timings
```
Post here the output please.

**Comment by useredsa** [comment]
> Hi @useredsa!
> Could you please install xonsh from master and try again? Install:
> 
> ```shell
> pip install -U git+https://github.com/xonsh/xonsh
> ```
> 
> If you still see the lags please run:
> 
> ```shell
> # bash
> COMMANDS_CACHE_SIZE_WARNING=1 xonsh --timings
> ```
> 
> and post here the output please.

I can confirm it's working smooth now, although I had stopped using `xonsh`. I may use it again now.

**Comment by anki-code** [comment]
Great! Please close this issue if it's solved.
