### ISSUE TITLE
xdg-open doesn't go to background by itself

### ISSUE THREAD

**Issue by jonaslb** [xonsh/xonsh#3496]
## Current Behavior
When using `xdg-open doc.pdf`, okular (my default pdf reader) opens as expected. Terminal is blocked until okular is closed. Unless ` &` is used explicitly, of course.

## Expected Behavior
In bash, `xdg-open doc.pdf` *automatically* goes to the background after starting, even without using `&` explicitly. This is the behaviour I'm used to and expected. xdg-open is not aliased or anything in bash.

## Workaround
So I have `aliases["o"]="xdg-open"` normally, and this can be replaced by a function that calls xdg-open with `&` such that it is sent to background as expected. 

I filed this issue anyway because I don't really know why bash and xonsh differ in how they treat xdg-open (as I believe in both cases it resolves directly to the shell script `/usr/bin/xdg-open`), so I thought it could be a bug. 

## xonfig

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | fedora               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by laloch** [comment]
Hi @jonaslb, `xdg-open` is a simple script, that behaves very much in dependence on the desktop environment you run. I use Plasma DE and, yes, I can reproduce the issue. Under both Xonsh and Bash the `xdg-open` invocation ultimately ends in a call to `kde-open5`. So it really is `kde-open5` that behaves differently depending on the shell it was started from. I can check its source code to see what the difference is, but I can't (and don't want to either) fix other DEs.

**Comment by laloch** [comment]
Turns out that `kde-open` decides according to identity of `stdin`, `stdout` descriptors. Try to add `__xonsh__.commands_cache.threadable_predictors['xdg-open'] = lambda args: False` to your `.xonshrc`.

**Comment by scopatz** [comment]
This is maybe one of the things that should by default be turned off.  PRs welcome!

**Comment by laloch** [comment]
Sure, PR incoming.
