### ISSUE TITLE
Add xonsh AppImage to release`s assets by new simplest way

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3501]
Hi! Thank you for xonsh! You're the best of the best!

The new way to build xonsh AppImage made by Valentin Niess is extremely simple :
```
git clone https://github.com/niess/python-appimage && cd python-appimage
python -m python_appimage build app applications/xonsh
./xonsh-x86_64.AppImage
```
To build with different versions of python add `-p` argument:
```
python -m python_appimage build app -p 3.6 applications/xonsh && mv xonsh-x86_64.AppImage xonsh-3.6-x86_64.AppImage
```

The xonsh AppImage was build on manylinux2010 along with [PEP 517](https://www.python.org/dev/peps/pep-0517/) and works on many linux distros. And the size was reduced to ~25MB.

Valentin made the example for xonsh appimage config in the `python-appimage` package: 
[applications/xonsh](https://github.com/niess/python-appimage/tree/master/applications/xonsh) . It will be right way if you copy this config and add it to the xonsh repo and building process. After this just change the path in the command:
```
python -m python_appimage build app path/to/your/xonsh-appimage-config
```

So it will be great if xonsh AppImage will appear in release`s assets.

Thanks!

**Comment by scopatz** [comment]
Hi @anki-code - That's cool!  

We use / wrote the [`rever`](https://regro.github.io/rever-docs/) tool to perform releases. If you want the appimage as a future release asset, I would recommend adding it to the rever.xsh file in the repo here.  Specifically, you should add an activity that generates AppImages and then modify the [`$GHRELEASE_ASSETS`](https://regro.github.io/rever-docs/activities.html#ghrelease) list to add the path to the appimage.

It would actually be great if you could put in a generic PR to rever itself for adding appimages.  I realize that might be too big of a request though.  If you just want to add it to xonsh, you can put in a PR here.  Thanks!

**Comment by anki-code** [comment]
Thank you for references. When you give a more detailed answers it really helps!

Here is the PRs:
* rever appimage - https://github.com/regro/rever/pull/215
* xonsh appimage - https://github.com/xonsh/xonsh/pull/3559
