### ISSUE TITLE
Python builtins shadowing some programs

### ISSUE THREAD

**Issue by sawolford** [xonsh/xonsh#3508]
## Python builtins shadowing some programs

Some shell commands share the same name with Python builtin functions (e.g., "id"). I often run "id" to see what user I am currently in my shell. It also gives me group information at a glance, including current primary group.

I honestly think this is a symptom of a larger problem in that there is no good way that I'm aware of to force subprocess interpretation of a command. Even if I alias "id" to something that will then be interpreted in subprocess mode (e.g., aliases["id"] = "id -a"), Xonsh still interprets the line in Python mode before it even substitutes the alias.

Although I think the default mechanism of determining the command type by heuristic is fairly robust in practice, there are some edge cases that it can't handle. There ought to be a way to force one interpretation or the other (Python or subprocess mode) in a repeatable fashion if that's the intent of the user.

Alternatively, I would like to know how to handle this specific case without requiring unnecessary command-line switches to be passed (e.g., "id -a") or strange machinations (e.g., "echo $(id)").

# xonfig

```
+------------------+----------------------+
| xonsh            | 0.9.15               |
| Git SHA          | feeb6315             |
| Commit Date      | Mar 19 10:50:33 2020 |
| Python           | 3.7.7                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

## Expected Behavior

Xonsh should run the program and not return the type of the Python builtin of the same name (REPL-like behavior).

```
$ id
uid=501(username) gid=20(staff) groups=20(staff),<...>
```

## Current Behavior

```
$ id
<function id>
```

## Steps to Reproduce

Run "id" command on Unix-like operating system with no arguments.

**Comment by laloch** [comment]
@sawolford, as you already discovered yourself, Python built-ins and anything that can be evaluated as a Python statement/expression in general take precedence over Xonsh shell mode. That's a feature. If you need to override the precedence, you can:
```
$ ![id]
$ @$(which id)
$ echo $(id)
$ echo @$(which id)
```

**Comment by gforsyth** [comment]
I'm closing this out as answered.

**Comment by elgow** [comment]
I don't consider this issue to be answered. In my first few days with xonsh I hit the exact problem that is the example above and it is making me reconsider using xonsh. 

For the above example I would say that interpreting "id" as referring to the python builtin function is wrong. If one types "id("  then the function is desired. If not followed by a "(" then it is not. I see no reason to use a python function name alone as the first or only element on a line in xonsh. For callables the open paren should be required to choose python mode over subprocess mode. 

Alternatively, an alias should take precedence over python builtins for the first token on a line.

**Comment by bestlem** [comment]
@anki-code Isn'y that only in macOS.  The uid and group names rather suggest that.

**Comment by anki-code** [comment]
In xonsh >= 0.23.0 use `$XONSH_BUILTINS_TO_CMD=True` to enable experimental feature: if plane name is python builtin and has executatble or alias use it as cmd (so simple `id`, `zip`, `import` are working).
