### ISSUE TITLE
Using sudo on the left of a pipe expression fails

### ISSUE THREAD

**Issue by kseistrup** [xonsh/xonsh#351]
When running the following command in a `xonsh` interactive shell, sudo's prompt is never displayed, and thus the command line never completes:

```sh
$ sudo netstat -anp | grep /python
```

It doesn't make any difference whether the `SHELL` inviroment variable is set to `xonsh` or a real shell like `bash`.

**Comment by scopatz** [comment]
I agree that this should not hang.  Interestingly, though, this is because the term on the right is ambiguous between Python and subproc modes.  This can be fixed by wrapping in $[]

```console
scopatz@athenaie ~ $ sudo netstat -anp | grep /python  # hangs
scopatz@athenaie ~ $ $[sudo netstat -anp | grep /python]  # works
scopatz@athenaie ~ $ sudo netstat -anp | grep python  # works
scopatz@athenaie ~ $ sudo netstat -anp | $[grep /python] # hangs
scopatz@athenaie ~ $ sudo netstat -anp | grep "/python"  # works
```

**Comment by scopatz** [comment]
Maybe we want to put a timeout on stdin?

**Comment by kseistrup** [comment]
Interesting, thanks.

**Comment by esafak** [comment]
Is this still a problem? I can't run the OP's example because netstat -p requires an argument (the protocol) on my system, but I can use sudo in pipes just fine: `sudo ls | grep /python`.

**Comment by scopatz** [comment]
Hmm this is still an issue for me.  You are on a mac though, right @esafak? I am on Ubuntu and even your ls example hangs

**Comment by esafak** [comment]
Yes, 10.10.5

**Comment by scopatz** [comment]
Good to know it works somewhere :)

**Comment by laerus** [comment]
this seems fixed on current master. both
`$ sudo netstat -anp | grep /python`
`$ sudo ls | grep /python`
work as expected.

closing this, feel free to reopen if this issue still exists!

**Comment by kseistrup** [comment]
Seems to work here, too. Thanks!
