### ISSUE TITLE
@$ subprocess operator regression after 0.9.17

### ISSUE THREAD

**Issue by KazWolfe** [xonsh/xonsh#3514]
## xonfig

<details>

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.9.17.dev2         |
| Git SHA          | 97a921c7            |
| Commit Date      | Apr 8 14:48:23 2020 |
| Python           | 3.7.6               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.9               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.4.2               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Expected Behavior

The `@$()` operator should behave as specified in #3156 and #3510, that is:

```
$ echo test @$(which cp)
test /bin/cp
```

See also #3457.

## Current Behavior

```
$ echo test @$(which cp)                                                    
$ which cp 
/bin/cp
$ @$(which cp)                                                              
IndexError: list index out of range
```

```
$ pwd                                                                       
/Users/kazwolfe
$ cd @$(mktemp -d)                                                          
/var/folders/2y/f0ky62v534bftznczzd9h2480000gp/T/tmp.ZoZJ0ypU
$ pwd                                                                       
/Users/kazwolfe
```

```
 $ mkdir 1 2 3 4 5                                                           
$ ls @$(ls)                                                                 
1 2 3 4 5
1 2 3 4 5
```

Additionally, subprocess mode seems to be invoked inaccurately:
```
$ thing = @$(echo hi)                                                       
xonsh: subprocess mode: command not found: thing
Did you mean one of the following?
    ping:   Command (/sbin/ping)
    nping:  Command (/usr/local/bin/nping)
```

## Steps to Reproduce

1. Create temporary folders `1  2 3 4 5` using `mkdir 1 2 3 4 5`.
2. Attempt to list all folders using `ls @$(ls)`
3. Expect: Bash-like output per #3457. Result: Double-print of `ls` output.

**Comment by laloch** [comment]
Hi @KazWolfe, works just fine for me (on Linux though):
```
$ echo test @$(which cp)
test /usr/bin/cp
$ cd @$(mktemp -d) and touch 1 2 3 4 5
$ ls -l @$(ls)
-rw-r--r-- 1 str users 0 Apr  9 18:25 1
-rw-r--r-- 1 str users 0 Apr  9 18:25 2
-rw-r--r-- 1 str users 0 Apr  9 18:25 3
-rw-r--r-- 1 str users 0 Apr  9 18:25 4
-rw-r--r-- 1 str users 0 Apr  9 18:25 5
```
What were your steps to install or upgrade Xonsh?

**Comment by KazWolfe** [comment]
Might definitely be user-error, heh. Upgrade was done using `xpip install -U xonsh` followed by a full terminal restart.

**Comment by KazWolfe** [comment]
Also interesting:

```
$ cat                                                                       
^Cgot except
```

Possible I got a dev/weird version from pip somehow?

**Comment by laloch** [comment]
I just did a clean install using Python docker image and the version is the same:
```
# xonfig
+------------------+---------------------+
| xonsh            | 0.9.17.dev2         |
| Git SHA          | 97a921c7            |
| Commit Date      | Apr 8 14:48:23 2020 |
```
@xonsh/xore, anyone able to test the release on MacOS?

**Comment by KazWolfe** [comment]
Interesting... testing Python 3.7 in a container  yields some interesting behavior on variable assignment:

```
<user>@bf370b0a74bf /tmp/tmp.jbCoE7Sfw7 # $TF = $(mktemp)
<user>@bf370b0a74bf /tmp/tmp.jbCoE7Sfw7 # $TF = @$(mktemp)
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: /tmp/tmp.CWKhPtp2qM

<user>@bf370b0a74bf /tmp/tmp.jbCoE7Sfw7 # TF = $(mktemp)
<user>@bf370b0a74bf /tmp/tmp.jbCoE7Sfw7 # TF = @$(mktemp)
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: TF
```

Not sure this  is related to my install problem though, I can always open another ticket if this is actually an issue and not just user error.

**Comment by laloch** [comment]
Those are two different issues. Since `@$(cmd)` substitution is supposed to be functionally equivalent to `@([i.strip() for i in $(cmd).split()])`, your `$TF = @$(mktemp)` is not really supposed to work. `ls @$(ls)` should, however, work as expected.

**Comment by KazWolfe** [comment]
I managed to work around this problem by disabling the `bashisms` xontrib.

**Comment by laloch** [comment]
OK, thanks for the update. I'll check what the problem with `bashisms` is.

Regarding the second issue, it's in fact quite easy to hack in. As a matter of fact, I already have it implemented here. I don't, however, know whether we want it, considering that you can get almost the same functionality from `$TF = $(mktemp).splitlines()`.

**Comment by KazWolfe** [comment]
Yeah, I'm using `$TF = $(mktemp).strip()` to get around this as that (basically) does what I want. 

Perhaps some way to make this a setting/optional?

**Comment by anki-code** [comment]
@KazWolfe does this thread still actual? If yes could you please update the xonsh to 0.9.22 and post the new snippets of gotted/expected results?

**Comment by KazWolfe** [comment]
Without Bashisms, everything seems to work normally. 

    $ echo test @$(which cp)                                                    
    test /bin/cp

```
$ mkdir 1 2 3 4 5                                                           
$ ls @$(ls)                                                                 
1:

2:

3:

4:

5:
```

Still broken once `bashisms` is loaded though:

```
$ xontrib load bashisms                                                     
$ ls @$(ls)                                                                 
1 2 3 4 5
1 2 3 4 5
```

**Comment by anki-code** [comment]
Thank you! Bashism xontrib by themselves is not a problem. There is THREAD_SUBPROC=False in the code that raises a problem:
```bash
$THREAD_SUBPROCS=True
ls @$(ls) 
#1:
#
#2:
#
#3:
#
#4:
#
#5:

$THREAD_SUBPROCS=False
ls @$(ls) 
#1  2  3  4  5
#1  2  3  4  5
```
