### ISSUE TITLE
Is it possible to have shift+arrows text selection?

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3515]
Modern terminal editors like [micro](https://github.com/zyedidia/micro#installation) support this feature. it would be really useful to have such feature atleast with ptk shell. I see some issues created in `ptk` reposiory like below  
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/979
 
can we have such feature by default? or through a xontrib

**Comment by scopatz** [comment]
Yep this would be great! Having them in the stock ptk implementation here would be awesome if someone wants to PR that in.

**Comment by melund** [comment]
I haven't mocked around with PTK keybindings, but the git commit for the feature in PTK seems to indicate that there may be an easy way to activate it:
```
All the related bindings are defined in a new
`load_emacs_shift_selection_bindings()` function, now called
in `key_binding.defaults.load_key_bindings`.
```
