### ISSUE TITLE
Unquoted absolute paths in exec

### ISSUE THREAD

**Issue by vitaut** [xonsh/xonsh#352]
As mentioned in https://github.com/scopatz/xonsh/issues/84#issuecomment-92981521, there is an issue with passing absolute paths to `exec` (`xexec`):

```
$ exec /bin/sh
Traceback (most recent call last):
  File "/home/viz/Programs/xonsh/lib/python3.4/site-packages/xonsh/shell.py", line 131, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/home/viz/Programs/xonsh/lib/python3.4/site-packages/xonsh/execer.py", line 124, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'builtin_function_or_method' and 'builtin_function_or_method'
```

**Comment by scopatz** [comment]
Hi @vitaut - thanks for reporting!  I am not sure what to do about this except to make exec a keyword in the language.  It is probably easiest to just put quotes around the abspath or $[] around the entire thing.

Although.... now that I think about it, it might be possible to detect that functions aren't divisible and then try subproc.... hmmm... Let me think about this.

**Comment by asmeurer** [comment]
Isn't the real problem that aliases don't override builtins?

**Comment by astronouth7303** [comment]
Should this be rolled into #1361?

**Comment by scopatz** [comment]
Let's not muddle up #1361 anymore than it is :).  But this actually is an ambiquous form between pymode and subproc mode and so the user does need to do something to make it not Pythonic.  Maybe `exec /./bin/sh` is enough.

**Comment by astronouth7303** [comment]
Ah, the greatest problem of xonsh: How to read the user's mind.

**Comment by scopatz** [comment]
> Ah, the greatest problem of xonsh: How to read the user's mind.

So true :)

Also, it should be noted that putting quotes around the command name is valid (and recomeneded) in most other shells. So adding the quotes doesn't affect interop at all.

**Comment by PaulReiber** [comment]
Anthony,

I'd like to make a proposal.

In python, you don't get far starting a line with \

>>> \x
  File "<stdin>", line 1
    \x
     ^
SyntaxError: unexpected character after line continuation character

However in bash, it's just fine to do that:

$ \ls
a.py
b.py
$

\-quoting lets you run commands that start with a space character, for
example.  But it's a "no-op" to the left of most regular characters.

My proposal is that xonsh could recognize "\<anything>" - a backslash
that's NOT at the EOL - as indicating that a command is bash code, not
python code.

...What do you think?

Kind regards,
Paul

On Wed, Jul 27, 2016 at 5:34 PM, Anthony Scopatz <notifications@github.com>
wrote:
>
> Ah, the greatest problem of xonsh: How to read the user's mind.
>
> So true :)
>
> Also, it should be noted that putting quotes around the command name is
valid (and recomeneded) in most other shells. So adding the quotes doesn't
affect interop at all.

**Comment by scopatz** [comment]
> Anthony,

Please refer to the core-devs collectively :) Thanks!

Thanks for your proposal.  We have historically shied away from adding backslash escapes in subproc mode, in favor of the more powerful quoting.  At least some of us core-devs feel that adding backslashes is a slippery slope.

> My proposal is that xonsh could recognize "\<anything>" - a backslash that's NOT at the EOL - as indicating that a command is bash code, not python code.

I personally definitely want to avoid behaviour like this. This is certainly makes it harder to teach, debug, learn...

**Comment by asmeurer** [comment]
@PaulReiber you can use `$[` at the beginning of the line in the way that you are suggesting to use `\` (with the caveat of course that you have to remember to end the line with `]`).

**Comment by scopatz** [comment]
Also, if you wanted a command that started with a space you do `$ " xyz" arg0`

**Comment by laerus** [comment]
Closing since this `exec /bin/sh` now works on latest master
