### ISSUE TITLE
can not use export to setup proxy

### ISSUE THREAD

**Issue by pyctp** [xonsh/xonsh#3520]
xonsh.__amalgam__.XonshError: xonsh: subprocess mode: command not found: export
Did you mean one of the following?
    expr:    Command (/usr/bin/expr)
    import:  Command (/usr/bin/import)
    expiry:  Command (/usr/bin/expiry)

how to solve this problem?
thanks.

**Comment by gforsyth** [comment]
Hi @pyctp -- I'm assuming you are trying to set an environment variable like `HTTPS_PROXY`?

You can define / assign env vars as follows (you can put these in your `xonshrc` or even write a xonsh function that sets these when called):

```
$HTTP_PROXY="http://localhost:3128"
```

**Comment by astronouth7303** [comment]
https://xon.sh/bash_to_xsh.html
