### ISSUE TITLE
main._failback() doesn't honor $SHELL

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#3523]
Failback doesn't use environment variable $SHELL to find failback shell, immediately tries the system wide options in `/etc/shells`, which are not ordered by preference.  I'd argue that $SHELL should be the first shell to try, since it's the user's preferred login shell.

This caused me some consternation because my login shell is `bash`, but Xonsh failed back to `dash` from `/etc/shells`.  I have never configured this and it happened to have some rc configuration error that caused an infinite loop of 'bad substitution:/bin/sh' messages, so I could never see the original Xonsh exception.

I have a PR for a proposed fix, coming right up.

**Comment by scopatz** [comment]
On my system, `$SHELL` is xonsh, because I have set it as my login shell.  So using `$SHELL` as the fallback would be dangerous. Maybe the fallback could be smart and avoid using $SHELL` if it the same path as the sessionwe are executing in. 

Thanks for pointing this out @bobhy!

**Comment by bobhy** [comment]
Yes, I did this.  It doesn't use $SHELL if it is same path as main() argv[0].

**Comment by scopatz** [comment]
Great!
