### ISSUE TITLE
Line continuation in implicit subproc mode

### ISSUE THREAD

**Issue by Cheaterman** [xonsh/xonsh#3532]
This is a follow-up to #2194 .

It seems like this is no longer working. Also, the examples provided by @scopatz near the end seem to yield a different result nowadays.

As previously stated there:
```
xonsh/0.9.17.dev2 here, and this is broken again.

Also @scopatz the examples you showed above now work a bit differently - to get line continuation,
I was forced to use both explicit subproc mode ![] AND to end each line with \ (space + backslash).
Maybe the backslash wasn't necessary but EOL whitespace is a nono in my book :-)
```

Thanks in advance!

**Comment by laloch** [comment]
Hi @Cheaterman, could you please provide more details? I don't seem to be able to reproduce the issue:
```
$ echo hello \
. world
.
hello world
```

**Comment by anki-code** [comment]
I also can't reproduce this on xonsh 0.9.26.

**Comment by Cheaterman** [comment]
I somehow don't even remember this issue - but I _do_ vaguely remember this being fixed shortly after by an upgrade here. Good close! :-)
