### ISSUE TITLE
/usr/bin/cut: the delimiter must be a single character with cut -d';'

### ISSUE THREAD

**Issue by sucrecacao** [xonsh/xonsh#3539]
try to run 
```
cat ~/.zsh_history  | cut -d';' -f2-
```
and got the error:
`/usr/bin/cut: the delimiter must be a single character`

## xonfig

<details>

```
$ xonfig
```

</details>

## Expected Behavior
Should show the trimmed command from my zsh history, like if I run it in zsh or bash
## Current Behavior
show the above error

## reproduce 
enter
```
cat ~/.zsh_history  | cut -d';' -f2-
``` 
in a xonsh terminal

**Comment by sucrecacao** [comment]
I found out the solution while writing the issue. 
zsh/bash allow `-d';'` without space and xonsh need a space. I was used to skip the space.

**Comment by sucrecacao** [comment]
`cut --delimiter=';'` won't work neither, I guess I understand why, but it's still a little bit disappointing ( first time using xonsh )

**Comment by anki-code** [comment]
You expect that `';'` works the same way as in bash/zsh but no. The working example:
```bash
cat ~/.zsh_history  | cut -d@(';') -f2-
cat ~/.zsh_history  | cut --delimiter=@(';') -f2-
```
To understand the difference you can use `$XONSH_TRACE_SUBPROC=True`:
```bash
> $XONSH_TRACE_SUBPROC=True

> cat ~/.zsh_history  | cut --delimiter=';' -f1 o> /dev/null e> /dev/null  
TRACE SUBPROC: (['cat', '/home/user/.zsh_history'], '|', ['cut', "--delimiter=';'", '-f1', '>', '/dev/null'])

> cat ~/.zsh_history  | cut --delimiter=@(';') -f1 > /dev/null
TRACE SUBPROC: (['cat', '/home/user/.zsh_history'], '|', ['cut', '--delimiter=;', '-f1', '>', '/dev/null'])
```

**Comment by anki-code** [comment]
@scopatz @gforsyth Meanwhile I can't find the explanation of this difference in the documentation.

Why xonsh can't do the same as bash? 

The xonsh works like bash in this examples:
```
xonsh$ $XONSH_TRACE_SUBPROC=True
xonsh$ echo 'qwe'                                                                                                                                                                                                                           
TRACE SUBPROC: (['echo', 'qwe'],)
```
```
bash$ set -x
bash$ echo 'qwe'
+ echo qwe
```

But:
```
$ echo arg='qwe'                                                                                                                                                                                                                       
TRACE SUBPROC: (['echo', "arg='qwe'"],)
```
```
bash$ echo arg='qwe'
+ echo arg=qwe
```

**Comment by anki-code** [comment]
The answer is above and the issue could be closed.

**Comment by laloch** [comment]
The following should work as well:
```
$ cat ~/.zsh_history | cut "-d;" -f2
```
