### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character on Windows 10

### ISSUE THREAD

**Issue by mardukbp** [xonsh/xonsh#3542]
In a brand-new installation of xonsh on Windows 10 following the official installation instructions.

## Expected Behavior

Writing Unicode characters to `.xonshrc` using `xonfig web` should not produce an error.

## Current Behavior

`UnicodeEncodeError: 'charmap' codec can't encode character` is thrown in the console by `xonsh/webconfig/main.py` line 75. 

## Steps to Reproduce

1. Run xonsh

2. $ xonfig web

3. Choose a prompt containing Unicode characters

4. Click Save

## Solution

As [discussed in StackOverflow](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters) on Windows UTF-8 encoding has to be specified when opening a file in order to write Unicode characters.

The above problem is solved by replacing line 74 in `xonsh/webconfig/main.py`  with

```py
with open(fname, "w", encoding="utf-8") as f:
```

**Comment by melund** [comment]
Thanks @mardukbp That is a classic mistake in cross platform Python. A PR would be very welcome :)

**Comment by gforsyth** [comment]
Closed via #3543
