### ISSUE TITLE
Documentation - Mention the cross-platform terminal emulator Alacritty

### ISSUE THREAD

**Issue by mardukbp** [xonsh/xonsh#3545]
[Alacritty](https://github.com/alacritty/alacritty) is a GPU-accelerated terminal emulator written in Rust that runs on macOS, Linux, BSD, and Windows. I believe that it is a great companion to xonsh, because combined they allow one to have the same CLI environment across operating systems.

Of course it would be great to distribute both as a single executable. And this should be possible using another Rust program: [PyOxidizer](https://github.com/indygreg/PyOxidizer). I already started working on that. I will let you know when I have a prototype.

**Comment by astronouth7303** [comment]
We only mention a couple of terminal emulators in the docs ("Alternatively, you can setup your terminal emulator (xterm, gnome-terminal, etc) ...") and we have been extremely unopinionated about what terminal emulator you should use.

I don't believe anyone in xore would be interested in working on xonsh as a total CLI environment distributable. We, of course, encourage a broad and diverse ecosystem. (I thought there used to be a page/section "projects that use xonsh" that would be good for mentioning it, but I'm not finding it now.)

**Comment by laloch** [comment]
> I thought there used to be a page/section "projects that use xonsh" that would be good for mentioning it, but I'm not finding it now.

[Projects that use xonsh](https://github.com/xonsh/xonsh#projects-that-use-xonsh)

**Comment by mardukbp** [comment]
Thanks! I hope to add an entry to that page some time.
