### ISSUE TITLE
`vim $(echo foo +5)` open a file called "foo +5" instead of open foo with +5 as an argument

### ISSUE THREAD

**Issue by sucrecacao** [xonsh/xonsh#3547]
## xonfig
+------------------+---------------------+
| xonsh            | 0.9.17.dev2         |
| Git SHA          | 97a921c7            |
| Commit Date      | Apr 8 14:48:23 2020 |
| Python           | 3.7.3               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.5               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.3.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | ubuntu              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+

## Expected Behavior
`vim $(echo foo +5)`  
should open file foo at line 5

## Current Behavior

vim open a file called `foo +5` 
</details>

## Steps to Reproduce
in a xonsh terminal
`vim $( echo foo +5)`

**Comment by astronouth7303** [comment]
This is by design.

You want `@$(echo foo +5)`

See https://xon.sh/tutorial.html#command-substitution-with
