### ISSUE TITLE
`echo @$(ls | fzf)`  doesn't show fzf menu

### ISSUE THREAD

**Issue by sucrecacao** [xonsh/xonsh#3548]
## xonfig

<details>

```
$ xonfig
```

</details>

## Expected Behavior
`echo @$(ls | fzf)` should prompt the fzf menu to select a file in the dir. 
it work with dmenu and rofi but block with fzf and fzy.
`echo $(ls | fzf)` works fine

## Current Behavior
the shell create a new line with a blinking cursor. We need to ctrl+c to exit.
get `"RecursionError: maximum recursion depth exceeded while calling a Python object"` when exiting with Ctrl+c

## Steps to Reproduce

install fzf or fzy
`echo @$(ls | fzf)`

**Comment by scopatz** [comment]
Do you have an example that doesn't use fzf?

**Comment by sucrecacao** [comment]
> Do you have an example that doesn't use fzf?

no, only `fzy`

**Comment by scopatz** [comment]
hmmm neither of these work for me

**Comment by scopatz** [comment]
hmmm neither of these seem to work, but `echo @($(ls | fzf).strip())` seems to
