### ISSUE TITLE
xonsh in docker, endless error: BlockingIOError: [Error 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3554]
![Screenshot_20200429_233500](https://user-images.githubusercontent.com/1708680/80644527-7316cb80-8a72-11ea-8fcc-8ed83281cf85.png)

**Comment by astronouth7303** [comment]
That's wild.

What containers are you using and what are you doing with them?

**Comment by anki-code** [comment]
It looks like xonsh behavior extremely uncontrolled depends on terminal environment.

You can run xonsh in docker on local mac/linux/windows and it will be worked like a charm.

But when you run xonsh on some server using something like web console for it OR you run xonsh in the docker without appropriate locale settings or environment OR you run xonsh from AppImage THEN you will get the uncontrolled crazy wondering glitches in xonsh while it interacting with terminal, console or other environment, don't know. And no one can help to understand why, and no one can help to fix.

In this example I just run xonsh in ubuntu 18 docker container using portainer terminal.

**Comment by anki-code** [comment]
I've again caught this issue in PyCharm terminal in docker. I run PyCharm terminal then docker then I run xonsh and after command I've got this issue.

**Comment by anki-code** [comment]
I'm going to close this issue because the details in #3555

**Comment by anki-code** [comment]
Don't know how to repeat.
