### ISSUE TITLE
xonsh stops and freezes or crash with unexpected errors when run from not interactive bash

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3555]
Hello @xonsh/xore! I've found the way to reproduce #3525 #3553 and my lovely #3554.

In short beginning with [commit with the ghost emoji in the comment](https://github.com/xonsh/xonsh/issues/3525#issuecomment-617307862) xonsh shows crazy behaviour when it run from not interactive bash.

```
xonsh$ bash
bash$ echo "xonsh --no-rc" > spooky.sh && chmod +x spooky.sh
bash$ bash -i spooky.sh
xonsh$ 
xonsh$ echo It works!
It works!
```
But if we run without interactive:
```
bash$ bash spooky.sh
```
After this you can get stop message immediately:
```
[1]+  Stopped ./spooky.sh
```
Or you can see xonsh prompt. Don't worry! After the first subprocess command it will be crashed:
```
xonsh$
xonsh$ echo spooky!
spooky!
[2]+  Stopped                 ./spooky.sh
```
And every time you will be do it the zombie will appear in the processes:
```
$ ps -ax | grep xonsh
 259847 pts/3    S      0:02 xonsh --no-rc        # zombie with endless errors
```

Very cute ghost! :) What do you think @scopatz @gforsyth  @melund @astronouth7303 @laloch ? :)

**Comment by gforsyth** [comment]
Hey @anki-code -- nice job tracking that down!  I am not sure what's going on there, but all of job control is... hard.  

Can you post your `xonfig` and also the output of `bash --version`?  I can't reproduce this in Arch, running bash 5.0.16.

Also, can you test and see what happens if you try to force xonsh to run interactively?

```
bash$ echo "xonsh -i --no-rc" > spooky.sh && chmod +x spooky.sh
```

and see if that makes any difference?

**Comment by gforsyth** [comment]
Oh wait, nevermind!  I can reproduce.  I forgot to run a command in `bash` after starting it non-interactively.

I can confirm that adding the `-i` call to the `xonsh` invocation seems to stop the problem.  Which is weird, but another thread to pull on.

**Comment by anki-code** [comment]
> I can confirm that adding the -i call to the xonsh invocation seems to stop the problem

Don't clearly understand what you mean. For double check:

```
bash$ echo "xonsh -i --no-rc" > spooky.sh && chmod +x spooky.sh
bash$ ./spooky.sh
# Stopped or will be stopped after first subprocess command in xonsh
```
```
bash$ echo "xonsh --no-rc" > spooky.sh && chmod +x spooky.sh
bash$ ./spooky.sh
# Stopped or will be stopped after first subprocess command in xonsh
```
Only `bash -i soopy.sh` works for me.

**Comment by gforsyth** [comment]
Hey @anki-code -- ok, I can reproduce more reliably now.  I run `xonsh` as my default shell, so some env-vars are sticking around if I first launch `bash` and then run `spooky.sh`

If I use `env` to wipe out my environment, then I see the weirdness you see

```
(base) gil@badcatredux ~/tmp $ env -i HOME=/home/gil USER=gil XONSH_DEBUG=1 bash              
[gil@badcatredux tmp]$ cat spooky.sh 
xonsh -i --no-rc
[gil@badcatredux tmp]$ ./spooky.sh 

                           Welcome to the xonsh shell (0.9.17.dev3)                           

                                 ~ Break out of your shell ~                                  

----------------------------------------------------------------------------------------------
xonfig tutorial    ->    Launch the tutorial in the browser
xonfig web         ->    Run the configuration tool in the browser and claim your shell 
(Note: Run the configurationn tool or create a ~/.xonshrc file to suppress the welcome screen)

gil@badcatredux ~/tmp $ echo hi                                                               
hi

[1]+  Stopped                 ./spooky.sh
[gil@badcatredux tmp]$ exit
There are stopped jobs.
[gil@badcatredux tmp]   4Rgil@badcatredux ~/tmp $                                             
[gil@badcatredux tmp]$ fg 1
./spooky.sh

gil@badcatredux ~/tmp $                                                                       

Unhandled exception in event loop:

Exception None
Press ENTER to continue...                                                                    
gil@badcatredux ~/tmp $ echo hi                                                               
hi

[1]+  Stopped                 ./spooky.sh
```

That's definitely a weird one.

**Comment by anki-code** [comment]
@scopatz It looks like the issue is actual and the commit shouldn't close this :)

![Screenshot_20200827_214913](https://user-images.githubusercontent.com/1708680/91482706-28d21980-e8af-11ea-9b36-77428fbf4d69.png)

**Comment by anki-code** [comment]
I can't repeat this on xonsh 0.11
