### ISSUE TITLE
Can't use ulimit -n

### ISSUE THREAD

**Issue by RemiTorracinta** [xonsh/xonsh#3569]
Currently, I'm unable set my open file limit when a xonsh shell. I'm on MacOS 10.15.4 .

`ulimit -n` works fine on other shells, such as zsh, but as you can see in the example below nothing seems to happen for me with xonsh.

```
 ~  $ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 5568
virtual memory          (kbytes, -v) unlimited
 ~  $ ulimit -n 1000
 ~  $ _.rtn
0
 ~  $ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 5568
virtual memory          (kbytes, -v) unlimited
 ~  $
```

I don't know much about ulimit but it's my understanding that it should set resource limits for the current shell process and its children. So maybe something about the xonsh implementation of subprocess mode doesn't make this work.

**Comment by laloch** [comment]
Hi @RemiTorracinta, unfortunately, Xonsh does not support the `ulimit` command (I'll consider implementing it). However, since Xonsh, essentially, is Python, you can use the Pythonic way of setting your limits:
```python
$ import resource
$ nofile = resource.getrlimit(resource.RLIMIT_NOFILE)
$ resource.setrlimit(resource.RLIMIT_NOFILE, (1000, nofile[1]))
```

**Comment by RemiTorracinta** [comment]
Oh! I didn't realize ulimit is a shell built-in. The pythonic approach is working fine, thank you!
