### ISSUE TITLE
alias with -- causes AttributeError

### ISSUE THREAD

**Issue by cjrh** [xonsh/xonsh#3570]
## xonfig

+------------------+-------------------------------------------------------+
| xonsh            | 0.9.18                                                |
| Git SHA          | 49cd2812                                              |
| Commit Date      | Jan 31 06:16:59 2020                                  |
| Python           | 3.8.1                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 3.0.5                                                 |
| shell type       | prompt_toolkit                                        |
| pygments         | 2.6.1                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x000001B936DD3370> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x000001B936DD33D0> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+

## Expected Behavior

It should be possible to set an alias to `ls -lah --color` without error.

## Current Behavior

Setting an alias seems to fail if it has a `--` parameter.  This is happening on current master 3a6e9de2 (despite what the xonfig below says).

In the snippet below, an alias string of `ls -lah` is fine, but `ls -lah --color` raises.

```
$ aliases['ll'] = 'ls -lah'
~
$ aliases['ll'] = 'ls -lah --color'
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "f:\documents\repos\xonsh\xonsh\base_shell.py", line 362, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "f:\documents\repos\xonsh\xonsh\codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "f:\documents\repos\xonsh\xonsh\aliases.py", line 131, in __setitem__
    elif isexpression(val):
  File "f:\documents\repos\xonsh\xonsh\ast.py", line 315, in isexpression
    node = builtins.__xonsh__.execer.parse(node, ctx, *args, **kwargs)
  File "f:\documents\repos\xonsh\xonsh\execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "f:\documents\repos\xonsh\xonsh\execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "f:\documents\repos\xonsh\xonsh\parsers\base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "f:\documents\repos\xonsh\xonsh\ply\ply\yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "f:\documents\repos\xonsh\xonsh\ply\ply\yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "f:\documents\repos\xonsh\xonsh\parsers\base.py", line 2161, in p_factor_unary
    op = self._factor_ops[p1.value]()
AttributeError: 'str' object has no attribute 'value'
```

**Comment by cjrh** [comment]
This does not occur on tag 0.9.18.

**Comment by cjrh** [comment]
Ok, can confirm this was introduced in the latest commit 3a6e9de2

**Comment by laloch** [comment]
Hi @cjrh, thanks for reporting.
Each time we change our grammar in some way, it is necessary to run `python setup.py install` in order to reflect the change in the parser tables. My best guess would be, that you forgot to do so.

**Comment by cjrh** [comment]
I didn't even know it was necessary 🙃

Sorry for the noise.
