### ISSUE TITLE
How to use env variables in f-strings?

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3572]
The line

    key='HOME'; print(f"{key} = {${key}")

gives me the error `ValueError: unexpected '{' in field name` which sort of makes sense, but renders f-strings for environment variables useless.

In f-strings, is there a way to access the environment array through a less ambiguous name maybe?

This issue might be related to #2822 and #2870.

### xonfig

The problem occurs in multiple xonsh versions:

1)

```
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.4                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.3                |
| shell type       | dumb                 |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

2)

```
+------------------+---------------------+
| xonsh            | 0.9.18              |
| Git SHA          | 26475146            |
| Commit Date      | May 5 06:42:28 2020 |
| Python           | 3.7.7               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | None                |
| shell type       | dumb                |
| pygments         | None                |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by anki-code** [comment]
f-strings works strange in xonsh (#3454) as workaround I recommend avoid using f-strings.

**Comment by gforsyth** [comment]
Hey @halloleo -- out env-lookup syntax of `${}` predated f-strings and there are some weird cases where things don't really work as planned (this is one of them).  
It's more verbose but you can always do a lookup in the `env` dict directly:

```
f"{key} = {__xonsh__.env.get(key)}"
```

**Comment by laloch** [comment]
Hi @halloleo, welcome back.
I can confirm, that `${}` operator does not work in f-strings.
For now, you can use this workaround:
```
key='HOME'; print(f"{key} = {__xonsh__.env[key]}")
```

**Comment by scopatz** [comment]
I thought that this worked:

```
$ f"{$HOME}"                                             
'/home/scopatz'
```

**Comment by halloleo** [comment]
Yes,  using a the key name _directly_ in the f-string works. But what when the key name is given in a variable `key='HOME'`?

    key='HOME'; print(f"{${key}")

does - understandably but unfortunately - not work, so for the moment I use @gforsyth's `__xonsh__` pattern.

**Comment by scopatz** [comment]
Yeah, that is not great.  Thanks for pointing this out!

**Comment by halloleo** [comment]
Cool! I can confirm that 

    key='HOME'; print(f"{${key}}")

works in the current github version of xonsh. :smile:
