### ISSUE TITLE
Little question: How to return from a xonsh script prematurely

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3573]
Say I have a xsh script but under one condition I want to exit the script early. E.g.:

```
# myscript.xsh

if $DONOTHING == 1:
   exit
# more code
# more code
# more code
```

`exit` on its own does not work. `return` doesn't ether. Do I have to import `sys` and write `sys.exit()` or is there a shorter way to do this?

***

BTW, thanks to everybody for xonsh! It's still my favourite shell (despite dabbling very briefly into [elvish](https://elv.sh/)).

**Comment by anki-code** [comment]
Try `raise SystemExit` to avoid importing.

**Comment by laloch** [comment]
This is a duplicate of #3241.

**Comment by halloleo** [comment]
`raise SystemExit` is cool! Thanks! :-)
