### ISSUE TITLE
How to run xonsh in Midnight Commander?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3583]
Hello! xonsh is xool!

When I run Midnight Commander from xonsh and want to use the shell by pressing Ctrl+O I've got bash (if the default user shell is bash) or I've got nothing (if the default user shell is xonsh).

Is there a way to use xonsh in Midnight Commander?

Thanks!

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laloch** [comment]
Unfortunately, that's not possible right now. Midnight Commander only supports whitelisted shells. See https://github.com/MidnightCommander/mc/blob/45bb66704b008025516135153964c79ac36a396f/lib/shell.c.

**Comment by laloch** [comment]
It should be fairly easy to add. See [this patch](https://midnight-commander.org/attachment/ticket/3748/mc-mksh-subshell-v2.patch), that adds support for mksh.

**Comment by anki-code** [comment]
I reviewed the MC code and I see that:
* MC expects strong path (`/usr/bin`) for shell. Because xonsh could be installed in any plase where python installed there is complex task to add xonsh as MC compatible shell. 
* I tried to patch MC and put them the path to bash script that calls xonsh, but it looks like MC expects another binary interface.
Closed until new info or new heroes on this way.
