### ISSUE TITLE
job control: ctrl-z in foreground process does not return to shell if xonsh is not direct parent

### ISSUE THREAD

**Issue by valer-cara** [xonsh/xonsh#3584]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.14          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

```

</details>

## Expected Behavior

On `ctrl-z`, control should return to shell.

## Current Behavior

When ctrl-z is pressed in a process that's not a direct child of xons, control does not return to shell. Only way to escape from here is `pkill -CONT vim` from another shell.

## Steps to Reproduce

Can be reproduced with any curses like program if ran from a child of xonsh. Examples:

- `bash -c "vim"`
- `bash -c "mc"`
- `sops ./my-test-file` (https://github.com/mozilla/sops)

Any of the above, then `Ctrl-Z` hangs the shell

**Comment by laloch** [comment]
Hi @valer-cara, thanks for reporting!
This is a known issue. Basically any subprocess that is "unthreadable" in Xonsh suffers from this issue.

**Comment by laloch** [comment]
No, wait! It works just fine in v0.9.18.

**Comment by laloch** [comment]
OK, it's the other way out. I can run `mc` directly from Xonsh and the job control works as expected. If I run `bash -c "mc"` the mc subprocess hangs in the stopped state exactly as you describe. This is because Xonsh cannot detect the "unthreadability" in such a case.
You can work the issue around by setting `$THREAD_SUBPROCS=False` temporarily. For instance:
```
$ with ${...}.swap(THREAD_SUBPROCS=False):
... bash -c "mc"
```
Sorry for the confusion.

**Comment by CharString** [comment]
On v0.9.19
```sh
$ sleep 600
```
doesn't respond to ctrl-z. And when the sleep process receives a SIGTSTP, the shell hangs until sleep receives SIGCONT (or SIGKILL of you like core dumps).

**Comment by laloch** [comment]
@CharString, yes, we are aware of the issue. It will change in the future, but that's, unfortunately, how subprocesses are currently managed by Xonsh. See https://xon.sh/envvars.html#thread-subprocs and #3342 for explanation.

**Comment by CharString** [comment]
Yeah, I found #3342 after some digging.
I love the idea and first feel of xonsh. But it starts creaking  when I actively try to use it in my day to day work.
Deadlocks and the occasional hard to reproduce Failback to /bin/bash make me uncomfortable to dive in an really use it.
