### ISSUE TITLE
bashisms unexpectedly sets THREAD_SUBPROCS to False

### ISSUE THREAD

**Issue by grzn** [xonsh/xonsh#3590]
It is not clear why, but bashisms contrib sets THREAD_SUBPROCS to False, which breaks the capture of the standard output and error into the history objects (noticed this when xontrib-histcpy didn't work for me).

I am not sure if this is needed or not, so:
# if it is needed, hav this behaviour documented on https://xon.sh/xontribs.html
# if it is not needed, remove it from the code

tnx

**Comment by laloch** [comment]
Hi @grzn, thanks for reporting.
We are aware of the issue. I have already contacted the author of the respective commit (@scopatz) and asked about the reasons. We're waiting for an answer right now.

**Comment by grzn** [comment]
Yeah I found your question on gitter.im, but didn't get any response or an open issue here so I thought it couldn't hurt bringing it up again as a proper issue.

**Comment by scopatz** [comment]
I think it is needed for some reason.  It might require some digging though the git history / issues / gitter to figure out why

**Comment by laloch** [comment]
If this is really needed, then a) there should be a big fat warning about the xontrib essentially breaking the shell, or b) we should drop the xontrib altogether. I vote in favor of b).

**Comment by scopatz** [comment]
I think we should try to figure out why this was put there

**Comment by scopatz** [comment]
OK this was put in as part of the Ctrl+Z backgrounding fix: https://github.com/xonsh/xonsh/commit/dc8728bdafcf3c1967305df57451c225e8bf8ba2

**Comment by laloch** [comment]
Yes, I know. It was in the same commit that introduced `$THREAD_SUBPROCS`, but I don't have a clue about why it is needed for `bashisms`.

**Comment by scopatz** [comment]
I guess we can remove it from that xontrib and people can add it themselves if wanted

**Comment by anki-code** [comment]
Closed with reference to #4250
