### ISSUE TITLE
history gc not working for JSON files backend

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#3599]
Discovered by code inspection in the course of working on #3586.

The fix is easy.  But the bug has been present for a couple of years now and reintroducing "correct" behavior will clip somebody's history, behavior indistinguishable from a new bug.

Do we need to add a new flag or warning to go along with this?  Let's discuss...

**Comment by astronouth7303** [comment]
Deleting data unexpectedly isn't great.

Do we have a config on how old the history is?

I almost feel like we need to enshrine the "bug" as the default behavior? I don't like that option, but it's either that (and allow the default history to grow unbounded), or the next release will delete data.

**Comment by bobhy** [comment]
Yes, there is $XONSH_HISTORY_SIZE which lets you configure history garbage
collection.  This has been documented behavior from the beginning of the
history feature.

I don't think it's a good idea to let history grow without bound.  Large
histories cause problems in Xonsh (#3586) and other PTK applications
and other shells have ways of enforcing a limit, so we're we're not being
arbitrary.

One way to go would be to issue a warning every time you start Xonsh if we
see that your existing history is "well" over the configured limit (which
defaults to 8128 commands.  Where did that number came from?) until you
either manually trim your history or change the configured limit.  So we
would not automatically and silently delete history.

Another way (more accomodating to senior users) would be to add some new
config flag to confirm you want to apply the configured or defaulted
limit.  E.g, add a third item in $XONSH_HISTORY_SIZE  or create a signal
file in the history directory?
I'd rather not do this, it complicates the elegant simplicity that is Xonsh
config today.

Your (all) thoughts?

**Comment by laloch** [comment]
I think `$XONSH_HISTORY_SIZE` should be honored for JSON backend.
However:
Do I understand it right, that #3586 is in fact a PTK issue? Why do we want to work it around in Xonsh? Does @jonathanslenders even know it exists?

**Comment by bobhy** [comment]
Yes, I do think it is an internal PTK issue.  See https://github.com/xonsh/xonsh/issues/3586#issuecomment-637512579 for more disussion.

**Comment by laloch** [comment]
What about changing the default from 8128 (?) commands to something like 2 years?

**Comment by bobhy** [comment]
That would accommodate senior users nicely (I exclude myself), but imposes a potential for bad performance on all users in exchange. 3 complete copies of history are loaded into memory between Xonsh and PTK3, and PTK reloads one copy (memory to memory) on each prompt!  Memory is cheap and disks are SSD these days, but still...
The metric I'm working on is to issue the warning if you have accumulated double your configured limit.  Senior users will have to make a one time decision and new users won't have to think about it.  There's the risk of false trigger if you manage to double your preserved history within one session, but if you're doing that unawares, you might appreciate the warning.

**Comment by astronouth7303** [comment]
> There's the risk of false trigger if you manage to double your preserved history within one session, but if you're doing that unawares, you might appreciate the warning.

Does that exclude your first couple of sessions?

**Comment by bobhy** [comment]
No, there's no special protection for the first couple of sessions.  But you are protected by the default $XONSH_HISTORY_SIZE of 8128 commands. So if you start new with Xonsh and don't configure history size, you would have to go from 0 to 16236 commands in a single session to trigger the warning.  And if that was actually intended, I'd argue you should get a warning that invites you to configure a larger limit.
I'll put in the PR tonight and we can tweak the warning then.

**Comment by bobhy** [comment]
In the course of testing this, was able to repro behavior "similar" to [this](https://github.com/xonsh/xonsh/issues/3586#issuecomment-639197914).  Including a fix for it, as well.  This makes it easier to work with Xonsh when you have very large history on disk.

There's one remaining thing that might be good:  all of my testing was with very large history, 10k files, 3M commands.  Xonsh with the PTK shell gets very sluggish in this regime (even with the above fix), and I've found it helpful to artificially limit the amount of history loaded into the prompt (independent of the Xonsh history gc that's the core of this issue).  I'm documenting the observation here, but let's finish this PR and see whether it's necessary to act on it.

**Comment by scopatz** [comment]
I think this can be closed now, right @bobhy?

**Comment by bobhy** [comment]
Mischief managed.
