### ISSUE TITLE
Inconveniente raise for command not found

### ISSUE THREAD

**Issue by luizoti** [xonsh/xonsh#3605]
## xonfig

<details>

```
$ xonfig
```

</details>

## Expected Behavior

Print the error in a more friendly way, without 'raising' it.

## Current Behavior

I get two errors when I enter a non-existent command, I believe that the correct behavior would be to only report the error without 'raising'

FileNotFoundError: [Errno 2] No such file or directory: 'q'
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: q

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

Execution of any non-existent command.

**Comment by scopatz** [comment]
Can you post the output of xonfig and the full traceback please?

**Comment by luizoti** [comment]
Unfortunately I'm not using the program anymore, but as soon as possible I can test it to see if it still happens.

BUT the problem occurred in any situation where the command does not exist.

**Comment by luizoti** [comment]
Reinstall and do not receive the error of commands that exist, maybe it is some xontrib that was being installed, strange, for now, you can close this problem as solved.

At the time I remember having tested without xontrib, anyway it's ok at the moment.
