### ISSUE TITLE
'$HOME' directory created in home dir on launch

### ISSUE THREAD

**Issue by AlexanderDavid** [xonsh/xonsh#3609]
Upon the launch of the shell in a window (using `xonsh or xonsh --no-rc`) a directory called '$HOME' is created in my home directory. 

## xonfig

<details>

```
$ xonfig

+------------------+-----------------+
| xonsh            | 0.9.14          |
| Python           | 3.8.3           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior

Xonsh should not create any files on startup

## Current Behavior

Xonsh creates a directory called '$HOME' in the home directory. Even when started with `xonsh --no-rc`

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

`xonsh --no-rc`
`cd ~ and ls`

**Comment by laloch** [comment]
Hi @AlexanderDavid, thanks for reporting.
It seems that some of your environment variables (e.g. `XDG_CONFIG_HOME` or `XDG_DATA_HOME`) contain literal "$HOME" string. Does the "$HOME" directory contain any files?
It is very unfortunate, by the way, that Arch got stuck at v0.9.14 despite the package being flagged out-of-date for quite a long time now. That version had several nasty issues. We are already at v0.9.18.

**Comment by laloch** [comment]
> Is there anything you can do to update the arch community package?

Well, we can try to mention the maintainer here...
@jleclanche, would you be so kind and update the [Arch Linux xonsh package](https://www.archlinux.org/packages/community/any/xonsh/) for us? Thanks!

**Comment by jleclanche** [comment]
Sure. Done. Sorry for the delay.

**Comment by laloch** [comment]
> Sure. Done. Sorry for the delay.

Wow! That was fast. Thanks a lot @jleclanche!

**Comment by AlexanderDavid** [comment]
I just took a closer look and there is a hidden directory in the $HOME file. There is are files at `/home/alex/$HOME/.local/share/xonsh/xonsh_script_cache/home/alex/_.config/xonsh/rc_.xsh.cpython-38`, `/home/alex/$HOME/.local/share/xonsh/xonsh_script_cache/home/alex/_.config/xonsh/$HOME/.config/fish/fish_variables` and then fish generated completions at `/home/alex/$HOME/.local/share/xonsh/xonsh_script_cache/home/alex/_.config/xonsh/$HOME/.local/share/fish/generated_completions`. I cannot find any env vars that have a literal "$HOME" in them. Do you have any other idea how I could find the culprit?

**Comment by laloch** [comment]
No, not really. If the directory appears even with `--no-rc`, I'm pretty sure that your `XDG_DATA_HOME` is set to something wrong. What do `env | grep HOME` and `echo $XONSH_DATA_DIR` print?

**Comment by laloch** [comment]
I think this needs an explanation. In Xonsh, environment variables are not just strings. They are Python objects and in Xonsh's Python mode they are treated as such. So you can do
```
$ $FOO = {"bar": [42, 18]}
$ $FOO["bar"]
[42, 18]
$ $FOO["bar"][0] + $FOO["bar"][1]
60
$ type($FOO)
dict
```
In shell mode, however, the environment variables are stringified and hence
```
$ echo $FOO
{'bar': [42, 18]}
$ # even within strings
$ echo "FOO is $FOO"
FOO is {'bar': [42, 18]}
$ #but not within raw strings
$ echo r"FOO is $FOO"
FOO is $FOO
```

**Comment by anki-code** [comment]
@AlexanderDavid Is this issue actual?

**Comment by AlexanderDavid** [comment]
> @AlexanderDavid Is this issue actual?

@anki-code I think in a sense. I tried to port my existing config over which I think was the root of th problem. I no longer use this shell though so I never figured out a fix.

**Comment by anki-code** [comment]
Let's close this and reopen in case someone faced with this.
