### ISSUE TITLE
How to use actual globals after loading xontrib?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3625]
Hello! Thank you for xonsh!

1. If I write function and put it to xonshrc I've got actual globals
2. But if I put the same code to xontrib and load it I've got not actual globals

Example:

1. Code in xonshrc:
```bash
pip install pandas
curl https://raw.githubusercontent.com/anki-code/xontrib-pipeliner/master/xontrib/pipeliner.xsh >> ~/.xonshrc2
xonsh --rc ~/.xonshrc2
echo 123 | pl "pd.DataFrame()"
# NameError: name 'pd' is not defined
import pandas as pd
echo 123 | pl "pd.DataFrame()"
Empty DataFrame
# It works after module loading!
```

2. But for xontrib:
```bash
pip install xontrib-pipeliner
xontrib load pipeliner
echo 123 | pl "pd.DataFrame()"
# NameError: name 'pd' is not defined
import pandas as pd
echo 123 | pl "pd.DataFrame()"
# NameError: name 'pd' is not defined
# It is not workng after module loading!
```

How I can load this code to use actual globals?

Thanks!

**Comment by laloch** [comment]
Hi @anki-code, xontribs are technically Python modules. Python module has it's own namespace and "globals" are in fact contained within that namespace, so they are actually module-local globals. The short answer thus is that there is no clean way to access globals in your parent module.
In Xonsh, however, you can extend builtins to provide your exported objects. This is how I used it to export `abbrevs` dictionary:
https://github.com/xonsh/xonsh/blob/ecfea5d965392bb2530ab121df23135a9bc3caf5/xontrib/abbrevs.py#L15-L17

**Comment by anki-code** [comment]
Am I right that I can't use this technique for any module? I have user defined globals and user defined code and I should run the code with globals. In the code snippet and below I see getting certain module.

**Comment by laloch** [comment]
I don't quite understand you question, but you can
```python
def pandas():
    import builtins
    import pandas as pd
    from xonsh.built_ins import DynamicAccessProxy
    builtins.__xonsh__.pd = pd
    proxy = DynamicAccessProxy("pd", "__xonsh__.pd")
    setattr(builtins, "pd", proxy)
```
This adds `pd` to your `__builtins__`, so it's accessible from anywhere in Xonsh.

**Comment by astronouth7303** [comment]
or just use `__all__` in your xontrib to declare what should be exported to the "shell context" (the global available to the user).

`xontrib load spam` is pretty close to `from xontrib.spam import *`, and adding a name to `__all__` will make make the named thing available to the user.

You use builtins tricks if you want something to be universally global (the way `aliases` and `events` are.)

Keep in mind, though, I don't believe commands (such as your hypothetical `do`) don't check the python variable scope stack (locals, closures, globals, builtins). If you want to add a `do` command, you need add it to `aliases`. (Although you might also bump into xonsh's threading/foreground/background stuff?)

**Comment by laloch** [comment]
@astronouth7303, I think I remeber what `do` or `pl` is. I think it's my idea from some time ago looking similar to:
```python
def _pl(args, stdin, stdout):
    import os
    command_string = "lambda line,index:"
    for arg in args:
        command_string += arg + " "
    fn = eval(command_string)
    index = 0
    for line in stdin.readlines():
        index += 1
        res = fn(line.rstrip(os.linesep), index)
        if res is not None:
            print(res, file=stdout, flush=True)

aliases['pl'] = pl
```

**Comment by anki-code** [comment]
@astronouth7303 Sorry I don't understand your suggestion.

I have this simple code in xontrib:
```
import os

def _pl(args, stdin, stdout):
    fn = eval('lambda line, num:'+args[0])
    num = 0
    for line in stdin.readlines():
        res = fn(line.rstrip(os.linesep), num)
        num += 1
        print(res, file=stdout, flush=True)

aliases['pl'] = _pl
del _pl
```

I just want to have an ability to call module like this:
```
import pandas as pd
echo 123 | pl "pd.DataFrame([line])"
```
This is not working when I do it in module. How `__all__` can help?

**Comment by astronouth7303** [comment]
oh! I'm sorry, I thought you were struggling to get your xontrib into the shell context.

What you want is to get the shell context inside your alias--or, technically, the calling context? (figuring out the proper callstack frame for that sounds tricky and fragile, so let's skip that for now.)

`__xonsh__.ctx` holds the shell context--the current scope of the repl. Note that this assumes that your alias was called by the repl.

[macros](https://xon.sh/tutorial_macros.html) might also be worth checking?

**Comment by anki-code** [comment]
> __xonsh__.ctx

It works! Thanks!
```
fn = eval('lambda line, num:'+args[0], __xonsh__.ctx)
```
> macros might also be worth checking?

I checked it almost immediately. And it will be great if I could create macros which can read the stdin from pipe. In this case I could use xonsh syntax highlighting:
```
cat /etc/passwd | pl!(line + '!!!')
# instead of:
cat /etc/passwd | pl "line + '!!!'"
```
I tried to deep dive into macros but without success to understand how to add reading from pipe.
