### ISSUE TITLE
Incorrect parsing of ~/.xonshrc when missing newline at end of file

### ISSUE THREAD

**Issue by tommynyquist** [xonsh/xonsh#3629]
## xonfig

<details>

```
+------------------+---------------------+
| xonsh            | 0.9.18              |
| Git SHA          | 26475146            |
| Commit Date      | May 5 06:42:28 2020 |
| Python           | 3.7.3               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.5               |
| shell type       | prompt_toolkit      |
| pygments         | None                |
| on posix         | True                |
| on linux         | True                |
| distro           | unknown             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Expected Behavior

1.  I should be able to start my shell without any errors, regardless of whether I have a newline at the end of my `~/.xonshrc` or not.
2.  When there is an error, it should point to where the error is in the configuration, instead of what happened to fail because of that.

## Current Behavior - Case 1

When I load `xontrib` modules, I typically keep each of them on its own line, like so:

```
xontrib load first_module \
  second_module \
  third_module

... more configuration ...
```

However, this seems to require that the whole `.xonshrc` file has a newline at the end.

If I have a newline at the very end of the file, everything works, but if I don't, I get this error:

```
  File "<string>", line None
SyntaxError: /home/<MY USERNAME>/.xonshrc:1:8: ('code: load',)
xontrib load coreutils \
        ^
syntax error in xonsh run control file '/home/<MY USERNAME>/.xonshrc': /home/<MY USERNAME>/.xonshrc:1:8: ('code: load',)
xontrib load coreutils \
        ^
```

This is particularly confusing if you have a long `.xonshrc` file, because if you miss a newline at the end of the file, the error still points to the `xontrib load` line, which might be much further up the file.

One important thing to note here is that the following works as expected even if there is no newline at the end of the file:

```
xontrib load first_module second_module third_module

print('hello')
```

But by splitting the modules to individual lines like this causes an issue if there is no newline after the `print('hello')` statement, but causes no issue if there is a newline.

```
xontrib load \
  first_module \
  second_module \
  third_module

print('hello')
```

### Traceback - Case 1

<details>

```
Traceback (most recent call last):
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/environ.py", line 1757, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/codecache.py", line 160, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/codecache.py", line 119, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/execer.py", line 238, in _parse_ctx_free
    raise original_error from None
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/execer.py", line 223, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/parsers/base.py", line 3314, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/parsers/base.py", line 676, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: /home/<MY USERNAME>/.xonshrc:1:8: ('code: load',)
xontrib load coreutils \
        ^
syntax error in xonsh run control file '/home/<MY USERNAME>/.xonshrc': /home/<MY USERNAME>/.xonshrc:1:8: ('code: load',)
xontrib load coreutils \
        ^
```

</details>

## Steps to Reproduce Case 1

Enter the following content into `~/.xonshc`:

```
xontrib load coreutils \
  prompt_ret_code

print('hello')
```

NOTE: Do not have an newline after the `print('hello')` statement to reproduce the error. If you do have a newline, everything works as expected.

## Current Behavior - Case 2

The following configuration also generates an error with no newline at the end:

```
xontrib load coreutils \
  prompt_ret_code
```

But that error is:

```
TypeError: expected Module node, got Expression
error running xonsh run control file '/home/<MY USERNAME>/.xonshrc': expected Module node, got Expression
```

### Traceback - Case 2

<details>

```
Traceback (most recent call last):
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/environ.py", line 1757, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/codecache.py", line 160, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/codecache.py", line 119, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/home/<MY USERNAME>/.local/lib/python3.7/site-packages/xonsh/execer.py", line 138, in compile
    code = compile(tree, filename, mode)
TypeError: expected Module node, got Expression
error running xonsh run control file '/home/<MY USERNAME>/.xonshrc': expected Module node, got Expression
```

</details>

## Steps to Reproduce Case 2

Enter the following content into `~/.xonshc`:

```
xontrib load coreutils \
  prompt_ret_code
```

NOTE: Do not have an newline after `prompt_ret_code` to reproduce the error. If you do have a newline, everything works as expected.

**Comment by laloch** [comment]
Hi @tommynyquist, thanks for reporting! I can reproduce the issue.
It is, however, very strange, because we have the following:
https://github.com/xonsh/xonsh/blob/14771a7e51441144148399ab286c81c0d5edbb3d/xonsh/codecache.py#L110-L116
I'm investigating the issue.

**Comment by laloch** [comment]
So no, not really. The case #1 fails for me regardless of the terminating EOL character. It is caused solely by the line continuation in the `xontrib load` command.

**Comment by laloch** [comment]
@tommynyquist, I've just submitted #3630, that should fix the issue. It would be great if you could test yourself, because I could not reproduce the issue exactly as described. Thanks!

**Comment by tommynyquist** [comment]
Using "Steps to Reproduce - Case 1" and "Steps to Reproduce - Case 2" from above, with and without newline at the end, these are my results:

# With trailing newline
- #3630: Works for both cases.
- xonsh/0.9.18: Works for both cases.

# Without trailing newline
- #3630: Works for both cases.
- xonsh/0.9.18: Fails as reported.

So I've verified that the fix works. Thank you for the incredibly quick turnaround!


Note to self for my steps for testing the fix:

```
cd ~/code
mkdir xonsh-home
touch xonsh-home/.xonshrc
git clone https://github.com/xonsh/xonsh.git
cd xonsh
gh pr checkout 3630
sudo python3 xonsh-in-docker.py
<Ctrl+D>
sudo docker run -it --rm  -v /home/<MY USERNAME>/code/xonsh-home:/root xonsh:latest xonsh
```

And then I ran docker manually and edited `xonsh-home/.xonshrc` each time for the various repro cases.

Is there an easier way to read a particular `.xonshrc` using `xonsh-in-docker.py`?

**Comment by laloch** [comment]
Thanks for testing the patch @tommynyquist.

> Is there an easier way to read a particular .xonshrc using xonsh-in-docker.py?

Yes, you can `./xonsh-in-docker.py --python 3.8 XONSHRC=/xonsh/test.rc`, provided that there's `test.rc` file at the Xonsh working tree directory.
