### ISSUE TITLE
Xonsh-Python_Toolkit Integration Tutorial

### ISSUE THREAD

**Issue by shadowrylander** [xonsh/xonsh#3631]
Hello!

I've been looking for a tutorial for the prompt_toolkit's use with xonsh, but I can't seem to find one anywhere; would someone be able to direct me to one, or failing that, give me a few pointers on how to get started? It seems as though the toolkit's documentation itself is for general application, and doesn't give any indication of how to integrate it into xonsh.

Thank you kindly for the help!

**Comment by laloch** [comment]
Hi @shadowrylander, thanks for your interest in Xonsh.
Currently, there is no PTK+Xonsh tutorial. Xonsh makes use of `PromptSession` "shortcut" class and integrates with PTK's history, completion and key binding features. Is there any particular topic you are interested in?

**Comment by shadowrylander** [comment]
For the moment, just how to start integrating them; do you have to replace the current, non-toolkit prompt, for example? And how do you color and otherwise change the appearance a prompt managed by the toolkit?

**Comment by laloch** [comment]
I'm afraid, I don't quite understand. If you have PTK installed Xonsh will detect and use it by default. Run `xonfig` to see what type of prompt you are using.

**Comment by shadowrylander** [comment]
Ah; yes, it appears that I'm already using the toolkit. But I still don't know how to customize it.

**Comment by laloch** [comment]
There are [$PROMPT](https://xon.sh/envvars.html#prompt), [$RIGHT_PROMPT](https://xon.sh/envvars.html#right-prompt), [$PROMPT_FIELDS](https://xon.sh/envvars.html#prompt-fields) and [$BOTTOM_TOOLBAR](https://xon.sh/envvars.html#bottom-toolbar) environment variables. See [Customizing the Prompt](https://xon.sh/tutorial.html#customizing-the-prompt) for some details.

**Comment by laloch** [comment]
You might also want to try `xonfig web` to choose from some predefined default prompt styles.

**Comment by shadowrylander** [comment]
When I originally switched to the toolkit, it seemed that its defaults overrode my own `$PROMPT` settings, so I don't quite know what happened there; I can post the appropriate snippet here, if that would help?

**Comment by laloch** [comment]
Yes, sure.

**Comment by shadowrylander** [comment]
```
$PROMPT = """
{BOLD_#E5004D}{env_name}{BOLD_#FC9F71}{user}@{hostname}
{BOLD_#FCFDF7}{cwd}
{branch_color}{gitstatus} {BOLD_#FF4081}λ """
```
It seems as though the colors went back to their defaults somehow after using the toolkit.

**Comment by laloch** [comment]
Looks the same here using readline and prompt_toolkit. The only difference is that PTK resets the color if the input itself to default whereas readline displays the input in a pinkish (#FF4081) color.

**Comment by shadowrylander** [comment]
That makes sense. I'll play around with it a bit, then; thanks for all the help!
