### ISSUE TITLE
CI failure - AttributeError: module 'builtins' has no attribute '__xonsh__'

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#3635]
CI test failure that doesn't happen locally and doesn't seem to be related to any (recent) code change.  
Exact point of failure fluctuates from run to run and (is this just my paranoia?) time of day or week.

So far, I have always been able to get a clean run by manually re-running the jobs on the same code 
 (in my staging repo on GitHub there's a `re-run all jobs` option, though not on the PR to `xonsh/xonsh`)

Does anyone have insight as to what's actually going on? 

A superficial review of the failing  code (traceback, below) shows a sequence of statements successfully referring to `builtins.__xonsh__`, then boom! one fails, and it is not the last in the sequence, either.  This colud be a race condition between tests running in parallel, but I do not believe the Xonsh CI action invokes `pytest` that way.  

### Traceback (if applicable)

<details>

```
==================================== ERRORS ====================================
____________ ERROR at setup of test_premain_with_file_argument[-i] _____________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fbe619419a0>
xonsh_events = <xonsh.events.EventManager object at 0x7fbe5ec582e0>

    @pytest.fixture
    def xonsh_builtins(monkeypatch, xonsh_events):
        """Mock out most of the builtins xonsh attributes."""
        old_builtins = set(dir(builtins))
        execer = getattr(getattr(builtins, "__xonsh__", None), "execer", None)
        session = XonshSession(execer=execer, ctx={})
        ensure_attached_session(monkeypatch, session)
        builtins.__xonsh__.env = DummyEnv()
        if ON_WINDOWS:
            builtins.__xonsh__.env["PATHEXT"] = [".EXE", ".BAT", ".CMD"]
        builtins.__xonsh__.shell = DummyShell()
        builtins.__xonsh__.help = lambda x: x
        builtins.__xonsh__.glob = glob.glob
        builtins.__xonsh__.exit = False
        builtins.__xonsh__.superhelp = lambda x: x
        builtins.__xonsh__.pathsearch = pathsearch
        builtins.__xonsh__.globsearch = globsearch
        builtins.__xonsh__.regexsearch = regexsearch
>       builtins.__xonsh__.regexpath = lambda x: []
E       AttributeError: module 'builtins' has no attribute '__xonsh__'

tests/conftest.py:122: AttributeError
```

</details>

## Steps to Reproduce
1. Push a test version of Xonsh to staging repo on github
2. Let configured github actions kick off a job.

**Comment by laloch** [comment]
Hi @bobhy, we are painfully aware of the issue. As far as I can tell, no one has been able to come with a satisfactory explanation so far.

**Comment by bobhy** [comment]
Annoying!  Is there a trick I can use to run the CI jobs a second time on the PR without pushing a (trivial) change to the linked repo?  E.g, in https://github.com/bobhy/xonsh/actions, there is a 're-run all jobs' button above the log panel when I look at a particular log file, but no such link on https://github.com/xonsh/xonsh/actions.

Has there been any prior discussion on possible causes?  I note that the code that seems to fail is (always?) reference to `builtins.__xonsh__`, which seems oddly specific.

**Comment by laloch** [comment]
> Annoying! Is there a trick I can use to run the CI jobs a second time on the PR without pushing a (trivial) change to the linked repo?

Yeah, quite annoying and spooky. I think only members can re-run the CI. I do occasionally check the CI results and retrigger the run if I judge it failed for some intermittent reason. You can, of course, leave us a message.

> Has there been any prior discussion on possible causes?

Not really, at least as far as I can remember. I can only tell that it happens a lot less often now with Github Actions than before with Azure.

> I note that the code that seems to fail is (always?) reference to `builtins.__xonsh__`, which seems oddly specific.

Yes, it's pretty much always the same.

**Comment by scopatz** [comment]
I am seeing it all the time on github actions now, actually...
