### ISSUE TITLE
Attempting to install xonsh on Windows with pipx fails

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#3637]
## Expected Behavior

Using `pipx install xonsh` should install a working `xonsh` command.

## Current Behavior

Using `pipx install xonsh` results in an error, `No module named xonsh`.

It seems the executable wrappers (`.bat` files, yuck) are unaware of the Python virtual environment created by pipx.

```
PS C:\WINDOWS\system32> pipx install xonsh
  installed package xonsh 0.9.18, Python 3.8.3
  These apps are now globally available
    - xon.sh
    - xonsh-cat.bat
    - xonsh.bat
done!
←[?25h
PS C:\WINDOWS\system32> xonsh
C:\Python38\python.exe: No module named xonsh
PS C:\WINDOWS\system32> cat ~/.local/bin/xonsh.bat
@echo off
call :s_which py.exe
if not "%_path%" == "" (
  py -3 -m xonsh %*
) else (
  python -m xonsh %*
)

goto :eof

:s_which
  setlocal
  endlocal & set _path=%~$PATH:1
  goto :eof
```

This issue does not seem to occur with other programs installed by pipx, which end up with `.exe` wrappers.

## Steps to Reproduce

Using a late Windows 10, install Python 3.8 to C:\Python38 (default for Chocolatey). Then use `py -m pip install pipx` to install pipx system-wide, then use the pipx command to install xonsh.

**Comment by melund** [comment]
I recall that we don't generate "exe" wrappers because they were slow to start up. Or used to be at least. You can see here:

https://github.com/xonsh/xonsh/blob/master/setup.py#L392-L401

The "exe" wrapper comes back if `'console_scripts': ['xonsh = xonsh.main:main'],` is added back to "entry_points".  

Maybe you could make the current batch scripts work with pipx? Or maybe we could add the entry point back for Windows only. I suspect the batch script wrapper on windows are probably also slow. So maybe the difference is marginal here. Also this will  probably not affect xonsh installed using conda since it creates its own exe wrappers.

**Comment by jaraco** [comment]
> You can see [here](https://github.com/xonsh/xonsh/blob/master/setup.py#L392-L401)

I'm pretty sure that comment is stale.

In the old days, when using `easy_install`, the script wrappers would `import pkg_resources`, which could add significant startup overhead (depending on the environment), and were appropriately characterized as "slow". Today, `easy_install` is deprecated in favor of `pip install`, which uses `distlib` to generate script wrappers that are "fast". The only case where setuptools' `console_scripts` are still slow is with "editable installs" (i.e. `setup.py develop` or `pip install -e`).

Probably the right thing to do here is to do just what the comment advises against and use console scripts. I'll run some tests to see if the startup time is affected.

**Comment by jaraco** [comment]
Using `xonsh` at master, I ran these timing tests:

```
xonsh master $ time .tox/python/bin/xonsh -c "pass"
        0.34 real         0.11 user         0.03 sys
xonsh master $ time .tox/python/bin/xonsh -c "pass"
        0.16 real         0.12 user         0.03 sys
xonsh master $ time .tox/python/bin/xonsh -c "pass"
        0.15 real         0.11 user         0.03 sys
```

I then patched xonsh thus:

```diff
diff --git a/setup.py b/setup.py
index e482b751..dc3905ad 100755
--- a/setup.py
+++ b/setup.py
@@ -337,10 +337,8 @@ def main():
         readme = f.read()
     scripts = ["scripts/xon.sh"]
     if sys.platform == "win32":
-        scripts.append("scripts/xonsh.bat")
         scripts.append("scripts/xonsh-cat.bat")
     else:
-        scripts.append("scripts/xonsh")
         scripts.append("scripts/xonsh-cat")
     skw = dict(
         name="xonsh",
@@ -399,6 +397,9 @@ def main():
         #     'console_scripts': ['xonsh = xonsh.main:main'],
         #
         # END WARNING
+        skw.update(
+            console_scripts=['xonsh = xonsh.main:main'],
+        )
         skw["entry_points"] = {
             "pygments.lexers": [
                 "xonsh = xonsh.pyghooks:XonshLexer",
```

And ran the tests again and got comparable results:

```
xonsh master $ time .tox/python/bin/xonsh -c "pass"
        0.27 real         0.11 user         0.03 sys
xonsh master $ time .tox/python/bin/xonsh -c "pass"
        0.15 real         0.12 user         0.03 sys
xonsh master $ time .tox/python/bin/xonsh -c "pass"
        0.15 real         0.12 user         0.03 sys
```

That change has the effect of creating this wrapper script on macOS:

```
xonsh master $ cat .tox/python/bin/xonsh
#!/Users/jaraco/code/public/xonsh/.tox/python/bin/python

from xonsh.main import main
main()
```

I've tried validating this change on Windows under pipx install, but pipx is really buggy on Windows and when I install from source, it doesn't find the "'xonsh' app".

**Comment by jaraco** [comment]
Hmm. So it seems I was mistaken. The diff I'd used was incorrect because `console_scripts` wasn't included in `entry_points`... so it had no effect.

**Comment by jaraco** [comment]
After creating a correct diff, I've confirmed the startup times are comparable:

```
xonsh console-scripts $ time .tox/python/bin/xonsh -c "pass"
        0.16 real         0.12 user         0.03 sys
xonsh console-scripts $ time .tox/python/bin/xonsh -c "pass"
        0.16 real         0.12 user         0.03 sys
xonsh console-scripts $ time .tox/python/bin/xonsh -c "pass"
        0.17 real         0.12 user         0.03 sys
```

with the pip-based script wrapper:

```
xonsh console-scripts $ cat .tox/python/bin/xonsh
#!/Users/jaraco/code/public/xonsh/.tox/python/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from xonsh.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by jaraco** [comment]
The diff at f0e621c5 demonstrates a diff that has suitable startup performance when installed with pip but also works properly when installed with pipx on Windows.

**Comment by jaraco** [comment]
This issue is likely related to #2646.

**Comment by melund** [comment]
I think I need @scopatz' input for this one. 

Using `pip install . ` does install fast wrappers, but it is not the case when using `python setup.py install`.  I think there may still be a reason we use the latter, although it could have been solved since then. 

Thinks have improved over time. The last time this was brought up the remaining reasons were dependency on setuptools and the ability to regenerate parser tables.

See: #1126 

I really hope this can be fixed now :)

**Comment by scopatz** [comment]
@jaraco - you are totally correct that we were avoiding the pkg_resources import in the generated script.  From what you say now, using the entry points doesn't seem to impact performance anymore.  Would you mind putting in a PR to switch to entry points, please? Thanks!

**Comment by anki-code** [comment]
Hi @jaraco! I see PR here. Does this issue still actual?

**Comment by jaraco** [comment]
Let me give it a spin in a Docker container.

Yes! I ran `pipx install xonsh`, and while I got a bunch of warnings about subprocess encoding not being in cp-1252, it installed fine and the `xonsh` command was available thereafter. Seems to be fixed. Thanks all!
