### ISSUE TITLE
Remove distutils install path

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#3638]
The current implementation of xonsh uses a bi-modal install routine that uses setuptools if available and falls back to distutils if setuptools is not available. Use of distutils is discouraged and distutils is likely to be deprecated and removed from stdlib. The recommended practice now is to require setuptools, either implicitly (failing when it's not available) or explicitly (using PEP 518 build requirements).

Dropping the distutils fallback from xonsh would simplify the install routine, prepare it for future compatibility, and enable features like declarative config.

Would you consider a PR to remove the distutils fallback? Are there known use-cases relying on it that could not be adapted to use Setuptools?

**Comment by scopatz** [comment]
Yep! Totally in favor of removing disutils!
