### ISSUE TITLE
Question: How to update prompt?

### ISSUE THREAD

**Issue by samedamci** [xonsh/xonsh#3640]
Hello, I want to update prompt state one time after pressing Esc without setting $UPDATE_PROMPT_ON_KEYPRESS, because this is really slow. How can I do this? I was looking for solution in documentation but I didn't found anything. Is available some method to do this or something similar?

**Comment by scopatz** [comment]
Cool idea. You should take a look at https://xon.sh/tutorial_ptk.html  This should be doable with the instructions there

**Comment by deeuu** [comment]
I'd also like to know how to update the prompt from inside a `ptk` event-handler. For example, I'm currently executing `xonsh.built_ins.cd` within a custom keybinding event, but `$PROMPT` does not update, despite the dir change:

```
from prompt_toolkit.keys import Keys
from xonsh import built_ins

@events.on_ptk_create
def custom_keybindings(bindings, **kw):

    @bindings.add(Keys.ControlW)
    def go_home(event):
        built_ins.cd(['~'])
```
@scopatz any hints please!

**Comment by scopatz** [comment]
I don't know that PTK let's you redraw the actual prompt itself.  Maybe it does?

**Comment by beetleb** [comment]
I too have the same problem. I'm using fzf to select a directory, and I cd to it. However, the prompt still shows the old directory.

Not sure if this helps: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/788

**Comment by deeuu** [comment]
@beetleb Try [following `cd` by a carriage return](https://github.com/deeuu/xontrib-fzf-widgets/blob/master/xontrib/fzf-widgets.xsh#L221-L222) as a workaround

**Comment by beetleb** [comment]
@deeuu 

That actually worked. Thanks!

**Comment by eugenesvk** [comment]
@deeuu have you found a proper solution without the carriage return workaround? Would be cool if you could CD with keybinds just like in fish without having newlines on every call

**Comment by eugenesvk** [comment]
I've found a way!

The gist below has a xonsh xontrib example that CDs up one folder on <kbd>⎈</kbd><kbd>z</kbd> and updates all 3 prompts (if they exist) "inline", i.e., without generating a new line like the carriage return workaround does

https://gist.github.com/eugenesvk/fb8078d7388fc4d722f2c4b88f63cda1

Let me know if you find a better way, e.g., it would be nice not having to recalculate/reformat with all the token escapes all the new prompt values yourself but maybe trigger some hidden xonsh command that would do that for you

**Comment by eugenesvk** [comment]
But this example has the same issue as all the other examples in the various issues on this topic - they don't address the main use case of updating **existing** prompts

Gist is just a snippet (though it's also technically just a git repo), there is no complete solution yet, though I was thinking of one: replicating fish with inline history CDs with ⌘◀▶ that could use this snippet and become a standalone xontrib
