### ISSUE TITLE
keybindings messed up when staring within a script [NixOs specific?]

### ISSUE THREAD

**Issue by con-f-use** [xonsh/xonsh#3644]
Given I have as script `./morefile.sh`:
```
#!/usr/bin/env bash
more somefile.txt
```
and I run it from within xonsh, then I cannot use key bindings in `more`  at all. This happens:

![more keybindings broken with xonsh](https://user-images.githubusercontent.com/11145016/88485895-0e3c1600-cf7a-11ea-8272-805d20c75294.png)

The <kbd>j</kbd>, <kbd>k</kbd>, <kbd>↑</kbd>, etc. keys are supposed to scroll, but are printed in the bottom line instead. Same for vim and some other programs.

**Comment by scopatz** [comment]
It might be because the script is marked as threadable

**Comment by con-f-use** [comment]
Okay, that means what exactly?

**Comment by gforsyth** [comment]
@con-f-use try putting this in your `xonshrc`:

```
(base)   ~ $ from xonsh.commands_cache import predict_false
(base)   ~ $ __xonsh__.commands_cache.threadable_predictors["more"] = predict_false
```

interactive programs should usually be marked false this way.  we try to detect them automatically but it doesn't always work.

**Comment by scopatz** [comment]
I think `more` is in the default predictors. I think the issue might be that the xsh script that is calling this (ie `morefile.sh`) is not in threadable predictors. So more like:

```
(base)   ~ $ from xonsh.commands_cache import predict_false
(base)   ~ $ __xonsh__.commands_cache.threadable_predictors["morefile.sh"] = predict_false
```

**Comment by con-f-use** [comment]
Neither seem to fix it for me, and yes, I did restart xonsh after I changed the rc.

**Comment by scopatz** [comment]
It matches the basename of the commane (ie `more` in `/path/to/more`) or the fullpath.  I don't think this is a nix-specific issue.  Could you try:

```
__xonsh__.commands_cache.threadable_predictors["/full/path/to/morefile.sh"] = predict_false
```

**Comment by con-f-use** [comment]
Yeah, that does the trick - also just `morefile.sh`, without full path, does. I must have had a typo earlier.

**Comment by scopatz** [comment]
We have some general heuristics that mostly work, but they do fail this use case

**Comment by scopatz** [comment]
I am open to ideas here

**Comment by con-f-use** [comment]
The easiest thing to do is include it in the troubleshooting section of the manual. "If you have this problem, try setting the predictor to false."
I'll make a PR tomorrow, I think.

**Comment by scopatz** [comment]
It does, but our heuristic right now doesn't know that more is going to be run, which is the real problem.  We really need to replace the execution engine in xonsh, but I think that might be a 2.0 feature

**Comment by anki-code** [comment]
I'm going to close this issue with reference to #4214
