### ISSUE TITLE
How to detect if an alias' output is beign redirected?

### ISSUE THREAD

**Issue by cafehaine** [xonsh/xonsh#3648]
Hi, I've been using xonsh for about a week now, and I'm writing a xontrib that acts like [lsd](https://github.com/Peltoche/lsd), however I would like to detect when my alias' output is being piped to another process (in order to fall back to the system's ls command).

Python's sys.stdout.isatty doesn't seem to work, as it always returns False, and the "stdout" argument that xonsh passes to the alias is a buffer, so I can't determine this way if the output is interactive.

Is there any way to do this? I couldn't find anything about this in the documentation.

Here is a basic example:
```
$ def _echo(args): 
.     if not sys.stdout.isatty(): 
.         print("Not a tty") 
.         @(["/usr/bin/env", "echo"] + args) 
.         return 
.     print("A tty") 
.     print(args) 
.
$ aliases['echo'] = _echo
$ echo a b
Not a tty
a b
$ echo a b | cat                                                                                                                                              
Not a tty
a b
```
In the above example, the code always goes inside the if.

Thanks in advance !

**Comment by scopatz** [comment]
I think you want the 5th kind of callable alias, which gets you the `spec` (`SubprocessSpec`) object: https://xon.sh/tutorial.html#callable-aliases

We use this in our `which` command (https://github.com/xonsh/xonsh/blob/master/xonsh/xoreutils/which.py#L116) to see if the command is being captured or not in order to determine if a newline should be added

**Comment by cafehaine** [comment]
My bad, I didn't read this section of the tutorial with enough attention.

Unfortunately it doesn't seem to detect a piped output (`ls | cat`), only captured via `$()` or `!()` as indicated in the tutorial.

I don't really mind not detecting this, so my issue can be closed, however this might be a useful addition to xonsh.

Thanks a lot!

**Comment by scopatz** [comment]
Ok - This does exist.  You need to use the `last_in_pipeline` attr (boolean) of the spec:

```sh
$ def _echo(a, si, so, se, spec): 
       print(spec.last_in_pipeline)                                                                
$ aliases['mine'] = _echo                                       
$ mine                                                          
True
$ mine | cat                                                    
False
```

Some specific docs on this would be very welcome!

**Comment by cafehaine** [comment]
Technically it's in the documentation even if I didn't realize it:
https://xon.sh/api/built_ins.html#xonsh.built_ins.SubprocSpec

I think even just a link to the documentation of SubprocSpec could be enough to lead a user in the right direction (or just adding another if in the example you linked above)

**Comment by scopatz** [comment]
Yep! PRs welcome!
