### ISSUE TITLE
Do we really support python3.5?

### ISSUE THREAD

**Issue by daniel-shimon** [xonsh/xonsh#3651]
According to the docs xonsh supports python3.5, but it doesn't seem to actually support it:

* There are f-strings in a lot of places
* The CI only runs with python3.6 and above
* Black only runs with python3.6+

Shouldn't the docs and `setup.py` change to python3.6+?

**Comment by melund** [comment]
I think everyone agrees we should drop 3.5. 

So unless anyone @xonsh/xore objects a PR removing 3.5 would be very welcome :)

**Comment by Carreau** [comment]
As a point, IPython got a new release yesterday marked at 3.7+.

**Comment by gforsyth** [comment]
please someone kill 3.5

or I can get to it later this week.

**Comment by Carreau** [comment]
#3654 is step toward it.

**Comment by daniel-shimon** [comment]
Awesome! Thanks!
