### ISSUE TITLE
Xonsh invoked with wrong python (on Windows)

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#3661]
`py.exe` launcher for windows seems to choose the "wrong" interpreter when invoked with `py -3`.

In my case, the "wrong" interpreter is the system-wide one lacking Pygments, prompt_toolkit xonsh prerequisites.  The "right" interpreter is in a currently active virtual environment which does have these installed.  

For example:
<details>

```
(.venv) PS C:\Users\bobhy\src> xonsh
C:\Users\bobhy\AppData\Local\Programs\Python\Python38\lib\site-packages\xonsh\__amalgam__.py:16266: UserWarning: prompt_toolkit is not available, using readline instead.
  warnings.warn(
Skipping setup. Because no `readline` implementation available.
            Please install a backend (`readline`, `prompt-toolkit`, etc) to use
            `xonsh` interactively.
            See https://github.com/xonsh/xonsh/issues/1170
```

</details>

## Expected Behavior

Invoking `xonsh` from CLI command line (whether `cmd.exe` or `powershell` on Windows) should run with the python interpreter found first on the PATH (which should correspond to an activated virtual environment, if `venv` has done its job).

## Current Behavior

This seems to be a bug in [py.exe](https://docs.python.org/3/using/windows.html#launcher) when there are multiple python interpreters in PATH.

```
(.venv) PS C:\Users\bobhy\src> echo $env:PATH
C:\Users\bobhy\src\xonsh\.venv\scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Users\bobhy\bin;C:\Users\bobhy\AppData\Local\Programs\Python\Launcher\;C:\Users\bobhy\AppData\Local\Microsoft\WindowsApps;C:\Users\bobhy\AppData\Local\Programs\Microsoft VS Code\bin;C:\dev\nvm;C:\Program Files\nodejs;C:\Users\bobhy\AppData\Local\Programs\Azure Data Studio\bin
(.venv) PS C:\Users\bobhy\src> py -3 -c 'import sys; print(sys.executable, sys.version)'
C:\Users\bobhy\AppData\Local\Programs\Python\Python38\python.exe 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)]
(.venv) PS C:\Users\bobhy\src> py -c 'import sys; print(sys.executable, sys.version)'
C:\Users\bobhy\src\xonsh\.venv\Scripts\python.exe 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
(.venv) PS C:\Users\bobhy\src>
```

Note that `py -3` invoked a python 3.x interpreter further down PATH than the unadorned `py`.  

[xonsh.bat](https://github.com/xonsh/xonsh/blob/master/scripts/xonsh.bat) uses `py -3`, triggering this error.

Simple fix (now that python 2.x is no longer supported) is to remove the `-3`. A fancier fix would be to drop the dependence on `py.exe`, invoke python by name and rely on user to establish a proper PATH.   I'd expect this to continue to work when a future python v4 comes out and explicitly specifying the version once again becomes a thing.

A PR is forthcoming.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Did seems like an entrypoints issue CC @jaraco

**Comment by bobhy** [comment]
Fix for this issue accepted, I'm happy.

**Comment by jaraco** [comment]
I only now just got around to reviewing this. I'm okay with this approach, especially if it's working.
