### ISSUE TITLE
Question: Redirect output to a variable when using execx

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3663]
In normal xonsh syntax you can write:

    mydir = "/what/ever/is/the/correct/dir"
    res = $(ls -l @(mydir))

and res will contain the directory list.

How can I achive this output redirection to a variable when using `execx`? Say,`ls -l @(mydir))` is given as a string `cmd = 'ls -l @(mydir))'`, then

    res = execx(cmd) 

does not return the output, but rather prints it to the terminal.

Can I somehow use `execx`'s filename argument for this?

**Comment by laloch** [comment]
Hi @halloleo,
```python
cmd = 'res = $(ls -l @(mydir))'
execx(cmd, locs=locals())
```

**Comment by halloleo** [comment]
Of course! Cool! Very literal! Thanks.
