### ISSUE TITLE
tab completion on empty line shows many files

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#367]
When I press tab on an empty terminal xonsh prints more than 5524 files. That is long list. I guess that is all the files I have in my path. In my normal terminal there is only 813 files. Seems that Xonsh also includes non executables. 

Also my normal terminal has a some nice behaviour. First is always ignores the first tab-press. On the second press it asks:

```
Display all 813 possibilities? (y or n)
```

Maybe xonsh should do something similar?

**Comment by scopatz** [comment]
Are you on readline or prompt-toolkit?

**Comment by scopatz** [comment]
I vaguely recall seeing this feature before with xonsh in readline, but it has been a while.

**Comment by melund** [comment]
It was using readline. prompt-toolkit only shows five completions in which you can scroll. Do you know of any way to ask the user if there are many completions.

**Comment by scopatz** [comment]
The magic variable is apparently `rl_completion_query_items`, which you can read about at http://www.delorie.com/gnu/docs/readline/rlman_47.html

This is probably not set, or set way too high, or something.  Something like what is done for `RL_COMPLETION_SUPPRESS_APPEND` should be done for this variable.

**Comment by scopatz** [comment]
This should be fixed by #2086

**Comment by gforsyth** [comment]
Fixed in #2086
