### ISSUE TITLE
pip install . doesn't install __amalgam__ and parser tables. 

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#3681]
It seems that `__amalgam__.py` and parser tables are not installed when running `pip install .`. The old `python setup.py install` does the right thing. 

Pip does create the "`__amalgam__.py`" files in the temporary build directory. But it doesn't copy them afterwards. Probably it ignores all temporary files generated during the build

To reproduce: 
1. Ensure that xonsh repo is clean from any "`__amalgam__.py`" files. Otherwise it will appear to work. 
2. Ensure that you remove the "Lib/site-packages/xonsh" folder before trying.

**Comment by scopatz** [comment]
Yeah this is a huge issue

**Comment by scopatz** [comment]
Uggh pip just seems totally broken. Manually adding these to data files and the manifest did nothing

**Comment by laloch** [comment]
> Uggh pip just seems totally broken. Manually adding these to data files and the manifest did nothing

Are you sure, that's a problem with pip? When I did `python setup.py sdist` in a clean working directory a few days ago, the files were not in the archive either.

**Comment by scopatz** [comment]
Yeah, sdists are just a tarball, so that is expected. They should appear in a wheel though. I guess I trying to figure out how to get genereated files into the wheel.

**Comment by scopatz** [comment]
Or maybe generate the files before the wheel is created somehow?

**Comment by laloch** [comment]
> Yeah, sdists are just a tarball, so that is expected.

No, it's not. It should be handled by `class xsdist(sdist)`, but it's not.

**Comment by scopatz** [comment]
Maybe it is that `get_file_list` needs to be overridden?

**Comment by melund** [comment]
> Or maybe generate the files before the wheel is created somehow?

Yes. I think that will work. They are only copied if they are present in the source directory before the build starts. But I don't know if it is possible. What about some dummy/empty files in the source repository. They could then be regenerated during the build as we do now. I think that will ensure they are copied.

**Comment by scopatz** [comment]
Actually I think we might need to change from install to build_py

**Comment by scopatz** [comment]
OK! I think I have a fix in #3695
