### ISSUE TITLE
settitle() corrupts prompt in Windows Terminal and cmd.exe

### ISSUE THREAD

**Issue by tc21** [xonsh/xonsh#3703]
On Windows, when using Windows Terminal, sometimes when I run a program, the prompt gets corrupted with parts of some ANSI control codes.

![demo2](https://user-images.githubusercontent.com/14813183/90605770-a6ad6b00-e1b3-11ea-9db5-e4b2337247be.png)

I've figured out that this started happening because https://github.com/xonsh/xonsh/pull/3377 gave `$ANSICON` a default value, which broke this code in BaseShell.settitle:

```
    if ON_WINDOWS and "ANSICON" not in env:
#                     ^^^^^^^^^^^^^^^^^^^^ this is broken
            kernel32.SetConsoleTitleW(t)
        else:
            with open(1, "wb", closefd=False) as f:
                # prevent xonsh from answering interactive questions
                # on the next command by writing the title
                f.write("\x1b]0;{0}\x07".format(t).encode())
                f.flush()
```

Remarks: 
- A similar thing happens in cmd.exe and powershell.exe.
- I was able to consistently reproduce it by running a git for Windows exe, but I couldn't figure out the specific reasons and circumstances that caused it to happen. if I changed `"\x1b]0;{0}\x07"` to `"\x1b]0;{0}\x07\x1b["` it would fix it in Windows Terminal (but either not help or break it elsewhere), for example.
- `$ANSICON` isn't the only environment variable that got a default value: a quick compare got me this list: `{'XONSH_SOURCE', 'OLDPWD', 'VIRTUAL_ENV', 'TERM', 'XONSH_INTERACTIVE', 'XONSH_GITSTATUS_*', 'ANSICON'}`

## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.19                                                |
| Python           | 3.8.2                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.10                                                |
| shell type       | prompt_toolkit                                        |
| pygments         | 2.4.2                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x000001DF0EC23D60> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x000001DF0EC23D00> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

**Comment by tc21** [comment]
I've uploaded the fix I'm using locally, in case it helps you.

**Comment by scopatz** [comment]
Ahhh I was wondering why this happened! Thanks so much!

**Comment by scopatz** [comment]
Maybe we can avoid calling `settitle()` on windows instead? I didn't think it would be called at all, but something changed either here or in the windows terminal

**Comment by laloch** [comment]
Yeah, but that wouldn't solve the other issues caused by the existence of variables, that shouldn't exist.

**Comment by scopatz** [comment]
Those variables all should exist though

**Comment by laloch** [comment]
Well, that's questionable at least in case of `VIRTUAL_ENV` and `XONSH_SOURCE`. Besides, it breaks pre-0.9.19 scripts that test for existence of those variables. I realize, that we are still stabilizing and that occasional changes of such kind are acceptable, but this doesn't make much sense to me.

**Comment by scopatz** [comment]
Actually, I think those are some of the ones that really should exist in all cases.  In any event, if we wanted the default value to be some other type that indicates invalid values (like None or NoDefaultGiven) then the ensurers and converters would need to be changed from their current str-only functions, which is why that PR is failing.

I guess the real difference is if we want people to test `if "XONSH_SOURCE" in ${...}` or `if $XONSH_SOURCE is None` or `if $XONSH_SOURCE`.

I don't care much before v1.0,  which one we choose to go with but it does seem like having these always be strings is the most robust. :wink:

**Comment by tc21** [comment]
Thanks for your responses. It probably doesn't matter which way an invalid/empty value is indicated, but it might be a good idea to establish a preferred convention. Personally I think it wouldn't be elegant if we had to do `if ${...}.get("VAR_NAME"):`. I'm just wondering, *should* there be a semantic difference between an unset env var and an empty one? It makes sense that they're different, but they'll probably end up meaning the same thing (hence the "should there be an established convention?"). 

This isn't really my area of expertise, just glad I could be of a little help. I really appreciate all of your work.

**Comment by scopatz** [comment]
My view on this is that the defaults are there to provide a semantically meaningful & properly typed value when the variable is otherwise unset. Not saying I am 100% right on this view though, just that this is how the Env class was originally designed.

**Comment by bobhy** [comment]
Let's think about the user here a bit...
When user is constructing a command line, s/he needs to convert everything to string eventually.  In this use-case, it's actually convenient if reference to an undefined variable returns an empty string: no need to slavishly check for existence before referring to the variable and that's great when entering commands interactively.

OTOH, when writing a multi-line script with some flow control, user definitely wants to distinguish undefined from value is empty string, and (in Xonsh) wants to access the native Python type.

But Xonsh is both a programming language and a shell, so you can have it both ways!

How about this? If you refer to `$<environment_variable>, the value is empty string if _<environment_variable>_ is not defined.  This works in python and subproc mode.  But if you refer to `Env["<environment_variable>"]` you get the python value (or raise KeyError).

Then we don't have to be so thoughtful about default values or the design of Env class.

**Comment by bobhy** [comment]
... But Env class is documented as "environment", that creates user expectation that it matches OS environment.  Idea proposed in #3739 to resolve dilemma.

**Comment by scopatz** [comment]
@tc21 - ahh Sorry! I missed your PR.  Let me know when it is no longer a draft

**Comment by anki-code** [comment]
Hi @tc21! Does it still actual after PR?
