### ISSUE TITLE
Make the main page of https://xon.sh/ more delicious

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3706]
Hello! xonsh is my day-by-day shell! It's great! Thank you!

What about to make the xonsh shell landing page more delicious?

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Just want to save here:
![image](https://user-images.githubusercontent.com/1708680/94447866-f61f8780-01b2-11eb-9952-41933125c6e6.png)

**Comment by scopatz** [comment]
Hey @anki-code, thanks for putting these together! Do we have the right to reuse that shell image?

**Comment by anki-code** [comment]
As I see on https://pixabay.com/vectors/conch-shell-sound-beach-ocean-48143/:

![Screenshot_20200930_192707](https://user-images.githubusercontent.com/1708680/94713065-fc4c6a00-0352-11eb-9aa5-9035f00cac55.png)

**Comment by anki-code** [comment]
New concept of the introduction image (it's not 4 images, it's one image with 4 blocks):

![image](https://user-images.githubusercontent.com/1708680/96355885-052d9180-10f0-11eb-8c08-8ddabb92b669.png)

<details>

```
      Xonsh is the shell
      ******************

> cat /etc/passwd | head -n 1

> ls /



      Xonsh is Python
      ***************

$ 2+2

$ json.dumps({"sum": 21+21})




  Xonsh is the shell in Python
  ****************************

$ for i in range(0,10):
      echo -e @(i) | grep 5


  Xonsh is Python in the shell
  ****************************

$ var = 'he' + 'llo'

$ echo @(var) | sed 's/he/a/'
```

</details>

**Comment by scopatz** [comment]
I really like this idea!

**Comment by das-g** [comment]
> New concept of the introduction image (it's not 4 images, it's one image with 4 blocks):
> 
> ![image](https://user-images.githubusercontent.com/1708680/96355954-aae10080-10f0-11eb-9f62-d1bf5a350ae3.png)
> 
> The text:
> 
> To format the text - https://carbon.now.sh
> 
> The code examples should be changed to more beautiful.

Nice! :sparkles: 

For valid syntax, should the claims ("Xonsh is ...") be comments?

**Comment by anki-code** [comment]
@das-g yeah, it should and examples could be more delicious too. Feel free to create more interesting ones using https://carbon.now.sh or similar services.

I think it really could be copy-paste-able html widgets on xonsh landing in the future. Every visit to the main page shows new examples :)

**Comment by anki-code** [comment]
Landing page draft:

![image](https://user-images.githubusercontent.com/1708680/98030302-df0f2d80-1e21-11eb-86fc-e9fa9d3c7641.png)

The code blocks are copy-pastable and could be different if we detect Windows browser for example.

**Comment by scopatz** [comment]
PRs welcome!

**Comment by anki-code** [comment]
New concept:

![xonsh-landing-anki-code-2020-11-28](https://user-images.githubusercontent.com/1708680/100520411-96dbf480-31ae-11eb-92a1-1e392692fada.png)

Here I chosen similar colors with the current "landing page" but make the style more strict.

**Comment by anki-code** [comment]
New version of new concept of the xonsh landing page:

![20201204](https://user-images.githubusercontent.com/1708680/101194882-aa380580-366f-11eb-88c9-c32fe389aa0a.png)

**Comment by anki-code** [comment]
@scopatz @melund @laloch what do you think about this concept? What is missed? What should be changed?

**Comment by anki-code** [comment]
The new xonsh landing page now available to touch - https://xonsh-landing.github.io/ ([source](https://github.com/xonsh-landing/xonsh-landing.github.io))

Feel free to make PRs or replace https://xon.sh @scopatz @gforsyth @laloch @melund.
