### ISSUE TITLE
[Question] Does the "six" library need to be packaged with Xonsh?

### ISSUE THREAD

**Issue by samueldg** [xonsh/xonsh#3722]
(Apologies for hijacking the issues for a question; hopefully this is appropriate.)

Context: I've been maintaining the Xonsh releases on Homebrew for the last few versions, and recently they made a change where resources must be updated manually. (By "resources" I mean all the packages that have to be installed with Xonsh) After 0.9.20 was released today, I was going about updating those extra libraries to their latest version, and I noticed `six` was listed as a dependency for Xonsh:
 
https://github.com/Homebrew/homebrew-core/blob/e27263de442eca4f3cac1e1e560a196e6e249d89/Formula/xonsh.rb#L38-L41

This struck me as surprising, as I haven't seen this in the `setup.py`or anywhere.

So I did a dependency analysis of an installation with the appropriate extras:

```sh
$ poetry add 'xonsh[ptk,pygments,proctitle]'
$ poetry show --tree
xonsh 0.9.20 Python-powered, cross-platform, Unix-gazing shell
├── prompt-toolkit >=2.0
│   └── wcwidth *
├── pygments >=2.2
└── setproctitle *
```

And `six` doesn't show up, unlike the 4 other dependencies which are already resources in the Xonsh formula...

My question is: can I remove this and stop requiring `six`to be installed with Xonsh?

Note that I tried to search for `six` in the code here, and I only found this:

https://github.com/xonsh/xonsh/blob/eb0c3940fcab7e92024e60f2c66aba2d7d802aec/xonsh/ply/test/testcpp.py#L4

which is in a test, so I doubt it is needed for end users, right?

Anyway at this point I'm 96% confident I could remove the dependency on `six` in the Xonsh formula, but better safe than sorry!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hi there @samueldg! Yeah, you are right.  xonsh has never worked on Python 2, and so six has never been a dependency and should be safe to remove.

Also, thanks for maintaining the homebrew recipe!

**Comment by melund** [comment]
six is not needed. I think prompt-toolkit once depended on six, but that is no longer the case 
The dependency has also been removed from the conda package recently: httpss://github.com/conda-forge/prompt_toolkit-feedstock/pull/48

**Comment by samueldg** [comment]
@scopatz @melund Awesome! Thanks to your quick reply, I was able to sneak this into https://github.com/Homebrew/homebrew-core/pull/60250, so Homebrew users won't unnecessarily install `six` anymore.
