### ISSUE TITLE
subproc_captured_stdout in the completer freezes completion and raises "Application is already running"

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3746]
Hello! xonsh is super cool shell! Thank you!

I should run subprocess command inside my completer but I've faced with error (xonsh 0.21).
(I'm trying to support [kislyuk/argcomplete](https://github.com/kislyuk/argcomplete) in [xontrib-argcomplete](https://github.com/anki-code/xontrib-argcomplete))

![image](https://user-images.githubusercontent.com/1708680/92370874-8f530500-f103-11ea-99d2-c5eb2b9e83b2.png)

The code:

<details>

```
def _xontrib_argcomplete_completer(prefix, line, begidx, endidx, ctx):
    if line.startswith('ttt'):
        with __xonsh__.env.swap(_ARGCOMPLETE=2, _ARGCOMPLETE_IFS='\n', COMP_LINE=line, COMP_POINT=begidx):
            result = __xonsh__.subproc_captured_stdout(['bash', '-c', 'echo -e "111\n222\n333"'])

        tokens = set(result.split('\n'))
        return (tokens, len(prefix))

__xonsh__.completers['xontrib_argcomplete'] = _xontrib_argcomplete_completer
__xonsh__.completers.move_to_end('xontrib_argcomplete', last=False)
```

</details>

How I can avoid this error and get the result of subprocess command in the completer?

Thanks!

**Comment by anki-code** [comment]
Workaround 1 - using `subproc_captured_inject` instead of `subproc_captured_stdout`:
```python
def _xontrib_argcomplete_completer(prefix, line, begidx, endidx, ctx):
    if line.startswith('ttt'):
        with ${...}.swap(_ARGCOMPLETE=1, _ARGCOMPLETE_IFS=' ', COMP_LINE='python aaa.py --proto ', COMP_POINT=22, COMP_TYPE=9):
            result = __xonsh__.subproc_captured_inject(['echo', '-e', '111\n222\n333'])    
        tokens = set(result)
        return (tokens, len(prefix))

__xonsh__.completers['xontrib_argcomplete'] = _xontrib_argcomplete_completer
__xonsh__.completers.move_to_end('xontrib_argcomplete', last=False)
```

Workaround 2 - using `subprocess`:
```python
def _SC(cmds, env):
    """
    Run shell command (workaround for https://github.com/xonsh/xonsh/issues/3746)
    """
    proc = subprocess.Popen(cmds, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env, shell=True)
    [out, err] = proc.communicate()
    return (out, err, proc)

def _xontrib_argcomplete_completer(prefix, line, begidx, endidx, ctx):
    if line.startswith('ttt'):
...
        o, e, proc = _SC('echo -e "111\n222\n3333"', env=env)
        tokens = set([t for t in o.decode().split('\n') if prefix in t])
...
```

**Comment by scopatz** [comment]
It would be cool if you could use the Python API of argcomplete so that you could just import it and not have to run a subprocess.

**Comment by anki-code** [comment]
@scopatz there is no python api in argcomplete because the list of completions build by python script and it should be executed with appropriate environment variables. I solve this by workaround 1 in the message above. 
I leaves this issue open because the problem with `subproc_captured_stdout` is actual.
