### ISSUE TITLE
PROMPT: {cwd_dir} should append slash if it isn't empty and doesn't end with a slash

### ISSUE THREAD

**Issue by planet36** [xonsh/xonsh#3751]
## xonfig

<details>

```
$ xonfig info
+------------------+-----------------+
| xonsh            | 0.9.21          |
| Python           | 3.8.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```
</details>

My goal is to use both `{cwd_dir}` and `{cwd_base}` in my prompt, but make `{cwd_base}` a more intense color.

## Expected Behavior

I expect that concatenating `{cwd_dir}` and `{cwd_base}` would be equal to `{cwd}`.

| cwd      | cwd_dir | cwd_base |
|----------|---------|----------|
| ~        |         | ~        |
| ~/code   | ~/      | code     |
| /        | /       |          |
| /usr     | /       | usr      |
| /usr/bin | /usr/   | bin      |

## Current Behavior

Here is what the prompt elements show for various paths.

| cwd      | cwd_dir | cwd_base |
|----------|---------|----------|
| ~        |         | ~        |
| ~/code   | ~       | code     |
| /        | /       |          |
| /usr     | /       | usr      |
| /usr/bin | /usr    | bin      |

**Comment by scopatz** [comment]
Ahh yeah, this is fair.  PRs welcome! Thanks for reporting @planet36!

**Comment by jnoortheen** [comment]
Closing this as the PR is merged already
