### ISSUE TITLE
Can't use winget, the official package manager for windows, in xonsh.

### ISSUE THREAD

**Issue by oxygen-dioxide** [xonsh/xonsh#3752]
## xonfig

<details>

```
+------------------+---------------------+
| xonsh            | 0.9.18              |
| Git SHA          | 26475146            |
| Commit Date      | May 5 06:42:28 2020 |
| Python           | 3.7.6               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.3               |
| shell type       | prompt_toolkit      |
| pygments         | 2.5.2               |
| on posix         | False               |
| on linux         | False               |
| on darwin        | False               |
| on windows       | True                |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | True                |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Expected Behavior

Winget commands successfully run.

## Current Behavior

Winget commands work successfully in cmd, but fail in xonsh
```
For full traceback set: $XONSH_SHOW_TRACEBACK = True
OSError: [Errno 22] Invalid argument: 'C:\\Users\\lin\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe'
```

xonsh (left) and cmd (right)
![image](https://user-images.githubusercontent.com/54425948/92865310-ba559580-f430-11ea-9f0a-f32411b6fb0b.png)

### Traceback
<details>

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 17776, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 2942, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 22658, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 22579, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured)
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 22532, in cmds_to_specs
    spec = SubprocSpec.build(cmd, captured=captured)
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 22300, in build
    spec.resolve_executable_commands()
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 22375, in resolve_executable_commands
    self.cmd = get_script_subproc_command(self.binary_loc, self.cmd[1:])
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 21863, in get_script_subproc_command
    elif _is_binary(fname):
  File "E:\anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 21825, in _is_binary
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\lin\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe'
```

</details>

## Steps to Reproduce

1. Download and install [winget](https://github.com/microsoft/winget-cli/releases)
2. Run any winget command in xonsh. For example, "winget install deepvocal", or "winget search browser"

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

[I have created an issue in the winget repo](https://github.com/microsoft/winget-cli/issues/565)

**Comment by oxygen-dioxide** [comment]
To temporarily solve this problem, run this command in an elevated xonsh:

```
echo @winget %* > C:\Windows\System32\wg.bat
```

Then you can use "wg" command instead of "winget".

**Comment by scopatz** [comment]
Hey there @oxygen-dioxide - A couple of things: Does `C:\\Users\\lin\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe` actually exist on your filesystem?  Also could you please upgrade xonsh to 0.9.21 and see if this is still happening? Thanks!

**Comment by oxygen-dioxide** [comment]
1. Yes, "C:\\Users\\lin\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe" exists.
![image](https://user-images.githubusercontent.com/54425948/93335562-39940080-f859-11ea-8be8-70ec7a95d3ca.png)

2. After I upgraded to xonsh 0.9.21, winget still failed to work in xonsh

**Comment by scopatz** [comment]
What do `__xonsh__.commands_cache.get('winget')` and `__xonsh__.commands_cache.get('winget.exe')` return?

**Comment by oxygen-dioxide** [comment]
```
lin@LAPTOP-K4JTR2V5 ~\Desktop $ __xonsh__.commands_cache.get('winget')
('C:\\Users\\lin\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe', None)
lin@LAPTOP-K4JTR2V5 ~\Desktop $ __xonsh__.commands_cache.get('winget.exe')
('C:\\Users\\lin\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe', None)
```

**Comment by melund** [comment]
I think I have seen something similar with with other WindowsApps. They are not real exe files. They are shims created by windows with zero file size. 

![image](https://user-images.githubusercontent.com/1038978/93427549-472fa180-f8be-11ea-98e7-89a2768d476a.png)

So it fails when we inspect them with `_is_binary()`. If we could find a way to detect those kind of exe files we probably work around the problem. Can you fix that @oxygen-dioxide ?

**Comment by oxygen-dioxide** [comment]
Sorry, I am a amateur python user. I'm not able to fix this issue.

**Comment by melund** [comment]
I don't know how we can detect these App Execution aliases.  They show up when running `os.listdir()` and they can be used as arguments to `popen` (esentially `CreateProcess` resolves them). But we can't open them and `os.path.exists()` returns false.

**Comment by melund** [comment]
@xonsh/xore   Ouch. I just accidentally pushed my fix to this issue directly to master :( VSCode is dangerous that way.

I am quite sure it works, but I will still let one of you roll it back so we can do a proper PR. Sorry. It is late here.

**Comment by scopatz** [comment]
> They are not real exe files. They are shims created by windows with zero file size. 

Are they basically symbolic links?  It seems like we need to find a way to support these. That is pretty weird though! Thanks for tracking this down @melund

**Comment by scopatz** [comment]
Should this be closed?

**Comment by melund** [comment]
Sort of symbolic links. At least the CreateProcess API on windows knows how to handle them. But I can't find much info about them. They seem very unsupported by python. I can't stat them for example. They are a way the windows store apps can be launched from the command line and the can be individually enabled/disabled in Windows settings. 

Let @oxygen-dioxide test it before we close the issue. Thanks a lot @scopatz

**Comment by oxygen-dioxide** [comment]
Now I can use winget in xonsh. Thanks.
