### ISSUE TITLE
use via cygwin

### ISSUE THREAD

**Issue by wendellwt** [xonsh/xonsh#3756]
xonsh does not operate on windows via cygwin.  It installs via pip, and on startup the prompt shows up.  However, typical Unix commands either get permission denied or hang the terminal, as in:
```
$ ls
xonsh: subprocess mode: permission denied: ls
$ /usr/bin/ls
a_file  notes.txt
<terminal hangs>
```
Q: if one were to try to diagnose this in the source code, where would one start to look?  What environment variables/settings are useful for debugging xonsh itself?

**Comment by wendellwt** [comment]
Well, it turns out that there were two issues:
1) in `get_script_subproc_command()` in `built_ins.py`, the cygwin version of `os.access()` doesn't check the PATH.  This is my workaround:
```
    # make sure file is executable
    if not os.access(fname, os.X_OK):
        # explicitly look at all PATH entries for cmd
        wt_path = os.getenv("PATH").split(':')
        wt_fpath = list(map(lambda p: p + os.sep + fname,wt_path))
        if not any(list(map(lambda p: os.access(p,os.X_OK), wt_fpath))):
            raise PermissionError

```
2) in `iterraw()` in `proc.py`, at line 2036, the `proc.wait()` never returned; removing it allowed the command to complete:
```
        self.stream_stderr(safe_readlines(stderr))
        # wt: proc.wait()   # <<<<<<<<<<<<<<< HELP
        self._endtime()

```
I have no idea if removing the proc.wait() causes other problems, but it allows the cygwin version to work.

**Comment by scopatz** [comment]
> Q: if one were to try to diagnose this in the source code, where would one start to look? What environment variables/settings are useful for debugging xonsh itself?

You can set `XONSH_DEBUG` to get more info: https://xon.sh/envvars.html#xonsh-debug

**Comment by scopatz** [comment]
You probably do need to wait for the process to end.  But maybe we could pass on that if in cygwin.  @wendellwt - would you be willing to put in a couple of PRs for these?
