### ISSUE TITLE
On Windows, xonsh can't find executables that are in my PATH

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#3763]
## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.21                                                |
| Python           | 3.8.5                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 3.0.7                                                 |
| shell type       | prompt_toolkit                                        |
| pygments         | 2.6.1                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000022DBFC6DDF0> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000022DBFC7D070> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Expected Behavior
It should execute the executable in the path.

## Current Behavior

It says it can't find it:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\xonsh\built_ins.py", line 561, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\xonsh\proc.py", line 584, in __init__
    self.proc = proc = subprocess.Popen(
  File "c:\program files\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\program files\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\xonsh\proc.py", line 1889, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\xonsh\built_ins.py", line 550, in run
    p = self._run_binary(kwargs)
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\xonsh\built_ins.py", line 577, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: rg
Did you mean one of the following?
    fg:  Alias
    bg:  Alias
    rd:  Alias
    d:   Alias
    j:   Alias

```

The above is an example with ripgrep (rg). I confirmed it is in my PATH. In fact, the text even changes color when I type 'rg' which shows that xonsh is recognizing this as a valid command in the path.

Some other relevant details:

I recently upgraded from Python 3.7 to 3.8, as well as the Xonsh version from 0.8.x to 0.9.21. It was working fine prior to those changes. There seem to be other issues associated with this change - I'll file separate bugs for them.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Does it find `rg.exe`?

**Comment by beetleb** [comment]
> Does it find `rg.exe`?

No. Like with `rg`, it will change the color indicating it does recognize it, but when I hit Enter, I get a "command not found".

**Comment by melund** [comment]
I can't reproduce this. @beetleb can you try with the newest version released yesterday?

**Comment by auneri** [comment]
Hello, I'm also experiencing this behavior with all versions >0.9.18 (downgrading to 0.9.18 solves it).
```python
$PATH.insert(0, 'C:\\path\\to\\executable')  # prepend to PATH
print($PATH[0])  # confirm insertion
executable  # fails with "command not found"
```

**Comment by beetleb** [comment]
> 
> 
> I can't reproduce this. @beetleb can you try with the newest version released yesterday?

I tried with 0.9.22 and the problem remains.

**Comment by melund** [comment]
I can't reproduce any your errors @beetleb and @auneri

**Comment by melund** [comment]
Let me see your $PATH variable and also  try to run `which -v -s rg`

**Comment by beetleb** [comment]
> 
> 
> Let me see your $PATH variable and also try to run `which -v -s rg`

Does `which` work in Windows?

**Comment by melund** [comment]
It is xonsh' implementation of which I was referring to

**Comment by melund** [comment]
Xonsh has its own version of which

**Comment by auneri** [comment]
When the executable is not in path:
```
> which -v -s ipython
ipython not in $PATH
subprocess.CalledProcessError: Command '['which', '-v', '-s', 'ipython']' returned non-zero exit status 1.
```
Note the different error message when it is in path:
```
> $PATH.insert(0, r'C:\path\to\ipython')
> which -v -s ipython
C:\path\to\ipython.exe (from PATH element 0)
> ipython
xonsh: subprocess mode: command not found: ipython
subprocess.CalledProcessError: Command '['ipython']' returned non-zero exit status 1.
```

**Comment by auneri** [comment]
Note that I get suggestions only when I specify the executable with its suffix. The first suggestion is the one I just added to path.
```
> $PATH.insert(0, r'C:\Users\auneri1\Miniconda3\envs\py37\Scripts')
> ipython.exe
xonsh: subprocess mode: command not found: ipython.exe
Did you mean one of the following?
    ipython.exe:   Command (C:\Users\auneri1\Miniconda3\envs\py37\Scripts\ipython.exe)
    python.exe:    Command (C:\Users\auneri1\Miniconda3\envs\shell2\python.exe)
    ipython3.exe:  Command (C:\Users\auneri1\Miniconda3\envs\py37\Scripts\ipython3.exe)
    pythonw.exe:   Command (C:\Users\auneri1\Miniconda3\envs\shell2\pythonw.exe)
subprocess.CalledProcessError: Command '['ipython.exe']' returned non-zero exit status 1.
```

**Comment by melund** [comment]
This is very weird. When I call `which` I don't get a `CalledProcessError`. Can you try to start xonsh with the standard configuration and see if that makes a difference ` xonsh --no-rc`

**Comment by auneri** [comment]
I activated my dedicated environment for `xonsh` and started it with `xonsh --no-rc`... same response.

I should reiterate this started happened with v0.9.19. I have another environment with v0.9.18 that works just fine.

**Comment by melund** [comment]
Do you mind trying out 0.9.22, or the master branch on github?

**Comment by auneri** [comment]
I tried every version up to master (via conda-forge). No difference.

I just tried master branch (via pip, per instructions). Only difference is the output I get when I specify the executable with `.exe` extension. Compared to the previous output, the suggested paths are not shown. Note that `which` still finds it in `PATH`.
```
> ipython.exe
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: ipython.exe
Did you mean one of the following?
    PYTHON.EXE:    Command (PYTHON.EXE)
    IPYTHON.EXE:   Command (IPYTHON.EXE)
    PYTHONW.EXE:   Command (PYTHONW.EXE)
    IPYTHON3.EXE:  Command (IPYTHON3.EXE)
```

**Comment by melund** [comment]
Can you try to set the following before stating xonsh
```
set XONSH_DEBUG=1
set XONSH_SHOW_TRACEBACK=1
```

Then post the traceback you get when starting a command

**Comment by auneri** [comment]
Here is the traceback for v0.9.22:
```
> ipython
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\auneri1\Miniconda3\envs\shell2\lib\site-packages\xonsh\built_ins.py", line 571, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "C:\Users\auneri1\Miniconda3\envs\shell2\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\auneri1\Miniconda3\envs\shell2\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\auneri1\Miniconda3\envs\shell2\lib\site-packages\xonsh\proc.py", line 1889, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "C:\Users\auneri1\Miniconda3\envs\shell2\lib\site-packages\xonsh\built_ins.py", line 560, in run
    p = self._run_binary(kwargs)
  File "C:\Users\auneri1\Miniconda3\envs\shell2\lib\site-packages\xonsh\built_ins.py", line 587, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: ipython
```

**Comment by auneri** [comment]
Let me know if there is anything I can do to expedite the process.
I can dig into the code and pointers on likely culprits would be very helpful.

**Comment by scopatz** [comment]
Hi @auneri - yeah, @melund is really the main xore developer for windows.  But I am happy to review & merge any PRs that come through.  If you could dig into the code to figure this out that would be super helpful!

**Comment by melund** [comment]
Sorry. I am so tied up in other matters at the moment and I couldn't reproduce this. 

If this is common issue for many users it is if course serious. If you could debug down to the subprocess we may be able to compare with my machine. Maybe there is problem with some of your environment variables which cause it to miss behave.

**Comment by auneri** [comment]
An interesting observation: `$UPDATE_OS_ENVIRON = True` followed by `$PATH = $PATH` solves the error with the minimal snippet [I shared above](https://github.com/xonsh/xonsh/issues/3763#issuecomment-695022034). After these two lines, `xonsh` seems to locate executables in directories that are added to `PATH`.

Hopefully this workaround can shed some light on the actual problem, as I don't observe it to be a robust solution. For example, one issue that remains for me is finding `python`. Similar to the above example:

```
> $PATH.insert(0, r'C:\Users\auneri1\Miniconda3\envs\py37')
> which python
C:\Users\auneri1\Miniconda3\envs\py37\python.exe  # expected
> python -c "import sys; print(sys.executable)"
C:\Users\auneri1\Miniconda3\envs\shell\python.exe  # unexpected
```

This is the Python executable that is in the same environment as `xonsh`. It is not explicitly listed in `$PATH`, yet it always takes precedence.

**Comment by scopatz** [comment]
What is the output of `which -v python`?

**Comment by auneri** [comment]
```
> which -v python
C:\Users\auneri1\Miniconda3\envs\py37\python.exe (from PATH element 0)
```
Output of `where` is also the same. The path for that other Python is not in my environment variable; it is however in the environment that contains `xonsh`.

**Comment by beetleb** [comment]
I did confirm that setting `OS_UPDATE_ENVIRON` to True fixed this for me.

**Comment by anki-code** [comment]
Hello! I may be wrong and this is unrelated to this issue but want to remind that in commands cache the command in Windows [is going to cache in upper case](https://github.com/xonsh/xonsh/blob/0f9f74bfdac89b357491f6c2ce69698c732abed6/xonsh/commands_cache.py#L117). May be try to run `RG` or `RG.EXE`?

**Comment by auneri** [comment]
Setting `UPDATE_OS_ENVIRON` covers a number of cases, but at least the [issue in finding the correct python](https://github.com/xonsh/xonsh/issues/3763#issuecomment-705586333) remains.

@anki-code Changing casing had no impact; one still has to set `UPDATE_OS_ENVIRON` and it does not address my other case.

**Comment by auneri** [comment]
Hello, just wanted to ping this. My issue [stated above](https://github.com/xonsh/xonsh/issues/3763#issuecomment-705586333) still remains, which has me stuck at v0.9.18.

Unfortunately I wasn't able to dig too much in the code. I did test on fresh environments and different machines and all I can say is that this behavior was introduced by changes in v0.9.19.

**Comment by auneri** [comment]
I think I have been able to pinpoint the problem -- seems to be related to [subprocess PATH semantics and portability](https://bugs.python.org/issue8557).

I was able to get things working by modifying `self.cmd` [here](https://github.com/xonsh/xonsh/blob/0.9.25/xonsh/procs/specs.py#L462) before using it as follows:

```python
if xp.ON_WINDOWS:
    from io import StringIO
    from xonsh.xoreutils.which import which
    out = StringIO()
    if which(self.cmd[:1], stdout=out) > 0:
        raise FileNotFoundError
    self.cmd[0] = out.getvalue().strip()
```

I'm not sure if this is cleanest implementation, but I wanted to reuse xonsh's own functionality.

Note that this fix avoids the need to set `UPDATE_OS_ENVIRON=True` and works for all executables including `python`.

**Comment by eugenesvk** [comment]
I have the same issue, where `which` can find an executable, but running it directly can't find it, although adding it to `PATH` via `environ['PATH'] += ';/path/to/myexe/'` instead of using the `$PATH.add` works.
The suggested fix to the `self.cmd` also seems to be working with `XONSH_DEBUG=1`
Using the latest 0.9.27 version
