### ISSUE TITLE
Is there an event to change command or execute another command?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3767]
Hi! xonsh is amazing! Thanks!

I've read about `on_precommand` and `on_transform_command` events and wondering is there a way to change command or execute another command?

###  For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hi @anki-code - this is what aliases are for :wink: https://xon.sh/tutorial.html#aliases You would write something like

```py
aliases["uname"] = "echo uname"
```

**Comment by anki-code** [comment]
@scopatz aliases are cool! I'm using it and big thanks!

But in this case I'm talking about catching and modifying any command. For example I want to catch any command that contains only path and do different command with this path:
```bash
$ /
# run: ls /
bin cdrom dev ...

$ ~/home/.xonshrc
# run: cat ~/home/.xonshrc
xonsh='cool' ...

$ ~/Downloads/file.tar.gz
# run: als ~/Downloads/file.tar.gz
file_in_arch1 file_in_arch2 file_in_arch3 ...
```
Do you understand? )

**Comment by scopatz** [comment]
Ahh yeah, you want something like: https://xon.sh/events.html#event-categories but for all commands, like just an `on_pre_spec_run` event. That would need to be added

**Comment by anki-code** [comment]
Solved by using [on_precommand](https://xon.sh/events.html#on-precommand)
