### ISSUE TITLE
Change the main page to sphinx back

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3771]
Hello! Xonsh is great!

Current xon.sh page with shells pictures looks funny but there is a lack of information. I think the previous sphinx page looks better.

All I suggest for the old page is to remove "Try it now!" section to accelerate installations and avoid misleading screenshot with code. If you're ok with it I can prepare a PR to remove section.

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hi @anki-code - Lot's of projects have a landing page and this is something we have wanted to have for a long time (it is on the 1.0 roadmap, #3234). I think we are open to any and all improvements to this page, but don't want to remove it yet.  Thoughts from other people on @xonsh/xore?

**Comment by anki-code** [comment]
Current version of landing looks very very far from old page. I think it will take much time to improve it. Also old sphinx page looks strong and serious instead of new. I suggest use old page until the new will become stronger.

**Comment by anki-code** [comment]
Thanks to all xore for very interesting discussion here. Closed.

**Comment by anki-code** [comment]
Just want to be understandable.

I expect that xonsh is shell. Shell is not a toy is a core tool.

If I try to explain [like designer in Silicon Valley series](https://www.youtube.com/watch?v=V3jxWCJUPQQ) then

1. How I expect that xonsh should look in the visual materials:

![Screenshot_20201008_010037](https://user-images.githubusercontent.com/1708680/95392619-b880d400-0901-11eb-9136-6fce07e41b86.png)

2. How it looks on the current version of landing in my opinion:

![Screenshot_20201008_005845](https://user-images.githubusercontent.com/1708680/95392450-748dcf00-0901-11eb-96e8-4c314ca77f3e.png)

So I believe that if the community haven't time to design let's just do black text on white background and the [conch image](https://github.com/xonsh/xonsh/issues/3706#issuecomment-700056485).
