### ISSUE TITLE
Support multiline prompt in ptk completer

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3775]
Hello! xonsh is the best shell! Thanks!

By default I have only 2 lines when [xontrib-prompt-bar](https://github.com/anki-code/xontrib-prompt-bar) at the end of console window:

![Screenshot_20200917_230746](https://user-images.githubusercontent.com/1708680/93522735-9adfd080-f93a-11ea-8f66-5d1f832c5dfe.png)

Here is no support for multiline prompt:
https://github.com/xonsh/xonsh/blob/40352638bf6b01d308538b4a32e995bb68913a6c/xonsh/ptk_shell/completer.py#L118-L123

As result:
```
Count of lines in completer = ($COMPLETIONS_MENU_ROWS - LINES_IN_PROMPT - 1) = (5 - 2 - 1) = 2 
```

Workaround: increase `$COMPLETIONS_MENU_ROWS`.

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
@bobhy I see that you have many commits related to prompt-toolkit. May be you can advice how to increase count of lines in xonsh?

**Comment by scopatz** [comment]
Yeah, I think this stopped working at some point.  The default should be 5, https://xon.sh/envvars.html#completions-menu-rows.  It might need a deeper fix

**Comment by bobhy** [comment]
I haven't been here long enough to know whether this is a change from prior behavior.  I'm not sure it's a bug.
2 observations:
* multiline is not completely broken.  If you start at the top of the screen and display completions, you will get the full 5 lines, as expected.  
* But if you're down to the last line of the buffer and display completions, ptk displays fewer lines.  I think the code you found is trying to show however many lines it can without scrolling the display,  When I disabled it and ran from the last line of the screen, I found ptk only displays one one completion at a time, so it's doing *something* useful.

What would you like Xonsh to do at the bottom of the screen?  Always scroll up the full $COMPLETIONS_MENU_ROWS number of lines?

**Comment by anki-code** [comment]
@bobhy Yeah, it was I expected.

**Comment by scopatz** [comment]
> Always scroll up the full $COMPLETIONS_MENU_ROWS number of lines?

Yeah, it used to do this a few years ago
