### ISSUE TITLE
if leftmost is alias, use subproc mode

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#378]
This is an idea that I forget where it came up, but would solve the problem where

```python
f = lambda args, stdin=None: print(args)
f /home/me/file
```

on the second line this goes into python mode because `f/home` is a valid python expression.  I think it also might be a nice idea to have every callable alias get an `is_alias` attribute added to it when it is added to `aliases`.  This could also be a nice place to wrap functions to ensure that they take consistent arguments. Don't know if this should target 0.2 or not.

**Comment by scopatz** [comment]
given that @(f) can now take callables, I vote that we close this issue in favor of the more explicit syntax. Any objections?

**Comment by gforsyth** [comment]
No objections.
