### ISSUE TITLE
Force import file without .xsh extension, with /usr/bin/env xonsh shebang, containing xonsh code

### ISSUE THREAD

**Issue by shadowrylander** [xonsh/xonsh#3783]
## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.19          |
| Python           | 3.8.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.6           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | nixos           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

```

</details>

## Expected Behavior

More of a feature request, if such as feature doesn't already exist in `xonsh`.

The shell should theoretically import `xonsh` code if the associated file uses either a `.xsh` extension, or a shebang leading to the `xonsh` binary. Examples include sourcing secrets (potentially with the `.sec` extension) such as passwords, in `xonsh` environment variables.

## Current Behavior

`RunTimeError: attempting to source non-xonsh file! [...]`

**Thank you kindly for the help!**

**Comment by anki-code** [comment]
Looks like there is no checking shebang:

https://github.com/xonsh/xonsh/blob/a8d4a57f01a25b1ce77f0a3adec1c0b11f49ad1a/xonsh/aliases.py#L566-L572

PRs are welcome!

**Comment by anki-code** [comment]
May be the better way is to have `--force` mode in `source` util to avoid checking shebang and just sourcing the files as is.

**Comment by shadowrylander** [comment]
I was thinking the same thing; I'm assuming a force option already exists?

**Comment by anki-code** [comment]
No because `source` command in xonsh works like in bash: every argument passed to the sourced file into $ARGS.

I think the best and easy way to you is to add environment variable called `XONSH_SOURCE_CHECK_EXT`, It will be True by default and could be switched to False.

**Comment by anki-code** [comment]
This feature looks easy:
```
if env.get("XONSH_SOURCE_CHECK_EXT"):
    if fext and fext != ".xsh" and fext != ".py":
```
+ new environment variable description like here  - https://github.com/xonsh/xonsh/pull/3462/files

**Comment by shadowrylander** [comment]
Right; I'll see to it!

**Comment by anki-code** [comment]
@shadowrylander please close this issue if you don't plan to make PR soon because the answer of how it could be achieved is above.

**Comment by shadowrylander** [comment]
Ah; yes, I overestimated how much time I actually have. Thanks for the reminder!

**Comment by scopatz** [comment]
Hi there, no need to ask specific people for PRs, in my opinion.

**Comment by shadowrylander** [comment]
Regarding which one of us? 😅

**Comment by anki-code** [comment]
It's to me. Ok, got it.

**Comment by scopatz** [comment]
Yeah, I think it better just to say that it would very welcome if I PR were made, so that anyone who comes along in the future knows that it is OK to put in a PR
