### ISSUE TITLE
Capturing subprocess stdout without stderr

### ISSUE THREAD

**Issue by ajeetdsouza** [xonsh/xonsh#3786]
Suppose I try to `ls` in a directory without proper permissions in Bash:

```bash
> result=$(ls)
ls: cannot open directory '.': Permission denied
```

The command fails, and stderr is printed directly to the console. However, in xonsh, the same code silently fails:

```
> result=$(ls)
> result
''
```

Is there a way to capture only stdout, so that errors show up immediately? I did see `!()`, but using that means we lose out on colored output in the error messages from a lot of programs.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Workaround: `result = $(ls | head)`
I don't clearly understand how it works but in this case you will get the stdout in `result` and colored errors in stderr.

**Comment by ajeetdsouza** [comment]
@anki-code piping to cat does solve the problem, but it messes with exit code, so I can't really use it. Is there any other way of doing this?

> The title of issue is misleading. It could be like "Add colors to captured stderr"

xonsh is not removing colors from stderr, the program is.

Most programs, only print ANSI sequences (colors) if they are printing to a terminal (i.e. `isatty`). Since xonsh is capturing stderr and not printing it to the terminal, the program chooses not to use colors. IMO, the solution here is not to trick the program into thinking the captured output is going to a terminal (that will cause other issues); it's to not redirect `stderr` at all (which most shells do), so it goes directly to the terminal.

**Comment by scopatz** [comment]
Ahh yeah, this is probably a bug/oversight.  Though I would argue that this is sort of undefined behaviour.  @anki-code is right that this issue is that it is because when capturing, the last-command-in-the-pipeline is being used and does not go through the normal iteration of line printing. Happy to review PRs / fixes for this.
