### ISSUE TITLE
Feature request: exit 1 should work

### ISSUE THREAD

**Issue by Anonym-User-426** [xonsh/xonsh#3794]
Currently the commands "exit 0" or "exit 1" don't do anything.
It would be nice if it would do the same as "sys.exit(0/1)" to make it easier and faster to convert a bash script to xonsh.

**Comment by anki-code** [comment]
We can also use short import:
```python
from sys import exit
# ...
exit(1)
```

**Comment by anki-code** [comment]
After merging #3797 you can just call `exit(0/1)`.

**Comment by anki-code** [comment]
@Anonym-User-426 now you can update xonsh from master and try exit:
```bash
pip install -U git+https://github.com/xonsh/xonsh
echo 'exit(42)' | xonsh
_.rtn
# 42
```
