### ISSUE TITLE
Update old page "Wishlist & To-Dos"

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3806]
Hi! Xonsh is the one small step for a slug and one giant leap for mankind. Thanks for this!

I noticed that "[Wishlist & To-Dos](https://xon.sh/todo.html)" page looks old and not actual.

> Tab completion from man pages

Supported.

> urwid based command prompt

This is still look as a good solution? I don't think.

>    Support for Python 2.7

Not needed.

> Support for future versions of Python

Supported. Thanks to the xore!

> Testing on Mac OSX

Step by step. Issue by issue. Release by release. No special.

So may be we delete the page?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hey @anki-code - thanks, yeah I think this page should be updated, rather than removed.

**Comment by anki-code** [comment]
Not actual like described in or above.
