### ISSUE TITLE
Add preview image to the xonsh/xonsh repo

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3821]
Hi! Xonsh is super cool! Thanks for this!

@scopatz could you please open the repo settings and add "Social preview" to improve xonsh`s Github Topics section?

![image](https://user-images.githubusercontent.com/1708680/94846222-751df580-0429-11eb-8e80-ee1e663cd9cc.png)

For example you could [use my drafts](https://github.com/xonsh/xonsh/issues/3706#issuecomment-700056485). I've made simple high resolution Github-ready image:

![image](https://user-images.githubusercontent.com/1708680/94846953-a4813200-042a-11eb-96d6-f783b0151759.png)

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @anki-code -- this seems fine with me, and I note from your linked issue that the conch image is permissively licensed, so we can go ahead and stick it into that "social preview" section

**Comment by gforsyth** [comment]
Thanks, @anki-code, for the image!  I've added it to our social preview.
