### ISSUE TITLE
autocompletion - show description of flags

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3823]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.22               |
| Git SHA          | 00a42e01             |
| Commit Date      | Sep 18 19:57:59 2020 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.3                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
+------------------+----------------------+

```

</details>

## Current Behavior

as of now the autocompletion menu looks like this
![image](https://user-images.githubusercontent.com/6702219/94892537-87884580-04a2-11eb-8b9d-bf8dec891134.png)

## Expected Behavior

it is hardly usable. we can benefit from the suggestions only if we know what each option do. For that we need to check the manual or help page. Is it possible to show the description along with the flags ? like here
![1527157317-cli-autocomplete-launch-blog](https://user-images.githubusercontent.com/6702219/94892586-aedf1280-04a2-11eb-87d3-b81d66af1cb3.gif)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
I also think about it and found that in jedi xontrib there is a code to show description:
![Screenshot_20201002_101308](https://user-images.githubusercontent.com/1708680/94897253-e8f6e700-0497-11eb-8bf3-eaece65e8acf.png)

**Comment by jnoortheen** [comment]
that looks like a good start. I will check there.

**Comment by jnoortheen** [comment]
with the inclusion of fish-shell based completer, now most of the completions have description as well. Also now the default aliases show descriptions during auto-completion
