### ISSUE TITLE
NO_COLOR and RESET are not the same

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3827]
## xonfig

<details>

```
+------------------+---------------------+
| xonsh            | 0.9.22.dev166       |
| Git SHA          | 42e1c85e            |
| Commit Date      | Oct 2 17:41:59 2020 |
| Python           | 3.8.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.3               |
| shell type       | prompt_toolkit      |
| pygments         | 2.7.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | manjaro             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| on jupyter       | False               |
| jupyter kernel   | None                |
+------------------+---------------------+

```

</details>

## Expected Behavior

using `RESET` should reset color as well as background . But only color is reset. While NO_COLOR resets both.

## Steps to Reproduce

using from master branch

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hmm they should be exactly the same... That seems odd. CC @cafehaine

**Comment by cafehaine** [comment]
yup, only `DEFAULT` resets the color without the attributes, at least during my testing with readline.

I might have missed something while testing with PTK as the behavior is already different

**Comment by cafehaine** [comment]
![image](https://user-images.githubusercontent.com/11913365/95167933-c7a43c80-07b0-11eb-9927-48f027238cf4.png)
I'm observing the opposite of what you're describing, but this still is a differing behavior that should be fixed.
