### ISSUE TITLE
Add topics to xonsh/xonsh repository

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3829]
Hello! xonsh is inspiring!

xonsh/xonsh repository has `xonsh` and `python` topics. Please add new topics:
* `prompt` - xonsh repo will be on the first page by this topic
* `shell` -  xonsh repo will be on the second page by this topic
* `cli` (command line interface) -  xonsh repo will be on the second page by this topic
* `command-line ` -  xonsh repo will be on the second page by this topic

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Done.  Thanks for all the marketing tips, @anki-code !

**Comment by anki-code** [comment]
@gforsyth I also suggest to change repo image to clean contrast squared conch:
![image](https://user-images.githubusercontent.com/1708680/94995410-c4d5fb80-05a6-11eb-9008-a2c4c1214a3b.png)

**Comment by anki-code** [comment]
@scopatz please take a look at this list also please.
