### ISSUE TITLE
PTK completion prefix matching is broken

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#3833]
I believe #3774 had a few unintended side-effects (and also laid out that we probably need more completion tests).

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.22.dev165        |
| Git SHA          | 580b675f             |
| Commit Date      | Sep 30 19:48:13 2020 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.7                |
| shell type       | prompt_toolkit       |
| pygments         | 2.6.1                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
+------------------+----------------------+
```

</details>

## Expected Behavior
When completing available options, we should insert the entirety of the matching prefix of all available options, nothing more.

E.g. if I have this folder structure:

```
dask/
  dask/
  distributed/
```

and I type

```
cd dask/<TAB>
```

it should fill in the common `d` and then stop.

## Current Behavior

In the above, when I type `cd dask/<TAB>` it autoselects `dask/dask`

## Steps to Reproduce

```
mkdir -p dask/dask dask/distributed
cd dask/<TAB>
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Potential fix in  #3835

**Comment by scopatz** [comment]
Sorry I got the number wrong

**Comment by scopatz** [comment]
Hmm should we revert #3774 then? CC @bobhy

**Comment by bobhy** [comment]
Arrgh, late to the party, as always!
@scopatz, @gforsyth , I think both behaviors are valid, so we need a configurable option to select which.  I'll redo #3774 with an option, but it will be off by default.

**Comment by gforsyth** [comment]
Sounds great, @bobhy -- thanks for taking this on!
