### ISSUE TITLE
Github repository improvements

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3838]
Hi! xonsh is straight forward shell! Thank you for this!

I suggest to improve the Github repository:

1. Change organization image to clean contrast squared conch. I prepared this:
![image](https://user-images.githubusercontent.com/1708680/94995410-c4d5fb80-05a6-11eb-9008-a2c4c1214a3b.png)

2. Change organization description from "A general purpose, Python-ish shell" 
  * to "Python-powered, cross-platform, Unix-gazing shell." 
  * or "Python-powered shell." 

    It's more clear.

3. Remove "Under the sea" location - it's funny but have negative connotation with "out of history"/"not actual".

4. Add `xontrib-cookiecutter` repo to "Pinned repositories" becase there is a place there and it helps to promote this a bit.

5. Add 🐚 emoji to the xonsh/xonsh repo description (e.g. "🐚 Python-powered, cross-platform, Unix-gazing shell") - it helps to make a bit more attention when someone star the repo or use description somewhere.

6. Click About settings and disable "Packages" because it is unused section.

7. Disable Wiki on Github because we have docs and no one update the github wiki. If someone want to create cheat sheet or awesome xontrib list the best way for this is to create repository - thus community will grow. At this time Github Wiki is the dead end. 

 * UPD: PR to move wish list #3841

8. Disable Projects because it's unused.

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
1. I would prefer to have a larger community discussion around the logo. 
2. Done
3. I don't understand the objection here. Could you explain?
4. Done.
5. Done.
6. Isn't it used?
7. I am OK with leaving the wishlist
8. Is it a problem to keep it? I can see people using the projects in the future.

**Comment by anki-code** [comment]
> 1. I would prefer to have a larger community discussion around the logo.

I just suggest to set this image because it's more clear then current and then we will go to discuss  🍻 :) 

> 2. Done

I still see old text. 

> 3. I don't understand the objection here. Could you explain?

Make the description more strict, less funny. I understand that most of docs has a bit of sea rhetoric but on github it looks a bit too much and should be more strict to make first impression to admins/devops/devs.

> 6. Isn't it used?

Yeah:
![Screenshot_20201007_002347](https://user-images.githubusercontent.com/1708680/95261626-683b4080-0833-11eb-97b2-e69c904e3ec2.png)

> 8. Is it a problem to keep it? I can see people using the projects in the future

Ok, let's keep. It's just an another link to dead end in github UI.

**Comment by scopatz** [comment]
2. Oh I see, you mean the org, not the repo.  It should be fixed now

**Comment by anki-code** [comment]
Thanks!
