### ISSUE TITLE
print_color raises exception from RC file

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3840]
Hi! Xonsh is super incredible! Thanks!

I've found that `print_color` not working when it used in rc-file:
```bash
# bash
cd /tmp
echo 'from xonsh.tools import print_color' > rc
echo 'print_color("{RED}Hello!")' >> rc
XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=1 xonsh --rc rc
```
Result:
```
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/environ.py", line 2245, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "rc", line 3, in <module>
    print_color('{RED}123')
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/tools.py", line 1783, in print_color
    builtins.__xonsh__.shell.shell.print_color(string, **kwargs)
AttributeError: 'NoneType' object has no attribute 'shell'
```

For example `aliases.py` contain `print_color` and could fail from rc.

It's on current master - `580b675f` (Oct 1 02:48:13 2020).

Please fix. Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
@scopatz it could be regress and related to THREAD_SUBPROC again because the last suspicious commit is ["THREAD_SUBPROCS=None for xonshrc files"](https://github.com/xonsh/xonsh/commit/22610f48d64b1ca7136babd8ab894cc5e6798987).

**Comment by scopatz** [comment]
That would be weird if it is related to THREAD_SUBPROCS.  In general, though I would not expect that `print_color()` to work until xonsh is fully started up. There may be some changes that could be made to use the ASCII printing prior to the shell being fully available as sort of a hack to get this working when xonshrc is run.
