### ISSUE TITLE
Object converts to string when xonsh runs from xonsh

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3846]
Hi! I've found a old new creature in the consh spirals!

For example we store the `dict` to the environment variable and then want to run xonsh from xonsh:
```bash
# bash
cd /tmp
echo 'if 'QWE' not in ${...}:' > rc
echo '   $QWE = {"dict":"1"}' >> rc
echo 'print(repr($QWE))' >> rc
echo 'print(type($QWE))' >> rc

xonsh --rc rc  # run xonsh
# {'dict': '1'}
# <class 'dict'>

xonsh --rc rc  # run xonsh from xonsh
# "{'dict': '1'}"
# <class 'str'>
```
Wow! Our `dict` in the second xonsh becomes `str` and our xonshrc or xontrib will crashed in common case.

I understand why it works like this. Because the second xonsh read environment as strings and don't know the types.

But there is no clarification about it in the docs and everyone who think that it could store the objects to environment has a risk to crash xonsh in the new runs.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Probably the `${...}.register('QWE', 'dict')` should solve this problem. I just faced with this and aware first time :)

**Comment by anki-code** [comment]
One thought: why we don't use pickle of environment between processes instead of converting objects to strings and back?

**Comment by scopatz** [comment]
I think there are a couple of reasons:

1. Pickle is very sensitive to Python versions
2. The operating system (and all shells and commands) expect to receive the environment variables as strings.
