### ISSUE TITLE
$ENABLE_ASYNC_PROMPT not handling nested format string in $PROMPT

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#3879]
Using a prompt with the "nested format string" syntax, e.g {_<prompt_field>_: _text_ **{}** _more_text_}, async prompt seems to ignore static string (e.g _text_, _more_text_) when it does the delayed update of the prompt field.  The static text (or something) is initially displayed, but then overwritten when the async update happens.

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.23               |
| Git SHA          | fdbc82a1             |
| Commit Date      | Oct 11 23:34:07 2020 |
| Python           | 3.8.6                |
| PLY              | 3.11                 |
| have readline    | False                |
| prompt toolkit   | 3.0.7                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.1                |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
+------------------+----------------------+
```

</details>

## Expected Behavior
Prompt should look the same after async update as it would look without async update.

## Current Behavior

![image](https://user-images.githubusercontent.com/1971300/95779210-81eae680-0c7e-11eb-8dff-5370316251e9.png)

@jnoortheen, could you please take a look?  I couldn't figure out what was happening here.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for the bug report!

**Comment by jnoortheen** [comment]
@bobhy it has unresolved tokens in a list and updates the item at index in place. It happens in formatter.py and updator.py . I will try to check this coming weekend.
