### ISSUE TITLE
How to get the PID of the current xonsh session?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3889]
Hi!

For example in bash the `$$` returns one stable pid:
```bash
$$
#707915: command not found
$$
#707915: command not found
kill -9 707915
# Warning: Program '/bin/bash' crashed.
```

How to get the PID of the current xonsh session?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laloch** [comment]
This is Python, so I think `os.getpid()` should do the trick.
