### ISSUE TITLE
Disable or update https://xonsh.github.io/

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3899]
Hi! xonsh is the one small step for a snail and one giant leap for mankind!

Please make the redirect from https://xonsh.github.io/ to https://xon.sh/contents.html.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
That is weird, why is that pointing to the 0.4.4 docs....

**Comment by scopatz** [comment]
I think it is because this repo needs to be updated to point to https://github.com/xonsh/xonsh-docs

**Comment by laloch** [comment]
That's strange. This repo has GitHub pages disabled...

**Comment by anki-code** [comment]
But it is already in search index:
![Screenshot_20201018_012100](https://user-images.githubusercontent.com/1708680/96354509-32724380-10e0-11eb-8f5d-346d951f81de.png)

**Comment by laloch** [comment]
It probably comes from here: https://github.com/xonsh/xonsh.github.io

**Comment by anki-code** [comment]
The best way is to replace all html pages in the old repo to javascript redirect:
```
<html>
<script>
window.location.replace("http://www.w3schools.com");
</script>
</html>
```

**Comment by anki-code** [comment]
[Google guidelines](https://support.google.com/webmasters/answer/2721217?hl=en) told:
> Using JavaScript to redirect users can be a legitimate practice. For example, if you redirect users to an internal page once they’re logged in, you can use JavaScript to do so.

**Comment by anki-code** [comment]
And add `robots.txt` with:
```
User-agent: *
Disallow: /
```
To remove all old pages from index.

**Comment by scopatz** [comment]
PRs to that repo welcome!

**Comment by anki-code** [comment]
Here it is https://github.com/xonsh/xonsh.github.io/pull/4
