### ISSUE TITLE
sh-compatible argument parsing in subprocess mode

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3905]
Hi! xonsh is better than best! Thanks!

Quick question just for understanding. Can potentially xonsh subprocess mode be sh-compatible around arguments parsing? 

⚠️ **I don't mean full sh-syntax support (loops, conditions and others). I mean only the arguments and string behavior.**

For example:

1. [The line from stackoverflow](https://stackoverflow.com/questions/61618236/find-and-replace-text-in-files-with-xonsh):
    ```
    find . -type f -name "*baz*" -exec sed -i 's/foo/bar/g' {} +
    ```
    It will work in xonsh only if we add quoting to `{}` and `+`.

2. Or another [example from stackoverflow](https://stackoverflow.com/questions/59579274/xonsh-and-rsync-command):
    ```
    rsync -avz --exclude="2.txt" --dry-run test1/ test2/
    ```
    This is not working because xonsh argument is `--exclude="2.txt"` instead of `--exclude=2.txt` in sh.

Is it possible to make simple sh-commands work by default in xonsh or there are core causes that it will not be achieved ever?

I don't expect complete answer with all cases. If the answer is no it's what I need :)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for opening this @anki-code. In my opinion, this is what `source-bash`or `source-sh` is for.

```
$ source-bash! find . -type f -name "*baz*" -exec sed -i 's/foo/bar/g' {} +
```

This might need some cleanup etc to make sure it fully works in all cases. 

Also, it would be pretty easy to write a marco function or context manager that ran in sh.  https://xon.sh/tutorial_macros.html

**Comment by anki-code** [comment]
Ah, really, the command could be run in any shell and macro way is could solve it. Thanks!

**Comment by scopatz** [comment]
Yep! Macros are pretty powerful!
