### ISSUE TITLE
Consider including zoxide under xontribs

### ISSUE THREAD

**Issue by ajeetdsouza** [xonsh/xonsh#3910]
I'm working on adding xonsh support for [zoxide](https://github.com/ajeetdsouza/zoxide), a fast cross-platform directory jumper written in Rust.

This can't be made into a Python module - the initialization code is generated at runtime based on user-provided flags and is tied to a specific version of the zoxide binary. Therefore, it must be initialized by adding this line to .xonshrc:

```python
execx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')
```

I was wondering if you'd consider including it under xontribs. The source code can be found [here](https://github.com/ajeetdsouza/zoxide/blob/master/crates/zoxide-shell/templates/xonsh.txt). It's written in a templating language, but it should be quite self-explanatory.

On a side note, reviews on the code itself would be welcomed - I'm quite new to Xonsh!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
@ajeetdsouza - absolutely! PRs welcome, docs on how to add here: https://xon.sh/tutorial_xontrib.html#tell-us-about-your-xontrib

**Comment by dyuri** [comment]
@ajeetdsouza I quickly created https://github.com/dyuri/xontrib-zoxide which does nothing really but executes the single line you provided. If you like it I can create a PR for xonsh to include it in the _official_ xontrib list.

P.S. `zi` doesn't work for me, the `-i` argument seems to be missing. (I built `zoxide` from github, and I have `fzf` installed and working.)

**Comment by ajeetdsouza** [comment]
@dyuri thanks! I had temporarily removed `zi` on master while refactoring, it should be all good now. I'll create a new release once I'm able to do a bit more testing.

**Comment by ajeetdsouza** [comment]
I've released zoxide v0.5 with xonsh support, so everything should work fine now.

@scopatz is there any way I can get this added to the [website](https://xon.sh/xontribs.html), or is that a curated list?

**Comment by dyuri** [comment]
I think it will be added at the next release.

**Comment by ajeetdsouza** [comment]
Awesome! Closing the issue.
