### ISSUE TITLE
Slower start: read files from PATH dirs many times

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3912]
Hi! xonsh is shell but python but shell but python but the best!

While I worked on #3911 I found that reading of the files in the PATH directories was done many times in case of using default conda init:

```bash
pip install -U git+https://github.com/anki-code/xonsh.git@wsl_speed

# Run without rc - 1 warning
XONSH_WARNING_PATH_FILES=10 xonsh --no-rc
#Warning! Found 5,785 executable files in the PATH directories!
```
```bash
cat ~/.xonshrc_conda
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
import sys as _sys
from types import ModuleType as _ModuleType
_mod = _ModuleType("xontrib.conda",
                   "Autogenerated from $(/opt/miniconda/bin/conda shell.xonsh hook)")
__xonsh__.execer.exec($("/opt/miniconda/bin/conda" "shell.xonsh" "hook"),
                      glbs=_mod.__dict__,
                      filename="$(/opt/miniconda/bin/conda shell.xonsh hook)")
_sys.modules["xontrib.conda"] = _mod
del _sys, _mod, _ModuleType
# <<< conda initialize <<<
```
```bash
# Run with conda rc - 3 warnings
XONSH_WARNING_PATH_FILES=10 xonsh --rc ~/.xonshrc_conda 
#Warning! Found 5,785 executable files in the PATH directories!
#Warning! Found 5,785 executable files in the PATH directories!
#Warning! Found 5,785 executable files in the PATH directories!
```

**As result instead of scan 5795 - 2298 - 420 = 3077 files once it scans 5795 files 3 times = 17,385 in sum.**
It looks like this is the cause why xonsh have 2 sec start time on my linux!

Please take a look at `commands_cache.py` and conda init. It looks like a speed issue.

Also `--timings` not shows the time of creating prompt on the first run that uses commands_cache so this is why no one can detect the problem.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Details by directories:
```python
all=0
for p in $PATH:
    print(p)
    a=len([l for l in fp'{p}'.glob('*')])
    all += a
    print(a)
print(all)
```
```bash
/opt/miniconda/bin
353
/opt/miniconda/condabin
1
/home/pc/.local/bin
2
/usr/local/sbin
0
/usr/local/bin
0
/usr/sbin
420
/usr/bin
2298
/sbin
420
/bin
2298
/usr/games
0
/usr/local/games
0
/snap/bin
3

5795
```
And we can see that:
```bash
ls -la /bin
#/bin -> usr/bin

ls -la /sbin
/usr/sbin
```
So xonsh scan the same directory twice.

As result instead of scan 5795-2298-420=3077 files once it scans 5795 files 3 times (17,385 in sum).

**Comment by anki-code** [comment]
> So xonsh scan the same directory twice.

@scopatz and the counter here the source of true instead of `len(allcmds)`;)

**Comment by scopatz** [comment]
The counter is too slow in my opinion.

**Comment by anki-code** [comment]
@scopatz I've made the PR to fix the double reading of the directory and the symlink to this directory. But I still need help with understanding why the reading happens three times when conda init sourced.
