### ISSUE TITLE
Cannot configure style colours for xonsh specific tokens

### ISSUE THREAD

**Issue by kip93** [xonsh/xonsh#3929]
When registering a custom style, you cannot modify the colours for any xonsh specific tokens.

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.8.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | pop             |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

## Expected Behaviour

When running

```
$ from xonsh.tools import register_custom_style

$ _custom_style = {token: "#FF0000" for token in (
      "Token.Aborted", "Token.AutoSuggestion", "Token.Menu.Completions", "Token.Menu.Completions.Completion",
      "Token.Menu.Completions.Completion.Current", "Token.Scrollbar.Arrow", "Token.Scrollbar.Button",
  )}  # Set these tokens to bright red for this example
$ register_custom_style("custom", _custom_style, base="default")
$ $XONSH_COLOR_STYLE = "custom"

$ xonfig colors
```

the output should show the detailed tokens as bright red (or whichever colour you want to configure).

## Current Behaviour
After running the commands specified above, the colours of any of those tokens do not change.

## Steps to Reproduce

Run the snippet shown above.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
I think that #3920 fixes this.

**Comment by scopatz** [comment]
Thanks for reporting @kip93!

**Comment by dyuri** [comment]
Yep, #3920 should fix this, but those rules are for PTK1 and I doubt you are using it. For PTK2+ you'll need `Token.PTK.AutoSuggestions` (or simply `auto-suggestions`) for those to work.

The actual `*.PTK.*` tokens should be displayed by default in the output of `xonfig colors`, so you can check them once you have a version that contains the fix.

**Comment by kip93** [comment]
Seems like this is a known problem already, so I would like to close this as a duplicate if there is another issue that I could link, but I cannot find the original one referenced in either #3920 or #3932. Otherwise, I will keep this open for tracking purposes and wait for the fix so I can re-test this once this is solved.

Let me know if you need any more info or some help testing some pre-release patch.

**Comment by scopatz** [comment]
Feel free to keep this open now

**Comment by dyuri** [comment]
Yep there was no "original issue", I discovered those PTK-only styles while introducing `$XONSH_STYLE_OVERRIDE` and trying to provide a common interface for all the different "render backends".
Now with #3933 I hope I'm on a good path, @kip93, I'd be happy if you could give it a try.

**Comment by kip93** [comment]
Hey @dyuri! Just tested it using both `register_custom_style` and `$XONSH_STYLE_OVERRIDE` and both methods seem to be working correctly now. Thanks for looking into it!

The only thing that I cannot find is how to change the background of the auto-completion menu, but that might be an unrelated issue. I am not even sure if PTK allows for that (at least I think that is done with PTK, I have not looked too deeply at the code). Let me know if I should open a separate ticket for that.

Thanks again for the help!

**Comment by dyuri** [comment]
![image](https://user-images.githubusercontent.com/126637/97403042-fb780b00-18f3-11eb-80b8-e8effa0745bd.png)
Which "background" do you want to change? The one in the pink rectangle can be changed, it's `Token.PTK.CompletionMenu` (or `completion-menu`). The other (yellow rect.) is the background of the terminal, nothing is drawn there AFAIK, so we cannot really change that indeed.

**Comment by kip93** [comment]
Never mind, I forgot to add `bg:` before the colour. It was a noob mistake :p
I have only been using xonsh for a couple of weeks, and just began ricing it last week to try to use is as my main shell.

I have not encountered any more issues with this. Do let me know if you need anything else from me (:
