### ISSUE TITLE
xontribs.json alternative format?

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3931]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.24               |
| Git SHA          | 74543ea9             |
| Commit Date      | Oct 10 15:12:47 2020 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.3                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | argcomplete          |
| xontrib 3        | autovox              |
| xontrib 4        | cmd_done             |
| xontrib 5        | hist_navigator       |
| xontrib 6        | jedi                 |
| xontrib 7        | notifypy             |
| xontrib 8        | pdb                  |
| xontrib 9        | prompt_ret_code      |
| xontrib 10       | readable-traceback   |
| xontrib 11       | vox                  |
| xontrib 12       | voxapi               |
+------------------+----------------------+
```

</details>

As of now all the xontribs are mentioned in a single file. 
 - it will grow in size and sometimes my IDE auto-formats the whole file.
 - it will be difficult to maintain as it grows in size. 

I propose that we use directory called `xontrib/metadata` folder, that will hold `*.json` files. each describing a single xontrib info. We can add a README in that directory for how to add new xontrib.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hey @jnoortheen - I am totally in favor of rethinking how xontribs are loaded. The JSON was a quick and dirty initial implementation. As part of any redesign, I would like to make sure that load times are fast. This is because `xontrib load` is likely part of many people's xonshrc, and therefore would contribute to the startup time. Hope this makes sense!

**Comment by jnoortheen** [comment]
> Hey @jnoortheen - I am totally in favor of rethinking how xontribs are loaded. The JSON was a quick and dirty initial implementation. As part of any redesign, I would like to make sure that load times are fast. This is because `xontrib load` is likely part of many people's xonshrc, and therefore would contribute to the startup time. Hope this makes sense!


Yes. I will try to benchmark the time difference between parsing a single large file and multiple single files. I will try to do it in the weekend.

**Comment by scopatz** [comment]
Amazing! Thanks for tackling this

**Comment by jnoortheen** [comment]
@scopatz I did check with multiple files. Here are the [results](https://gist.github.com/jnoortheen/5ce9b267a941f9751dadd7bc353193b7) 

Loading multiple files did take some time. so the best bet would be to use pickle to compile them and package as part of setup.py build process.  What do you think?

**Comment by scopatz** [comment]
Are the results total time? Or time per instance?

**Comment by jnoortheen** [comment]
Per function. It is simply the output from the test function

**Comment by scopatz** [comment]
Hmm yeah, well, moving pickles around can be problematic because the bytecode changes.  But maybe it would be better to turn this into a regular Python module than can be imported. Wheels and import caching would make this fast then.

**Comment by jnoortheen** [comment]
Yeah that is better. How that will look like? a single py file per xontrib that inherits a base class ?

**Comment by jnoortheen** [comment]
I think we can define the schema as `typing.NamedTuple` and have instances of it for every xontrib in a single file.

**Comment by scopatz** [comment]
> I think we can define the schema as typing.NamedTuple and have instances of it for every xontrib in a single file.

This sounds like a good plan

**Comment by jnoortheen** [comment]
OK I will create a Draft PR with it.
