### ISSUE TITLE
Discussion on broad @mentions

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#3934]
In https://github.com/xonsh/xonsh/pull/3926#issuecomment-716232379, @anki-code mentioned a large number of people attempting to reach contributors to gather broader input. Some [expressed dismay](https://github.com/xonsh/xonsh/pull/3926#issuecomment-716233013) and the action led the maintainers to [lock the discussion](https://github.com/xonsh/xonsh/pull/3926#issuecomment-716237861).

I wanted to open this issue to discuss the concern separately. If you were automatically subscribed to this thread but are uninterested in this meta discussion, please select the unsubscribe button to the right.

I, for one, was happy to be notified of the issue. Although at first I had the same reaction of dismay, after reading the guidance in the comment, I understood the motivation and actually found it informative. I'm glad to have had the opportunity to be drawn into this change, because the underlying issue also affects me.

The attempt by the contributor to get feedback from other contributors is something that's not often done, and when it is, it's often through another forum. I don't see how anki-code could have achieved what they were after any other way.

I do see how the action did seem spammy, but since the action was very much on-topic and if such an action is rare, it seems reasonable to force these "key stakeholders" into a conversation, especially when the investment of each individual to opt-out is to simply click the unsubscribe button, but the value of being involved in the discussion around a high-impact change is potentially high.

Surely, it would have been nicer if there were a better forum where contributors or users or enthusiasts could opt in to announcements or calls-to-action like these. I similarly face challenges like these in the projects I maintain when I wish to reach a key audience of users but have no good way to select or reach those people.

I'd like to explore ways to meet this use-case other than "please don't ever do that", which implies "you can't reach other potentially interested parties around changes that will impact them without merging and publishing the change first."

Perhaps it would make sense for xonsh to create a `xonsh-contributors@` or `xonsh-enthusiasts@` or similar where contributors could be encouraged to opt-in (and out to their preference) and where similar rare announcements could reach the interested parties.

**Comment by jaraco** [comment]
Also, if Github had a feature where commenters or admins could unsubscribe users or where commenters could one-time-mention a user (without also implicitly subscribing them), that would likely have limited the fallout of such a communication attempt.

**Comment by anki-code** [comment]
Hi @jaraco! Thank you for support and kind words! I had lack of them. I agree with you that unsubscribe is easy.

And I agree with @gforsyth. His reaction technically right. And I agree with @gforsyth. His reaction technically right. It's not a good step and I made it out of despair. 

As you see we continue the discussion in 3924 issue. You're welcome :)

**Comment by scopatz** [comment]
Thanks for your thoughtful post here @jaraco. I think we should have some sort of code-of-conduct. I also think that there should be an enhancement proposal process, where these kinds of details can be hammered out that is outside of particular issues and PRs. Changes to aspects of xonsh, like fundemental syntax, will not happen quickly if we are being honest with ourselves. 

Speaking personally, I don't have the time or will power to read every post on every xonsh thread. And there have been a number of discussions lately where the posting becomes overwhelming. I think you are right that we need a place for people to discuss in a way that means that only people who want to can weigh in. Sort of a python-ideas parallel.  Maybe this is another gitter channel? Maybe it is another repo in the xonsh org where people can discuss ideas on that issue tracker? I am open to suggestions.

**Comment by anki-code** [comment]
@scopatz I successfully push the PRs and you accept them. Many thanks! 

And the problem (for me) with "subproc syntax" PR is not around place of talking.

The key questions for me is how to understand that you open for changes without backwards compatibility, you accept them, you agree with them and you help to release it smooth? I have no answer on this questions and now. 

We write overwhelming posts but people is talking that this topic is old and I don't understand: if the topic of the syntax have an age then it means that you reject the proposals before (right?) so why I should invest my time for it now and you reject the proposal after 1-2 weeks of silence?

It's not about "place of talking". It's about how to make core PRs, getting your acceptance and push it to release.

**Comment by scopatz** [comment]
> The key questions for me is how to understand that you open for changes without backwards compatibility, you accept them, you agree with them and you help to release it smooth? 

> I want to know it now. Not after months of working on it.

Yeah, I think that is fundamental issue. I am not the only one who has a voice in the decision making process here. I think most or all of the xore team will need to buy into these kinds of changes. That takes time. I do my best to keep up with the PRs and releases, but I am only one voice on xore. 

Xonsh is a community project. It cannot move as fast as a single person working on their own personal fork, by definition. 

> > enhancement proposal process

> And Definition Of Done or Definition Of Acceptance.

Yeah, the PEP process has a really good process here for determining changes and what it means for proposals to be accepted. See [PEP-1](https://www.python.org/dev/peps/pep-0001/). I don't know that it makes sense to follow this exactly, but it could be a good start.
