### ISSUE TITLE
Inconsistency importing modules between using ~/.xonshrc and ~/.config/xonsh/rc.xsh

### ISSUE THREAD

**Issue by kip93** [xonsh/xonsh#3936]
I found that you can use `~/.config/xonsh/rc.xsh` instead of `~/.xonshrc` to configure xonsh, but when I tried to import a module on a separate file I found that while on `~/.xonshrc` this works as [detailed in the tutorial](https://xon.sh/tutorial.html#importing-xonsh-xsh), trying to do the same in `~/.config/xonsh/rc.xsh` fails. I was able to work around this by using the following snippet

```
with open(p"$HOME/.config/xonsh/my_module.xsh") as file:
    execx(file.read())
```

but I think this should not be the correct approach. I tried appending `~/.config/xonsh` to both `$PATH` and `$PYTHONPATH` on top of the run control file but that did not help.

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.24.dev1424       |
| Git SHA          | b4931a59             |
| Commit Date      | Oct 27 17:05:19 2020 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.5                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | pop                  |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

**Note:** The xonsh version is a build [this](https://github.com/dyuri/xonsh/tree/ptk_support_for_themes) branch because of a fix not yet merged.

</details>

## Expected Behaviour

Configuring the run control for xonsh should behave the same when using either `~/.xonshrc` or `~/.config/xonsh/rc.xsh`.

## Current Behaviour

When I run this on my home folder
```
$ echo 'print(1)' > my_module.xsh
$ echo 'from my_module import *' > .xonshrc
$ xonsh
```
then I get a `1` on stdout and the module is correctly imported, but if I run the following inside `~/.config/xonsh`
```
$ echo 'print(1)' > my_module.xsh
$ echo 'from my_module import *' > rc.xsh
$ xonsh
```
then I get the traceback detailed beneath.

**Note:** If I place the module on my home folder, then the import is successful, which led me to try to `cd` into `~/.config/xonsh/` before running xonsh but the behaviour was the same, so this does not depend on where xonsh is started, it seems to always look in the user's home folder.

### Traceback

<details>

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 17286, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/home/user/.local/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 2471, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/user/.local/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 2376, in run_compiled_code
    func(code, glb, loc)
  File "/home/user/.config/xonsh/rc.xsh", line 9, in <module>
    from my_module import *
ModuleNotFoundError: No module named 'my_module'
error running xonsh run control file '/home/user/.config/xonsh/rc.xsh': No module named 'my_module'
```

</details>

## Steps to Reproduce

Running these commands seem to be the easiest way to reproduce:
```
$ echo 'print(1)' > ~/.config/xonsh/my_module.xsh
$ echo 'from my_module import *' > ~/.config/xonsh/rc.xsh
$ xonsh
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for reporting this @kip93! What is your $PYTHONPATH set to? This is really what determines what is importable.

**Comment by kip93** [comment]
Hello @scopatz! The `$PYTHONPATH` variable is not set, and even if I do `$PYTHONPATH = [p"$HOME/.config/xonsh/"]` before importing the module is still not found. I will update the issue to add this.

**Comment by kip93** [comment]
Ok, with some more testing I realised that while putting `$PYTHONPATH = [p"$HOME/.config/xonsh/"]` on top of `~/.config/xonsh/rc.xsh` does not work, running `$PYTHONPATH=[p"$HOME/.config/xonsh/"] xonsh` does seem to work. Still, I do not think that this should be the correct behaviour, but it at least provides a starting point.

Maybe, when importing from `~/.config/xonsh/rc.xsh` this value could be appended to the `$PYTHONPATH`? It seems simple enough, I could take a stab at it and do a PR.

**Comment by anki-code** [comment]
Hi @kip93! This works for me:
```bash
# bash
echo 'print(1)' > $HOME/.config/xonsh/my_module.xsh
echo 'from my_module import *' > $HOME/.config/xonsh/rc.xsh
PYTHONPATH=$HOME/.config/xonsh xonsh 
# 1
# xonsh
```

**Comment by scopatz** [comment]
Yeah, I can see an argument for adding these default rc directories to the PYTHONPATH, even if just temporarily while loading rc files. I think that would be a good fix.

**Comment by kip93** [comment]
@anki-code That's what I clarified on my last comment, if you patch the `$PYTHONPATH` either by setting it before running xonsh or by using `sys.path.append` as per your example, this works. But, I would say that that is a workaround rather than correct behaviour.

**Comment by kip93** [comment]
@scopatz If patching the `$PYTHONPATH` while loading rc files is a good approach, then this weekend I can try to do it myself and create a PR.

I just have 2 questions to help me with this fix faster, since this is my first time hacking at xonsh:
1. Which file has the code responsible for start up and loading rc files, and
2. Which are all the possible directories that an rc file could be located at? I know of `~/.xonshrc`, `~/.config/xonsh/rc.xsh` and `/etc/xonshrc`, but these are the Linux file locations, not sure if they are exactly the same on BSD & OSx or if there is some difference there, and I have no clue where they are on Windows.

**Comment by scopatz** [comment]
I believe that there is a `load_rcs()` function or similar somewhere.  The list of default RC files lives in `enviorn.py`. See https://xon.sh/envvars.html#xonshrc too

**Comment by kip93** [comment]
Thanks @scopatz! Those pointers are a really big help (:

I will work on this and let you guys know if and when I have a fix ready.

**Comment by kip93** [comment]
Hello again! As you can see above, I just opened a PR with a fix. Only really tested it on my linux machine, but nothing I used should cause any issues with Windows. Let me know what you think!

**Comment by kip93** [comment]
Well, it seems I was wrong, god damn Windows test do not pass ):

I will continue debugging and report back.

**Comment by kip93** [comment]
Hello there! It's me again. I wanted to put down some findings that I discovered while failing to fix Windows support.

Seems like on Windows, prior to version 3.9 of Python, the registry is used to handle the `sys.path` (see [this issue](https://bugs.python.org/issue8901)). I tried several workarounds, but none of them were able to correctly handle the case when an user might explicitly add the same path as the rc to `sys.path`, which I would consider to be a regression, since before this patch the user could do that without any problem.

This is made even worse because I cannot properly test any of this because the most modern Windows PC that I have access to is a 2005ish 32-bit Windows XP netbook which I do not know if it even boots anymore (and I do not have a Windows license to use on a VM), so I have been depending on the pytest checks' output.

Other than that, this has had no issue on the linux and macos tests. So much so, that with only the first 4 commits the PR was done were it not for Windows.

Unfortunately, I do not have any more time to pout into this this weekend. I will tackle this again next week.

**Comment by kip93** [comment]
I'm back!

During the week I remembered that you can get a copy of Windows 10 without a key for reduced functionality, so I spun up a VM and did some debugging. With this, I found that:

1. On Windows, any sort of wrapper I try to put on the `sys.path` is completely ignored (prior to Python 3.9), probably because of how Windows handles it using the registry.
2. Seems like the error with missing `sys.path` entries that are manually added in the rc file is not due to my PR. I copied the test to the master branch and the same behaviour is present, so it is not a regression as I originally thought. This probably deserves its own issue, since it only presented itself here because I added a test for this case.
To avoid the failing test I added a condition to skip if running on Windows with a version of Python prior to 3.9.

I believe that the PR is ready to be reviewed. Should I add a label or something to the PR?

**Comment by scopatz** [comment]
I'll take a look at the PR again

**Comment by jnoortheen** [comment]
I use the following setup and it helps me to avoid PATH problems https://gist.github.com/jnoortheen/8b5220f200bc5c9e121a7722836bf674
