### ISSUE TITLE
Update and close 3926

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3943]
Hi! xonsh is super cool!

Please:
1. Replace the description of PR 3926 to the text:
    ````
    #### UPD: The proposal description moved to 
    [XEP-1 in xonsh-operators-proposal](https://github.com/anki-code/xonsh-operators-proposal)
    ````

2. Remove the emoji from the title.

3. Close it.

Thanks!

**Comment by laloch** [comment]
Hi @anki-code, done and closed.
I'm glad you reconsidered using emoji in PR titles.

**Comment by anki-code** [comment]
Thanks @laloch ! Yeah :)
If you have time it will be great to get your feedback on [XEP-2](https://github.com/anki-code/xonsh-operators-proposal/blob/main/XEP-2.rst) approach.
