### ISSUE TITLE
Autosuggestion is not working in python substitution

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3946]
Hi! xonsh is inspiring for change the mindset! Thanks!

I've noticed the auto suggestion is working in command substitution in python mode. Meaningless example:

![Screenshot_20201031_120914](https://user-images.githubusercontent.com/1708680/97775468-e6a8ab00-1b71-11eb-93ff-d47906a4cfc3.png)

But not working in subproc mode:

![Screenshot_20201031_121040](https://user-images.githubusercontent.com/1708680/97775491-1bb4fd80-1b72-11eb-884a-7c7da7242d20.png)

It will be cool to fix this or point out what is the best place to start fixing. Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Workaround is to use jedi:

![Screenshot_20201031_122407](https://user-images.githubusercontent.com/1708680/97775711-fa551100-1b73-11eb-82e5-b6d44b251d68.png)

**Comment by scopatz** [comment]
thanks for reporting!

**Comment by bestlem** [comment]
I think the cd completer is failing in the same way in subproc mode
