### ISSUE TITLE
Input Lag with fresh install in WSL with conda installation

### ISSUE THREAD

**Issue by datwaft** [xonsh/xonsh#3948]
## System information

WSL 2 Debian 10
Windows 10 Pro 2004

## xonfig

<details>

I don't have any xonfig yet, it is a fresh install.

</details>

## Expected Behavior
Not have any lag, like with zsh or bash (or even fish).

## Current Behavior

There is input lag with the fresh install of xonsh. A very noticeable input lag.

## Steps to Reproduce

1. Install the latest version of conda using:

```sh
wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh
bash Anaconda3-2020.07-Linux-x86_64.sh
```

2. Install xonsh with conda

```sh
conda config --add channels conda-forge
conda install xonsh
```

3. Open xonsh

```sh
xonsh
```

## Additional details

<details>

I tried to use a fresh **OpenSUSE WSL** installation and there is input lag, but if I install and old version with `zipper` there is no input lag.

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @datwaft ! Please check it out - #3895

**Comment by datwaft** [comment]
> Hi @datwaft ! Please check it out - #3895
> And please change WSL to WSL2 in the title.

Thank you! I tried to google it but didn't find anything. That explains it.
