### ISSUE TITLE
Travis is ending (changing?) their free OSS runs

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#3952]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

The only thing we still run on Travis is `doctr` for managing the doc builds + pushes.  It looks like we'll get some free credits that should tide us over for a while (i can't grok right now if those credits are on a monthly basis or just a one-time thing).  So this might be enough for our purposes, or it might not.

**Comment by scopatz** [comment]
yeah, I am hoping that it is enough for us
