### ISSUE TITLE
Universal new lines in captured object output

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3954]
Hi! The snail-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep conch.

While I'm working on [XEP-2](https://github.com/anki-code/xonsh-operators-proposal/blob/main/XEP-2.rst) I've found that `!().out` returns not original command output. Example:

```python
echo -n '1\n2\r\r3\r\n4\n' > txt
!(head -n 10 txt).out
# '1\n2\r\r3\n4\n'

# Prepared by xontrib-hist-format
```
Here we've got `3\n4` instead of `3\r\n4`. This behavior with `!().out` is expected or it's the bug?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
This is a known and expected feature of python, see  [Universal Newlines](https://www.python.org/dev/peps/pep-0278).

Note in regular python on windows:

```python
with open(".gitignore", "r") as f:
    print(repr(f.read()))
# '*.pyc\n*.out\n...'

with open(".gitignore", "rb") as f:
    print(repr(f.read()))
# b'*.pyc\r\n*.out\r\n...'
```

**Comment by anki-code** [comment]
Hi @daniel-shimon! I understand that it's expected in Python. I just don't have strong confidence that this difference is expected in the shell:

```python
echo -n '1\n2\r\r3\r\n4\n' > txt

echo -n @(!(head txt).out) | wc -c
# 9
bash -c! head txt | wc -c
# 10

echo -n @(!(head txt).out) | md5sum
# 1572fccf492b7a38a29660914572a7de
bash -c! head txt | md5sum
# 43773b3ca1accd84485ea0ff69dab1fe
```
I think: 
1. This difference should be in the [Tutorial](https://xon.sh/tutorial.html).
2. We should have the method/property to get pure output without universal newline replacing to solve the example above. This is the cause why I suggest to you [to add `!().raw` property in your PR](https://github.com/xonsh/xonsh/pull/3925#issuecomment-721229496).

**Comment by daniel-shimon** [comment]
What you wrote doesn't seem to be a problem on windows:

```python
echo -n '1\n2\r\r3\r\n4\n' > txt
echo -n @(!(head txt).out) > txt2
bash -c! head txt > txt3
md5sum txt*
"""
cbd56acf9dcc16e42b5f2776cffc6e21 *txt
cbd56acf9dcc16e42b5f2776cffc6e21 *txt2
cbd56acf9dcc16e42b5f2776cffc6e21 *txt3
"""
```

On linux though, we get weird behavior because files shouldn't contain `\r\n` line endings.
I agree it should be easy to get the raw output from a command without python decoding shenanigans. That's what the `raw_out` PR is for.

So `echo -n @(!(head txt).raw_out)` should do what you want.
Currently it doesn't work because the `@()` doesn't check for `bytes` objects and does weird stuff.

Will fixing `echo -n @(!(head txt).raw_out)` close this issue?

**Comment by anki-code** [comment]
> Will fixing echo -n @(!(head txt).raw_out) close this issue?

It will be much better. And we still need the couple of word in the Tutorial about difference between `out`, `output`, `raw_out`.

**Comment by daniel-shimon** [comment]
Added commit in the PR for this, now on Ubuntu:

```python
echo -n '1\n2\r\r3\r\n4\n' > txt

echo -n @(!(head txt).raw_out) | md5sum
#43773b3ca1accd84485ea0ff69dab1fe  -

bash -c! head txt | md5sum
#43773b3ca1accd84485ea0ff69dab1fe  -
```
