### ISSUE TITLE
In prompt-toolkit Shift-Right (and other Shift + Cursor keys) does nothing in macOS Terminal 

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3956]
When using prompt-toolkit `Shift-Right` is suppose to extend the selection in emacs-mode. At least it does so in xonsh on Linux (xterm) and of course in Emacs.

However in macOS default Terminal app  `Shift-Right` doesn't do anything.

Is this rather a prompt-toolkit problem? Maybe there is a custom fix possible in the .xonshrc file?

Here the xonfig:

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.8.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

**Comment by scopatz** [comment]
This might be a xonsh problem. It probably could be fixed in a xonshrc, but the interface should be the same across platform.  Pull requests welcome!

**Comment by halloleo** [comment]
I just found out this seems to be a problem with the vendored prompt-toolkit. When I install the current version prompt-toolkit 3.0.8 into my xonsh environment, everything works as expected. :-)

**Comment by scopatz** [comment]
Ahh OK.. PRs to update the vended version welcome!

**Comment by halloleo** [comment]
Well, teh issue is bettered when using PTK 3.0.8. How would I go about "vendoring" this into the xonsh project? Just copying the `site-packages/prompt_toolkit` files to `xonsh/vended_ptk/prompt_toolkit`?

**Comment by gforsyth** [comment]
Hey @halloleo -- yes -- although if you are going to do that, can I suggest adding a directive to the `Makefile` that is similar to the one we use to (infrequently) update `ply`?  That way we can have a way of reliably repeating the process.

**Comment by halloleo** [comment]
Ok, I had a look at the Makefile.

So, I don't _copy_ the prompt_toolkit-files into the xonsh tree, but rather _issue the following git command_ instead:

    git subtree pull --prefix xonsh/vended_ptk/prompt_toolkit https://github.com/prompt-toolkit/python-prompt-toolkit.git master --squash

(This command then goes into the Makefile as well.)

**Comment by halloleo** [comment]
Sorry, running into a problem:


    git subtree add --prefix xonsh/vended_ptk/prompt_toolkit https://github.com/prompt-toolkit/python-prompt-toolkit.git master --squash

adds an additional directory level: i.e. what was before in `xonsh/vended_ptk/prompt_toolkit`  is now in `xonsh/vended_ptk/prompt_toolkit/prompt_toolkit`.

 I guess it is safer just to copy the files into the proper dirctory - but then I cannot do the Makefile bit.

**Comment by gforsyth** [comment]
Sorry, @halloleo -- I missed this.  What if you do:

```
git subtree pull --prefix xonsh/vended_ptk/ https://github.com/prompt-toolkit/python-prompt-toolkit.git master --squash
```

instead?  I'm also not attached to the directory name of "vended_ptk" -- it's pretty obvious that we vended it

**Comment by daniel-shimon** [comment]
Closing this since we don't vendor prompt toolkit anymore
