### ISSUE TITLE
Using Xonsh as a base for a pentesting project. (Ask for advise and oppinions)

### ISSUE THREAD

**Issue by grg121** [xonsh/xonsh#3957]
Hello there! I'm Paco, a QA Software engineer.

I'm working on a project for a penetration testing environment tool. I want to send logs to my tool with the command executed on a shell (I don't mind if it is bash, zsh or xonsh) and their outputs (to parse them and log them along with relevant information such as hosts discovered, IPs, vulnerabilities detected, etc...).

I've found various solutions that suite my objectives but they're tricky and are based on the parsing of a console input and output.

I'm now wondering it there could be possible to do this with a modern shell such as Xonsh. 

I didn't know the project but I've found it very interesting and I'm getting started with it but I would like to ask people that have worked on it what do they think about what I'm trying to do.

I've read this interesting topic in the doc talking about Xonsh shell having a teeing pseudo-terminal running on top of pty and I am overwhelmed with the possibilities this offers... but It concerns me the behaviour of this pseudo-terminal with ssh sessions. I would like to keep monitoring user actions (with output) even if they are executed remotely or in another shell (suppose someone wants to run zsh or bash inside Xonsh, for example). And I'm wondering how difficult this would be using xonsh. My current approach is to use a terminator (console emulator) plugin that parses the user input (to the emulator) and console output and tries to differentiate between user input and console output but, as I said, it is tricky and I'm afraid I could make something way better using Xonsh as a base!

I'm reading right now more about Xonsh and testing ideas myself,  feel free to close this issue if required. The purpose of this issue is just to ask the community and developers for some ideas on this topic. If you have read this and have anything to contribute, I would be so grateful to read your suggestions!

Also, If you know possibles problems that I will handle, I would appreciate your advice as well.

Best regards.

**Comment by anki-code** [comment]
Hi @grg121 ! Could you please describe your desired use case of the shell step by step?

**Comment by grg121** [comment]
Hello @anki-code, thanks for your answer! Yes, it is something like that.

My server will listen to syslog messages and analyze them to find relevant information, let's say, for example, that the IP `172.217.8.164`appear in the input or in the output of a command executed.

So the use case could be:

1. User open the shell and run "nmap -sn 172.217.8.164" 
2. Shell send to the server something like this:
```
2020-10-30-18:04:48 kali-linux Auditor: nmap -sn 172.217.8.164 executed with output:  Starting Nmap 7.80 ( https://nmap.org ) at 2020-10-30 18:04 CET Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn Nmap done: 1 IP address (0 hosts up) scanned in 3.07 seconds
```
3. The server analyzes that output and alert of nmap being executed for `172.217.8.164

I think that would be easy to implement in Xonsh, I just need to find the best wat to do it. I imagine that it would be with a custom Xontrib.

But also, the main issue is to track commands even if the shell changes. For example:

1. User open the shell and, inside of it, changes to /bin/bash or /bin/zsh or run msfconsole
2. User run `echo "hello world`"
3. shell send syslog message to the server with
```
2020-10-30-18:04:36 kali-linux Auditor: echo "Hello world" executed with output:  Hello world
```

In this case, I doubt xonsh could differenciate user input and command output without parsing them, but that Teeing pseudo-terminal mentioned here in the docs: https://xon.sh/tutorial_hist.html#exciting-technical-detail-teeing-and-pseudo-terminals gives me the hope of being able to to something with that pseudo-tty STDIN and STDOUT to easily handle what's going on the new shell (bash, zsh, whatever) 

The same (and even. more important) would be if the user logs into an external shell using ssh:

1. User open the shell and run "ssh kali@192.168.56.10"
2. shell send syslog message to the server with:
```
2020-10-30-18:04:36 kali-linux Auditor: ssh 192.168.56.10 executed with output: The authenticity of host '192.168.56.10 (192.168.56.10)' can't be established. ECDSA key fingerprint is SHA256:nMJ45DVt1gURHpd2QYCu9JlIiBKTynYzBgYcLxe27hY. ECDSA key fingerprint is MD5:d0:41:7d:2e:2a:98:aa:9a:9b:94:ec:f0:71:af:2b:bc. Are you sure you want to continue connecting (yes/no)? yes Warning: Permanently added '192.168.56.10' (ECDSA) to the list of known hosts. root@192.168.56.10's password:  Last login: Thu Nov  5 11:28:39 2020 from 192.168.56.1 
```
3. User run "rm -rf /important_directory" and shell send the message:
```
2020-10-30-18:04:36 kali-linux Auditor: "rm -rf /important_directory" executed with output ""
```
4. The server analyzes that and generates an alert saying "ey, the importat_directory has been removed from the system" (os something like that)

Again, unless I use something like `xxh`, I cannot control what is being executed in the remote server, nor command output or exit status. But Maybe I could handle user input to track then a command is executed and the output of such commands.

Currently, I do this with a plugin in a console emulator that detects user input and console content-changes events using pyte callbacks and when a remote command is executed, I read the entire line from the command, remove the prompt and record the output. My main problem is to determinate when a command has finished, for example. 

I know this is a difficult topic, and maybe I won't be able to have it working easily but I'm willing to hear ideas! 

Best regards,

**Comment by anki-code** [comment]
Got it! Thank you for detailed description! I heard about solutions for "ssh proxy servers". You can connect to the server via ssh and then use shell or connect to another ssh servers and all what you will do during session will be saved to the logs without regarding what shells you run or what you do after ssh to another servers. Sad but I haven't names. It's like a "ssh bastions" or "ssh proxy" or "recording ssh session" or something like this. This kind of logging is needed to know what user (sysadmin/devops) was did and what output he had. Finally this logs used to resolve incidents when sysadmin/devops did a mistake.

If we back to xonsh you can use events and `__xonsh__.history` to get commands and the output. But it's not the good solution for your case.

**Comment by grg121** [comment]
Alright, @anki-code , thanks for your answer, I will check these ssh proxies... and I will think about if it is worth to use xonsh as a base for the auditor project or keep using terminator (or something else).

If anyone else  has anything to share I would be glad to know! thanks!

**Comment by scopatz** [comment]
Hi @grg121 - that sounds like a great application for xonsh.  

Xonsh really shines in projects where you really need to do a lot of complex logic (relative to things like Bash) and a lot of subprocess calls (relative to Python).  

FWIW there is rever ([code](https://github.com/regro/rever/), [docs](https://regro.github.io/rever-docs/)) that is a full project / application written in xonsh, if you need an example.

**Comment by grg121** [comment]
Hello @scopatz,

I think you may be able to help me with this: I've read that doc: https://xon.sh/tutorial_hist.html#exciting-technical-detail-teeing-and-pseudo-terminals which says there is a `xonsh.teepty` to tee the STOUD of the process that run as subproces. Nevertheless, this class seems to not exists anymore.

I've found this issue you oppened in 2016 https://github.com/xonsh/xonsh/issues/795 which mention the posibility of changin such module by `ptyprocess` but you finally closed the issue in 2017 saying "no longer needed"

I would like to know what happened, what is being used nowaday when I enable `XONSH_STORE_STDOUT` to tee the command STODOUT??

I'm looking to understand how the command output of subprocess commands could be stored into history and maybe parsed as well.

Any help or indication would be appreciated! Also, If the documentation is outdated as it seems I would be happy to open a PR updating it!

Best regards and thanks for your time : )

**Comment by scopatz** [comment]
Hi @grg121 - yeah, we moved everything to the CommandPipeline object.  You should look there.  There are `.out` attributes of subprocess calls that allow you to get the output of commands.

**Comment by grg121** [comment]
Oh, just what I was looking for, thank you very much : )

**Comment by scopatz** [comment]
Great! Glad that helped!

**Comment by grg121** [comment]
I finally decided to use xonsh as a base for my project along with XXH, I will use a modified history backend to store the command execution in the format that I need and merge remote xxh-xonsh logs when connecting to outside hosts.

Thanks for your help!
