### ISSUE TITLE
Importing aliases and events via Xonsh Python library

### ISSUE THREAD

**Issue by ajeetdsouza** [xonsh/xonsh#3958]
I'm developing a plugin for Xonsh, and I'm experimenting with writing it in pure Python to get the benefit of linting, formatting, typechecking, etc. However, `mypy` complains that some identifiers (which are globally available in Xonsh) have not been imported or declared. Is there any way to import these?

- `@events.on_post_prompt` and `@events.on_chdir`
- `aliases`

**Comment by scopatz** [comment]
Yep! You can find where these are defined in the API docs. (`xonsh.aliases` and `xonsh.events`), but it is usually best to get them from the builtins module.  That is, 

```py
import builtins

builtins.aliases
```

The reason to do this is because what is in builtins is proxied over to the current XonshSession object, called `builtins.__xonsh__`

**Comment by ajeetdsouza** [comment]
Thanks! Unfortunately, `mypy` still isn't happy with this, since `builtins` is part of Python and it can't find `aliases` or `events` within the module. I don't think there's a better solution here, so I'm closing this.

I've added `# type: ignore` to pacify `mypy`, but do let me know if you can think of any other way.

**Comment by ajeetdsouza** [comment]
Leaving this here in case anybody else needs it:

```python
import builtins

aliases = builtins.__dict__["aliases"]
events = builtins.__dict__["events"]
```

**Comment by laloch** [comment]
Why not just `aliases = builtins.aliases` or even `from builtins import aliases`?

**Comment by ajeetdsouza** [comment]
Tools like mypy or pylint complain if you use `builtins.aliases`, because `builtins` is a standard module that is known not to contain `aliases`.

One could add a comment that disables static analysis on those lines. Each tool requires a different comment format in order to do this. I didn't see the point of doing this - the entire reason I'm adding in this line is to please the typechecker.

However, if you access it via the `__dict__`, none of the tools attempt to verify dictionary keys. It doesn't do anything particularly clever either - the `__dict__` object is pretty much how everything in Python works under the hood.

**Comment by scopatz** [comment]
I would skip linting on those lines rather than use `__dict__` personally.

**Comment by laloch** [comment]
> Tools like mypy or pylint complain if you use `builtins.aliases`, because `builtins` is a standard module that is known not to contain `aliases`.

Oh, I see, sorry for the confusion. I didn't read the original post well enough. Yeah, that's a known mypy deficiency. Alas, there seems to be no incentive to fix it.

+1 for suppressing linting rather than accessing `__dict__`.
The best solution would, of course, be to add Xonsh builtins stubs to typeshed.

**Comment by ajeetdsouza** [comment]
Fair enough, I've switched to disabling the linter on that line.

I too would appreciate type hinting within Xonsh - not only will the API become easier to use, you might just catch a couple of bugs along the way.
