### ISSUE TITLE
autocompletions support for generators

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3968]
[PromptToolkit](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#a-custom-completer) lets you return generators from autocompleters. But xonsh requires one to return `set`. It beats the purpose of having the env variable `COMPLETION_QUERY_LIMIT` . All the functions will be running and that is not efficient. 

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.24               |
| Git SHA          | 74543ea9             |
| Commit Date      | Oct 10 15:12:47 2020 |
| Python           | 3.8.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.3                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | argcomplete          |
| xontrib 3        | autovox              |
| xontrib 4        | back2dir             |
| xontrib 5        | cmd_done             |
| xontrib 6        | hist_navigator       |
| xontrib 7        | jedi                 |
| xontrib 8        | kitty                |
| xontrib 9        | notifypy             |
| xontrib 10       | pdb                  |
| xontrib 11       | prompt_ret_code      |
| xontrib 12       | vox                  |
| xontrib 13       | voxapi               |
+------------------+----------------------+

```

</details>

## Expected Behavior

xonsh should enable returning autocompleters with yield support as well. 

## Current Behavior

1. not able to use generators as completers
2. not able to style the autocompletion menu. eventhough the shell supports it.

I think it is this way to support the compatibility with readline. At this point, does xonsh need to support readline? as it now ships with `prompt_toolkit`.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
> I think it is this way to support the compatibility with readline. At this point, does xonsh need to support readline? as it now ships with `prompt_toolkit`.

If I remember correctly (it was many years ago) we did this to allow combining results from many completers and de-duping them.  But that certainly doesn't mean we can't `yield from` those sets (or explore a different implementation).

Dropping readline support is a larger discussion issue, but I don't think it needs to block this.  Worst case, we can just exhaust the generator by dumping it into a set for the readline backend.

**Comment by jnoortheen** [comment]
> If I remember correctly (it was many years ago) we did this to allow combining results from many completers and de-duping them. But that certainly doesn't mean we can't `yield from` those sets (or explore a different implementation).
> 

I think it is better to use `yield from` from the sets and let ptk handle the rest. Atleast when the shell is PTK we can add wrapper around the existing functions that return sets. 


> Dropping readline support is a larger discussion issue, but I don't think it needs to block this. Worst case, we can just exhaust the generator by dumping it into a set for the readline backend.

But I just wanted to know the reasons for keeping readline with the project. I will create an issue maybe where one can list what it brings to the table.

**Comment by jnoortheen** [comment]
@daniel-shimon I want to work on this. My aim is to make the completer iterate only upto necessary number of completions (keeping set as well as current sequential returns). Please point me where to start.

**Comment by daniel-shimon** [comment]
Cool!
So the code you'll need to change is in `xonsh/completer.py`.
Currently the completers' results are saved in a `set`, I recommend saving a list of their results and then use `itertools.chain` to chain them and `itertools.islice` to take as many as you need
