### ISSUE TITLE
readline shell benefits?

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3969]
It will be clear if we summarize the benefits of using readline over `prompt_toolkit`. Previously it would be that it comes with python. But now `prompt_toolkit` ships as part of `xonsh`. It adds maintainance overhead and in the process of abstraction, some features provided by `ptk` is not explicitly shown or not available at all. I just want hear from people who use `readline` shell and what people using `ptk` is missing. Please anyone using readline as their preferred shell, please comment your view.

**Comment by jnoortheen** [comment]
#3968

**Comment by scopatz** [comment]
I don't use it as my preferred shell, but I do use it ~1/2 of the time.  A major benefit of readline (in addition to the ones you named) is that it boot much faster than PTK.  So people on slower or reduced compute machines will still be able to use xonsh in a snappy time frame.

**Comment by halloleo** [comment]
`readline` is valuable for people on "dumb" terminals.

 For example if you want to run your beloved xonsh in your beloved Emacs,  `readline` in a shell-buffer is still a feasible option. (I personally have switched to [emacs-libvterm](https://github.com/akermu/emacs-libvterm), but this lessens the integration with Emacs editing a bit.)

**Comment by jnoortheen** [comment]
I think these settles eventhough, the memory usage between ptk and readline is ~10MB only
