### ISSUE TITLE
Some doubts about Xonsh syntax

### ISSUE THREAD

**Issue by grg121** [xonsh/xonsh#3976]
Hello there,

I have some doubts about Xonsh syntax:

1. How can I catch a Xonsh command output? For example, I want to have some config block on .xonshrc that check if a xontrib is installed and install it if it isn't:

```python
for xontrib in load_xontribs:
    if ¿¿xontribs list @(i) ??.split()[1] == "not-installed":
         pip install whatever
    xontrib load @(i)
```

2. What is the correct way to import xonsh modules into a xonsh script? For example, if I want to run some code from `xonsh/xontribs.py`, how should I import functions from there? 

Best regards!

**Comment by halloleo** [comment]
I just tried it, and I can see something iswrong with `xontribs list`: If you wrap that subprocess line in `$(...)` it still writes to the terminal and nothing is captures in Python. :-( 

Might be a bug in the underlying implementation of `xontribs list`. You can look at it with `which -a xontrib`.

**Comment by grg121** [comment]
Hello @halloleo, thanks for answering! Yeah, it seems that the xontrib command itself isn't executed as a regular command, I've noticed that when you check the history entry for these commands, the output and return value are `None` and 0, I've checked what you proposed but I'm not understanding the code of the xontrib module...

```
grg121@archlinux ~ $ which -a xontrib
aliases['xontrib'] = <function xontribs_main at 0x7ff880eca1f0>
Type:         function
String form:  <function xontribs_main at 0x7ff880eca1f0>
File:         /usr/lib/python3.8/site-packages/xonsh/__amalgam__.py
Definition:   (args=None, stdin=None)
Source:
@unthreadable
def xontribs_main(args=None, stdin=None):
    """Alias that loads xontribs"""
    if not args or (
        args[0] not in _MAIN_XONTRIB_ACTIONS and args[0] not in {"-h", "--help"}
    ):
        args.insert(0, "load")
    parser = _create_xontrib_parser()
    ns = parser.parse_args(args)
    if ns.action is None:  # apply default action
        ns = parser.parse_args(["load"] + args)
    return _MAIN_XONTRIB_ACTIONS[ns.action](ns)
```

As far as I understand, `_MAIN_XONTRIB_ACTIONS[ns.action](ns)` would be a function that prints the output of the command, I don't understand how is this command executed and why the output is not recorded. I will investigate it and inform there in case someone is interested.

For the second point. I've also struggled with this. I've seen that, in xonsh.main there is the following import:

```
from xonsh.xontribs import xontribs_load
```

If I ran it in a xonsh session, I can execute the `xontribs_load` method. But, if I try to load another method from this module, it gives me an unknown error that seems to say the module wasn't found.

```
grg121@archlinux ~ $ from xonsh.xontribs import xontribs_loaded
Traceback (Most recent call last):
1 <xonsh-code> <module> --> 
```
Also, I got this:
```
grg121@archlinux ~ $ import xonsh.xontribs as test
grg121@archlinux ~ $ test
<module 'xonsh.__amalgam__' from '/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py'>
```
[
A little research ](https://pypi.org/project/amalgamate/) and I found that xonsh as some dark magic to speed up the importing of modules which are causing me to not being able to import these functions that are not in the `__amalgam__.py'`. I'm wondering if I could import them in another way. Maybe I will need to rewrite some required functions in my configuration file to use them.
