### ISSUE TITLE
Option to disabling additional checking of the directory in autocomplete

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3978]
Hello! There is a house in New Oceans, they call the Rising Snail! 

When I'm using network drives (i.e. [FUSE filesystem over Google Drive](https://github.com/astrada/google-drive-ocamlfuse)) I see lags in xonsh autocomplete. Example:

```python
google-drive-ocamlfuse /home/snail/network-drive
mount | grep google
# google-drive-ocamlfuse on /home/snail/network-drive (rw, nosuid, nodev, relatime, user_id=2004, group_id=2005)

ls /home/snail/ne<Tab>
# waiting 2-3-10 seconds
ls /home/snail/network-drive
```

It will be great to have an option to disabling additional checking of the directory (I suppose this needed to colorize the path).

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @anki-code -- thanks for raising this and sorry for the delay in responding!

Yeah, I recall some previous issues around similar things -- can you confirm _which_ completer is taking all the time?
I usually run something like:

```
$ for name, comp in __xonsh__.completers.items():
     print(name)
     print(comp("/home/snail/ne", "ls /home/snail/ne", 0, 0, {}))
```

**Comment by anki-code** [comment]
```python
path = "/home/snail/netw"
times = {}
for name, comp in __xonsh__.completers.items():
     t = time.time()
     comp(path, f"ls {path}", 0, 0, {})
     times[name] = time.time() - t
[(k,v) for k, v in sorted(times.items(), key=lambda item: item[1])]

#[('xontrib', 4.0531158447265625e-06),
# ('autojump', 5.7220458984375e-06),
# ('xontrib_output_search', 7.152557373046875e-06),
# ('conda', 8.344650268554688e-06),
# ('completer', 9.059906005859375e-06),
# ('xonfig', 1.3113021850585938e-05),
# ('pip', 1.9788742065429688e-05),
# ('import', 0.007668972015380859),
# ('rmdir', 0.007886171340942383),
# ('man', 0.007889509201049805),
# ('xontrib_argcomplete', 0.008347749710083008),
# ('base', 0.008350849151611328),
# ('skip', 0.008438348770141602),
# ('cd', 0.008899450302124023),
# ('python', 0.009075403213500977),
# ('python_mode', 0.009318351745605469),
# ('path', 0.11119318008422852),
# ('bash', 0.306837797164917)]

# Prepared by xontrib-hist-format
```

**Comment by gforsyth** [comment]
ahh, I thought it might be the `bash` completer -- usually when there's a slow bash completion that I don't want I remove the corresponding completion file, but bash path completion is baked in.

**Comment by anki-code** [comment]
Sorry, I don't clearly understand your thought. The lag produces by bash completion (0.3s) and it's as expected? If yes I close the issue then.

**Comment by gforsyth** [comment]
A lot of times bash completions can be slow in certain situations.  If it's a xonsh-native completion that's slow, we can try to fix it.  If it's a bash completion that's slow, those are harder to fix.

The naive way to fix it is to remove the `bash` completer from the completer list, but this obviously will have other impacts.
If it's a particular set of bash completions that are slow, say the `helm` bash completions, you can remove the corresponding file from `bash_completion.d`.  In the case of path completions, though, there isn't a special file for `cd` completions, it's just part of `bash`.  There might be some way to selectively disable it but I'm not sure how to do that.
