### ISSUE TITLE
Unable to find xontrib.json

### ISSUE THREAD

**Issue by BrianGallew** [xonsh/xonsh#3979]
Following the instructions in https://xon.sh/tutorial_xontrib.html?highlight=extensions#tell-us-about-your-xontrib I forked xonsh/xonsh and attempted to edit xontrib.json to provide a pointer to my xontrib, only to discover that xontrib.json is a symlink to xonsh/xontrib.json, which doesn't exist in master.

FWIW, my xontrib can be found at https://github.com/BrianGallew/xonsh_shells.  Once installed, you can load three different pieces:

1. shared_cache: enables you to mark environment variables as being shared among all your xonsh processes. 
 Changing the value in one shell results in a change in the rest.

1. aws_role: provides a tool to help you capture AWS session tokens and share them amongst shells using the shared_cache.  Also provides a "knife" alias that is aware of the value of $AWS_PROFILE, and a new section (aws) for powerline which is inserted by default into $PL_PROMPT

1. CIDR: provides a cidr alias that trivially displays useful information about a given subnet.

**Comment by jnoortheen** [comment]
This has been changed in the master. Here is the current version of the docs https://xon.sh/dev/tutorial_xontrib.html?highlight=extensions#tell-us-about-your-xontrib
