### ISSUE TITLE
xonsh with prompt-toolkit does not recognise setting the terminal width on the command line

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3980]
In **bash** I can do the following:

    $ stty cols 40
    $ wget http://ipv4.download.thinkbroadband.com/10MB.zip

And the printed progress bar will lie nicely in the width of 40:

    23%  2,489,475    167K/s  eta 48s      

If I am in  **xonsh with readline** all is good and happy as well. However when I issue in **xonsh with prompt-toolkit**:

    $$$ stty cols 40
    $$$ wget http://ipv4.download.thinkbroadband.com/10MB.zip

The progress-bar will have the width of the terminal _without_ the `stty` call:

    27% [==============================>                                                                                     ] 2,878,363    174K/s  eta 46s     

Depending on the terminal settings this can be inappropriately long. (This will be the reason why  in the first place you issued the `stty` command!)

prompt-tooklit in xonsh somehow messes with the proper width settings for the terminal. :-(

### Notes

The problem might be relatetd to the fact that `wget` issues the prgress-bar to std _err_.

### xonfig

<details>

```
+------------------+---------------------------------+
| xonsh            | 0.9.24                          |
| Python           | 3.6.4                           |
| PLY              | 3.11                            |
| have readline    | True                            |
| prompt toolkit   | 3.0.8                           |
| shell type       | prompt_toolkit                  |
| pygments         | None                            |
| on posix         | True                            |
| on linux         | True                            |
| distro           | Red Hat Enterprise Linux Server |
| on darwin        | False                           |
| on windows       | False                           |
| on cygwin        | False                           |
| on msys2         | False                           |
| is superuser     | False                           |
| default encoding | utf-8                           |
| xonsh encoding   | utf-8                           |
| encoding errors  | surrogateescape                 |
| on jupyter       | False                           |
| jupyter kernel   | None                            |
+------------------+---------------------------------+
```

</details>

**Comment by gforsyth** [comment]
Thanks for reporting @halloleo -- it sounds like this might be an issue with either/both of `prompt_toolkit` and `wget` -- or is there something particular that xonsh is doing wrong here?

**Comment by halloleo** [comment]
Actually as it turns out, this is neither a `xonsh/prompt_toolkit` nor a `wget` issue, but a issue with my terminal emulator `emacs-libvterm`. 

The emulator seems to start the shell before it is fully initialised. See [Shell starts up before vterm completely finishes initialising · Issue #452 · akermu/emacs-libvterm](https://github.com/akermu/emacs-libvterm/issues/452).

Sorry for the noise.
