### ISSUE TITLE
semantic versioning

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3982]
The recent releases follow `0.9.*` versioning. It should be like patching like fixing any bugs introduced in `0.9` series. But it often introduces breaking changes. Even though xonsh hasn't reached version 1 and hence this behaviour can be justified. 
But people have been using xonsh for long time and it could atleast have breaking changes in a minor release like `0.10` ... 

It will help people using xonsh as dependency and also people packaging it for [nix](https://search.nixos.org/packages) or similar.

https://semver.org/

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Yeah, I was under the understanding that we are using semantic versioning right now, and that we are in the pre-1.0 state.

**Comment by jnoortheen** [comment]
It is good to hear that it is under your radar. Sometime back my PROMPT were broke after upgrading.

**Comment by scopatz** [comment]
Yeah, I think that was a bug rather than intentional
