### ISSUE TITLE
First filling of CommandsCache takes around 60% of boot time

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3985]
Hi! We are the champions my snail! And we'll keep our conch till the end!

I've made some experiments to understand why empty xonsh has around 0.4s to boot on Ubuntu 20:
```python
cd /tmp
echo '$PROMPT="> "' > rc  # to disable default prompt
xonsh --rc rc --timings
#|-------------------------|-----------|-----------|
#|Event name               | Time (s)  | Delta (s) |
#|-------------------------|-----------|-----------|
#...
#|on_pre_prompt            |   0.376   |   0.000   |
#|-------------------------|-----------|-----------|
```

As result around 60% time (0.2s) takes reading 3k executable files from PATH in this loopster:

https://github.com/xonsh/xonsh/blob/ee46b17255bc30a383529bfbdbc87fd106446499/xonsh/commands_cache.py#L112-L118

I think this logic should be redesigned. 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Interesting fact:

If we wrap the code to timer:
```python
        t = time.time()
        allcmds = {}
        for path in reversed(path_immut):
            # iterate backwards so that entries at the front of PATH overwrite
            # entries at the back.
            for cmd in executables_in(path):
                key = cmd.upper() if ON_WINDOWS else cmd
                allcmds[key] = (os.path.join(path, cmd), alss.get(key, None))
        print(len(allcmds))
        print(time.time() - t)
```
And run xonsh:
```python
xonsh --rc rc --timings
#3384
#0.14377164840698242
```

But if we create distinct py file with the same code:
```
cat 1.py 
import os, time
from xonsh.platform import ON_WINDOWS, ON_POSIX, pathbasename
from xonsh.tools import executables_in
from xonsh.lazyasd import lazyobject
from xonsh.commands_cache import CommandsCache

t = time.time()

paths = os.environ['PATH'].split(':')
paths = CommandsCache.remove_dups(paths)
path_immut = tuple(x for x in paths if os.path.isdir(x))

alss = {f'a{i}':'qwe' for i in range(0,40)}

allcmds = {}
for path in reversed(path_immut):
    # iterate backwards so that entries at the front of PATH overwrite
    # entries at the back.
    for cmd in executables_in(path):
        key = cmd.upper() if ON_WINDOWS else cmd
        allcmds[key] = (os.path.join(path, cmd), alss.get(key, None))

t = time.time() - t

print(len(allcmds))
print(t)
```
We will have:
```python
3384
0.015847444534301758
```

0.14s vs 0.015s - why we can see so significant difference?

**Comment by anki-code** [comment]
@scopatz what do you think about difference above?

**Comment by scopatz** [comment]
Yeah, this does seems like an issue on certain platforms. What are the contents of snail.py?

**Comment by scopatz** [comment]
FWIW, I am not seeing these kinds of issues, but I think my PATH is much smaller

**Comment by anki-code** [comment]
@scopatz 

1. [snail.py is above](https://github.com/xonsh/xonsh/issues/3985#issuecomment-729916942)

    > But if we create distinct snail.py file with the same code:

2. The PATH directories is normal for Ubuntu + conda:

    ```python
    echo $PATH
    /opt/miniconda/bin:/opt/miniconda/condabin:/home/pc/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    ```

3. JFYI Python 3.8.2, xonsh from master

**Comment by anki-code** [comment]
I tried to repeat this in docker and on virtual ubuntu server but with no similar result.

On my local I see that the speed of the loop is different for shell type:
```
python snail.py
# 3177 files, 0.022s loop speed
xonsh --timings --no-rc --shell-type=readline
# 3177 files, 0.027s loop speed

# but:
xonsh --timings --no-rc
# 3177 files, 0.128s loop speed
```

I tried to install xonsh using local pip instead of conda but I see this big speed difference also.

This bug is abomination. 
I'm going to close this issue because don't know how to repeat by using docker and have no additional thoughts...

**Comment by anki-code** [comment]
After new experiments I've found that 50% of time (0.2s / 0.4s) takes conda init hook in xonsh. After disabling conda hook I got normal 0.2s speed start.
