### ISSUE TITLE
ssh interaction causes 100% CPU and growing memory usage (until out of memory)

### ISSUE THREAD

**Issue by n0x32schneider** [xonsh/xonsh#3999]
I am a little short on time, therefore I will omit some things, and fill out the blanks later, in case it is neccessary. This issue does not seem to be xonshs fault, but xonshs handling of it is problematic

## xonfig

<details>

+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.8.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+

</details>

## Expected Behavior
I am opening a ssh portforward into the environment running xonsh: ssh -L someport:addr:someport xonsh_host

The ssh open is done in a python subprocess call. When the python program finishes or is killed, the local ssh connection is closed (the sent signal does not change behaviour, I tried kill -1, -2, -3 so far).

What should happen: xonsh on the xonsh_host that was opened with the ssh call should be closed.

## Current Behavior

What does happen: xonsh on the xonsh_host stays active, occupies 100% CPU (around 0% before), and starts allocating memory until out of memory.

The error's cause is not the xonsh, but something related to ssh, I would assume.
I tested the same thing with fish shell, and there the shell also occupies the CPU and starts allocating memory, but the fish shell terminates after some time, instead of going on until out of memory.

I can fix the behaviour, by not allocating a terminal with the ssh call (ssh -N -L ..).
<details>

```
traceback
```

</details>

## Steps to Reproduce

Write a python script, that starts a ssh port forward in a subprocess (subprocess.run(["ssh",  "-L", "somep:someaddr:somep" ,"xonsh_host"]

Get the local ssh pid, and kill it.
-> xonsh instance on the xonsh_host starts described behaviour

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
It will be great to have repeatable test using docker container with xonsh and with ssh server. For example you can get docker-compose and Dockerfile for this from [xxh/xxh-dev](https://github.com/xxh/xxh-dev).

**Comment by anki-code** [comment]
I'm going to close this until we get repeatable step by step example.
