### ISSUE TITLE
Using Entrypoints to discover and load Xontribs

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4003]
# Feature Request
- Currently making a xontrib discoverable to users require making a PR to the main repo. This is different from other popular projects(pytest, flak8, etc.,). Can we start using setuptools' entrypoints group feature to discover xontribs ?

## Advantages
- no need for extra PR and complex xontribs loading mechanism
- Could use setuptools to find and load packages. 
    i. Currently it relies on the user knowing exactly what name to specify in the `xontrib load command`. Though the `xontrib-meta` provide the name of the module inside `xontribs`, it is still confusing how it gets loaded.

## Proposal
- we can support the existing mechanism as well as entrypoints while encouraging developers to migrate to entrypoints.

https://stackoverflow.com/questions/774824/explain-python-entry-points
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by agoose77** [comment]
The `setup.cfg` for xontribs might look something like:
```ini
[options.entry_points]
xonsh.xontrib = 
   a-cool-xontrib = a_cool_xontrib.name_of_a_callable
```

and the module itself would need a registration method:
```python3
def name_of_a_callable(xsh):
    pass
```

I believe that we would also want a configuration setting that disables this auto-loading, so that users can opt-out if they wish to. Given that this mechanism would require existing xontribs to opt-in, I propose that it become enabled by default.

**Comment by agoose77** [comment]
Additionally - we do need to be careful about performance. The `setuptools` discovery method is quite slow - see also https://entrypoints.readthedocs.io/en/latest/
