### ISSUE TITLE
rich's console.print not working in interactive mode

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4008]
rich - https://github.com/willmcgugan/rich

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.24               |
| Git SHA          | 74543ea9             |
| Commit Date      | Oct 10 15:12:47 2020 |
| Python           | 3.8.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.8                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.3                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | argcomplete          |
| xontrib 3        | autovox              |
| xontrib 4        | back2dir             |
| xontrib 5        | broot                |
| xontrib 6        | cmd_done             |
| xontrib 7        | commands             |
| xontrib 8        | hist_navigator       |
| xontrib 9        | jedi                 |
| xontrib 10       | kitty                |
| xontrib 11       | notifypy             |
| xontrib 12       | pdb                  |
| xontrib 13       | prompt_ret_code      |
| xontrib 14       | vox                  |
| xontrib 15       | voxapi               |
+------------------+----------------------+
```

</details>

## Expected Behavior
expected to print the colored text 
![image](https://user-images.githubusercontent.com/6702219/101597999-7e28d580-3a1d-11eb-9fd6-e9782a4aa97f.png)

## Current Behavior

Running this interactively 
```
$from rich import print
$print("[italic red]Hello[/italic red] World!", locals())
```
raises error

### Traceback (if applicable)

<details>

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/noor/.config/xonsh/xsh-src/xonsh/base_shell.py", line 362, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/home/noor/.config/xonsh/xsh-src/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/noor/.config/xonsh/.venv/lib/python3.8/site-packages/rich/__init__.py", line 43, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "/home/noor/.config/xonsh/.venv/lib/python3.8/site-packages/rich/console.py", line 1139, in print
    self._buffer.extend(new_segments)
  File "/home/noor/.config/xonsh/.venv/lib/python3.8/site-packages/rich/console.py", line 562, in __exit__
    self._exit_buffer()
  File "/home/noor/.config/xonsh/.venv/lib/python3.8/site-packages/rich/console.py", line 540, in _exit_buffer
    self._check_buffer()
  File "/home/noor/.config/xonsh/.venv/lib/python3.8/site-packages/rich/console.py", line 1271, in _check_buffer
    self.file.write(text)
  File "/home/noor/.config/xonsh/xsh-src/xonsh/base_shell.py", line 183, in write
    self.mem.write(s)
ValueError: I/O operation on closed file.
```

</details>

## Steps to Reproduce
```sh
$ from rich import print
$ print("[italic red]Hello[/italic red] World!", locals())
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
When I run:
```python
# pip install rich
from rich import print as pt
pt("[italic red]Hello[/italic red] World!", locals())
```
I have no colors or italic red in xonsh. 
I have colors and italic red in python.

**Comment by willmcgugan** [comment]
Author of Rich here. Can you run the following command (requires Rich v9.4.0) and paste the output here...

```
python -m rich.diagnose
```

**Comment by jnoortheen** [comment]
> Author of Rich here. Can you run the following command (requires Rich v9.4.0) and paste the output here...
> 
> ```
> python -m rich.diagnose
> ```

Sure. Here it is 
![image](https://user-images.githubusercontent.com/6702219/101985928-db888500-3cb0-11eb-90d4-2c954d5ccd9f.png)

it seems all OK here. 

When ran the same inside xonsh shell (it is like ipython)
![image](https://user-images.githubusercontent.com/6702219/101985973-138fc800-3cb1-11eb-9a70-4eacc7a6292e.png)

**Comment by anki-code** [comment]
>Author of Rich here. Can you run the following command (requires Rich v9.4.0) and paste the output here...
>python -m rich.diagnose

Hi! It's inspiring! My log:

<details>

![image](https://user-images.githubusercontent.com/1708680/101986082-d3264f00-3c9c-11eb-9f93-c74312566a6a.png)

</details>

I see additional interesting thing that if I repeat the running of rich there is I/O error.

**Comment by willmcgugan** [comment]
It looks like Rich has detected (incorrectly) that is not running on a terminal. I think this may be because Xonsh has wrapped sys.stdout with a proxy class (shell._TeeStd) that doesn't declare itself to be a terminal. The fix might be to add an `isatty` method to `TeeStd` that returns True. The Xonsh devs may be able to comment further.

The traceback may be a related issue. The Console class will hold on to the file object, which looks like it is closed after each line is execute. That I may be able to fix from the Rich side by not caching the file object. I'll consider that for the next release.

**Comment by jnoortheen** [comment]
Yes that seems to be the case. 
![image](https://user-images.githubusercontent.com/6702219/101988989-50fd5100-3cc3-11eb-8cc3-657a92f12300.png)

We can wait for core members to respond.

**Comment by anki-code** [comment]
It works now! Thanks!
