### ISSUE TITLE
prompt_ret_code: <xonsh.history.json.JsonCommandField object at 0x7fdce67b3310>

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#4011]
```
~/.local/xonsh/lib 🐚 false
~/.local/xonsh/lib [<xonsh.history.json.JsonCommandField object at 0x7fdce67b3310>]🐚
```
v0.9.24

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
@AstraLuma -- can you try current master?  I can't duplicate this error.

```
(base)   ~ $ xontrib load prompt_ret_code
(base)   ~ $ false
(base)   ~ [1]$
```

**Comment by AstraLuma** [comment]
Hm.

It reads like it's getting an unexpected type from the history module.

**Comment by AstraLuma** [comment]
No, using the file from `master` makes no change.

It produces this output whether the command succeeds or fails.

**Comment by anki-code** [comment]
I can't repeat this.

**Comment by anki-code** [comment]
Can't repeat this on xonsh 0.11
