### ISSUE TITLE
declutter and organise ENV variables based settings

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4014]
as of now the default variables are defined inside a big dict here `xonsh/environ.py:632`. It doesn't do any organisation of the variables. 

I want to organise them into groups like done in https://takoshell.org/documentation.html#section_27 . We can create a custom class (Settings) that gets value from env variables or return a default value. This singletons can be passed around/imported.

It can still work with existing code-base. We can also update the [documentation](https://xon.sh/envvars.html) page to show the variables under sub-headings. 

What do you think ?

**Comment by gforsyth** [comment]
Hey @jnoortheen -- this seems like a solid idea to me.
