### ISSUE TITLE
Ctrl+z seems not working

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4024]
I tried to suspend the `gitk` command using the shortcut `Ctrl+z` and it is not working as shown in the screenshot.

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.24               |
| Git SHA          | 0f6e1812             |
| Commit Date      | Dec 13 19:19:32 2020 |
| Python           | 3.8.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.8                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.3                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | argcomplete          |
| xontrib 3        | avox_poetry          |
| xontrib 4        | back2dir             |
| xontrib 5        | broot                |
| xontrib 6        | cmd_done             |
| xontrib 7        | commands             |
| xontrib 8        | fzf-widgets          |
| xontrib 9        | hist_navigator       |
| xontrib 10       | jedi                 |
| xontrib 11       | kitty                |
| xontrib 12       | notifypy             |
| xontrib 13       | powerline3           |
| xontrib 14       | prompt_ret_code      |
| xontrib 15       | vox                  |
| xontrib 16       | voxapi               |
+------------------+----------------------+

```

</details>

## Expected Behavior
it should be suspended to background

## Current Behavior

![image](https://user-images.githubusercontent.com/6702219/102539357-965ebb80-40d3-11eb-9ffa-0d706250fd05.png)

the control wasn't returned to shell.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
upon inspecting, 
when I manually triggered TSTP with  
`kill -20 <pid>` it cause the program to pause. 

Then again running `bg` resulted in error

<details>
 <summary>traceback</summary>
Traceback (most recent call last):
  File "/data/src/shell/xsh-src/xonsh/procs/proxies.py", line 508, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
        │      │          │         │          │          │     └ SubprocSpec([], ProcProxyThread, stdin=None, stdout=<_io.TextIOWrapper name=8 mode='w' encoding='UTF-8'>, stderr=<_io.TextIOWrap...
        │      │          │         │          │          └ SubprocSpec([], ProcProxyThread, stdin=None, stdout=<_io.TextIOWrapper name=8 mode='w' encoding='UTF-8'>, stderr=<_io.TextIOWrap...
        │      │          │         │          └ <_io.TextIOWrapper name=10 encoding='utf-8'>
        │      │          │         └ <_io.TextIOWrapper name=8 encoding='utf-8'>
        │      │          └ None
        │      └ <ProcProxyThread(Thread-64, started 140048146101824)>
        └ <ProcProxyThread(Thread-64, started 140048146101824)>
  File "/data/src/shell/xsh-src/xonsh/procs/proxies.py", line 300, in proxy_two
    return f(args, stdin)
           │ │     └ None
           │ └ []
           └ <function bg at 0x7f5fabd95b80>
  File "/data/src/shell/xsh-src/xonsh/jobs.py", line 445, in bg
    res = resume_job(args, wording="bg")
          │          └ []
          └ <function resume_job at 0x7f5fabd95a60>
  File "/data/src/shell/xsh-src/xonsh/jobs.py", line 424, in resume_job
    pipeline.resume(job)
    │               └ {'cmds': (['gitk'],), 'pids': [142233], 'obj': <PopenThread(Thread-28, stopped 140048607471168)>, 'bg': False, 'pipeline': , 'pg...
    └ 
  File "/data/src/shell/xsh-src/xonsh/procs/pipelines.py", line 470, in resume
    self.end(tee_output=tee_output)
    │                   └ True
    └ 
  File "/data/src/shell/xsh-src/xonsh/procs/pipelines.py", line 429, in end
    self._end(tee_output=tee_output)
    │                    └ True
    └ 
  File "/data/src/shell/xsh-src/xonsh/procs/pipelines.py", line 437, in _end
    for _ in self.tee_stdout():
  File "/data/src/shell/xsh-src/xonsh/procs/pipelines.py", line 343, in tee_stdout
    for line in self.iterraw():
  File "/data/src/shell/xsh-src/xonsh/procs/pipelines.py", line 218, in iterraw
    stdout = NonBlockingFDReader(stdout.fileno(), timeout=timeout)
    │        │                   │                        └ 0.0001
    │        │                   └ <_io.BufferedReader name=4>
    │        └ <class 'xonsh.procs.readers.NonBlockingFDReader'>
    └ <_io.BufferedReader name=4>
ValueError: I/O operation on closed file
</details>

then it tries to restart the shell in a never ending loop. 

so two issues here

1. ctrl+z not triggering TSTP 
2. bg results in error

**Comment by alvarv** [comment]
I have experienced possibly related problems. For example:
```sh
~ $ emacs
[Ctl-Z]
~$ bg #does not return, as it should. Instead, one must hit Ctl-Z again to recuperate the prompt
``` 
After that:
```sh
~ $ jobs
[1]+ stopped: emacs & (103793)
```
when emacs is actually running in the background (one can continue editing...).

**Comment by jnoortheen** [comment]
Yes I checked with vim, that works too. They are marked as non-threadable. But GUI programs that started as a fg process not gets suspended nor the control given back to shell.

**Comment by Cheaterman** [comment]
Today I can't exit `less` when doing `git diff`. Probably related. Will have to rollback to whichever version worked last...

**Comment by yaxollum** [comment]
@Cheaterman Have you tried adding `$THREAD_SUBPROCS=False` to your `.xonshrc`?

**Comment by brechtm** [comment]
Ctrl-Z doesn't seem to be able to bring any application to the background for me either (xonsh 0.9.27 on macOS). Tested with gitk, less, ncdu, python.

**Comment by Cheaterman** [comment]
> @Cheaterman Have you tried adding `$THREAD_SUBPROCS=False` to your `.xonshrc`?

I confirm that your workaround is entirely correct! Even in a running session, before setting it you need to `killall less`, but afterwards it works like a charm. Give it a try too, @brechtm ; and perhaps we need to set this as default, until someone can fix the real issue with threaded subprocesses (or whatever is going on here) ?

**Comment by daniel-shimon** [comment]
Hi! 
All these issues are indeed because xonsh tries to capture the output of interactive processes. 
Turning `THREAD_SUBPROCS` off kinda fixes it but it isn't good either, since it means `$(...)` doesn't always work.
We've decided to add a new `XONSH_CAPTURE_INTERACTIVE` variable that will give us better control and will be False by default - see #4283

**Comment by Cheaterman** [comment]
Thanks a lot @daniel-shimon, I didn't realize this was a WIP :-) I'll follow closely and fix my .xonshrc once #4283 is merged. Thanks again for the heads up!
