### ISSUE TITLE
Pasting multiple lines breaks indentation

### ISSUE THREAD

**Issue by sirex** [xonsh/xonsh#4043]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.9.1           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.8           |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | manjaro         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

## Expected Behavior

I'm trying to paste following code into xonsh prompt:

```python
for i in range(2):
    for j in range(2):
        print(j)
    print(i)
print('done')
```

And I expect it to be pasted like this:

```python
> for i in range(2):
.     for j in range(2):
.         print(j)
.     print(i)
.  print('done')
```

Or at least, there should be an option to turn auto indentation on and off (ipython has `--no-autoindent` flag):

```python
> $XONSH_AUDOINDENT = False
> for i in range(2):
.     for j in range(2):
.         print(j)
.     print(i)
.  print('done')
```

## Current Behavior

Following code gets pasted:

```python
> for i in range(2):
.         for j in range(2):
.                     print(j)
.                         print(i)
.                         print('done')
```

With a broken indentation. The closest thing I could find to make this work is running xonsh with `--shell-type readline`, which works like this:

```python
> for i in range(2):
.
    for j in range(2):
.
        print(j)
.
    print(i)
.
print('done')
.
```

Lines are a bit off, but when I hit ENTER, pasted code works as expected.

Strangely following does not work too:

```python
> $SHELL_TYPE = 'readline'
> for i in range(2):
.         for j in range(2):
.                     print(j)
.                         print(i)
.                         print('done')
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @sirex -- I'm not sure if that's an issue with our usage of `prompt_toolkit` or with `prompt_toolkit` itself.  Will require a bit more investigation.
In the medium-term, when I do things like this, I hit `ctrl-x ctrl e` to open up an editor in my terminal session, paste in there, then quit out.

In re: your last point, `$SHELL_TYPE` won't change the currently running `xonsh` process unless you set it in your `xonshrc` or pass it as a startup arg to `xonsh` itself.

**Comment by anki-code** [comment]
I'm using Konsole and I have no problems with pasting multiline code. This issue looks like depend to the terminal and I'm going to close this.

PS: `ctrl-x ctrl e` - nice workaround, I will put it to [xonsh-cheatsheet](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md) thanks!
