### ISSUE TITLE
completion: begidx splits quoted values

### ISSUE THREAD

**Issue by rsteube** [xonsh/xonsh#4046]
The completion does a [simple rfind](https://github.com/xonsh/xonsh/blob/master/xonsh/ptk_shell/completer.py#L43) to set begidx. But this ignores quotation which is [needed in xonsh](https://xon.sh/tutorial_subproc_strings.html#no-escape) for values containing space.

## Expected Behavior
```sh
example multiparts --at "third with space@"<TAB>
# begidx=24
```

## Current Behavior
```sh
example multiparts --at "third with space@"<TAB>
# begidx=36
```

## Steps to Reproduce
Invoke completion on a quoted value containing space.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by rsteube** [comment]
this currently seems to work:

```python
#!/usr/bin/env python
from shlex import split
line = "example multiparts --at \"third with space@"
endidx = len(line)

words=""
wordsNonPosix=""
try:
    words=split(line[0:endidx] + "_") # ensure last word is empty when ends with space
    wordsNonPosix=split(line[0:endidx], posix=False)
except:
    try:
        words=split(line[0:endidx] + '"' + "_") # ensure last word is empty when ends with space
        wordsNonPosix=split(line[0:endidx] + '"', posix=False)
        wordsNonPosix[-1]= wordsNonPosix[-1][:-1]
    except:
        words=split(line[0:endidx] + "'" + "_") # ensure last word is empty when ends with space
        wordsNonPosix=split(line[0:endidx] + "'", posix=False)
        wordsNonPosix[-1]= wordsNonPosix[-1][:-1]

words[-1]=words[-1][0:-1]
if len(words[-1]) != 0:
    begidx = endidx
    for word in reversed(wordsNonPosix):
        begidx = begidx - len(word)
        print(word)
        print(begidx)
        print(line[begidx])
        if line[begidx-1] == " ":
            break
print(begidx)

```

**Comment by anki-code** [comment]
Hi! PR is welcome!

**Comment by daniel-shimon** [comment]
Hi! Sorry to be late to the party, I'm currently working on a parser for the completion system in https://github.com/xonsh/xonsh/pull/4017

That PR should eliminate this issue and other similar ones, can you check it out to see if it handles your case?

**Comment by rsteube** [comment]
@daniel-shimon it might, but unless the old completer api is replaced completely begidx probably should be fixed anyway

My personal need [for this](https://github.com/rsteube/carapace/blob/master/example/cmd/_test/xonsh.py) is the following:
- correct begidx so that completions have the correct `prefix_len`
- line correctly splitted into separate arguments (to be passed to a command)
- cutting off/supporting piped command line like `echo | sed -<TAB>` (which i'm seeing in your comment - i am not doing that correctly at the moment)

**Comment by daniel-shimon** [comment]
@rsteube so the parsed completion context handles all these cases correctly using a real PLY parser.
Corrently the only completer that seems tricky to move to the new API is `complete_path`, which doesn't use `prefix_len` too much and actually parses string literals correctly.
Other than that all parsers will use the new API. 

After that PR is merged, you would be able to use the completion context in your project

**Comment by rsteube** [comment]
@daniel-shimon Nice. `complete_path` isn't a problem for me as i'm doing that myself by now.

**Comment by anki-code** [comment]
Hi @rsteube and @daniel-shimon !
Should we close this issue and 4103 because we have 4017?

**Comment by rsteube** [comment]
Yes, i would say so.
