### ISSUE TITLE
Uptime function on FreeBSD broken

### ISSUE THREAD

**Issue by yggdr** [xonsh/xonsh#4048]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.8.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

## Expected Behavior
Xonsh starts without error messages.

## Current Behavior
Xonsh starts with an error caused by the `xoreutils.uptime.uptime` function.

### Traceback (if applicable)

<details>

```
❯ env XONSH_DEBUG=1 xonsh
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/yggdrasil/.asdf/installs/python/3.8.6/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/home/yggdrasil/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/json.py", line 137, in run
    files = self.files(only_unlocked=True)
  File "/usr/home/yggdrasil/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/json.py", line 180, in files
    boot = uptime.boottime()
  File "/usr/home/yggdrasil/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/xoreutils/uptime.py", line 280, in boottime
    up = uptime()
  File "/usr/home/yggdrasil/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/xoreutils/uptime.py", line 265, in uptime
    or _uptime_linux()
  File "/usr/home/yggdrasil/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/xoreutils/uptime.py", line 56, in _uptime_linux
    if xp.LIBC.sysinfo(buf) < 0:
AttributeError: 'NoneType' object has no attribute 'sysinfo'
yggdrasil@midgard /usr/home/yggdrasil master $

```

</details>

In this traceback we can see that the `uptime` function incorrectly falls through to the `_uptime_linux` function, because the `_uptime_bsd` function fails on FreeBSD for two reasons:
1. It cannot access `xp.LIBC.sysctlbyname` because in `xonsh.platform.LIBC` the `ON_BSD` branch tries to load libc by calling `ctypes.CDLL("libc.so")`. On FreeBSD `/usr/lib/libc.so` is a text file (an LD script?) that `ctypes` can't load. So either use `ctypes.util.find_library`, but that would start another process which according to the comments in the function is undesirable (because of performance? The comments are not very clear here). Or hardcode a `ON_FREEBSD` special case and load `libc.so.7`.
2. Afterwards `_uptime_bsd` tries to run `sysctlbyname` twice and gives it a string as a first parameter, but it needs bytes. So adding a `b` before the string is necessary.

After doing both those things, xonsh starts up. I can do that in a PR if the devs decide on point 1 which way to go.

## Steps to Reproduce
Just run `xonsh` on FreeBSD. In my case, `xonsh` was installed via `pipx`, which in turn came from FreeBSD's packages.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @yggdr -- thanks for reporting!  I know we fall down on some BSD stuff, sorry about that!

Before we start trying to fix `xoreutils` -- we've been thinking of swapping in `cmdix` for the `xoreutils` functionality.  Can you check if the `uptime` functionality in `cmdix` works?

**Comment by yggdr** [comment]
I'm assuming you mean `https://github.com/jaraco/cmdix`? I had some trouble setting that one up in a venv with the venv behaving very strangely. But after looking over the code for a bit, it looks very Linux-only (scanning /proc with no fallback)

**Comment by gforsyth** [comment]
Hey @yggdr -- yes I did mean that.  Sorry, should've provided a link.

Hmm, well, that's a bummer.
We don't have any unit tests for BSD, so I'm not sure what makes the most sense here.  I'm inclined to special-case it with an `ON_FREEBSD` as you suggest.

**Comment by yggdr** [comment]
I've created a PR with the hardcoded workaround fix.

Btw, like an idiot, I completely forgot to look into FreeBSD's ports tree to see how they managed to make this work. They have also patched the same two places, but went with the `find_library` route: https://svnweb.freebsd.org/ports/head/shells/xonsh/files/.

**Comment by anki-code** [comment]
Hi @yggdr! I see the PR was merged. Can we close this issue?

**Comment by yggdr** [comment]
Yes, seems to work in the new releases, closing.
