### ISSUE TITLE
Using Xonsh appimage as default shell causes a weird behavior with directories

### ISSUE THREAD

**Issue by SpotHound** [xonsh/xonsh#4050]
Hello guys! 

I've been using Xonsh for a few months in Arch Linux. When Arch Linux updated the default Python version to 3.9 and I upgraded to it, I started having some issues with Xonsh, so I decided to move to an appimage installation to have an isolated immutable python installation for Xonsh.

I'm learning more about app images but I have detected something with the xonsh appimage. If I use it as a default shell (that is, I add it's the path to `/etc/shells` and configure my user to use it with `chsh`), the following happen:

1. In file browser such as Dolphin, when I open a terminal it no longer moves to the open directory (which is the default behaviour with any shell, Xonsh included when it is installed as a package and not in an appimage).
2. When I have a terminal open, for example on the terminator and I decide to split it, the new terminal doesn't start in the same directory than the previous (which is the default behaviour with any shell, Xonsh included when it is installed as a package and not in an appimage).

I've decided to get back using Xonsh Pacman package instead of the appimage for this reason, but I'm curious about the cause of this issue. I open this issue just to see if anyone else has experimented this and if someone have any idea on what could be happening with Xonsh appimage and if this could be solved.

Best regards!

p.s For those using Arch Linux and Xonsh as the default shell, if you read this I would like to ask you how do you use Xonsh in the arch to avoid problems with python 3.9, I'm currently installing the pip package on a 3.8.6 pyenv but this gives me some troubles so I'm looking for another better approach. 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @SpotHound !  
I use arch also, but I'm usually running on master and not using the system package.  I didn't realize we'd been moved into `community`, so that's exciting!  I would've suggested that the AUR recipe pin to python 3.8, but that's trickier now that it's in the main package index.

@anki-code -- do you have any input on the appimage questions?

**Comment by anki-code** [comment]
Hi! 
If we download the appimage and add it to PATH we see that it works correct:
```bash
# bash
cd /tmp
wget https://github.com/xonsh/xonsh/releases/download/0.9.24/xonsh-x86_64.AppImage
mv xonsh-x86_64.AppImage xon
chmod +x xon
export PATH=/tmp:$PATH
xon -c 'pwd'
# /tmp
cd /
xon -c 'pwd'
# /
```
The question is how Dlophin or terminal emulator run the shell?

> to avoid problems with python 3.9

Maybe you can try pipx (https://pipxproject.github.io/pipx/):

```bash
pip install pipx
pipx install --python python3.8 xonsh
pipx run xonsh 
# or add /home/$USER/.local/bin to PATH (/etc/shells) to running just xonsh
```
It's my assumption I wasn't try this.

**Comment by SpotHound** [comment]
Ey! Thanks for your answers, I'm going to check this out as soon as possible. Regarding the question about Dolphin, actually, I didn't explain myself, actually, Dolphin starts the shell in the right directory. The problem with appimage is that when you (graphically) changes a directory, konsole is supposed to run a cd command in the shell so it follows the graphic interface. This works with regular xonsh but when I have the appimage installed the cd command isn't executed at all. 

As I said, as soon as I have some time I will try your suggestions. Thank you both.

**Comment by SpotHound** [comment]
Hello guys! I've tried the installation with pipx and it works like a charm! I've still not had time to check and better describe the problem with the appimage, but from now I can say that this option is the better one I've found!

Of course, I still using appimages for other purposes (for example, to use it with xxh) but I¡ll keep this one for my main shell :)

Maybe it would be interesting to improve the documentation by adding some info about this! If you agree with this I could spend some time to make some improvements and open a PR : ) 

Thank you both again!

**Comment by gforsyth** [comment]
> Maybe it would be interesting to improve the documentation by adding some info about this! If you agree with this I could spend some time to make some improvements and open a PR : )

More documentation on installation options is always welcome :smile:
