### ISSUE TITLE
ImportError: cannot import name 'load_emacs_shift_selection_bindings'

### ISSUE THREAD

**Issue by mzechmeister** [xonsh/xonsh#4055]
I installed `xonsh` on opensuse with `pip3 install --user xonsh`

Attempting to start it `python3 -m xonsh` or `xonsh` results in
```
  File "/home/user/.local/lib/python3.6/site-packages/xonsh/ptk_shell/shell.py", line 26, in <module>
    from prompt_toolkit.key_binding.bindings.emacs import (
ImportError: cannot import name 'load_emacs_shift_selection_bindings'
Xonsh encountered an issue during launch
Failback to /bin/bash
```

`xonsh` starts after commenting out essentially those two lines
https://github.com/xonsh/xonsh/blob/80aca856e46f2485786ff7eb2c2ba1cffd1b7c83/xonsh/ptk_shell/shell.py#L26-L28

https://github.com/xonsh/xonsh/blob/80aca856e46f2485786ff7eb2c2ba1cffd1b7c83/xonsh/ptk_shell/shell.py#L177-L179

**Comment by gforsyth** [comment]
Thanks for reporting @mzechmeister!  Can you try upgrading `prompt_toolkit` and see if that helps?  
`pip3 install --user -U prompt_toolkit`

**Comment by mzechmeister** [comment]
Yes, upgrading from 2.0.6 to 3.0.10 solves the issue.

Maybe the "not working" moment can be avoided via the installer script or via optional imports (I don't use emacs).

**Comment by gforsyth** [comment]
we have a lot of gates -- `prompt_toolkit` isn't a hard dependency, but if it's present, we try to use it.  we can probably add an additional import check to cover this situation, where it wasn't installed as a `xonsh` dependency (which would've bumped the version up) but was already present.

in re: `emacs*bindings` -- those are the default in any posix terminal emulator.  You can go to the beginning of the line with Ctrl-a, or the end with Ctrl-e, these are all emacs bindings.  There are also vim bindings available.  But it's referring to the keyboard shortcuts, not the editor itself.
