### ISSUE TITLE
Shell should filter out " characters when parameters are specified as --parameter="value"

### ISSUE THREAD

**Issue by maresb** [xonsh/xonsh#4061]
There seems to be a bad interaction between `xonsh` and `git-lfs-migrate`. I'm not sure on which side the problem is, so I'm opening an issue in both projects. (Apologies in advance to the innocent.)

https://github.com/git-lfs/git-lfs/issues/4372

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.8.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | True            |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

## Expected Behavior

The following command is designed to rewrite the history of a git repository so that specified files are stored in a separate storage for large files.

Running from within the xonsh shell, the following command works as expected:
```bash
git lfs migrate import --everything --include "*.txt"
```

Now all files with the `.txt` extension appear in the LFS store.

## Current Behavior

Using bash, the following command is equivalent. In xonsh it is not.

This command fails to add any files to LFS (note the `=` after `--include`):
```bash
git lfs migrate import --everything --include="*.txt"
```

The equals sign is suggested by [the documentation](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn), so it really should work.

I expect bash and xonsh to have the same behavior when the `=` is included.

## Steps to Reproduce

For a complete example shell session, see https://github.com/git-lfs/git-lfs/issues/4372 .

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by maresb** [comment]
On the suggestion of the git-lfs developers, I made `foo.sh` containing
```bash
#!/bin/bash
echo $@
echo $0
echo $1
echo $2
echo $3
```
I am getting in bash
```bash
$ ./foo.sh abc --include="*.txt" '*.dat'
abc --include=*.txt *.dat
./foo.sh
abc
--include=*.txt
*.dat
```
however xonsh produces
```bash
$ ./foo.sh abc --include="*.txt" '*.dat'
abc --include="*.txt" *.dat
./foo.sh
abc
--include="*.txt"
*.dat
```
#### Note how xonsh fails to strip the `"` around `*.txt`.

Is this expected behavior?

**Comment by gforsyth** [comment]
Hey, thanks for reporting @maresb !

We use quotes to escape certain characters (like spaces) in lieu of backslashes the way `bash` and other posix shells do, but I think that when passing in arguments to a subprocess like this we should probably be stripping out the quotes even if they are within a single argument.  

In the interim, it looks like removing the `=` is hopefully not a too annoying workaround.

cc @scopatz who can almost certainly provide more context

**Comment by maresb** [comment]
Thanks so much for the answer! If @scopatz agrees that the quotes should be stripped, then I'll close the issue in git-lfs.

The workaround is absolutely no problem for me. I really love xonsh, and I find it totally worthwhile, but occasionally it's brutal to have these subtle differences with bash. In this particular case it took me several hours before I suspected that xonsh could be at fault. Since it was my first time using `git-lfs-migrate` I was convinced that I was using it improperly. Next I was convinced that there was a bug in `git-lfs-migrate` with parsing the quotes.

**Comment by gforsyth** [comment]
> but occasionally it's brutal to have these subtle differences with bash

Yeah, sorry about that.  We believed (and believe) that there were important changes to make to the way a shell should act, but there are definitely some very frustrating edge cases like this one.

**Comment by anki-code** [comment]
@maresb take a look at this answer - https://stackoverflow.com/a/64414157/14470020 - it helps to understand/debug the cases around arguments. It should help to learning :)

**Comment by maresb** [comment]
Hi @anki-code, thank you for the link, it is really insightful!

It seems that you are subtly suggesting that this is the proper behavior, and that I must adapt my commands accordingly. I will thus close this issue.

**Comment by anki-code** [comment]
Related: #3541

**Comment by maresb** [comment]
For reference, and straight to the point, [Tutorial: Subprocess Strings](https://xon.sh/tutorial_subproc_strings.html)
