### ISSUE TITLE
Chaining does not work on captured subprocess

### ISSUE THREAD

**Issue by elbehery95** [xonsh/xonsh#4072]
Non captured mode:

```py
ls ; echo ls

# ls executed then echo
```
Captured sub-process: 
```py
ret = $(ls ; echo ls)
ls: cannot access ';': No such file or directory
ls: cannot access 'echo': No such file or directory
```

Other chain operators like ``&&`` works only on the non captured mode

**Comment by gforsyth** [comment]
Thanks for reporting @elbehery95 -- I can confirm the issue.  This should be resolvable with some tweaks to the parser.

**Comment by jnoortheen** [comment]
closing this on behalf of #4020
