### ISSUE TITLE
Locally installed xonsh is slower by several orders of magnitude

### ISSUE THREAD

**Issue by carmenbianca** [xonsh/xonsh#4080]
## xonfig

<details>

xonfig of PyPI-installed xonsh
```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.26               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.10.0               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.14               |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.4                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | vox                  |
| xontrib 2        | voxapi               |
+------------------+----------------------+
```

xonfig of locally installed xonsh
```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.25.dev3          |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 14:58:58 2021 |
| Python           | 3.10.0               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.14               |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.4                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | vox                  |
| xontrib 2        | voxapi               |
+------------------+----------------------+
```

</details>

## Expected Behavior

When I install xonsh via `pip install .` inside of the Git source tree, I expect the same speed as when I installed xonsh via `pip install xonsh`.

## Current Behavior

xonsh installed via `pip install .` is heaps slower. `python -m xonsh run-tests.xsh test` is slower by several orders of magnitude.

Because I don't want to wait for the entire suite to finish, here's a timing comparison for a single test file:

- PyPI-installed `pytest tests/test_aliases.py`: 0.90s
- Locally installed `pytest tests/test_aliases.py`: 167.02s

## Steps to Reproduce

```bash
$ cd Projects/xonsh
$ git checkout 71fe9014  # Make sure we're on the same commit!
$ vox create xonsh-slow
$ vox workon xonsh-slow
$ pip install -r requirements/development.txt
$ pip install -r requirements/tests.txt
$ # Locally install xonsh and test it
$ pip install .
$ xonsh
$ python -m xonsh run-tests.xsh test
# This is very slow
^C
$ exit
$ # Install xonsh via PyPI and test it
$ pip uninstall xonsh
$ pip install xonsh
$ xonsh
$ python -m xonsh run-tests.xsh test
# This is not slow
$ exit
```

## More information

When I launch xonsh and interrupt it, I inevitably get this exception:

```
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/parsers/base.py", line 496, in parse
    time.sleep(0.01)  # block until the parser is ready
KeyboardInterrupt
```

Full traceback:

<details>

```
^CTraceback (most recent call last):
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 22413, in main
    args = premain(argv)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 22349, in premain
    env = start_services(shell_kwargs, args)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 22299, in start_services
    xonshrc_context(rcfiles=rc, execer=execer, ctx=ctx, env=env, login=login)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 17893, in xonshrc_context
    status = xonsh_script_run_control(rcfile, ctx, env, execer=execer, login=login)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 17940, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 3218, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 3123, in run_compiled_code
    func(code, glb, loc)
  File "/var/home/carmenbianca/.xonshrc", line 10, in <module>
    aliases["gpg"] = "gpg2"
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 18910, in __setitem__
    elif isexpression(val):
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 7555, in isexpression
    node = builtins.__xonsh__.execer.parse(node, ctx, *args, **kwargs)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 21416, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/__amalgam__.py", line 21540, in _parse_ctx_free
    tree = self.parser.parse(
  File "/var/home/carmenbianca/.virtualenvs/xonsh3.10/lib64/python3.10/site-packages/xonsh/parsers/base.py", line 496, in parse
    time.sleep(0.01)  # block until the parser is ready
KeyboardInterrupt
```
</details>

This suggests to me that the parsing is—for one reason or another—immensely slow. I just don't know why.

This bug is preventing me from tinkering on xonsh for Fedora packaging; I wish I had the patience of a saint :p

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @carmenbianca !

This _seems_ like the parser table isn't being properly generated/stored during local installation.
And that would force it to regenerate before every test.

Could you try doing a `python setup.py install` locally and checking the output to see if there are messages about the parser table location? 

It used to be that a pip install locally would discard the parser table but I thought that had been fixed

**Comment by carmenbianca** [comment]
[Output of `python setup.py install > out.txt 2> out.txt`](https://gist.github.com/carmenbianca/36297a5631016650a22fbb30f6ef9e54)

There's no difference in speed between `python setup.py install` and `pip install .`.

I'm not entirely certain how to spot the error in the output.

**Comment by gforsyth** [comment]
Ok, two things to check.  First, in the `site-packages/xonsh` directory within your venv, is there a `parser_table.py` file?

Second, I don't know why it should make a difference, but could you see if this difference is also noticeable on Python 3.8?

**Comment by carmenbianca** [comment]
>  First, in the site-packages/xonsh directory within your venv, is there a parser_table.py file?

Exists. See https://gist.github.com/carmenbianca/5958aec7a71d94719f055442a4c1854b

> Second, I don't know why it should make a difference, but could you see if this difference is also noticeable on Python 3.8?

No difference. Frustrating, but thanks a lot for the help :)

---

I've also tried doing `python setup.py sdist; pip install dist/*.tar.gz` on the assumption that an sdist is uploaded to PyPI, but no difference also.

**Comment by gforsyth** [comment]
> No difference. Frustrating, but thanks a lot for the help :)

I wonder if the new Python parser and our PLY parser are getting into a fight.  The sdist on PyPI was probably generated on my machine, running on 3.8.  So here's a terrible thing to try: install xonsh from source in your 3.10 environment.  Then copy the `parser_table.py` file from the 3.8 environment to into the 3.10 `site-packages/xonsh` directory and see if that fixes the performance issues

**Comment by carmenbianca** [comment]
I've [created a gist](https://gist.github.com/carmenbianca/fbc228dee757bda13a4e6935077085b8) with a heap of parser tables.

Sample file name: py3.8-local-xonsh-parsers-parser_table.py

File name explained: Python 3.8, locally installed using `pip install .`, located in directory `xonsh/parsers`, file name `parser_table.py`.

In doing this exercise, I discovered one strange thing: locally installed xonsh has both a `site-packages/xonsh/parser_table.py` and a `site-packages/xonsh/parsers/parser_table.py`. These files are **not identical**. Pip-installed xonsh only has `site-packages/xonsh/parser_table.py`.

>  So here's a terrible thing to try: install xonsh from source in your 3.10 environment. Then copy the parser_table.py file from the 3.8 environment to into the 3.10 site-packages/xonsh directory and see if that fixes the performance issues

I did this several ways.

First: Install xonsh from source in 3.8 venv. Copy the 3.8 PyPI parser_table.py into `site-packages/xonsh`. Then check the speed. Result: It's fast again!

Second: Install xonsh from source in 3.10 venv. Copy the 3.8 PyPI parser_table.py into `site-packages/xonsh`. Then check the speed. Result: It's fast again!

Second: Install xonsh from source in 3.10 venv. Copy the 3.10 PyPI parser_table.py into `site-packages/xonsh`. Then check the speed. Result: It's fast again!

I have not touched `site-packages/xonsh/parsers/parser_table.py` at all. Not sure what that's doing there.

Also, in case there was a miscommunication: Locally installing xonsh using a Python 3.8 venv **is still slow**.

---

Conclusion: Fedora's version of Python (be it 3.8 or 3.10) is incapable of correctly generating `parser_table.py`. I have no idea what that's about.

---

To make sure that conclusion is halfway right, I created a Debian 10 Podman container, installed the necessary packages for Python development, cloned the xonsh repo, and did `pip install .`. This installation of xonsh is fast. And interestingly, it does not have `site-packages/xonsh/parsers/parser_table.py`.

**Comment by carmenbianca** [comment]
Oh, huh, late observation. I diffed `python3.8/site-packages/xonsh/parsers/parser_table.py` against the table shipped on PyPI: They're **identical**.

**Comment by carmenbianca** [comment]
… Close this issue. I did a `git clean -xf` to start fresh in the repo---I've had this repo on my file system for a long time. It removed:

```
Removing xonsh/__amalgam__.py
Removing xonsh/completers/__amalgam__.py
Removing xonsh/dev.githash
Removing xonsh/history/__amalgam__.py
Removing xonsh/parser.out
Removing xonsh/parsers/parser.out
Removing xonsh/procs/__amalgam__.py
Removing xonsh/prompt/__amalgam__.py
```

and everything works again. So sorry for wasting your time @gforsyth, and thanks nevertheless for the help :)

**Comment by gforsyth** [comment]
oh, wild!  That's ok!  This _will_ happen to someone else so it's super helpful to have a possible resolution here!
