### ISSUE TITLE
screenshots in landing page

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4083]
Great work on landing page :clap: 

just a small thing, would it be possible to merge the screenshots as a slideshow in the about page itself. As of now the **screenshots seems to taking so much space** and also one needs to zoom in to view get detail. 
![image](https://user-images.githubusercontent.com/6702219/107113387-a9486d80-6884-11eb-84b8-b957928ae330.png)
![image](https://user-images.githubusercontent.com/6702219/107113469-207e0180-6885-11eb-81c9-ce64ca3e5a7d.png)

I am talking about making the image a slideshow and putting the screenshot images here with the current option to zoom in on click and see all of them at bottom after zoomin. Otherwise just one image visible with option to move by dots. 

@gforsyth is it possible to enable Github discussion for this repo? we could have a forum for questions like this :)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
I suggest to use https://xonsh-landing.github.io/ as landing page.
