### ISSUE TITLE
Vi mode doesn't work with async prompt enabled

### ISSUE THREAD

**Issue by tejasvi** [xonsh/xonsh#4088]
It's likely an issue with vi-mode though I am not sure. Feel free to close this issue if that is the case.

https://github.com/t184256/xontrib-prompt-vi-mode/issues/9

**Comment by anki-code** [comment]
Hi! The ENABLE_ASYNC_PROMPT feature is fresh feature and I suppose the xontrib just not implemented the support so I'm going to close this issue. Feel free to reopen if you'll get the comments from xontrib maintainer.
