### ISSUE TITLE
How exactly @$() gets parsed?

### ISSUE THREAD

**Issue by tejasvi** [xonsh/xonsh#4094]
From the [docs](https://xon.sh/tutorial.html#command-substitution-with) `@$(cmd)` seems to be syntactic sugar for `@([x.strip() for x in $(cmd).split()])`. But with fzf, only the expanded form works.
`vi @([x.strip() for x in $(fzf).split()])`: works
`vi @$(fzf)`: Freezes the terminal and on `ctrl-c` gives `RecursionError`. https://dpaste.com/9BD6JPMAU

Clearly there are some implementation differences between the two. Where can I find the actual implementation of `@$()`?

**Comment by anki-code** [comment]
> Where can I find the actual implementation of @$()?

1. `@$(` is `atdollar_lparen` in the xonsh parser:

https://github.com/xonsh/xonsh/blob/c4e7843598201236307352b1db77e53c14ae9ade/xonsh/parsers/base.py#L396

2. Find parser function by the `atdollar_lparen`:

https://github.com/xonsh/xonsh/blob/c4e7843598201236307352b1db77e53c14ae9ade/xonsh/parsers/base.py#L3233-L3246

3. Then `__xonsh__.subproc_captured_inject` is what we need:

https://github.com/xonsh/xonsh/blob/c4e7843598201236307352b1db77e53c14ae9ade/xonsh/built_ins.py#L172-L184

Enjoy ;)
