### ISSUE TITLE
New versions tagged in repository before version, changelog updates

### ISSUE THREAD

**Issue by chronitis** [xonsh/xonsh#4095]
The tags for 0.9.25 and .26 are associated with the last commit _before_ merging the news, updating authors and updating the version. Eg, tag 0.9.26 points to https://github.com/xonsh/xonsh/commit/d3eda8e90bafe4edfc712c1038dec4b8267280e0 at which point `xonsh/__init__.py` still identifies itself as version 0.9.25. This has changed since 0.9.24, which was tagged after the version bump, etc. Is this intentional?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
There's something screwed up with the rever release and I don't have the cycles to fix it right now.  Thanks for reporting the issue.

**Comment by bestlem** [comment]
xonsh --version gave 0.9.24 for 0.9.25 but seems correct for 0.9.26

**Comment by gforsyth** [comment]
Thanks for confirming that @bestlem -- that was the more egregious mismatch in the 0.9.25 release, but I think @chronitis is correct that things are still happening slightly out of order re: the tags on the repo

**Comment by gforsyth** [comment]
ping @CJ-Wright in case he has any thoughts on what might be going on with rever

**Comment by CJ-Wright** [comment]
@gforsyth do you have your local `rever` dir handy?

**Comment by gforsyth** [comment]
ack, sorry @CJ-Wright -- yes, I do.  Any particular files you want me to throw up in a gist?

**Comment by CJ-Wright** [comment]
I think there should be a log file that would be helpful.

**Comment by gforsyth** [comment]
Here's the log @CJ-Wright : https://gist.github.com/gforsyth/5256a85e6e1625c0238ee570588ec972

Should be pretty short since I nuked my rever folder a few times while trying to track down a bug

**Comment by gforsyth** [comment]
Yes it did -- thanks for the nudge, @anki-code !
