### ISSUE TITLE
Allow whitespace in .xonshrc at the beginning of a line

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#4102]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.26          |
| Python           | 3.9.1           |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | 3.0.16          |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.4           |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior
To make my `.xonshrc` slighly more readable I'd like to have the following format that is on the one hand detailed enough to tweak any changes I like and on the other hand easily foldable in my text editor as not to create too much visual noise — the whitespace (two spaces `  `) at the start of each line allows me to group settings by module like so:
```
# output_search config
  # default: Press Alt + F hotkeys
  # default: Type f__ and press Tab key
  $XONTRIB_OUTPUT_SEARCH_KEY='i'           	# 1. Alt+i combination. Meaning: @bindings.add('escape', 'i')
  #$XONTRIB_OUTPUT_SEARCH_KEY_BINDING='c-g'	# 2. Control+g combination. Meaning: @bindings.add('c-g')
  #$XONTRIB_OUTPUT_SEARCH_KEY_META='right' 	# 3. Right+Left combination. Meaning: @bindings.add('right', 'left')
  #$XONTRIB_OUTPUT_SEARCH_KEY='left'       	#    text placeholder will be `left__`

```
I'd expect xonsh to just ignore the whitespace at the start of each newline and treat
`  ` `$XONTRIB_OUTPUT_SEARCH_KEY='i'           	# 1. Alt+i combination. Meaning: @bindings.add('escape', 'i')`
the same as 
`$XONTRIB_OUTPUT_SEARCH_KEY='i'           	# 1. Alt+i combination. Meaning: @bindings.add('escape', 'i')`

## Current Behavior
Instead, I get the following error:
```
  File "<string>", line None
SyntaxError: C:\Users\UserName/.xonshrc:8:0: ('code:   ',)
  $XONTRIB_OUTPUT_SEARCH_KEY='i'
```

## Steps to Reproduce
- add two spaces in front of any uncommented line in .xonshrc, e.g.
`  ` `$XONSH_COLOR_STYLE = 'vs'`
- launch xonsh

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @eugenesvk! The xonsh syntax is the superset of Python syntax where indentation has strong logic. I suggest you to use true-conditions for making blocks i.e.:
```python
if 1:
    $QWE=1

if 'my qwe setting':
    $QWE=1
```

**Comment by eugenesvk** [comment]
Thanks for a prompt response and this suggestion, it works nicely (though for some reason I though the configs used another syntax language)
