### ISSUE TITLE
Absolute paths to executables breaks bash completions

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#4104]
I came across this because I have a few aliases to make sure I'm running a given executable no matter what environment I'm in, e.g.

`aliases["git"] = "/usr/local/bin/git"`

## xonfig

<details>

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.9.26.dev7         |
| Git SHA          | c4e78435            |
| Commit Date      | Feb 9 10:54:17 2021 |
| Python           | 3.8.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.8               |
| shell type       | prompt_toolkit      |
| pygments         | 2.7.3               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| on jupyter       | False               |
| jupyter kernel   | None                |
| xontrib          | []                  |
+------------------+---------------------+
```

</details>

## Expected Behavior
bash completions should work when we pass in an absolute path to an executable

```
$ /usr/local/bin/git st<TAB>
```

should show me git completions

## Current Behavior
```
$ /usr/local/bin/git st<TAB>
```

shows me path completions as a fallback

## What's going on
the bash completer function (and all the others, too) expect inputs in the form `(prefix, line, begidx, endidx, ctx)` -- only `prefix` and `line` are applicable here.

If I use the absolute path, then `line == "/usr/local/bin/git st"`, at which point the bash completer helper looks for an executable named `/usr/local/bin/git` which doesn't exist, i.e. it is parsing the path to the executable as the full executable.

We should do a `rstrip("/")[-1]` or similar to return the correct completions

## Steps to Reproduce
Try to complete a `git` command using the absolute path to your `git` executable

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
Hey! waiting for https://github.com/xonsh/py-bash-completion/pull/17, and then we will use it in xonsh

**Comment by gforsyth** [comment]
Hey @daniel-shimon -- upstream merged and I also cut a new release with the changes.
