### ISSUE TITLE
ShiftDelete doesn't work

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#4105]
I'm trying to understand how to delete whole words and found the <kbd>Shift</kbd><kbd>Delete</kbd> binding that's supposed to do exactly that, however, it doesn't seem to work
As far as I understood from this [PR](https://github.com/xonsh/xonsh/pull/3787), the `whole_word_jumping.py` file has the corresponding functions:
- `ctrl_left` and `ctrl_right` functions bound to `Keys.ControlLeft` and `Keys.ControlRight` , both of which are working fine
- but the `shift_delete` function bound to `Keys.ShiftDelete` doesn't get called on shift-delete

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+     
| xonsh            | 0.9.26          |     
| Python           | 3.9.1           |     
| PLY              | 3.11            |     
| have readline    | False           |     
| prompt toolkit   | 3.0.16          |     
| shell type       | prompt_toolkit  |     
| pygments         | 2.7.4           |     
| on posix         | False           |     
| on linux         | False           |     
| on darwin        | False           |     
| on windows       | True            |     
| on cygwin        | False           |     
| on msys2         | False           |     
| is superuser     | False           |     
| default encoding | utf-8           |     
| xonsh encoding   | utf-8           |     
| encoding errors  | surrogateescape |     
| on jupyter       | False           |     
| jupyter kernel   | None            |     
| xontrib          | []              |     
+------------------+-----------------+     
```

</details>

## Expected Behavior
<kbd>Shift</kbd><kbd>Delete</kbd> should delete the whole word

## Current Behavior
<kbd>Shift</kbd><kbd>Delete</kbd> deletes only a single symbol just like <kbd>Delete</kbd> 

## Steps to Reproduce
Open a terminal, type a word and try to delete it with <kbd>Shift</kbd><kbd>Delete</kbd> 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi! Are you load the xontrib?
```
xontrib load whole_word_jumping
qweqweqwe asdasdasd zxczxczxc<Shift+Del>  # will delete the zxczxczxc argument
```

**Comment by eugenesvk** [comment]
> Hi! Are you loading the xontrib before?

Yes, it doesn't work in the Windows-native shell/console even with `xontrib load whole_word_jumping` — I was testing with both this command (it's part of my profile) and with an empty profile (although I realize this testing made no sense — even though ctrl+Left/Right were working with an empty config it wasn't handled by `whole_word_jumping.py`)

However, it does work within WSL!
So it's something unique to Windows native shell/console combination?

**Comment by anki-code** [comment]
Sounds like Windows related issue. Also probably prompt_toolkit upstream issue.

**Comment by eugenesvk** [comment]
> Sounds like Windows related issue. Also probably prompt_toolkit upstream issue related to Windows Terminal.

maybe, though I'm using the same Windows Terminal in both cases: with the Windows xonsh and with the WSL brew-installed xonsh
Anyway, will open a ticket with the prompt_toolkit, maybe they'd have an idea

**Comment by alvarv** [comment]
not a fix, but a workaround... Ctrl+w and ESC+Bsp both provide (different) word erasures, the difference lying in what is considered a word delimiter...

**Comment by eugenesvk** [comment]
This one is definitely a prompt_toolkit issue, managed to find a way to fix it there in this PR https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1381
