### ISSUE TITLE
A lingering Python.exe process grows its memory usage until OOM (Windows)

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#4111]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+     
| xonsh            | 0.9.26          |     
| Python           | 3.9.1           |     
| PLY              | 3.11            |     
| have readline    | False           |     
| prompt toolkit   | 3.0.16          |     
| shell type       | prompt_toolkit  |     
| pygments         | 2.7.4           |     
| on posix         | False           |     
| on linux         | False           |     
| on darwin        | False           |     
| on windows       | True            |     
| on cygwin        | False           |     
| on msys2         | False           |     
| is superuser     | False           |     
| default encoding | utf-8           |     
| xonsh encoding   | utf-8           |     
| encoding errors  | surrogateescape |     
| on jupyter       | False           |     
| jupyter kernel   | None            |     
| xontrib          | []              |     
+------------------+-----------------+     
```

</details>

## Expected Behavior
After all xonsh sessions are closed, no related python processes should remain

## Current Behavior
Sometimes a python process remains and keeps growing its memory usage until OOM
Once or twice I caught this even while a few xonsh sessions were still running

## Steps to Reproduce
Unfortunately, I only see that when it's too late, so at the moment I have no idea what's causing this.
(upd: I've checked via Process Explorer that the misbehaving process indeed belongs to xonsh, not any other app)

I realize that this makes the issue report kind of useless, so I'd like to ask what I could do to pinpoint the issue?

P.S.
Not using ssh and not on Linux, so [this issue](https://github.com/xonsh/xonsh/issues/3999) doesn't seem to be applicable?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
I'm going to close this until we get repeatable step by step example.
Personally I seen many tools that sometimes becomes zombie with OOM. To talking about this cases without repeatable example is wasting of time.
