### ISSUE TITLE
XONSH_HISTORY_FILE is not actual

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4118]
Hi!

I've found that `XONSH_HISTORY_FILE` is not actual:

```python
history info | grep filename
# filename: /home/user/.local/share/xonsh/xonsh-history.sqlite

$XONSH_HISTORY_FILE
# '/home/user/.xonsh_history.json'

# Prepared by xontrib-hist-format

```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hey @gforsyth you did a clean up in #4145 may be this code also outdated?

**Comment by gforsyth** [comment]
Hey @anki-code -- yes, I agree we can remove that env-var now.  Should be straightforward, although there are a bunch of sample test files that we _may_ need to edit
