### ISSUE TITLE
How to parse the string and get commands tuple?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4123]
Hi!
I know about lexer:
```python
__xonsh__.execer.parser.lexer.split('echo 123')
# ['echo', '123']
```
But it's not working with pipe and `run_subproc`:
```python
import xonsh
__xonsh__.execer.parser.lexer.split('echo 123 | fzf')
# ['echo', '123', '|', 'fzf']
xonsh.procs.specs.run_subproc((['echo', '123', '|', 'fzf'],), captured="stdout")
# '123 | fzf\n'
```
because `run_subproc` is expecting the tuple `(['echo', '123'], '|', ['fzf'])`.

Is there a way to get this tuple from the string and pass them to `run_subproc`?

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
@gforsyth it is better to have the GitHub's Discussion enabled for this repo. It can help as a knowledge base and a public forum

https://docs.github.com/en/discussions
https://github.com/vercel/vercel/discussions/3874

**Comment by gforsyth** [comment]
Hey @jnoortheen -- I've just enabled discussions on xonsh/xonsh.  Let's give it a shot and see how it goes.

**Comment by jnoortheen** [comment]
Have you tried using the [CompletionsParser](https://github.com/xonsh/xonsh/blob/main/xonsh/parsers/completion_context.py) ?
