### ISSUE TITLE
The first user experience after removing PTK

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4141]
Hi!

I have a concern about bad user experience after removing PTK in #4107.

The `readline` shell is not so good and full featured like `prompt-toolkit`. When I do
```python
docker run --rm -it python:3.9-slim /bin/bash -c "apt update && apt install -y git && pip install -U git+https://github.com/xonsh/xonsh.git; xonsh"
# I should know about `pip install prompt-toolkit` to get all features
```
I get xonsh 0.9.27 with readline by default and it starts fast but I'm feeling bad without beautiful ptk suggestion and grey line suggestion of the command. The first impression experience was decreased by removing PTK. Also the users who will install PTK-tested prompt themes may face with ugly issues.

~We released the new landing where `pip install xonsh` is used and user who will run this command will get the `readline` shell. It's sad.~ (PR with the fix below)

What do you think about these consequences?

I personally for the adding ptk as the default dependency for xonsh package.

@jnoortheen @gforsyth 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @anki-code -- there's a longer discussion to be had here, for sure, but as a stopgap, do we want to update the front page to suggest `python -m pip install xonsh[full]`?

**Comment by anki-code** [comment]
> Hey @anki-code -- there's a longer discussion to be had here, for sure, but as a stopgap, do we want to update the front page to suggest python -m pip install xonsh[full]?

Yep, PR is here #4142

And while I update the page I think: how it works in package managers (apt/brew/etc)? Are they also installing pure xonsh?

**Comment by gforsyth** [comment]
I know that brew, conda-forge, and pacman install with prompt toolkit, I'll wager apt does the same thing.  General policy of most packagers is to grab all options

**Comment by gforsyth** [comment]
Yep, I think we're all set for `apt`, too: https://packages.debian.org/sid/xonsh

**Comment by anki-code** [comment]
> Yep, I think we're all set for apt, too: https://packages.debian.org/sid/xonsh

I seen the 0.9.25 and imagined may be after update to 0.9.27 the ptk dependency will disappeare. But if you have an assurance, that's cool :) Thanks!

**Comment by anki-code** [comment]
I think we should have a words in the welcome message (without rc) like "You're using readline, install prompt-toolkit for the best experience." (and a bit colors refactoring #2401). This feature would close this issue...

**Comment by gforsyth** [comment]
That works for me, @anki-code -- the message should probably only appear the first time a user launches the readline shell (or the message should be easy to disable)

**Comment by anki-code** [comment]
@gforsyth To make this feature with minimal code I think about just one line that will appear forever if the shell_type is not ptk:

![image](https://user-images.githubusercontent.com/1708680/110135442-940d2300-7ddf-11eb-93cf-0ab08bd6fd67.png)

**Comment by gforsyth** [comment]
That works for me!

**Comment by jnoortheen** [comment]
xonsh needs `pygments` to show the colors which in my opinion is a must for any modern shell. 

The term `best-experience` is subjective. Some may want to stay minimal. It can be worded like `featureful`

**Comment by anki-code** [comment]
I faced with issues in readline many times. It's may be personally but PTK works much stable.
Also while I review the issues a week ago I noticed that readline has problems that less people want to fix.
I think I will try to use readline more to make more complete opinion.

**Comment by jnoortheen** [comment]
> I faced with issues in readline many times. It's may be personally but PTK works much stable.
> Also while I review the issues a week ago I noticed that readline has problems that less people want to fix.
> I think I will try to use readline more to make more complete opinion.
> I thought forever that readline is something like prompt fallback in xonsh. What is the goal of having readline?

I also faced the same thing, I have created an issue [here](https://github.com/xonsh/xonsh/issues/3969) as well. But sometimes, it is needed in a memory constrained environment. So alas if it saves some 10MB.

**Comment by anki-code** [comment]
Thanks for the link! All the messages about readline sounds like "this is a plan B in case of restrictions". It's ok. 
My concern is about that this second-class solution becomes the facade of the shell just because the first class solution is a dependency. 
I think we should supply best experience by default and user can set the second-class solution by using RC or `--shell-type` manually.
