### ISSUE TITLE
Add preview image to xontrib-cookiecutter

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4149]
Hi!

Please open the seetings of the [xonsh/xontrib-cookiecutter](https://github.com/xonsh/xontrib-cookiecutter) repository and add "Social preview" image:

![image](https://user-images.githubusercontent.com/1708680/110229963-5236c680-7f1e-11eb-8da6-0955f3759a70.png)

Then check the result - https://github.com/topics/xontrib

@gforsyth 

Thanks!

**Comment by gforsyth** [comment]
Done -- thanks for the image, @anki-code !
