### ISSUE TITLE
Reinventing the prompt end character for xonsh

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4152]
Hi folks! 

Prerequisites:
1. While I'm watching [@scopatz streams](https://www.youtube.com/watch?v=dGTkiGvrYHg) I noticed that [xonsh looks like bash](https://youtu.be/EbX2fhfwOWc?t=832) and if we don't know that it's the xonsh we will never understand that it is xonsh. 
2. When I alternately use Bash and Xonsh I caught myself thinking that I am making an effort to figure out which shell I am currently using.
3. When I'm reading the bug reports in the issues or another code quotations the `$` character means bash as well as xonsh and I need to special effort to understand the meaning.
4. The bash-like prompt looks cozy but after a few rakes with the syntax users feel misled. The conch character will remind them that here is Python mindset.
5. We have double dollar in case of using env: `user@home ~ $ $VAR=1`. The conch character will dilute the repetition.
6. The conch character (`@`) in the prompt will complete the xonsh identity. We can remove or replace this character between user and host to more significant effect.
7. The `@` character looks both like conch and python (snake).
8. Using `$` limit the spreading the word about xonsh and growing the community because people think that it's bash.
9. By using `@` we can separate `$` for bash and `@` for xonsh.
10. The `@` character with `~` looks like "snail (snake, python) going to conch (shell)" - very very very metaphoric - `host@user ~ @`.

Overview:
```bash
# xonsh default 
user@host /path $

# bash default
user@host:/path$

# zsh has percent by default
user@host /path %  

# fish wants to look like fish
user@host /path>

# Starship cross-shell prompt (bold angle bracket)
❯

# proposed for xonsh
user@host /path @
```

**What if we replace `$` to `@` and make/replace a space between user and host in xonsh?** 

![image](https://user-images.githubusercontent.com/1708680/110364234-9330f700-8054-11eb-8d91-1afe1905754a.png)

![image](https://user-images.githubusercontent.com/1708680/110359210-42b69b00-804e-11eb-97bf-a4d1113a5335.png)

This looks like snail and conch:

![image](https://user-images.githubusercontent.com/1708680/110358956-f79c8800-804d-11eb-91a3-0e06f1e3c0ac.png)

[xontrib-prompt-bar](https://github.com/anki-code/xontrib-prompt-bar) appearance:

![image](https://user-images.githubusercontent.com/1708680/178773604-b2f9954a-6ecc-427d-adad-7401cff2b184.png)

### 📄 [XEP-like description](https://github.com/xonsh/xonsh/issues/4152#issuecomment-794875983)

# 📗 VOTE HERE - https://github.com/xonsh/xonsh/issues/4152#issuecomment-794178842

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Personally I replaced `$` to `@` in [xontrib-prompt-bar](https://github.com/anki-code/xontrib-prompt-bar) and it looks nice:

![image](https://user-images.githubusercontent.com/1708680/110252131-f9564500-7f94-11eb-8627-ada7a67b1f8f.png)

**Comment by anki-code** [comment]
If I remember correct I already seen that AstraLuma replaced `$` to 🐚 icon.

![image](https://user-images.githubusercontent.com/1708680/110251432-7089da00-7f91-11eb-9af5-03f2beceb58d.png)

**Comment by anki-code** [comment]
For anybody who agree with me I suggest to add this to the `~/.xonshrc`:
```python
from xonsh.tools import is_superuser
$PROMPT_FIELDS['prompt_end_xonsh'] = "#" if is_superuser() else "@"  # or "🐚"
$PROMPT = $PROMPT.replace('prompt_end', 'prompt_end_xonsh')
```

**Comment by gforsyth** [comment]
Seems like a reasonable default to me.  I use 🐚 as my `prompt_end`.
I'll wait a bit to see if anyone has any concerns about this, then we can go ahead and merge in #4155

**Comment by jnoortheen** [comment]
IMHO `@` doesn't seems to be the end of prompt. What do you think about `❯`. It is a special symbol(probably would required utf-8 support from the terminal) but it looks modern and proper start for the commands to be entered.

**Comment by anki-code** [comment]
I think ">" is used so commonly (fish, Starship, pure, powerline) that will be the same as $ soon. In other side @ could be the part of xonsh individuality/identity.

**Comment by jnoortheen** [comment]
It is just `@` doesn't click as the end of prompt. Maybe it is because we use it a lot in emails and expect it to be in the middle and not at the end.

**Comment by jnoortheen** [comment]
Also, @ is part of language, when copy pasting, it can cause confusion to newcomers. I know about $, since we are asking for a new one, can't we have a better one that doesn't clash with the language.

**Comment by anki-code** [comment]
I don't realize what will confusion newcomers? You mean they will copy all the string including @? I think they will do it once to understand.

**Comment by anki-code** [comment]
A bit playing with colors:

![image](https://user-images.githubusercontent.com/1708680/110358956-f79c8800-804d-11eb-91a3-0e06f1e3c0ac.png)

**Comment by jnoortheen** [comment]
yes they may copy it as whole or will read the content and it may confuse when first seeing the code snippet

for example something like this
```
~@ @('ls')
```
. Regarding colors, it needs pygments.

**Comment by anki-code** [comment]
> ~@ @('ls')

![image](https://user-images.githubusercontent.com/1708680/110359354-74c7fd00-804e-11eb-9d0e-32422f15b693.png)

The use case above is rare than this:

```
user@host ~ $ $ENV=1
```

**Comment by jnoortheen** [comment]
> > ~@ @('ls')
> 
> ![image](https://user-images.githubusercontent.com/1708680/110359354-74c7fd00-804e-11eb-9d0e-32422f15b693.png)
> 
> The use case above is rare than this:
> 
> ```
> user@host ~ $ $ENV=1
> ```

yes that is what I was saying, we have the oppertunity to have something new. So we can avoid similar mistakes.

**Comment by anki-code** [comment]
> Regarding colors, it needs pygments.

Any shell has white color for @

**Comment by anki-code** [comment]
Visual concept:

![image](https://user-images.githubusercontent.com/1708680/110360921-65e24a00-8050-11eb-9a37-e6d70cfb13e2.png)

**Comment by gforsyth** [comment]
> What do you think about `❯`

I think it looks cool but I don't want the default to require utf-8 encoding (just because it can sometimes be a pain to get configured correctly).

We could make the default `>` -- which doesn't have the lovely shell evolution scheme that @anki-code introduced above, but would avoid the copy-paste collisions for both `$` and `@` operators

**Comment by jnoortheen** [comment]
can we detect the support and choose it dynamically between `❯` and `>`. Also most of the new age shells use `>` as default like nushell, elvlish ...

**Comment by anki-code** [comment]
The concept behind @ is to accent the xonsh identity and identify the xonsh on any screenshot/video stream. I'm personally indifferent to ">" because it has wide usage and suppose xonsh will look as fish :)

If you see many issues around @ I prefer close this issue without any negative emotions because the world is really complex. May be the better way is to add the choice to the xonfig wizard.

I'll be happy to hear @scopatz oppinion because from his video streams I started this issue :)

**Comment by jnoortheen** [comment]
Yes it is better to be unique but should not look weird. Lets hear out more people's opinion.

**Comment by daniel-shimon** [comment]
I kinda like this idea!
- Sure it can look like the `@()` token but that will happen with just about any ASCII character (and it already happens with `$`).
- I think adding a recognizable small change like this adds some nice spark to xonsh users.

Since this is really a stylistic thing, maybe we should have some sort of vote?

**Comment by anki-code** [comment]
We could have a slang "I'm using @-shell :)"

**Comment by gforsyth** [comment]
Ok -- let's hold a vote, open to all.  React with 👍  if you want to change the default `prompt_end` to `@`, 👎 if you prefer something else.

@xonsh/xore @xonsh/xore-emeritus @xonsh/xonsh-triage 
And if someone can post a link to this on Gitter, I'd appreciate it (blocked on `$WORK_LAPTOP`)

**Comment by jnoortheen** [comment]
> Ok -- let's hold a vote, open to all. React with  if you want to change the default `prompt_end` to `@`,  if you prefer something else.
> 
> @xonsh/xore @xonsh/xore-emeritus @xonsh/xonsh-triage
> And if someone can post a link to this on Gitter, I'd appreciate it (blocked on `$WORK_LAPTOP`)
> 
> We'll give it until EOD on Friday 2021-03-12, AoE (https://en.wikipedia.org/wiki/Anywhere_on_Earth)

can we consider, holding for 
1. `@`
2.  `>`
3.  `❯` if character code is printable/available otherwise `>` 
4. other characters (open to people's suggestion)

**Comment by jnoortheen** [comment]
Ok.

**Comment by Carreau** [comment]
🤷 is not a voting option :-) I'm not for, but not against either. It's configurable anyway; so why not changing.

**Comment by anki-code** [comment]
To clear understanding what the complete changes list were suggested:
1. Replace prompt_end character from $ to @.
2. The @ character will be white color to associate with classic xonsh conch.
3. The @ between user and host will be removed.
4. (Optionally/Future) The xonfig wizard will have an option to set the classic bash prompt.

How it looks:

![image](https://user-images.githubusercontent.com/1708680/110577146-19dbf600-8173-11eb-9447-5da7a3e6aefa.png)

This look has many meanings:
1. The @ char remember that it's xonsh.
2. The @ char point out to both conch and Python.
3. In the home directory "~ @" looks like snail with conch.
4. The space between user and host make the line clean.

Potential issues:
1. If we weill use @ in the quotation (`@ echo 1`) the @ char may not be read as the prompt start by novices. 
Workaround: we will use color  accent.
2. If we weill use @ in the quotation (`@ echo 1`) the code highlighters may not to highlight the commands properly. 
Workaround: no.
3. The @ char will have vidual duplication in case `@ @('ls')` as `$ $VAR=1` in the current prompt. 
Our acceptance logic for this based on that the first case is rare than second.
4. Someone could fing the @ char as unusual/differ/unconfortable. 
Our logic of acceptance for this is "just simply change PROMPT to comfortable". For example default zsh prompt looks like `host%` and nobody complains and just use custom prompts.

**Comment by anki-code** [comment]
> 🤷 is not a voting option :-) I'm not for, but not against either. It's configurable anyway; so why not changing.

@Carreau In this case please set the 👀 reaction ;)

**Comment by jb-leger** [comment]
It is configurable, so the default choice seems to very important for me. But, I think for new users it can be very uncomfortable. The best option for me is to add a choice of prompt in xonfig wizard, but keep the actual prompt in default choice (it is why I choose :-1:, but this choice is "something else", and I had to explain the sub-choice).

**Comment by halloleo** [comment]
Good discussion, but I’m not convinced about a single @ symbol. As said before by others, it is not associated with waiting for a prompt and too often used in emails. I  *could* live with something like  `@>`.

**Comment by anki-code** [comment]
Nice question - [What is the origin of the UNIX $ (dollar) prompt?](https://superuser.com/questions/57575/what-is-the-origin-of-the-unix-dollar-prompt). Answers:

* The culmination of your login efforts is a percent sign “%”. The percent sign means that UNIX is ready to accept commands from the terminal.

* The original Bourne shell prompt was a snail shell, "@". I remember this on UNIX 6th edition which, I believe, is before UNIX was sold commercially. So the switch to a $ sign could be related to commercialisation of UNIX, as Robert suggested, $hell.

* By contrast the traditional C shell prompt is a percent sign (%). 

Wow!

**Comment by halloleo** [comment]
> https://xkcd.com/1172/

Uuuuuuuuuh, soooo funny - soooooo true!

**Comment by anki-code** [comment]
Thanks you all for the attention to this issue :)
I'm going to close this issue.
Personally I will praise and recommend to set `@` as prompt_end in [prompt_bar](https://github.com/anki-code/xontrib-prompt-bar) and [prompt_starship](https://github.com/anki-code/xontrib-prompt-starship).

The results for the history:

<details>

![image](https://user-images.githubusercontent.com/1708680/110975655-11e9a500-8371-11eb-8ca6-2d8f3bea39e3.png)

</details>

**Comment by mattmc3** [comment]
One small downside to the section sign is some monospaced fonts like Courier render it like a double S instead of the more elegant s with a center oval `§`:
<img width="372" alt="Screen Shot 2022-07-14 at 10 51 27 AM" src="https://user-images.githubusercontent.com/978625/179011786-21a82a1a-dc9c-43de-9ba6-036741fa7677.png">

**Comment by das-g** [comment]
My vote still is for changing it to `§`.

If given the choice only between not changing it or changing it to `@`, I think I have a slight preference for not changing it, as I can see the arguments how `@` as a prompt can sometimes be confusing, especially with the important role `@` already has in Xonsh's syntax. (But I'm not fundamentally opposed to changing it to `@`.)

**Comment by halloleo** [comment]
I concur with @anki-code, that “@“ is a great symbol: It represents conch _and_ Python!

Also, I do think it is good to have an identifying symbol when you show a xonsh command line in some documentation: It quickly makes clear (to insiders at least) that e.g.

```
for f in g`*.md`:
...     head @(f) | showed -t
```

is a Xonsh command line (as oppose to a bash command line or else).

**Comment by bestlem** [comment]
How many terminals are now non Unicode and can't display the conch (🐚 )?

This would make xonsh noticeable.

**Comment by bestlem** [comment]
@halloleo I think your example needs to be without any prompt so users can just cut and paste it,

I have had to deal with new users who cut and paste the prompt character into their terminal and then get error messages.

**Comment by bestlem** [comment]
> I myself uses the starship prompt across all my shells (side effect of nixos).
> 
> ```
> ~/Code/nixos on  master [$!] 🐚 xonsh
> at 16:42:32 ❯ zsh
> ```

I would note that your example does show some of the issues. The Consh shows up to me no problem - but your starship nix prompt shows a missing character between on and master - I huess trying to use a nerd font. I am using iTerm on macOS and also the email copy showed the issue.

SO yes I like the conch shell but I think we are stuck with plain ASCII for the default (unless we can workout if emojis are available)

**Comment by con-f-use** [comment]
Being late to the discussion, because I didn't see it despite being a long-time xonsh user. I don't like the `@` and just now noticed it that it's been rolled out on NixOS. It's not a big deal though. I'd, just like to ask, that in the future future, any AI change or more importantly any breaking change can get a kind of opt-in deprication warning a release or two in advance, maybe with a link to the discussion? I'd like to have participated.

As a side-note a 2 to 0 to 3 vote or a 15 to 10 should not really decide anything. The participation is just so low that it is not representative of anything. Same goes for a 5000 to 5001, though here the reason is that despite participation it's not decisive enough.

Not attacking anything or wanting to dunk on anything, just something to consider for next time.
