### ISSUE TITLE
Expand callable environment variable in subprocess mode

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4167]
Hi! Think that's nice:

```python
$DATE = lambda: $(date --iso).strip()
echo The date is $DATE
```
Current output:
```
The date is <function <lambda> at 0x7f807ecda940>
```
Suggested output:
```
The date is 2021-03-11
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by alvarv** [comment]
But $DATE **is** a function, not a call to a function... Shouldn't you just write 
```
echo The date is @($DATE())
```
Granted, a little uglier... But if finding a function in a line automatically invokes it (with no parameters)... wouldn't that break other use cases?

**Comment by anki-code** [comment]
Current behavior (returning `<function <lambda>>` as string) more unexpected than calling.

**Comment by anki-code** [comment]
@alvarv I made this feature optional and by default add the raising an exception to avoid getting `<function>` as an argument. This is more stable logic I suppose.

**Comment by anki-code** [comment]
Example:
```python
$ENV = lambda: 123
echo $ENV
# Exception: The ENV variable is callable. If you want to use callables set $XONSH_ENV_ALLOW_CALLABLE = True

$XONSH_ENV_ALLOW_CALLABLE = True
echo $ENV
# 123
```

**Comment by anki-code** [comment]
JFYI In the #4148 the user also expect that lambda that putted to TITLE will be executed. It's not the same as current issue but the expectations are similar.

**Comment by anki-code** [comment]
I lost motivation while thinking about this logic. Sorry.

It's not good to have callables that can uncontrolled be converted to strings. This is another one question that should be redisigned, reinvented, rethought. Some day...

**Comment by anki-code** [comment]
Basically I see three different approaches:
1. **Transparent way**. If any object is callable and we expect another type (str, list, class) we should call it to get the actual value.
    * Pros: transparent, expected, extensible
    * Cons: The moment of executing the callable may be uncontrolled and for example if the callable depends on time we can get unexpected result when callable was executed in the past but we expect that it executes now. 
2. **The wall way**. If any object is callable and we expect another type (str, list, class) we should raise an exception to force explicit implementing the call from the developer i.e. replace `echo $VAR` to `echo @($VAR())`.
    * Pros: explicit calling
    * Cons: we should do the check in every plase where we could have callable (everywhere)
3. **Deprecation**. If someone try to set callable to env var raise an exception.
    * Pros: clean logic that told that variable can have only static value
    * Cons: no callable variables in the env, someone go to cry
