### ISSUE TITLE
Disable history loading in case of running the script or the command

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4177]
Hi!

We found in https://github.com/xonsh/xonsh/issues/2496#issuecomment-798959368 that xonsh loads the history in case of running script and this produces some side effects.

Example for json backend:
```python
bash
cd /tmp
echo "echo 123" > e.xsh
XONSH_HISTORY_BACKEND=json xonsh e.xsh
## loading thousands of json files history
## running the script
# 123

XONSH_HISTORY_BACKEND=json xonsh -c 'echo 123'
## loading thousands of json files history
## running the command
# 123
```
Probably this is the cause of slow running the scripts in some cases.

We should disable history loading in case of running the script.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Here is the start point to fix:

https://github.com/xonsh/xonsh/blob/f32c36b600eaf780b6f1787f54d3de085c04acc0/xonsh/shell.py#L203-L206

This code should not be executed in case of running the script.

**Comment by anki-code** [comment]
@gforsyth @jnoortheen @daniel-shimon I think this bug pretty epic to discuss and fix in the near release.

**Comment by anki-code** [comment]
I think I've found a bug in logic. I'm working on PR.

**Comment by jnoortheen** [comment]
This can be decorated with the `lazyobj` function. That way one can access history if they wanted inside script.

**Comment by anki-code** [comment]
@jnoortheen nice thought but we have no guarantee that history will not be called in the xonsh code in the future. Developer can add calling the history and we will catching side effects again and without any warnings. 

To add backwards comaptibility I replaced history to DummyHistory in case of not interactive mode.

**Comment by jnoortheen** [comment]
> @jnoortheen nice thought but we have no guarantee that history will not be called in the xonsh code in the future. Any developer can add calling the history and we will catching side effects again and without any warnings.
> 
> To add backwards comaptibility I replaced history to DummyHistory in case of not interactive mode.

That would make it like a hackish solution. We should be avoiding history loading if not necessary. Since we apply the solution in the source, we should be making sure that it works in all places.

**Comment by anki-code** [comment]
@jnoortheen  Am I right you prefer to set history to None and fix all exceptions instead of setting history to Dummy?

**Comment by anki-code** [comment]
I've added setting to None. I will look on tests.

**Comment by jnoortheen** [comment]
> @jnoortheen Am I right that you prefer to set history to None and fix all exceptions instead of setting history to Dummy?

I prefer setting it to a lazy-loaded object. That way if anyone wants to access history, then it will get loaded. Otherwise, it will not get loaded.

**Comment by anki-code** [comment]
> Otherwise, it will not get loaded.

LazyJson will be executed in any time you use the object. This will have side effects now and in the future like here - https://github.com/xonsh/xonsh/pull/4178#issuecomment-799208963

**Comment by jnoortheen** [comment]
> > Otherwise, it will not get loaded.
> 
> LazyJson will be executed in any time you use the object. This will have side effects now and in the future like here - [#4178 (comment)](https://github.com/xonsh/xonsh/pull/4178#issuecomment-799208963)
> 
> UPD: After research I've found that xonsh uses history backend as storage for the last_cmd_rtn in many places so the solution with Dummy history is most native for now.

Then I think it is the way to go for now.
