### ISSUE TITLE
Default branch renamed to `main` -- update your local dev environment

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#4180]
The default branch is now called `main`.  You can update your local dev environment to match by running the following:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by anki-code** [comment]
This issue was pinned so I'm going to close this.

**Comment by jnoortheen** [comment]
@gforsyth the same need to be done for codecov as well. PS https://github.com/statsmodels/statsmodels/issues/7424
