### ISSUE TITLE
Unwanted "or/and" syntax highlighting in the beginning of the word

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4184]
Hi!

![image](https://user-images.githubusercontent.com/1708680/111293377-42c02780-865a-11eb-90f7-3118781a95db.png)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @daniel-shimon! Please take a look. I think it's related to #3986

**Comment by daniel-shimon** [comment]
Haha seems like it!
Probably adding `\b` before and after each word in that regex will do the trick
