### ISSUE TITLE
question about exporting and curiosity

### ISSUE THREAD

**Issue by vinniec** [xonsh/xonsh#4186]
Is it possible to export/save history blocks in some way? i've been trying xonsh for a few days and it's very nice, and I found myself writing functions that now i would like to save in some way without having to copy them all by hand.

The second question is that I tried the appimage and then I also tried to install with pip, the two versions are very different, I think for a dependencies discrepancy.
Could I know out of curiosity, what is included in the appimage version?

**Comment by anki-code** [comment]
Hi @vinniec and welcome!

> Is it possible to export/save history blocks in some way?

You can use `__xonsh__.history` to operate with previous commands:

```python
def hello_world():
     print('Hello world!')

hello_world
#<function __main__.hello_world>

hello_world()
# Hello world!

prev = __xonsh__.history[-3:]

prev
#[HistoryEntry(cmd="def hello_world():\n    print('Hello world!')\n    \n", out=None, rtn=0, ts=[1615957220.8358638, 1615957220.8358676]),
# HistoryEntry(cmd='hello_world\n', out=None, rtn=0, ts=[1615957226.8963404, 1615957226.9051766]),
# HistoryEntry(cmd='hello_world()\n', out='Hello world!\n', rtn=0, ts=[1615957229.3809042, 1615957229.3809958])]

prev[0].cmd
# "def hello_world():\n    print('Hello world!')\n    \n"
```
Or you can extract commands from history files:
```python
# json history
cat $XONSH_DATA_DIR/xonsh-*.json | jq '.data.cmds[].inp'

# sqlite history
sqlite3 $XONSH_DATA_DIR/xonsh-history.sqlite "SELECT inp FROM xonsh_history"
```

> Could I know out of curiosity, what is included in the appimage version?

To [building the xonsh AppImage](https://xon.sh/appimage.html#building-your-own-xonsh-appimage) (take a look at "If you don’t have Python on your host") we use [pre-requirements.txt](https://github.com/xonsh/xonsh/blob/main/appimage/pre-requirements.txt) and [python-appimage](https://github.com/niess/python-appimage).

**Comment by vinniec** [comment]
Thanks, I have tried and all of these ways are helpful solutions.
I was wondering if there was a way to do this from the actual prompt though.
For example imagine I wrote a function doing experiments editing it from time to time, each time I would go back into the history with ctrl+up, making the changes and executing them with alt+enter.
At some point I decide that this function is useful to me outside this session and I want to save it.
I could do as you suggested, i.e. i can select the block i want in the history with ctrl+up or ctrl+r, alt+enter to execute it, and then give the command `__xonsh__.history[-1:][0].cmd > file.xsh`.
This is the best I can come up with, but I was wondering if there was any way to do this by directly intervening on the selected block, e.g. by a keyboard combination or by adding something like jupyter's magic function "%%writefile myfile.py" to the beginning of the block.
I tried xonsh when you showed me an example of a working appimage on alpine here https://github.com/AppImage/AppImageKit/issues/1015#issuecomment-795301721
Of course I tried it, ok vscodium doesn't work but xonsh is really interesting, so one star is required :)

**Comment by anki-code** [comment]
Yeah, you want something like Jupyter and [xonsh has the kernel for Jupyter](https://xon.sh/jupyter.html) :)

Your idea is interesting but it's not so native for the shell. When you run `echo 1` and then get this command from the history and edit to `echo 123` you want to have both "1" and "123" in the history.

The native way is to save big script to the file and then run/source the script.

**Comment by vinniec** [comment]
Yes, you are absolutely right, what I am asking is not a normal thing to do in a terminal, it is not "obvious" that it is there. And I totally understand wanting to keep the ideology behind your shell pure, that's something I appreciate as well.

It all comes from the fact that I happen to do things on the terminal, then I get the desire to improve them and in the end it's a shame not to keep them but the idea of doing it in a lazy way for me is motivating, but I'm sure my way is totally unorthodox!
For an example, I've always felt the need to use the terminal more, but I started doing that when I discovered drop down terminals, before I was annoyed I always had to open a window and have it around the desktop :D

When I first tried your appimage, I noticed at first that I liked all the conveniences of your shell, and I also liked the idea of being able to use python syntax instead of sh syntax.
However, I really took a liking to it when I realized that with your shell I can test python commands directly without opening the interpreter! and this delights my laziness once again :D

Now I'm starting to think that I could make a module containing snippets and utilities that I find myself doing often and each time import it at startup, aliases have always bored me, a module is better :P

**Comment by anki-code** [comment]
I think you can experiment with `vipe` - it read the `stdin` then open the editor and then put the result to the `stdout`.
```python
apt install moreutils
echo 1
new_cmd = $(echo @(__xonsh__.history[-1].cmd) | vipe)  # add 23
new_cmd
# `echo 123\n`
```
I'm going to close this question. Thanks!

**Comment by anki-code** [comment]
@vinniec take a look - https://shellnotebook.com/
Sadly but it's not open source and there is no way to change the shell.

**Comment by vinniec** [comment]
I received a message about shellnotebook in my email and I reply here.
I think for certain uses it can be useful, however I have been thinking and in my case I still prefer xonsh.
I tried another time also ipython shell, let's say that all the magic it has are very useful but what I like about xonsh is the immediacy, I use it a bit like a sketchbook, instead ipython is in the middle between a more reflective analysis of jupyter and experimentation of xonsh.
Ok, ipython also shows the numbers of the cells, but honestly I do not remember them so I always need to search for the cell I want to start, so it is useful but only when you make operations that require time.
However, I saw that xonsh works even without the appimage in alpine, I'm trying to create the package (it's my first attempt but it still works), I'm waiting for the merge :)
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/19628

**Comment by gforsyth** [comment]
@vinniec -- when I want to save a function I've written in the prompt, I reverse search (Ctrl-r) for it, then once it's in the prompt, you can hit Ctrl-x Ctrl-e to open up the current prompt contents inside your `$EDITOR` and then save that function to another file.

**Comment by vinniec** [comment]
you gave me a valuable advice, i can't use it directly because my idea was to add the content of multiple buffers to the same file one at a time, but looking for information on shortcuts I found this page: https://xon.sh/tutorial_ptk.html
Now I'm not in the right moment, but this means that I can invent something to do what I was saying, maybe a menu with the buffer previews and when you click it asks you to enter the file name.
So thanks, I also noticed two problems on that page, but I think it's more correct that I report them in another issue. Thanks :)
