### ISSUE TITLE
Just installed xonsh from apt repo - tried to run wizard but get error

### ISSUE THREAD

**Issue by MostHated** [xonsh/xonsh#4187]
## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.19          |
| Python           | 3.8.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.16          |
| shell type       | prompt_toolkit  |
| pygments         | 2.8.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | pop             |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior

I presume a setup wizard was to walk me through initial setup?

## Current Behavior

Upon trying to run `xonfig wizard` I get the following:

```sh
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
AttributeError: 'Env' object has no attribute '_docs'
```
As per the instructions above, I set `env XONSH_DEBUG=1` went back into xonsh and tried `xonfig wizard` but received the same error message. I then tried to set `$XONSH_SHOW_TRACEBACK = True` and ran `xonfig wizard` a third time but still just keep getting back the same error.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce
It was a fresh install from Pop_OS! `sudo apt install xonsh`, It typed `xonsh`, then `xonfig wizard`.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Current version of xonsh is 0.9.27. Please update and try again.
```python
python -m pip install -U 'xonsh[full]'
# xonsh 0.9.27
```

**Comment by MostHated** [comment]
I went ahead and removed the one from apt repo, then installed as you mentioned and things seem to be as they should be now. Instead of wizard, there was a web config which I went through, selected a few things and saved and went back to the shell, installed the manually required packages and everything seemed good. :+1: 

I appreciate it,
-MH
