### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by AndreiPashkin** [xonsh/xonsh#4189]
I have found the minimal way of how to reproduce the error but I'm not sure how to correctly describe what am I doing or am I using Xonsh as intended as I'm a new user. 

My practical use case is that I was trying to do something like `find ... | xargs @(lambda ...)`

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 8ad8b043             |
| Commit Date      | Mar 17 00:07:11 2021 |
| Python           | 3.9.1                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | none                 |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

</details>

## Expected Behavior
No exception.

## Current Behavior
Exception.

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/home/andrei/projects/xonsh/xonsh/xonsh/procs/pipelines.py", line 160, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/andrei/projects/xonsh/xonsh/xonsh/procs/specs.py", line 448, in run
    self._fix_null_cmd_bytes()
  File "/home/andrei/projects/xonsh/xonsh/xonsh/procs/specs.py", line 517, in _fix_null_cmd_bytes
    cmd[i] = cmd[i].replace("\0", "\\0")
AttributeError: 'function' object has no attribute 'replace'
```

</details>

## Steps to Reproduce
```
$ xonsh -DXONSH_SHOW_TRACEBACK=1 -c 'echo hello @(lambda args, stdin=None: "world")'
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/andrei/projects/xonsh/xonsh/xonsh/procs/pipelines.py", line 160, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/andrei/projects/xonsh/xonsh/xonsh/procs/specs.py", line 448, in run
    self._fix_null_cmd_bytes()
  File "/home/andrei/projects/xonsh/xonsh/xonsh/procs/specs.py", line 517, in _fix_null_cmd_bytes
    cmd[i] = cmd[i].replace("\0", "\\0")
AttributeError: 'function' object has no attribute 'replace'
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @AndreiPashkin !

> find ... | xargs @(lambda ...)

The Python substitution operator expects value, list or callable alias. These examples will work:
```python
echo @('Hello')
# Hello

echo @(['-n', 'World'])  # two arguments for echo
# World

echo Hello | @(lambda args, stdin: 'Callable ' + stdin.read() )
# Callable Hello
```
I recommend to read [xonsh tutorial](https://xon.sh/tutorial.html) and [xonsh cheatsheet](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md#---use-python-code-as-an-argument-or-a-callable-alias).

But you right we should add catching the exception.

**Comment by AndreiPashkin** [comment]
@anki-code, could you please explain in more detail - why is providing a callable as an argument wrong? Or - how can I pass Python code as xargs command using Xonsh?

**Comment by anki-code** [comment]
> why providing a callable as an argument is wrong? 
> how can I pass Python code as xargs command using Xonsh?

Please give me an example what you're doing and what you expect. 
The `xargs` tool is indifferent to python and expects arguments that described in `xargs --help`. When we call python substitution operator `@()` we commonly mean that we get the argument, or the arguments list from the python code i.e. `echo @(i for i in range(0, 10))` will produce 10 arguments for `echo`.

In common way:

1. You can use `xargs` as you are used to. You should just keep in mind only one thing that in xonsh you should use quotes for characters or braces. [Reade more](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md#three-most-frequent-things-that-newcomers-missed).

2. If you want to operate with arguments more Pythonic way the solution could be:

```python
for filename in `.*`:   # find all files by regex
    du -h @(filename)
```

3. If you want to using Python in a pipe try [xontrib-pipeliner](https://github.com/anki-code/xontrib-pipeliner).
