### ISSUE TITLE
Chaning terminal window size causes xonsh to print unwanted newlines in kitty terminal emulator

### ISSUE THREAD

**Issue by g33kex** [xonsh/xonsh#4194]
## xonfig

<details>

I've tested with `xonsh --no-rc` to have the default config. 

</details>

## Expected Behavior
When changing the window size in the kitty terminal emulator, xonsh prompt should stay at the same position and not insert newlines before printing a new prompt. It should not be reprinted at a different position when there is a window resize. 

## Current Behavior

When running xonsh in the kitty terminal emulator, changing the windows size (for example going to fullscreen and back) inserts some newline before reprinting the prompt. 
This means if you type a command that has an output, for instance this one:
```
@ ls /
```
(The @ sign symbolizes the xonsh prompt)

Then if you maximize the terminal window and unmaximize it, this is what happens to the prompt:
```
@ ls /
bin dev home lib64 opt .....
@


<a bunch of newlines, about a screen's worth>

@ 
```

So when going back from fullscreen mode to unmaximized mode, many new lines are inserted, and then the prompt is printed. 

This also happens if the window is resized manually. It does not happen though if the prompt was at the bottom of the terminal window before the resize. If the prompt is in the middle of the window, sometimes it just seems to prints the prompt again at each resize event. 

This only happens on xonsh with kitty, it doesn't seem to happen on other terminal emulators (it works fine on alacritty for example), and it doesn't happen with bash. 

Maybe it's the fact of how kitty handles changing the window size that's misinterpreted by xonsh, but in any case there seem to be a bug somewhere. 

## Steps to Reproduce

Open xonsh (I have version 0.9.24) in kitty (I have version 0.19.3). Make sure the prompt is at the top of the window. Run 
```
ls /
```
To get some output. Then maximize the window and unmaximize it. Your ls output will disappear and you'd have to scroll back up past all the new lines to see it. Also, if you try to resize the window manually, xonsh prompt will be printed multiple times during the resize. 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi! Could you please check the prompt toolkit version and update it i.e.
```python
pip list | grep prompt-toolkit
# prompt-toolkit-3.0.8
pip install -U prompt-toolkit
# prompt-toolkit-3.0.17
```
Then recheck the issue. Thanks!

**Comment by anki-code** [comment]
I'm going to close this issue because I've tested prompt toolkit and it looks like this is upstream issue in prompt-toolkit+Kitty.  Please open an issue in https://github.com/prompt-toolkit/python-prompt-toolkit

**Comment by anki-code** [comment]
How to test:
```python
# kitty
bash
cd /tmp
git clone --depth 1 https://github.com/prompt-toolkit/python-prompt-toolkit
cd python-prompt-toolkit/examples/prompts
python rprompt.py
# maximize minimize window
# maximize minimize window
# maximize minimize window
```
