### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by 89z** [xonsh/xonsh#4208]
I see a mention of Unicode here:

https://github.com/xonsh/xonsh/blob/main/docs/customization.rst#use-utf-8-characters-in-xonsh

but the characters listed:

~~~
     cpoint  dec    utf-8       html       name
'ß'  U+00DF  223    c3 9f       &szlig;    LATIN SMALL LETTER SHARP S
'ð'  U+00F0  240    c3 b0       &eth;      LATIN SMALL LETTER ETH
'đ'  U+0111  273    c4 91       &dstrok;   LATIN SMALL LETTER D WITH STROKE
~~~

are all 2 byte characters:

https://en.wikipedia.org/wiki/UTF-8#Encoding

If you try a 3 byte character, such as:

# ∞ (U+221E)

with PowerShell, you can paste the character, or on Windows you can enter as Alt + 236. However Xonsh does not accept paste or keyboard input of this character.

**Comment by anki-code** [comment]
> However Xonsh does not accept paste or keyboard input of this character.

I can't repeat this in Konsole on Arch:
```
echo ∞
# ∞
```

**Comment by 89z** [comment]
Windows yes

**Comment by anki-code** [comment]
Could it be related to the terminal emulator?

**Comment by 89z** [comment]
This issue is specific to Xonsh, as that character can be represented using a combination of any of these:

- Cmd.exe
- PowerShell.exe
- Console Host
- Windows Terminal

**Comment by anki-code** [comment]
I wanted to say about upstream but you already created the upstream issue :) So we can close this issue for xonsh. Thank you for reporting!

**Comment by 89z** [comment]
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1405
