### ISSUE TITLE
Remove ./ and ../ from cd and path completion

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4213]
Hi!

What about to remove `./` and `../` from the completion? 

![image](https://user-images.githubusercontent.com/1708680/113190898-90957c00-9265-11eb-9c28-dae6846bee84.png)

It's annoying when the directory has the one subdirectory and it's needed to see the list of `['../','./','subdir']` to choose the `subdir`.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Baileymnm1999** [comment]
@anki-code Does this accomplish what you would like?
