### ISSUE TITLE
Tons of test issues

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#423]
My first instinct when running the tests was to just run `py.test` in the xonsh directory. That leads to [these failures](https://gist.github.com/asmeurer/9ce34b1ffee14af5c26c#file-running-py-test-in-the-xonsh-directory). Then I looked in the CONTRIBUTING file to see if I was doing something wrong, and it said to run nosetests in the tests directory. OK, py.test is better, but whatever. I did that, and I got [this](https://gist.github.com/asmeurer/9ce34b1ffee14af5c26c#file-running-nosetests-in-the-tests-directory). Note the places where I had to control-C because it was (apparently) hanging (although I admit I wasn't the extremely patient with it). 

I think it might be picking up my installed xonsh, and I also think it is reading my bash profile information. 

Anyway, this makes it impossible to contribute any changes to xonsh because I can't write any tests if I can't run them.

**Comment by scopatz** [comment]
It looks like you need to reinstall xonsh from the repo (or modify your PYTHONPATH) because you are picking up a pre-v0.2.1 xonsh.

**Comment by asmeurer** [comment]
I did conda remove xonsh and still get a bunch of errors, especially with py.test (nosetests gives a bunch of errors, but mostly just junk output, and also it is *definitely* sourcing my .profile as part of the tests, which doesn't seem like a good idea).

**Comment by scopatz** [comment]
> I did conda remove xonsh and still get a bunch of errors, especially with py.test 

I don't think that matters, if these are the same errors as before. You need to `python setup.py install` to install xonsh before you test xonsh.  Are you doing that?

>  and also it is definitely sourcing my .profile as part of the tests, which doesn't seem like a good idea). 

That is a separate issue. Please open another issue for this.

**Comment by asmeurer** [comment]
> I don't think that matters, if these are the same errors as before. You need to python setup.py install to install xonsh before you test xonsh. Are you doing that?

I created a new conda environment and setup.py developed xonsh into it. It didn't seem to help. 

> That is a separate issue. Please open another issue for this.

https://github.com/scopatz/xonsh/issues/430

**Comment by scopatz** [comment]
Hmm I have never tried to do `setup.py develop` with xonsh. Are the errors the same?That is, are you still missing the new modules? Does the following point to the correct source/develop directory?

```console
python -c "import xonsh; print(xonsh.__file__)"
```

**Comment by asmeurer** [comment]
Yeah, looks like the same errors. Probably something weird is going on with py.test. But there are issues with nosetests as well (`test_parser.test_ls_nest_ls_dashl({}, '$(ls $(ls) -l)')`, `ls: -l: No such file or directory` is printed during the test; looking at it, it's probably related to my `ls` alias in my bash profile, i.e., #430).

**Comment by scopatz** [comment]
Ahh - OK.  I can turn off the execution of the lses.  It isn't meaningful to run the command anyway.

**Comment by asmeurer** [comment]
That sounds like it would help, and make the tests run faster for everyone.

**Comment by asmeurer** [comment]
And I guess py.test fails because the tests are explicitly designed to run with nose (py.test doesn't run setup() it would seem). So you can mark that as wontfix if you want.

**Comment by scopatz** [comment]
> That sounds like it would help, and make the tests run faster for everyone. 

Yup. I have taken a first stab at this and pushed it to master.  Let me know if I missed any.  

> And I guess py.test fails because the tests are explicitly designed to run with nose (py.test doesn't run setup() it would seem). So you can mark that as wontfix if you want. 

Ahh I see.  I wouldn't mind having both nose and py.test be supported, but I don't personally want to go through this exercise. Pull requests welcome :)

**Comment by asmeurer** [comment]
OK, that fixed the error. It is still hanging somewhere. And I still get the warnings printed to the terminal. The hanging is probably related to #430 because it happens right after text from my .profile is printed to the screen. It's a little annoying that nosetests suppresses the traceback when you keyboard interrupt the tests.

**Comment by scopatz** [comment]
I think you can run nosetests without capturing the stdout via the `-s` flag, if that helps.

**Comment by asmeurer** [comment]
That prints even more junk output during the tests but nothing around the part where it hangs.

**Comment by asmeurer** [comment]
Running it with the `-v` flag I get

```
test_parser.test_redirect({}, '$[echo "test" 2>1 1> test.txt < input.txt]', False) ... ok
Failure: SkipTest (prompt_toolkit is not available) ... SKIP: prompt_toolkit is not available
test_prompt_toolkit_tools.test_format_prompt_for_prompt_toolkit ... ok
<THIS IS THE PART WHERE IT PRINTS STUFF FROM MY .profile AND HANGS>
```

**Comment by scopatz** [comment]
Ahhh OK.  I see where it is hanging.  It is hanging in the replay - where the whole point is that it should source stuff. I'll turn it off for Mac.

**Comment by scopatz** [comment]
Alright, @asmeurer - Try the current master.  I have put in some stuff to skip the replay tests in your case.

**Comment by asmeurer** [comment]
> I'll turn it off for Mac.

Umm, OK. That seems like a bandaid. The real fix should be #430.

**Comment by scopatz** [comment]
Sure, but I only have time for bandaids today.

**Comment by asmeurer** [comment]
And also, the tests are still sourcing my .profile (and hanging).

**Comment by asmeurer** [comment]
This is not high priority.

**Comment by melund** [comment]
@asmeurer I also prefer py.test .. Pytest should be able to support nosetests, so I was a bit pussled that it didn't work. Now I figured out why. 

To make it work with pytest, we just need to rename module level test fixture from `setup()` to `setup_module()`, then pytest works again.

**Comment by melund** [comment]
@scopatz Here is the errors I get in pytest when running the tests on ffcad78b... on my win10 computer:

https://gist.github.com/melund/22a7ef8827e97be9773f

And the output from running nosetests:

https://gist.github.com/melund/2bfa3ac2d9e35977d59d

**Comment by scopatz** [comment]
Thanks @melund.  It seems like a simple `setup_module = setup` would work in most files.  Also some of the errors seem related windows specific drive/path issues.  Pull requests welcome for both of these.

**Comment by krader1961** [comment]
I'm not having any problems running the tests after I figured out two things:

1) You need to ensure the lexer/parser tables have been built: `python3 -c 'import setup; setup.build_tables()'`

2) You need to ensure ~/.xonshrc isn't loaded: XONSHRC=/dev/null nosetests

See https://github.com/krader1961/xonsh/tree/add-makefile for a proposed change that adds a makefile so you can simply type "make test-all" (or just "make test" to test just the uncommitted changes).

**Comment by scopatz** [comment]
I think that you also be able to set `$XONSHRC` to an empty string or an empty list too.

**Comment by krader1961** [comment]
> I think that you also be able to set $XONSHRC to an empty string

I'll verify that works and if it does use that form when I convert the run_tests script in my PR to be a xonsh script. That will make it possible to use the script on ms-windows. I vaguely recall that ms-windows has the equivalent of /dev/null but don't know if it supports accessing it via that pathname.

**Comment by Russell-Jones-OxPhys** [comment]
http://stackoverflow.com/questions/313111/dev-null-in-windows

**Comment by asmeurer** [comment]
You can use `os.devnull` if you are inside of Python or xonsh.

**Comment by krader1961** [comment]
On Tue, Nov 17, 2015 at 9:04 AM, Russell Jones <notifications@github.com>
wrote:

> http://stackoverflow.com/questions/313111/dev-null-in-windows
>

Yep, that matches my vague memory of the MS Windows equivalent of the UNIX
/dev/null. Thanks.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by laerus** [comment]
closing this issue, we moved to pytest afterall!
