### ISSUE TITLE
xsh not compatible for lsf

### ISSUE THREAD

**Issue by bobo-acount** [xonsh/xonsh#4242]
## xonfig

<details>

```
$ xonfig # use default xonfig
$ p = !(bjobs -sum)
$ print(p) # terminal shows input/output='' stdin/stdout/stderr=None
```

</details>

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

1. make sure IBM LSF installed
2.  p = !(bjobs -sum)
3. terminal shows following log:
“”“
RUN SSUSP USUSP
1       0         0
”“”
4. print(p) indicates there is no output log in p:
'''
stdin=None,
stdout=None,
stderr=None,
...
input='',
output='',
'''
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi! Does the `bjobs -sum` interactive tool or it just print the output?

You can try this workaround:
```
p = !(bjobs -sum | head -n 1000)  # this tells xonsh that the command is capturable
p
```

**Comment by bobo-acount** [comment]
hi sir,
thx a lot.
all of the solutions work well
