### ISSUE TITLE
Fix the installation command on the main page

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4247]
Hi @gforsyth !

Please change the xonsh installation command on the main page manually. We already have the right command in the main branch:

https://github.com/xonsh/xonsh/blob/a5292f70d100f6a7cdfee0a6c1a8309235d4acb3/docs/_templates_overwrite/index.html#L324

We don't know when we will have the new release (also because we're waiting 4218) but for now the users are facing with readline shell type by using the wrong command. We should fix the command manually for now. Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
And a short question. I think many people do typing `pip install xonsh` by default when them hearing about xonsh. 

I understand that we have `xonsh` and `xonsh[full]` to give a small and full mode. But why we give users the worst experience by default? I suggest to create `xonsh[min]` instead of `xonsh[full]` and use `xonsh` for the best experience.

**Comment by gforsyth** [comment]
Hey @anki-code -- if you can come up with a way to have `extras_require` remove any external dependencies, I'm all for it

**Comment by anki-code** [comment]
@gforsyth thank you for the fix on the main page! Please add quotes i.e. `pip install 'xonsh[full]'` because zsh don't like braces :)

**Comment by gforsyth** [comment]
Done -- and thanks for catching that @anki-code  (and for the initial suggestion)!

**Comment by anki-code** [comment]
> if you can come up with a way to have extras_require remove any external dependencies, I'm all for it

I've created the feature request to pip - https://github.com/pypa/pip/issues/9938
