### ISSUE TITLE
SQLite history backend with ignoredups control has wrong __xonsh__.history

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4248]
Hi!

SQLite history backend with `ignoredups` control has wrong `__xonsh__.history`.

The right behavior (6 commands in the history from 0 to 5):
```python
bash
HISTCONTROL='ignoredups' xonsh --no-rc
len(__xonsh__.history)
# 0
len(__xonsh__.history)
# 1
len(__xonsh__.history)
# 2
len(__xonsh__.history[:])
# 3
len(__xonsh__.history[:])
# 4
len(__xonsh__.history[:])
# 5
for h in __xonsh__.history: print(h.cmd)
# len(__xonsh__.history)
# len(__xonsh__.history)
# len(__xonsh__.history)
# len(__xonsh__.history[:])
# len(__xonsh__.history[:])
# len(__xonsh__.history[:])
exit
```

The wrong behavior:
```python
bash
XONSH_HISTORY_BACKEND=sqlite HISTCONTROL='ignoredups' xonsh --no-rc
len(__xonsh__.history)
# 0
len(__xonsh__.history)
# 1                                         # WRONG COUNTER
len(__xonsh__.history)
# 1                                         # WRONG COUNTER
len(__xonsh__.history[:])
# 3
len(__xonsh__.history[:])
# 4
len(__xonsh__.history[:])
# 5
for h in __xonsh__.history: print(h.cmd)
# len(__xonsh__.history)                                 # WRONG LIST
# len(__xonsh__.history)
for h in __xonsh__.history[:]: print(h.cmd)
# len(__xonsh__.history)
# len(__xonsh__.history)
# len(__xonsh__.history)
# len(__xonsh__.history[:])
# len(__xonsh__.history[:])
# len(__xonsh__.history[:])
# for h in __xonsh__.history: print(h.cmd)
exit
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Workaround is to use `__xonsh__.history[:]` instead of `__xonsh__.history`.

**Comment by anki-code** [comment]
Workaround:
```python
# load full history
history = [h for h in __xonsh__.history[:]]
# use history instead of __xonsh__.history
```

**Comment by jnoortheen** [comment]
AFAIK The variable is used when storing and in memory list is not affected.

**Comment by bcr** [comment]
Digging into it. The `SQLiteHistory.append` does what I expect:

```python
        if "ignoredups" in opts and inp == self._last_hist_inp:
            print("Skip")
            # Skipping dup cmd
            return
```

Prints `Skip` when it's time to skip.

**Comment by bcr** [comment]
> AFAIK The variable is used when storing and in memory list is not affected.

I think this lines up with `SQLiteHistory.append` anyway -- it updates the member variables with the history item and then skips the write to the database if `ignoredups` is set.

I did a search in the code for `ignoredups` to see if the behavior is defined. I only see:

https://github.com/xonsh/xonsh/blob/b0c81048af13da9bb301e7c807b247c15d975576/xonsh/environ.py#L1552

**Comment by bcr** [comment]
Digging back to ye olden times before the JSON backend separation, I think the intent of `ignoredups` is to ignore dupes both in-memory and when persisting.

https://github.com/xonsh/xonsh/blob/7231a20d9bf2e719f530ca1800430e028c7ae250/xonsh/history.py#L601

**Comment by jnoortheen** [comment]
@anki-code as explained, it is ignored when persisting onto the database. The in memory only checks the last item
