### ISSUE TITLE
adding stale bot to project

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4251]
What do you think about adding [stale](https://github.com/marketplace/stale) bot to the project. This will reduce number of issues that don't receive any input from the user and not traceable by the contributors. 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
I think this creates additional buzz without an additional value. 

The best thing that we can do for issues is to add more valuable labels i.e. `history`, `threading`, `environ` and other parts of xonsh.

Personally I think that there is two major thing that should be done for xonsh: the first is improving the core machinery around threading (hello 2159) and the second is finalisation the decision around XEP2 (hello 3924).
