### ISSUE TITLE
Ubuntu 20.04: gnome-terminal powershell and other graphics characters are wonky.

### ISSUE THREAD

**Issue by rcludwick** [xonsh/xonsh#4252]
In ubuntu 20.04 running xonsh in gnome-terminal seems to screw up graphical characters.  

```
$ cat .xonshrc

$XONSH_COLOR_STYLE = 'paraiso-dark'

$PL_PROMPT = "user>short_cwd"
$PL_RPROMPT = "!"
$PL_TOOLBAR = "!"

xontrib load autovox bashisms coreutils distributed fzf-widgets pipeliner
```

```
$ xonfig

+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.5                |
| shell type       | prompt_toolkit       |
| pygments         | 2.6.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | True                 |
| jupyter kernel   | None                 |
| xontrib 1        | autovox              |
| xontrib 2        | bashisms             |
| xontrib 3        | coreutils            |
| xontrib 4        | distributed          |
| xontrib 5        | fzf-widgets          |
| xontrib 6        | pipeliner            |
| xontrib 7        | voxapi               |
+------------------+----------------------+
```
</details>

## Expected Behavior

Graphical characters should be rendered correctly.

## Current Behavior

So trying to run powerline for the prompt yields something that looks like this:

https://twitter.com/RobLudwick/status/1378944720840237058

Sshing to the raspberry pi looks like this while running raspi-config.  Note the offset characters and menu that's not centered.

![image](https://user-images.githubusercontent.com/1568675/116836108-8cb98a00-ab82-11eb-87b8-c558b66757b3.png)

In bash all this works correctly.

## Steps to Reproduce

In Ubuntu 20.04 run gnome-terminal create a new profile.  In the new profile run xonsh instead of bash.  Then try to set up powerline or run any graphical menu in ubuntu.

**Comment by anki-code** [comment]
Hi! Some bullets:
* Try to update `pip install -U prompt-toolkit`
* I'm not recommended to use `bashisms` because of 4250 issue
* If you like `pipeliner` please give a star to the repo https://github.com/anki-code/xontrib-pipeliner and to xonsh repo as well - it will help to grow the community.
* `Then try to set up powerline or run any graphical menu in ubuntu.` - give us a repeatable example please.

**Comment by rcludwick** [comment]
> give us a repeatable example please.

```sudo dpkg-reconfigure debconf```

![image](https://user-images.githubusercontent.com/1568675/117551541-d2070d00-b003-11eb-94dc-b0fd1a846d4f.png)

Then this is what it looks like from the gnome-terminal bash profile.

![image](https://user-images.githubusercontent.com/1568675/117551584-1b575c80-b004-11eb-9bea-f2a42174f7fe.png)

**Comment by rcludwick** [comment]
self inflicted wound.  Ambiguous width characters was set to "wide".  It should have been set to narrow.
