### ISSUE TITLE
history show all is slow

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#4268]
Hi,

I'm trying to replace ^R behavior to use fzf - basically piping the result of `history show all` to fzf.

The thing is, it takes 83s to run `history show all`.

Any way to speed this up? Why should it take this long?

Alternatively, can we have an option for it to start producing output immediately, even if it's incomplete? It seems to gather the whole history and then show it. For the purposes of fzf, I'm OK if it does it piecemeal (and not preserving order).

## xonfig

```
+------------------+------------------------------------------------+
| xonsh            | 0.9.24                                         |
| Python           | 3.8.8                                          |
| PLY              | 3.11                                           |
| have readline    | True                                           |
| prompt toolkit   | 3.0.8                                          |
| shell type       | prompt_toolkit                                 |
| pygments         | 2.7.2                                          |
| on posix         | True                                           |
| on linux         | True                                           |
| distro           | gentoo                                         |
| on darwin        | False                                          |
| on windows       | False                                          |
| on cygwin        | False                                          |
| on msys2         | False                                          |
| is superuser     | False                                          |
| default encoding | utf-8                                          |
| xonsh encoding   | utf-8                                          |
| encoding errors  | surrogateescape                                |
| on jupyter       | True                                           |
| jupyter kernel   | /home/mueen/.local/share/jupyter/kernels/xonsh |
+------------------+------------------------------------------------+

```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @beetleb! What kind of history backend you're using?

Personally I've got around 20k rows from the history for less then a second:
```python
$XONSH_HISTORY_BACKEND
# 'sqlite'

history show all | wc -l
# 20651

timeit! history show all > /dev/null
# 10 loops, best of 3: 20.7 ms per loop

# Prepared by xontrib-hist-format
```

If you want to read all history as fast as possible you can use appropriate tools:
```python
# sqlite
sqlite3 $XONSH_HISTORY_FILE  "SELECT inp FROM xonsh_history;"

# json
cat $XONSH_DATA_DIR/*.json $XONSH_DATA_DIR/history_json/*.json | jq -c '.data.cmds[].inp'
```

**Comment by anki-code** [comment]
I see you use old version of xonsh and prompt-toolkit. Please update `pip install -U 'xonsh[full] prompt-toolkit'`

**Comment by anki-code** [comment]
> I'm trying to replace ^R behavior to use fzf

@beetleb also please take a look at [github xontribs page](https://github.com/topics/xontrib) and i.e. [xontrib-fzf-widgets](https://github.com/laloch/xontrib-fzf-widgets).

**Comment by beetleb** [comment]
Upgrading dropped to 43s. Still too slow. 

I'm using the json backend (default).

I can believe switching to sqlite will fix this, but I can't test it - because if I switch I lose all my history! Is there no way to migrate json history into sqlite? I found this old gist: https://gist.github.com/mitnk/d9385c60e113eef14e41d42509846a5c - would it be safe to use?

In any case, if the only way to get fast history is to use sqlite, perhaps this should be documented somewhere - especially given that json is the default.

BTW, I have this problem on 2 machines (very different setups).

Yes - I am aware of xontrib-fzf-widgets and am modifying it for my own needs. I don't think I touched the ^R portion, so I doubt it's due to any modifications I made.

**Comment by beetleb** [comment]
Also, I wiped out my rc.xsh and tried it - it took over a minute - so I doubt my config file is the problem.

In any case, I'm fine with switching to sqlite if I can migrate my history. I do think it's worth having the issue open for the json backend - either to see if it can be sped up or to have a way for it to return results while its processing instead of waiting till it has gathered the whole history.

(I have about 8k rows in my history)

What I don't get is how PgUp for completing a line is so fast...

**Comment by beetleb** [comment]
OK. Deleting all those extra files solved my problem. Now it's practically instant. You can ignore all the complaints above (although I do need to check why it's slow on my other machine - pretty sure I don't have a cron job there).

**Comment by anki-code** [comment]
> Is there no way to migrate json history into sqlite?

Yes! Here is the code - https://github.com/xonsh/xonsh/discussions/4132
