### ISSUE TITLE
Add new lables for the issues

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4273]
Hi @gforsyth!

Please add new labels for the issues:
* history
* history sqlite
* history json
* completion
* threading
* environ
* speed
* jupyter
* high priority

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Done.

**Comment by anki-code** [comment]
@gforsyth please add the `alias` label.
