### ISSUE TITLE
Using captured stdout breaks the piping from the callable alias

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4277]
Hi!

The captured subprocs breaks the piping from the callable alias.

### Case 1: piping into capturable command

This works as expected:
```python
xonsh --no-rc

def _callme(args):
    print('one\ntwo\nthree')

aliases['callme'] = _callme
callme | grep t
# two
# three

# Prepared by xontrib-hist-format
```

But the same code with added the one line:

```python
xonsh --no-rc

def _callme(args):
    $(echo 1)
    print('one\ntwo\nthree')

aliases['callme'] = _callme
callme | grep t
# No response, terminal freezed, Ctrl+C Ctrl+D Ctrl+Z have no effect
```

Workaround is using `!()`:
```python
def _callme(args, stdin=None, stdout=None):
    out = !(echo -n "one\ntwo\nthree")
    for line in out:
        stdout.write(line + '\n')

aliases['callme'] = _callme
callme | grep t
# two
# three
```

### Case 2: piping into uncapturable command

We want to `less` many lines and this is working:
```python
def _lines(cmd, stdin=None, stdout=None, stderr=None):
    for line in [str(i) for i in range(1,100)]:
        stdout.write(line+'\n')

aliases['lines'] = _lines
lines | less
# Less allows to scroll lines
```
But the same code with added the one line with `$()`:
```python
def _lines(cmd, stdin=None, stdout=None, stderr=None):
    $(echo 0)  # Just added this line without using it
    for line in [str(i) for i in range(1,100)]:
        stdout.write(line+'\n')

aliases['lines'] = _lines
lines | less
# Freezed
```
And the same code with added the one line with `![]`:
```python
def _lines(cmd, stdin=None, stdout=None, stderr=None):
    ![echo 0]  # Just added this line without using it
    for line in [str(i) for i in range(1,100)]:
        stdout.write(line+'\n')

aliases['lines'] = _lines
lines | less
# Printing first part of lines and less is not working.
```
And the same code with added the one line with `$[]`:
```python
def _lines(cmd, stdin=None, stdout=None, stderr=None):
    $[echo 0]  # Just added this line without using it
    for line in [str(i) for i in range(1,100)]:
        stdout.write(line+'\n')

aliases['lines'] = _lines
lines | less
# Print 0
# Freezed
```

### Case 3: Using uncaptured subprocess breaks the piping from the callable alias with the error

See #4281

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Workaround is using `!()`:
```python
def _callme(args, stdin=None, stdout=None):
    out = !(echo -n "one\ntwo\nthree")
    for line in out:
        stdout.write(line + '\n')

aliases['callme'] = _callme
callme | grep t
```

**Comment by anki-code** [comment]
References to the code to diving into this issue:
1. [predict_threadable](https://github.com/xonsh/xonsh/blob/27db574d99ab1be1d0435ca9e298830c0f2aba66/xonsh/commands_cache.py#L292) function to mark the command threadable/unthreadable
2. [run_subproc](https://github.com/xonsh/xonsh/blob/27db574d99ab1be1d0435ca9e298830c0f2aba66/xonsh/procs/specs.py#L844) function that runs the subproc commands in captured/uncaptured mode
3. [_update_last_spec](https://github.com/xonsh/xonsh/blob/27db574d99ab1be1d0435ca9e298830c0f2aba66/xonsh/procs/specs.py#L720) function to modify last command
4. [CommandPipeline](https://github.com/xonsh/xonsh/blob/27db574d99ab1be1d0435ca9e298830c0f2aba66/xonsh/procs/pipelines.py#L92) class that has the logic around capturing the stds

And a big picture:

<details>

![image](https://user-images.githubusercontent.com/1708680/116824270-fbeaaa80-ab91-11eb-8ab0-378c3ed93507.png)

</details>

**Comment by anki-code** [comment]
> Case 1: piping into capturable command

Let's try [to trace](https://github.com/xonsh/xonsh/discussions/4183) this freezing case on Linux:

```python
$PYTHONHUNTER='depth_lt=100,stdlib=False,module_startswith=\'xonsh.procs\'' $XONSH_DEBUG=1 xonsh -c @("""
def _callme(args):
    $(echo 1)
    print(123)
aliases['callme'] = _callme
callme | grep 1
""") a> /tmp/case1_log

# Wait 10 sec and press Ctrl+C (this is working in not interactive mode)

vim /tmp/case1_log
```
In the log we see the infinite loop here:

https://github.com/xonsh/xonsh/blob/e02c7d76c4ae169408078c8695214589552617c9/xonsh/procs/posix.py#L159-L180

The infinite loop appears on runnning `grep 1` command. 

It looks like using the captured stdout (`$(echo 1)`) breaks the pipe and `grep 1` dead in infinite waiting for stdin (`while proc.poll() is None`). And the Ctrl+C combination can't stop this infinite loop.

Any help with solving this are very welcome!

**Comment by yaxollum** [comment]
@anki-code This seems to be a job control issue, because when I replace the line
https://github.com/xonsh/xonsh/blob/1919b7dc80d74c4663c83fecb308adf6c58ace7e/xonsh/procs/pipelines.py#L247

with 
```python
task = None
```
all of the examples which you gave work as expected. Of course, this isn't a proper fix since it will break tasks that need to be waited for.

I'm not very familiar with the job control system, but I'll try to investigate how this can be fixed.

**Comment by anki-code** [comment]
@yaxollum it will be great! Thanks!
