### ISSUE TITLE
add tutorial for completers with `CompletionContext` and add some standard completers

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4285]
The completers tutorial [here](https://xon.sh/dev/tutorial_completers.html) need to be updated to reflect completers with `CompletionContext` and the utility methods.

Also `xonsh ` should have some standard completer classes like [`ptk`](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#nested-completion) does. Especially `NestedCompleter` can be used for setting completions for most of the CLIs.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
@jnoortheen good call!
I would like to write the tutorial, so you want to take on writing a Nested Completer?

**Comment by jnoortheen** [comment]
> do you want to take on writing a Nested Completer?

Sorry, I am currently trying to create completer generated from argparser. It will be useful for some of my xontribs.

**Comment by gforsyth** [comment]
Closed via #4307
