### ISSUE TITLE
Allow User to specify alternative clipboard tool

### ISSUE THREAD

**Issue by JackofSpades707** [xonsh/xonsh#4301]
## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.27          |
| Python           | 3.9.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.18          |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.4           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | True            |
| jupyter kernel   | None            |
| xontrib 1        | abbrevs         |
| xontrib 2        | autovox         |
| xontrib 3        | autoxsh         |
| xontrib 4        | avox            |
| xontrib 5        | fzf-widgets     |
| xontrib 6        | jedi            |
| xontrib 7        | prompt_ret_code |
| xontrib 8        | voxapi          |
| xontrib 9        | z               |
+------------------+-----------------+

pyperclip==1.7.0

```

</details>

## Expected Behavior
I'd like to be able to copy & paste things when using xonsh :)

## Current Behavior

The issue is probably within the scope of pyperclip, but allowing users to specify an alternate clipboard utility would be really nice.

Basically, when I press CTRL+W or CTRL+K it tries to use pyperclip (which provides a traceback every time I try to use it, even though it's installed)

I'm glad you guys recently opted to make those keybinds for deleting text a configurable option for copying them to the clipboard :)

Although, It's probably because I'm using Windows -> Arch Linux via WSL2.
However, I configured things to where xclip works, and I'd love to be able to specify a way to use that instead of pyperclip, at least temporarily, and There are other people who'd enjoy this I'm certain. https://github.com/asweigart/pyperclip/issues/169

If it's something that's easy to implement, I don't mind making a pull request to let others do this too

### Traceback (if applicable)

<details>

```
Unhandled exception in event loop:
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 168, in callback_wrapper
    callback()
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 691, in read_from_input
    self.key_processor.process_keys()
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_processor.py", line 274, in process_keys
    self._process_coroutine.send(key_press)
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_processor.py", line 186, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_processor.py", line 329, in _call_handler
    handler.call(event)
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 102, in call
    result = self.handler(event)
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/key_binding/bindings/named_commands.py", line 364, in kill_line
    event.app.clipboard.set_text(deleted)
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/clipboard/base.py", line 101, in set_text
    self._clipboard().set_text(text)
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/clipboard/base.py", line 52, in set_text
    self.set_data(ClipboardData(text))
  File "/usr/lib/python3.9/site-packages/prompt_toolkit/clipboard/pyperclip.py", line 25, in set_data
    pyperclip.copy(data.text)
  File "/usr/lib/python3.9/site-packages/pyperclip/__init__.py", line 301, in __call__
    raise PyperclipException(EXCEPT_MSG)

Exception
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error
Press ENTER to continue...

```

</details>

## Steps to Reproduce
use [Windows Terminal](https://github.com/microsoft/terminal) -> use WSL2 -> use xonsh -> try to copy something with built-in copy mechanic

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by JackofSpades707** [comment]
OH, I should also note, that if I set my default shell to /bin/bash $(chsh -s /bin/bash)
and within ~/.bashrc I exec $(xonsh).
The copy/paste mechanics work (although this leads to other issues)

**Comment by JackofSpades707** [comment]
What's even weirder is that pyperclip says :
"On Linux, this module makes use of the xclip or xsel commands, which should come with the os. Otherwise run "sudo apt-get install xclip" or "sudo apt-get install xsel" (Note: xsel does not always seem to work.)"

So maybe pyperclip is attempting to do things the Windows way within WSL2?

Because xclip works just fine, but pyperclip itself doesn't.

**Comment by daniel-shimon** [comment]
I also use wsl2, and on it pyperclip uses powershell and some other windows utility

Seems to my like you need to add a PR to pyperclip

**Comment by JackofSpades707** [comment]
Thanks, I agree that's the best solution, and hopefully, I get the time to tackle that soon :)
In the mean time I'll just keep my default shell as /bin/bash and have that call xonsh in my ~/.bashrc until I can look at it in more depth
