### ISSUE TITLE
pager - input incorrectly interpreted [Windows Terminal]

### ISSUE THREAD

**Issue by JackofSpades707** [xonsh/xonsh#4302]
pager keyboard input broken
I've only tested `git diff` and `man make`
but this should affect program that uses `less` as it's default pager.

## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.27          |
| Python           | 3.9.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.18          |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.4           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | True            |
| jupyter kernel   | None            |
| xontrib 1        | abbrevs         |
| xontrib 2        | autovox         |
| xontrib 3        | autoxsh         |
| xontrib 4        | avox            |
| xontrib 5        | fzf-widgets     |
| xontrib 6        | jedi            |
| xontrib 7        | prompt_ret_code |
| xontrib 8        | voxapi          |
| xontrib 9        | z               |
+------------------+-----------------+

[Windows Terminal](https://github.com/microsoft/terminal)
WSL 2 : Arch Linux
/usr/bin/xonsh set as default shell
```

</details>

## Expected Behavior
Arrow keys should work
q should quit

## Current Behavior
It forwards what appears to be the terminals raw interpretation of the keyboard input to the pager as individual characters into the pagers buffer, meaning that interacting with the pager is broken and you can't simply quit.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce
Use:
[Windows Terminal](https://github.com/microsoft/terminal)
WSL 2 : Arch Linux
And run $(man make)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by JackofSpades707** [comment]
I should also note, this only happens when it displays the diff as a pager (like /bin/more | /bin/less)
If it appears to simply cat out the diff, it exits before any input is required, which doesn't cause any issues.

My guess is this is an issue with how Windows Terminal interprets user input, and hands them to the shell (xonsh)

**Comment by JackofSpades707** [comment]
Yup.

Windows Terminal -> Bash    -> $(man make) = no issue
WSLTTY                  -> xonsh  -> $(man make) = no issue
Windows Terminal -> xonsh  -> $(man make) = issue

**Comment by JackofSpades707** [comment]
Duplicate of https://github.com/xonsh/xonsh/issues/4243
Running `xonsh --no-rc` solves the problem.

**Comment by JackofSpades707** [comment]
I'm reopening this along with a solution for this.

If you simply set the LESS environment variable to '-Xr' the issue goes away. and since man uses less by default, it fixes it there as well.

```xonsh
$LESS="-Xr"
```

**Comment by JackofSpades707** [comment]
Closing. This is terminal Specific.

**Comment by swedneck** [comment]
somehow i am running into this on fedora 34, and neither `--no-rc nor` `$LESS='-Xr'` helps. I have troubleshooted to make sure that it's not my terminal as well.
