### ISSUE TITLE
Take my money? [Donate]

### ISSUE THREAD

**Issue by JackofSpades707** [xonsh/xonsh#4303]
I want this to continue to grow and succeed.
Words of appreciation are nice, but don't really do a whole lot.
I don't have much time to contribute to this or make xontribs currently. (But in the future, that's something I'd like to do)
Take my money instead?

How can I donate?

I can only donate via BTC or credit/debit card unfortunately

**Comment by anki-code** [comment]
Hi! Thank you for you suggestion! We haven't the way to donate now.
I'm going to close this with reference to #3375
