### ISSUE TITLE
Problem with interfering with OSC sequences

### ISSUE THREAD

**Issue by zasdfgbnm** [xonsh/xonsh#4304]
See: https://github.com/muesli/duf/issues/129, you can reproduce using `duf`.

**Comment by daniel-shimon** [comment]
Hi! Can you try setting `$THREAD_SUBPROCS=False`and then running it?

**Comment by muesli** [comment]
@daniel-shimon That indeed works around the problem!

**Comment by daniel-shimon** [comment]
Cool! See https://github.com/xonsh/xonsh/issues/4024#issuecomment-854504082
