### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4305]
Hi! Three months have passed since previous release. We have a bunch of new features in https://github.com/xonsh/xonsh/tree/main/news. So let's release them!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
Hi! Before we release a version:
1. I'd like to wait at least for the completers tutorial in #4285
I'm working on it and will finish it in the coming days
2. Make sure amalgamation works in pip (as discussed in #4290). It seems to work now when `pip install .` from the source code, but `pip install xonsh` with the previous version doesn't do it
