### ISSUE TITLE
Subprocess call not rendering TUI properly

### ISSUE THREAD

**Issue by JackofSpades707** [xonsh/xonsh#4309]
## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.27          |
| Python           | 3.9.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.18          |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.4           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | True            |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+

```

</details>

## Expected Behavior

neovim should render properly and respond to the input as opposed to simply typing the raw keys over existing text

## Current Behavior

neovim is typing raw keys over text (when called by another binary within xonsh, when called directly, this isn't the case)
#4302 may hold some relevancy here as well.
NOTE: `:q` will actually exit neovim, so the behavior is a bit different from the issue mentioned above.

### Traceback (if applicable)

<details>

```
N/A
```

</details>

## Steps to Reproduce

Terminals: `Windows 10 Terminal` | `Fluent Terminal` | `wsltty`
Shell: `/bin/bash xonsh --no-rc` | `xonsh`
Command: `yay -S $aur_pkg --editmenu --nodiffmenu`
- Select at least 1 PKGBUILD script to edit so that `yay` spawns an instance of nvim.
- type anything.
![image](https://user-images.githubusercontent.com/17239750/121027860-27961d00-c75c-11eb-97ee-8b1c34efc523.png)
![image](https://user-images.githubusercontent.com/17239750/121027944-37adfc80-c75c-11eb-9bbf-148fe65c40c9.png)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by JackofSpades707** [comment]
using wsltty with a TUI [xonsh --no-rc]:
![image](https://user-images.githubusercontent.com/17239750/121043888-e442ab00-c769-11eb-8be2-7c78150051bb.png)

using wsltty with a TUI [bash]:
![image](https://user-images.githubusercontent.com/17239750/121043997-00dee300-c76a-11eb-8c98-0089ef13edb4.png)

**Comment by daniel-shimon** [comment]
Does `$THREAD_SUBPROCS=False` solve it?

**Comment by JackofSpades707** [comment]
🤦 
Sorry for opening the issue.
Thank you.

**Comment by JackofSpades707** [comment]
> Does `$THREAD_SUBPROCS=False` solve it?

Is there a good reason that this is enabled by default?

**Comment by daniel-shimon** [comment]
> > Does `$THREAD_SUBPROCS=False` solve it?
> 
> Is there a good reason that this is enabled by default?

See #4283
