### ISSUE TITLE
Add news file linting checks to gh action

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#4313]
We currently check that the news item is correctly formatted in our regular `pytest` CI runs -- the result of this is that when there is an improperly formatted news item most of the CI checks fail.

Now that @jnoortheen has created a standalone news checker, we can move the linting check there (maybe?) and remove it from the other `pytest` runs.

**Comment by jnoortheen** [comment]
We better move it to the qa check along flake8.
