### ISSUE TITLE
xonsh disables ^Z suspend character on linux

### ISSUE THREAD

**Issue by caedmon-kitty** [xonsh/xonsh#4315]
<!--- If you have a question along the lines of "How do I do this Bash command in xonsh"

^Z does not suspend a currently running process on linux
In fact ^Z appears to do nothing

I have removed all entries from .xonshrc except setting the prompt like this:
$PROMPT = '{GREEN}⇨ {RESET}'

using stty I can see xonsh disables susp.  First using zsh all is well:

zsh-term> stty -a
speed 38400 baud; rows 54; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
...

launch xonsh

zsh-term> xonsh
⇨ stty -a
speed 38400 baud; rows 54; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = <undef>;
...

Note that susp is <undef>

The same thing happens if i run xterm -e xonsh.  susp is <undef>
and ^Z does nothing

**Comment by anki-code** [comment]
Hi! Basically xonsh implement it's own behavior for ^Z. Because this issue has empty description I'm going to close this with reference to the tutorial - https://xon.sh/tutorial.html#job-control. If you have a feature request or a bug request please provide more info in the new issue.
