### ISSUE TITLE
^Z is ignored on linux

### ISSUE THREAD

**Issue by caedmon-kitty** [xonsh/xonsh#4318]
## xonfig

xonsh 0.9.27
Fedora Linux version 33
xonsh installed via pip3

I have removed all entries from .xonshrc except setting the pronpt
$PROMPT = '{GREEN}⇨ {RESET}'

<details>
When running an application in the foreground ^Z is ignored.  I.e., the running application is NOT suspended.  <br>The only command xonsh accepts is ^C which kills the running application.
<br><br>
Example of running a pdf viewer evince.  I twant to move the application to the background so I may enter additional commands:
<br><br>
Enter the command:<br>

```
⇨ evince file.pdf
^Z
```
^Z echos as shown above but nothing else happens.<br><br>
Try ^C to kill the application
```
⇨ evince file.pdf
^C
⇨
```
^C worked<br><br>

There appears no way to suspend a running application

</details>

## Expected Behavior

<details>
^Z should suspend the running application
</details>

## Current Behavior

<details>
Nothing happens
</details>

### Traceback (if applicable)

<details>

</details>

## Steps to Reproduce

1.  Enter any long running CLI command
2. type ^Z
3. Note that the ^Z is ignored - nothing happens

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
@caedmon-kitty Can you try setting `$THREAD_SUBPROCS` to `False` in your xonshrc?

**Comment by caedmon-kitty** [comment]
@yaxollum

Setting $THREAD_SUBPROCS to False fixes the problem.  ^Z works as expected.
