### ISSUE TITLE
About the return value of a custom function

### ISSUE THREAD

**Issue by YouXam** [xonsh/xonsh#4323]
## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.6.9                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.18               |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.4                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | True                 |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | True                 |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

</details>

## Expected Behavior

When I enter the following code:
```
root@LAPTOP ~ # def f(s):
...............     print(s + '.')
...............
...............
root@LAPTOP ~ # @f`1`
```
The output I want to get is:
```
1.
```
or:
```
1.
None
```

## Current Behavior

Current output(when $XONSH_SHOW_TRACEBACK = True):
```
1.
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xonsh/base_shell.py", line 374, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/local/lib/python3.6/dist-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/xonsh/built_ins.py", line 162, in pathsearch
    return o if len(o) != 0 else no_match
TypeError: object of type 'NoneType' has no len()
```

</details>

## Other

In fact, as long as the object returned by the function does not have a "\_\_len\_\_" method, this error will occur

**Comment by yaxollum** [comment]
@YouXam I don't think there's anything unexpected about the error.

[From the xonsh tutorial](https://xon.sh/tutorial.html#custom-path-searches):
> A search function is defined as a function of a single argument (a string) that **returns a list of possible matches** to that string.

Your function `f` doesn't have a return statement, so it returns `None`, which obviously is not a "list of possible matches."

This is why you're getting `TypeError: object of type 'NoneType' has no len()`.

<hr>

I'm not sure what you're trying to do with this code. If all you want to do is call the function `f` normally, you should use the regular Python syntax:

```python
def f(s):
    print(s+'.')

f('1') # call the function normally
```
<hr>

If you actually want to use `f` for custom path searching, you should change it to:
```python
def f(s):
    return [s+'.'] # return a list containing a single string
```
so that you can call it using the custom path searching syntax:

```xonsh
@f`1`
```

**Comment by anki-code** [comment]
To understand how functions can be called in xonsh please read:
* [Basics](https://xon.sh/tutorial.html#basics)
* [Aliases](https://xon.sh/tutorial.html#aliases)
* [Custom path searches](https://xon.sh/tutorial.html#custom-path-searches)
* [Macros](https://xon.sh/tutorial_macros.html)
