### ISSUE TITLE
fish-like partial suggestion completion

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4330]
Xonsh already supports the fish-like suggestion completion, which is great. I.e., on a greyed suggestion, typing the right arrow completes with the full suggestion.

One thing I miss though is the fish partial suggestion completion. In fish, if I am right, when a suggestion is provided, typing "alt + right_arrow" completes the suggestion only until the next separator. Great to use parts of a suggestion only.

Any way a partial suggestion completion with alt + right_arrow is either already available, or could be added? :) .

**Comment by jnoortheen** [comment]
Yeah that would be awesome. The auto-suggest part comes from [ptk[(https://github.com/prompt-toolkit/python-prompt-toolkit)'s featureset. I don't think it is available right now. But one can easily implement it.

**Comment by daniel-shimon** [comment]
Hey, this actually does exist in xonsh with ALT-F if I'm not mistaken

We could add a default key binding for ALT-RIGHT like you suggest, I think it will be really cool
See https://github.com/xonsh/xonsh/issues/3639#issuecomment-654215680
