### ISSUE TITLE
typo on the xonsh xontrib website

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4333]
On this website: https://xon.sh/xontribs.html

This instruction:

```
# install with pip
xpip install xontrib-fzf-widgets
```

Is probably wrong, should be:

```
# install with pip
pip install xontrib-fzf-widgets
```

**Comment by jerabaul29** [comment]
Another small note: ```fzf``` needs to be installed on the sytem (for example with a ```sudo apt install fzf```) before this works of course, but wonder if may be useful to name in the documentation too :) .

**Comment by jnoortheen** [comment]
'xpip'  is a wrapper around pip. It is correct to use it to install xontrib packages.

**Comment by jerabaul29** [comment]
Ok, interesting, xpip did not work on my machine but pip did.

**Comment by jnoortheen** [comment]
can you check that you are inside xonsh shell? and run commands like `xonfig`

**Comment by jerabaul29** [comment]
Aaah, you are right: ```xpip``` does not work from a "normal" bash terminal, but it does work from a xonsh terminal.

One annoying thing though: xpip seems to ask for the sudo password:

```
jj@MBX20:~$ xonsh
jj@MBX20 ~ $ xpip
[sudo] password for jj: 
```

while the "normal" ```pip3``` approach was simply defaulting to userspace installation, thus requiring no sudo, which I of course like better :) .

**Comment by gforsyth** [comment]
> the "normal" `pip3` approach was simply defaulting to userspace installation, thus requiring no sudo, which I of course like better :) .

huh, that's interesting.  the default behavior of `pip` is to install into the `site-packages` directory.  I wonder if your OS has some customization to default to `--user` installs?

**Comment by jerabaul29** [comment]
I wonder if this is a "modern pip3" behavior:

```
~$ pip3 install xontrib-fzf-widgets
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xontrib-fzf-widgets in ./.local/lib/python3.8/site-packages (0.0.4)
```

My version:

```
~$ pip3 --version
pip 21.1.1 from /home/jrmet/.local/lib/python3.8/site-packages/pip (python 3.8)
```

(note that it complains that even that is not the latest :) ).

**Comment by jnoortheen** [comment]
You may want to install xonsh in its own environment. 'pipx' will come in handy.

**Comment by jnoortheen** [comment]
This is more like a configuration issue, than a bug. Closing this. Please feel free to create a [discussion thread](https://github.com/xonsh/xonsh/discussions) if you face any difficulty getting started. 

1. Install [pipx](https://pypa.github.io/pipx/)

```
pipx install "xonsh[full]"

# then start your shell as usual
$ xonsh

$ xpip --version
```
