### ISSUE TITLE
Why don't readline and prompt-toolkit use the same function for coloring?

### ISSUE THREAD

**Issue by yaxollum** [xonsh/xonsh#4340]
**Question: Why don't readline and prompt-toolkit use the same function for coloring? They seem to have two different `print_color()` functions that are intending to do the same task:**

- readline `print_color()`
https://github.com/xonsh/xonsh/blob/86f02c034182e2c7211036f1bba0a460df909e77/xonsh/readline_shell.py#L650
- prompt-toolkit `print_color()`
https://github.com/xonsh/xonsh/blob/86f02c034182e2c7211036f1bba0a460df909e77/xonsh/ptk_shell/shell.py#L508

<hr>

The readline `print_color()`, when passed a string, uses `self.format_color()`, which then uses `ansi_partial_color_format()`

https://github.com/xonsh/xonsh/blob/86f02c034182e2c7211036f1bba0a460df909e77/xonsh/ansi_colors.py#L133

The prompt-toolkit `print_color()`, when passed a string, tokenizes the string using `partial_color_tokenize`, and then uses pygments to format the tokens.

<hr>

The different functions have some behavior differences, for example: #1403, #3801, #4339

Also, pygments doesn't support many of the formatting modifiers:
https://github.com/xonsh/xonsh/blob/948129b7a0cdb734ac0d025b4393c9924b0b0ca0/xonsh/pyghooks.py#L141-L163
so something like `xonsh.tools.print_color("{STRIKETHROUGH_RED}test")` displays correctly on readline, but not on prompt-toolkit.

Can someone please explain why there need to be two different `print_color` functions? Why can't both prompt-toolkit and readline use `ansi_partial_color_format()`? 

Thanks
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
AFAIK, pygments is not available with the default installation and these differences evolved over time. Contributions are always, to cleanup and merge similar functionality.

**Comment by gforsyth** [comment]
Yeah, the backends have drifted apart and will probably continue to, especially where styling is concerned.  PRs are welcome, but I'm going to close this out as answered.
