### ISSUE TITLE
how to define and use bash functions?

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4341]
I am a bit confused and I do not manage to find the answer in the documentation (probably I am just so confused that I do not manage to find the right place where to look in the doc :( ).

How can I 1) define, 2) use a bash function in Xonsh? For example, in bash, I can do:

```
jj@MBX20:~$ hello_world(){
> echo "hello world"
> }
jj@MBX20:~$ hello_world 
hello world
```

But in Xonsh:

```
jj@MBX20 ~ $ hello_world() {
............ echo "hello world"
............ }
............
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:1:14: ('code: {',)
hello_world() {
              ^
```

Any ways to "natively" define and run bash functions in Xonsh? (I am confused as I thought Xonsh was practically some form of superset of bash).

**Comment by jnoortheen** [comment]
It is a superset of Python. It essentially has some ways to run commands like other shell languages (which under the hood uses subprocess module). Please check the https://xon.sh/bash_to_xsh.html guide
