### ISSUE TITLE
weird intermixed output lines issues when running a given python script from a Xonsh terminal

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4346]
I am hitting a weird intermixed lines output bug when running a range of python scripts using the ```icecream``` package. I am on Ubuntu 20.04, using Python 3.8.10, icecream 2.1.1, and xonsh 0.9.27.

If I run this script, calling it example.py (it is a toy script derived from looking at a similar problem in some production code):

```python
from icecream import ic

ic.configureOutput(prefix='')

print("a line")
print("another line")
print("yet another line")

i1 = 1
i2 = 2
i3 = 3

ic(i1)
ic(i2)
ic(i3)

for i in range(5):
    print("this is line {}".format(i))
```

- from my "normal" bash shell I get the expected output:

```
$ python3 example.py 
a line
another line
yet another line
i1: 1
i2: 2
i3: 3
this is line 0
this is line 1
this is line 2
this is line 3
this is line 4
```

- from a xonsh terminal I get intermixed lines:

```
$ python3 example.py 
a line
another line
yet another line
i1: 1
i2: 2
this is line 0
this is line 1
this is line 2
this is line 3
this is line 4
i3: 3
```

This is super, super confusing when debugging code... Any idea what creates this? I think this is somehow related to Xonsh, since it happens when I run from a xonsh terminal but not from a bash terminal...

**Comment by jnoortheen** [comment]
it is same as the ones reported here https://github.com/xonsh/xonsh/issues/2129 , https://github.com/xonsh/xonsh/issues/2561 I guess

**Comment by jerabaul29** [comment]
Mmmh, ok. Seems these are stalled, right? Quite painful :( .

**Comment by jerabaul29** [comment]
(and yes, you are right, the problem comes from the fact that icecream writes to stderr by default, in which case, the stdout and stderr seem to be intermixed...).

**Comment by jerabaul29** [comment]
This is really painful, but in this specific case, there is a simple workaround :) 

https://github.com/gruns/icecream/issues/77

It definitely is the same issue, so closing, hope this gets better somehow in the future :) .

**Comment by daniel-shimon** [comment]
This issue appears a lot and can be improved by having two different threads for stderr and stdout in pipeline's `iterraw` function.
Any volunteers? 😊

**Comment by jnoortheen** [comment]
> This issue appears a lot and can be improved by having two different threads for stderr and stdout in pipeline's `iterraw` function.
> Any volunteers?

As specified in other issue comments, it is more like the issue with buffering. each interface has threads already. in fact three for stdin, stdout and stderr
