### ISSUE TITLE
let Xonsh automatically create closing ) " ' ] } for the user

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4349]
In Xonsh when I type I often end up in situations like this screenshot. What happens is that I start typing a string, but Xonsh does not understand it as a string yet (there is no terminating "), and as a consequence, Xonsh colorizes stuff as if it were faulty python code:

![Screenshot from 2021-07-01 13-53-04](https://user-images.githubusercontent.com/8382834/124120334-f2879c80-da73-11eb-8090-da7fa76b3c28.png)

The problem of course disappears as soon as the closing " is added:

![Screenshot from 2021-07-01 13-53-08](https://user-images.githubusercontent.com/8382834/124120355-fca99b00-da73-11eb-817d-966f4bf1fd1d.png)

My question is: is there a way to / how could I make sure that Xonsh "auto types" the closing ) " ' ] } for me as I type? I.e., that typing " actually produces double "" and puts my cursor in the middle of them, and typing ( actually produces () and puts my cursor in the middle, as most text editors / IDE would do?

**Comment by daniel-shimon** [comment]
Hi! Try setting `$XONSH_AUTOPAIR=True`

**Comment by jerabaul29** [comment]
That did it, amazing, many thanks :) .

Wondering if it would make sense to have it as a default :) .

But this is solved, so closing.
