### ISSUE TITLE
Xonsh shell pipe problem

### ISSUE THREAD

**Issue by DHammarberg** [xonsh/xonsh#4352]
## xonfig

<details>
+------------------+----------------------------------+
| xonsh            | 0.9.27                           |
| Python           | 3.9.5                            |
| PLY              | 3.11                             |
| have readline    | True                             |
| prompt toolkit   | 3.0.18                           |
| shell type       | prompt_toolkit                   |
| pygments         | 2.9.0                            |
| on posix         | True                             |
| on linux         | True                             |
| distro           | arch                             |
| on darwin        | False                            |
| on windows       | False                            |
| on cygwin        | False                            |
| on msys2         | False                            |
| is superuser     | False                            |
| default encoding | utf-8                            |
| xonsh encoding   | utf-8                            |
| encoding errors  | surrogateescape                  |
| on jupyter       | True                             |
| jupyter kernel   | /usr/share/jupyter/kernels/xonsh |
+------------------+----------------------------------+

</details>

## Expected Behavior

Pipes should work.

## Current Behavior

I need a remedy for my xonsh Shell pipe problem

Since 1-2 months back, I've got this odd likely pipe-related problem with Xonsh. Somehow, when it opens other shells, scripts and stuff, it messed up the pipe sockets. This results in not being able to send any input to programs like more, less, etc. Basic terminal input through Bash:s read command and stuff works, but no pipes.

I'm not entirely sure how to put the problem any more plainly in words, which is why I thought I'd supply some log history I've created. I've compared running the same trivial script through three different paths:

1: My usual Arch Linux Xonsh environment (where pipes in scripts fail).
2: Bash in said environment (where the same things work)
3: A Debian server of mine running Xonsh (which works too)

I've also noticed that in the buggy environment, the ending less is opened before the program it's supposed to receive output from. Anyway, below are the logs, so to speak - the file handles from starting a 1-line script piping jq output through less:

### Traceback (if applicable)

<details>

	My "go-to" Arch Linux Xonsh environment: (running prompt_toolkit3)

	1_shell/fd/:

	lrwx------ 1 daniel daniel 64  1 jul 17.35 0 -> /dev/pts/36
	lrwx------ 1 daniel daniel 64  1 jul 17.35 1 -> /dev/pts/36
	lrwx------ 1 daniel daniel 64  1 jul 17.35 2 -> /dev/pts/36
	lrwx------ 1 daniel daniel 64  1 jul 17.35 255 -> /dev/pts/36

	1_one-liner/fd/:

	lrwx------ 1 daniel daniel 64  1 jul 17.35 0 -> /dev/pts/36
	lrwx------ 1 daniel daniel 64  1 jul 17.35 1 -> /dev/pts/36
	lrwx------ 1 daniel daniel 64  1 jul 17.35 2 -> /dev/pts/36
	lr-x------ 1 daniel daniel 64  1 jul 17.35 255 -> (( 1-line Bash script ))

	1_jq/fd/:

	lrwx------ 1 daniel daniel 64  1 jul 17.35 0 -> /dev/pts/36
	l-wx------ 1 daniel daniel 64  1 jul 17.35 1 -> 'pipe:[569259498]'
	lrwx------ 1 daniel daniel 64  1 jul 17.35 2 -> /dev/pts/36
	lr-x------ 1 daniel daniel 64  1 jul 17.35 3 -> (( JSON file ))
	
	1_less/fd/:

	lr-x------ 1 daniel daniel 64  1 jul 17.35 0 -> 'pipe:[569259498]'
	lrwx------ 1 daniel daniel 64  1 jul 17.35 1 -> /dev/pts/36
	lrwx------ 1 daniel daniel 64  1 jul 17.35 2 -> /dev/pts/36
	lr-x------ 1 daniel daniel 64  1 jul 17.35 3 -> /dev/pts/36
	

	Arch Linux Bash environment: (the shell I've left behind for Xonsh)

	2_shell/fd/:

	lrwx------ 1 daniel daniel 64  1 jul 17.36 0 -> /dev/pts/76
	lrwx------ 1 daniel daniel 64  1 jul 17.36 1 -> /dev/pts/76
	lrwx------ 1 daniel daniel 64  1 jul 17.36 2 -> /dev/pts/76
	lrwx------ 1 daniel daniel 64  1 jul 17.36 3 -> /dev/ptmx
	lrwx------ 1 daniel daniel 64  1 jul 17.36 4 -> 'anon_inode:[eventpoll]'
	lrwx------ 1 daniel daniel 64  1 jul 17.36 5 -> 'socket:[569061930]'
	lrwx------ 1 daniel daniel 64  1 jul 17.36 6 -> 'socket:[569061931]'
	lrwx------ 1 daniel daniel 64  1 jul 17.36 7 -> /dev/pts/117
	lrwx------ 1 daniel daniel 64  1 jul 17.36 8 -> /dev/ptmx
	lrwx------ 1 daniel daniel 64  1 jul 17.36 9 -> /dev/pts/121

	2_one-liner/fd/:

	lrwx------ 1 daniel daniel 64  1 jul 17.36 0 -> /dev/pts/76
	lrwx------ 1 daniel daniel 64  1 jul 17.36 1 -> /dev/pts/117
	lrwx------ 1 daniel daniel 64  1 jul 17.36 2 -> /dev/pts/121
	lr-x------ 1 daniel daniel 64  1 jul 17.36 255 -> (( 1-line Bash script ))

	2_jq/fd/:

	lrwx------ 1 daniel daniel 64  1 jul 17.36 0 -> /dev/pts/76
	l-wx------ 1 daniel daniel 64  1 jul 17.36 1 -> 'pipe:[569274279]'
	lrwx------ 1 daniel daniel 64  1 jul 17.36 2 -> /dev/pts/121
	lr-x------ 1 daniel daniel 64  1 jul 17.36 3 -> (( JSON file ))

	2_less/fd/:

	lr-x------ 1 daniel daniel 64  1 jul 17.36 0 -> 'pipe:[569274279]'
	lrwx------ 1 daniel daniel 64  1 jul 17.36 1 -> /dev/pts/117
	lrwx------ 1 daniel daniel 64  1 jul 17.36 2 -> /dev/pts/121
	lr-x------ 1 daniel daniel 64  1 jul 17.36 3 -> /dev/pts/121

	Debian Xonsh environment: (entered prompt_toolkit2 in .xonshrc, yet loading ptk3. )

	xonsh:

	lrwx------ 1 daniel daniel 64  1 jul 17.47 0 -> /dev/pts/17
	lrwx------ 1 daniel daniel 64  1 jul 17.47 1 -> /dev/pts/17
	lrwx------ 1 daniel daniel 64  1 jul 17.47 2 -> /dev/pts/17
	lrwx------ 1 daniel daniel 64  1 jul 17.47 3 -> 'anon_inode:[eventpoll]'
	lrwx------ 1 daniel daniel 64  1 jul 17.47 4 -> 'socket:[1604535]'
	lrwx------ 1 daniel daniel 64  1 jul 17.47 5 -> 'socket:[1604536]'
	lrwx------ 1 daniel daniel 64  1 jul 17.47 6 -> /dev/ptmx
	lrwx------ 1 daniel daniel 64  1 jul 17.47 7 -> /dev/pts/42
	lrwx------ 1 daniel daniel 64  1 jul 17.47 8 -> /dev/ptmx
	lrwx------ 1 daniel daniel 64  1 jul 17.47 9 -> /dev/pts/43

	bash:

	lrwx------ 1 daniel daniel 64  1 jul 17.52 0 -> /dev/pts/17
	lrwx------ 1 daniel daniel 64  1 jul 17.52 1 -> /dev/pts/42
	lrwx------ 1 daniel daniel 64  1 jul 17.52 2 -> /dev/pts/43
	lr-x------ 1 daniel daniel 64  1 jul 17.52 255 -> (( 1-line Bash script ))

	jq:

	lrwx------ 1 daniel daniel 64  1 jul 17.53 0 -> /dev/pts/17
	l-wx------ 1 daniel daniel 64  1 jul 17.53 1 -> 'pipe:[110134119]'
	lrwx------ 1 daniel daniel 64  1 jul 17.53 2 -> /dev/pts/43
	lr-x------ 1 daniel daniel 64  1 jul 17.53 3 -> (( JSON FILE ))

	less:

	lr-x------ 1 daniel daniel 64  1 jul 17.56 0 -> 'pipe:[110134119]'
	lrwx------ 1 daniel daniel 64  1 jul 17.56 1 -> /dev/pts/42
	lrwx------ 1 daniel daniel 64  1 jul 17.56 2 -> /dev/pts/43
	lr-x------ 1 daniel daniel 64  1 jul 17.56 3 -> /dev/tty

I'd be thankful for any help. This is a serious inconvenience at present.

</details>

## Steps to Reproduce

I could provide access to my computer system if needed, if someone takes significant interest in this problem.

**Comment by daniel-shimon** [comment]
Hi! Thanks for the detailed report!
Can you provide the exact command line you are running?

**Comment by DHammarberg** [comment]
The command line wasn't really relevant, but I did still end up managing to come up with a fix for my problem - after reading anki-code's post about the capturing problem, I simply altered subproc_captured_hiddenobject() to call run_subprocess() with captured set to False instead. It is a satisfying solution for me now, with everything working, though I guess one could have managed a somewhat more clean one if one had delved more into the threading issue.

**Comment by daniel-shimon** [comment]
In that case this should already work on main since https://github.com/xonsh/xonsh/pull/4283
Can you verify this?

**Comment by jnoortheen** [comment]
Closing this since version 0.11 is out and doesn't try to capture by default
