### ISSUE TITLE
completion ordering

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4356]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | bc3b4962             |
| Commit Date      | Jun 11 12:27:29 2021 |
| Python           | 3.9.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.19               |
| shell type       | prompt_toolkit       |
| history backend  | sqlite               |
| pygments         | 2.9.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | argcomplete          |
| xontrib 3        | avox_poetry          |
| xontrib 4        | back2dir             |
| xontrib 5        | broot                |
| xontrib 6        | cmd_done             |
| xontrib 7        | commands             |
| xontrib 8        | fzf-widgets          |
| xontrib 9        | hist_navigator       |
| xontrib 10       | jedi                 |
| xontrib 11       | powerline3           |
| xontrib 12       | prompt_ret_code      |
| xontrib 13       | vox                  |
| xontrib 14       | voxapi               |
+------------------+----------------------+

```

</details>

## Expected Behavior

This is to discuss the behavior of ordering the completions by name. This is not useful in some cases. For example, 
`git checkout` on bash brings the local branch names first. Since we order the completions in xonsh it shows the `origin/...` and tag names first. This makes the branch completion not much useful.

## Current Behavior

The ordering should be left to the completer functions.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
I agree, should we poll this?
Still, there are some nuances to this:

1. If we're changing this we need to ensure the other completers sort by
themselves.
2. What about non exclusive completers? They return first but don't
necessarily need to be the first completions.

**Comment by jnoortheen** [comment]
1. we change the default completers that comes with xonsh and make sense with byname-sort.
2. aren't we supposed return first the exclusive completions ? since we also have completion number restrictions it is best to find exclusive ones first right?

**Comment by gforsyth** [comment]
> I agree, should we poll this?

I don't think we have to -- there's an old (possibly still open?) issue about this.  When we were still using `set` to handle mashing together non-exclusive completions preserving completion order wasn't an option.

**Comment by jnoortheen** [comment]
@gforsyth  How can we approach this?

**Comment by gforsyth** [comment]
I suspect most of the issues caused by sorting all completions lies in the bash completers that we re-use.

So we defer the sorting to the completers -- for non-exclusive completers, I'd be curious to see how it looks (and feels) if we just concatenate the various completers results as they come in.

For the non-exclusives, our options are, I think, threefold:
1. block concatenation (completer A's results, then completer B's results)
2. chaos concatenation (interleave results without regard to whether completer A is sorted or not or B is sorted or not)
3. sorted concatenation (slurp up all the completions, then sort)

I think 3 could potentially block for too long, but not certain.  I think 2 is... maybe not great?  Depends on the two completers involved.  I think my vote would be for 1, but I'm open to whatever implementation.

**Comment by jnoortheen** [comment]
Now the completer accept generators. I am closing this on behalf of #1408
