### ISSUE TITLE
Stuck in Git help pager

### ISSUE THREAD

**Issue by Megaguy32** [xonsh/xonsh#4360]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.18               |
| shell type       | prompt_toolkit       |
| pygments         | 2.9.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | True                 |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | cd                   |
| xontrib 3        | powerline2           |
| xontrib 4        | readable-traceback   |
| xontrib 5        | vox                  |
| xontrib 6        | voxapi               |
| xontrib 7        | z                    |
+------------------+----------------------+
```

</details>

## Expected Behavior
navigate and exit the help normally

## Current Behavior

I'm unable to navigate the git pager help with arrow keys. and am unable to quit with q.
instead I get append output like the following
```
^[OB^[OB^[OBqqq
```

## Steps to Reproduce

```shell
git help branch
```
then try pressing down, and/or q 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
Hi, this will be resolved in the upcoming release
For now you can set `$THREAD_SUBPROCS = True` for that command.
Note that it will disable output capturing in `![]`

**Comment by Megaguy32** [comment]
Thanks @daniel-shimon!

**Comment by daniel-shimon** [comment]
Sure thing!

**Comment by con-f-use** [comment]
I have a similar problem where a bash script opens neovim. `$THREAD_SUBPROCS = True` doesn't help here. Any thoughts? @gforsyth @scopatz 

```
$ cat vimwrapper                                                😱  😱
#!/usr/bin/env bash

nvim "$@"
$ ./vimwrapper /proc/cpuinfo
```

and than this is what happens:

![image](https://user-images.githubusercontent.com/11145016/125137939-f8355000-e10d-11eb-85aa-654f355bb00b.png)

**Comment by daniel-shimon** [comment]
Hi, my bad! Try setting `$THREAD_SUBPROCS = False`.
 Also see https://github.com/xonsh/xonsh/pull/4283 for the fix (as you can there have been many issues surrounding this subject)

**Comment by con-f-use** [comment]
Very nice, thanks a lot!
