### ISSUE TITLE
EnvPath.add() doesn't maintain uniqueness with Path objects

### ISSUE THREAD

**Issue by egnor** [xonsh/xonsh#4366]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | 2.9.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | apt_tabcomplete      |
| xontrib 2        | direnv               |
| xontrib 3        | kitty                |
| xontrib 4        | linuxbrew            |
+------------------+----------------------+
```

</details>

## Expected Behavior
`EnvPath.add(thing)` (e.g. `$PATH.add(thing)`) should not allow multiple copies of `thing` to enter the list, compared as strings.

## Current Behavior (and reproduction steps)
`EnvPath.add("str")` and `EnvPath.add(p"str")` do not detect each other's entries:

```
egnor@ostrich ~ $ $PATH
EnvPath(
['/usr/local/sbin',
 '/usr/local/bin',
 '/usr/sbin',
 '/usr/bin',
 '/sbin',
 '/bin',
 '/usr/games',
 '/usr/local/games',
 '/snap/bin']
)
egnor@ostrich ~ $ $PATH.add("/home/egnor/bin")
egnor@ostrich ~ $ $PATH.add(p"~/bin")
egnor@ostrich ~ $ $PATH
EnvPath(
['/usr/local/sbin',
 '/usr/local/bin',
 '/usr/sbin',
 '/usr/bin',
 '/sbin',
 '/bin',
 '/usr/games',
 '/usr/local/games',
 '/snap/bin',
 '/home/egnor/bin',
 '/home/egnor/bin']
)
```

This is because `EnvPath.add(data)` will put its data (of any type, `Path` or `str`) into the object directly, and `Path("foo") != "foo"`.

My first instinct was to have `EnvPath.add(data)` include `data = str(data)`, but then I realized that `EnvPath.__init__` was explicitly written to allow a mixed bag of `Path` and `str` objects, so I wasn't sure what was desired. `EnvPath` is documented as being a "list of strings" so I would expect it to stringify everything on entry, but maybe there's some concerns with that?

Note that `$PATH.add(p"~/bin")` seems like a very logical and idiomatic thing to put in one's `.xonshrc`, but due to this bug will end up with repeated copies when subshells occur.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
Hi!

> EnvPath.add(thing) (e.g. $PATH.add(thing)) should not allow multiple copies of thing to enter the list, compared as strings.

Why? 
AFAIK the OS doesn't mind and other shells allow this as well.

**Comment by egnor** [comment]
The `.add` method is specifically documented not to add duplicates (with
flags controlling precise de-duping semantics), and in general when all the
items are "str" it does not, and that seems to be that method's whole
reason to exist, vs `.append` or whatnot.

The general use case is adding to `$PATH` or similar strings in one's
`.xonshrc` without ending up with an ever expanding path full of dupes due
to subshells that launch each other for various reasons.

This all works just fine but the `Path`/`str` mixture seems to break that.

>

**Comment by daniel-shimon** [comment]
Oh sorry I missed you used add instead of append

**Comment by meramsey** [comment]
Can confirm this is still a thing too. Also even with add used and replace it never removes all copies before inserting the one in front. So you will still have consistent issues.

![image](https://user-images.githubusercontent.com/1596188/132262503-ff91e3c7-aba0-4c73-baa9-964362bec31a.png)
![image](https://user-images.githubusercontent.com/1596188/132262525-70067811-40b9-4a71-9471-69e643824159.png)

Still think the suggestion from: https://github.com/xonsh/xonsh/issues/2562#issuecomment-357891119
Was sleekest way to clean this up after
![image](https://user-images.githubusercontent.com/1596188/132262586-98c3a08b-1bdd-43f4-8aca-017ac4644995.png)
