### ISSUE TITLE
Return status of previous command not readily accessible in prompt fields

### ISSUE THREAD

**Issue by egnor** [xonsh/xonsh#4367]
Many dynamic shell prompts will show a flag when the previous command failed with a nonzero return code. (This is mostly applicable for pipeline commands, not Python commands, naturally.)

However, I see no straightforward way to do this in xonsh. The [bash-to-xonsh guide](https://xon.sh/bash_to_xsh.html) says to use `_.rtn`, which is great interactively, but the `_` variable's binding seems to be inconsistent. When the prompt is first rendered it is not defined at all. It doesn't seem to be present in `globals()`.

If `_` (or something analogous) were readily available from a prompt field function that would be great -- I could use `isinstance(_, CommandPipeline)` and if True use `_.rtn`. But, I can't quite sort out how to do that.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by egnor** [comment]
This seems to work, but feels icky. Is this reasonable / is there a better way / any gotchas?

```
def _add_command_error():
    from xonsh.procs.pipelines import CommandPipeline as CP

    def prompt_command_error():
        rv = __builtins__.get("_")
        return rv.returncode if isinstance(rv, CP) and rv.returncode else None

    $PROMPT_FIELDS["command_error"] = prompt_command_error

_add_command_error()
```

**Comment by daniel-shimon** [comment]
Hi, This functionality is available in the `prompt_ret_code` xontrib!
You're welcome to go see it's code in the `xontrib` dir

**Comment by egnor** [comment]
Aha, `xonsh.built_ins.XSH.history.rtns` is the magic!

(Maybe consider moving that into main? Seems like a good thing to have in `$PROMPT_FIELDS` by default?)

**Comment by jnoortheen** [comment]
> (Maybe consider moving that into main? Seems like a good thing to have in `$PROMPT_FIELDS` by default?)


I also think it is good to have in the default prompt fields. what do you think @daniel-shimon

**Comment by daniel-shimon** [comment]
Yeah sure, sounds good
