### ISSUE TITLE
Document that non-interactive xonsh shells don't source .xonshrc

### ISSUE THREAD

**Issue by egnor** [xonsh/xonsh#4377]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.19               |
| shell type       | prompt_toolkit       |
| pygments         | 2.9.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | apt_tabcomplete      |
| xontrib 2        | direnv               |
| xontrib 3        | kitty                |
+------------------+----------------------+
```

</details>

## Discussion
The circumstances where `.xonshrc` is loaded or not loaded would be documented on the "[Run Control File](https://xon.sh/xonshrc.html)" page. Currently, that only says this:

> Xonsh allows you to customize your shell behavior with run control files, called “xonshrc” files. These files are written in the xonsh language (a superset of Python) and are executed exactly once at startup.

That can lead to the mistaken impression that it's _always_ executed at startup.

Other shells (bash, zsh, csh, etc) typically have a whole flotilla of startup file options that get sourced or not depending on whether the shell is interactive or not and login shell or not. I would argue that this conventional system is overwrought, overcomplicated and failure prone and I am very much in favor of simplicity, especially if all important non-interactive configuration can be inherited through the environment. (Alternatively, one could argue that xonsh scripts should always run with a predictable configuration, at least for behavioral things? Hmm.)

Anyway, this choice (and the philosophy under it) should be clearly documented, and the differences from other shells called out.

## Steps to Reproduce
1. Be a noob setting up xonsh
2. Get slightly confused by the documentation, wonder why your `.xonshrc` isn't being loaded in some cases
3. File yet another nitpicky bug report

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by EternityForest** [comment]
Making shell scripts that depend on local config(Which might even be a user's personal config) like that seems like a bit of an antipattern, so running .xonsh only interactively seems like a good plan.

Either that, or we need to always run but provide a standard reliable way to check if you are interactive or not.  Either way, it needs to be decided and documented!

**Comment by gforsyth** [comment]
The `xonshrc` files are only loaded if the shell is running in interactive mode (or if you force it by including the `-i` flag.  We're always open to improvements to the docs!
