### ISSUE TITLE
bg command does not work after suspending running app with ^Z

### ISSUE THREAD

**Issue by caedmon-kitty** [xonsh/xonsh#4380]
## xonfig

<details>
When using ^Z to interrupt a running app I try to put the app into the background using the bg command.  Instead the app is put into the foreground and subsequent commands are ignored until the running app exists.
```
$ xonfig
```

</details>

## Expected Behavior

bg should put the suspended app into the background.  xonsh should respond to input from the keyboard.

### Traceback (if applicable)

<details>
The suspended app is put into the foreground with the bg command.

</details>

## Steps to Reproduce

```
# Note two line prompt.  Keyboard input is after '⇨' character
~ @ Cowboys
⇨ evince file.pdf

# Enter ^Z
~ @ Cowboys
⇨ bg
[1]+ running: evince nest-doorbell-cam-210706.pdf (40260)

ls
# The app is run in the foreground and the "ls" command entered is ignored until the evince app exits. 
``
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by caedmon-kitty** [comment]
Forgot the details
Fedora Linux version 33
xonsh compiled from repository pull'ed on on 12 July 2021.

**Comment by daniel-shimon** [comment]
Hi! Can you try again with xonsh `0.10.1`?

**Comment by caedmon-kitty** [comment]
Just installed 0.010.1  The problem still persists.  ^Z suspends the running application.  The bg command resumes it but the prompt does not return.

~ @ Cowboys                                                                     
⇨ evince file.pdf
# Enter ^Z                                                  
~ @ Cowboys                                                                     
⇨ bg                                                                            
[1]+ running: evince file.pdf (11739)
# No prompt

Entering ^Z after the bg command does result in a prompt.  The task appears to continue to run in the background.

I ran my tests without an .xonshrc file to avoid possible conflicts.

**Comment by daniel-shimon** [comment]
Is the issue that the prompt isn't printed? If you press enter does it get printed?
Or is the problem functional?

**Comment by caedmon-kitty** [comment]
Prompt does not get printed when hitting enter or any input other than ^Z or ^C (^C also kills the application).

If I enter another command (ls for example) it is echoed but otherwise ignored.

**Comment by caedmon-kitty** [comment]
Does anyone have a patch or hack to fix this.  It is really getting in the way of my productivity.

**Comment by ylmrx** [comment]
Regarding the workflow, you could run évincé with a & at the end of the line so it backgrounds the command from the start (evince has no CLI interaction, you don't really ever need it on foreground)

**Comment by alvarv** [comment]
I have observed the same behaviour (xonsh 0.11, Ubuntu 20.04).
@ylmrx is right, of course, but the problem is sometimes you hit Return too soon... :roll_eyes: 
A workaround that works for me: after entering bg<Return>, **hit ^Z again**! I then get back my prompt, and the process continues operating in the background as expected...

**Comment by tkossak** [comment]
Same problem here:
xonsh 0.12.2
Linux Manjaro
