### ISSUE TITLE
DeprecationWarning: There is no current event loop

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#4409]
I get this error running the latest `xonsh[ptk]` on Python 3.10:

```
/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/application/application.py:882: DeprecationWarning: There is no current event loop
  loop = get_event_loop()
```

The warning emits on every command entered.

The upstream issue is https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1440.

**Comment by jaraco** [comment]
Adding this to my .xonshrc works around the issue:

```
# workaround https://github.com/xonsh/xonsh/issues/4409
__import__('warnings').simplefilter('ignore', DeprecationWarning, 882)
```

**Comment by henryiii** [comment]
FYI, brew has now switched the xonsh recipe to Python 3.10, so this pops up all the time on any brew installed xonsh.

**Comment by jnoortheen** [comment]
It is now fixed upstream

**Comment by mharig** [comment]
Reappeared in xonsh 0.13.4/Python 3.10.9

**Comment by jnoortheen** [comment]
@mharig what is the version of prompt-toolkit ?

**Comment by jaraco** [comment]
See https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1696.

**Comment by mharig** [comment]
@jnoortheen prompt-toolkit 3.0.36
@jaraco So I have to wait until someone fixes this in something. Rather annoying. But I forget to mention, that the warning does not pop up on every command, but only after the start of xonsh. So it is not sufficient painful to use the workaround.
