### ISSUE TITLE
Windows: fail to complete after C: 

### ISSUE THREAD

**Issue by educhana** [xonsh/xonsh#442]
In windows path completion is not working when referring to other disk than current.

To reproduce simply put:

C:

or 

C:\

And try to complete with tab.

Python version: 3.4
xonsh version: 0.2.2

**Comment by scopatz** [comment]
Thanks for reporting. Pull requests very welcome.

**Comment by adqm** [comment]
This actually looks like it is still an issue, even after the tab completer updates.  `C:\<tab>` seems to work, but not `C:<tab>`.

**Comment by adqm** [comment]
I think has been resolved on current master, so I will close for now.  If this issue persists, please feel free to reopen.
