### ISSUE TITLE
xonsh.bat script ignoring parameters in windows

### ISSUE THREAD

**Issue by educhana** [xonsh/xonsh#443]
xonsh.bat files dont pass parameters down

this causes that:

xonsh -c script

ignores the execution of requested script.

should be very simple to fix xonsh.bat simply adding %*
```
@echo off
python -m xonsh.main %*
```

**Comment by scopatz** [comment]
See #444

**Comment by scopatz** [comment]
Thanks for reporting @educhana!

**Comment by scopatz** [comment]
This has been fixed for a while.
