### ISSUE TITLE
C-k and C-y don't behave as expected

### ISSUE THREAD

**Issue by arnfaldur** [xonsh/xonsh#4430]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.10.0          |
| Python           | 3.9.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.18          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.9.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on wsl           | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | True            |
| jupyter kernel   | None            |
| xontrib 1        | argcomplete     |
| xontrib 2        | coreutils       |
| xontrib 3        | kitty           |
| xontrib 4        | prompt_starship |
| xontrib 5        | vox             |
| xontrib 6        | voxapi          |
| xontrib 7        | z               |
+------------------+-----------------+
```

</details>

## Expected Behavior

`C-k` *kills* the characters after the cursor and `C-y` yanks them back to the line.
pressing these two in succession after pressing `C-a` should essentially be a no op, just a cut and paste.
## Current Behavior

When I try to yank with `C-y` nothing happens.

## Steps to Reproduce

`C-a C-k C-y` is all I do, I don't do anything else in a newly opened shell to make it happen.
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting this @arnfaldur!

I can reproduce this.  Also, if I have `pyperclip` installed (optional clipboard dependency) then `C-y` "works" in that it pastes what is in my system clipboard, but not what I've put into the kill ring using `C-k`.

So I think we have two issues:
1. If `pyperclip` is present, `C-k` should dump into that
2. `C-y` should be able to pull from the default `prompt_toolkit` kill-ring.

cc @jnoortheen who I think was working on some clipboard stuff

**Comment by jnoortheen** [comment]
there is [this code](https://github.com/xonsh/xonsh/blob/10778ecaa56ce114d5b00e23e15fa2eb7ffa8c5f/xonsh/ptk_shell/shell.py#L142) which disables some kill-ring related shortcuts. It was added after enabling sytem clipboard integration. Are you trying to do the actions in them?

**Comment by gforsyth** [comment]
wow, I had definitely forgotten about that.

Oddly, even setting `$XONSH_COPY_ON_DELETE=True` doesn't fix this -- I wonder if we need to set it before startup.

I have confirmed that if `pyperclip` is installed that `C-y` does pull from that clipboard:

```
(base)   ~ 🐚  __xonsh__.shell.shell.prompter.clipboard.set_text("123abc")
(base)   ~ 🐚  123abc     # <--- C-y
```

**Comment by gforsyth** [comment]
Awesome, thanks for the pointer there @jnoortheen !

@arnfaldur -- if you have `$XONSH_COPY_ON_DELETE=True` in your `xonshrc` file then `C-a C-k C-y` should function as expected

**Comment by gforsyth** [comment]
Nope, even without `pyperclip`, `C-a C-k C-y` will work -- but note that `$XONSH_COPY_ON_DELETE` isn't responsive within a given prompt session, it needs to be set either before startup or in the `rc` files

**Comment by arnfaldur** [comment]
Great! `$XONSH_COPY_ON_DELETE=True` fixed it. Thanks a lot for looking into it.

Feel free to close it unless you consider this fix to the issue to be temporary.

**Comment by gforsyth** [comment]
I'm going to close it out unless folks want to have a conversation around changing defaults.
Thanks again for reporting!

**Comment by sbliven** [comment]
Is it possible to set up xonsh to use a different clipboard? I use the kill ring a lot in bash, and I like that it is separate from the system pasteboard. `$XONSH_COPY_ON_DELETE=True` means that I'm constantly replacing system copy/paste with trivial terminal commands. (macOS, xonsh 0.10.1)

I would also suggest documenting this in the bash transition guide.

**Comment by daniel-shimon** [comment]
Hi @sbliven, the integration with the normal clipboard happens when `pyperclip` is installed. You can uninstall it to remove the integrations.
I agree this should be documented, PRs welcome!

**Comment by sbliven** [comment]
I got my desired behavior by uninstalling pyperclip (`xpip uninstall pyperclip`) and setting `$XONSH_COPY_ON_DELETE=True` in .xonsh.

The default `$XONSH_COPY_ON_DELETE=False` doesn't seem useful to me either with or without pyperclip. I would recommend defaulting to True.

**Comment by jnoortheen** [comment]
The thing is , now ptk supports `shift+left/right` keys to select the buffer text and `cut/copy` to system clipboard if pyperclip is installed. It will be useful to paste between applications. 

I think, you can get the same behaviour with just setting `$XONSH_COPY_ON_DELETE=True`. (that would also copy to system clipboard and not just ptk's killring.) Perhaps a new setting can be added to control when it gets copied to system clipboard when copy-on-delete is on.
