### ISSUE TITLE
Dont load ~/.xonshrc

### ISSUE THREAD

**Issue by ErickTucto** [xonsh/xonsh#4435]
![Captura de pantalla de 2021-08-25 19-04-36](https://user-images.githubusercontent.com/22831024/130879870-c24dcb9c-1959-4960-87b1-2f91325e2c5a.png)
I have my .xonshrc file created, but it is not recognizing me
## xonfig

<details>

```bash
+------------------+-----------------+
| xonsh            | 0.10.0          |
| Python           | 3.9.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.20          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.10.0          |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on wsl           | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+
```

</details>

## .xonshrc

<details>

```python
from os.path import isfile
# GENERAL SETTINGS
$XONSH_SHOW_TRACEBACK = True
$XONSH_TRACEBACK_LOGFILE = f"{$HOME}/.xonsh/errors.log"

# MI PATH
$PATH.append(f"{$HOME}/.cargo/bin")
$PATH.append('/opt/blender')
$PATH.append('/opt/ngrok')
$PATH.append('/opt/vagrant')
$PATH.append('~/.yarn/bin')
$PATH.append('~/.config/composer/vendor/bin')
$PATH.append('~/.npm-global/bin')
$PATH.append('~/.local/bin')
$PATH.append(f"{$HOME}/Tools/azuredatastudio")

# ENVIRONMENT VARIABLES
$TERM = "xterm-color"
$NVM_DIR=f"{$HOME}/.nvm"
$TITLE = 'Terminal'

# LOAD SOURCES BASH
source-bash $NVM_DIR/nvm.sh

# LOAD XONTRIB PLUGINS
xontrib load add_variable
xontrib load base16_shell

# FUNCTIONS
s = lambda cmd : cmd.strip('\n') if type(cmd) is str else cmd

l = lambda cmd : cmd.split('\n')[:-1] if type(cmd) is str else cmd

# LOAD CUSTOM SETTINGS
if (isfile(f"{$HOME}/.xonsh/personal.xsh")):
    source $HOME/.xonsh/personal.xsh

chprompt profile default


```

</details>

## Expected Behavior
Load my .xonshrc

## Current Behavior
Dont load my .xonshrc

## Steps to Reproduce

```bash
~ $ git clone https://github.com/ErickTucto/dotfiles.git .dotfiles
~ $ cd .dotfiles/xonsh
~/.dotfiles/xonsh $ ./install.xsh
```
Reopen Terminal

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by ErickTucto** [comment]
thanks, is okay

**Comment by RomuloPBenedetti** [comment]
![xonsh](https://user-images.githubusercontent.com/12467382/132961553-57f43eb0-263e-453a-9499-df3262b39561.jpeg)

I'm not so lucky.

**Comment by gforsyth** [comment]
hmm, can you try running outside of `tmux` to confirm?

**Comment by RomuloPBenedetti** [comment]
Thanks for the attention @gforsyth, I've found the problem, I was following `Byobu`'s developer advise in [this answer](https://askubuntu.com/a/296388) that point this configuration:

    set -g default-shell /shell/path
    set -g default-command  /shell/path

Actually it only happens to work for me with `default-command` only, as both at same time happen to launch two shells what apparently leads to some problem, was not a problem around 0.9.x. `default-shell` may work maybe, I've not tried it, prefere `Bash` as login shell, xonsh give me some problems here and there, like icons not showing correctly in `Latte-Dock`.

**Comment by gforsyth** [comment]
Ahh, glad you tracked that down and thanks for following up here with your discovery!  Yeah, seems like some clobbering is happening if both of those are set.
