### ISSUE TITLE
Rotate deploy keys for xonsh docs

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#4473]
Travis has once again leaked a bunch of secrets -- I've taken the step of deleting the compromised deploy key from `xonsh/xonsh-docs` -- I'll try to get a new one set up and configured for doc pushes soon.

This may also be the time to start looking at github actions for doc deployment so we can leave travis behind for good.

**Comment by jnoortheen** [comment]
The PR for [GH actions support](https://github.com/drdoctr/doctr/issues/351) for `doctr` is stalled. We can just use GH Actions directly.  

We can use anyone of the following 
 - https://github.com/JamesIves/github-pages-deploy-action
 - https://github.com/appleboy/gh-pages-action

We should also consider having versioned docs
