### ISSUE TITLE
Prompt displayed on the same line as command output

### ISSUE THREAD

**Issue by ZyX-I** [xonsh/xonsh#448]
Consider the following code:

```
echo -n foo
```

. This will result in

```
foozyx@zyx-desktop ~ $
```

on the next line in place of just

```
zyx@zyx-desktop ~ $
```

. Zsh in this case outputs per cent sign:

![highlighted per cent after foo](http://img-fotki.yandex.ru/get/9746/9151298.6/0_b9316_bb69ddd8_orig.png)

(note: attaching a screenshot to show that this sign is highlighted). (Of course, in zsh this is controlled by some option. I do not see why this should be optional though, but in zsh you can customize not only sign presence, but also how it is highlighted and what text should be there exactly (including running some command and displaying its output).)

Xonsh version 0.2.2.

**Comment by scopatz** [comment]
Thanks for reporting this @ZyX-I.  I think that xonsh's current behaviour is the expected behaviour here.  The `-n` option to `echo` is exactly what this enables.  That said, I wouldn't mind it if there was an environment variable that dictated what to append if the command does not have a trailing newline.  For example, `$APPEND_IF_NO_NEWLINE`.  The default for this should be an empty string.

**Comment by scopatz** [comment]
Pull requests welcome!

**Comment by auscompgeek** [comment]
It's not just zsh that forces the prompt to be printed on a new line. fish does this as well:

![screenshot from 2015-11-04 12-57-03](https://cloud.githubusercontent.com/assets/128854/10927402/96c46a96-82f3-11e5-93f2-09ba1be12c69.png)

(note that the `⏎` is a grey that is not my terminal's default colour)

**Comment by scopatz** [comment]
I think this would be easy to do for anyone who feels up for it.

**Comment by SanketDG** [comment]
I would like to work on this, I am guessing I should define the environment variables in `environ.py` but where would I define how it would behave?

**Comment by laerus** [comment]
a good place would be in base_shell.py maybe in the `default` method

**Comment by scopatz** [comment]
Yeah, I agree with @laerus.  Somewhere in BaseShell. Probably either in default() or postcmd()

**Comment by scopatz** [comment]
Thanks for being willing to take this on @SanketDG!

**Comment by scopatz** [comment]
Any progress on this @SanketDG?

**Comment by scopatz** [comment]
I am trying to close out as many open issues as possible and any help would be greatly appreciated!

**Comment by SanketDG** [comment]
No I haven't been able to work on this, sorry. I will try getting on this as soon as I can.

If this is high prio, then anyone else can feel free to work on this.

**Comment by scopatz** [comment]
Thanks! Clearing this out would be nice.
