### ISSUE TITLE
Vim automatically backgrounds in xonsh and cannot be brought back

### ISSUE THREAD

**Issue by ZyX-I** [xonsh/xonsh#449]
Consider the following script:

    xonsh 2>/dev/null
    vim -u NONE -i NONE -N

. This will output

    *[1] stopped: vim & (PID)

. Trying to use `fg` will output

    *[1] running: vim -u NONE -i NONE -N (PID)
    
    *[1] stopped: vim -u NONE -i NONE -N & (PID)

. Note: `xonsh 2>/dev/null` is `xonsh 2>any-path-that-is-not-a-tty`. You will see the same behaviour if you use [hilite program](http://sourceforge.net/projects/hilite) (which is basically how I found this problem).

Xonsh version is 0.2.2.

**Comment by scopatz** [comment]
Do you have `$XONSH_STORE_STDOUT=True`? Just curious. Also what kind of system are you on?

**Comment by scopatz** [comment]
Thanks for reporting @ZyX-I

**Comment by ZyX-I** [comment]
@scopatz $XONSH_STORE_STDOUT is not set. I am on Gentoo amd64 linux:

    Linux zyx-desktop 4.0.9-gentoo #1 SMP Fri Oct 30 16:18:44 MSK 2015 x86_64 AMD FX(tm)-6200 Six-Core Processor AuthenticAMD GNU/Linux

. If I set `$XONSH_STORE_STDOUT` to true the problem disappears.

**Comment by scopatz** [comment]
>  If I set $XONSH_STORE_STDOUT to true the problem disappears.

That is a first :).  What happens when you run vim without arguments or without `-N`?

**Comment by ZyX-I** [comment]
@scopatz Just the same thing. `vim -u NONE -i NONE -N` was chosen only to show that it is not my configuration that is responsible for such vim behaviour.

By the way, `echo abc | less` shows the same behaviour (note that `less` can also be suspended).

Note 2: setting $XONSH_STORE_STDOUT to True does not affect `bg` behaviour for already launched programs.

**Comment by scopatz** [comment]
Does this same behaviour happen if you start xonsh without the redirection to /dev/null?

**Comment by ZyX-I** [comment]
@scopatz This behaviour was originally observed with `hilite`. If I run `hilite xonsh` or if I start it from zsh where `hilite` is enabled in the zshrc I see the same behaviour. If both streams are connected to the tty everything is fine.

**Comment by ZyX-I** [comment]
Note that `hilite` is used to highlight stderr output in red, and it automatically breaks some programs which use `isatty` on a stderr stream. (Where “breaks” most of time means “program starts thinking it is not in a tty”.) If xonsh can highlight stderr with red on its own it would be much better.

**Comment by scopatz** [comment]
I think xonsh could definitely be made to optionally highlight stderr. Could you open another feature request issue for this please?

As per the isatty issue, I am not sure what we can do that remains general. The reason it seems to work for `$XONSH_STORE_STDOUT`, is that we are purposefully changing the TTY behavior and it happens to not care about the streams being different. However, this only works on Linux. When we don't store stdout, we rely on Python's Popen. This functionality is what seems to care about the TTY behavior. It would be much easier to implement hilite capabilities in xonsh than to mess with reimplementing Popen.

**Comment by adqm** [comment]
I believe this has been fixed with the recent job control overhaul, so I'm going to close this issue.  If this persists, please feel free to reopen.
