### ISSUE TITLE
Strange colouring git push origin master

### ISSUE THREAD

**Issue by singpolyma** [xonsh/xonsh#4490]
## xonfig

<details>

+------------------+--------------------+
| xonsh            | 0.9.25             |
| Python           | 3.7.3              |
| PLY              | 3.11               |
| have readline    | True               |
| prompt toolkit   | 3.0.14             |
| shell type       | prompt_toolkit     |
| pygments         | 2.3.1              |
| on posix         | True               |
| on linux         | True               |
| distro           | debian             |
| on darwin        | False              |
| on windows       | False              |
| on cygwin        | False              |
| on msys2         | False              |
| is superuser     | False              |
| default encoding | utf-8              |
| xonsh encoding   | utf-8              |
| encoding errors  | surrogateescape    |
| on jupyter       | False              |
| jupyter kernel   | None               |
| xontrib 1        | argcomplete        |
| xontrib 2        | back2dir           |
| xontrib 3        | ergopack           |
| xontrib 4        | onepath            |
| xontrib 5        | output_search      |
| xontrib 6        | pipeliner          |
| xontrib 7        | sh                 |
| xontrib 8        | whole_word_jumping |
+------------------+--------------------+

</details>

## Expected Behavior

the word `origin` should not have a colour

## Current Behavior

The or get colour darker grey, the igin turns red.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
This is no longer the case. It is fixed in >=0.11
