### ISSUE TITLE
API docs are all broken on the website

### ISSUE THREAD

**Issue by tmewett** [xonsh/xonsh#4496]
Hi, sorry if this isn't the repo to report this; I saw the docs are kept in-tree and didn't see an active repo for the website.

All the pages under https://xon.sh/api/ have the same contents: they all start with "Amalgamation of xonsh package, made up of the following modules, in order: ..." and then all have a handful of functions and types TokenError, TokenInfo, tokenize, untokenize. It looks like one module has been duplicated over the entire API. Interestingly the subfolder /api/lib doesn't seem to have been affected.

**Comment by anki-code** [comment]
Looks like fixed.
