### ISSUE TITLE
Upgrading to 0.10.1 breaks configs on Arch

### ISSUE THREAD

**Issue by Mikadore** [xonsh/xonsh#4499]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.10.1          |
| Python           | 3.9.7           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.20          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.10.0          |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on wsl           | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior

`~/.xonshrc` is loaded.
## Current Behavior
xonsh >= 0.10 doesn't load ` ~/.xonshrc` . This only happens after rebooting after first installing xonsh. It's not present on xonsh 0.9.27. As far as I can tell, this problem is only present in Arch.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi! I can't repeat this. Could you please check that you run xonsh from the appropriate user and xonshrc file has appropriate access rights.

**Comment by Mikadore** [comment]
Hm, it seems this problem is specific to alacritty (I've had this for a few weeks, I seem to recall that being an issue with xterm too, but it doesn't seem like that anymore). I've reproduced this problem on 3 separate installs on 2 separate machines though

**Comment by Mikadore** [comment]
This problem seems to apply to every terminal emulator (interestingly the ttys work, as does vscode's integrated terminal). However, launching a terminal from within another, which has the xonshrc loaded, e.g. by `--rc`, makes the new terminal load the config correctly. The config has `rwx` and I'm the owner of it (tried without x perms as well).

**Comment by anki-code** [comment]
Hmm... need more info how to repeat this. Could you create a repeatable example like
```
useradd -s /opt/miniconda3/bin/xonsh -m tst
echo 'echo rc' > /home/tst/.xonshrc
sudo su tst
```

**Comment by Mikadore** [comment]
> Same problem here. I think this is related to this issue #4394. Fixed by downloading latest version from main branch.

Thanks you a lot! Installing from git fixed it for me as well.

**Comment by gforsyth** [comment]
Just cut a release so you should be good on Arch installing from pypi or conda-forge (if you wish)

**Comment by Mikadore** [comment]
Awesome!

**Comment by egamby** [comment]
Thanks a lot for the new release!
