### ISSUE TITLE
Depreciation warnings Python 3.10

### ISSUE THREAD

**Issue by gsilvers** [xonsh/xonsh#4513]
## xonfig

default

## Expected Behavior
Upon launching xonsh I would expect no warnings 

## Current Behavior

when launching xonsh installed via pip on python 3.10 I am getting these warnings:

### Traceback (if applicable)

```
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dockerpycreds/utils.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py:882: DeprecationWarning: There is no current event loop
  loop = get_event_loop()
gregsilverstein@gregs-mbp ~ $
```

## Steps to Reproduce
Use pip3.10 / python3.10 to install xonsh 
run xonsh

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
Hi @gsilvers, I am closing it since It is an [upstream issue ](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1440). It has a PR already. I hope it gets released soon.

**Comment by gsilvers** [comment]
Ah couldn't find it thank you!

**Comment by mattmc3** [comment]
Just to close the loop, if you are still getting this warning, make sure you upgrade prompt-toolkit to 3.0.22 or above. As of Nov 2021, Xonsh seems to still start off with 3.0.19.

Check your prompt-toolkit version with: `xpip list`. You can easily update your prompt-toolkit by running the following command:

```
xpip install prompt-toolkit --upgrade
```

**Comment by gsilvers** [comment]
I've run the command and will get back to you if the issue pops up. So far seems good.

**Comment by 19216801-Franz** [comment]
Hi, I just started using xonsh and I'm loving it so far. But sadly I am still getting this issue on prompt-tookit 3.0.38 and python 3.10.9. 
Any suggestions?

**Comment by SonicZentropy** [comment]
Also getting this still, Python's current at 3.11.2 and prompt-toolkit 3.0.38, Windows 11 latest update

**Comment by f0rdprefect** [comment]
Same here

**Comment by CaseyBaileyPDX** [comment]
This finally annoyed me enough I figured out a solution.  It's because someone re-introduced the same bug back to prompt-toolkit in 3.0.37 https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1750

If you force downgrade it back to 3.0.36, the error goes away again!

`pip install --force-reinstall prompt-toolkit==3.0.36`
