### ISSUE TITLE
[Feature request] highlight while typing

### ISSUE THREAD

**Issue by Carreau** [xonsh/xonsh#452]
with prompt toolkit, it should be possible to highlight while typing. 

Fish does it to mark not-existing command before executing:

![screen shot 2015-10-30 at 11 51 50](https://cloud.githubusercontent.com/assets/335567/10855057/c712a4ba-7efc-11e5-86b0-9c6a6212fd2d.png)

**Comment by scopatz** [comment]
I am all for this.  Pull requests welcome.

**Comment by scopatz** [comment]
This has been implemented.
