### ISSUE TITLE
Feat: add f-glob strings

### ISSUE THREAD

**Issue by agoose77** [xonsh/xonsh#4545]
In Xonsh we have augmented string literals with `p`-strings (that return a Path object) and glob strings g`...` (that return a list of results). It would seem that we want glob strings to behave similarly to normal strings, and so there is a case to be made for supporting `f`-strings in this context.

An example:
```xonsh
>>> ls
file-a  file-b
>>> prefix = "file"
>>> echo fg`{prefix}*`
file-a file-b
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mattmc3** [comment]
Weirdly, you can do what you want to already, just not with f-strings, you have to use environment variables:

```shell
>>> touch file-a file-b
>>> $prefix = "file"
>>> g`$prefix*`
['file-a', 'file-b']
```

I'm not saying Xonsh shouldn't let you use Python variables this way, just that there is already some magic replacement going on somewhere.
