### ISSUE TITLE
Hilight unhighlighted stderr output

### ISSUE THREAD

**Issue by ZyX-I** [xonsh/xonsh#455]
In case program mixes stderr with stdout output this visually highlight errors in the stream, making them easier to find and also giving a hint about what will be redirected if redirecting only one of the streams.

**Comment by scopatz** [comment]
This has been implemented with `$XONSH_STDERR_PREFIX` and `$XONSH_STDERR_POSTFIX` envvars: http://xon.sh/envvars.html#xonsh-stderr-prefix
