### ISSUE TITLE
[RFC] Feat: entrypoint-hooks for xontribs

### ISSUE THREAD

**Issue by agoose77** [xonsh/xonsh#4553]
Currently, xontribs are loaded into xonsh with `xontrib load`. In my experience, I only install xontribs that I want to be loaded in my shell.

I propose that we add support for entrypoints, such that a xontrib can make itself known to xonsh, and xonsh can automatically load it at startup. 

The `setup.cfg` for xontribs would require
```ini
[options.entry_points]
xonsh.xontrib = 
   a-cool-xontrib = a_cool_xontrib.name_of_a_callable
```

and the module itself would need a registration method:
```python3
def name_of_a_callable(xsh):
    pass
```

For the user, this would mean that they would no longer need to add `xontrib load a_cool_xontrib` to their RC files.

We would also want a configuration setting that disables this auto-loading, so that users can opt-out if they wish to. Given that this mechanism would require existing xontribs to opt-in, I propose that it become enabled by default.

Related: https://github.com/xonsh/xonsh/issues/4541

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
well I have created this sometime back https://github.com/xonsh/xonsh/issues/4003

**Comment by agoose77** [comment]
Ah, drat! I'll make a comment over at your issue!
