### ISSUE TITLE
Requiring >=python3.8 versions in CI

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4560]
Most of the popular libraries have adapted to support latest three versions of Python. Xonsh can also follow the suit and can drop versions lower than py3.8 ? 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
I'm not opposed to dropping lower versions but we should follow a deprecation schedule. NEP29 is one I've used on other projects and drops 3.7 quite soon.
https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by jnoortheen** [comment]
That looks good. Can we put that as part of the readme? As of version 0.11 we can drop py3.6?

**Comment by gforsyth** [comment]
Sounds good to me. We can release a 0.11.1 that formally drops support
