### ISSUE TITLE
No conda package for v0.11

### ISSUE THREAD

**Issue by auneri** [xonsh/xonsh#4561]
Very happy to see the v0.11 release. Is there are a timeline for generating the conda package? I am surprised a pull request was not automatically generated by bots (at https://github.com/conda-forge/xonsh-feedstock) after the pypi release.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @auneri -- thanks for raising this!  Not sure what happened with the tick bot, but I just updated the recipe manually.  New conda packages should be available in the next 15 minutes or so.
