### ISSUE TITLE
0.11.0 missing downloadable release assets on Github

### ISSUE THREAD

**Issue by jleclanche** [xonsh/xonsh#4572]
I package Xonsh for Arch Linux. [0.11.0](https://github.com/xonsh/xonsh/releases/tag/0.11.0) is missing the usual tarball that would live at this url: https://github.com/xonsh/xonsh/releases/download/0.11.0/xonsh-0.11.0.tar.gz 

Is this omission intentional or just a mistake?

**Comment by jnoortheen** [comment]
I think it is a mistake. Could you check @gforsyth ?

**Comment by gforsyth** [comment]
Yes, it was a mistake.  I've added the missing tarball now.  Sorry, auto-release got borked by the github key rollover.

**Comment by anki-code** [comment]
@gforsyth could you please to add AppImage as well?

**Comment by gforsyth** [comment]
@anki-code -- added

**Comment by anki-code** [comment]
hi @gforsyth! Thanks but the version is `0.10`:
```
cd /tmp
wget https://github.com/xonsh/xonsh/releases/download/0.11.0/xonsh-x86_64.AppImage
chmod +x xonsh-x86_64.AppImage
./xonsh-x86_64.AppImage --version
# xonsh/0.10.0
```
Could you please rebuild. Thanks!

**Comment by gforsyth** [comment]
@anki-code you can try again now

**Comment by anki-code** [comment]
@gforsyth It's still 0.10

**Comment by gforsyth** [comment]
It says 0.11.0 on my end, so I don't know what it's doing. If you can build it, feel free to edit the release

**Comment by anki-code** [comment]
I think it's the cache.

**Comment by anki-code** [comment]
I've uploaded xonsh.AppImage for 0.11
