### ISSUE TITLE
Subprocess output not captured

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#4576]
Yesterday, I read up on history in xonsh and in particular about capturing output of the commands.

I saw in the docs, it indicated that `XONSH_STORE_STDOUT` needs to be configured, but while I was testing in my environment, I found that not to be the case. XONSH_STORE_STDOUT was not set, yet output was being captured.

Incidentally, I also upgraded xonsh around this time. I suspect I was running 0.9.x, but I don't recall exactly. Now I'm running 0.11.0.

And now, when I try to extract the output from a recent command, it doesn't work:

```
~ $ $XONSH_STORE_STDOUT
True
~ $ echo foo
foo
~ $ __xonsh__.history[-1].out is None
True
```

Following the docs, I added the following to a file that gets sourced during .xonshrc (verified in the output above).

What else should I try to restore history stdout support? I can bisect releases if needed, but I'm guessing the maintainers might know what's going on.

I did search the issues and also changelog, but didn't find anything relevant.

## xonfig

<details>

```
~ $ xonfig
+------------------+----------------------------------------+
| xonsh            | 0.11.0                                 |
| Git SHA          | 337cf25a                               |
| Commit Date      | Nov 17 15:37:41 2021                   |
| Python           | 3.9.7                                  |
| PLY              | 3.11                                   |
| have readline    | True                                   |
| prompt toolkit   | 3.0.18                                 |
| shell type       | prompt_toolkit                         |
| history backend  | json                                   |
| pygments         | None                                   |
| on posix         | True                                   |
| on linux         | True                                   |
| distro           | unknown                                |
| on wsl           | False                                  |
| on darwin        | False                                  |
| on windows       | False                                  |
| on cygwin        | False                                  |
| on msys2         | False                                  |
| is superuser     | False                                  |
| default encoding | utf-8                                  |
| xonsh encoding   | utf-8                                  |
| encoding errors  | surrogateescape                        |
| on jupyter       | False                                  |
| jupyter kernel   | None                                   |
| xontrib 1        | vox                                    |
| xontrib 2        | voxapi                                 |
+------------------+----------------------------------------+
```

</details>

## Expected Behavior

Output should have been captured.

## Current Behavior

No output is captured.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
This is related to #4283 and please read about [XONSH_CAPTURE_ALWAYS](https://xon.sh/envvars.html#xonsh-capture-always).

**Comment by anki-code** [comment]
Where we should fix the documentation?

**Comment by jaraco** [comment]
I can submit a PR.

**Comment by jaraco** [comment]
I think there may be two issues. There's still a lot of code referencing XONSH_STORE_STDOUT, but it doesn't seem to have the effect I'd expect.

```
xonsh main $ $XONSH_STORE_STDOUT
False
xonsh main $ $XONSH_CAPTURE_ALWAYS
True
xonsh main $ echo foo
foo
xonsh main $ __xonsh__.history[-1].out is None
False
```

So even though the value is set to false, output is still captured.

Oh, maybe XONSH_STORE_STDOUT is about storing on disk if captured and XONSH_CAPTURE_ALWAYS is about capturing. 

I'm not even sure how I could validate that, as although history is stored across sessions, it's only inspectable as a rich object for the current session, and if I end the session, I can no longer inspect the stdout of the history, at least as far as I can tell from the docs.
