### ISSUE TITLE
[FR] bass like utility for xonsh to use bash functions

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4582]
`bash` has most adaptation amongs shells. It would be good to have a way to use those from xonsh. 

Fish shell has an interesting one [bass](https://github.com/edc/bass) . Can we adopt something from it to `bashisms` or another xontrib ? 

I got there when searching for google-cloud tools https://stackoverflow.com/a/36830765/5048394

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by agoose77** [comment]
From looking at `bass`, isn't this just `source-bash`? It invokes a bash shell and captures the changes using `env` et al.

**Comment by jnoortheen** [comment]
@agoose77 I didn't check the code. I thought it was doing some translation.
