### ISSUE TITLE
Should xonsh interpret python escape sequences inside of single-quoted strings?

### ISSUE THREAD

**Issue by Techcable** [xonsh/xonsh#4587]
## xonfig
      
<details>

```
+------------------+--------------------------+
| xonsh            | 0.11.0                   |
| Python           | 3.9.9                    |
| PLY              | 3.11                     |
| have readline    | True                     |
| prompt toolkit   | 3.0.20                   |
| shell type       | prompt_toolkit           |
| history backend  | sqlite                   |
| pygments         | 2.10.0                   |
| on posix         | True                     |
| on linux         | False                    |
| on darwin        | True                     |
| on windows       | False                    |
| on cygwin        | False                    |
| on msys2         | False                    |
| is superuser     | False                    |
| default encoding | utf-8                    |
| xonsh encoding   | utf-8                    |
| encoding errors  | surrogateescape          |
| on jupyter       | False                    |
| jupyter kernel   | None                     |
| xontrib 1        | back2dir                 |
| xontrib 2        | jedi                     |
| xontrib 3        | readable-traceback       |
| RC file 1        | /Users/nicholas/.xonshrc |
+------------------+--------------------------+
```

</details>

## Expected Behavior
xonsh should pass-through single-quoted strings inside $(...) and shell contexts.

## Current Behavior
1. Execute: `git log --oneline origin/master  | head -11 | rg '^(\w+).*' -r '$1'`
2. Likewise execute `revs = $(git log --oneline origin/master  | head -11 | rg '^(\s+).*' -r '$1').splitlines()`

In both cases this gives `<unknown>:1: DeprecationWarning: invalid escape sequence \w`.
This warning will only show the first time you run it.

This means that xonsh is interpreting `\s+` as a python-style escape. The current (python) behavior is to pass through unknown escape sequences and raise a DeprecationWarning.

Is this intended behavior?

The tradition in shells is to make single-quoted strings (inside '...') completely pass-through and not interpret escapes...

This could result in subtly different (and unexpected) behavior between traditional shells and xonsh.

Furthermore, the `DeprecationWarning` is definitely annoying 😦 

### Alternatives
1. Continue to interpret single-quoted strings as Python strings (in a shell context), however, suppress the `DeprecationWarning` for unknown escapes
    - This means that `\t` and `\n` would be interpreted as their equivalent python escapes, however, `\w` and `\s` would be ignored and passed through to the command
        - Technically, this is the current behavior but gives the annoying `DeprecationWarning`  
    - This risks breaking compatibility if python ever adds new escapes
        - If python ever added a new escape (\p) and users were relying on pass-through in their xonsh scripts, then the behavior would change from pass-through to triggering python's new escape `\p` 
        - Compatibility workaround: Just ignore any new escapes.
          - Downsides: Potentially confusing to new users. Requires documentation. 
2. Switch to more traditional shell behavior: Pass through single-quoted strings as-is, without interpreting escapes (only in a shell context)
  -  If you want to support python-style escapes (at the user's request), consider using a separate 'p' prefix similar to the `r` or `f` prefixes. For example, `p'\n\t'` would be interpreted python-style. The difference from the current behavior is that Python escapes would be off-by-default instead of on-by-default.
  - Switching to this behavior risks breaking compatibility with current scripts.

Also, note that this is only an issue/annoyance in a shell context (top-level commands or in $(....)), in a python context you obviously want to interpret single-quoted strings as python-style escapes.

Let me know if any of this is confusing. This is a complicated issue and I'm kind of just throwing ideas out there 😄

**Comment by gforsyth** [comment]
> This could result in subtly different (and unexpected) behavior between traditional shells and xonsh.

That sounds like us.

The general rule in `xonsh` is that Python always wins when we have conflicts with existing shell behaviors. 

if you want Python/xonsh to ignore the escapes, I suggest using a raw string, instead, e.g.

```
git log --oneline origin/master | head -11 | rg r'^(\w+).*' -r '$1'
```

Also note that `p""` is already a thing and returns a `pathlib.Path` and it's entirely possible that Python will choose to add their own style of p-strings at some point and completely break compatibility, but for now all we can do is hope.

**Comment by gforsyth** [comment]
Ah, the other option is to silence python warnings in your `xonshrc` since, as you noted, the unknown escapes get passed through (and so the underlying subprocess commands execute correctly)
