### ISSUE TITLE
Best methods for remotely executing scripts or python/xonsh functions?

### ISSUE THREAD

**Issue by Shellcat-Zero** [xonsh/xonsh#4589]
Xonsh info:
```python
> which xonsh
/home/myuser/miniconda3/bin/xonsh
```
```python
> xonsh --version
xonsh/0.11.0
```
## xonfig
<details>

```
$PROMPT = '{YELLOW}{env_name}{BOLD_BLUE}{user}@{hostname} {BOLD_GREEN}{cwd} {gitstatus}{RESET}\n> '
$XONSH_COLOR_STYLE = 'solarized-dark'

_xontribs = [
    'coreutils',
    'distributed',
    'mpl',
    'pdb',
    'readable-traceback',
    'whole_word_jumping',
    'z'
]
if _xontribs:
    xontrib load @(_xontribs)

source-zsh --login True "echo loading xonsh foreign shell"
```

</details>

I am pretty new to Xonsh and configuration management is the big thing I would like to accomplish with it. I have found the [distributed xontrib](https://github.com/xonsh/xonsh/blob/main/xontrib/distributed.py), but the [documented example](https://xon.sh/xontribs.html#distributed) currently fails:

```python
with dsubmit('127.0.0.1:8786', rtn='x') as dsub:
    x = $(echo I am elsewhere)

res = dsub.future.result()
print(res)
```
Traceback:
```python
/home/myuser/miniconda3/lib/python3.8/site-packages/distributed/client.py:4267: UserWarning: Executor has been renamed to Client
  warnings.warn("Executor has been renamed to Client")

Traceback (Most recent call last):
1 <xonsh-code> <module> -->
72 /home/myuser/miniconda3/lib/python3.8/site-packages/xontrib/distributed.py dsubmit --> e = Executor(*a, **kw)
4268 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/client.py __init__ --> super().__init__(*args, **kwargs)
763 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/client.py __init__ --> self.start(timeout=timeout)
945 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/client.py start --> sync(self.loop, self._start, **kwargs)
327 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/utils.py sync --> raise exc.with_traceback(tb)
310 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/utils.py f --> result[0] = yield future
762 /home/myuser/miniconda3/lib/python3.8/site-packages/tornado/gen.py run --> value = future.result()
1035 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/client.py _start --> await self._ensure_connected(timeout=timeout)
1095 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/client.py _ensure_connected --> comm = await connect(
308 /home/myuser/miniconda3/lib/python3.8/site-packages/distributed/comm/core.py connect --> raise OSError(
OSError: Timed out trying to connect to tcp://127.0.0.1:8786 after 30 s
```

I also discovered the `+hf` and `+he` options for [xxh](https://github.com/xxh/xxh) but this also fails for me, and it's not clear which option would be correct for executing a local .xsh file on a remote host. For a local file `test.xsh`:
```bash
cat /etc/issue
```
Attempting to run the file remotely with `xxh myuser@192.168.1.100 +s xonsh +hf ./test.xsh` yields:
```python
xonsh: ./test.xsh: No such file or directory.
```
Alternatively with `xxh myuser@192.168.1.100 +s xonsh +he ./test.xsh` yields:
```python
base64: invalid input
```
Otherwise, specifying the Xonsh path with a shebang at the top of a script for a pre-installed Xonsh on the remote host works as expected with ssh, using patterns like those discussed on this [Stackoverflow question](https://stackoverflow.com/questions/305035/how-to-use-ssh-to-run-a-local-shell-script-on-a-remote-machine).

**The Goal:**
What I would like to do, is execute an arbitrary Xonsh script or function against any number of remote hosts. I've tended to use [Python Bundlewrap](https://bundlewrap.org/) as the pythonic alternative to Ansible, but being able to consolidate Python and Bash into the same (Xonsh) scripts offers a lot of advantages, likely negating the need for Bundlewrap/Ansible I think. I'd love to know if or how this is accomplished from Xonsh.

Here's a crude example of the goal, printing hosts and their respective EFI/BIOS mode:
`functions.xsh`:
```python
def efi_or_bios():
    return test -d /sys/firmware/efi && echo efi || echo bios
```
Then from a local Xonsh shell,
```python
from functions import efi_or_bios
hostlist = [192.168.1.100, 192.168.1.101, 192.168.1.102]
for host in hostlist:
    print(host)
    print(xxh myuser@host +s xonsh +hc efi_or_bios())
```
I believe this assumes the remote host has been set up with Xonsh and any python modules, which I could do with a prior bash script or possibly with some nested Xonsh logic that checks for missing modules and installs them, but if there's a more Xonsh-specific way of accomplishing that ([xxh-plugin-prerun-dotfiles](https://github.com/xxh/xxh-plugin-prerun-dotfiles)?) I would like to hear more about it. From the xxh-plugin-prerun-dotfiles plugin it's not clear if there's a way to configure virtualenvs there like with Conda. It would be ideal if the remote host could get the Python modules, virtualenv, etc. directly from the localhost rather than running pip/conda install commands if that's possible, I have used `conda-pack` generally for exporting virtualenvs this way.

Apologies in advance if I've missed something obvious in the documentation.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi! You can do something like:
```python
# Download xonsh AppImage
wget https://github.com/xonsh/xonsh/releases/download/0.11.0/xonsh-x86_64.AppImage
chmod +x xonsh-x86_64.AppImage

# Upload xonsh AppImage and myscript.xsh and run it
hosts = ['192.168.1.100']
for h in hosts:
    echo Run on @(h)
    scp xonsh-x86_64.AppImage @(h):/tmp
    scp myscript.xsh @(h):/tmp
    ssh @(h) '/tmp/xonsh-x86_64.AppImage /tmp/myscript.xsh'
```

**Comment by anki-code** [comment]
Another interesting technique is to use [macro](https://xon.sh/tutorial_macros.html#context-manager-macros):

```python
from xonsh.contexts import Block

class RunInSSH(Block):
    def __init__(self, host):
       self.host = host

    def __exit__(self, *a, **kw):
        xonsh_appimage_url = 'https://github.com/xonsh/xonsh/releases/download/0.11.0/xonsh-x86_64.AppImage'
        ssh @(self.host) -o LogLevel=QUIET -t @(f'cd /tmp && wget -q -nc {xonsh_appimage_url} && chmod +x xonsh-x86_64.AppImage')
        ssh @(self.host) -o LogLevel=QUIET -t @(f'echo -e {repr(self.macro_block)} > /tmp/run.xsh')
        output = $(ssh @(self.host) -o LogLevel=QUIET -t /tmp/xonsh-x86_64.AppImage /tmp/run.xsh)
        print(output)

# And to run commands you can write:
with! RunInSSH(host='127.0.0.1'):
    var = 123
    echo Hello @(var)
```

**Comment by Shellcat-Zero** [comment]
Thank you @anki-code! This is ingenious. Is this going to wget the AppImage for every invocation of `RunInSSH`? If possible, I would like to figure out how to just copy/duplicate or create the environment or selected modules directly from the localhost (with xxh?), and also stream output from the remote host for whatever is being executed there, possibly with some option to watch the stream or just capture it to a buffer to view either periodically or after a return code is provided from the command.

**Comment by Shellcat-Zero** [comment]
Also, has anyone considered creating a Xonsh version of [RPyC](https://rpyc.readthedocs.io/en/latest/index.html) for distributed computing? As far as I can tell, RPyC looks like it's just a Python layering on top of [plumbum](https://plumbum.readthedocs.io/en/latest/). If no one has scoped that out, I will probably look into it as a possible Xontrib, if that sounds appropriate. That seems to me to be the most straightforward solution to distributed computing with Xonsh, but I would be curious to hear what the potential advantages were of the dask-based distributed module. I have historically had lots of problems with dask.

**Comment by anki-code** [comment]
> Is this going to wget the AppImage for every invocation of RunInSSH?

The `-nc` option checks that AppImage exists or not.

> with xxh?

I think it's possible to create xxh-plugin with the environment and then deliver it to the host using xxh.

**Comment by Shellcat-Zero** [comment]
Big thanks again, especially for pointing me to the Discussions page.  Your example fits nearly all of my use cases, though I will probably try to add some per-host buffering of output by wrapping them in objects of some sort. I just also just wanted to note here that the script, as-is, quietly fails (-q) because the 0.11.0 AppImage does not currently exist there, so I had to change it to the 0.10.1 version.

Building off of an [RPyC example](https://rpyc.readthedocs.io/en/latest/tutorial/tut1.html), I would like to try to accomplish something like the following `teleport` operation if you had any suggestions:
```python
>>> from rpyc.utils.zerodeploy import DeployedServer
>>> from plumbum import SshMachine
>>> mach = SshMachine("somehost", user="someuser", keyfile="/path/to/keyfile")
>>> server = DeployedServer(mach)
>>> conn = server.classic_connect()

>>> def square(x):
...    return x**2
>>> fn = conn.teleport(square)
>>> fn(2)
4
```
The `teleport` function here is handling serialization with [Brine/Vinegar](https://rpyc.readthedocs.io/en/latest/api/core_brine.html), so we are just offloading some set of functions to specific hosts where they will handle computation and return the results to us.

**Comment by Shellcat-Zero** [comment]
Just to expand on this, the `teleport` functionality may be replicated in bash with:
```bash
ssh user@host "$(typeset -f myfn); myfn"
```
as illustrated in [this Stackoverflow answer](https://stackoverflow.com/a/22107893/3433625).

**Comment by gforsyth** [comment]
Closing this as answered

**Comment by Shellcat-Zero** [comment]
@gforsyth following my last comment, I have not seen any solution for this, and I am still stuck. Should I open another issue?

**Comment by gforsyth** [comment]
Hey @Shellcat-Zero ! 
If you have a specific bug or a concrete feature request, then definitely open an issue.  Otherwise I think starting a thread over in discussions is better suited.

**Comment by Shellcat-Zero** [comment]
Ok thanks.
