### ISSUE TITLE
Xonsh does not source `~/.xonshrc` on Fedora 35

### ISSUE THREAD

**Issue by FynnFreyer** [xonsh/xonsh#4594]
I installed xonsh via pip on a freshly installed Fedora box, and it does not source my config (in `~/.xonshrc`). This definitely seems to be a Fedora specific issue, because on Ubuntu it just works™.

The same issue arose with the AppImage (also 0.11.0, I think) and the packaged version  (0.10.1)

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.11.0               |
| Git SHA          | 337cf25a             |
| Commit Date      | Nov 17 15:37:41 2021 |
| Python           | 3.10.0               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.23               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.10.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | fedora               |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
| RC file          | []                   |
+------------------+----------------------+
```

</details>

## Expected Behavior

When I start xonsh, I would expect the file `~/.xonshrc` to be sourced correctly.

## Current Behavior

When I start xonsh, the configuration does not get applied.

After my config didn't work, I tried with a very simple example xonshrc
```
$PROMPT = '>>> '
```
but the standard prompt appeared.

Also the XONSHRC (or similar?) env var is not set.

### Traceback (if applicable)

When I start with `env XONSH_DEBUG=1 xonsh` the only message it gives me is `[history.json] Enumerated 1 history files for 0.0047s.`

## Steps to Reproduce

(On Fedora 35)
install xonsh (`sudo pip install xonsh[full]`) (could also be via dnf or AppImage)
fill `~/.xonshrc` with
```
$PROMPT = '>>> '
```
run xonsh
prompt is not `>>> `

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by FynnFreyer** [comment]
PS: if I manually `source ~/.xonshrc` after invoking the shell, the prompt changes (and the other config values get applied as well)

**Comment by anki-code** [comment]
I can't repeat this in Fedora 35 docker:

```python
docker run --rm -it fedora /bin/bash \
    -c "yum install -y pip && pip install xonsh && echo 'echo hello' > ~/.xonshrc && xonsh"
# ...
# hello
# <user>@22eef83f00f3 / #
```

> Also the XONSHRC (or similar?) env var is not set.

This is weird. Hi @chronitis! Could you please take a look. Could it be related to #4408?

**Comment by FynnFreyer** [comment]
I feel so stupid now. It just took a reboot ... I sat on this for (literally) three hours 🤦 
Thanks for doing a sanity check
