### ISSUE TITLE
“Failed building wheel for xonsh” error on Windows

### ISSUE THREAD

**Issue by uranusjr** [xonsh/xonsh#460]
Log below:

~~~
C:\Users\uranusjr\Documents\programming\pepsi\pepsi>pip install xonsh
Collecting xonsh
  Downloading xonsh-0.2.2.tar.gz (158kB)
    100% |████████████████████████████████| 159kB 655kB/s
Collecting ply (from xonsh)
  Downloading ply-3.8.tar.gz (157kB)
    100% |████████████████████████████████| 159kB 873kB/s
Building wheels for collected packages: xonsh, ply
  Running setup.py bdist_wheel for xonsh
  Complete output from command C:\Python\34\python.exe -c "import setuptools;__file__='C:\\Users\\uranusjr\\AppData\\Loc
al\\Temp\\pip-build-j7y2_1iy\\xonsh\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec
'))" bdist_wheel -d C:\Users\uranusjr\AppData\Local\Temp\tmpiyapkapspip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 2829: illegal multibyte sequence

  ----------------------------------------
  Failed building wheel for xonsh
  Running setup.py bdist_wheel for ply
  Stored in directory: C:\Users\uranusjr\AppData\Local\pip\Cache\wheels\d9\34\fe\b9f5d00d8690911944b0c24811ed7f5fb2c5d89
f9c4d6053c7
Successfully built ply
Failed to build xonsh
Installing collected packages: ply, xonsh
  Running setup.py install for xonsh
Successfully installed ply-3.8 xonsh-0.2.2
~~~

I believe this is related to the content in the setup script (having seen this error numerous times myself), but didn’t look deep into this. The setup seems to complete, however, and I do get to import xonsh in Python. <del>The prompt would be in gibberish, but I don’t think the two problems are related. (Currently looking into this one.)</del> Edit: Seems that I missed the Windows Guide on the main page. Scratch the last part.

**Comment by scopatz** [comment]
I think that there are some issues on v0.2.2 with encoding that have been fixed on master.  Could you try that branch please?

**Comment by stonebig** [comment]
Seems to work now, at least when creating the wheel from python3.4.

It would be nice  to have a wheel on pypi.

**Comment by scopatz** [comment]
I'll update at the next release, which should be soon. Pypi sucks at replacing versions.

**Comment by stonebig** [comment]
pypi doesn't lke you overwrite yourself, but you can if you remove it by hand first.

**Comment by scopatz** [comment]
Right, which is why I'll wait. We'll do a v0.2.4 release in the next week or so. We have had some critical bug fixes so I want to get them out there anyway.

**Comment by stonebig** [comment]
do someone of the team realize one basic test on Windows 7 / Python 3.5 + prompt_toolkit ?

**Comment by scopatz** [comment]
> do the team target Windows 7 / Python 3.5 + prompt_toolkit ?

I am not entirely sure what you mean. But I don't think that conemu is required.

**Comment by stonebig** [comment]
If conemu is not mandatory all is ok: I'll redo a clean test with xonsh 0.2.4 wheel + `$SHELL_TYPE = 'prompt_toolkit'`.

**Comment by gforsyth** [comment]
I believe this has been resolved.  Please reopen if it's still an issue.  Thanks!
