### ISSUE TITLE
unable to create virtualenv

### ISSUE THREAD

**Issue by pannet1** [xonsh/xonsh#4602]
## xonfig
# XONSH WEBCONFIG START
$PROMPT = '{BOLD_INTENSE_RED}➜ {CYAN}{cwd_base} {gitstatus}{RESET} '
$XONSH_COLOR_STYLE = 'monokai'
xontrib load abbrevs  argcomplete autovox autoxsh avox coreutils distributed hist_navigator histcpy kitty mpl onepath output_search pdb  prompt_bar prompt_vi_mode readable-traceback  ssh_agent vox vox_tabcomplete z
# XONSH WEBCONFIG END
aliases['vi']="lvim"
aliases['vim']="lvim"
aliases['gvim']="lvim"
aliases['personal']="cd ~/Personal;ls -la"
aliases['scripts']="cd ~/Scripts/client;ls -la"
aliases['hosting']="cd ~/Backup/hosting/home;ls -la"
aliases['html']="cd /var/www/html;ls -l"
aliases['ytv']="clear;echo 'config file is in ~/.config';youtube-viewer"
aliases['fif']="find . -type f -name "
aliases['fid']="find . -type d -name "
aliases['act']="source env/bin/activate;which python"
aliases['deact']="deactivate"
aliases['gromit']="gromit-mpx --key 'w'"
aliases['sshv']="lxterminal; ssh -v carrierc@ecomsense.in"
aliases['sonf']="vi ~/.config/sxhkd/sxhkdrc"
aliases['qonf']="vi ~/.config/qtile/config.py"
aliases['vonf']="nvim ~/.config/lvim/config.lua" 
aliases['wonf']="vi ~/.config/worm/rc"
aliases['xonf']="vi ~/.xonshrc"
aliases['exa']="exa -l@"
aliases['ensite']="sudo $HOME/Scripts/client/_ensite.sh"
aliases['disite']="sudo $HOME/Scripts/client/_disite.sh"
aliases['ydl']='yt-dlp --concurrent-fragments -5 '
<details>

```
$ xonfig

```

</details>

## Expected Behavior
xontrib load vox
load vox and then try to create a virutalenv 

## Current Behavior

<details>
XonshError: xonsh: subprocess mode: command not found: xcontrib
Did you mean the following?
    xontrib:  Alias
</details>

**Comment by jnoortheen** [comment]
The error you have mentioned has a typo. Please check that you are typing `xontrib `
