### ISSUE TITLE
How to get current vim state 

### ISSUE THREAD

**Issue by tristone13th** [xonsh/xonsh#4612]
How to get current vim state in .xsh, I want to customize prompt and cursor style by the state.

**Comment by anki-code** [comment]
Hi! I don't clearly understand what you mean.

**Comment by jnoortheen** [comment]
The VI mode of PTK can be controlled using this variable https://xon.sh/envvars.html#vi-mode . Also you can ask for questions in the [discussions](https://github.com/xonsh/xonsh/discussions) page.
