### ISSUE TITLE
Is there any plan for changing cursor shape automatically?

### ISSUE THREAD

**Issue by tristone13th** [xonsh/xonsh#4615]
Regard to this [cursor shape (e.g. for vim mode) · Issue #192 · prompt-toolkit/python-prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/192).

**Comment by anki-code** [comment]
hi! PR is welcome!

**Comment by jnoortheen** [comment]
This can be added in upstream projects. I don't think we can add it here.
