### ISSUE TITLE
[fish completions] Fails with strange error auto-completing `cp`

### ISSUE THREAD

**Issue by Techcable** [xonsh/xonsh#4652]
## xonfig

<details>

```
+------------------+--------------------------+
| xonsh            | 0.11.0                   |
| Git SHA          | 4af68065                 |
| Commit Date      | Jan 8 20:16:06 2022      |
| Python           | 3.9.10                   |
| PLY              | 3.11                     |
| have readline    | True                     |
| prompt toolkit   | 3.0.23                   |
| shell type       | prompt_toolkit           |
| history backend  | sqlite                   |
| pygments         | 2.11.2                   |
| on posix         | True                     |
| on linux         | False                    |
| on darwin        | True                     |
| on windows       | False                    |
| on cygwin        | False                    |
| on msys2         | False                    |
| is superuser     | False                    |
| default encoding | utf-8                    |
| xonsh encoding   | utf-8                    |
| encoding errors  | surrogateescape          |
| on jupyter       | False                    |
| jupyter kernel   | None                     |
| xontrib 1        | back2dir                 |
| xontrib 2        | fish_completer           |
| xontrib 3        | jedi                     |
| xontrib 4        | readable-traceback       |
| xontrib 5        | term_integration         |
| RC file 1        | /Users/nicholas/.xonshrc |
+------------------+--------------------------+```
```

</details>

xonfig seems to be giving incorrect output, I'm actually using commit 7eceb7f956bb81a2309d1e60ceb2dfcf4ed4efb4 (latest as of this writing)

## Expected Behavior
Fish completions should work seamlessly, without erroring.

They're already a significant improvement over bash-completions :)

## Current Behavior

When trying to autocomplete with partial input `cp ~/Downloads/drill01.zip '~/Documents/Classes/CSC 210/'Or` I get a bizarre error 

> Failed to get fish-completions: Command '['fish', '-c', "complete --no-files cp; complete -C 'cp ~/Downloads/drill01.zip '~/Documents/Classes/CSC 210/'Or'"]' returned non-zero exit status 2.

## Steps to Reproduce
Try the above partial input (NOTE 'CSC 210' has a directory called 'Original Assignments')

I might want to tag @jnoortheen since he's the maintainer of this xontrib :)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
usually the errors from the completers should not be visible. can you check if [this](https://github.com/xonsh/xonsh/pull/4648) solves the issue?

**Comment by Techcable** [comment]
> usually the errors from the completers should not be visible. can you check if [this](https://github.com/xonsh/xonsh/pull/4648) solves the issue?

Yes that PR appears to fix this specific issue 😄 

It also seems to fix a number of other strange bugs and quirks I've encountered with completions. In my quick smoke tests, completions seem much more reliable with that PR

Thank you very much :)

**Comment by jnoortheen** [comment]
Closing as the PR is merged
