### ISSUE TITLE
Very dark blue on black in iTerm is completely unreadable

### ISSUE THREAD

**Issue by taw** [xonsh/xonsh#4656]
So I wanted to give Xonsh a try, but I keep running into a lot of issues.

The first one, completely unreadable color scheme. This dark blue on black should never be used for anything:

![Screenshot 2022-01-25 at 15 55 20](https://user-images.githubusercontent.com/17444/151011630-0a05b561-3757-4a8e-b80c-3d72df3ff4f7.png)

This it iTerm on default settings. I even checked various color schemes (this one is friendly), and all of them use dark blue on black for some things.

I'm sure it violates every possible minimum contrast guideline.

Is there any way for Xonsh to avoid such low contrast combinations?

**Comment by anki-code** [comment]
hi @dyuri! Sensei, could you please propose the workaround of this coloring problem? :)

**Comment by jnoortheen** [comment]
@taw you can experiment with different color presets. It is set using https://xon.sh/envvars.html#xonsh-color-style . You can also customize the particular token/color that doesn't work in your environment.

**Comment by dyuri** [comment]
You can also try to change the colors of your terminal, I think those are the default green (color2) and blue (color4) colors, and are indeed bad choice.

I'm using a gruvbox based theme for my terminal:
```
color0  #282828
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #a89984
color8  #928374
color9  #fb4934
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2
```
![image](https://user-images.githubusercontent.com/126637/151116921-e280dcc2-1b6e-4e3f-acda-62c19297d8f3.png)

**Comment by gforsyth** [comment]
Closing as answered
