### ISSUE TITLE
Issues with gitstatus in prompt

### ISSUE THREAD

**Issue by taw** [xonsh/xonsh#4657]
So I have this prompt as configured by `xonfig web`:

```
$PROMPT = '{BOLD_INTENSE_RED}➜ {CYAN}{cwd_base} {gitstatus}{RESET} '
```

It has two issues.

First, every shell that's not in a git directory has a double space, as it's implemented as "space gitstatus space":

![Screenshot 2022-01-25 at 16 17 55](https://user-images.githubusercontent.com/17444/151015780-849205a3-7b63-4428-988d-7ca06fcf1fe7.png)

This makes me think I accidentally pressed space and wanting to backspace it.

Responsibility for spacing or not spacing should just move to gitstatus, it can't really do proper spacing otherwise.

So a fixed version would need to be something like (gitstatus returning extra initial space if it git directory):

```
$PROMPT = '{BOLD_INTENSE_RED}➜ {CYAN}{cwd_base}{gitstatus}{RESET} '
```

Second issue is the stash count:

![Screenshot 2022-01-25 at 16 19 42](https://user-images.githubusercontent.com/17444/151016145-d2cb5bce-9cef-454f-bada-863a72fe9b1e.png)

While that might be useful to some, I find it just very distracting, and other git prompts for other shells never bother displaying this count, as it's really irrelevant for most people.

I don't think there's any way to disable stash count other than by editing /usr/local/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/prompt/__amalgam__.py (or wherever it's installed). 

For some git info, most people don't bother cleaning up stashes, and `git stash apply` doesn't do this. It's generally better to use `git stash apply` instead of `git stash pop` it case things get messed up and you want to retry later.

Anyway, I'd recommend turning it off by default, and in any case there probably should be some kind of gitstatus configuration, as I'd expect people to want a lot of different things from it.

**Comment by anki-code** [comment]
As alternative you can try [xontrib-prompt-bar](https://github.com/anki-code/xontrib-prompt-bar) or [xontrib-prompt-starship](https://github.com/anki-code/xontrib-prompt-starship).

**Comment by gforsyth** [comment]
Hi @taw !  

1. You might like the behavior of `{branch_color}{curr_branch: {}}{RESET}` over `{gitstatus}`
2. If possible, when you have multiple questions / issues, splitting them out makes it a bit easier to triage the individual bits.

**Comment by gforsyth** [comment]
oh right, also there's a `XONSH_GITSTATUS_FIELDS_HIDDEN` environment variable that you can use to configure which bits get shown -- not sure where the docs are on the field names, but they're up top in xonsh/prompt/gitstatus.py

**Comment by jnoortheen** [comment]
closing this one, as this is answered. Please use Discussions for QA.
