### ISSUE TITLE
Weird stacking auto-complete 

### ISSUE THREAD

**Issue by GanerCodes** [xonsh/xonsh#4668]
It happens a lot and is pretty annoying, anyone get this/know a fix?

https://user-images.githubusercontent.com/34655998/153747557-fc8d07f3-78e4-4606-b8f6-415c26a5503d.mp4

Here are my custom environment variables
```
$DOTGLOB = True
$COMPLETIONS_CONFIRM = False
$COMPLETION_IN_THREAD = True
$COMPLETIONS_BRACKETS = False
$COMPLETIONS_DISPLAY = "single"
$CASE_SENSITIVE_COMPLETIONS = False
$AUTO_SUGGEST_IN_COMPLETIONS = True
$UPDATE_COMPLETIONS_ON_KEYPRESS = True
$COMMANDS_CACHE_SAVE_INTERMEDIATE = True
$XONSH_HISTORY_BACKEND = "sqlite"
$XONSH_HISTORY_FILE = "/home/ganer/.xonsh_history"
$XONSH_CACHE_EVERYTHING = True
$XONSH_CTRL_BKSP_DELETION = True
$UPDATE_PROMPT_ON_KEYPRESS = True
$XONSH_COLOR_STYLE = 'default'
$XONSH_STYLE_OVERRIDES['Token.Literal.Number'] = '#1111ff'
```

edit: also on a another note, typing backshashes before most characters cause a error to appear in the console

**Comment by jnoortheen** [comment]
Xan you set `$XONSH_TRACE_COMPLETIONS` and check where does the completions come from?

**Comment by GanerCodes** [comment]
Got one on camera

https://user-images.githubusercontent.com/34655998/153767136-46a5c6fd-1d61-4062-be6c-ca7d4594ff88.mp4
