### ISSUE TITLE
make promp.env.env_name venv --prompt aware (set in pyvenv.cfg)

### ISSUE THREAD

**Issue by obestwalter** [xonsh/xonsh#4670]
## xonfig

<details>

```
> xonfig
<xonsh-code>:1:0 - xonfig
<xonsh-code>:1:0 + ![xonfig]
+------------------+----------------------+
| xonsh            | 0.11.0               |
| Git SHA          | adfa60ea             |
| Commit Date      | Feb 11 14:53:00 2022 |
| Python           | 3.9.7                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| history backend  | json                 |
| pygments         | 2.11.2               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | coreutils            |
| xontrib 2        | vox                  |
| xontrib 3        | voxapi               |
| RC file 1        | /home/ob/.xonshrc    |
+------------------+----------------------+
```

</details>

## Expected Behavior

When activating a venv via `vox activate` the name should be set to the value of `prompt` key in `pyvenv.cfg` if present (file and key) - see https://docs.python.org/3/library/venv.html.

## Current Behavior

The prompt is always set to name of venv directory independent of prompt settings.

## Steps to Reproduce

```shell
$ python -m venv --prompt "MY SPECIAL PROMPT" .venv
$ cat .venv/pyvenv.cfg | grep prompt
prompt = 'MY SPECIAL PROMPT'
vox activate ./.venv
```

new prompt looks like this:
`[17:58:10] (.venv)  ob@ob1 ~/oss/xonsh dropthedot|✓`

but should look like this:
`[17:58:10] (MY SPECIAL PROMPT)  ob@ob1 ~/oss/xonsh dropthedot|✓`

## Also add `--prompt` to `vox new`?
If this is done, maybe a good idea would be to also add `--prompt` to `vox new` to make this possible on creation (also in the interest of symmetry), but it seems like the common pattern for many xonsh users is to have virtualenvs in `~/.virtualenv` with the venv folder name being the same as the project, therefore automatically having a meaningful prompt, so this does not seem to be an urgently wanted feature for most.

I want to prepare a PR for the "passive" part of the functionality, but could also have a stab at adding `--prompt`  to `vox new` at a later date. My main itch would be to respect `prompt` from already existing venvs first.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
@obestwalter yes it will be helpful to add the --prompt option as well. It is straight forward, since we pass all these to `venv` directly. Only the reading pyvenv.cfg would require more code

**Comment by obestwalter** [comment]
Hey @jnoortheen ok, but I will do this in a separate issue and PR. That way they can be reviewed individually, as they touch quite different areas in the code anyway.

The issue here was not even about vox. The PR addresses the problem at the root, which is that the generation of env_name was not aware of pyvenv.cfg, so this will now work under all circumstances, where VIRTUAL_ENV points to an existing venv with a pyvenv.cfg containing a prompt key that vaguely adheres to the ad-hoc format used by venv.
  
So even the issue name was wrong as this has nothing to do with vox activate.

**Comment by obestwalter** [comment]
I just saw that env.py with all its functions is exposed as an API ... https://xon.sh/api/prompt/env.html :fearful: - looking for usages on github, there is nothing really - the 10 hits are all forks or unrelated. I don't know though if that search can be trusted (https://github.com/search?l=Python&q=%22find_env_name%28%29%22&type=Code).

I restored the functions now to the way they behaved before, except that find_env_name now can find more (a.k.a. prompt).
