### ISSUE TITLE
jsonl and csv based history backends

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4679]
Currently there is sqlite and json based implementation for the backend. There should be csv based one as well. It will be much more lightweight. Also jsonl can be loaded one line at a time, and can be safe to use when Xonsh crashes in the middle (we can append after each prompt)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
JFYI There is also [xontrib-history-encrypt/](https://github.com/anki-code/xontrib-history-encrypt/).

**Comment by anki-code** [comment]
Also JFYI. I suppose the best history backend is [sqlite history backend](https://xon.sh/tutorial_hist.html#sqlite-history-backend) because it allows to manage history by using SQL language in very simple manner. Example - https://github.com/xonsh/xonsh/discussions/4132#discussioncomment-421399

**Comment by jnoortheen** [comment]
Yes but we load all data into memory when the shell starts. We are not leveraging any of its advantages. 

Also when the history is a plain text, we can use dotfile managers to keep track of them (using git) . I use sqlite backend, and export it before saving to git repo. It is manageable but can be better. 

The json backend uses locks (which I want to simplify) and I saw some issues with it when the session crashes. Since it is a default one, we should improve it. Also csv is supported by spreadsheet softwares. 

It is just about adding more options

**Comment by jnoortheen** [comment]
These can be implemented as xontribs if needed.
