### ISSUE TITLE
Cannot `deactivate` virtual environment created by `virtualenv`

### ISSUE THREAD

**Issue by TeddyHuang-00** [xonsh/xonsh#4684]
I can smoothly activate a virtual environment created by `virtualenv` but cannot deactivate it through `deactivate`, like mentioned in the previous issues #108 #2663 

## xonfig

```
# XONSH WIZARD START
source-zsh --login True "echo loading xonsh foreign shell"
# source-bash $(/usr/libexec/path_helper -s)
xontrib load coreutils prompt_ret_code whole_word_jumping
# source-foreign "bash" ["~/.bashrc"] --overwrite-aliases
# XONSH WIZARD END
```

Though I put the rc file here, I don't think the problem has anything to do with this

## Expected Behavior
`deactivate` should be able to deactivate the virtual environment and clean up the $PATH config

## Current Behavior

`deactivate` doesn't work and the $PATH isn't changed

## Steps to Reproduce

![screen recording](https://user-images.githubusercontent.com/64199650/155927926-c916a09c-9bbc-4f23-a492-4a10a10367cb.gif)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Does [xontrib-vox](https://xon.sh/python_virtual_environments.html) solve the issue?

**Comment by TeddyHuang-00** [comment]
> Does [xontrib-vox](https://xon.sh/python_virtual_environments.html) solve the issue?

It works! But I just wonder why we couldn't get it work on `deactivate` itself 😕

**Comment by jnoortheen** [comment]
deactivate is a bash/sh script. We have vox for this purpose only.
