### ISSUE TITLE
$XONSH_TRACEBACK_LOGFILE with '~' crashes xonsh

### ISSUE THREAD

**Issue by dev2718** [xonsh/xonsh#4696]
## Steps to Reproduce

```sh
$XONSH_TRACEBACK_LOGFILE = "~/log"
raise Exception
```

## xonfig

Current master.

## Expected Behavior
Log gets written without errors.

## Current Behavior

Xonsh crashes [here](https://github.com/xonsh/xonsh/blob/8e1a1f3342bc30e9b5c0d58e4713daf8e23295d0/xonsh/tools.py#L976) with `FileNotFoundError: [Errno 2] No such file or directory: '<current path>/~/log'`.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
This looks like `os.path.expanduser` needed. PR is welcome!
