### ISSUE TITLE
How do I copy and paste from the SYSTEM clipboard?

### ISSUE THREAD

**Issue by tahir-hassan** [xonsh/xonsh#4717]
How do I copy and paste from the system clipboard in Windows?  I am using the copy and paste functionality as described in [keyboard_shortcuts](https://xon.sh/keyboard_shortcuts.html).

It only seems to set some internal clipboard that Xonsh knows about and not the system clipboard.

Also can't we make Control-c copy?  In PSReadLine in PowerShell, Control-c is bound to CopyOrCancelLine().  In other words, it either copies text if there is any selection going on, or it cancels the operation.

## xonfig

<details>
<summary>xonfig output</summary>

```
+------------------+-------------------------+
| xonsh            | 0.11.0                  |
| Python           | 3.10.2                  |
| PLY              | 3.11                    |
| have readline    | False                   |
| prompt toolkit   | 3.0.27                  |
| shell type       | prompt_toolkit          |
| history backend  | json                    |
| pygments         | 2.11.2                  |
| on posix         | False                   |
| on linux         | False                   |
| on darwin        | False                   |
| on windows       | True                    |
| on cygwin        | False                   |
| on msys2         | False                   |
| is superuser     | False                   |
| default encoding | utf-8                   |
| xonsh encoding   | utf-8                   |
| encoding errors  | surrogateescape         |
| on jupyter       | False                   |
| jupyter kernel   | None                    |
| xontrib          | []                      |
| RC file 1        | C:\Users\th203/.xonshrc |
+------------------+-------------------------+
```

</details>

**Comment by tahir-hassan** [comment]
I have done a bit of research and found that the line of code [key_bindings](https://xon.sh/_modules/xonsh/ptk_shell/key_bindings.html) is not doing what it is supposed to do:

```python
event.app.clipboard.set_data(data)
```

I am having a look at [prompt_toolkit tutorial](https://xon.sh/tutorial_ptk.html) to see if I can implement a solution myself (though I don't know Python yet).

**Comment by jnoortheen** [comment]
Does your snippet works?

**Comment by tahir-hassan** [comment]
> Does your snippet work?

@jnoortheen yes, but I believe that there should be an easier way.  New users who try to copy and paste, will say "Xonsh does not allow copy and pasting", rather than fixing the problem themselves. 

I think there should be an environment variable for this behaviour.   I would call it `$XONSH_USE_SYSTEM_CLIPBOARD`.  

There are two environment variables that we could model it on:

- [$VI_MODE](https://xon.sh/envvars.html#vi-mode)
- [$XONSH_COPY_ON_DELETE](https://xon.sh/envvars.html#xonsh-copy-on-delete)

I ain't a Python developer, but I could have a look implementing this and providing a pull request?

**Comment by jnoortheen** [comment]
It should be working already when pyperclip is installed. I don't use windows so debugging the issue could be difficult. For starters, can you check that you have installed pyperclip (when poding `pip install xonsh[full]` it will install that automatically) ?

**Comment by tahir-hassan** [comment]
Ah cool is installing `xonsh` through `pip` the recommended way?  I got the impression that installing through conda was the right approach.

Anyhow I will give it a go and get back to you mate.

**Comment by gforsyth** [comment]
Hey @tahir-hassan -- it should be updated now if you want to give it a try

**Comment by tahir-hassan** [comment]
> Hey @tahir-hassan -- it should be updated now if you want to give it a try

@gforsyth is this the main package in conda, as in `conda install xonsh`?

**Comment by gforsyth** [comment]
On conda-forge so `conda install -c conda-forge xonsh`

**Comment by jnoortheen** [comment]
Closing this as the initial question is answered

**Comment by tahir-hassan** [comment]
I have tested Xonsh in a new conda environment using 
```
conda create --channel conda-forge --name xonsh-test-env xonsh
```

And the clipboard functionality works as expected.  Thank you.
