### ISSUE TITLE
bash_completions defaults no longer practical on Apple Silicon Mac

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#4737]
## xonfig

<details>

```
$ xonfig
+------------------+------------------------+
| xonsh            | 0.11.0                 |
| Git SHA          | 337cf25a               |
| Commit Date      | Nov 17 15:37:41 2021   |
| Python           | 3.10.2                 |
| PLY              | 3.11                   |
| have readline    | True                   |
| prompt toolkit   | 3.0.28                 |
| shell type       | prompt_toolkit         |
| history backend  | json                   |
| pygments         | None                   |
| on posix         | True                   |
| on linux         | False                  |
| on darwin        | True                   |
| on windows       | False                  |
| on cygwin        | False                  |
| on msys2         | False                  |
| is superuser     | False                  |
| default encoding | utf-8                  |
| xonsh encoding   | utf-8                  |
| encoding errors  | surrogateescape        |
| on jupyter       | False                  |
| jupyter kernel   | None                   |
| xontrib 1        | vox                    |
| xontrib 2        | voxapi                 |
| RC file 1        | /Users/jaraco/.xonshrc |
+------------------+------------------------+
```

</details>

## Expected Behavior
Using homebrew with bash-completion@2 installed, xonsh should honor bash completions.

## Current Behavior
Bash completions aren't honored.

## Steps to Reproduce
1. Install homebrew on macOS 12.3 or similar with Apple Silicon using default instructions, which installs homebrew to `/opt/homebrew` on this platform.
2. `brew install git bash-completion@2`
3. Observe that git completions are present in bash but not in xonsh.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jaraco** [comment]
I've done some investigation. I read up on #1786, where I and other users had similar issues.

I can observe the following:

```
~ $ $BASH_COMPLETIONS
EnvPath(
['/usr/local/share/bash-completion/bash_completion',
 '/usr/local/etc/bash_completion']
)
~ $ ls /usr/local/share/bash-completion/bash_completion
ls: /usr/local/share/bash-completion/bash_completion: No such file or directory
~ $ ls @$(brew --prefix)/share/bash-completion/bash_completion
/opt/homebrew/share/bash-completion/bash_completion
```

According to [the docs on BASH_COMPLETIONS](https://xon.sh/envvars.html#bash-completions), that environment variable uses sane defaults, but based on [tab completion docs](https://xon.sh/osx.html#tab-completion), those defaults are based on the assumption that homebrew installs to `/usr/local`, which isn't the case for custom installs or for the default install on Apple Silicon.

Using this command, completions start working:

```
~ $ $BASH_COMPLETIONS.append($(brew --prefix).strip() + '/share/bash-completion/bash_completion')
```

Perhaps that behavior should be the default.

Side note: the use of "sane" can in some contexts connote disparity for those with mental illness. Consider using "practical" or "reasonable" instead.

**Comment by gforsyth** [comment]
Hey @jaraco -- thanks for tracking down the discrepancy!

Can you tell me what the output of `platform.machine()` is on a Mac M1?  We might have to add that as a separate platform and set some of the defaults accordingly (I can't imagine that bash completion install locations are the only difference).

I suppose we could also attempt to set it using `brew --prefix` and then fallback to our reasonable defaults if we don't find `brew` installed.

**Comment by gforsyth** [comment]
I opted for the simpler solution, which is adding the M1 default bash completion path to the list of paths to check.  Iterating over the possible locations should be very quick if there's nothing located in the first two.  This is at least a reasonable stop-gap until/unless we add in m1 carveouts.

**Comment by jaraco** [comment]
> Can you tell me what the output of `platform.machine()` is on a Mac M1? 

```
~ $ platform.machine()
'arm64'
```

**Comment by bestlem** [comment]
Isn't this a Homebrew problem not an M1 issue. I don't use Homebrew and bash completions just work the same on my  M1 Monterey as they did on Mojave

On second thoughts why do I have to have the Homebrew paths added to my setup? I assume that has a startup cost. I definitely don't want calls to brew unless I explicitly add them.

I suppose the /usr/local paths are OK even though I don't have anything in them as they are Unix standard.

Perhaps only add Homebrew paths if xonsh is installed via Homebrew

**Comment by gforsyth** [comment]
Hi @bestlem -- it has no startup cost beyond the memory consumed by holding an extra string in a list.  

#4668	was already fixed, I've just marked it as closed.

**Comment by jaraco** [comment]
To answer one question, it’s not enough to honor homebrew-installed xonsh. I install xonsh using pipx but rely on bash completions installed using homebrew.

**Comment by jnoortheen** [comment]
Can this be closed now? the related pr is merged

**Comment by jnoortheen** [comment]
@bestlem we are open to accept PR for their integration. 
On another note, I think it would be better if we don't do that handling of paths ourselves and launch the bash withits rc files loaded. Like we do for fish based completer

**Comment by gforsyth** [comment]
@bestlem PRs welcome
