### ISSUE TITLE
ModuleNotFoundError: No module named 'prompt_toolkit.cursor_shapes'

### ISSUE THREAD

**Issue by pannet1** [xonsh/xonsh#4760]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 22324, in main
    args = premain(argv)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 22264, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 22212, in start_services
    XSH.shell = Shell(execer=execer, **shell_kwargs)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 15234, in __init__
    self.shell = self.construct_shell_cls(
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 15189, in construct_shell_cls
    from xonsh.ptk_shell.shell import PromptToolkitShell as cls
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 20128, in exec_module
    rtn = self.loader.exec_module(module)
  File "/usr/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 10, in <module>
    from prompt_toolkit.cursor_shapes import ModalCursorShapeConfig
ModuleNotFoundError: No module named 'prompt_toolkit.cursor_shapes'
Xonsh encountered an issue during launch
Failback to /bin/sh
```
## xonfig
```
xonfig: command not found



```
$ xonfig
```

</details>

## Expected Behavior
<!--- Tell us what should happen -->

## Current Behavior
<!--- Tell us what happens instead of the expected behavior -->
<!--- If part of your bug report is a traceback, please first enter debug mode before triggering the error
To enter debug mode, set the environment variable `XONSH_DEBUG=1` _before_ starting `xonsh`.
On Linux and OSX, an easy way to to do this is to run `env XONSH_DEBUG=1 xonsh` -->
```
SHELL=/usr/bin/xonsh
WINDOWID=29360143
COLORTERM=truecolor
LC_ADDRESS=en_IN
LC_NAME=en_IN
DESKTOP_SESSION=qtile
LC_MONETARY=en_IN
KITTY_PID=3753
EDITOR=nvim
GTK_MODULES=canberra-gtk-module
XDG_SEAT=seat0
PWD=/home/pannet1/Programs/py
LOGNAME=pannet1
XDG_SESSION_DESKTOP=qtile
QT_QPA_PLATFORMTHEME=qt5ct
XDG_SESSION_TYPE=x11
SYSTEMD_EXEC_PID=991
XAUTHORITY=/run/user/1000/gdm/Xauthority
QT_STYLE_OVERRIDE=kvantum
WINDOWPATH=2
MOTD_SHOWN=pam
GDM_LANG=en_US.utf8
HOME=/home/pannet1
USERNAME=pannet1
LC_PAPER=en_IN
LANG=en_US.utf8
KITTY_WINDOW_ID=1
XDG_SESSION_CLASS=user
TERMINFO=/usr/lib/kitty/terminfo
TERM=xterm-kitty
LC_IDENTIFICATION=en_IN
USER=pannet1
DISPLAY=:0
SHLVL=1
LC_TELEPHONE=en_IN
LC_MEASUREMENT=en_IN
XDG_VTNR=2
XDG_SESSION_ID=3
XDG_RUNTIME_DIR=/run/user/1000
KITTY_LISTEN_ON=unix:/tmp/kitty-3753
LC_TIME=en_IN
GTK3_MODULES=xapp-gtk3-module
BROWSER=firefox
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/pannet1
GDMSESSION=qtile
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/pannet1
KITTY_INSTALLATION_DIR=/usr/lib/kitty
LC_NUMERIC=en_IN
_=/usr/bin/env
XONSH_DEBUG=1
```
I am on EOS a derivative of Arch Linux. Got this issue after i updated Xonsh.

**Comment by jnoortheen** [comment]
Please install 0.12.1 it has a fix

**Comment by pannet1** [comment]
now using xonsh-git version and the problem got resolved. However, xontrib prompt_bar threw me into a error loop and hence not getting the prompt. 
unable to break the loop and the issues is same with terminals `alacritty` and `lxterminal`. finally removed `prompt_toolbar` from .xonshrc and the issue is resolved.
