### ISSUE TITLE
/etc/xonshrc not loading on 12.1?

### ISSUE THREAD

**Issue by raddessi** [xonsh/xonsh#4761]
## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.12.1               |
| Git SHA          | cd334e44             |
| Commit Date      | Apr 15 13:10:59 2022 |
| Python           | 3.8.10               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.28               |
| shell type       | prompt_toolkit       |
| history backend  | sqlite               |
| pygments         | 2.10.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | fedora               |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| xontrib          | []                   |
| RC file          | []                   |
+------------------+----------------------+

```

</details>

## Expected Behavior

The file should be sourced on startup

## Current Behavior

The file was not sourced like it was in 11.x

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
Now the default has been changed slightly to support directory loading as well. https://xon.sh/envvars.html#xonshrc

So you need to move the file to `/etc/xonsh/xonshrc` or update the $XONSHRC

**Comment by raddessi** [comment]
Oh perfect! I see, thank you.

**Comment by SamLukeYes** [comment]
> Now the default has been changed slightly to support directory loading as well. https://xon.sh/envvars.html#xonshrc
> 
> So you need to move the file to `/etc/xonsh/xonshrc` or update the $XONSHRC

According to https://github.com/NixOS/nixpkgs/pull/204252#issuecomment-1336156734, there are still some parts of the document suggesting the use of `/etc/xonshrc`. It seems the document needs to be updated.
