### ISSUE TITLE
xontribs_meta -> awesome-xonsh repo

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4769]
This is to suggest creating a separate repo for xontribs and remove `xontrib_meta.py` from xonsh. 
As of now new plugins need to create a PR for registering them and users will not be aware of it until a new release. Currently there is no provision to categorize the extensions making it hard to go through. 

If we have a separate repo like `awesome-xonsh` under `xonsh` organization we can the plugins more discoverable. The `xonfig web` can fetch the data using urllib3 if requested. 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
This is a great idea @jnoortheen -- I'm totally on board

**Comment by anki-code** [comment]
Yeah, I started using and recommending https://github.com/topics/xontrib to solve the same issue.

**Comment by jnoortheen** [comment]
> Yeah, I started using and recommending https://github.com/topics/xontrib to solve the same issue.

Yes that is good for repos maintained at github. It will be better to have this page curated 
<img width="576" alt="image" src="https://user-images.githubusercontent.com/6702219/165101359-b81978f0-5f37-4fcd-b41f-203f8172f02b.png">


I have created this repo https://github.com/xonsh/awesome-xontribs . Now we need to update the docs
