### ISSUE TITLE
Inherit completions

### ISSUE THREAD

**Issue by mo8it** [xonsh/xonsh#4775]
In fish, I have this function:
```
function ssh -w ssh
    echo "SSH with kitty"
    kitty +kitten ssh $argv
end
```

From `function --help` in fish:
```
-w WRAPPED_COMMAND or --wraps WRAPPED_COMMAND
       Inherit completions from the given WRAPPED_COMMAND. See the documentation for complete for more information.
```

If I tpye `ssh` in fish and klick `TAB`, I get the completions for `ssh` and NOT `kitty`. Is there a way to do so in Xonsh, too? If not, I would like to friendly request this feature.

Thanks for the awesome shell!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Mo8it** [comment]
Thanks for your tips! I did not try it out since I did go back to fish, to be honest. But this is a workaround. A direct support as a feature would be awesome for others who could need it.
