### ISSUE TITLE
Feature Proposal: special "$?" variable for last exit code

### ISSUE THREAD

**Issue by dev2718** [xonsh/xonsh#4794]
Currently, obtaining the last exit code requires something like
```
__xonsh__.history[-1].rtn
```
which is long to type and requires knowledge about a few xonsh constructs.

I propose that I implement a special read only "?" environment variable such that "$?" can be used to obtain the last exit code, as it is possible among bash, sh, ...

What do you think about this?

**Comment by dev2718** [comment]
I have no issue touching the parser (I did that plenty when implementing the match keyword). Also this addition should be minor. Thanks for pointing me to `@events.on_postcommand`!

Additionally, I think this would be a good opportunity to add a new prompt customisation option like `last_return_status` or similar that expands to "" for 0 and "[<code>]" for codes != 0.
Maybe the default prompt could be updated to use this. My inspiration here is the fish shell which does this really nicely by default.

**Comment by yaxollum** [comment]
@dev2718 a simple way to get the last return code is `_.rtn`
For example:
```
$ rm /dev/null
rm: cannot remove '/dev/null': Permission denied
$ _.rtn
1
```

**Comment by dev2718** [comment]
> @dev2718 a simple way to get the last return code is `_.rtn` For example:
> 
> ```
> $ rm /dev/null
> rm: cannot remove '/dev/null': Permission denied
> $ _.rtn
> 1
> ```

Thanks, this is definitely shorter! But it does not work non-interactively, nor in $PROMPT. Also, it does not capitalize on "$?" being well-known.

**Comment by gforsyth** [comment]
Closing this out as partially implemented
