### ISSUE TITLE
Fix wheel release process

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#4801]
We subclass various `setuptools` build steps to add in parser and lexer generation steps -- if we want to release wheels, we need to do the same for `bdist_wheel`.
I took an initial stab at this and it just didn't work, not sure why. 

For now, I've removed wheels from releases because the `sdist`s at least work correctly.

**Comment by gforsyth** [comment]
ugh -- ok, so the wheel files will need to be built on each version of python we support so that the proper parser table gets generated.

**Comment by gforsyth** [comment]
on a positive note, we don't need to subclass `bdist_wheel` -- the parser tables gets generated using the current setup, we just need to make sure it's the right one.

**Comment by jnoortheen** [comment]
it is not possible, building for each major python versions alone. I think it is better to update the parser like [here ](https://github.com/psf/black/blob/7f033136ac5e0e5bf6cf322dd60b4a92050eedc4/src/blib2to3/pygram.py#L199)
