### ISSUE TITLE
xonfig web doesn't display xontrib descriptions properly

### ISSUE THREAD

**Issue by jlane67** [xonsh/xonsh#4839]
Go to `xonfig web` and click on the Xontribs tab.  All the Xontrib descriptions are the same as the first one.

<img width="983" alt="Screen Shot 2022-06-14 at 11 15 00 AM" src="https://user-images.githubusercontent.com/57652484/173660528-0b4794ee-77ef-4e66-8a26-329169bff9d5.png">

**Comment by yaxollum** [comment]
This appears to have been introduced by #4790

**Comment by gforsyth** [comment]
cc @jnoortheen

**Comment by gforsyth** [comment]
Thanks for reporting this @jlane67 !

**Comment by jnoortheen** [comment]
I will check it
