### ISSUE TITLE
CalledProcessError error

### ISSUE THREAD

**Issue by sbillinge** [xonsh/xonsh#4844]
In v 0.12 a change was made in xonsh so calls to xonsh.subprocess.CalledProcessError failed with exit status 1 when they worked before.  We figured out that we could override this behavior by importing CalledProcessError from the standard library and then raising CalledProcessError instead of subprocess.CalledProcessError.  All good.  But we are now getting this same error from a function call within xonsh itself, `_raise_subproc_error` in `xonsh.proc.pipelines`.

I could put in a PR that modifies that method with the same fix we are using locally, but I am nervous that our fix is just a workaround and that you would recommend handling this situation differently.  Any advice would be appreciated

## xonfig

<details>

```
$ xonfig
```

</details>

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
@sbillinge Could you please give a simple, reproducible example of the issue that you're experiencing?

**Comment by sbillinge** [comment]
OK, I think it is working fine and we can close this issue.  I just got confused and didn't read the error message well enough.
```
from xonsh.lib import subprocess
raise subprocess.CalledProcessError(1, "bad command")
```
resulted in 
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
subprocess.CalledProcessError: Command 'bad command' returned non-zero exit status 1.
```
which is the correct behavior.
