### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by arkhan** [xonsh/xonsh#4848]
Running python3 setup.py build does not generate executables
![image](https://user-images.githubusercontent.com/3141865/175081841-c0e3aec4-8522-4964-bc6e-d8d49a924e6f.png)

**Comment by gforsyth** [comment]
To build an installable tarball or wheel, you should install `build` and upgrade `setuptools`.  Then you can run `python -m build . --wheel` to generate a `.whl`, or `python -m build . --sdist` to create a `.tar.gz` source distribution

**Comment by jnoortheen** [comment]
Closing it with reference to #4807 . Please see the https://xon.sh/devguide.html for up-to-date information.

**Comment by jnoortheen** [comment]
I see that multiple issues getting reported regarding installing from. I will pin this issue to help such situations.
