### ISSUE TITLE
Git can't use Editor Commands with Arguments in xonsh

### ISSUE THREAD

**Issue by Eisfunke** [xonsh/xonsh#4849]
Git commands that open an editor fail in xonsh if the configured editor command has arguments.

## xonfig

<details>

```
+------------------+------------------------------------+
| xonsh            | 0.12.5                             |
| Python           | 3.10.5                             |
| PLY              | 3.11                               |
| have readline    | True                               |
| prompt toolkit   | 3.0.29                             |
| shell type       | prompt_toolkit                     |
| history backend  | sqlite                             |
| pygments         | 2.12.0                             |
| on posix         | True                               |
| on linux         | True                               |
| distro           | arch                               |
| on wsl           | False                              |
| on darwin        | False                              |
| on windows       | False                              |
| on cygwin        | False                              |
| on msys2         | False                              |
| is superuser     | False                              |
| default encoding | utf-8                              |
| xonsh encoding   | utf-8                              |
| encoding errors  | surrogateescape                    |
| xontrib 1        | kitty                              |
| RC file 1        | /home/nicolas/.config/xonsh/rc.xsh |
+------------------+------------------------------------+
```

</details>

## Expected Behavior

When I run a Git command like `git -c core.editor="nano -0" commit --amend`, or any other Git command that opens an editor with an editor with an argument configured, inside a Git repo it will open the desired editor.

## Current Behavior

I get this error with exit code 1:

```
hint: Waiting for your editor to close the file... "nano -0": line 1: nano -E: command not found
error: There was a problem with the editor '"nano -0"'.
Please supply the message using either -m or -F option.
```

The error message seems to me like xonsh isn't properly parsing the command and trying to call an executable named "nano -E".

This could also be a bug in Git, but the command works flawlessly in bash, so it at least has *something* to do with xonsh.

Editor commands with no arguments work fine, e.g. `git -c core.editor="nano" commit --amend` or `git -c core.editor="/usr/bin/nano" commit --amend`.

`xonsh -c "nano -0"` also works fine, so I'm not really sure what Git actually does with the editor command. `XONSH_DEBUG=1` doesn't give anything concerning what Git is actually calling xonsh with.

Interestingly, `$VISUAL="/usr/bin/nano -0" git commit --amend` also works fine — so there's something specific that Git does with the editor command from its configuration.

Note: I noticed this problem while using VSCode (VSCodium, to be precise) with the GitLens plugin when I tried to start an interactive rebase. GitLens then calls `git -c sequence.editor="/usr/bin/codium --wait --reuse-window" rebase --interactive COMMITHASH` which fails just like the command I used above.

## Steps to Reproduce

`git -c core.editor="nano -0" commit --amend` inside any Git repo (have in mind that `git commit --amend` will change your last commit if you don't clear the opened file, so remember to fix that after trying around or clone a throwaway repo for testing)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
@Eisfunke I think
```
git -c "core.editor=nano -0" commit --amend
```
is what you are looking for (quote the entire argument instead of only the part after the equals sign).

I made a simple test program that prints the actual CLI arguments that a program receives from the shell:

```python
import sys

for i,arg in enumerate(sys.argv):
    print(f"ARG {i}: {arg}")
```

You can save this as a file called `test.py`.
## Using xonsh
```
 $ python test.py core.editor="nano -0"
ARG 0: test.py
ARG 1: core.editor="nano -0"
 $ python test.py "core.editor=nano -0"
ARG 0: test.py
ARG 1: core.editor=nano -0
```
## Using bash
```
bash-5.1$ python test.py core.editor="nano -0"
ARG 0: test.py
ARG 1: core.editor=nano -0
bash-5.1$ python test.py "core.editor=nano -0"
ARG 0: test.py
ARG 1: core.editor=nano -0
```
As you can see from the above tests, xonsh handles quotes around only the part after the `=` sign vs around the whole argument differently, whereas bash handles them the same way. The `git` option that you're using expects the argument to be `core.editor=nano -0` (which is what xonsh supplies if you quote the entire argument)

**Comment by Eisfunke** [comment]
I see, thank you! With the entire argument quoted it works indeed.

Knowing that the quote positioning was the problem, not trying to call a command with an argument, I found this part of the manual: https://xon.sh/tutorial_subproc_strings.html#the-quotes-stay

So this seems to be intended behavior (and the arguments on the page do make sense) and not a bug, so I'm closing this.

I guess I'll open an issue with GitLens then and hope they'll consider quoting the entire argument so it works on xonsh too...

Thanks for the help again!
