### ISSUE TITLE
Update setuptools build dependency to v62

### ISSUE THREAD

**Issue by PythonCoderAS** [xonsh/xonsh#4850]
## xonfig

<details>

```
$ xonfig
```

</details>

## Expected Behavior

Setuptools needs to be v62+ in order to function as expected. I am not sure the exact minor version number that is needed, but setuptools v61 does not work while latest v62 does.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

1. Try to install xonsh with setuptools <61

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
version with `>=61` is enough and it is already defined in master. pip should install the build time dependency in an isolated environment. For example, 

```sh

$ docker run --rm -ti python:3-slim bash
$ apt update && apt install git
$ pip install git+https://github.com/xonsh/xonsh.git
# this will install xonsh correctly, but still has an older setuptools
$ pip list
Package    Version
---------- -------
pip        22.0.4
setuptools 58.1.0
wheel      0.37.1
xonsh      0.12.6
```

So if pip install is not working, please report it to the pip repo or try using its latest version.

**Comment by PythonCoderAS** [comment]
I am unable to replicate using the `ubuntu` package. For some reason using the `python:3-slim` package works, but not if I use the ubuntu package as such:

```bash
$ docker run --rm -ti ubuntu bash
$ apt update
$ apt install python3 python3-pip git
$ pip list
Package    Version
---------- -------
pip        22.0.2
setuptools 59.6.0
wheel      0.37.1
$ pip install git+https://github.com/xonsh/xonsh.git
Collecting git+https://github.com/xonsh/xonsh.git
  Cloning https://github.com/xonsh/xonsh.git to /tmp/pip-req-build-xtbsvuet
  Running command git clone --filter=blob:none --quiet https://github.com/xonsh/xonsh.git /tmp/pip-req-build-xtbsvuet
  Resolved https://github.com/xonsh/xonsh.git to commit 5401a246c6224944f2f05a3c8a9ce8fa49b1e396
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py310-none-any.whl size=3724 sha256=b21ec49bf1af7a54234ac79c010a8e444857d1af6e0b6383ec9e21addf7cfff9
  Stored in directory: /tmp/pip-ephem-wheel-cache-hehpcs6a/wheels/9e/59/cf/a377b8647d98064e0df62b7e9379881c3ef92fbac9245103aa
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

**Comment by jnoortheen** [comment]
Yes I have mentioned it in the other comment. It seems to be a quirk with how pip is installed. It is better be reported to pip or ubuntu package maintainers.
