### ISSUE TITLE
Moving the xonsh/xontrib/* to the repositories

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4861]
Hi @jnoortheen!

Because you started to move parts of xonsh to xontribs (thanks!) what do you think about moving the default xontribs (bashisms, coreutils, etc) to the repositories?

I'm favor of this because it will rid us to update xonsh to update default xontribs. For example we have bad case in #4853 and to release this xontrib fix we need to release xonsh.

Also I'm for packing to the xontrib the sqlite history backend as already packed [xontrib-history-encrypt](https://github.com/anki-code/xontrib-history-encrypt). Probably xonsh/xompletions also should be in the distinct repo as xontrib. Finally it will be cool to add the links to the docs and to the lists of xontribs into [xonsh/xontrib/README](https://github.com/xonsh/xonsh/blob/main/xontrib/README).

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
The moved xontribs were dependent on external packages. That is also true for ptk-shell. Currently we do some version compatibility check, which I don't think not needed with external xontrib. This is not the case for other core xontribs. Moving a fairly complex xontrib might help in testing and maintenance. But small xontribs fairly see any updates.
