### ISSUE TITLE
Compare the speed of xonsh between python <=3.10 and faster python 3.11

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4866]
https://docs.python.org/3.11/whatsnew/3.11.html#summary-release-highlights

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
I have this https://github.com/jnoortheen/xonsh-benchmarks but hasn't tested it with Python 3.11 yet
