### ISSUE TITLE
xon.sh doc theme

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4867]
The changes to the theme settings are not reflected in https://xon.sh/tutorial_macros.html
<img width="726" alt="image" src="https://user-images.githubusercontent.com/6702219/177516238-8f1d3921-3b73-4514-9905-e72f7da61d97.png">

But the dev version has the theme running,
https://xon.sh/dev/tutorial_macros.html

<img width="801" alt="image" src="https://user-images.githubusercontent.com/6702219/177516070-ad1a51e1-1031-47e0-9649-ed0eb67c0845.png">

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by melund** [comment]
@jnoortheen Is this the furo theme? It looks nice and clean. The old cloud theme is abandoned so it is good to move to something new. 

We have a lot of things in the side bar, so I was thinking  that we could consider the pydata theme also? It would allow us to group the sidebar into a few major categories which would then be shown in the header. 
https://pydata-sphinx-theme.readthedocs.io/en/stable/ 

Maybe it is not as clean as furo, but we could also just structure he side bar a little to give more structure. I have some time again for side-projects so I could do this.

**Comment by jnoortheen** [comment]
@melund yes it is the furo theme. Some of the other popular projects have also moved to it recently. I just checked the pydata theme, it looks good. On mobile furo looks much clean though. It would help to have #4779 . Also linking the cause https://github.com/xonsh/xonsh/issues/4097

@anki-code gforsyth has added https://github.com/xonsh/xonsh/pull/4689 sometime back

**Comment by jnoortheen** [comment]
@melund I just checked the desktop version, it looks nice having the top level sections. Can we have that in furo as well?

**Comment by jnoortheen** [comment]
closing this as the https://xon.sh/tutorial_macros.html is up to date now. But some outdated pages are still out there like mentioned in #4097
