### ISSUE TITLE
Don't recommend or enable use of 'sudo pip'

### ISSUE THREAD

**Issue by rpdelaney** [xonsh/xonsh#4878]
Related to #4369.

xpip is a built-in alias to `sudo pip`:

```console
$ which xpip
sudo /usr/bin/python -m pip
```

This is a severe security and privilege escalation hazard: installing untrusted, unsigned packages from unknown third parties allows them to execute arbitrary code as root. Consider the risks from:

* Typosquatting, 
* Unknown vulnerabilities in the dependencies of modules installed with xpip (aka "supply chain attacks"), 
* Disruption to the host OS by writing files that the system package manager expects to control exclusively, 
* Intentional malicious code in the modules, which are not vetted by anyone.

For example, these topics are explored in Chris Warrick's [blog on python env management](https://chriswarrick.com/blog/2017/07/03/setting-up-a-python-development-environment/#installing-packages).

Instead, consider this:

```
$ pip3 install --user
```

Documentation should be updated if necessary to remove recommending use of `sudo pip` anywhere.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
To be clear, we don't document (god, I hope) the usage of `sudo pip` anywhere.  There are some heuristics that add a `sudo` which should be changed.

Note that this is system dependent, for instance, I don't use system python (for anything), so

```xonsh
$ which xpip
/home/gil/mambaforge/bin/python -m pip
```

**Comment by rpdelaney** [comment]
Beware that `--user` is an argument to the `install` command. I don't know if this would break `xpip list` etc or not?
