### ISSUE TITLE
bug: no error message in cd when $THREAD_SUBPROCS is False

### ISSUE THREAD

**Issue by TimotheeMathieu** [xonsh/xonsh#4882]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.13.0               |
| Python           | 3.10.5               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.30               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.12.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| xontrib 1        | sh                   |
| xontrib 2        | cd                   |
| xontrib 3        | z                    |
| xontrib 4        | bashisms             |
| xontrib 5        | whole_word_jumping   |
| xontrib 6        | voxapi               |
| xontrib 7        | vox                  |
| RC file 1        | /home/user/.xonshrc |
+------------------+----------------------+
```
</details>

## Expected Behavior

When I use `cd a_nonexistent_directory`, I expect the error message `cd: no such file or directory: a_nonexistent_directory`

## Current Behavior

I don't get any error message.  The return code is 1 but there is no message.
```
~ @ > cd a_non_existant_directory
~ [1] @ >
```
When I remove the load bashism in xonshrc and restart, I get back the expected behavior.
### Traceback (if applicable)

<details>

```
> cd a_nonexistent_directory
--- before precommand event
+++ after precommand event
@@ -1 +1 @@
-cd a_nonexistent_directory
+cd! a_nonexistent_directory
<stdin>:1:2:28 - cd! a_nonexistent_directory
<stdin>:1:2:28 + ![cd! a_nonexistent_directory]
```
</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by TimotheeMathieu** [comment]
After further investigation it seems that it is not due to bashisms at all sorry. 
I removed and readded things in my xonshrc and found out that it was due to the way I started X in xonshrc (linked possibly to https://github.com/xonsh/xonsh/issues/1156).

I don't know why but at some point, removing bashism also solved the issue but this must be due to some weird combination I guess.

Anyway, before, I started X with 
```
 bash -c "[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx"
```
but this seems to alter something and as an effect, the cp error do not show (for whateve reason). Hence, for now I start X manually and it works.

**Comment by gforsyth** [comment]
What is `xontrib load cd` doing?

**Comment by TimotheeMathieu** [comment]
https://xon.sh/xontribs.html#cd

**Comment by gforsyth** [comment]
Does the error persist if you don't load that `xontrib`?

**Comment by TimotheeMathieu** [comment]
Yes, the error is still there.

**Comment by gforsyth** [comment]
What about if you start `xonsh` with the `--no-rc` flag?

**Comment by TimotheeMathieu** [comment]
Yes, with `--no-rc` it works.
