### ISSUE TITLE
`history | grep foo` hangs on Windows

### ISSUE THREAD

**Issue by Awpteamoose** [xonsh/xonsh#4884]
`history | grep foo` outputs matches and then hangs on Windows, regardless of whether there actually were matches or not. I'm using `wt.exe` for terminal, `xonsh --no-rc` and GNU grep for Windows (in PATH). Other things like `cat foo | grep bar` work fine.

## xonfig
<details>

```
+------------------+-----------------+
| xonsh            | 0.13.0          |
| Python           | 3.10.5          |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | 3.0.30          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.12.0          |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib          | []              |
| RC file          | []              |
+------------------+-----------------+
```
</details>

## Expected Behavior
Outputs history lines matching pattern and returns me to the shell.

## Current Behavior
Outputs history lines matching pattern and hangs.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Qyriad** [comment]
Here's a more generic reproducible case:
```sh
$ any_xonsh_builtin | python -c "import sys\nwhile sys.stdin.read():\n    print()"
```

Interestingly, introducing a `sys.stdout.flush()` after the `print()` immediately fixes this, but passing `-u` to Python does not.
