### ISSUE TITLE
Change HOME directory on Windows?

### ISSUE THREAD

**Issue by MikeTheGreat** [xonsh/xonsh#4885]
I'm running xonsh on Windows 11 (in Windows Terminal) and I'd like my .xonshrc file to be stored somewhere other than `C:\Users\<MyUserName>`  I've got the environment variable HOME set but xonsh doesn't seem to be using it.  I tried setting `XONSH_CONFIG_DIR` but the xonsh shell doesn't seem to read that from the OS.

I know that bash and zsh will honor HOME on Windows, and I know that xonsh is not bash/zsh :)

Is it possible to change the home dir on Windows so that I can keep all my config files where I want them, not where Windows would like me to store them?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
Hi @MikeTheGreat ! You should be able to simply set the [`XONSHRC` environment variable](https://xon.sh/envvars.html?highlight=environment#xonshrc) to the path to your xonshrc file (e.g. `C:/Users/YourUserName/customdir/xonshrc`).

**Comment by MikeTheGreat** [comment]
This works!  Thank you very much and sorry for not reading the docs closer!
