### ISSUE TITLE
Cwd Cached in PROMPT when using SHELL_TYPE readline

### ISSUE THREAD

**Issue by marky1991** [xonsh/xonsh#4887]
The {cwd} format key is cached in version 0.13.0-1. The following prompt:

"{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{RESET} {BOLD_BLUE}{prompt_end}{RESET}"

renders the same working directory forever, despite calls to cd. Example (starting xonsh in my home directory):

mark@localhost ~ $ cd /tmp/
mark@localhost ~ $ pwd
/tmp 
mark@localhost ~ $

In xonsh-0.11.0-3 : 
mark@localhost ~ $ cd /tmp/
mark@localhost /tmp $ pwd
/tmp
mark@localhost /tmp $

## xonfig
```
+------------------+---------------------+
| xonsh            | 0.13.0              |
| Python           | 3.10.5              |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | None                |
| shell type       | readline            |
| history backend  | json                |
| pygments         | 2.12.0              |
| on posix         | True                |
| on linux         | True                |
| distro           | artix               |
| on wsl           | False               |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| xontrib          | []                  |
| RC file 1        | /home/mark/.xonshrc |
+------------------+---------------------+
```

## Expected Behavior
{cwd} should never be cached or at least the cache should be cleared after each cd call.

## Current Behavior
Once initialized {cwd} returns the same value forever.

## Steps to Reproduce
mark@localhost ~ $ cd /tmp/
mark@localhost ~ $ pwd
/tmp 
mark@localhost ~ $

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
This was fixed in #4916
