### ISSUE TITLE
compatibility with zsh and bash-completions

### ISSUE THREAD

**Issue by TheJJ** [xonsh/xonsh#49]
Many programs ship some completion files, which are updated by the completed package itself. Parsing these files and providing zsh-like completion menus would be the killer feature.

**Comment by scopatz** [comment]
bash completion hooks are already there. I am not super familiar with what zsh does.  Is it significantly different than bash?

**Comment by TheJJ** [comment]
uh-oh. It's much more awesome than bash :grin:

If you are too lazy to write the config yourself, use [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh), or [try mine](https://github.com/TheJJ/conffiles/blob/master/homedir/.zshrc).

**Comment by TheJJ** [comment]
btw, i packaged `xonsh` in our [gentoo overlay](https://github.com/SFTtech/gentoo-overlay)

**Comment by erik-stephens** [comment]
@scopatz Can you explain how `BASH_COMPLETIONS` needs to be defined?  I can't figure out how to export it so that xonsh treats it as a list/tuple instead of a string.  Thanks in advance.  Without looking at the source, I tried a glob pattern:

    BASH_COMPLETIONS="${BASH_COMPLETION_DIR}/*" xonsh

Then I saw that it expects a tuple:

    BASH_COMPLETIONS="$(ls ${BASH_COMPLETION_DIR}/*)" xonsh

But that treats it as a string, so I tried an actual bash array but doesn't look like xonsh groks bash arrays:

    BASH_COMPLETIONS=($(ls ${BASH_COMPLETION_DIR}/*)) xonsh

**Comment by scopatz** [comment]
@TheJJ awesome! Thanks.

**Comment by scopatz** [comment]
@erik-stephens So `BASH_COMPLETIONS` expects a list or tuple of strings (see http://xonsh.org/tutorial.html#environment-variables).  The special env variables could probably use their own page in the documentation (pull requests welcome!).  Also you need to prefix environment variables with a `$`.  I would do something like following, using the backtick regular expression globbing, which returns a list of strings.

```console
$BASH_COMPLETIONS=`$BASH_COMPLETION_DIR/.*`
```

**Comment by scopatz** [comment]
Let me know if you still run into problems or if something is unclear.  For reference, mine look like:

```console
scopatz@athenaie ~ $ $BASH_COMPLETIONS
['/etc/bash_completion', '/usr/share/bash-completion/completions/git']
```

**Comment by erik-stephens** [comment]
@scopatz Ah!  The use of the phrase "environment variables" is confusing to me.  To me, that implies that environment variables defined in the parent process (eg bash) will be honored.  Defining $BASH_COMPLETIONS from *within* xonsh still doesn't work for me:

    me@machine ~/ $ $BASH_COMPLETIONS
    ['/opt/boxen/homebrew/etc/bash_completion']

I've got a not-so-standard setup so probably something on my end.  I'll poke around the code some more.

**Comment by erik-stephens** [comment]
Got it.  If I define $BASH_COMPLETIONS in a XONSHRC file, then completions are registered:

    BASH  : cat > ~/.xonshrc <<EOF
    $BASH_COMPLETIONS = ['/opt/boxen/homebrew/etc/bash_completion']
    EOF

    BASH  : XONSHRC=~/.xonshrc xonsh

    XONSH : $BASH_COMPLETIONS
    ['/opt/boxen/homebrew/etc/bash_completion']

    XONSH : git st
    st       stage    stash    status

**Comment by scopatz** [comment]
> Ah! The use of the phrase "environment variables" is confusing to me.

Whoops, sorry about the confusion @erik-stephens. Yeah, env variables are those that live in the special `__xonsh_env__` mapping. The xonsh language gives you access to these via the `$NAME` syntax. The contents (as applicable) of the environment are exported to subprocess, like in other shells and process management tools.

And yes, I am sorry I didn't realize or mention this.  The bash completion functions are loaded once right when the Shell class starts up.  That implies that you have to set the `$BASH_COMPLETIONS` variable in the xonshrc.  If you set it at run time, it is already too late. That tidbit should make it into the docs.  I'd really appreciate if you pull requested that in.  (I am super busy trying to respond to everyone's issues so help is *very* welcome ~_~)

**Comment by scopatz** [comment]
I think completions have evolved significantly since this issue was first opened.  Please feel free to open new issues that target the new completion framework.
