### ISSUE TITLE
prompt_ret_code stopped working and its replace doesn't have color substitution based on return code

### ISSUE THREAD

**Issue by con-f-use** [xonsh/xonsh#4918]
The prompt_ret_code xontrib stopped doing anything for me.

![image](https://user-images.githubusercontent.com/11145016/183745261-424968d8-a9d0-4f1b-af2f-bc59cc6211f7.png)

**Comment by con-f-use** [comment]
Ah, I see it's #4815 that did this. But I don't think the built-ins have feature parity, because I want color based on the return code.

**Comment by jnoortheen** [comment]
You can use something like this here - https://github.com/dev2718/xonsh/blob/6a7ff54991664f741c7a3c12c2a25e8f43c169f2/xonsh/prompt/base.py#L161

**Comment by con-f-use** [comment]
I'm not entirely sure what is happening there and what `{last_return_code_if_nonzero:[{BOLD_INTENSE_RED}{}{RED}] }` does. Doesn't seem to be standard python string formatting.

**Comment by jnoortheen** [comment]
Xonsh uses this to hide prompt field when the value is None. You see more detail in docs - https://xon.sh/tutorial.html#customizing-the-prompt

**Comment by con-f-use** [comment]
Yes, thanks for attention, but the bit I don't understand was the bit after the colon, i.e `:[{BOLD_INTENSE_RED}{}{RED}] }`. It's where normally a format spec for `last_return_code_if_nonzero` would go, but that stuff doesn't match any python format spec I'm aware of.

**Comment by jnoortheen** [comment]
Yes it is an invention of its own. whatever inside the {} is interpreted (colors, field names, env variables)

**Comment by con-f-use** [comment]
Okay got it, it's implemented in the xonsh prompt formatter code and is basicall something like the ternary conditional in C (`condition ? if_true : if_not`) only it's got no `if_not` branch. Again, thanks for explaining.
