### ISSUE TITLE
Add `--no-env` argument

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4921]
xonsh [has `--no-rc`](https://github.com/xonsh/xonsh/blob/6fa83f830579d2bad39b1842911951f55a9da22c/xonsh/main.py#L180-L186) to avoid loading RC files. But if we want to run completely clean xonsh we need to avoid inheritance environment.

For example sometimes I faced with issues when I want to run xonsh from xonsh and `$XONSH_HISTORY_FILE` goes to the new xonsh instance and lock the file system. I believe that the similar logic could produce the issues with any other use cases. For example we had issues around multiple running `xonsh -c ...` because the history backend uses the same file (fixed in #4178).

I suggest to add `--no-env` as well as [`--no-rc`](https://github.com/xonsh/xonsh/blob/6fa83f830579d2bad39b1842911951f55a9da22c/xonsh/main.py#L180-L186) argument that will run xonsh with `default_env` only:

https://github.com/xonsh/xonsh/blob/6fa83f830579d2bad39b1842911951f55a9da22c/xonsh/environ.py#L2499-L2500

So to get clean xonsh instance we can run `xonsh --no-rc --no-env`.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by 121247** [comment]
Hi, hello
Can I and my friend (@Juncheng-wq) take over this issue plz? We will try to work on it by the end of October. 
Thankyou

**Comment by 121247** [comment]
Hi maintainers,

Could I just ask if we want to write tests to see if the` default_env` is returned correctly by` --no-env` command, are we expected to include it in `test_environ.py` file or` test_main.py` file? I'm not so sure with if.

Thankyou
