### ISSUE TITLE
resizing terminal.app window on macos causes new prompts

### ISSUE THREAD

**Issue by tybug** [xonsh/xonsh#4958]
## xonfig

<details>

```
tybug@MacBook-Pro ~/Desktop $ xonfig
+------------------+-----------------+
| xonsh            | 0.13.3          |
| Python           | 3.10.5          |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.30          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.12.0          |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib          | []              |
| RC file          | []              |
+------------------+-----------------+
tybug@MacBook-Pro ~/Desktop $

```

</details>

## Expected Behavior

Resizing the terminal should not cause new prompts / lines to be printed.

## Current Behavior

resizing terminal window on macos causes new prompts to be printed. seems to happen once on every resize event, so if I only resize by 1px only one new prompt gets printed. Seems similar to #4194.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

install xonsh on macos -> `xonsh` in terminal.app -> resize terminal window

video: 

https://user-images.githubusercontent.com/31628143/193889933-140e852a-ae79-476c-a2d4-81f94954ff2e.mov

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
thanks for reporting @tybug !  
Can you try starting with the `readline` backend and see if the issue appears there, too?  You can do that by running `xonsh --shell-type readline`

**Comment by tybug** [comment]
issue does not reproduce with `xonsh --shell-type readline`

**Comment by gforsyth** [comment]
Okeydoke -- thanks!  Looks like this is an upstream issue with `prompt_toolkit` then -- I'm going to close this out here and you should open an issue at https://github.com/prompt-toolkit/python-prompt-toolkit
