### ISSUE TITLE
Enable xonsh in pdb sessions

### ISSUE THREAD

**Issue by corbinbs** [xonsh/xonsh#496]
I do a lot of debugging via test runs using `nosetests` with the `--pdb` and `--pdb-failures` switches turned on.   After hearing @scopatz speak at a meet up this evening, I started to wonder about additional extensions / use cases for xonsh capabilities when I'm dropped into a debugging session during a test run.   I think it could be quite powerful to have xonsh capabilities available during a typical debugging session.   Maybe pdb could be extended such that if `xonsh` was available, valid xonsh commands could be used while debugging?
After scanning https://docs.python.org/3/library/pdb.html, it looks like pdb is extensible since it's defined as the class https://docs.python.org/3/library/pdb.html#pdb.Pdb

**Comment by scopatz** [comment]
Thanks for the suggestion @corbinbs! There is also something out there called `ipdb` which has the same sort of idea, but for IPython. This would be a really cool feature to have.

**Comment by dotsdl** [comment]
If you write a `xonsh` script, and use `pdb` within it (such as putting `pdb.set_trace()` here and there), you can run it with your current `xonsh` shell and `pdb` will halt execution where you expect. I don't believe it is really possible (or advisable) to make `xonsh` handle `pdb` usage for scripts executed with a python child process, or with `nose` or `pytest`. It makes sense instead for those child processes to handle this behavior.
