### ISSUE TITLE
Web config tool includes \r in prompt

### ISSUE THREAD

**Issue by JoBrad** [xonsh/xonsh#4960]
When using the web config (xonfig web), newlines are interpreted as "\r\n". On macOS (and Linux, I assume) this adds a "^M" to the prompt, before the newline. 
## xonfig
```
+------------------+--------------------------------+
| xonsh            | 0.13.3                         |
| Python           | 3.10.7                         |
| PLY              | 3.11                           |
| have readline    | True                           |
| prompt toolkit   | 3.0.31                         |
| shell type       | prompt_toolkit                 |
| history backend  | json                           |
| pygments         | 2.13.0                         |
| on posix         | True                           |
| on linux         | False                          |
| on darwin        | True                           |
| on windows       | False                          |
| on cygwin        | False                          |
| on msys2         | False                          |
| is superuser     | False                          |
| default encoding | utf-8                          |
| xonsh encoding   | utf-8                          |
| encoding errors  | surrogateescape                |
| xontrib          | []                             |
+------------------+--------------------------------+
```

## Expected Behavior
I would expect the "\r" to be stripped from the text field before the prompt is set. 

## Current Behavior
I was able to confirm that the "\r" is being added to the prompt variable by checking my .xonshrc after using the web config. Removing this value removes the "^M" from my prompt.

## Steps to Reproduce
* Run xonfig web from your shell.
* Select a multi-line prompt, and set your .xonshrc
* Exit and restart xonsh. You'll see a "^M" before the new line.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by peipacut** [comment]
i'm happy to try working on this, could someone assign me the issue?

**Comment by gforsyth** [comment]
All yours, @peipacut -- we historically haven't relied on issue assignment, you should feel free to pick up any open issues and just ping in the issue that you're going to work on them to avoid duplicate effort.
