### ISSUE TITLE
COMMANDS_CACHE_SIZE_WARNING set in .xonshrc is ignored, warning still shows

### ISSUE THREAD

**Issue by oxysoft** [xonsh/xonsh#4961]
Hi, I have a simple problem:

```
Warning! Found 6,324 executable files in the PATH directories!

~ via  v18.8.0 🐍 v3.10.6
❯
```

This annoying message shows and I have found COMMANDS_CACHE_SIZE_WARNING to supposedly disable it by setting the number above 6000. I have tried all ways of setting this environment variable, but it seems there is no way to set it early enough.

How should I disable this annoying message? 

Thanks!

**Comment by oxysoft** [comment]
Yup

```
Warning! Found 6,324 executable files in the PATH directories!

~ via  v18.8.0 🐍 v3.10.6
❯ cat .xonshrc
$XONSH_COLOR_STYLE='one-dark'
$COMMANDS_CACHE_SIZE_WARNING = 99999

$fzf_history_binding = "c-r"  # Ctrl+R
$fzf_ssh_binding = "c-s"      # Ctrl+S
$fzf_file_binding = "c-t"      # Ctrl+T
$fzf_dir_binding = "c-g"      # Ctrl+G

xontrib load bashisms fish_completer whole_word_jumping abbrevs coreutils
xontrib load kitty
xontrib load zoxide
xontrib load fzf-widgets
xontrib load prompt_starship
xontrib load jedi
xontrib load histcpy
xontrib load hist_navigator
xontrib load cmd_done

~ via  v18.8.0 🐍 v3.10.6
❯
```

**Comment by gforsyth** [comment]
That's pretty weird -- two things:
1. Can you post the output of `xonfig`?
2. Is the value of the warning env-var equal to 99999 in the interactive session after things are loaded?

**Comment by jnoortheen** [comment]
This error has become irrelevant after #4954 merge.
