### ISSUE TITLE
how to activate anaconda / miniconda on Linux

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4985]
In Bash, I can do the following to enable conda:

```
~> eval "$(/home/jrmet/miniconda3/bin/conda shell.bash hook)"
(base) ~>
```

In Xonsh, I have tried a number of "similar looking commands", but I do not know how to activate my miniconda3 conda in a similar way. I hit several issues on this repo, but I was not able to adapt to my needs.

## xonfig

```
xonfig
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.8.10               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.19               |
| shell type       | prompt_toolkit       |
| pygments         | 2.6.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | True                 |
| jupyter kernel   | None                 |
| xontrib 1        | fzf-widgets          |
+------------------+----------------------+

```

## Expected Behavior

I am looking for a one liner extrapolated from the command I use in bash, to get access to ```conda``` in Xonsh.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
You can run `conda init xonsh` to add the required snippet to your `xonshrc`. (You'll have to restart your shell for it to take effect)

**Comment by jerabaul29** [comment]
Many thanks for the help :) . I get further but it does not work. What I did:

- in a new terminal in bash:

```bash
~> eval "$(/home/jrmet/miniconda3/bin/conda shell.bash hook)"
(base) ~> conda init xonsh
```

- in a new xonsh terminal: I can see that the conda command is now available:

```bash
jrmet@L590 ~  
conda env list
# conda environments:
#
base                  *  /home/jrmet/miniconda3
test_env                 /home/jrmet/miniconda3/envs/test_env
```

- however, it seems I cannot actually use the conda environment; after trying to activate, the prompt does not change, and I can see that the python3 I point to does not change either:

```bash
jrmet@L590 ~  
conda activate test_env
jrmet@L590 ~  
which python3
/usr/bin/python3
```

So it looks like it does not work at the moment. Also, I would like to i) be able to load conda / activate environments in xonsh, but ii) have by default no conda env (not even base) activated when firing a new xonsh window.

**Comment by bestlem** [comment]
conda command line accepts shell.xonsh as a parameter so should work in xonsh without going through bash

**Comment by jerabaul29** [comment]
@bestlem , sorry for likely being a n00b here, but can you explain a bit more?

- Initially I did not have access to the ```conda``` command in xonsh at all (I use to get access to ```conda``` in bash by using ```eval "$(/home/jrmet/miniconda3/bin/conda shell.bash hook)"```, but this does not work in xonsh, seems like the ```eval``` command does not exist?). By using the ```conda init xonsh``` in bash I now seem to have access to the ```conda``` command in xonsh now.

- however, I am still not able to activate environments in xonsh by using the conda command, as shown in the previous message.

**Comment by jerabaul29** [comment]
PS: the snippet added to my ```~/.xonshrc``` by issuing ```conda init xonsh``` in bash looks like:

```python
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
import sys as _sys
from types import ModuleType as _ModuleType
_mod = _ModuleType("xontrib.conda",
                   "Autogenerated from $(/home/jrmet/miniconda3/bin/conda shell.xonsh hook)")
__xonsh__.execer.exec($("/home/jrmet/miniconda3/bin/conda" "shell.xonsh" "hook"),
                      glbs=_mod.__dict__,
                      filename="$(/home/jrmet/miniconda3/bin/conda shell.xonsh hook)")
_sys.modules["xontrib.conda"] = _mod
del _sys, _mod, _ModuleType
# <<< conda initialize <<<
```

**Comment by jerabaul29** [comment]
Can this be related to https://github.com/xonsh/xonsh/issues/3067 ? It seems though that my version of conda is new enough:

- in bash:

```bash
~> eval "$(/home/jrmet/miniconda3/bin/conda shell.bash hook)"
(base) ~> conda --version
conda 4.10.3
```

- in xonsh though, I get a weird error (though the conda command is available):

```
jrmet@L590 ~  
conda --version
usage: xonsh command
xonsh: error: the following arguments are required: command
conda activate test_env
jrmet@L590 ~  # but nothing is activated I think: see below
jrmet@L590 ~  
which python3
/usr/bin/python3

```

**Comment by bestlem** [comment]
The snippet from conda init xonsh looks OK.
BUT
I think I now get the same issue as you.

The working version I have is if I have created an xonsh environment in conda. ie installing xonsh via conda.

Then I start xonsh using the conda installed xonsh 
i.e.
    /Users/mark/miniconda3/envs/xonsh/bin/xonsh 

Sorry for making it appear simple.

I seem to remember when setting this up a few years ago it dod take me several attempts as I could not get it working from a plain python - It would be nice if someone who did have that working as many messages here say showed a minimal rc.xsh file that works.

**Comment by jerabaul29** [comment]
Many thanks for you digging further in this @bestlem :) . No worries at all, glad we understand why it was hard on my setup and easy on your initial setup :) .

Yes, being able to use conda from xonsh even if xonsh was not installed in conda would be very useful :) .

**Comment by gforsyth** [comment]
You can definitely install xonsh outside of `conda` and still use `conda` (i know this because I would have a _very_ hard time developing it otherwise).

One thing to try here is to (temporarily) remove any conda activate snippets from your `bashrc` or similar -- since `xonsh` attempts to port over existing bash functions if it is launched from `bash` you may be hitting some weird collision in how we define the `conda activate` helper.

**Comment by jerabaul29** [comment]
@gforsyth I do not have any conda in my bashrc at the moment that I know of (and I just checked by grepping for conda in my bashrc). Any extra idea about why I seem to have the conda command available in xonsh but activating an environment seems to do nothing?

If you have a simple, step by step instruction about how to use conda in xonsh and being able to activate an environment that would be great :) . And / or sharing some insights about the parts of your xonshrc that make things work out :) .

**Comment by jerabaul29** [comment]
As a side note, if this may help:

```
~> tail -14 .xonshrc 

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
import sys as _sys
from types import ModuleType as _ModuleType
_mod = _ModuleType("xontrib.conda",
                   "Autogenerated from $(/home/jrmet/miniconda3/bin/conda shell.xonsh hook)")
__xonsh__.execer.exec($("/home/jrmet/miniconda3/bin/conda" "shell.xonsh" "hook"),
                      glbs=_mod.__dict__,
                      filename="$(/home/jrmet/miniconda3/bin/conda shell.xonsh hook)")
_sys.modules["xontrib.conda"] = _mod
del _sys, _mod, _ModuleType
# <<< conda initialize <<<
```

and 

```
~> cat /home/jrmet/miniconda3/bin/conda
#!/home/jrmet/miniconda3/bin/python
# -*- coding: utf-8 -*-
import sys
# Before any more imports, leave cwd out of sys.path for internal 'conda shell.*' commands.
# see https://github.com/conda/conda/issues/6549
if len(sys.argv) > 1 and sys.argv[1].startswith('shell.') and sys.path and sys.path[0] == '':
    # The standard first entry in sys.path is an empty string,
    # and os.path.abspath('') expands to os.getcwd().
    del sys.path[0]

if __name__ == '__main__':
    from conda.cli import main
    sys.exit(main())
```

(a bit surprised by how little there is in the second one, but that may be as expected?).

**Comment by gforsyth** [comment]
Do you see `conda` listed in the output of `xontrib list`?

here's me re-adding `conda` support from a pretty bare-bones setup:
```xonsh
gil@stravaig ~ $ $PATH
EnvPath(
['/usr/bin',
 '/usr/local/bin',
 '/usr/bin/vendor_perl',
 '/usr/bin/core_perl']
)
gil@stravaig ~ $ which conda
conda not in $PATH or xonsh.builtins.aliases
gil@stravaig ~ [1] $ xontrib list
abbrevs             not-loaded
autovox             not-loaded
bashisms            not-loaded
conda               not-loaded
coreutils           not-loaded
direnv              not-loaded
fish_completer      not-loaded
free_cwd            not-loaded
pdb                 not-loaded
prompt_ret_code     not-loaded
term_integration    not-loaded
vox                 not-loaded
voxapi              not-loaded
whole_word_jumping  not-loaded
xog                 not-loaded
gil@stravaig ~ $ import sys as _sys
                 from types import ModuleType as _ModuleType
                 _mod = _ModuleType("xontrib.conda",
                                    "Autogenerated from $(/home/gil/mambaforge/bin/conda shell.xonsh hook)
")
                 __xonsh__.execer.exec($("/home/gil/mambaforge/bin/conda" "shell.xonsh" "hook"),
                                       glbs=_mod.__dict__,
                                       filename="$(/home/gil/mambaforge/bin/conda shell.xonsh hook)")
                 _sys.modules["xontrib.conda"] = _mod
                 del _sys, _mod, _ModuleType
(base) gil@stravaig ~ $ xontrib list
abbrevs             not-loaded
autovox             not-loaded
bashisms            not-loaded
conda               loaded      manual
coreutils           not-loaded
direnv              not-loaded
fish_completer      not-loaded
free_cwd            not-loaded
pdb                 not-loaded
prompt_ret_code     not-loaded
term_integration    not-loaded
vox                 not-loaded
voxapi              not-loaded
whole_word_jumping  not-loaded
xog                 not-loaded
(base) gil@stravaig ~ $ conda activate conda-build
(conda-build) gil@stravaig ~ $ conda deactivate
```

**Comment by jerabaul29** [comment]
I do not see conda in xontrib list:

```
jrmet@L590 ~  
$PATH
EnvPath(
['/home/jrmet/miniconda3/bin',
 '/home/jrmet/miniconda3/condabin',
 '/home/jrmet/.cargo/bin',
 '/home/jrmet/.local/bin',
 '/home/jrmet/bin',
 '/usr/local/sbin',
 '/usr/local/bin',
 '/usr/sbin',
 '/usr/bin',
 '/sbin',
 '/bin',
 '/usr/games',
 '/usr/local/games',
 '/snap/bin']
)
jrmet@L590 ~  
which conda
conda
jrmet@L590 ~  
xontrib list
abbrevs             installed      not-loaded
autovox             installed      not-loaded
bashisms            installed      not-loaded
coreutils           installed      not-loaded
distributed         installed      not-loaded
free_cwd            installed      not-loaded
fzf-widgets         installed      loaded
jedi                installed      not-loaded
mpl                 installed      not-loaded
mplhooks            installed      not-loaded
pdb                 installed      not-loaded
prompt_bar          installed      not-loaded
prompt_ret_code     installed      not-loaded
prompt_vi_mode      installed      not-loaded
readable-traceback  installed      not-loaded
vox                 installed      not-loaded
voxapi              installed      not-loaded
whole_word_jumping  installed      not-loaded
xog                 installed      not-loaded
```

Running the snippet from the xonshrc does not make conda appear either.

**Comment by bestlem** [comment]
No I mean install xonsh from conda package https://anaconda.org/conda-forge/xonsh into a conda environment say xonsh. Then use this xonsh as your shell.

**Comment by bestlem** [comment]
@gforsyth - this is the same issues as I had.

Can you please show a complete rc.xsh that allows you to run conda.

Yes we know the snippet to be loaded from conda and know the files in conda but that does not seem to be sufficient.
It is the setup before the snippet from conda that I am missing?

It might be as simple as showing how to get the conda xontrib - Google for it shows no such xontrib - nor does https://xonsh.github.io/awesome-xontribs/ which xonsh gives as an error message

**Comment by gforsyth** [comment]
The `conda` xontrib is created by the snippet created when you run `conda init xonsh`.  I'll try spinning up a docker container to start from "scratch" -- also, try updating `xonsh` since 0.9.27 is quite out of date

**Comment by gforsyth** [comment]
This is in a fresh ubuntu container -- all I've done is installed `curl` so I can grab a `Mambaforge` installer, then installed `mambaforge` and done a `./mambaforge/bin/mamba install -c conda-forge xonsh`

```
root@stravaig:~# which conda
root@stravaig:~# echo $SHELL
/bin/bash
root@stravaig:~# ./mambaforge/bin/conda init xonsh
modified      /root/mambaforge/condabin/conda
modified      /root/mambaforge/bin/conda
modified      /root/mambaforge/bin/conda-env
no change     /root/mambaforge/bin/activate
no change     /root/mambaforge/bin/deactivate
no change     /root/mambaforge/etc/profile.d/conda.sh
no change     /root/mambaforge/etc/fish/conf.d/conda.fish
no change     /root/mambaforge/shell/condabin/Conda.psm1
no change     /root/mambaforge/shell/condabin/conda-hook.ps1
no change     /root/mambaforge/lib/python3.10/site-packages/xontrib/conda.xsh
no change     /root/mambaforge/etc/profile.d/conda.csh
modified      /root/.xonshrc

==> For changes to take effect, close and re-open your current shell. <==

root@stravaig:~# ./mambaforge/bin/xonsh
(base) <user>@stravaig ~ # which conda
<function _conda_main at 0x7f0ca7b565f0>
(base) <user>@stravaig ~ # conda deactivate
<user>@stravaig ~ [2] # conda activate base
(base) <user>@stravaig ~ #
```

Or, if I uninstall  `xonsh` from the base environment and instead create an environment called `xonsh` and install it in there:

```
root@stravaig:~# ./mambaforge/envs/xonsh/bin/xonsh
(base) <user>@stravaig ~ # conda deactivate
<user>@stravaig ~ [2] # conda activate base
(base) <user>@stravaig ~ #
```

**Comment by jerabaul29** [comment]
Mmmh, as discussed above, somehow, this is not working in my case. I *think* (this was a couple of years ago) that I had installed xonsh outside of a conda environment, wonder if this is the explanation.

**Comment by jerabaul29** [comment]
```
jrmet@L590 ~  
xpip install --upgrade xonsh
[sudo] password for jrmet: 
Collecting xonsh
  Downloading xonsh-0.13.3-py38-none-any.whl (623 kB)
     |████████████████████████████████| 623 kB 5.0 MB/s 
Installing collected packages: xonsh
Successfully installed xonsh-0.13.3
jrmet@L590 ~  
conda init xonsh
no change     /home/jrmet/miniconda3/condabin/conda
no change     /home/jrmet/miniconda3/bin/conda
no change     /home/jrmet/miniconda3/bin/conda-env
no change     /home/jrmet/miniconda3/bin/activate
no change     /home/jrmet/miniconda3/bin/deactivate
no change     /home/jrmet/miniconda3/etc/profile.d/conda.sh
no change     /home/jrmet/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/jrmet/miniconda3/shell/condabin/Conda.psm1
no change     /home/jrmet/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/jrmet/miniconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /home/jrmet/miniconda3/etc/profile.d/conda.csh
no change     /home/jrmet/.xonshrc
No action taken.
jrmet@L590 ~  
conda activate tejrmet@L590 ~  
which python3  # confirm that conda had no effect
/usr/bin/python3
```

I checked, no conda stuff in my bashrc.

**Comment by gforsyth** [comment]
You relaunched xonsh after upgrading, yes? Can you post the new xonfig and also your PATH?

**Comment by jerabaul29** [comment]
Yes, I have relaunched xonsh (I restarted my whole machine after the update).

```
jrmet@L590 ~  
xonfig
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.8.10               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.19               |
| shell type       | prompt_toolkit       |
| pygments         | 2.6.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | True                 |
| jupyter kernel   | None                 |
| xontrib 1        | fzf-widgets          |
+------------------+----------------------+
jrmet@L590 ~  
echo $PATH
/home/jrmet/miniconda3/envs/test_env/bin:/home/jrmet/miniconda3/condabin:/home/jrmet/.cargo/bin:/home/jrmet/.local/bin:/home/jrmet/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

PS: I can re-confirm that I have no conda stuff in my bashrc, and the PATH in my bash looks like:

```
~> echo $PATH
/home/jrmet/.cargo/bin:/home/jrmet/.local/bin:/home/jrmet/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Also I set up a shortcut for starting xonsh terminals:

```
Ctrl-Alt-x => 'gnome-terminal -e xonsh
```

But I get the same result starting xonsh from a normal bash terminal:

```
~> xonsh
jrmet@L590 ~  
conda activate test_env
jrmet@L590 ~  
which conda
conda
jrmet@L590 ~  
which python3
/usr/bin/python3
```

**Comment by gforsyth** [comment]
I'm confused as to why your version is still 0.9.27 after you've installed 0.13.x

**Comment by jerabaul29** [comment]
That's true. Weird. No idea either. I do have restarted my machine.

**Comment by gforsyth** [comment]
Where is `xonsh` installed?

**Comment by jerabaul29** [comment]
```
~> which xonsh
/home/jrmet/.local/bin/xonsh
```

**Comment by gforsyth** [comment]
Ok, that seems like the sensible place for a `pip` install to land.  I would look at `/etc/shells` and other spots to confirm you haven't hard-coded the path to the older `xonsh` in some place -- once you can start up the upgraded version we can check on other possible issues with the `conda` activation

**Comment by gforsyth** [comment]
There's clearly some weirdness _somewhere_ but it can be hard to find.  I just want to cover our bases first by getting things upgraded before we continue troubleshooting in weird corners.
