### ISSUE TITLE
`history` only shows histories in current session

### ISSUE THREAD

**Issue by jcguu95** [xonsh/xonsh#4998]
## xonfig

My config is empty.

```
# nothing here
```

## Expected Behavior
Enter `history`, and a list of all commands input in all previous sessions should be printed, according to [the tutorial](https://xon.sh/tutorial_hist.html)

> xonsh displays the past inputs from all valid json files found in XONSH_DATA_DIR. As such, this operates on all past and present xonsh sessions.

My `XONSH_DATA_DIR` is `~/.local/share/xonsh/`, while all the json histories can be found in `~/.local/share/xonsh/history_json/`.

## Current Behavior

Only the commands input in the current sessions are printed.

## Steps to Reproduce
```
bash > xonsh
xonsh> 1
1
xonsh> history
1
xonsh> exit
bash > xonsh
xonsh> history
xonsh>
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jcguu95** [comment]
@anki-code Thanks for the suggestion. However, even with sqlite backend, with the command `history` I can only see the histories in the current session..

**Comment by jnoortheen** [comment]
@jcguu95 by default it returns the current session. `history all` can be used for listing from all sessions.

**Comment by jnoortheen** [comment]
I am closing this issue, since the `history` in the tutorial is hightlighted to show the commands from the same session.

**Comment by jcguu95** [comment]
@jnoortheen .. Doesn't seem to work for me. Is this a version issue?

```
$ xonsh --version
xonsh/0.13.3
$ xonsh
jin@guu ~ $ history all
usage: history [-h] {show,id,file,info,flush,off,on,clear,gc,transfer} ...

history: error: cannot convert 'all' to slice
```

**Comment by jnoortheen** [comment]
my bad `history show all` will work
