### ISSUE TITLE
vox only has global virtual environments

### ISSUE THREAD

**Issue by Virgilio-AI** [xonsh/xonsh#5002]
I want to be able to have the same functionality as 
```
python -m venv environmen_name
```
because it creates a folder in the same directory and you can just simply source it with
```
source environment_name/bin/activate
```
I know you can use source_bash but the problem is that you cannot deactivate it hence the need for vox.

please I would be the only thing that I need xonsh to be able to do, also if you need my help I could develop it myself. just with the help of a little guidance on the project structure and vox source files

**Comment by jnoortheen** [comment]
You can activate venv created with `python -m venv` with vox. 

```
python -m venv /tmp/venv
vox activate /tmp/venv
vox deactivate
```

If you want to implement creating venv at the given path, you can start by checking https://github.com/xonsh/xonsh/blob/c07155dbe2a86c9547326e91baaea3c47511c370/xontrib/vox.py#L78 . I suggest when the given name starts with path literal, like `./path or /root/path` it should treat that as the destination path.

**Comment by Virgilio-AI** [comment]
oh I think I missed that, thank you. and I will certainly will look into that thanks for the insight
