### ISSUE TITLE
Format of documentation of snippets

### ISSUE THREAD

**Issue by bestlem** [xonsh/xonsh#5011]
In the documentation for xonsh snippets in the [Run Control File page](https://xon.sh/xonshrc.html#snippets-for-xonshrc) all the snippets are prefixed with the python input prompt, however on the rest of the page code is not prefixed.

Is there a reason for doing this.

I think it is wrong as you can't cut and paste these snippets easily as the >>> has to be removed.

**Comment by gforsyth** [comment]
Hey @bestlem -- I agree that we should strip out the leading characters.

Longer term, it might be nice to do something similar to IPython and ignore leading characters that match known prompt prefixes, but that'll be more work than just updating the docs.

Care to put in a PR?
