### ISSUE TITLE
Prompt toolkit broke after update

### ISSUE THREAD

**Issue by pannet1** [xonsh/xonsh#5016]
## xonfig

<details>

```
$ xonfig


+------------------+------------------------+
| xonsh            | 0.13.3                 |
| Python           | 3.10.9                 |
| PLY              | 3.11                   |
| have readline    | True                   |
| prompt toolkit   | 3.0.36                 |
| shell type       | prompt_toolkit         |
| history backend  | json                   |
| pygments         | 2.13.0                 |
| on posix         | True                   |
| on linux         | True                   |
| distro           | unknown                |
| on wsl           | False                  |
| on darwin        | False                  |
| on windows       | False                  |
| on cygwin        | False                  |
| on msys2         | False                  |
| is superuser     | False                  |
| default encoding | utf-8                  |
| xonsh encoding   | utf-8                  |
| encoding errors  | surrogateescape        |
| xontrib 1        | gruvbox                |
| xontrib 2        | output_search          |
| xontrib 3        | cmd_done               |
| xontrib 4        | distributed            |
| xontrib 5        | gitinfo                |
| xontrib 6        | sh                     |
| xontrib 7        | broot                  |
| xontrib 8        | argcomplete            |
| xontrib 9        | back2dir               |
| xontrib 10       | up                     |
| xontrib 11       | mpl                    |
| xontrib 12       | abbrevs                |
| xontrib 13       | autovox                |
| xontrib 14       | hist_navigator         |
| xontrib 15       | readable-traceback     |
| xontrib 16       | coreutils              |
| xontrib 17       | prompt_vi_mode         |
| xontrib 18       | vox_tabcomplete        |
| xontrib 19       | ssh_agent              |
| xontrib 20       | onepath                |
| xontrib 21       | xlsd                   |
| xontrib 22       | vox                    |
| xontrib 23       | kitty                  |
| xontrib 24       | avox                   |
| xontrib 25       | autoxsh                |
| xontrib 26       | voxapi                 |
| xontrib 27       | powerline3             |
| xontrib 28       | z                      |
| xontrib 29       | pdb                    |
| xontrib 30       | histcpy                |
| RC file 1        | /home/pannet1/.xonshrc |
+------------------+------------------------+
```
</details>

When i open the shell i get the below error. I am on EOS and hence rolling to the latest and greatest versions where available.
`
/usr/lib/python3.10/site-packages/prompt_toolkit/eventloop/utils.py:118: DeprecationWarning: There is no current event loop
  return asyncio.get_event_loop_policy().get_event_loop()
`

**Comment by ion201** [comment]
Upstream issue https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1696

**Comment by pannet1** [comment]
Will try this workaround

https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1696#issuecomment-1355308726

**Comment by mattmc3** [comment]
Last time I got fed up and just went ahead and figured out how to fix it for the prompt-toolkit project:
- https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1440#issuecomment-936471685
- https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1505)
 
This time, I'm not really sure what's going on, so hopefully another hero rises to the challenge.

**Comment by wasertech** [comment]
I find this comment on a PR that tried to solve prompt toolkit to be very informative:
https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1823#issuecomment-1845609678

**Comment by pannet1** [comment]
The combination of Arch and Xonsh, creates lot of issues for someone with programming as a profession like me. Unfortunately shifting back to bash and it ecosystem for now. Combining System Python and Arch packages during installation worked. I have not figured yet how venv installation would work alongwith the actual venv i create for each one of my python projects.

Anyway, thanks for the update @wasertech

**Comment by pannet1** [comment]
over the many past months, i have  got  great support from you .  python programming is my main business and yet i lack the skill in managing the quirks of arch and pip installation ecosystem. even i am  facing lot of problems when developing in linux  box and delivering to customers on windows box. this is nothing to do with xonsh. having said this i am always trying to come back to qtile/xonsh combo. sorry did  not mean to disappoint you.
