### ISSUE TITLE
Documentation Error displayed.

### ISSUE THREAD

**Issue by bestlem** [xonsh/xonsh#5041]
On https://xon.sh/customization.html the page under Firefox and Safari on macOS shows the table of contents starting with and error message which you can't copy and paste.

So screenshot
![Screenshot ](https://user-images.githubusercontent.com/37385/216028304-e74627dd-0e74-4ec2-8248-2634ebc8ce8c.png)

**Comment by gforsyth** [comment]
Thanks for the  heads up @bestlem !  I've pushed up a fix.

**Comment by bestlem** [comment]
The rogue table of contents is still there.
