### ISSUE TITLE
Separating xonsh/xontrib to repositories

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5051]
We have 11 xontribs in [xonsh/xontrib](https://github.com/xonsh/xonsh/tree/main/xontrib). 

If we separate the xontribs to repositories:
* We will have [almost 100 xontribs on Github](https://github.com/topics/xontrib)
* We will have separate rating, description and issues like in [mpl, jupyter, jedi, etc](https://github.com/xonsh?q=xontrib-&type=all&language=&sort=)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by bestlem** [comment]
I agree with anki-code that having different projects does make it easier for contributors so they can see just the parts they are interested in.

However trhe upside of having xontribs in the main repo is that you can just call them from your xonsh startup scripts and not have to play around with manually calling xpip to install when on a new machine.

To help this it might be useful for xonsh to optionally call xpip it self if it could not load the xontrib or provide someother help.
