### ISSUE TITLE
Improve suggestions (as-in ipython 8.9+)

### ISSUE THREAD

**Issue by doronz88** [xonsh/xonsh#5056]
IPython lately refactored their suggesions and completers UX to allow several new features. You can look here at their PR:
https://github.com/ipython/ipython/pull/13888

I think the best one of this feature is making the `right` key accept a single character instead of the whole expression, since sometimes all we want is just partial completions from that whole expression. In addition, for those who do want to whole completion you can just `Ctrl`+`E` or `End` to have it as-well.

Also, in general since xonsh tries to give an IPython-like feel I think its better to change accordingly.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
ipython uses the same prompt-toolkit to achieve this, so I don't get why is this a prompt-toolkit issue?

**Comment by gforsyth** [comment]
We currently support completing individual words with `Ctrl-Right`.

I'm not sure we are going to change the behavior of the right-arrow just to match IPython (by default).  This probably falls under one more thing where it would be great if users could define their own keybindings.

**Comment by doronz88** [comment]
I saw this in `key_bindings.py`, however on macOS `Ctrl` is reserved and therefore this doesn't work there

**Comment by doronz88** [comment]
@gforsyth I'll create then a PR that also creates an alias for `escape`+`right`
