### ISSUE TITLE
$MULTILINE_PROMPT doesn't filter out OSC commands

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#5058]
I'm adding "terminal integration" to xonsh and as such need to add various prompt commands to prompt for the terminal to recognize when input/output starts/ends etc. [doc](https://github.com/wez/wezterm/blob/main/docs/shell-integration.md)

It's working fine in other prompt variables, but then in `$MULTILINE_PROMPT` it breaks down, I see the commands as literal ugly strings instead of them being their regular invisible selves with just `.`

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.13.4          |
| Python           | 3.10.10         |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.36          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.14.0          |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib 1        | cd              |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior

```xsh
$MULTILINE_PROMPT = "\001" + "\x1b]133;P;k=c\x07" + "\002" + "."
```

Signals that every new line in the multiline propmt is a "continuation prompt", but it should be invisible, the result should be just the same multiple `.` dots depending on your prompt width

## Current Behavior

Instead, I get this
```xsh
$MULTILINE_PROMPT = "\001" + "\x1b]133;P;k=c\x07" + "\002" + "."
~ $ if 2:
^A^[]133;P;k=c^G^B.^A^[]133;P;     echo 1
#                 ↑ this is our dot :)
```

while this works fine
```xsh
~ $ $PROMPT = "\001" + "\x1b]133;P;k=i\x07" + "\002" + "<"
<
```

It might be due to some issues in parsing in this command here? Maybe it's due to repetition of the `.`?:

https://github.com/xonsh/xonsh/blob/main/xonsh/prompt/base.py#L184

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

- Start `xonsh --no-rc`
- Execute `$MULTILINE_PROMPT = "\001" + "\x1b]133;P;k=c\x07" + "\002" + "."`
- Type a multiline command

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
This sounds like a problem solved here https://github.com/xonsh/xonsh/pull/4629 . I think the codes need to be wrapped differently for ptk shell and readline shells

**Comment by eugenesvk** [comment]
How should they be wrapped in ptk?

The linked messages mentions the 1/2 which are already used as wrapping codes
>* OSC codes in ``$PROMPT`` is no longer removed when using ptk shell.
> These codes need to be escaped with ``\001..\002`` instead.

I've tried to replace the wrapper functiton with returning this, but that didn't help
```py
def ansi_esc_ptk(code: str):
  return fragment_list_to_text([
    ("[ZeroWidthEscape]","\001"), ("", f"{code}"), ("[ZeroWidthEscape]","\002"),
  ])
```
