### ISSUE TITLE
curr_branch not working in my prompt

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#5132]
I switched to a new (Windows) laptop, and my prompt no longer shows the branch I'm in. The config is the same between the two laptops, although the xonsh version probably did change.

## xonfig
```
+------------------+--------------------------+
| xonsh            | 0.13.4                   |
| Git SHA          | 85e85edc                 |
| Commit Date      | Dec 8 14:22:27 2022      |
| Python           | 3.11.1                   |
| PLY              | 3.11                     |
| have readline    | True                     |
| prompt toolkit   | 3.0.36                   |
| shell type       | prompt_toolkit           |
| history backend  | json                     |
| pygments         | 2.14.0                   |
| on posix         | False                    |
| on linux         | False                    |
| on darwin        | False                    |
| on windows       | True                     |
| on cygwin        | False                    |
| on msys2         | False                    |
| is superuser     | False                    |
| default encoding | utf-8                    |
| xonsh encoding   | utf-8                    |
| encoding errors  | surrogateescape          |
| xontrib 1        | autojump                 |
| xontrib 2        | coreutils                |
| RC file 1        | C:\Users\me/.xonshrc |
+------------------+--------------------------+
```
</details>

## Expected Behavior
I should see the branch.

## Current Behavior
I don't see the branch.

Please give me ideas on how to debug. Could this be due to a git configuration issue?

Thanks.

**Comment by jnoortheen** [comment]
You can start looking from https://github.com/xonsh/xonsh/blob/041bfb2d2936fc20a5f45802c9106d98cd2feb9c/xonsh/prompt/vc.py#L178 . The same can be executed as '$PROMPT_FIELDS["cuurent_branch"]()'. Please what is the output of the function

**Comment by mn-intel** [comment]
This was a fun one to debug. 

`$PROMPT_FIELDS["current_branch"]()` returns nothing. Digging into the code, it seems the subprocess call to `git` fails:

```
 subprocess.check_output(['git', 'symbolic-ref', '--short', 'HEAD'], env=denv)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

It does work if I add `shell=True`.

I tried it on a fresh xonsh config and everything works fine, so something in my config was causing  the problem. I narrowed it down to loading the [autojump xontrib](https://github.com/wshanks/xontrib-autojump).

Specifically, this line was causing the problem:

```
    # the $PATH variable from xonsh isn't respected by python's subprocess so
    # put it in the environment
    os.environ["PATH"] = ':'.join(__xonsh__.env['PATH'])
```

Now I need to figure out how to fix autojump!

**Comment by jnoortheen** [comment]
@mn-intel , further you can inspect the value of https://github.dev/xonsh/xonsh/blob/8b0dd5cae744ce6aba14c92713a6334c719004ec/xonsh/prompt/vc.py#L26 denv dictionary when the subprocess runs? 

One other thing, does `$PROMPT_FIELDS["gitstatus"]()` work ?

**Comment by mn-intel** [comment]
There is no difference in the denv dictionary, but when I do `os.environ["PATH"]`, there is a difference. Without commenting out the offending line, the separators are all colons. In Windows it should be semicolon, which is what I get when I comment the line out.

So changing the line to:

```
os.environ["PATH"] = os.pathsep.join(__xonsh__.env['PATH'])
```

makes it work again.

**Comment by jnoortheen** [comment]
Good then, you can make this a PR to the autojump extension. It can help others as well.
