### ISSUE TITLE
piping from xonfig is not working

### ISSUE THREAD

**Issue by AsafMah** [xonsh/xonsh#5150]
## xonfig

<details>

```
$ xonfig
+------------------+------------------------------+
| xonsh            | 0.13.4                       |
| Git SHA          | 85e85edc                     |
| Commit Date      | Dec 8 14:22:27 2022          |
| Python           | 3.11.0                       |
| PLY              | 3.11                         |
| have readline    | True                         |
| prompt toolkit   | 3.0.38                       |
| shell type       | prompt_toolkit               |
| history backend  | json                         |
| pygments         | 2.14.0                       |
| on posix         | False                        |
| on linux         | False                        |
| on darwin        | False                        |
| on windows       | True                         |
| on cygwin        | False                        |
| on msys2         | False                        |
| is superuser     | False                        |
| default encoding | utf-8                        |
| xonsh encoding   | utf-8                        |
| encoding errors  | surrogateescape              |
| xontrib 1        | commands                     |
| RC file 1        | C:\Users\<redacted>/.xonshrc |
+------------------+------------------------------+
```

</details>

## Expected Behavior
` xonfig info -j | jq .`  should finish pretty much immedietly.

## Current Behavior
error

It hangs forever.

Weirdly enough:
```xonsh
 xonfig info -j > f
```
Does work fine

Here it is with the debug flag:
```
xonfig info -j | jq .
<stdin>:1:7 - xonfig info -j | jq .
<stdin>:1:7 + ![xonfig info -j | jq .]
```
(Get's stuck there)

## Steps to Reproduce
1. Xonsh windows (emptied my xonshrc file to be sure it's nothing else)
2. get jq
3. run the command `xonfig info -j | jq .`

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by guraltsev** [comment]
I am having the same exact problem and specifically with `jq`! I tried it with the python from `msys2` with `ucrt64` as well as with the standard windows python (3.11.7 and 3.12.1). In both cases `jq` hangs from the command:

``` xonsh
echo "{\"a\":2}"  |  jq .
```
but works perfectly if  one does
``` xonsh
echo "{\"a\":2}"  > test
jq . test
```
Also, the same problem happens if one does 
``` xonsh
echo "{\"a\":2}"  > test
cat test | jq . 
````

However 
``` xonsh
tail test | jq .
```
works ok! 

The problem, I believe, is that both `cat` and `echo` are xonsh commands while tail is a "true" executable. 

The problem seems to lie in the piping logic of xonsh

**Comment by guraltsev** [comment]
Just a follow-up. Actually! it is not just `jq` that does not work. Piping seems broken in general. For example:

```
echo "hello" |  C:\Programs.global\msys2\app.noinstall\ucrt64\bin\cat.exe
```
freezes in xonsh but works normally under git-bash for windows or msys bash

**Comment by anki-code** [comment]
Closed with the reference to https://github.com/xonsh/xonsh/issues/5317#issuecomment-2032017790

Use explicit `@thread xonfig | grep xonsh` because xonfig marked as unthreadable yet.
