### ISSUE TITLE
stderr not captured

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#5176]
## xonfig

<details>

```
 bugs @ xonfig
+------------------+-----------------+
| xonsh            | 0.14.0          |
| Python           | 3.11.4          |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.39          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on wsl           | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib 1        | voxapi          |
| xontrib 2        | vox             |
| xontrib 3        | jaraco.xonsh    |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior

Using captured output (`$()`, `!()`), the output should be captured into a variable.

## Current Behavior

I've tried capturing output from a command, but the output is never captured. I've tried all of [these workarounds](https://github.com/anki-code/xonsh-cheatsheet#uncaptured-output), but none of them have any effect. I've verified that 
`$XONSH_CAPTURE_ALWAYS=True`:

```
 bugs @ res = $(/google/bin/releases/piper-fig/fetch_bugreport_upload/fetch_bugreport_upload --upload_id=c5d1c460fec6268e)
fetching 100% |Goooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogle|       1/1 chunks     1.58/s Time: 00:00:00
Bugreport upload downloaded into /usr/local/google/home/jaraco/bugs/bugreport_upload-unknown_bug-1.tar.gz
Bugreport upload extracted into /usr/local/google/home/jaraco/bugs/291148228-1
 bugs @ res
''
```

I don't know a whole lot about the binary I'm running, though I could find out more. It is not a shell script but an ELF binary on Linux.  It's not excluded from threadable predictors:

```
 bugs @ __xonsh__.commands_cache.threadable_predictors['fetch_bugreport_upload']
<function xonsh.commands_cache.predict_true>
```

What other options do I have to troubleshoot why the output isn't captured?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
If it is writing to stderr you should redirect it to stdout.

**Comment by jaraco** [comment]
> If it is writing to stderr you should redirect it to stdout.

That is indeed what's happening. Adding `2>&1` to the command worked around the issue. I'm guessing `e>o` would have worked too.

Thanks, I guess everything is working as intended.

I wonder if the docs should advise somewhere that

- only stdout is captured (not stderr)
- add `e>o` to a command to capture both stderr and stdout.

**Comment by jnoortheen** [comment]
It is common for shells to capture only the stdout by default
