### ISSUE TITLE
Ctrl-Z on jobs does not work $XONSH_STORE_STDOUT = True

### ISSUE THREAD

**Issue by nicfit** [xonsh/xonsh#519]
```bash
$ sleep 10
^Z^Z^Z^Z^Z^Z^Z^Z
````

**Comment by scopatz** [comment]
Thanks for reporting @nicfit

**Comment by redshodan** [comment]
Looks like the True value is coming from the ~/.xonshrc file. I did not create that file and must have been autocreated with $XONSH_STORE_STDOUT=True in it. Once I flip that setting, ^Z works fine.

**Comment by scopatz** [comment]
> I did not create that file and must have been autocreated with $XONSH_STORE_STDOUT=True in it.

Hmm that is strange.  I don't believe that we autocreate that file.  Not sure where that would be coming from.

**Comment by redshodan** [comment]
It's certainly possible I copied the example xonshrc from http://xonsh.org/xonshrc.html and forgot about that. My xonshrc is almost an exact duplicate, minus removing the LD_LIBRARY_PATH and changing the homedir. I've tried a couple of times to break my bash addiction and get into xonsh, with long periods of time inbetween. :) I didn't think I had it set and was trying to figure out why it kept coming up True. Nevermind, sorry to distract from the real problem.

**Comment by scopatz** [comment]
> sorry to distract from the real problem.

No worries!

>  I've tried a couple of times to break my bash addiction and get into xonsh, with long periods of time inbetween. :)

If there are specific areas that you think could use help, please let us know!
