### ISSUE TITLE
Idea: $RANDOM

### ISSUE THREAD

**Issue by ksaj** [xonsh/xonsh#5223]
Hello! I have an idea!

Under bash, zsh, and probably others, if you type "echo $RANDOM" you get a random number. It is a different random number each time it is echoed.

I thought this should be a thing in Xonsh because this post from It's FOSS on Mastodon treats it as a given that "echo $RANDOM" on the (unnamed) CLI will have this effect, but this is not the case for Xonsh.

https://infosec.exchange/deck/@itsfoss@mastodon.social/111277379265186528

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by HLSSLenda** [comment]
@ksaj You can use a `@events.on_pre_prompt` on your `.xonshrc` to emulate `$RANDOM`.
```py
@events.on_pre_prompt
def _():
    import random
    return random.randint(0, 32767)
```
Now you can use `$RANDOM` like you would do in `bash`.
```sh
16:48:50 47% jorge@localhost ~ @ $RANDOM
20034
16:48:51 47% jorge@localhost ~ @
```
