### ISSUE TITLE
xpip fails to correctly install on fedora

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#5229]
```
The following xontribs are enabled but not installed: 
   ['vox', 'autovox', 'avox']
Please make sure that they are installed correctly by checking https://xonsh.github.io/awesome-xontribs/
/usr/lib/python3.12/site-packages/prompt_toolkit/application/application.py:955: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
astraluma@nandi ~ @ which xpip
/usr/bin/python3 -m pip @(['install', '--user'] + $args[1:] if $args and $args[0] == 'install' else $args)
astraluma@nandi ~ @ xontrib list
coreutils  not-loaded
astraluma@nandi ~ @ xpip install xontrib-avox xontrib-vox
Requirement already satisfied: xontrib-avox in ./.local/lib/python3.12/site-packages (0.8)
Requirement already satisfied: xontrib-vox in ./.local/lib/python3.12/site-packages (0.0.1)
Requirement already satisfied: xonsh>=0.12.5 in /usr/lib/python3.12/site-packages (from xontrib-vox) (0.14.1)
astraluma@nandi ~ @ source ~/.xonshrc
The following xontribs are enabled but not installed: 
   ['vox', 'autovox', 'avox']
Please make sure that they are installed correctly by checking https://xonsh.github.io/awesome-xontribs/
astraluma@nandi ~ @ xonsh --version
xonsh/0.14.1
astraluma@nandi ~ @ which xonsh
/usr/bin/xonsh
```

Installed on fedora via dnf

## Expected Behavior
xpip should be able to install packages that are available to xonsh

## Current Behavior
Packages installed by xpip are not available to xonsh

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by tacaswell** [comment]
```
✔ 12:00:43 [yennefer] @ import sys
~ 
✔ 12:01:12 [yennefer] @ sys.path
['/usr/lib64/python312.zip',
 '/usr/lib64/python3.12',
 '/usr/lib64/python3.12/lib-dynload',
 '/usr/lib64/python3.12/site-packages',
 '/usr/lib/python3.12/site-packages']
~ 
✔ 12:01:13 [yennefer] @ python
Python 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib64/python312.zip', '/usr/lib64/python3.12', '/usr/lib64/python3.12/lib-dynload', '/home/tcaswell/.local/lib/python3.12/site-packages', '/usr/lib64/python3.12/site-packages', '/usr/lib/python3.12/site-packages']
>>> 
~ 
✔ 12:03:14 [yennefer] @ sys.executable
'/usr/bin/python3'
~ 

```

I think the problem is that the home-directory `user` path is non it `sys.path` in xonsh.

**Comment by tacaswell** [comment]
Adding this

```python
import sys
from site import getusersitepackages
sys.path.append(getusersitepackages())

```

to the top of my `.xonshrc` fixes the problem.

**Comment by bestlem** [comment]
> I think the problem is that the home-directory `user` path is non it `sys.path` in xonsh.

Is the home-directory `user` path set in that distribution of python?

**Comment by AstraLuma** [comment]
> > xpip was designed to just work--it should always point to the correct environment to install xonsh modules into.
> 
> That's right. PR with fix is welcome!

I no longer remember what the ideal handling of xonsh installation environments is, and it might vary by installation method.

I fixed it for my own zipapp version by making a xonsh-specific site directory--see https://gitlab.com/doyouevenclick/xonsh/-/blob/master/main.py?ref_type=heads

I would much rather a current xore make a design decision in this regard--share a site dir with python? have xonsh manage its own? does that apply if xonsh is installed with pipx or conda?

**Comment by rpdelaney** [comment]
I have eschewed `xpip` in favor of [`pipx`](https://github.com/pypa/pipx):

```console
pipx install xonsh
pipx inject xonsh xontrib-autovox # etc
````

This seems to have solved these problems cleanly without complicating or polluting my environment.

**Comment by AstraLuma** [comment]
> I have eschewed `xpip` in favor of [`pipx`](https://github.com/pypa/pipx):
> 
> ```
> pipx install xonsh
> pipx inject xonsh xontrib-autovox # etc
> ```
> 
> This seems to have solved these problems cleanly without complicating or polluting my environment.

pipx is really excellent if what you're installing is programs to call as commands.

If you're installing xontribs or modules, it's completely the wrong tool.

**Comment by gforsyth** [comment]
I released 0.14.3 which should fix this on Fedora and other systems where `site-packages` isn't necessarily user-writeable

**Comment by rpdelaney** [comment]
@AstraLuma 

> If you're installing xontribs or modules, it's completely the wrong tool.

Can you say more? I have not had any issues so far.

**Comment by AstraLuma** [comment]
> @AstraLuma
> 
> > If you're installing xontribs or modules, it's completely the wrong tool.
> 
> Can you say more? I have not had any issues so far.

oh, I should have read more carefully.

Yes, if you've installed xonsh with pipx, then `pipx inject` will work.

But I installed xonsh via dnf, so `pipx inject` is nonsensical.

`pipx` exists to smooth over these differences and should always work, regardless of installation method.
