### ISSUE TITLE
Bring consistency to `which`

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5265]
I don't like when command returns the unexpected data type:

```xsh
which env
# /opt/homebrew/opt/coreutils/libexec/gnubin/env        # string with path
aliases['env']='echo hello'
which env
# echo hello                                            # string with command
```

Because we intent to make xonsh consistent I would expect:

(the examples moved to details as outdated, [see here instead](https://github.com/xonsh/xonsh/issues/5265#issuecomment-1898286460))

<details>

(1)
```xsh
which env
# {"type":"path", "value":"/opt/homebrew/opt/coreutils/libexec/gnubin/env"}
aliases['env']='echo hello'
which env
# {"type":"alias", "value":"echo hello"}
```
OR (2) - bash like behavior:
```xsh
which env
# /opt/homebrew/opt/coreutils/libexec/gnubin/env
aliases['env']='echo hello'
which env
# Error with return code 1
```
OR (3): by default be (2) and use `--any` to invoke (1).

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
It's just a representative example of using the output of `which` in a capture to create another command

**Comment by gforsyth** [comment]
yeah, that's where you'd want the horrible `@$` operator, so `@$(which vim) world`
(that's a different and longer discussion)

the more likely use case is if you want to `cat` out the contents of a script on your path, then you might do

```
cat $(which scriplet)
```

**Comment by Qyriad** [comment]
I find which for aliases invaluable for commands that run a user-supplied command, e.g. `watch $@(which ls)`

**Comment by bestlem** [comment]
The current default is the correct way around.

My usual case for which is  (eg, `which cmd`)
a) See what cmd is
b) I just ran cmd and it did not do what I expected.

Thus I want which cmd to tell me what cmd is and that includes aliases.

This is all consistent, which tells me what cmd is.

There is a bit more to this. Do xonsh aliases work in non-interactive scripts? If so then the logic is the same and bash logic here is definitely wrong.

**Comment by gforsyth** [comment]
There's GNU `which`, the bash built-in `which`, the zsh built-in `which` and BSD `which` -- these all have different behaviors and take different command line args.

**Comment by bestlem** [comment]
I wish I had not started looking at what I say below, I remembered which not being consistent from 25 years ago but not why. So down a rabbit hole.


which does have history, also look at type and command -V.
The history is a mess and shows which is not that stable. I could not find which on the  POSIX  page so  not a formal definition.

I think some shells aliases which to type -P  - but see later ...

There is also a version that lists all the places a program can be found on the path.
In zsh (and Windows cmd) this is where. In zsh this also lists aliases - zsh also has whence..

type -a seems similar to where (and fails to find xonsh aliases as is an external program)

Also see [SO answer](https://unix.stackexchange.com/a/10529/5140) as to why which is also not reliable.
Note that this suggests that type -P does what anki suggests but the [POSIX definition](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/type.html#tag_20_136) of type is minimal and [Wikipedia](https://en.wikipedia.org/wiki/Type_(Unix)) says type is not part of POSIX.

So there is no good consistent definition of which or type, seems that command -V is defined but that finds aliases.


I do think zsh has it correct. But I am in the simple user category,

However I do agree that for script writers you do need more. So I would suggest writing a Python function with well defined behaviour.
