### ISSUE TITLE
Update website - doc still 0.14.0

### ISSUE THREAD

**Issue by ClausAndersen** [xonsh/xonsh#5279]
This was supposed to be an easy pull request but I found out that it was already done but your deployment is behind.

In https://xon.sh/packages.html there is a small link problem for Windows Terminal at the bottom.

This was fixed more than 6 months ago:
https://github.com/xonsh/xonsh/blame/main/docs/packages.rst

I would kindly suggest getting 0.14.4 docs deployed to the website.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for the ping.  The docs are supposed to update automatically but clearly that's broken.
