### ISSUE TITLE
Please ship tests to pypi

### ISSUE THREAD

**Issue by jlec** [xonsh/xonsh#534]
Downstream maintainers love to test during packaging. Please include the tests into the pypi tarball.

**Comment by scopatz** [comment]
I'd happily accept a PR that implements this.  Excuse my naivete, but why wouldn't the downstream package maintainers use the actual source rather than the pypi package? Again, happy to support this, I just want to understand the use case.

**Comment by scopatz** [comment]
This is for Gentoo, I assume :)

**Comment by jlec** [comment]
> This is for Gentoo, I assume :)

Sure it is. But Fedora, debian and others also take the pypi package and do testing.

**Comment by scopatz** [comment]
OK thanks.  Happy to have this.
