### ISSUE TITLE
Research: Capturing output from interactive tool e.g. `fzf`

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5342]
## Motivation

`fzf` is a common tool to fuzzy search and commonly used to choosing file name. People expect that it works in captured object mode `!()` but this mode was made to capture everything (stdout/stderr) and the people expectations are not satisfied because fzf use stderr to show UI and produces unexpected exceptions. We need to have solid approach of how to operate with this kind of tools and fix exceptions.

## UPD: Instant answer

Use `$()` to operate this this kind of tools. The captured mode operator `!()` only for commands that have no any interaction with terminal.

## Goals

* Catch and fix logic errors and exceptions.
* Fix what is possible to work as expected.
* For the complex cases provide solid way to achieve expected result without errors.

## Test cases

<details>

Pipe (#2404 #2159 #5003 #4444):
```xsh
r1 = $(fzf)
r2 = $(ls / | fzf)  # I'm using `ls` for the test because it allows to catch issues around interactive usage because shows the colors.
r3 = $(ls / | fzf | head)
r1, r2, r3

r1 = !(fzf)
r2 = !(ls / | fzf)
r3 = !(ls / | fzf | head)
r1, r2, r3

r1 = ![fzf]
r2 = ![ls / | fzf]
r3 = ![ls / | fzf | head]
r1, r2, r3

r1 = $[fzf]
r2 = $[ls / | fzf]
r3 = $[ls / | fzf | head]
r1, r2, r3

# TODO: 
# * Alias at the beginning, middle, end.
# * Different type of alias (string, function, ExecAlias, threadable, unthreadable, capturable, uncapturable).
```

Alias:

```xsh
@aliases.register('astd')
def _astd():
    r1 = $(fzf)
    r2 = $(echo 123 | fzf)
    r3 = $(echo 123 | fzf | head)
    r1, r2, r3

@aliases.register('aobj')
def _aobj():
    r1 = !(fzf)
    r2 = !(echo 123 | fzf)
    r3 = !(echo 123 | fzf | head)
    r1, r2, r3

@aliases.register('ahid')
def _ahid():
    r1 = ![fzf]
    r2 = ![echo 123 | fzf]
    r3 = ![echo 123 | fzf | head]
    r1, r2, r3

@aliases.register('aunc')
def _aunc():
    r1 = $[fzf]
    r2 = $[echo 123 | fzf]
    r3 = $[echo 123 | fzf | head]
    r1, r2, r3

# TODO: @unthreadable
```
```xsh
# Alias
aliases['r1'] = "fzf"
aliases['r2'] = "echo 123 | fzf"
aliases['r3'] = "echo 123 | fzf | head"

# ExecAlias
aliases['er1'] = "@('fzf')"
aliases['er2'] = "echo 123 | @('fzf')"
aliases['er3'] = "echo 123 | @('fzf') | head"
```

PTK (#4700):
```xsh
from prompt_toolkit.keys import Keys
@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    @bindings.add(Keys.ControlR)
    def fzf_history(event):
        choice = $(@('fzf'))
# Press Ctrl+R
```

Script mode:
```xsh
echo 'r = !(fzf)' > script.xsh
xonsh --no-rc script.xsh
```

TODO: XonshMode (main.py): single_command, script_from_file, script_from_file, interactive.

</details>

## Docs

See #5444 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
You are doing a great work. As I tried to remove the [threaded subprocs](https://github.com/xonsh/xonsh/pull/4634), most of the code has used threads in some way and needed more time and haven't looked beyond the surface.

**Comment by junegunn** [comment]
@anki-code This might be of your interest. https://github.com/junegunn/fzf/commit/d274d093afa667a6ac5ee34579807de195ade784
