### ISSUE TITLE
Windows: case of commands is incorrectly upper-cased on Windows

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#5469]
## Current Behavior

As reported and investigated in https://github.com/rust-lang/rustup/issues/3848#issuecomment-2143100269, on Windows, it seems that xonsh will transform an executable name to a non-canonical uppercase form before invoking in a subprocess.

```
 ~ # import xonsh.environ as xenv
 ~ # xenv.locate_binary('./rustup-init')
'C:\\Users\\jaraco\\RUSTUP-INIT.EXE'
```

This causes problems when an executable is named `rustup-init` and that executable depends on recognizing its own name to dispatch its behavior but fails when `RUSTUP-INIT.EXE` is what appears in ARG0.

This undesirable upper casing is almost certainly happening in one or more of the Windows-specific `upper()` calls in [commands_cache](https://github.com/xonsh/xonsh/blob/main/xonsh/commands_cache.py).

This mismatch of case led to obscure and annoying problems while attempting to install Rust from xonsh using the recommended install technique.

## Expected Behavior

At the very least, xonsh should not alter the case of the characters typed by the user for the command. If they typed `rustup-init`, then those characters should appear in arg0 of the subprocess.

Even better would be to do what Powershell does and use case-insensitive matching to locate the command, but then use the case of the characters in the filename itself for arg0. That way, if the user types `./RUSTUP-INIT`, the arg0 will be `full\path\to\rustup-init.exe`. For example:

```
 ~ # powershell -c '.\\Print_ARG0.py'
C:\Users\jaraco\print_arg0.py
```

## xonfig

<details>

```xsh
 ~ # xonfig
+------------------+-----------------+
| xonsh            | 0.16.0          |
| Python           | 3.12.2          |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | 3.0.40          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.18.0          |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | True            |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib 1        | vox             |
| xontrib 2        | voxapi          |
| xontrib 3        | jaraco.xonsh    |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jaraco** [comment]
I'll plan to look into it. Can you assign to me?

Also, if you're willing to give me triage permission (or contributor) to the project, I'd be happy to help out and will avoid any controversial changes without proper coordination/approval.

**Comment by gforsyth** [comment]
@jaraco , very happy to have you help out as a contributor. Let me see if this is easy to do from mobile, otherwise i can get to it next week when I'm back in front of a keyboard.

**Comment by gforsyth** [comment]
> @jaraco , very happy to have you help out as a contributor. Let me see if this is easy to do from mobile, otherwise i can get to it next week when I'm back in front of a keyboard.

Hey @jaraco, just following up here that I've invited you to join the org.  Welcome aboard!

**Comment by jaraco** [comment]
I did get and accept the invitation to collaborate on xonsh/xonsh (this repo) and I've since merged a (my own) PR. Is there
