### ISSUE TITLE
Windows: Don't imply PATH=.

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#5476]
In 48dac6e9cdaec8f20d7054aa44213fed6803a462, @byk added a few lines to what is now [found](https://github.com/xonsh/xonsh/blob/6245e460a6841b1bc51382265e4bb9afa8c9ec58/xonsh/commands_cache.py#L281-L286) in the command_cache module:

https://github.com/xonsh/xonsh/blob/6f8f82646e95ab5e626de7cf9b0dbf9717e2b2dd/xonsh/environ.py#L770-L772

It's not even obvious from that commit why the behavior was even relevant to enabling sudo.

In my opinion, `xonsh` shouldn't be adopting platform-specific behaviors from other shells but should instead provide a unified "xonsh" experience across platforms. Additionally, the presence of this platform-specific behavior complicates the implementation and adds cognitive load to maintenance.

And while it's It's true that `cmd.exe` will allow execution of bare executables in the current working directory, that's just a cmd.exe behavior. Powershell, for example, does not have that behavior:

```
PS C:\Users\jaraco> Get-ChildItem -File -Filter "*.exe" | Select-Object -ExpandProperty Name
rustup-init.exe
PS C:\Users\jaraco> rustup-init
rustup-init : The term 'rustup-init' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ rustup-init
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (rustup-init:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command rustup-init was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\rustup-init". See "get-help about_Command_Precedence" for more details.
```

xonsh should drop this legacy divergent behavior and replace it with a unified expectation that matches that of xonsh on other platforms and (incidentally) Powershell.

**Comment by BYK** [comment]
Yeah, those were different times 😅 

I'm happy to drop this behavior, move it to a xontrib or hide behind a configuration. For maintenance, I think the best would be a xontrib if people want it. I certainly don't need or use it for now.

I'll check the sudo implementation to remember what was going on but arguably, that should be in a xontrib too. Thoughts?

**Comment by BYK** [comment]
Just checked the sudo alias and TBH I think it is actually quite confusing if for people who want a unified experience. Don't know why we thought it was a good idea to bake in. I guess we didn't have xontribs back then so we didn't have a better way to share this around?

**Comment by jaraco** [comment]
> I'm happy to drop this behavior, move it to a xontrib or hide behind a configuration.

The linked PR #5477 just removes it. No need to add it to a xontrib - if a xonsh user wants this behavior, they can `$PATH.insert(0, '.')` (on any platform).

**Comment by jaraco** [comment]
Done in cf2f4224.

**Comment by jaraco** [comment]
I was going to say prepend, but I read a stackoverflow on the security of it and the recommend append to avoid masking system commands.

Sent from my comm

On Jun 3, 2024, at 04:55, Andy Kipp ***@***.***> wrote:

﻿

Great read! One question: append or prepend?

**Comment by kbauer** [comment]
Possible regression on this one in xonsh 0.19 or incomplete fix: When executing the "where" and "which" commands (the latter via the "coreutils" xontrib) may report executables in the current directory over the ones specified in $PATH.

Setup:
- Windows 11 with git installation, which includes Git bash.
- Xonsh installed via `pip install xonsh[full]` using Python 3.11.9 (built into Windows).
-  In `.xonshrc`: Move "C:\Windows" to the end to prefer Git bash commands:
    ```
    if $OS == "Windows_NT":
        for _p in list($PATH):
            if _p.startswith($windir):
                $PATH.remove(_p)
                $PATH.append(_p)
    ```

With this, the commands `which` and `where` produce the following outputs

> **C:\WINDOWS\System32 @** which which
> FuncAlias({'name': 'which', 'func': 'which', 'return_what': 'result'})
> 
> **C:\WINDOWS\System32 @** which -a find
> duplicate: C:\WINDOWS\system32\find.EXE (from PATH element 25)
> C:\WINDOWS\System32\find.exe (from current directory)
> C:\Program Files\git\usr\bin\find.exe (from PATH element 17)
> 
> **C:\WINDOWS\System32 @** which where
> C:\WINDOWS\System32\where.exe
> 
> **C:\WINDOWS\System32 @** where find
> C:\Windows\System32\find.exe
> C:\Program Files\Git\usr\bin\find.exe

This would indicate implied `.` in `$PATH`. It does not match the actual behavior however, which gives 

> **C:\WINDOWS\System32 @** find --version | head -2
> find (GNU findutils) 4.9.0
> Copyright (C) 2022 Free Software Foundation, Inc.

i.e. the `find.exe` from git bash is called.
