### ISSUE TITLE
Unintended loading `xonshrc` file in script mode

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5488]
My xonshrc is pretty silent and I suddenly noticed that xonshrc is loaded in script mode:

```xsh
cd /tmp
echo 'echo RC' >> ~/.xonshrc
echo '#!/usr/bin/env xonsh' > myscript
chmod +x myscript

./myscript
# RC

xonsh myscript.xsh
# RC
```

When I run any xonsh script I have no any expectation that my huge `.xonshrc` with features for prompt will be loaded.

Bash/zsh also don't load RC files when you run script:

```xsh
cd /tmp
echo 'echo RC' >> ~/.bashrc
echo 'echo 1' > script.sh
bash script.sh
# 1  # No RC

echo 'echo RC' >> ~/.zshrc
echo 'echo 1' > script.zsh
zsh script.zsh
# 1  # No RC
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
> The user own xonshrc that is mostly for using it in prompt must NOT be loaded in script mode.

I mean, that's the bash approach, but `zsh` and `fish` do load those files in script mode.

A user can run using `--no-rc` to avoid loading their `xonshrc` file

**Comment by gforsyth** [comment]
ah, right, `zsh` does load `zshenv` though -- I don't want to get into having a million special cased startup files, though.

I'm fine with this either way.  If we do disable loading `rc` files in script mode, then we should ensure that a user can force loading them by passing `-i`

**Comment by bestlem** [comment]
> I understand the idea from [here](https://github.com/xonsh/xonsh/issues/4096#issuecomment-792035141) to have this in every xonshrc file:
> 
> ```python
> if $XONSH_INTERACTIVE:
>     # ...
> ```
> 
> It looks clear BUT you forget about software around (e.g. `conda`, `zoxide`, `xonsh wizard`, `xonsh web`, etc) that just do:
> 
> ```python
> echo "some_init_code()" >> ~/.xonshrc
> ```
> 
> And this kind of tools don't know about `$XONSH_INTERACTIVE`. And when they add init code into xonshrc directly ALL scripts will be affected by this and will produce errors and slow timings! This is why I think it's a not so good idea @gforsyth .
> 
> We need more complex behavior. I'm thinking about at least push out `~/.xonshrc` to interactive mode.

This is exactly how fish does it - load the came config.fish in all cases but have test for --is-interactive and --is-login Why is this not an issue for fish?

**Comment by bestlem** [comment]
Looking at my fish config item and fzf look at --is-interactive others don't affect script usage 


In my experience I use my ~/.zshenv,  config.fish etc to enforce a sane set of constant stuff across all my environments. and the PATH and environment variables will differ between Windows / WSL / MacOS/ Solaris /NeXT / Linux and if my machine is in London or Chicago when travelling I don't what to have to make each script I write deal with all those cases when I can with any other shell just change one or two files for each OS.

The environment configuration is not the job of my script.

Actually I have been commenting on SO question that you must understand what each line in your shell config files does. If you don't then leave that line out,


There MUST be a way to run xonsh for scripts loading ~/.xonshrc - if you don't want it then there is --no-rc which you can put in the shebang of your script.

The major problem before was that there was --no-rc but setting XONSH_INTERACTIVE was being done in the wrong place so I think if you loaded a config file ir set it to true in all cases.

**Comment by bestlem** [comment]
And my tools will have to all have -l in their shebang.

Making ~/.xonshrc and ~/.config/xonsrc behave differently is very bad no-one else does that. It is so inconsistent. Scripts will run differently depending on where the config file is and that is unmaintainable.

In my cases xonsh is not installed by the admins so no /etc/xonshrc.

Anyway the same logic applies here as it does for all other shells - load all the config files or none or for posix/csh lot different files wether interactive or login or not but always load both user and system setups. Your suggestions will just suprise everyone.

Why make xonsh behave differently to all other shells?

Can you write bash scripts that have not loaded ~/.profile - In most Unix this has already been read by the login shell - In macOS it can differ. So ~/.xonshrc will have been read anyway as the login shell. So your suggestion will mean that scripts run differently if the login shell is bash or xonsh - in the former ~/.xonshrc will never have been read whilst in the latter it will always have been read.

**Comment by bestlem** [comment]
There are some inconsistencies here.


 But the inconsistencies are that in all cases all the other shells read either both user and files in /etc or neither. ie the behaviour is never not read ~/.xonshrc but read /etc/xonsrc/* 
Add to that you are suggesting that ~/.xonshrc and ~/.config/xonsrc are treated differently - that is just different to anything else and will mean the script depends on where a file is which is unusual.


I note that sh and bash behave differently to zsh and fish in that the former does not read anything but the latter do read some files for scripts.

I also work on Macs and Next  which don't have a login shell. On other Unixes the login shell will already have been read, So I am used to having to get $PATH set by something and I don't want that in the script but something has to be read in e.g. using ~/.xonshrc etc,

**Comment by bestlem** [comment]
The issue is that I need to set $PATH and other environment variables. This is done via Login shell in most Unix or the registry in Windows. In macOS/Next nothing sets it.

As for fish they use the --is-interactive flags to stop inclusion of unneeded stuff.
As for zsh it includes ~/.zshenv
bash is the outlier of the current main shells.

Separation of concerns - the script does not set the environment but the initialisation/login shell does.

**Comment by bestlem** [comment]
Part from the environment issue my main issues here are 

1) We must have --no-rc and the opposite to load rc files in shebangs and -i means run interactively and that is independent of not reading rc files, there need to be a separate flag for the opposite of --no-rc reading the default files.
2) Consistency - I think for most shells the config files in ~ and ~/.config have exactly the same functionality or that only the ons in ~ matter (bash/sh/csh don't understand XDG and zsh needs you  to change ZDOTDIR. I don't think anything else reads both. Different behaviour for xonsh could be confusing. 
3) Consistency - I think all shells read both the ones in home and /etc or they read none. Does xonsh have a reason to do differently.

I can accept the current suggestion but points 2 & 3 have to be documented and The command line  Use ``xonsh -i script.xsh`` to run xonsh in interactive mode is not sufficient. (This is the error we had in the first place interactive means using the keyboard and not just choosing which files to load)
There needs to be a flag to run xonsh scripts reading config files in non-interactive mode,
