### ISSUE TITLE
Macs and Next don't have a login shell

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5496]
_Originally posted by @bestlem in https://github.com/xonsh/xonsh/issues/5488#issuecomment-2162391775_
            

> I also work on Macs and Next  which don't have a login shell. On other Unixes the login shell will already have been read, So I am used to having to get $PATH set by something and I don't want that in the script but something has to be read in e.g. using ~/.xonshrc etc,

**Comment by bestlem** [comment]
macOS does not run in docker

xonsh -i means run setting $XONSH_INTERACTIVE it says nothing about reading startup files.
Running with startup files is a separate concept - how do you run a non-interactive shell loading the default startup files.

This is the same points I made in https://github.com/xonsh/xonsh/issues/4096
