### ISSUE TITLE
problems importing case_insensitive_dict

### ISSUE THREAD

**Issue by sbillinge** [xonsh/xonsh#5627]
## Current Behavior

Traceback (if applicable):

<details>

```xsh
Traceback (most recent call last):
  File "C:\Users\simon\miniconda3\envs\r312\Scripts\regolith", line 2, in <module>
    from regolith.main import main
  File "C:\Users\simon\dev\regolith\src\regolith\__init__.py", line 6, in <module>
    XSH.load(execer=Execer())
  File "C:\Users\simon\miniconda3\envs\r312\Lib\site-packages\xonsh\built_ins.py", line 633, in load
    from xonsh.commands_cache import CommandsCache
  File "C:\Users\simon\miniconda3\envs\r312\Lib\site-packages\xonsh\commands_cache.py", line 27, in <module>
    from case_insensitive_dict import CaseInsensitiveDict as CacheDict
ModuleNotFoundError: No module named 'case_insensitive_dict'
```

I was able to install `case_insensitive_dict` from pip (it wasn't found in conda-forge or conda defaults) but then I still got an import error:

```xsh
$ regolith --version
C:\Users\simon\dev\regolith\src\regolith\version.py:38: UserWarning: Package metadata not found.
  warn("Package metadata not found.")
Traceback (most recent call last):
  File "C:\Users\simon\miniconda3\envs\r312\Scripts\regolith", line 2, in <module>
    from regolith.main import main
  File "C:\Users\simon\dev\regolith\src\regolith\__init__.py", line 14, in <module>
    XSH.load(execer=Execer())
  File "C:\Users\simon\miniconda3\envs\r312\Lib\site-packages\xonsh\built_ins.py", line 633, in load
    from xonsh.commands_cache import CommandsCache
  File "C:\Users\simon\miniconda3\envs\r312\Lib\site-packages\xonsh\commands_cache.py", line 27, in <module>
    from case_insensitive_dict import CaseInsensitiveDict as CacheDict
ImportError: cannot import name 'CaseInsensitiveDict' from 'case_insensitive_dict' (C:\Users\simon\miniconda3\envs\r312\Lib\site-packages\case_insensitive_dict\__init__.py)
```
Any help with this would be appreciated.

</details>

## xonfig

<details>

```xsh
bash: xonfig: command not found
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by sbillinge** [comment]
sorry, some stuff got cut off there in my back and forth.

I recently created a new conda env and got xonsh 0.18.2 py312h2e8e312_0 and got this error.  There was no such error in my previous env (which was also python 3.12 but built some time before)

**Comment by sbillinge** [comment]
Thanks @anki-code .  I tried that and then I got the import error (please see the second stack dump in the post for the full stack dump).
```
    from case_insensitive_dict import CaseInsensitiveDict as CacheDict
ImportError: cannot import name 'CaseInsensitiveDict' from 'case_insensitive_dict' (C:\Users\simon\miniconda3\envs\r312\Lib\site-packages\case_insensitive_dict\__init__.py)```

**Comment by sbillinge** [comment]
@anki-code yes, I can confirm, going back to 0.16.0 cured the problem and allowed it to run.

**Comment by sbillinge** [comment]
I will look into it.  All I know atm is that 0.16.0 it ran, and it gave the error in 0.17.0 and 0.18.0.  But I have a starting point for digging in to it.

**Comment by jnoortheen** [comment]
We can remove this external dependency.

**Comment by sbillinge** [comment]
> Really,
> 
> https://github.com/xonsh/xonsh/blob/31e7c4204ad41368aa0b47c18292f77c823c575b/xonsh/commands_cache.py#L26-L29
> 
> We can remove this completely and replace `CacheDict` to `dict` in the code.
> 
> @sbillinge if you can prepare the PR it will be cool.

Yes, I am happy to do that.  I can do it tonight or tomorrow. Meetings today...:(

**Comment by nova-nowiz** [comment]
Thank you for the temporary fix of using th 0.16.0 release.
It seems that the PR is a bit stuck at the moment, are there some blocking points where I could help out ?
I would love to use the latest version

**Comment by sbillinge** [comment]
> Thank you for the temporary fix of using th 0.16.0 release. It seems that the PR is a bit stuck at the moment, are there some blocking points where I could help out ? I would love to use the latest version

Thanks for the offer of help.  I did run into difficulty with it.  I need to go back and remember what the block was, but some help may be just what is needed....

**Comment by sbillinge** [comment]
One fix maybe just to import `CaseInsensitiveDict` from `requests.structures` when we are on Windows,   The downside is that we lose one dependency, but gain another.   

If we want this functionality in xonch itself, with a bit of help from chatGPT we came p with this code:
```
class CaseInsensitiveDict(dict):
    def __init__(self, *args, **kwargs):
        super().__init__()
        self._store = {}
        self.update(*args, **kwargs)

    def __setitem__(self, key, value):
        # Store the key in lowercase but preserve the original case for display
        self._store[key.lower()] = key
        super().__setitem__(key.lower(), value)

    def __getitem__(self, key):
        return super().__getitem__(key.lower())

    def __delitem__(self, key):
        del self._store[key.lower()]
        super().__delitem__(key.lower())

    def __contains__(self, key):
        return key.lower() in self._store

    def get(self, key, default=None):
        return super().get(key.lower(), default)

    def update(self, *args, **kwargs):
        for k, v in dict(*args, **kwargs).items():
            self[k] = v

    def keys(self):
        # Return the original keys with their original casing
        return (self._store[k] for k in self._store)

    def items(self):
        return ((self._store[k], self[k]) for k in self._store)

    def __repr__(self):
        return f"{self.__class__.__name__}({dict(self.items())})"

    def copy(self):
        return CaseInsensitiveDict(self.items())
```

**Comment by nova-nowiz** [comment]
Woaw, that was fast 👀
Here if you still need help, I did not get if this was a temporary fix or the full solution you wanted to implement in the end
Anyhow, thank you so much @sbillinge ! ❤️

**Comment by sbillinge** [comment]
> Woaw, that was fast 👀 Here if you still need help, I did not get if this was a temporary fix or the full solution you wanted to implement in the end Anyhow, thank you so much @sbillinge ! ❤️

no, that was the full fix in the end.... I just had some time to do it.  It was nagging me that it was sitting unfinished, so this feels good.  And xonsh officially has no required dependencies now, so this won't happen again in the future.....

**Comment by sbillinge** [comment]
it will go out in the next xonsh release.  We pinged the maintainers so hopefully it will be soon.
