### ISSUE TITLE
history all command

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#572]
It would be nice to have a "history all" or "history show --all" command that shows the history from all past and (optionally) concurrent sessions. This behavior would be similar to the way zsh behaves. 

As requested the concurrent updating behavior should not be turned on by default. 

For additional details see the mailing list discussion: https://groups.google.com/forum/#!topic/xonsh/VVIPFQSXitI

**Comment by josefson** [comment]
Zsh shell is really good at working with history, this ability to see other shell instance's history and use it is really handy. But it goes further than that, many zsh users use a fish-like function that perform a substring search in all past history and present from all sessions.
In fact, we are so in use with history functions that it would be really cool if we could somehow import all of our zsh hsitory to xonsh, the same could be said from bash i think. We would not start from point 0. And i think this would improve xonsh adoption once we would have our neat history completion in hands.

**Comment by scopatz** [comment]
Pull requests definitely welcome for that @josefson!

**Comment by JohnLunzer** [comment]
Ha, so hilarious that I opened up two issues for this like 6 months apart. I think I'll close the newer one #952.

I've been working on the "history all", but job work and life has been getting in the way.

I have a python only function that performs history all and I'm pretty happy with it. Part of what I like about it is that it has the option to return a python list with a tuple of (command, command_start_time, history_index).

But when I was converting this function to a "history all" alias I ran into the issue that I think xonsh aliases cannot return a python object? Is this the case? And if it is the case I was thinking about adding a method to the __xonsh__.history object to return the list of all history instead. Does this sound reasonable?

To what @josefson said, I also have made a function to list all Zsh history as well, it would not be difficult to make a "history zsh" or "history bash" alias.

**Comment by scopatz** [comment]
> But when I was converting this function to a "history all" alias I ran into the issue that I think xonsh aliases cannot return a python object? Is this the case?

That is true.  xonsh aliases are like subprocesses.  They can only communicate through stdin, stdout, stderr, and the return code.  We have no notion of a subprocess returning a Python object.  We could potentially consider something like this, but:

1. there are potential security concerns
2. why not just use a Python / xonsh function in python mode?

This is probably off into the weeds a bit ;)

> And if it is the case I was thinking about adding a method to the __xonsh__.history object to return the list of all history instead. Does this sound reasonable?

For the current session, you can simply do `__xonsh_history__.inps[:]`.  For expanding beyond the current sesssion to read all available session files, this could be useful.  I think that the completers must do something like this already...  However, both the readline and ptk completers do this in their own ad hoc way if I recall correctly.

**Comment by JohnLunzer** [comment]
@scopatz, I have no desire to start messing with fundamental xonsh processes, I'm perfectly fine with aliases only returning stdout. I just wanted to get your thoughts on adding a method to `__xonsh_history__`, now that I know you think its an okay idea that is the path forward I will take.

**Comment by scopatz** [comment]
Sounds great @JohnLunzer!

**Comment by matclab** [comment]
In xonsh 0.7.10, `history all` doesn't exist. Did i miss something ?

**Comment by scopatz** [comment]
Yeah, exactly, it is `history show all`.  It would be great to have `history all` point to this command too.  PRs welcome!

**Comment by v3ss0n** [comment]
history show all dosen't show zsh histories or am i missing something?

**Comment by gforsyth** [comment]
`all` shows all xonsh history -- if you want `zsh` or `bash` you need to do `history show zsh`

**Comment by elgow** [comment]
Does this issue need to be re-opened? The `history all` option seems not to exist. 

```
me@my_host ~ @ history all
usage: history [-h] {show,id,file,info,pull,flush,off,on,clear,delete,gc,transfer,diff} ...

history: error: cannot convert 'all' to slice
```

I can find no way to access the history from past sessions.
