### ISSUE TITLE
iTerm2 shell integration with xonsh

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5740]
iTerm2 has shell integration feature - https://iterm2.com/documentation-shell-integration.html

It will be cool to have xonsh.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by bestlem** [comment]
It does https://github.com/jnoortheen/xontrib-term-integrations

Of course not part of xonsh as someone has pushed for bits of xonsh to be made into separate xontribs as has happened here.
