### ISSUE TITLE
Running `.py` files with xonsh code follows to the syntax error

### ISSUE THREAD

**Issue by Hi-Angel** [xonsh/xonsh#5757]
It seems `xonsh` behaves differently depending on whether it's run interactively or not. The same `ls build` works interactively, but results in "Syntax error" if you put it to a script.

Surprisingly, searching similar problems came with nothing, so I'm not sure what this is about. Either way, reporting

# Steps to reproduce *(in terms of terminal commands)*

```bash
λ cat test.py
#!/usr/bin/env xonsh
ls build
λ xonsh --no-rc --no-env test.py
  File "test.py", line 2
    ls build
       ^^^^^
SyntaxError: invalid syntax
```

## Current Behavior

```bash
  File "test.py", line 2
    ls build
       ^^^^^
SyntaxError: invalid syntax
```

## Expected Behavior

`ls` command get executed

## xonfig

<details>

```xsh
zsh: command not found: xonfig
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Hi-Angel** [comment]
I found the reason. It seems, xonsh has its own extension `.xsh`, and somehow it parses the code in a different way, if the extension instead `.py`.

**Comment by Hi-Angel** [comment]
I am kinda confused… Admittedly, I am new to all this, but it would seem like if a person wants pure `.py` file, they would simply run it via `python` and then import `xonsh` modules. OTOH, if a person runs a file via `xonsh`, that implies the file is different from the usual Python, otherwise `xonsh` wouldn't have been called

**Comment by jnoortheen** [comment]
Xonsh runs *.py files with a set of predefined builtins (like __xonsh__), it is not the same as running it with Python binary. But the code inside *.py file is expected to be Python syntax. So for the above code, you could run it as 

```py
__xonsh__.subproc_captured(["ls", "/tmp"]) # or similar. This will run the subprocess with any environment variables in the session. 
```

**Comment by jnoortheen** [comment]
To answer @anki-code 's question, 

`source 1.xsh`  would not compile, since it is expected to have Context free grammar. So it needs to be wrapped in ![ls build] to work. 

As you see, `ls build` is reworked in interactive mode through multiple try/catch of parsing the line with context-free parser. It first tries to parse as ctx-free grammar and falls back to wrapping the line inside `![...]`
