### ISSUE TITLE
make remarkable prompt

### ISSUE THREAD

**Issue by dacoex** [xonsh/xonsh#584]
The program sound great.

But please make the prompt more distinguishable from the normal bash prompt.

Thanks.

**Comment by gforsyth** [comment]
Hey @dacoex -- 

You can customize the prompt however you like to make it distinguishable from whatever your bash prompt looks like.  You can put a variation of the following line in your `xonshrc` (or just enter it into the prompt directly).  The variable `$PROMPT` behaves like `PS1` in Bash.

```
$PROMPT = '{user}@{hostname}:{cwd} <xonsh> '
```

**Comment by asmeurer** [comment]
I've suggested making the default prompt end character 🐚.

**Comment by scopatz** [comment]
> I've suggested making the default prompt end character 🐚

PRs welcome :)

**Comment by melund** [comment]
I tried that once... Couldn't get it working on Windows. Can't rember why exectly. It may be buried in a discussion for another issue.

**Comment by melund** [comment]
Here was the issue were we discussed the problems with unicode characters in xonshrc on windows. https://github.com/scopatz/xonsh/issues/315

**Comment by laerus** [comment]
closing this since the prompt is something that the user must configure and it's best we keep a minimum default for xonsh. Also i don't think it would be wise to include unicode characters since there are still problems with 'wcwidth' for example and not all terminals like these characters anyway.
