### ISSUE TITLE
xonsh distinguish between python and command-line case-sensitivity for tab-completion

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#589]
@scopatz, can't xonsh distinguish between python and command-line case-sensitivity for tab-completion?

https://github.com/scopatz/xonsh/issues/364#issuecomment-168070874

**Comment by scopatz** [comment]
xonsh cannot distinguish between case sensitivity in different modes. Case sensitivity is either on or off, right now. I think this would be a nice feature to have.

**Comment by scopatz** [comment]
Please reopen if desired
