### ISSUE TITLE
--no-rc shouldn't ask about the configuration wizard

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#664]
If you use `--no-rc` it probably means you already have a configuration but don't want to use it for whatever reason. So asking if you want to run the configuration wizard is a bit annoying. 

However, I can see a reason against this if you want to maintain purity that `--no-rc` always is exactly the same as not having an rc file.

**Comment by scopatz** [comment]
> However, I can see a reason against this if you want to maintain purity that --no-rc always is exactly the same as not having an rc file.

That was the idea.  I see `--no-rc` mostly for testing purposes.  But maybe we could also have a `--no-config-wizard` option or something too.

**Comment by gforsyth** [comment]
I don't remember when this happened, but `--no-rc` doesn't prompt for the wizard anymore.
