### ISSUE TITLE
conda virtual env support in vox

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#679]
Right now, vox only supports venv.  Conda support would be great to have too.

**Comment by gforsyth** [comment]
Surely you mean `xonda`?

**Comment by scopatz** [comment]
Now that you mention it, yes :)

**Comment by gforsyth** [comment]
Hey @scopatz -- I'm going to close this out since `xonda` seems to fill this niche, but if there's extra functionality we want we can open a new issue for it.

Yay for clearing out the backlog?

**Comment by scopatz** [comment]
Sounds great!  

> Yay for clearing out the backlog?

Here, here!
