### ISSUE TITLE
built-in ssh support

### ISSUE THREAD

**Issue by tmbdev** [xonsh/xonsh#685]
It would be convenient to have built-in ssh server support in xonsh, perhaps via consh, so that a Python installation is all that's needed to ssh into a system.

**Comment by scopatz** [comment]
I agree! I think that this is related to #655.  Pull requests very welcome.

**Comment by scopatz** [comment]
Also, if anyone needs help implementing this, please pipe up!

**Comment by BYK** [comment]
Welp, then I also want Mosh support! :D

**Comment by scopatz** [comment]
Haha @BYK - PRs very welcome :)

**Comment by scopatz** [comment]
This should probably be a xontrib at this point.  This could even be in the xonsh xontribs if we wanted.
