### ISSUE TITLE
Is there a problem of importing modules from local dir?

### ISSUE THREAD

**Issue by guy-do-or-die** [xonsh/xonsh#731]
Have just stared using xonsh and am wondering how can I import modules from current dir if possible at all? For now I'm only getting ImportError. Thanks in advance.

**Comment by scopatz** [comment]
@guy-do-or-die, You might need to check `sys.path` to see if the current directory or an empty string is in this list. As long as you can import other modules, this is a Python thing.

**Comment by scopatz** [comment]
Thanks for asking, @guy-do-or-die!

**Comment by guy-do-or-die** [comment]
@scopatz, thanks for the answer. i've added the expanding sys.path with '.' to .xonshrc file which i created in my home directory, but now virtualenv is not working properly )

**Comment by scopatz** [comment]
I think that you might have something else going on then: http://stackoverflow.com/questions/29528954/virtualenv-using-incorrect-sys-path

**Comment by guy-do-or-die** [comment]
@scopatz i just thought that i would be able to import modules which are dependent on libs from env, but it seems not the case...

**Comment by gforsyth** [comment]
I'm closing this as I believe it's addressed in the docs now, see https://xonsh.github.io/xonsh-docs/dev/customization.html#import-python-modules-from-a-local-directory
