### ISSUE TITLE
Pygments coding for  ${...}.swap() is broken

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#774]
Coloring of `${...}.swap()` see

![image](https://cloud.githubusercontent.com/assets/1038978/14206841/43150048-f816-11e5-9fe7-8e12c7900dcb.png)

Without `.swap()` it works fine: 
![image](https://cloud.githubusercontent.com/assets/1038978/14206853/581bfea6-f816-11e5-92c9-2bb2b0a99120.png)

I can't figure what to change in the pygments style to make this work: 
https://github.com/scopatz/xonsh/blob/master/xonsh/pyghooks.py

Anyone?

**Comment by scopatz** [comment]
Yeah, I have noticed this in other cases too, but have never dived in deep enough to figure out what was wrong :)

**Comment by gforsyth** [comment]
Fixed in #1711 !
