### ISSUE TITLE
~/anaconda/bin/emacsclient -a emacs-server-start -nw —socket-name=$TTY wants line completion

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#778]
```
🐚 ~/anaconda/bin/emacsclient -a emacs-server-start -nw --socket-name=${'TTY'}
........................
  File "<string>", line None
SyntaxError: <xonsh-code>:1:1: ('code: /',)
```

Note that I have an alias defined relating to this https://github.com/asmeurer/dotfiles/blob/0e1f5f541d69f9281957c0e4a3e63025943002c0/.xonshrc#L188. 

It does the same thing if I use just `--socket-name=$TTY`, but if I use `--socket-name="$TTY"` it works. 

It does it in both prompt-toolkit and readline mode.

**Comment by asmeurer** [comment]
Dupe of https://github.com/scopatz/xonsh/issues/622

**Comment by gforsyth** [comment]
@asmeurer, is this still an issue on your machine?  I can't reproduce it anymore

**Comment by asmeurer** [comment]
Looks like it is fixed. Still having issues actually starting emacsclient with that command (I forgot what we determined the reason for that was), but it doesn't line continue.

**Comment by asmeurer** [comment]
Although, this seems to imply that the newline is being added to the argv:

```
~/anaconda/bin/emacsclient -a emacs-server-start -nw —socket-name $TTY
/Users/aaronmeurer/anaconda/bin/emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
Warning: Unknown defun property `interactive-only' in flycheck-disable-checker
Warning: Unknown defun property `interactive-only' in flycheck-set-checker-executable
../../../fuzzy-el/fuzzy.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
../../../fuzzy-el/fuzzy.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
../../../fuzzy-el/fuzzy.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
ad-handle-definition: `isearch-message-prefix' got redefined
ad-handle-definition: `isearch-search' got redefined
Loading cua-base...
Loading cua-base...done
Loading delsel...
Loading delsel...done
Loading desktop...
Loading desktop...done
Loading linum...
Loading linum...done
Loading subword...
Loading subword...done
Loading undo-tree...
Loading undo-tree...done
Loading paren...
Loading paren...done
Failed to enable theme: 1am
Starting new Ispell process hunspell with default dictionary...
Starting Emacs daemon.
Unable to start daemon: Emacs server named "ttys006

" already running
Wrote /Users/aaronmeurer/.emacs.d/ac-comphist.dat
Wrote /Users/aaronmeurer/.emacs.d/places
Saving file /Users/aaronmeurer/.emacs.d/ido.last...
Wrote /Users/aaronmeurer/.emacs.d/ido.last
Error: server did not start correctly
```

**Comment by asmeurer** [comment]
OK, the command in the OP, `~/anaconda/bin/emacsclient -a emacs-server-start -nw --socket-name=${'TTY'}` does want a newline, and then gives a syntax error. Is there a syntax error there?

**Comment by gforsyth** [comment]
Not that I see.  I can duplicate the error with the `${'TTY'}` socket name and xonsh is pointing to the `e` in `emacs-server-start` as the culprit, which leads me to believe there's a parser error somewhere in here.  Tricky, too, since everything left of the `=` is valid Python

**Comment by scopatz** [comment]
The version with `~/anaconda/bin/emacsclient -a emacs-server-start -nw --socket-name=$TTY` seems to now be interpreted correctly. Is this closable?

**Comment by scopatz** [comment]
Please feel free to reopen, if needed.
