### ISSUE TITLE
Problem with sdtout and stderr redirection on windows 

### ISSUE THREAD

**Issue by michelepagot** [xonsh/xonsh#787]
```
User@User-PC ~ $ ping err>dir.log

  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: err',)
User@User-PC ~ $ ping out>dir.log

  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: out',)

User@User-PC ~ $ exit

Terminare il processo batch (S/N)? S

C:\Users\User>xonsh --version
('xonsh/0.2.6',)
```

**Comment by scopatz** [comment]
Thanks for reporting @michelepagot.  Currently only `out> dir.log` (note the space) works.  The redirection stuff needs to be worked on.

**Comment by TobalJackson** [comment]
Not sure if this belongs here, but it seems related.

<pre>tobaljackson@b14ckb0x [16:16:57] [~/tmp/xonsh_test]  
-> % a  
'0\n1\n2\n3\n4\n5\n6\n7\n8\n9'  
tobaljackson@b14ckb0x [16:17:23] [~/tmp/xonsh_test]  
-> % echo a  
a  
tobaljackson@b14ckb0x [16:17:31] [~/tmp/xonsh_test]  
-> % echo @(a)  
0  
1  
2  
3  
4  
5  
6  
7  
8  
9  
tobaljackson@b14ckb0x [16:17:34] [~/tmp/xonsh_test]  
-> % echo @(a) > ./tmp.txt  
....   
  File "<string>", line None  
SyntaxError: <xonsh-code>:1:5: ('code: @(',)  
</pre>
I can't seem to get output redirection working at all when there is python code in the mix (evaluated with `@()`)

**Comment by gforsyth** [comment]
Hey @TobalJackson -- are you on current master?  I believe this was fixed in #842.

**Comment by TobalJackson** [comment]
I actually just updated to current as well as most recent prompt_toolkit, and one of the two fixed this issue I was having.

**Comment by scopatz** [comment]
Hi @TobalJackson - What is the one that remains?

**Comment by TobalJackson** [comment]
Hi @scopatz, I meant that one of the two actions I took (updating to current master as well as most recent prompt_toolkit) fixed the issue I was having!

**Comment by scopatz** [comment]
Ahh great!
