### ISSUE TITLE
Pasting multiple lines should switch to multiline mode

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#806]
When pasting multiple lines (stuff with `\n` in) xonsh should switch to multiline mode. Similar to what IPyhton's QT console does. 

Currently, only the string before the newline is pasted, the rest is discarded. Also, the newline causes the line to run which can be dangerous when pasting from the web.

**Comment by gforsyth** [comment]
Hey @melund -- is this on the prompt_toolkit or the readline shell?  I'm not observing the behavior you describe in the pt shell.

**Comment by melund** [comment]
I am on prompt-toolkit somewhere between 0.60 and the current master. I also recall the behaviour was a little different 0.60.

**Comment by melund** [comment]
Well. I get the behaviour I described on both prompt_toolkit 0.6 and master.
```
$ xonfig
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 0.60  |
| pygments         | 2.1.3 |
| on posix         | False |
| on linux         | False |
| on arch          | False |
| on windows       | True  |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by melund** [comment]
@gforsyth I better add that I have been using cmd.exe on windows

**Comment by gforsyth** [comment]
Huh... does the same thing happen with conemu?  

The prompt_toolkit shell is always in multiline mode -- we just overload the Enter key to either add extra lines or send the command, whichever is appropriate, so there shouldn't be a "switch" required.  A windows machine has randomly appeared in my office, so I'll try to see if I can reproduce on that.

**Comment by melund** [comment]
No. I get a behaviour which is much more weird in ConEmu. 

If I right-click to paste (similar to what I do with cmd.exe), then I first get a dialog asking if I want to paste stuff with ´\n´ in. Next, the first line is executed (this is similar to cmd.exe). Then, some part of the last line (of the 4 lines in the clipboard) is partially pasted. How much of the last line it pastes varies.

![image](https://cloud.githubusercontent.com/assets/1038978/14795586/6a46fcb8-0b29-11e6-912d-a9eb2b23e43d.png)

![image](https://cloud.githubusercontent.com/assets/1038978/14795810/72805a72-0b2a-11e6-90de-8add1b9a5d7d.png)

If I press ´Ctrl-V´ to paste instead, then all the lines are pasted as one concatenated string....

![image](https://cloud.githubusercontent.com/assets/1038978/14795965/317c0ed0-0b2b-11e6-94e0-310438af0f77.png)

**Comment by melund** [comment]
It really should work as it does in Jupyter QT console:
![image](https://cloud.githubusercontent.com/assets/1038978/14797512/699c9b2e-0b33-11e6-96cb-ac9c12e4e51d.png)

**Comment by gforsyth** [comment]
Yikes.  Agreed that it should work as it does in the QT console.  
If you have a little time, @melund, can you try out current master on [ipython dev](https://github.com/ipython/ipython) and see if the same issue occurs?  They're also switching to a prompt_toolkit backend.

**Comment by scopatz** [comment]
This is very strange, @melund.  Thanks for reporting. I haven't noticed this behaviour on either ptk or readline.  This might not be something that we can 100% handle from our end since it is the terminal emulator that is dealing with the copy/paste semantics. Does pasting multiple line on in cmder into bash or cmd.exe work? Or does it remove the newlines there too?

**Comment by BYK** [comment]
I'll look into this when I am near my Windows machine again. The dialog is something ConEmu and cmder does and can be turned off. I believe this is just some tweaking around those settings.

**Comment by scopatz** [comment]
Thanks @BYK!

**Comment by melund** [comment]
Yes. The dialog and the difference between right-click and 'ctrl-v' is due to settings in ConEmu. @gforsyth I will look at how it works in ipython master

**Comment by melund** [comment]
@gforsyth 
On IPython master things are also really weird.
I am pasting the following lines
```
s1 = 'Hallo'
s2 = 'World'
print(s1+s2)
```

![image](https://cloud.githubusercontent.com/assets/1038978/14830891/5c33b01a-0bf3-11e6-9502-e786d65bf071.png)

As you can see it concatenates the two first lines, and drops all after the last newline. The behaviour in xonsh is exactly the same. 

![image](https://cloud.githubusercontent.com/assets/1038978/14831705/2d4df446-0bf7-11e6-91a0-73480d2fb8b3.png)

I also tried pasting something which opens newline mode:

```
for i in range(3):
    i += 1
    print(i)
```

![image](https://cloud.githubusercontent.com/assets/1038978/14831586/ad9d6b64-0bf6-11e6-8959-6ceacfb94007.png)

![image](https://cloud.githubusercontent.com/assets/1038978/14831675/100ab676-0bf7-11e6-8f9c-4b54e1b64ac4.png)

**Comment by mitnk** [comment]
+1 for this feature.

When writing git commit message, we sometime need to type into multiple messages for good. But this is break in xonsh when hit Enter.

```
$ git commit -am 'Fixed issue xxx - <hit RETURN key>
fatal: Paths with -a does not make sense.
$
```

**Comment by melund** [comment]
Ohh. We should be able to do `shift-enter` to open multi-line mode

**Comment by mitnk** [comment]
@melund what do you mean, I hit `shift+enter` after `git ci -am 'foo bar`, still got the fatal error. 

And I find more interesting fact:

`git ci -am 'foo` - this works, and made a commit with msg `'foo` 
`git ci -am 'foo bar` - this raise the fatal error

In both cases, I want to added some more multiple line messages.

**Comment by melund** [comment]
Sorry for not being clear. It is not a feature we have but something I think we ought to have.

**Comment by gforsyth** [comment]
Hmmm, so I added in Alt-Enter support to insert a newline and it doesn't work very well.  git still expects to see a "short message" on a single line.

**Comment by melund** [comment]
Hmm. Ok. But would it not be a nice feature to have a short-key to open multi-line mode. I was just thinking it should be Shift-Enter. Similar to what it is in most messenger apps.

**Comment by gforsyth** [comment]
I'm happy to put it in -- the PTK prompt is always in multiline mode by default, but this would let people force carriage returns to enter multiple commands in one prompt.

**Comment by melund** [comment]
I think that would be nice to have :)

**Comment by gforsyth** [comment]
Ok -- for reasons involving cross-platform gobbledegook, Shift+Enter is not so easy.  

Can I interest you in Ctrl+Enter or Alt-Enter or some other combination?

**Comment by melund** [comment]
He he. Then let us hear what the others prefer :)

**Comment by scopatz** [comment]
Hi All, On PTK this works as expected for me.  Would you mind updating your ptk to 1.0.0?  I believe that these is a conda package already

**Comment by scopatz** [comment]
I am not sure that this remains an issue.

**Comment by mitnk** [comment]
@scopatz tried prompt_toolkit 1.0.0 as the shell type on OS X and Debian, still got error for me:

```
$ git ci -am 'foo -
fatal: Paths with -a does not make sense.
```

**Comment by mitnk** [comment]
Sorry, this issue seems talking about `pasting multilines`, I open a new issue for git issue here: #1152

**Comment by melund** [comment]
This is fixed on master :)
