### ISSUE TITLE
Show Incoming/Outgoing Changesets in Prompt

### ISSUE THREAD

**Issue by Siecje** [xonsh/xonsh#811]
Show if the default remote repo has additional changes in the prompt.

And show if the local repo has additional changes missing from the remote repo in the prompt.

**Comment by melund** [comment]
Great idea. Do you have any opinion on how the command prompt should look in either case? This also something which you could try implement yourself directly in your `.xonshrc` file. Here is, for example, a snippet from my `.xonshrc` file which makes the branch a little more fancy if I launch xonsh in ConEmu: 

``` python
from xonsh.environ import current_branch
have_conemu = 'CONEMUBUILD' in ${...}
def _fancy_branch():
    b = current_branch(pad=False)
    label = ''
    if b:
        if have_conemu:
            label = '\uE0A0' + b + '{NO_COLOR}'
        else:
            label = '(' + b + ')'
    return label

$FORMATTER_DICT['curr_branch'] = _fancy_branch
del _fancy_branch
```

If you do come up with something cool a PR is very welcome..

**Comment by Siecje** [comment]
I primarily use Mercurial so this is what I came up with.
It uses the [hg-prompt](https://bitbucket.org/sjl/hg-prompt/src) Mercurial extension.
The terminal is noticeably slower.
I'm putting this here for feedback on the speed and as a reference.

```~/.xonshrc``` file.
```Python

import os
from functools import lru_cache
from xonsh.environ import current_branch

@lru_cache(maxsize=32)
def _inside_hg():
    """Check if pwd is inside an hg repo"""
    ret = !(hg root)
    return ret.returncode == 0

#@lru_cache(maxsize=32)
#def _inside_hg():
#    """ Find an hg directory above $PWD
#    without calling `hg root` because that's too slow
#    """
#    root = ""
#    dir = $PWD
#    while dir != '':
#        if os.path.isfile(os.path.join(dir, '.hg', 'dirstate')):
#            root = os.path.join(dir, '.hg')
#            break
#        # Go up one directory
#        dir = '/'.join(dir.split('/')[:-1])
#
#    if root:
#        return True


def _fancy_branch():
    # Remove branch from hg repo
    b = current_branch(pad=False)
    if b:
        b = ' ' + b.split(',')[-1].strip()

    if _inside_hg():
        # Add hg incoming and outgoing to prompt
        outgoing = $(hg prompt '{outgoing|count}')
        incoming = $(hg prompt '{incoming|count}')
        if outgoing or incoming:
            inOut = ' ('
            if outgoing:
                inOut += outgoing + '↑'
            if incoming:
                inOut += incoming + '↓'
            inOut += ')'
            b += inOut
    return b 

$FORMATTER_DICT['curr_branch'] = _fancy_branch
del _fancy_branch
```

**Comment by melund** [comment]
Hi @Siecje .. I think you should have a look at how the current hg stuff is implemented in xonsh. https://github.com/scopatz/xonsh/blob/master/xonsh/environ.py#L878 

I think it also uses the os.path approach to figure if it is in a 'hg' repo. What is the bottleneck in your code? Does it connect to the remote server every time it runs.

**Comment by scopatz** [comment]
Cool idea!  Can you test if your function is being called each keypress or whether it is on each new prompt @Siecje?

**Comment by Siecje** [comment]
@melund Thanks! Pretty sweet that I can just import functions from that module.

Here is my ```.xonshrc``` file. One problem is that after you commit it would be nice to invalidate the cache. Is it possible to create a wrapper for hg commands?

```Python
from functools import lru_cache
import os
import time
from xonsh.environ import call_hg_command, current_branch, ensure_hg


UPDATE_FREQ = 16 * 60 # 16 minutes
# The hg prompt cache lasts for 15 minutes so no point in checking
# It is slow to call hg prompt


# Will contain a dict for each hg repo visited in the terminal
Repos = {}


def in_and_out(root, cwd):
    global Repos
    if root in Repos and time.time() - Repos[root]['time'] < UPDATE_FREQ:
        return Repos[root]['value']

    outgoing = $(hg prompt '{outgoing|count}')
    incoming = $(hg prompt '{incoming|count}')
    #outgoing = call_hg_command(["prompt", "'{outgoing|count}'"], cwd)
    #incoming = call_hg_command(["prompt", "'{incoming|count}'"], cwd)
    inOut = ''
    if outgoing or incoming:
        inOut += ' ('
        if outgoing:
            inOut += outgoing + '↑'
        if incoming:
            inOut += incoming + '↓'
        inOut += ')'
    Repos[root] = {'time': time.time(), 'value': inOut}
    return inOut

@lru_cache(maxsize=32)
def _inside_hg(dir):
    """ Find an hg directory above $PWD
    without calling `hg root` because that's too slow
    """
    root = ""
    while dir != '':
        if os.path.isfile(os.path.join(dir, '.hg', 'dirstate')):
            root = os.path.join(dir, '.hg')
            break
        # Go up one directory
        dir = '/'.join(dir.split('/')[:-1])

    if root:
        return True, root
    return False, None

#@ensure_hg # blah with the decorator, git branches don't work.
def _fancy_branch():
    b = current_branch(pad=False)
    cwd = $PWD
    found, root = _inside_hg(cwd)

    if found:
        # Remove branch from hg repo
        if b:
            b = ' ' + b.split(',')[-1].strip()

        # Add hg incoming and outgoing to prompt
        b += in_and_out(root, cwd)
    return b

$FORMATTER_DICT['curr_branch'] = _fancy_branch
del _fancy_branch
```

**Comment by scopatz** [comment]
>  Is it possible to create a wrapper for hg commands?

Yep, you should be able to just dump them into `aliases`

**Comment by Siecje** [comment]
I can make a python function that you can call with hg() but not with hg
commit etc

**Comment by scopatz** [comment]
Oh ok, I don't know how hg does it's hooks.  I know that git and conda work by looking up subcommands via git-commit or something.

Currently, xonsh only matches aliases on the first token, ie the command name.  This could certainly be extended. Do you want to take a stab at this? Or should we add it as an issue?

**Comment by Siecje** [comment]
How do you make a shell command in xonsh without requiring brackets? Like
git isn't git()

**Comment by scopatz** [comment]
You can have python functions that you then add to the aliases dict: http://xon.sh/tutorial.html#aliases Then you can just use these functions exactly like you would use an external command in any subproc mode.  For example,

```console
$ aliases['banana'] = lambda args, stdin=None: ('My spoon is tooo big!\n', None)
$ banana
My spoon is tooo big!
scopatz@localhost ~ $ x = $(banana)
scopatz@localhost ~ $ x
'My spoon is tooo big!\n'
```

**Comment by Siecje** [comment]
Thanks! That makes sense. Now I can wrap ```hg``` and remove the cache when you commit, pull, or push.

**Comment by scopatz** [comment]
np :)

**Comment by gforsyth** [comment]
Closing due to age, please ping if you are interested in taking this on!
