### ISSUE TITLE
`$()` appending new line at end of command?

### ISSUE THREAD

**Issue by Carreau** [xonsh/xonsh#815]
I was just trying to do `ls $(jupyter --runtime-dir)/kernels` which prompt me for a new line. 

```
(rootenv)~$ ls $(jupyter --data-dir)/kernel
...........
```
Which feel weird, could it be due to `$()` appending a new line at the end of expression?

```
(rootenv)~$ $(jupyter --data-dir)
'/Users/bussonniermatthias/Library/Jupyter\n'
```

So is the `\n` and end of output intentional ?  I would understand for `$(something)/something_else` to not work, but I'm still wondering.

**Comment by scopatz** [comment]
I don't think that this is the `$()` appending a newline.  I think it is jupyter that is adding the newline.  For example:

```console
scopatz@localhost ~ $ aliases['x'] = lambda args, stdin=None: "wakka  ->"
scopatz@localhost ~ $ x
wakka  ->scopatz@localhost ~ $ 
scopatz@localhost ~ $ $(x)
'wakka  ->'
# or with echo
scopatz@localhost ~ $ $(echo -n "yo")
'yo'
scopatz@localhost ~ $ $(echo "yo")
'yo\n'
```

**Comment by scopatz** [comment]
I believe that this has been resolved with the `@$(..)` operator.  Closing, but please feel free to reopen.
