### ISSUE TITLE
Explain about different shell types and vi-mode in tutorial

### ISSUE THREAD

**Issue by abspoel** [xonsh/xonsh#834]
I just installed xonsh, and it looks like a really good candidate to replace zsh as my main shell. One issue I ran into: I'm really fond of zsh's vi-mode key mappings. Now, I found out that xonsh has a VI_MODE option that's supposed to enable this, but however much I set that and pressed ESC, it was not working.

Eventually, I found out xonsh supports both readline and prompt_toolkit as shells (set with the `--shell-type` command line argument), but since I didn't have prompt_toolkit installed it defaulted to readline. Installing prompt_toolkit fixed the problem.

I'm mainly writing this for other users running into the same problem, and to suggest perhaps the different shell types could be explained in the documentation, as well as the VI_MODE feature. Also maybe a warning if VI_MODE is True and readline is not installed, or perhaps supporting readline's vi-mode.

**Comment by gforsyth** [comment]
Hey @abspoel -- thanks for letting us know!  We can definitely use some more work on the docs (PRs welcome!).  And we can definitely throw a warning if a user has `prompt_toolkit` specific options in their `xonshrc` but is using the `readline` shell.

**Comment by gforsyth** [comment]
Closing in favor of general documentation meta issue #2315
