### ISSUE TITLE
Performance issues with default prompt on Windows

### ISSUE THREAD

**Issue by Will-W** [xonsh/xonsh#849]
I've just set up Xonsh (from master) on Windows. 
On first load up, the first thing I did was hit enter a couple of times, which had a very poor performance loading the next line of prompt (several hundred milliseconds, I'd estimate). It made a poor first impression.

The default prompt is:
'{env_name}{BOLD_INTENSE_GREEN}{user}@{hostname}{BOLD_INTENSE_CYAN} {cwd}{branch_color}{curr_branch}{NO_COLOR} {BOLD_INTENSE_CYAN}{prompt_end}{NO_COLOR} '

After a little digging, it turns out to be the branch_color function that's causing the slowdown (curr_branch is fine). I have git and mercurial installed, and the performance issue is the same whether the working dir is in a repo or not.

**Comment by Will-W** [comment]
For reference - this is a relatively fast machine (Quadcore 2.7Ghz i7, SSD).

**Comment by melund** [comment]
I don't have a feeling of it beeing slow on windows. What is the ouptut of running `xonfig`?

**Comment by melund** [comment]
Can you try to run the following lines?
```
mel@xonsh_dev ~
$ timeit.repeat('current_branch()',setup='from xonsh.environ import current_branch', number=1)
[0.04200691358022368, 0.04197688888888251, 0.03884483950616868]
mel@xonsh_dev  ~
$ import timeit
mel@xonsh_dev  ~
$ timeit.repeat('current_branch()',setup='from xonsh.environ import current_branch', number=1)
[0.044014617283949065, 0.0399265185184845, 0.051671308641971336]
mel@xonsh_dev  ~
$ timeit.repeat('hg_dirty_working_directory()',setup='from xonsh.environ import hg_dirty_working_directory', number=1)
[0.02125866666665388, 0.02629491358021596, 0.022464790123422063]
mel@xonsh_dev  ~
$ timeit.repeat('git_dirty_working_directory()',setup='from xonsh.environ import git_dirty_working_directory', number=1)
[0.04103940740736789, 0.03377461728399567, 0.03384335802468286]
```

**Comment by Will-W** [comment]
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | False |
| prompt toolkit   | 1.0.0 |
| pygments         | 2.1.3 |
| on posix         | False |
| on linux         | False |
| on arch          | False |
| on windows       | True  |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+


WW@L1 ~ $ import timeit
WW@L1 ~ $ timeit.repeat('current_branch()',setup='from xonsh.environ import current_branch', number=1)
[0.03439650088090218, 0.03394793459389689, 0.033975498010526906]
WW@L1 ~ $ timeit.repeat('hg_dirty_working_directory()',setup='from xonsh.environ import hg_dirty_working_directory', number=1)
[0.016859749029428883, 0.016377955610060724, 0.016773282969055003]
WW@L1 ~ $ timeit.repeat('git_dirty_working_directory()',setup='from xonsh.environ import git_dirty_working_directory', number=1)
[0.4116819045792255, 0.41021009364765604, 0.4097411379839784]

**Comment by melund** [comment]
`git_dirty_working_directory` is 10 times slower on your computer :(

**Comment by melund** [comment]
Weird. What version of git are you using?

**Comment by melund** [comment]
Are you running in Cmder/ConEmu or cmd.exe? If you are can you try cmd.exe as well?

**Comment by Will-W** [comment]
Even doing:

`timeit.repeat('subprocess.call(["git", "--version"])', setup='import subprocess', number=1)`

Gets 0.4s (via xonsh, and via cmd). There's clearly something funny in my setup. I'll dig into it.

**Comment by melund** [comment]
I am on:  
```
mel@sea C:\Users $ git --version
git version 2.8.1.windows.1
```

**Comment by melund** [comment]
Let us know what you come up with :)

**Comment by Will-W** [comment]
For the record I was on "git version 2.7.4.windows.1". I'm upgrading now to see if that makes a difference.

**Comment by Will-W** [comment]
At this point I have a strong suspicion that it relates to the virus scanner that work have installed, but it's difficult to verify.

Either way, it looks like it's outside the scope of Xonch.

**Comment by adqm** [comment]
It's also true that that check depends on the size of the repository, the speed of the hard disk, etc.

I had to remove all of the checks about the current working copy being clean from my prompt because most of the Git/Hg repos I work with are humongous and the check took a long time.

**Comment by melund** [comment]
@Will-W You also saw it outside git repos right?

**Comment by Will-W** [comment]
Yes. I was seeing it in and outside repos, and even on 'git --version' which doesn't query anything. There's something slowing down simple launching of the process.

**Comment by scopatz** [comment]
Hi All, It seems like the right thing to do would be to have a timeout on the subprocess calls that determine the branch name (10 - 100 ms?). Just pass the `timeout` kwarg into the subproc call.  Maybe this could even be controlled by an envvar `$XONSH_BRANCH_TIMEOUT`.  If the timeout is reached, then some default string would be used (`<branch-timeout>`).

**Comment by scopatz** [comment]
Anyone want to take a stab at this?

**Comment by melund** [comment]
I don't mind but it is a good place to help out for new people

**Comment by scopatz** [comment]
> I don't mind but it is a good place to help out for new people

I agree. (nudge nudeg @Will-W ~_~).  All the relevant code should be in `xonsh/environ.py`

**Comment by gforsyth** [comment]
This was implemented somewhere along the way.  `$VC_BRANCH_TIMEOUT` sets the time to wait on a git branch before timing out.
