### ISSUE TITLE
PROMPT_TOOLKIT_COLORS setting seems to have no effect

### ISSUE THREAD

**Issue by TobalJackson** [xonsh/xonsh#854]
Hello,

It seems that when trying to set/change the PROMPT_TOOLKIT_COLORS environment variable to change how keywords are highlighted on the prompt, the settings have no effect.  The following is an example of what my prompt coloring looks like:

![](https://i.imgur.com/gDcpX7J.png)

As you can see, the Blue color set for highlighting environment variable-like strings is hard to see, and I'd like to change it.

referring to the documentation, it seems that the PROMPT_TOOLKIT_COLORS functions by referring to the 'color names' that PT uses, which I found here: 
https://github.com/jonathanslenders/python-prompt-toolkit/blob/08005800b477b77f30b6c66e41ac6af26760e999/prompt_toolkit/styles/base.py#L39

These are the only color names I could find.  So I set the environment variable to each of the following values with no effect on the colorization of environment variable-strings ($SOMETHING):

{'black': (0xf2, 0x4a, 0x82), 'white': (0xf2, 0x4a, 0x82), 'default': (0xf2, 0x4a, 0x82), 'red': (0xf2, 0x4a, 0x82), 'green': (0xf2, 0x4a, 0x82), 'yellow': (0xf2, 0x4a, 0x82), 'blue': (0xf2, 0x4a, 0x82), 'fuchsia': (0xf2, 0x4a, 0x82), 'turquoise': (0xf2, 0x4a, 0x82), 'lightgray': (0xf2, 0x4a, 0x82), 'darkgray': (0xf2, 0x4a, 0x82), 'darkred': (0xf2, 0x4a, 0x82), 'darkgreen': (0xf2, 0x4a, 0x82), 'brown': (0xf2, 0x4a, 0x82), 'darkblue': (0xf2, 0x4a, 0x82), 'purple': (0xf2, 0x4a, 0x82), 'teal': (0xf2, 0x4a, 0x82)}

{'ansiblack': 'f24a82', 'ansiwhite': 'f24a82', 'ansidefault': 'f24a82', 'ansired': 'f24a82', 'ansigreen': 'f24a82', 'ansiyellow': 'f24a82', 'ansiblue': 'f24a82', 'ansifuchsia': 'f24a82', 'ansiturquoise': 'f24a82', 'ansilightgray': 'f24a82', 'ansidarkgray': 'f24a82', 'ansidarkred': 'f24a82', 'ansidarkgreen': 'f24a82', 'ansibrown': 'f24a82', 'ansidarkblue': 'f24a82', 'ansipurple': 'f24a82', 'ansiteal': 'f24a82',}

{'ansiblack': '#f24a82', 'ansiwhite': '#f24a82', 'ansidefault': '#f24a82', 'ansired': '#f24a82', 'ansigreen': '#f24a82', 'ansiyellow': '#f24a82', 'ansiblue': '#f24a82', 'ansifuchsia': '#f24a82', 'ansiturquoise': '#f24a82', 'ansilightgray': '#f24a82', 'ansidarkgray': '#f24a82', 'ansidarkred': '#f24a82', 'ansidarkgreen': '#f24a82', 'ansibrown': '#f24a82', 'ansidarkblue': '#f24a82', 'ansipurple': '#f24a82', 'ansiteal': '#f24a82'}

{'ansiblack': (0xf2, 0x4a, 0x82), 'ansiwhite': (0xf2, 0x4a, 0x82), 'ansidefault': (0xf2, 0x4a, 0x82), 'ansired': (0xf2, 0x4a, 0x82), 'ansigreen': (0xf2, 0x4a, 0x82), 'ansiyellow': (0xf2, 0x4a, 0x82), 'ansiblue': (0xf2, 0x4a, 0x82), 'ansifuchsia': (0xf2, 0x4a, 0x82), 'ansiturquoise': (0xf2, 0x4a, 0x82), 'ansilightgray': (0xf2, 0x4a, 0x82), 'ansidarkgray': (0xf2, 0x4a, 0x82), 'ansidarkred': (0xf2, 0x4a, 0x82), 'ansidarkgreen': (0xf2, 0x4a, 0x82), 'ansibrown': (0xf2, 0x4a, 0x82), 'ansidarkblue': (0xf2, 0x4a, 0x82), 'ansipurple': (0xf2, 0x4a, 0x82), 'ansiteal': (0xf2, 0x4a, 0x82)}

{'black': (0xf2, 0x4a, 0x82), 'white': (0xf2, 0x4a, 0x82), 'default': (0xf2, 0x4a, 0x82), 'red': (0xf2, 0x4a, 0x82), 'green': (0xf2, 0x4a, 0x82), 'yellow': (0xf2, 0x4a, 0x82), 'blue': (0xf2, 0x4a, 0x82), 'fuchsia': (0xf2, 0x4a, 0x82), 'turquoise': (0xf2, 0x4a, 0x82), 'lightgray': (0xf2, 0x4a, 0x82), 'darkgray': (0xf2, 0x4a, 0x82), 'darkred': (0xf2, 0x4a, 0x82), 'darkgreen': (0xf2, 0x4a, 0x82), 'brown': (0xf2, 0x4a, 0x82), 'darkblue': (0xf2, 0x4a, 0x82), 'purple': (0xf2, 0x4a, 0x82), 'teal': (0xf2, 0x4a, 0x82)}

Is there another way to change the color of the syntax highlighting or something that I'm doing wrong with this approach?

**Comment by scopatz** [comment]
Hi @TobalJackson, Yeah, sorry that variable is deprecated IIRC.  You should use `$XONSH_COLOR_STYLE` http://xon.sh/envvars.html#xonsh-color-style.  You can use `xonfig styles` to display the available color style name, and `xonfig colors` to display what the palette looks like.

**Comment by TobalJackson** [comment]
Hey @scopatz, thank you for your reply! I just changed my color style to native and everything looks great!  Is there a suggested/public interface for adding color styles or is editing the files found at https://github.com/scopatz/xonsh/search?utf8=%E2%9C%93&q=autumn 
the only way right now?

**Comment by scopatz** [comment]
Hi @TobalJackson - yeah, unfortunately there isn't a great way to add a style yet.  One of the main issues is that in addition registering it with xonsh in the various places, a new style would also need to be registered with pygments, if pygments in installed.  I haven't looked into this yet.  A pull request with this feature would be very welcome :). 

One alternative would be to just have a "user" style that users are allowed to modify.  This could patch the current need, but doesn't really allow for people to add many styles.  

Currently the best way is to just modify a style's colors directly, which really is the least awesome option.

**Comment by scopatz** [comment]
See http://pygments.org/docs/styles/ for more details

**Comment by gforsyth** [comment]
I'm closing this out since users can use `default` to customize their shells
