### ISSUE TITLE
Strange behaviour on 'git pull'

### ISSUE THREAD

**Issue by mindflayer** [xonsh/xonsh#858]
Hi there, I'm having a strange behavior when running a **git pull** on every GIT repo I have on my desktop at the office:
```bash
$ git pull
/bin/sh: mc: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `mc'
Already up-to-date.
```
Here is the system I'm using:
```bash
$ cat /etc/os-release 
NAME=openSUSE
VERSION="13.1 (Bottle)"
VERSION_ID="13.1"
PRETTY_NAME="openSUSE 13.1 (Bottle) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
```
_xonsh_ shell is running on **pyenv 3.5-dev**.

**Comment by scopatz** [comment]
Hi @mindflayer - this SO post seems relevant: http://stackoverflow.com/a/11577652/2312428. Could you try running `source-bash /usr/share/Modules/init/bash` first and then try running git?  It seems like git expects a bash environment on your systems that isn't there.  (Note that git is partially written in Bash.)  You might try adding such a line to you `.bash_profile` to make this go away too.

**Comment by laerus** [comment]
hey @mindflayer do you mind taking a look at this again in the latest xonsh version?

**Comment by mindflayer** [comment]
```(.venv) drizzt@mindflayer ~/repos/xonsh master $ git pull
Already up-to-date.
(.venv) drizzt@mindflayer ~/repos/xonsh master $ xonsh --version
xonsh/0.4.6.dev86
```

**Comment by mindflayer** [comment]
@laerus Did I try the right version?

**Comment by laerus** [comment]
yes @mindflayer thank you! do you still get this issue? it seems like you just did a `git pull` successfully

**Comment by mindflayer** [comment]
Affermative! :+1: 
It looks like you fixed it.

**Comment by laerus** [comment]
someone fixed this but it wasn't me! :smile: glad it's working for you.
