### ISSUE TITLE
source-bash activate conda env errors

### ISSUE THREAD

**Issue by CJ-Wright** [xonsh/xonsh#864]
I am trying to activate a conda environment in xonsh but it fails.

``` bash
christopher@deepthought ~ $ source-bash activate dp_dev
xonsh: error: Source failed: activate dp_dev
```

However, I can activate the env in regular bash

``` bash
christopher@deepthought:~$ source activate dp_dev
discarding /mnt/work-data/other_src/anaconda/bin from PATH
prepending /mnt/work-data/other_src/anaconda/envs/dp_dev/bin to PATH
(dp_dev)christopher@deepthought:~$ 
```

What am I doing going wrong?

Potentially related
`which python` gives back the system python

``` bash
christopher@deepthought ~ $ which python
Illegal option -v
/usr/bin/python
```

but running python the command gives back the anaconda installation

``` bash
Python 2.7.11 |Anaconda 2.1.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
```

just for comparison bash gives: `/mnt/work-data/other_src/anaconda/bin/python` as the python without any environment.

**Comment by gforsyth** [comment]
Hey @CJ-Wright -- you aren't doing anything wrong, it's a problem with the way that bourne shells handle their PATH vs. xonsh

If you want you can try out a script I wrote to handle this.  It's not ready for primetime but maybe it'll be of use to you:
https://github.com/gforsyth/dotfiles/blob/master/pyselect.xsh

Just stick that somewhere in your PATH (like `/usr/local/bin`), 
set `$WORKON_HOME` to the `/env` directory inside your anaconda install, and then you can `source pyselect` and you should have a tab-completable listing of your environments to choose from.  

Also, are you on current master?  The `Illegal option -v` is an odd thing to see in the output of `which`.  Do you have any aliases that call Python?

**Comment by CJ-Wright** [comment]
Thank you very much! I will try your pyselect.
I got xonsh from `conda install -c xonsh/channel/dev xonsh`
I am not sure what you mean by "aliases that call Python".

**Comment by gforsyth** [comment]
What's the output of 

```console
which which
```

?

And I mean something in your `bashrc`, `zshrc` or `xonshrc` along the lines of `aliases['python'] = 'python -v'`

**Comment by scopatz** [comment]
Maybe pyselect, vox, and the other virualenvs things should be xontribs in this repo? Just a suggestion :)

**Comment by CJ-Wright** [comment]
```bash
christopher@deepthought ~ $ which which
Illegal option -v
which -> <function which at 0x7f4959b65d08>
```

**Comment by gforsyth** [comment]
@scopatz The very thing I was working on

@CJ-Wright huh... what OS are you on?

**Comment by scopatz** [comment]
@gforsyth aweome, you have all the good ideas :)

**Comment by gforsyth** [comment]
Now I need to figure out how to put github comments on my CV

**Comment by CJ-Wright** [comment]
```bash
christopher@deepthought ~ $ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```

**Comment by CJ-Wright** [comment]
@gforsyth I think one reason is that anaconda appends itself to the path via the .bashrc so maybe something is happening there, but otherwise no there are no python aliases.

**Comment by gforsyth** [comment]
Thanks @CJ-Wright.  Would you mind opening up another issue for that `which` error you're getting?
```
Illegal option -v
```
And since it shows up when you type `which which` then I think anaconda is off the hook

**Comment by CJ-Wright** [comment]
@gforsyth sure 
which which is now #866

**Comment by melund** [comment]
@gforsyth Why shouldn't the `source-bash activate env` work.

On windows we got the batch scripts working so 'source-bat activate env' calls the activate.bat scripts and reads the changes to PATH back into xonsh. I thought `source-bash` was the same.

**Comment by gforsyth** [comment]
@melund -- it had just never worked for me, but I was just digging in and I figured it out.  

The subprocess call in `source_foreign` is failing because `activate` complains about not being sourced.  You can, however, do

```console
source-bash source activate envname
```

and that works

**Comment by gforsyth** [comment]
and I think one of the main differences in the windows implementation is that the idea of 'sourcing' doesn't really exist, I don't think.

**Comment by melund** [comment]
OK. But foreign shell stuff should call it with the 'source' commend automatically. Hence the name 'source-bash' so if it doesn't there is probably some bug. What do you think @scopatz ?

**Comment by scopatz** [comment]
If you `source-bash` it should call the source command.  That is what I thought it did.  I think this is probably a bug.  One thing that I have considered adding that I think would be helpful here is if we had a verbose or debug flag on the source-foreign alias and `foreign_shell_data()` function that prints to stdout the script that it is about to run.  There is no real way to know what command the `foreign_shell_data()` function is about to execute, as of right now.  If we had that, we'd know if the source command is making it to the script.

**Comment by birdsarah** [comment]
I think this is the same issue. I tried `source activate env` and got the following

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16049, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 310, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2343, in p_error
    self.xonsh_code)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 411, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:4:5: ('code: [',)
![if [[ -n $BASH_VERSION ]]]; then
     ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9401, in wrapped_simple_command
    r = f(args, i)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 14286, in source_alias
    builtins.execx(fp.read(), 'exec', builtins.__xonsh_ctx__)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16035, in exec
    transform=transform)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15996, in compile
    tree = self.parse(input, ctx, mode=mode, transform=transform)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15967, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16107, in _parse_ctx_free
    raise original_error
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16049, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 310, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2343, in p_error
    self.xonsh_code)
  File "/Users/sbird/miniconda3/lib/python3.5/site-packages/xonsh/parsers/base.py", line 411, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:4:9: ('code: $BASH_VERSION',)
if [[ -n $BASH_VERSION ]]; then
```

`source-bash activate env` didn't work, but `source-bash source activate env` did work.

**Comment by scopatz** [comment]
@birdsarah  `source-bash source activate env` That is a hilarious workaround. It seems like our sourcing command is trying to be too clever when sourcing scripts written at the command line.  Also, do you know about vox? http://xon.sh/python_virtual_environments.html

**Comment by gforsyth** [comment]
Ack. No, don't use vox (in this particular situation, no hate for vox in my heart). Vox relies on virtualenv which relies on `ensurepip` which doesn't ship with continuum builds of Python. It will fail spectacularly.

**Comment by scopatz** [comment]
fair point

**Comment by scopatz** [comment]
Ok, at this point I think that the `xonda` xontrib solves this problem and this is probably closable. Please feel free to close it @CJ-Wright or bring up any lingering issues.

**Comment by CJ-Wright** [comment]
I haven't tried out the xonda xontrib, but I'll make a point to try it out and close.

**Comment by scopatz** [comment]
Any action on this @CJ-Wright? I'd like to close this out today since there is a long standing alternative and the underlying problem with unexported process state is not something that we can/should fix.

**Comment by scopatz** [comment]
Closing this out for the above reasons. Please feel free to reopen if this is in error.
