### ISSUE TITLE
Noisy tests

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#882]
After the #789 was merged in the tests became more noisy. 

For example one of the tests run `ipconfig /all` on windows https://github.com/scopatz/xonsh/blob/master/tests/test_execer.py#L49. 

After #789 this started printing it output when running `nosetests -q`. 

Anyone got a clue why that is?

**Comment by adqm** [comment]
Not sure why, but I do notice this as well.

It also almost looks like xonsh is trying to parse some of the output as xonsh code?  I see something like "command not found: the.  did you mean: tee?".

**Comment by scopatz** [comment]
For what it is worth, I have noticed this too.

**Comment by laerus** [comment]
does this still apply to pytest?

**Comment by scopatz** [comment]
I have not seen it recently. Feel free to reopen
