### ISSUE TITLE
Fuzzy autocomplete

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [xonsh/xonsh#894]
Hello

I think it might be cool to have a fuzzy search feature (as in Fish shell).

And potentially the subdirectory search that is in zsh.

Has anyone already tried implementing this ? 

Do you think it would be a good idea ?

**Comment by melund** [comment]
Also an awesome idea. Someone else mentioned fzf https://github.com/junegunn/fzf but I don't know how it compares to your idea. I haven't used fish. 

I might be a good option for a xontrib packages https://github.com/scopatz/xonsh/blob/master/docs/tutorial_xontrib.rst

**Comment by GuillaumeLeclerc** [comment]
I tried fzf when I was using zsh and I was not convinced. It seemed overkill and it would break the user exprience (It opens a huge split at the bottom).

I was thinking about a more simpler feature. When we compute the list of file completions for an input `x`. instead of returning all possibilities that start with `x` we would return all possibilities that satisfy the following condition: " x is a substring of y".

Example:

if y type "ab". The bold elements would be matched:

- __ab__
- ac
- __"alphabeta"__

**Comment by melund** [comment]
Not real 'fuzzy' then. But could be useful anyway. I would like to try it.

**Comment by GuillaumeLeclerc** [comment]
What's you definition of fuzzy ? If might be even more useful

**Comment by GuillaumeLeclerc** [comment]
Do you mean something related to levenstein distance ?

**Comment by GuillaumeLeclerc** [comment]
I took a look at the completer but it seems all completers have a common interface accepting a prefix as an argument. It make the fuzzy search a little hard to implement. I'm thinking of two options:

- Write a fuzzy implementation for all completers (It could take a while)
- pass an empty string to all completers and filter the set using a generic fuzzy filter

What's your thought about this ?

**Comment by melund** [comment]
Well. A little over my head here. I think @adqm and @scopatz did much of the completers. So I think it is up to them.

**Comment by scopatz** [comment]
First off, thanks @GuillaumeLeclerc for opening up this issue. Like @melund mentioned, @azag0 brought up this issue of fuzzy completer as well. Personally, I think it is a good idea and would like to see it happen either through fzf or another tool.  Frankly, though, our completer system needs an overhaul.

At is core, completion takes a line and a cursor position and suggests a replacement line.  However, many completer, including Bash, are oriented around the idea of suggesting just the current token.  I would like to see xonsh support a variety of completion ideas:

1. Python context completion (current)
2. Bash completion (current)
3. Man page completion (needs rewrite)
4. Jedi, fzf and other external tools (optionally if user has them installed)
5. Custom completion commands that the user registers (or more likely a xontrib or xonsh core)

I think the structure that is there right now needs to be overhauled to support this.  This has been on my to-do list for a while.  However, if some one else wants to take the lead on architecture this, I would be more than happy to help!

**Comment by azag0** [comment]
Ah, I forgot about the mail to the mailing list. As I see no reply there, does it mean that there is currently no easy way to do that within xonsh? Fish, for example, has the `commandline` built-in that provides the user with quite powerful command line buffer manipulation.

**Comment by GuillaumeLeclerc** [comment]
You can check my very basic implementation in #903

**Comment by scopatz** [comment]
@azag0, sorry about not responding on the mailing list.  That shows you how backlogged on email I am :/.  The cliff notes version is that I have never used `fzf` but would welcome any kind of integration. @GuillaumeLeclerc has taken the initiative :)

**Comment by GuillaumeLeclerc** [comment]
It's on master branch now
