### ISSUE TITLE
proposal: add a local documentation server

### ISSUE THREAD

**Issue by funkyfuture** [xonsh/xonsh#897]
for the following reasons i propose to add functionality of a local http-server that serves the _current_ documentation:
- the current dev-docs are not hosted on http://xon.sh
  - which is sad if you are running xonsh from source
- there isn't always a network, but using hypertext-documentation helps a lot

therefore i would implement three functions:
- `run_docs_server`
  - build html docs in a temporary directory
  - start a webserver serving the files
  - open a web browser with the url
- `refresh_docs_server`
  - build the docs again
- `stop_docs_server`
  - stop the webserver
  - remove the temporary directory

alternatively a command-subcommand-style cli can be implemented.

the functions would refuse to do something if Sphinx wasn't installed.

before i get into it, i'd appreciate a feedback if this was accepted.

also, i'm confused where such functions would live. i'd expect it to be in `xonsh.tools`, but that module is rather a `utils` with loads of helper functions. it's also not obvious to me what the distinction of `built_ins` and `tools` is.

**Comment by gforsyth** [comment]
Hey @funkyfuture -- not sure if this fits your needs, but if you go into the docs folder you can run `make html` and then `firefox _build/index.html` to browse the docs as they are in master.

**Comment by funkyfuture** [comment]
that wouldn't help with installations from a package as the docs are not bundled. generally the idea is about purest cli convenience.

but the http-part isn't really necessary.

**Comment by gforsyth** [comment]
Ok.  The docs have not been pushed up as frequently as they might've been, but that's been mostly automated at this point.  
Would it fit your needs if we had the dev docs on xon.sh?

**Comment by funkyfuture** [comment]
that'd help a lot. but for offline situations still failing in 'overall accessibility performance'. ;-)

**Comment by gforsyth** [comment]
Ooo, how about a man page?

**Comment by funkyfuture** [comment]
for API browsing? i demand that Berners-Lee stuff!

**Comment by gforsyth** [comment]
Ok.  But if the docs aren't bundled when you install as a package then where are you serving them from?  I am likely totally missing some use case here, but I'm also trying to avoid anyone putting in work to duplicate existing functionality.

**Comment by funkyfuture** [comment]
> But if the docs aren't bundled when you install as a package then where are you serving them from?

by bundling them!?

the use-case is to have a well accessible documentation shipped with the application. (once that was a standard.)

**Comment by melund** [comment]
Could this not be a `xontrib`. So if you have this xontrib enabled, you could just write a command to launch the local doc server?

**Comment by funkyfuture** [comment]
i thought about that, but it feels strange to decouple application and docs while their state is coupled.

a xontrib could fetch the docs, either found relative to the running xonsh instance or if there is none based on the version from the web and keep it cached locally.

**Comment by melund** [comment]
A xontrib is also a way to convince skeptics that it may be a good idea ;)

**Comment by astronouth7303** [comment]
```
import pydoc, webbrowser
pydoc._start_server(pydoc._url_handler, 8080)
webbrowser.open('http://localhost:8080')
```

See https://github.com/python/cpython/blob/3.6/Lib/pydoc.py

**Comment by scopatz** [comment]
Closing due to age
