### ISSUE TITLE
extend docs on xontribs

### ISSUE THREAD

**Issue by funkyfuture** [xonsh/xonsh#907]
i think it'd be a good idea to extend the xontribs-documentation with best practices. in particular, this comes to my mind
- [ ] how should a package be called? (especially regarding [automatic] discovery in the PyPI)
  - `xonsh-<name>`
  - `xonsh-xontrib-<name>`
  - `xontrib-<name>`
- [ ] where should userdata live? certainly in the xonsh data dir
  - `.../xontribs/<name>/`
- [ ] what xonsh modules are commonly of interest when developing xontribs
  - is there a way to register aliases with a xontrib?
  - are there hooks for events like a xonsh termination?
- [ ] it seems very reasonable to me to provide a **simple** and consistent framework for common cli-functionalities, such as
  - argument parsing
  - subcommand-delegation
  - automated documentation

a short description how xontribs are discovered by xonsh would be interesting.

@Siecje your input would be helpful here i assume

**Comment by scopatz** [comment]
Thanks for suggesting this, @funkyfuture! New as they are, I am sure that the xontribs docs could definitely be improved.  Some of these I think are things that will come as people write more of these.

> how should a package be called? (especially regarding [automatic] discovery in the PyPI)

I am not sure we should force people to call their packages anything.  If they want to prepend or append with xontrib, that is probably fine.

> where should userdata live? certainly in the xonsh data dir

Well, they are welcome to use [`$XONSH_DATA_DIR`](http://xon.sh/envvars.html#xonsh-data-dir) if they want.

> what xonsh modules are commonly of interest when developing xontribs, is there a way to register aliases with a xontrib?

Same as you would in an rc file or at the command line, just use `aliases`

> are there hooks for events like a xonsh termination?

Not yet.  This is something we should consider.  We implemented a very simple framework to start with.

> it seems very reasonable to me to provide a simple and consistent framework for common cli-functionalities, such as argument parsing, subcommand-delegation

These seem to apply more to writing aliases than xontribs.

> automated documentation

There is some of this already if the xontrib is registered.

> a short description how xontribs are discovered by xonsh would be interesting.

I thought this was covered, but clearly not well enough :)

**Comment by funkyfuture** [comment]
> I am not sure we should force people to call their packages anything.

i wasn't writing about forcing something, but to recommend best practices. i think this is also of value for the non-authoring user who can rely on a convention. eg, knowing the expected place of user data is more fun than searching.

> I thought this was covered, but clearly not well enough :)

nah, it tells a lot about where, but not how.

i had an idea for a nonsense xontrib. i'll see that i amend the docs on the way.

**Comment by astronouth7303** [comment]
A lot of this is covered by https://github.com/laerus/cookiecutter-xontrib (although it's not always clear when the `xontrib-` prefix should be used.

There's an event subsystem now, although xonsh exit is probably best covered by the `atexit` Python module. Aliases work just like in a `.xonshrc`.

I would like to see more utilities to make writing a xontrib easier (eg, command wrappers based on argparse/fire/etc, functional utilities such as that provided by `xontrib-schedule`), but they're unfortunately fairly low on the priority list.

Are there any other questions you have, @funkyfuture? Or is this just about covered?

**Comment by scopatz** [comment]
I think this is probably covered at this point.  Feel free to reopen this @funkyfuture!  We could probably add a pointer to the coockiecutter to the docs, if it isn't there already...

**Comment by funkyfuture** [comment]
> We could probably add a pointer to the coockiecutter to the docs, if it isn't there already...

at least not on the xontribs' page, where is no link to dev resources at all.

**Comment by astronouth7303** [comment]
xontribs are written just like interactive xonsh. Yeah, we need an actual manual for the xonsh language, services, etc, but that's not a xontrib-specific problem.
