### ISSUE TITLE
Unable to use utf-8

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [xonsh/xonsh#912]
Hello,

I was trying to do something like this today:

`echo @(output)`, where output contains utf-8 chars. And even if the default encoding for my python environment is utf-8 I get this error:

`UnicodeEncodeError: 'ascii' codec can't encode character '\xc5' in position 109: ordinal not in range(128)`

Is it normal. How can I deal with this ?

**Comment by scopatz** [comment]
Hi @GuillaumeLeclerc, thanks for reporting.  What is the output of `xonfig` when you see this message? Also, can you send us the full traceback by setting [`$XONSH_SHOW_TRACEBACK = True`](http://xon.sh/envvars.html#xonsh-show-traceback)

**Comment by GuillaumeLeclerc** [comment]
I will as soon as I'm on the computer I had this bug. Sorry I did add the traceback in the first place

**Comment by GuillaumeLeclerc** [comment]
```
$ xonfig
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 1.0.0 |
| pygments         | 2.1.3 |
| on posix         | True  |
| on linux         | True  |
| on arch          | True  |
| on windows       | False |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
```
__command__: 

```
$ echo @(toto)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/base_shell.py", line 154, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 55, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/xonsh/built_ins.py", line 644, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.5/site-packages/xonsh/built_ins.py", line 522, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1483, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe5' in position 14: ordinal not in range(128)
```

**Comment by scopatz** [comment]
What is the value of `toto`?

**Comment by scopatz** [comment]
This is what I am seeing on master, 

```console
scopatz@artemis ~/xonsh master $ echo @("\xe5")
å
scopatz@artemis ~/xonsh master $ toto = "\xe5"
scopatz@artemis ~/xonsh master $ echo @(toto)
å
scopatz@artemis ~/xonsh master $ xonfig
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 0.60  |
| pygments         | 2.1.3 |
| on posix         | True  |
| on linux         | True  |
| on arch          | False |
| on windows       | False |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
scopatz@artemis ~/xonsh master $ $XONSH_ENCODING
'utf-8'
```

**Comment by GuillaumeLeclerc** [comment]
Its a very long file I did not included here for clarity.

I don't get the same thing as you:

```
$ echo @("\xe5")
UnicodeEncodeError: 'ascii' codec can't encode character '\xe5' in position 0: ordinal not in range(128)
```
I have been slightly diverging from master but I don't think it should impact this.

Do you have any idea why I would not get the same thing as you ?

**Comment by scopatz** [comment]
What is your value for `$LC_TYPE`?

**Comment by GuillaumeLeclerc** [comment]
I don't have any env variable called `$LC_TYPE`.

Though, `LC_LANG` is undefined which is strange since.

```$ localectl
   System Locale: LANG=en_US.UTF-8
       VC Keymap: fr_CH
      X11 Layout: n/a
```

**Comment by scopatz** [comment]
It looks like your Popen may be ignoring universal newlines for some reason.  Could you please tell us what is getting passed into this call:  https://github.com/scopatz/xonsh/blob/master/xonsh/built_ins.py#L530

Specifically stdout and universal_newlines.

**Comment by GuillaumeLeclerc** [comment]
I tried setting my "$LC_LANG" to `en_US.UTF-8`. and I still have the same problem.

I also remarked the error is only when outputing, using an non ascii character as a varable name works fine

```
~ $ ð = 2
~ $ ð
2
~ $ echo "ð"
UnicodeEncodeError: 'ascii' codec can't encode character '\xf0' in position 0: ordinal not in range(128)
```

**Comment by scopatz** [comment]
Yeah, you are going to have this problem with all non-ASCII characters.  It is all edth-ed up :)

**Comment by GuillaumeLeclerc** [comment]
My point was it is working in python mode but not in subproc mode.

```
print(stdout, uninew) 
None True
```

I tried in an isolated docker container and I don't face the bug at all

**Comment by scopatz** [comment]
OK, that is weird.  There must be some messed up setting in your Python or env, but your `xonfig` output indicates that this should work.

**Comment by scopatz** [comment]
What does `sys.getfilesystemencoding()` say? for me it is utf-8

**Comment by scopatz** [comment]
Also what is `locale.getpreferredencoding(False)`, it seems like this might be helpful: http://stackoverflow.com/a/28996987/2312428

**Comment by GuillaumeLeclerc** [comment]
`sys.getfilesystemencoding()` return `ascii`. 
I tried setting all `LC_` env variables to `en_US-UTF-8`. and I still get this result

The problem comes from the fact that xonsh is started before the env variables are set (since I add them in .xonshrc). If I start a new xonsh subprocess it works fine because it inherit the env variables.

I think the only way to fix this is to define the variables before xonsh start. Since it's my login shell. It will work for any terminal I start inside the X server (because xinit inherit from my login shell) but it will not work when I only have a tty (when I don't want to start X). I'll try setting it with pam_env and tell you what happens.

**Comment by GuillaumeLeclerc** [comment]
it's not working. As I said it only works in shells started inside another shell (this is the case for shells in X). 

The only way I see to fix it would be to add an env variable in my tty service, but since I don't have a recovery live CD to fix any mistake I could make. I will do it later.

**Comment by scopatz** [comment]
@GuillaumeLeclerc - You probably need to change the value in `/etc/default/locale` and reboot to have the change affect the whole system permanently: see

1. http://www.shellhacks.com/en/HowTo-Change-Locale-Language-and-Character-Set-in-Linux
2. https://help.ubuntu.com/community/Locale

If this works then it would be nice if you could add an entry to the Linux guide about having an ascii filesystem... I'd appreciate that so we can point people to it in the future.

**Comment by scopatz** [comment]
And maybe we should do a check on startup for this, and issue a runtime warning.

**Comment by GuillaumeLeclerc** [comment]
I don't have `/etc/default/locale` on arch. We have `/etc/locale.conf` and the file is filled correctly but it does not set env variables. I don't know why but it does not seem related to xonsh. I think I can close this u

**Comment by scopatz** [comment]
Well, it still seems like there should be a note about this issue in the Linux guide.  If you wouldn't mind adding that, I think we can close this. Thanks!

**Comment by GuillaumeLeclerc** [comment]
I will make a pull request with this. Ping me if I forget it.

**Comment by scopatz** [comment]
@GuillaumeLeclerc any chance you can make a PR to the docs with this, please?

**Comment by GuillaumeLeclerc** [comment]
I will do it right now.

**Comment by MareinK** [comment]
Just wanted to add my solution on Arch Linux for future readers. I was not able to input UTF8 characters into the xonsh terminal. I tried setting `$LANG` and `$LC_LANG` in a bunch of files. In the end setting it in `/etc/environment` worked for me. Note that that file in particular takes just `KEY=VALUE` pairs, so no `export` commands. So this is what I put in the file:

```
LANG=en_GB.UTF-8
LC_LANG=en_GB.UTF-8
```
