### ISSUE TITLE
Infinite loop during python parsing

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [xonsh/xonsh#914]
Hello,

When I type this:

`[(f, p) for f,,p in [[1,2,3], [1,2,3]]]`

xonsh just hang. On the python interpreter I get a syntax error

**Comment by melund** [comment]
I can confirm this.

**Comment by scopatz** [comment]
Thanks for reporting @GuillaumeLeclerc

**Comment by laerus** [comment]
i think this is solved! `[(f, p) for f,,p in [[1,2,3], [1,2,3]]]` now raises `SyntaxError`
