### ISSUE TITLE
Autocomplete: use left and right keys to cycle through items (prompt kit)

### ISSUE THREAD

**Issue by sebastien** [xonsh/xonsh#917]
Zsh's auto-complete option list allows users to move the current selection not only with the top/down arrow keys (previous/next) but also with left/right (item to the left, item to the right, in multi-column mode). This feature is very useful when browsing through many items, as the left/right arrows allow to quickly skip dozens of items.

**Comment by gforsyth** [comment]
This would be great.  There's also an open issue for this here: https://github.com/jonathanslenders/python-prompt-toolkit/issues/147

**Comment by rampage644** [comment]
+1 here, very convenient feature of zsh

**Comment by scopatz** [comment]
We also should make TAB completions first response the current token from the history.

**Comment by gforsyth** [comment]
I'm closing this since it's an upstream issue -- I know it's on @jonathanslenders todo list and it will make it into `xonsh` eventually.
