### ISSUE TITLE
Crash when following xonfig wizard and using an external, nonexistent shell

### ISSUE THREAD

**Issue by kirbyfan64** [xonsh/xonsh#941]
Hello!

I just started using Xonsh, and I love it so much I set it to be my default shell. It's awesome!

However, I noticed a slight issue with the xonfig wizard. When I was following the steps, it came to the section where you put in the name of external shell (in `xonfig.make_fs`). I accidentally misspelled the path to bash but didn't notice. When the wizard finished and I closed and re-opened Xonsh...it crashed.

Ideally, this would print some type of warning instead of completely crippling the shell. I had to change it back to bash just to edit `~/.config/xonsh/config.json` and fix the path, then change my shell back to Xonsh.

**Comment by scopatz** [comment]
Thanks for reporting this @kirbyfan64!  I think what we need to do is make it so that the foreign shells don't fail fatally on startup.

**Comment by scopatz** [comment]
I believe that this has been solved the the addition of fallback shells.  If something fatal happens during startup, you get an escape hatch.  I am going to close this, but please feel free to reopen if needed.
