### ISSUE TITLE
Can't make the test suite crashing

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [xonsh/xonsh#942]
Hello,

I was trying to tests. To try it I made a simple test to make it fail and see if it works but the problem is `nosetests` says it's all fine.

I tried adding a function:

```python
def test_tests(): 
    assert_equal(True, False)
    print("HOHOHOHOH")
```

and no tests are failing. Moreover nothing is printed

I tried adding a print on top of the file and it's not getting printed. Then I tried adding a false assertion in other tests and none of them is failing. 

I'm sure I must be something wrong but I can't figure out what.

**Comment by scopatz** [comment]
What if you call this `test_x()` rather than `test_tests()`?

**Comment by GuillaumeLeclerc** [comment]
The same thing happen. The strange thing is nothing is printed, even if I add it on top of the file

It seems the code I'm typing is not taken into account. It looks like tests are cached in some way.

**Comment by melund** [comment]
Nose captures stdout. To print use `nosetest -q -s` 
If you also add a filename to the command  you don't have to run the entire year suite

**Comment by laerus** [comment]
solved with pytest!

**Comment by scopatz** [comment]
woohoo!
