### ISSUE TITLE
Lines too long make the prompt disappear

### ISSUE THREAD

**Issue by refi64** [xonsh/xonsh#953]
I had a case where I was in a directory with the path `/media/ryan/stuff/oxygine-framework/examples/HelloWorld/src`, and the prompt looked like this:

```
ryan@DevPC-LX /media/ryan/stuff/oxygine-framework/examples/HelloWorld/src master
```

Note that the `$` got cut off at the end. In short, if the path overflows the edge of terminal, absolutely _nothing_ you type will be visible. At all.

Slightly more interesting is when there's almost no space at the end:

```
ryan@DevPC-LX /media/ryan/stuff/oxygine-framework/examples/HelloWorld master $ e
.............................................................................. c
.............................................................................. h
.............................................................................. o
..............................................................................  
.............................................................................. 1
.............................................................................. 2
.............................................................................. 3
..............................................................................  
```

Wouldn't a possible solution be to just remove the whole `...` thing and have the text flow normally to the next line like bash? I thought the line justification was cool at first, but when you're in deeply nested directories, it kind of bites...

Or maybe it could be an option?

**Comment by melund** [comment]
I think #899 could fix this issue.

**Comment by JohnLunzer** [comment]
In the mean time you could try making a custom prompt which contains a newline:
```$PROMPT = '{BOLD_GREEN}{user}@{hostname} {WHITE}[{cwd}]\n{BLUE}`-> {BOLD_BLUE}%{NO_COLOR} '```

I've always preferred this method anyway as it keeps your prompt in a consistent location despite your current working directory.

**Comment by janschulz** [comment]
I have a similar problem:

```
|jschulz@littlebottom C:\data\downloads\libpng\matplotlib-1.5.0+2326.gf349629-np18py27_0.tar\mat 
```
-> the `|` is the cursor sign, but when I type something nothing is shown :-(

**Comment by gforsyth** [comment]
Hey @janschulz -- you can try setting `$DYNAMIC_CWD_WIDTH='30%` (or some other percentage) and then the current folder path will never occupy more than that percentage of your current window width

**Comment by scopatz** [comment]
I think the many options now for dealing with this make this issue closable. Please feel free to reopen if desired.

**Comment by nh2** [comment]
So is there currently a solution that can make long lines overflow into the next line normally like in bash?

**Comment by nh2** [comment]
To clarify: I think this bug is still present for me. See for example: https://asciinema.org/a/1t6k5hqg8zq41v0x37cwih9sq

**Comment by laerus** [comment]
hey @nh2 can you please post the output your `xonfig`

**Comment by nh2** [comment]
@laerus It's the empty config `{}` on `xonsh/0.5.12`

**Comment by laerus** [comment]
i mean type `xonfig` in xonsh and paste the output.

**Comment by nh2** [comment]
> i mean type xonfig in xonsh and paste the output.

@laerus Ah, I misunderstood. Here it is:

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.14              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | Ubuntu              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by laerus** [comment]
maybe we need some kind of a wrapping?

**Comment by nh2** [comment]
> maybe we need some kind of a wrapping?

@laerus For me normal wrapping into the next line like bash does would be totally sufficient; is that possible?

**Comment by laerus** [comment]
@nh2 i don't believe this is possible with the `prompt_toolkit` backend atm, 
readline works as you expect though.

**Comment by gforsyth** [comment]
Closing this out, ping if you're interested in taking it on.
