### ISSUE TITLE
Is there a `clear` command?

### ISSUE THREAD

**Issue by howdoicomputer** [xonsh/xonsh#957]
I looked through the documentation and I couldn't find anything. Is there a way to clear the terminal so that there is only the prompt?

**Comment by melund** [comment]
On windows the command is `cls`, which is an alias to the cmd.exe `cls` command.  I think the command on posix is `clear`

**Comment by howdoicomputer** [comment]
Ah, that explains it. I was using cmder and it had aliased clear. Neat. Thanks for the information.

**Comment by ns-phennessy** [comment]
`ctrl + l` also works for this.

**Comment by scopatz** [comment]
Closing since it seems this has been answered.  Feel free to reopen if desired.!
