### ISSUE TITLE
demo still points to old broken link

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#964]
scopatz@athenaie ~/xonsh master $ # to learn more visit http://xonsh.org

**Comment by melund** [comment]
@denfromufa . Thanks for letting us know. I think scopatz is too hung up before PyCon to make a new asciinema video ( https://asciinema.org/ ).

If you or anyone of you that work on Linux or Mac is up for it, I think a PR would be very welcome. 

It should basically show the same things, plus some of the new features. @scopatz  pointed out that he would love to see the following things added to the video

- Prompt-toolkit completion
- Changing color palettes, 
- The and/or feature in subproc mode (e.g `echo a and echo b` and `echo a && echo b`)

**Comment by scopatz** [comment]
Old demo has been removed
