### ISSUE TITLE
provide a way to build executable binaries from list of xonsh commands

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#965]
provide a way to build executable binaries from list of xonsh commands using `cx_freeze` or `pyinstaller`.

**Comment by denfromufa** [comment]
`xonsh deploy` with arguments

**Comment by scopatz** [comment]
This would be neat!  A PR would most certainly be welcome.

**Comment by funkyfuture** [comment]
i read through `pyinsstaller`'s docs and my conclusion was that it would be impossible to install further python packages as user. but i'm not sure if this was the case with *folder builds*. due to security concerns the *standalone build* doesn't seem to be a good idea anyway.

**Comment by scopatz** [comment]
Closing due to age
