### ISSUE TITLE
pure python shell commands

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#966]
pure python shell commands, e.g. using

https://github.com/ghantoos/lshell

Discussion started here:
https://groups.google.com/forum/#!topic/xonsh/mm6-MwDNKA0

can open up to 2 more related issues according to @scopatz

**Comment by denfromufa** [comment]
motivation - bash commands in Windows without msys, cygwin, cmder, mingw, git-bash, Windows 10 linux subsystem

**Comment by adqm** [comment]
I agree completely, @denfromufa!  In fact, we're already working toward this (in #742, which I'll finally be able to come back to today and tomorrow!).

**Comment by scopatz** [comment]
+1 to this.  It might also be worth trying to convince the lshell devs to contribute to xonsh instead. I am not sure how much they would be interested in this, due to their focus on whitelisting, but maybe someone could ask...

**Comment by scopatz** [comment]
Also note that lshell is GPL licensed and so that precludes us from incorporating their code ourselves.

**Comment by denfromufa** [comment]
@scopatz that's a show stopper, I should have looked closer!

**Comment by adqm** [comment]
> Also note that lshell is GPL licensed and so that precludes us from incorporating their code ourselves.

Unless we wanted to switch xonsh to GPL :)

**Comment by scopatz** [comment]
> Unless we wanted to switch xonsh to GPL :)

GPL v3 though, only right :)

**Comment by scopatz** [comment]
Closing this since #742 has been merged. If there are specific additional utilities you'd like to see in xoreutils, please open new issues!
