### ISSUE TITLE
no autocompletion on module names but for imported modules works fine

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#968]

**Comment by scopatz** [comment]
This is an optimization to prevent pre-importing module names.  The alternative is set up a cache of names or use importlib to find module names w/o importing.  I am now sure what jedi does or if this would just come automatically with jedi integration.  Do you know @asmeurer?

**Comment by denfromufa** [comment]
btw, ptipython is capable of this feature

**Comment by scopatz** [comment]
Sure, but IPython used to keep a cache of known modules around, which the first time IPython was ran would significantly add to the startup time.  They may have moved to jedi, though...

**Comment by scopatz** [comment]
This is now (optionally) available with the merger of #2166 and the Jedi xontrib. Please feel free to reopen if needed.
