### ISSUE TITLE
ptpython (ptipython) feature set comparison

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#969]
I really like ptipython, how does xonsh compare? Particularly can I get the menu (F2-F7) like in ptpython?

**Comment by scopatz** [comment]
Hi @denfromufa - thanks for bringing this issue up. I don't think that we currently support this, but they certainly can/should be.  A pull request would be very welcome!

**Comment by gforsyth** [comment]
Closing in favor of meta-website issue in #3225
