### ISSUE TITLE
status line plugin - powerline

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#972]
https://github.com/powerline/powerline

e.g. this can be used for live whos:

https://github.com/scopatz/xonsh/issues/936

**Comment by scopatz** [comment]
Happy to have a PR for this too :)

**Comment by melund** [comment]
I know @BYK was pretty into Powerline..

**Comment by GuillaumeLeclerc** [comment]
I think I'd like it too. But not sure how to include a vim plugin in python. Does not seem simple to me

**Comment by denfromufa** [comment]
According to docs other environments such as bash shell and IPython are
also available:

Powerline is a statusline plugin for vim, and provides statuslines and
prompts for several other applications, including zsh, bash, tmux, IPython,
Awesome and Qtile.

**Comment by GuillaumeLeclerc** [comment]
That would be cool if it was possible then

**Comment by BYK** [comment]
I was thinking about this so I'll see if I can get this integrates.

**Comment by santagada** [comment]
https://github.com/milkbikis/powerline-shell <-- this could probably be easily adapatable to xonsh

**Comment by astronouth7303** [comment]
Would this be better as a xontrib instead of core?

**Comment by alairock** [comment]
I think it makes more sense as a xontrib. Keeping the bloat out of the core. (Just my opinion, from a non-contributor)

**Comment by scopatz** [comment]
Pull requests welcome!

**Comment by PaulReiber** [comment]
Sounds right to me as well.

**Comment by santagada** [comment]
I have my own powerline.xsh here... should probably release it somewhere.

**Comment by laerus** [comment]
hey @santagada if you can make a xontrib out of it that would be very cool!

**Comment by santagada** [comment]
Is there any command to generate the skeleton of a xontrib? I could do this in a second if I had it. I also would want to put the code on the xonsh org, to incentivise contributions (my code is terrible right now) but I'm ok with putting on my account for now.

**Comment by laerus** [comment]
@santagada you can use cookiecutter with the xontrib [template](https://github.com/laerus/cookiecutter-xontrib)! you can publish your xontrib like [this](http://xon.sh/tutorial_xontrib.html#tell-us-about-your-xontrib)

**Comment by scopatz** [comment]
That is awesome @laerus! That should make it into the xontrib docs somewhere....

**Comment by santagada** [comment]
please test it out: https://github.com/santagada/xontrib-powerline
its pretty simple right now and has no configuration, but I will change that soon

**Comment by gforsyth** [comment]
I'm closing this issue out since `xontrib-powerline` now exists (and has for more than a year)
