### ISSUE TITLE
steal feature from bpython or dreampie - tooltip for list of arguments

### ISSUE THREAD

**Issue by denfromufa** [xonsh/xonsh#973]
http://www.bpython-interpreter.org/images/3.png

**Comment by denfromufa** [comment]
http://www.dreampie.org/screenshot2.png

**Comment by scopatz** [comment]
I personally dislike tooltips, but I can see that this would be a valuable and desirable feature.  This should be very do-able within the prompt-toolkit shell.  Again, a PR here would be very helpful.

**Comment by anki-code** [comment]
Closed because too old issue without any new thoughts. For anyone who interesting in this the new xontrib is welcome. We have [cookiecutter template](https://github.com/xonsh/xontrib-cookiecutter) to creating xontribs in 10 minutes.
