### ISSUE TITLE
Proposal: Move away from locked history files for history garbage collection

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#999]
Upon further examination of the history and garbage collector I am thinking that perma-locked files from crashed/killed xonsh represent a physical memory leak. This is because locked files are never garbage collected and there is no method to examine a locked file to see if it is perma-locked. Obviously this is not likely to cause any problems but it seems unnecessary. 

Can I propose to move away from file locking all together and rather rely on process ID? Instead of a locked status you put the parent xonsh process PID into log file and then check to see if it is still an active process. If it is an active process do not include it in the garbage collection.

Does this sound reasonable?

**Comment by scopatz** [comment]
Hi @JohnLunzer - I fully agree that the crashed xonsh logs represent a physical memory leak.  (For killed processes, though, we do have a signal handler that unlocks the current history before the process dies. This, of course, isn't 100% either.)

I believe a system based on process ids could work better.  My main concern here is that process ids are recycled, especially between shutdown and startup. Like there might be some weird case if you fork the xonsh process, detach it the slave (which has a new pid), and then kill the master.  This could cause another xonsh process to clean up the slave's history.  That is probably super unlikely to happen.

Also, another concern I have is that it might not be easy to tell which process ids are actually related to xonsh instances.  Someone could write:

**hidden.py**
```python
from xonsh.main import main()
main()
```

and run `python hidden.py`. There would be nothing in the process list about xonsh, but this would be xonsh.  I think we would need to have some local file or service that contains (1) the current time the system started up or some other mechanism to note when this cache is invalid, and (2) all of the processes ids that each instance of xonsh history is responsible for writing its own pid to.

Like I said, I think this pid thing could work and would be in favor of it, but I also think there are some tricky edge cases. :)  A PR would be awesome for this!

**Comment by JohnLunzer** [comment]
I will give this some thought moving forward to see how we can mark log files uniquely based on system parameters (time, pid, etc).

**Comment by scopatz** [comment]
Thanks @JohnLunzer! It is worth noting that firefox does something like this pid locking, and they seem to have this stuff figured out.

**Comment by JohnLunzer** [comment]
A unique process ID could be had through a tuple of (PID, system start time):

First it is needed [a method for checking if PID is active](http://stackoverflow.com/questions/568271/how-to-check-if-there-exists-a-process-with-a-given-pid). This works cross platform. With this out of the way we need methods for getting system start time for both *nix/windows.

[For windows](http://stackoverflow.com/questions/11606774/how-to-get-the-uptime-in-windows) these methods appear the simplest: `wmic os get lastbootuptime` or `net statistics workstation`. Both stay static from start of system so that is really all that matters, which ever is fastest to subprocess wins.

For *nix: `cat /proc/stat` and within `btime` is static boot time.

When made into a tuple and written to log file at creation you can check if the log is "in use" if PID is active and boot time matches that in the log. If either fail then it is eligible for garbage collect.

And it shouldn't matter if xonsh is run from script or not since you are only checking existence of PID and match for boot time which are already written in the log file. You never need to look for "xonsh".

**Comment by scopatz** [comment]
HI @JohnLunzer - this looks eminently reasonable!  I would also add that if we allow for optional psutil integration, they have a cross platform function for getting the boot time: https://pythonhosted.org/psutil/#psutil.boot_time

**Comment by scopatz** [comment]
I think this is a sane path forward.

**Comment by scopatz** [comment]
Also note, that you don't need to run cat since you can just open a file handle:

```
scopatz@artemis ~ $ with open('/proc/stat') as f:
`·.,¸,.·*¯`·.,¸,.·*     x = f.read()
`·.,¸,.·*¯`·.,¸,.·*     
`·.,¸,.·*¯`·.,¸,.·* 
scopatz@artemis ~ $ x
'cpu  19973 1500 4374 860406 1115 0 72 0 0 0\ncpu0 2776 190 704 106789 142 0 47 0 0 0\ncpu1 2678 178 744 107060 100 0 18 0 0 0\ncpu2 3024 188 640 106994 60 0 0 0 0 0\ncpu3 2720 188 642 107217 136 0 6 0 0 0\ncpu4 2031 188 414 108378 88 0 0 0 0 0\ncpu5 2272 196 461 107939 104 0 0 0 0 0\ncpu6 1916 190 350 108579 48 0 0 0 0 0\ncpu7 2554 180 416 107447 435 0 0 0 0 0\nintr 947614 18 2 0 0 0 0 0 0 1 0 0 0 4 0 0 0 29 1780 0 0 0 0 0 33 0 0 0 0 0 0 14410 0 0 0 0 0 0 0 0 49761 0 0 556 81787 12 777 46585 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\nctxt 5391468\nbtime 1464034565\nprocesses 3199\nprocs_running 1\nprocs_blocked 0\nsoftirq 492410 7 122083 185 85337 49652 0 49887 101448 0 83811\n'
```

**Comment by JohnLunzer** [comment]
@scopatz , I agree with using psutil. My concern was dependencies but optionally preferring psutil would be best. I wanted to present the fall backs so the proposed solution would be complete.

Also, what setup do you have that allows those fancy wavy multi-line characters?!

**Comment by scopatz** [comment]
Absolutely, we definitely need the fallbacks :).

As for the wavy lines it is just the `$MULTILINE_PROMPT`, see http://xon.sh/envvars.html#multiline-prompt, set to ```'`·.,¸,.·*¯`·.,¸,.·*¯'```. This is used in the example xonshrc file http://xon.sh/xonshrc.html :)

**Comment by scopatz** [comment]
I have been meaning to colorize it even :)

**Comment by JohnLunzer** [comment]
Can it be colorized in the same way as the command prompt?

**Comment by scopatz** [comment]
Yep, pretty much anything can be colorized using the same rules as the prompt.

**Comment by JohnLunzer** [comment]
I realize this is off topic but I tried to colorize the multiline prompt like I do with my regular prompt, for example `{BLUE}>>>>>` but it is not parsing the color tag.

**Comment by scopatz** [comment]
You are right @JohnLunzer - That seems to be a bug.

**Comment by scopatz** [comment]
And I see why.... it is annoying to do right :)

**Comment by scopatz** [comment]
Ok @JohnLunzer - @1020 implements colors in the multiline prompt.  Mind taking a look?

**Comment by scopatz** [comment]
I believe that after #2125 is merged and since the addition of custom history backends, this issue will be closable.

**Comment by scopatz** [comment]
I am closing this since #2152 has been merged. If new issues arise or other backends are desirable, please open new issues. Thanks!
